### ISSUE TITLE
Cesium and meteor integration

### ISSUE THREAD

**Issue by ababakanian** [meteor/meteor#10001]
How do you get cesium to work with meteor? After installing cesium

`meteor npm install cesium`

including it in the front end:

`require('cesium\Cesium')`

doesn't work, and it's not clear what else needs to be done to integrate it with meteor

**Comment by copleykj** [comment]
It appears to me that you should be able to do a `import cesium from 'cesium'`

**Comment by ababakanian** [comment]
does that work for you? I get the following error on the front end
```
TypeError: id.charAt is not a function
    at fileResolve (modules-runtime.js?hash=9f9bb5e055614ddf4eb3e743737b7a5b3cfd9d34:511)
```
and when I do `require('cesium\Cesium')` it says it cannot find cesium in src.

**Comment by copleykj** [comment]
Sorry, I haven't actually tested this. Just postulating from the code in the index.js of the project.

**Comment by benjamn** [comment]
Module identifier strings should always use `/` separators, even on Windows, so I think that should be `require("Cesium/Cesium")` or just `require("cesium")`.

Taking a closer look at the Cesium library repository, I noticed the whole thing is written in an AMD/`require.js` style. Not just as a bundle output format, either; the source code literally calls `requirejs` and/or `define` in every module.

There was a time when this was a reasonable way to distribute code, but since then the ecosystem has moved onto either CommonJS (`require` and `exports`, by far the most common format used by npm packages) or ECMAScript module syntax (`import` and `export`, i.e. the future).

If this module format was just an implementation detail, hidden away from consuming code, the only drawback would be that the `r.js` runtime is pretty enormous:

<img width="763" alt="require js bundle visualization" src="https://user-images.githubusercontent.com/5750/41499687-33b6a72a-7152-11e8-8e7b-31a44d193a76.png">

Unfortunately, `require.js` does not hide itself in this way, and thus does not transparently work with other module systems, and I'm not sure there's much hope of that happening at this point.

Fortunately, it looks like the conversion to ECMAScript module syntax is on the roadmap for Cesium 2: https://github.com/AnalyticalGraphicsInc/cesium/issues/2524

**Comment by eportico** [comment]
I have the same error. I don't be able run Cesium with Meteor
