### ISSUE TITLE
[SOLVED] Meteor 1.7 rebuilds on story changes

### ISSUE THREAD

**Issue by sakulstra** [meteor/meteor#10064]
*Disclaimer*
I'm not sure if this is a bug or feature request as i might misunderstand the changelog.

We noticed that meteor rebuilds when we change test files which are not located below /tests.
```
- client/
-- main.js -> only imports foo.js
- imports/
-- foo.js
-- foo.spec.js
```
As I get it, this is the default behavior for meteor < 1.7, but with https://github.com/meteor/meteor/blob/devel/History.md#v17-2018-05-28
```
"meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    }
  }
```
that shouldn't be the case any more, should it? I'm happy to create a reproduction if this is not only me misunderstanding the mainModule feature.

**Comment by axelvaindal** [comment]
Not sure about this, I assume @benjamn would know more about it, but in my understanding, the building process was not impacted by the release of the `mainModule` feature.
As I understand it, it is solely in order to remove the `imports` directory and declare client/server entry point.
As long as these entry points are declared, none of the files in your application are eagerly loaded, and you have to import them, even if they are not in the `imports` directory.
Based on this description, I assume the rebuild does not take in consideration the fact that test files no longer needs to be put in a `test` directory and can be in whatever folder, considering they won't be loaded anyway.

If this was not expected, this is probably a bug because meteor should ignore test files extension when it runs in development mode and shouldn't rebuild when there is a change unless the test driver is on.
If this was expected, this is a meaningful feature request, considering I agree test file shouldn't trigger a rebuild during running unless the test driver is on.

**Comment by lmachens** [comment]
@sakulstra You did a mistake in the description.
We don't have issues with `*.spec.js` files (these test files are ignored by the file watcher correctly).
In our case we had a `foo.stories.js` for Storybook.

So the issue we have is that manipulating files in the import folder which are not imported by the mainModule are triggering a server rebuild. 
You can test it if you run Meteor and create a new file `bar.js` in the imports folder. It will trigger a rebuild.

**Comment by axelvaindal** [comment]
@benjamn will confirm this, but as it was previously the case before using the `mainModule`, I think the behavior hasn't changed.
As long as the file in your application is supposed to be in the build, it triggers a rebuild no matter if it has been imported or not.
I have seen issue about [tree-shaking and dead code elimination](https://github.com/meteor/meteor-feature-requests/issues/206) in order to reduce the build process, but I assume this can only be done after the building process has been triggered, thus this is why Meteor is permanently watching for `*.js` or `*.ts` files even if they are not imported in your app.

If you don't want Meteor to rebuild your app when you're changing these files, you can still add them to the `.meteorignore` file of your app.
Something like `*.stories.js` should prevent Meteor to trigger a rebuild each times you make a change in your Storybook related files.
Wouldn't this solve your problem ? 🙂

**Comment by sakulstra** [comment]
@axelvaindal lmachens is right, we originally faced the issue with story files - so your suggestion would probably solve my problem.

Anyhow i'm wondering why it is behaving like this. I wrongly assumed that only files imported trigger a rebuild - I though meteor just takes the starting point and ripples trough the imports.

Isn't this approach of watching everything problematic? Let's assume i try to utilize TDD and test the heck out of my newly created file - every change to the file will trigger a rebuild even if the file isn't used yet - manually ignoring it till i use it sounds not like the most developer friendly approach.
```
- client/
-- main.js // will at some point import foo.js, but not yet
- imports/
-- foo.js // frequent changes as i just start writing the code to fulfill the tests
-- foo.spec.js // contains all the test
```

Testing aside, let's imagine i have a `imports/ui/WhatEver.jsx` (not hidden behind client as we might need it for ssr) - as I get your comment now every change to `WhatEver.jsx` will trigger a server rebuild.

Can i somehow force meteor to only watch relevant files?

**Comment by axelvaindal** [comment]
@sakulstra 
Meteor doesn't watch everything located in your `imports` directory by default, only the files supposed to be built (such as `*.js` or `.ts`) files, because they probably need to be sent to client/server whenever there is a change. I understand it might be inconvenient, but it is by far the most convenient approach for developers writing large codebase everyday, considering they won't have to manually build and/or configure large settings before starting, it just works.
The reason Meteor doesn't evaluate in the background every file each time you add one, and check for `import/export` to see if it used is probably performance, particularly when you have hundreds of code files in your project. I assume it's faster to simply trigger the building process, and then check for unused code and remove it, considering you have to evaluate the file either way to know if the import is done or not. Watching all the files and checking if it is imported might be too much in terms of resources consumption compared to the annoyance of using `.meteorignore`. 
Then again, this is only my thought, I haven't looked into it much to know the real reason, @benjamn or @hwillson are by far more aware than I am about why they did it this way.

If you try to utilize TDD, you will probably be using `meteor test` in order to test your code inside `foo.js` in the `foo.spec.js` file, thus importing it. In consequence, the server will rebuild the application accordingly and rerun the test in order to display the changes, which is was we should expect. Then again, it would have rebuilt even if you hadn't imported yet, considering Meteor is watching file as I stated before.

I am not aware of a way to only watch relevant files, apart from using `.meteorignore` in order to remove the irrelevant ones from the watching system.

All this said, rebuilding shouldn't be an issue, considering it shouldn't take more than a few seconds in development. If you're changing files not imported, you won't be able to see a difference in your app yet, so you're probably not watching your UI or server logs at this point, thus making the building process transparent. The only reason you would have unused files would be for testing purposes or external tools such as Storybook, and this are use cases covered by my previous explanations.

This discussion makes me wonder if there may be a problem with the building process on your side, perhaps taking too long ? Why is the building of unused files annoying you in your daily development ? 🙂

**Comment by sakulstra** [comment]
~too long is a matter of perception :) the rebuild+startup time for us varies from 5-10s which I guess isn't that bad, but is at least perceptive a magnitude higher than at my non meteor projects(they are also smaller, so that comparison lacks).

We don't use meteor test, but vanilla jest so it might be a bit different for us, but i get your point :+1:

We definitely have some flaws in our setup(e.g. not ignoring story files) so there might be 1-2 seconds we can squeeze out - especially the server startup does some stuff in dev which is only required n production for us so there might be some space for optimization as well.

@axelvaindal thanks for all this information!
I guess the core issue here is solved: it's just not working like I thought it is, so this is no bug :D - i'm closing this for now.
