### ISSUE TITLE
No sourcemaps for js files, modules.js is showing as a source

### ISSUE THREAD

**Issue by kolyasya** [meteor/meteor#10095]
Meteor v. 1.7.0.3 (but the same problem was on previous 1.6.* versions).

So the issue is quite obvious and I can't understand what is happening.
I have no source files in Chrome Dev tools.

Here is an example with simple console.logs:

![image](https://user-images.githubusercontent.com/3371143/43091509-f0eb19c0-8eb2-11e8-874c-0bd1794f1ea3.png)

It points to `modules.js` instead of `App.jsx`

package.json

```
{
  "name": "op",
  "private": true,
  "scripts": {
    "start": "meteor --settings settings-local.json"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.44",
    "@easypost/api": "^3.0.12",
    "apollo-cache-inmemory": "^1.2.1",
    "apollo-client": "^2.3.2",
    "apollo-link": "^1.2.2",
    "apollo-link-context": "^1.0.8",
    "apollo-link-http": "^1.5.4",
    "apollo-link-ws": "^1.0.8",
    "apollo-server-express": "^1.1.7",
    "babel-runtime": "^6.23.0",
    "bcrypt": "^1.0.3",
    "body-parser": "^1.17.2",
    "bootstrap3": "^3.3.5",
    "casual": "^1.5.12",
    "cron": "^1.2.1",
    "deepmerge": "^2.1.0",
    "easypost": "^0.1.1",
    "express": "^4.15.4",
    "express-basic-auth": "^1.1.2",
    "fs": "0.0.1-security",
    "graphql": "^0.11.7",
    "graphql-server-express": "^1.1.2",
    "graphql-subscriptions": "^0.4.4",
    "graphql-tools": "^1.2.2",
    "graphql-type-json": "^0.1.4",
    "jimp": "^0.2.28",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "meteor-node-stubs": "~0.2.4",
    "milk-magento-nodejs": "git link...",
    "moment": "^2.18.1",
    "pdfmake": "^0.1.36",
    "printnode-client": "git link...",
    "raven": "^2.4.2",
    "raven-js": "^3.24.0",
    "react": "^15.4.2",
    "react-apollo": "^1.4.15",
    "react-bootstrap": "^0.31.0",
    "react-bootstrap-table": "^3.3.3",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.4",
    "react-router-dom": "4.1.1",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0",
    "screenfull": "^3.2.0",
    "soap": "^0.19.2",
    "subscriptions-transport-ws": "^0.9.9",
    "sys": "0.0.1",
    "type-detect": "^4.0.0",
    "underscore": "^1.8.3",
    "underscore.string": "^3.3.4",
    "v": "^0.3.0",
    "xmlrpc": "^1.3.2"
  },
  "devDependencies": {
    "eslint": "^3.19.0",
    "eslint-plugin-react": "^7.0.1"
  }
}
```

Meteor packages

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

# Core
meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.5.0                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library
random@1.1.0
http@1.4.1

standard-minifier-css@1.4.1   # CSS minifier run for production mode
standard-minifier-js@2.3.4    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.11.1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command

# UI
static-html
fourseven:scss

# Users
accounts-base@1.4.2
accounts-password@1.5.1
alanning:roles

# GraphQL
apollo

# Collections
matb33:collection-hooks
swydo:graphql

dynamic-import@0.4.0
webapp@1.6.0
underscore
```

**Comment by benjamn** [comment]
This is working as designed. Modules that are imported from the application's `node_modules` directory get relocated into the `modules.js` package bundle, since that bundle loads before all other packages that use the module system, and other packages (which load before application code) need to be able to import "peer dependencies" from the `node_modules` directory in the application.

In practice, there are just too many modules in `node_modules` to load them all individually, so we concatenate them into a single bundle. Combining their source maps would also be prohibitively expensive, so we don't do that. And because we don't compile `node_modules` files, they don't have "interesting" source maps (beyond just mapping back to the original file), so source maps are somewhat less useful in this case. However, the main concern is build performance.

I would recommend clicking on those `modules.js?hash=...:22381` links and examining the code around the given line. There's a header surrounded by `//////` comments for every file which tells you the original file path. It's a very low-tech substitute for source maps, but it's workable.

It's a tradeoff for sure, but I genuinely believe you would not like the alternative.

**Comment by kolyasya** [comment]
@benjamn thank you for detailed answer!
I'm working with Meteor for a few years now and all of my projects except mentioned in the issue are working correct in this case.

I would like to specify the issue description a little bit.

The problem is not with files from `node_modules`. If I call `console.log()` in my own files, such as `/imports/ui/App.jsx` I still see them as `modules.js`.

Here is an example from another app written with Meteor 1.6.1.1

![image](https://user-images.githubusercontent.com/3371143/43214762-e0edfd12-9042-11e8-8827-33c3d64fc516.png)
