### ISSUE TITLE
Meteor fails to import @material/ripple (fails to import dependencys)

### ISSUE THREAD

**Issue by marvinside** [meteor/meteor#10146]
- Meteor Version: Meteor 1.7.0.4
- OS: Ubuntu 18.04.1 on 4.15.0-30-generic

Only changes:

1. ```meteor npm i @material/ripple```
2. Place ```import { MDCRipple } from "@material/ripple";``` in client/main.js
3. (run meteor)

Expected Behavior:
Browser displays a Blank Page
Console shows: `Uncaught SyntaxError`: Unexpected identifier
(and a lot of following errors because modules were not loaded)

Actual Behavior: Browser has a lot of Error Messages in console, failes to display anything.

Reproduction Repo: https://github.com/marvinside/Meteor_materialImportBug

**Comment by stolinski** [comment]
You might have better luck if you post the error message.

**Comment by marvinside** [comment]
@stolinski Thanks, had the Error in the Reproduction repository.
Updated the Issue.

**Comment by benjamn** [comment]
The `@material/ripple` package is publishing ECMAScript `import` and `export` syntax directly to npm, so you'll need to make Meteor recompile the package in order to import it. See [this forum post](https://forums.meteor.com/t/litelement-import-litelement-html/45042/8?u=benjamn) for a similar situation and its solution.

I think it's useful to understand what's going on, so I recommend reading that post in full, but the following commands will make your reproduction work:
```bash
mkdir -p imports/links
cd imports/links
ln -s ../../node_modules/@material .
cd ../..
meteor run
```

**Comment by tafelito** [comment]
@benjamn I just commented on the PR #9771 about an error with linking a external library as a symlink. I was going to open a new issue but since this one seems related, I'll copy the issue here as well

I'm running an app with Meteor 1.7.0.1 and I found that when I use the symlink solution there is something not working. The app itself does build and doesn't complain about the missing modules but the source code of the module doesn't seem to be transpiled. On the other hand, when I clone the repo of the lib I'm trying to use, transpiled with babel and then linking it, it does work, but only if I link the lib from outside my meteor app. If I clone the repo inside imports/linked/... then meteor does not compile, it throws error While processing files with ecmascript (for target web.browser):

Is there anything that has to be done in order to have this working?

Thanks

**Comment by benjamn** [comment]
As a first step, have you done `meteor reset` recently, just in case this is some kind of build caching problem?

As a second step, try `meteor update --release 1.7.0.5` to get the latest version of the build tool (just released today).

If you're up for a larger update, you might try the latest Meteor 1.7.1 release candidate:
```bash
meteor update --release 1.7.1-rc.2
```
Make sure your app is under version control in case you need to roll back because this update caused problems.

If that doesn't work, a small reproduction would be helpful!

**Comment by tafelito** [comment]
I just run `meteor reset` and updated to 1.7.0.5 and symlink is still not working and neither the submodule option. 

I'm gonna try to put a sample repo so you can take a look

**Comment by tafelito** [comment]
OK I put a quick demo here 

https://github.com/tafelito/meteor-symlinks

It's using react-native-web and the external library is react-native-popup-menu

**Comment by marvinside** [comment]
Thanks @benjamn for the solution.
Importing ripple or select works now. But MDCDialog still won't work.
See the Updated Repo: https://github.com/marvinside/Meteor_materialImportBug
( Or see Diff: https://github.com/marvinside/Meteor_materialImportBug/commit/b4bddbd87a2b32f0060febe2d42401c25c8b2862 )

**Comment by filipenevola** [comment]
Hi @marvinside is this still an issue for you?

**Comment by marvinside** [comment]
Seems resolved with current Meteor version. Linking via `imports/links` is also not required anymore.
