### ISSUE TITLE
cordova build fails in 1.7.x and home page is blank

### ISSUE THREAD

**Issue by honwlt** [meteor/meteor#10142]
We upgraded meteor to latest 1.7.0.4 and our build doesn’t produce cordova project folder in the build folder

Here’s the command:
meteor build --directory …/build --architecture os.linux.x86_64 --server https://ourserver.url

It only produces build/bundle and NOT build/ios. And when we deploy the bundle folder to AWS, the  home page is blank.

But if we just downgrade the meteor to 1.6.1.3(everything else exactly same), the above build command produces both build/bundle and build/ios folders. And after AWS upload, the home page displays the content.

may be related to modern-browsers package introduced in 1.7.x?

**Comment by benjamn** [comment]
After trying several times, I have not been able to reproduce this problem locally.

Is `ios` definitely in your `.meteor/platforms` file?

Can you try running `meteor reset` first, to ensure a clean build (with nothing left over from 1.6.1.3)?

Can you try without the `--architecture` flag?

I'm guessing `.../build` (rather than `../build`) is just a typo?

Does the `../build` directory already exist when you run this command?

**Comment by honwlt** [comment]
Thanks for the pointers.
I tried all those, but no luck.

Yes, iOS is in the platforms file.
I tried with meteor reset.
Yes, .../build was a typo. My bad.

The build commands are in a script, it fails with Meteor 1.7.x.
But if just revoke to 1.6.1.3, and just run the script again, everything works great and i see ios project folder.

Is it possible it's not able to recognize --server option and hence not producing mobile build and not associating home page with the right server?

**Comment by ajmandel** [comment]
I'm new to this but I think I see the same problem.

**Comment by feraudet** [comment]
+1

**Comment by kelbongoo** [comment]
+1

**Comment by abernix** [comment]
Since we're not able to easily reproduce this, our ability to fix it is going to be dependent on a reproduction supplied by those who are encountering it.

Can any of the several users who are running into this please work on putting a reproduction together?  The [guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor) have more details on how to make a reproduction.  Unfortunately, if nobody is able to make a reproduction, we'll have to close this.

Thanks!

**Comment by honwlt** [comment]
I can confirm that upgrading to 1.8 fixes the issue.
