### ISSUE TITLE
[Meteor 1.6.1.3] Accounts.onLogin not fired if disabled cache and slow network

### ISSUE THREAD

**Issue by goodideal** [meteor/meteor#10157]
Using `accounts-base@1.4.2`.

When the network is bad and disable the cache or entering the page first time, the `Accounts.onLogin` was fired occasionally. But `Meteor.userId()` in `autorun` works perfectly.

**Comment by johnwils** [comment]
This issue can be reproduced in Chrome.
1. Open dev tools
2. Check 'Disable cache (while devtools is open)':

<img width="282" alt="screen shot 2019-03-01 at 1 29 57 pm" src="https://user-images.githubusercontent.com/13921582/53667568-2fce8c00-3c26-11e9-91d9-2977f335022d.png">

Observe `Accounts.onLogin` does not fire on page refresh (only hard login).

Uncheck the box and `Accounts.onLogin` fires every time (both on page refresh and login).

**Comment by brucejo75** [comment]
This still exists on build 1.8.1
I am seeing this bug on Cordova builds.

After `location.reload()`
* [accounts_common.js#L199](https://github.com/meteor/meteor/blob/release-1.8.1/packages/accounts-base/accounts_common.js#L199) executes as expected
* [accounts_client.js#L226](https://github.com/meteor/meteor/blob/release-1.8.1/packages/accounts-base/accounts_client.js#L226) fails to execute.

This just started happening, so I suspect it is a timing bug that gets exacerbated by disabling the cache.

**Comment by brucejo75** [comment]
@benjamn ,

I made some progress tracking this down.

Essentially, the `livedata` connection is up and running before the `Accounts.onLogin` callbacks can get registered.  When using cache this **kinda** goes away (the first `location.reload` will display the issue until cached, which I suppose I have always assumed was a glitch 😸 ).

I am assuming that the timing of this code running is likely pretty tricky.  So I propose to add another internal method to `Accounts`: ` _startupCallback(callbackId)`.

This function will check that the user is already logged in, if true then go ahead and schedule the execution of the callback with `{type: "resume"}`, because this can only really be called if a resume happens before the `onLogin` is called.

I have it all tested out in my config and it works well.

I will have PR up in a jiffy.
