### ISSUE TITLE
Crash on startup (always) with latest Meteor and babel-runtime 7.0.0+ (not beta)

### ISSUE THREAD

**Issue by ephemer** [meteor/meteor#10187]
Running on Mac, but this error is expected everywhere because it's a javascript bug in `babel-runtime`. I'm on Meteor 1.7.0.5 but I'm assuming there are a bunch of other versions affected too.

Reproduction:

```bash
meteor create bug
cd bug
meteor npm update @babel/runtime # updates to 7.0.0
meteor
```

Result:

```
.meteor/local/build/programs/server/boot.js:475
}).run();
   ^
TypeError: Cannot read property '1' of null
    at babel-runtime.js (packages/babel-runtime.js:51:13)
    at fileEvaluate (packages/modules-runtime.js:322:7)
    at Module.require (packages/modules-runtime.js:224:14)
    at require (packages/modules-runtime.js:244:21)
    at packages/babel-runtime.js:101:15
    at packages/babel-runtime.js:108:3
    at .meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at .meteor/local/build/programs/server/boot.js:220:19
    at .meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
```

The issue is due to the following code at `packages/babel-runtime.js:51:13`, which has a bug:

```javascript
var match = /^7\.0\.0-(beta|rc)\./.exec(babelRuntimeVersion);
  if (match &&
      match[1] === "rc" ||
      (match[1] === "beta" &&
       parseInt(babelRuntimeVersion.split(".").pop(), 10) > 55)) {
```

Instead it should read:

```javascript
var match = /^7\.0\.0-(beta|rc)\./.exec(babelRuntimeVersion);
  if (match &&
      (
        (match[1] === "rc") ||
        (match[1] === "beta" && parseInt(babelRuntimeVersion.split(".").pop(), 10) > 55)
      )
  ) {

// (might be better to write this as a condition that breaks early if 'match' is null..)
```

I haven't used Meteor regularly for a couple of years now and I don't have the internal structure clear in my head anymore, otherwise I'd make a pull request.

This is an extremely annoying bug though, would be great to see it fixed ASAP.

**Comment by paulincai** [comment]
As far as I know the last supported version is "@babel/runtime": "^7.0.0-beta.55".  Please read [here](https://github.com/meteor/meteor/blob/devel/History.md) for version 1.7.0.4.
If this answers your query, would be nice to close the matter as I see the number of opened matters has gone from 60 to 190 in just 2-3 month ...

**Comment by abernix** [comment]
You're right that there was an error at play here in the message - fixed with https://github.com/meteor/meteor/commit/1e34acadc06572557e7e781c0738758d017d2cf2!

But keep in mind, there's a good reason that the default Meteor 1.7.0.5 application pins its `@babel/runtime` to exactly `7.0.0-beta.55`, as the (intended) message (would have) highlighted!  This began on the 1.7.0.x release series as mentioned in this comment on 1.7.0.4's #10134 (as @paulincai helpfully linked to above):

> Make sure new Meteor 1.7.0.4 apps install @babel/runtime@7.0.0-beta.55 and nothing later.

By updating beyond, you'd be breaking that limitation that was put in place.  (Btw, Meteor generally warns, via the message you showed above, when its time to update `@babel`)

Due to breaking changes that came out in `@babel/*-7.0.0-beta.56`, you'll need to either update to the Meteor 1.7.1 release candidate (See #9942 for instructions), or pin to exactly `@babel/runtime@7.0.0-beta.55`.

Thankfully, 1.7.1 (`1.7.1-rc.5` being the latest when I wrote this message) works properly when updating `@babel/runtime` to the latest, official 7.x release.  Thanks for raising this!

**Comment by abernix** [comment]
Oh, and existing, pre-1.7.1 applications who are suffering from this should be able to `meteor update babel-runtime` — though that'll only implement the helpful error message, not `@babel/runtime@7.0.0` support, which will still necessitate updating to 1.7.1 (release candidates).

**Comment by ephemer** [comment]
Ok thanks for the updates! Is there any plan to allow removing Babel entirely? I’d be very happy not to have it our stack whatsoever
