### ISSUE TITLE
[1.7.1-rc.7] "The Mongo server and the Meteor query disagree on how many documents match your query" when query contains undefined value

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#10205]
This has been observed (and fixed): https://github.com/meteor/meteor/issues/9619

but it seems to reappear.

We had this query running in a publication:

```
const userId = Meteor.userId()
const campaignId = "testcampagin" // was a function arg in our publication
const { companyId } = Users.findOne(userId) || {}; // companyId was undefined in this case

const query = {
    campaignId,
    companyId, // this was undefined
    members: {
      userId,
    },
  };

return Teams.find(query);
```

and it throwed "The Mongo server and the Meteor query disagree on how many documents match your query""

we are using https://github.com/cult-of-coders/redis-oplog, collectionhooks and aldeed:collection2, maybe one of them messes with https://github.com/meteor/meteor/pull/9671?

**Comment by benjamn** [comment]
Note that #9671 was reverted before it was ever published, so we're not actually stripping undefined fields, so the client and server can still disagree because the server uses the `ignoreUndefined` option. Ideally, I think we should throw if undefined values are encountered in a query, per my comment https://github.com/meteor/meteor/pull/9671#issuecomment-369462985.

**Comment by actionnick** [comment]
I get this when running a query without any undefined values, 
```
{"options.edits":{"$elemMatch":{"deliveredAt":{"$gte":{"$date":1533706200000}},"editedBy":"email@website.com"}}}
```

**Comment by sebakerckhof** [comment]
@actionnick I've been working on some minimongo fixes recently. If you could create a small reproduction repository of that I might be able to take a look into it.
