### ISSUE TITLE
Old version of babel-compiler package

### ISSUE THREAD

**Issue by mariusrak** [meteor/meteor#10207]
https://github.com/meteor/meteor/blob/de6717da66c1bcdccfcaa01b5d16de1fdb383c7f/packages/babel-compiler/package.js#L13

Hello @benjamn, why do you use old version of babel-compiler, when release 7.0.0 is available?

**Comment by benjamn** [comment]
That's the `devel` branch. The new version is coming in Meteor 1.7.1:
https://github.com/meteor/meteor/blob/release-1.7.1/packages/babel-compiler/package.js#L13
There have been some major breaking changes in the Babel packages (especially `@babel/runtime`) since beta 53, so it would not be appropriate to release `meteor-babel@7.0.0` for Meteor 1.7.0.x apps.

**Comment by mariusrak** [comment]
Yeah, but this is meteor version 1.7.1, right?

**Comment by mariusrak** [comment]
Okay, thank You, Now I understand more the flow :)
