### ISSUE TITLE
Multiple concurrent deploys to Galaxy puts deploy steps in a loop

### ISSUE THREAD

**Issue by neelmehta247** [meteor/meteor#10237]
We started noticing this issue in Meteor v1.7 when the `meteor deploy` step started waiting for the Galaxy deploy to propagate and finish before ending the step. 

The problem occurs when we have two builds that are going through at the same time (due to our CD solution). Galaxy recognizes that we're trying to deploy two versions at the same time and cancels the older version, which is great. However, Meteor CLI sees this as a failure (and not as an "Abort") and then proceeds to retry the whole build process, deploying again. This in turn interferes with the newer build that cancelled this one in the first place and then that gets cancelled and Meteor retries that and this keeps going.

This hurts our workflow as we now have to make sure we have enough time between two deploys such that this doesn't happen or monitor the Meteor output and manually cancel the builds if we see that the build was being retried due to an aborted deploy.

Both of these are suboptimal and the ideal solution would be where Meteor recognizes that the deploy was aborted and accordingly doesn't retry and stops gracefully. We love that the CLI waits for the deploys as we now know if a deploy was actually successful or not.

This is the output that shows up which indicated the issue to us
```
Building app image...

Deploying app...

******************************************************************************
ERROR: Failed to deploy new app version: 2376.
Galaxy failed to deploy your app. The final deploy status was: Deploy Aborted.
Your app is currently deployed; the active version is 2375.
See https://galaxy.meteor.com/app/<website>/logs for details.
******************************************************************************

Deploying <branch> failed. Retrying now.
```

**Comment by abernix** [comment]
There might be a bug here (particularly in regard to the retrying), but in the short term (and out of curiosity) if you use the `--no-wait` flag to `meteor deploy` does this help?

**Comment by neelmehta247** [comment]
Yes, it does but that's only because the CLI doesn't wait for the deploy anymore. In this case it is the same as it was before we moved to 1.7.

We actually like this feature though, so if it could gracefully quit that would be a lot better.

**Comment by neelmehta247** [comment]
@benjamn @abernix I can help with a PR, but what would you want the desired behavior to be?

**Comment by jamesmillerburgess** [comment]
Would just like to say that we have a similar issue. We have continuous deployment set up on CircleCI, but we don't get into an infinite loop. Instead if there are two concurrent deployments, CircleCI eventually kills both of them due to an extended period of time without console output, so neither one gets deployed.

It's not the end of the world having this issue, but it would be a quality of life improvement to detect this case automatically and perhaps cancel the older version's deployment while proceeding with the newer version. Although 'newer' and 'older' might not be strictly what we expect in terms of commit recency, since the deployments would be in a race.
