### ISSUE TITLE
Many npm packages only working on client and not on server

### ISSUE THREAD

**Issue by nanu-c** [meteor/meteor#10245]
This uses 
meteor@1.9.2 on ubuntu 18.04

**Expected behaviour:** all npm packages can be used in client and server

 **actual behaviour:** npm modules can only used in the client

 A **simple** reproduction!
First:
`meteor npm install --save merge-images`

then 
```
import mergeImages from 'merge-images'
Template.vpRender.events({
  "click button": function(e,t){
    console.log(mergeImages);
    Meteor.call("merge");
  }
});
```
the console shows this:
`function mergeImages()`

On server 

```
import mergeImages from 'merge-images'
Meteor.methods({
  merge() {
     console.log(mergeImages);
  }
})
```
then the server console:
`{}`

solution:
instead of 
`meteor npm install --save merge-images`
use
`npm install --save merge-images`
and restart server manually
`I20181002-21:02:18.695(2)? [Function: mergeImages]`

What is the right way to do it, or did I broke something?

**Comment by nanu-c** [comment]
ups 
meteror --version is Meteor 1.7.0.5

.meteor/versions tells about Meteor 1.9.2

**Comment by benjamn** [comment]
You do have to restart the server manually sometimes to pick up new packages installed in `node_modules`. Do that, and you will have no trouble using `merge-images` on the server.

Watching the contents of `node_modules` for changes is an invitation to performance problems, since `node_modules` often contains such an enormous number of files and directories.

There is no difference between `meteor npm ...` and `npm ...` in this case.
