### ISSUE TITLE
[1.8] Insanely long initial build time in a big CoffeeScript project

### ISSUE THREAD

**Issue by MatejJan** [meteor/meteor#10298]
I run an [open source project](https://github.com/Retronator/Pixel-Art-Academy) with over 1,000 CoffeeScript files and ran into an issue on Meteor 1.6 where adding too many files crashed the compiler with maximum call stack size exceeded, involving the caching compiler similar to #10028. 

The discussion there led me to upgrade to 1.8 and CoffeeScript 2. After doing the necessary syntax changes, when I try to build the project now from the ground up (after meteor reset), the build runs out of memory after many many minutes of waiting.

I tried to increase the heap space to 4 GB (`TOOL_NODE_FLAGS="--max-old-space-size=4096"`), but the build still failed:

```
=> Started proxy.                             
   Building for web.browser                  -
<--- Last few GCs --->

[44085:0x103000a00]   582829 ms: Mark-sweep 4027.5 (4140.9) -> 4027.5 (4140.4) MB, 288.3 / 0.0 ms  allocation failure GC in old space requested
[44085:0x103000a00]   583126 ms: Mark-sweep 4027.5 (4140.4) -> 4027.5 (4138.9) MB, 297.7 / 0.1 ms  last resort GC in old space requested
[44085:0x103000a00]   583424 ms: Mark-sweep 4027.5 (4138.9) -> 4027.5 (4138.9) MB, 297.6 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1d7058d25879 <JSObject>
    1: split(this=0x1d707c94d4f9 <Very long string[981760]>)
    2: /* anonymous */(aka /* anonymous */) [/Users/Retro/.meteor/packages/coffeescript/.2.3.1_2.e4x3ip.tz2aw++os+web.browser+web.browser.legacy+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/template/lib/builder.js:~24] [pc=0x2d659ebbb38e](this=0x1d70c2d022d1 <undefined>,/* anonym...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Note especially the line `split(this=0x1d707c94d4f9 <Very long string[981760]>`. That is one very long string indeed, and looking at other similar issues where people profiled the build I'm guessing this has something to do with the babel compiler?

After increasing the heap space to 8 GB, it actually finished compiling for `web.browser` platform and made it all the way to `web.browser.legacy` (in about 30 minutes), but still crashed eventually, this time with error:

```
=> Started proxy.                             
   Building for web.browser.legacy           \
<--- Last few GCs --->

[44148:0x102803200]  2491848 ms: Mark-sweep 8081.6 (8283.2) -> 8081.5 (8283.7) MB, 766.7 / 0.0 ms  allocation failure GC in old space requested
[44148:0x102803200]  2492635 ms: Mark-sweep 8081.5 (8283.7) -> 8081.5 (8279.2) MB, 786.6 / 0.1 ms  last resort GC in old space requested
[44148:0x102803200]  2493217 ms: Mark-sweep 8081.5 (8279.2) -> 8081.5 (8279.2) MB, 581.3 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3e66a525879 <JSObject>
    1: DoJoin(aka DoJoin) [native array.js:~94] [pc=0x5feed348734](this=0x3e60bb022d1 <undefined>,o=0x3e601e71179 <JSArray[3978]>,p=3978,D=0x3e60bb02371 <true>,z=0x3e60bb02431 <String[0]: >,y=0x3e60bb023e1 <false>)
    2: Join(aka Join) [native array.js:~119] [pc=0x5feebbf8c5e](this=0x3e60bb022d1 <undefined>,o=0x3e601e71179 <JSArray[3978]>,p=3978,z=0x3e60bb02431 <String[0]: >,y=0x3e60bb023e1 <fal...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

My project is made out of close to 50 packages. Removing them all and building by adding a few at a time mitigates this issue due to incremental compiling (although even adding a few packages at a time can take 5–10 minutes for an initial build). 

This is hardly a workaround since after every meteor reset, you have to resort back to manually adding packages one by one and even in this way it takes more than an hour to get a build going. (After that recompiles run very fast, so kudos on that.)

I don't have a repository to share yet as I haven't committed the conversion yet (I have a third of packages left to update to CoffeeScript 2), but will reply when the reproduction is available in its branch. It'll hopefully be of service to you to help iron out build performance issues in 1.8.

**Comment by MatejJan** [comment]
My codebase that should build on Meteor 1.8 is now available in the [meteor-update](https://github.com/Retronator/Pixel-Art-Academy/tree/meteor-update) branch of my repository. 

I was able to build it by commenting all the non-system packages inside `.meteor/packages` and then adding them one by one (or a couple at a time).

Compare this with the master branch that is on 1.6 and builds in about 10 minutes on first run.

**Comment by KoenLav** [comment]
@MatejJan there is definitely something wrong with the build proces in 1.8, thanks for providing so much detail and a reproduction!

I hope the Meteor devs will be able to figure this out sooner rather than later.

**Comment by benjamn** [comment]
Ok, if you run `meteor update coffeescript coffeescript-compiler` to get the latest version (2.3.2_1), build times should be substantially improved.

On my machine, a full build after `meteor reset` now takes about five minutes (and more importantly it doesn't crash). Stopping the server and restarting it with `METEOR_PROFILE=20 meteor` takes ~25 seconds to build and ~20 seconds to start the server (you've got a lot of startup logic). Rebuild times (without stopping the server) are generally shorter than that, though they vary widely, depending on how many packages depend on the code that changed.

If you want to do something about the fixed cost of restarting the server, I would have a look at the [`Meteor.startup` call](https://github.com/peerlibrary/meteor-peerdb/blob/4ae6483030465c2080a81a2766fb19c11f6a2fa5/lib.coffee#L1507) in `packages/peerlibrary_peerdb/lib.coffee`, since that's taking the vast majority of the startup time.

**Comment by MatejJan** [comment]
Thank you so much for this very swift fix. I can confirm it works (same 5 min initial build time on my machine as well). Awesome!

**Comment by FlyingTigra** [comment]
> meteor update coffeescript coffeescript-compiler
@benjamn , I believe I have similar issue... but above mentioned command does not allow me to bump version...

> Newer versions of the following indirect dependencies are available:
>  * coffeescript 1.0.17 (2.3.2_1 is available) 

And then...

> $meteor update coffeescript
> The specified packages are at their latest compatible versions.

**Comment by benjamn** [comment]
@FlyingTigra If you're using Meteor 1.8, there's a new feature that allows you to override conflicting versions in your `.meteor/packages` file. From [`History.md`](https://github.com/meteor/meteor/blob/devel/History.md#v18-2018-10-08):

* The `.meteor/packages` file supports a new syntax for overriding
  problematic version constraints from packages you do not control.

  If a package version constraint in `.meteor/packages` ends with a `!`
  character, any other (non-`!`) constraints on that package elsewhere in
  the application will be _weakened_ to allow any version greater than or
  equal to the constraint, even if the major/minor versions do not match.

  For example, using both CoffeeScript 2 and `practicalmeteor:mocha` used
  to be impossible (or at least very difficult) because of this
  [`api.versionsFrom("1.3")`](https://github.com/practicalmeteor/meteor-mocha/blob/3a2658070a920f8846df48bb8d8c7b678b8c6870/package.js#L28)
  statement, which unfortunately constrained the `coffeescript` package to
  version 1.x. In Meteor 1.8, if you want to update `coffeescript` to
  2.x, you can relax the `practicalmeteor:mocha` constraint by putting
  ```
  coffeescript@2.2.1_1! # note the !
  ```
  in your `.meteor/packages` file. The `coffeescript` version still needs
  to be at least 1.x, so that `practicalmeteor:mocha` can count on that
  minimum. However, `practicalmeteor:mocha` will no longer constrain the
  major version of `coffeescript`, so `coffeescript@2.2.1_1` will work.

I realize this may be all kinds of confusing, so please feel free to ask additional questions.

**Comment by FlyingTigra** [comment]
Thank you, @benjamn , that was pretty clear.
We're on 1.8.0.2 and after we updated project we having issues building it: process exiting with error 137 and I thought that could be because of few packages that are not updated to latest versions, those include coffeescript. But those are referenced indirectly, so, we cannot just bump them via 'packages 'hack' that you proposed, I guess...
