### ISSUE TITLE
Downstream partially blocked when unresolved Promise (no call callback, no subscribe, no reload)

### ISSUE THREAD

**Issue by bvanderdrift** [meteor/meteor#10352]
After some code changes we notice that one of our user Journeys was blocked. Digging deeper we noticed a callback of `Meteor.call` was never called. After that block happened we also couldn't resubscribe, the application wouldn't reload on edits, and the actuall Meteor Method was re-run on the server every time the server restarted (as in the whole call, so you saw the whole log re-appear the amount of times the call was pressed).

Eventually we figured out we had made a `Promise` that would not resolve by accident:

```javascript
return new Promise((resolve, reject) => {
    SomeCollection.insert(someDocument);
});
```

This blocked the downstream connection for us. Since this failed silently we spent multiple days debugging this issue. A simple timeout would have saved us a lot of time. This issue hopes to address the silent failing of the `Promise` by putting an upper limit. (I am not sure if you can call it a fail, since this is a halting problem).

* Version: at least 1.7.0.2 upwards
* OS: Ubuntu 18.04, 16.04 OSX Sierra 10

## Expected Behaviour
When running a promise that never resolves timing out.

## Actual Behaviour

* Original call with the unresolved `Promise` would execute on the server. 
* All publications that are open at that moment would also update. 
* The original call and any consecutive calls would not have their callback called. 
* Any new publication would never be `ready()`. 
* Our application wouldn't update client side anymore on a code-change. 
* On every restart of the server the congested call would re-run.

## Reproduction Repository
https://github.com/bvanderdrift/meteor_blocked_downstream_issue (See README)

**Comment by macrozone** [comment]
I think, i ran into a similar problem, altough there was no code change at all (non that i am aware of).

The symptoms where the same:

- publications would send out old data altough the client was refreshed. Even logout and login would not solve. This had the weird effect, that users would see different data on different browsers (!)
- Meteor.logout is blocked, any given callback is not called. you would have to clear localStorage and reload the page to logout
- Methods would not call its callback, altough i see in the websocket connection (and with the older meteor chrome dev tools) that i receive a result from the method call

I could temporarily solve it by restarting all servers, so that open connections would flush, but i could not find the real issue.  I don't think we have async methods in this project (nor any promise).


Meteor 1.8.1
