### ISSUE TITLE
[1.7-1.8] Production build errors with dynamic modules import

### ISSUE THREAD

**Issue by nabiltntn** [meteor/meteor#10393]
I am still having problems building my application with 1.7 and 1.8 for production ( Dev is OK ). I am using dynamic modules imports from methods to call functions defined in server code.

Errors happen in minify step, I tried to add debug messages to minifier-js package at this level 
https://github.com/meteor/meteor/blob/0fcc7ddd46d0ef8a278376ba64538210486ab646/packages/minifier-js/minifier.js#L25-L31

The error message is : `SyntaxError: Import statement may only appear at top level`. It occurs with code that look like this :
```js
function __minifyJs(){
// My application imports
import { a } from 'a';
import { b } from 'b';
// ...etc
}
```
It looks like dynamic modules are wrapped during build inside a function with special name `__minifyJs` which explains the error. Looking for its origin , i found this

https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/tools/isobuild/bundler.js#L1295-L1315

Does that comment is still relevant with terser being used to minify ?

Why the module code is not transpiled to es5 before wrapping it inside that function ?

**Comment by benjamn** [comment]
It doesn't make sense that there would still be `import` syntax in the code that's being minified. Are you using something other than the official `ecmascript` package?

**Comment by nabiltntn** [comment]
Yes , i am using the official `ecmascript` package with version `0.12.3` with `standard-minifier-js@2.4.0` and `@babel/runtime": "^7.2.0`.

I am defining methods ( with validated-method) and server code inside a local package *myapp-api* under packages folder.

These methods are imported and called from another 2 local UI packages *myapp-client-web* and *myapp-client-mobile* which are loaded with :
 
**Web**
```
api.mainModule('client/index.js', 'web.browser', { lazy: true });
```
**Cordova**
```
api.mainModule('client/index.js', 'web.cordova', { lazy: true });
```

**Comment by benjamn** [comment]
Does your `myapp-api` package also have `api.use("ecmascript")` in the `Package.onUse` section of its `package.js` file? Just want to be sure.

By the way, I do agree it's worth checking whether `terser` can handle parsing a single anonymous function, since that would be a nice simplification here. Also happy to consider other approaches to that problem, such as wrapping all the function expressions in an array so we can minify them at once, then parsing them back out.

**Comment by nabiltntn** [comment]
Yes, `ecmascript` is declared with `api.use(["ecmascript"])` in myapp-api package.

**Comment by nabiltntn** [comment]
I created a repo with the same structure to reproduce the bug : 
https://github.com/nabiltntn/reproduction-1-8-build-error

The application has 3 packages : `myapp-api` ,  `myapp-client-web` and myapp-client-mobile`

Method from myapp-api is called from main app and myapp-client-web package

**Comment by CaptainN** [comment]
I've been tracking an issue that may be related to this, though I haven't had time to make a reduction. I have a very simple wrapper for `dompurify` to make that npm package compatible with SSR:

package.js
```js
/* global Package */
Package.describe({
  name: 'pixstori:dompurify',
  summary: 'A simple wrapper to enable dompurify use on client and server in Meteor',
  description: 'A simple wrapper to enable dompurify on the server using jsdom.',
  version: '1.0.10'
})

Package.onUse(function (api) {
  api.versionsFrom('METEOR@1.5')
  api.use('ecmascript')
  api.mainModule('client.js', 'client', { lazy: true })
  api.mainModule('server.js', 'server', { lazy: true })
})
```

client.js
```js
export dompurify from 'dompurify'
```

server.js
```js
import { Meteor } from 'meteor/meteor'
import dompurify from 'dompurify'
import { JSDOM } from 'jsdom'
const { window } = new JSDOM('<!DOCTYPE html>')
export const DOMPurify = dompurify(window)
```

The problem is that when `appcache` and `dynamic-imports` are enabled, when it goes to preload the modules, it throws an error trying to load `client.js`. It still works at runtime, it just fails to preload with this message:

```
Uncaught (in promise) Error: Cannot find module '/node_modules/meteor/pixstori_dompurify/client.js'
```

I don't know if it's related, but it seemed it might be. Hopefully I'll have some time in the next few weeks to dig in and see what's up.
