### ISSUE TITLE
TypeError: Accounts.setPassword is not a function

### ISSUE THREAD

**Issue by Gobliins** [meteor/meteor#10425]
I am using: 
Meteor Version 1.8, 
accounts-password@1.5.1

When invoking:
```
  Meteor.methods({
    setPassword(newPassword, userId) {
      check(userId, String);
      check(newPassword, String);
      if(Meteor.user().isAdmin){
        Accounts.setPassword(userId, newPassword);
      }
    },
  });
```

by

```
Meteor.call('setPassword', password, this.userId);
```

i get this error:
```Exception while simulating the effect of invoking 'setPassword' TypeError: Accounts.setPassword is not a function``` 
but the password is still set...

**Comment by Gobliins** [comment]
Hi,
The method is on the server and exported to client by Meteor methods (see updated code). And so i call it from client. Strange i get problems by using this approach...
So how could i change the pw (or call the Accounts.setPassword function) of a user from client?

**Comment by axelvaindal** [comment]
Even if you're wrapping `setPassword` inside a Meteor methods available both on client and server, it doesn't change the fact that the `Accounts` package only make `setPassword` available on a server environment (for obvious security reasons).
What you did with the methods is a good approach to call it from the client, but you should prevent the function to be called directly from the client simulation by doing something like this: 

```
Meteor.methods({
    setPassword(newPassword, userId) {
      check(userId, String);
      check(newPassword, String);
      if(Meteor.user().isAdmin){
          if (!this.isSimulation) {
            Accounts.setPassword(userId, newPassword);
          }
      }
    },
  });
```

This way, the client won't try to call `setPassword` when simulating your method call for optimistic ui.
Everything is explained in the Meteor [Guide](https://guide.meteor.com/), I suggest you to read it carefully to understand better these concepts before going further in your development.
Last thing about your code, be very careful about passing `userId` to such a sensitive part of code. Changing password should only be available for the own logged in user, and thus your code should be rewritten as this: 


```
Meteor.methods({
    setPassword(newPassword) {
      check(newPassword, String);

      if (!Meteor.user().isAdmin() || this.isSimulation) {
          // Perhaps log, throw an error or anything you found suitable instead of just doing nothing
          return;
      }
      Accounts.setPassword(this.userId, newPassword);
    },
  });
```
This way, you can prevent a malicious user to send a specific userId in order to change the password of a designated user and steal his account. Security issues related to user ids have a dedicated section in the guide [here](https://guide.meteor.com/security.html#user-id-client).

As explained before, this issue tracker is not here to give solutions to each developer issue, in particular when such solutions can easily be found in the [docs](https://docs.meteor.com/), the [guide](https://guide.meteor.com/), the [tutorials](https://www.meteor.com/tutorials) or many other source of information available online.

I hope my answer is clear enough for you to debug your code and keep going on. If you're still experiencing issues, please ask direclty on the [forum](https://forums.meteor.com/) so we can avoid spamming MDG users with notifications/emails.

**Comment by Gobliins** [comment]
Issue is solved by wrapping it with if(Meteor.isServer)
