### ISSUE TITLE
RangeError: Out of memory

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#10430]
I am getting the error after some time, I mean it appears onces in a week or 4 days:

I am using Ubuntu 16.4
```

W20190123-10:00:24.534(1)? (STDERR) /home/myuser/.meteor/packages/meteor-tool/.1.8.0_2.11dn4zp++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190123-10:00:24.535(1)? (STDERR)                                             throw(ex);
W20190123-10:00:24.535(1)? (STDERR)                                             ^
W20190123-10:00:24.539(1)? (STDERR) 
W20190123-10:00:24.539(1)? (STDERR) RangeError: Out of memory
W20190123-10:00:24.539(1)? (STDERR)     at processNext (packages/ddp-server/livedata_server.js:563:10)
W20190123-10:00:24.540(1)? (STDERR)     at unblock (packages/ddp-server/livedata_server.js:550:11)
W20190123-10:00:24.540(1)? (STDERR)     at packages/ddp-server/livedata_server.js:562:9
=> Exited with code: 1
=> Meteor server restarted
```

**Comment by lamhieu-vk** [comment]
are you sure that the methods you call are not recursive?

**Comment by MartiniHenry1988** [comment]
@lamhieu-vk Yes I double checked the code, its not recursive. Or is there any other way to find out any recursion on server?

**Comment by MartiniHenry1988** [comment]
Alright i will check all the methods with this.unblock. but I assume there is some subscription that is consuming memory. Because few days back my server was down and when i checked memoy usage, monodb was taking 100% of ram and cpu

**Comment by lamhieu-vk** [comment]
@MartiniHenry1988 you can use [meteor-apm-agent](https://github.com/meteor/meteor-apm-agent) to easier debug and tracking for your Meteor app.

**Comment by MartiniHenry1988** [comment]
@lamhieu-vk I tried monti-apm. For some reason my server goes down when i setup monti-apm on live server. On my local server it works fine and i don't get any issues on my local and staging servers. It only live server that keeps going down. I also have an ongoing thread about server going down:

https://github.com/meteor/meteor/issues/10424

**Comment by lamhieu-vk** [comment]
@MartiniHenry1988 
in case your server crashes, there are many causes from both objective and subjective factors so it is really difficult for me to help you!
the following are the most likely cases:
- you use many `subscriptions` or cannot reuse` observe`. when you have too many `observe`, at the same time you get many `notifications oplog` from the Mongo server, your server may crash, you can reduce the number of subscriptions to the server using: [lamhieu:hypersubs](https://atmospherejs.com/lamhieu/hypersubs). it does not solve this case completely because it relates to the core of Meteor.
- methods you call are invoked, in which case you can check again.
- the clients call many times to server by methods, in which case you can limit it or remove `this.unblock` for methods not need necessary use it.

**Comment by MartiniHenry1988** [comment]
@lamhieu-vk I used subscriptions only where they were needed. E.g
I have a delivery app. So i created a subscription where i provide 5 deliveries  to a delivery guy in the radius of 10km around. For more jobs he has to scroll down and after that i provide 10 deliveries 5 old and 5 new to keep the old 4 deliveries reactive.

And besides that i used subscriptions for realtime parcel tracking and real time location of delivery guy tracking.

Is this too much for meteor to handle? Or any advice how should i handle these cases?

**Comment by lamhieu-vk** [comment]
@MartiniHenry1988 do you want handle infinite loading?

**Comment by MartiniHenry1988** [comment]
@lamhieu-vk infinite loading? Can you please explain more?

**Comment by lamhieu-vk** [comment]
@MartiniHenry1988 example here: https://infinite-scroll.com/demo/full-page/page4.html
