### ISSUE TITLE
I'm baffled by "Can't set timers inside simulations."

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10438]
Running Meteor `1.6.1.4` and Blaze `2.3.3`.

I noticed that using timers inside onCreated has the potential of breaking up a the UI with this kind of errors being thrown:

```
Exception in queued task: Error: Can't set timers inside simulations
    at withoutInvocation (http://localhost:3000/packages/meteor.js?hash=c9a34f92f28ede5a42eac467d3fa1763b624436a:517:13)
    at bindAndCatch (http://localhost:3000/packages/meteor.js?hash=c9a34f92f28ede5a42eac467d3fa1763b624436a:529:33)
    at Object.Meteor.setTimeout (http://localhost:3000/packages/meteor.js?hash=c9a34f92f28ede5a42eac467d3fa1763b624436a:544:21)
    at ViewModel.onCreated (http://localhost:3000/app/app.js?hash=85b93e1855dfdc5e82b271862a5988c379ff13e0:86488:29)
```

The code that causes the error:

```js
onCreated(instance) { // corresponds to Template.x.onCreated(function () { ...
    instance.timer = Meteor.setTimeout(() => doSomething, 500);
},

onDestroyed(instance) { // corresponds to Template.x.onDestroyed(function () { ...
    Meteor.clearTimeout(instance.timer);
}
```
I'm wondering, why? It seems to work if I move the creation of that timer into `onRendered` or just use normal `setTimeout` instead of the Meteor-variant.

From what I understood, `Meteor.setTimeout` is crucial only in server environment, right?

I haven't noticed this issue before and I've been writing Meteor code for about four years, so I hope to understand what is going on here and _why_.

**Comment by brucejo75** [comment]
Did you try setting a breakpoint within `Meteor.setTimeout`, take a look around and see what catches the error?

From reading the documents, simulations should only be run from within a method.  Is your template code being executed within a method by any chance?

Notes on my use of methods:
- I tend to practically ignore simulations, most of my method calls I only execute useful code if `!Meteor.isSimulation` otherwise it is too confusing for me to deal with.
- Simulation is where I usually test for and catch all method argument errors, that is handy as it stops the server side code from executing if an error is found there.
