### ISSUE TITLE
Poor syntax error report 

### ISSUE THREAD

**Issue by pociej** [meteor/meteor#10433]
Im not sure in which version it appeard, now im on 1.8.0.2, OS is ubuntu 18.04 LTS. 
I older versions when there was some syntax error in html it was catched on build level, so in my console i was able to see whats wrong. Now i noticed that in case of such sytax error i see everything ok in builder on client when template is loaded i see error like :

    Uncaught Error: Cannot find module './upsell.html'
    at makeMissingError (modules-runtime.js:232)
    at Module.require (modules-runtime.js:251)
    at Module.moduleLink [as link] (modules.js:344)
    at upsell.js (app.js:2784)
    at fileEvaluate (modules-runtime.js:346)
    at Module.require (modules-runtime.js:248)
    at Module.moduleLink [as link] (modules.js:344)
    at index.js (app.js:2773)
    at fileEvaluate (modules-runtime.js:346)
    at Module.require (modules-runtime.js:248)

Which gives nothing usefull and you have to go through whole html file lookig for what is wrong.

**Comment by bogdanrn** [comment]
Adding just `{{if}}` would throw an error on the terminal. But i was able to reproduce the bug by adding to one of the HTML templates the snippet below:
```
          {{if false}}
          {{/unless}}
``` 
It throws no error on terminal, but in the browser console it would show me the same error as @pociej . Interesting is that the error gets the file right. But it might be a coincidence. I remember having this issue in the past but it was just throwing errors in the browser because the routes weren't loaded properly. Once i fixed the html template, app started working as expected.

**Comment by tromgy** [comment]
I too have run into the same issure recently. I had this code (from Meteor's TODO app tutorial):
```
<button class="toggle-private">
        {{#if private}}
          Private
        {{#else}} // <= should be {{else}} !
          Public
        {{/if}}
</button>
```
which I mistyped (assuming the syntax for `else` was the same as for `if`), and there were no errors reported during the build process, only the error about missing HTML file in the browser.

Meteor version **1.8.0.2**

**Comment by ckmahoney** [comment]
I support review for this issue.

There is a layer of abstraction between the contents of the message and the reason for the message. 
It seems that Meteor found an error while parsing a Blaze .html file and therefore did not produce the template module. 

However, rather than relay the build error to the client, we are instead given a generic `cannot find module [filename].html` browser console error. The terminal shows no errors and instead happily displays  `App running at localhost:3000`.

Something as simple as forgetting to remove an old closing `</button>` tag after updating to an `<input/>` will trigger this error without pointing to the faulty syntax. Doesn't seem like a big deal, but noticing a mismatched closing tag doesn't always jump out in front of your eyes. 

While there may soon come a point when I can smell this problem before it happens, right now it is frustrating because the neither the docs nor the terminal specify reasons for errors like this. 

Is there a way to print a browser console error when a build error occurs in Blaze template files?

**Comment by pociej** [comment]
Well i think its good day to go and light candle on meteors grave. It doesn't seem to be under active development anymore and we should all leave siking ship.
