### ISSUE TITLE
TypeError for any Meteor.[function] call

### ISSUE THREAD

**Issue by sgarcia30** [meteor/meteor#10456]
Version of Meteor: 1.8.0.2.
Operating System: Mac (10.14.2)

Just trying to get the project up and running.  My boss has it working on his environment, but I've had a TON of issues.  Had to change the version of Meteor I was using.  Now I have the server up, but any commands that call for a "Meteor.[function]" give me a TypeError.

Here are the steps I took to set up my project:
1. git clone
2. git checkout -b develop
3. git pull origin develop
4. npm install --> (fails with "Error: `gyp` failed with exit code: 1")
5. rm -rf ~/.node-gyp/
6. rm -r node_modules/.bin/;
7. npm install node-pre-gyp
8. npm install bcyrpt
9. npm install
10. meteor update
11. meteor update --all-packages
12. npm run start --> (fails with a couple of these... "(node:6535) UnhandledPromiseRejectionWarning: Error: Unknown absolute import path /Users/sarahanngarcia/Desktop/FreelanceProjects/quick-draw-dev/ebacmap/node_modules/normalize.css/normalize.css")
13. meteor remove u2622:persistent-session
14. npm run start --> (server launches, but now I'm getting the TypeErrors anytime I try an functionality that calls `Meteor.[function]`... example of error below)

Exception in delivering result of invoking 'login': TypeError: Session.setAuth is not a function
    at Meteor.loginWithPassword.error (login.js:28)
    at Object.userCallback (password_client.js:69)
    at loginCallbacks (accounts_client.js:235)
    at loggedInAndDataReadyCallback (accounts_client.js:358)
    at MethodInvoker._callback (meteor.js?hash=33066830ab46d87e2b249d2780805545e40ce9ba:1223)
    at MethodInvoker._maybeInvokeCallback (MethodInvoker.js:52)
    at MethodInvoker.receiveResult (MethodInvoker.js:71)
    at Connection._livedata_result (livedata_connection.js:1508)
    at Connection.onMessage (livedata_connection.js:1667)
    at forEachCallback.callback (browser.js:186)

**Comment by coagmano** [comment]
Sorry this response doesn't have a clear answer, but I have a few questions:

From the stack trace, it looks like the error is coming from the line that calls `Session.setAuth` in your app code (Likely in the callback supplied to `Meteor.loginWithPassword`).
This is probably because you removed the session package in step 13. Why was this removed?

Which other `Meteor.[function]` calls are failing?

Often these kinds of TypeErrors are because of a faulty import statement (ie, imports undefined instead of the module). It should use a named import and look like this:
```
import { Meteor } from 'meteor/meteor';
```
Are you importing Meteor? and does it match the above line?

Either way, I can't use these reproduction steps, as I don't have access to your code. You will need to post the relevant code from your app (especially `login.js`) or create a simplified reproduction that you can share.

A few more questions and notes that might help get to the bottom of the issue:
 - Why did you have to change the version of meteor to the existing version?
 - You should use `meteor npm` to ensure the version of `node` and `npm` match exactly that which the app will use (this could be the cause of the gyp error)
 - The `gyp` error is a red flag, try it with `meteor npm install`
 - You should not need to install `node-pre-gyp`
 - Why are you updating meteor and all packages, when trying to run a known working version of the app?
 - For the absolute import path issues, if `normalize.css` is installed via npm, you can import it with: `import 'normalize.css/normalize.css';` (the name has to be twice the first is the module name, and the second is a file path. This is needed because it's not a js file so needs to be pointed to directly)

**Comment by sgarcia30** [comment]
This is the login.js file.
```
import $ from 'jquery';
import 'jquery-validation';
import { browserHistory } from 'react-router';
import { Meteor } from 'meteor/meteor';
import { Bert } from 'meteor/themeteorchef:bert';
import { getInputValue } from './get-input-value';

// import {createFixtures} from '../../server/clientfixtures';

let component;

export const login = (email, password) => {
  Bert.alert('Attempting sign in', 'info');
  Meteor.call('allowSigninByEmail', email,
    (error, res) => {

      if (error) {
        Bert.alert(error.message || error.reason, 'warning');
        return;
      }

      Meteor.loginWithPassword(email, password, (error) => {
        if (error) {
          Bert.alert(error.message, 'warning');
        } else {

          let clientId = Meteor.user().profile.clientId || '';
          Session.set('clientId', clientId);

          Meteor.call('clientfixtures.createFixtures', { clientId }, function (err, result) {
            if (error) {
              Bert.alert(error.message || error.reason, 'danger');
            } else {

              Meteor.call('stripePaymentStatus',
                (error, result) => {
                  if (error) {
                    Bert.alert('Error retreiving billing status', 'warning');
                  }
                  else {
                    Session.set('payment_status', {
                      billing_is_paid: result.isPaid,
                      billing_message: result.message
                    });
                  }
                  Bert.alert('Logged in!', 'success');
                  console.log('pushing /dashboard');
                  browserHistory.push('/dashboard');
                });
            }
          });
        }
      });
    });
}

const validate = () => {
  $(component.refs.login).validate({
    rules: {
      emailAddress: {
        required: true,
        email: true,
      },
      password: {
        required: true,
      },
    },
    messages: {
      emailAddress: {
        required: 'Need an email address here.',
        email: 'Is this email address correct?',
      },
      password: {
        required: 'Need a password here.',
      },
    },
    submitHandler() { login(); },
  });
};

export const handleLogin = (options) => {
  component = options.component;
  validate();
};
```

**Comment by sgarcia30** [comment]
I ended up changing all of the `Session.setAuth`s to `Session.set`.

I removed the session in #13, because it was one of the things I found online to get it working.  Before I did that, I couldn't even get the server to spin-up.

I upgraded it to get it to even spin-up.  I was getting lots of errors otherwise.

I may try to spin up a different version with some of your suggestions.  I'm piecemealing this together.  I work as a remote, contract developer and I'm fairly new to the industry.  I'm just trying to get it up and running so I can complete the tasks/updates my boss asked for.

**Comment by sgarcia30** [comment]
* The `gyp` error is a red flag, try it with `meteor npm install`
--> tried your suggestion, still failing with the same `gyp` error

**Comment by coagmano** [comment]
>I'm piecemealing this together. I work as a remote, contract developer and I'm fairly new to the industry. I'm just trying to get it up and running so I can complete the tasks/updates my boss asked for.

Ouch, it's never fun to get a contract for a project that won't even build.

What exactly is the gyp error? And which module is failing to build?

And can you list the other errors and I'll try and help point you in the right direction for each of them

**Comment by sgarcia30** [comment]
Here's a complete log of the gyp error.  
[2019-02-18T14_40_56_110Z-debug.log](https://github.com/meteor/meteor/files/2877686/2019-02-18T14_40_56_110Z-debug.log)

This time around when I was trying your suggestions and then even trying my solution above, I never could get past the `gyp` error.

I've been able to complete several of the tasks I've been assigned with the version I do have running.  Just not sure if the site is behaving as expected or is glitchy because of my crazy tactics for getting the server up and running.

**Comment by coagmano** [comment]
Looks like the `fibers` module.
Does the project use fibers directly?
Normally it's not included as a dependency of your application directly because it's already built into meteor, so if it's not `import`ed or `require`d anywhere, try removing it

Also, if you haven't done it already, it might be worth trying a `meteor reset`, `meteor npm cache clean`, `rm -rf ./node_modules` and a fresh `meteor npm install`
