### ISSUE TITLE
[1.8] TOOL_NODE_FLAGS="--expose-gc" does not work

### ISSUE THREAD

**Issue by s7dhansh** [meteor/meteor#10460]
Earlier `expose-gc` was allowed through NODE_OPTIONS (and probably also through TOOL_NODE_FLAGS). Now NODE_OPTIONS explicitly blocks it, and TOOL_NODE_FLAGS somehow does not pass on the flags to the node process. Can someone kindly check/help?

I initially thought it wasn't a bug and raised a question at SO, but now I am inclined to assume it to be a bug.
https://stackoverflow.com/questions/54785026/how-to-properly-use-expose-gc-in-meteor

**Comment by jankapunkt** [comment]
I just want to follow up on this post. You can simply reproduce this by starting your project with the 

```bash
TOOL_NODE_FLAGS="--expose-gc"
```
environment variable or put this into your `settings.json` but neither in `process.env` nor in `process.argv` will anything of this be present and as @s7dhansh already described is the `gc` not available either.

Interesting side-effect though, that the title of the terminal-window (on OSX) will contain the `--expose-gc` parameter of the running node app.

I tried to play around with the `meteor` starter script but no chance to have an effect on this. I think these arguments are be stripped somewhere in the startup process.

**Comment by javascriptlove** [comment]
This issue has to be reopened

**Comment by FlavienBusseuil** [comment]
This issue is not totally coupled with meteor.
`--expose-gc` is part of V8 options that are **not** allowed with NODE_OPTIONS. https://nodejs.org/api/cli.html

Executing the command `meteor node --v8-options | grep expose` also pointed that the correct option for me is `--expose_gc` with a `_` instead of `-` 🤷 

As said `TOOL_NODE_FLAGS` seems not to spread down the option to `meteor run ...`.

For my temporary needs I hacked the file:
`~/.meteor/packages/meteor-tool/.1.8.1.b0nkkp.qsthi++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js`

I added the option manually here (around line 300):
```
    opts.push(entryPoint); // Call node
	// Added option
    opts.push("--expose_gc");
```

**Comment by filipenevola** [comment]
hi @javascriptlove why do you need this option? As @FlavienBusseuil said it was not between the allowed options on V8.

**Comment by nytamin** [comment]
Setting the environment variable `SERVER_NODE_OPTIONS` to `--expose_gc` seems to do the trick for me (tested on Meteor 1.10.2)
