### ISSUE TITLE
Cordova-ios version upgrade

### ISSUE THREAD

**Issue by arbiro** [meteor/meteor#10511]
There is an issue trying to build with XCode >= 10.2 because Cordova-Ios only supports it in build 5.0 and only 4.54 is integrated in Meteor. Are there any plans to update the Cordova-IOS integration?

**Comment by rj-david** [comment]
Bummer! So the quick fix is not to use XCode 10.2 now.

Meteor 1.8.1 is in RC and it is currently supporting only cordova-ios 4.5.4. We can push cordova-ios 5.0.0 for Meteor 1.9

**Comment by arbiro** [comment]
Thanks for answering so quickly ^_^.
Is there a chance I could help with that/ contribute?

**Comment by alanning** [comment]
Related issue: https://github.com/meteor/cordova-plugin-meteor-webapp/issues/76

**Comment by davidecantini** [comment]
While appreciating much the work of the MDG, it's a bit disappointing to come up with a release candidate that is not working with Xcode 10.2. Swift 3 has been deprecated since a long time ago, and this release has been in beta for several months. 
It would be recommendable to address this issue as soon as possible in a possibly 1.8.2 release (which hopefully won't take months to be released!)

**Comment by alanning** [comment]
I like the idea of a patch release which just focuses on supporting Cordova-iOS 5.

I think this was (rightly) considered a lower priority since there was an easy workaround and not many people had Xcode 10.2.  The easy workaround still exists, just revert back to Xcode 10.1, but now that Apple is auto-upgrading everyone to Xcode 10.2 this issue becomes a lot more visible.

(Well, I should say my Xcode was auto-updated to 10.2 so I'm assuming it was the same for others.)

I submitted a PR for the Meteor Mobile guide that highlights the dependency on Xcode 10.1.  Hopefully it will help others avoid some confusion.  https://github.com/meteor/guide/pull/951

Perhaps someone could make a list of the code that needs to be updated to support Cordova-iOS 5 and then we can volunteer on which parts we want to work on?

**Comment by arbiro** [comment]
I would definitely invest some time into fixing this if provided with a direction regarding what is required to be changed.

**Comment by rj-david** [comment]
@arbiro, why close this issue?

You can fork this project and check tools > cordova > index.js

Then use the script 'meteor' from the root of this project instead of the meteor command installed in your machine.

I made a sample run today. Updated  the following:
cordova-lib: 9.0.0
cordova-common: 3.1.0
cordova-ios: 5.0.0
cordova-android: 8.0.0

I immediately faced plugin errors in my android build because of some deprecated functions in cordova. I'll test cordova-ios early next week

**Comment by macrozone** [comment]
oh dear... not again.

@arbiro can you reopen this issue? I think this should be top priority now

**Comment by arbiro** [comment]
Yes, sorry for the delay.

**Comment by macrozone** [comment]
With meteor 1.8.1 it works somewhat in xcode 10.2, but you have to switch the build tool to the legacy build tool in workspace settings, otherwise you can't upload an archive to the app store. But other than that, it seems to work

**Comment by davidecantini** [comment]
@macrozone Yes, but that was also happening in Xcode 10.1.

**Comment by buzzoids** [comment]
XCode 10.2 is needed for iOS 12.2, there needs to be an easy solution to this.

**Comment by davidecantini** [comment]
@buzzoids The solution at the moment is [this](https://github.com/meteor/meteor/issues/10516):

`meteor update --release 1.8.1-issue-10516.0`

**Comment by buzzoids** [comment]
I ran that command. It still complains about the compatibility.

Do I still have to open the project up in 10.1 so that I can convert it to swift 4.2?

**Comment by davidecantini** [comment]
After installing both Xcode 10.2 and that Meteor patch, you should see the project with Swift 4.2 already (at most you may need to clean the project (Xcode->Product->Clean) and build).

**Comment by buzzoids** [comment]
@davidecantini I have XCode 10.2 and 10.1 installed.
run Meteor --version  (outputs Meteor 1.8.1-issue-10516.0)
updated cordova-plugin-meteor-webapp@1.7.0
run meteor build ... (successful build)
open XCode 10.2 and open  .meteor/local/cordovabuild/platforms/ios workspace

It opens up without issues now. Thanks.

**Comment by frankwo1** [comment]
Hi, I cannot upload to app store - keeps giving this message No suitable application records were found. Verify your bundle identifier 'com.frank' is correct. I have triple checked (chnaged to legacy build) -- any advice?

**Comment by Nauzer** [comment]
> @buzzoids The solution at the moment is [this](https://github.com/meteor/meteor/issues/10516):
> 
> `meteor update --release 1.8.1-issue-10516.0`

@benjamn Will this be integrated in official release 1.8.2?

**Comment by scottstensland** [comment]
Why was this ticket closed ?  the problem is ongoing ... to quote an update from Cordova crew : 


Update 11/25/2019: The Cordova team has released Cordova iOS 5.1.0, which disables UIWebview at compile time. To use it, ensure you have a WKWebView plugin installed, then add to your config.xml file. Complete details below.

https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/

**However**   the latest Meteor release 1.8.3 still uses Cordova iOS 4.5.5. We can not fix the issue using above solution unless Meteor upgrades the Cordova iOS version to 5.1.0

When will meteor get upgraded to use  Cordova iOS version to 5.1.0

**Comment by rj-david** [comment]
https://github.com/meteor/meteor/pull/10810
