### ISSUE TITLE
Major performance degradation when upgrading from meteor 1.6.0.1 to meteor 1.7 or 1.8

### ISSUE THREAD

**Issue by dolle39** [meteor/meteor#10515]
I recently upgraded meteor from 1.6.0.1 to 1.8.0.2 and experienced a major 
performance degradation (around 50%) on mongo queries.

I have a nightly job that I run every night which reads alot of data from the database
and checks that it is consistent. After the upgrade I noticed that the execution time for the job
increased with almost 100%. I can see the same degradation when running in development mode aswell as when deploying the application to production.

Now, to actually verify that this degradation was not due to any external dependencies 
in my application I cloned the **Todos** test application and added a performance test to it.
see https://github.com/dolle39/meteor-performance-test-versions.

I have added the test under _imports/api/performance-test_

It consists of two functions _insertDataForPerformanceTest_ and _runPerformanceTest_.

The _insertDataForPerformanceTest_ inserts 200000 documents writes the total time for the insert operation.

The other function _runPerformanceTest_ reads all the documents in batches (in the same manner as my nightly job in my real application).

In order to run the test open meteor shell and write:

`> insertDataForPerformanceTest()`

and then

`> runPerformanceTest()`

which outputs the total execution time.

I have created 3 separate branches with different meteor versions.

**performance-test-meteor-1.6.0
performance-test-meteor-1.7.0.1
performance-test-meteor-1.8.1**

**NOTE:** When switching between the branches always run:
```
> meteor reset
> meteor npm install
> meteor npm rebuild
```
Results:
========

**insertDataForPerformanceTest() total time [s] (inserts 200000 documents):**
meteor 1.6.0: ~60  [s]
meteor 1.7.0: ~90  [s]
meteor 1.8.1: ~320 [s]

**runPerformanceTest() total time [s] (find and fetches 200000 documents in batches):**
meteor 1.6.0: ~3.5  [s]
meteor 1.7.0: ~8.8  [s]
meteor 1.8.1: ~8.7  [s]

The **insert** test almost takes more than 5 times longer for meteor 1.8.1 compared to meteor 1.6.0!

And the **find** test takes more than double the time which was exactly the same behavior as I saw in my own real application.

To me this seems to be way out of the expected range of what you would expect when upgrading to a new release of meteor. Or am I missing something fundamentally in my test?

**Comment by filipenevola** [comment]
Hello @dolle39 , what is your Mongo Server Version?

**Comment by dolle39** [comment]
@filipenevola, 

In my production environment I am running Mongo version 3.4.20.

However, the test results above is run in development mode, which means that I am running the mongo version which meteor comes bundled with.

That is:
```
meteor 1.8.1 -> mongo v4.0.6
meteor 1.7.0.1 -> mongo v3.6.4
meteor 1.6.0.1 -> mongo v3.2.15
```

Other information about my environment.

I am running on the following OS:

```LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic```

**Comment by arggh** [comment]
@dolle39 Did you notice performance degradation in just these nightly queries (handling large amounts of data) or in all queries, big or small?

**Comment by dolle39** [comment]
@arggh I can not say that I have really noticed them for small queries.

But in order to see if there is a difference between small/large queries I extended the test with a test that runs multiple `findOne` and calculates the average time per query.

Run the test:

`> runPerformanceTestWithSingleFinds()`

Results
=========

**runPerformanceTestWithSingleFinds(findOne on 200000 documents)**
meteor 1.6.0: ~0.189 [ms]/query
meteor 1.7.0: ~0.364 [ms]/query
meteor 1.8.1: ~0.285 [ms]/query

Thus, even on small queries you can see a noticeable difference.

**Comment by dolle39** [comment]
Any idea what could cause this performance degradation?

I checked the history of `mongo_driver.js` but I cannot see any extensive changes that would cause this performance degradation (see https://github.com/meteor/meteor/commits/devel/packages/mongo/mongo_driver.js). Or could it be the underlying mongodb npm package which causes this? That I see has been upgraded between the releases.

Or could it be that the node version has been upgraded?

**Comment by veered** [comment]
Can you take a CPU profile of the benchmark?

https://github.com/qualialabs/profile

**Comment by arggh** [comment]
I tried crawling through possibly relevant bug reports in MongoDB's issue tracker, but found only one:

https://jira.mongodb.org/projects/NODE/issues/NODE-1140

The issue reporter mentions having performace woes on multiple versions as of lately, and the MongoDB representative reminded they have just released `v3.2.x` which might have made an improvement on that front.

So, I decided to take the latest `v3.2.3` MongoDB driver for a test ride and ran the test app by @dolle39 with it, but sadly the new driver did not improve performance at all.

Benchmarks, as ran locally on my Macbook, looked like this:

```
Meteor 1.6.0.1: ~ 5  seconds
Meteor 1.8.1:   ~ 10 seconds
Meteor 1.8.1 (MongoDB driver 3.2.3): ~ 10 seconds

Slowdown x2
```

Running the benchmarks on Meteor `1.8.1` with the older `2.x` MongoDB driver could maybe isolate the issue into the driver, but Meteor of course breaks in many ways when trying to use the old driver with the latest release.

**Comment by arggh** [comment]
One peculiar finding: on my local tests, inserts were equally fast/slow on `1.6.01` and `1.8.1` at around 60 seconds, opposed to the 5x slowdown in tests by @dolle39 .

**Comment by bhunjadi** [comment]
I've just tested on my machine and I can confirm dolle39's results.
I was testing in Ubuntu VM (Hyper-V, Host is Win 10 x64)
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
### insertDataForPerformanceTest
```
1.6.0.1: 92.116 s
1.7.0.1: 155.106 s (x 1.68)
1.8.1: 485.597 s (x 5.27)
```

#### qualia:profile
```
Profiler.profileDuration('myprofile', path, 10000);
insertDataForPerformanceTest()
```
#### Results 1.6.
![image](https://user-images.githubusercontent.com/18718248/56080568-f2534600-5e02-11e9-8f0d-813a55f197ff.png)

#### Results 1.8.1
![image](https://user-images.githubusercontent.com/18718248/56080572-06974300-5e03-11e9-9c31-b18ccad767ce.png)

It looks like in 1.8.1 there is garbage collection taking a lot of CPU. I can't be sure what is wrong here, GC is probably triggered by more memory usage in case of 1.8.1. Could it be that GC is too eager to collect in that version of node?

### runPerformanceTest (multiple runs)
```
1.6.0.1
Performance test with 200000 entries took 4.258 [s].
Performance test with 200000 entries took 3.6 [s].
Performance test with 200000 entries took 3.409 [s].
Performance test with 200000 entries took 3.499 [s].

1.7.0.1
Performance test with 200000 entries took 13.116 [s].
Performance test with 200000 entries took 10.005 [s].
Performance test with 200000 entries took 9.915 [s].
Performance test with 200000 entries took 10.474 [s].

1.8.1
Performance test with 200000 entries took 10.694 [s].
Performance test with 200000 entries took 10.068 [s].
Performance test with 200000 entries took 10.213 [s].
Performance test with 200000 entries took 10.19 [s].
Performance test with 200000 entries took 9.985 [s].
```

#### qualia:profile
#### Results 1.6
![image](https://user-images.githubusercontent.com/18718248/56080703-a30e1500-5e04-11e9-8e75-61749c8e2791.png)

#### Results 1.8.1
![image](https://user-images.githubusercontent.com/18718248/56080706-abfee680-5e04-11e9-93b6-bd36897ddd40.png)

Big difference in idle because I ran both tests for 10 seconds and 1.6 was over in 4. 1.8.1 took some time for `Promise.asyncApply` and `_tickDomainCallback` if we look at Total Time.

**Comment by KoenLav** [comment]
Could you try with Meteor 1.9, which makes use of Node.js 11, and see if these is a difference?

**Comment by dolle39** [comment]
@KoenLav I tested with Meteor release METEOR@1.9-alpha.0 and unfortunately found no performance improvement.

Results with Meteor 1.9-alpha.0
========================

**insertDataForPerformanceTest:** 
`Inserting 200000 entries took 289.986 [s].`

**runPerformanceTest (multiple runs)**
```
Performance test with 200000 entries took 13.955 [s].
Performance test with 200000 entries took 14.59 [s].
Performance test with 200000 entries took 14.501 [s].
```

**Comment by KoenLav** [comment]
I see.

I think it's too soon to conclude that this isn't related to the Node version, but I don't expect it to be... 

Promise.asyncApply and _tickDomainCallback indeed seem to be the major difference between the two profiles. 

@benjamn are there any specific areas in the code which might be of interest here?

**Comment by KoenLav** [comment]
@dolle39 could you further narrow down the cause of the issue by running these tests on Meteor 1.6.1 and 1.6.1.1 respectively?

The changelog tells us Node.js was updated to 8.11.1 in Meteor 1.6.1.1: https://docs.meteor.com/changelog.html#v161120180402

You will probably also need to update @babel/runtime to the latest version.

**Comment by bhunjadi** [comment]
I tried 1.9 and it seems that `insertDataForPerformanceTest` performs little bit better and from CPU profile (10 sec duration) GC takes only 14%, opposed to 38% in 1.8.1 (node 8.15.1).

On the other hand, `runPerformanceTest` is worryingly **50%** slower in 1.9. 
GC in that case is down from 20% in 1.8.1 to 14% in 1.9.

[profiles-1.9.zip](https://github.com/meteor/meteor/files/3077192/profiles-1.9.zip)

**Comment by bhunjadi** [comment]
Results for Meteor 1.6.1.1 and 1.6.1.4 are the same as for 1.6.0.1.

From the 1.7 changelog: `The mongodb driver package has been updated from version 2.2.34 to version 3.0.7.`
This could be potential cause.

**Comment by gaurav-** [comment]
> Running the benchmarks on Meteor `1.8.1` with the older `2.x` MongoDB driver could maybe isolate the issue into the driver, but Meteor of course breaks in many ways when trying to use the old driver with the latest release.

Try comparing the performance by using the driver directly in node script, outside of meteor?

**Comment by KoenLav** [comment]
It's possible the use of fn.apply in executeOperation in the utils.js file of the mongodb Node.js driver is the cause of this:

https://github.com/mongodb/node-mongodb-native/blob/master/lib/utils.js

In 2.x they didn't make use of apply yet and I believe Node.js doesn't make use of apply, on purpose, in their 'nextTick' function because of some performance cost associated with it:
https://github.com/nodejs/node/blob/master/lib/internal/process/task_queues.js

Also the code within executeOperation is calling args.length on multiple occasions, this should probably be changed to assigning const argsLength = args.length at the top of the function.

Correct me if I'm wrong :)

**Comment by bhunjadi** [comment]
Just made a test with mongodb driver directly, as suggested by gaurav-. For now only for `runPerformanceTest`.
Node version: 8.15.1

In `runPerformanceTest` there are two parts:
- first is **initial fetch** of all docs to get ids 
- second is fetching documents in 10k **chunks**

I used 2.2.34 (used by npm-mongo in 1.6.1.4) and 3.1.13 (in Meteor 1.8.1).

|        | Mongo 2.2.34 | Mongo 3.1.13 |
| ---- | ---------------- | --------------- |
| Initial fetch | 0.42s | 1.10s |
| Chunks  | 2.0s | 2.1s |

So in the **initial fetch** there is significant difference and in the **chunks** test there is around 5% diff. Just note that deviations of test results are small and v2 constantly beat v3 in this test, too.

Mongodb driver 3.2.3 performs the same as 3.1.13.

**Comment by rj-david** [comment]
Found this bug related to SSL but should have been fixed for mongo driver 3.0.4 onwards: https://jira.mongodb.org/browse/NODE-1357 (posting it here if there is something related)

**Comment by gaurav-** [comment]
> It's possible the use of fn.apply in executeOperation in the utils.js file of the mongodb Node.js driver is the cause of this:
> 
> https://github.com/mongodb/node-mongodb-native/blob/master/lib/utils.js
> 
> In 2.x they didn't make use of apply yet and I believe Node.js doesn't make use of apply, on purpose, in their 'nextTick' function because of some performance cost associated with it:
> https://github.com/nodejs/node/blob/master/lib/internal/process/task_queues.js
> 
> Also the code within executeOperation is calling args.length on multiple occasions, this should probably be changed to assigning const argsLength = args.length at the top of the function.
> 
> Correct me if I'm wrong :)

@KoenLav, it seems the performance penalty you hinted at has been addressed (https://github.com/nodejs/node/commit/f4f937b296f62c11dfbd3a8f92abac81049b629e) and the fix might land in the next Node.js version.

Would it be possible for somebody to repeat the tests on the master branch of https://github.com/nodejs/node? @bhunjadi?

**Comment by bhunjadi** [comment]
@gaurav- 

Ok, so with node 13 built from master branch & mongodb 3.1.13 I got:

Initial fetch: 0.8 - 0.9s
Chunks: 1.6s

This is a noticeable improvement, but mongodb 3 is still lagging behind on initial fetch.

**Comment by gaurav-** [comment]
> @KoenLav, it seems the performance penalty you hinted at has been addressed ([nodejs/node@f4f937b](https://github.com/nodejs/node/commit/f4f937b296f62c11dfbd3a8f92abac81049b629e)) and the fix might land in the next Node.js version.

https://github.com/nodejs/node/commit/f4f937b296f62c11dfbd3a8f92abac81049b629e is part of the just released [Node 12.2.0](https://nodejs.org/en/blog/release/v12.2.0/)

**Comment by sebakerckhof** [comment]
I found there are some major peformance improvements in the npm-mongodb driver 3.3.2+ (ref. https://github.com/meteor/meteor/issues/10677 )

Could you try with meteor 1.10-beta.4 which upgrades the mongodb driver?

**Comment by bhunjadi** [comment]
Thanks for pointing this out.
I tried with node & 3.4.1 mongodb driver as soon as I noticed your solution in the other issue.
[Here](https://github.com/bhunjadi/meteor-issue-10515) is the repo with the code and results.

Also, one thing to note is that in `insertData` function we are inserting sequentially and also generating random string for fields when generating data which is not perfect.

That being said, from the results I got regarding this issue these are the conclusions:
- Node v12 improves mondodb v3 driver performance
- While fetching large amount of documents (200k in this example) v2 outperforms v3
- There is no tangible difference between 3.1.13 & 3.4.1

**Comment by filipenevola** [comment]
Hi @dolle39 did you try on Meteor 1.11? In this version we upgraded MongoDB Driver to 3.6.

**Comment by dolle39** [comment]
@filipenevola I ran the tests again with Meteor 1.11 and compared with 1.6. I still get a huge difference especially when it comes to get documents:

**insertDataForPerformanceTest()** total time [s] (inserts 200000 documents):
meteor 1.6: ~69 [s]
meteor 1.11: ~87 [s]

**runPerformanceTest()** total time [s] (find and fetches 200000 documents in batches):
meteor 1.6: ~3.5 [s]
meteor 1.11: ~15.6 [s]

**Comment by sebakerckhof** [comment]
@dolle39 Could you attach CPU profiles?

**Comment by hiteshagja** [comment]
After long time I started upgrading my old project into newer version and I realized that meteor is still there. Slow build time, takes too much run time memory. Ages to run project.

**Comment by filipenevola** [comment]
Do we have any evidence this issue in on Meteor and not in the MongoDB driver?

We are always updating Node.js and MongoDB driver and I don't see why this would be a Meteor problem.

If I'm missing something please let me know and we can reopen this issue.

**Comment by arggh** [comment]
Maybe this issue shouldn't get closed just because we don't know if it's a problem in Meteor or MongoDB?

Instead, let's verify that the problem exists with the latest and greatest Meteor & MongoDB driver, and if so, take it upstream, while keeping this issue open for tracking?

**Comment by hiteshagja** [comment]
@filipenevola I and my team designed admin panel app using core-ui react template. Without meteor, using "Create-react-app" app works really well, no flaw at all. Then I moved entire app to new meteor --react app and after that problem started. It takes indefinite time to build and refreshing app, which was working absolutely ok using "Create-react". Until now no external db connection involved. 

After this I decided not to use meteor for this and I have started to create apis in node.js and will continue with "Create-react".  

Sorry meteor team.

**Comment by arggh** [comment]
> @filipenevola I and my team designed admin panel app using core-ui react template...

I believe this has nothing to do with the MongoDB degradation problem discussed here.

**Comment by filipenevola** [comment]
Hi @hiteshagja, I can't say much about your issue but as you are not using a database it seems not related to this issue here at all.

Maybe you are importing some modules in a way that Meteor is not tree-shaking (this is in beta) and Create react app was tree-shaking.

Without your reproduction it's hard for us to say, if you can please open a new issue with a reproduction and we will be glad to take a look.

We definitely have many projects using Meteor + React without issues. You can see my talk where I show some numbers in a big React app with Meteor (link to the specific moment where I show some numbers https://www.youtube.com/watch?v=Zg_NTjtvMP8&t=913s).

I'm going to hide my comment and yours and they are not related to this issue here.

**Comment by filipenevola** [comment]
Hi @arggh closing and opening issues is not a big deal. We are never going to deny reopening issues so we should not waste our time discussing about this.

As you can see we've been very transparent in everything that we are doing in Meteor. Roadmaps, podcast, talks, blog posts, etc. We don't have anything to hide. As I already said some times, the goal here is to have opened only the issues that we (community) want to work on and we have confirmed they are problems or features on Meteor and not in related technologies. I know you hated stale-bot and now that we have a better process to keep the stage of each issue/PR it was removed 😉 No more stale-bot 🎉 

About this https://github.com/meteor/meteor/issues/10712, it's a known issue that tree-shaking alleviates or solve when the app is including a huge module. As Meteor (in the stable versions) doesn't have tree-shaking is expected to take time to build an app importing huge modules even if they are not used.

We are already investigating how to minimize this even without tree-shaking in case we want to have it disabled in development. @renanccastro and @zodern should have some news about this in the near future. We believe this time for this specific case was increased on Meteor 1.8.2.

This issue was classified as MongoDB driver related 1 year and a half ago, that is why I closed it as not directly related to Meteor. If we have many opened issues about the same problems or improvements that we want to have on Meteor we will waste time tracking and understanding all of them, it's better to manage the same problem in a single issue here on GitHub.
