### ISSUE TITLE
Meteor 1.8.1 uses dynamic loaded modules as "modern" in "non-modern"-browsers from the cache

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#10524]
i have a problem with certain browsers, see here: https://github.com/meteor/meteor/issues/9934#issuecomment-482061535

I found out that in this case, the non-modern browser loaded a lazy/dynamic loaded module which was transpiled as "modern" from its indexeddb-cache. After wiping the indexedDB, the issue was gone. 

The application was updated from METEOR@1.8.1-beta.17 to METEOR@1.8.1. So maybe something went wrong there with the cache? Is it possible to force meteor to re-download the dynamic loaded files or to clear the indexedDB?

**Comment by benjamn** [comment]
The version hashes that we use to store dynamic modules in IndexedDB are based on the final compiled code of the module, so while it's possible that the exact same module might be used in both modern and legacy bundles, it should be fine to share the code (because it's the same code). Hash collisions are possible in theory, but I would much sooner blame bugs in the caching code.

We can definitely modify the hashing code to rehash every module, effectively invalidating the current contents of IndexedDB, but I'd like to make sure we've fixed the underlying issue first.
