### ISSUE TITLE
Unreachable require should be ignored

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#10538]
When using the `jsdom` library, meteor struggles with this piece of code:

```js
 exports.Canvas = null; 
 let canvasInstalled = false; 
 try { 
   require.resolve("canvas"); 
   canvasInstalled = true; 
 } catch (e) { 
   // canvas is not installed 
 } 
 if (canvasInstalled) { 
   const Canvas = require("canvas"); 
   if (typeof Canvas.createCanvas === "function") { 
     // In browserify, the require will succeed but return an empty object 
     exports.Canvas = Canvas; 
   } 
 } 
```

It sees the `require("canvas")` and tells me to install it, even though it will never reach it. 

I expect meteor to not tell me to install it:

```sh
Unable to resolve some modules:

  "canvas" in /Users/Florian/.../node_modules/jsdom/lib/jsdom/utils.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save canvas    
```

Related: https://github.com/jsdom/jsdom/issues/2508

**Comment by sakulstra** [comment]
actually we're a similar problem with `component-classes` (which is required via rc-slider).
The following piece of code:
```
try {
  var index = require('indexof');
} catch (err) {
  var index = require('component-indexof');
}
```
results in 
```
Unable to resolve some modules:

  "indexof" in
.../node_modules/component-classes/index.js
(web.browser)
```
although `component-indexof` is installed.

**Comment by benjamn** [comment]
It's standard practice for JS bundlers (Browserify, Webpack, Parcel, Rollup, Meteor, etc.) to treat any `require(...)` call as a dependency, even if there's a chance the call will not be executed. Scanning the AST for `require` calls is a relatively easy static analysis task, whereas the question of whether a particular bit of code will be executed at runtime—especially when its execution depends on dynamic information like `canvasInstalled`—is fundamentally [undecidable](https://en.wikipedia.org/wiki/Undecidable_problem), so most bundlers don't even try to answer that question.

You could `npm install` the offending packages to get rid of the warnings, but then the packages would be bundled unnecessarily. If you just ignore the warnings, and your code works at runtime, you don't have to pay the cost of bundling the unused packages. That's why I included the specific language "If you notice problems related to these missing modules," meaning that no action is required if there are no problems.

If you're interested in a way to silence these warnings, I hear you, but I also have to be honest with you that it's not a very high priority right now. Please see [`_warnAboutMissingModules`](https://github.com/meteor/meteor/blob/efc8a3525db6067bf1d381c033c6ac937c15d631/tools/isobuild/compiler-plugin.js#L1437) for the relevant code if you're interested in working on a PR.

**Comment by derwaldgeist** [comment]
Same problem here after I installed `rc-slider`
