### ISSUE TITLE
Build is not listening to changes in the `public` and `private` folder anymore

### ISSUE THREAD

**Issue by scharf** [meteor/meteor#10590]
Meteor version `1.8.1` on MacOS

When I change a file in `public` or `private` meteor does not rebuild anymore. Adding or removing a file triggers a rebuild. 

Since there is now the `.meteorignore` anyone who does not want this behaviour should add the respective directories to  `.meteorignore`.

To reproduce:

```bash
meteor create dummy
cd dummy
mkdir public
meteor
```

In another shell add a file. This triggers a re-build (as expected):
```
touch public/dummy.txt
```

Changing the file does **not** trigger a re-build:

```
echo 'hello world' >  public/dummy.txt
```

Removing the file does trigger a re-build:
```
rm public/dummy.txt
```

**Workaround**

manually trigger a rebuild by adding and removing a trigger file....

```
rm -f public/*.dummy-file; touch public/`date "+%Y-%m-%dT%H:%M:%S"`.dummy-file
```

**Comment by rooch84** [comment]
I'm also experiencing this issue.

**Comment by domq** [comment]
Experiencing the issue here too (Mac OS X version 10.14.6 (18G95); file system is case **in**sensitive).

For some reason, the timestamp seems to be ignored i.e. changing a file in `public` has no effect on a running Meteor server; on the other hand, creating or deleting a file works normally (see attached GIF).
![meteor-public](https://user-images.githubusercontent.com/1629585/67148003-af36cb80-f29a-11e9-824b-bf4dc7cb9561.gif)
A workaround is therefore to delete and recreate files.
