### ISSUE TITLE
I've tried downloading this software all day and it won't load, I've tried downloading chocolately then downloading meteor but it keeps timing out. I'm trying to download it directly but now it won't stop loading.

### ISSUE THREAD

**Issue by juliaotteson** [meteor/meteor#10601]

**Comment by CaptainN** [comment]
This is indeed, extremely annoying. The fix for me is to do these things:

1. Disable Windows Defender while installing Chocolatey and Meteor, which is the bane of Windows life.
2. Try to install. If it stalls, or fails. Restart the whole computer, then disable WD, then try again. Yes, restart the whole computer. Windows is just like this - but most of the time for me, it will install the second time, right after a restart. Oculus Rift also requires constant full system restarts, other games generally run much better after a fresh restart. It's not just Meteor or Chocolaty, it's Windows..

After you do get it installed, meteor tends to run pretty well, but it will occasionally stall when you try to do a `meteor update` on a project. Same as above applies. You may also want to put your meteor install directory, and your project directory both in an exceptions list in Windows Defender. NPM and node can be quite slow if Windows Defender is active.

**Comment by klaussner** [comment]
Closing because this is not a Meteor bug.
