### ISSUE TITLE
Help getting up and running to port Meteor tools to TypeScript

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#10613]
I gotta earn this water bottle! A bag would be nice too.

I just cloned Meteor, checked out the `release-1.8.2` branch, converted `archinfo.js` to `archinfo.ts`, then realized there were no types available, but I also didn't see an obvious package.json in order to run `npm install` for utils (I do see a ton of them in other tools folders).

So I tried running `./meteor` to set things up (is this right?).

Ironically, I got the error

```
release-1.8.2 ❯ ./meteor
It's the first time you've run Meteor from a git checkout.
I will download a kit containing all of Meteor's dependencies.
######################################################################## 100.0%
Installed dependency kit v8.16.0.21 in dev_bundle.

module.js:550
    throw err;
    ^

Error: Cannot find module './archinfo.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tools/utils/utils.js:7:16)
    at Module._compile (module.js:653:30)
    at Module.Mp._compile (/tools/static-assets/server/runtime.js:41:21)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/trusktr/src/meteor+meteor/dev_bundle/lib/node_modules/meteor-babel/register.js:59:14)
    at Module.load (module.js:566:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:13:29)
```

because, I renamed archinfo to .ts. :)

So I renamed that back, ran `./meteor`, and `dev_bundle/lib/node_modules` exists.

But now I'm in archinfo.ts (renamed it again), and it says there's no `underscore` module.

It's not a standard TS workflow, so I'm not sure how I should proceed.

**Comment by Floriferous** [comment]
It would actually be really helpful to have a `TypeScript migration guide for Meteor`, which has a checklist of things to do in each file. And since people are almost rewriting entire files, it could be helpful to migrate old code as well.

Maybe this can also help set the scope of the changes, for example:

Checklist: 
1. Add types to each variable
1. Add types to each function
    * "Here's what a good type name looks like in this repo: ..."
1. Rewrite all require statements as `import` statements
1. Rewrite all `var` as `let` or `const`
1. Explicitly import as many global variables as possible (#10560)
1. etc.

Instructions:
1. Only convert a single file per PR
1. etc.

Common pitfalls:
* TBD

**Comment by trusktr** [comment]
Ah, I see, the main thing I was missing was to add `@types` dependencies to `dev-bundle-tool-package.js`. I'll give porting some files another go when I find more time...

**Comment by menewman** [comment]
Based on some feedback from Ben [here](https://github.com/meteor/meteor/pull/10650#pullrequestreview-266903936), I have a few suggestions for a style guide:

1. Use semicolons instead of commas when defining a type like this:
```ts
// do this
type Foo = {
  bar: number;
  baz: number;
};

// ...not this
// do this
type Foo = {
  bar: number,
  baz: number,
};
```

2. Use the `private` modifier to make underscore-prefixed members, including methods, actually private. Then, remove the underscore from the member name.

**Comment by bbenoist** [comment]
@menewman It would be nice to use `git mv` for renaming files so that their history could be kept 😉

**Comment by bbenoist** [comment]
@menewman 
> Use semicolons instead of commas when defining a type like this:
> ```ts
> // do this
> type Foo = {
>   bar: number;
>   baz: number;
> };
> ```

I would suggest using `interface` instead of `type`:

```ts
interface Foo {
  bar: number;
  baz: number;
};
```

Bonus, with this rule of thumb you don't care about commas and semicolons since `interface` only allows semicolons.

**Comment by nicu-chiciuc** [comment]
@bbenoist what are the benefits of using interface? I'm usually using type so that I can create union or intersection types easily.

**Comment by menewman** [comment]
Not sure if stale or still relevant?

Not sure what the current priority of TypeScript migration is; it seems like migration has been on pause since a bit before the Tiny acquisition. Either way perhaps this doesn't need to be an "issue" since it doesn't really describe a problem with Meteor.

**Comment by afrokick** [comment]
@filipenevola @benjamn any plans?

**Comment by MarceloPrado** [comment]
@afrokick I just had a conversation with Filipe and we're going to review some of the opened PRs related to typescript conversion (there about 10 of them right now).

I don't really know the priority of converting to TS, but count on me to drive this effort a little further. 
Any help is appreciated!
