### ISSUE TITLE
Cordova iOS - Update cordova-plugin-wkwebview-engine to 1.2.0 in webapp package

### ISSUE THREAD

**Issue by rossmartin** [meteor/meteor#10626]
When iOS 11 came out it messed up new apps being built that used the `cordova-plugin-wkwebview-engine` (meteor forces you to use this and you cannot use UIWebView).  There has been an update to `cordova-plugin-wkwebview-engine` (1.2.0) that fixes a very important issue on devices running iOS 11 and higher.  The issue with using `cordova-plugin-wkwebview-engine` < 1.2.0 on iOS 11 or higher is that it causes a blank white space in the top or bottom of the webivew (see attached screenshots below).  It is caused by the `cordova-plugin-wkwebview-engine` < 1.2.0 when the `StatusBarOverlaysWebView` preference is set to `true` (most cordova iOS use this preference with the status bar plugin).

![image](https://user-images.githubusercontent.com/2498502/61087929-9c3f7000-a3fc-11e9-8272-f6665295040f.png)

![image](https://user-images.githubusercontent.com/2498502/61087938-a3ff1480-a3fc-11e9-839a-b63e6a7f0ab7.png)

Here is the change that happened in `cordova-plugin-wkwebview-engine` in May 2018  (around line 99, see "start of fix" and "end of fix" for new code needed for iOS 11+) - 

`cordova-plugin-wkwebview-engine\src\ios\CDVWKWebViewEngine.m`
```
// re-create WKWebView, since we need to update configuration
WKWebView* wkWebView = [[WKWebView alloc] initWithFrame:self.engineWebView.frame configuration:configuration];

// start of fix
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
if (@available(iOS 11.0, *)) {
  [wkWebView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
}
#endif
// end of fix

wkWebView.UIDelegate = self.uiDelegate;
self.engineWebView = wkWebView;
```

That was part of this commit - https://github.com/apache/cordova-plugin-wkwebview-engine/commit/81eeadeb542fefc05c4cd5e68ba0221e6a965c73

If I manually apply that change in the `CDVWKWebViewEngine.m` file my app renders correctly on all iPhone devices.  Without that fix I end up with a blank white space at the bottom of the webview.

I see that the meteor webapp package.js has a `Cordova.depends` for `cordova-plugin-wkwebview-engine` set to `1.1.4` - https://github.com/meteor/meteor/blob/b3807831e45008ad17be4e9457f02d60bf6505dc/packages/webapp/package.js#L24

Please update this to `1.2.0` to solve this issue for iOS 11 and higher.  This issue is also directly related - https://github.com/meteor/meteor/issues/9041

@martijnwalraven  @benjamn

**Comment by rj-david** [comment]
@benjamn, does this mean that if we explicitly installed `cordova-plugin-wkwebview-engine@1.2.1` it will not override the version added in `Cordova.depends()` function?

Would also like to figure out how can we help to completely remove the dependency of cordova with Meteor core so that the community can take over the upgrade of cordova packages outside meteor. There were issues with the cordova-ios that hopefully fixed by the cordova community soon but it will seem to require updates with meteor core to use the updates

**Comment by filipenevola** [comment]
Let's update this also here #10810

**Comment by filipenevola** [comment]
hi @rossmartin, as you can see [here](https://github.com/apache/cordova-plugin-wkwebview-engine/commit/dc8b277) the fix you are mentioning was reverted but we are going to update to latest anyway because it also includes other [fixes](https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/RELEASENOTES.md#120-jun-27-2019).

I have iOS apps running Meteor 1.8.1 version without the issue mentioned by you.

If you still need help fixing this issue let me know and soon we will have guides to explain everything you need to do to deliver high-quality native apps with Meteor.

I'm closing this as we are going to update but not because of this issue specifically.

**Comment by rossmartin** [comment]
@filipenevola Thanks for the update and info.  Are your iOS apps using the `cordova-plugin-statusbar` plugin with the `StatusBarOverlaysWebView` preference set to `true`?  If you aren't using that plugin and preference then this issue won't occur.

**Comment by filipenevola** [comment]
Hi @rossmartin for the plugin yes, for the preference no.

I just reopened this issue and we can check if this is solved soon when Cordova 9 branch is available in a beta release.

**Comment by filipenevola** [comment]
Hi, as we already have even RCs for 1.10 I'm closing this. Please double-check on 1.10-rc.3 or the latest.
