### ISSUE TITLE
[1.8.2-beta.15] IE11 - Base64 package - Object doesn't support 'forEach'

### ISSUE THREAD

**Issue by rodcope1** [meteor/meteor#10628]
When trying to use Google or Facebook login, I get the following error in my Windows 8.1/IE11 VM:

> "Object doesn't support property or method 'forEach'"

It happens on line 35 of the standard Meteor base64 package's _encode_ function which looks like this:

`array.forEach((elm, i) => {`

It's very easy to reproduce in the IE11 console:

`> Base64.encode("test")`
`"Object doesn't support property or method 'forEach'"`

I just rapidly upgraded from 1.6 to 1.6.1.4 to 1.7 to 1.8.1 to 1.8.2-beta.15 (to fix another issue I was having with 1.8.1), so I don't yet know which version caused this to stop working.  This appears to be the last issue I have with 1.8.2-beta.15 in a large app.

**Comment by jamesmillerburgess** [comment]
Looks like for strings it is converting to an `Uint8Array`, which doesn't support `forEach` on any version of IE:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/forEach#Browser_compatibility

I'm the one that modernized this and caused the issue, but I'm not sure if the fix for this should be avoiding the use of `forEach` or polyfilling the method for `TypedArray`.

**Comment by rodcope1** [comment]
Thanks for the quick fix!
