### ISSUE TITLE
[1.8.2-beta.18] Uncaught (in promise) Error: Cannot find module (but the file exists)

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#10698]
I'm importing a file that exists (I quadruple checked), but I get `Error: Cannot find module`.

**Comment by trusktr** [comment]
To reproduce:

```
git clone --recursive git@github.com:trusktr/trusktr.io.git
cd ./trusktr.io/meteor-app
git co meteor-issue-10698
npm i
meteor
```

then open `localhost:3000`.

**Comment by trusktr** [comment]
I'm having this same issue on `1.8.1` as well. I reverted to the previous version of Meteor I was using, `1.6.1.4`, to get back to a working state.

**Comment by benjamn** [comment]
The file in question (`rsvp.vue`) contains `<style lang=sass>`, so you need to run `meteor add akryum:vue-sass` to install that language plugin. If you don't do this, the Vue compiler throws an error internally, so the compiled code never gets passed to `inputFile.addJavaScript`, which is why the module ends up missing in the client bundle.

While you're at it, it looks like you need to update `akryum:vue-component` to version 0.15.1:
```sh
meteor update akryum:vue-component
```
This version of `akryum:vue-component` was compiled assuming the current `module.link` API, rather than the deprecated (and now removed) `module.watch` API.

Finally, you may need to run `meteor npm i vue@latest` to avoid a Vue version mismatch error.

These problems are compounded because the `akryum:vue-component` package sometimes swallows the errors because `e.line` may be undefined [here](https://github.com/meteor-vue/vue-meteor/blob/6ef113739751c024f02bf67c5c71c6c5da094ae6/packages/vue-component/plugin/vue-compiler.js#L543).
