### ISSUE TITLE
Meteor detects IE11/Vivaldi/Firefox Mobile/Chromium to use legacy bundle, causes Wekan to not work on those

### ISSUE THREAD

**Issue by xet7** [meteor/meteor#10692]
https://github.com/wekan/wekan/issues/2643

**Comment by benjamn** [comment]
The legacy bundle should work in all browsers, not just legacy browsers. If that's not the case, then that's a bigger problem than which browsers are classified as legacy browsers.

**Comment by xet7** [comment]
From ksy at https://webcompat.com/issues/38423#issuecomment-524950168

Firefox and Chrome are being served different js files.

I get [this bundle](https://boards.wekan.team/68ad622d5840c0345bb18fa03590ef9fa1228a6b.js?meteor_js_resource=true) in Firefox and [this one](https://boards.wekan.team/12b6e45e597687a086414a57a18cf86611237213.js?meteor_js_resource=true) in Chrome.

When I click on the cards I get this error: `Error: No such template: minicardStartDate`, so looks like for Firefox the template is not being registered, while in the bundle for Chrome I see:
```
 .register("minicardStartDate"),
      class extends r {
          showDate() {
              return this.date.get().format("l")
          }
   }
```
Unsure why this is happening, but looks like Firefox for Android is being considered legacy browser by Meteor.js, so it gets a different bundle intended for older browsers:
```
function() {
        var t = __meteor_runtime_config__;
        e = t.meteorEnv,
        n = {
            isProduction: "production" === e.NODE_ENV,
            isDevelopment: "production" !== e.NODE_ENV,
            isClient: !0,
            isServer: !1,
            isCordova: !1,
            isModern: t.isModern
        },
        t.gitCommitHash && (n.gitCommitHash = t.gitCommitHash),
        t.PUBLIC_SETTINGS && (n.settings = {
            public: t.PUBLIC_SETTINGS
        })
    }
```
so isModern here is false for Firefox for Android.

When I spoof as Chrome, a different js bundle is served and cards open up.

I came across this discussion #9751 for Chrome Mobile,
we could perhaps add a similar PR for Firefox Mobile to https://github.com/meteor/meteor/blob/devel/packages/modern-browsers/modern.js , though this requires a bit of testing.

I'll look into adding the PR, but for now I'll move this issue into needs contact.

**Comment by xet7** [comment]
This happened when I upgraded from Meteor 1.6.x to 1.8.1.

I started getting bug reports that Wekan stopped working in those browsers.

**Comment by xet7** [comment]
> The legacy bundle should work in all browsers, not just legacy browsers. If that's not the case, then that's a bigger problem than which browsers are classified as legacy browsers.

Can you give more details, if this is not about browser detection, what can it then be?

**Comment by benjamn** [comment]
Accidentally classifying Firefox as a legacy browser is definitely a bug, but it shouldn't cause your application to break. The legacy bundle is bigger than the modern bundle because it's compiled to an older ECMAScript target, and has more compatibility logic, but it should be functional in all browsers. I think what's happening here is that the legacy bundle is broken in all browsers, and the accidental classification of Firefox as a legacy browser merely surfaced that brokenness in a browser that developers were actively testing.

**Comment by xet7** [comment]
Hmm, I did not even think of that. To me, Meteor is this magic kitchen sink of everything that makes it possible to code advanced features with just a couple lines of code.

**Comment by CaptainN** [comment]
I don't know if it's relevant to this specific case, but when I've had legacy browser breakage it has been because an npm packages has uncompiled modern syntax. The solution is to do the symlink thing to get it to compile (which I don't know how to do cause I'm on Windows), or use 1.8.2 (currently at rc.0) and it's recompile setting.

**Comment by xet7** [comment]
@CaptainN 

How do you set it's recompile setting?

**Comment by benjamn** [comment]
@xet7 Here's the PR that introduced the `meteor.nodeModules.recompile` configuration options in `package.json`: https://github.com/meteor/meteor/pull/10603
