### ISSUE TITLE
When importing a folder, 'index.css' files will be imported instead of 'index.tsx'.

### ISSUE THREAD

**Issue by nicu-chiciuc** [meteor/meteor#10708]
_Meteor version:_ 1.8.2-rc.3
_OS:_ macOS Mojave 10.14.6
_Expected behavior:_
When importing a folder which contains an 'index.tsx' and an 'index.css', the 'index.tsx' should be imported.
_Actual behavior:_
The `index.css` is imported causing errors.

_Reproduction repository:_ https://github.com/nicu-chiciuc/meteor-import-issue
The repository has 2 commits. In the first one, the command `meteor --release 1.8.2-rc.3 create --typescript meteor-import-issue` was run. And in the second one `Hello.tsx` was moved to `Hello/index.tsx` and the empty file `Hello/index.css` was added.

**Comment by nicu-chiciuc** [comment]
This issue is probably caused by `resolver.ts` and the order in which extensions are chosen in `joinAndStat()`.

**Comment by benjamn** [comment]
In cases like this, you really should just include the file extension explicitly in your import. Otherwise you're rolling the dice. There's no way for Meteor to read your mind that `.tsx` deserves higher priority than `.css`. This might work in systems where `.css` is never imported as JS, so `.css` files are simply ignored, but in Meteor importing a `.css` file makes it part of the JS bundle, and injects the stylesheet lazily into the DOM. This ambiguity is fundamental.

**Comment by jonlachlan** [comment]
I doubt there should be more than one index file in any module. I would add `import './styles.css'` to index.tsx.

**Comment by nicu-chiciuc** [comment]
It doesn't happen just to index files. For any files with the same name, the `.scss` one will be chosen instead of the `.tsx` one. We've resorted to renaming the files as we go along with the typescript conversion, so the issue can be closed. Nevertheless, it seems like a very hidden quirk.

**Comment by jonlachlan** [comment]
It seems like `*.tsx` is being used as an extension of/alternative to `*.js`, in a JavaScript module system. I'd say there is no reason to support`*.css` nor `*.scss` files, etc., as modules, i.e., one ought to specify the full filename+extension of style files.

**Comment by nicu-chiciuc** [comment]
That's exactly what we do for style files, we specify the filename+extension. But for `.tsx` and `.js` files we don't.

**Comment by nicu-chiciuc** [comment]
I'm closing the issue since it's stale and the problem is more of a tricky behavior instead of an issue.

**Comment by bduff9** [comment]
@nicu-chiciuc I would really like this reopened if possible, I just spent a week converting my React app to typescript and ran into this exact issue.  I can specify the .tsx in all imports to get Meteor to at least compile the app as expected, however, that breaks VS Code (I get a TS error that I should not include the tsx suffix as apparently this is not valid typescript to specify ts or tsx) and so I do not get any type hints on imported components nor can I command-click to directly open a component:
```
An import path cannot end with a '.tsx' extension. Consider importing '../MovieItemsDetail/MovieItemsDetail' instead.ts(2691)
```

Since Meteor does not currently enforce types, this makes it much harder to use Typescript in React projects.  I would at least like to discuss if others have this issue or if there is a way around this or something I'm doing wrong as currently, a lot of the benefit I was hoping to gain in this React project with Typescript is lost due to this issue.

**Comment by nicu-chiciuc** [comment]
@bduff9 The solution we resorted to, was to rename files like so:
```
index.js  -> index.tsx 
index.css -> styles.css
```

```
SomeComponent.js      -> SomeComponent.tsx
SomeComponent.css     -> SomeComponentStyles.css
```

I guess this could've been automated. But we basically use this renaming technique whenever we touch a component that needs to be converted.

**Comment by nicu-chiciuc** [comment]
So in this case, the extensions don't have to be specified.

**Comment by bduff9** [comment]
Thanks, I went with `SomeComponent.module.css` but that does seem to work better now

**Comment by javoire** [comment]
Hello! So I also ran into this (#11041). To shortly summarize the inconsistency:

**Case 1A:** Typescript and CSS -> `SomeComponent.css` is imported
**Case 1B:** Typescript and LESS -> `SomeComponent.less` is imported

**Case 2A:** Javascript and CSS -> `SomeComponent.css` is imported
**Case 2B:** Javascript and LESS -> `SomeComponent.less` is **not** imported

Case 2B is where I was, then I migrated to Typescript, like some commenters above, which subsequently broke my app.

This being inconsistent would qualify it as a bug imo! It's an odd developer experience.

What would be the technical difference between Case 2B and Case 1B? Some new behavior in Meteors module resolution?

Cheers

**Comment by javoire** [comment]
Also for anyone reading who wants to use the workaround mentioned by e.g. @nicu-chiciuc, here's a script to change all `MyComponent.less` to `MyComponentStyles.less`

```sh
find imports -name "*.less" -exec sh -c 'mv "$0" "${0%.less}Styles.less"' {} \;
```
