### ISSUE TITLE
[1.8.2] Production build times have increased with 50%

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#10786]
When deploying using meteor-up from CircleCI our build times have increased from ~10 minutes to ~15 minutes after upgrading from Meteor 1.8.1 to Meteor 1.8.2.

**Comment by benjamn** [comment]
I've observed something similar, and I have a theory that the performance is caused by additional memory pressure. Since optimistic in-memory caching is one of the more memory-intensive parts of the build system, I have found that setting the environment variable `METEOR_DISABLE_OPTIMISTIC_CACHING=1` can help improve memory usage during `meteor build`, which seems to improve the total build times. This configuration is perfectly safe because the whole point of optimistic caching is to keep track of previous results for future _rebuilds_, but in the case of `meteor build` there's only ever one initial build, so the extra bookkeeping is unnecessary. If we can validate this hypothesis, I think I'd like to disable optimistic caching by default when running `meteor build` or `meteor deploy`.

**Comment by KoenLav** [comment]
Thanks for the swift reply, testing now.

**Comment by KoenLav** [comment]
@benjamn using that environment variable the deployment time went down to 10:40 again (whereas it was consistently at 15/16 minutes before that), so I guess we can confirm your hypothesis.

**Comment by Floriferous** [comment]
Just FYI, this took our circle CI build time down from ~7mins to 1.5mins, i.e. almsot 5x faster :)

**Comment by rj-david** [comment]
We slashed 8 minutes from our build time. Thanks

**Comment by smeijer** [comment]
@benjamn, as you closed this issue, does that mean that `METEOR_DISABLE_OPTIMISTIC_CACHING` will become the default for the `build` command?
