### ISSUE TITLE
MongoDB and Meteor Minimongo sorting null and undefined differently

### ISSUE THREAD

**Issue by nsinfoPRO** [meteor/meteor#10852]
https://stackoverflow.com/questions/59643348/mongodb-and-minimongo-sorting-null-and-undefined-differently

**Comment by Warchino** [comment]
Do you have any repo to reproduce it?

**Comment by sebakerckhof** [comment]
Minimongo sorting matches mongodb.
Execute this in your browser console to verify:
```js
const test = new Mongo.Collection(null);
test.insert({foo: undefined});
test.insert({foo:'foo'});
test.insert({foo:null});
test.find({}, { sort: { foo: 1 } }).map(i => i.foo);
```

Returns correctly: `[undefined, null, 'foo']`

**Comment by nsinfoPRO** [comment]
If you use MongoDB date. Yellow is mark as undefined.
![Capture](https://user-images.githubusercontent.com/40522817/72517973-9a93b080-3854-11ea-8354-f337e2da7c87.PNG)
![Capture2](https://user-images.githubusercontent.com/40522817/72517990-9ff0fb00-3854-11ea-8f78-6c0372720639.PNG)

**Comment by sebakerckhof** [comment]
This is a bug with minimongo explorer, you will have to take it up with the developer of that plugin (ping @radekmie )

If you use minimongo directly, it also works correct for dates, this behavior is well covered with unit tests:
```
const test = new Mongo.Collection(null);
test.insert({foo: undefined});
test.insert({foo:new Date()});
test.insert({foo:null});
test.find({}, { sort: { foo: 1 } }).map(i => i.foo);
```
Result:
```
[undefined, null, Thu Jan 16 2020 13:58:21 GMT+0100 (Central European Standard Time)]
```

**Comment by radekmie** [comment]
Indeed, it may be a bug in MiniMongoExplorer. I'm actually using [marsdb](https://github.com/c58/marsdb) for [sorting](https://github.com/radekmie/MiniMongoExplorer/blob/master/extension/lib/safeDocumentSorter.js), which is no longer maintained, but it's something I could take care of. But I don't have to, because the sorting is actually working - the thing is, that the table sorting is not working though. It should affect the `sort` above, not sort it on its own.

Anyway, @nsinfoPRO, please do file an issue. I think this one can be closed then.
