### ISSUE TITLE
Unable to upgrade to Meteor 1.9 due to stylus issue

### ISSUE THREAD

**Issue by deepakprabhakara** [meteor/meteor#10868]
I am upgrading our project from 1.8 to 1.9 (I had also tried 1.8.1 earlier and had the same issue) but the build fails since for some reason stylus is not being preprocessed correctly. I am using the coagmano:stylus package but the issue seems to be with the standard-minifier-css package.

Has anyone successfully upgrade a project with stylus to Meteor 1.9? Otherwise are there any workarounds I could try.

```
Errors prevented bundling:
While minifying app stylesheet:
<input css 1>:4830:3: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: 0.4em + $error-frame-width
```

**Comment by benjamn** [comment]
You could try cloning https://github.com/Meteor-Community-Packages/meteor-stylus into your app's `packages/` directory, so that it will be rebuilt by Meteor from source, which might avoid the mismatch between the last published version of the package and the new version of Meteor. If that works, then the package probably needs to be republished with Meteor 1.9 (after its minor version is bumped), which is something you could take up with `coagmano`.

**Comment by deepakprabhakara** [comment]
Thanks @benjamn . When you say clone it in the app's `packages/` directory where exactly do you mean? There is no such directory in my app folder and trying this in the packages directory of the .meteor home directory did not work.

**Comment by filipenevola** [comment]
Hi @deepakprabhakara this folder should be in the root of your project and not inside .meteor folder. Then Meteor will first try to resolve packages from this folder.

**Comment by deepakprabhakara** [comment]
Thanks @filipenevola, I'll give that a try.

**Comment by deepakprabhakara** [comment]
That didn't work, I get the same error.

**Comment by deepakprabhakara** [comment]
I have switched standard-minifier-css with postcss and it is looking promising. Will post back if it works.

**Comment by deepakprabhakara** [comment]
Switching standard-minifer-css to postcss did the trick. Thanks @filipenevola @benjamn. I will close the issue.
