### ISSUE TITLE
Mongo 1.8.2 client/server pub/sub data update not working

### ISSUE THREAD

**Issue by irafunesta** [meteor/meteor#10915]
Hello I have a strange problem with 2 Meteor apps that i’m working on, both of them use Meteor 1.8.2, but only one of them is working properly.
I have attached both applications, they use an external mongo instance to save data , i have removed all the code except for a single page with a list of data, in the working app, if i change a value in the collection, the page is refreshed with the new value,
in the not working app, the page is never refreshed until i add/remove a document from the collection or change a document structure.

To test this behavior

lunch MongoDB, create a database called testdata and add the collection test_client_update (attached the collection .json file)
lunch both app with meteor npm start,
the working one is on localhost:7002, the not working one is on localhost:7000
change a value in the collection and see the issue.
Both app where made with Meteor 1.8 and then updated to 1.8.2
Here is the link to the apps https://drive.google.com/file/d/1Y9e_HU_eoZQDc1NWcqXQnZgSHSHPK1yQ/view?usp=sharing

Thanks for the help

**Comment by irafunesta** [comment]
Has anyone ever had this bug ?

**Comment by filipenevola** [comment]
Hi, I've checked your code and you have a lot of packages there, maybe one of these packages are causing the issue because this is not a Meteor issue as you can see your other app is working fine and if I create a new app it's also working fine. My advice would be for you do remove the packages one by one to check if the reactivity return to work fine.

If you can create a reproduction in a new project I would be glad to investigate the issue but I really don't believe the issue is on Meteor.
