### ISSUE TITLE
Accounts base login method expects `this.connection` to be defined

### ISSUE THREAD

**Issue by eric-burel** [meteor/meteor#10937]
Hi,

I am currently trying to make Meteor fully usable through GraphQL, without DDP connection. The last missing bit is user authentication.

- Meteor version: 1.83 but should apply to 1.9 too.
- Running locally on Ubuntu, calling the Meteor server through a graphql endpoint

I've tried to reuse the `login` method defined by `meteor/accounts-base`. It should work correctly, however it expects a `connection` to be defined.
As far as I understand, handling the connection (I guess we talk about active DDP connection) and handling auth are actually rather independant problems.

### Expected
Therefore, I would expect the `login` method to work even if `this.connection` is not defined.

[Relevant code is here](https://github.com/meteor/meteor/blob/d612d7546fa446cd574b51c0ea7953253f5e4bb7/packages/accounts-base/accounts_server.js#L854).

### Actual
`connection.id` will throw an error as `connection` may not be defined.

There is no reason to fail if `this.connection` is null or undefined. Do you think that parts of the code expecting a `connection` could simply be wrapped with an `if` statement?

**Comment by sebakerckhof** [comment]
Since Meteor is not stateless, I don't really agree that doing a login and handling the connection are independant, basically all methods (logout, logging out other connections, renewing tokens) are bound to the connection). In a stateless system you would just generate a token (Accounts._generateStampedLoginToken() / Accounts._insertLoginToken() ) and check it as part of authorization header or something similar. E.g. this is what `simple:rest` does.
Can you clarify what you expect the login call to do when you use the resume handler with a token? Just check the token and return true/false ?

**Comment by eric-burel** [comment]
I am not yet familiar with the more advanced pattern like "resume handler", to be fair Meteor accounts system is very impressive, it's the first time I get my hands on this part of the code.

Basically yes I only expect to check the token, with a basic JWT pattern.
 
I've seen that the stamped token comes with a `when` value in order to be hashed for comparison, but except during logout I am not sure of its use. This value is stored server side while the user usually only needs to store the token itself and pass it in the request header to be considered as authenticated.

Even during logout we do not really need to keep track of the token server side, it's only necessary in order to keep some legacy tokens active. We could just delete the whole `loginToken` array in the database to logout the user.

I'll try to post code as I progress I'll comment with a link in a few hours showing my draft stateless implementation. Again sorry if I am unclear as the auth process and its implication are hard to grasp.

**Comment by eric-burel** [comment]
Here is a demo with stateless login/logout: https://github.com/VulcanJS/Vulcan/blob/400efb96bf9496972ba39fb0f66d864cd39132a8/packages/vulcan-users/lib/server/AuthPassword.js

Sorry it's full of comments as it's a work in progress. It's based on `accounts` code but I only kept the stateless parts. Therefore it probably will work only very partially with Meteor, eg not supporting methods, publications and all. However the good thing is that you can connect clients that do not want to use Meteor.

My idea was to refactor the `accounts` code just enough so you can directly run the Meteor methods even when a connection is not defined. This would have allowed me to reuse them to implement those features.

**Comment by sebakerckhof** [comment]
Yes, that vulcan code is pretty similar to what for example simple rest does. Using the basic building blocks of the Accounts package to create a stateless login method is kind of the recommended way.
Note that that focuses on password authentication. But `accounts-password` is an optional add-on which `accounts-base` doesn't even know about. For example I have one app where users can only login with SAML.

A big part of the complexity in the accounts package is because Meteor deals with stateful connections. For example:
- on login / logout the subscriptions of that connection should be re-run ( done by https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js#L781 ).
- logging out other clients is also tricky because of this: https://github.com/meteor/meteor/blob/d612d7546fa446cd574b51c0ea7953253f5e4bb7/packages/accounts-base/accounts_server.js#L533-L587

So commenting out the connection-related parts isn't that easy and might become messy. While just creating a method like that Vulcan proposal is pretty easy.
It may also break other stuff, because onLogin/validateLogin hooks from users may expect the connection to always be there.

**Comment by sebakerckhof** [comment]
Btw, not to say that I don't think that separating accounts from DDP isn't a worthwhile effort. But it's a big effort/refactor

**Comment by eric-burel** [comment]
Yeah I understand. I'll close for the moment as it's not really an issue, more a feedback. I hope that auth technologies progressively unifies, Meteor's system is very powerful and it's tempting to try to use it everywhere ^^

**Comment by eric-burel** [comment]
Looking at `meteor-rest` they indeed have the same strategy we ended up to implement [in this code](https://github.com/stubailo/meteor-rest/blob/master/packages/rest-accounts-password/rest-login.js). However they also lose nice features like checking logging attempt, eg to avoid brute forcing password.

**Comment by julioysmaelhernandezalbarran-jpg** [comment]
A mí me aparece este error -1 cuando intento iniciar sesión con el meteor cliente
