### ISSUE TITLE
[1.9, maybe 1.8.2] Broken in Safari 9 due to SyntaxError

### ISSUE THREAD

**Issue by banjerluke** [meteor/meteor#10957]
Yes, I know, Safari 9 is almost five years old... who cares, right? 🙄

The thing is, a lot of somewhat-old iPads are stuck on this version, and I would like to continue to support them for a little while longer if I can.

Everything works just fine on release 1.8.1. But when I update to 1.8.2 (using `meteor update --release 1.8.2`, _without_ updating any Meteor/NPM packages), it doesn't load due to some SyntaxErrors.

Strangely, a blank Meteor 1.8.2 project *does* run, but a blank Meteor 1.9 project breaks in the same manner.

### Reproduction steps:

1. Get access to Safari 9 (desktop or mobile), probably either on an old iPad or a browser testing service like BrowserStack, LambdaTest, or CrossBrowserTesting.

2. Create a blank Meteor 1.9 (or later) project and run it:
```bash
meteor create safari-error-test
cd safari-error-test
meteor update --release 1.9
meteor
```

### Resulting errors in console:

```
SyntaxError: Invalid parameters or function name in strict mode
    promise.js:132

[followed by lots of "TypeError: undefined is not an object..." from modules not being loaded]

SyntaxError: Invalid parameters or function name in strict mode
    ecmascript-runtime-client.js:1129

[followed by many more TypeErrors]
```

### Relevant source code excerpts:

Excerpt from promise.js (line 132 is right after `'use strict'`):
```js
},"node_modules":{"promise":{"lib":{"es6-extensions.js":function module(require,exports,module){

///////////////////////////////////////////////////////////////////////////////////////
//
// node_modules/meteor/promise/node_modules/promise/lib/es6-extensions.js
//      
///////////////////////////////////////////////////////////////////////////////////////
                                                                                                                    
'use strict';
     //<---- this is line 132, the offending line... yes, this blank one
//This file contains the ES6 extensions to the core Promises/A+ API

var Promise = require('./core.js');

module.exports = Promise;

/* Static Functions */
. . .
```

Excerpt from ecmascript-runtime-client.js (again, the error's line number is the one right after `'use strict'`):
```js
},"es.map.js":function module(require,exports,module){

////////////////////////////////////////////////////////////////////////////
//
// node_modules/meteor/ecmascript-runtime-client/node_modules/core-js/modules/es.map.js
//
////////////////////////////////////////////////////////////////////////////

'use strict';
var collection = require('../internals/collection');
var collectionStrong = require('../internals/collection-strong');

// `Map` constructor
// https://tc39.github.io/ecma262/#sec-map-objects
module.exports = collection('Map', function (get) {
  return function Map() { return get(this, arguments.length ? arguments[0] : undefined); };
}, collectionStrong, true);
. . .
```

My hopes aren't very high, but if anybody has an idea of why this might be happening, please chime in. I'm at a loss myself. Thanks!

**Comment by cfnelson** [comment]
@banjerluke Not sure if this will be of much help. But I can attest to having experienced similar ambiguous Syntax Errors referring to promises and/or ecmascript or maybe it was the polyfills.

From memory most of the issues I encountered were in late 2018/early 2019 and were only occurring in Safari and were caused by:

- the usage of async/await/promises 
- the usage of **dynamic imports** along with async/await. 
- promise related bug that happened due to polyfills and bundling in production for older clients.
- I had a crash that would occur from just adding a pkg to the project or having  an import line in the source code but not instantiating the imported code.
- I was also able to trigger similar errors by minor variations in how code was being ordered or imported. (was only reproducible in production builds)

For most the issues I don't think I found satisfactory answers or solutions to the exact cause. I think it was mostly due to Safari behind behind or playing catch with certain web standards. 
I think most situations I ended up side stepping the issues altogether by reverting any of the code and/or doing something hacky to get around the issue in safari.

**Comment by banjerluke** [comment]
I verified that Safari 9 clients were receiving the legacy bundle, so async/await and other ES6+ features are transpiled. I've only got a couple dynamic imports for seldom-used features and the SyntaxErrors seemed unrelated. But yeah, probably something to do with polyfill changes, etc.

In the end, I just wrote all my users who were using iOS 9 devices (according to my analytics) and told them I was going to stop supporting it. Everyone seems to either be gracious and understanding, or keeping their mouth shut. 😉

This issue can be closed as far as I'm concerned, unless someone else wants to tackle this for their own project.
