### ISSUE TITLE
Adblocker breaks a Meteor app

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10959]
Took me a while to figure out what was going on. I just installed UBlock to my dev browser, which is Google Chrome.

UBlock is very effective in it's job. It causes an `Cannot find module` -error to be thrown on startup, since I have configured FlowRouter to track all pageloads via our own lightweight analytics package, which loads Google Analytics internally or uses `ganalytics` as a fallback.

Apparently UBlock decides to block the analytics code from being run, based on some Google-sniffing or name-based-heuristics, effectively breaking our Meteor app completely.

I'm not sure if this is something that can be mitigated or fixed by tweaking the Meteor module system, but I thought I'd share this since it took me a while to figure out why my app suddenly wasn't working, complaining about a missing package that definitely was installed.

<details>
<summary>Stack</summary>

```
modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232 Uncaught Error: Cannot find module 'meteor/arggh:analytics'
    at makeMissingError (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232)
    at Module.resolve (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:238)
    at Module.moduleLink [as link] (modules.js?hash=296b907d28c60caa2429456e308edc59fe5ea7c9:388)
    at module (routeHelpers.js:1)
    at fileEvaluate (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:346)
    at Module.require (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:248)
    at Module.moduleLink [as link] (modules.js?hash=296b907d28c60caa2429456e308edc59fe5ea7c9:395)
    at module (flowrouter.js:1)
    at fileEvaluate (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:346)
    at Module.require (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:248)
```

</details>

Possibly related: https://github.com/meteor/meteor/issues/10872

**Comment by hexsprite** [comment]
maybe file an issue with uBlock. Seems like a bug in uBlock. Shouldn't break the whole site...

**Comment by banjerluke** [comment]
It's probably because the module has the word "analytics" in the title. I'll bet if you rename it, the error will go away. (Wouldn't be an issue in production since all js files are combined into one.)

**Comment by cfnelson** [comment]
`@banjerluke` is correct, the cause is due to having `analytics` in the filename or request.
 
uBlock & other ad blockers will normally inspect the names of files being requested along with other various heuristics for deciding when to block requests or intercept incoming resources.

The issue isn't specific to Meteor, I've experienced the above in Meteor & non Meteor projects alike. A crash or inability to load the Web App was always due to how a package or our own source code being poorly designed by depending & expecting the blocked resource to exist.
Both situations can be resolved by refactoring the code to check if the bundle exists.

If you'd like to not experience the above in Meteor, you can rename the module or just run your app in with `--production`. If Meteor were to rename every pkg bundle it would make debugging during development more convoluted.

**Comment by arggh** [comment]
@cfnelson @banjerluke yup, like I wrote in the issue description:

> Apparently UBlock decides to block the analytics code from being run, based on some Google-sniffing or name-based-heuristics

> I'm not sure if this is something that can be mitigated or fixed by tweaking the Meteor module system, but I thought I'd share this since it took me a while to figure out why my app suddenly wasn't working

...Hoping that whoever happens to stumble on this same problem won't spend an hour trying to figure out why their app is suddenly crashing :)
