### ISSUE TITLE
Node options required to be together blocked to be used 

### ISSUE THREAD

**Issue by linegel** [meteor/meteor#10964]
Before reporting a bug, please check for existing or closed issues
first and read the instructions for filing a bug report:
https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor

Bug report:
Meteor version - 1.9.2
OS - MacOS

The expected behavior:
Pass `NODE_OPTIONS="--experimental-modules --input-type=module --es-module-specifier-resolution=node"` with meteor build and have flags used by nodejs during building process

The actual behavior.
Following error:
`/Users/User/.meteor/packages/meteor-tool/.1.9.2.1bpgp1k.xybn++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node: bad option: cannot use --es-module-specifier-resolution and --experimental-specifier-resolution at the same time
`

Simple reproduction:
Try to make a Meteor build with following node options:
` NODE_OPTIONS="--experimental-modules --input-type=module --es-module-specifier-resolution=node" NODE_ENV=production APP_ENV=dev meteor build ../app --directory --server-only --architecture os.linux.x86_64
`

Note №1: 
This works as expected, no errors thrown
<img width="1228" alt="Screen Shot 2020-03-12 at 04 29 34" src="https://user-images.githubusercontent.com/1746296/76478616-4fdc8200-641a-11ea-95b3-221efcbbb909.png">

With clean node, removal of --experimental-modules leads to error, coz it **required** for 2 other options 
Error which is thrown in case of --experimental-modules removal by node:
```
node: --input-type requires --experimental-modules to be enabled
node: --es-module-specifier-resolution requires --experimental-modules be enabled
```

Removal of  --es-module-specifier-resolution=node isn't a case since it's required for expected behavior during modules importing. 

Note №2:
Removal of --experimental-modules shows an error, that it is required to use both -input-type and --es-module-specifier-resolution (which previously was blocked by --experimental-modules) which makes situation feels like a circular block.
So, the actual question is why the usage of both
`--experimental-modules` and `--es-module-specifier-resolution=node` together throws error? 
<img width="975" alt="Screen Shot 2020-03-12 at 04 51 53" src="https://user-images.githubusercontent.com/1746296/76479556-3557d800-641d-11ea-806f-b2f442f7caa0.png">

Anybody had any similar issue or have ideas about why it's happening?

**Comment by linegel** [comment]
Just to make the issue clear, since Meteor 1.9.2 uses nodejs 12.16.1 I updated the local nodejs version from 12.12.0 to 12.16.1 and both options still passed to nodejs successfully, following expected behavior (no options out of 3 provided blocks any other)

**Comment by hexsprite** [comment]
Did you try `TOOL_NODE_OPTIONS` instead ? That is passed directly to the node that invokes the Meteor runner iirc...

**Comment by hexsprite** [comment]
Oops nevermind I think you wanted it during the build phase...

**Comment by sebakerckhof** [comment]
Ok, there are a couple of things going on here:
1. This is the normal node behavior, and happens before any Meteor code runs.
E.g. if you try: 
NODE_OPTIONS="--experimental-modules --input-type=module --es-module-specifier-resolution=node" /Users/User/.meteor/packages/meteor-tool/.1.9.2.1bpgp1k.xybn++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node

You will get the same error. Or if you download node (e.g. from https://nodejs.org/dist/v12.16.1/) and run: NODE_OPTIONS="--experimental-modules --input-type=module --es-module-specifier-resolution=node" ./node 

You will also get:
```
bad option: cannot use --es-module-specifier-resolution and --experimental-specifier-resolution at the same time
```

2. NODE_OPTIONS used to be an envar that didn't affect node and Meteor just invented this to pass along arguments, however, since Meteor 1.6 / Node 8, it has become a default node envar: https://nodejs.org/api/cli.html#cli_node_options_options

This is a bit of a problem, because now these options are also passed automatically to the process of Meteor tool, and not only the Meteor server app. So NODE_OPTIONS automatically also become TOOL_NODE_OPTIONS (and it also makes our parsing of the envar rather useless)

I guess we should rename NODE_OPTIONS envar to something else, like SERVER_NODE_OPTIONS or something.

3. Any particular reason you want to pass these envars? Since Meteor handles ES modules, it can also deal with .mjs files without using the native support. Is there a reason this doesn't work for you?
