### ISSUE TITLE
Aggregate with ObjectId

### ISSUE THREAD

**Issue by zhe1ka** [meteor/meteor#10966]
Hi,
Noticed that "aggregate" doesn't work with `ObjectId` as a value in `$match` despite it works well for any other kind of types. Could it be fixed?

![image](https://user-images.githubusercontent.com/6460571/76681336-9e487700-65fa-11ea-88b5-d58a9c65e57f.png)

**Comment by zhe1ka** [comment]
I've figured out that `Mongo.ObjectID` and `mongo.ObjectID` return different objects. If to use `mongo.ObjectID` inside the aggregating it works as expected

![image](https://user-images.githubusercontent.com/6460571/76682267-364a5e80-6603-11ea-9766-0d6bc730e177.png)

**Comment by cfnelson** [comment]
@zhe1ka Not sure if this will solve your issue, as I'm not sure if your question is asking for:

1. A different syntax for querying ObjectID's directly on Meteor mongo rawCollections or;
2. How can I access the raw npm mongodb driver's ObjectID instead of Meteor's own ObjectID's implementation which is implemented using the meteor/random pkg and doesn't behave exactly the same as the MongoDB nodejs driver.

Assuming that you're asking about the npm mongodb module and you're calling the aggregation on the server.

You can directly access/use the npm mongodb version that meteor is using if you import from Meteor's [npm-mongo](https://github.com/meteor/meteor/blob/devel/packages/npm-mongo/package.js). 

Not sure if this is the recommended way, but it's worked for me when I've wanted direct access.

```js
import { NpmModuleMongodb } from 'meteor/npm-mongo';
const _id = new NpmModuleMongodb.ObjectID();
``` 

`NpmModuleMongodb` provides everything that's exposed by the [Node.js driver API v3.5](https://mongodb.github.io/node-mongodb-native/3.5/api/) if you import like I've done in the example above. (Note: mongodb driver v3.5 is used by Meteor 1.9.3).
 
If you're curious what is happening then here is some old docs/warnings about [Direct Access to MongoDB driver](https://github.com/meteor/meteor/tree/devel/packages/mongo#direct-access-to-npm-mongodb-api which suggests a different way of accessing the npm pkg.
