### ISSUE TITLE
ecmascript@0.14.3

### ISSUE THREAD

**Issue by flean** [meteor/meteor#10988]
Going from ecmascript@0.14.2 to ecmascript@0.14.3 creates this bug in iOS
right after App Start
`Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service`

**Comment by filipenevola** [comment]
Hi @flean I have tested on a new app running `ecmascript@0.14.3` and it's working fine on iOS, I have tested on Safari directly as a web app and also as a native app.

Could you please provide a reproduction or more details about how are you getting this error and why do you think this is because of `ecmascript@0.14.3`?

**Comment by flean** [comment]
Yes, I’ll see how to reproduce. When I load the app in Xcode and run the simulator it just stays stuck. If I roll back it all works.
