### ISSUE TITLE
[1.10.1] Steady increase in server CPU and Memory consumption

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#11026]
Example pattern (please note the number of Sessions - 0). This is a standby no cron jobs project. It is exposed via a public URL and approximately 80 URL are being indexed for SEO (served from a Prerender server.)

Reported/discussed by multiple developers here: https://forums.meteor.com/t/steadily-increasing-cpu-on-meteor-v1-10-1/52517.

![Screen Shot 2020-04-15 at 20 32 12](https://user-images.githubusercontent.com/26188915/79634499-ce47e480-817b-11ea-8d89-a44c891d1716.png)

**Comment by sebakerckhof** [comment]
Do you know if also happened before 1.10.1?

**Comment by paulincai** [comment]
@sebakerckhof the shot was taken with 1.10.1. I believe 1.9.1 was still ok. I attach another shot (not too useful anyway) The drop in CPU utilization is a re-deploy of code.
![Screen Shot 2020-04-24 at 02 46 31](https://user-images.githubusercontent.com/26188915/80156987-46783500-85d6-11ea-8779-f6485206e318.png)

**Comment by skarborg** [comment]
Unfortunately I skipped 1.9 due to various factor including ironically Mongo client version. More below.

I switched to a blue/green deployment (with DNS failover) this week and see the same CPU increase over a matter of days across both nodes. The warm node is occasionally used for admin, but no user traffic. So I don't think it's a flaw in my app code.

BLUE/hot:
<img width="350" alt="Screenshot 2020-04-24 at 18 51 27" src="https://user-images.githubusercontent.com/6149354/80239655-e9759100-8660-11ea-815a-fa47c705e912.png">

GREEN/warm:
<img width="344" alt="Screenshot 2020-04-24 at 18 51 55" src="https://user-images.githubusercontent.com/6149354/80239652-e8dcfa80-8660-11ea-9253-47c64734b434.png">

I've attached the node js CPU profile [default.cpuprofile.gz](https://github.com/meteor/meteor/files/4530483/default.cpuprofile.gz) I took for 10min on the GREEN/warm host.  You can import into Chrome devtools but I've included a screenshot below.

My observations:

- Some timer seems to be running every 10 seconds. Mongo poll and diff? I'm using OPLOG though.
- A lot of the CPU time is spent in the npm-mongo package and specifically in processTicksAndRejections()

Not experienced analysing cpu profiles though so any input appreciated...

<img width="1278" alt="Screenshot 2020-04-24 at 19 20 28" src="https://user-images.githubusercontent.com/6149354/80239640-e4184680-8660-11ea-81bf-b49f6bb1d04c.png">

**Comment by chrishearn** [comment]
I'm also experiencing this issue with my app and currently investigating if this could be related to the Node v12 memory leak fix detailed here for the Mongo DB node driver - https://github.com/mongodb/node-mongodb-native/releases/tag/v3.5.5

As you can see the issue was fixed in v3.5.5, however latest version of Meteor is using v3.5.4 according to the change log.

**Comment by skarborg** [comment]
I think you are 100% on the money. After my CPU hit 10% during off peak I checked and it was still the npm-mongo package utilizing the bulk of the CPU. Just bigger spikes now.

**Comment by hexsprite** [comment]
@filipenevola sounds like an upgrade to Mongo node driver 3.5.5 is needed as Meteor uses the legacy topology types iirc.

**Comment by hexsprite** [comment]
There's some other potentially relevant fixes around session reuse in 3.5.7 as well.

**Comment by filipenevola** [comment]
Hi, I published `npm-mongo@3.7.1` and it uses `mongodb` `3.5.5` so if you run `meteor update` in your project it will update your `npm-mongo` version to `3.7.1` if you already running `3.7.0`.

Please let me know if this new version fixes this issue @paulincai @chrishearn @skarborg

**Comment by sebakerckhof** [comment]
@skarborg not every query is usable by the oplog driver. So meteor may decide for some queries to still use poll and diff.

We also noticed this memory increase. Will also report my findings, thanks for pointing out the mongo issue

**Comment by chrishearn** [comment]
@filipenevola thanks for updating the package so swiftly. I've deployed this and will monitor the metrics over the next couple of days then report back.

**Comment by rpesciotta** [comment]
@filipenevola thanks for the prompt update! I’ve got it deployed in prod, and will report if this fixes the continuous increase!

**Comment by paulincai** [comment]
2 days after the update, CPU sits at less than 1%. As mentioned initially, this is still a standby project, with almost no traffic so, within the same circumstances, I do not see that steady growth of CPU usage.
Will keep an eye on the memory for the next couple of days too. 


![Screen Shot 2020-05-08 at 22 49 33](https://user-images.githubusercontent.com/26188915/81438724-4489a680-917e-11ea-9d31-094793932164.png)

![Screen Shot 2020-05-08 at 22 49 33](https://user-images.githubusercontent.com/26188915/81439019-c4b00c00-917e-11ea-824c-2cff4cdf7a3e.png)

**Comment by filipenevola** [comment]
If you are still getting this issue you should run meteor update to update your npm-mongo as it seems npm-mongo@3.7.1 solves this issue!

**Comment by sebakerckhof** [comment]
Btw @filipenevola I was testing a clone with npm-mongo 3.5.7, which turns out to be fine and contains some additional fixes.

**Comment by skarborg** [comment]
Brilliant, thanks so much guys. This has sorted out the issues I was
facing. Bravo!

**Comment by skarborg** [comment]
I was maybe too hasty as I'm not so sure this is 100% solved for me yet... while it is much better than before I'm still seeing a steady but slow growth of CPU over time. Can anyone else confirm after the update?

![image](https://user-images.githubusercontent.com/6149354/86132475-36556800-bae7-11ea-8c14-0960755a6ba2.png)

**Comment by skarborg** [comment]
Much easier to see with new Digital Ocean graphs... The arrows are redeploys of app. I have migrated DB to Atlas since I thought the issue was fixed, maybe that's a consideration. Different DB version from mLab 🤔

From my Meteor versions file: npm-mongo@3.7.1

![image](https://user-images.githubusercontent.com/6149354/86212977-44ec5f80-bb79-11ea-98f7-3928a27d9ac5.png)
