### ISSUE TITLE
Single package tests in meteor core don't seem to work

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#11036]
I'm trying to run tests on some core meteor packages, but after following the docs, it seems like it doesn't work.

Steps:
1. Clone Meteor repo
2. Install dependencies `./meteor --help`
3. Run tests for a single packages: `./meteor test-packages mongo`

And then nothing happens. I'd expect the tests for that package to run and show something in my terminal, instead it logs `App running at ...:3000` and nothing else.

Maybe I'm missing something?

**Comment by delki8** [comment]
Hello @Floriferous, Meteor uses TinyTest. 
From the [docs](https://github.com/meteor/meteor/blob/devel/packages/tinytest/README.md#what-is-tinytest):
> Tinytest is the official Meteor package test runner.

The '[Executing the Tests](https://github.com/meteor/meteor/blob/devel/packages/tinytest/README.md#executing-the-tests)' section explains that tests results are presented on the browser at port 3000. That's why you're seeing   `App running at ...:3000` on your console, Meteor is telling you where you can see your test results. This is also mentioned inside the [development docs](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-tests-on-meteor-core).

So I believe this is not an issue :)

**Comment by Floriferous** [comment]
My bad, I was too used to seeing test results in my terminal 🤦‍♂️
