### ISSUE TITLE
[1.10.2] `meteor create app` fails with isopacket errors

### ISSUE THREAD

**Issue by teenangst** [meteor/meteor#11051]
I am unable to create an app, after using the app I get 2 errors:
```
PS C:\Users\x\source\Meteor> meteor create todos
Errors prevented isopacket load:
 
While loading isopacket `combined`:
C:\Users\x\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1170:25:
sourcemapConsumer.destroy is not a function
at
C:\Users\x\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1170:25
at Function.time
...

C:\Users\x\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^
 
Error: isopacket load failed?
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:320:11)
    at C:\tools\tool-env\isopackets.js:113:9
    ...
```
Whole error: https://pastebin.com/uGhVukea

I went to `C:\Users\x\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\fs\tools\fs\` to look for `files.ts` and the directory doesn't exist, but `C:\Users\x\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\tools\fs\` does, with `files.js` inside with no `files.ts`. I also get this error for other actions such as `update` and `show`

I have installed 1.10.1 as well and I get the same issue again

Running on Windows 10 64

**Comment by teenangst** [comment]
I tried running it on my laptop and I got a different error, but still on the same line as the second error `node_modules\meteor-promise\promise_server.js:218`

![unknown](https://user-images.githubusercontent.com/30373155/81501016-d3590900-92cd-11ea-8586-f4f0ef90e205.png)

**Comment by teenangst** [comment]
I see, Meteor is a dead project and I can't expect a response.

**Comment by filipenevola** [comment]
Hi, we have tested and it's working fine on Windows.

Have you tested in a fresh installation? 

```
 C:\Users\Denyhs\Documents>meteor create app-test
 Created a new Meteor app in 'app-test'.
 
 To run your new app:
   cd app-test
   meteor
 
 If you are new to Meteor, try some of the learning resources here:
   https://www.meteor.com/tutorials
 
 When you're ready to deploy and host your new Meteor application, check out Galaxy:
   https://www.meteor.com/hosting
 
 To start with a different app template, try one of the following:
 
   meteor create --bare       # to create an empty app
   meteor create --minimal    # to create an app with as few Meteor packages as possible
   meteor create --full       # to create a more complete scaffolded app
   meteor create --react      # to create a basic React-based app
   meteor create --typescript # to create an app using TypeScript and React
 
 
 C:\Users\Denyhs\Documents>cd app-test
 
 C:\Users\Denyhs\Documents\app-test>meteor npm install && meteor npm start
 audited 617 packages in 1.708s
 found 0 vulnerabilities
 
 
 > app-test@ start C:\Users\Denyhs\Documents\app-test
 > meteor run
 
 [[[[[ C:\Users\Denyhs\Documents\app-test ]]]]]
 
 => Started proxy.
 => Started MongoDB.
 => Started your app.
 
 => App running at: http://localhost:3000/
    Type Control-C twice to stop.
```

**Comment by teenangst** [comment]
Yes, multiple times

**Comment by delki8** [comment]
Hey @teenangst could you help me out with this? I'm not a Windows user, and tried the following:
- installed a Windows 10 x64 on a virtual machine using virtual box
- installed chocolatey following these instructions: https://chocolatey.org/install
- installed meteor using `choco install meteor`
- opened a simple cmd and typed `meteor create my app` -> `cd myapp` -> `meteor`
- Meteor couldn't start due to some weird Mongo errors (#10036) but [this comment](https://github.com/meteor/meteor/issues/10036#issuecomment-416485306) helped me
- after those Mongo errors were gone `meteor` worked as expected and the app was running on port 3000
- uninstalled Meteor and tried to install it again from within a PowerShell without admin privileges (didn't know that PowerShell was a thing) but the installation couldn't be completed due to the lack of privileges to write to some directories


is there anything else you could share to help me reproduce this bug you're facing?

**Comment by iBeACoder** [comment]
I have been having the same problem updating or create any of my projects on my Windows 10 64-bit machine. I have mentioned it on #10930 the seems to be originating from:

`tools/fs/files.ts` **on line 1170**

as far as I know.

I have tried to go find more about the error and you can see as mentioned in my comment: https://github.com/meteor/meteor/issues/10930#issuecomment-613324152. If you have any idea as to where the issue is originating let me know. I am sure there a few people stuck on it. And not being able to get the latest version is a problem. I am stuck on version 1.8.3

**Comment by iBeACoder** [comment]
Hi @teenangst, @filipenevola & @delki8 I found a potential solution check out https://github.com/meteor/meteor/issues/10930#issuecomment-630721277 I am not sure how to test out and or fix meteor repo but this seems to do the trick for my local machine. It might help you get started and running again @teenangst and perhaps someone who can fix the code on the repo can take a look at the files mentioned on the comment see if it can be a permanent fix.

**Comment by filipenevola** [comment]
Let's focus here https://github.com/meteor/meteor/issues/10930 as this looks like the same problem.

**Comment by dsten32** [comment]
I had a similar issue and this solved it:
https://forums.meteor.com/t/solved-upgrade-1-10-2-problem-or-i-am-not-sure/52990/2

May or may not someone else
