### ISSUE TITLE
Meteor update issue from 1.6.1 to 1.9.3

### ISSUE THREAD

**Issue by harmansingh2908** [meteor/meteor#11141]
** meteor update --release 1.9.3 **

**printing this error on console:**
tester git:(wnzl_dev_drop_20-4) ✗ meteor update --release 1.9.3 

**/Users/hussain/.meteor/packages/meteor-tool/.1.9.3.1va0bh.1jr3w++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node[2850]: ../src/node_contextify.cc:649:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
[1]    2850 abort      meteor update --release 1.9.3**

How I can solve this error, please help

**Comment by jaydeebee** [comment]
I ran into that recently, in an upgrade from 1.8.x to 1.10.2.  In my case, it was one of the meteor packages causing it. I was able to identify which by creating a new project, copying in my .meteor/packages and .meteor/versions files, then removing packages one-by-one until the culprit identified.

If you haven’t already, be sure to remove/let it rebuild node_modules.

**Comment by harmansingh2908** [comment]
@jaydeebee  Thanks for quick reponse.
I am using **less** package and this line causing issue. 
const less = Npm.require('less');

Specially **less** package.

**Comment by jaydeebee** [comment]
Hm I think that was the problem package for me as well, and it looks like I went from less 2.7.11 to 2.8.0.  Try that?

**Comment by harmansingh2908** [comment]
@jaydeebee  Still getting same error,

**Comment by jaydeebee** [comment]
Ah, darn, sorry for the misleading idea, then. The other thing i had updated in that commit was meteor-node-stubs.  i had updated from 0.4.x(!) to 1.0.0, but a 1.0.1 (with security fixes!) was released since then. If you haven’t already, that update is also likely worth a try too.

To be honest, I’m just looking at my git history, I’m not 100% sure if I’m looking at the right commit (in fact, my notes are pretty clear that I replaced a Meteor package, not an NPM, and meteor-node-stubs is npm, where less is a meteor package).  It was all part of a larger effort, and the details are a bit hazy already.

The way I’d tracked it down was to create an an empty/basic demo repo, added the same packages as my problem repo, then removed packages one-by-one until it worked again.  Once it did, I had a thread to follow.

I’d commented to a friend at the time:

```
i have determined that it's caused by some meteor package (not an npm package). so my way to divine which is,

$ cd .meteor
$ while ! meteor run ;do meteor remove $(tail -1 < packages);done

Delete packages until it stops crashing so much.
```

(That snippet will be a little quirky if you have comments in your .meteor/packages file, so you may have to do it more manually)

**Comment by jaydeebee** [comment]
Ah, one thing I just noticed is that I was having problems with `meteor run`, post-upgrade, where you’re having issues with the upgrade itself.  So I might be on the wrong path here.

**Comment by harmansingh2908** [comment]
@jaydeebee  Thanks! I am able to remove the issue, There is .npm folder inside bootstarp package. I have delete that build is working fine.
