### ISSUE TITLE
we use rocket.chat (with meteor) met an issue(message delay sometimes),we don't know how to resove it,please give us a hand...

### ISSUE THREAD

**Issue by codeneno** [meteor/meteor#11184]
Actual behavior:
Server Setup Information:
Version of Rocket.Chat Server: 3.3.3
Operating System: ubuntu
Deployment Method: docker
Number of Running Instances: 18
DB Replicaset Oplog: enabled
NodeJS Version: v12.16.1
MongoDB Version:4.2.1
Client Setup Information
Desktop App or Browser Version: chrome 81
Operating System: windows
Additional context
sometimes ,some people told us their send message in a room or direct message will be delayed more than 100 senconds

**Comment by codeneno** [comment]
we have olny one (DISABLE_PRESENCE_MONITOR=NO),It should have nothing to do with this, right?
we don't know how to resolve it too,Is it related to Meteor and MongoDB's OPLOG?

**Comment by codeneno** [comment]
anybody?

**Comment by StorytellerCZ** [comment]
Are you using Redis Oplog? This might be better suited for Rocket.chat then here unless it is related to a specific Meteor issue.

**Comment by codeneno** [comment]
NO we are using meteor ,and the bug was reported by Meteor's code

**Comment by StorytellerCZ** [comment]
@codeneno If you have an actual error message then please provide it, because right now the only thing you have told us that sometimes some users experience delay and pointed to Rocket.Chat configuration option. That is why I have suggested to ask people at [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) first as they are the experts on how Rocket.Chat works and what settings can be tweaked to potentially remedy the situation.
Without more information about your app setup, the errors/issues you are running into I can only guess wildly.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while and it's not clear if this issue is on Meteor or not.
