### ISSUE TITLE
`Meteor.user()` and `Meteor.userId()` not reactive with Svelte using `useTracker`

### ISSUE THREAD

**Issue by probablykasper** [meteor/meteor#11259]
I'm trying to show the user different content based on whether the user is logged in. According to the [Svelte guide](https://www.meteor.com/tutorials/svelte/adding-user-accounts), the following should work for this:
```js
$: currentUser = useTracker(() => Meteor.user());
```

However, when I do this, `currentUser` is just set to an object with a `subscribe` function, and this never changes, even when `Meteor.user()` returns `null` or a user object later on.

Reproduction repo: https://github.com/probablykasper/meteor-usetracker

Meteor 1.12
macOS 10.14.6

**Comment by filipenevola** [comment]
Hi, the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.

If you really believe this is a bug in the Svelte tutorial you can open the bug here https://github.com/meteor/simple-todos-svelte
