### ISSUE TITLE
[1.12] Cordova chooses different version of NPM module than other web platforms

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#11272]
This problem is showing up when using `@fullcalendar/react` in Meteor.

The reproduction will show that in Cordova it doesn't load the CSS. It seems to be because in the Cordova code it is using the CJS version, whereas the other web platforms are not.

https://github.com/hexsprite/meteor-fullcalendar-cordova

This is in Cordova
![image](https://user-images.githubusercontent.com/23538/103045878-0d181080-453b-11eb-8647-fcba02182196.png)

This is in iOS Safari on the same simulator

![image](https://user-images.githubusercontent.com/23538/103045890-1dc88680-453b-11eb-874e-8d1eb280db05.png)

**Comment by filipenevola** [comment]
Hi @hexsprite this issue is happening only on Meteor 1.12?

**Comment by hexsprite** [comment]
I also tried downgrading to 1.11 but didn't try past versions.

**Comment by filipenevola** [comment]
I'm not sure but by your explanation but this could solve this issue as well https://github.com/meteor/meteor/pull/11290

What do you think @hexsprite ?

**Comment by hexsprite** [comment]
@filipenevola I've tested the repro with Meteor 2.0 and still having the same problem.

I tried both: `legacy` and `["client"]` for the `meteor.nodeModules.recompile` options:

```
    "nodeModules": {
      "recompile": {
        "@fullcalendar/common": "legacy",
        "@fullcalendar/daygrid": "legacy"
      }
    }
```

Still chooses the wrong entry point when running in Cordova but works fine in mobile browser in the simulator.

**Comment by filipenevola** [comment]
Hi @hexsprite I was checking your reproduction and it seems Meteor is recompiling your node modules as expected but I believe fullcalendar is not working in old browser even if the JS is compatible with it.

See my screenshot:

<img width="1841" alt="meteor-fullcalendar-cordova – ~:Documents:meteor:ws:tests:meteor-fullcalendar-cordova: meteor:local:build:programs:web cordova:… 2021-03-17 14-51-40" src="https://user-images.githubusercontent.com/437372/111522316-85ecca00-8730-11eb-8e33-0a3607fd2588.png">

The code was compiled differently but see that on IE11 I also get the same behavior:

<img width="889" alt="Dashboard 2021-03-17 14-52-26" src="https://user-images.githubusercontent.com/437372/111522365-900ec880-8730-11eb-89a4-d5f62383e79b.png">

Then the problem is not the code not being compiled correctly, the problem is that the lib is not working as expected on legacy browser.

Does that make sense?

That is why it works on Safari (as it gets the modern version) and it doesn't in the WebView (as it  gets the legacy version).

**Comment by hexsprite** [comment]
Thanks for the bump. It seems like it's working as currently designed -- Cordova uses legacy and Mobile Safari uses the modern bundle. And I have a workaround. There still may be an issue with how it imports the CJS but I'll reopen if necessary....

**Comment by tpmh31292** [comment]
> Thanks for the bump. It seems like it's working as currently designed -- Cordova uses legacy and Mobile Safari uses the modern bundle. And I have a workaround. There still may be an issue with how it imports the CJS but I'll reopen if necessary....

Would you be able to show your workaround?

I'm having the same issue.

**Comment by hexsprite** [comment]
I just imported the css directly

import ***@***.***/common/main.css'
import ***@***.***/daygrid/main.css'
import ***@***.***/timegrid/main.css'


Jordan
