### ISSUE TITLE
Meteor 1.12 bare empty project crashes when installing faker 5 npm module

### ISSUE THREAD

**Issue by Nidroide** [meteor/meteor#11273]
OS: ubuntu 20.04 and 18.04
Faker version: 5.1.0
Step to reproduce:
```
meteor create --bare test
cd test
meteor npm install -S faker
meteor
```
this brings to:
```
...
/home/user/.meteor/packages/static-html/.1.2.2.17noaev.cf7q++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (/home/user/.meteor/packages/static-html/.1.2.2.17noaev.cf7q++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:284:11)
   at CachingHtmlCompiler.processFilesForTarget (packages/caching-html-compiler/caching-html-compiler.js:40:5)
...
=> Your application has errors. Waiting for file change.
=> Started MongoDB.   
...
```
The environment then sometimes breaks and running meteor again may brings to a segfault:
```
meteor
[[[[[ ~/test ]]]]]                            

=> Started proxy.                             
Segmentation fault (core dumped)             -
```

Note: no source code added in the project nor other npm modules, uninstalling faker make the project build again.
There is a open issue on Faker.js repository, but I guess the problem needs to be investigated here too as may happen with other modules too. P.s. why does meteor process in some way a module not imported in the app source code?

References: https://github.com/Marak/faker.js/issues/1066

**Comment by filipenevola** [comment]
Hi, we need to understand what Faker is using that other npm modules are not.

We need more information here as it is not a problem in Meteor itself but maybe something that is different in Faker that Meteor would need to adapt or Faker would need to change.

Also, we need to understand how many users of Faker + Meteor we do have then we can prioritize accordingly. It's impossible for us to analyze and eventually fix problems caused by different libs as each author can do whatever they want inside the library.

**Comment by aureooms** [comment]
I had the same problem back in August 2020 and did not investigate further. I was using meteor 1.10.2 at the time and I was trying to upgrade to the newest version of meteor. Today I managed to get meteor 2.0 running successfully after removing the faker dependency (faker 5.1.0).

**Comment by aureooms** [comment]
Version 5.0.0 of faker was released on August 23rd 2020. I can't remember if I tried to upgrade before or after that and if I tried to upgrade meteor and faker simultaneously.

**Comment by aureooms** [comment]
Yesterday, I noticed that the build goes through if you do not have `blaze-html-templates` or `static-html` installed. I was just moving from `blaze-html-templates` to `static-html` (trying to fix the problem) and tried to run the server ater removing `blaze-html-templates` before installing `static-html`. The build went through but I had to add `static-html` because `React` complained about the render element not being there.

With `blaze-html-templates` I eventually got a similar error log to https://github.com/meteor/meteor/issues/11273#issue-778065546 but mentioning `templating-compiler` rather than `static-html`.

**Comment by StorytellerCZ** [comment]
@Nidroide Tried to replicate your approach, but did not run into any issues.
@make-github-pseudonymous-again There have been few updates recently. Can you check if the problem still persist and if yes provide a reproduction? Thank you!

**Comment by make-github-pseudonymous-again** [comment]
I believe this was fixed yes. Let me fetch the source.

**Comment by make-github-pseudonymous-again** [comment]
Here https://github.com/Marak/faker.js/issues/1066#issuecomment-784108391. Fixed for me since Feb 23.
