### ISSUE TITLE
Why always prompt me to download meteor-tools

### ISSUE THREAD

**Issue by xuguotong** [meteor/meteor#11309]

**Comment by filipenevola** [comment]
Hi, this issue is incomplete.

It this was a question: the best place to ask questions is in the [Forums](https://forums.meteor.com) or in our [Community Slack](https://join.slack.com/t/meteor-community/shared_invite/enQtODA0NTU2Nzk5MTA3LWY5NGMxMWRjZDgzYWMyMTEyYTQ3MTcwZmU2YjM5MTY3MjJkZjQ0NWRjOGZlYmIxZjFlYTA5Mjg4OTk3ODRiOTc).

Please send this question there and I'm sure you are going to get some help.
