### ISSUE TITLE
Deprecate browser policy packages

### ISSUE THREAD

**Issue by harryadel** [meteor/meteor#11424]
The official guide no longer recommends browser policy and recommends helmet instead. https://guide.meteor.com/security.html#httpheaders
So, should it be deprecated like HTTP package https://github.com/meteor/meteor/pull/11161?

**Comment by StorytellerCZ** [comment]
That is a good discussion point. I'm split on this. I do agree that solutions like `helmet` are a great replacement, but at the same time I think with a bit of care we could improve these packages to utilize `helmet` or do things themselves and due to their unique integration with Meteor it could easily provide some security that otherwise is annoying to setup. The main thing afterwards is their continuous management.

**Comment by harryadel** [comment]
>same time I think with a bit of care we could improve these packages to utilize helmet or do things themselves and due to their unique integration with Meteor it could easily provide some security that otherwise is annoying to setup. The main thing afterwards is their continuous management.

If we were to have browser policy use Helmet internally or even develop it to achieve a similar level as Helmet, it'd be a reinvention of the wheel and an unwise investment of resources unless the tight Meteor integration offers quite a unique value that can't be achieved otherwise. Although, if such claims were true Helmet integration wouldn't have been so seamless. Also, given the current state of Meteor with the removal of old compatibility code https://github.com/meteor/meteor/pull/11395 the current atmosphere :smile: is in favor of of deprecating unused code/packages in order to slim Meteor down and keep it nimble for future work. https://github.com/meteor/meteor-feature-requests/issues/392

I'm not really trying to enforce my opinion but the odds of keeping it aren't high.

**Comment by StorytellerCZ** [comment]
I'm up for investigating if there is something non-trivial that we could use the package for. I remember that a while back when I was investigating Helmet I decided that I could just do without it and use the raw WebApp handlers, but then there was something that was non-trivial that I couldn't achieve even with Helmet even though Helmet had functionality for it, as it required additional integration elsewhere in Meteor. So for cases like this if we could re-purpose the library that would be awesome, but I will have to do more investigation.

**Comment by jankapunkt** [comment]
We could make browser policy an optional out-of-the-box (zero-) config for helmet, keeping the api the same but use helmet under the hood. If that makes any sense. However, note, that these decisions were already made in the past and then (now) turned out to be very close coupled to a technology that is now outdated (similar to the http or jquery package).

From a beginners perspective I love the zero-config way of adding working code with few experience required.
From an enterprise perspective flexibility and long-term maintainability is king.

**Comment by harryadel** [comment]
https://github.com/meteor/meteor/issues/9689#issuecomment-367773413

**Comment by StorytellerCZ** [comment]
Closing this in favor of this discussion: https://github.com/meteor/meteor/discussions/11591
