### ISSUE TITLE
Meteor.LoginWithPassword will cause a subscribe twice?

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#11473]
is this a bug and why publish are called twice?

reproduction

https://github.com/crapthings/pubtwice

```sh
git clone https://github.com/crapthings/pubtwice
cd pubtwice
meteor npm i
meteor
```

```js
Meteor.loginWithPassword('demo', 'demo')
Meteor.subscribe('test')
```

```js
Meteor.startup(function () {
  if (Meteor.users.findOne()) return

  Accounts.createUser({
    username: 'demo',
    password: 'demo',
  })
})

Meteor.publish('test', function () {
  console.log(this._name)
})
```

**Comment by jamesloper** [comment]
The reason your publication function is going to run twice because of where the subscription is placed. In a web app such as with meteor or many frameworks, the user is actually logged out initially. Logging in happens over the network, quickly after page open. You appear to be subscribing in a logged out state, so you will get one console log. Eventually the app will log in, this will cause the subscription to be invalidated, and get rerun, so you will get a second console log. You'll understand better if you put a `console.log(this.userId)` in there. Anyways, the solution is to subscribe only after you have logged in.
