### ISSUE TITLE
 Could not find mainModule for 'web.browser' architecture: client/main.jsx use --minimal demo

### ISSUE THREAD

**Issue by snowwolfjay** [meteor/meteor#11622]
just use meteor create app --minimal and then build
-----
system win10
meteor 3.2.5
_____
Errors prevented bundling:
While building the application:
```
error: Could not find mainModule for 'web.browser' architecture: client/main.jsx
Check the "meteor" section of your package.json file?
error: Could not find mainModule for 'web.browser.legacy' architecture: client/main.jsx
Check the "meteor" section of your package.json file?
```
----
> tried add web.browser and legacy, not work, but js project why need jsx?

**Comment by StorytellerCZ** [comment]
Hi @snowwolfjay can you please copy here the content of `package.json`

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while and weren't able to reproduce the issue.

**Comment by snowwolfjay** [comment]
This issue will happen when install meteor-client-bundle at the same directory, need use another folder pack client - code then things go well

**Comment by StorytellerCZ** [comment]
Hi @snowwolfjay I don't follow, can you please provide a reproduction of the issue.

**Comment by JanvanCasteren** [comment]
I can reproduce this issue.

I encountered it while trying to use meteor-client-bundler (Just like @snowwolfjay did).

The issue can be reproduced as follows:

create new Meteor app:
`meteor create myapp`

cd into myapp folder and run build
`meteor build `

meteor build runs without problem 

Now remove 'ecmascript@0.16.6' package from the .meteor/packages file.

run `meteor build` again.

Now you get this error:
```
Errors prevented bundling:                    
While building the application:               
error: Could not find mainModule for 'web.browser' architecture: client/main.jsx
Check the "meteor" section of your package.json file?
error: Could not find mainModule for 'web.browser.legacy' architecture: client/main.jsx
Check the "meteor" section of your package.json file?
```

The error message doesn't make sense, because the mainModule section in package.json is correct and the file client.main.jsx is in place. 

Instead the error message should be something like:
`Please include ecmascript script package if you want to use react client.`

Anyway, my problem is solved because I realised that i have to include the ecmascript package in my client bundle. But it would be good I think if this situation is handed with a better error message.

**Comment by JanvanCasteren** [comment]
strange enough, I still get the error when building through meteor-client-bundler, even if I include ecmascript package

**Comment by Grubba27** [comment]
This is mostly a missing docs issue + better explanation of why you need ecmascript package. 
As it enables the latest features of your client app, It does not comment anything about using [JSX in the docs](https://docs.meteor.com/packages/ecmascript.html).
This happens probably because it is trying to import the files using `import` instead of `require` or using an ES6 feature, and because it does not have this functionality without the package, it throws an error. I agree that the error message should be better.

**Comment by aakashsharma7** [comment]
@snowwolfjay can i resolve this?

**Comment by nachocodoner** [comment]
Closing this in favor of a proper reproduction on Meteor 3.x. The Meteor 2.x reproductions shared here may no longer be accurate after the many changes and improvements in the Meteor build stack, including updates to web architecture handling that may have already resolved some of these cases.
