### ISSUE TITLE
Seemingly random version constraints from local Atmosphere packages

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#11746]
While attempting to update to latest Meteor, the Meteor tool complained that two of my local packages had incompatible version constraints.

However, they had none. The dependency for `accounts-base` was defined without any version requirement whatsoever.

```
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint accounts-base@1.4.4 is not satisfied by accounts-base
2.2.0.
Constraints on package "accounts-base":
* accounts-base@~2.2.0 <- top level
* accounts-base@2.2.0 <- service-configuration 1.3.0
* accounts-base@2.2.0 <- accounts-password 2.2.0
* accounts-base@1.4.4 <- arggh:test-utils 0.0.1
* accounts-base@1.6.0 <- arggh:wormhole 0.0.1
```

I then proceeded to declare those dependencies in mu packages with the version requirement `2.2.0`, after which the Meteor update completed succesfully.

The operating system you're running Meteor on: Mac OS 11.6

**Comment by filipenevola** [comment]
Hi @arggh could you provide your `.meteor/packages` file and `.meteor/release` file?

I see that the problem was because of `arggh:wormhole`:

`accounts-base@1.6.0 <- arggh:wormhole 0.0.1`

So it should still be a problem, unless you have changed something in this package.

Core packages are defined by the version of Meteor, so even if you don't declare a version they are going to respect the version published with your current Meteor version.

**Comment by StorytellerCZ** [comment]
@arggh Just quickly looking at the constraints, you might need to update `arggh:test-utils` and `arggh:wormhole` to have `api.versionsFrom('2.3')` if you have that in you packages. Depending on the age of the packages you might or might not have that. Good idea to add it though.

**Comment by arggh** [comment]
Thanks @StorytellerCZ, bumping `api.versionsFrom` resolves the issue. Maybe this is something that could be improved, documentation or error message wise?
