### ISSUE TITLE
Incorrect class transpilation since v2.2.3

### ISSUE THREAD

**Issue by zendranm** [meteor/meteor#11793]
Classes aren't correctly transpiled since version 2.2.3. Up to version 2.2.2 the code below returns `test` and `test`. Since version 2.2.3 it returns `test` and `undefined`.

Reproduction:
```
class X {
  a: any;
  constructor() {
    this.a = 'test';
  }
}

class Y extends X {
  a: string;
}

console.log((new X()).a)
console.log((new Y()).a)
```
Repository with basic reproduction: https://github.com/zendranm/class-transpilation-bug/blob/main/imports/ui/App.tsx

**Comment by radekmie** [comment]
Can we have some eyes on it? It’s something that actually broke our project on migration and may affect others.

**Comment by filipenevola** [comment]
Hi @radekmie sure.

Meteor transpiles code using other libraries.

The version 2.2.3 indeed [changed](https://docs.meteor.com/changelog.html#v22320210812) some things that could affect that, as such Babel and Typescript.

Did you try to find the issue a similar issue in Babel or Typescript so we could understand the root cause of this problem?

Do you also confirm that this problem starts to occur in Meteor 2.2.3?

**Comment by radekmie** [comment]
If I recall correctly, it started exactly in 2.2.3 and we haven’t found anything related to it in Babel nor TypeScript. @zendranm, @wadamek65 could you confirm?

**Comment by wadamek65** [comment]
@filipenevola @radekmie When I investigated this I was unable to reproduce it on any version of TypeScript nor Babel (past ones and latest ones). I also checked TS-related Babel plugins and was unsuccessful. The only thing that I didn't investigate was meteor-specific packages and configuration so I suspect this issue is specific only to meteor.

**Comment by zendranm** [comment]
@filipenevola @radekmie As for my investigation I can confirm - it looks like meteor specific. It starts to occur in Meteor 2.2.3.

**Comment by JanMP** [comment]
@radekmie are you talking about https://github.com/vazco/uniforms/issues/1084 ? I just tried 2.7-beta.2 and it's still broken.

**Comment by radekmie** [comment]
@JanMP No, this is something completely different.

**Comment by zendranm** [comment]
Problem still present in meteor v2.6.1

**Comment by zendranm** [comment]
@renanccastro @filipenevola Since the problem wasn't solved by the new release, are there any other suggestions?

**Comment by zendranm** [comment]
@fredmaiaarantes @zodern Since the problem is still present, can we have some eyes on it?

**Comment by fredmaiaarantes** [comment]
> @fredmaiaarantes @zodern Since the problem is still present, can we have some eyes on it?

Hey @zendranm, I think that @denihs has made some tests on this recently. 
Denilson, do you have something to share about it?

**Comment by denihs** [comment]
I think the one you're referring to is that problem we had with Terser. 

I did check on this, and yes, the problem exists, so we have to work on it.

**Comment by afrokick** [comment]
thanks to @radekmie I found this issue and can report that the issue was appeared because of https://github.com/microsoft/TypeScript/issues/34787#issuecomment-849379479 (TSConfig `useDefineForClassFields = true` for ESNext by default from TS4.3)

I think we should set `useDefineForClassFields = false` here https://github.com/meteor/babel/blob/master/index.js#L149

**Comment by zendranm** [comment]
@afrokick Thank you for the workaround and the explanation.
