### ISSUE TITLE
I am able to download json data in csv format in meteor app. But I can't download in xls format. I want to export json data in xls format in Meteor application.

### ISSUE THREAD

**Issue by zehrademirel** [meteor/meteor#11857]

**Comment by StorytellerCZ** [comment]
Hi @zehrademirel for questions like this please use the [Meteor Forums](https://forums.meteor.com). GitHub issues are for tracking bugs and features in Meteor itself.
As for your question, more information will be needed in order to assist you. Are you trying to just get data from the DB, or is this in your application? What is your current implementation to get the data in cvs format? In either case to get the data into xls format you will need to find an appropriate package that is going to take the raw data (most likely in json) and make xls file out of it.

**Comment by zehrademirel** [comment]
It would be very helpful if there is a sample application created with xls.
