### ISSUE TITLE
Minimongo's projection compatibility regression

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#11855]
This PR introduced a bug in how projection is computed in comparison with the server:

https://github.com/meteor/meteor/pull/10499

If you run the test against MongoDB proper, you see the original results, not results as changed in PR:

```
$ docker run --rm -d --name mongo mongo:latest
$ docker exec -t -i mongo mongo
> db.test.insert({
...     setA: [{
...       fieldA: 42,
...       fieldB: 33,
...     }, {
...       fieldA: 'the good',
...       fieldB: 'the bad',
...       fieldC: 'the ugly',
...     }],
...     setB: [null, {
...       anotherA: { },
...       anotherB: 'meh',
...     }, null, {
...       anotherA: 1234,
...       anotherB: 431,
...     }, null],
...   });
> db.test.find().pretty()
{
	"_id" : ObjectId("61e30b2a3361d28a6bdff138"),
	"setA" : [
		{
			"fieldA" : 42,
			"fieldB" : 33
		},
		{
			"fieldA" : "the good",
			"fieldB" : "the bad",
			"fieldC" : "the ugly"
		}
	],
	"setB" : [
		null,
		{
			"anotherA" : {
				
			},
			"anotherB" : "meh"
		},
		null,
		{
			"anotherA" : 1234,
			"anotherB" : 431
		},
		null
	]
}
> db.test.find({}, { 'setA.fieldA': 1, 'setB.anotherB': 1 }).pretty()
{
	"_id" : ObjectId("61e30b2a3361d28a6bdff138"),
	"setA" : [
		{
			"fieldA" : 42
		},
		{
			"fieldA" : "the good"
		}
	],
	"setB" : [
		{
			"anotherB" : "meh"
		},
		{
			"anotherB" : 431
		}
	]
}
```

As you see, no `null` values in the result.

I discovered this because [for my package](https://github.com/peerlibrary/meteor-reactive-mongo) I run [minimongo tests against real MongoDB](https://github.com/peerlibrary/meteor-reactive-mongo/blob/master/tests_prepare.js). As you see in that file, I have to disable many tests because they fail on MongoDB proper. I find this pretty sad. I think it would be really beneficial if Minimongo tests would run against MongoDB. There are few known extensions (like sorting by providing a function, etc.) but for most of the things we want full compatibility. Which is currently not so. I have opened an issue for this [quite some time ago](https://github.com/meteor/meteor-feature-requests/issues/33).

**Comment by DonJGo** [comment]
Hello there,

Just wanna to jump in as this issue seems pretty related to the one we have on our side.
I'm not sure our problem is related to this opened issue but the topic fits well with our it.

We just updated our Meteor project to the last 2.6 version (to support futur mongo5 update)
And we encounter an issue related to minimongo 1.8.0

I paste you the error here : 
`Exception from sub front-subscription id ******* MinimongoError: Minimongo doesn't support operators in projections yet.
I20220210-16:40:47.741(1)?     at MinimongoError (packages/minimongo/common.js:1087:17)
I20220210-16:40:47.742(1)?     at packages/minimongo/local_collection.js:847:13
I20220210-16:40:47.742(1)?     at Array.forEach (<anonymous>)
I20220210-16:40:47.742(1)?     at Function.LocalCollection._checkSupportedProjection (packages/minimongo/local_collection.js:834:23)
I20220210-16:40:47.742(1)?     at Function.LocalCollection._compileProjection (packages/minimongo/local_collection.js:868:19)
I20220210-16:40:47.742(1)?     at new OplogObserveDriver (packages/mongo/oplog_observe_driver.js:94:40)
I20220210-16:40:47.742(1)?     at MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1385:21)
I20220210-16:40:47.742(1)?     at MongoConnection.mongoConnectionProto._observeChanges (packages/mdg:meteor-apm-agent/lib/hijack/wrap_observers.js:164:38)
I20220210-16:40:47.743(1)?     at Cursor.observeChanges (packages/mongo/mongo_driver.js:993:22)
I20220210-16:40:47.743(1)?     at Cursor.cursorProto.<computed> (packages/mdg:meteor-apm-agent/lib/hijack/db.js:131:32)
I20220210-16:40:47.743(1)?     at Cursor.kadira_Cursor_observeChanges [as observeChanges] (packages/mdg:meteor-apm-agent/lib/hijack/set_labels.js:84:41)
I20220210-16:40:47.743(1)?     at Function._publishCursor (packages/mongo/collection.js:412:32)
I20220210-16:40:47.743(1)?     at Cursor._publishCursor (packages/mongo/mongo_driver.js:956:27)
I20220210-16:40:47.743(1)?     at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1164:13)
I20220210-16:40:47.744(1)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1136:12)
I20220210-16:40:47.744(1)?     at Subscription.subscriptionProto._runHandler (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:12:24)
I20220210-16:40:47.744(1)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:917:9)
I20220210-16:40:47.744(1)?     at Session.sub (packages/ddp-server/livedata_server.js:673:12)
I20220210-16:40:47.744(1)?     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:77:34
I20220210-16:40:47.745(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220210-16:40:47.746(1)?     at Session.sessionProto.protocol_handlers.sub (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:76:44)
I20220210-16:40:47.746(1)?     at packages/ddp-server/livedata_server.js:603:43`

This error comes from a publish method that do something like this :
`
collection.find({}, {
  fields: {
    myArray : {
        $slice : -1
    }
})
`

This was working well for us on the previous version of Meteor (2.5.3) and minimongo (1.7.0)

I don't know if we've done something wrong or if it is a real issue from minimongo side.
That's the reason why i would like to have your feedback on this.

Thanks by advance for your advices ;)

**Comment by renanccastro** [comment]
@DonJGo your issue is legit and it's fixed in this [PR](https://github.com/meteor/meteor/pull/11908). 
We will ship a patch of the mongodb package asap. Let's follow in this [link](https://github.com/meteor/meteor/pull/11908) for not polluting @mitar's thread

-------

It would be great if the original owner of the PR @maxnowack could chime in, but I'm not sure if he is still around.

@mitar as for your suggestion, I agree it's important to test minimongo against the server and a discussion would surely help this get more traction.

**Comment by DonJGo** [comment]
Ok thanks for your quick answer, will stay tuned to see when the PR is merged.

**Comment by denihs** [comment]
As this issue was already solved on this [PR](https://github.com/meteor/meteor/pull/11908), I'm closing it now.

**Comment by mitar** [comment]
@denihs I think part of this issue was also to run Minimongo tests against MongoDB proper to make sure no such regressions happen again.
