### ISSUE TITLE
2.6: applySkipLimit is permanently enabled on all mongo cursor count() calls

### ISSUE THREAD

**Issue by tonymckendry** [meteor/meteor#11921]
### Last version showing the problem: 
Version 2.6

### Last version where problem did not occur: 
Any version pre-2.6

### OS: 
Ubuntu 

### Expected Behavior: 
<cursor>.count() should return the total number of documents found by the cursor's query without taking into account the `skip` or `limit` in the options. This was extremely helpful for things like pagination. Mongo offers an `applySkipLimit` parameter to `count` which applies the skip and limit values to the count. 

### Actual behavior: 
Post-2.6, count returns only the number of documents post-skip-and-limit. There is no way to determine the number of documents that the query would return without doing an additional query. 

### Explanation: 
Historically, I have used the following function on my backend to grab a paginated set of data from a given collection in my DB. 
The `count()` function on the cursor always used to give me the total number of documents that matched the query regardless of the `skip` and `limit` options, but now it seems like I'm only getting back the post-limit count. 

The 2.6 migration notes mention: 
> applySkipLimit option for count() on find cursors is no longer supported.

It appears that when this option was removed, it was set to `true` at all times. As the default behavior of `count` was for this value to be `false`, I believe it should always be `false` if we are not going to be given the option. 

### Example/Reproduction: 

Simple example fetching paginated data: 
```
const getData = (collection, options = {}) => {
    let query = options.query || {}
    let cleanup = {
        limit: options.perPage,
        skip: (options.page - 1) * options.perPage,
        sort: {
            [options.sortBy]: options.sortDirection === 'asc' ? 1 : -1
        }
    }
    if (isNull(options.perPage)) {
        cleanup = { sort: { [options.sortBy]: options.sortDirection === 'asc' ? 1 : -1 } }
    }
    let data = collection.find(query, cleanup) // get cursor
    return {
        results: data.fetch(), // return limited documents
        total: data.count() // return total count - equal to limit post-2.6
    }
}
```

At this point, the only solution I've been able to get to work is to effectively query the database twice like so: 
```
    let data = collection.find(query, cleanup).fetch()
    let count = collection.find(query).count()

    return {
        results: data,
        total: count
    }
```
though I have to imagine this is not as performant and not my ideal solution. 

Count is something that I use pretty extensively in many of my projects. 

Is there an alternative or workaround that might be more efficient? Was this an intended outcome?

**Comment by radekmie** [comment]
The [`mongodb`](https://mongodb.github.io/node-mongodb-native/4.3/classes/FindCursor.html#count) package documentation (the actual MongoDB driver that Meteor uses) no longer provides [such an option](https://mongodb.github.io/node-mongodb-native/4.3/interfaces/CountOptions.html). I believe it was easier to stay in align with the driver rather than reimplementing something ourselves.

> At this point, the only solution I've been able to get to work is to effectively query the database twice like so:

Keep in mind, that `find` alone does not do anything really. It's just a wrapper that keeps the query (and the state of iteration if any). Doing two `find`s - one for `fetch` and another one for `count` - is perfectly fine and no slower at all. 

---

Actually, MongoDB [deprecated `Cursor.count`](https://docs.mongodb.com/manual/reference/method/db.collection.count/). You should switch to [`Collection.countDocuments`](https://docs.mongodb.com/manual/reference/method/db.collection.countDocuments/) or [`Collection.estimatedDocumentCount`](https://docs.mongodb.com/manual/reference/method/db.collection.estimatedDocumentCount/) (only the former supports `$limit` and `$skip`).

**Comment by brianlukoff** [comment]
It may be worthwhile to note in the release notes that this is breaking change, since `count` now behaves differently with Meteor 2.6 vs pre-2.6?

**Comment by denihs** [comment]
Hi @tonymckendry ,

Thank you for the detailed description.

In fact, this option is not supported anymore. 

We had this mentioned in our [history.md](https://github.com/meteor/meteor/blob/devel/docs/history.md#meteor-version-release-2) and in our [Migrating to Meteor 2.6](https://guide.meteor.com/2.6-migration.html) guide, but now we'll make that more [explicit](https://github.com/meteor/meteor/pull/11944).

We'll close this issue now.
