### ISSUE TITLE
Be able to get URLs of assets

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1193]
I am using web workers to do some things and for that I load JavaScript code from files which are being server by Meteor. The issue is that there is no way currently on client side to ask for URL of the file in a package. So to get whole URL (including cache invalidation query string) which is otherwise output in what Meteor serves.

**Comment by glasser** [comment]
See also #3705

**Comment by mitar** [comment]
One can use manifest file to resolve to assets file. The issue is that manifest file has sometimes wrong URLs (#5714).

So using information about the current package (#6192) and fixed manifest URLs (#5714) one could correctly resolve asset values (especially because all assets have a flag that they are assets (type: asset) in the manifest file).

**Comment by hwillson** [comment]
Since PR #6440 was accepted, [`Assets.absoluteFilePath(assetPath)`](http://docs.meteor.com/api/assets.html#Assets-absoluteFilePath) can now be used on the server. Since this functionality is available server-side, leveraging the approach mentioned in https://github.com/meteor/meteor/issues/1193#issuecomment-54586151 (using a Method to get the path from the server) is the best solution for now. Since this is an old feature request (almost 4 years!) with very little interest, and there is an acceptable workaround, as part of the on-going old issue cleanup process, I'll close it off. Thanks for suggesting this originally!

**Comment by mitar** [comment]
Hm, in #3705 there was quite a lot of interest in client-side version of it, it seems to me.

Also, how does absolute path on the server side help you get the client side URL? Can you give an example? Especially if an asset is bundled with a package? How does one get an URL to it?
