### ISSUE TITLE
In cordova code imported from /imports behaves differently from same code imported from node_modules

### ISSUE THREAD

**Issue by JanMP** [meteor/meteor#11969]
Meteor 2.6.1, macOs 12.2.1 (Apple M1)

Initially this looked like a problem with uniforms-unstyled. The recommended way to customize uniforms is to copy the source of uniforms-unstyled into your project and work with that. This really works fine in web apps but breaks in cordova with `TypeError: Cannot call a class constructor without new`

At first I thought this was a problem with TS transpilation, but the problem also occured with the js, produced by the same build settings used to build the uniforms npm packages. As it turned out the same code that works fine when imported from node_modules breaks on cordova when imported from /imports.

Reproduction: https://github.com/JanMP/npm-local-import

Run 'meteor run ios' to reproduce the error (or `meteor add-platform android` and then `meteor run android`). The App should show a form with a string input on browser and a white screen on cordova app (with `TypeError: Cannot call a class constructor without new`. See comments and imports in App.jsx

**Comment by denihs** [comment]
Hey @zodern, not sure if this is your area of expertise.

I was able to reproduce the error, but I've also found [this](https://github.com/vazco/uniforms/issues/433) issue and [this](https://github.com/vazco/uniforms/pull/612)  one. They give some solutions and workaround in both of them. So I'm not sure if this is a problem with Meteor or uniforms-unstyled... 

What do you think?

Also @JanMP, did you find this issue I sent above? Did you try anything there to see if it works?

**Comment by JanMP** [comment]
Yes, I found those issues and I tried the solutions (as far as they applied to my problem) and I have found a workaround but it really sucks: I would like to import a copy of uniforms-unstyled/src from /imports (so I can modify it easily). I instead have to use a different build tool to build a npm package from /src so I can then import my changed version from node_modules.

Uniforms for sure got a vulnerability for this error, but when I have to move code that's working fine in the browser to node_modules to make it work in cordova, then that seems to be more of a meteor specific issue.

**Comment by radekmie** [comment]
When it comes to uniforms, we indeed had problems with bundlers in the past. It's because we encourage people to `extend` classes that we export. And when there's a misalignment between bundlers, e.g., there's a ES6 `class` in `node_modules` being imported to the project, but the project transpiles its own code down to ES5 "classes" (`function`), then this problem happens.

However, it's fixed for most cases; probably all except this one. It works in Meteor, Webpack, Parcel, etc. There is a problem with Cordova though, just as @JanMP reported here (and in the issues linked).

Also, we recently had a similar problem due to Browserslist misconfiguration (https://github.com/vazco/uniforms/issues/1089), but @JanMP says it's not solving his problem.

**Comment by zodern** [comment]
Meteor uses the legacy bundle on cordova, which does transpile es6 classes.

If you have Meteor recompile uniforms, then it will work: https://guide.meteor.com/using-npm-packages.html#recompile. There is a bug in Meteor where using the `meteor.nodeModules.recompile` option doesn't work with some packages, and that seems to include uniforms, but the symlink method does work.

**Comment by JanMP** [comment]
Uniforms is working fine from node_modules. And Benjamin states at the beginning of his description that you can't use the symlink method  if you want to modify the code locally - wich is exactly what I am doing .

**Comment by zodern** [comment]
Meteor is leaving the code in `uniforms` as is with ES6 classes, while the classes in app code, which includes `uniforms-unstyled`, is being transformed by babel. The error is happening because an ES6 class in uniforms is trying to extend a transpiled class from uniforms-unstyled, which is not supported.

If you have Meteor transpile the code in `uniforms`, then it will work. You can enable this by doing something like
```
cd imports
ln -s ../node_modules/uniforms uniforms
```

> And Benjamin states at the beginning of his description that you can't use the symlink method if you want to modify the code locally - wich is exactly what I am doing .

How are you modifying the `uniforms` package?

**Comment by JanMP** [comment]
Ah, ok do that linking trick to the other parts of uniforms. I'll try that.

I am changing the react components that render the form elements (I have e.g. changed the default select to react-select and added settings to switch to floating labels).

**Comment by JanMP** [comment]
Yes, that works. The possibility to use that symlink trick on the OTHER uniforms packages really eluded me there.
