### ISSUE TITLE
minify-css-postcss: Cannot read property 'getContentsAsString' of undefined

### ISSUE THREAD

**Issue by JanMP** [meteor/meteor#11967]
Importing the css file from react-virtualized causes this error in minify-css-postcss:

```
=> Errors prevented startup:
   
   While minifying app stylesheet:
   packages/minifier-css-postcss/plugin/minify-css-postcss.js:362:40: Cannot read property 'getContentsAsString' of undefined
   at packages/minifier-css-postcss/plugin/minify-css-postcss.js:362:40
   at Array.map (<anonymous>)
   at mergeCss (packages/minifier-css-postcss/plugin/minify-css-postcss.js:361:36)
   at CssToolsMinifier.processFilesForBundle (packages/minifier-css-postcss/plugin/minify-css-postcss.js:202:18)
```

The Problem is the last line (the comment).

Reproduction: https://github.com/JanMP/meteor-css-error/blob/master/README.md

**Comment by fredmaiaarantes** [comment]
Hey, I'm closing this issue as it was fixed in Meteor `2.7-rc.4`.

I just created a [PR for your repository](https://github.com/JanMP/meteor-css-error/pull/1) where I have updated the project and followed the [migration guide preview](https://deploy-preview-11916--meteor-guide.netlify.app/2.7-migration.html) and it worked fine.
