### ISSUE TITLE
C.find(q, {limit: N}).count() inconsistent between server and client

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1201]
When comparing how `.count()` works in Meteor and MongoDB I found a difference. In MongoDB default is that `.count()` returns the count of all elements in the cursor, no mater if `skip` or `limit` was used. But in Meteor this is not true. As a consequence, it seems impossible to get number of all results in `find` in Meteor.

See [MongoDB documentation](http://docs.mongodb.org/manual/reference/method/cursor.count/).

The issue is if I want to provide pagination. I would like to know how many were all results, but then send over the wire only a page of the results.

**Comment by mitar** [comment]
The main issue is not that the option is not implemented, but that behavior between server and client is different. Minimongo behaves like `applySkipLimit` is set to `true`, while server side queries like `applySkipLimit` is set to `false`. So if you run the same query both on the client and server side you get differences.

**Comment by mitar** [comment]
To see what I am talking about, run `minimongo - basics` tests on the server. Basic tests will fail.

**Comment by mitar** [comment]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. It exposes this issue as one of the failed tests.

**Comment by glasser** [comment]
Unfortunately, it doesn't look like I got to this as part of the 1.0.4 maintenance work.

**Comment by RobertLowe** [comment]
@glasser D'aw, I wanted to see this! `applySkipLimit` would be great for [publish-counts](https://github.com/percolatestudio/publish-counts) I'm using. Maybe for `1.0.5`?

I feel keeping things 1-to-1 with Mongo is pretty important priority.

I'll just make another workaround in the meantime. :disappointed:

**Comment by jamesgibson14** [comment]
I would love for my minimongo code `Collection.find({},{limit:10}).count()` to have the same out put on both client and server.

**Comment by laosb** [comment]
Fixed in bce4df9

**Comment by mitar** [comment]
What about on the client side? There is no way to control it on the client side, no?

**Comment by mitar** [comment]
See #5023 pull request and discussion there.

**Comment by laosb** [comment]
I didn't look at all the comments carefully and closed this seeing `@okland added a commit to okland/meteor that referenced this issue on 15 Oct 2015`, sorry!

Should I reopen this or track it in #5023?

**Comment by mitar** [comment]
I think that #5023 is a pull request which does not even have source repository anymore. That one should probably be closed, and this one kept around until we address this also on the client side.

BTW, are there any tests added for bce4df9?

**Comment by laosb** [comment]
Yeah, I'd reopen this. As #5023 lost its source repo so no further updates can be made, we should close it.

**Comment by titovanton** [comment]
Hmmm. First of all, for a user, who is familiar with MongoDB, the behavior of your counting - is not obviose. And it makes me fill strange: what did you think about when prefer: `Blabla.find().count()`, instead of original `db.collection.count(query, options)`? And `applySkipLimit` - looks like crutch, not less! :/

**Comment by hwillson** [comment]
Hi all - to help move this along, I've marked this issue as `pull-requests-encouraged`. PR #5023 was started to address this issue, but was closed due to inactivity. If anyone in the community is interested in blowing the dust off things and submitting a new PR, it will definitely be reviewed in a timely manner, and be considered for merging. Thanks!

**Comment by carlevans719** [comment]
I'm happy to pick this up. Is the consensus still that we will be changing the default behaviour of `.count()` on the client so that it is consistent with the way it works on the server?

**Comment by hwillson** [comment]
#9205 was merged, so this functionality will be coming soon. Thanks @carlevans719 et. al!

**Comment by mitar** [comment]
I do not think this should be closed. By default, client and server are still inconsistent, as this issue is claiming. #9205 is just adding an option to change this. This makes isomorphic code hard to write.

**Comment by hwillson** [comment]
Thanks @mitar - yes, we went back and forth on this one. For now this approach is the most flexible while still maintaining backwards compatibility (in particular in the case where people are using minimongo without mongo, for client side caching, etc.). This new option will show up in the docs, so people who want to ultimately enable the correct behavior can. At some point this will be switched around (so we're passing `false` into `count()` by default), but the consensus was not yet (given the impending release of 1.6). That being said, we don't want to lose sight of this, so keeping this open sounds like the way to go. 

Just to re-itereate though to anyone coming to this issue. PR #9205 introduces the ability to fix this manually by passing `false` into your client side cursor `count()` - e.g. `someCollection.find().count(false)`.

**Comment by mitar** [comment]
Yes, this is great progress and the major step! Thanks!

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
