### ISSUE TITLE
Server side `cursor.observe` `changed` callback is fired multiple times

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#12128]
I was essentially seeing the same behavior as #12098 on the server but #12107 does not appear to fix it.

I snapped a copy of the `mongo` package for #12107 and included it in the `packages` folder.

On the server side I defined a publication:
<details>

<summary>publish code</summary>

```javascript
Meteor.publish('change', function publishChanges() {
  const self = this;

  ChangeCollection.find({}).observe({
    added(doc) {
      self.added('change', doc._id, doc);
      self.ready();
    },
    changed(newDoc, oldDoc) {
      self.changed('change', newDoc._id, newDoc);
      console.log('changed doc: ', newDoc);
      self.ready();
    },
    removed(oldDoc) {
      self.remove('change', oldDoc._id);
      self.ready();
    }
  });
  self.ready();
  return;
});
```
</details>

And I log every time the `changed` callback is called.

On the client I query the collection within an `autorun` and log its values.

## Environment
`METEOR@2.7.3`
OS: Ubuntu 20.04.4 (WSL)

## Expected
For each change to a document in Mongo to receive 1 `changed` callback in the `observe` method.

## Actual
See a changed callback for each time the client subscribes to the publication.

## Repro repository: https://github.com/brucejo75/observe_change_issue
To see the issue.

1. Click `Change Collection Value`,
2. Observe server output
3. Click `Restart Subscription`
4. Observe undesired behavior in the server output.

**Comment by radekmie** [comment]
I guess you meant #12107, not #12017. I've tried your reproduction and there are a few things.

First of all, the fact that restarting a publication triggers more and more `console.log`s is correct - you're not stopping the observer, therefore every subscription adds a new one. Here's how to fix it:
```diff
@@ -3,7 +3,7 @@ import { ChangeCollection } from './change_common.js';
 Meteor.publish('change', function publishChanges() {
   const self = this;
 
-  ChangeCollection.find({}).observe({
+  const handle = ChangeCollection.find({}).observe({
     added(doc) {
       self.added('change', doc._id, doc);
       self.ready();
@@ -18,6 +18,7 @@ Meteor.publish('change', function publishChanges() {
       self.ready();
     }
   });
+  self.onStop(() => handle.stop());
   self.ready();
   return;
 });
```

Secondly, none of the `oplogV2V1Converter` changes affect the problem of the `undefined` being pushed to the client, because the replace operation (you're not doing `$set`/`$unset`, but always replace the entire document) does not generate a new-style oplog entry.

Lastly, the problem comes from the fact, that MongoDB removes a field when its value is `undefined`, making it **not** present in your `changed` callback, meaning that the client won't see any change - in the end, there's no new value for the field (it's simply not there). The only option I see now would be to _somehow_ handle replace operations with field removals, although it's probably going to be backward-incompatible, I think.

**Comment by brucejo75** [comment]
Arrgggh, sorry @radekmie!

1. I repaired my PR reference to #12107.
2. I should have seen the `stop` issue.  Sorry for the waste of time.
3. I still have questions re: the problem of `undefined` which I will ask in #12130
