### ISSUE TITLE
Unable to build/submit Android to play store - new requirements API 31

### ISSUE THREAD

**Issue by matheusccastroo** [meteor/meteor#12126]
The new play store requirements (https://developer.android.com/google/play/requirements/target-sdk) states that new apps (for now) should target API 31 of Android. Starting from november, all apps (new apps or updates) will need to target API 31.

For that to work, we need to add the `android:exported` flag to the main activity that cordova generates.

This is already done in the `cordova-android` repository, and has been out since `10.1.2`. Meteor is using the `10.1.1` version, so we need to update this one at least one version.

This is quite critical, since will block new apps from being created/updated.
Will create the PR for the update here, should be quite simple.

EDIT:
The following workaround works inside the `App.AppendToConfig`: 
```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application/activity" xmlns:android="http://schemas.android.com/apk/res/android">
    <activity android:exported="true"></activity>
</edit-config>
```
But besides that, you also need to compile/build the app using Java 11 and also with the latest cmdline-tools from the SDK.

For more info, check https://github.com/meteor/meteor/issues/12126#issuecomment-1212373864

**Comment by matheusccastroo** [comment]
Also, one other point we should have in mind is to update the whole cordova stack we have, since they are a bit outdated.

**Comment by matheusccastroo** [comment]
@fredmaiaarantes @denihs Think we could maybe release a `2.7.3-2` version here?

**Comment by Gywem** [comment]
```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application/activity" xmlns:android="http://schemas.android.com/apk/res/android">
    <activity android:exported="true"></activity>
</edit-config>
```

This code snippet on `App.appendToConfig` has made the issue with exported to go away from our end.

However, we encounter now another problem on build the app.

> java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)

![image](https://user-images.githubusercontent.com/2581993/184142156-f74e51c7-ae96-4fff-856f-89afb7733de2.png)

This problem seems to be solved by upgrading and exporting the JAVA_HOME [to point to the JDK11 version.](https://stackoverflow.com/questions/68344424/unrecognized-attribute-name-module-class-com-sun-tools-javac-util-sharednametab)

But upgrading to JDK11 is not possible on Meteor, or at least we get another error.

```
✗ Android target: Command failed with exit code 1: avdmanager list target
Exception in thread "main" java.lang.NoClassDefFoundError:
javax/xml/bind/annotation/XmlSchema
at
com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
at
com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException:
javax.xml.bind.annotation.XmlSchema
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

The way [to solve that is to be on JDK 8 actually](https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a/46405092#46405092), and even on Meteor docs this version is the one required, at least on M1, but in all projects I have worked on JDK 8 was the version to use to overcome the aforementioned problem.  

Anyway, that is the contrary expected by the new android sdk 31 requiring JDK 11. This is like a dead end on Meteor once the new android version is mandatory (from November on, and currently for any new app).

**Comment by Gywem** [comment]
I solved the problem above by ensuring that the Java version used by Meteor is 11. Then, you have to ensure the cmdline-tools are updated to latest version. Then make sure that both Java 11 and latest cmdline-tools are set on the PATH for Meteor to use them.

Some cmds that could work on your end if you have homebrew or linuxbrew would be:

```
brew install java11

export JAVA_HOME="$(brew --prefix java11)"
export PATH="$JAVA_HOME/bin:$PATH"

sdkmanager --install "cmdline-tools;4.0"

# set the PATH into the cmdline-tools if necessary 
export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${PATH}"
```

> The PATH is recommended to be extended in .bashrc/.bash_profile/.zshrc files
