### ISSUE TITLE
meteor@1.10.3 doesn't generate types

### ISSUE THREAD

**Issue by tosinek** [meteor/meteor#12365]
Looks like `meteor@1.10.3` doesn't generate types with `zodern:types` into `\.meteor\local\types\packages.d.ts`
Downgrading to @1.10.2 fixes it. It happened after upgrading to 2.9.0, but that might be just a coincidence.
@zodern

**Comment by Grubba27** [comment]
Yes! it happened that it was removed by mistake while we were merging files. We are working on assembling a 2.9.1 release to solve this and other types of issues.
If you want to see where the problem is, it is here https://github.com/meteor/meteor/commit/f60bfc7f75a24263539ef67fe856afab6eaf983e#r92920783

**Comment by Grubba27** [comment]
Closing this one as it was solved in 2.9.1 and forward
