### ISSUE TITLE
Mongo query mismatch hangs client

### ISSUE THREAD

**Issue by jdgjsag67251** [meteor/meteor#12516]
If the Meteor server publication ever has `undefined` in a query, it will throw an error about a mismatch between Meteor and MongoDB: `Exception in defer callback: Error: The Mongo server and the Meteor query disagree on how many documents match your query. Maybe it is hitting a Mongo edge case?`. I believe this is [expected behavior](https://docs.meteor.com/changelog.html#breakingchanges-51). However, throwing this error means that the client never receives a response for the subscription, which in turn blocks all other requests/responses. This makes it seem like the client hangs forever.

We first noticed this in version 2.7.3 (probably not the earliest occurrence, just a code change on our part), but I have confirmed this is also the case for version 2.10.0.

I've created an example project containing the issue: https://github.com/jdgjsag67251/meteor-sub-bug.

**Comment by KoenLav** [comment]
To be clear: from that moment onward all clients (subscribed to that collection, whether a field in the selector is undefined or not) will not receive responses.

If we really want to throw an error, I'd rather have the error stop the server process, making this much easier to debug. But instead I think it would be better to just break the single subscription of the client who subscribed to undefined, instead of all.

**Comment by chneau** [comment]
I had a similar issue https://github.com/meteor/meteor/issues/12063. My workaround was to guard against `undefined` values or malformed dates, in my case, the client could subscribe with a malformed date, which on the server side was triggering this specific error.

**Comment by KoenLav** [comment]
Attempted fix: https://github.com/meteor/meteor/pull/12587
