### ISSUE TITLE
Meteor website Docs is becoming unusable

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#12608]
2.11 - page missing

https://docs.meteor.com/v2.10/api/accounts-multi.html#AccountsCommon   (seen same in 2.12)

import { AccountsCommon } from 'meteor/accounts-base'

AccountsCommon is undefined consequently cannot be configured as per the documentation. However, the documentation talks about AccountsCommon while configurations are exemplified from Accounts.config()

I've been using Meteor for 10 years and I still find it really difficult to read this documentation. How about Javascript syntax and examples instead of 'AccountsCommon#userId()'.

References to code in Github no longer link to the relevant line. Example:

[AccountsCommon#userId()](https://docs.meteor.com/v2.10/api/accounts-multi.html#AccountsCommon-userId)
[(accounts-base/accounts_common.js, line 88)](https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_common.js#L88)

Line 88 has nothing to do with userId().

**Comment by StorytellerCZ** [comment]
Quiet a few issues here.

@Grubba27 the docs for 2.11 seem to be missing completely. Probably the most actionable right now.

The `AccountsCommon`, agreed that is not written/formatted well. Looks like it is being exported as just `Accounts` and things like `userId()` are merged into the `Meteor` class as well. PRs to fix are welcome!

As for the pointing to the wrong place in code:
The older version of docs points to the old line where `userId` used to be. The current version of docs points to the correct line (line 111), the mistake is because the link is to the current `master` branch, instead of the legacy code.

**Comment by Grubba27** [comment]
Sorry for the delay, but the 2.11 are back online https://docs.meteor.com/v2.11/

Regarding the `userId()` code, it is in line 421

```js
/**
 * @summary Get the current user id, or `null` if no user is logged in. A reactive data source.
 * @locus Anywhere but publish functions
 * @importFromPackage meteor
 */
Meteor.userId = () => Accounts.userId();

```
Let's make it more like the other API pages using only the name of the methods. See [tracker](https://docs.meteor.com/api/tracker.html#Tracker-withComputation) for example. It uses the name of the methods to create the docs.

**Comment by bilalshaikh292** [comment]
Heyy the issue have not been solved yet ? I would like to contribute ? is the issue still open ?

**Comment by StorytellerCZ** [comment]
The issues have been resolved, but more examples are always welcome. @Grubba27 I think we can close this.
