### ISSUE TITLE
[2.15] libcrypto.so.3 not found on CircleCI

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#13064]
When running tests on in CircleCI using cimg/node-14:14.18-browsers on Meteor 2.15 we're receiving "No such file or directory" for "licrypto.so.3".

```
/home/circleci/.meteor/packages/meteor-tool/.2.15.0.14dvwv6.8tc8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod:
error while loading shared libraries: libcrypto.so.3: cannot open shared object
file: No such file or directory
Unexpected mongo exit code 127. Restarting.
```

This problem did not occur in Meteor 2.13.3

We've already tried installing openssl, libssl-dev and a couple of other suggestions found online when there are issues with OpenSSL/libcrypto, but to no avail.

**Comment by nachocodoner** [comment]
What OS are you currently using?

In our latest update, 2.15, we've added support for Mongo 7, requiring a g++ version higher than 11. For certain OS like Ubuntu, this may require an upgrade to at least Ubuntu 22.04. I encountered similar challenges in my environment due to outdated native libraries, as required by the latest expectations of Mongo 7.

Further details can be found in [our blog post](https://blog.meteor.com/new-meteor-js-2-15-and-mongodb-7-f358bc304250).

**Comment by KoenLav** [comment]
Resolved by running on a lower version of Ubuntu.

**Comment by nachocodoner** [comment]
@KoenLav. On a lower version? Which version did you use and which fixed it?

Since after 2.15 the expectation was to use a higher version I would say.

**Comment by KoenLav** [comment]
@nachocodoner you're correct, we had to upgrade to Node.js 20, but had to use cimg/node:20.9-browsers instead of cimg/node:20.12-browsers for uploads through MUP to work.
