### ISSUE TITLE
Meteor 2.16 error - Called saveOriginals twice without retrieveOriginals

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#13278]
In Meteor v2.16, I'm seeing an issue with `Called saveOriginals twice without retrieveOriginals` when calling `insertAsync` inside an isomorphic Meteor method. I don’t see the error in v2.14 or v2.15. 

I think it has to do with this commit: https://github.com/meteor/meteor/commit/188ae56a2150dfb791f03979829de22787029382

I'm not sure adding `*Async` methods was necessary in `minimongo/local_collection.js` since I think they are added here: https://github.com/meteor/meteor/blob/b11416c1f0f03af9a0b75b80b44e1f1dd7557a30/packages/mongo/collection.js#L988

If it is necessary, then maybe they also need `isCalledFromAsync = true`. Let me know if I'm missing something.

**Comment by nachocodoner** [comment]
`insertAsync` and other `*Async` operations were introduced in Meteor 2.x's LocalCollection to align with [the new Meteor 3.0 API](https://github.com/meteor/meteor/blob/release-3.0/packages/minimongo/local_collection.js#L173), allowing both behaviors to be ready for migration to the new version. On tests added on Meteor 2 and 3 was clear that those implementations were missing on Meteor 2.

Does the issue occur consistently when you use `insertAsync` directly from the `Collection` object, via `LocalCollection` using `._collection`, or in another situation?

At first glance, adding new `*Async` methods shouldn't affect existing workflows since the new async API only applies when using `._collection` in the local collection. There isn't explicit usage of these new behaviors in the core unless you're using `_collection.insertAsync` on your app/package and something is missing in the new behavior.

I might be overlooking something.

**Comment by jamauro** [comment]
Thanks for taking a look. After more investigation, I don't think Meteor has an issue so I'm going to close this. 

It's still a mystery to me why I didn't see this error in versions prior to 2.16 though. But ultimately, I think 2.16 is exhibiting the correct behavior. I've fixed the issue on my side.
