### ISSUE TITLE
Understanding the structure and content of bundled package

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#1393]
Hi all together in meteor space,

We are new on board and have done some minor testings and workouts and really love that pretty cool stuff in the meteor univers.

Currently I try to understand what is done in the build environment and what is the functionality inside the directories of the bundled package.

Example folder when extracting bundled tar

```
./bundle/

server /

   ? what is this server directory standing for

programs /

   client /

      ? this is all the part what is delivered to the client when starting url://localhost:port

   ctl /

      ? what is inside and for what kind of use is this directory
      ? what is the function of start.sh

   server /

      ? this is the backend service
      ? what is the function of start.sh
```

Thanks for some hints in advance.

Tom

**Comment by tvoglund** [comment]
Well, I still after reading every link here do not see any explanation of the bundle file structure.  I have a meteor.js application and I want to verify the correct typescript code was compiled correctly to the .js.  But I am unable to find any description on where the new js files would be inside the bundle.  Please help.

**Comment by hwillson** [comment]
Hi @tvoglund - you'll have better luck getting an answer to this type of question by posting on the [Meteor Forums](https://forums.meteor.com) or [Stack Overflow](http://stackoverflow.com/questions/tagged/meteor), since your question isn't directly related to a Meteor bug or feature request. The bundle structure is outlined in this issue thread (here's the updated link for the [`bundler.js`](https://github.com/meteor/meteor/blob/7baed435f53c4fa2cf5515679e64c68d88d31d7a/tools/isobuild/bundler.js)), so if you have more specific questions please continue them on the forums/SO. Thanks!
