### ISSUE TITLE
Calling Meteor.call when the window is closed (ie. .on('unload')).

### ISSUE THREAD

**Issue by funkjunky** [meteor/meteor#1434]
```
  5          $(window).on('unload', function() {
  6             console.log('asdfgfdggf');
  7             Meteor.call("leaving_room", this.params.roomid);
  8          });
  9          $(window).bind("beforeunload", function() {
 10             console.log('wadsfghfj');
 11             //Meteor.call("leaving_draft", this.params.roomid, function(){});
 12             return "Are you sure you want to leave the lobby?";
 13          });
```

So the unload method doesn't seem to call my leaving_room meteor method. Obviously the console.log isn't even going to show up, because you're leaving the window. I have no idea how to troubleshoot this kind of an issue.

Also if I uncomment the Meteor.call in the beforeunload event, then the user is no longer asked if they want to stay on the page... the whole event seems to stop working. Otherwise the console.log shows up and the confirmation message is shown when they attempt to leave.

Version 0.6.5.1

**Comment by evolross** [comment]
I was researching this issue and saw this post. Very helpful.  

In Firefox, I'm using awatson1978's code snippet and I'm noticing it shows you the popup dialog no matter what asking if you really want to leave the page and if you cancel and stay on the page, the `closingWindow` method has already fired.  So now you have a user still on the page with a bunch of cleanup work done on the server that you may not necessarily want to have happened.  

Has there been any additional "standard practices" for this kind of thing since the time of this posting?  There's not much on the web - everyone seems to be having the same issue.
