### ISSUE TITLE
Two {{loginButtons}} on the page cause two login boxes

### ISSUE THREAD

**Issue by rantav** [meteor/meteor#1472]
This bug follows a discussion on the meteor-talk group. https://groups.google.com/forum/#!topic/meteor-talk/2O7FtbZm1GA
It may be addressed in the future by meteor-ui, but as of now it's a bug...

In some cases it makes sense to have two {{loginButtons}}

![reversim_summit_2014-2](https://f.cloud.github.com/assets/87037/1284019/b133885e-2f8e-11e3-8c96-da357829de6e.png)

The problem is that when one of them is clicked, two login boxes open. 

![reversim_summit_2014_and_1 _rantav_mathbook_pro____dev_reversim-summit-2014__zsh_](https://f.cloud.github.com/assets/87037/1284043/007d7dfc-2f8f-11e3-98eb-93a85e00feed.png)

**Comment by glasser** [comment]
See some other discussion on #3300 that happened before the duplicate was detected.

**Comment by adamwong246** [comment]
I like @glasser's idea. Maybe like how autoform passes in a string as a unique id, loginButtons could do the same
```
{{loginButtons id='naviagational_login_buttons'}}
....

**Comment by aaronjudd** [comment]
@stubailo @glasser Since this is a two year old issue,  is it time for this to get some attention again? Since the issue #3300 had been marked "pull request encouraged" maybe at least a label can be applied to this issue so that we know it's being tracked.  If there is a rework coming for MDG (that would be great), but clarity would be helpful now before we invest time in a PR.

**Comment by stubailo** [comment]
For production accounts UI, we recommend the `useraccounts` series of packages. Ideally in the future they will be a complete replacement for accounts-ui. This means we are probably not going to improve accounts-ui except for basic bug fixes.
