### ISSUE TITLE
Allow write concern option to be specified for database operations

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1547]
**_1 Upvote**_ It is unclear what [write concern](http://docs.mongodb.org/manual/core/write-concern/) does Meteor use when connecting to MongoDB database. But mainly, it would be useful to be able to specify various levels of write concern:
- I do not care about the result – write operation could return immediately or callback could be called immediately
- I do care about writing to primary
- in the case or replica set used for MongoDB database, I would want that write operation returns or callback is called only after data is propagated to secondaries

**Comment by avalanche1** [comment]
+1

**Comment by opfpqgoon** [comment]
+1 for sure.

Right now there's no good way to build a massively distributed application that can leverage different write concerns for different types of data.  

Example:
- A social media platform where we would comment data to be written with a lower write concern; we care more about performance than consistency here.  If a comment happens to be lost due to infrastructure failure it wouldn't be the end of the day.  Eventual consistency is acceptable.
- This same platform would want to make sure that certain user data is consistent before acknowledging the write.  If a user updates their password we want that change to be fully propagated to all mongo servers before reporting a successful password change.

Right now we could hard code a fully consistent write concern, but this would apply to all transactions, and we would have to rely much here heavily on callbacks for transactions that need to be quick (the first part of the above example).

**Comment by msavin** [comment]
Any chance this has been implemented already?

**Comment by mitar** [comment]
I didn't notice it. I think MDG is not really developing Mongo support in Meteor now that they moved to Apollo. So we should probably make pull requests for such features if we want them.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20write%20concern%20option%20to%20be%20specified%20for%20database%20operations&body=Migrated%20from:%20meteor/meteor%231547) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
