### ISSUE TITLE
Accounts UI does not trigger password store/autocomplete in Firefox

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1746]
**_1 Upvote**_ I just now noticed that Accounts UI does trigger password store/autocomplete in Firefox. As using password managers is a good security practice, I think this should be addressed somehow.

Tested on Firefox 26. Should be probably tested on other browsers as well.

**Comment by JobJob** [comment]
+1

**Comment by obiwarn** [comment]
This annoys many of my users. 
Is there a workaround?

**Comment by nkoren** [comment]
FWIW, I built a custom login page *not* using Accounts-UI -- just a bunch of custom templates -- and it works fine with password managers in all browsers. So server-side rendering doesn't seem to be needed; it's something else that is causing the problem.

**Comment by JobJob** [comment]
Also, FWIW, this workaround, while extremely kludgy, seems to work in firefox:

    <form id="loginform" action="javascript:">
        {{loginButtons}}
    </form>

Then somewhere in a js file

    Blaze._allowJavascriptUrls() //to enable the action="javascript:" in the <form> element
    Template._loginButtonsLoggedOutDropdown.events({
      'click #login-buttons-password': function () {
        $('#loginform').submit()
      },
      'keypress #login-username, keypress #login-email, keypress #login-username-or-email, keypress #login-password, keypress #login-password-again': function (event) {
        if (event.keyCode === 13)     
          $('#loginform').submit()
      }
    });

It seems Firefox may need a form element and relies on the submit event in order to ask the user to save a password. @nkoren do you have a form that you submit in your custom login page?

**Comment by hugoroy** [comment]
Sorry if this isn't the right place, but we have this problem on a meteor app as well, https://github.com/tosdr/tosdr2/issues/3 -- is there an official way to work around this bug or is this bug fixed? 

Thanks

**Comment by pierreozoux** [comment]
Indeed, it is still an issue.
It is sad because even successful open source projects like https://demo.rocket.chat/home are facing the same issue.
Maybe you use oauth, but email login is still widely used and is good for user's privacy.

Can somebody from meteor team give a status on this? It would be awesome!

@nkoren can you share a code sample please?

**Comment by steinmb** [comment]
Still an issue for me also.
### System
- Firefox 40.0.3
- OS X 10.10.5

**Comment by stubailo** [comment]
I have been trying to track down the criteria that popular password managers use to identify password forms. Is it the URL? Is it some attributes on the form?

I can't find any documentation on this issue, anything would be super appreciated.

**Comment by pierreozoux** [comment]
@stubailo from earlier comment:

https://github.com/meteor/meteor/blob/0f3dff7866228c81d721d859a6f376eff97dca4c/packages/accounts-ui-unstyled/login_buttons_dropdown.html#L161

https://gist.github.com/kostiklv/968927

Tell me if you find good ways to make it work :)

**Comment by hugoroy** [comment]
Any update on this? @pierreozoux @stubailo

**Comment by michielbdejong** [comment]
I think just adding a form tag around the login form is not enough, probably because it's generated dynamically. One ugly but minimal work-around is to add a 'Remember my password' form in the "not logged in" page, but still use the default login form for actually logging in: https://github.com/tosdr/tosdr2/pull/41/files

If there is really no way to make dynamically generated login forms (like the one Meteor uses) work in Firefox, then this might also be worth submitting a bug to Firefox about this? If I can get some guidance from a Meteor core person about what a desired solution would be, then I could work on that.

**Comment by mitar** [comment]
[useraccounts](https://github.com/meteor-useraccounts) do not have this problem and autocomplete works. So I am not sure what is a difference.

**Comment by hwillson** [comment]
I've submitted PR https://github.com/meteor/meteor/pull/9442 to help address this.
