### ISSUE TITLE
TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#1804]
Fedora 20
Meteor 0.7.0.1

$ curl https://install.meteor.com | /bin/sh
looks OK.

$ meteor --help
~/.meteor/tools/09b63f1ed5/tools/meteor.js:7
Fiber(function () {
^
TypeError: undefined is not a function
    at Object.<anonymous> (~/.meteor/tools/09b63f1ed5/tools/meteor.js:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

What is wrong?

**Comment by pjump** [comment]
I'm experiencing the same issue as eMxyzptlk. I'm on Linux Mint 17 (~Ubuntu 14.04).

**Comment by pjump** [comment]
I got the same issue on Ubuntu 14.04 with node v0.10.25 and it's cause by the `node-fibers` package. I had a similar issue with `socket.io`, which I tracked to the `ws` package. The problem seems to be that these C/C++ add-ons rely on some old ABI where the C++ init function for a NODE_MODULE would have been declared "extern C".  This is not mentioned in the current documentation and removing the `extern "C"` fixes the problem, though it introduced a problem with older nodejs's for ws, which has a comprehensive test suite, so I ended up removing conditionally, like so:
`
#if !NODE_VERSION_AT_LEAST(0,10,0)
extern "C"
#endif
`
which was fine with `ws`'s test suite and it should work with `node-fibers` too (my PR is here https://github.com/laverdet/node-fibers/pull/217 , but can't currently integration-test it accros multiple archs because node-fibers doesn't have that for travis-ci, and I'm currently on a very old, make-shift PC that doesn't handle virtualization that well).

**Comment by glasser** [comment]
@pjump Thanks.  If this gets merged and released in Fibers, can you open a new issue requested us to upgrade?
