### ISSUE TITLE
Accounts collection errors involving Mongo ObjectIds

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#1834]
**_2 Upvotes**_ Hi Core Dev Team!

A couple of us are getting the following error when trying to connect Meteor apps to pre-existing Mongo databases that have legacy accounts with ObjectIds in the users._id fields.  
#### setUserId must be called on string or null, not object

```
Exception while invoking method 'login' Error: setUserId must be called on string or null, not object
```

The problem was originally reported by Serkan, when he was trying the following code:

``` js
Accounts.onCreateUser(function(options,user) {
  check(options, Object);
  check(user, Object);

  // options.profile.email = user.services.facebook.email;
  // options.profile.facebookId = user.services.facebook.id;
  // user.profile = options.profile;

  // options._id = new Meteor.Collection.ObjectID(user._id); /* this one complains about _id being too short, naturally... */
  options._id = new Meteor.Collection.ObjectID(); /* creates a new random ObjectID */
  user._id = options._id;

  return user;
});
```
#### {idGeneration : 'MONGO'}

I tried using another approach, by specifying `{idGeneration : 'MONGO'}` on the Accounts collection, like so.  

``` js
Accounts = new Meteor.Collection("users", {idGeneration : 'MONGO'});
```

Predictably, this gave the following error, basically saying that the collection was already defined:

``` js
W20140211-12:28:05.698(-5)? (STDERR) Error: A method named '/users/insert' is already defined
W20140211-12:28:05.699(-5)? (STDERR)     at packages/livedata/livedata_server.js:1210
W20140211-12:28:05.699(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:87)
W20140211-12:28:05.699(-5)? (STDERR)     at _.extend.methods (packages/livedata/livedata_server.js:1208)
W20140211-12:28:05.700(-5)? (STDERR)     at Meteor.Collection._defineMutationMethods (packages/mongo-livedata/collection.js:673)
W20140211-12:28:05.700(-5)? (STDERR)     at new Meteor.Collection (packages/mongo-livedata/collection.js:176)
W20140211-12:28:05.700(-5)? (STDERR)     at app/accounts-objectid.js:1:47
W20140211-12:28:05.700(-5)? (STDERR)     at app/accounts-objectid.js:112:3
W20140211-12:28:05.701(-5)? (STDERR)     at /Users/abigailwatson/Code/ThinAire/accounts-objectid/.meteor/local/build/programs/server/boot.js:155:10
W20140211-12:28:05.701(-5)? (STDERR)     at Array.forEach (native)
W20140211-12:28:05.701(-5)? (STDERR)     at Function._.each._.forEach (/Users/abigailwatson/.meteor/tools/09b63f1ed5/lib/node_modules/underscore/underscore.js:79:11)

```
#### Bug Replication

The bug has been isolated in it's own repository, and can be viewed online, using the following links:  
https://github.com/awatson1978/accounts-objectid  
http://accounts-objectid.meteor.com/  
#### Impact

This bug is preventing some of us from deploying Meteor applications in environments that already have production Mongo databases.  In particular, it prevents deploying Meteor applications with user databases where the Users collection has to be accessed by external applications (i.e. Express apps), and where the Users._id field is already defined as an ObjectId.

**Comment by engelgabriel** [comment]
Just adding my +1 to @awatson1978 and @serkandurusoy 
I just runned exactly into the same problem here... and this limitation is as frustrating as disappointing. We will have to spend days converting our current users collections and all other references to string, and I'd be much happier telling my developers to come with a fix and submit a pull request if there was any indication that MDG would be willing to accept it, rather than just spending thousands of $$$ in an otherwise pointless data migration :(

**Comment by pcorey** [comment]
I recently ran into an issue similar to this. I wanted to build a Meteor app that would work together with an external app. The external app handled user registration and kept users in a MongoDB "users" collection. I figured that I'd be able to use accounts-base and a custom loginHandler to authenticate against this collection in my Meteor app. Unfortunately, the external app was using ObjectIds instead of Strings in its _id field.

Thinking about it, I don't think that accounts-base not supporting ObjectId is the issue here. As @glasser  said, accounts-base is a package designed to do a particular task, and has a specific schema used for that task. Integrating with 3rd party applications through the users collection is not what accounts-base is designed to do, even if the 3rd party users schema is a close match. A better solution would be to roll your own users collection (probably based on a forked accounts-base).

However, it looks like the ddp package holds a "setUserId" method, which is called by accounts-base on login/logout. It expects userId to be a [String or null](https://github.com/meteor/meteor/blob/59ac39ce81cac85cd733ec91f2be74b4d8251e59/packages/ddp/livedata_server.js#L700-L702). I'm far from a Meteor expert, and I've only just started digging into the Meteor source, but it seems strange that this restriction/assumption would exist outside of accounts-base. If I were to roll my own accounts-base style package to support my ObjectId based schema, I wouldn't be able to use setUserId, which I believe would have a major impact on my session/subscriptions.

**Comment by glasser** [comment]
We have a function `LocalCollection._idStringify` (probably needs a better name/location) that lets you convert a variety of types, including ObjectId and string, to a string in a reversible manner.

**Comment by JNissi** [comment]
There's still no good solutions to this? I'm trying to reuse the users from a legacy database without invasive shotgun surgery to all collections, and now I can't because I can't set `users._id` to ObjectId? ffs!

**Comment by MilosStanic** [comment]
I have to say I fully support all arguments pointed out by @awatson1978 and @serkandurusoy. 

I think this is a serious issue and I'm really surprised how this passed under radar, and I really haven't stumbled upon it in any tutorials. I hope this resolves in a sensible manner, otherwise it may render Meteor unusable for many applications.

**Comment by serkandurusoy** [comment]
In fact, I now believe this issue *must* be revisited due to current work by @stubailo on sql support and his comments about the accounts system being a unified one that is compatible with both sql and mongodb backends. This means support for integer autoincrement id's as well.

**Comment by jrothman** [comment]
+1 for native ObjectID support (ran into the same late-stage integration issues as several others above!)

**Comment by jbaviat** [comment]
+1

**Comment by timmaybrown** [comment]
+1 This should definitely be re-evaluated. @awatson1978 and @serkandurusoy have definitely presented some very articulate and well thought out set of use cases.

**Comment by austinrivas** [comment]
+1 this was the reason I stopped developing meteor apps almost 2 years ago, and it is still not resolved.

I am currently trying to build a prototype meteor app for a client that is very excited about using meteor, and now this is a blocker yet again. @awatson1978 and @serkandurusoy clearly demonstrated why this was an issue, so I will not rehash it.

**Comment by mediatainment** [comment]
...years later: +1 @awatson1978 and @serkandurusoy and all others.
I spent days to modify my rails apps to cooperate with meteor:
* It's own `Meteor.users`-schema. (solved)
* It's own version of BCRYPT password hashing with SHA256 (still try to deal this: http://stackoverflow.com/questions/35951065/meteor-authenticate-email-password-from-a-different-server-with-bcrypt)
* But with the handling of strings instead of ObjectIDs I ran into so many issues with my apps, who wanna connect to users. They are not searchable. If I would get this up and running, I have to rewrite ALL my search functions in all outside apps. 
The Users are THE CORE of nearby _any_ app. This single case keeps me out to use meteor in production. Only of the lack of "stringyfied" ids

Please make this working:

    Users = new Mongo.Collection('users', {idGeneration: 'MONGO'});

**Comment by engelgabriel** [comment]
We from https://github.com/RocketChat are working with MDG on a refactoring of the account package, and I'll ask @Sing-Li to take this into considerations. The main focus of the refactoring is to make it database agnostic, so it would be able to run in PostgreSQL.

If you are interest in helping out, please visit the new repository for the accounts package:
https://github.com/meteor/accounts

**Comment by XAOPT** [comment]
+1

**Comment by gabma** [comment]
+1 anybody got a working solution to share :/ ?

**Comment by austinrivas** [comment]
@gamba you can check out the Meatier project, a lot of the same functionality without the vendor lock in and mongodb...

https://github.com/mattkrick/meatier

**Comment by anymos** [comment]
+1

**Comment by semeano** [comment]
Oh wow. This is still an issue.

**Comment by maxkufner** [comment]
We are migrating away from meteor because of this, for what its worth!
