### ISSUE TITLE
Add minimongo support for $addToSet: { <field>: { $each: [ <value1>, <value2> ... ] } }                       }

### ISSUE THREAD

**Issue by frozeman** [meteor/meteor#1895]
Currently when inserting a document like described in the mongo docs:
http://docs.mongodb.org/manual/reference/operator/update/addToSet/#up._S_addToSet

                      {
                        $addToSet: { <field>: { $each: [ <value1>, <value2> ... ] } }
                      }

It adds me the following structure:

![screen shot 2014-03-07 at 15 12 09](https://f.cloud.github.com/assets/232662/2357741/f01cd102-a602-11e3-8298-1bfd0a2332a0.png)

p.s. i use blaze-rc0

**Comment by glasser** [comment]
I'm guessing this is fixed by b0e8968b.  Since @frozeman ignored our [guidelines for filing bugs](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor), there is no trivial way to automatically check to see if it is fixed, so I'm just going to close it on the assumption that maybe b0e8968b was related instead of actually checking.
