### ISSUE TITLE
[Blaze] event fire order does not match expected

### ISSUE THREAD

**Issue by alanning** [meteor/meteor#1957]
Event firing order difference between Blaze and previous Meteor versions.

Repro steps:
- Clone repo

```
$ git clone https://github.com/alanning/meteor-click-event-order-test.git
```
- Run pure jQuery app and click picture.
  `
  $ cd meteor-click-event-order-test/jqueryApp
  $ python webserver.py
  $ open http://localhost:8000/test.html
  `
- Verify browser console output:

```
  click child
  click parent
```
- Stop app
- Run app and click picture.
  `
  $ cd ../meteorApp
  $ meteor --release 0.7.2
  `
- Verify browser console output:

```
  click child
  click parent via rendered
  click parent via event
```
- Stop app
- Run app and click picture.
  `
  $ meteor --release 0.8.0-rc1
  `
- Verify browser console output:

```
click parent via rendered
click child
click parent via event 
```

**Comment by hwillson** [comment]
There is a reason for the behavior outlined in the original issue (Blaze switched from using its own home-brewed event delegation to jQuery's). Quite a bit of time has passed since the last comment on this issue, and the lack of +1's to look into improving this leads me to believe people have gotten used to the caveats of Blaze's current jQuery based event delegation model (we've had a few years to adapt :-)). I vote to close this issue - thanks!

**Comment by abernix** [comment]
Agree.  Thanks, @hwillson.
