### ISSUE TITLE
Better error needed for attempting to login before service configuration is loaded

### ISSUE THREAD

**Issue by timhaines** [meteor/meteor#2048]
In the various requestCredential functions (i.e. for Facebook and twitter), there's code like this:

```
  var config = ServiceConfiguration.configurations.findOne({service: 'twitter'});
  if (!config) {
    credentialRequestCompleteCallback && credentialRequestCompleteCallback(new ServiceConfiguration.ConfigError("Service not configured"));
    return;
  }
```

It should be updated to check for whether the configuration has finished loading yet (something like checking Accounts.loginServicesConfigured()), and should show a more informative error if the requestCredentials function was invoked before the configuration subscription was ready.  Something along the lines of "Configuration subscription not ready" rather than "Service not configured".

**Comment by danlg** [comment]
The issue of google auth has been driving me crazy for hours and days of debugging as the behaviour is not reproducible.  I suspect a very subtle file load order issue. The error I get is ONLY on iOS device or simulator "Login service configuration not yet loaded: undefined" . This works fine when deploying to the web.
Definitely the project of the Meteor GUIDE http://info.meteor.com/blog/meteor-guide-interview is VERY WELCOME as advanced docs for best practice are definitely lacking.

Previous code which I though was working using meteor 1.1.0.3 and thought the regression was due to the zillions change on cordova when upgrade to meteor 1.2 are actually not working. The debugging of cordova app (especially IOS) is a real pain as there is virtually 0 error messaging even using the iOS simulator which is supposed to be working see https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients

The promise of meteor cannot be held if such basic things are so time consuming and prevent to focus on the business logic. Thanks for your support. Please reopen.

**Comment by talha-asad** [comment]
Simply put you can use: `Accounts.loginServicesConfigured()`

It's a reactive source. It needs to be documented on the accounts page though.

**Comment by abernix** [comment]
@talha-asad A PR to the Docs repo would be very much appreciated if this is the case.  We want these things to be fixed for the next users, so even an issue [over there](https://github.com/meteor/docs/issues) is great).

(If you can't explain it perfectly, for `docs` issues, even a PR with some of the work done is a great start for someone to pick it up and finish!)
