### ISSUE TITLE
node 0.11 / es6 support

### ISSUE THREAD

**Issue by tjwebb** [meteor/meteor#2310]
I can't find any information on node 0.11 or es6/harmony support, so I'm not sure whether it exists, if its planned, not planned, etc. What are the team's plans?

**Comment by dandv** [comment]
Any updates on this? Tried to use execSync, which was [introduced in v0.12](https://strongloop.com/strongblog/whats-new-in-node-js-v0-12-execsync-a-synchronous-api-for-child-processes/). [v0.12.0 stable was released on Feb 6](http://nodejs.org/changelog.html).

**Comment by glasser** [comment]
We typically don't try to upgrade to the `*.0` version of Node, since they tend to be the most buggy.  We're tracking plans to upgrade to 0.12 (or io) in #3666.

For what it's worth, I wouldn't recommend using execSync in anything other than the equivalent of shell scripts: it ties up the whole event loop and destroys concurrency.

**Comment by dandv** [comment]
Thanks, will follow that ticket.

I wanted to use `execSync` in `Package.js` to call `npm` and get the version of the 3rd party library we're wrapping [in case package.json isn't available](https://github.com/MeteorPackaging/discussions/issues/8#issuecomment-74211524). Using plain `exec` with `Package.describe` in the callback didn't work because Meteor code needed to be run in a Fiber. However, the `Meteor` object isn't available in package.js, to use bindEnvironment or wrapAsync.

Another avenue I've looked at was an [HTTP request to the NPM registry API](http://registry.npmjs.org/summernote/latest), but the same problems apply.

**Comment by tjwebb** [comment]
> I wanted to use execSync in Package.js to call npm

`npm` has its own API that you should use via `require('npm')`

> We typically don't try to upgrade to the *.0 version of Node

meteor has existed through how many *.0 node releases? My main purpose in filing this thread was to discuss es6 support, which *just happened to be* in node 0.11, and see if the meteor team could publish any sort of public plans or roadmap.

**Comment by dandv** [comment]
> npm has its own API that you should use via require('npm').

How can I query the latest version of an arbitrary package using that API?

> As @glasser said, you should never ever use any *Sync method in a web server.

Is `package.js` a web server? I've used readFileSync [just fine](https://github.com/dandv/meteor-webix/blob/master/package.js#L6).

**Comment by tjwebb** [comment]
> How can I query the latest version of an arbitrary package using that API?

I am not the npm documentation thank you very much. I trust that you're capable of googling that sort of thing. My point is that you can and should interact with npm through its API, and not use execSync as a sledgehammer to solve this kind of problem.

**Comment by dandv** [comment]
We should probably move this discussion elsewhere. My point is that the [npm API](https://docs.npmjs.com/api/npm) doesn't allow the kind of querying that I want to do.

**Comment by tjwebb** [comment]
Yea we're off topic because the problem you're trying to solve with execSync doesn't actually exist.

>> How can I query the latest version of an arbitrary package using that API?
> My point is that the npm API doesn't allow the kind of querying that I want to do.

The npm API does everything that npm does. npm *uses its own API*. If it's possible on the command line, it's possible in the API. If you're just trying to get the latest version of a package, all you have to do is `npm.view("somePackage")`.

> If no version is specified, "latest" is assumed.

If you have any more npm-related questions, you should continue in npm/npm.
