### ISSUE TITLE
synchronous return point for observeChanges/insert/etc doesn't work reentrantly

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#2315]
In minimongo, several methods have a contract about what observe callbacks will be invoked before they synchronously return.  For example, observeChanges invokes all the initial adds before returning; and insert/update/remove/resumeObservers invokes all affected observe callbacks before returning.

This is implemented by passing all observe callbacks through a Meteor._SynchronousQueue and calling drain() from within those functions.

However, drain() returns immediately when itself called from a task on the same queue (eg, if observeChanges or insert is called from an observe callback).  That means that in this case, the methods don't wait at all like they should.

**Comment by mitar** [comment]
How is this progressing?

**Comment by glasser** [comment]
Hoping to work on it soon if time allows. Of course as you know there are lots of Mongo-related issues worth looking at :)

**Comment by mitar** [comment]
I think that issues with unable to use Meteor.setTimeout inside observe is the biggest issue. So that after a client side method is run, it keeps running inside a noYieldAllowed.

**Comment by glasser** [comment]
Unfortunately, it doesn't look like I got to this as part of the 1.0.4 maintenance work.

**Comment by mitar** [comment]
Noooo. :-( Ah, why I reported all those nonimportant Minimongo stuff when this is the biggest issue.

**Comment by glasser** [comment]
I'm curious what your reason for caring about this one is — is it mostly what you discussed on #3597 about how it makes client and server less isomorphic?

**Comment by glasser** [comment]
Or I guess mostly because of #2691?

**Comment by mitar** [comment]
It is #2691. We use global observes on the client which call into complex code to react to changes to data. But now when we use latency compensation on the client, that complex code is failing regularly when there is this leaking of the context mentioned above. So this is failing in the current codebase. (Workaround are using `setTimeout` (not `Meteor.setTimeout`) to escape the context. And also to use `Tracker.nonReactive`. But this is really ugly and it makes things unclear why are necessary.)

#3597 is something we are not yet using, as it is not yet fixed. That is more for the future. I have an initial implementation of server-side Tracker but I stopped working on that because I am waiting for these fixes first. But this is not yet so critical. It is more just to report everything so that things will get fixed eventually.

**Comment by mitar** [comment]
So the main issue is that the observe callback gets called in the context where insert was called on the client (#2691). The order of things (#3597) is less important.

**Comment by mitar** [comment]
My temporary workaround:

```coffee
queue = new Meteor._SynchronousQueue()

originalObserveChanges = LocalCollection.Cursor::observeChanges
LocalCollection.Cursor::observeChanges = (callbacks) ->
  for own name, callback of callbacks
    do (name, callback) ->
      callbacks[name] = (args...) ->
        queue.queueTask ->
          callback args...

  originalObserveChanges.call @, callbacks

originalObserve = LocalCollection.Cursor::observe
LocalCollection.Cursor::observe = (callbacks) ->
  for own name, callback of callbacks
    do (name, callback) ->
      callbacks[name] = (args...) ->
        queue.queueTask ->
          callback args...

  originalObserve.call @, callbacks
```

**Comment by avital** [comment]
If and when this gets resolved by running observe callbacks asynchronously when calling Minimongo mutators, please make sure to remove `wrapNotInMethodStub` from package/minimongo/minimongo.js (there's a comment linking to this issue in that file).

The test in packages/minimongo/call_in_observe_test.js should still stick around, and should still pass.

**Comment by hwillson** [comment]
While we could consider keeping this open for another 4 years, I think at this point we're safe to close it off. While this is still a potential issue, it's not that common, and a proper fix for this is not trivial. Workarounds exist (https://github.com/meteor/meteor/issues/2315#issuecomment-84482790), so unless anyone feels strongly otherwise, I'll close this off. That being said, if someone stumbles across this issue in the future and is interested in working on a proper fix, please let us know. Thanks!
