### ISSUE TITLE
Curl install command fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by manaberg** [meteor/meteor#245]
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Is the error I get when trying to install meteor in my Ubuntu through this command

curl https://install.meteor.com | /bin/dash

**Comment by rudolfbyker** [comment]
Why is this closed?
Upgrading an operating system that is widely used and still being supported (Ubuntu 12.04) is not a solution to the problem, nor a feasible workaround for most people.

**Comment by jhgaylor** [comment]
The issue you're having is that curl isn't finding your ssl certificates. You'll need to fix that before the install will work over https.

**Comment by deprosun** [comment]
for debian people, you may not have /etc/pki/tls/ directory. create it. then create /etc/pki/tls/certs/. Then cd into it. then run this command: sudo cp /etc/ssl/certs/ca-certificates.crt ca-bundle.crt. UBUNTU GNOME 14.04

**Comment by staminaloops** [comment]
@deprosun Thank you! It worked.

**Comment by deprosun** [comment]
Glad! :)

**Comment by pengubco** [comment]
@deprosun great answer! I got a similar problem when I use 'cur https://... | ...". Thank you.

**Comment by pheer** [comment]
Is anyone still running into this?  I've tried all the suggestions without any success.  On trusty64 VM.

ubuntu-trusty-64:~$ /usr/bin/curl https://install.meteor.com | /bin/sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6121    0  6121    0     0    951      0 --:--:--  0:00:06 --:--:--  1245
Downloading Meteor distribution
############                                                              17.9%tar: Skipping to next header
####################                                                      28.1%tar: Exiting with failure status due to previous errors

curl: (23) Failed writing body (1040 != 16384)
Installation failed.

**Comment by guiambros** [comment]
@deprosun Thanks! This finally solved my problems with curl/openssl.

**Comment by Shaunakde** [comment]
I had to copy the 'ca-bundle.crt' file to '/etc/pki/tls/certs/'
