### ISSUE TITLE
Allow a way to delete or deprecate packages/versions of packages

### ISSUE THREAD

**Issue by matteodem** [meteor/meteor#2459]
Is it now possible to remove packages from the atmosphere / meteor servers without leaving any traces anywhere? I got a lot of deprecated ones that I'd like to get rid off.

Using 0.9.0

**Comment by matteodem** [comment]
Any news on this?

**Comment by glasser** [comment]
We agree that being able to delete or deprecate packages and versions is a useful feature. For more information on how we evaluate feature requests, see [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/2459#issuecomment-54230786, the current approach to deprecating packages involves publishing a new version of the package that identifies the package has been deprecated, in some way. If anyone is looking for an example of this, take a look at the deprecated Meteor core package [`code-prettify`](https://github.com/meteor/meteor/tree/a9cd336ed551ce70d1862c53cc84ce62746ec8b6/packages/deprecated/code-prettify) (the latest/last version contains a single [`deprecated.js`](https://github.com/meteor/meteor/blob/a9cd336ed551ce70d1862c53cc84ce62746ec8b6/packages/deprecated/code-prettify/deprecated.js) file, that dumps a deprecation message to the console when used).

Since this issue hasn't received much attention in >2 years, and the above method of deprecating packages is pretty widely used / accepted, I'll close this issue for now. Thanks!
