### ISSUE TITLE
Allow dashes in Meteor Developer Account usernames

### ISSUE THREAD

**Issue by nathan-muir** [meteor/meteor#2487]
**_1 Upvote**_ I'm not going to make a huge case for this, except to say that github usernames allow dashes, and it would be mightily convenient if the two could line up.

For the record, github account names:
- Allow any alphanumeric [capitals included]
- Allow dashes, but must not start with dashes
- Work case-insensitive [ https://github.com/Nathan-Muir == https://github.com/nathan-muir ]

**Comment by hwillson** [comment]
Since the level of interest in this issue is quite low, and there hasn't been any activity in a few years, I think we're safe to close this issue off. Just to add - Meteor Developer Account's aren't managed as part of the Meteor project itself, so this type of request is likely better handled elsewhere. Thanks for suggesting this originally!
