### ISSUE TITLE
Environment variable PACKAGE_DIRS

### ISSUE THREAD

**Issue by zoowar** [meteor/meteor#2496]
Consider deprecating PACKAGE_DIRS in favor of something more meteor specific to avoid environment variable name clashes. For example, METEOR_PACKAGE_DIRS

**Comment by digitalsanity** [comment]
Instead of using PACKAGE_DIRS, try symlinks.

I have a directory next to my projects that is called "meteor-hot", where I clone any projects that need modification.  Then just symlink within packages/ --  i.e. meteor-admin -> ../../meteor-hot/meteor-admin-dev.

Using symlinks lets the changes get picked up and are reflected immediately.

**Comment by zoowar** [comment]
@digitalsanity What problem are you trying to solve? What you describe works equally well by changing the environment variable.

**Comment by dcsan** [comment]
using symlinks is more explicit - it should be more obvious which version of a package is getting used.
also, when deploying (at least to meteor.com) the bundling process will pick up those versions of packages (maybe this works with PACKAGE_DIRS too?)
