### ISSUE TITLE
Wouldn't it make more sense for force-ssl to redirect with a 301 instead of a 302?

### ISSUE THREAD

**Issue by mjgallag** [meteor/meteor#2503]
https://github.com/meteor/meteor/blob/devel/packages/force-ssl/force_ssl_server.js#L50

**Comment by abernix** [comment]
Stumbled upon this.  This is incredibly old, and I'm not proposing to change this, but I'll just leave Google's ["Best practices when using HTTPS"](https://support.google.com/webmasters/answer/6073543?hl=en) here:

> Redirect your users and search engines to the HTTPS page or resource with server-side 301 HTTP redirects

In general, I'm not sure it matters.

**Comment by mjgallag** [comment]
@abernix I'm not sure if Google had yet explicitly recommended `301` from `http` to `https` way back when I logged this issue, thanks for the update!

**Comment by glasser** [comment]
For what it's worth, I personally (and I think this is shared by others at MDG) no longer think that `force-ssl` is solving the problem at the right layer. It makes more sense to do HTTP redirection in the layer of your production service that actually handles HTTPS certs (which Meteor doesn't) rather than in the app itself.   This would also mean that the decisions about whether or not to redirect would be made directly based on "am I receiving this message over my HTTPS port" rather than parsing headers (eg #6120) and guessing to see if we're in dev mode (though that issue has been mostly resolved recently, thanks).  For example, for Galaxy users we recommend people use Galaxy's force SSL feature (which is implemented inside our proxy) instead of the force-ssl package.

And for what it's worth, we decided to use 301 in Galaxy :)

**Comment by hwillson** [comment]
So, what's the general consensus here guys - keep this issue open and get the 302 to 301 change in place, or leave things as is (since the impact of this issue is quite low, and the `force-ssl` README has been updated to mention a better approach for handling HTTP redirection)?

**Comment by abernix** [comment]
I'm going to close this with no change.

Both 301 and 302 redirects would work fine, but since `force-ssl` is no longer the recommended approach for implementing the SSL redirect, I think it could it be argued that this is better left off as a temporary redirect (302) since this might be used for testing (pre-deployment).

To further clarify the "temporary" aspect of this header, a 301 redirect is [cached indefinitely by some browsers](https://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s) and should be implemented by someone who knows what they're doing.  For example, this might involve adding custom `Cache-Control` headers that provide some definition to the cache duration.  It's important that care is taken here, and to allow room for error I think this packages implementation should be left as "temporary", even if the ideal situation would be a permanent redirect with cache headers (harder to implement with such a simple package).
