### ISSUE TITLE
Package System Support for Corporate Firewall Configurations

### ISSUE THREAD

**Issue by jmanos3** [meteor/meteor#2515]
With the new packaging system in 0.9.0, the 'meteor add' and 'meteor search' commands fail to work when behind a corporate firewall.  When issuing the commands, I am receiving the message that the server could not be reached at wss://packages.meteor.com/websocket.

I had to setup my HTTP_PROXY / HTTPS_PROXY shell environment variables so that the 'curl' command would work when installing meteor.  However, I have not been able to find a means of telling the DDP configuration to use the corporate proxy.

Working from the understanding that DDP is using SOCKS, I did try setting up the environment variable SOCKS_PROXY which did not affect the results.  I also looked at the meteor code and confirmed that SOCKSJS was being used also.

**Comment by liuxihua** [comment]
when i install the bootstrap with meteor in windows 7. And, i worked behind a proxy, and i already do as what https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy said.

when i use "meteor update", it works fine,

when I install packages , got a error like below :

    C:\Studio\microscope>meteor add  twbs:bootstrap@3.3.6
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

 => Errors while adding packages:

While downloading twbs:bootstrap@3.3.6...:
error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

Your package catalog may be out of date.
Please connect to the internet and try again.


when i use npm it works fine, because i set the proxy and set the "strict-ssl = false" also in the npm config (.npmrc).

So what should i do to fix this problem, thanks

**Comment by RafaelOrtiz** [comment]
Hi all not sure if its enterely related to this issue but I-m facing a wierd behavior whuile trying to install meteor behing a Corp environment, i manage to set up the proxy and package download and installation start, meteor shows a progress bar....after a while the progrss bar disappears and the process gets stalled. 
any idea how i may fis this ?
