### ISSUE TITLE
Inconsistent field names in ServiceConfiguration.configurations

### ISSUE THREAD

**Issue by adamgins** [meteor/meteor#2562]
I am using Meteor 0.9.2 rc-3

I have a pretty simple app with not much in it and I was just tesing out some of the basic Cordova stuff, which works.

If i try and login via the browser (Chrome on the desktop). The Facebook login is configured via:

```
ServiceConfiguration.configurations.remove({
 service: "facebook"
 });

 ServiceConfiguration.configurations.insert({
 service: "facebook",
 clientId: "XXXXXXXX",
 secret: "YYYYYYYYYY"
 });
```

that seems to work as I can click on the login screen.

After that I just get a blank pop-up and do not get prompted to login. There does not seem to be anything on the server log/console or browser console.(ie blank)

I have a similar setup for accounts-google and it all works fine. 

Any thoughts?

**Comment by hwillson** [comment]
Hi all - given that:

- This isn't a bug
- People have had years to get used to the `appId` / `clientId` naming differences
- This issue has received very little attention/support in over 2 years

As part of the on-going old issue cleanup process, I'll close this issue. Happy to re-open if anyone feels otherwise - thanks for reporting this originally!
