### ISSUE TITLE
Meteor show output follows unclear/unexplained rules with regards to architectures

### ISSUE THREAD

**Issue by tanis2000** [meteor/meteor#2568]
It would be nice to have a command to check which architectures are available for a certain package.
Something like meteor archs package@version 

The same information should be shown when doing meteor show package@version

**Comment by glasser** [comment]
Hmm, this was actually made less visible in 1.0.3.1 (architectures are now only visible with `show --ejson`).

**Comment by hwillson** [comment]
There are a few different issues outlined in this issue thread, so I'll just focus on the main/original issue (*Meteor show output follows unclear/unexplained rules with regards to architectures*). The other issues can be (and probably are) opened in separate issues if anyone would like to see them preserved. 

As mentioned in https://github.com/meteor/meteor/issues/2568#issuecomment-72787790, `meteor show` no longer shows any architecture details unless the `--ejson` option is included. That being said, the Meteor Tool CLI help explains this fairly well, and the architecture details shown when running `meteor show --ejson` are very clear (and well formatted). For example:

**`meteor show --ejson meteor-tool@1.4.2_3`**

```json
{                                             
  "exports": [],
  "implies": [],
  "dependencies": [],
  "name": "meteor-tool",
  "version": "1.4.2_3",
  "description": "[Source code of released version](https://github.com/meteor/meteor/tree/master/packages/meteor-tool) | [Source code of development version](https://github.com/meteor/meteor/tree/devel/packages/meteor-tool)\n***\n\nThis is the Meteor command-line tool. Most of the code for it is in the [tools directory](https://github.com/meteor/meteor/tree/master/tools) of the Meteor repository.\n\nThe Meteor tool also includes testing functionality and example apps for the Meteor framework.\n\nRead more about it on the [project page](https://www.meteor.com/tool)",
  "summary": "The Meteor command-line tool",
  "git": null,
  "publishedBy": "benjamn",
  "publishedOn": {
    "$date": 1479409717421
  },
  "installed": true,
  "architecturesOS": [
    "os.linux.x86_32",
    "os.linux.x86_64",
    "os.osx.x86_64",
    "os.windows.x86_32"
  ]
}
```

I believe this addresses the issues outlined in https://github.com/meteor/meteor/issues/2568#issuecomment-55182715 quite well, which represents the main issue in this thread. Given this (and the age of this issue), I think it's safe to close this issue off. Let me know if anyone feels otherwise - thanks!
