### ISSUE TITLE
Cannot log Meteor.Error

### ISSUE THREAD

**Issue by zol** [meteor/meteor#2589]
In the browser console, type: `Log.error(new Meteor.Error('wtf'))`. An exception is thrown, `Error: 'time' must be a Date object`.

**Comment by hwillson** [comment]
Hi guys - I know this is an old one, but it's still a valid issue. This problem is caused when the `Meteor.Error` object (passed in as `obj`) is cloned within the `Log.format` function [here](https://github.com/meteor/meteor/blob/8e32da57a128a70fdc09823b5d506758ce6a9b82/packages/logging/logging.js#L188):

```js
Log.format = function (obj, options) {
  obj = EJSON.clone(obj); // don't mutate the argument
  options = options || {};

  var time = obj.time;
  if (!(time instanceof Date))
    throw new Error("'time' must be a Date object");
...
```

`Meteor.Error`'s have their own `clone` function defined [here](https://github.com/meteor/meteor/blob/8e32da57a128a70fdc09823b5d506758ce6a9b82/packages/meteor/errors.js#L105-L108), that when called creates a new `Meteor.Error` object. When the `EJSON.clone` call above calls the `Meteor.Error` clone function, a new object is returned that no longer has the needed `time` property.

A quick fix for this is to wipe the clone function before attempting to log the `Meteor.Error`:

```js
const someError = new Meteor.Error('Oh no!');
someError.clone = null;
Log.error(someError);
```

As for addressing this issue in the `logging` package, this is definitely a bit of an edge case. You would usually expect that all properties that are part of an object would be cloned when calling `EJSON.clone`; it just so happens in this case however that `Meteor.Error` is using a custom `clone` function that will only copy over certain properties. I don't think there's much value in updating the `logging` package to handle this edge case, especially since this can be worked around in application code.

Given the above, I'll close this for now. Happy to re-open if anyone feels differently. Thanks!
