### ISSUE TITLE
Blaze, meteor's templates, are not usable with polymer's templates

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#2765]
**_8 Upvotes**_ Is there any example of how Polymer can be used in a meteor app?

I'm getting various errors e.g. : `Template has no 'name' attribute`

**Comment by Slava** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).


Honestly, I think this is a good direction, Blaze should be simple and easy to use in a mix with other templating systems like Polymer or Angular. I don't know if configuring the spacebars compiler to use a different syntax for Blaze templates is a good idea.

In my ideal world, everyone who wants to mix templates should write a separate build plugin for the new templating system that is handled by your packages from start to finish. It would make it kinda hard to mix data-bindings of Blaze inside, say, Polymer components, but it looks like a cleaner separation.

**Comment by lutzleonhardt** [comment]
+1

**Comment by apalgen** [comment]
+1

**Comment by Pickachu** [comment]
:+1:

**Comment by rapito** [comment]
+1

**Comment by GuillaumeM69** [comment]
+1

**Comment by mitar** [comment]
Also with 1.0 version?

**Comment by mitar** [comment]
There are much less invasive with 1.0 version.

**Comment by AndreasGalster** [comment]
+1 for this. Also, this is not about Polymer. It's about template tags in general, which is part of the HTML specs. Polymer comes with several helpers that extend the standard template tag to do certain functions inside and outside of a custom element, which is why sometimes you would want to define template tags in a Blaze template, which currently is not possible.

**Comment by justinfagnani** [comment]
There's rarely a good reason to generate custom element definitions. If you're trying to dynamically generate an element you've probably just not parameterized the element enough. Keep elements static and you'll never have a problem of clashing template syntaxes. You can generate things at the element usage site, just not the definition.

**Comment by sujith3g** [comment]
[Here](https://github.com/meteorwebcomponents) is an attempt to make polymer-1.0 work with meteor using separate [compiler](https://github.com/meteorwebcomponents/compiler) and [layout-manager](https://github.com/meteorwebcomponents/layout)

**Comment by apalgen** [comment]
All in all it's not the user friendliest way to bring Meteor and Polymer together. I would like to replace Blaze with Polymer completely. There are so many ways to use React with Meteor, but Polymer seems not to be very imported in the Meteor universe. There are many attempts, but no real solution. And so the search for the "holy grail" continues...

**Comment by justinfagnani** [comment]
I'm curious, why are you trying to dynamically generate element definitions?

**Comment by AndreasGalster** [comment]
I'm not exactly sure what you're referring to @justinfagnani . I don't see any point why it shouldn't be possible to define templates within templates though. Templates also have nothing to do with element definitions.

**Comment by justinfagnani** [comment]
Forgive me if I'm confusing things, I'm just poking around issues people are having with Polymer and other frameworks and trying to understand them.

It seemed like there was a conflict between Meteor's handling of `<template>` and standard client-side usage of `<template>`. I could be understanding this wrong, but if that's the case, what I'm asking is why Polymer element definitions, which use a `<template>` tag, are even being passed through the Meteor template system. Can HTML modules not bypass Meteor's processing altogether?

**Comment by AndreasGalster** [comment]
Yes, if you define custom elements in Polymer which use templates, then you're all good. However, there are a few reasons why you may wanna use templates in a meteor template, with or without Polymer.

First obvious reason is simply stamping out templates, which I personally have never done though. However, what if you want to do something like a template with dom-bind in case you want to use polymer databindings outside of a polymer element? I know this will also generate issues with the curly braces syntax even if templates were to work as expected.

Personally for me that's not an issue since I just define one big view custom-element for each view anyway due to other incompatabilities with meteor though (haven't checked lately but I'm guessing webcomponents-lite/polymer is still going to break with meteor's way of injecting new elements into a page).

Imo this is not a Polymer specific issue though. Templates are part of the spec and it should be possible with Meteor to define a template within a meteor specific template without breaking the app.

**Comment by HedCET** [comment]
advise to look https://github.com/meteorwebcomponents

**Comment by brylie** [comment]
Please support web component alignment in Blaze 2. See issue #6236.

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#187. Closing this one - thanks!
