### ISSUE TITLE
meteor.local doesn't work on old Androids (2.x)

### ISSUE THREAD

**Issue by raix** [meteor/meteor#2822]
Hi,

I've just tried `meteor create --example todos` to see the new example, looks sweet :)

I just wanted to see it running on my android device too, `$ meteor run android-device`, but no luck - the app starts on the android but says that it cannot find the webpage "http://meteor.local"

Now in the docs it states that meteor will autodetect the local server adr + port, but I have used `--mobile-server` flag pointing to `ip:3000` and later `http://ip:3000` *(where "ip" is the local static ip)*

I can access the example via the android browser, so its on the same network etc.

Its on mac os x, android 2.3.4, meteor 0.9.4

Let me know how I can provide replication or logs

**Comment by ansarizafar** [comment]
@Slava I am facing the same issue. Is there any solution available?

**Comment by Weijtmans** [comment]
Same here, any updates?

**Comment by jlourenco** [comment]
Same here with android 2.3.3

Log:

03-11 18:19:02.524: I/CordovaLog(6690): Changing log level to DEBUG(3)
03-11 18:19:02.534: I/CordovaLog(6690): Found start page location: index.html
03-11 18:19:02.534: D/Whitelist(6690): Unlimited access to network resources
03-11 18:19:02.534: D/CordovaActivity(6690): CordovaActivity.onCreate()
03-11 18:19:02.544: I/dalvikvm(6690): Could not find method android.webkit.WebView.<init>, referenced from method org.apache.cordova.CordovaWebView.<init>
03-11 18:19:02.544: W/dalvikvm(6690): VFY: unable to resolve direct method 442: Landroid/webkit/WebView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;IZ)V
03-11 18:19:02.544: D/dalvikvm(6690): VFY: replacing opcode 0x70 at 0x0001
03-11 18:19:02.544: D/dalvikvm(6690): VFY: dead code 0x0004-0046 in Lorg/apache/cordova/CordovaWebView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;IZ)V
03-11 18:19:02.544: I/dalvikvm(6690): Could not find method org.apache.cordova.CordovaWebView.setWebContentsDebuggingEnabled, referenced from method org.apache.cordova.CordovaWebView.setup
03-11 18:19:02.544: W/dalvikvm(6690): VFY: unable to resolve static method 5071: Lorg/apache/cordova/CordovaWebView;.setWebContentsDebuggingEnabled (Z)V
03-11 18:19:02.544: D/dalvikvm(6690): VFY: replacing opcode 0x71 at 0x00be
03-11 18:19:04.014: D/CordovaWebView(6690): CordovaWebView is running on device made by: Sony Ericsson
03-11 18:19:04.024: D/JsMessageQueue(6690): Set native->JS mode to 2
03-11 18:19:04.034: I/CordovaWebView(6690): Disabled addJavascriptInterface() bridge since Android version is old.
03-11 18:19:04.044: I/dalvikvm(6690): Could not find method android.content.Intent.setSelector, referenced from method org.apache.cordova.CordovaUriHelper.shouldOverrideUrlLoading
03-11 18:19:04.044: W/dalvikvm(6690): VFY: unable to resolve virtual method 124: Landroid/content/Intent;.setSelector (Landroid/content/Intent;)V
03-11 18:19:04.044: D/dalvikvm(6690): VFY: replacing opcode 0x6e at 0x0052
03-11 18:19:04.044: D/dalvikvm(6690): VFY: dead code 0x0055-005e in Lorg/apache/cordova/CordovaUriHelper;.shouldOverrideUrlLoading (Landroid/webkit/WebView;Ljava/lang/String;)Z
03-11 18:19:04.054: D/CordovaActivity(6690): CordovaActivity.init()
03-11 18:19:04.394: D/dalvikvm(6690): GC_CONCURRENT freed 128K, 51% free 2708K/5447K, external 3562K/4448K, paused 119ms+6ms
03-11 18:19:04.674: D/CordovaWebView(6690): >>> loadUrl(file:///android_asset/www/index.html)
03-11 18:19:04.674: D/PluginManager(6690): init()
03-11 18:19:05.604: D/CordovaWebView(6690): >>> loadUrlNow()
03-11 18:19:05.674: I/CordovaLog(6690): Changing log level to DEBUG(3)
03-11 18:19:05.744: I/CordovaLog(6690): Found start page location: index.html
03-11 18:19:05.744: D/Whitelist(6690): Unlimited access to network resources
03-11 18:19:05.744: D/CordovaActivity(6690): Resuming the App
03-11 18:19:05.744: D/CordovaActivity(6690): CB-3064: The errorUrl is null
03-11 18:19:05.764: D/CordovaActivity(6690): Paused the application!
03-11 18:19:05.764: D/CordovaWebView(6690): Handle the pause
03-11 18:19:06.404: D/SoftKeyboardDetect(6690): Ignore this event
03-11 18:19:06.444: D/CordovaWebViewClient(6690): onPageStarted(file:///android_asset/www/index.html)
03-11 18:19:06.444: D/CordovaActivity(6690): onMessage(onPageStarted,file:///android_asset/www/index.html)
03-11 18:19:06.454: D/SoftKeyboardDetect(6690): Ignore this event
03-11 18:19:07.044: D/CordovaLog(6690): undefined: Line 1 : exception firing pause event from native
03-11 18:19:07.044: I/Web Console(6690): exception firing pause event from native at undefined:1
03-11 18:19:07.414: D/CordovaWebViewClient(6690): onPageFinished(file:///android_asset/www/index.html)
03-11 18:19:07.414: D/CordovaActivity(6690): onMessage(onPageFinished,file:///android_asset/www/index.html)
03-11 18:19:07.764: W/CordovaPlugin(6690): Attempted to send a second callback for ID: StatusBar1760506083
03-11 18:19:07.764: W/CordovaPlugin(6690): Result was: "Invalid action"
03-11 18:19:07.774: D/CordovaActivity(6690): onMessage(spinner,stop)
03-11 18:19:07.854: W/PluginManager(6690): THREAD WARNING: exec() call to File.requestAllPaths blocked the main thread for 32ms. Plugin should use CordovaInterface.getThreadPool().
03-11 18:19:07.874: W/System.err(6690): java.io.FileNotFoundException
03-11 18:19:07.874: W/System.err(6690): 	at org.apache.cordova.file.LocalFilesystem.getEntryForLocalURL(LocalFilesystem.java:138)
03-11 18:19:07.874: W/System.err(6690): 	at org.apache.cordova.file.FileUtils.resolveLocalFileSystemURI(FileUtils.java:617)
03-11 18:19:07.874: W/System.err(6690): 	at org.apache.cordova.file.FileUtils.access$300(FileUtils.java:52)
03-11 18:19:07.874: W/System.err(6690): 	at org.apache.cordova.file.FileUtils$13.run(FileUtils.java:374)
03-11 18:19:07.874: W/System.err(6690): 	at org.apache.cordova.file.FileUtils$24.run(FileUtils.java:540)
03-11 18:19:07.874: W/System.err(6690): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
03-11 18:19:07.874: W/System.err(6690): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
03-11 18:19:07.874: W/System.err(6690): 	at java.lang.Thread.run(Thread.java:1019)
03-11 18:19:07.894: D/CordovaLog(6690): file:///android_asset/www/meteor_cordova_loader.js: Line 12 : METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.id2oqotb1sgzs8odl2sma/files/meteor/version
03-11 18:19:07.894: I/Web Console(6690): METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.id2oqotb1sgzs8odl2sma/files/meteor/version at file:///android_asset/www/meteor_cordova_loader.js:12
03-11 18:19:07.894: D/CordovaLog(6690): file:///android_asset/www/meteor_cordova_loader.js: Line 12 : METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.
03-11 18:19:07.894: I/Web Console(6690): METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets. at file:///android_asset/www/meteor_cordova_loader.js:12
03-11 18:19:07.904: W/meteor.cordova.updater(6690): startServer(/android_asset/www/application/,/android_asset/www/)
03-11 18:19:07.904: W/meteor.cordova.updater(6690): Filesystem root not found; falling back to assets: /android_asset/www/application/
03-11 18:19:07.904: D/meteor.cordova.updater(6690): Doing assetManager list on www
03-11 18:19:08.024: W/PluginManager(6690): THREAD WARNING: exec() call to CordovaUpdate.startServer blocked the main thread for 121ms. Plugin should use CordovaInterface.getThreadPool().
03-11 18:19:08.024: D/CordovaLog(6690): file:///android_asset/www/meteor_cordova_loader.js: Line 12 : METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
03-11 18:19:08.034: I/Web Console(6690): METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local at file:///android_asset/www/meteor_cordova_loader.js:12
03-11 18:19:08.034: D/CordovaWebViewClient(6690): onPageStarted(http://meteor.local/)
03-11 18:19:08.034: D/CordovaActivity(6690): onMessage(onPageStarted,http://meteor.local/)
03-11 18:19:08.464: D/CordovaWebViewClient(6690): CordovaWebViewClient.onReceivedError: Error code=-2 Description=Não foi possível localizar o URL. URL=http://meteor.local/
03-11 18:19:08.464: D/CordovaActivity(6690): onMessage(onReceivedError,{"errorCode":-2,"url":"http:\/\/meteor.local\/","description":"Não foi possível localizar o URL."})
03-11 18:19:08.464: D/CordovaWebViewClient(6690): onPageStarted(http://meteor.local/)
03-11 18:19:08.464: D/CordovaActivity(6690): onMessage(onPageStarted,http://meteor.local/)
03-11 18:19:08.574: D/CordovaWebViewClient(6690): onPageFinished(http://meteor.local/)
03-11 18:19:08.574: D/CordovaActivity(6690): onMessage(onPageFinished,http://meteor.local/)
03-11 18:19:09.424: D/CordovaActivity(6690): onMessage(spinner,stop)
03-11 18:22:25.214: I/CordovaLog(6690): Changing log level to DEBUG(3)
03-11 18:22:25.214: I/CordovaLog(6690): Found start page location: index.html
03-11 18:22:25.214: D/Whitelist(6690): Unlimited access to network resources
03-11 18:22:25.214: D/CordovaActivity(6690): Resuming the App
03-11 18:22:25.214: D/CordovaActivity(6690): CB-3064: The errorUrl is null
03-11 18:22:25.224: D/CordovaLog(6690): undefined: Line 1 : exception firing resume event from native
03-11 18:22:25.224: I/Web Console(6690): exception firing resume event from native at undefined:1
03-11 18:22:25.414: D/CordovaActivity(6690): Paused the application!
03-11 18:22:25.414: D/CordovaWebView(6690): Handle the pause
03-11 18:22:25.424: D/CordovaLog(6690): undefined: Line 1 : exception firing pause event from native
03-11 18:22:25.424: I/Web Console(6690): exception firing pause event from native at undefined:1
03-11 18:22:27.364: I/CordovaLog(6690): Changing log level to DEBUG(3)
03-11 18:22:27.364: I/CordovaLog(6690): Found start page location: index.html
03-11 18:22:27.364: D/Whitelist(6690): Unlimited access to network resources
03-11 18:22:27.364: D/CordovaActivity(6690): Resuming the App
03-11 18:22:27.364: D/CordovaActivity(6690): CB-3064: The errorUrl is null
03-11 18:22:27.384: D/CordovaLog(6690): undefined: Line 1 : exception firing resume event from native
03-11 18:22:27.384: I/Web Console(6690): exception firing resume event from native at undefined:1
03-11 18:22:27.554: D/dalvikvm(6690): GC_CONCURRENT freed 741K, 53% free 3093K/6471K, external 3215K/4015K, paused 2ms+17ms
03-11 18:22:59.944: D/CordovaActivity(6690): Paused the application!
03-11 18:22:59.944: D/CordovaWebView(6690): Handle the pause
03-11 18:22:59.954: D/CordovaLog(6690): undefined: Line 1 : exception firing pause event from native
03-11 18:22:59.954: I/Web Console(6690): exception firing pause event from native at undefined:1
03-11 18:23:06.514: W/IInputConnectionWrapper(6690): getTextBeforeCursor on inactive InputConnection
03-11 18:23:06.524: W/IInputConnectionWrapper(6690): getExtractedText on inactive InputConnection

**Comment by fungilation** [comment]
Not sure if this should be submitted as a new issue, but besides old androids, this is also a dependent issue for performant Cordova apps on iOS 8: https://github.com/Telerik-Verified-Plugins/WKWebView/issues/70. Bundling a (node) web server and switching from Meteor.local to http://localhost routes would sidestep 2 issues here

**Comment by dotnetwise** [comment]
This support would be great for Meteor 1.1.0, launched just after cordova 4.0 (for IOS) will be launched!

**Comment by salamanders** [comment]
I don't think so.  Not working on it right now, so can't repro, but will reopen if encounter it again.

**Comment by timbotnik** [comment]
We've hit this one as well.  Excerpt from logs:
```
07-21 15:31:55.331: I/Web Console(398): METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local at file:///android_asset/www/meteor_cordova_loader.js:12
07-21 15:31:55.331: D/CordovaWebViewClient(398): onPageStarted(http://meteor.local/)
07-21 15:31:55.331: D/JsMessageQueue(398): Set native->JS mode to null
07-21 15:31:55.331: D/CordovaActivity(398): onMessage(onPageStarted,http://meteor.local/)
07-21 15:31:55.581: D/CordovaWebViewClient(398): CordovaWebViewClient.onReceivedError: Error code=-2 Description=The URL could not be found. URL=http://meteor.local/
```

**Comment by TimeBandit** [comment]
I'm seeing the same issue with Android 2.3.6. A workaround or fix would be appreciated

**Comment by martijnwalraven** [comment]
As Cordova now only supports Android 4.0 (API level 14) or higher, I'm going to close this issue.
