### ISSUE TITLE
0.9.4 Meteor taking too much time to reload after code changes

### ISSUE THREAD

**Issue by wolasss** [meteor/meteor#2855]
After updating to 0.9.4 I have encountered meteor taking to much time to reload the app on the server side on code update. Especially with local packages.

For instance creating new meteor app with `meteor create`, and changing generated .js file within `Meteor.isServer` block while meteor is running - it takes ~8s for meteor to reload the server and show "Meteor server restarted" on console. 

But things are getting even longer when I add local package in /packages directory. The package is only `package.js` and `test.js` loaded on server. When I edit test.js, then it takes up to 16s for meteor to reload the server.

I have a project with multiple local packages after I update ANY file in ANY package, it takes up to 3min (sic!) for meteor to reload and apply changes - both client and server. 

No idea how to even debug what is taking so long. Before updating to 0.9.4 the reload was rather instant.

While starting that project (with multiple packages) I am also getting a few 

```
Error connecting to package server: DDP connection timed out
Warning: could not connect to package server

Error connecting to package server: Network error: wss://packages.meteor.com/websocket: socket hang up
Warning: could not connect to package server
```

as described [https://github.com/meteor/meteor/issues/2777]. But not sure if it has anything to do with reload time. 

Any ideas?

**Comment by ilearnio** [comment]
A fresh install of Meteor 1.2.0.2 compiles files after I press ctrl+s in like 2 seconds on my Macbook pro. It's awful! Why not to compile just a single file I'm working on? I can't imagine how long it's going to take if my project will grow huge. It would be impossible to work! 
So i'm thinking about switching to gulp (until it's not too late), and it will compile my sources to Meteor project and it will also perform live reload (instead of Meteor)
