### ISSUE TITLE
android build for a project with a name starting with a digit

### ISSUE THREAD

**Issue by netanelgilad** [meteor/meteor#2868]
Hi,
I've encountered an issue trying to run my meteor app on android.
When I built the app and run it by `meteor run android` I got compilation errors for classes that are called after the project name (those extending CordovaActivity).

I've never seen anywhere a warning about creating a project with a name that starts with a digit. Should be taken care of somehow when using `meteor create`. I guess by a warning or maybe an error.
What do you guys think?

**Comment by davidyaha** [comment]
You could also worn the user when the name of the app starts with a digit and the user uses `meteor add-platform android`... Even you would fix the issue by recognizing the issue and escape with a suitable character the user should know that he's app name will be changed for android apps.

I should note that you shouldn't use digits on the beginning of the `name` field in `App.info()` object.

Example:
````
App.info({
  id : 'com.exapmle',
  version : '0.0.1',
  name : '1Blue', 
  description : 'Example',
  author : 'John Doe',
  email : 'contact@example.com',
  website : 'http://example.com'
}); // This will result with a broken android app

**Comment by abernix** [comment]
Thanks for opening this originally!  In the process of triaging issues, I've created a few Cordova apps just this month using issue numbers.  I'm not sure this issue is relevant anymore and it hasn't received any other +1s (at all) so this must be fixed either upstream or is already fixed in Meteor.

If you continue to experience this problem, I'd be happy to reopen this, but please try with the latest version of Meteor first!
