### ISSUE TITLE
Cannot run on iOS

### ISSUE THREAD

**Issue by striletskyy** [meteor/meteor#2878]
Hello,

When I am trying to use `meteor run ios` I get error:
![screen shot 2014-10-21 at 12 35 11 pm](https://cloud.githubusercontent.com/assets/5245787/4718576/34c4a898-5922-11e4-8c9f-a6f6b2d9df81.png)

**Comment by thetwosents** [comment]
Bump. I've been trying to update everything and so far it seems like a terrible no good very bad day

**Comment by DanAncona** [comment]
I'm in the same boat. Yosemite 10.10.1, just updated XCode, just updated meteor, Simulator session timing out. NBD since it's a toy app and I'm getting it up and running on the web first, but thought I'd mention it.

```
Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=2 "Simulator session timed out." UserInfo=0x7fbe38650d30 {NSLocalizedDescription=Simulator session timed out.}
Command finished with error code 1: /Users/da/dev/meteor/accountability/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
Error: /Users/da/dev/meteor/accountability/.meteor/local/cordova-build/platforms/ios/cordova/run: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/da/.meteor/packages/meteor-tool/.1.0.38.1sk5fe9++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

Could not start the app in the iOS simulator.
Try running again with the --verbose option.
```

**Comment by thetwosents** [comment]
I decided to instead just run directly to device with meteor run iOS-device and use phone gap on the device. Hope that helps

**Comment by DanAncona** [comment]
Just tried "meteor run ios-device" - xcode pops up, hit play, it loads in the simulator and works great. Including auto-reload on edits. Thanks for the tip @thetwosents!

**Comment by thetwosents** [comment]
Super glad I could help man. And yea the Xcode crap sucks but it does work! Congrats!

**Comment by southgraphic** [comment]
I also was getting the session timeout error running XCode 6.1.1 and OSX 10.9.5. Using xcode worked for me, I had to close iOS simulator and do 'meteor run ios-device' again, but then it worked.

**Comment by thetwosents** [comment]
Awesome!

**Comment by gibex** [comment]
For me it hangs in both ios simulator / device. No errors 
OSX 10.10.2
XCode 6.1.1

Works fine in android simulator.

**Comment by gibex** [comment]
Works fine if I close both the app and simulator (ios), then open and run project directly from xcode.

Does anybody knows how to build the app without open the simulator?

**Comment by tdmoneybanks** [comment]
also having a problem with this. updating to latest version of xcode to see if that helps

**Comment by criesbeck** [comment]
Yosemite 10.1.2, Xcode 6.1.1.   Following the tutorial, no problems or warnings all through deployment to meteor.com, installing and adding the ios platform. but  when I do meteor run ios or meteor run ios-device, I get a missing Cordova component error. Something obvious to try?

    Error while running for mobile platforms: Error running                         
    /Users/riesbeck/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
    Error: version not found: 0.2.10 : org.apache.cordova.console/0.2.10
    at RegClient.<anonymous>
    (/Users/riesbeck/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
    at Request.self.callback
    (/Users/riesbeck/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)

**Comment by thetwosents** [comment]
Ive just started getting the same issue now. Submitted a request to try and get some help. I have one of my apps working perfectly and then even when creating a new meteor app and trying it gives me the same issue

**Comment by sumitk** [comment]
Can't run app on simulator or device. Same errors as mentioned above.

**Comment by nightsurge** [comment]
I am also getting an error running on ios. Surprisingly for once, running on android was less hassle and worked the first time!

```
Error while running for mobile platforms: Error running
/Users/jjarnold/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
2015-02-20 11:20:35.403 xcodebuild[37879:5003] error: Error Domain=NSPOSIXErrorDomain Code=2 "Non-zero exit code 1 returned from shell command: /usr/local/bin/gcc-4.6 -v -E -dM
-arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -x objective-c -c /dev/null 2>&1"
UserInfo=0x7fcc726e7710 {NSLocalizedDescription=Non-zero exit code 1 returned from shell command: /usr/local/bin/gcc-4.6 -v -E -dM -arch i386 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -x objective-c -c /dev/null 2>&1, NSLocalizedFailureReason=No
such file or directory}
2015-02-20 11:20:35.403 xcodebuild[37879:5003] Warning:  Couldn't discover the 'gcc-4.6' compiler's built-in search paths and preprocessor definitions for language dialect
'objective-c'.
Compiler: /usr/local/bin/gcc-4.6
Reason:   /usr/local/bin/gcc-4.6 -v -E -dM -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk
-x objective-c -c /dev/null 2>&1
2015-02-20 11:20:35.480 xcodebuild[37879:7b03]  DVTAssertions: Warning in
/SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-6269/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/XCCommandLineToolSpecification.m:1048
Details:  Unable to get message category info for tool '/usr/local/bin/gcc-4.6'.
Reason: gcc-4.6: error: unrecognized option '--print-diagnostic-categories'
gcc-4.6: fatal error: no input files
compilation terminated.

Object:   <XCCompilerSpecificationClang: 0x7fcc746195e0>
Method:   -messageCategoryInfoForExecutablePath:
Thread:   <NSThread: 0x7fcc76246d80>{name = (null), num = 9}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **
```

**Comment by vinu123** [comment]
My app starts, I see meteor's logo in the bottom corner and then it crashes. Heres the log

Command finished with error code 0: /Users/vinodsobale/Documents/Projects/todos/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
I20150223-17:15:22.551(5.5)? (ios) Unlimited access to network resources
I20150223-17:15:22.554(5.5)? (ios) 
I20150223-17:15:22.544(5.5)? (ios) Multi-tasking -> Device: YES, App: YES
I20150223-17:15:22.555(5.5)? (ios) Started backup to iCloud! Please be careful.
I20150223-17:15:22.554(5.5)? (ios) 
I20150223-17:15:22.555(5.5)? (ios) Your application might rejected by Apple if you store too much data.
I20150223-17:15:22.555(5.5)? (ios) For more information please read "iOS Data Storage Guidelines"
I20150223-17:15:22.555(5.5)? (ios) You could find it at the following address https://developer.apple.com/icloud/documentation/data-storage/ .
I20150223-17:15:22.555(5.5)? (ios) 
I20150223-17:15:24.119(5.5)? (ios) [CDVTimer][file] 1.666009ms
I20150223-17:15:24.119(5.5)? (ios) [CDVTimer][statusbar] 20.496964ms
I20150223-17:15:24.119(5.5)? (ios) [CDVTimer][splashscreen] 3.872037ms
I20150223-17:15:24.120(5.5)? (ios) [CDVTimer][TotalPluginStartup] 28.930962ms
I20150223-17:15:24.120(5.5)? (ios) Resetting plugins due to page load.
I20150223-17:15:24.120(5.5)? (ios) Finished load of: file:///Users/vinodsobale/Library/Developer/CoreSimulator/Devices/01A3166C-3C6B-4292-AC3C-656973875F3B/data/Applications/2DB95521-2DF9-4A89-8BF9-2B13924B3C34/todos.app/www/index.html
I20150223-17:15:24.120(5.5)? (ios) start serving (
I20150223-17:15:24.120(5.5)? (ios)     "/Users/vinodsobale/Library/Developer/CoreSimulator/Devices/01A3166C-3C6B-4292-AC3C-656973875F3B/data/Applications/2DB95521-2DF9-4A89-8BF9-2B13924B3C34/Library/NoCloud/meteor/8947bb0c8584e4195f1fb3a2e8516c8141e65b50/",
I20150223-17:15:24.120(5.5)? (ios)     "/Users/vinodsobale/Library/Developer/CoreSimulator/Devices/01A3166C-3C6B-4292-AC3C-656973875F3B/data/Applications/2DB95521-2DF9-4A89-8BF9-2B13924B3C34/todos.app/www/"
I20150223-17:15:24.121(5.5)? (ios) )
I20150223-17:15:24.121(5.5)? (ios) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
I20150223-17:15:24.121(5.5)? (ios) Resetting plugins due to page load.
I20150223-17:15:24.121(5.5)? (ios) METEOR CORDOVA DEBUG loading filepath: (null) for path: %2F
I20150223-17:15:24.121(5.5)? (ios) *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
I20150223-17:15:24.121(5.5)? (ios) *** First throw call stack:
I20150223-17:15:24.121(5.5)? (ios) (
I20150223-17:15:24.122(5.5)? (ios) 	0   CoreFoundation                      0x001971e4 __exceptionPreprocess + 180
I20150223-17:15:24.122(5.5)? (ios) 	1   libobjc.A.dylib                     0x01dda8e5 objc_exception_throw + 44
I20150223-17:15:24.122(5.5)? (ios) 	2   CoreFoundation                      0x00196fbb +[NSException raise:format:] + 139
I20150223-17:15:24.122(5.5)? (ios) 	3   Foundation                          0x019f492b -[NSURL(NSURL) initFileURLWithPath:] + 123
I20150223-17:15:24.122(5.5)? (ios) 	4   Foundation                          0x019f47fd +[NSURL(NSURL) fileURLWithPath:] + 67
I20150223-17:15:24.123(5.5)? (ios) 	5   todos                               0x000bc5eb -[METEORCordovaURLProtocol startLoading] + 747
I20150223-17:15:24.123(5.5)? (ios) 	6   Foundation                          0x01aebd62 __31-[_NSCFURLProtocolBridge start]_block_invoke + 59
I20150223-17:15:24.123(5.5)? (ios) 	7   Foundation                          0x01a53d65 -[NSBlockOperation main] + 88
I20150223-17:15:24.123(5.5)? (ios) 	8   Foundation                          0x01aacc79 -[__NSOperationInternal _start:] + 671
I20150223-17:15:24.123(5.5)? (ios) 	9   Foundation                          0x01a299c8 -[NSOperation start] + 83
I20150223-17:15:24.123(5.5)? (ios) 	10  Foundation                          0x01aead63 -[_NSCFURLProtocolBridgeWithTrampoline processEventQ] + 291
I20150223-17:15:24.123(5.5)? (ios) 	11  Foundation                          0x01aeb412 -[_NSCFURLProtocolBridgeWithTrampoline pushEvent:from:] + 264
I20150223-17:15:24.123(5.5)? (ios) 	12  Foundation                          0x01aebd22 -[_NSCFURLProtocolBridge start] + 94
I20150223-17:15:24.124(5.5)? (ios) 	13  Foundation                          0x01aecf31 bridgeStart + 80
I20150223-17:15:24.124(5.5)? (ios) 	14  CFNetwork                           0x05e91e0b _ZN19URLProtocol_Classic28_protocolInterface_startLoadEPK20_CFCachedURLResponse + 65
I20150223-17:15:24.124(5.5)? (ios) 	15  CFNetwork                           0x05ebbc33 ___ZN19URLConnectionLoader27_private_ScheduleOriginLoadEPK13_CFURLRequestPK20_CFCachedURLResponse_block_invoke_2 + 147
I20150223-17:15:24.124(5.5)? (ios) 	16  CFNetwork                           0x05eba868 ___ZNK19URLConnectionLoader25withExistingProtocolAsyncEU13block_pointerFvP11URLProtocolE_block_invoke + 30
I20150223-17:15:24.124(5.5)? (ios) 	17  CoreFoundation                      0x00138c69 CFArrayApplyFunction + 57
I20150223-17:15:24.125(5.5)? (ios) 	18  CFNetwork                           0x05e1a441 _ZN19RunloopBlockContext7performEv + 155
I20150223-17:15:24.125(5.5)? (ios) 	19  CFNetwork                           0x05efc3f4 _ZThn16_N19RunloopBlockContext24multiplexerClientPerformEv + 20
I20150223-17:15:24.125(5.5)? (ios) 	20  CFNetwork                           0x05e1a257 _ZN17MultiplexerSource7performEv + 299
I20150223-17:15:24.125(5.5)? (ios) 	21  CFNetwork                           0x05e1a06c _ZN17MultiplexerSource8_performEPv + 76
I20150223-17:15:24.125(5.5)? (ios) 	22  CoreFoundation                      0x0012077f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
I20150223-17:15:24.125(5.5)? (ios) 	23  CoreFoundation                      0x0012010b __CFRunLoopDoSources0 + 235
I20150223-17:15:24.125(5.5)? (ios) 	24  CoreFoundation                      0x0013d1ae __CFRunLoopRun + 910
I20150223-17:15:24.126(5.5)? (ios) 	25  CoreFoundation                      0x0013c9d3 CFRunLoopRunSpecific + 467
I20150223-17:15:24.126(5.5)? (ios) 	26  CoreFoundation                      0x0013c7eb CFRunLoopRunInMode + 123
I20150223-17:15:24.126(5.5)? (ios) 	27  WebCore                             0x048f4a18 _ZN7WebCoreL15runLoaderThreadEPv + 360
I20150223-17:15:24.126(5.5)? (ios) 	28  JavaScriptCore                      0x08d20b2c _ZN3WTFL16threadEntryPointEPv + 76
I20150223-17:15:24.126(5.5)? (ios) 	29  JavaScriptCore                      0x08d21025 _ZN3WTFL19wtfThreadEntryPointEPv + 21
I20150223-17:15:24.126(5.5)? (ios) 	30  libsystem_pthread.dylib             0x02703e13 _pthread_body + 138
I20150223-17:15:24.126(5.5)? (ios) 	31  libsystem_pthread.dylib             0x02703d89 _pthread_body + 0
I20150223-17:15:24.127(5.5)? (ios) 	32  libsystem_pthread.dylib             0x02701e52 thread_start + 34
I20150223-17:15:24.127(5.5)? (ios) )
I20150223-17:15:24.127(5.5)? (ios) libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Bijiabo** [comment]
I am also getting an error running on ios too... Help...

**Comment by andreayaya** [comment]
I see these problems started a while back, just wondering if anything resolved?  I am running:
xcode v. 6.3.2
OSX v. 10.10.3

The iOS simulator does not open when using:
meteor run ios
and no error messages.

Not sure what resolution is here, or if I just will never be able to see my app in iOS :(

**Comment by stubailo** [comment]
This code has been totally ripped out in Meteor 1.2 in favor of using `cordova-lib`. If this error occurs again we should file a new issue.
