### ISSUE TITLE
Documentation by version

### ISSUE THREAD

**Issue by mariorodriguespt** [meteor/meteor#2960]
Could you add the option to see the documentation by meteor version on docs.meteor.com?

I understand that we should be using meteor 1.0 having in consideration that using previous versions might not be the best option. example: Today, on meteor 0.8.3, I couldn't fetch a package from atmosphere.

I'm force to upgrade to meteor 1.0 and it's not being easy at all. It would be great to have the documentation by version, I've no doubt that some developers need to delivery meteor projects and this is an unpleasant stone in the shoe.

**Comment by servel333** [comment]
Since Meteor is moving so fast, this would be very helpful. After only a few weeks of working with Meteor the documentation and API have differed enough that many parts of the latest documentation are not useful to me. I would like to see this issue reopened and see the team officially host older versions of the documentation.
