### ISSUE TITLE
messages in the background updater are not entirely accurate

### ISSUE THREAD

**Issue by wulfmeister** [meteor/meteor#2998]
After Meteor 1.0 has already been downloaded and installed when updating another repo, running the comand `meteor` in another old project causes the tool to say that 1.0 is being downloaded.  It's not (there's already a local copy).

Reproduction steps:
1. Update a project to 1.0 (or otherwise make sure 1.0 is installed)
2. cd into another project @ version 0.9.3 (the one I reproduced with)
3. run `meteor`

At this point you get the prompt: "Meteor 1.0 is being downloaded in the background. You can update to it by running 'meteor update'."  However, no network download activity happens (see screenshot).  I think this is the tool knowing that Meteor 1.0 is already on the user's machine, but not informing the user correctly.

![screenshot](https://cloud.githubusercontent.com/assets/6174700/4891110/b8d748ca-63a4-11e4-9353-3a9c7c1604ed.PNG)

**Comment by hwillson** [comment]
Many new Meteor versions have been released since this issue was created, and a lot has changed with regards to the release-downloading / message-printing code. This problem shouldn't be happening with newer Meteor releases, so I'll close this issue. Let us know if this happens again and thanks for originally reporting this issue (and sorry for the delay in getting to this)!
