### ISSUE TITLE
Block helpers don't create a template instance in the hierarchy of template instances

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3071]
If I create a block helper:

```
  {{#noop}}
     {{> hello}}
  {{/noop}}
```
```
<template name="noop">
  {{> Template.contentBlock}}
</template>
```

And I traverse template instances hierarchy, that block helper template is not available in the hierarchy. For example, if I add data to `noop` template instance in `created` callback, it is not reacable from inside `hello` template instance.

**Comment by avital** [comment]
Yes, block helpers-via-templates are implemented by having `parentView` intentionally skip over the actual template defining the block helper (you can see this in a view of type "InOuterTemplateScope" in the view hierarchy). This is so that the data context in the contents of the block helper are the same as the data context outside of it, even if you pass attributes to the block helper. (Admittedly, this is confusing.)

The solution to your specific question is to look at the `originalParentView` property when you hit a `InOuterTemplateView` view, which will get you the actual template that defined the block helper.

**Comment by mitar** [comment]
Ah, I will have to start making some references to my code where I needed this. Now I do not know anymore where this issue came from. :-(

**Comment by mitar** [comment]
That was helpful. But I also see that when using a block helper, `"(contentBlock)"` template instance is injected in the hierarchy. Is there some way to detect such instance without having to check for the name?
