### ISSUE TITLE
Client does not react on collection update with $unset

### ISSUE THREAD

**Issue by dohomi** [meteor/meteor#3086]
I have a little script to update `Meteor.users` collection. I unset a property of the user, but the change is not triggering `observerChange`at the frontend:

```
Meteor.users.update(Meteor.userId(),{$unset:{language:''}});

Meteor.users.find(Meteor.userId()).observeChanges({
    changed: function(id,fields){
        console.log("CHANGED", arguments); // not getting called on an update with mongo $unset
    }
});
```

Is this correct behaviour? In my case `Meteor.user()`on the client side doesn't update, only after reload the user property is updated.

**Comment by evolross** [comment]
I just ran into this on Meteor 1.5.2.  I have a small repo that reproduces the issue. The repo is on 1.5.2 because that's what my production app is on.  

The repo is here: [https://github.com/evolross/redis-oplog-issues](https://github.com/evolross/redis-oplog-issues)

**NOTE:** This is a repo I've used to demonstrate `redis-oplog` bugs, hence the name, and I thought this was maybe `redis-oplog` related, but the error occurs even with `redis-oplog` disabled. So despite the name, the latest commit currently has `redis-oplog` off and the error still occurs.

To reproduce the issue, do the following:

1. Clone. Run `meteor --settings settings.json`
2. Create an account in the upper left-hand-corner
3. Click the "Add Twenty Tasks" button. This will display five paginated `task` documents each with a green status indicator.  In the code, it checks if `task.color` exists, if so, it displays the color in the indicator. If not, it displays a red circle. We will `$unset` the task.color from a client update.
4. On the first task, click on the "$unset Status" button. This calls `Tasks.update({_id: ...}, {$unset: {color: ""}}, {...})` on the client.

You'll notice nothing happens at all or the indicator will momentarily flash to the red-outline circle but then back to the green-filled circle.  Upon investigating mini-mongo with `mongol` (press CTRL-M), you'll see the `color` field is still present. Upon refreshing the page, you'll see the UI updates and mini-mongo as well, and it's now gone.

You can repeat this on the additional tasks.  To reset, click "Remove All Tasks".  Here's a GIF of the issue:

![meteorunsetissue](https://user-images.githubusercontent.com/7980725/43925733-f2406190-9bdc-11e8-9eac-a7932102e1ae.gif)

I know I need to upgrade but just the upgrade to 1.5.3 broke some Mongo stuff for me - so I put it on the backburner for my production app. Will be upgrading to 1.6.x shortly. I'm running OS X 10.10.5 (also need to upgrade this). Browser is Chrome 67.0.3396.99.

**Comment by Batistleman** [comment]
@evolross did you manage to solve this issue? We are experiencing the same problem on Meteor 1.11.1

**Comment by evolross** [comment]
I think upgrading did the trick. I'm on Meteor 1.10.2. Have you tried testing the repo above and confirming it's still an issue in the repo?
