### ISSUE TITLE
Url package conflicts with browser global

### ISSUE THREAD

**Issue by andylash** [meteor/meteor#3089]
The url package exports a global called URL.  This conflicts with the new DOM API: https://developer.mozilla.org/en-US/docs/Web/API/Window.URL#Browser_compatibility.  I noticed this while using this filesaver library, where polymer has the same problem, but is planning to fix it: https://github.com/eligrey/FileSaver.js/pull/97.

**Comment by abernix** [comment]
Closing this.  With NPM support in Meteor now, the expectation at this point is that developers shouldn't use the Meteor `url` package directly, but instead use the `url` NPM package (which is what Meteor uses internally anyway).

`url` is already not documented in the new docs (for probably a very good reason), and I'd guess (personally) is one of the first candidates (due to it's simplicity) for replacement in the Meteor 1.5 NPM-oriented-release.
