### ISSUE TITLE
Blaze._javascriptUrlsAllowed make the same feature to be enabled per helper

### ISSUE THREAD

**Issue by adaptabi** [meteor/meteor#3103]
Make it per handler e.g. a simple example, where only this helper is allowed:

```
Template.registerHelper('pathForBack', function(view, opts){
  opts.javascriptUrlsAllowed = true;
  return "javascript:history.back()";
});
```

**Comment by avital** [comment]
Yeah, this would be a useful feature, but I don't think it makes sense for this to be a property of the helper, since a single HTML attribute might be constructed of several helpers, or constant text and a helper. For example, imagine the following template:

```html
<div onclick="javascript:{{foo}}" />
```

So, a more relevant API might live on the template level, such as: `Template.foo._allowJavascriptUrls()`. We'll take a look at a pull request (with tests) implementing this.

**Comment by RobertLowe** [comment]
@glasser I was working on a patch for this, but in `blaze/attrs.js` we don't have access to the view, I imagine this was done on purpose? I could refactor `ElementAttributesUpdater` to keep a reference to the `parentView`. 

Also should the API be:

`Template.foo._allowJavascriptUrls()`

or is a callback preferred:

`Template.foo._hasJavascriptUrls = function () { return true/false }`

Thoughts?

**Comment by RobertLowe** [comment]
@Slava bump, any thoughts on this?

**Comment by ChrisCinelli** [comment]
This can be useful to create bookmarklet that need absolute URL and you want it to work both locally and after deploying

**Comment by hwillson** [comment]
Migrated over to meteor/blaze#199 - closing here - thanks!
