### ISSUE TITLE
[Cordova] iOS app archive fails to validate: missing icon size

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3153]
![screen shot 2014-11-21 at 2 26 56 pm](https://cloud.githubusercontent.com/assets/251288/5150855/73b03230-718b-11e4-8bdf-2431ada8fda5.png)

I was able to get a file of the right size into the right directory by adding a `project/cordova-build-override/platforms/ios/AppName/Resources/icons/icon-57.png` file. However, it looks like it also needs to be in the icon files array in the `AppName-Info.plist`, and I can't find a configuration option (http://docs.meteor.com/#/full/mobileconfigjs) for modifying the plist. Is there a way? Or can the additional file size be added to the list of sizes that meteor is already generating?

**Comment by adam-hanna** [comment]
For what it's worth.... +1.

@hellogerard, your work-around did it for me. Thanks!

**Comment by funkyeah** [comment]
@Slava any luck on seeing the validate now that itunes connect is back up?

**Comment by Slava** [comment]
@funkyeah I will come back to this next time I work on Cordova-related issues.

**Comment by brugnara** [comment]
`android_xxhdpi` and `android_xxxhdpi` options are missing too.

This causes application published as **not made for tablet**

**Comment by funkyeah** [comment]
I have since published my app to itunes with the 57 px workaround for validation.
I have had a number of users download and install. The icon config does not work for iphone6+ but icons on other platforms look fine.

I use the following config:

`  'iphone_3x': 'icons/robot_icon_180x180square.png' `

which points to this image:

[robot_icon_180x180square.png](https://github.com/The3vilMonkey/BrewsOnTap/blob/master/icons/robot_icon_180x180square.png)

and instead of that image for an icon people are getting the default meteor icon.

**Comment by brugnara** [comment]
I've solved this way but with some manual operations.

```js
  'iphone': 'resources/splash/iphone/appicon.png', // 57x57
  'iphone_2x': 'resources/splash/iphone/appicon-60@2x.png', // 120x120
  'iphone_3x': 'resources/splash/iphone/appicon-60@3x.png', // 180x180
  'ipad': 'resources/splash/iphone/appicon-76.png', // 76x76
  'ipad_2x': 'resources/splash/iphone/appicon-76@2x.png' // 152x152
```

After building with meteor, in XCode, I've replaced **manually** the `icon-72.png` and `icon-72@2x.png` that are **wrong sized** at `76x76`and `152x152` with right sizeds `72x72` and `144x144` PNGs. Now I can send to iTunes without warnings. Hope this helps to find out the problem.

**Comment by awatson1978** [comment]
Daaang.  Months of work, only to run into icon size issues at the (almost) last step of publication.  :sigh:
+1

57px and 72px icon errors.

**Comment by lorensr** [comment]
If you don't mind changing the target to ios 7, the errors should go away.

**Comment by awatson1978** [comment]
Brilliant!  It's still burping a warning for a 57pixel icon, but it validated and I'm good to go.  Thank you Loren!

**Comment by hellogerard** [comment]
Yes. Since I posted my workaround, I learned that setting the Deployment Target to 7.0 solves this problem. Appears that 6.0 requires 57x57 icons and 7.0 requires 60x60. The thing is that in 2015, targeting 7.0 and up should be just fine.

**Comment by andrewreedy** [comment]
:+1: The full range of icons for iOS submission https://www.dropbox.com/s/wivj2ycw13nc5y8/Screenshot%202015-03-10%2013.24.37.png?dl=0

**Comment by florasolutions** [comment]
Setting deployment target has to be iPhone instead of universal before this issue is solved, but still getting issue for 152x152 and 76x76 icons when having "universal" selected. Looking in the built resources/icons folder, the file icon-76.png is really 72x72 pixels and icon-76@2.png is 144x144 pixels. My mobile-config looks like this and the original icon files have the correct size:
```
// Icons (generated with http://ticons.fokkezb.nl/)
App.icons({
    // iOS
    'iphone': 'resources/ticons/app/assets/iphone/appicon-60.png',
    'iphone_2x': 'resources/ticons/app/assets/iphone/appicon-60@2x.png',
    'ipad': 'resources/ticons/app/assets/iphone/appicon-72.png',
    'ipad_2x': 'resources/ticons/app/assets/iphone/appicon-72@2x.png',

    // Android
    'android_ldpi': 'resources/ticons/platform/android/res/drawable-ldpi/appicon.png',
    'android_mdpi': 'resources/ticons/platform/android/res/drawable-mdpi/appicon.png',
    'android_hdpi': 'resources/ticons/platform/android/res/drawable-hdpi/appicon.png',
    'android_xhdpi': 'resources/ticons/platform/android/res/drawable-xhdpi/appicon.png'
});
```

**Comment by wreiske** [comment]
+1 having this issue right now... ugh!

**Comment by karandesai** [comment]
Yup. At the very last step having these icon issues!

**Comment by wreiske** [comment]
Please take this for a spin,

Set your iOS build for 7.0 and try the python and mobile config from here: https://gist.github.com/wreiske/a9d2706491a073b293de

Let me know if this works for you!

Basically all you need is one large icon-ios.png and icon-android.png that is larger than any of the icons you will be making.

    python icon-generator.py

Will generate all the icons you need.

**Comment by miri-am** [comment]
This is working (same as @brugnara) for me with iOS 8.2 without any warnings.
```
  'iphone': 'resources/icons/iphone/appicon-60.png',
  'iphone_2x': 'resources/icons/iphone/appicon-60@2x.png',
  'iphone_3x': 'resources/icons/iphone/appicon-60@3x.png',
  'ipad': 'resources/icons/iphone/appicon-76.png',
  'ipad_2x': 'resources/icons/iphone/appicon-76@2x.png'
```

**Comment by dotnetwise** [comment]
This is still an issue for IOS7

**Comment by dotnetwise** [comment]
https://github.com/meteor/meteor/blob/devel/examples/todos/mobile-config.js#L12

@Slava can you please fix the example file?

**Comment by MoeBadr** [comment]
+1 issues with following sizes missing:  57x57, 72x72 + 152x152

**Comment by dotnetwise** [comment]
@Slava are you still alive?
![image](https://cloud.githubusercontent.com/assets/485535/7158591/462095ec-e384-11e4-8f89-4b5904390549.png)

**Comment by brugnara** [comment]
@dotnetwise see my previous post for a solution.

**Comment by dotnetwise** [comment]
Thanks @brugnara but that is an work around. We need a work term solution.
I am not using xcode for this as everything is done in an automated process.

**Comment by MoeBadr** [comment]
@brugnara Thank you for posting your work around, incredibly helpful.

**Comment by Slava** [comment]
@dotnetwise 
> @Slava are you still alive?

I am still alive, thank you for your interest in my well-being. I do have a minor neck-pain, but I think, it will be over next week.


**2all:**
I am sorry this is getting unresolved for a long time. I have been busy working on the Windows release and right now I am on a different project improving the build tool.

I am marking this ticket as "pull-requests-encouraged", here is what one would do to fix this:

- See the lines of predefined icon formats in the meteor-tool: https://github.com/meteor/meteor/blob/d956f0976f8189d42467ec757ddf0e7030bca54e/tools/commands-cordova.js#L1377-L1414
- See the logic that gets the icon paths from the mobile-config.js file: https://github.com/meteor/meteor/blob/d956f0976f8189d42467ec757ddf0e7030bca54e/tools/commands-cordova.js#L1559-L1585
- See the part that adds the images to the config.xml of the Cordova project: https://github.com/meteor/meteor/blob/d956f0976f8189d42467ec757ddf0e7030bca54e/tools/commands-cordova.js#L1732-L1800
- Figure out what needs to be added to these lines in order to cover all the icon sizes to pass the App Store submission process
- Document how to test

**Comment by eric011** [comment]
It's obvious that Meteor failed to convert those icons, just copy them:
```
Resources/icons/icon-40.png:       PNG image data, 57 x 57, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-40@2x.png:    PNG image data, 120 x 120, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-50.png:       PNG image data, 57 x 57, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-50@2x.png:    PNG image data, 120 x 120, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-60.png:       PNG image data, 57 x 57, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-60@2x.png:    PNG image data, 120 x 120, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-60@3x.png:    PNG image data, 180 x 180, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-72.png:       PNG image data, 72 x 72, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-72@2x.png:    PNG image data, 144 x 144, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-76.png:       PNG image data, 72 x 72, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-76@2x.png:    PNG image data, 144 x 144, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-small.png:    PNG image data, 57 x 57, 8-bit/color RGBA, non-interlaced
Resources/icons/icon-small@2x.png: PNG image data, 57 x 57, 8-bit/color RGBA, non-interlaced
Resources/icons/icon.png:          PNG image data, 57 x 57, 8-bit/color RGBA, non-interlaced
Resources/icons/icon@2x.png:       PNG image data, 120 x 120, 8-bit/color RGBA, non-interlaced
```
After manually replace the icon-72 and icon-72@2x, the submission warning is gone.

**Comment by maersu** [comment]
For people like me (I just copied the [mobile-config.js](https://github.com/meteor/meteor/blob/devel/examples/todos/mobile-config.js) from the todo example):
you have to adjust the required sizes. Instead of 72 use the 76.

```
App.icons({
  // iOS
  'iphone': 'resources/icons/icon-60x60.png',
  'iphone_2x': 'resources/icons/icon-60x60@2x.png',
  'ipad': 'resources/icons/icon-76x76.png',
  'ipad_2x': 'resources/icons/icon-76x76@2x.png',
});
```

**Comment by Slava** [comment]
We sat down @maersu on Devshop and figured out, people probably use Meteor examples and copy the config files from there. And while the file is called "icon-72x72", in reality it has the size "76x76", which confuses people. I made changes to the examples here: https://github.com/meteor/meteor/commit/8946bd3963655675f7934880eb8bec56051dc0f0

**Comment by maersu** [comment]
@Slava it seem there is currently no one-size-fits-all configuration because for different build targets we need different sizes for the 'iphone', 'iphone_2x', 'ipad', 'ipad_2x' keys

So either 

* we are fine with the warnings and missing icons for ≥ 7.0
* or we manually change the Build Target to ≥ 7.0. 
* or there is a possibility to specify different size for different build targets in mobile-config.js
* or there is a way to specify the build Target
* or the default build target is changed to 7.0

**Build Target ≥ 6.0 needs**

```
App.icons({
    // iOS
    'iphone': 'resources/icons/icon-57x57.png',
    'iphone_2x': 'resources/icons/icon-60x60@2x.png',
    'iphone_3x': 'resources/icons/icon-180x180.png',
    'ipad': 'resources/icons/icon-72x72.png',
    'ipad_2x': 'resources/icons/icon-72x72@2x.png',
});
```
(Has some warnings about missing 76px and 152px sizes for devices ≥ 7.0, which is of course not cool)

**Build Target ≥ 7.0 needs**

```
App.icons({
  // iOS
  'iphone': 'resources/icons/icon-60x60.png',
  'iphone_2x': 'resources/icons/icon-60x60@2x.png',
  'iphone_3x': 'resources/icons/icon-180x180.png',
  'ipad': 'resources/icons/icon-76x76.png',
  'ipad_2x': 'resources/icons/icon-76x76@2x.png',
});
```

**Comment by maersu** [comment]
I would prefer changing the default to 7.0 ([Cordova docs](http://docs.build.phonegap.com/en_US/3.1.0/configuring_preferences.md.html)):

````
<preference name="deployment-target" value="7.0" />
````

And add a valid config to the docs

```
App.icons({
  // iOS
  'iphone': 'resources/icons/icon-60x60.png',
  'iphone_2x': 'resources/icons/icon-60x60@2x.png',
  'iphone_3x': 'resources/icons/icon-180x180.png',
  'ipad': 'resources/icons/icon-76x76.png',
  'ipad_2x': 'resources/icons/icon-76x76@2x.png',
});
```

**Comment by Slava** [comment]
This should be fixed on devel. Please, comment on this thread if you think this is not fixed.

**Comment by lorensr** [comment]
The problem @brugnara mentioned above still exists in `v1.1.0.2`. On `run ios-device`:

`Error while running for mobile platforms: Error reading mobile-config.js:Error: android_xxhdpi: unknown key in App.icons configuration.`

Guessing the same for `xxxhdpi`

**Comment by Slava** [comment]
@lorensr what comment are you talking about? Isn't this ticket about iOS? I suggest you open another ticket with a repro and/or PR.

**Comment by lorensr** [comment]
https://github.com/meteor/meteor/issues/3153#issuecomment-74836271

**Comment by mardo** [comment]
+1 android_xxhdpi & android_xxxhdpi

**Comment by Pushplaybang** [comment]
+1 android_xxhdpi & android_xxxhdpi

**Comment by insaneinc01** [comment]
+1 android_xxhdpi & android_xxxhdpi!!!

**Comment by xpluscal** [comment]
+1 android_xxhdpi & android_xxxhdpi
