### ISSUE TITLE
Subscription not ready in onReady callback

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#3194]
In Deps.autorun, when using a session variable to modify a subscription, the onReady() callback
is called when data is not ready yet. Using setTimeout(0) solves the problem.

Tested on Meteor 0.8.3 and WINDOWS-PREVIEW@0.0.8

Here is the repo to reproduce (see README.md): https://github.com/steph643/meteor-issue-3194/

Issue also reported by someone else here: http://stackoverflow.com/questions/24103652/subscriptions-onready-called-when-cursor-is-not-ready/27174142

**Comment by glasser** [comment]
This is working as intended, though it's possible that this behavior is not as useful as it could be and that additional APIs could be useful here.

On startup, you make subscription S1 with dontShow=false. When re-running the autorun body, two things happen: we start a new subscription S2 with dontShow=true, and we unsubscribe from S1.  The way that subscribe-inside-autorun works is designed to send the new subscription before it unsubscribes from the old one; that way, if the two subscriptions overlap, rather than the server having to say "forget all this data! oh and now here that data is again", it can just send the diff between the two subscriptions.

But that means we get the "S2 ready (with no contents)" message before we get the "forget about all the contents of S1" messages.  (This is partially a result of the fact that DDP does server-side subscription merging rather than tagging data with subscription IDs, so there's no way for the client to just immediately forget the data that came from S1.)  So the S2 onReady fires before S1's data has been dropped.

At a low level, this is somewhat reasonable: onReady is a single-subscription callback and given the current DDP merge model, it's totally correct to say that this onReady is called when all of its data is in minimongo.  On the other hand, this is not analogous to how method callbacks work; method callbacks are not invoked until all outstanding possibly relevant methods have finished (which can be confusing in the opposite direction; see eg #3211).  Perhaps there should be more structure so that onReady doesn't get called until all subscriptions from the same autorun have finished becoming ready/unsubbing.

Another part of the problem here is that there's no "done unsubbing" callback for S1.

On the other hand, if you're just using reactivity rather than onReady, everything should just work.  In a sense, the issue here is that onReady and autorun are two different types of programming --- one is asynchronous event callback programming, and the other is reactivity.  And they don't always work together as well as you'd like.

**Comment by steph643** [comment]
That makes perfect sense.

Maybe something like this could be added to the doc:

*The onReady callback is called as soon as missing records have been received by the client. In case a subscription has the final effect of* ***removing*** *data from the client (this happens when a call to subscribe from Tracker.autorun cancels a previous subscription), onReady is called* ***before*** *records are removed from the client.*

**Comment by PeppeL-G** [comment]
I don't mind a clarification in the docs, especially regarding "[...] is designed to send the new subscription before it unsubscribes from the old one [...]", which I don't think the current documentation "[...] Meteor will subscribe to the new room's chat messages, unsubscribe from the original room's chat messages [...]" implies (or is this written somewhere else in the docs?).

But if you have two different subscriptions publishing documents to the same collection, you should be able to use a selector on the client to only find the documents coming from one (or both) of them, right?   Then this shouldn't be a problem. Or is there a use case where one can't use a selector to distinguish them?

**Comment by glasser** [comment]
@PeppeL-G You can't do that because subscriptions are merged on the server and data sent to the client is not tagged by subscription.  (I personally would make a different decision if it made sense for us to make model changes to DDP right now.)

@steph643 The problem is that that's not really accurate...  there are two different subscriptions there. I think the real issue is that the autorun/subscribe model, while enjoyable to write, is not actually great at representing on a concrete level what's happening.  The control is inverted in my opinion.  I'd rather have something like:

```
Meteor.subscribe(function () {
  return {
    name: 'myCollection',
    args: [Session.equals('dontShow', true)]
  };
});
```

where a single subscription object has reactive arguments.  And extend DDP so that you can send "reconfigure" commands to an existing subscription instead of dropping, restarting, and relying on the (expensive) server merge box.  And finally, have the equivalent of onReady be called on each reconfigure too.

(I've been thinking about mocking this up using methods when I get a chance, though honestly I don't think "make incompatible changes to the DDP model" is a high priority right now even if it might be better in the long term.)

**Comment by PeppeL-G** [comment]
@glasser, I meant something like this:

    Meteor.publish('newsInCategory', function(category){
        return News.find({category: category})
    })
    
    Tracker.autorun(function(){
        Meteor.subscribe('newsInCategory', Session.get('newsCategory'), function(){
            // This doesn't work as intended (contains old category result as well as the new one):
            News.find()
            // But this works as intended (use the same selector as in the publish):
            News.find({category: Session.get('newsCategory')})
        })
    })

What I wondered was: is there a use case where you can't use the same selector on the client as you did on the server? I can't think of a reasonable one. However, I just realized the usage of `options.limit` and `options.skip`do introduce some complications one would like to avoid.

**Comment by steph643** [comment]
@glasser

I understand how your proposal would solve the onReady issue accurately.

Some thoughts about it (beyond onReady):

1- It would probably have further implications on app architecture, but I cannot foresee them. I find the current philosophy charming and easy to grab, but at the same time I am having hard time achieving what I want...

2- I am interested in the CPU load aspect. As your "reconfigure commands" would be built client-side, I guess it means "merging" (hopefully most of it) would be performed client-side. This would reduce server load and impact issues such as reactive joins (feel free to comment on my point 2 [here](https://www.discovermeteor.com/blog/reactive-joins-in-meteor/#comment-1782704628)).

**Comment by mitar** [comment]
> You can't do that because subscriptions are merged on the server and data sent to the client is not tagged by subscription.

Oh yea. I would love to be able to make a query based on which subscription it came through! At this moment I have to tag that manually with a client-only field. (So I add a field in publish to every document, using [middleware](https://github.com/peerlibrary/meteor-middleware).) One simple use case if full text search where you cannot run the query on the client. So you have to know on the client which documents are result of full text search publish, and which documents are maybe getting in through some other publish. So while you can re-query on the client it is easy, then you limit using MongoDB, but if you cannot, then you are stuck. Having a tag could help a lot. Especially now that a subscription ID is getting into the codebase.

> And extend DDP so that you can send "reconfigure" commands to an existing subscription instead of dropping, restarting, and relying on the (expensive) server merge box. And finally, have the equivalent of onReady be called on each reconfigure too.

That could be useful. Especially for things like pagination and infinity scrolling. But it is also something packages can already do using one more layer of caching though, so you have a local collection on the server, which is populated from the MongoDB, and then each publish take data from there and modify how that local collection is populated, but otherwise is pretty thin and simple, so unsubscribing and resubscribing is not so big problem.

@steph643: Are you maybe mixing `onReady` with `Tracker.afterFlush`? Wouldn't you rather use `afterFlush` as a signal that `autorun` have finished? But yes, probably some logic would be needed which would make sure that you call your code both when `afterFlush` happened, `onReady` happened, and `onStopped` of the previous one also happened. :-)

**Comment by steph643** [comment]
@mitar: maybe I'm wrong, but I don't think the state of Tracker invalidation is related to the state of subscriptions. The fact that `autorun` has finished doesn't mean the subscription is ready, right? So I am not sure `Tracker.afterFlush` would be of any help... Am I missing something?

I am still not convinced the coming `onStopped` feature will allow to know when the local cache has been updated after a subscription stop. I am a bit confused and I am waiting wait for an answer [here](https://forums.meteor.com/t/how-to-know-when-a-subscription-has-finished-stopping/655/8).

Also, I hope this same answer will bring some insights about the kind of logic you describe, allowing to wait both for `onReady` on the new subscription and for `onStopped` on the previous one.

**Comment by mitar** [comment]
True, `afterFlush` by itself is not enough, you should combine it also with `onReady` and `onStopped`.

**Comment by steph643** [comment]
@glasser:

In my opinion, there currently are two big issues with Meteor: *Blaze context/scope* and *subscription control*.

The *Blaze context/scope* issue is now being publicly discussed ([here](https://meteor.hackpad.com/Blaze-lexical-scope-and-template-arguments-fZP806qG6xQ)). Even though it is an ongoing effort that will bear fruits in a distant future, it is comforting for us who are sweating on the current version of Meteor.

What about the *subscription control* issue discussed in this thread? (the biggest one in my opinion) Could this be made official the same way?

**Comment by mitar** [comment]
@steph643, I looked at the code here. I have not tested it, but why do you want to use `onReady` callback and not `ready()` reactive source?

Something like:

```javascript
Tracker.autorun(function (computation) {
  var handle = Meteor.subscribe('myCollection', Session.equals('dontShow', true));
  Tracker.autorun(function (computation) {
    if (!handle.ready()) return;
    computation.stop();

    console.log('Data as seen when ready:');
    console.log( MyCollection.find({}).map(function(o) { return o.value; }) );
  });
});
```

**Comment by steph643** [comment]
@mitar, `ready()` has the exact same issue: it will tell you when new data have arrived, but not when the old data have been removed. 

In your code, when `dontShow` changes, I think 'Data as seen when ready' will be displayed twice in immediate sequence:
- once when the new subscription is ready (because of `ready()` reactivity), displaying both old and new data,
- once when old data have been removed (because of `cursor.map()` reactivity), displaying only new data.

**Comment by mitar** [comment]
I wanted to jump and tell you that you are wrong, but I decided to run my code again and:
* no, autorun runs only once, when it is ready
* but you are right, documents are not removed as they should be, they stay there, previously I tried it only once and it removed all, so I thought this works, but that is a rare case, more often than not documents are still there when `ready()` triggers, but subscription is removing them

So when I am toggling the subscription, see that sometimes the even outputs are empty, but not always.

![screen shot 2015-10-05 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/585279/10293334/cde03656-6b68-11e5-9188-c8d32ffed5d2.png)

@glasser, this goes against your comment that:

> On the other hand, if you're just using reactivity rather than onReady, everything should just work.

So this is not true. Even if you use just reactivity, things do not work. I think this ticket should be reopened and fixed.

See reproduction here: https://github.com/mitar/meteor-issue-3194

**Comment by steph643** [comment]
@mitar, in your code, you stop the computation with `computation.stop()` (I didn't see it at first). I think that is why the message is not displayed twice (as I thought it would), and that is also why you don't really follow @glasser's advice to *"use reactivity rather than onReady"*.

**Comment by mitar** [comment]
No, I am using reactivity to wait for the subscription `ready()` to be `true`. Once it is `true`, I would assume (from @glasser comment) that I can be assure that the collection is updated with the state from the server-side publish. So I am using reactivity to wait for subscription `ready()` to be true.

**Comment by glasser** [comment]
What I meant was more broadly to use the reactive style of programming, so that we're talking about "data changes lead reactively to UI changes that are perceived by the eyes".  Eventual consistency, basically.  As opposed to "try to make something happen just once at a precise point in time and hope that its current view of the world is useful".

The mechanism of locating that single point in time (onReady callback vs complete-once autorun) is not relevant to what I was getting at.

That said, I think we've learned a lot over the past 4 years of Meteor, including that the super smooth eventually-consistent Tracker-based reactivity model doesn't actually let one accomplish all of one's frontend goals.

**Comment by mitar** [comment]
So maybe we should just have additional reactive source like `stopped()`? Then maybe this would work:

```javascript
var handle = null;
var oldHandle = null;
Tracker.autorun(function (computation) {
  oldHandle = handle;
  handle = Meteor.subscribe('myCollection', Session.equals('dontShow', true));
  Tracker.autorun(function (computation) {
    if (!handle.ready()) return;
    if (oldHandle && !oldHandle.stopped()) return;
    computation.stop();

    console.log('Data as seen when ready:');
    console.log( MyCollection.find({}).map(function(o) { return o.value; }) );
  });
});

**Comment by mitar** [comment]
So maybe what we should learn is that for every callback in every Meteor API, there should also be a reactive state variable for it?

I think this is what is often a problem. That there is some information which you can get only through callbacks, and then you start combining callbacks with reactive variables and things get messy, and wrong, and also do not allow to fully utilize reactivity and Tracker. We do not want to have to deal with messy callbacks.

**Comment by mitar** [comment]
So at least provide such reactive state variables. Then we as a community can build on top various helper things and see which patterns work or not. So the above code could then be made into a higher level `autorun`.

**Comment by tmeasday** [comment]
So for my 2c on this problem:

1. Although I think we should have a `.stopped()`, it's not necessarily super awesome because it makes you have to sweat the details of the way the old handle stops and the new one starts (i.e. referencing both of them as @mitar does above), which is really complicated to get right across all cases I would expect.

2. There are a bunch of other subtle problems you'll run into if you don't properly query for documents on the client:
  1. If you do animations and have two things on the screen at once, you may want both subs to be open
  2. If you use subs-manager you'll definitely have random subs open
  3. Other weirdness that we haven't run into you.

3. Given 2., and the lack of a client-side merge box, you need to figure out a way to query on the client always. 
  1. In simple cases a pattern around wrapping queries for publications is useful, like @SachaG's https://github.com/SachaG/smartquery
  2. @mitar's publication middleware is one more subtle approach
  3. Another is https://atmospherejs.com/percolate/find-from-publication which uses a secondary metadata collection.

**Comment by mitar** [comment]
Yes, but please add `stopped()`. Then we can build stuff on top of this. People would not have to do stuff like I did with point 1. directly. That can then be nicely wrapped.

**Comment by tmeasday** [comment]
You could build stopped yourself too though couldn't you?

**Comment by mitar** [comment]
It would be some ugly monkey-patching, I think.

Yea, but that goes back to my belief that Meteor should provide both reactive variables and callbacks for everything. I see the whole history of Meteor APIs as catching up. Once they make a callback interface, and then later on add reactive variable. And next time they add just reactive variable, but then later on a callback. (See for example accounts and login states and so on.)

I think it would be a good principle and even maybe something to be added to code style to just expose always both.

**Comment by tmeasday** [comment]
I agree 100%

**Comment by mitar** [comment]
I am proposing that in #5005 as well.
