### ISSUE TITLE
vm.runInThisContext has no third parameter

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#3200]
Just saw that you pass `true` as third argument [here](https://github.com/meteor/meteor/blame/devel/tools/server/boot.js#L171)

```
var func = require('vm').runInThisContext(wrapped, scriptPath, true);
```

vm.runInThisContext has no third parameter. So the true does nothing I think. I first thought it's something undocumented.

**Comment by d-schiffner** [comment]
Hi,
sorry for reposting in old issue, but the syntax actually has changed since then. The filename as well as the displayError is actually given as an object. It just silently ignore the old (undocumented behavior)

https://github.com/nodejs/node/blob/master/src/node_contextify.cc#L539

**Comment by abernix** [comment]
@d-schiffner The link you've provided is to the `master` branch of `node`, however Meteor is using Node.js 4.x.  The API has changed since then, but [here is what Meteor would be using](https://github.com/nodejs/node/blob/v4.x/src/node_contextify.cc#L475) and it would appear that the argument would be observed.

**Comment by d-schiffner** [comment]
Hi @abernix,

you're correct, but the changes to the api are way older. In the given version (4.7.x) the same applies. The methods `Get*Args` all take the same object

```
 static Local<String> GetFilenameArg(const FunctionCallbackInfo<Value>& args,
                                      const int i) {
    Local<String> defaultFilename =
        FIXED_ONE_BYTE_STRING(args.GetIsolate(), "evalmachine.<anonymous>");

    if (args[i]->IsUndefined()) {
      return defaultFilename;
    }
    if (args[i]->IsString()) {
      return args[i].As<String>();
    }
    if (!args[i]->IsObject()) {
      Environment::ThrowTypeError(args.GetIsolate(),
                                  "options must be an object");
      return Local<String>();
    }

    Local<String> key = FIXED_ONE_BYTE_STRING(args.GetIsolate(), "filename");
    Local<Value> value = args[i].As<Object>()->Get(key);

    if (value->IsUndefined())
      return defaultFilename;
    return value->ToString(args.GetIsolate());
}
```

I would assume, at some point, the string backward compatibility will be dropped, and furhtermore, the "undocumented" boolean flag is actually never used (See https://github.com/nodejs/node/blob/v4.x/src/node_contextify.cc#L604)

**Comment by glasser** [comment]
That said, if we know the API is likely to change in a future version of Node it probably makes sense to proactively change our code to detect version (or detect feature) and work under both.

**Comment by d-schiffner** [comment]
I looked up the history, since when the option object has been introduced and i stumpled upon the old commit from Aug 2013 

https://github.com/nodejs/node/commit/fd3657610e49005dfc778c3f060dbba0a34f286a

`Passing a filename is still supported in place of certain options
arguments, for backward-compatibility, but timeout and display-errors
are not translated since those were undocumented.

Also managed to eliminate an extra stack trace line by not calling
through the `createScript` export.

Added a few message tests to show how `displayErrors` works.`

It actually states, that display-errors is not processed, so passing this option is actually invalid. I don't think it is necessary to check for an "old" version here, unless you want to be compatible with a VERY old nodejs version
