### ISSUE TITLE
Do another pass of profiling requires

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3217]
If you set METEOR_PROFILE_REQUIRE you get a nice profiule of what we spend time requiring.  Let's do a pass to make sure that we don't spend extraneous time on unnecessary requires for commands that should be fast.

**Comment by hwillson** [comment]
Numerous [performance optimizations have been included in version 1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142), which came (in part) from the results of running a lot of profiling against the Meteor codebase. Given this, and the fact that this issue is > 2 years old, I'll close it off. Thanks!
