### ISSUE TITLE
email package: false negative log message when e-mail sent

### ISSUE THREAD

**Issue by petermikitsh** [meteor/meteor#3219]
If I configure my MAIL_URL in a startup script, e.g., via the `settings.json` file:

```javascript
// METEOR@1.0
// server/startup.js
Meteor.startup(function () {
  process.env.MAIL_URL = Meteor.settings.MAIL_URL;
});
```

And then send an e-mail via the email package, the console incorrectly logs that mail was not sent:

```
====== BEGIN MAIL #0 ======
(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
```

But e-mails definitely do send.

**Comment by glasser** [comment]
This is printed by the function that is called instead of actually sending the mail, so I'm pretty sure that this particular call to Email.send really is not sending any mail.  I can certainly believe there's some issue here, since you think you're setting $MAIL_URL and it isn't taking effect.  Please submit a cloneable reproduction so we can more clearly see what you're doing and we can reopen this bug: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor
