### ISSUE TITLE
Contributing guide is lacking information how to run Meteor tests

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3255]
Contributing guide is lacking information how to run Meteor tests directly from a checkout of a Meteor repository.

**Comment by glasser** [comment]
That's a good point.  Feel free to propose some text.

**Comment by ryneeverett** [comment]
Any chance of a casual explanation right here in the meantime?

**Comment by abernix** [comment]
@mitar, what do you think?  [This exists now](https://github.com/meteor/meteor/blob/devel/Contributing.md#running-tests-on-meteor-core), but I don't think there is any documentation on `self-test`, for example.  Might be useful.

**Comment by hwillson** [comment]
Information about running internal Meteor tests is currently documented in 2 places:

1. The [Contributing](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/Contributing.md) guide outlines how to run tests for internal Meteor packages.
2. The [Meteor Tool README](https://github.com/meteor/meteor/blob/8a81e7156e07ca9e1a6c2b2b89870eb4abe72a2d/tools/README.md) outlines how to run Meteor `self-test`'s.

Since most contributors will start with the Contributor guide, I think adding a link to the Meteor Tool README in the tests section (mentioning to see that README for Meteor Tool testing) should help address this issue. If you guys agree, I'll submit a PR. Thanks!

**Comment by hwillson** [comment]
I've submitted a small PR to help address the items I mentioned in https://github.com/meteor/meteor/issues/3255#issuecomment-268354700. Thanks!

**Comment by hwillson** [comment]
Since #8186 was merged in, I believe this issue has now been addressed. Thanks all!
