### ISSUE TITLE
Add discoverable button/input field for docs search

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3264]

**Comment by avital** [comment]
I'd love for this to exist!

**Comment by stubailo** [comment]
Yeah I've been working on this on/off. There's a branch with some stuff but it doesn't look as nice as I want yet.

**Comment by abernix** [comment]
Well, the new docs are here, but there's no search at all, so this is no longer a problem! :wink:

But in seriousness, there's an issue over there (meteor/docs#5) to track the lack of search, and it will very likely (it has to be) be a very discoverable input because things are now on different pages entirely.

Closing this in favor of that other issue.
