### ISSUE TITLE
[package sys] Getting permission error on one package when publishing

### ISSUE THREAD

**Issue by raix** [meteor/meteor#3307]
Hi I'm getting this error when doing `$ meteor publish`

```bash
# publishing cfs:filesaver
$ meteor publish
Reading package...                            
                                              
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EACCES, mkdir '/private/var/folders/8b/2r3gpvjd69q5nhqr7ld9wxrw0000gn/T/.tmpj7575m/underscore-1.0.1-pre.0-os+web.browser+web.cordova/os'
```

So I've tried to sudo and remove the temp folder and published again - but same error just a different temp folder. Super odd.

All other packages are published just fine, not sure how to replicate this

Kind regards Morten

**Comment by avital** [comment]
Could it be that any of the following folders don't have write permissions for all users: `/private`, `/private/var`, `/private/var/folders`? (On my machine, they are all owned by root but writeable by all)

**Comment by glasser** [comment]
Are you still seeing this in 1.0.2 or later?  We changed a lot of the code around how we build things for publish in 1.0.2.  (You didn't mention which meteor release you were using, which would have been helpful.)

Also, I suspect there was a larger stack trace which would have been convenient.

Since we rewrote a bunch of this code, closing. Can reopen if you're still seeing this.
