### ISSUE TITLE
Error: key $type must not start with '$'

### ISSUE THREAD

**Issue by pdavidow** [meteor/meteor#3310]
Simply hit the test button.
https://www.dropbox.com/s/1iosnrvvf1dz330/meteor_bug.zip?dl=0

**Comment by pdavidow** [comment]
This is a serious bug as it prevents sending array of type over the wire.
Please advise.

**Comment by glasser** [comment]
`Measure.toJSONValue` returns an encoding of your type that is valid JSON but is not valid for inserting into mongodb, because Mongo has extra restrictions on valid documents.  If you instead just tried `MeasureCollection.insert(measure)` you would have gotten the error `Only plain objects may be inserted into MongoDB`.  We don't support EJSON custom types at the top level.  However, you can do something like `MeasureCollection.insert({measure: measure})` to insert a top-level plain object which has a field which is an EJSON custom type.

**Comment by pdavidow** [comment]
If 'measure' (top-level custom-type) holds onto to a simple object like number, then it actually works; however, if 'measure' holds to a custom-type (not necessarily in an array), such as 'beat', then it does not work.  So, I'm not sure what you mean by 'We don't support EJSON custom types at the top level.'

Please see my latest commit:
https://github.com/pdavidow/meteor-issue-3310/tree/9b48b0d28dae19adcb312e9afa5a4480c67df7e3

**Comment by pdavidow** [comment]
Perhaps the issue may have something to do with:
https://github.com/LearnBoost/mongoose/issues/2012

**Comment by glasser** [comment]
This is not a bug.  What it comes down to is `Collection.insert({$type: 'x'})` and that's not valid with Meteor, end of story.

If you can find official MDG docs that tell you that you should call `toJSONValue` on things and then insert the result of that into a Mongo collection, then that would be a bug.

**Comment by pdavidow** [comment]
Please update official doc to reflect your above non-obvious point:

"We don't support EJSON custom types at the top level. However, you can do something like MeasureCollection.insert({measure: measure}) to insert a top-level plain object which has a field which is an EJSON custom type."

Thanks

**Comment by pdavidow** [comment]
It would be nice to have your input here:
http://stackoverflow.com/questions/28308816/meteor-custom-type-find
