### ISSUE TITLE
installer script displays incorrect version number

### ISSUE THREAD

**Issue by AJ-Acevedo** [meteor/meteor#3378]
Not sure if this is the correct repo for submitting suggestions and issues for the installer script hosted at https://install.meteor.com but there does not appear to be a repo for it.

I just ran `meteor update` and it successfully installed Meteor 1.0.2.1.

When the update completed the following message appeared
`Installed. Run 'meteor update' inside of a particular project                   
directory to update that project to Meteor 1.0.1.`

It appears that [release.current.getDisplayName](https://github.com/meteor/meteor/blob/6320acabc46bd6832d2f6db943b69a0634d6b6f9/tools/commands-packages.js#L1576) is not displaying the correct version number of 1.0.2.1.

When I run `meteor --version` from the CLI it displays the correct version of 1.0.2.1

**Comment by glasser** [comment]
This is specific to the pre-0.9.0 upgrade scripts which only affects users who haven't run meteor at all since August.  It's an extra step to our release process that we've stopped doing because it only affects the monotonically decreasing number of users who haven't touched meteor since August, and only affects this particular message that you just saw.
