### ISSUE TITLE
Structure meteor repository as git submodules

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3387]
Structure meteor repository so that every package is in its own git repository, combined together with git submodules.

This would make forking (and integrating upstream changes) a core package much easier.

There are few packages which would really benefit from that:
* `http`
* `accounts-ui`
* `mimimongo`

**Comment by mitar** [comment]
I think they know that. With Meteor 1.0 release those projects are listed on their [site](https://www.meteor.com/projects). I think it is just the question of resources to split this and prepare separate packages.

But it is a tricky question about tickets and development. Where to open a ticket? I think having multiple repositories and multiple GitHub projects would confuse things here a lot. Where does one using whole Meteor open a ticket against Blaze? Where somebody who is using only Blaze?

Personally, I think it is good that things are tightly integrated and have one repository for development and tickets. But I would like to be able to easy maintain a fork of a package.

It could even be an automatically synced directory from main Meteor repository. So meteor/blaze could be a read-only repository I can fork, but no commits would be made there.

**Comment by mquandalle** [comment]
Why do you consider hard to maintain a fork today ? `git subtree` should do the work, no?

**Comment by mitar** [comment]
I don't think `git subtree` allows me to take the Meteor's `package/minimongo` package and put it in my project's `packages` directory?

**Comment by glasser** [comment]
git submodules are pretty confusing.  I'm basically a former Version Control Professional (having spent all of my career before Meteor building version control systems) and *I* barely understand how submodules work.  When we had one in our repo in the past it mostly led to a lot of pain.  I suspect there are scripts to make things better (maybe the one Google uses for Android) but it's definitely a big cost for a questionable benefit.  Subtree is kinda better, but it still does create more release management work.  Right now we're trying to find out ways to make maintenance and release management less work for MDG rather than more, and I think this would be counterproductive.

I do think we should break out some of our packages from the "release".  We've already started doing that (see the `packages/non-core` directory) and we should probably start moving them into separate repos at some point.  These are best for packages that don't change too often (so it's easy to remember to publish them when we change them) and rarely change in ways that require corresponding atomic changes in other packages.  I think http is one of them; minimongo, on the other hand, often has changes that go along with changes in ddp or mongo.

**Comment by mitar** [comment]
What about an automatic sync of a package into its own read-only repository? So `packages/minimongo` could be synced into `meteor/minimongo` repository, synced on every push into main `meteor` repository?

**Comment by mitar** [comment]
BTW, a common practice is to add forked packages as git submodules under `packages`. So developers are already used to using them.

**Comment by mquandalle** [comment]
https://github.com/meteor/meteor/commit/634c6d623b131d90a78557eb3c17b6f02de230bc

**Comment by mitar** [comment]
Interesting: http://danluu.com/monorepo/
