### ISSUE TITLE
Add SMTP envelope to mail function

### ISSUE THREAD

**Issue by svennergr** [meteor/meteor#3388]
Hey,

in some cases, for example if you want to set a certain "Return-Path" header, there is a need to set a SMTP envelope in the current mail function.
Since meteor uses the `mailcomposer` module in the background, it should not be too hard to implement this: https://github.com/andris9/mailcomposer#add-message-parts

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This one is pretty simple, so we'd probably take a PR that contains tests.

**Comment by hwillson** [comment]
While adding SMTP envelope handling functionality to the `email` package sounds like a good idea, it has been a couple of years since this feature request has received any attention, or gained any traction. Also - the original issue mentioned the idea of being able to override the `Return-Path`. It's worth noting that `mailcomposer` / `Nodemailer` (which the `email` package uses) has [decided not to support this functionality](https://github.com/nodemailer/mailcomposer/pull/34#issuecomment-47445532), since [RFC 822](https://tools.ietf.org/html/rfc822#section-4.3.1) states this should be handled by the email transport system, not an email client/library.

Given the above, I'll close this for now. Happy to re-open if anyone disagrees. Thanks!
