### ISSUE TITLE
Meteor Accounts only authenticates DDP, not HTTP

### ISSUE THREAD

**Issue by aadamsx** [meteor/meteor#3390]
I posted a SO question: http://stackoverflow.com/questions/27734110/authentication-on-server-side-routes-in-meteor

And wanted to follow up on it here as well...

Why can I only get the Meteor.userId() / this.userId in Publish/Methods in Meteor?  Why does it seem I'm being forced into a hack, using cookies/local storage, in order for the server to "know" who is logged in on a situation that seems to me so common as a server route to a static pdf file?

This seems like such a common web development scenario (coming from a business/.net background).  Get a file: pdf/image/anything and render it to the screen.

Everything in Meteor has so far been great, superb platform to work with (again coming from a .net background), yet I've really surprised by this.

**Comment by glasser** [comment]
We use localstorage and explicit code that sends authentication over a DDP websocket instead of cookies to do auth.  This has some good security properties (eg, we've been protected from several web-wide issues in the past few years that broke most cookie-based sites) but as you observed, does mean that you can't authenticate anything *other* than DDP websockets.

We may at some point in the future decide to switch over to cookies, which would fix this.

**Comment by avital** [comment]
Here's a blog post we wrote about how Meteor auth-via-localStorage works and some of the challenges with using cookies instead: https://www.meteor.com/blog/2014/03/14/session-cookies

**Comment by hwillson** [comment]
Using `localStorage` and DDP for authentication instead of session cookies was/is an intentional Meteor design decision. Given that this hasn't changed since this issue was created (almost 2 years ago), and the lack of +1's (not a popular feature request), I think it's safe to assume this isn't going to change anytime soon. As part of the on-going old issue cleanup process, I vote to close this issue.
