### ISSUE TITLE
Android Icon Size mdpi is wrong 

### ISSUE THREAD

**Issue by harryworld** [meteor/meteor#3419]
`android_mdpi` is set, but the output of Android build keeps using the default phonegap icon.

I checked the cordova tool at

`~/.meteor/packages/meteor-tool/.1.0.38.zn45zr++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js`

https://github.com/meteor/meteor/blob/devel/tools%2Fcommands-cordova.js#L1362

On line number 1363, it states android icon size `42x42`, where meteor and phonegap documentation suggest `48x48`  

```
var iconAndroidSizes = {
  'android_ldpi': '36x36',
  'android_mdpi': '42x42',
  'android_hdpi': '72x72',
  'android_xhdpi': '96x96'
};
```

Reference:
https://github.com/meteor/meteor/blob/devel/examples/todos/mobile-config.js
https://github.com/phonegap/phonegap/wiki/App-Icon-Sizes

**Comment by Slava** [comment]
Thanks, I will take a look at this next time I am fixing cordova icons code.

**Comment by Tarang** [comment]
This also creates the wrong `res/drawing/icon.png`. 

Its quite bad because this is the icon that comes on the play store in certain instances.

**Comment by simakwm** [comment]
I think it is because of this issue the launcher icon on my device running Lollipop are always reverted to Meteor's default icon. Running the app on the Android emulador (which runs KitKat) shows the launcher icon I specified in mobile-config. Maybe Its launcher is ldpi?

**Comment by mkimmet** [comment]
When I try to run my app on a low resolution LG Optimus Fuel running KitKat it shows the default Cordova icon and not my custom icon.  On my higher resolution Android tablet the custom icon works, but in Settings-->Apps it shows the default Cordova icon as well. Is this related to the 42x42 bug?  

If I do a "meteor build" the following build folder is empty, while all the other drawable folders have icon.png files:
myapp-build/android/project/res/drawable-mdpi

**Comment by charles-neemtec** [comment]
I am also facing the same issue.
In Settings-->Apps it shows the default Cordova icon as well. Is this related to the 42x42 bug?

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

**Comment by simakwm** [comment]
Thanks!

**Comment by timmakken** [comment]
I was about to create a new issue but i think here may be a better place since its so similar:
would be issue title : Android Icon Size ldpi is wrong/ no longer supported
`WARNING: android_ldpi: unknown key in App.icons configuration. The key may be deprecated.
` 
was the verbose output when i added the ldpi icon to the mobile-config.js
to test if it was my app that was bugged i cloned the todos example and ran it on both my phone and nvidia shield tablet.
my phone displays the icon properly but my tablet does not.

According to the cordova docs there should be a ldpi size.
and according @martijnwalraven 's post it should be there aswel

So i hope it can be added back to the build tool that would be great :+1:
