### ISSUE TITLE
Meteor.call or Meteor.method is not working on cordova android

### ISSUE THREAD

**Issue by vonrussel** [meteor/meteor#3428]
I created a dummy meteor method on the server and try calling it on the client once a button is clicked. The server method contains inserting a data in a dummy collection. I also added logs to check if callback of method is reached but turns out it did not. I can't see any added data in the dummy collection. 

Thanks in advance.

**Comment by Slava** [comment]
We require a clonable reproduction with step-by-step instructions with every bug report. Otherwise, we cannot reproduce the issue.

Meteor methods work well for me and you can try running an example like Todos to validate that it works. In your case, check that your mobile app can connect to the Meteor server (they should be on the same network and server should be accessible).

**Comment by ulyssey** [comment]
I have the same issue. Here after a reproduction:
https://github.com/ulyssey/Meteor_Call_not_working_with_cordova_android

It's quite possible i forgot something, but I did not see anything that must be done specificaly for the android/cordova app in this case.

Thanks.

**Comment by benjick** [comment]
Having the same problem, doing it the same way as @ulyssey is doing

**Comment by vigile** [comment]
My project worked perfectly. Then I faced the same problem. I reproduce the same projet describe here and I have the outcome.
Any advice on this?
Thanks!
