### ISSUE TITLE
Changing server from a phonegap application

### ISSUE THREAD

**Issue by partus** [meteor/meteor#3435]
I have several meteor  servers and one application on the mobile market, In which I want to allow the user to change the sever. The servers contain different mongo data ( and maybe different client and server code). The question is: how can I change the server from mobile application? If it is not suported, I would like to develop this functionality. As you are the developer of meteor, can you briefly describe what is the easiest way to implement it? 

I also posted the question on stackoverflow, but no reasonable answer there http://stackoverflow.com/questions/27743079/dynamically-changing-mobile-server-from-meteor-phonegap-application/27743299#27743299

**Comment by Slava** [comment]
@partus 

Hi, I think what you are looking for is [`DDP.connect`](http://docs.meteor.com/#/full/ddp_connect). It allows you to hold multiple connections to different Meteor servers and call the Meteor methods there and subscribe to publications.

For the Hot Code Push functionality, you would always need to chose one main server that you bundle into your app. Switching the HCP sources on the fly is not supported by design of this feature.
