### ISSUE TITLE
Get full command-line docs on the web

### ISSUE THREAD

**Issue by matteodem** [meteor/meteor#3474]
Having a more detailed documentation for commands like "set-unmigrated" on http://docs.meteor.com/#/full/ and others would be helpful. Also I don't see "set-unmigrated" in the list when executing `meteor admin help`.

**Comment by mquandalle** [comment]
You can always

```sh
$ meteor admin set-unmigrated --help
```

**Comment by matteodem** [comment]
I know, but the set-unmigrated command is nowhere to be found in the official docs.

**Comment by stubailo** [comment]
This is a good point - there should be complete documentation for the command line tool on docs.meteor.com/#/full. We should figure out some way to avoid duplicating the help.txt, though.

**Comment by glasser** [comment]
Right now though, the docs on docs.meteor.com ("full") are intended to be an overview.  I don't think that trying to maintain two separate but complete versions of the docs is a good idea.  We should either make the docs.meteor.com part just be built from help.txt, or provide some other nice UX around seeing help.txt on the web.  Maybe the "full" docs should contain a (prettier) help.txt and the "basic" docs should contain something like what's on "full" now, minus some of the more rarely used commands.

Until we do that, it's probably helpful to note that the current state *is* that it's just an overview; I've added that in 1541a31.

As far as `set-unmigrated` goes, there's a reason that it's a hidden command --- it was a specific short-term command designed around a specific migration that happened last August.  I recognize that since we don't have a delete-version command, it's useful to continue to use `set-unmigrated` to achieve a similar goal, and we probably shouldn't remove `set-unmigrated` until we provide a better tool to delete versions.  But I don't think we need to shine a spotlight on it either.

**Comment by matteodem** [comment]
Okay, I think that's understandable. When executing ```meteor help``` though, it does not show the admin command in that list:

```bash
meteor help | grep admin
```

**Comment by glasser** [comment]
Yes, that's what I was alluding to re "hidden command".

**Comment by dandv** [comment]
I was about to send a doc patch adding "--update" to `meteor publish`, when I saw this issue. I understand why the help shouldn't be duplicated on docs.meteor.com/full.

On the other hand, most developers, especially those who *have* used Meteor before, will search through the docs (thanks in part to @stubailo's excellent search feature), or will land to a specific command from the ToC or via an anchor link found online, e.g. http://docs.meteor.com/#/full/meteorpublish

In all these frequent cases, they'll miss the new overview paragraph, and may reasonably conclude that the options presented under each command represent the full set of options. Also, when searching for something like "unmigrated" returns nothing, the developing experience is suboptimal.

What would be some ways to address this?

* Include a bit of text at the end of each CLI command along the lines of "This is only an overview; please consult `meteor help` for more information"?
* Transclude the full help in both docs.meteor.com and `meteor help`, and maybe hide it on docs under a "Show more" link?

**Comment by matteodem** [comment]
I understand that hidden commands shouldn't be shown in the docs, but to my understanding ```meteor admin``` is not a hidden command. So for me there's no reason to __not__ show it in the ```meteor help``` command.

The first variant by @dandv would be okay for me, as long as ```meteor help``` lists all "official" commands as http://docs.meteor.com/#/full/meteorhelp does.

**Comment by glasser** [comment]
You're right, it would be helpful for 'admin' itself to show up at the top level, because there are real supported commands under it. Fixed.

**Comment by matteodem** [comment]
Perfect, thank you.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/3474#issuecomment-70759911, the web based command-line docs (now located at http://docs.meteor.com/commandline.html) are intended to show an overview of the more common command-line options, not all possible options. The main remaining suggestion in this issue thread (to make sure `admin` shows up at the top level of the command-line help docs) has been addressed, so I'll close this issue. Thanks very much!
