### ISSUE TITLE
Will meteorjs ever switch to io.js?

### ISSUE THREAD

**Issue by itsnauman** [meteor/meteor#3479]
Well I am just curious whether meteor will continue with node or will it switch to io.js in the near future? :smiley:

**Comment by mitar** [comment]
Why it would?

**Comment by mitar** [comment]
And this is more suitable question for meteor-core mailing list, not GitHub.

**Comment by jagi** [comment]
I think it's good idea to move to io.js because it's compatible with node and follow the newest standards where node is still far behind. Support for ES6 would be nice.

**Comment by glasser** [comment]
We use GitHub to track bugs feature requests in Meteor, and this is more of an open-ended discussion topic.  We at MDG do our best to provide some sort of real response to everything on GitHub, and opening the floodgates to vague questions about the future would really make it harder to meet that standard. Specific concerns like "I tried to run a bundled Meteor app in iojs and it failed because..." would be better suited for GitHub; questions like this maybe should be aimed at the meteor-talk mailing list.

We'd certainly love to see (on the mailing list) discussions about what successes or challenges users are seeing using io.js vs Node, and when it comes time for us to upgrade the JS engine we ship with Meteor again we'll certainly consider all options.

**Comment by v3rron** [comment]
http://venturebeat.com/2015/05/13/node-project-spinoff-io-js-is-moving-to-the-node-js-foundation-with-a-merge-in-progress/
