### ISSUE TITLE
Offer reusable packages as standard Node modules?

### ISSUE THREAD

**Issue by ericelliott** [meteor/meteor#3480]
Packages like Minimongo, Tracker, Blaze would all have broad appeal if they were offered as Node modules.

Is there any chance you'd be willing to work with me on an effort to port them into Node modules?

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests). I'm not sure that this is likely to be high priority compared to other things on our roadmap right now.

I think it would be great to make it easier to export server-only Meteor packages as npm packages.  As far as the core packages go, it would be nice to have them accessible outside of Meteor, but it definitely will add more release engineering and QA work to what is already a thorough project.  There's a fair amount of design required too; for example, should we publish each package fully separately (so that we attempt to replicate the meteor dependency structure in npm packages) or publish each package as a "statically linked" copy containing all its dependency?  Pros and cons to either.

**Comment by hwillson** [comment]
A full transition to npm is planned, and will likely happen at some point in the not too distant future (as mentioned in the [`Roadmap.md`](https://github.com/meteor/meteor/blob/devel/Roadmap.md#full-transition-to-npm). Since this work is already being tracked in the Roadmap, I'll close it here. Thanks for suggesting this originally - and while I'm at it - thanks for everything else you do @ericelliott! 🙂

**Comment by ericelliott** [comment]
👍
