### ISSUE TITLE
Events not firing in meteor command line programs

### ISSUE THREAD

**Issue by jsep** [meteor/meteor#3488]
In this example repository you will find a meteor command line program where both Meteor.setTimeout and and child_process stdout  data events are not being called.

https://github.com/practicalmeteor/meteor-cli-app-bug-no-events

**Comment by rbabayoff** [comment]
Steps to reproduce:

```
git clone https://github.com/practicalmeteor/meteor-cli-app-bug-no-events
cd meteor-cli-app-bug-no-events
meteor --once
```

**Comment by rbabayoff** [comment]
You can close this. Works with futures.

**Comment by rbabayoff** [comment]
I made it work with futures. But would love some guidance on how exactly would you go about it.

**Comment by glasser** [comment]
The way `main` works in Meteor is that if you don't return `'DAEMON'`, the process will exit.  So returning `'DAEMON'` from `main` mostly fixes your app.  (You also want to listen on the `close` `child_process` event rather than `exit`.)

Note that this API is not particularly supported yet; it may change in the future.

**Comment by rbabayoff** [comment]
I already implemented async support using futures in [mcli] (https://atmospherejs.com/practicalmeteor/mcli) :) and yes, close is what I used in the sample command.

Question regarding DAEMON, even though it's not our use case, but for future reference, how do I exit? Plain process.exit or should I use one of the signals, (and if yes, which one) or is there an exit api?

**Comment by glasser** [comment]
`process.exit` is fine.
