### ISSUE TITLE
[accounts-password] forgot-password should not tell whether account exists

### ISSUE THREAD

**Issue by iStefo** [meteor/meteor#3502]
While convenient for the user, there should be no information about whether an account for a given address was found or not. The generic message should be something like "We sent a link, please check your inbox" regardless of success or failure.

Otherwise, an attacker could try to find out about registered email addresses (or even about *valid/existing* email addresses for spam purpose). We don't want to expose our users to a potential threat like this.

Is there a way to fork accounts-password without cloning the whole meteor repo? I'm new to the meteor ecosystem, thats why I'm asking.

**Comment by Tarang** [comment]
Isn't this counterproductive? You could attempt to sign up and find out whether the user exists or not

**Comment by iStefo** [comment]
True. This is why the login error message should be more generic, too. More like "Username not found or wrong password."
For example, Google does exactly this ("The entered email address or password is wrong." translated freely from German). Facebook, on the other hand, even shows the profile picture of the email you entered, if registered. For more sensitive systems though, hiding as much information as possible would be a reasonable thing to.

**Comment by Tarang** [comment]
@iStefo I understand what you're saying. I just mean it's quite pointless to someone who has malicious intent on compromising an account. Even on Google, one can find whether the email is active by trying to sign up and it tells you right on the front page, without even having to sign up.

Also, the login message can be altered by placing the code like follows in your `/server` directory

```
Accounts.validateLoginAttempt(function(info) {
    if(!info.allowed) throw new Meteor.Error(500, "The entered email address or password is wrong");
}
```

It also depends on what app you're trying to build. I prefer to know if I entered the wrong username/email, since I use many emails to avoid spam to sign up to sites. 

Given that you can already exploit the fact whether an email or username is wrong, its a bit odd to remove the information which can be useful in avoiding frustration to a user, when it is available anyway?

**Comment by iStefo** [comment]
Now I see what you mean. When registering, you can find out whether an address is in use or not. Preventing automated registrations is another goal we have in mind, but would probably require using a CAPTCHA.

Thanks for the hint with replacing the error message, that seems like the right choice for the initial problem! However, I'd like to hear more opinions on this topic and therefore leave this issue open for now.

**Comment by glasser** [comment]
We've commented on this concern in the past in https://github.com/meteor/meteor/issues/1206#issuecomment-21157488
and https://github.com/meteor/meteor/issues/2139#issuecomment-43156013

I think we're still pretty sure that the best default is to provide superior UX.  It would be possible to add the "worse UX, slightly better security" as a configurable option, but it would definitely be a big maintenance burden to ensure that all changes to accounts-password preserve this functionality.  (And it's quite difficult to avoid timing attacks on V8 servers without just adding extra random latency or something.)  For now I don't think we want to try to make this promise to users if we aren't sure we can keep it.
