### ISSUE TITLE
[accounts-password] should limit the maximum login tries

### ISSUE THREAD

**Issue by iStefo** [meteor/meteor#3503]
In order to harden the login system, a reasonable maximum try count for logging into a specific account should not only be an option, but the default. I'm thinking about ~10 tries within an hour or so. After that, neither successful nor unsuccessful login should be permitted. Otherwise, the account system is vulnerable to automated attacks testing smaller wordlists.

Notifying the user about more than a few failed login attempts via email would also be a nice feature, but definitely an optional one.

As we don't want the (genuine) user to be completely locked out of the system, resetting the password should also reset this limit.

What do you think? In contrast to #3502, this one needs more engineering to work properly.

**Comment by glasser** [comment]
We added [login hooks](http://docs.meteor.com/#/full/accounts_validateloginattempt) to allow users to build their own rate limiting systems rather than hard coding a few policies into core.

It looks like https://atmospherejs.com/matteodem/easy-security is a package that does this (though I'm surprised that it doesn't use `validateLoginAttempt`).
