### ISSUE TITLE
Enforce strict mode globally with meteor run --strict

### ISSUE THREAD

**Issue by meonkeys** [meteor/meteor#3510]
Idea: add a `--strict` argument to `meteor run` to enforce `'use strict';` on all the application's JavaScript source code.

**Comment by andylash** [comment]
It's not that easy though.  Every file in meteor is wrapped in a closure.  That's how anything with a var is scoped to the file only, anything without var is global to the app (or to the package if you're in a package).
If you "use strict" a file, you change this semantics (and everything is scoped to the file).  Basically this means that if you want globals in a file you can't have use strict on the file.  A nice technique is to put just the declarations of globals in a separate file that isn't "use strict"'d where all the other code is.

Anyway, this is presumably possible to change, but it would seem like a pretty big change in meteor.

**Comment by meonkeys** [comment]
Ah, good point. A convention/API for app globals would be handy too.

**Comment by yauh** [comment]
Looks like this issue may be related: https://github.com/meteor/meteor/issues/1380

**Comment by glasser** [comment]
Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I agree that it's not helpful to apply "use strict" at the local level of individual files, but we could make it so that when the linker joins each package (things are slightly different in the app) into a single file (and converts "globals" into package-level locals) that it includes "use strict".  Maybe this would be a setting in the package's `onUse` section.  (And we'd get this in the app once we implement https://trello.com/c/mHK2dpr5/68-new-way-of-defining-packages-and-controlling-file-load-order )

I don't think that having this as a runtime option makes sense; it should be part of your source code.  Otherwise you have two developers working on a package and an app; one of them runs with `--strict` and gets annoyed when the other one keeps accidentally adding non-strict code.

**Comment by abernix** [comment]
Closing this.  It's up to the developer to add `use strict` if that's something they would like to use.  As mentioned above not doing so could cause inconsistency for developers working on the same project.  Additionally, Meteor 1.3 supports ES2015 modules, so if you want to `use strict`, you'll be able to work around Meteor's global variable style which was previously could have been problematic when combined with `use strict`.

**Comment by meonkeys** [comment]
@abernix Thanks. That's fair, and I appreciate the clear decision and explanation.

FWIW, my team uses the `"strict": true` .jslint setting to enforce that (among other conventions) `use strict;` appears at the top of every `.js` file.
