### ISSUE TITLE
meteor show should render markdown in the README to text-only version

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3519]
Currently it just displays the README raw. But it could render the README and for example wrap lines based on the terminal width.

**Comment by stubailo** [comment]
This is a good idea for an improvement! We have talked about this as well, and I'm sure we will have it eventually.

**Comment by ekatek** [comment]
Can you give an example where we don't wrap lines based on terminal width? We should be doing that automatically.

**Comment by mitar** [comment]
Terminal wraps it, but then it does not render markdown and aligns the text as it should be. Compare this with `man` pages, they can nicely adapt to the width of the terminal. You just dump the markdown file as it is. This is not "wrapping" I had in mind. ;-)

![untitled](https://cloud.githubusercontent.com/assets/585279/5929380/23ac1ac4-a638-11e4-9c97-d50ba3cc2ea9.png)

**Comment by hwillson** [comment]
While the identified wrapping issue does still happen in some cases, I think we're safe to close this issue. There has been very little interest in this issue in over 2 years, and most people are accessing package README's/details via [Atmosphere](https://atmospherejs.com), 3rd party sites like http://fastosphere.meteorapp.com, or from GitHub directly. `meteor show` is definitely a useful feature, and although the formatting can be off at times, the text based README content is still (almost always) visible / legible. Happy to re-open if anyone feels otherwise - thanks!
