### ISSUE TITLE
meteor set-unmigrated does not yank package

### ISSUE THREAD

**Issue by fourseven** [meteor/meteor#3524]
Hi, I've tried to publish a binary-dependant package (`fourseven:scss@1.2.3`) but npm's `node-sass` does not build on the linux meteor build boxes. 

I ran `meteor admin set-unmigrated fourseven:scss@1.2.3` to try and remove it again but it's now the default version to install, even though that version doesn't have linux binaries, and will never be able to build them.

How do I remove a package version from atmosphere/meteor packaging?

**Comment by fourseven** [comment]
Any updates or suggestions here please?

**Comment by glasser** [comment]
There's a reason that `set-unmigrated` is barely documented and has a weird name, which is because it doesn't actually delete/deprecate a package. It has a specific technical use related to the migration from the old community Atmosphere package database to the new core package database.  We haven't removed it because people do find it useful as a workaround for the lack of a delete/deprecate package command, but the fact that it doesn't do the same thing isn't really a bug.

See #2459 for the feature request about deleting/deprecating packages.
