### ISSUE TITLE
Minimongo allows numeric IDs, but server-side MongoDB throws an exception

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#3527]
> Meteor requires document _id fields to be non-empty strings or ObjectIDs

But numeric IDs are even in Minimongo [tests](https://github.com/meteor/meteor/blob/devel/packages/minimongo/minimongo_tests.js#L115). So the question is: should this be synced? So that behavior is the same? Why exactly does server-side does not allow numeric IDs?

**Comment by glasser** [comment]
I think the history here is that we used to only support string IDs, and there was a heroic amount of work (including designing EJSON) in order to allow ObjectID also, and that one particular check in collection.js didn't get updated to also allow numbers.  (LocalCollection._idStringify does, so it should be fine.)  PRs welcome, but they should also include end-to-end tests in the mongo package that show that this stuff works (and eg, if you have a collection with one document with id `42` and one with id `'42'`, they can coexist fine at all levels including observeChanges).

**Comment by mitar** [comment]
I made this [test package](https://github.com/mitar/minimongo-diff), which runs Minimongo tests on the server. It exposes this issue as one of the failed tests.

**Comment by mitar** [comment]
I updated the [example](https://github.com/mitar/minimongo-diff) with latest Meteor code. There are still differences on the server side.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Minimongo%20allows%20numeric%20IDs%2C%20but%20server-side%20MongoDB%20throws%20an%20exception&body=Migrated%20from:%20meteor/meteor%233527) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
