### ISSUE TITLE
[spacebars] stray slash when no trailing space in <input/> tag

### ISSUE THREAD

**Issue by zhenyasav** [meteor/meteor#3557]
Say the data context is `{val: "foo"}`
`<input type="text" value={{val}}/>` produces a text box with the value "foo/"
`<input type="text" value={{val}} />` works correctly with value "foo"

Meteor 1.0.2.1

**Comment by dgreensp** [comment]
This is consistent with HTML5.  `<input type="text" value=foo/>` will give you a text field containing `foo/` in HTML, and `<a href=http://{{domain}}/foo/>` will also include the final `/` in the URL.

These days, the trailing slash in "void" elements like `<input>` is usually omitted, because it is ignored by browsers and only allowed for "backwards compatibility" with XHTML documents.  See https://wiki.whatwg.org/wiki/FAQ#Should_I_close_empty_elements_with_.2F.3E_or_.3E.3F

**Comment by zhenyasav** [comment]
Cool, thanks for educating :)
