### ISSUE TITLE
"meteor mongo" insert inserts a different _id type to minimongo/meteor

### ISSUE THREAD

**Issue by Miges** [meteor/meteor#3570]
When inserting an item via the mongo command line tool (meteor mongo) an item is inserted with an _id that is of the mongo ObjectId type, i.e.

> { 	
>     "_id" : ObjectId("54c764b051f7ea00b48309b9"), 	
>     "example" : "test",
> }

Since meteor/minimongo insert objects with an _id of the type String, i.e.

> { 	
>     "_id" : "54c764b051f7ea00b48309b9", 	
>     "example" : "test",
> }

this makes the "meteor mongo" tool no good for inserting if one is relying on an automatically generated _id.

**Comment by glasser** [comment]
Correct.  The Mongo shell (and server's) default for `_id` generation is ObjectId whereas Meteor's default is strings. You can configure a Meteor collection's ID generation technique via the idGeneration option.  See http://docs.meteor.com/#/full/mongo_collection

**Comment by boustanihani** [comment]
Is it possible to let the Mongo shell also generate String IDs ?

**Comment by glasser** [comment]
I don't believe so; you can insert new documents with String IDs using mongo shell, but if you leave the `_id` out Mongo will always generate an ObjectID.

**Comment by boustanihani** [comment]
Thx.

**Comment by HannesHolste** [comment]
@glasser: Why does Meteor use string `_id`'s rather than Mongo ObjectID by default? What was the reasoning and design decision behind that?

**Comment by glasser** [comment]
@HannesHolste This decision goes back to the very early days of Meteor, before it was even called Meteor and before I worked on the project (eg, the first commit in this repo). However, I can tell you what I assumed the answer was.

While Mongo defaults to using its own ObjectID for `_id` when you don't specify an `_id` on insert, you can certainly provide your own `_id` as well, which can be several types including string.

Meteor's implementation of optimistic UI (where actions are rendered locally immediately, in parallel with performing the operation on the server) requires the same `_id` to be generated for newly inserted documents on the client and on the server, so this means that Meteor has to generate the `_id` itself instead of letting MongoDB do it in the DB server.

We used to do this by generating the `_id` on the client and explicitly passing it to MongoDB as part of an `insert` method call; now we have a more generalized implementation where the client and server both pseudo-randomly generate the same `_id` using a special seeded stream.

So we had to generate our own IDs, but it could have been an ObjectID, not a string, right?  Well, as I said, we used to actually send that ID over DDP as a method parameter.  Back then, DDP didn't have any way of sending more detailed type information than JSON, so there was no way to say "this argument is an ObjectID, not a string".  And DDP methods are generic, so it wouldn't make sense to hard-code the implementations to know that a particular argument to a method is an ObjectID vs a string.  Because MongoDB understands both string and ObjectID as separate types, we couldn't really use ObjectIDs pervasively in Meteor without a way to serialize them over the network in DDP.

We solved this issue in Meteor 0.5.7 with EJSON, which among other things provided a way to serialize ObjectIDs in DDP.  But strings for `_id`s had already been the default for a while at that point and we decided to keep the default the same; I don't remember exactly why (though you can change the id-generation strategy on a collection-by-collection basis).

**Comment by abernix** [comment]
That read like a very emotional biography about Meteor.  Very well explained, @glasser.

**Comment by pihentagy** [comment]
If you are seeking for a solution / workaround how to handle those items:

```
someObject._id.valueOf()
```
