### ISSUE TITLE
Uniform API for local template state and data context

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3579]
***2 Upvotes*** Currently there are 3 different ways to access a template variable. It would be good if they could be more uniform:

```coffeescript
Template.item.created = ->
  @isDisabled = new ReactiveVar false

Template.item.events
  'click #disable': (e, template) ->
    template.isDisabled.set (not template.isDisabled.get())

Template.item.helpers
  isDisabled: ->
    Template.instance().isDisabled.get()
```

**Comment by stubailo** [comment]
What are the three different ways?

**Comment by stubailo** [comment]
Oh, I see. Actually, you can use `Template.instance()` in all three cases.

**Comment by stubailo** [comment]
I'm going to reopen this issue to track some ideas I have (and other people at MDG)

1. Template.instance() is currently the "official" way to get the template object from anywhere. We should probably deprecate using `this` or the `template` argument to get the same object.
2. In the future, we hope to have a much simpler API for getting the template instance by replacing `this` with `Template.instance()` in all callbacks, helpers, and event handlers. Currently, `this` is used to refer to the data context, which is a problem for a number of reasons, so we will add a different method for accessing the data context, for example `this.context.get("x")`.

**Comment by stubailo** [comment]
There is also an ongoing project #3561 about introducing a new pattern for managing local state.

### Before:

```
Template.item.created = ->
  @isDisabled = new ReactiveVar false

Template.item.events
  'click #disable': (e, template) ->
    template.isDisabled.set (not template.isDisabled.get())

Template.item.helpers
  isDisabled: ->
    Template.instance().isDisabled.get()
```

### After (currently in code review):

```
Template.item.created = ->
  Template.instance().state.set("disabled", false)

Template.item.events
  'click #disable': (e) ->
    Template.instance().state.set "isDisabled", not Template.instance().get("isDisabled")

# you don't even need a helper because you can use
# Template.state "isDisabled" inside your template HTML
```

**Comment by lorensr** [comment]
Ha, I was actually hoping for overloading `this` by providing `this.isDisabled` or `this.template.isDisabled` in the helper, or adding the template instance as the optional last arg. While in the former you have the risk of conflicting with the data context, I prefer things that take fewer characters: `this/@`, `template/t` over `Template.instance()`

**Comment by stubailo** [comment]
Yeah, that's why we have the future plan of replacing `Template.instance()` with `this`. Unfortunately, that isn't going to happen right now, but we are working on it.

**Comment by stubailo** [comment]
The question of adding it as a last argument is an interesting one - how would that work for helpers?

**Comment by lorensr** [comment]
Oh nice, so when you said "by replacing this with Template.instance()" above, you meant the other way around.

**Comment by stubailo** [comment]
Good point, edited my comment.

**Comment by lorensr** [comment]
```coffeescript
Template.item.helpers
  foo: (bar, template) ->
    template.isDisabled
```
html:
```
{{foo "bar"}}
```
You could also write `foo: (bar) ->` if you didn't need the template instance, same as event handlers that just need the event and not the template.

But just `this.isDisabled` would be preferable.

**Comment by stubailo** [comment]
For now, you can make it super duper short by doing `ti = Template.instance` somewhere in your app and then using `ti()` everywhere. It will still work properly.

**Comment by lorensr** [comment]
Ha, thanks.

**Comment by rclai** [comment]
Yeah, typing ```Template.instance()``` is kind of a PITA, I can't wait for those nice and short syntactic API improvements.

**Comment by jamiter** [comment]
+1

Love these ideas. Also easier to introduce Blaze to new developers, because of the consistency.

**Comment by kevohagan** [comment]
+1 awesome!! :)

**Comment by PeppeL-G** [comment]
Having `this` referring to the template instance everywhere and `this.context` referring to the context in helpers and event handlers sounds great to me, even though it sounds weird that template instances have a context property changing from time to time (a fair trade off).

**Comment by stubailo** [comment]
Yeah, the only other options I can think of are:

1. Have an extra argument to helpers and event handlers that represents the data context - not great because helpers can have an arbitrary number of arguments so it might get confusing.
2. Keep using a global function like `Template.currentData` - this is basically the same as `this.context` would be, but is a lot longer and weirdly global.

I think right now putting the data context as a property on `this` is the best we can do.

**Comment by PeppeL-G** [comment]
I agree with you @stubailo, and would like to add that I don't like the idea of passing the context as an argument because one has to type the "variable name" one extra time (as a parameter), and people will probably use different names for it (no big deal, but a drawback).

Sure, writing `this.context` 10 times will result in more typing than writing `context` 11 times, but I use CoffeScript, where `this.` is written as `@`, so no big loss (:

**Comment by bensmeets** [comment]
@stubailo Take note, that Template.instance() seems buggy, as it not always returns the correct template instance. I believe there are a couple of issues open on this already. Especially within helpers I need all kinds of dirty workarounds to get the correct instance. Top of my head, especially if you use more complex structures in the templates (wrappers using UI.contentBlock etc. top of my head).

Would also like to mention, that this syntax is great. Would want to use it today instead of tomorrow :) Something that might be related as well, is how to get a reference to the instance from the parent. I currently need all kinds of workarounds for this as well. e.g.

<template name="parent">
  {{> child}}
</template>

In this situation (as far as I know now), it's hard to read out any state of the child from the parent. E.g. if you have a nice component that does autocomplete-search, it's hard to read the selected item from the parent. Only with a lot of hacking.

my 0.02.

**Comment by stubailo** [comment]
@bensmeets we have already fixed the `Template.instance()` bug and it will be out with the latest release.

**Comment by rclai** [comment]
Perhaps ```Template.instance().child(level, [indexOfArrayIfOneExists?])```

**Comment by stubailo** [comment]
The problem I have with that interface is it's very brittle - what if you have a dynamic number of children, or you insert a new child at the top of your template. Now you would have to redo a bunch of index math. Maybe assigning names to children somehow?

**Comment by bensmeets** [comment]
I'm novice on this, so take it with a grain of salt... :) But it would make sense to me to allow a name/id like property on the child, from the parent's context. Something like this:

```
<template name="parent">
  {{> child id="child"}}
</template>
```

So the parent can just reference it like 'this.child.selectedReactiveVar.get()' or something along those lines. The workaround I use now is like this. I pass the "id" from the parent, which the child-template attaches on it's main dom element. The child then attaches the variables that need to be communicated upwards (can be the child instance itself as well) through the jQuery .data() method. In the parent I can then use:

```
this.$('.the-id-i-chose-when-including-it).data('the-var-i-need-from-child');
```

Hacky and limited.... but for these simple uses I have now it works.

**Comment by Sanjo** [comment]
> In the future, we hope to have a much simpler API for getting the template instance by replacing Template.instance() with this in all callbacks, helpers, and event handlers. Currently, this is used to refer to the data context, which is a problem for a number of reasons, so we will add a different method for accessing the data context, for example this.context.get("x"). This will also make templates feel more like objects, where this usually refers to the instance.

Please! :+1:

Right now I have to write `var self = Template.instance()` in a lot of my helpers and events. I never use the current value of `this`.

**Comment by mitar** [comment]
I think what this ticket is about is in fact the main reason why we made [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components). I think by making template instance (we make a component instance, which wraps a template instance, but it is more or less the same idea) `this` everywhere you make things really easy to work with. Then also one can easily add reactive variables (or even better, [reactive-field](https://github.com/peerlibrary/meteor-reactive-field)s) to template instance and use them around. (In Blaze Component we allow easy way to template/component instance properties from the template itself.)

So data context then becomes something you get from outside, and then you add your own additional reactive state onto the template instance (for example, in `onCreated`). This is really great then because you then often manipulate that reactive template instance state through event handlers, and Blaze then modifiers DOM accordingly.

I would really advice against adding new stuff to template instance like "state" or "attrs". This does not have to be part of the core, because everyone can add their own reactive variables or dicts or fields or whatever manually in the `onCreated`. The problem is that it is hard to access template instance around.

But, not in Blaze Components.

**Comment by stubailo** [comment]
Totally agree - `this` is the real underlying issue.

**Comment by lorensr** [comment]
Migrating to `meteor/blaze` repo:

https://github.com/meteor/blaze/issues/46
