### ISSUE TITLE
Support WkWebView

### ISSUE THREAD

**Issue by ndevr** [meteor/meteor#3603]
Please add support for WkWebView. There are some polyfills out now but they don't work because of the file:// Protocol. Would be also cool to remove the http server cause wkwebview will have also one.

Is there any plans yet?

**Comment by stubailo** [comment]
What are the benefits of WkWebView?

**Comment by ndevr** [comment]
WKWebView has the Nitro JavaScript engine.

**Comment by Slava** [comment]
We will support it once cordova supports it and if we can port our cordova plugin cleanly (wkwebview has more limitations as far as I understand)

**Comment by thedracle** [comment]
So, I'm trying to use WKWebView just using:

https://github.com/Telerik-Verified-Plugins/WKWebView

It would be nice to have a work-around to try/use WKWebView in the interim.

It almost works out of the box with the above plugin, but fails due to the CordovaUpdate plugin,
mainly because it is using NSURLProtocol to alter paths.

WKWebView works in another process, so intercepting paths using NSURLProtocol doesn't appear to work.

Any ideas/suggestions would be appreciated.

**Comment by dotnetwise** [comment]
@Slava +1, WKWebView breaks meteor because of the `http://localhost/12334` redirect

**Comment by dotnetwise** [comment]
Perhaps this is even better - as is more actively developed
https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine

**Comment by rbabayoff** [comment]
All, I already got the telerik wkwebview plugin to work in one of my projects, with a little bit of required modifications to the meteor core, in a fork of mine. But, it won't work out of the box, without adding path prefixes to iron router routes. To make it work transparently, without breaking your app, the meteor cordova plugin needs to be updated, but since I'm not an Objective C developer (looks like Chinese to me, why did apple have to choose a language that doesn't like like anything else out there??), it will take me forever to do it. I know exactly what needs to be done, so if someone with knowledge of Objective C wants to give me a hand, we can work on it together and publish it to the community. And yes, performance is 2 times faster using wkwebview.  

FYIs:

@ndevr, problem is not file://, it's the meteor cordova plugin not being able to intercept http requests anymore.

@dotnetwise, I tried this one too, but it doesn't work with the current version of cordova that meteor is using. You will need to use a cordova version that is still in development.

**Comment by Tarang** [comment]
Something nice with the WKWebView is javascript execution doesn't pause while momentum scrolling, which is a bit irritating with the current UIWebView

**Comment by rbabayoff** [comment]
Just published a package to support wkwebview in meteor. See [blog post](http://practicalmeteor.com/drastically-improving-the-performance-of-your-meteor-ios-app-with-wkweb%E2%80%8Bview/) for details:

**Comment by woniesong92** [comment]
Now that Meteor 1.2-rc7 is released, is there any way to do it simply? @martijnwalraven

**Comment by martijnwalraven** [comment]
Unfortunately, not right now. It'll probably have to wait until the release of Cordova iOS 4.0, which should support pluggable web views and make the use of WKWebView on iOS as easy as using Crosswalk on Android.

**Comment by rjakobsson** [comment]
Crosswalk has announced support for iOS and WKWebView: https://crosswalk-project.org/documentation/ios.html . Not sure if that's of any help for us, however.

**Comment by martijnwalraven** [comment]
This has been fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.
