### ISSUE TITLE
meteor tool's default release can be a non-downloaded tool

### ISSUE THREAD

**Issue by MattiSG** [meteor/meteor#3615]
```shell
$ meteor show meteor-tool
     Installing meteor-tool@1.0.40...
```

I didn't expect this behavior. `meteor show` help states that it will show detailed information, not install the package.

**Comment by glasser** [comment]
What's going on here has nothing to do with `meteor show`.  Your local package database knows about the latest version of Meteor but doesn't have the tool downloaded yet.  When you run any command outside of a package, it tries to act as the latest release of meteor, which might require downloading the tool.

To fix this, we could do the following: The default "latest release" (when you aren't using `--release` and aren't in a package) should probably be the latest one you have downloaded.  (Put thought into what `meteor create` does though.)

However, we should still make sure that the banner telling you to run "meteor update" still prints before the tool is downloaded (see also #2998) so that if you never run "meteor run" long enough to download the new tool, you still find out somehow that there's a new version of meteor.

**Comment by MattiSG** [comment]
Thanks a lot for this detailed answer, you've made it clear what happened here  :)
