### ISSUE TITLE
Remove default allow on user.profile

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3618]
Pros: 
- May help new devs learn that they can selectively choose fields to allow.

Cons:
- Even though it's clearly stated in the full docs, some devs may miss this or forget, and trust that eg user.profile.name will always be the same, or put other data that shouldn't be client-editable in there. They see a "profile" object in their user docs with a name in it, and they think, "okay, I'll store user data here". Easy to forget, because it's the only thing that remains client-editable after you remove the insecure package.

IMO, cons > pros.

**Comment by glasser** [comment]
Thanks for the feature request! (It's a feature request because it's working as intended, but you have a good argument for why our approach was not optimal.) You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I think we agree that `profile` is confusing but we're probably not going to make this backwards-incompatible change on its own, outside of a larger project to improve Meteor Accounts in a bunch of ways.  (ie, one big backwards-incompatible change instead of a trickle of many.)

**Comment by stubailo** [comment]
I think this would be great to include in the next major release, since people keep getting tripped up on it.

**Comment by mitar** [comment]
See #7743. :-)

**Comment by mitar** [comment]
In fact it is on you. You said that you have to talk to @benjamn about this. ;-) We are waiting on that.

**Comment by stubailo** [comment]
@mitar this is different - that PR is about _publishing_ data, this issue is about _writing_ to profile.

**Comment by mitar** [comment]
You are right.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Remove%20default%20allow%20on%20user.profile&body=Migrated%20from:%20meteor/meteor%233618) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
