### ISSUE TITLE
[QUESTION] Storing Meteor.user() in session

### ISSUE THREAD

**Issue by ashah888** [meteor/meteor#3624]
Out of curiosity, I'd like to know how Meteor.user() works. Am I calling a findOne() inside the MongoDB every time I use Meteor.user()?

If this is the case, would it be smart to run Meteor.user() once inside a Tracker.autorun and then storing the user data in a session? Or does Meteor.user() function already do this for me?

Would storing the user data in a session be smart or unnecessary?

**Comment by PeppeL-G** [comment]
[Here's the code for it](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_client.js#L42). As you see, it queries minimongo each time you call the function. However, it's unlikely that your app runs slow due to too many calls to `Meteor.user`, so you shouldn't worry about it.

**Comment by stubailo** [comment]
Hi, I think discussions like this are best had on Stack Overflow under the "meteor" tag, or on the [mailing list](https://groups.google.com/forum/#!forum/meteor-talk). We're trying to keep GitHub to specific actionable issues, so I'm going to close this.
