### ISSUE TITLE
slow increase of memory after deployement

### ISSUE THREAD

**Issue by darkship** [meteor/meteor#3645]
**_1 Upvote**_ Hi,

I checked for memory leaks with Kadira. I found and corrected some in my app, some remains because I still see the memory increasing in 24h.
But still with just Kadira as external package the memory increases slowly. (see repo)

![capture du 2015-02-05 11 37 18](https://cloud.githubusercontent.com/assets/3523710/6058838/7c239dfe-ad2b-11e4-9441-e944c1c7b000.png)

17h30 : 85.46MB
18h00 : 99.79 MB
21h00 : 113.26 MB
00h00 : 115.06 MB
03h00 : 115.8 MB
06h00 : 120.87
09h00 :120.92 MB

repo : https://github.com/darkship/test_memory (don't forget to add your kadira key)
server
OS : Debian GNU/Linux 6.0
CPU : Intel(R) Xeon(R) CPU E31220 @ 3.10GHz
RAM : 12GB/16GB (MemFree/MemTotal)
Mongo : 2.4.9
no sharded cluster, single node instance, nodeJS and MongoDB on the same server,

Until now I didn't run out of memory nor used 100% of CPU but it happened that my app got stuck with no error so that I couldn't log in even if the login page was displayed. I noticed that problem since I updated to Meteor 1.0.3.1 and it was only for some users (1 of 10 users mostly).

**Comment by glasser** [comment]
Thanks for the report and the reproduction.  I'm not sure when we'll look into this particular report, but it will be helpful when we next focus on these sorts of issues.

**Comment by patrickml** [comment]
+1 im seeing this issue as well https://www.dropbox.com/s/wree3m2e9bpnyrm/Screenshot%202015-07-27%2010.28.33.png?dl=0

**Comment by mjmasn** [comment]
@glasser 
+1 I think we're still seeing this issue with Meteor 1.2.0.2. Slow increase in RAM usage until we hit the limits of --max-old-space-size (~700MB in this case). When Node tries to garbage collect the CPU rises to 100% and server becomes unresponsive until it eventually crashes 30 minutes or so later with OOM error. 

Unfortunately I don't really have a clue how to track down the issue because there's so much going on that we just leave to the magic of Meteor. However I have seen similar results with an empty Meteor app (just meteor create x, then meteor build) where RAM usage always rises but never falls even with 0 connections, so I'm willing to put my money on it being a Meteor issue.

Each big fall on the graphs relates to the app crashing and restarting (we're running it with PM2). The smaller fall around 11am was a re-deploy.

<img width="729" alt="screen shot 2015-10-26 at 14 33 54" src="https://cloud.githubusercontent.com/assets/2977095/10731723/a5effe4c-7bee-11e5-85ab-ba6173daa57f.png">

<img width="731" alt="screen shot 2015-10-26 at 14 29 23" src="https://cloud.githubusercontent.com/assets/2977095/10731586/056d4d3a-7bee-11e5-87b8-a99af83ce244.png">

Workaround for the moment is just telling PM2 to restart the app if it reaches just under 700MB RAM so the server is only down for a few milliseconds rather than 30 minutes.

**Comment by hwillson** [comment]
It's been a while since there has been any activity on this issue, and many new versions of Meteor have been released since this issue was created. As part of the on-going old issue cleanup process, I'll close this issue for now. If you notice this still happens with the latest version of Meteor, please post pack and we'll re-open. Thanks for posting this issue originally!
