### ISSUE TITLE
Parameter { reactive: false } does not apply and page is still updated

### ISSUE THREAD

**Issue by tomitrescak** [meteor/meteor#3646]
Hi, I am trying to make non reactive find query, by page keeps updating:

Server:
```javascript
Meteor.publish('schedule', function(id) {
  check(id, String);
  return Schedules.find({_id: id});
});
```

Client
```javascript
var subscriptions = new SubsManager(); // the one from Arunoda

Router.route('/channel/:scheduleName/:scheduleId', {
  name: 'practicals',
  template: 'Practicals',
  waitOn: function () {
    return [
      subscriptions.subscribe('schedule', this.params.scheduleId)
    ];
  },
  data: function() {
    var schedule = Schedules.find({_id: this.params.scheduleId}, {reactive: false});
    ...
    return {
      schedule: schedule
      ...
    };
  }
});
```

**Comment by glasser** [comment]
I don't understand what the issue is. Please follow https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor and provide a full cloneable example with explicit descriptions of what you hope to see and what you actually see.

Ideally, you would avoid using `iron:router` and SubsManager in such a reproduction, which are complex pieces of software maintained by another team.

You might also get better help for this on StackOverflow.
