### ISSUE TITLE
New attribute of Meteor.user is published with delay

### ISSUE THREAD

**Issue by aj07mm** [meteor/meteor#3647]
Hi guys, i had this problem yesterday. I tried adding a WaitOn clause on the router for the userData:

```
Router.waitOn(function(){
	this.subscribe('userData');
});
```

but the problem persists

here is an example of helper that is broken because of this: 

```
UI.registerHelper("cartCounter", function () {
	if(Meteor.user()){
		var cart = Meteor.user().cart;
		return cart.length;	
	}
	return false;
});

```

the only solution i found was this: https://stackoverflow.com/questions/25674659/exception-in-template-helper-using-global-helper-in-meteor

add some checks for undefined variables.

**Comment by glasser** [comment]
I don't understand what the issue is. Please follow https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor and provide a full cloneable example with explicit descriptions of what you hope to see and what you actually see.

Ideally, you would avoid using iron:router in such a reproduction, which is a complex piece of software maintained by another team.
