### ISSUE TITLE
May be CoffeeLint?

### ISSUE THREAD

**Issue by comerc** [meteor/meteor#3652]
As part of meteor-platform or coffeescript-package.

http://www.coffeelint.org/

**Comment by jagill** [comment]
I think this is better done in user-land.  It would be a great package, however!

**Comment by stubailo** [comment]
I agree this would make a great package, it will probably not be part of core because we are focusing on the native JavaScript development experience over CoffeeScript.

Thanks for the feature request! You might be interested in reading our [feature request guidelines](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).
