### ISSUE TITLE
Internal server error if adding as package maintainer non-existent user

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3674]
``` sh
$ meteor admin maintainers pdftk:pdftk --add aadamsx  # his GitHub username
Adding a maintainer to pdftk:pdftk...
Error from package server: Internal server error [500]
# WTF?
$ meteor admin maintainers pdftk:pdftk --add aadams
# oh, okay, typo, different MD username
```

A friendlier error would be nice. `meteor admin members` works well:

``` sh
$ meteor admin members pdftk --add aadamsx
Error adding member: Specified user does not exist
```

**Comment by ekatek** [comment]
Thanks -- I'll take a look.

**Comment by hwillson** [comment]
The message you're seeing is coming directly from the package server. The Meteor Tool is just dumping the error message:

https://github.com/meteor/meteor/blob/34b02373646d67aa86c971b57aeba7b77a6f8107/tools/meteor-services/auth-client.js#L29-L31

Changes to address this will have to be made to the package server source, which has not been open sourced.

@abernix @benjamn - should this stay open here or be moved internally since it can only be addressed by MDG? If it should stay open here I'll migrate it over to the feature requests repo.

Thanks!

**Comment by abernix** [comment]
Thanks @hwillson I've migrated this to our internal repository.
