### ISSUE TITLE
Tutorial/docs should tell people to put the .meteor directory into version control

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#3707]
People are constantly posting GitHub repos without the `.meteor` directory, we should probably have some points in the docs about this.

**Comment by avital** [comment]
I think it's because people run `git add *` instead of `git add .`

**Comment by stubailo** [comment]
Whooooa what does that do? Ignore gitignores?

**Comment by glasser** [comment]
The `*` is processed by the shell, not git, and expands to all files that don't start with a dot.

**Comment by rgoomar** [comment]
Also, i've seen people just add files individually and when they run `ls` the hidden directories don't show up.

**Comment by rgoomar** [comment]
It could be useful to add it into the [next steps](https://www.meteor.com/try/12) section in the installation guide.

**Comment by hwillson** [comment]
I have a feeling this is no longer an issue (or at least very rare), since projects created via `meteor create` now include a `.gitignore` (and `.meteor` is, of course, not listed). Closing this off - if anyone feels otherwise, please open a new issue against either the [docs](https://github.com/meteor/docs) or [guide](https://github.com/meteor/guide) repo. Thanks!
