### ISSUE TITLE
You can't create a Meteor project inside another Meteor project.

### ISSUE THREAD

**Issue by udondan** [meteor/meteor#3714]
Since today I can not create any new meteor projects. No matter where I call `meteor create` it immediately quits with the following message:

```
/tmp$ meteor create foo
You can't create a Meteor project inside another Meteor project.
```

`/tmp` obviously is not a Meteor project, neither does `foo` exist, but the error is the same from wherever I call this and whatever is the projects name.

I ran an update yesterday to 1.0.3.1 and as well created a new project - before the update. So something must be broken since then. Before yesterdays update I had  0.9.3.1 installed.

**Comment by glasser** [comment]
Does either of `/tmp/.meteor/packages` or `/.meteor/packages` exist?

**Comment by udondan** [comment]
Yes `/.meteor/packages` exists, created on October 20 2014. Is that the problem? Should I delete `/.meteor` or only `/.meteor/packages`?

**Comment by glasser** [comment]
Yes that is the issue.  So your `/`, somehow, is a Meteor app!  Delete `/.meteor` and all should be well.

**Comment by udondan** [comment]
Thanks, that fixed it. Crazy, I wonder how that folder got created then. It's not even new. How would I have been possible to create a new project just the day before? I guess only the new Meteor version is checking for `.meteor` in parent directories then.

**Comment by dotku** [comment]
I think the issue might be due to this.
I just fresh installed meteor and tried `meteor create .` and it would create /.meteor folder

**Comment by FBosler** [comment]
So I know this issue is closed, but I am encountering the same problem.
When I try to create a new meteor app I get:
'You can't create a Meteor project inside another Meteor project.'

Now I looked for `/.meteor/packages`and did find it in `/Users/MyName/`, now the thing is I feel hesitant to just delete the folder because there are a lot of packages I used for a previous project (like a lot). Its been a year since I worked on that project, but I still don't want to screw anything up. As you can probably tell, I am a novice :)

Cheers and thank you
