### ISSUE TITLE
Update appcache 5MB limit

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#3738]
***3 Upvotes*** I believe the 5MB rec is outdated. See this 2014 HTML5Rocks article:

http://www.html5rocks.com/en/tutorials/offline/quota-research/

The only desktop or mobile browser with 5MB limit is Android Firefox, and that limit is not hard – can be raised by prompting for higher limit. The next-smallest limit is either:

- iOS WebView (not Safari) with 100MB, or
- Chrome (10% of remaining disk space)

**Comment by glasser** [comment]
Interesting.  I can't recall — is there actually code that matters here or just docs?

**Comment by lorensr** [comment]
Afaik docs and the warning that's printed out.

**Comment by awwx** [comment]
"10% of remaining disk space" sounds like a lot, but what if the user happens to be low on disk space?  A variable limit is even worse than a fixed limit, because now you don't know what the limit is, even for a particular browser version.

Is 100mb safe? Is 25mb?  How can we be sure?

The serious problem is that if the application cache goes over the browser's limit, whatever it is, then cache updates fail.  And the browser is stuck running old code, *even in online mode*.  It's a customer support nightmare: some random fraction of your users aren't receiving code updates.

Perhaps the autoupdate package could at least detect when reloads fail.  Right now there's not even a way for a developer to be notified if any of their users are trapped running old code.

An alternative approach, if there's resources to tackle an implementation, might be to have the appcache just contain a fixed sized file loader bootstrap program.  The code in the appcache would itself download the JavaScript code of the application, the images and other resources that the developer wants to be available offline, and store it in persistent storage (local storage or one of the other browser databases).

Now the code in the appcache is small, so it's unlikely to go over any browser's limit.  And it stays the same, so even if a browser temporarily refuses to update the appcache, it doesn't matter.  And you can implement whatever caching or update policy you want, instead of relying on the browser to get it right.

**Comment by lorensr** [comment]
I agree that:

1. It's important the full-cache state be handled better than that. A good
default would be stopping using the cache.
2. It would be great to be able to customize what is cached.

**Comment by awwx** [comment]
> It's important the full-cache state be handled better than that. A good
> default would be stopping using the cache.

I never found a way to detect the full-cache state.  If you know of one, that would be good news :)

**Comment by lorensr** [comment]
Quota Management API is a w3 draft and implemented in Chrome, which is the
only one with an unpredictable quota.

**Comment by glasser** [comment]
OK. Is there a specific suggestion/PR about what needs to change now?

**Comment by lorensr** [comment]
Yes:

1. Change 5MB limit in docs + logged warnings.
2. In Chrome and Android Firefox, if you've filled the cache, ask for more disk space, and if you don't get it, either stop using the cache or automatically pare down how many things are cached.
3. Allow customization of which files are cached.

**Comment by serkandurusoy** [comment]
+1 to @lorensr's list of 3 suggestions.

**Comment by teknologist** [comment]
+1 to @lorensr too.

**Comment by AugustNagro** [comment]
+1 @lorensr

**Comment by lorensr** [comment]
Maybe `appcache` should use a Service Worker, a new API implemented in FF and Chrome:

http://www.html5rocks.com/en/tutorials/service-worker/introduction/
http://caniuse.com/#feat=serviceworkers

**Comment by dandv** [comment]
@lorensr: #5982

**Comment by matikucharski** [comment]
I think we could also include warning in docs that AppCache will be disabled on insecure origins:

https://bugs.chromium.org/p/chromium/issues/detail?id=588931

**Comment by lorensr** [comment]
Just as FYI for anyone +1'ing this...

AppCache has been deprecated from the web standard so it seems that this should get removed from not only Cordova, but everything. I wouldn't recommend using it in any new projects.

Service Workers are supposed to be the replacement which is being tracked in #5982.

-- https://github.com/meteor/meteor/issues/3796#issuecomment-248309633

**Comment by abernix** [comment]
I think it's fair to close this.  It's unlikely to become a feature and is being removed from browsers entirely soon.
