### ISSUE TITLE
Meteor dep conflicting with Traceur

### ISSUE THREAD

**Issue by Termina1** [meteor/meteor#3752]
Here is the complete description of fixing this issue: https://github.com/mquandalle/meteor-harmony/issues/37

I'm just not sure how meteor-pathwatcher-tweaks is updated in meteor (is it fork or just published as a separate package from node-pathwatcher), so I just wanted to mention, that it the last step to fix this issue is to merge my last fixes from node-pathwatcher.

**Comment by glasser** [comment]
We've already stopped using the fork of pathwatcher on devel since our PR got accepted.  (Usually we install forked npm modules directly from git but pathwatcher requires publish-time coffeescript compilation, so this was the easiest way to install it.)

It looks like your relevant fix was in pathwatcher 4.0.2 and we're now using 4.1.0 on devel, so I think this is resolved? Let me know if I'm confused.

**Comment by Termina1** [comment]
Yes, everything is right. So, we really waiting for the bext release. Thank you.
