### ISSUE TITLE
Android platform on OSX unnecessarily demanding "emulator acceleration" installation

### ISSUE THREAD

**Issue by danopia** [meteor/meteor#3754]
When I try creating an APK for one of my apps on OSX, `meteor install-sdk android` is prompting me to install the Intel HAXM package. I get that this package is useful for emulator users, but I just want to package up APKs and put them on hardware.

The platform install requiring this package seems demanding and makes initial application bundling more than a simple, 2-command process. Can this be made optional in some way, perhaps with a `--force` flag somewhere? Doesn't really chalk up to `Platform requirements not yet met`.

**Comment by criesbeck** [comment]
Also -- and I could easily be missing something -- HAXM has been a showstopper for me when installing Android on Windows using Vagrant, because AFAICT you can't use a normal virtual box and I've not been able to get a KVM version working, that HAXM needs (I think).

**Comment by stubailo** [comment]
I think this is just a matter of updating the text - everything will actually run fine without HAXM even though `meteor install-sdk android` tells you you're not done.

**Comment by danopia** [comment]
Looks like it, I was able to proceed with building an APK and putting it on my device. Thanks for the tip!

**Comment by Type1J** [comment]
Confirmed: "meteor add-platform android" does work after "meteor install-sdk android" is run and "fails" with HAMX as the only requirement missing.

My setup is Ubuntu 64-bit running in a VMWare VM on a Windows 8.1 machine.

Since Windows is not yet supported for Cordova apps, a VM setup is the only way to proceed, and one will run into this false error every time.
