### ISSUE TITLE
Blaze messing up with inline style definition

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#3765]
Consider the following code:

``` html
<head>
  <title>hello</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>
  {{> hello}}
</body>

<template name="hello">

  <button>Click Me</button>

  <p>You've pressed the button {{counter}} times.</p>

  <h4>Case 1: as expected</h4>
  <p style="{{#if counter}}visibility:hidden{{/if}}; color:red;">Still waiting for a click!</p>

  <h4>Case 2: unexpected behavior, by omitting the final semicolon in the inline style</h4>
  <p style="{{#if counter}}visibility:hidden{{/if}}; color:red">Still waiting for a click!</p>

</template>
```

``` javascript

if (Meteor.isClient) {

    // counter starts at 0
    Session.set('counter', 0);

    Template.hello.helpers({
        counter: function () {
            return Session.get('counter');
        }
    });

    Template.hello.events({
        'click button': function () {
            // increment the counter when button is clicked
            Session.set('counter', Session.get('counter') + 1);
        }
    });
}
```

If you click the button once, the text "Still waiting for a click!" disappears as expected in case 1, but remains visible with the wrong color in case 2.

The issues is caused by Blaze doing some reordering inside inline styles.

Here is Blaze-generated html:

``` html
Case 1 (reordered, but working):
<p style="color:red; visibility:hidden;">Counter is even!</p>

Case 2 (reordered, not working):
<p style="color:red visibility:hidden;">Counter is even!</p>
```

**Comment by steph643** [comment]
The issue has been tested on WINDOWS-PREVIEW@0.1.7 and Meteor 0.8.3 for Windows (sdarnell port):

**Here is the repo** for WINDOWS-PREVIEW@0.1.7: https://github.com/steph643/meteor-issue-3765

You can also create an empty project and copy/past the above code.

**Comment by stubailo** [comment]
Hi @steph643!

We've confirmed that this is a bug. The problem is that we split the `style` attribute into tokens, and then [join them back together after diffing using `String#join(' ')`](https://github.com/meteor/meteor/blob/08bc9ab002454957834588906bafb12e92c67cfc/packages/blaze/attrs.js#L90).

Another issue is that it's hard to preserve order of style declarations because we [serialize them into an object](https://github.com/meteor/meteor/blob/08bc9ab002454957834588906bafb12e92c67cfc/packages/blaze/attrs.js#L158).

It looks like there's a good workaround for this issue by adding semicolons at the end of each style property, so it's not a top priority. However, there are several related issues around attribute handling (#3869, #3628) and we would love to accept a pull request refactoring and improving this functionality.

Here's a proposed design for a solution:
1. Revise the `parseValue` function to return a better data structure that can maintain the order of properties, as well as duplicates. (We also need to make sure every subclass is updated with the new return type)
2. Allow the `join` method of `DiffingAttributeHandler` to be subclassed, so that the subclasses can ensure that a valid attribute value is constructed. In this case, the `StyleHandler` could override that method to ensure that there are semicolons between each style.

Thanks for the report and detailed reproduction!

**Comment by rufusthecat** [comment]
As an additional piece of information, this does not work also
'<div class="sixteen; wide; mobile; sixteen; wide; tablet; sixteen; wide; computer; eleven; wide; large screen; eleven; wide; widescreen; column">'

**Comment by dgreensp** [comment]
@rufusthecat I don't think the semicolons are supposed to be there.  But that's correct, our handling of the class attribute is not currently friendly to Semantic UI -- see #3628.

**Comment by hwillson** [comment]
I've created meteor/blaze#159 to track this. This issue can be closed. Thanks!

**Comment by abernix** [comment]
LGTM. :)
