### ISSUE TITLE
Mobile: Make it easier to use ionic CLI resources command

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#3767]
The ionic CLI has a [nifty new command to generate resource images](https://github.com/driftyco/ionic-cli#icon-and-splash-screen-image-generation). It should work with Meteor mobile builds (use of ionic framework not necessary), but some of the "features" of Meteor builds get in the way.

This is how I was trying to do it:

First put this in mobile-config.js:

``` js
App.launchScreens({
  'iphone': 'resources/splash.png'
});
```

The main goal being that I want my splash.png file (the template ionic uses for splash screen generation) to end up in `.meteor/local/cordova-build/resources`.

Then `cd` to `.meteor/local/cordova-build` and enter `ionic resources --splash` command to generate all the files and add them to config.xml.

But although it generates the images, the default Meteor splash images don't seem to get replaced.

**EDIT:** One additional problem is that the build renames the file to `iphone.splash.png` whereas ionic cmd needs it to stay the same.

Ideas:
- Allow me to disable generation of the default splash/icon
- Allow me to define a post-build script to copy the template file and run the `ionic resources` command.
- Could even automatically copy resources/splash.\* and resources/icon.\* if found, provide default Meteor versions of those, and document the ionic cli as the recommended way to do it.

**Comment by Slava** [comment]
I agree that improving the story of adding assets is a good direction. Borrowing the design ideas from the Ionic team sounds good to me, too. Since I don't work on this project full-time at the moment, I will be happy to talk to anyone who is willing to get going on a PR for this.

**Comment by aldeed** [comment]
@ccorcos and @andrewreedy have done some work on packages related to resource generation. They may have some input on PR/core changes.

**Comment by andrewreedy** [comment]
@aldeed Thanks for linking me in. @Slava I've been working on https://github.com/buildhybrid/assets which works but I still have a few more levels of options to add when it comes to generating launch screens and icons for Windows apps. Basically you can generate icons for every platform with 2 source images though .. one white with transparent background for Windows and Android notifications and then your standard app icon. 

I'm developing it as an NPM module so I could easily integrate it into the CLI depending on how we want to approach the issue. @aldeed we could do some tests with the purely JS iteration of GM, like you suggested, so that users don't need an external native dep. We may want to start with a less complex version of my NPM module for integrating into the CLI .. like start with Android / iOS assets and go from there. 

Let me know what you guys think. I would be glad to help out.

**Comment by ccorcos** [comment]
nice job @andrewreedy. My solution works, but i couldn't consider it a good / elegant solution

https://github.com/ccorcos/meteor-icon-splash-maker

The one thing that gets me with all existing solutions is that they aren't vector graphics and don't have any layout constrains. For icons, we could use a giant image and compress them as necessary, but for splash screens, we have different screen sizes and different orientations. I'm not sure there is a way to reason about how to crop an initial splash screen image. And its often nice if the splash screen lines up nicely with the initial page. That was the inspiration for using html and css for my splash screen. Its slow though and kind of a hack... :/

**Comment by andrewreedy** [comment]
Yea good point. If you really want to produce a professional app / branding generating a single splash screen for every screen format doesn't really cut it... I'm including cropping in the Assets package for quick prototyping and then allowing for more advanced config in the `json` sheet. 

Cool idea for the SVG / HTML / CSS package! 

We should throw some ideas together and maybe @slava could give us some MDG input on what he thinks would be acceptable.

**Comment by ccorcos** [comment]
Thanks! It was a bigger pain than you might expect though. 

1. SVG is a huge pain to style for some reason
2. PhaontomJS doesnt support vh and vw CSS which is absolutely necessary
3. I've ended up using Firefox (SlimerJS) because it has vh and vw, but I have an arbitrary delay to wait for meteor to render, lol

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Mobile%3A%20Make%20it%20easier%20to%20use%20ionic%20CLI%20resources%20command&body=Migrated%20from:%20meteor/meteor%233767) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
