### ISSUE TITLE
new Meteor.Collection(null) and keys with dots vs a server collection

### ISSUE THREAD

**Issue by RobertLowe** [meteor/meteor#3786]
When using a `new Meteor.Collection(null)` on the client side, you can have keys with `.`'s in them.

So for instance it's possible to insert: `http://dbpedia.org/data/George_Carlin.json` into the local collection. However, on the server with a Mongo backed connection you cannot persist keys with `.`'s in them.

`Exception while invoking method '/Thing/insert' Error: key http://dbpedia.org/resource/George_Carlin must not contain '.'`

Which makes sense as Mongo reserves `.` & `$` characters. 

> Field names cannot contain dots (i.e. .) or null characters, and they must not start with a dollar sign (i.e. $). See Dollar Sign Operator Escaping for an alternate approach.

http://docs.mongodb.org/manual/reference/limits/#Restrictions-on-Field-Names

This issue requests that the behaviour between Client & Server be unambiguous.

Thoughts?

**Comment by Slava** [comment]
I think @RobertLowe has found a valid difference in behavior between Mongo and Minimongo:

```
> c = new Package.minimongo.LocalCollection
< d {name: undefined, _docs: d._IdMap, _observeQueue: e._SynchronousQueue, next_qid: 1, queries: Object…}
> c.insert({'a.b': 'c'})
< "rXiJrw4CmDQju5axq"
```

This looks rather harmless but a check in LocalCollection methods wouldn't hurt.

**Comment by hwillson** [comment]
I've submitted PR #8169 to prohibit the use of dot containing field names during Minimongo inserts. Thanks!

**Comment by abernix** [comment]
#8169 has landed.  Thanks for the fix, @hwillson, and thanks for reporting it originally, @RobertLowe!  This will be included in an upcoming 1.4.x release.

**Comment by laddi** [comment]
I updated to 1.4.2.6 the other day and started seeing this error all over since I've been using LocalCollections to store various data, such as kubernetes labels, that contain keys with dots in them.  I understand why this checks needs to be in place when using database-backed collections but I'm hugely disappointed that I will now have to refactor my code, that is not using database-backed collections, significantly because of it.  This should have been implemented with an opt-out when using LocalCollections to minimize regression errors.

**Comment by hwillson** [comment]
Hi @laddi - sorry to hear! The problem with providing an opt-out when using `LocalCollections`'s is that Minimongo is intended to mirror Mongo as much as possible, to limit surprises in other areas. Since Mongo doesn't allow keys with `.`'s, we wanted to make sure Minimongo doesn't either, since by far the most common use of Minimongo is with named collections. If we put an opt-out in place to handle this edge case, then this becomes one more edge-case that needs to be supported/handled in the codebase (and another source of potential problems for something that falls outside of what Mongo supports). Again, sorry to hear about this, but I don't think this is going to be changed (or an opt-out is going to be added) anytime soon, unless of course this is reported to be an issue for many developers (but even if it is, Minimongo and Mongo should really be on feature parity as much as possible ...). Thanks!

**Comment by laddi** [comment]
I'm really sorry to hear that, this will result in us having to refactor significantly or being stuck in 1.4.2.3 (last known version that didn't have this "fix").  Both options are equally bad.

Like I said, I understand why this was implemented, but for me this is a regression and an unnecessary one as well.  A warning would have been more than enough, imo.  Judging by the fact that this issue is being watched by five people, me included, tells me this wasn't a problem to begin with.  So now as many people have complained about the fix as the original problem... ;)

**Comment by laddi** [comment]
Furthermore, the original post isn't accurate.  If I created (prior to the fix) a `new Meteor.Collection('xxx', { connection: null })` server-side, I could successfully insert dot containing keys both client and server side.  So there wasn't a discrepancy in the behavior to begin with and therefore this fix is completely unnecessary...

Also, the "correct" behavior was already in place, i.e. an error thrown when you tried to store dot containing data into MongoDB.  So again, this fix was not needed, and I request you revert the changes asap.

**Comment by sputnick** [comment]
I have to agree with @laddi. The only downside of storing keys with dots in them in  is that you cannot search using those keys. The purpose of `Meteor.Collection('xxx', { connection: null })` is often to create a caching layer or making an api searchable that isn't searchable - you intentionally do not want to persist these collections. In many cases the backing dataset or api might have dots in the key names like @laddi mentioned is the case with Kubernetes (e.g. in standard annotation keys from google). It's not feasible to anticipate every key that might have this behaviour. There needs to be an opt-out setting for in memory collection or this can simply be a warning.

**Comment by hwillson** [comment]
Thanks @laddi @sputnick - I get what you're saying; I'm just a little worried about introducing more differences between Mongo/Minimongo, when there are already a lot of open issues right now complaining about Mongo/Minimongo differences, and how they should be brought in-line. This is really a problem of semantics - Minimongo can be used for all sorts of great things that don't really tie back into Mongo, but yet there is an expectation of feature parity (caused by the *mongo name alone). Also - if we allow one form of Mongo restricted character into `LocalCollection` field names, then what about the others? I know most people aren't attempting to start their field names with `$`'s or null characters, but who knows. Right now it's nice and succinct to be able to say "hey, if [Mongo doesn't support it](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names), we don't".

Regarding:

> Furthermore, the original post isn't accurate. If I created (prior to the fix) a new Meteor.Collection('xxx', { connection: null }) server-side, I could successfully insert dot containing keys both client and server side. So there wasn't a discrepancy in the behavior to begin with and therefore this fix is completely unnecessary...

Yes, that makes sense, but I believe the original issue was pointing more to the fact that if you can't do it in Mongo, why can you in Minimongo (again, feature parity).

All of that being said, I definitely don't want to stand in the way of anyone's workflow, or cause unnecessary headache. I believe the fix addresses the original issue, but since it sounds like there is more at stake here, I'm definitely open to re-visiting this. 

@abernix What do you think?

**Comment by sputnick** [comment]
thanks @hwillson - an opt out option i.e. "validateKeys: false" seems the easiest thing here to move forward with compliance with MongoDB so you don't break existing systems that are caching valid json responses e.g. from restful backend APIs. 

BTW according to this stack overflow you can actually get passed the restriction in MongoDB with the option {check_keys: false}

http://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name

**Comment by sputnick** [comment]
To be more specific
https://mongodb.github.io/node-mongodb-native/api-generated/collection.html

**Comment by hwillson** [comment]
Well, I can honestly say I didn't know that option existed. Okay - I think the changes made to address this issue still stand, but I'll open a new issue to track the implementation of insert `options.checkKeys` support. Thanks!

**Comment by abernix** [comment]
@sputnick, @laddi: I can respect your need to be able to use keys with dots on `LocalCollection`s and flexibility to do what you'd like, especially in your own local environment.

As @hwillson has stated above though, it is important to maintain consistent behavior on the server and client and Meteor tries to ensure that.  Even if it's (admittedly) _not_ perfect in some places, it seems reasonable to keep moving in that direction - it is "MiniMongo" after-all and the official Mongo server does explicitly forbid those characters in key names.

> The only downside of storing keys with dots in them in is that you cannot search using those keys

While it may work for you, I think this point is a fairly substantial downside that could cause confusion downstream and this may further validate the need for this check to be default behavior (as it is now).  Consider an implementation where a user may store a collection locally and (eventually) ship it to the server, causing an (eventual) error that could have been prevented earlier in the process.

That said, and again in an effort to remain consistent with Mongo, you're right, this should be possible to opt-out of on the local collection: In the same way that [the server](https://mongodb.github.io/node-mongodb-native/api-generated/collection.html#insert) allows it, `LocalCollection#insert` should accept a `checkKeys` option to bypass this check.

Would you consider making a [contribution](https://github.com/meteor/meteor/blob/devel/Contributing.md#making-changes-to-meteor-core) to Meteor in the form of a pull request that would implement this option?  It looks like @hwillson has already opened an issue to track its necessity, but your help in implementing it would be appreciated and I don't think it would be a complicated change.  We'd happily review this!

Alternatively, you should be able to pin your `minimongo` version to `1.0.19` (the previous version) until someone is able to amend this as I don't see us reverting the change:

    meteor add minimongo@1.0.19

You could then still use newer versions of Meteor, but you just wouldn't get newer versions of `minimongo`.  Let me know your thoughts and thanks for bringing this up!

**Comment by JamesLefrere** [comment]
That's a good suggestion about the version-pinning @abernix, but I was unable to get this to work, perhaps due to this change? https://github.com/meteor/meteor/blame/devel/History.md#L23

**Comment by abernix** [comment]
@JamesLefrere What if you put:

    minimongo@=1.0.19

In your `.meteor/packages` file by hand?

**Comment by JamesLefrere** [comment]
Thanks, but I'm afraid I'm still getting minimongo errors relating to the change. 

.packages and .versions show 1.0.19, but it doesn't appear to be being used.

**Comment by sputnick** [comment]
thanks for the update @abernix not sure we have the cycles right now to implement it (making a large Qstack release) but we'll take a look at the issue.

**Comment by laddi** [comment]
```
meteor add minimongo@1.0.19
```

I tried this but it defaults back to 1.0.20 on startup, so sadly that doesn't help... 😞

But like @sputnick said, we'll take a look at the issue and see if we can find a time to take a crack at it.

**Comment by JulianKingman** [comment]
I'm using astronomy and am coming across this error when trying to insert a nested field (`Exception while invoking method 'login' Error: key profile.Leagues must not contain '.'`).

Astronomy uses classes, so it looks like this:
````javascript
const user = new User({profile: {...profileFields}});
const userId = user.save();
// error!
````

**Comment by JulianKingman** [comment]
NM, it's unrelated to this issue.

**Comment by Anoop-Goudar** [comment]
@sputnick , can you please help me in using `validateKeys`. I am facing difficulty in inserting keys having a dot (ex: "abc.xyz")

**Comment by laddi** [comment]
@Anoop-Goudar the way we "solved" this was by converting the `{ 'foo.boo': 'bar' }` objects to an `Array` of `{ key: 'foo.boo', value: 'bar' }` and then just accounting for that in the code.  It's clunky but a valid "solution"...

**Comment by Anoop-Goudar** [comment]
It would be expensive for me if start converting it to the way you suggested. But if `validateKeys:false` works, then why don't we use it ?
I just need an example of using validateKeys

**Comment by laddi** [comment]
The `validateKeys: false` has not, to my knowledge, been implemented yet.  Therefore this is a workaround until such time that it is.  At least the issue is still open...

**Comment by timsun28** [comment]
I ran into this same issue recently and did some research on the current state of things: 

Since MongoDB 5.0, the support for using . and $ symbols has been added for the server side of things. 
https://www.mongodb.com/docs/manual/reference/limits/#mongodb-limit-Restrictions-on-Field-Names
https://www.mongodb.com/docs/manual/core/dot-dollar-considerations/#std-label-crud-concepts-dot-dollar-considerations
You can read more in the above two links. 

Because it is now officially supported, I don't see any reason to keep this limitation in minimongo any more. 
The only important thing to take into account is mentioned here: https://www.mongodb.com/docs/manual/core/dot-dollar-considerations/#general-restrictions
Where in case the version of mongoDB on the server is earlier than 5.0, there could be some issues. 

Because it's now supported since version 5.0, I would suggest to either revert the changes, or make it so that we can set a certain flag that allows . and $ signs in the key names, so users with up-to-date databases can choose to opt in.
