### ISSUE TITLE
Schematic for Meteor + Cordova

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#3798]
Any chance to add at https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration the hi-res image from https://www.youtube.com/watch?v=4dJLPLWMImw#t=273 ?

Would be a nice overview for how things work.

![image](https://cloud.githubusercontent.com/assets/33569/6335001/157ecae4-bb4d-11e4-87bd-0147612694a1.png)

**Comment by Slava** [comment]
Right now the wiki page doesn't explain anything on how the apps work. So, it doesn't make sense to put this image into text that has nothing to do with the process of installation and usage.

If you have a suggested text to append to the wiki page, I would gladly accept that with the image.

**Comment by hwillson** [comment]
Since the wiki isn't being used anymore, I'll close this off. If you still think this (or any other architecture diagrams) should be added alongside the Guide's Meteor + Cordova information (https://guide.meteor.com/mobile.html#introduction), please consider opening a new request for this in the https://github.com/meteor/guide repo. Thanks!
