### ISSUE TITLE
Blaze.renderWithData() and event map

### ISSUE THREAD

**Issue by skandragon** [meteor/meteor#3833]
Meteor 1.0.3.2

I have a template that I am using as an info window for Google Maps.  I want the infoWindow to update when changes occur; this part is working.  I am using code like this (pseudocode here)

```
if we have a previous Blaze.renderWithData() return value in blazeId
  call Blaze.remove(blazeId)
blazeId = Blaze.renderWithData(Template.infoWindow, {data: 'here'})
infoWindow.setContent($('infoWindow')[0])
```

The template looks like:

```
<template name="infoWindow">
  <div id="infoWindow">
      <input type="button" class='btn controls' id="iw-xxx" value="Markers" />
  </div>
</template>
```

My template setup looks like:

```
Template.infoWindow.rendered = ->
  console.log "Rendered!"

Template.infoWindow.events
  'click #iw-xxx': (event) ->
    event.preventDefault()
    console.log "Clicked!"
```

Either I have a typo in here somewhere that is eluding me, or it looks like it is not setting up events on a template that is programmatically rendered in this way.  There is an entry in Template.infoWindow.__eventMaps for the 'click #iw-xxx' event, but it does not seem to fire.

**Comment by gsuess** [comment]
Events are working fine with `Blaze.render()`: http://meteorpad.com/pad/b3HQcw5NNkcXXysFE/Leaderboard

**Comment by stubailo** [comment]
@gsuess in your reproduction, when I replace `Blaze.render` with `Blaze.renderWithData`, the events still work. I suspect the problem is related to Google Maps info windows.

Can you create a reproduction where `Blaze.render` works inside an info window, but `Blaze.renderWithData` doesn't? It also might be the case that neither works inside an info window, and if that's true then it would be good to have a reproduction of that as well.

**Comment by skandragon** [comment]
This is likely an issue with google maps and meteor combined.  I'l close this, and if this re-occurs, re-open it.
