### ISSUE TITLE
Nested Helper explanation needs example or two

### ISSUE THREAD

**Issue by Maxhodges** [meteor/meteor#3841]
No matter how many times I read this, I can't be sure what it's saying. Please provide an example or two.

>Nested Helper: If there is a positional argument followed by other (positional or keyword arguments), the first argument is called on the others using the normal helper argument calling convention.

**Comment by Maxhodges** [comment]
is this right?

Passing helperB to helperA
`{{a b}}`

Passing helperB with argument x to helperA
`{{a b x}}`

Passing helperB with argument x=false to helperA
`{{a b x=false}}`

**Comment by stubailo** [comment]
@Maxhodges, looks like you have it correct. I agree that this is confusing. Can you point me to the part of the documentation that has that sentence?

**Comment by abernix** [comment]
I'm moving this to the docs repo.  This is in the Spacebars docs here: https://docs.meteor.com/packages/spacebars.html

@Maxhodges I realize this issue is super old but I'm sure the community would appreciate a pull-request to make this more clear if you get a chance.  I think the examples you provided are helpful too.

**Comment by abernix** [comment]
Issue moved to [meteor/docs #73](https://github.com/meteor/docs/issues/73) via [**ZenHub**](https://www.zenhub.com/)
