### ISSUE TITLE
Meteor Phonegap: support for non-english app name

### ISSUE THREAD

**Issue by adam-hanna** [meteor/meteor#3845]
I built my first Chinese language app. The app's name is in Chinese characters. Unfortunately, there is an auto-generated file located at: ".meteor/local/cordova-build/platforms/android/src/com/id...../*.java"

The name of this file and the class created within are both dependent on the app name. I tried manually changing these, the app now builds but is crashing :(

**Comment by Slava** [comment]
Meteor doesn't use the name you provide to generate any source files. In fact, Meteor just passes that value to Cordova in hope that it knows how to treat different app names correctly. We already had numerous reports that an app wouldn't compile because the name has a space, this issue looks related.

I found this ticket that might be related: https://issues.apache.org/jira/browse/CB-7494

**Comment by adam-hanna** [comment]
Awesome, thanks. I should've assumed it was a cordova issue.

Yeah, looks like there were a few others. In this issue, they claim using unicode chars was fixed? https://issues.apache.org/jira/browse/CB-6992
