### ISSUE TITLE
On update removes the Android Bundle installed

### ISSUE THREAD

**Issue by mhshakouri** [meteor/meteor#3874]
By running the following command to update the installation also, 

curl https://install.meteor.com/ | sh 

it removed the folder android_bundle inside .meteor 

I'm on linux (ubuntu 14.10)

I've been using Cordova ./ Ionic and android studio, and i was using the same sdk for them all!

now I don't have any sdk's :(

since I'm in iran and slow connection and transactions , It's a hard process to get those sdk's again!

**Comment by stubailo** [comment]
Hi @mhshakouri, the preferred way of updating is by running the `meteor update` command, rather than re-running the installer. That way, all of your local state including the `android_bundle` is preserved.

How can we make it more clear that `meteor update` should be used to update rather than `curl ... | sh`?

**Comment by mhshakouri** [comment]
yeah my bac and my mistake :) 
You're absolutely right! I think I shall remove this post to prevent negative bar

**Comment by stubailo** [comment]
@mhshakouri no worries - in the future, I think it would be helpful for people to see what problems others have run across, so editing your post is not necessary.
