### ISSUE TITLE
Div contenteditable two way data binding not working

### ISSUE THREAD

**Issue by brg2** [meteor/meteor#3885]
Unable to attach two way data binding to a `<div contenteditable>` tag. Here is the [demo](http://editablebinding.meteor.com) with code: http://meteorpad.com/pad/XeQwTgAKvDfsRr8m6/

... and if those are down, here is the source:

html
```html
<body>
  <div contenteditable style="height:40px;min-width:40px">{{content}}</div>
</body>
```

js
```javascript
if (Meteor.isClient) {
  Session.setDefault('content', 'Try to edit me')

  Template.body.helpers({
    content: function () {
      return Session.get('content')
    }
  })

  Template.body.events({
    'keydown div': function (e) {
      setTimeout(function(){ Session.set('content', $(e.target).text()) })
    }
  })
}
```

**Comment by jagi** [comment]
Here is the solution for problems with contenteditable: https://github.com/meteor/meteor/issues/1964#issuecomment-57948734

**Comment by stubailo** [comment]
@brg2, @jagi posted a link to a great discussion on this topic. The current state of the issue is the following: https://github.com/meteor/meteor/issues/3635

Basically, it is impossible to reliably do two way binding on `contenteditable` elements, and other don't do this either - in fact, React explicitly disallows this.

Thanks for the reproduction.
