### ISSUE TITLE
Provide a way to rewrite Package Templates

### ISSUE THREAD

**Issue by dropfen** [meteor/meteor#3895]
Hi, I am having some drupal background.
And in Drupal you have a lot of predefined Markup, which you can rewrite in your own Templates.
for example if you use an module like comments, there is not only the logic & DB part, but also the template. The template itself, is rewritable, so that you don't need to care about the logic, but customize
the UI part.

Meteor is growing really fast, and there are a lot of cool packages out there. Lot's of them provides you the templates with their own logic.

I guess it's clear what I want to say. We need some proper way to just rewrite the given templates. This should be somewhere in the build step. For example we could define our rewriteTemplates like:

template name="rewrite:ForExampleTheAccountsUILoginTemplate"

check for the string rewrite and replace the given templates. That's it nothing more.

This will only work, if we provide some special stuff, like buttons with special classes, for the events.
the one who will implement rewritten template will have to look for the original templates of course.
But it's doable.

thumbs up ;)

**Comment by rclai** [comment]
Use [this](https://atmospherejs.com/aldeed/template-extension)

**Comment by dropfen** [comment]
Thanks to pointing me to the template-extension package, it's has a 
replaces method.

But, I actually don't really like this approach, because it's handled on 
runtime, in the browser.
so it means I'm serving code which is not used.

The best would be, that it's handled after the CompileStep in the 
building process.

Am 10.03.15 um 12:50 schrieb Richard Lai:

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

As a side note, it is currently impossible to make this happen during the building process, because packages are built when published, not when loaded. This would require some big changes in the Meteor build system. Some of these changes are already planned, but it might be a while until then. I think the template-extension package is currently the best way to do it.

**Comment by dropfen** [comment]
Ok, got it, thank you Sashko. Will also check out the feature request page.

**Comment by hwillson** [comment]
As things currently stand, the chances of the current package build process changing to accommodate this feature request are quite low. Given that there is a viable workaround for this request (using the [`replaces`](https://github.com/aldeed/meteor-template-extension/#replacestemplatename) function of the [aldeed:template-extension](https://atmospherejs.com/aldeed/template-extension) package), the lack of support for this feature request, and the age of this issue, I recommend closing this feature request.

**Comment by abernix** [comment]
Agree.  This certainly falls into the category of "(can be) implemented as Atmosphere or npm packages rather than changes to core" per the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) and hasn't been popular enough to consider otherwise.

However, great suggestion, @dropfen!
