### ISSUE TITLE
Meteor Shell: HTTP is not defined

### ISSUE THREAD

**Issue by chicagogrooves** [meteor/meteor#3899]
I know it used to be though! Defined vars starting with 'H': `HTML        Handlebars`

Here are my versions:
```
application-configuration@1.0.4
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
ddp@1.0.14
deanius:promise@1.0.3
deps@1.0.6
ejson@1.0.5
emgee:mssql@1.3.0_1
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
lbee:moment-helpers@0.0.2
livedata@1.0.12
logging@1.0.6
meteor@1.1.4
meteor-platform@1.2.1
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
momentjs:moment@2.9.0
mongo@1.0.11
observe-sequence@1.0.4
ordered-dict@1.0.2
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
session@1.0.5
slava:miniredis@1.0.0
slava:redis-livedata@1.0.2
spacebars@1.0.5
spacebars-compiler@1.0.4
templating@1.0.11
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
webapp@1.1.6
webapp-hashing@1.0.2

```

**Comment by chicagogrooves** [comment]
Related to #3343  ?

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

Are you sure that `HTTP` is actually defined in your app (eg in the browser console)?  That will only be the case if you have directly added `http` to your app, not if it just happens to be used transitively by another package.  There is no way for me to tell if you did in your app because you did not follow our bug reporting guidelines.

**Comment by chicagogrooves** [comment]
I didn't realize I had to add http to the app. Thanks for pointing out about the transitive dependencies.
