### ISSUE TITLE
When trying to update a project, it first downloads the old version of meteor

### ISSUE THREAD

**Issue by jamgold** [meteor/meteor#3902]
There is no built-in way to delete old version of the meteor tool or packages, so I recently blew away and re-installed meteor to get rid of some cruft on my SSD. Unfortunately, the update option first downloads the original version meteor

```
 cat .meteor/release 
0.8.2
 meteor update
Installing Meteor 0.8.2:                      
 * 'meteor' build tool (version 858c88b520)
yaddiyadd
```
it would be nice to avoid that and/or have an option to clean out $HOME/.meteor. Alternatively a plugin infrastructure for the ```meteor``` command would be cool, then we could write little add ons

**Comment by glasser** [comment]
Whenever you run `meteor`, it follows this series of rules:

- Start by executing the latest release of `meteor` (this is what the `~/.meteor/meteor` symlink points to).
- If `--release` is specified, switch to running that release instead.
- Otherwise, if you're running inside an app which is pinned to a specific release, switch to running *that* release instead.
- Continue on to execute the specific command's implementation.  Some of these commands, such as `update`, will choose to switch to the latest release of the current track, but even this logic could change from release to release.

I think you're suggesting making this even more complicated by doing something more like:

- Start by executing the latest release of `meteor` (this is what the `~/.meteor/meteor` symlink points to).
- If `--release` is specified, switch to running that release instead.
- Otherwise, if you're running a specific set of commands like `update`, and you're in an app, look to see what track the app is pinned to, and switch to the latest release on that track.
- Otherwise, if you're in an app, switch to the release that the app is pinned to.
- Now run the command.

The rules around which release to run are already pretty complicated, so I don't think that this extra complexity is warranted.  As a workaround for this particular case, you can just run `meteor update --release 1.0.3.2` or whatever directly, which will hit the "you specified a release" case and not run the old version.

**Comment by jamgold** [comment]
> As a workaround for this particular case, you can just run meteor update --release 1.0.3.2 or whatever directly, which will hit the "you specified a release" case and not run the old version.

that makes total sense, didn't know that. Either way, I started writing a little nodejs cli tool to purge $HOME/.meteor

Thanks for responding
