### ISSUE TITLE
package `google` file `google_client.js` has an unmet dependency on `accounts-base`

### ISSUE THREAD

**Issue by nathan-muir** [meteor/meteor#3903]
`if (typeof Accounts._options.restrictCreationByEmailDomain === 'string')`

Assumes that `Accounts` is available in the global scope - rather than depending on the `accounts-base` package.

**Comment by glasser** [comment]
You're right that this code is incorrect, but actually, the problem is that it's using `Accounts` at all.  This is the `google` package, not the `accounts-google` package, so it should not depend on `accounts-*` at all.  I think that this should be changed to be an option to `Google.requestCredential` and `loginWithGoogle` should do the job of translating from `Accounts._options` to `Google.requestCredential`.

(Also, hmm, I thought that `google` shouldn't even transitively depend on `accounts-base` but it does via `service-configuration`, which is a bit of a shame.  Not clear why the DDP stuff around publishing and writing to ServiceConfiguration are in `accounts-base` rather than in `service-configuration` or a third package used by them both.)
