### ISSUE TITLE
Tutorial Step 8: Unclear that events need to be separated by commas

### ISSUE THREAD

**Issue by mckinleymedia** [meteor/meteor#3922]
Love the system and the tutorial.  I'm a convert.  Thought you'd want to know though... It's not clear that you need to add a comma to the previous event when adding the code to "Template.body.events"

**Comment by stubailo** [comment]
Good point! I should add something to make that more clear.

**Comment by abernix** [comment]
A cursory look at the tutorial didn't yield this problem to me, but I could be missing something.  The tutorial has also probably changed dramatically since this issue was opened.  If this is still relevant, please consider opining an issue or pull request at the `tutorials` repo: https://github.com/meteor/tutorials/ 

😄
