### ISSUE TITLE
meteor run ios-device keeps running a previous version of my app

### ISSUE THREAD

**Issue by yanndebelgique** [meteor/meteor#3925]
So i submitted my app to the app store and now I want to iterate on my app but when I run meteor run ios-device I get the version running of my last build. What should I do? What should I delete to make this work correctly?

**Comment by mikesurowiec** [comment]
Check that you're not running with the ```--mobile-server``` option pointed at your production url. If your local build connects up to your deployed server, it will download the client from that server.

**Comment by Slava** [comment]
as @mikesurowiec said, you probably should point your mobile app to the correct location of your server, otherwise it will not be able to discover the new versions. Also make sure that you can connect to your server from your network (for example, on some wifi networks, the network isolation is enabled and it prevents the clients from connecting to each other).

**Comment by yanndebelgique** [comment]
thanks for the reply. I don't think it was due to that issue. Someone encountered the same error on the meteor forum and gave me a pointer to solve it :+1: 

Hello Yann,

Thanks for your help.
After 4 days of searching (lost & depressed days !!! smile ), I figured out that there was a config.xml cordova file in my $HOME....
That was the problem !!!

cheers
jeangui

**Comment by Slava** [comment]
Your problem was, that a random config.xml file in your home directory was breaking the run of app? This sounds... surprising and terrible.
