### ISSUE TITLE
Meteor releases like 1.0.4.1 are not valid semver versions

### ISSUE THREAD

**Issue by Sanjo** [meteor/meteor#3958]
I have some code in my package that must behave different depending on the Meteor version. I use Meteor.release for this. I remove the `METEOR@` part.

I want to do a `semver.lt` comparison (Meteor release version is less then a specific version). But both the NPM package "semver" and the Meteor package "package-version-parser" fail in parsing versions that have four version parts.

I will fix this in my case by removing and ignoring the last part of the version. But why do you not use valid semver version for Meteor core? I don't see a problem in bumping the patch part more often. And bump the minor version when new features are added. Isn't that the convention for semver versioning?

**Comment by stubailo** [comment]
Meteor release numbers are primarily for marketing, and are not intended to be semver, although they also often consist of dots and numbers. Only package versions are semver.

What is the case in your package where you need to parse the Meteor release version? Maybe there is a better way to do what you are trying to do.

Going to close this issue for now because it's "working as expected".

**Comment by Sanjo** [comment]
Ok.

My use case is running a NPM CLI tool from a Meteor package.
I have a working solution now, so it's ok.

If your are interested:

* https://github.com/Sanjo/meteor-karma/blob/master/main.js#L107-L118
* https://github.com/Sanjo/meteor-meteor-version/blob/master/main.js
