### ISSUE TITLE
X-Frame-Options SAMEORIGIN breaks sockjs

### ISSUE THREAD

**Issue by occasl** [meteor/meteor#3963]
Recently, our admins applied this setting to our Apache proxies which resulting in sockJS failures from the server. Can't this setting co-exist with sockJS?

They applied:
```
Header set X-Frame-Options SAMEORIGIN
```
Results in this error:
```
[Error] WebSocket network error: The operation couldn't be completed. Connection reset by peer (ma-meteor.mydomain.com, line 0)
[Error] Refused to display 'https://ma-meteor.mydomain.com/sockjs/iframe.html#h4jei51e' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'. (about:blank, line 0)
```

**Comment by glasser** [comment]
I think you need to provide some more context for this to make sense to me.  Where is this error being printed --- your apache logs?  A browser's logs?  Which browsers? What is actually triggering that?

Generally, settings X-Frame-Options to SAMEORIGIN is fine for Meteor; in fact, if you use the [`browser-policy`](https://atmospherejs.com/meteor/browser-policy) package then it will do that by default. However, it does not apply those options to SockJS requests.  (So you may want to just use `browser-policy` instead of Apache configurations.)

One of the fallbacks used by SockJS when websockets aren't available involves using an iframe, and so presumably if you set SAMEORIGIN on the iframe request, then the iframe's origin needs to match the main page's origin.  Looks like the iframe's origin is https://ma-meteor.mydomain.com/ .  Is the main page's origin something different?  Maybe your app's origin is on `http`?

I don't think this is a Meteor bug, though; if you choose to take an alternate method of configuring browser security options other than the one we built, and it breaks your app, then I don't think that's a Meteor bug.
