### ISSUE TITLE
Unable to use a npm module that depends on the fibers module

### ISSUE THREAD

**Issue by Dev1an** [meteor/meteor#3967]
When I try to require an NPM module that depends on the [fibers][1] module using `Npm.require('...')`, I get the following error:

	W20150319-10:27:40.453(1)? (STDERR) 
	W20150319-10:27:40.454(1)? (STDERR) /Users/Damiaan/.meteor/packages/meteor-tool/.1.0.43.1hhjw1a++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
	W20150319-10:27:40.454(1)? (STDERR) 						throw(ex);
	W20150319-10:27:40.455(1)? (STDERR) 						      ^
	W20150319-10:27:40.666(1)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
	W20150319-10:27:40.666(1)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
	W20150319-10:27:40.666(1)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
	W20150319-10:27:40.667(1)? (STDERR)     at Object.DDP.randomStream (packages/ddp/random_stream.js:69:1)
	W20150319-10:27:40.667(1)? (STDERR)     at [object Object].self._makeNewID (packages/mongo/collection.js:72:1)
	W20150319-10:27:40.668(1)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/mongo/collection.js:488:1)
	W20150319-10:27:40.668(1)? (STDERR)     at updateVersions (packages/autoupdate/autoupdate_server.js:97:1)
	W20150319-10:27:40.669(1)? (STDERR)     at packages/autoupdate/autoupdate_server.js:161:1
	W20150319-10:27:40.669(1)? (STDERR)     at /Users/Damiaan/Downloads/fiberBug/.meteor/local/build/programs/server/boot.js:229:5
	=> Exited with code: 8

A reproduction of this problem can be found here: https://github.com/Dev1an/meteor-fibers-bug.git

  [1]: https://www.npmjs.com/package/fibers

**Comment by glasser** [comment]
`control-flow` uses the relatively ancient 0.6.9 version of Fibers, which had the terrible behavior of overwriting the global `Fiber` symbol.  This means that if you load multiple versions of `fibers` (as you do here), the second one to load (the old one) will redefine the global variable `Fiber`, which causes lots of problems.

The global variable issue was fixed in 1.0.0 (https://github.com/laverdet/node-fibers/commit/f412b0994366878ce0dc6ee8418a8b8b322de65e); and 1.0.4 improves it even more by ensuring that multiple versions of the library will never load (as long as they all are at least at 1.0.4; https://github.com/laverdet/node-fibers/commit/d9bc3a7b9d486d6f45170501de8626d52dfa5dfa).

You should get your module to upgrade. Looks like `synchronize` is the new name for `control-flow` and it uses `fibers` 1.x.
