### ISSUE TITLE
Missing documentation for options to api.addFiles -- isAsset and bare

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#3984]
There's no documentation for being able to specify options as a third argument to  `api.addFiles`. Takes a bit of digging through [the source](https://github.com/meteor/meteor/blob/13de1a81abf8a563eccac8feebde4d5a9e75b63d/tools/compiler.js#L359) to find out how this works. Many packages use this, it'd be great to get documented correctly. Thanks!

**Comment by ekatek** [comment]
Thanks! I'll look into it.

**Comment by abernix** [comment]
Thanks for reporting this initially! Sorry it's been open for so long.  The [asset pipeline](https://docs.meteor.com/api/assets.html) has changed entirely since this was opened, and [the newly revamped Meteor Docs](http://docs.meteor.com) document the [package.js file much more thoroughly](https://docs.meteor.com/api/packagejs.html).  Closing as resolved.
