### ISSUE TITLE
Source handler doesn't run for a file extension if it is a file name

### ISSUE THREAD

**Issue by stevezhu** [meteor/meteor#3985]
When using a file name as a file extension when registering a source handler as cited in the [Plugin.registerSourceHandler docs](http://docs.meteor.com/#/full/Plugin-registerSourceHandler)
```javascript
Plugin.registerSourceHandler('some_json.json', function(compileStep) {
  console.log('In some_json.json source handler');
});
```
"In some_json.json source handler" isn't logged unless you also add a source handler with just json
```javascript
Plugin.registerSourceHandler('json', function(compileStep) {
  console.log('In json source handler');
});
```
Note: this works fine for `api.addFiles` in packages

reproduction: https://github.com/stevezhu/meteor-source-handler-bug  
using osx mavericks 10.9.5 if it's relevant

**Comment by glasser** [comment]
So, you're right that there's a bug here, but the bug is that the exact filename match ever works at all.  The feature is documented as:

> The file extension that this plugin should handle, without the first dot. Examples: "coffee", "coffee.md".

It's pretty explicit that this is supposed to be an extension, and most of the code (eg, the code that looks for relevant files inside an app) correctly handles this.  The fact that, in certain odd cases, the full filename can match, is a bug that I'll fix. Thanks!

**Comment by avital** [comment]
I think some packages may have depended on this behavior. (Unfortunately I don't recall specific examples)

**Comment by glasser** [comment]
@avital Would love to know.  I checked https://atmospherejs.com/mizzao/build-fetcher and it uses extension.

And note that the behavior worked inconsistently here: it would work in a package, or in an app if there was a suffix of the extension also declared (as @stevezhu showed).  Because the code that looks in your app for files to process does assume that extensions are extensions:

```js
        var sourceInclude = _.map(
          extensions,
          function (isTemplate, ext) {
            return new RegExp('\\.' + utils.quotemeta(ext) + '$');
          }
        );
```

**Comment by stevezhu** [comment]
Ahh I see, thanks for that clarification and glad I unintentionally uncovered another bug.

**Comment by stevezhu** [comment]
Just a note; from reading the commit, it also seems to fix the bug where something like `.some_json.json` wouldn't be processed with `Plugin.registerSourceHandler('some_json.json')`

**Comment by johanholmerin** [comment]
[mquandalle:bower](https://github.com/mquandalle/meteor-bower) and [numtel:publicsources](https://github.com/numtel/meteor-publicsources) both relie on this.

**Comment by glasser** [comment]
@mquandalle @numtel You may way to try to address this before the next Meteor release.

(I'm thinking of adding `filename:` support to a build plugin refactoring though.)

**Comment by johanholmerin** [comment]
@Differential's [Vulcanize](https://github.com/Differential/meteor-vulcanize/) also uses this pattern.

**Comment by numtel** [comment]
@glasser Already taken care of. My packages are no longer dependent on this bug.

**Comment by avital** [comment]
https://github.com/elidoran/cosmos-browserify also depends on this (cc @elidoran)

**Comment by avital** [comment]
https://github.com/elidoran/cosmos-browserify also depends on this, or at least the example in the README (cc @elidoran)

**Comment by elidoran** [comment]
Good to know, thank you @avital 
I'll revise cosmos:browserify accordingly.

**Comment by glasser** [comment]
Note that a forthcoming version of Meteor (implemented on the `batch-plugins` branch) allows plugins using the new registerCompiler API to register for specific filenames in addition to extensions.
