### ISSUE TITLE
Connection dropped due to an invalid login attempt

### ISSUE THREAD

**Issue by xbaun** [meteor/meteor#4034]
If a non-existing userid is returned from a login handler, meteor closes unexpectedly the connection and the client is forced to reconnect.

Is also the autopublish packaged installed, the client runs into an infinite login loop. The client tries to reconnect because it hasn't received any result from the server and sends the same login call again...

```javascript
Accounts.registerLoginHandler(function (options) {
	return { userId: "123" }
});
```

Server closed the connection without any error code:

    c[1000,"Normal closure"]

I assume that this should not happen at all.

**Comment by glasser** [comment]
This is by design.  `accounts-base` ensures that all connected user connections correspond to a resume token in a user document in `Meteor.users`.  This means that deleting a user from the DB or clearing its resume tokens (as we do when you reset your password) causes other connections to be disconnected.

If you want to build an accounts system that is not based on `Meteor.users`, you can integrate with the low level `ddp` setUserId methods yourself, but this is a security feature of the design of `accounts-base`.
