### ISSUE TITLE
specify mongo version in development mode for meteor 1.1

### ISSUE THREAD

**Issue by partus** [meteor/meteor#4092]
Seems like it's not documented, I have to force meteor to use mongo 2.6 instead 3.0 , how can I do it?

**Comment by glasser** [comment]
I'm sorry, I don't understand what you're asking.

A given version of the meteor tool ships with a single version of mongod.  For example, Meteor 1.1 ships with mongod 2.6.7.  `meteor run` uses that version.  You're also welcome to install your own version of mongod, run it, and set `MONGO_URL` to tell `meteor run` to talk to your mongod instead of running its own.
