### ISSUE TITLE
TWBS/Bootstrap Crashing 

### ISSUE THREAD

**Issue by jmar42** [meteor/meteor#4098]
I'm trying out Windows Meteor and it crashes when trying to download the TWBS/Bootstrap.  Attached is a screen shot trying to download the Bootstrap.
![winmeteor error](https://cloud.githubusercontent.com/assets/6071085/6953025/7b217aae-d87b-11e4-9cc0-d85b2e1fcac5.png)
![winmeteor error1](https://cloud.githubusercontent.com/assets/6071085/6953108/f090e450-d87b-11e4-9171-92f33ed22c7d.png)
![winmeteor error2](https://cloud.githubusercontent.com/assets/6071085/6953157/3c8f6c14-d87c-11e4-8783-b1ca107a7a9b.png)

**Comment by glasser** [comment]
`*.html` files in Meteor are template files, not HTML files; top-level things in them should be in `<template>`.  You may want to use [the twbs:bootstrap package](https://atmospherejs.com/twbs/bootstrap)

There's definitely a bug that this is showing a stack trace instead of just the first line, though.  What version of Meteor are you running?  I'm confused that it has names like `init_from_app_dir` in that stack trace, because the function in modern Meteor is called `initFromAppDir`...

**Comment by jmar42** [comment]
I downloaded Bootstrap directly from the package right now, still same error.

I downloaded Meteor Win last night.  How do I download the boostrap?  I tried the command 
    meteor add twbs:bootstrap

It wouldn't download.

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by jmar42** [comment]
Oh, ok thx.
