### ISSUE TITLE
Document Reactive Dict - including clear() and all()

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4100]
@tmeasday The PR I merged from you didn't include docs, but we should have them. The only issue is that those functions don't really make sense for `Session`.

**Comment by tmeasday** [comment]
Hey @stubailo - I'm not really sure about the process of doing docs but I'm happy to learn! 

PS I'm not sure they aren't useful for the `Session`. There's was an *old* feature request for `Session.all()` I can remember from way back when.

**Comment by stubailo** [comment]
What would that be used for? I imagine it would be easy for other parts of your app or even packages to pollute your Session namespace. I think it would encourage bad things

**Comment by tmeasday** [comment]
I think it was more for debugging. People wanted to have some insight into what was currently in the session.

**Comment by Maxhodges** [comment]
what is "all()"? getKeys()?

**Comment by stubailo** [comment]
It returns a static object that matches the contents of the ReactiveDict, is that what you mean by getKeys?

**Comment by Maxhodges** [comment]
I disagree with calling it 'all'.

I feel the ReactiveDict is already a bit oddly designed and has very questionable semantics. Ordinarily (in language like VB.NET, C#, Java, Python) a keys method returns an enumeration of the keys in the hashtable, but ReactiveDict returns a single object--which I assume is some kind of internal structure--with keys AND (stringified??) values. ReactiveDict confuses keys with items/elements.

Also a Dictionary is generally a type-safe hashtable so maybe ReactiveHashtable is a better name? ;)

Ordinarily you wouldn't simply `set` and `get` values in a dict, you would `add` (or put) and `remove` them. Once added you get or set them via a property accessor `items` (or elements) which takes 'key' as a param. Presently in ReactiveDict set is overloaded to both set an existing key's value or *add* a new key-value pair (think about it).

If you add keys to the Dictionary and one is already present, you should get an exception. You can catch possible exceptions with Try and Catch, but since this often causes a performance loss we can mitigate this by checking with `containsKey` that the key is not present.

And of course `clear` to remove all key-value pairs from a Dictionary.

In my case I'm using ReactiveDict to store template state throughout my application, but the design leaves much to be desired.

In one template I use ReactiveDict to track which items in a list someone has selected. 

Let's say my user selects 3 packages from their mailbox for consolidation, a click event will toggle their selection by adding these three items to the dict. I set them to true to designate they are selected.

Here is the contents of my reactiveDict:
```
t.selectedParcelIds.keys
>Object {PP9dCpuC: "true", PPxp2wkq: "true", PPgHct57: "true"}
```

first, notice that it's my true and false booleans are stringified and rather than returning an array of keys (as expected), it's returning a single object which includes the values too. One would think keys should return a collection/array of keys.

Now if the user removes one item from their selection, I can't simply remove it (no such method), so I set it to 'false'

`>Object {PP9dCpuC: "true", PPxp2wkq: "false", PPgHct57: "true"}`

Now, I simply want to get a list of selected parcels from this dict. But how? If I could have simply removed the deselected items then I could just get the keys and be done. Instead, since "set" irreversibly *adds*, we'll need to check the true/false values:

```
var selectedParcels = _.map(t.selectedParcelIds.keys, function(value, key) {
  if (value === "true") { // ugly but necessary, the booleans are now strooleans! 
    return {key};
  }
});
selectedParcels = _.compact(selectedParcels); // removes undefined values
```

That's one way, but it doesn't feel right to be doing this stroolean check does it?

Here is another method:

```
var keys = Object.keys(t.selectedParcelIds.keys); // this is what .keys should be returning natively
// Now I have the keys without the values. So I can get the values imperatively:
var trueKeys = [];
keys.forEach(function(key){
if (t.selectedParcelIds.get(key)){
trueKeys.push(key);
}
});
```

Is there a more functional or OO method?

I appreciate that the team who built it was trying to solve problems quickly and wanted to keep things simple. On the whole ReactiveDict is unnatural and unproductive to work with. Maybe I just have high-expectations from working with dictionaries and hashtables in other languages.

Suggested changes
- `set` is semantically odd. It doesn't just set a key's value, it's also used to *add* a new key-value pair to the dict. (irreversibly I might add, since you can't remove them). Depreciate set and add `add` and `remove`methods 
- `get`  is OK, but now it  seems unbalanced without set. An `item` property accessor to get or set a key would be move flexible.
- add a `remove` method
- add a `clear` method to remove all items. 

We may have a workaround for clear with:

```
var rd = new ReactiveDict;
rd.add('game', 'breakout'); 
rd = new ReactiveDict; // poor man's clear? not 100% sure if this would work. Would reactiveDict items need to be de-referenced from tracker (deps) first?
```

Basically the core properties and methods you get with [hashtable](https://msdn.microsoft.com/en-us/library/System.Collections.Hashtable(v=vs.110).aspx) in .NET provides a very well-designed paradigm:

Altogether:
```
var rd = new ReactiveDict;
rd.add('make', 44);
rd.add('model', 55);
var currentMake = rd.item('make'); // gets the value (returns 44)
rd.item('modal') = 56; // set new value for key
rd.item('color') = 77; // adds a new key-value pair (since color wasn't previously added)
var keys = rd.keys; // returns a collection of keys 
rd.remove('model'); // removes key-value pair by key
rd.clear(); // remove all keys
```

Of course it should work as expected with underscore functions like map, pick and filter. I'd just create a pull-request, but I'm not a hardcode JS expert yet.

Hope these ideas get accepted!

**Comment by aadamsx** [comment]
I use ReactiveDict in the same way as @Maxhodges -- for reactivity within my template subscriptions.  And I too come from a c#, java, c++ background.

I completely agree with what @Maxhodges has to say.  ReactvieDict in its current state is just not a complete implementation compared to other languages.

Please take his feedback into consideration.

**Comment by stubailo** [comment]
@Maxhodges thanks for the extremely detailed comment. I think some of these should be independent feature requests, so that they can be discussed separately. The title of this issue is 'document ReactiveDict', rather than a discussion about improvements to the same.

### Semantics and method naming

I think it's important to match the semantics of JavaScript rather than VB, Java, or Python. In JavaScript, you interact with dictionaries, which are called 'objects', via the `=` operator and the `delete` keyword, like so:

```js
var x = {};
x["a"] = 5; // no special call needed to add, same as changing existing value
delete x["a"];
x.hasOwnProperty("a") // like the "contains" that you were mentioning
// no 'clear' method, but you need it for reactivity to work properly
```

Unfortunately, ReactiveDict isn't as consistent with this as it could be. But we should probably improve that.

### ReactiveDict#keys

It's unfortunate that this is not a "private" property, because it exposes an internal implementation detail of ReactiveDict - namely, that the values are serialized. You should really be calling `ReactiveDict#all` instead, so that things are deserialized for you.

### Your complaints

I think most of your complaints stem directly from a lack of documentation, which makes this issue very relevant.

> Now if the user removes one item from their selection, I can't simply remove it (no such method), so I set it to 'false'

Currently the "correct" way is to use `set(key, undefined)` - in fact some of the internal machinery is optimized for that case. But we should have a `delete` method, and I've added a feature request here: https://github.com/meteor/meteor/issues/4438

> Now, I simply want to get a list of selected parcels from this dict. But how?

That's why we added `all` - it makes it so that you get the actual deserialized values. Accessing the `keys` property is not the right way.

> add a clear method to remove all items.

That already exists. In fact, documenting it is in the title of this issue, which you should probably read before posting this suggestion.

> keys returns an enumeration of keys in the dict/hashtable

Does `all` do this for you? Is your disagreement with the name, or do you really need an array of strings to be the return value?

> Of course it should work as expected with underscore functions like map, pick and filter.

This would also work through `all`, as in you can just do `_.each(dict.all(), func)` and it should work perfectly.

### Conclusion

I agree that ReactiveDict could be improved, and we definitely should add some things. We should discuss those as individual feature requests. But most importantly, it's not adequately documented. That's why this issue is here.

**Comment by Maxhodges** [comment]
Hi @stubailo thanks for the clarifications, and sorry for misposted in the wrong place. I'll try to figure how the correct way to make feature requests! But would like your feedback on a few more points.

I didn't realize `all` was implemented yet. Maybe I need to update my Meteor version! `all ` sounds like it might make things easier, but yeah, the naming is a big part of my gripe.

>in JavaScript, you interact with dictionaries, which are called 'objects', via the = operator and the delete keyword, 

I wanted to disagree with this and insist that Dictionaries are not simply Objects but hashtables with special properties and methods. But I dug in a bit more and it seems you are right!

JavaScript Objects Are Dictionaries
In C++ or C#, when we’re talking about objects, we’re referring to instances of classes or structs. Objects have different properties and methods, depending on which templates (that is, classes) they are instantiated from.

That’s not the case with JavaScript objects. In JavaScript, objects are just collections of name/value pairs—think of a JavaScript object as a dictionary with string key i.e. 

```
var myDict= {}; // equivalent to new Object() in C#

myDict["lastLoginTime"] = new Date(); // add a key-value pair

alert(myDict["lastLoginTime"]); // get a value by key
```

But this point seems inconsistent

> I think it's important to match the semantics of JavaScript rather than VB, Java, or Python.

If that's true, then it seems `set` isn't anymore closer to the semantics of JavaScript than add right? Is it that we need these functions to wrap these special behaviors around the default JavaScript Object/Dictionary (namely tracker registration)? In that case, I'd still argue that `add` is semantically more accurate (set doesn't just set, it adds it to the dict if it doesn't already exist.) Likewise `keys`, one would think, should return an enumeration of keys.

Maybe the trouble is I think is OOP concepts too much and JavaScript is OOP challenged. But I can't help but think ReactiveDict needs more design work, not just better documentation.

Cheers!

**Comment by dandv** [comment]
> JavaScript is OOP challenged

@Maxhodges: updates in light of ES2015 and Meteor 1.2?

**Comment by hwillson** [comment]
An issue to track ReactiveDict documentation was opened in the docs repo, via meteor/docs#52. Since this issue is being tracked there, I'll close it here. Thanks!
