### ISSUE TITLE
cordova seem to be crashed because of loading all of /public everytime opened

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#4119]
I was getting a lot of notifs that our app would die on a white screen after installing. But it seems this is a known issue: 

from [Known issues](https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration#known-issues)

> All the assets in /public folder will be shipped to the client mobile app on every update of your code. And, in addition to that, a change of an asset is not noticed. The asset will be pushed with the next source code change.

is there a workaround for this, or within the ability/roadmap of meteor team to fix it?
This makes an app incredibly slow at startup if it has content.

This also will not happen in the background as normal app updates, but when the user opens the app - the first few minutes are spent starting at a white screen which looks like the app has crashed.

If images themselves haven't updated, its silly to have to re-download them every time. With meteor the goal is to do code-pushes frequently but that means every time someone opens the app they'll think its crashed.

What other mitigation approaches are there for this awful UX?

## don't use /public - put images on a CDN
One option is to put all the assets onto a CDN and use cdn URLs, but then presumably cordova wont cache the images after the first load?  Not sure how much caching the webview itself will do.

## preload images
Another trick - preload the images from the CDN after the body has loaded
http://stackoverflow.com/questions/18802336/how-to-make-image-load-smoother-in-phonegap-application
or load them into single pix images in the background
that would require to build some kind of list of assets

with both of these issues the only caching would be what the cordova webview does, which is probably not that much: 10mb? and volatile if the cordova app gets bounced from memory? Its not like a real "on disc" cache.

**Comment by dcsan** [comment]
OK so i moved all my assets to a CDN, installed fast-render, and the app is quicker but still has a "white screen of death" at startup that takes about 2 minutes to go away. It's longer than the auto-timeout / turn off setting for the phone, and since JS hasn't started yet, there's no "loading progress" from meteor.
This is on the latest samsung note and fast cell connection.

I think this is a cordova problem as the app starts much quicker just accessing from a browser.

has anyone else found ways around this? Perhaps a decent native cordova loader plugin could take care of it, but not sure if its complicated by meteor loading assets in a different way than it does when just playing from a normal browser.

**Comment by Slava** [comment]
The general rule of thumb is not to put any big files into `/public` for a lot of reasons:

- the build process of meteor naively copies all the files and uploads them on deployment
- serving static assets from a node.js server is generally not the best approach
- mobile apps contain all the assets (and they are redownloaded every time the app is updated)

So how to use the `/public` folder then? Put small assets essential for the application, like logo icons, sprites for buttons, etc. Don't put photos, media files or any user-generated content there. For these purposes use a service that would store and serve static assets for you (like S3 or similar services from RedHat).

Here is no a workaround, you as a developer have to understand the cost of every asset you bundle with your app.

Now, if you decide to load all the assets from your server, always (and never bundle any assets with the mobile app), you can create a local package and add assets only for the browser part (and not for the mobile part). Then, when you render images, always set the absolute url to the url of your server, this way mobile app will always go and fetch them from the Internet.

I am not sure I understood what is the "white screen of death" and how is it even relevant to the static assets. If there is a reproduction that is strictly related to the number of assets  bundled with the app, please open a separate ticket. Otherwise, this looks like a good topic for Meteor Forums to figure out the best strategy to split your assets to external service vs app bundle.

**Comment by slickdev** [comment]
@Slava 

What if you have a mobile application that needs to be able to load all assets offline + hosting assets on server or CDN is not possible? In my case we have many PDFs and video files that need to be included. What would be the best option for loading this static content into our iOS app?

**Comment by derwaldgeist** [comment]
I would like to second on that. One of the key ideas of having a Meteor Cordova app (at least in my POV) is the ability to run the app offline as well - seemlessly. But this can only work if all the essential static assets have been included in the app itself. I understand that it is not a good idea to put them in /public. But where else can I put the essential stuff, then?
