### ISSUE TITLE
Win XP Error: Couldn't run tasklist.exe (when meteor run)

### ISSUE THREAD

**Issue by rabet** [meteor/meteor#4128]
Hey guys,

I downloaded Meteor 1.1.0.1 and installed on my Windows XP (SP3). I can create the project with *"meteor create"*.
But when I exec *"meteor run"* I got the following error:

C:\meteor\leaderboard>meteor run
[[[[[ C:\meteor\leaderboard ]]]]]

=> Started proxy.

C:\Documents and Settings\Dari\Local Settings\Data aplikac├ş\.meteor\packages\me
teor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.j
s:278
                                                throw(ex);
                                                      ^
Error: Couldn't run tasklist.exe: {"killed":false,"code":1,"signal":null}
    at Object.Future.wait (C:\Documents and Settings\Dari\Local Settings\Data ap
likac├ş\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\dev_bundle\lib\n
ode_modules\fibers\future.js:398:15)
    at findMongoPids (C:\Documents and Settings\Dari\Local Settings\Data aplikac
├ş\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\tools\run-mongo.js:12
0:16)
    at findMongoAndKillItDead (C:\Documents and Settings\Dari\Local Settings\Dat
a aplikac├ş\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\tools\run-mo
ngo.js:254:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Documents and Settings\Dari\
Local Settings\Data aplikac├ş\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x
86_32\tools\run-mongo.js:378:7)
    at launchMongo (C:\Documents and Settings\Dari\Local Settings\Data aplikac├ş
\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\tools\run-mongo.js:630:
7)
    at [object Object]._.extend._startOrRestart (C:\Documents and Settings\Dari\
Local Settings\Data aplikac├ş\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x
86_32\tools\run-mongo.js:730:19)
    at [object Object]._.extend.start (C:\Documents and Settings\Dari\Local Sett
ings\Data aplikac├ş\.meteor\packages\meteor-tool\1.1.2\mt-os.windows.x86_32\tool
s\run-mongo.js:688:10)
    at C:\Documents and Settings\Dari\Local Settings\Data aplikac├ş\.meteor\pack
ages\meteor-tool\1.1.2\mt-os.windows.x86_32\tools\run-all.js:199:26
    - - - - -
    at C:\Documents and Settings\Dari\Local Settings\Data aplikac├ş\.meteor\pack
ages\meteor-tool\1.1.2\mt-os.windows.x86_32\tools\run-mongo.js:73:24
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

I followed other threads with similar issue but nothing helped. I have windows/system32 path in my PATH env., can easily run tasklist.exe in cmd. I also restarted system after installation (someone pointed it as a solution to this issue), nothing worked.

Thanks a lot for any help,

r.

**Comment by amitchanchal** [comment]
I am getting similar error on windows 7

**Comment by spyhole** [comment]
The Windows installer supports Windows 7, Windows 8.1, Windows Server 2008, and Windows Server 2012. The command line installer supports Mac OS X 10.7 (Lion) and above, and Linux on x86 and x86_64 architectures.

**Comment by amitchanchal** [comment]
I have mine running now. I added path to tasklist and restarted the system, which was quite straightforward.. do you have the error still?

**Comment by avital** [comment]
@rabet: [Windows XP](https://github.com/meteor/meteor/wiki/Supported-Platforms) is not one of the supported platforms for Meteor.

@amitchanchal: I'm curious, is your `tasklist.exe` not in `C:\Windows\System32`? Or was that directory not in your path?

**Comment by amitchanchal** [comment]
@avital - my tasklist.exe was in C:\Windows\System32 but the directory was not there in path.

**Comment by daix6** [comment]
@avital : my tasklist.exe was in C:\Windows\System32 ,and the directory was in my path. But I still got the same problem...

**Comment by harrisonbfs** [comment]
@amitchanchal  how do you add the path to task list?
thx im a noob

**Comment by harrisonbfs** [comment]
<a href="https://www.google.com/">Test</a>

**Comment by ndarilek** [comment]
Seeing this under Windows 10. My app worked fine last Friday before the 10 upgrade, I was on Windows 8.1. tasklist.exe runs fine and is in my path. Multiple restarts, multiple reinstalls. Failed under Meteor 1.1.0.2 and 1.1.0.3.

I just need to get this working so I can get back to work. Any help greatly appreciated.

**Comment by ndarilek** [comment]
I have a bit more information at #4877, which I'll leave open because it describes another issue that is probably unrelated. Here are some other things I've tried:

 * Manually blowing away ~/AppData/local/.meteor, which was left around after the uninstall.
 * Removing the .meteor/local directory in my app.
 * Creating an entirely new app. This behavior happens there as well.

Looking at the returned JSON, is it possible that tasklist.exe runs but exits with code 1 for some reason? And, instead of trying for a successful parse, whatever runs it simply concludes that the 1 is an error condition and gives up? I can run it just fine from the console and get a list of running tasks.

Or is there some way of getting at the contents of stdout/stderr? Would be nice if `--verbose` gave a bit more insight.

Thanks.

**Comment by ndarilek** [comment]
I have a possible fix. It isn't a patch as such, but instructions on how to modify mt-os.windows.x86_32\tools\run-mongo.js. Don't ask me why it works, and it should probably be more widely tested, but it works for me.

When I manually run:

`child_process.exec('tasklist /fi "IMAGENAME eq mongod.exe"', function(err, stdout, stderr) {
   console.log(stdout, stderr)
})

I get this interesting gem:

> INFO: No tasks are running which match the specified criteria.
 The system cannot find the path specified.

So it looks like it both runs and doesn't. I see the same error when running Node's extended cmd incantation for this particular case, so it's something deeper down the rabbit hole than I personally can manage or debug.

Out of curiosity, I wondered what would happen if I changed:

    child_process.exec('tasklist /fi "IMAGENAME eq mongod.exe"',
      function (error, stdout, stderr) {
        if (error) {

to:

    child_process.exec('tasklist /fi "IMAGENAME eq mongod.exe"',
      function (error, stdout, stderr) {
        if (error && stdout.length == 0) {

And, low and behold, the mongod error went away. Had to do the same for netstat slightly below in the same file. Please don't ask why that works for me, I'm using Windows in anger and know just enough to be dangerous and not get too much malware. :)

My app still doesn't quite start, but that is due to a package error that looks refreshingly non-OS-related.

I would appreciate it if anyone more familiar with Windows and Node on same could chime in here, and I'd *really* appreciate it if we could work this into a fix so I don't have to manually patch this going forward. :) I can work on a PR but have no idea why this happens or if this is the right way to fix it. I also have no clue how to build Meteor from source, so the best I can likely manage is put these changes in the right place and hope someone smarter than me can ensure that they make it to an upcoming release.

Thanks.

**Comment by avital** [comment]
@ndarilek When I run:
```
child_process.exec('tasklist /fi "IMAGENAME eq mongod.exe"', function(err, stdout, stderr) {
console.log(stdout, stderr)
})
```

on my Windows 10 machine I don't see "The system cannot find the path specified.". I  wonder how our environments differ...

**Comment by ndarilek** [comment]
Aha, more information. Turns out I had something in my autorun settings that was no longer present after my upgrade. See this:

http://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified

I use cygwin/bash as my shell so didn't see this one much. But I started noticing that every cmd instance threw this error. Clearing the first key in that answer resolved the issue for me.

**Comment by georgiosd** [comment]
For me (Windows 10), it fails because the command itself fails. Even though it seems valid according to spec, tasklist responds with "Invalid query"

**Comment by georgiosd** [comment]
After searching and searching, everything was solved by rebooting... go figure

**Comment by isdzulqor** [comment]
i have the similar problem, and i still cannot fix it,,, 
@georgiosd what do you mean solved by rebooting? i restart and reboot, but it's not working,,

**Comment by isdzulqor** [comment]
[SOLVED]
I add C:\Windows\System32 to my PATH of System variables in environment variable,

**Comment by witmicko** [comment]
[SOLVED]
Running on Windows 10 x64
Had tasklist command on the path, but was still getting this err.
fix> in file AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-mongo.js
change line 65 from:
if (process.platform === 'win32') {
to
if (process.platform === 'win64') {

**Comment by muceres** [comment]
[SOLVED]
If atfer adding C:\Windows\System32 it's still don't work, try adding C:\Windows\SysWOW64.
It's worked for me :)

**Comment by lyquocnam** [comment]
OMG windows xp :D

**Comment by abernix** [comment]
Closing this very old Windows XP issue as it seems to have no outstanding action item.

If you're encountering a "The system cannot find the path specified" message after installing Meteor, you should restart your computer to ensure that your `PATH` is updated properly – it is still not set properly without reboot in Windows 10.
