### ISSUE TITLE
Include required node version when building server package.json

### ISSUE THREAD

**Issue by fiveisprime** [meteor/meteor#4137]
Hi, maintainer of Demeteorizer here. :)

I'm working on using the Meteor's build command in place of bundle and I've
found that the result is close to being able to deploy to Modulus directly. The
only thing lacking is the node version in package.json so latest stable node
(0.12.1) is used which doesn't compile fibers.

Demeteorizer looks at `MIN_NODE_VERSION` in `boot.js` to determine the required
version, but there's no access to that variable when [building the server package.json](https://github.com/meteor/meteor/blob/c99f9584c1ab6af9c2b64c04557abb3f4cf7e407/scripts/dev-bundle-server-package.js#L18)
and I'd rather not add some kludgey code to your project so I'll open an issue
instead. <3

**Comment by glasser** [comment]
You mean as an engines field? Sure, that seems reasonable. Send a PR, including updating the place where it lists all the things that have to be changed when we upgrade Node.

**Comment by baberuth22** [comment]
I tried specifying the node version and I get an error.

~/Meteor/booking3: demeteorizer --server-only --node-version 4.4.7 --architecture os.linux.x86_64

  error: unknown option `--node-version'



Although the json version works fine.

demeteorizer --json "{ \"engines\": { \"node\": \"4.4.7\" } }"

**Comment by hwillson** [comment]
Closing since demeteorizer now supports modifying the `engines` field (see [Modifying the Generated package.json](https://github.com/onmodulus/demeteorizer#modifying-the-generated-packagejson)). Any further demeteorizer questions should be opened within the [demeteorizer repo](https://github.com/onmodulus/demeteorizer). Thanks for posting this request originally!
