### ISSUE TITLE
Meteor.loginWithPassword parameter documentation contains misleading information

### ISSUE THREAD

**Issue by ianjonesidau** [meteor/meteor#4145]
The Accounts documentation has a misleading parameter description, which states that:

> Either a string interpreted as a username or an email; or an object with a single key: email, username or **id**.

But when checking the source for the function I noticed that `id` is not supported. This mislead me for a while when trying to write my own custom login function.

http://docs.meteor.com/#/full/meteor_loginwithpassword
https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_client.js#L14

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

I'm not sure what caused you to believe that `id` was not supported, since according to the source for the server it is: https://github.com/meteor/meteor/blob/453981214ded436c1fc13d82b92de912776ac14c/packages/accounts-password/password_server.js#L84-L86

**Comment by ianjonesidau** [comment]
Sorry my bad, a simple confusion with client vs server code.
