### ISSUE TITLE
Allow to pass parameters to mongo shell  from "meteor mongo"

### ISSUE THREAD

**Issue by skagedal** [meteor/meteor#4164]
It would be nice if you could pass on parameters to the mongo shell from a `meteor mongo` command line. Suggested interface:

```
meteor mongo $METEOR_MONGO_PARAMS -- $MONGO_PARAMS
```

Typical use case:

```
meteor mongo myapp.meteor.com -- my-script-file.js
```

(Also see [Stack Overflow](http://stackoverflow.com/a/29547659/1132101))

Curious to hear if a PR for this feature would be considered.

**Comment by Slava** [comment]
It is a good idea, would love to review a PR.

**Comment by dferber90** [comment]
I looked into implementing this. Getting the suggested interface (`meteor mongo $METEOR_MONGO_PARAMS -- $MONGO_PARAMS`) seems to be "impossible" right now, because Meteor strips the `--` before saving the arguments to `options.args`. Therefore the function can not differentiate between arguments for Meteor and arguments for Mongo.

Since this idiom could be reused across multiple commands, identifying the additional arguments should maybe be part of `tools/main.js` and expose the part after `--` in `options.additionalArgs` for `main.registerCommand` (e.g. [here](https://github.com/meteor/meteor/blob/devel/tools/commands.js#L978)). Or is this already possible and I just didn't see it?

**Comment by skagedal** [comment]
I created a standalone script called `mmongo` that gives this functionality, [see GitHub page](https://github.com/skagedal/mmongo).  There, I also wrapped some other MongoDB command line tools like `mongodump`, `mongorestore`, `mongoexport` and `mongoimport`. The syntax here is, for example: `mmongo <parameters for meteor> dump <parameters for mongodump>`. And then for the `mongo` tool, I use `run`, as in  `mmongo <parameters for meteor> run <parameters for mongo>`. Maybe this style would be better for `meteor mongo` than the `--` separator?

**Comment by hwillson** [comment]
This has definitely become much less of an issue now that *.meteor.com hosting (including Mongo) has been sunsetted. That being said @skagedal's great [mmongo](https://github.com/skagedal/mmongo) library shows that this functionality can be handled outside of the Meteor core. There are also other options for handling this, like using the full blown `mongo` CLI outside of Meteor, or piping scripts / commands into `meteor mongo` like `echo 'show collections' | meteor mongo`. 

Given the above, and as part of the on-going old issue cleanup process, I'll close this for now. Thanks for submitting this feature request originally!
