### ISSUE TITLE
Class based helpers

### ISSUE THREAD

**Issue by sdistefano** [meteor/meteor#4180]
It would be nice to be able class based helpers in Meteor, and other patterns that are compatible with the OOP capabilities of coffee script.
Currently Meteor has much more repeated code than, for example, Django or RoR.

I would love something like this to be possible:

```
class Template1Helper extends BaseTemplateHelper
   method1: ->
      @baseMethod arg

Template.Template1.registerHelperObject Template1Helper
```

for example

**Comment by thinklinux** [comment]
So you can do something like this [See here](http://coffeescript.org/#try:class%20Foo%0A%0A%20%20m%3A%20-%3E%201%0A%20%20bla%3A%20-%3E%202%0A%0Aobj%20%3D%20new%20Foo%0A%0Amap%20%3D%20%7B%7D%0A%0Amap%5Bk%5D%20%3D%20v%20for%20k%2C%20v%20of%20obj%20when%20typeof%20v%20is%20'function'%0A%0Aconsole.log%20map%0A)

And when you have a map of all the methods in your instance you can register it to a template.

**Comment by sdistefano** [comment]
Thanks, I've tried something like this already. The problem is that it doesn't let us call internal methods, such as
```
_render_stuff: (item) ->
    return "<strong>#{item}</strong>"

render_a: ->
    @_render_stuff 'a'

render_b ->
    @_render_stuff 'b'

```

This is very important for DRY I think.

Regarding the appropiate place to put it, for sure this isn't a bug, but I'm not sure of where to submit suggestions for improvement? The forum and stackoverflow are more for questions about usage, I believe?

**Comment by thinklinux** [comment]
Ok. You can see a new example [Here](http://coffeescript.org/#try:class%20Foo%0A%0A%20%20_render_stuff%3A%20-%3E%0A%20%20%20console.log%20'Calling%20private%20method'%0A%20%20m%3A%20-%3E%20%40_render_stuff()%0A%20%20bla%3A%20-%3E%202%0A%0Aobj%20%3D%20new%20Foo%0A%0Amap%20%3D%20%7B%7D%0A%0Amap%5Bk%5D%20%3D%20v.bind(obj)%20for%20k%2C%20v%20of%20obj%20when%20typeof%20v%20is%20'function'%0A%0Aconsole.log%20map%0Amap.m()%0A)

If I understood correctly that example should work for you.

Well Meteor now accept feature requests as you can see [here](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests) but again I don't know how much MDG is involved in supporting coffee script throughout the whole platform. That's why I gave you links to Meteor's forums and Stackoverflow because I think this is something the community can handle.

**Comment by sdistefano** [comment]
Understood, thank you!

**Comment by Slava** [comment]
Glad you resolved your questions.
