### ISSUE TITLE
Accounts package will not use different database.

### ISSUE THREAD

**Issue by joetidee** [meteor/meteor#4185]
I have installed the Account-Base package and when I register a new user, the package always writes to the default 'meteor' database, not the actual database I am using for my app. - how do I get it to connect correctly?

I have tried MONGO_URL en var, but have been told this is not to be used in development. I have used the MongoInternals.RemoteCollectionDriver method, but have been told that this is an undocumented feature and shouldn't be used - so WHAT do i use??

**Comment by serkandurusoy** [comment]
How did you define the "actual database" that you use in your app in the first place?

You normally have two options:

a) Run meteor as is and it will use its internal mongodb. The name of the database will always be meteor.

b) Run meteor passing in the MONGO_URL environment variable. That can use any mongo database anywhere with any database name. The accounts package, as well as the rest of your app will use that.

So I wonder, without providing a MONGO_URL parameter, how you managed to split your data into two different databases anyway.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

I don't see any reason that `Meteor.users` would use a different database than the default database used by the rest of your app (configured via `MONGO_URL`).

You also didn't specify if this was a production or development issue.

**Comment by joetidee** [comment]
I used the following line to connect to my 'actual database'. This was in a file located in a 'server/lib' folder pf my Meteor app.

var d = new MongoInternals.RemoteCollectionDriver("mongodb://127.0.0.1:3001/my-db");
coll = new Mongo.Collection("my-coll", {_driver: d});

At present, I am still in development, using Virtual Machine to run the Meteor app and Mongo instance. I am guessing that because this way of connecting to a database within Meteor would not be picked up by the Accounts-Basic package automatically - could you confirm this?

**Comment by serkandurusoy** [comment]
@joetidee this is something you would do only in rare circustances where you need to connect to some secondary database other than what your meteor app connects to by default as its main app database.

When using meteor, you don't define a connection like you normally do with a node app.

By default, if you run metor, it will also run an instance of mongodb that is bundled with meteor itself.

If you don't want to use that and use some other database or you want to use it but /my-db instead of /meteor, what you should do is run meteor using the MONGO_URL environment variable. You can read this http://docs.meteor.com/#/full/deploying for further information.

Also, if you like to continue this discussion, please come over to https://forums.meteor.com/ or http://stackoverflow.com/questions/tagged/meteor where you'll find virtually unlimited help. :wink: 

Meteor devs kindly ask us to use this tracker for bugs and feature requests that follow https://github.com/meteor/meteor/blob/devel/Contributing.md
