### ISSUE TITLE
Template name collision

### ISSUE THREAD

**Issue by dbnoble** [meteor/meteor#4189]
In the case of a template being named "watch", rendering is halted when viewing with Firefox, leaving only a blank page.

The following error is thrown:

Expected template or null, found: undefined

The error is only thrown in Firefox, while in IE and Chrome the application seems to load as expected.

I'm assuming that there are likely other template names which would the same type of collision with native javascript functions.

**Comment by Slava** [comment]
This looks like a valid concern that needs to be addressed. Several reasons why the current state is weird:

- `Template` is a constructor name, which has a type "function"
  + functions have more and more methods on their prototype, in Firefox, additional experimental methods are added with every release (`watch` is one of them)
- `Template` also acts as a namespace, every new template compiled from spacebars files, is attached to the `Template` object/function.
- Since it happens in the generated code, adding a check or changing the API can be difficult for all the packages already compiled.

**Comment by mitar** [comment]
[Blaze Components](https://github.com/peerlibrary/meteor-blaze-components#namespaces) have namespaces. :-)

**Comment by hwillson** [comment]
I've migrated this over to meteor/blaze#180 - closing - thanks!
