### ISSUE TITLE
Package 'launch-screen' automatically available

### ISSUE THREAD

**Issue by jmanos3** [meteor/meteor#4200]
I am finding that the 'LaunchScreen' object is available automatically in a project without the need to add it via 'meteor add launch-screen'. Should this be the case? If so, should the documentation be changed?

The documentation at https://github.com/meteor/meteor/tree/release-1.1/packages/launch-screen1 led me to believe that this package would need to be added to a project for use. In fact, if you do a 'meteor add launch-screen', you get 'launch-screen: Default and customizable launch screen on mobile.' And, if you do a 'meteor list' after added it to the project, you get 'launch-screen 1.0.2 Default and customizable launch screen on mobile. in the list packages in the project.

However, if you create a brand new project, without adding the package, the LaunchScreen object is available.

**Comment by Slava** [comment]
It is included by default in `meteor-platform`, the meta package. It doesn't show up in the `meteor list` output, as it is a transitive dependency. I think the docs are correct, because the package docs refer to a case of a plain project.

https://github.com/meteor/meteor/blob/dda3a9f76694d21ce9e5d63e8a0bacf1c4fddb10/packages/meteor-platform/package.js#L72
