### ISSUE TITLE
PACKAGE_DIRS should be splitted by semicolon on windows

### ISSUE THREAD

**Issue by dim2man** [meteor/meteor#4204]
I have a Meteor app using local packages from several directories. On Linux I use PACKAGE_DIRS environment variable to specify the locations of my package directories and it works just fine.
```
export PACKAGE_DIRS=/path/to/dir1:/path/to/dir2:/path/to/dir3
```
After migration to Meteor 1.1.0.2 and starting the app on windows OS it fails because it cannot find the local packages by name. The PACKAGE_DIRS variable is set as below:
```
set PACKAGE_DIRS=D:\path\to\dir1;D:\path\to\dir2;D:\path\to\dir3
```
I suspect the PACKAGE_DIRS environment variable is splitted in the https://github.com/meteor/meteor/blob/master/tools/project-context.js#L509 always by colon. However the standard path delimiter on windows is semicolon because colon is used to separate the drive letter from the path.

As a workaround I've changed paths in PACKAGE_DIRS to the relative ones and delimited them by colon. After that the app has been started successfully.
```
set PACKAGE_DIRS=relative_path\to\dir1:relative_path\to\dir2:relative_path\to\dir3
```

**Comment by Slava** [comment]
You are right it is a bug. We should fix it.

(cc @avital)

**Comment by komposure** [comment]
@Slava This bug is stupidly easy to fix, is it not?:

https://github.com/meteor/meteor/blob/643d09a629a4fa28c466c72e1e3386f1080360f3/tools/project-context.js#L542

Change the character to a ';', instead of a ':'. How you'd deal with backwards compatibility is up to you guys, but you could simply change the delimiter for `process.platform === "win32"` or if no colons are found in the path, else use the colon operator as the delimiter.

Something like:

    var self = this;
    var searchDirs = [files.pathJoin(self._projectDirForLocalPackages, 'packages')];

    if (! self._ignorePackageDirsEnvVar && process.env.PACKAGE_DIRS) {
      var packageDirs = process.env.PACKAGE_DIRS;
      var packageDirsDelimiter = 
        (process.platform === "win32" || packageDirs.indexOf(':') === -1) ? ';' : ':';

      _.each(process.env.PACKAGE_DIRS.split(packageDirsDelimiter), packageDirsArray, function (p) {
        searchDirs.push(files.pathResolve(p));
      });
    }

**Comment by derwaldgeist** [comment]
Stumbled upon this. Why isn't this simple thing fixed yet? It prohibits my build on Windows now. :-/

**Comment by abernix** [comment]
Probably because it has three votes (now) and there are a lot of other pressing issues?

If it's important to you, I highly believe Meteor Core Team would accept a pull request for this (probably even without backward compatibility).  Please do as, you're likely in a better position to test this than anyone!

As mentioned above, I believe you can work around this by using relative paths – even if that means going down a level (i.e. `..\..\global\packages`)

**Comment by derwaldgeist** [comment]
Yeah, maybe that's not one of the most important issues. But it's neglecting core folder mechanisms on Windows. Anyway, as I am mainly working on a Mac, I don't care.
