### ISSUE TITLE
Meteor.setInterval(func, delay, noOfIterations)

### ISSUE THREAD

**Issue by dcworldwide** [meteor/meteor#4210]
Would be great if setInterval allowed us to define how many iterations the timer should execute before terminating.

**Comment by Slava** [comment]
This is not how `window.setInterval` works according to MDN: https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setInterval.

`Meteor.setInterval` is an ugly API that exists only because we need to bind some dynamic environment and start fibers on the server. Hopefully, in the future, we would be able to use a feature that landed in node 0.12 that allows us to configure universally how all async callbacks should be wrapped.
