### ISSUE TITLE
Website doesn't accept uppercase usernames

### ISSUE THREAD

**Issue by c316** [meteor/meteor#4216]
When trying to create a meteor account I am not able to use one with uppercase letters. 
![screen shot 2015-04-16 at 11 07 07 am](https://cloud.githubusercontent.com/assets/3142974/7185569/3022e9fc-e429-11e4-89c7-3a396a1bc021.png)

**Comment by Tarang** [comment]
I think this is because of the integrity required to 1) package names & org names (which all have to be lower case) & 2) to prevent duplication with different casing.

When things were on Meteorite things became very confusing when everything wasn't forced down to lowercase. The package name has to be case sensitive due to *nix system's case sensitivity.

The problem aroused when trying to explain something on stackoverflow or sharing code where the capitalisation sensitivity created all these problems where packages wouldn't add or crash. The 'forced' lowercase package names (as a result of the forced lowercase usernames) solves all this.

**Comment by Slava** [comment]
@c316 As Tarang said, there are technical reasons why there are so many limitations implied on the usernames. Since Meteor Developer Accounts don't support separate display names, these names have to be some proper strings that can be used in other places.
