### ISSUE TITLE
Wrong package version if a package is added as dependency of local package rather thant adding it from the project

### ISSUE THREAD

**Issue by Brindavoine** [meteor/meteor#4226]
From the project :

```
meteor create test
cd test
meteor add percolate:momentum
```
All is ok, lastest version is added (0.7.2) :
```
Changes to your project's package version selections:
                                              
percolate:momentum    added, version 0.7.2    
percolate:velocityjs  added, version 1.1.0
```

----------

From a local package :

```
meteor create test
cd test
meteor create --package foo:bar
meteor add foo:bar
```

packages/bar/package.js
```
Package.describe({
  name: 'foo:bar',
  version: '0.0.1',
  // Brief, one-line summary of the package.
  summary: '',
  // URL to the Git repository containing the source code for this package.
  git: '',
  // By default, Meteor will default to using README.md for documentation.
  // To avoid submitting documentation, set this field to null.
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.1.0.2');

  api.imply('percolate:momentum');
  api.addFiles('bar.js');
});

Package.onTest(function(api) {
  api.use('tinytest');
  api.use('foo:bar');
  api.addFiles('bar-tests.js');
});

```

Wrong version is added (0.0.2) :
```
Changes to your project's package version selections:
                                              
foo:bar             added, version 0.0.1      
percolate:momentum  added, version 0.0.2
```

**Comment by ekatek** [comment]
This is not actually a bug. We use different criteria to select versions for apps and for packages, so you might not (and don't) get the same answer. You probably want the line in `packages/bar/package.js` to say `api.imply('percolate:momentum@0.7.2');`.

A more detailed explanation follows:
The idea is, when you are adding a package to the app, you want to add the latest version of that package. This means that when you run `meteor add`, you get version `0.7.2`. We store this choice in .meteor/versions, so any time someone checks this app out from version control to run it, they will run it with `percolate:momentum` at `0.7.2`.

Packages are fundamentally different from apps, because packages have to interoperate with other packages. Additionally, packages are meant to be reused in different contexts. That means that, if you create a package (foo:bar), using another package (percolate:momentum), you want to set constraints on the version of percolate:momentum that you end up using -- if a new, incompatible version of percolate:momentum comes out, and then, app A adds foo:bar, you don't want things to break invisibly. Similarly, if A is already using another package that demands a much earlier version of percolate:momentum (ex: 0.0.0), you want the user to get a helpful error message, rather than trying to use foo:bar with an incompatible version of percolate:momentum.

That's why, in order to publish foo:bar, you would have to specify a constraint for percolate:momentum. For example, you would have to put percolate:momentum@1.0.0 (anything greater than 1.0.0, but less than 2.0.0 is fine) or percolate:momentum@=0.7.2 (use 0.7.2 only). Here is the key -- given a constraint, in general, we try to take the earliest possible version. For example, if you wrote percolate:momentum@1.0.0, we would try to provide percolate:momentum@1.0.0, and only increment to percolate:momentum@1.0.1 if we have to. We do this, because we assume that if foo:bar requests percolate:momentum@1.0.0, the maintainer of foo:bar has tested it with version 1.0.0. We want to play it safe, and give the version that the package is tested with.

Since you did not specify a lower bound (percolate:momentum@0.7.0, for example), the lower bound was automatically set to 0.0.0. Meteor then chose the earliest version of percolate:momentum that it could, which is 0.0.2. Specifying percolate:momentum@0.7.2 should give you the result that you are looking for.

**Comment by Brindavoine** [comment]
Adding a constraint works.
Thanks a lot for your answer. Default constraint to 0.0.0 makes sense.
