### ISSUE TITLE
Make the base64 package public?

### ISSUE THREAD

**Issue by dandv** [meteor/meteor#4237]
I found [base64](https://github.com/meteor/meteor/tree/devel/packages/base64) useful to handle images taken by mdg:camera, which are base64-encoded.

Happy to submit a PR. It's already available [on Atmosphere](https://atmospherejs.com/meteor/base64), so why not?

Also, would it be possible to use the native Buffer on the server?

    new Buffer(encodedString, 'base64').toString()

**Comment by glasser** [comment]
I'm not sure what you're actually suggesting here.  Just changing the README to not say that it's internal?

I'm not sure how much more support we should give to this package.  At the time, we thought it made sense to use the "cross-platform" Uint8Array class instead of Buffer on the server, but that may have not been the best choice.

**Comment by abernix** [comment]
At this point,  I think an NPM package would serve your purpose better.  I don't think encouraging this or publicizing this would do much good, especially as Meteor works toward the NPM-sphere.
