### ISSUE TITLE
Packages as services

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4247]
**_1 Upvote**_ I think this is an interesting idea: [Atom Services API](http://blog.atom.io/2015/03/25/new-services-API.html). It would be interesting if packages could be offered like that. So multiple packages offering multiple versions. And also if a package could declare that it is a replacement for some other package, because it exposes the same API (so same (or more) symbols with same API).

And there is also lazy loading. Also interesting.

**Comment by ekatek** [comment]
Awesome, thanks for the feature request!  Yeah, this is an interesting idea. It is similar to what I was thinking about for how forking would (theoretically) work, so it is super neat to both, see this feature request, and see this awesome explanation and terminology from Atom. I agree that this would be super cool. Unfortunately, since we have limited manpower, I think that it is very unlikely that we will get to this in the very near future.

**Comment by mitar** [comment]
So yes, this could address both lazy loading, forking, shadowing, extending, etc. It uses semantic versioning as well. I think it would be an easy upgrade path without breaking backwards compatibility.

If I understand correctly, `api.imply` does not work like this yet? So that you could create an alternative implementation and say that it implies to original one?

One useful thing would be to be able to get also the contents of original package. For example, for many core Meteor packages it is really hard to use them. You have to git submodule the whole Meteor repository and then `addFiles` from there. And often the symbols you want to access are maybe not even exposed on the package level.

**Comment by ekatek** [comment]
>> If I understand correctly, api.imply does not work like this yet? So that you could create an alternative implementation and say that it implies to original one?

Yeah, I think trying to hack together forking with the current `api.imply` would be awkward, and probably not work very well. At the moment, one way to think of `api.imply` is like `api.add`, that also exposes the api of the implied package. But if X implies `tracker`, for example, you still end up with the app bundling both X and `tracker`. That's the opposite of what you want if X is a fork of `tracker`.

This is really the sort of thing that really wants to be propagated down into the version solver, which can learn to treat X as, uh, implementing the `tracker` service, so that if `requires-tracker` requires `tracker`, and X is present, we can decide that the constraints for `requires-tracker` are satisfied.

>> One useful thing would be to be able to get also the contents of original package.

That's probably a different issue, if I understand what you are saying correctly. (That since we store the source already, we should give you an easier way to get the source, especially for core packages, without having to checkout the entire Meteor repository).

**Comment by mitar** [comment]
> That's probably a different issue, if I understand what you are saying correctly. (That since we store the source already, we should give you an easier way to get the source, especially for core packages, without having to checkout the entire Meteor repository).

The question is if I need source, or just symbols. It is probably different. So one thing would be that you would have something like `api.addPackage` which would do the same as you would call `api.addFiles` on all files of that package, on that spot. Or you could even select which files.

But another option would be to allow simply access to all symbols in the package, both package-level and file-level in some way (maybe just the former). This is for example something which would better, because you would not have to care about concrete implementation, just that it is available, so that you can wrap or patch it. And of course, even your dependency could be replaced with some other implementation. ;-)

Anyway, yes, this is probably something for later on. I would do it together with lazy loading of packages.

**Comment by Gaelan** [comment]
:+1::exclamation:

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Packages%20as%20services&body=Migrated%20from:%20meteor/meteor%234247) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
