### ISSUE TITLE
DDP Server pong response does not follow DDP spec, can cause client heartbeat to be lost and infinite re-connects

### ISSUE THREAD

**Issue by rogerrathers** [meteor/meteor#4298]
DDP SPEC: "At any time after the connection is established either side may send a ping message. The sender may chose to include an id field in the ping message. When the other side receives a ping **it must immediately respond with a pong message** ." https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md

### Screenshot of issue ###
![ddp_pong_blocked](https://cloud.githubusercontent.com/assets/9425048/7399855/9683dee2-ee6d-11e4-885c-1aaa73925360.png)

View live demo here: http://ddp_pong_blocked.meteor.com/

### Reproduction recipe ###
git clone https://github.com/rogerrathers/meteor_ddp_pong_blocked
cd meteor_ddp_pong_blocked/
meteor

Graemian's issue #2466 has a root cause in this blocked pong response.

**Comment by glasser** [comment]
Thanks for the good reproduction.

So, what's happening here is that your publisher body runs entirely synchronously and doesn't actually yield to the event loop for a while.  For me, it takes about 0.8 seconds for it to run and send all the `added` messages.  Then it sees the ping and immediately resolves with a pong.

It then takes a remarkably long time for the client to process those 30K messages; there may be some accidental quadratic behavior in there we could look at.  My guess that this is because we apply the messages to minimongo one at a time instead of batching them up.  Only after processing all these messages do we see the pong message.

First, we really should change the way that the heartbeat works to count *any* message from the other server (not just a ping) as a pong.  That's a simple change that will fix the timeout issue at the bottom.  I think this is pretty simple, basically just:

```diff
diff --git a/packages/ddp-client/livedata_connection.js b/packages/ddp-client/livedata_connection.js
index c3783fb..c8965cf 100644
--- a/packages/ddp-client/livedata_connection.js
+++ b/packages/ddp-client/livedata_connection.js
@@ -211,6 +211,11 @@ var Connection = function (url, options) {
       return;
     }
 
+    // Count any message as a pong.
+    if (self._heartbeat) {
+      self._heartbeat.pongReceived();
+    }
+
     if (msg === null || !msg.msg) {
       // XXX COMPAT WITH 0.6.6. ignore the old welcome message for back
       // compat.  Remove this 'if' once the server stops sending welcome
@@ -243,9 +248,6 @@ var Connection = function (url, options) {
         self._heartbeat.pingReceived();
     }
     else if (msg.msg === 'pong') {
-      if (self._heartbeat) {
-        self._heartbeat.pongReceived();
-      }
     }
     else if (_.include(['added', 'changed', 'removed', 'ready', 'updated'], msg.msg))
       self._livedata_data(msg);
diff --git a/packages/ddp-server/livedata_server.js b/packages/ddp-server/livedata_server.js
index 373d11e..67c788e 100644
--- a/packages/ddp-server/livedata_server.js
+++ b/packages/ddp-server/livedata_server.js
@@ -494,6 +494,13 @@ _.extend(Session.prototype, {
     if (!self.inQueue) // we have been destroyed.
       return;
 
+    // All messages count as pongs.
+    if (self.heartbeat) {
+      Fiber(function () {
+        self.heartbeat.pongReceived();
+      }).run();
+    }
+
     // Respond to ping and pong messages immediately without queuing.
     // If the negotiated DDP version is "pre1" which didn't support
     // pings, preserve the "pre1" behavior of responding with a "bad
@@ -513,10 +520,6 @@ _.extend(Session.prototype, {
       return;
     }
     if (self.version !== 'pre1' && msg_in.msg === 'pong') {
-      if (self.heartbeat)
-        Fiber(function () {
-          self.heartbeat.pongReceived();
-        }).run();
       return;
     }
```

(This doesn't help if you're slowed by a single very large message; see https://github.com/faye/faye-websocket-node/issues/35)

Finally, how about getting the pong earlier, so that the "blocked pong" case works?  If we changed DDP to properly respect TCP flow control buffering, we could stop writing messages to the websocket when it gets "jammed" and maybe insert pong in the middle.  Not sure if this is worth the extra complexity, compared to just doing the about fix.

(about to head out on vacation for a week so can't look into this more

**Comment by rogerrathers** [comment]
Thanks for the detailed response!

The real-world issue users were running into was loading a few thousand documents over a slower connection got stuck in the infinite-reload loop.  Your solution of counting every message as a 'pong' should fix the lost 'pong' heartbeat issue.  The current ping/pong implementation already works as spec'ed over idle connection (arguably the most critical situation to use them),  so my vote would be going with the simple fix you suggested.

**Comment by gchpaco** [comment]
d84c96295f1734e11d48fc4383e0ece75e20360e on `devel` implements the implicit pong, and should hopefully fix your issue.
