### ISSUE TITLE
Allow Plugin.registerSourceHandler() for .css source files

### ISSUE THREAD

**Issue by stolinski** [meteor/meteor#4307]
https://github.com/postcss/postcss

PostCSS processing would require the ability to watch CSS files. I only really see conversation of multiple Source Handlers in the context of .js or .html. I think being able to add onto the the default css Source Handler would be very beneficial to take advantage of the numerous plugins and options for css post-processors.

**Comment by mquandalle** [comment]
Related: #1207 and https://github.com/MeteorCommunity/discussions/issues/51

**Comment by benjamn** [comment]
cc @Slava @glasser

I believe support for multiple build handlers will be improving soon.

**Comment by Slava** [comment]
I don't think our effort on the `batch-plugins` branch enables this but it creates a separate feature for post-css and minifiers and linters and other things.

**Comment by Primigenus** [comment]
I ran into the same problem when I tried to write a package for @purifycss/purifycss, so this would be great to have!

**Comment by hwillson** [comment]
`Plugin.registerSourceHandler` has been deprecated (since Meteor version 1.2). The [Build Plugins API](https://docs.meteor.com/api/packagejs.html#build-plugin-api) should be used in its place. PostCSS processing is now possible, and is discussed in the [PostCSS and Autoprefixer](https://guide.meteor.com/build-tool.html#postcss) section of the Guide. Closing this off - thanks!
