### ISSUE TITLE
Module system in Meteor.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4310]
Is there any plan to have a module system for Meteor (ES6 Modules perhaps)?

I'm using Webpack to make bundles (one can be made for the server and one for the client). Each bundle can `require`/ or `import` common things used on both sides. It works nicely...

But problems can arise when (for example) a webpack bundle needs to depend on an Atmosphere package's globally exposed API, and that API depends on another Atmosphere package that contains an external non-Meteor library that the initial webpack bundle depends on too, causing duplicate code to exist in the app: one in the webpack bundle, and one in an Atmosphere package. For example, a library I'm using in my webpack bundle depends on [Famous](https://www.npmjs.com/package/famous) from npmjs.com, while a library I need from Atmosphere depends on [raix:famono](https://atmospherejs.com/raix/famono) which supplies a global version of Famous, so I have two Famous libraries in my app, which can lead to unexpected things happening because two sets of code that depend on Famous both want to use a Famous `Engine`, but there's no out of the box way for them to share the same `Engine`. A quick solution would be to port the Atmosphere package depending on raix:famono to npm, depend on Famous from npm instead of raix:famono, then I can use that library in my webpack bundle and there will be a single Famous `Engine` in the app.

It can be harder for large teams in large organizations to adopt Meteor for projects that are projected to be big because it doesn't have a module system (where modules with file-level scopes can export things that *aren't* put in global scope and other file-level scopes can import those things directly) in a world where the best tools outside of Meteor (webpack, browserify, etc) already have this (CommonJS for importing and exporting things at first, but AMD/ES6 with extensions to the tools).

Imagine what happens when a Meteor app gets huge, with hundreds of thousands of lines of code. The largest Meteor app I've seen in person was 12,000 lines and I could already see the complications.

Galaxy will scale application bandwidth, but we also need something that scales developer productivity in a standard way that the whole rest of the JavaScript community uses (CJS and now ES6 Modules, goodbye AMD). Meteor's packaging system is evolving aside from the JavaScript community's overall standard instead of working with it.

**Is Meteor's packaging system made so that beginners can get started quickly?** It's obvious that adding packages to a Meteor app and having things exposed in global scope makes it easy for novices to just start writing code (perhaps spaghetti code). This problem can be solved by simply telling people to make two entry points, one for server, one for client, and for common code to be put in a third place to be imported by either of the two sides. The tutorial can briefly explain how to import and export things from modules.

**Is Meteor's packaging system designed to hook people into the Meteor ecosystem?** Building packages strictly for Atmosphere means that the those packages can't easily be used elsewhere. This might be good because it means people will be dedicated to their Meteor-only packages and more likely to stay in the Meteor community! But! It might also mean that some people simply won't jump into the ship!

**Comment by trusktr** [comment]
### Alright, so here's the basic premise:

Files can be modular using CommonJS, AMD, or ES6 Modules. If a package doesn't interact with Meteor APIs (Famo.us or jQuery for example) then there's no need for it to exist on Atmosphere, it can be on npmjs.org. If a package *does* use Meteor APIs then it should be on Atmosphere, be able to depend on npm packages (already works for server-side), but its should also be modular (CJS, AMD, or ES6). Every application and every package on Atmosphere should have a way to specify dependencies from npm (for both server *and* client). In the entry-level case, a user would have two entry points, one for client and one for server, and the build system would build a bundle from each entrypoint.

### And here's a rough idea of how it might work:

Meteor (or a Meteor package) might adopt webpack (or similar) and expose an API that allows other packages to use the API to specify dependencies. The implementation might read a `.webpack.config.js` file that a user would optionally create and that the implementation would use to recursively override/extend properties in the implementation's very own `webpack.config.js`. By default the implementation's `webpack.config.js` would have some sane defaults (it might include the `babel` and `style!css` loaders, etc, out of the box).

**Comment by trusktr** [comment]
I haven't read all of the isobuild code yet, but I see that every file already runs in a function scope on the global object. It might be possible to skip the whole webpack idea and just add CJS support directly to these functions (and eventually move to ES6 Modules), then just turn off the whole directory/alphabetical loading mechanism (or keep it for compatibility, but ignore it for files that are detected to be using CJS or ES6).

**Comment by trusktr** [comment]
After further investigation, it looks like using `Package.registerBuildPlugin` might be the way to go.

**Comment by benjamn** [comment]
Supporting ES6 modules is something I'm currently working on! It will most likely work by using Babel to compile `import` and `export` to CommonJS `require` and `exports`. I'm open to using something like WebPack to implement the CommonJS module system, though I haven't yet decided against implementing a simpler, more Meteor-specific module system instead. Your thoughts on the matter are very helpful!

**Comment by trusktr** [comment]
@benjamn Hey, that's cool! I'm working on Meteor package that is using webpack behind the scenes to create bundles. It's still WIP. I was hoping to release to Atmosphere this week: https://github.com/trusktr/rocket-module

The idea is that it will allow Meteor packages to import anything from npmjs. In your package that depends on this package you'd use `api.addFiles` to add entry points that webpack compiles into bundles and runs them in Meteor just like any other files, and the bundles can use Meteor APIs since those are loaded first.

What I'm working right now is detecting all packages that depend on my package in a given application, then using Webpack's code-splitting feature to so that libraries common to multiple Meteor packages would be compiled into a separate bundle.

Do you have a link to what you're working on? Maybe we can collaborate on this?

**Comment by trusktr** [comment]
@benjamn To test it out run this Meteor app where rocket-module is a locally installed and two other local packages depend on it: https://github.com/trusktr/meteor-with-webpack

**Comment by jantimon** [comment]
Wow this idea is amazing - bringing webpack and meteor together is in my opinion way better than just adding ES6 to meteor.  
The main advantage is that webpack focuses on a really fast build process and supports CommonJS, AMD, ES6, typescript, flowcheck, sass, less and many template languages.
Is there any progress on your module @tusktr?

**Comment by trusktr** [comment]
@jantimon I'm aiming for the initial release, v1.0.0, to come out soon, maybe in 1 to 3 weeks. This is all I'm working on until it's released. :smiley:

**Comment by vjau** [comment]
My two cents : i am using Typescript to develop with Meteor, and actually it doesn't play well with Meteor because of scope problems : file level globals in Meteor are package/app based where Typescript convert every variable/function/class to a `var foo` local.
However Typescript is able to generate standard based ES6 modules, and i think this could mean the end of the problems for us Meteor in Typescript developers.
There as been some tentatives like universe:modules to load ES6 modules in Meteor but my experience has been that it doesn't play well with meteor packages and typescript. The special syntax used to import code from meteor packages in ES6 modules confuses the typescript compiler which is not aware of this special syntax and can only understand standards based syntax. 
So i think there should be some brainstorming (perhaps @benjamn has ideas already) about a way to fold meteor packages in ES6 modules while staying standard compliant.

**Comment by trusktr** [comment]
@vjau I plan to release my package [`rocket:module`](https://forums.meteor.com/t/4620) before the end of the month. I'm hoping to give a lightning talk about it at DevShop.

> There has been some tentatives like universe:modules to load ES6 modules in Meteor but my experience has been that it doesn't play well with meteor packages and typescript

To play well with packages is the main goal of `rocket:module`. `rocket:module` shares dependencies and common modules across packages of a given app via code splitting.

**Comment by zimt28** [comment]
@trusktr DevShop talk would be nice. Maybe you could then add a comparison with `universe:modules`.
@benjamn Still working on this? It's been three months now :)

**Comment by trusktr** [comment]
@zimt28 I meant to talk this last DevShop, but one of the girls coordinating didn't know I was there. SHe knows for next time now, and by then we should have v1.0.0 released! x)

**Comment by trusktr** [comment]
@zimt28 I can tell you the different right now:

#### `universe:modules`:
- Lets you import files and npm dependencies within a package.
- Supports JSX and the latest language features via Babel.
- Is basically equivalent to cosmos:browserify, but using SystemJS instead of Browserify to create bundles.
#### `rocket:module`:
- Lets you import files and npm dependencies within a package.
- Supports JSX and the latest language features via Babel.
- Shares common modules from files and NPM dependencies across all the packages in an application, reducing duplicate code (in contrast, Meteor duplicates NPM dependencies across packages). `rocket:module` is using Webpack's code-splitting feature to minimize duplicate modules. For example, if Meteor packages A, B, and C all want to use `async@^1.0.0` from NPM, then your app will only contain a single copy of async, shared with all three Meteor packages.
- Loads CSS and GLSL files, with planned support for coffeescript, typescript, less, sass, and stylus.
- v1.0.0 will let you import files from any other package.
- v1.0.0 will have caching for fast rebuilds, using Webpack's cache feature.
- v1.0.0 will handle source maps.

**Comment by trusktr** [comment]
By the way! The implication of the third bullet point

> shares common modules from NPM dependencies (and your local files) across all the Meteor packages in an application

is that we no longer need to write wrapper packages for Meteor. Packages just need to use `rocket:module` to get their NPM dependencies, and `rocket:module` will try to minimize duplicate modules across all the packages of your app. We should have to make Package.

By using `rocket:module`, we can remove pollution from the Atmosphere.

**Comment by dandv** [comment]
> we no longer need to write wrapper packages for NPM packages that we want to use in Meteor

Woot! CC @splendido re. [Aurora](https://autopublish.meteor.com/).

**Comment by jantimon** [comment]
"Note that Meteor's load order rules don't apply to any files that you've imported or required from any other file. In this case, the order is defined by you, and loading starts from your entrypoint files. Imported or required files are completely ignored by Meteor's load order mechanism."

@trusktr this sounds amazing!

**Comment by MacRusher** [comment]
Disclaimer: I'm author of [universe:modules](https://github.com/vazco/universe-modules)

There was some questions about comparing `universe:modules` with `rocket:module`.

While both packages are introducing modules to Meteor, philosophy and used technology are quite different.

`rocket:module` is based on Webpack, with all pros and cons of it. @trusktr explained it very well what his solution has to offer :)

`universe:modules` on the other hand are using Babel and [SystemJS](https://github.com/systemjs/systemjs) (ES6 Module Loader Polyfill) to be as ES2015 spec compliant as possible.
Our goal is to write modular code in Meteor today. In the future when MDG introduces own ES2015 modules implementation we will try to provide painless migration path.
We are also trying to embrace Isobuild instead of replacing it.

Few other goodies:
- You also don't have to worry so much about file loading order.
- Full support for React and other Babel modules.
- We will add support for lazy loading modules on the client instead of bundling them with main Meteor app.
- Any non-standard spec is based on Meteor as much as possible (e.g. best practices from packages like less - file names, syntax for importing from packages)
- Loading packages from other ecosystems (e.g. npm) is IMHO different responsibility. But we could use [jspm](http://jspm.io/) for it, that itself is based on SystemJS.

PS. We're using modules internally to build bigger project called [Universe](http://unicms.io) - we will be releasing soon some packages that will allow to build apps on top of Meteor and React

**Comment by rclai** [comment]
Migration to a module system is going to be a huge change. I think a core package (called `modules` or something like that) should be made to make a Meteor app function via modules, otherwise it should function the way it does now in order to keep simplicity.

The ideas I like about `universe:modules` and `rocket:module` are being able to import from within your app as well as from packages via `import Module from '{package-author:package}'`, the importing of modules isomorphically with the optional `@client/@server` suffix, and the handling of `*.entry.js` files on both server and client side or both.

**Comment by mquandalle** [comment]
@benjamn Could you please share your progress on this with the community?

**Comment by mquandalle** [comment]
Yay, Ben published its work in progress — https://github.com/meteor/meteor/pull/5475

**Comment by Sanjo** [comment]
Can we close this issue because the module system was shipped with Meteor 1.3?

**Comment by benjamn** [comment]
I think so!
