### ISSUE TITLE
Hard to discover that collection observes run synchronously, but Tracker autoruns are asynchronous

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4339]
If I use on the client autorun to observe a reactive variable and observe a collection and I modify variable and after it a collection, collection change through observe is propagated first. This surprises quite a bit. It is in some way clear because observes are run synchronously, while reactivity happens on flushes, but it is hard to reason about this and discover it in a larger application where you mix both reactive variables and local collections as another more complex reactive source.

Reproduction: https://github.com/mitar/meteor-issue4339

When run, the output in the web console is:

```
variable value null
collection value undefined
collection observe value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
variable value true
collection value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
```

I would expect that it would be:

```
variable value null
collection value undefined
variable value true
collection value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
collection observe value Object {value: true, _id: "hXrmCZfbaFzSGCAoZ"}
```

In the order autoruns and observes were defined.

**Comment by stubailo** [comment]
My understanding is that code using `Tracker` is not meant to assume when exactly the update will happen, so this is working as expected. If you want a function to be called synchronously when you change a variable, you should call `Tracker.flush` after modifying the variable or call the function directly.

The documentation talks about this right under `Tracker.autorun`:

> A change to a data dependency does not cause an immediate rerun, but rather "invalidates" the computation, causing it to rerun the next time a flush occurs. A flush will occur automatically as soon as the system is idle if there are invalidated computations. You can also use Tracker.flush to cause an immediate flush of all pending reruns.

However, we don't do a great job of documenting that `observe` callbacks run synchronously, so that could be a good place to start.

**Comment by mitar** [comment]
Yea, I do not mind that autoruns are delayed. I mind that observes are before them. :-)

**Comment by hwillson** [comment]
This issue has been moved into the docs repo: meteor/docs#117. Closing here - thanks!
