### ISSUE TITLE
Blaze speed of removing templates

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4352]
Thought I'd isolate a single subissue of #3596. It takes 340ms for one of my templates to be removed from the DOM, which is a noticeable delay for the user. A click handler changes a template reactive var, which causes `foo` to be removed:

```
{{#if reactive_var}}
  {{> foo}}
{{/if}}
```

The bottom of the flame graph is mostly `anonymous function`, `jQuery.event.remove`, `Tracker.computation.stop`, and garbage collection. 

https://dl.dropboxusercontent.com/u/27134267/remove_timeline
https://dl.dropboxusercontent.com/u/27134267/remove_cpu

Had an error opening timeline on Chrome, but it worked in Chrome Canary.

![image](https://cloud.githubusercontent.com/assets/251288/7549763/5062cd5e-f5f9-11e4-9a3b-09339d9de3f2.png)

![image](https://cloud.githubusercontent.com/assets/251288/7549746/dad0ba8e-f5f7-11e4-988b-01df1e3d68f5.png)

![image](https://cloud.githubusercontent.com/assets/251288/7549765/99e3e65c-f5f9-11e4-8d1f-816536835033.png)

**Comment by glasser** [comment]
Do you have a reproduction?

**Comment by lorensr** [comment]
Closed-source app, but from the callstack it looks like it's all Blaze. Can be re-recorded at parlay.io – click a user's avatar to open their profile overlay, and then record closing it.

**Comment by skosch** [comment]
Same problem here. I'm showing 100 copies of the same template (a simple table row), and the `tearDownElement` takes way too long, because it also involves stopping autoruns ... so that when added up, hiding 100 table rows takes almost a whole second. I'm going to have to rewrite the whole thing in React I'm afraid ...

**Comment by lorensr** [comment]
Have you tried manually removing that subtree from the DOM? Would have the downside that events and computations aren't cleaned up, but should be quick. 

If you do rewrite in React, I'd be interested to hear how long their teardown of the same template takes!

**Comment by lorensr** [comment]
Also could leave it in the DOM and hide with CSS, or use `nrr`, which would save time on computation removal. For more info, see https://medium.com/parlay-engineering/fixing-your-meteor-app-s-render-performance-a727e918511c

**Comment by skosch** [comment]
Thanks for replying so quickly!

CSS hiding won't do the job ... my use case is that I have a list of ~800 items, only some of which are shown in a table depending on what's being typed into the search bar. Filtering the items is fast (and I'm doing it natively; no minimongo `limit`s or `sort`s), but instead of just re-rendering the table, Blaze uselessly tries to `diffArray` everything, which freezes the browser window for ~1s on every keystroke in the search bar.

So someone mentioned elsewhere that this is a bad idea, and I should instead wrap the table in `{{#if}}` (or `{{#unless}}`), hide it during the search, then re-render the whole thing with the new results – all to prevent the costly diffing. However, the teardown process isn't much faster either.

Then again, I could render all 800 items, and CSS-hide those that aren't in the search results. Not sure whether that'd be any faster ... but ... really?

**Comment by lorensr** [comment]
Yes, I'd guess the CSS-hide on the subset of 800 would be faster 😄 But if you do a Timeline JS profile on your first-paragraph scenario, and it looks like most of the time is spent in helpers, then moving the helpers to ReactiveVars should be a big help – see #4960

**Comment by skosch** [comment]
Oh, I was already doing that. Typing in the search bar re-sets a ReactiveVar to the filtered set of items, and the table rows loop through that ReactiveVar; the helper is only called once.

Do you have any experience with `timbrandin:blaze-react`? I wonder whether that might be a plug-in solution. This is a very old project I don't care much for, but users are complaining (rightly), and I really would love a quick fix :)

**Comment by lorensr** [comment]
Sorry, I meant changing any helpers on the row template to ReactiveVars –
it's a weird technique.

Haven't tried it, but heard good things.

**Comment by skosch** [comment]
I've removed all helpers from the row templates now, all data is passed in through the parent's data context. Still, both the removal of the old templates and the insertion of the new ones (via `doMaterialize` and descendants) takes around 1.5 s, for fewer than a hundred simple table rows. The CSS hiding doesn't help either.

I suspect there isn't really a solution to this. The underlying problem is that there's a ton of reactive data in those rows (that's the whole point of the application); if Meteor templates had `shouldTemplateUpdate` then it wouldn't have to constantly set up and tear down autoruns all over the place. Because I'm filtering *and* re-sorting, Blaze doesn't really know how to avoid this busywork either.

This is where React + ImmutableJS/Redux would really shine ... sigh. I suppose a rewrite is in order.

**Comment by mitar** [comment]
> Filtering the items is fast (and I'm doing it natively)

What do you mean doing it natively? Server-side MongoDB? Which you then publish?

From my experience in fact the issue is not with Blaze but DDP processing. We are improving some of those issues [with this pull request](https://github.com/meteor/meteor/pull/5680). So in fact it is not Blaze which is slow, but the fact that every change is done one by one.

**Comment by skosch** [comment]
No, the data is already on the client, and I'm manipulating purely what parts of it are displayed. By natively I mean I run `map`, `filter` and `sort` on the array instead of using Minimongo to do those things.

**Comment by mitar** [comment]
> By natively I mean I run map, filter and sort on the array instead of using Minimongo to do those things.

Do your documents have `_id`? Because otherwise Meteor do have to do diff? Or in general it might be even slower then using Minimongo for filtering?

**Comment by skosch** [comment]
They do have an `_id`. The filtering/sorting is just as fast as one would expect (it's just a few hundred items). The problem, as described above, is the teardown and setup of all the autoruns responsible for the reactive values *within* those list item templates. At least that's what I gather from looking at the profiling charts in the browser.
