### ISSUE TITLE
Dojo Toolkit with Meteor

### ISSUE THREAD

**Issue by r2d2Proton** [meteor/meteor#4354]
I have a few issues with Dojo(1.10.4) / Meteor(1.1.0.2). I'm using several templates, each wrapping various Dojo controls. The templates switching is managed similar to the way panels are. The problems are:

1. Not getting events from Dojo widgets but from the 'body' template. For example, the following contol is in a template:
    <button class="btn-createAccount" data-dojo-type="dijit/form/Button">create</button>

The problem is I do not see the event under the Template.name.events({}) codeblock but rather under the Template.body.events() codeblock. Also, modal dialogs seem to have the same problem.

2. The first time Dojo parses the template it renders perfectly. However, subsequent renders of the template are messed up. Basically, start at the first template and it renders fine. Switch to another template and it renders fine. When switching back to the original template it is incorrect.

3. possibly the underlying problem. . .Google Chrome is throwing a 'DOMException: Failed to execute 'querySelectorAll' on 'Element': '*;x' is not a valid selector'

Can anyone provide insight into these problems? Your help will be appreciated.

Thanks,
Jerry

**Comment by Slava** [comment]
The Meteor Core team doesn't have any expertise on how Dojo Toolkit works. If you find a smaller bug reproduction in terms of DOM manipulations using browser API or jQuery - we will look at it. Otherwise, questions like these are best asked on SO and forums.

"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!
