### ISSUE TITLE
Npm.depends support for non-absolute versions.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4355]
Why does `Npm.depends` not support symbols like `^` and `~` for package versions? Does absolute versioning outweigh the relative versioning for some reason?

**Comment by stubailo** [comment]
Right now, a single version of that NPM module is compiled into the Meteor package when it is published. It doesn't really make sense to allow non-absolute versions because users of the package would still always get the exact same version.

This would make sense for app-level dependencies, but we don't have those right now.

**Comment by glasser** [comment]
Specifically, a goal of `Npm.depends` is reproducible builds.

**Comment by trusktr** [comment]
@glasser 

> reproducible builds

That sounds good ideally. What happens when an app has two package installed, A and B, where A `Npm.depends('foo@1.2.3')` and B `Npm.depends('foo@1.2.4')`? Will the app as a whole now have both versions of `foo` in it?

**Comment by stubailo** [comment]
Ideally in the case of a singleton, there would be one Meteor package that includes the Npm dependency once, and then all of the other packages use that Meteor package.

**Comment by trusktr** [comment]
@stubailo True, but that's not enforceable. Any package can blatantly `Npm.depend` on things, not all packages will follow the use-the-most-popular-package-wrapper-for-foo-library pattern.
