### ISSUE TITLE
Password hashing on client side is insecure

### ISSUE THREAD

**Issue by tysonclugg** [meteor/meteor#4363]
In the accounts-password package, passwords are hashed on the client side without a salt and then sent hashed but not using encryption.  Attackers who can see the traffic can easily do a web search for the hashed password and is likely to retrieve the password plain text from any of the rainbow tables that Google has indexed.  Attackers with the hash can also use the hash in place to authenticate without knowing the plain text (ie: replay attack).  Attackers may also mount a MITM attack and serve malicious code to retrieve the plain text password as well.

Stop relying on hashing to obfuscate common passwords - go back to plain text passwords in DDP messages and force the use of encryption instead.  Yes you will need to have certificates configured and the barrier to entry will be increased, but at least you won't be leaving everyone vulnerable to poor security practices.

Continued use of hashed passwords only serves to provide a false sense of security, and does little to protect user accounts from being compromised.

Passing this off as a dev-ops issue doesn't serve the Meteor community, though it's true that for deployment this is indeed a dev-ops issue.  Make it easy for developers to do the right thing, make it possible for dev-ops to handle encryption using other layers in the deployment stack.

**Comment by introrse** [comment]
Ouch!  I (falsely) thought Meteor was using SRP.  I'm really disappointed Meteor apps now rely solely on SSL for any password security, and doubly disappointed the switch doesn't seem to have been announced with the same fanfare the addition of SRP support got.   Particularly with growing exploitation of SSL's PKI problems this seems like a bad choice.  

(FWIW, I found some discussion of the topic archived here:  
https://meteor.hackpad.com/SRP-bcrypt-J5mdBojeVfe )

**Comment by introrse** [comment]
The meteor-core thread referenced in the hackpad discussion above is this, BTW:
https://groups.google.com/forum/#!searchin/meteor-core/srp/meteor-core/dDD_u6mN4LA/6-hYd4ynfOUJ

Replacing SRP with bcrypt still seems like a tradeoff I wouldn't have made.  Perhaps I'm missing some piece of the threat model. Still, it makes my current goal of not serving Meteor app code to the user or enabling DDP connectivity until after the user is authenticated somewhat easier.

**Comment by glasser** [comment]
We stand by Emily's analysis from the thread https://groups.google.com/forum/#!searchin/meteor-core/srp/meteor-core/dDD_u6mN4LA/6-hYd4ynfOUJ.  I agree that with you (and her) that encryption (ie SSL) needs to be used in conjunction with `accounts-password`, and that the SHA256 step doesn't add very much.

**Comment by tysonclugg** [comment]
Thank you @glasser - sounds like I'm preaching to the converted.  Has someone formulated a plan on how to use SSL/TLS by default, or has that not started yet?

**Comment by JulianNorton** [comment]
I just want to clarify, this post: http://info.meteor.com/blog/meteor-082 does NOT address this issue, correct?

**Comment by tysonclugg** [comment]
First, a couple of points need to be clarified:

1. @introrse: The side issue of bcrypt vs SRP is NOT the subject of this ticket.  Switching to a more secure algorithm is security theatre, as the code delivery method is still vulnerable such that the password hashing can be supplanted in any man-in-the-middle attack.  Stop the security theatrics already and accept that plaintext passwords delivered inside a trusted, encrypted connection are far more secure than any password submitted to code that cannot be verified (ie: JavaScript delivered without SSL/TLS).

2. @JulianNorton: Indeed http://info.meteor.com/blog/meteor-082 does not address this issue.

This issue is really that TLS (commonly known as SSL) should be on by default, and that NO amount of "secure password hashing" done by the client can protect passwords if the JavaScript delivery channel cannot be trusted.

The purpose of hashing is generally to rate limit offline attacks should the database be compromised.  If the encrypted connection between the browser and server is compromised then password handling code can be replaced, so hashing within a secure connection serves no useful purpose.

Pre-calculating bcrypt hashes on the client and submitting the hash means the server has no work factor to verify passwords, so no natural rate limiting occurs.  This means the password verifier will happily answer as password "queries" as fast as the IO subsystem can keep up, instead of forcing expensive computational work to be done.  Also if the client calculated hash is used as input to another round of hashing the key space is *reduced* as hash collisions occur.

On compatibility (the reason I visited the Meteor password hashing code in the first place), upgrading to new hashing algorithms (which MUST be done from time to time) is much easier if the plaintext password is passed to the server, and transparent to the client as no new API is required to handle the case of upgrading from an old hash to a new hash.  The generally accepted means of storing hashes is "<algorithm>$<data>" such as "pbkdf2_sha256$15000$ZLpQISRxzhY0$fxrQcKxhkG//nHg10NrkulhvWkAqWbWeQg4QeD7c59E="
This is a PBKDF2 hash for the password "pass" which includes the number of rounds, the salt and the resultant hash ready to be verified and upgraded if required, for example by increasing the number of rounds from 150000 to 250000, or ready to be swapped to a different algorithm altogether (eg: pbkdf2_sha512).

@glasser, it's been 4 weeks since I opened this ticket.  Shall I write up a plan for using SSL by default in Meteor, or can you point me to where the plan is?  Is there a branch in the git repo for required changes?  Do we need to fork and pick up work elsewhere?

**Comment by xanatas** [comment]
Thanks for the explenation
My dev say there is no salt used on meteor-acounts so this might be an attack vector?

1- Login to the application 
2 - Intercept the request (by faulty ssl?)
3- Observe the SHA 256 Hash digest 
4- Now use any online SHA 256 decoder and found the cracked hash

**Comment by danielflippance** [comment]
"no salt used on meteor-acounts" "hashed on the client side without a salt" - Can anyone comment on if that is still the case (Dec 2015)? Is there any plan to add the ability to use a custom salt defined by the application and/or the ability to hash the password on the server side?

**Comment by glasser** [comment]
@danielflippance Passwords are salted as part of bcrypt, on the server side.  It's just that the thing which is salted is `SHA256(password)`, not the password itself.

**Comment by danielflippance** [comment]
Great, thanks @glasser

**Comment by tysonclugg** [comment]
Now that [Let's Encrypt](https://letsencrypt.org/) is in public beta, can we integrate [node-letsencrypt](https://www.npmjs.com/package/node-letsencrypt) into `meteor create` so the user is stepped through the SSL cert creation and `force-ssl` can be enabled by default?

Updates to the Meteor Guide as per https://github.com/meteor/guide/issues/148 are a step in the right direction, but SSL by default is the only real solution.

**Comment by dhrubins** [comment]
Not to rehash (sorry) old memories from a couple years ago, but we're still hashing without salt in the client which makes replay attacks somewhat of a concern. As previously discussed, hashing is only marginally better than sending plaintext passwords with respect to MITM attacks. Yes, everyone should have a healthy dose of TLS, but _**TLS alone is not sufficient**_, so the issue still stands. IF I can watch your traffic (obviously, that is a big IF with TLS), I can observe a login message, get the SHA256 hash of your password, and login as you.

Now, MITM'ing this would be difficult (maybe impossible?) without compromising TLS, so it's easy to think of this as an edge case for most folks. But, I would also argue that most people out there aren't using HPKP and a DNS CAA record, so there is still a reasonable path that allows a motivated attacker to screw with your TLS integrity and have a productive attack.

Here's how: an attacker runs mitmproxy on a public wifi network at a coffeeshop and sees that your user is interacting with your trusty Meteor server (people, always use a good VPN on public wifi!!!). Then, since you probably didn't pin your keys (only 0.09% do, but it's a good idea), the attacker can proxy your app and even provide TLS using their own cert (likely generated with Let's Encrypt since you don't have a CAA DNS record that whitelists the CA's you use). The attacker waits for the next time that your user has to log in, which they could probably force. When your user is logging back in, the attacker observes the connection through the proxy and grabs their SHA256 hash from the websocket traffic. **Boom**, they own your user's credentials and can probably find out their password from a rainbow table of SHA256 hashes. This makes for _A Very Bad Day_ for your user. Also, unless you have [Certificate Transparency notifications](https://developers.facebook.com/tools/ct/), you would probably never know the attacker issued a cert for your domain. So, relying on TLS is not sufficient.

With that dreadful scenario in mind, I am happy to put some work into this to help us all avoid the problem. Here is what I think: Rather than just salting the hash, how about we encrypt and sign the hashed password, while including some connection-specific info so it can't be replayed on a different connection. I'd propose using a simple implementation like ```tweetnacl``` that is quite strong, very fast, and extraordinarily difficult to screw up (we use this extensively in production @LegalRobot and it is sufficiently fast for our needs). Thoughts? Especially interested in comments from @data since this would involve changes to accounts-password internals.

**Comment by klaussner** [comment]
Maybe I'm misunderstanding the attack scenario you described, but would an attacker not be able to bypass the encryption and signing if he already established himself as a MITM? Once the TLS connection is compromised, an attacker can inject code into the website that sends him the plaintext password before it's encrypted.

**Comment by dhrubins** [comment]
@klaussner definitely, there are quite a lot of attack scenarios if you bust TLS. My point was that relying exclusively on TLS to protect the password in transit is probably not enough. I think adding encryption to the mix only addresses the issue of observability. The app could still be vulnerable to script injection - I wonder what other mechanisms we can use to address that? SRI certainly helps for 3rd party scripts. But, I'm not sure adding integrity to the scripts that Meteor loads would help, because an attacker could edit the integrity attribute along with the scripts.

**Comment by tysonclugg** [comment]
@danielflippance closed this after https://github.com/meteor/meteor/issues/4363#issuecomment-164585775 was made.  I think that was premature, since the password sent over the wire is NOT salted.

**Comment by abernix** [comment]
@tysonclugg This feature request is not closed, it's still being discussed.

@dhrubins As you've eluded to yourself, the implementation is still quite secure assuming TLS in place (as it absolutely positively should be in every web application!).

> My point was that relying exclusively on TLS to protect the password in transit is probably not enough.

If we can do more, we should do more!  We'd certainly appreciate your help looking into this if you have the time to spend on it.  Happy to help how we can.  Are you considering breaking changes for `accounts-password`?  Do you think it could be implemented in a backward-compatible manner?  Maybe some initial discussion about the scope of your changes?

**Comment by abernix** [comment]
@tysonclugg in regard to [your comment here](https://github.com/meteor/meteor/issues/4363#issuecomment-165418163) about using LetsEncrypt during `meteor create`, how would that work since the host in development is `localhost`?  You can't generate certificates for `localhost` (or anything which LetsEncrypt can't access).  We strongly recommend users use SSL in production, but having it on by default, in development is problematic.  Open to suggestions here if you have any ideas.

**Comment by dhrubins** [comment]
@abernix yep, I totally agree. Just in case anyone reading this is concerned: **_nothing_ about this issue suggests Meteor is insecure today** - just that most TLS implementations are not perfect and those imperfections can be exploited against _any_ application framework. I actually wouldn't even consider this a security vulnerability (which is why I'm posting publicly, rather than emailing the security team). Unfortunately, we live in a world where TLS is poorly implemented on most sites, and on top of it, there are some well-documented cases of CA's being compromised (DigiNotar) or wrongly issuing certificates (ahem... Symantec). We clearly can't rely on the CA's to be the internet's immune system. So, as developers, we can provide better security for our users by doing things like pinning keys, using CAA records, and examining Certificate Transparency records. But, we can also work on protecting our applications from threats if we assume a separate, fairly serious, compromise like busting TLS.

I don't think this would be a breaking change, and I also don't think we would need the kind of upgrade path that we did from srp to bcrypt. That aside, I think we should migrate toward scrypt, as suggested in #4272, and _that_ would likely require an upgrade path. One thing at a time though. 

For this change, I would propose first adding a new option to Accounts.config to allow people to opt-in to the feature, maybe call it ```encryptPasswordInTransit```. There will be some encoding steps between different formats like UTF8, UInt8Array, and base64 that I've left out.
1. (both) If this option was set, we would start the connection by generating keys (just takes about 1.1ms in my browser with ```tweetnacl```'s ```nacl.box.keyPair()```, plus transit time). This could be done lazily and the respective public keys added to the connection object. Or, we could do this at the time of login so we don't add overhead to each new connection.
1. (client) Start Accounts.loginWithPassword by putting the hashed password in a ```nacl.box```, which encrypts and authenticates the message using the server's public key, the client's secret key, and a new nonce. So, right around line 43 of packages/accounts-password/password_client.js, we send an object with the base64 encoded box and nonce rather than the naked SHA256 hash.
1. (server) Open the box using ```nacl.box.open```, which authenticates and decrypts the box with the client's public key, the server's secret key, and the given nonce. Then we just use the contents as usual with bcrypt (or srp, or perhaps even scrypt someday).

All of this, unfortunately, still doesn't address the attack vector. If the intermediary owns the connection and can edit the server's public key before it reaches the client, the intermediary can use their own keypair in place on either side. Not good. So, the server's public key should be signed using ```nacl.sign``` with a signing key (```nacl.sign.keyPair()```) that was stored in ```ServiceConfiguration```. The public half of the signing key(s) would be kept in the client's localStorage for verification before submitting the user's data. That way the client can verify it is encrypting with the real server's key. This gives us trust-on-first-use (TOFU), similar to HPKP. Like HPKP, we would want several keys and some ability to rotate them. To close the loop, we would include the server's public signing key that was presented to the client in the ```nacl.box``` for verification. I haven't fully worked through this part yet, but that's the direction I'm going.

Of course, I'm just one guy on the internet and I could have missed something. This is why we do things like this in public, so people can comment.

**Comment by tysonclugg** [comment]
@abernix [commented](https://github.com/meteor/meteor/issues/4363#issuecomment-290683213):
> @tysonclugg This feature request is not closed, it's still being discussed.

Indeed, my apologies.

@abernix [commented](https://github.com/meteor/meteor/issues/4363#issuecomment-290684064):
> @tysonclugg in regard to your comment here about using LetsEncrypt during meteor create, how would that work since the host in development is localhost?

One possible path:
LetsEncrypt supports DNS challege/response, so it is viable to have `dev.example.com` resolve as `127.0.0.1` and have a signed cert for that.  Indeed, that's what I'm doing using https://github.com/certbot/certbot with the https://github.com/lifeonmarspt/certbot-route53 plugin since our domain is hosted via AWS::Route53.  There are other plugins available for different DNS providers.

There are likely other paths that can be used to have local developers use signed certificates, and there is always the possibility of falling back to self-signed certs for developers who are unable to use an automated solution.

@dhrubins [commented](https://github.com/meteor/meteor/issues/4363#issuecomment-110330580):
> That aside, I think we should migrate toward scrypt, as suggested in #4272, and that would likely require an upgrade path. One thing at a time though.
...
> Of course, I'm just some guy on the internet and I could have missed something.

Yep, you missed [this](https://github.com/meteor/meteor/issues/4363#issuecomment-110330580):
> This issue is really that TLS (commonly known as SSL) should be on by default, and that NO amount of "secure password hashing" done by the client can protect passwords if the JavaScript delivery channel cannot be trusted.

If you want to migrate to some other password challenge/response system, take that up in separate issue.  Without TLS, it is impossible to guard against MITM attacks and as such, changing the password hashing scheme achieves NOTHING to avoid the more serious problems presented in this issue.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Password%20hashing%20on%20client%20side%20is%20insecure&body=Migrated%20from:%20meteor/meteor%234363) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by JulianNorton** [comment]
https://github.com/meteor/meteor-feature-requests/issues/44
