### ISSUE TITLE
Source maps for Production

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#4384]
Hey,

It seems `meteor build` (without --debug) (and `bundle` neither) builds source maps. Is it planned to work like this? I have error reporting system (rollbar) on frontend that uses stack traces and can work with .map 's, so it would be very cool to know in details about errors that customers have. Minimized stack traces doesn't make much sense.

**Comment by Firfi** [comment]
To be clear, I'm not about to serve .map s to users, but it'll rather be server to error reporting system after error occures and it seeks for correct line of code in original 'minified' stack.

**Comment by Slava** [comment]
Hey @Firfi, I think it is a valid feature to have in the build system. As you might have noticed already, minifiers are hardcoded in the build tool, thus changing its behavior (such as exporting sourcemaps) is not easy w/o changing the core.

We have an ongoing project on the `batch-plugins` branch that aims to address a lot of issues, including this one. Hopefully, after the work is done, it will be easy to configure any minifier to output the source maps (as well as set other options).

**Comment by DavidReinberger** [comment]
Bump, any news/solution on this? I'm using the same app (rollbar) as @Firfi, and it would be awesome to have sourcemaps.

**Comment by abernix** [comment]
Please +1 the original issue as a vote of interest!  Features are managed according to [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).

**Comment by wallslide** [comment]
I was going to make a new issue for this, when I found this one instead... so I'll paste what I wrote below:

**Outline of problem**
We want to be able to pinpoint in-production errors occurring on our users' browsers. Currently, the in-browser error reports returned by services such as Kadira or Raygun are very difficult to utilize.

The reason for this is because the source code is minified, and thus we cannot tell what file/line-number exceptions are occurring at based on the captured stacktraces. 

**Solution**
If we could get access to sourcemaps for the minified and deployed production code, we can upload those sourcemaps to these error reporting services, and get meaningful error reports.

**Reference**
Here is an example of the feature in Raygun's Crash Reporting suite that allows us to upload sourcemaps to decipher stacktraces:
![image](https://cloud.githubusercontent.com/assets/917069/18422838/6c6d453c-78da-11e6-8ca4-eaa04b67a3b5.png)

Here are links to the meteor forums where people have requested this feature:

- https://forums.meteor.com/t/sourcemaps-in-production/22982
- https://forums.meteor.com/t/create-sourcemaps-on-build-time-to-upload-to-errortracker/23655

**Additional Information**
We are currently using Galaxy for our Meteor hosting. Our app is on release `1.4.1`

**Comment by aknock** [comment]
:+1:

**Comment by tophsic** [comment]
:+1:

**Comment by gregory** [comment]
ping @Slava

**Comment by cfnelson** [comment]
👍

**Comment by mitar** [comment]
BTW, this is the fifth most upvoted issue for Meteor.

**Comment by chrisoquinn1** [comment]
I've written a build plugin to customize the minification in our meteor proj.
It creates the source maps in production mode (e.g. --production flag) but they look to be mal-formed.
e.g.  prefix in map file => )]}\'\n'; among other missing braces and such like.
The map isn't a proper json.
Since they are corrupted I can't properly use npm source-map to find original positions.
My stack mapping code works for dev mode though.

this is a snippet from the minify portion of my plugin..

 file.addJavaScript({
                    data: this.uglify(file.getContentsAsString(), minifyOptions).code,
                    path: file.getPathInBundle(),
                    sourceMap: file.getSourceMap()
                });

Creates the app.js.map (source map) but it's mal-formed. Any way to create the sourcemap properly?

**Comment by chrisoquinn1** [comment]
It turns out that if you remove the prefix the json map looks to be okay but npm sourcemap consumer doesn't find original positions still.

**Comment by hexsprite** [comment]
Hey guys, I really need this or need to look at using a different build system than Meteor for apps. I can't be trying to debug errors blind. `TypeError: l is not a constructor` just doesn't cut it.

Can someone who understands the build system explain what needs to be done? Maybe there are people in the community who will take up the torch. I know that I would be willing to put in a bit of time if I can get a overview of where to start.

**Comment by sdarnell** [comment]
Another benefit of being able to produce sourcemaps is that we'd be able to run [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) to analyse the size of the bundle. Currently it's just a big blob, and I'm not sure the development sizes are representative enough.

**Comment by s-devaney** [comment]
How is anybody supposed to debug production issues effectively without this?

**Comment by s-devaney** [comment]
With nothing on the immediate horizon RE: production source maps I spend some time to figure out how I could make production -> development mapping a little bit easier. The immediate problem I was trying to solve was: I have a number of identical logging statements in my application (i.e. for generic errors, etc) and there was no easy way to see which part of my application was throwing them in production (because of no source maps).

I created a Meteor build plugin to automatically replace an arbitrary string (`__LINE__` or `__FILE__`) with the file name and line number of the source file at compile time. I use this directly in my logging statements, but you could use it anywhere in your application.

This is obviously not a fix for a lack of production source maps, you can't even call it a workaround, but it will make my life a little bit easier.

If anybody is interested I'm happy to share the package.

**Comment by ffxsam** [comment]
This is still an issue. I sometimes get errors that I can't figure out. I have to grab the minified code from production, edit it in vim, and jump to (for example) line 5 column 13000 and read some very illegible code and try to figure out what's going on.

@abernix or @benjamn - any ideas? Services like Rollbar and Sentry support source maps, but they depend on a set source map name and minified URL. Meteor's minified JS file always changes at every build.

**Comment by zodern** [comment]
I created a fork of `minifier-js` and `standard-minifier-js` which creates a production sourcemap in `AppFolder/.production.min.js.map`. It is on GitHub at https://github.com/zodern/minify-js-sourcemaps.

> Meteor's minified JS file always changes at every build.

It might be possible to create a custom buildpack for heroku or scalingo, or create a script that runs after `mup deploy` that would upload the sourcemap and get the js filename from the bundle after building the app.

**Comment by zodern** [comment]
Last weekend I released 2.1 that simplified using with Rollbar or other error monitoring services. There were two main changes:
- The js file always has the same file name: `app.js`
- The source map is part of the bundle. You can find it at `programs/web.browser/app.js.map`

The sourcemap now is public, so if you want to prevent users from accessing it, you can add `zodern:hide-production-sourcemaps`.

Yesterday I integrated my app that is deployed to Scalingo to use Rollbar with source maps . There were three steps. This is specifically for Scalingo, but it would be similar for other PaaS or Meteor Up.

1) Add `zodern:standard-minifier-js`.
2) Create a `Procfile` with a `postdeploy` command.
```
web: ./.start-meteor-app
postdeploy: curl https://api.rollbar.com/api/1/deploy/ -F access_token=$ROLLBAR_ACCESS_TOKEN -F environment=$ROLLBAR_ENVIRONMENT -F revision=$CONTAINER_VERSION -F local_username=scalingo && curl https://api.rollbar.com/api/1/sourcemap -F access_token=$ROLLBAR_ACCESS_TOKEN -F version=$CONTAINER_VERSION -F minified_url="$ROOT_URL/app.js" -F source_map=@.app-build/bundle/programs/web.browser/app.js.map
```
3) Find a way to pass the last git commit SHA to the client. Rollbar requires the client to use the same version as when uploading the sourcemap. I use `meteorhacks:inject-initial` for this. On the server my code is:
```
import childProcess from 'child_process';
import { Inject } from 'meteor/meteorhacks:inject-initial';
import { WebApp } from 'meteor/webapp';

const pkg = require('../package.json');

let commitHash = process.env.SOURCE_VERSION || process.env.CONTAINER_VERSION;

try {
  if (!commitHash) {
    commitHash = childProcess.execSync('git rev-parse HEAD').toString().trim();
  }
} catch (e) {
  // not a git repository
}

WebApp.connectHandlers.use((req, res, next) => {
  if (Inject.appUrl(req.url)) {
    Inject.obj(
      'VERSION_DATA',
      {
        version: pkg.version,
        commit: commitHash
      },
      res
    );
  }
  next();
});
```

> Another benefit of being able to produce sourcemaps is that we'd be able to run source-map-explorer to analyse the size of the bundle.

I tried that today, and it only showed the size of packages and files in `*/imports`.

**Comment by billyvg** [comment]
@zodern Will there be any caching issues with changing the bundle name to `app.js`? Can we still request the bundle with a hash?

**Comment by zodern** [comment]
Meteor does add a `hash` query parameter to the url, but in some situations there might still be problems: http://stackoverflow.com/questions/9692665/cache-busting-via-params/20746756#20746756

**Comment by dagatsoin** [comment]
@zodern zodern:standard-minifier is usable on local un Chrome debbuger ? I Have still the minified version and I can see the app structure with the source files. But I can't navigate between them. I mean when an error occurs, Chrome leads me into the minified blob.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Source%20maps%20for%20Production&body=Migrated%20from:%20meteor/meteor%234384) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
