### ISSUE TITLE
Setting/getting objects in ReactiveVar can break reactivity of .set()

### ISSUE THREAD

**Issue by vaughnkoch** [meteor/meteor#4414]
If you store an object in a ReactiveVar and retrieve it with .get, you'll get an object reference back, not a copy of the object. That means that changing the object's members will change the actual object stored in the ReactiveVar even though set hasn't been called. 

If you then pass the changed object to set, it will call the equals function with two references to the same object, which obviously are equal.  Since equals returns true, the result is that set doesn't trigger invalidations either, even though its internal object has changed.

This isn't 'wrong' per se, it's just a Javascript gotcha about passing references. However, it can lead to subtle and pernicious bugs in application code for unsuspecting developers.
Suggestions:
1. Change .get to return a deep clone of the object via EJSON.clone (could be an optional parameter to skip this).
2. Or, update the documentation for ReactiveVar to add a warning about getting and setting objects because of this behavior.

While you're at it, you could add EJSON.equals as the default equals method for objects (again, this can be overridden with a custom equals function).

Here's a sample which shows the behavior:

```
// Create reactive var
var myReactiveVar = ReactiveVar({ 
  foo: 'one' 
}, function (oldObj, newObj) {
  console.log('Inside equals - old:' + oldObj.foo + ', new:' + newObj.foo);
  return EJSON.equals(oldObj, newObj); 
});


// Create reactive computation
Tracker.autorun(function() {
  var myObj = myReactiveVar.get();
  console.log('Inside autorun:', myObj.foo);  // Initially 
});


// Trigger reactive computation with unexpected results
var myEditedObj = myReactiveVar.get();
myEditedObj.foo = 'two';  // Let's edit this object. But it's the same reference under the hood!
myReactiveVar.set(myEditedObj);

var myClonedObj = EJSON.clone(myReactiveVar.get());  // Avoid using the same actual object
myClonedObj.foo = 'three';  // Let's edit this object
myReactiveVar.set(myClonedObj);



/* Output

Inside autorun: one
Inside equals - old:two, new:two  // Huh??
Inside equals - old:two, new:three
Inside autorun: three

*/
```

**Comment by stubailo** [comment]
ReactiveDict actually works the way you said, by deep cloning everything passed into it. However, this means you can't store anything that isn't serializable, like a function or object with a prototype. Do you have an opinion about this tradeoff?

**Comment by vaughnkoch** [comment]
Hi Stubailo, I was vaguely aware of ReactiveDict but haven't tried it yet - thanks for pointing that out.  A few thoughts on RD:

1. The documentation needs to be fleshed out, both in the sparse readme for RD and in the Meteor docs in general.
2. RD doesn't appear to have a 'delete' function, as in, remove a specific key from the dict. (It turns out that that's a use case in my app).

To answer your question - I think there's a use case for both storing purely serializable objects and separately storing objects with JS-only attributes like functions and prototypes. Ideally a developer should have the ability to do both, maybe with a passed-in option. If that behavior is implemented obviously it would have to be well documented so people don't get tripped up.

I think it's ok to have ReactiveVar behave the way it does, as long as it's well documented in the Meteor main docs. I think having an option to automatically clone makes sense though since that's probably the behavior many developers would want to have. It's probably better to separate app behavior (functions, prototypes etc) from the data storage itself.

**Comment by Maxhodges** [comment]
I have some suggestions on ReactiveDict design improvements which I've shared here
https://github.com/meteor/meteor/issues/4100#issuecomment-104796748
curious to hear your thoughts

**Comment by stubailo** [comment]
@vaughnkoch I think I'm going to encode this in an explicit feature request for `delete` on ReactiveDict here: https://github.com/meteor/meteor/issues/4438

**Comment by stubailo** [comment]
Also, your points are pretty valid overall, I think there should be a consistent story about what to do with data in Meteor. It's definitely on our radar as a priority in the near-ish future.

**Comment by vaughnkoch** [comment]
Thanks :) Having a single line in the docs about how objects are stored would have saved me a few hours of debugging..

**Comment by mitar** [comment]
Sorry, but things are not so simple. I think (despite filling numerous issues about this myself, like #3590 and #4073) the current semantic of `ReactiveVar` is pretty reasonable defaults: being pessimistic about equality, and not copying the data over. You cannot use `EJSON.clone` by default because that could be a potentially costly operation, and probably it could never finish if you have circular data structures. And cloning is also possibly costly operation, especially if you clone it no matter what. Not to mention that it is pretty hard to clone circular data structures in JavaScript. Of course you still get surprised (like templates being rerendered, or changing references under the hood #4377).

So, I think those are reasonable defaults. But there is some space for improvement in documentation and easier ways to understand the defaults and make it easier to modify them when needed.

In general many web frameworks are experimenting with different approaches here. React is going in a similar direction where any change triggers rerendering of virtual DOM, hoping that diffing is fast so that this is a better trade-off. Default Blaze does the same, opting for pessimistic (and in most cases correct) approach with default equality of ReactiveVar.

But ReactiveDict is a mess. :-)

Nothing prevents you from implementing your own variables on top of existing Tracker logic. I have done that in the past (for example, for arrays).

**Comment by DanielDornhardt** [comment]
Damn, I just got bitten by this - I wanted to watch an array of values, and to update it i was getting the array and pushing or removing data on it, and then setting it again as new value for the Reactive Dict.

I kept wondering why the reactivity didn't always trigger... darnit. These things cost a lot of time... maybe this could at least be mentioned more strongly in the docs?

I did this:

    let stepsCompleted = t.stepsCompleted.get()
    if (valid) {
        stepsCompleted.push(currentIndex);
    }
    t.stepsCompleted.set(stepsCompleted);

Nothing ever happened O_o :)

**Comment by Andrew1431** [comment]
@vaughnkoch mannnnn I spent 3 hours trying to figure this bug out on something I've written multiple times before in less than 10 minutes, but in this situation I was `delete`ing a key on an object I got from a reactiv var thinking that was safe to do. Then I googled "Strange reactive var behaviours" and this came up. Fixed the problem in seconds (`_.clone`) 

THANK YOU! lol

**Comment by DanielDornhardt** [comment]
Yeah, this one can really cost some hours and nerves. Maybe something to write in the reactive var docs in *BIG BOLD LETTERS* to make sure people keep it in mind while developing?

Also, careful, _.clone is a shallow clone, if you're changing an array or sub-object inside of your cloned object you'll run into the same effects...

**Comment by Andrew1431** [comment]
Yep thanks :) just needed the shallow clone.

**Comment by hwillson** [comment]
Based on the discussion here it sounds like the current `ReactiveVar` implementation is okay, but there are a few additional caveats that should be documented. If anyone here is interested in opening a new issue over in the http://github.com/meteor/docs repo (or better yet submitting a PR), that would be great! Since there isn't a bug here however, I'll close this for now. Thanks!
