### ISSUE TITLE
Add script tag inside body tag

### ISSUE THREAD

**Issue by ehallstr** [meteor/meteor#4415]
I tried to use an external javascript library, and had some problems. After quite a bit of searching I found this SO question: 

http://stackoverflow.com/questions/14389766/meteor-js-use-external-script

I feel it's wierd that you can't add a script tag inside a body tag after the contents. I know that the body is treated as a template, not a tag in the normal sense. But still, it would be nice if after first time the body templated is rendered, all containing script tags could be extracted and executed, so much simpler to test stuff! It should have the same standard behaviour for all templates I think.  Also adding script tag in the root html, outside of head is not working, why is that?

**Comment by dgreensp** [comment]
As background, putting `<script>alert("FOO")</script>` in the `<body>` works, so our intent, to the extent we thought it through, was for script tags to be acted on in templates.  Script tags in templates are created with `document.createElement`, so in theory they should just work as if you inserted programmatically yourself (which should result in the script being fetched and executed).  We have a separate code path for turning HTML strings into DOM, which is used for example in the case of triple-stache (`{{{ }}}`) tags, which goes through jQuery, which strips script tags of their power.  When we realized this, we decided not to change it, because it seems like a security feature if anything.

After looking into it, two things are happening here, both unintentional.  If the script tag is static (with no template tags), it gets optimized to a string, which uses the second code path I mentioned.  In any case, however, we incorrectly treat the script tag as an SVG element (because it's on our list of SVG elements...) and create it with `document.createElementNS`, which seems to also strip it of its power.

I think we can fix both of these things pretty easily.

**Comment by ehallstr** [comment]
Thanks for you reply David, I just saw that this had been fixed, and that you now can add the script tag in a template in the last version.

However adding script outside a body or a template tag throws an error as you said.  

http://meteorpad.com/pad/Kf42XzzMxrWQdec7r/Copy%20of%20Leaderboard

**Comment by glasser** [comment]
@ehallstr Sure, that's just not the syntax of our Spacebars `.html` files, which consist of `<template>`, `<head>`, and `<body>` sections.

https://github.com/meteor/meteor/blob/832e6fe44f3635cae060415d6150c0105f2bf0f6/packages/spacebars/README.md#top-level-elements-in-a-html-file
