### ISSUE TITLE
Meteor on Arm Linux

### ISSUE THREAD

**Issue by giacecco** [meteor/meteor#442]
Dear Meteor team,
Do you have any plans to port Meteor to Arm Linux, e.g. Raspbian “wheezy” running on Raspberry Pis? If so, and you need a beta tester, let me know. Thanks!

G.

**Comment by TomFreudenberg** [comment]
For anyone who is coming here by searching for running great meteor on yet unsuppo You will the updated gitrepo on https://github.com/4commerce-technologies-AG/meteor. The repo is kept updated always to latest meteor stable releases.

An additional blog with comments and hints from issues all over the time is available at: http://meteor-universal.tumblr.com/. Help and comments are welcome! You can send me your comments via github issues or by MENU->SuggestionBox on blog.

**Comment by suchipi** [comment]
@TomFreudenberg thanks for the comment; I was able to use meteor on an ARM Chromebook with that fork no problem.

**Comment by mlarghydracept** [comment]
@TomFreudenberg I had great luck running your fork on a Raspberry Pi. Thanks so much!

**Comment by wbartussek** [comment]
Hi, I just tried to install meteor on an Cubieboard 4 CC A80 (hardware architecture is armv7l), running Lubuntu Linaro 14.04 trusty) and got the message "Meteor only supports i686 and x86_64 for now" which led me finally to this thread. @TomFreudenberg Is this covered by your package mentioned above?

**Comment by skaag** [comment]
I strongly suggest you try the 4commerce distribution, I personally tried it and it worked wonderfully (it is also the quickest because it uses distro supplied binaries instead of compiling stuff for hours, or in the case of the ARM systems, DAYS!).

**Comment by TomFreudenberg** [comment]
Hi Wolfram ( @wbartussek ), yes it should work otherwise feel free to give me a post in the issue queue on https://github.com/4commerce-technologies-AG/meteor.

@skaag - thanks for your referral

**Comment by wbartussek** [comment]
Thanks for the quick response. I'll try it and report on my experience.

**Comment by wbartussek** [comment]
**Success!**
Now you can add the **Cubieboard 4 CC A80** to your supported hardware! 
One hint how to overcome a strange message specific to Lubuntu on Cubieboard: 
After starting your app with meteor you may possibly get:

=> Started proxy.                             
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Can't start Mongo server.                     
MongoDB failed global initialization

Looks like MongoDB doesn't understand your locale settings. See
https://github.com/meteor/meteor/issues/4019 for more details.

You can now get those language settings with
perl -e exit
which will yield an output like:

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

Obviously there is an inconsistency in language settings (due to the Chinese make of Cubieboard). This can be repaired by issuing:
sudo locale-gen en_US.UTF-8 
or e.g. for a German locale:
sudo locale-gen de_US.UTF-8 

Then everything works as expected.
@TomFreudenberg "Ich bin begeistert!"

**Comment by TomFreudenberg** [comment]
Hi Wolfram ( @wbartussek ) great to hear about success on Cubie as well.

For anyone fell in same condition about LOCALE please see the documented issue at:

https://github.com/4commerce-technologies-AG/meteor/issues/28

**Comment by trusktr** [comment]
Hello All, [Mongo for ARM](https://jira.mongodb.org/plugins/servlet/mobile#issue/SERVER-1811/comment/1365439) is officially complete! We're one nice step closer...

**Comment by TPXP** [comment]
:warning: This is only for 64-bit ARM architectures, so armv5/6/7 are still not supported...

**Comment by Dev1an** [comment]
Why is this issue closed? How can we run meteor (1.4 and later) on ARM devices?

**Comment by duvrai** [comment]
This issue lives now here: https://github.com/meteor/meteor-feature-requests/issues/130
