### ISSUE TITLE
"--mobile-server my.remote.server" overwritten with localhost:3000 on reload

### ISSUE THREAD

**Issue by ol-c** [meteor/meteor#4422]
I run:

`meteor run ios --mobile-server my.remote.server`

from my Mac and my application builds and launches correctly in the emulator.
I check `__meteor_runtime_config__` for `DDP_DEFAULT_CONNECTION_URL` and `ROOT_URL` and I get the expected `"my.remote.server"` Good times :) (server logs confirm the good times)

When I reload the page in the emulator (via the safari dev console) `DDP_DEFAULT_CONNECTION_URL` and `ROOT_URL` are reset to `localhost:3000` Oh no!

I reproduced this issue with a freshly created project from meteor version 1.1.0.2

I believe this issue is the root cause of another issue I'm seeing too. Maybe others are struggling with similar things:

I do the above, then I make a change on my remote server.
1. Client senses change and refreshes.
2. `DDP_DEFAULT_CONNECTION_URL` and `ROOT_URL` are overwritten by `localhost:3000`
3. Refreshed client now looks to `localhost:3000` for all the most recent files
4. After downloading all the files from `localhost:3000` the app realizes they are old versions and starts at number 2 again

Maybe I'm missing an extra configuration somewhere?
I am starting the live server with `ROOT_URL=my.remote.server meteor`

Thanks! BTW, awesome work with the platform and congrats on the Series B.

**Comment by ol-c** [comment]
Here's how I'm working around the issue in the mean time:

http://stackoverflow.com/questions/28948742/how-to-prevent-load-of-meteor-local-when-building-ios-app-with-phonegap

essentially, set these to the desired root url on the server and inside of Meteor.startup(...)

Meteor.absoluteUrl.defaultOptions.rootUrl
process.env.ROOT_URL
process.env.MOBILE_ROOT_URL 
process.env.MOBILE_DDP_URL

I couldn't find documentation on it, but a clever guy found these while poking around.

**Comment by Futurama56** [comment]
+1

**Comment by ol-c** [comment]
Sure, here's the bare bones version:

```
var ROOT_URL = 'http://example.com';

Meteor.startup(function () {
  if (Meteor.isServer) {
    //  otherwise client will look to http://localhost:3000 after first update
    Meteor.absoluteUrl.defaultOptions.rootUrl = ROOT_URL;
    process.env.ROOT_URL = ROOT_URL;
    process.env.MOBILE_ROOT_URL = ROOT_URL;
    process.env.MOBILE_DDP_URL = ROOT_URL;
  }
});
```

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.  

Please, a step by step reproduction starting with an empty directory (or ideally git cloning a repo).

**Comment by Rebolon** [comment]
@glasser i have the same problem since one month, so i did a sample project to help to reproduce : 
https://github.com/Rebolon/one-citation-a-day
clone it,
cd one-citation-a-day/app/mobile
cp package.dist.json package.json
cp settings.dist.json settings.json
edit package.json to set rooturl and mobileserver to your own server (http://myServer:port)
npm run-script build (it set the environment variable and then builds the app in one-citation-a-day)
then sign the app that is stored in one-citation-a-day/build/
install the app on an emulator
run the server with #npm start

open chrome and inspect the application :
 * first you can see that the app is well connected to the server (it displays informations)
 * if you pause the application, you can see that __meteor_runtime_config__ is well configured and display your server uri
 * then it downloads the app from the server
 * then it refresh the app and... no more connection to the server because the __meteor_runtime_config__ is no more well configured 

if you open the app in a browser it works well.
