### ISSUE TITLE
Meteor update call does not necessary return the number of documents updated

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#4436]
Meteor MongoDB update call uses `getlasterror` to get the number of documents updated. But in fact, that number is not really the number of documents updated, but the number of documents matched by the update query part.

See this MongoDB ticket for more information: https://jira.mongodb.org/browse/DOCS-5491

I think `nModified` should be used as a return value from MongoDB update call.

**Comment by glasser** [comment]
I believe this was a wire protocol change between 2.4 and 2.6 (and that the Node Mongo driver has lots of fun layers of backwards compatibility built in).

Hmm.  I mean, ideally we should just show the entire result object, but that's pretty backwards-incompatible. (The joys of building our own wrappers around other things...)  I'm not actually sure that I agree that nMatched shouldn't be the default if we're only getting a single number though.  After all, that's the number that MongoDB originally thought should be the only returned number...

Maybe adding an option to `update` that returns the full nModified/nMatched/etc object instead of just a number would be a good idea.  And implement in both Minimongo and the MongoDB driver, with tests. Pull requests welcome.

**Comment by mitar** [comment]
Personally, I would just return `nModified` and this is it. This is how is documented in Meteor, number of updated documents. So this would be a "fix" to really make it so. I do not see the usefulness of returning matched documents from an update call. So if we are returning one number, let's return `nModified` for update calls. And maybe later on we could additional option to return more.

Would a pull request for that be OK?

**Comment by glasser** [comment]
I mean, this is a backwards-incompatible change you're proposing, to something that isn't clearly a bug.  After all, Meteor's behavior matches MongoDB's pre-2.6 behavior, and MongoDB solved this problem not by redefining what the untagged number means but by adding more possible answers.  I think either guess as to what is meant by the vague MongoDB and Meteor documentation is plausible.

**Comment by mitar** [comment]
I think it is not a backwards incompatible, at least based on current Meteor documentation:

> Once the update completes, the callback is called with a single error argument in the case of failure, or a second argument indicating the number of *affected* documents if the update was successful.

(Emphasis mine.)

This is how I discovered this bug. I was using the code assuming that it works like that, but then I discovered it does not. So, I am proposing that we make code work as it is documented to work.

**Comment by davidecantini** [comment]
Here are some considerations (based on what Mongodb 2.6 returns as writeResult):
<ul>
<li><p>Update a field for an existing doc (i.e. matched):</p>
<code>{ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 }</code>
<p>
Assuming that nModified > 0 => nMatched > 0, and, even though we could have nMatched <> nModified, if only one value should be returned, nModified would be the one carrying the most useful information. Returning only nMatched would not guarantee that any field was modified.
</p>
</li>
<li><p>Update a field for a doc that doesn't exist (i.e. no match):</p>
<code>{ "nMatched" : 0, "nUpserted" : 0, "nModified" : 0 }</code>
</li>
<li>
<p>Update a field for an existing doc (i.e. matched), with the same field value:</p>
<code>{ "nMatched" : 1, "nUpserted" : 0, "nModified" : 0 }</code>
</li>
</ul>
<p>The last two cases show that if only nModified was returned, the app would not have any way to distinguish between the case where the document to be updated does not exist (possibly showing an error message) and the case where the field is updated with the same field (which most of the time, if not always, is allowed and doesn't call for any error message to be shown). Again, if only one value had to be returned, in this case nMatched would help, whereas nModified would not.</p>
<p>Bottom line: <a href="http://docs.meteor.com/#/full/update">collection.update</a> should provide the full nMatched/nModified/etc. object either by adding an option (maybe called "result") as suggested by @glasser or (if backward-compatibility is not yet a major concern) just returning the object instead of the scalar value. 
</p>

**Comment by abernix** [comment]
I didn't immediately see where `getLastError` was being used in the current setup, but per #6957, it appears that when Mongo 3.2 is released, `nModified` is [what is going to be returned from the mongo driver](https://github.com/meteor/meteor/blob/mongo-3.2/packages/mongo/mongo_driver.js#L604-L629).  This should make things work as documented and one of the goals of this issue.

Then I suppose the remaining issue from this ticket is:
>adding an option to update that returns the full nModified/nMatched/etc object instead of just a number

Does this sound right, @mitar?

**Comment by mitar** [comment]
Yes, switching to `nModified` would be in my opinion the correct thing to do. But we should definitely mention this in changelog.

**Comment by abernix** [comment]
Yeah, It seems like that's what's happening with that change – will need to check a bit more in detail and definitely need to make sure that's mentioned.

**Comment by mitar** [comment]
So, if I am understanding correctly, we are still returning only matched and there is no way to get the whole raw result from Mongo?

**Comment by mitar** [comment]
Hm, is seems there is already `_returnObject` flag which then returns augmented result object?

**Comment by abernix** [comment]
@mitar I don't think the discussed post-1.4 PR for the ability to request `rawResult` ever came from anyone but, as you pointed out, it does [appear](https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L530-L581) to support this by setting the `_returnObject` option right now.

**Comment by derwaldgeist** [comment]
I just stumbled upon this, since I was wondering why Meteor does return nMatched instead of nModified. +1 for returning nModified instead, this makes more sense IMHO.

**Comment by mitar** [comment]
It seems that probably we cannot really change this because of backwards compatibility, but you can try setting `_returnObject` in the options argument.

Maybe this issue could be about making `_returnObject` into `returnObject` and document it?

**Comment by derwaldgeist** [comment]
Thanks for your reply. Unfortunately, _returnObject will not help me, since I am still on 1.2, and it only returns numberAffected there.

**Comment by hwillson** [comment]
A brief update on this issue. I've verified we're still returning the total count of documents scanned, not modified (see https://github.com/meteor/meteor/blob/56ad858559c4222fad7d44115a63c3c759fc2abe/packages/mongo/mongo_driver.js#L623 and [`updateWriteOpResult`](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#~updateWriteOpResult)).

While you can pass `_returnObject: true` in as an `update` option, the object you get back isn't the full `updateWriteOpResult` object. For example:

```
widgetsCollection.update({ 
  _id: '24sMjtpYXmEmPKoST',
}, { 
  $set: { 
    someField: 'some value',
  },
}, { 
  _returnObject: true,
});
```

returns:

```
{ numberAffected: 1 }
```

This is actually super misleading; `numberAffected` here isn't really the number of records that were affected, it's the number of documents that were scanned (again, see https://github.com/meteor/meteor/blob/56ad858559c4222fad7d44115a63c3c759fc2abe/packages/mongo/mongo_driver.js#L623 - `mongoResult.n` represents the total count of documents scanned).

Given the above, it looks like the best way forward with this issue (since we can't change the current count returned by `update` for backwards compatibility reasons), is to:

1. Change the current `_returnObject` option to `returnObject`, so it appears/becomes more publicly supported.
2. Reference the `returnObject` option in the `update` docs.
3. Adjust the returned object to contain both "The total count of documents scanned" and "The total count of documents modified" - see the node mongo driver's  [`updateWriteOpResult`](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#~updateWriteOpResult) docs for details.

**Comment by abernix** [comment]
This seems like a good direction!

`returnObject` should be called something more clear when it's made public – maybe `returnWriteResult`?  `returnWriteOpResult`?

I guess, in a way, `numberAffected` could stay as "records scanned" and still make _some_ sense (they were at least touched, right?).  What's the thinking for the new field names on the returned object?: `numberModified` (would equal `modifiedCount`)?

We could also just take the opportunity to change the fields entirely (including renaming `numberAffected` to `numberScanned`), leave `_returnObject` doing what it was doing, but add a deprecation `Console.warn` on the server when it's used?  I'm just trying to imagine a world where this is on-parity with the actual `WriteOpResult`.

**Comment by mitar** [comment]
What if we simply return whatever node driver is returning and this is it (when a flag is set through options)? That will be easiest to document and explain to users. We do not have to rename/redefine anything.

**Comment by abernix** [comment]
That's exactly what I said in my last sentence.  A new `returnWriteOpResult` would return the Node driver's `WriteOpResult` and `_returnObject` could be deprecated.

**Comment by mitar** [comment]
Hm, maybe I misread something. Sorry.

**Comment by abernix** [comment]
To be fair, it would have been a lot more clear if it was my _only_ suggestion instead of just mentioning it in the last sentence.

I'll try to wake up some more and stop rambling.

**Comment by mutdmour** [comment]
I can work on this following @hwillson's points.

**Comment by hwillson** [comment]
Awesome @mutdmour! Maybe also note the suggestion in https://github.com/meteor/meteor/issues/4436#issuecomment-284653983 (it might make more sense to return everything the node driver is). Thanks!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20update%20call%20does%20not%20necessary%20return%20the%20number%20of%20documents%20updated&body=Migrated%20from:%20meteor/meteor%234436) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by sebakerckhof** [comment]
@mutdmour I stumbled upon this today. Are you still interested in making this into a PR?
