### ISSUE TITLE
Add `delete` to ReactiveDict

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4438]
Right now, you have to `set` to `undefined`, which is not really semantic. Also, it's not documented anywhere.

**Comment by mitar** [comment]
And also it does not clean up the dependency object. :-)

**Comment by Maxhodges** [comment]
delete might be fine. `remove` is used in some languages when the object could have a life outside of the collection from which it is removed. But if the property will truly not exist after deleting it (as opposed to simply setting it to null or undefined) then `delete` works for me. But if the dictionary element will exist but have an undefined value (as with `myDict.set('make', undefined);` , then calling it `delete` would not be appropriate.

**Comment by jagi** [comment]
I've made reactive JavaScript [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) package that can be found [here](https://atmospherejs.com/jagi/reactive-map). The GitHub repository is [here](https://github.com/jagi/meteor-reactive-map). It has `delete` and `has` methods and reactive `size` property.

```sh
$ meteor add jagi:reactive-map
```

```js
var map = new ReactiveMap();

map.set('key', 'value');
map.set({
  key1: 'value1',
  key2: 'value2'
});

map.get('key'); // Returns "value".

map.all(); // Returns { key: "value", key1: "value1", key2: "value2" }.

map.size; // Returns 3.

map.has('key'); // Return true.

map.delete('key'); // Deletes "key".

map.clear(); // Clears map.
```

I'm also planning to create ReactiveSet.

**Comment by stubailo** [comment]
How is the `size` property reactive if it's not a function?

**Comment by jagi** [comment]
Thanks to the getter defined on the `ReactiveMap` prototype https://github.com/jagi/meteor-reactive-map/blob/master/lib/reactive_map.js#L162

**Comment by mitar** [comment]
Can you provide a version without getters? To support browsers which does not have support for them? Getters are not really used around in Meteor.

**Comment by jagi** [comment]
Hmm I see. Yes of course I could replace the `size` property with the `size()` method. I think it's not a big deal. However it force me to think how many people are still developing for IE lower than IE9. It really makes development hard when you always have to think about old browsers. In fact I'm using [setters and getters](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/init_class.js#L107) extensively in my [Astronomy](https://github.com/jagi/meteor-astronomy) package and now I'm thinking about sacrifice using setters and getters in order to have better compatibility.

**Comment by jagi** [comment]
Ok I've made a fix changing the `size` property into the `size()` method.

**Comment by laosb** [comment]
As the PR was merged, closing.

**Comment by ramirez530** [comment]
Delete
