### ISSUE TITLE
Move docs to a separated repo

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#4439]
***2 Upvotes*** Meteor is a good platform for both production and education, so I decided to translate Meteor Docs into Chinese, it will be easier for China developers, even students, to play with Meteor. The problem is that docs exist as a folder in the main repo, so if I need to translate, I need to fork the main repo, which is unnecessary for document translating.

**Comment by ShashankaNataraj** [comment]
+1

**Comment by stubailo** [comment]
I think the reason docs are in the same repo right now is mainly so that they can be versioned as part of the same codebase. This means if you check out a release of Meteor in Git, that will also check out the correct version of the docs.

It seems to me like there isn't much of a cost to forking the whole Meteor repo for docs translation, other than just having a lot of unnecessary files in the directory - is there something you would like to do that is currently not possible because of this repository structure?

**Comment by laosb** [comment]
Due to the slow network connection between China Mainland and Github, and the MOST are the "unnecessary" files for docs translating, It's not worth cloning the whole codebase. 
To the point that "can be versioned as part of the same codebase", we can make the docs one of our example apps, so we can `meteor create --example docs` and I believe that it is much easier for those ones only need a docs app instead of a clone of Meteor.

**Comment by 285858315** [comment]
+1

**Comment by laosb** [comment]
In this way we can have a separated issues tracker for docs, which can make the docs better.
