### ISSUE TITLE
meteor/cordova/android how to display contact images?

### ISSUE THREAD

**Issue by uriva** [meteor/meteor#4444]
I'm getting this:

> Not allowed to load local resource: content://com.android.contacts/contacts/1253/photo

while trying to display contact image.

Perhaps related to this thread https://code.google.com/p/android/issues/detail?id=63033

**Comment by glasser** [comment]
"How can I do this?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. Good luck!

**Comment by uriva** [comment]
Apologies @glasser, I was under the impression that using url with content:// prefix cannot be done, making this a bug/feature request.
Am I wrong? If so I will be glad to ask elsewhere.

**Comment by glasser** [comment]
OK, but is this a bug in Meteor? Is there anything different about Meteor here than any other attempt to make a WebView-based Android app?

**Comment by uriva** [comment]
In cordova this works, in meteor it does not, so yes.

**Comment by glasser** [comment]
I'm confused. First you said "using url with content:// prefix cannot be done due to android limitations".  Now you're saying it's a Meteor-specific issue?

If this is a Meteor-specific bug, please follow the instructions in https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor that explain how to demonstrate a bug.  Ideally for this particular bug you will also show a non-Meteor Cordova project where this bug doesn't exist, so we can tell the difference between Meteor and Cordova issues.

**Comment by uriva** [comment]
Sorry for being unclear: I said it was meteor specific because as far as I know cordova users can deploy their apps with the web content inside, while meteor serves them via server.

**Comment by uriva** [comment]
Here is a minimal example:
https://github.com/uriva/meteor-content-url

**Comment by glasser** [comment]
Have you tried using App.accessRule in mobile-config.js? http://docs.meteor.com/#/full/App-accessRule

**Comment by uriva** [comment]
Tried now, didn't change anything.

**Comment by adrianolsk** [comment]
Any update on this?
I am getting this error on meteor console when I ported a cordova contact list to meteor
```
Not allowed to load local resource: content://com.android.contacts/contacts/10
```
I tried several diferent ways using  App.accessRule in mobile-config.js
```
App.accessRule("http://meteor.local/*");
App.accessRule("*");
App.accessRule("content://*");
App.accessRule("content:*");
```
But with no luck 
I think that's because using cordova the files are running on file:// and with meteor is on http://meteor.local, but I am not sure.

**Comment by uriva** [comment]
@glasser why is this closed?

**Comment by nickmendes** [comment]
Im still facing this issue in Meteor 1.3.2.4

**Comment by abernix** [comment]
@nickmendes Meteor 1.3.2.4 is almost a year old; you should try a newer version of Meteor which comes with newer versions of Cordova.  See [`History.md`](https://github.com/meteor/meteor/blob/devel/History.md).

**Comment by daniel-mf** [comment]
Meteor 1.5.1 and still I can't find a way of getting this to work.

**Comment by nickmendes** [comment]
@abernix Im using Meteor 1.5 also, and Im still unable to use local images.
