### ISSUE TITLE
BUG: error: Cannot override existing build, even though I'm building for different architectures.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4477]
I built a package for `os.linux.x86_64`, which worked fine, then I tried building the package for `os.linux.x86_32` and it gave the error:

```
=> Errors while publishing build:

While publishing package build for rocket:webpack:
error: Cannot override existing build
```

Any idea why this happens? Any more info I can provide? I triple checked I'm using two different machines, one for the 64bit and one for the 32bit.

**Comment by trusktr** [comment]
...Aaaaaaand, I just got the same error for the Windows target (I think, at least that what the terminal shows, but it looks like the Window machine manages to erase terminal history, so I might be seeing old output from the Linux error). I've never built this for Windows before.

I ran the command a second time, and this time the result overwrote some terminal history so I see the linux error directly above, but a successful Windows message below:

```
meteor@ip-172-31-46-28:~$   meteor publish-for-arch rocket:webpack@1.9.10
rocket:webpack: updating npm dependencies -- webpack...

Some package versions changed since this package was published!

rocket:webpack  added, version 1.9.10
Please log in with your Meteor developer account. If you don't have one,
you can quickly create one at www.meteor.com.
Username: trusktr
Password:
=> Errors while publishing build:

While publishing package build for rocket:webpack:
error: Cannot override existing build


C:\Windows\system32>  meteor publish-for-arch rocket:webpack@1.9.10
rocket:webpack: updating npm dependencies -- webpack...

Some package versions changed since this package was published!

rocket:webpack  added, version 1.9.10
C:\Windows\system32>
```

It seems to have worked. I don't have Windows handy right now for testing though.

**Comment by glasser** [comment]
OK, what's going on here is that there's this npm dependency chain webpack -> watchpack -> chokidar.  chokidar is a file-watching module.  It has a dependency on `fsevents` declared in package.json as an optional dependency.  `fsevents` is a Mac-only binary package.

So when you build this package on a Mac, you get fsevents and Meteor detects that there is binary code here and publishes it as a Mac-specific package.

When you build it on other platforms, fsevents fails to install, but that's OK since it's an optional dependency.  So it goes and publishes it as a platform-agnostic package.

And that's what the error you're getting is saying: when you go to publish on the second Linux platform or on Windows, it also tries to publish as platform-agnostic and finds that there's already one.

I think there's no actual bug here, even though it's confusing.  I've added a commit that extends the error message to include the architecture it was trying to upload.  (Also, in this odd case, it's unclear to me if we're guaranteed to choose the Mac build rather than the agnostic build when you're on a Mac and downloading packages.)

**Comment by trusktr** [comment]
@glasser I would never have known! I haven't seen the new error message yet, but maybe when `publish-for-arch` is used and Meteor ends up publishing an agnostic build, then it can say that in the message.

**Comment by aaronjudd** [comment]
@glasser I'd suggest that this shouldn't be closed, unless there is a duplicate as this is a frustrating error. I can never tell if the packages are really published correctly, as the x86_32 and windows build in many of my packages (with npm dependencies) are always reporting.  If there is an error, and I didn't cause the error then and the package actually IS published, then there should perhaps be either a warning or a "info" message, but certainly not an error.  As long as I see an error, I can only assume it's broken and hasn't been published.  If there were a method that we could use verify that the package works cross platform would be helpful, but for now it's just a guess. 

IE:

```
While publishing package build for ongoworks:bunyan-logger:
error: Cannot override existing build
```

Is it published or not?

**Comment by trusktr** [comment]
@glasser When `error: Cannot override existing build` is encountered, does the package get published for that platform? It doesn't seem like that's the case. We're getting errors that versions of rocket:webpack can't be found for the specified platform when doing binary builds of rocket:webpack at https://autopublish.meteor.com. Also, this is detected as an error which throws autopublish.meteor.com off. If there's nothing wrong, shouldn't this exit cleanly?

**Comment by cwaring** [comment]
I am stuck in this same confusing cycle too. After publishing `kit:cssnext` I'm requested to build the specific platform versions, the first build on os.linux.x86_64 completes and publishes and the `architecturesOS` is updated to:
```
     "architecturesOS": [
        "os"
      ]

```
Which I assume means it was detected as platform agnostic, because all subsequent builds on the remaining platforms return:
```
Errors while publishing build:
While publishing package build for kit:cssnext:
error: Cannot override existing build
```
So I continue to deploy my local application and then I'm hit with the error:
```
Errors prevented deploying:
While linking the program:
error: kit:cssnext is not compatible with architecture 'os.linux.x86_64'
```
Which seems to be because the bundler is using my local package source in `$PACKAGE_DIRS`. If I temporarily move the local package the bundler downloads the new sources and deploys successfully.

These series of events are going to trip most people up, but with the correct error messaging it would help guide people along.

As a quick fix is there a way to get the local bundler to use published package sources as a preference and then fallback to local ones? That will help overcome the build/deploy issues at least.

**Comment by trusktr** [comment]
If this could be cleaned and documented for `1.2`, that's be great! @glasser @stubailo

**Comment by cwaring** [comment]
@trusktr :+1: looking forward to this being fully automated too.

**Comment by ichernev** [comment]
I'm hitting this with momentjs package. Is there even a way to check what is uploaded and what is not? Not to mention moment is fully platform agnostic (excluding dev tools that only moment devs have to worry about).
