### ISSUE TITLE
[IDEA] don't save a dependency's node_modules in a dependent build plugin's isopack.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4493]
This is causing a dependent with no binary NPM dependencies to need to be published for specific architectures. In my specific case, [rocket:module](https://github.com/trusktr/rocket-module) is depending on [rocket:webpack](https://github.com/trusktr/rocket-webpack), and only rocket:webpack has binary NPM dependencies, but when publishing rocket:module still Meteor still asks me to publish rocket:module for specific architectures. 

Rocket:module only has a build plugin. Is this the cause? I haven't really tested this with normal packages yet.

It seems that if we can guarantee identical builds through Meteor's package system, then it should be fine to store the NPM dependencies for a package (f.e. rocket:webpack) only in that package's isopack, and if isopack filesystem structure is consistent, it should be possible for dependencies to be obtained across isopacks instead of bundled in a single topmost isopack.

Are there any plans to change this? Any thoughts against it? Maybe it just hasn't been implemented yet?

**Comment by trusktr** [comment]
I'm just wondering because it's definitely time consuming to have to get a machine for each build and publish for the architecture on each machine each time I make JavaScript code changes.

**Comment by glasser** [comment]
Well, the issue here is that build plugins are kind of like tiny self-contained apps, which contain all of their transitive dependencies.  So a build plugin that contains a platform-specific package *as part of the plugin* makes its package platform-specific as well.

There has definitely been thought given to revamping how binary builds work in Meteor.  We really like that in order to *use* a binary package, you don't necessarily need to have compilers installed (mildly annoying on OSX, rather tough on Windows), as long as the package maintainer jumped through the hoops of publishing the specific build. But maybe it wasn't the best idea to make this be the *only* way to get the binary parts of a publish package.  Future changes to the package system could simplify this experience.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BIDEA%5D%20don't%20save%20a%20dependency's%20node_modules%20in%20a%20dependent%20build%20plugin's%20isopack.&body=Migrated%20from:%20meteor/meteor%234493) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
