### ISSUE TITLE
Mobile app is not capturing users facebook/google profile pic. (bengott:avatar pckg)

### ISSUE THREAD

**Issue by ecuanaso** [meteor/meteor#4495]
When I run my app in my localmachine or on any browser be it laptop and or phone, the bengott:avatar package picks up the users facebook and or google profile picture, however when I run the app on my mobile application, the avatar package only picks up the initials of the user. What could be the problem?

**Comment by Tarang** [comment]
This is likely something related to the bengott:avatar package not meteor.

From their readme: https://github.com/bengott/meteor-avatar

The app displays initials as the avatar (fallbackType): https://github.com/bengott/meteor-avatar if nothing else can be found.

For more details, you may be better off there though. It may be something to do with your publication config where the required fields since its all done client side.

**Comment by ecuanaso** [comment]
I've already asked the question in the bengott:avatar issues. I get absolutely no help. I changed the fallbacktype already so I don't think its that.

And you said it might be due to the publication config? Ok, well heres what I have in my publications.

Meteor.publish('userData', function() {
  if(!this.userId) return null;
  return Meteor.users.find(this.userId, {fields: {
    "services.facebook.id" : true,
    "services.google.picture": true
  }});
});

**Comment by stubailo** [comment]
I suspect this might be something related to the specific package you are using. If you think this is a Meteor bug, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
