### ISSUE TITLE
WHY Mongodb BEFORE SQL ???

### ISSUE THREAD

**Issue by systemaker** [meteor/meteor#4503]
I still don't understand why native mongodb was preferred to native SQL (like SQLite or MySQL) ? :)

**Comment by steviee** [comment]
I think the decision was made due to several reasons:

1 - JSON everywhere, even in the database. You can use the same document on all tiers.
2 - Eventing/Callbacks from the database layer when changes happen: It's easier to integrate nosql databases that way than relational DB systems (my guess), because it's a lot harder to track ONE document which was normalized into several tables.
3 - Meteor is opinionated and they simply don't HAVE to do anything in any particular order. :)

Best regards,
Steviee

**Comment by stubailo** [comment]
Hey, @systemaker! This is a pretty valid question, but isn't really a bug or feature request for Meteor. We are going to be working hard on first class support for SQL soon, which will be a major project. If you'd like to discuss more, I'd suggest a post on the official forum: https://forums.meteor.com/

**Comment by donosemihai** [comment]
Recently I discovered a tool simply called DbSchema. First of all I was impressed because they do diagrams for MongoDB.
Second I found great an data explorer from them, where you can explore data from each collection and sub-documents in a separate window.
Now I am dealing with virtual foreign key from them, to explore data from two collections bind referencing one the other via ObjectId's.


Look for DbSchema tool, is great for the diagrams they do for MongoDB, query builder and data explorer.
Some features you may discover inside like virtual foreign keys makes the interaction really similar with relational databases, 
where you can place data in multiple collections and join it with ObjectId's.


I was surprised to see is possible to have diagrams for MongoDB as well, as for any relational database.
Go for the tool DbSchema. Have a look on relational data browse and the virtual foreign keys there, 
they are a step forward in designing a database with data over multiple collections and references between them via ObjectId's.

**Comment by wildfiremedia** [comment]
This is spam.
