### ISSUE TITLE
Warn when Meteor.Collection is used, and explain why you should use Mongo.Collection and depend on the 'mongo' package

### ISSUE THREAD

**Issue by babakness** [meteor/meteor#4519]
Hello, defining a collection with either Mongo or Meteor before startup within the app directories (not packages) works fine even if not wrapped in Meteor.startup

Within a package however, the Mongo object is only available within Meteor.startup. However, like the app directories, outside of Meteor.startup, the Meteor object is available. So Mongo.Collection only works within Meteor.startup in packages but Meteor.Collection will work outside of Meteor.startup.

I just wanted to point out this inconsistency. It seems that as other databases get added, Mongo.Collection would become the proper way to do things, however that does work the same way Meteor.Collection does now.

Best regards.

**Comment by rclai** [comment]
In your `package.js` file do you do `api.use('mongo')`?

**Comment by stubailo** [comment]
Yeah one of the reasons we are getting rid of `Meteor.*` is because it makes it easy to accidentally depend on packages like `mongo`. In a future where `mongo` is not as common, it would be good for packages to have to depend on it explicitly.

**Comment by hwillson** [comment]
I think [enough time has passed](https://github.com/meteor/meteor/blob/devel/History.md#v091-2014-sep-04) (almost 2.5 years) since the `Meteor.Collection` to `Mongo.Collection` cutover happened, and developers have had enough time to get used to the change (and update their notes, tutorials, blog posts, videos, books, t-shirts, coffee mugs, etc.). I'll close this issue off - happy to re-open if anyone disagrees. Thanks for the original request!
