### ISSUE TITLE
Change the way HTTP errors are thrown

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#4540]
I'd like to suggest either better documentation of HTTP error handling, or re-writing the code to throw a cleaner error object. If one catches an error thrown by `HTTP.call()`, (that is, `catch (e)`), the error object is pretty confusing.

First off, `_.keys(e)` reports it only has one property called `stack`. Yet if I do `console.log(e.message)`, I can see a message printed out, e.g.:

>failed [404] [{"errorCode":"NOT_FOUND","message":"The requested resource does not exist"}]

Yet I'm unable to access the error code via `e.errorCode` or anything useful like that.

Maybe someone can shed some light on how to handle/parse HTTP errors? It seems a bit of a mess compared to other error objects, like for `Match.Error` where I can simply access `e.errorCode`, `e.sanitizedError.reason`, etc.

**Comment by glasser** [comment]
So, this is actually documented:

> When run in asynchronous mode, the callback receives two arguments, error and result. The error argument will contain an Error if the request fails in any way, including a network error, time-out, or an HTTP status code in the 400 or 500 range. In case of a 4xx/5xx HTTP status code, the `response` property on error matches the contents of the result object. When run in synchronous mode, either result is returned from the function, or `error` is thrown.

This is a bit confusing, but what it's saying is that you want to look at the `response` field on the error.  That's an object with things like statusCode, contents, headers, etc, as documented.

Why don't you see `response` in `_.keys`?  It's because the Fibers module used by Meteor to make server-side code synchronous does some weird tricks to an Error object that gets thrown through a Future to make slightly better stack traces.  The error you end up with is a new object created with the original error as the prototype.  So `response` is a key on the error's prototype, not on the error itself, and it's skipped by `_.keys`.  You can see it in a normal `for (k in err)` loop though.
