### ISSUE TITLE
I want to deploy to my server with 'meteor deploy' 

### ISSUE THREAD

**Issue by endows** [meteor/meteor#4542]
I using meteor in my app.I have used 'git push deploy master'.
but it's not simple.
I want to use 'meteor deploy' like this.
```
meteor deploy root@myserver.com
```
Who you have any that are making this feature? When nobody,I'll make this.

**Comment by thinklinux** [comment]
For now you can use [meteor-up package](https://github.com/arunoda/meteor-up) or wait for the meteor team to launch galaxy (meteor production deployment).

**Comment by robertpitt** [comment]
I tested some things a while back with meteor deploy and it turns out you can actually use Meteor deploy to deploy to your own server.

Run this server: https://github.com/robertpitt/universe with node

then you can do

`DEPLOY_HOSTNAME="http://lcoalhost:3300" meteor deploy`

which will compile and package a tar.gz and send it to this server instance, and write it to the tmp folder, what you do with it is up to you.

Note: you must be authenticated with meteor univers before you can deploy to a server.

Good Luck.

**Comment by endows** [comment]
@thinklinux Thanks to reply.I already know that meteor-up.

**Comment by endows** [comment]
@robertpitt Oh..It's cool! I'll try it.Thank you.

**Comment by osv** [comment]
I use own git-hook script for build and deploy.

**Comment by ekatek** [comment]
It sounds like you can accomplish some of this with DEPLOY_HOSTNAME (as mentioned above) and some will have to wait for Galaxy. Closing this issue for now.
