### ISSUE TITLE
Some Meteor methods are blocking (login, meteor_autoupdate_clientVersions, ...) and slowing down all other subscriptions

### ISSUE THREAD

**Issue by olivierpascal** [meteor/meteor#4559]
Hello,

It seems that the some server methods are blocking. I'm thinking especially about "login",  "meteor_autoupdate_clientVersions" and "meteor.loginServiceConfiguration" (even without pushing any new code).

It slow down all other subscriptions and it hardly scale.

Is it possible to make these methods non-blocking? If I should ask this in the forum, just tell me, but I think it touches the core of meteor and I guess I cannot do anything about it, except reporting it here.

**Comment by artpolikarpov** [comment]
+1

**Comment by glasser** [comment]
It was a design choice to try to not overlap `login` with other methods (using the client-side `wait` mechanism), because we thought that having user ID change mid-method-body would be a difficult paradigm to write code for.

Future versions of accounts may change how login works to not be just another method.

**Comment by olivierpascal** [comment]
Is there any solution to this? I'm totally stucked with this problem, I can't scale my app because of this.  I have many FB logins per second, and it blocks all my other subscriptions and methods.

**Comment by y-ich** [comment]
+1

**Comment by evolross** [comment]
It's March 2017 and I think I have this issue with `meteor.loginServiceConfiguration`.  In Kadira, ALL of my other subscriptions are waiting a VERY long time for this with about 300 users.  I'm getting:

`observeChanges` on `meteor_accounts_loginServiceConfiguration` 168686ms 

My production app is still on Meteor `1.1.0.3` and  `accounts-base@1.2.0`.  Is there some kind of index to add somewhere for this?

**Comment by evolross** [comment]
I'm still having issues with this. I'm on Meteor `1.2.1` now (slowly getting to `1.5`). My entire app is still bogged down by these crazy wait times on my Galaxy production server on `meteor_accounts_loginServiceConfiguration`.  And my users don't even _log in_ to my app. It's freely open to the public. The users just hitting the server causes all kinds of issues. Was there any work done on this in Meteor `1.3` or later? I start having issues around fifty users.

**Comment by duytq1303** [comment]
+1

**Comment by leizard** [comment]
+1 I have the same issue on my production app. Anybody have solution for this ?

**Comment by evolross** [comment]
After banging my head for a **long** time, I found the issue was too many simultaneous users all downloading the JS app bundle at the same time, on a _very small_ Galaxy Compact container, which in turn blocks the database, which materializes in a side-effect of sorts that is `meteor_accounts_loginServiceConfiguration` and `meteor_autoupdate_clientVersions` (among others) all appearing slow/blocked.  The solution is to use a CDN to host your JS bundle and other assets (see Meteor docs) and to add more/higher powered servers.  See my two Meteor forums posts about it:

[https://forums.meteor.com/t/solved-poor-galaxy-meteor-performance-serving-small-bursts-of-users-load-test/38671](https://forums.meteor.com/t/solved-poor-galaxy-meteor-performance-serving-small-bursts-of-users-load-test/38671)

[https://forums.meteor.com/t/mongo-scaling-issues/27905/25?u=evolross](https://forums.meteor.com/t/mongo-scaling-issues/27905/25?u=evolross)

**Comment by giordanocardillo** [comment]
I have this exact problem, but I've got a self hosted VPS with 16 CPU and 16Gb or RAM. The deploy  was made using [meteor-up](https://github.com/zodern/meteor-up), so it runs inside docker containers. I've got over 3000 simultaneous connections and that is driving me crazy, because the CPU and the RAM are not suffering! I'm using this meteor build on a website, embedded by a js script which loads the meteor application inside an iframe. The project itself it's called [upaplu](https://upaplu.com).

Here you can see a screenshot  of my `top` and `htop` commands while te server is under the load of 4100 people.

<img width="734" alt="top" src="https://user-images.githubusercontent.com/3403386/36644186-dfe8d746-1a56-11e8-8752-de30518d2143.png">

<img width="728" alt="schermata 2018-02-25 alle 18 05 09" src="https://user-images.githubusercontent.com/3403386/36644183-dc455f4c-1a56-11e8-9d1d-aaa9a2721c66.png">


MongoDB is optimized, I use oplogs, replicaset and all the nedded indexes are accurately set.

**Comment by olivierpascal** [comment]
How do you handle clustering across your 16 vCPus?

-olivier

**Comment by giordanocardillo** [comment]
What do you mean by handle clustering? I've just deployed on a debian server machine

**Comment by olivierpascal** [comment]
I mean no matter how many CPUs you have, Node is mono-process and will run on only one CPU. Taking advantage of a multi-CPU server with a Meteor app is tricky: you need a load balancer, sticky sessions, ... scaling Meteor horizontally is easier. Combining both (horizontal and vertical scaling) can be a nightmare.

**Comment by giordanocardillo** [comment]
Thank you, this is m first big application using Nodejs, other projects I built didn't have such load or user base. I guess I'll look forward in scaling the application

**Comment by evolross** [comment]
How are you serving the Meteor JS bundle? How big is your app bundle? I just went to your app website and it felt a little slow to load.  If you're having Meteor serve the bundle you could have the same problem I did above (see above).

**Comment by giordanocardillo** [comment]
I've deployed using [meteor-up](https://github.com/zodern/meteor-up) so the bundle is served from a node.js. By the way today I clustered the application and is load balanced from a nginx server. Now I've got 32 clusters on a 48 vCPU machine, and it seems to run for 4200 sumultaneous clients... Today we had something like 6200 clients and it slowed up

**Comment by evolross** [comment]
80MB!?  Are you sure about that? That's outrageously big... why so?  I would say you're seeing the problem of this thread because your node.js is trying to serve your massive app bundle to all those clients.  If even a small percentage are hitting the server at the exact same time... you see the above issues.  Sounds like you're throwing a massive server at it to brute-force grind through a problem that should be offloaded to a CDN.  Did you read the thread I posted above?

Just an FYI, you can deploy your app with meteor-up and still serve your app bundle with a CDN.  Is there a reason you aren't you using a CDN for your app bundle?

**Comment by giordanocardillo** [comment]
Ok, sorry for misunderstanding, I was checking the meteor bundle size... the JS bundle size is 2MB. I'm using nginx to serve the static assets. I could serve the css and js using the same nginx, but how can I tell meteor that?

**Comment by giordanocardillo** [comment]
@evolross should I upload the assets to CDN manually? How can I extract the assets from the mup deploy and serve by cdn?

**Comment by evolross** [comment]
Here it is 2019 and I'm running into this problem again.  My app has grown and I'm getting about 2500 users all hitting the server simultaneously and **everything** is being blocked by `meteor_autoupdate_clientVersions`. And this was using 8 Galaxy Double containers. That's a lot of horsepower.  Still trying to figure this out.  I thought I might have a bad un-indexed query somewhere that was blocking and APM saying `meteor_autoupdate_clientVersions` was slow was maybe a side-effect. But I've optimized everything. Nothing else is taking a long time besides `meteor_autoupdate_clientVersions`.  Anyone get any farther on this?

**Comment by skxu** [comment]
> Here it is 2019 and I'm running into this problem again. My app has grown and I'm getting about 2500 users all hitting the server simultaneously and **everything** is being blocked by `meteor_autoupdate_clientVersions`. And this was using 8 Galaxy Double containers. That's a lot of horsepower. Still trying to figure this out. I thought I might have a bad un-indexed query somewhere that was blocking and APM saying `meteor_autoupdate_clientVersions` was slow was maybe a side-effect. But I've optimized everything. Nothing else is taking a long time besides `meteor_autoupdate_clientVersions`. Anyone get any farther on this?

Did you manage to solve this? I've been reading through your various posts from 2017 and am facing the same issue at the moment, but at a smaller scale.

**Comment by evolross** [comment]
Yes I solved it... I had to manually hack `service-configuration` out of `accounts-base` (this is what powers Meteor's accounts). I don't use any service configurations at all in this particular app (e.g. no log in with Facebook, Google, etc.) but `accounts-base` automatically includes the `service-configuration` package which will create this blocking publication (even though it's not used!) (I'm meaning to maybe create a Meteor PR to more intelligently add `service-configuration` to side-step this issue).

So I created a local, custom version of `accounts-base` with `service-configuration` completely removed and that removes this publication.

To remove the `meteor_autoupdate_clientVersions` publication (which is what allows your app to auto reload on a code update - I also don't need this in my production app) you have to remove the `hot-code-push` and `reload` packages.

Now that these are both gone I'm not seeing any bottlenecks!
