### ISSUE TITLE
Markdown package does not support tables

### ISSUE THREAD

**Issue by fooying** [meteor/meteor#4565]
The makrdown does not support table?
I had try

|a    |b    |c    |
|-----|-----|-----|
|aaa|bbb|ccc|

and
||a    ||b    ||c   ||
||aaa||bbb||ccc||

All can't。

**Comment by glasser** [comment]
We don't really maintain this package — it's been pretty much unchanged since we imported it ages ago, and there are much better markdown implementations these days.  We really only keep this one around because we use it on the docs site and haven't had time to port it to something better yet. I'd recommend looking on [Atmosphere](https://atmospherejs.com/?q=markdown) for a more maintained and modern Markdown package.
