### ISSUE TITLE
Selecting a very old version of kadira

### ISSUE THREAD

**Issue by arunoda** [meteor/meteor#4623]
**_1 Upvote**_ This happens on the latest Meteor version (1.1.0.2). 
I don't know whether this is happening on all platforms, but the errors being reported on windows consistently.

Our current [kadira](https://github.com/meteorhacks/kadira/blob/master/package.js) package version is `2.22.0`. But when users installed it via `meteor add meteorhacks:kadira` it sometimes they get a very old version. That version had some incompatibility with windows and cause issues.

> It's possible this is happening in Mac/Linux, but since it doesn't throw any errors users have no idea of it

But when we do `meteor add meteorhacks:kadira@2.22.0` it works pretty well.

Here's one such case: https://github.com/meteorhacks/kadira/issues/169#issuecomment-115101096

> This is just a one. But I receive a lot of requests in our support forum.

I can't recreate this issues and wanna know why is this happening?

If we couldn't find a cause for this, I'll have ask users to install `meteor add meteorhacks:kadira@<version>`. But that's ugly and I hope we don't need such with the version-solver.

**Comment by robertpitt** [comment]
I also run into this issue quite a lot, I tend to build my applications using packages only, and within packages doing the following sometimes results in old package versions:

```js
api.use("namespace:package");
```

I think this is problem/feature with the Logic Solver / Version Constraint Solver, which takes all the dependencies for your project, and tries to figure out the best version number that fit's all dependencies.

Take a look at @dgreensp 's DevShop about how this all works

https://www.youtube.com/watch?v=IWSaZfSVnFM

**Comment by arunoda** [comment]
It's not a feature and it should not select a older version of the package.

**Comment by robertpitt** [comment]
If you watched the video you should see that while it's unlikely to select an older version of a package it's not impossible.

Im going to leave this down to David to answer but IMO, I would like to see some way of highlighting when a package that has been added has been downgraded or upgraded.

**Comment by rclai** [comment]
Glad to see I wasn't the only one having this issue.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

This does sound like a problem.  We should be preferring the newest version by default.

But there are other things that are relevant.  eg, I think we try to minimize how much we have to upgrade existing packages with a higher priority than preferring newest version for the new package.  The idea being that it's more important to not break your app than to have the newest version of the new package.  https://github.com/meteor/meteor/blob/devel/packages/constraint-solver/solver.js#L712-L835 shows the order of preference from highest to least.  So ie what's happening is that Meteor is noticing that your app is using some ancient packages and is giving you a matching ancient Kadira instead of making a bunch of potentially incompatible changes to those packages.

If you provide a reproduction we would be able to see what is going on here.

**Comment by arunoda** [comment]
Okay. I'll try to do a re-production but unfortunately, I can't do it my self. It seems like this happens for new meteor installations. I'll give it a try.

Anyway, we don't use ancient packages. We use [packages](https://github.com/meteorhacks/kadira/blob/master/package.js#L84) from Meteor @1.0 - I hope 1.0 is not ancient :)

**Comment by dandv** [comment]
I've run into this a bunch of times as well - older packages selected as indirect dependencies.

I have a model package that depends on aldeed:simple-schema and is used by a frontend ap and a backend app. One app got v1.3.0, the other v1.3.3. I think this is bug #4170.

**Comment by derwaldgeist** [comment]
This also happens on MacOS, not only on Windows. I haven't had this problem with kadira, but with other packages like edgee:slingshot, see https://github.com/meteor/meteor/issues/5101. And it definitely not only occured when I imported the package in one of my own packages (i.e. #4170), but also when I added the package on the top level using ```meteor add```. So although #5101 was closed as being a presumed dup of #4170, I can confirm it is not. And I think this issue here is also one of these cases.

**Comment by krizka** [comment]
Hello. It's now very annoying and critical bug. And leads to many unpredictable errors with older package versions.
reproduction:
```
# meteor create version-bug && cd version-bug
# meteor create --package test
```
Add (for example) ```api.use('aldeed:collection2');``` to package.js, the latest version is 2.5.0
```
# meteor add test
Changes to your project's package version selections:
aldeed:collection2  added, version 0.1.7
test                added, version 0.0.1
```
Run meteor add for aldeed:collection2: 
```
# meteor add aldeed:collection2
aldeed:collection2: INCOMPATIBLE WITH METEOR 0.9.0 OR LATER
```
Please, fix it.

**Comment by egoldblum** [comment]
+1

I've wasted time debugging unexpected behavior when working in a large, package-heavy application.

At minimum, I'd appreciate much more verbosity when the constraint solver selects package versions that are major (or any!) package revisions behind the newest.

**Comment by rgstephens** [comment]
I've just run into this adding angular:angular-animate.  It's giving me version 1.3.15_1 from April 2015 which is 10 versions and 10 months old.

**Comment by lanmower** [comment]
Just ran into this myself, please fix, happening with alanning:roles referenced from any package.

**Comment by hwillson** [comment]
This is functioning as designed. For a detailed explanation of what's happening, see https://meteor.hackpad.com/Packaging-UX-Gravity-Hurts-FoTnLTVUklt. While the cases of this being an issue should be minimal, it can still happen. There are currently no plans to change this, but if anyone is interested in championing a feature request for this (over at https://github.com/meteor/meteor-feature-requests), that would be great! Closing for now - thanks!
