### ISSUE TITLE
In-browser developer tools for Meteor

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4628]
It'd be really nice to have a tool like [Batarang ](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk)

**Comment by martijnwalraven** [comment]
Thanks for the feature request, something like this would indeed be awesome! It seems this could potentially make a good addition to be worked on by the community. We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

Note that you will be able to use Batarang if you're using the `angular-meteor` package (see https://www.meteor.com/tutorials/angular/creating-an-app).

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/4628#issuecomment-117340468, in-browser Meteor developer tools can be implemented outside of Meteor itself. Here are a few examples:

- [Meteor Toys](http://meteor.toys)
- [Meteor DevTools](https://chrome.google.com/webstore/detail/meteor-devtools/ippapidnnboiophakmmhkdlchoccbgje)
- [Meteor MiniMongo Explorer](https://chrome.google.com/webstore/detail/meteor-minimongo-explorer/bpbalpgdnkieljogofnfjmgcnjcaiheg)

Since you mentioned the example of [Batarang](https://github.com/angular/batarang) which is Angular specific, I'll just note that the devtools for other view layers supported by Meteor (e.g. [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)) will work as well.

Thanks!
