### ISSUE TITLE
Add in support for a logging/stats mode to get counts of DDP method calls

### ISSUE THREAD

**Issue by anubhav94** [meteor/meteor#4652]
Add in ability for users to know which DDP methods are being called and drill down for counts per IP, per user, etc. We need this ability so that users can know what to realistically set their rate limits to without adding in rate limiting and then realizing they've made major impacts to the users. A 'testMode' feature could also be useful to get this information when running the app. See discussion on this [hackpad](https://meteor.hackpad.com/Proposal-Rate-Limiting-in-Meteor-core-HJafA26QtIy).

**Comment by serkandurusoy** [comment]
This can even lead to an *adaptive limiting* feature where we can possibly keep a time based mean/average on methods, as well as allowed deviations, over which the rate limiter can adaptively block method calls which exceed *current thresholds*.

I guess this boils down to the rate limiter having an API that allows extensions.

**Comment by stubailo** [comment]
I think this could also be a good use case for a general "method hook" feature - if you could easily add a function to run before/after every method, it would be simple to add logging or analytics.

**Comment by serkandurusoy** [comment]
@stubailo do you have anything in mind? Anything that's perhaps not covered by this:

https://github.com/workpop/meteor-method-hooks/

**Comment by sebakerckhof** [comment]
@serkandurusoy Meteor method hooks work by wrapping the original method. The problem is that this way you can't have wildcards. E.g. I can't add a hook that will be called for each method, but instead I have to add the hook for each and every method. Things like logging you typically want to happen for every method, and therefore wildcards are a must-have.

**Comment by hwillson** [comment]
Hi all - as part of the old issue cleanup process, I think we can safely close this issue. Packages like the linked to [Workpop Meteor Method Hooks](https://github.com/Workpop/meteor-method-hooks) package show that this functionality can be completely implemented as a separate package, that sits outside of (and can be maintained separately from) the Meteor core. Also, relating to the issues outlined in https://github.com/meteor/meteor/issues/4652#issuecomment-117663298, @sebakerckhof  has gratefully extended the original Method Hooks package to address these concerns (see [seba:method-hooks](https://atmospherejs.com/seba/method-hooks)). Happy to re-open this issue if anyone feels differently. Thanks!

**Comment by mitar** [comment]
But this hooking through modifying internals is pretty ugly. Also, to my understanding and experience, method hooks only work *after* rate limiting (only if method is really called). So you cannot setup logging to get information both about when call is made and then allowed or disallowed by rate limiting. This prevents logging attacks.

**Comment by sebakerckhof** [comment]
@mitar, would this do what you want:

```js
Meteor.server.stream_server.register(function(socket){
  socket.on('data',function(raw_msg){
    console.log(raw_msg)
  });
```

**Comment by hwillson** [comment]
Thanks @mitar - I agree, this approach can definitely be ugly. Since we're trying to close off old issues, I'm being pretty hard-lined with regards to following the outlined [triage process](https://github.com/meteor/meteor/blob/devel/IssueTriageFlow.png). I closed this issue since it can be (and has been) handled by a third party package (and because of the lack of interest/attention in > 1.5 years). It would be great to see this as part of the core though (and the code/process would likely be much cleaner), so if anyone feels like making this a reality let me know and I'll re-open this issue. In the meantime the external package approaches work, and as @sebakerckhof mentioned, you can intercept the raw DDP message on the server right after it's received, to handle any additional before rate-limiting checks. Thanks!
