### ISSUE TITLE
Log out user if their user record is deleted

### ISSUE THREAD

**Issue by westlakem** [meteor/meteor#4682]
when the user record is deleted from the database, the user isn't logged out.  They are still able to perform functions as if they were a logged in user.

Reproduction steps:

1. Create a meteor app
2. Include the accounts & accounts-ui packages
3. Start your App
4. Create a user (admin, admin1 for example)
5. Remove insecure/autopublish
6. Create a pub/sub that requires login (using 'Meteor.userId() != null')
7. Login to your site & go to page where login is required to see data
8. Open your mongodb instance ('meteor mongo')
9. Remove user records ('db.users.remove({})')
10. You are still able to access the data as if you were logged in.

If you have allow/deny setup for writes, it will also continue to work.

Recommendation:
Authenticate every time a 'Meteor.user' call is made.

**Comment by stubailo** [comment]
I think the main reason here is that `this.userId` and `Meteor.userId()` don't actually look in the collection; `userId` is a property of a DDP connection that is independent of the database, `accounts` packages, etc.

Gathering more info now.

**Comment by stubailo** [comment]
Ah, OK - I talked to some people and this issue was identified and resolved as far back as Meteor 0.6.6: https://github.com/meteor/meteor/blob/devel/History.md#accounts

There might be some details missing from the reproduction. Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by rclai** [comment]
There was some issue sitting around regarding this. You have to `this.setUserId(null)` in your method or something like that.

**Comment by westlakem** [comment]
@rclai I'm not using a method...  What I'm talking about is if someone's already logged in and I delete their user record, they're still logged into the app.
