### ISSUE TITLE
Need additional description about Nested Helper in documentation.

### ISSUE THREAD

**Issue by barkbaek** [meteor/meteor#4691]
In Spacebars README,

<a href="https://atmospherejs.com/meteor/spacebars">
Nested Helper: If there is a positional argument followed by other
(positional or keyword arguments), the first argument is called on the others
using the normal helper argument calling convention.
</a>

Is the first argument a positional argument ?
and why the first argument is called on the other positional or keyword arguments ?

I attempted to understand this but I can't.
Can you please describe more about this ? or give examples ?

**Comment by stubailo** [comment]
We should add an example there, but what it means is:

`{{#with helper x=1 y=2}}` will set the data context to `helper x=1 y=2`. Basically, it means that you can't pass positional arguments to `with` or a template inclusion.

I agree this is confusing, especially since it's not obvious that helpers can even have keyword arguments.

**Comment by hwillson** [comment]
Moved over to meteor/blaze#216 - closing here - thanks!
