### ISSUE TITLE
files.cp_r throws ENOENT when trying to copy symlink that links to a non existing file

### ISSUE THREAD

**Issue by Sanjo** [meteor/meteor#4692]
files.cp_r throws ENOENT when trying to copy symlink that links to a non existing file. I think instead it should ignore or copy the broken symlink.

**Comment by stubailo** [comment]
@Sanjo I think the `files` code is not intended to be a supported part of the Meteor API, and only exists as a convenience file for the Meteor tool code.

That being said, I agree that it would be good to have an option to `cp_r` to specify this behaviour if you need it for Velocity or similar. Feel free to submit a pull request adding this option.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by Sanjo** [comment]
Turns out that `options.preserveSymlinks = true` does what I want without error.

I'm not sure if you generally want to that files.cp_r throws when you try to copy a broken symlink. You could use `files.statOrNull` instead of `files.stat` here (https://github.com/meteor/meteor/blob/df4eecbac7ade7ad474306c4fcb9638fef3b3eee/tools/fs/files.js#L456) to not throw. I leave it up to you. I think currently you don't have this case.

It seems though that the node_modules/.bin folder sometimes still contain symlinks of node_modules that have been removed. Should I open a new issue for that?

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/4692#issuecomment-119340110, the [fies](https://github.com/meteor/meteor/blob/1b456d41a2de9137e75e5a3e43bfecbe449255f9/tools/fs/files.js) code is really just a bunch of internal utility functions used by the build tool. As such, the likelihood of anyone running into this issue is quite low, and using `options.preserveSymlinks = true` prevents this issue from happening (see https://github.com/meteor/meteor/issues/4692#issuecomment-127496904). Given all of this, and the low activity/interest in this issue in quite a while, I'll close it off. Thanks for reporting this originally!
