### ISSUE TITLE
Generated asset json object in program.json is incorrect after a meteor build under special cases

### ISSUE THREAD

**Issue by oliroy** [meteor/meteor#4712]
This issue pretains to Meteor 1.1.0.2.

We have two assets (plain old files) in the private folder named exactly:

pushNotificationCert.pem
pushNotificationKey.pem

These files are added to our CI server.  When we do meteor build on our CI server the generated app and accompanying program.json contain incorrect mappings such as:

    {
      "path": "app/lib/main.js",
      "assets": {
        "pushNotificationCert.pem": "assets/app/pushNotificationCert.pem",
        "pushNotificationKey.pem": "assets/app/pushNotificationCert.pem",

Both key and cert point to the same file in the assets folder though they are different files in the private folder.  When we use Asset.get('pushNotificationCert.pem') && Asset.get('pushNotificationKey.pem') we get the same file back as per mappings in program.json.  Not sure why this would happen.  Renaming the files to something more distinct resolves this issue.

Please advise.

**Comment by glasser** [comment]
This is working as intended. I forget why, but in https://github.com/meteor/meteor/commit/9538bec6852814c61bee2f8a62f263465c0f558e I apparently decided it would a good idea to de-duplicate assets based on contents.  Because the only supported APIs available for assets read the content, this should be a safe optimization... unless you take the build output and modify it, which it sounds like you do.  So as a workaround, just make sure the two files you're going to replace have distinct contents from each other and other assets in your app.

**Comment by ubald** [comment]
I spent all day trying to figure out why I was missing files in my assets directory because of this.

I understand that the assets api is "smart" enough to use the manifest but I'm using https://github.com/niftylettuce/node-email-templates which requires me to pass a directory containing all the template files to it so that it can load it itself. The problem is that all the mandatory ```style.less``` files are just containing one line for the moment ```@require "../common.less``` so they appear identical to meteor...

I'll just add a different comment/rant with a link to this issue in every template file then :P
