### ISSUE TITLE
Meteor not recognizing Xcode Version 7.0 beta 3 (7A152u)

### ISSUE THREAD

**Issue by connorblack** [meteor/meteor#4725]
I recently upgraded my Xcode from version 6 to version 7 and it's seems like meteor isn't picking up on it. Whenever `meteor run ios` is run, meteor responds with this:
```
The iOS platform is not installed; please run: meteor install-sdk ios
```
 Same deal with `meteor run ios-device`.

Is there anyway to configure meteor to look for Xcode 7? 

Thanks.

**Comment by martijnwalraven** [comment]
The current version of the Cordova integration does not support running beta versions of Xcode, because it explicitly checks for the existence of `Xcode.app` in `/Applications`. [I'm working on some improvements that I hope to get into the Meteor 1.2 release](https://forums.meteor.com/t/improvements-to-mobile-support/6817), and that should also allow you to run different versions of Xcode (using `xcode-select` to choose between them).

**Comment by sorenriise** [comment]
I downgraded from Xcode7 to Xcode 6.4 -- and now I get that "The device [iOS9] is not supported by this version" -- hence the old compiler no longer works, and the new xcode7 does not work either?

**Comment by martijnwalraven** [comment]
Xcode 7 should definitely work, just not the beta versions. I think it should work with Meteor 1.1.0.3 as well, but if you haven't done so already you might want to try Meteor 1.2, because there have been quite a few improvements to the Cordova integration.

**Comment by cyounghusband** [comment]
Not working for me since I upgraded to Xcode 7.
I tried removing the platform, and then re-adding it, but running it does not seem to work.   Seems to be a problem with the IOS sim detection  Suggestions welcome!
% meteor --version
Meteor 1.2.0.1    
                      
% xcodebuild -version
Xcode 7.0
Build version 7A220

% meteor run ios-device --verbose
Getting installed version for platform ios in Cordova project
Checking Cordova requirements for platform iOS
                                              
Your system does not yet seem to fulfill all requirements to build apps for iOS.
                                              
Please follow the installation instructions here:
https://github.com/meteor/meteor/wiki/Mobile-Development-Install:-iOS-on-Mac
                                              
Status of the requirements:                   
✓ Apple OS X                                  
✓ Xcode                                       
✗ ios-sim: simctl was not found.              
  Check that you have Xcode 6.x installed:
  xcodebuild --versionCheck that you have Xcode 6.x selected:
  xcode-select --print-path

% xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

Yet the  /Applications/Xcode.app/Contents//Developer/usr/bin/simctl binary is there.  I've tried messing with the paths but it does seem like it is set correctly.

**Comment by teknologist** [comment]
Had a similar issue when upgrading to Xcode 7. The problem is that I needed to start Xcode once to "Accept license". Once I did that, the error disappeared. Hope this helps.

**Comment by cyounghusband** [comment]
Hi Eric -- thanks for the note.  I thought you caught the brief period where I had posted in this thread and before I deleted my post a few minutes later  -- and you are exactly right that I had not accepted the new license so it failed.

**Comment by teknologist** [comment]
@cyounghusband Glad I could help.
