### ISSUE TITLE
A callback event after DOM is updated

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#4731]
***7 Upvotes*** *please feel free to close this issue if this request is invalid or I neglected an already-existing feature*

We need something better than `onRendered` that is called everytime a DOM is updated.

Given the following code:

```
<template name="FrameItems">
  {{#each frames}}
    <div id="frame-{{_id}}" class="frame-preview-item cyan lighten-5">
      <div class='frame-name'>{{name}}</div>
      <div class="ep"></div>
    </div>
  {{/each}}
</template>
```

and the helper function

```
  Template.FrameItems.helpers({
    frames: function() {
      var trialId = Session.get('trialId');
      return Frames.find({trialId: trialId});
    }
  });
```

DOM is updated every time `frames` helper function is re-run, but `onRendered()` only gets called once when the template was initially constructed. What if you want to update the DOM every time `frames` helper function returns new set of `.frame-preview-item`? On StackOverflow and Google Groups, people have been suggesting to use `Meteor.defer()`. However, since it's basically same as `setTimeout` it's not called exactly when the new frames are inserted (i.e. it's slower than `onRendered` callback). To solve this problem, I used `Blaze.remove` and `Blaze.render` to destroy `FrameItems` and insert them manually (not using `{{> frameItems}}`) every time `frames` is updated, so that I can use the `onRendered` callback.

This seems to be a common use case and I wonder if Meteor yet supports a clean way to deal with this.
These are links to posts asking how to do this:

http://stackoverflow.com/questions/10109788/callback-after-the-dom-was-updated-in-meteor-js
https://groups.google.com/forum/#!topic/meteor-talk/TMf4RLfQK_w
http://stackoverflow.com/questions/17584522/how-to-make-a-meteor-template-helper-re-run-render-after-another-template-has-re
http://stackoverflow.com/questions/31353120/run-a-function-after-dom-is-updated-from-a-helper-function/31353151?noredirect=1#comment50720195_31353151

**Comment by murillo128** [comment]
Use Tracker.flush() after changing frames, it will force all the reactive
changes to be applied and DOM changed.

Best regards
Sergio

**Comment by woniesong92** [comment]
@murillo128 Could you elaborate? I am not sure how that solves the problem.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I suspect one thing you can do here is make the body of the `{{#each}}` invoke another template and put an `onRendered` on that template?

**Comment by woniesong92** [comment]
@glasser Thanks! The problem with that is if you need to perform a batch action on all the items after they are ready, then you have no use of using `onRendered` on that template.

**Comment by iSuslov** [comment]
+1, I need to render messages list and after it actually rendered/updated I need to scroll to specific message. It is impossible now. 
https://stackoverflow.com/questions/30448656/meteor-each-loop-ready/30491915#30491915

**Comment by datanotion** [comment]
+1 It would be even nicer (for us) if we could apply it to only a certain parent template, so we were not getting flooded with DOM update messages across the entire app.  Template.myParentTemplate.onChildRendered ...

**Comment by woniesong92** [comment]
@glasser do you think I can work on it and submit a PR?

**Comment by avalanche1** [comment]
+1

**Comment by mitar** [comment]
In [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) you have an API which calls methods when DOM is inserted, moved, or removed. You can [see here](https://github.com/peerlibrary/meteor-blaze-components/blob/master/tests/tests.coffee#L465) how to make an reactive variable when DOM changes.

The downside with this approach is that it does not change when DOM element attributes change (like `class` change). Only when DOM elements themselves are changed. This works for most cases, but if you need the second, I suggest you simply use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). In this case you will be able to respond also to outside changes.

**Comment by zorro765** [comment]
+1

**Comment by mkvaghani** [comment]
Must needed !

**Comment by Szayet** [comment]
+1

**Comment by filipenevola** [comment]
+1

**Comment by dbradleyfl** [comment]
+1

**Comment by mitar** [comment]
So what is wrong with mutation observes for this?

**Comment by dbradleyfl** [comment]
@mitar I have a class in my app that is changed by a helper ie:
`<a class="my-class-{{helperReturnsNumber}}">link</a>`
When the data that effects "helperReturnsNumber" is changed, Meteor updates the dom. I tried to use MutationObserver() to watch for changes but they were never captured by MutationObserver(). I simply put a console.log in MutationObserver and watched for all changes, and at the same time logged "helperReturnsNumber" from the dom with a helper. The dom helper always was the last thing to return. Thats my issue personally. I can't figure out why.

That said, this is a necessary feature because it should be easier to do something after the update, ie animate a div after the data inside the div's class has changed (to make it blink or spin or something). I'd like to see a, Template.templateName.onUpdateCompleted(), where the callback is run after the DOM is updated by meteor. To my knowledge, onRendered() is only called once. onUpdateComplete() would run after every time meteor updates the templates dom.

Got into a bit of a scatter brained rant there, but hopefully it makes some sense and is helpful in deciding if this should be a feature...

**Comment by mitar** [comment]
So, for animation there are already hooks available in Blaze since 0.8.2. See here: https://stackoverflow.com/questions/26833596/meteor-js-unrendered-hook

This package wraps it into a nice API: https://atmospherejs.com/percolate/momentum

Blaze Components exposes them through a [simpler API](https://github.com/peerlibrary/meteor-blaze-components#animations).

**Comment by kcrawford** [comment]
+1

**Comment by laosb** [comment]
I found this helpful since I've been using TinyMCE these days.

In my app, *new article* and *edit article* functionalities shares the the same template. So when a user switches from an *edit article* page to *new article* page, actually only the data for the template was changed. But the content to edit was changed in fact, so we need to re-init the TinyMCE editor after the helper caused the DOM update.

**Comment by avalanche1** [comment]
this sd be moved to https://github.com/meteor/blaze

**Comment by laosb** [comment]
Yeah, totally.

**Comment by laosb** [comment]
Closing this and please go to meteor/blaze#53 for further discussions!
