### ISSUE TITLE
Docs: Give examples of accessing filesystem on localhost and in production

### ISSUE THREAD

**Issue by keyscores** [meteor/meteor#4734]
It's very difficult to find documentation on the meteor directory structure, especially local vs production.
I stumbled on this post which is incomplete.
http://stackoverflow.com/questions/17328807/what-is-the-meteor-server-side-path-to-public

The last post seems to be the best way: path.join(**meteor_bootstrap**.serverDir, "../web.browser/app");

 Though, I wish there was a canonical way (MDG) of doing this.

This issue originated with this use-case:
http://stackoverflow.com/questions/31362749/meteor-js-serve-static-files-and-persist-query-string/31363579#31363579

**Comment by stubailo** [comment]
Have you seen the `Assets` API? It does pretty much exactly this: http://docs.meteor.com/#/full/assets_getText

**Comment by keyscores** [comment]
Not quite what I'm looking for. If you see the Stack Overflow use case, I need to get the absolute path of the the assets folder for prod and dev.

**Comment by rfox90** [comment]
@keyscores In your stackoverflow example try changing "/public" to "./public"

dot slash means "in the current working directory". Without the slash you are accessing /public/ in the root of your filesystem. 

You won't need the full path this way. fs will know how to get there!

**Comment by keyscores** [comment]
thanks @rfox90 
I'm perplexed. I have tried every possible combination: 'public/', './public' with no change in error code. Also tried chmod 666 everywhere.

This works:
     PATH_FOR_YOUR_APP = path.join(__meteor_bootstrap__.serverDir, "../web.browser/app") 

But IMO it's an ugly hack. However others have proposed it on SO. So it seems to be a recurring issue.

Could this be OS-specific? I'm on OSX yosemite.

**Comment by rfox90** [comment]
Try this:
```
var meteorRoot = fs.realpathSync( process.cwd() + '/../' );
var publicPath = meteorRoot + '/web.browser/app/';
```
To get the equivalent of what you have. I do strongly reccomend CFS though!

**Comment by keyscores** [comment]
@rfox90 Yeah that should work.
@stubailo It seems that fs.readdirSync('./public/'); used to work up to meteor 0.6 . 
Should this be ticketed as a bug?

**Comment by stubailo** [comment]
@keyscores no, accessing source files using `fs` is not part of the Meteor API, so the fact that it changed isn't technically a bug. This is more of a feature request for being able to have a standard way to access app source files.

**Comment by keyscores** [comment]
Ok I understand. Would be very helpful to add this feature. Seems like lots of developers are trying to find ways around this. Just stumbled on another attempt:
var basepath = path.resolve('.').split('.meteor')[0];

ref: https://github.com/netanelgilad/meteor-excel/

**Comment by hwillson** [comment]
Since accessing the filesystem directly is not part of the current Meteor API's, and there are currently no plans to add support for this (since it can be handled by using Node's built in [file system support](https://nodejs.org/docs/v4.6.1/api/fs.html) and one of the options listed in this issue thread), I'll close this issue. Let me know if anyone disagrees (we're trying to clear out some of the older issues, and this one has had very little activity in >1.5 years). Thanks!

P.S. --> For reference, the solution mentioned in https://github.com/meteor/meteor/issues/4734#issuecomment-121002618 is probably the most popular, but the code sample isn't quite right; it should read:

```js
path.join(__meteor_bootstrap__.serverDir, '../web.browser/app');
```

If people prefer not to use magic Meteor variables, you can see how `__meteor_bootstrap__` is being set [here](https://github.com/meteor/meteor/blob/60c01002fcac340d8bc2776815d444173e7e9ee8/tools/static-assets/server/boot.js#L23-L34).

**Comment by Smudge-clark** [comment]
> Try this:
> 
> ```
> var meteorRoot = fs.realpathSync( process.cwd() + '/../' );
> var publicPath = meteorRoot + '/web.browser/app/';
> ```
> 
> To get the equivalent of what you have. I do strongly reccomend CFS though!





https://vcalendar275.github.io/cheering/
