### ISSUE TITLE
Why does an undefined argument to Meteor.subscribe become null in a publish function?

### ISSUE THREAD

**Issue by hockeyj85** [meteor/meteor#4742]
Why is it that when I call `Meteor.subscribe` on the client and pass in `undefined` as an argument that it becomes `null` in the publish function on the server whereas calling `Meteor.subscribe` without any arguments gives `undefined` arguments?

ie. If this publication exists on the server:

``` JavaScript
Meteor.publish('publication', function(arg) {
  console.log(arg);
  ...
}
```

Then:  

``` JavaScript
Meteor.subscribe('publication');
```

Outputs `undefined` on server, whereas:

``` JavaScript
Meteor.subscribe('publication', undefined);
```

Outputs `null` on the server

**Comment by stubailo** [comment]
#3877 is related, although I wouldn't go as far as saying it's a duplicate.

**Comment by abernix** [comment]
Thanks for opening this originally.  Please see https://github.com/meteor/meteor/issues/5097#issuecomment-265784532 for a very clear explanation by @hwillson.

**Comment by zimme** [comment]
@abernix, I don't see how that comment it related to this issue. That comment was in regards to how query observers are setup now how a publications arguments become `null` when `undefined` is defined for the subscription of that publication.

**Comment by zimme** [comment]
I'm pretty sure this is related to the issue @stubailo linked to and the reason you get null in this case is because undefined can't be JSON serializable.

So the fix might be to check for `undefined` and remove, or add `undefined` support in ejson which i believe Meteor is using.

**Comment by abernix** [comment]
@zimme I was closing a few similar issues together and my referral to that issue was a little bit vague, I agree.

The part of that comment I was referring to was the part about `undefined` not being serializable, which seems to be your prognosis as well.  I think #3877 might cover the core problem here, but if you disagree, I'm happy to reopen this.  Maybe this should be worked into that issue?  Ultimately if we agree it's the same problem I'd be in favor of merging.

**Comment by zimme** [comment]
No problem, I must have missed that part of the comment.

Anyways, let's see what becomes of #3877 and take it from there.
