### ISSUE TITLE
Meteor - Cant Render Headers - Fatal Error

### ISSUE THREAD

**Issue by harryward** [meteor/meteor#4750]
I have a recurring fatal error (every couple hours) on my meteor app. (server: Digital Ocean)

previous notes point at missing file references, I have triple checked that I don't have any missing files referenced at all.

Here is what i'm getting:

<img src="http://api.harryward.biz/bwJP/Screen%20Shot%202015-07-11%20at%204.22.12%20PM.png">

Please help!

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor Without a way to replicate your problem, we can't debug and fix it.

That said, I think I can understand what is happening here.  It looks like this is an error handling error: There's an underlying error occurring for some reason, and then we're crashing because we're cleaning up a resource incorrectly.  I'll push a change that should improve it.

**Comment by harryward** [comment]
Appreciate it
