### ISSUE TITLE
bindEnvironment messes up Promise chains

### ISSUE THREAD

**Issue by lourd** [meteor/meteor#4760]
`Meteor.bindEnvironment` causes functions that return promises to resolve to `undefined`, but _only_ when chained together. Paste the following code into the server shell of a running Meteor application that has `grigio:babel` as an installed package:

```js
var count = 0;
function foo() {
  count++;
  return Promise.resolve(count); 
}

foo().then( Meteor.bindEnvironment( function(res) {
  console.log("res is", res);
  return foo();
})).then( function(res2) {
  console.log("res 2 is", res2);
  return foo();
}).then( function(res3) {
  console.log('res 3 is', res3);
});
```

The console shows
```sh
res is 1
res2 is undefined # should be 2
res3 is 3
```

It's very peculiar that this works just fine though
```js
var foo = Meteor.bindEnvironment( function() { return Promise.resolve(2); });
var promise = foo();
promise.then(console.log);
// -> 2
```

**Comment by lourd** [comment]
The workaround isn't too bad. Instead of chaining after the `bindEnvironment`, you just don't return from the bound function, continuing the chain within it

```js
foo().then( Meteor.bindEnvironment( function(res) {
  console.log("res is", res);
  foo().then( function(res2) {
    console.log("res 2 is", res2);
    return foo();
  }).then( function(res3) {
    console.log('res 3 is', res3);
  });
}));
```

Doesn't mean it's not worth fixing though! :wink:

**Comment by glasser** [comment]
In Node, a function wrapped with `bindEnvironment` returns the return value of the wrapped function if it is called inside a Fiber, and doesn't if it's not. That's because it doesn't really have a choice — if it isn't run inside a Fiber, then it can't run the wrapped function past yields to completion.  Your "peculiar" example is probably within a Fiber and the Promise callbacks probably call it outside of a Fiber.

I'm glad you have a workaround.  We've been experimenting with moving Meteor more towards being natively based around Promises instead of Fibers, with a nice layer connecting the two.  Hopefully in the future, you'll be able to use Meteor server-side APIs that currently require to be run in a Fiber without being in a Fiber, and we'll stop requiring bindEnvironment at all.  Or alternatively, we might be able to use new Node 0.12 APIs to automatically put all code in Fibers, assuming it doesn't ruin performance.

**Comment by lourd** [comment]
Right, calling `bindEnvironment` doesn't even work if you're not in a Fiber. Regardless, the return value of the function isn't changing -- it's still a Promise. It's the value that the Promise resolves to that's different.

Both the "peculiar" example and the first example are within a Fiber. You can see this by making a new project, adding Babel, and running that code in a file for the server. The evaluation of the function given to the first `then` happens synchronously. This is equivalent:

```js
const boundFunc = Meteor.bindEnvironment((res) => {
  console.log("res is", res);
  return foo();
});

foo()
.then(boundFunc)
.then((res2) => {
  console.log("res 2 is", res2);
  return foo();
})
.then((res3) => {
  console.log('res 3 is', res3);
});
```

So I'm not quite sure why you closed the issue, as the actual problem wasn't solved.

Looking forward to 1.2 and beyond... our main package uses `bindEnvironment` 81 times right now. Looking forward to getting to drop those :smile:

**Comment by glasser** [comment]
No, I'm not talking about *calling* Meteor.bindEnvironment outside of a Fiber.  I'm talking about, with:

```js
var boundFunction = Meteor.bindEnvironment(func);
```

calling `boundFunction` outside of a Fiber. It is not possible for `boundFunction` to return the return value of `func` if `boundFunction` isn't invoked in a Fiber, because it cannot yield and wait for `func` to finish.

I'm sorry that the Fiber paradigm isn't compatible with `Promise#then`, but `then` callbacks are, if I understand it correctly, (a) called at a top-level context where there isn't a Fiber available and (b) care about the synchronous return value of the callback.  That's just not going to work.  I'm sorry that the two paradigms don't work well together; I recognize that lots of people like Promises, but the solution is to make Meteor APIs support Promises natively, not to figure out how to tweak bindEnvironment in impossible ways to work with it.

**Comment by lourd** [comment]
Ah ok

> `then` callbacks are, if I understand it correctly, (a) called at a top-level context where there isn't a Fiber available and (b) care about the synchronous return value of the callback. That's just not going to work.

That's what I wasn't understanding and wondering about. 

Agreed on the direction of work. Thanks for the clarification.

**Comment by benjamn** [comment]
@lourd Meteor 1.2 will support an [`ecmascript` package](https://github.com/meteor/meteor/tree/devel/packages/ecmascript), and along with it a version of the `Promise` constructor that runs all its `.then` callbacks in `Fiber`s, as if `Meteor.bindEnvironment` had been called (though it will preserve the environment more cheaply, without actually calling `Meteor.bindEnvironment`). You will still be able to use `Meteor.bindEnvironment` explicitly to bind a different environment, but I've found that case to be extremely rare.

Here's the repository for that: https://github.com/meteor/promise

The trick that allows this to work is overriding `Promise.prototype.then` so that it wraps the given callbacks with a function that runs the original callback in a `Fiber`. The `Fiber`s are are drawn from a [pool](https://github.com/meteor/promise/blob/master/fiber_pool.js), so that you only ever need as many `Fiber`s as you have simultaneous `Promise` callbacks. [Here](https://github.com/meteor/promise/blob/1e52f297b02ea83e7fb48ba4c2b17d3b4503c001/promise_server.js#L6-L34)'s where that magic happens.

Actually, come to think of it, you can already `meteor add promise`, though I would still consider it somewhat experimental (and would appreciate any feedback!): https://atmospherejs.com/meteor/promise
