### ISSUE TITLE
Run on different port if default port is in use

### ISSUE THREAD

**Issue by fullhdpixel** [meteor/meteor#4763]
`
meteor
`

`
Can't listen on port 3000. Perhaps another Meteor is running?
`

The default port 3000 is always in use on my machine, so I always have to type: meteor --port 4000. Maybe it would be helpful if Meteor could automatically got to port 4000 if port 3000 is in use?

`
meteor
`

`
Can't listen on port 3000. Running application on port 4000 now.
`

**Comment by stubailo** [comment]
Would creating a local script to launch your app that just contains `meteor -p 4000` solve your particular issue?

**Comment by ShashankaNataraj** [comment]
@fullhdpixel I have a shell script which just does

`meteor -p 8090`

as I find 8080 is going to run into conflicts with my setup. maybe the same can help you out too.

**Comment by hwillson** [comment]
Meteor's approach to this is pretty much standard practice. It tries starting on a default port, and reports a "can't start" message if that port is busy. It then provides an option to start on any port you prefer (via `--port` or `-p`). I don't think we can expect Meteor to start guessing at other free ports to try, as what happens if the second port it tries isn't available - does it keep trying other ports? When does it stop?

Now that Meteor supports npm, I'd recommend leveraging npm's `package.json` scripts support to start Meteor with your desired port:

**package.json**

```json
...
  "scripts": {
    "start": "meteor --port 4000"
  },
...
```

then start Meteor with:

```
meteor npm start
```

Thanks for the original request, but due to a lack of support on this request, I'll close it off.
