### ISSUE TITLE
Cordova on iOS using buggy IFRAME method, Meteor Autoupdate/Proxy method prevents workaround.

### ISSUE THREAD

**Issue by thedracle** [meteor/meteor#4767]
Cordova on iOS falls back on the iFRAME method because of an issue on iOS 4.2 with deviceready not being fired:

https://github.com/becka11y/incubator-cordova-ios/blob/master/guides/Changing%20the%20JavaScript%20to%20Native%20Bridge%20Mode.md

As a result, there appears to be issues/limit to the amount of communication that can be transmitted to/from cordova:
https://github.com/litehelpers/Cordova-sqlite-storage/issues/190

The suggested workaround is to switch to the XHR method via:
cordova.exec.setJsToNativeBridgeMode(cordova.exec.jsToNativeModes.XHR_OPTIONAL_PAYLOAD);

However Meteor's autoupdate method creates a local HTTP server and proxies another subdirectory to '/', causing '!gap_exec,' which Cordova uses for XHR requests, to no longer work.

execXhr.open('HEAD', "/!gap_exec?" + (+new Date()), true);

Please help me navigate this Javascript wonderland, since this hole seems to just spiral deeper and deeper.

Any suggestions or workarounds would be greatly appreciated.

**Comment by martijnwalraven** [comment]
I hadn't encountered this issue before, but thanks for bringing it to my attention. I'm currently working on some improvements to the Cordova integration that I hope to get into Meteor 1.2.

The thread you linked to mentions that Cordova iOS 3.8.0 includes [a fix for this issue](https://issues.apache.org/jira/browse/CB-8002) that wouldn't require a change of communication mechanism. I'll be updating Cordova to the most recent version, so that may be enough to avoid the described problems.

If I find the time I'll try to look into the different bridge modes in more detail, but in [this benchmark](http://blog.persistent.info/2013/10/a-faster-uiwebview-communication.html) it seems the iframe method may actually be faster than XHR.

**Comment by thedracle** [comment]
Any ideas for the short term? I have a product release on Monday that this behavior is blocking.

I'll try some of the workarounds mentioned.

I noticed all of the divs being created, it seems like a pretty significant memory leak for the number of transactions I'm doing--- definitely it will cause a problem over prolonged use of my application.
