### ISSUE TITLE
Assets.getText not looking in the correct folder in production

### ISSUE THREAD

**Issue by zooshme** [meteor/meteor#4777]
I have included a few files in the private folder in my app and I am including them on the server with the Assets.getText method. It works fine in development but in production because the path changes due to project compilation to a standard node app Assets.getText cannot find the files anymore. After the compilation the files are at this path:

`my-app/app/programs/server/assets/app/`

but Assets.getText is still looking for the files at:

`my-app/private/`

Is this a bug or am I doing something wrong?

Thanks

**Comment by Slava** [comment]
I believe `Assets.getText` method correctly looks at the path specified in the manifest file in production. If you believe this feature is not working correctly, please post a reproduction in a form of a public github repository and steps for reproduction.

**Comment by vmatekole** [comment]
@Slava I have ran into similar issues and cannot determine how to solve this. We deploy a set of keys to access a service provider. We naturally don't check these keys in to Git but store them locally in DEV and production, under the 'private' folder . Keys are accessed by calling ``` Assets.getText('keys/api.key') ``` .

We run Docker in production - deploy the keys to a home dir and add a volume to the image to add the keys at runtime:
-v /home/core/.XXXXXXX/keys:/app/XXXXXXXXX/build/bundle/programs/server/assets/app/keys \

Unfortunately, Meteor fails to find this key, despite it being in the correct location. When we add the key to Git and build Meteor with it, the key is found. This is strange behaviour as the files are located in the same place for each case.

**Comment by Slava** [comment]
@vmatekole Meteor builds a bundle-time list of all assets that the program is allowed to access to avoid giving unrestricted read access to the folder containing app files.

**Comment by hwillson** [comment]
@vmatekole - When the Meteor Tool Isobuild system bundles your application, it generates a `programs/server/program.json` file to track certain metadata. One of the things this file tracks is a mapping of your asset names to their stored locations. When you make an `Assets.getText` call behind the scenes the path you pass in is looked up in the cached object pulled from your `program.json` file, then the matching asset path is extracted and used. Since you don't have your keys stored with your application when you build/bundle it, the necessary entries aren't create in your `program.json` file, and `Assets.getText` doesn't know where to find them.

**Comment by hwillson** [comment]
Sorry @Slava, we just posted at the same time :-).

**Comment by Slava** [comment]
A simple workaround would probably work: bundle your app with an empty file
with your private data. In the deployment, replace the file with the actual
content

**Comment by vmatekole** [comment]
@Slava. Thank you so much for your tip, will try.
