### ISSUE TITLE
Optional different package name

### ISSUE THREAD

**Issue by DerekTBrown** [meteor/meteor#4805]
Several other packaging tools use package.js.  Would it be possible for the meteor packager to use meteor.js instead, if present?

**Comment by robertpitt** [comment]
Hey @DerekTBrown, I personally have only ever seen meteor use `package.js`, and after a few minutes with some quirky Google searches `site:github.com +package.js -package.json -meteor` I cant really see any immediate evidence of any conflicts.

Can you share your examples of what other packaging tools use `package.js`.

**Comment by DerekTBrown** [comment]
A couple of the lesser NPM packages I was importing into a project used package.js instead of index.js or main .js, which I guess is not good syntax on their part.

**Comment by stubailo** [comment]
OK, I'm glad that things worked out. I think `package.js` is reasonable in a world where NPM uses `package.json`. I'm pretty sure that `index.js` is the standard entry point, at least as generated by the NPM command line tool itself.

Also, @DerekTBrown you can use NPM packages directly in a project by using `Npm.depends` inside the `package.js` file, rather than importing the source code of the package.
