### ISSUE TITLE
Have a way to subscribe to data without realtime updates

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#4814]
Docs say 

```
.stop()
Cancel the subscription. This will typically result in the server directing the client to remove
 the subscription's data from the client's cache.
```

I need a _static_ subscription, which will only serve collection data **once** per page load and then cut all ties to the server, effectively eliminating all overhead related to maintaining reactive connection.
Thus I would like `.stop()` method **not to remove subs' data**, but sever the connection to the publication instead. Is it possible?
And possibly rename current `.stop()` method to smth like `.empty()`

**Comment by mizzao** [comment]
You may find ideas/links from http://stackoverflow.com/q/18821014/586086 helpful.

**Comment by avalanche1** [comment]
Yeah, I've spent a whole day researching the best approach and currently stopped on using sending data through methods (I've posted in your SO question).
But I think that it's an upside-down approach, more like a hack.
`Meteor.subscribe .stop()` should stop the subscription instead of killing all data on the client.

**Comment by stubailo** [comment]
Yeah, right now this is not supported. Subscriptions can only publish reactive data, with all of the overhead that comes with it. Having a way to make a subscription that just loads data once and then doesn't receive updates would be really awesome.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by Slava** [comment]
I am marking this as "feature" because DDP doesn't support the concept of "static" subscriptions as of today. While I agree this is something that looks like a good idea, it is not trivial to implement to work well with the Optimistic UI features, especially given that DDP Stores are global.

I think @avital is interested in this, too.

**Comment by avalanche1** [comment]
Hmm... does this option really remove all subsctiption observers from the server? (what's known as mergebox, if I'm not mistaken)

**Comment by hwillson** [comment]
HI @avalanche1 - no it doesn't; it will just prevent any changes made to the collection that impact its cursor documents from triggering a recomputation. So once per page load you could make a `find` call with reactivity disabled, to prevent reactive updates from firing in the future. This will help reduce some client side overhead, but re-reading your original post I see that you're interested in also reducing server side overhead. If you're not interested in reactivity, and you want to get away from the extra server side overhead of publications, could you not just use a Meteor Method to load your data? The Guide's [Loading data with Methods](https://guide.meteor.com/methods.html#loading-data) section talks about the pros/cons of this approach, but one of the main pros is that you avoid the exact server overheard issues you want to avoid.

That being said, I'll re-open this since I mis-read your original post and the solution I mentioned only addresses part of your issue. Thanks!

**Comment by avalanche1** [comment]
Yep, thanks for paying attention to details!
Indeed I do use methods when I don't need reactive updates, but if I had a .stop() method to not destroy my data but simply stop the updates - I would've gladly use pub/sub API instead.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Have%20a%20way%20to%20subscribe%20to%20data%20without%20realtime%20updates&body=Migrated%20from:%20meteor/meteor%234814) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
