### ISSUE TITLE
Read Package.js description of each package from with the app

### ISSUE THREAD

**Issue by meteorplus** [meteor/meteor#4819]
Hi

I am trying to read package.js description of each package from with the app from the server side or client, is there a better way to access it rather than trying to read the package.js file with `Npm.require('readline');` because it's very messy this way.

can i add other attribute to `package.describe({//like author
'author':'me',`

Thanks

**Comment by stubailo** [comment]
This is closely related to #4267, and the combination of these two feature requests makes sense to me. If you are building a CMS or other plugin-based system, being able to distribute plugins in the form of Meteor packages makes sense, and you should be able to display which plugins are being used.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by capensisma** [comment]
Thanks for the reply, yes we are building a CMS, that's whywe need to make use of Package.js otherwise they will need to let developers provide the metadata two times in our api and in package.describe(

I see we can access Package.name-of-the-package from the client and may even get that metadata from the server side may be, but that's just hacking around it.

also a nicer feature which will help us and a lot of people is to disable/enable a package from the client, i know it's impossible since the app needs to be rebuild and deployed but for prod apps we can fake by unloading the packages files and removing it from the enabled packages list ? then hard reload.

Features Summary : 
* Package API metadata (easy to do e.g : Package.name-of-the-package will return the metadata of the package in the server side for security reasons )
* Enabling/Disabling packages from the client
* Uploading package from the client then adding it to the app (yeah it seems impossible but which not let our dream be dream :D let's DO IT, we should DO IT :) )

Awesome work guys
I Love Meteor (#nohomo) haha

**Comment by stubailo** [comment]
I think the other features are best had as separate feature requests. This conversation is solely about reading data about currently used packages from the app.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Read%20Package.js%20description%20of%20each%20package%20from%20with%20the%20app&body=Migrated%20from:%20meteor/meteor%234819) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
