### ISSUE TITLE
ES6 files in NPM package

### ISSUE THREAD

**Issue by estk** [meteor/meteor#4828]
Hey Meteor team!

Got a quick question for ya, but first here's some context.
I'm using meteor devel and have added the ecmascript plugin, I'm also using the meteorhacks:npm package to pull in a npm repo.

Is it possible to hook the ecmascript plugin into the Npm.require function so that it compiles the file before meteor attempts to wrap it in a function and run it?

Here's what's happening when I add a package that has files which are es6:

```
W20150728-12:34:14.710(-7)? (STDERR) <...>/.meteor/local/isopacks/npm-container/npm/node_modules/react-mixin-decorator/index.jsx:1
W20150728-12:34:14.710(-7)? (STDERR) (function (exports, require, module, __filename, __dirname) { import React fro
```

Seems like the issue is that you can't import or export when you are inside a function (and you are because we call node's NativeModule.wrap on the source then try to process.binding('evals').NodeScript.runInThisContext() which all seems to happens in  local/build/main.js in my project.)

Really not sure how to hook in to Meteor's new compiler logic.

**Comment by benjamn** [comment]
Files in NPM packages are supposed to be compiled (if necessary) before they are published to NPM, so I'm not sure I understand why the `ecmascript` plugin would be needed to re-compile files installed from NPM, or why the NPM package that you're adding contains ES6 files.

If you really want to compile a file from NPM, your best bet is probably to copy it into your application, so that it is treated like any other `.js` file.

**Comment by jzempel** [comment]
> Files in NPM packages are supposed to be compiled (if necessary) before they are published to NPM

I'm not sure that's a valid assumption. As ES2015 continues to catch-on, more and more NPM packages are going to be published without transpiled code (aka binaries), leaving the flexibility for a consuming app to handle the compile step with whatever tooling it prefers.

It would be great if we could get some guidance here.

**Comment by matthewforr** [comment]
Just a heads up, I've encountered this issue with the [quickbase NPM](https://www.npmjs.com/package/quickbase) library. I'm currently looking for a workaround that doesn't involve forking the library but may end up having to do that.

**Comment by michaelforrest** [comment]
I'm encountering a problem with this, trying to use @Schmoopiie's library (referenced directly above this comment). Has there been any progress on this issue?

**Comment by abernix** [comment]
#7081 brought this up recently too.  I've closed it in favor of this issue since this is older.

@michaelforrest, as I mentioned in the other issue though, modules are not implemented in any browsers natively at this time, which means transpilation is still going to be necessary for the foreseeable future – which is why tmi.js has to use browserify (or something similar) to provide their browser CDN lib (otherwise, technically, it is incompatible with all browsers)

Meteor is upgrading to Node 4 relatively soon (#6921) which will solve the server side of this.

Until ES6 support is stabilized universally, NPM package authors have to think about providing compiled packages for the platforms they want to support – browsers and servers alike.

**Comment by yanickrochon** [comment]
The fact that Meteor apps run just fine in a development environment, regardless if some npm packages have ES5 sources, should be an indicator that this is inconsistent; why would the app run fine at one place, but would fail to run in another? Saying that vendors should provide compiled modules is not the correct approach. If it runs, and if it tests, it should build.

**Comment by abhaytalreja** [comment]
Is there any way to fix it? - Any approach to debug? - Deploying for the first time and a whole app is written (not sure where to start debugging)

**Comment by abernix** [comment]
@yanickrochon I don't see a reason why you would be experiencing that problem in development and not in production, unless you're using the wrong version of Node in production.  However, I see you've opened another issue about this (#8020) so will discuss in there.

@abhaytalreja Providing any error messages that you're receiving would be a good way to start, though please do so by opening a new issue for your particular error and not on this issue (or even better, by asking for assistance on the Meteor forums if you're not sure it's actually a bug with Meteor).

**Comment by hwillson** [comment]
Hi all - as mentioned in https://github.com/meteor/meteor/issues/4828#issuecomment-125795387, for now npm packages should be compiled to ES5, before being published. In the future this won't be the case, but for now it's necessary (e.g. [no production ready web browsers currently support native `import` functionality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)). As such, and as part of the on-going old issue cleanup process, let's close this issue for now (since there isn't much we can do about it at this point). When the time comes this will definitely be re-visited. Thanks for posting this originally!

**Comment by vmatekole** [comment]
@hwillson Any timeline on this — it is increasingly becoming a problem.

**Comment by hwillson** [comment]
@vmatekole This is now being actively discussed/tracked in https://github.com/meteor/meteor-feature-requests/issues/6.
