### ISSUE TITLE
Make it less obvious from the client which packages are used in a Meteor app

### ISSUE THREAD

**Issue by meteorplus** [meteor/meteor#4831]
Hello Meteor Team :)

I was just wondering are you still giving access to the users on client side to browse and list all packages installed in the current app ?

You can see it like this in all current meteor apps :

```
Object.keys(Package);
```

and

```
Object.keys(window).filter(function(key) { return window[key] instanceof Meteor.Collection; });
```

Or more dangerously see all the tables and fields :

```
Meteor.connection._mongo_livedata_collections
```

This last one is too much!

Can you do something for these things please thank you!

**Comment by stubailo** [comment]
I'm curious, is there a case in which knowing what packages the app is using, or what the names of the collections are, compromises the security of the app?

At best, hiding the names of the packages would be security through obscurity, which isn't really a thing. If you want to make your app secure, you should do it with authentication, permissions checks, and having a secure web server.

**Comment by capensisma** [comment]
What about knowing the packages name? 

What if a malicious user is aware of a vulnerability in an existing Meteor package. Using the Package object on the client, that user can quickly check to see if an application is making use of that package, and is therefore vulnerable.

This how Joomla/Wordpress CMS got hacked and more than 50% of website on the web were infected because they scanned the app and got a list of all installed extensions then check for a known exploit and try until they find a way. Then... Owned! 

In case of a more advanced app using like Paypal, Stripe or any payment gateway it might be more dangerous or authentication.

Security by obscurity for me is a must, even if the app  crash in front of users it shouldn't show an explicit error.

Also, giving the structure of the schema of the database is like giving someone a precise map of your castle and how it was built, they just need to figure out how to get in. (look look they are using this very old package)

Just don't ship the packages names and see how to not give the data to the client, since with a loop they can select all entries or post ? (hash based request ?) what if i liked all post at once (+200 post ) ?

A very dumb workaround used by Facebook right now is to crash the webpage when a user opens the console.

Anyway thanks for the reply

**Comment by stubailo** [comment]
Just for completeness, Facebook doesn't crash anything when you open the console: https://www.dropbox.com/s/9sb6c12jdduob2z/Screenshot%202015-07-29%2017.31.48.png?dl=0

**Comment by capensisma** [comment]
I swear to god it used to crash the whole webpage when the console opened 

http://stackoverflow.com/questions/21692646/how-does-facebook-disable-the-browsers-integrated-developer-tools

and here is how it can be done http://stackoverflow.com/questions/7798748/find-out-whether-chrome-console-is-open

Believe me or not! they crashed the whole page just before June.

**Comment by robertpitt** [comment]
@capensisma, I agree with you in regards to "Obscurity is Security", I mean, everyone who hack's WordPress sites these days start with [WpScan](https://github.com/wpscanteam/wpscan).

I agree that it's a totally different platform than PHP but I do believe hackers are pretty clever at finding ways to exploit frameworks and having this unnecessary exposure of packages is setting them up.

I read [https://medium.com/meteor-secret/what-ive-found-after-scraping-1740-meteor-apps-99a20ac6d252](this article) earlier today (coincidently) that outlines how easy it is to discover vulnerabilities in the exact same way as WpScan does.

- Version
- Packages (including insecure/auto-publish)
- Collections

I believe we should be actively trying to prevent this sort of sniffing.

Regards

**Comment by stubailo** [comment]
Would it not be better to create a different way to be more sure that your app is secure? I feel like even if you couldn't look at the list of packages, you could search the client-side minified code to find out if a package is present or not.

IMO it would be much better to just stop people from deploying apps with insecure rather than hiding that name from the list of packages.

**Comment by capensisma** [comment]
I agree we should take care of making our meteor apps more secure in both ways hiding what we can and fixing why we can, security is not absolute there would be always packages with some vulnerabilities.

And also why would the package name be in the minified code ? it should be randomly renamed.

Making it harder as much as we can to any hacker to figure it out.

**Comment by robertpitt** [comment]
@stubailo, preventing insecure and auto-publish on production compilations is one step, but those are packages that are designed to reduce security for prototyping, there are still packages that accidentally create security flaws.

I think that removing the ability to identify packages pragmatically is another step, assume that within a build we remove the Package declaration, package names to be either obfuscated with a private key or randomised on build.

It's a known fact that wordpress's greatest security flaw is it's plugin identification, we have an opportunity to use the powers of obfuscation to radically minimise the ability to allow script kiddies to use a tool with a "press here to hack" button.

If I am going to be hacked I would want the hacker to work for it, not be given it on a plate.

**Comment by stubailo** [comment]
Could be a good feature. What are some concrete ways in which this could be accomplished? Just replacing all of the package names with random IDs or hashes on deploy?

**Comment by capensisma** [comment]
I agree with Robert gets my point.

We should randomize the name even the object `Package` should be renamed a random name.

and if possible in production mode rename the database name and collections ?(dev mode they would be the same) this might be too much but it's worth it.

**Comment by robertpitt** [comment]
It's late here, and I think there are a lot of factors involved, such as packages that are using the `Package` to check for other packages.

I think that discussing the `Package` declarations existence and obfuscate/randomise package names is a good start, what problems can we immediately see.

**Comment by capensisma** [comment]
What I fear is someone can easily list/insert many entries at once.  (In Case of eCommerce app for transactions, cart ...). Just by a recursive function and watch!

and with all my due respect to Meteor Awesome Project, you should even rename the `Meteor` Object when in production so they wouldn't what framework is it using ? (Meteor, Express ...) they can easily know it's NodeJs.

Sometime the most obvious cases are the ones that screw it all.(sorry for this word :) )
Example :
```Meteor.isClient = False;Meteor.isServer = True;```
and you will get an error like npm package wasn't found since it's trying to load that package.

Rename Meteor Object as well to a random name when minified.
Thanks

**Comment by capensisma** [comment]
Hello Is there any ETA or new about this ?

**Comment by stubailo** [comment]
@capensisma If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by capensisma** [comment]
@stubailo Hi What's up ? :)

Was this issue solved in the new version 1.2?

Thanks

**Comment by stubailo** [comment]
Nope, not yet!

**Comment by capensisma** [comment]
Why is that :( bro ?

**Comment by stubailo** [comment]
We haven't had time yet - We aren't currently looking at this feature as the highest priority item compared to everything else we could be working on.

**Comment by capensisma** [comment]
Awesome thanks for your amazing work, keep it up guys :+1: You rock :)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Make%20it%20less%20obvious%20from%20the%20client%20which%20packages%20are%20used%20in%20a%20Meteor%20app&body=Migrated%20from:%20meteor/meteor%234831) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
