### ISSUE TITLE
Allow debugging/running shell commands from the same terminal where app is running

### ISSUE THREAD

**Issue by taromero** [meteor/meteor#4836]
Meteor apps should have the ability to read stdin from the terminal, just like a normal nodejs app. This will allow, for example, to prompt to the user for input.

Related SO question (by me): http://stackoverflow.com/questions/31690867/meteorjs-how-to-read-stdin-from-the-terminal?noredirect=1#comment51324172_31690867.
### 30-Jul-2015 update

One of the things that could be done with prompts in Meteor is to run a repl in the same terminal window where you run the code. I've made a package that does that: https://github.com/taromero/fibers-debugger. It currently only works on bundled apps (as it needs to use prompts). I attach the gif from the repo to give a quick overlook:

![](https://raw.githubusercontent.com/taromero/fibers-debugger/master/readme_images/fibers-debugger.gif)

**Comment by rfox90** [comment]
Meteor is a web app framework. Why should a webserver answer stdin?

**Comment by taromero** [comment]
In general I think Meteor should not limit Node's features (like passing arguments on `meteor`'s command or reading from stdin) without specific reasons.

In particular, prompting the user/developer on the terminal could be useful for initial package configuration (I'm thinking about maybe auth packages, that require GUI for initial configuration). It will be useful for development rather than production.

**Comment by rfox90** [comment]
Most package configuration should be done with configuration files or environment variables. Or GUIs e.g. wordpress installation file etc. Automatic and file/env based configuration support automatic and repeatable setups.

Here's a relevant documentation link: http://docs.meteor.com/#/full/meteor_settings

I haven't come across a web application or package here for meteor that would benefit from a command line process for configuration.

Of course command line switches are fine etc. What I mean is I see no benefit on halting the process of an application and asking "What do you want to enable?" "Input db conection string?" and then reading it from STDIN.

Do you have an example where an app would benefit from this? What happens if the app crashes? Do we have to re-enter everything? If the settings just get saved to a file then just write that file to start with :S?

Meteor is an application framework and not node certain features of node aren't going to be available.

**Comment by taromero** [comment]
@rfox90 thanks for the feedback!

I gave the example of auth packages (`accounts`) as they use a GUI to configure the package (configuration is saved to a file). I'm all for writing the configuration file myself, but having the option to have some sort of CLI `wizard` would sometimes be useful. And then there's the `GUI vs CLI` discussion. It might not be a common use case (and it might not be that useful :)), as you state, but I just want to raise the flag, maybe it's trivial to add support for reading stdin (allowing prompts).

I didn't mentioned this earlier as I wanted to come up with an example, but my initial motivation is to have a debugger tool displaying like the Ruby's CLI debugger (this is, showing a prompt in the same terminal window where the app is running). The goal is trying to avoid having to attach an external debugger (node-inspector or Node's CLI debugger) in a separate window, just for context inspection. I think Meteor would be a great platform to have this, since everything (in the server) is running on Fibers, so we can "halt" the execution of a function at some point and inspect it's values (we can't halt a function execution in a normal Node function, running outside Fibers).

**Comment by rfox90** [comment]
Have you read: http://joshowens.me/easily-debugging-meteor-js/

Gives some useful insight into debugging meteor.

**Comment by taromero** [comment]
I did, but it doesn't cover what I'm trying to achieve.

I know I can debug using `node-inspector` (thought I prefer Node's CLI debugger most of the time), but I'm trying to debug in a different way here (debugging using the CLI, in the same terminal window), and having prompts working on Meteor would allow that.

**Comment by stubailo** [comment]
@taromero I think this feature request would be better framed in terms of **what you want to achieve**, rather than the solution you think would solve it. Here are some options:

1. Allow easier configuration of packages from command line
2. Allow debugging of Meteor from the same terminal where you run the app
3. Allow running meteor shell from the same terminal where you run the app

I haven't seen any good reasons here to encourage packages to accept stdin input. IMO it would actually be an antipattern to block the server's startup to wait for command line input, since most web servers should be able to start and stop completely without human intervention, and configuration should live either in source code, database, or environment variables.

Also, if you are sharing your code over version control this will be a huge hassle for your collaborators - instead of just running the app and getting the settings from a file you committed, they will have to copy and paste it into the CLI.

**Comment by taromero** [comment]
@stubailo I think I've presented the feature request in a kind of messy way, so I got misunderstood. Thanks for your feedback on how to better present it.

The main reason I think accepting stdin input would be great is to allow `2` (debugging Meteor from the same terminal where you run the app). IMO this would be great to remove the need to attach an external debugger in another terminal (or worst, having to open Chrome). I'm developing both Meteor and Rails apps, and I find Ruby much more comfortable to debug (for most cases) than Meteor because of this. In Ruby you have your app/tests running and stopping at a breakpoint to debug, all in the same terminal. By accepting stdin input, we could do the same on Meteor apps.

Please consider reopening this ticket if you think having this simplification on the debug process would be useful while developing Meteor apps.

###### Clarification on the CLI configuration comment

As a rather secondary reason, there will be the ability to configure apps via terminal prompts instead of GUI prompts. By **no means** I was saying that configuration should be kept in memory based on terminal input, it should be kept in configuration files. I tried to clarify that point at the beginning of [my previous comment] (https://github.com/meteor/meteor/issues/4836#issuecomment-125996740). In fact, I gave the accounts package GUI configuration as an example of configuring the package via the GUI, which then created/modified the configuration file. The use case could be to only prompt if the package lacks the necessary configuration to work, and create/modify the configuration based on user input. This is a pattern I've seen in other place used to setup some nodejs packages or json configuration files.

**Comment by stubailo** [comment]
OK, I'm down to leave this open as a discussion of letting debugging/meteor shell happen in the same terminal as the app server.

**Comment by hwillson** [comment]
While there could be some advantages to being able to run debug/shell commands in the same terminal window as the running app, the amount of effort required to make that happen would likely not be worth the end result (given some of the other more popular Meteor feature requests). Existing Meteor developers are used to working within separate terminal windows, and new Meteor developers will have likely encountered the same type of approach elsewhere. Regardless, given that there has been very little activity/support for this issue in over 1.5 years, as part of the on-going old issue cleanup process, I'll close it off. Thanks for opening this originally!
