### ISSUE TITLE
I need to patch modules code

### ISSUE THREAD

**Issue by psy21d** [meteor/meteor#4837]
Need to patch meteor modules.
How I can do it recently?

Without repo cloning!

**Comment by sebakerckhof** [comment]
You can create a packages directory in your meteor projects and add packages with the same package definition file as the package you want to patch. Meteor will first look at these packages, before it will take packages from the package server.

It might also be worthwhile to see if you can access the method you want to patch through an exported variable of the package (e.g. OAuth._stateFromQuery, since I guess that's what you're after) and monkey-patch that package.

**Comment by psy21d** [comment]
I am not a monkey

**Comment by rfox90** [comment]
You were not being called one. Monkey Patch is a technical/colloquial term.

https://en.wikipedia.org/wiki/Monkey_patch

**Comment by psy21d** [comment]
Yes, I know
Just little joke

**Comment by stubailo** [comment]
I think @sebakerckhof has the right solution here. Thanks!
