### ISSUE TITLE
It's not clear which packages are shipped to the client

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4840]
I'm attempting to transition to a package-based app. I'm using React so I thought I'd try to get rid of unneeded packages. This is what I have right now:

`meteor remove meteor-platform autopublish insecure && meteor add meteor webapp logging tracker ddp mongo check`

However, webapp requires boilerplate-generator which required everything I just got rid of, namely blaze, spacebars, templating, ui.

I think boilerplate-generator shouldnt be required by web-app, right? Then again, I dont really know what it does. It just creates the initial files right?

**Comment by stubailo** [comment]
I'm currently working on a project to make it easy to remove Blaze from an app if you are just trying to use React, so I will definitely attack this before Meteor 1.2. Thanks for bringing it up!

**Comment by stubailo** [comment]
Oh - I think this report has one thing missing - WebApp, and Boilerplate Generator, only require those things on the _server_. Which means that you shouldn't be getting Blaze shipped to the client. Is there a problem with having Blaze included on the server?

**Comment by ccorcos** [comment]
It's not the end of the world, but I think it's a good idea to reduce any code that isn't needed.

**Comment by stubailo** [comment]
Yep, just remarking that it isn't as big of a problem as it sounded initially from the title. But I'll still try to get rid of that dependency.

**Comment by stubailo** [comment]
After talking with @Slava, we've come to the conclusion that the internal dependencies of `webapp` and `boilerplate-generator` aren't a problem. But the actual problem is that it's impossible to tell whether you are shipping Blaze to the client or not. So I'm going to rename the issue to that.

We are probably not going to start optimizing which packages we use on the server in the near future, but the client is another matter.

**Comment by ccorcos** [comment]
Here's another related issue for supporting Meteor without blaze

https://github.com/meteor/meteor/issues/4846

**Comment by ccorcos** [comment]
I agree -- not so worried abut the server. But the more modularlized the better

**Comment by hwillson** [comment]
There are a few ways to tell which packages are going to be sent to the client, like looking in your local apps `.meteor/local/build/programs/web.browser/packages` directory. Looking in that directory will give you an idea of what packages will be bundled into your production build, and served to any client accessing your app. Yes this is a manual process, but it works. That being said, I don't think there is enough outlined in this issue to justify keeping it open. *"It's not clear which packages are shipped to the client"* is quite broad and open-ended; what would a solution to this problem look like? Providing an option via the Meteor Tool CLI to spit out package stats (like what packages will be made available to the client, how big they are, etc.?)? Or is the solution to provide something more visual that can be displayed on Atmosphere based package pages, like splitting the Dependencies section up to show client and/or server depedencies separated out? Either way since there is currently a manual way to deal with this issue, and this issue is quite old with very little activity, I'll close it for now. Happy to re-open if anyone disagrees - thanks!
