### ISSUE TITLE
Facebook Login issue when app is using HTTPS

### ISSUE THREAD

**Issue by thdoan** [meteor/meteor#4841]
When the Meteor app is using HTTPS (e.g., https://myapp.meteor.com/), the Facebook Login functionality breaks because when you click on the button it spawns a popup window with the URL `http://myapp.meteor.com/_oauth/facebook?...`, which results in this error:

```
Uncaught SecurityError: Blocked a frame with origin "http://myapp.meteor.com" from accessing a frame with origin "https://myapp.meteor.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.
```

It seems like somewhere in the code "http:" is hard-coded. This can be fixed by removing the protocol and launching the popup with "//myapp.meteor.com/_oauth/facebook?...".

**Comment by anubhav94** [comment]
Hey @thdoan,

I'm on Meteor 1.1.0.2, created the leaderboard example, added `force-ssl`, `accounts-ui`, `accounts-facebook`, configured the FB login and added `{{> loginButtons}}` into my HTML template and was able to get Facebook login working. Can you please give us a way to reproduce the problem so that we can debug it and fix it?

Thanks,
Anubhav

**Comment by thdoan** [comment]
Thanks, I'll use `force-ssl` for now.

**Comment by terenceng2010** [comment]
I have the same issue. But the problem is that if I use force-ssl, the old cordova client in the wild which connects to the server via http can not connect to the server anymore and be hot-code pushed to the latest version which connects to the server via https. The below is my test result:

I have done a testing on old cordova client (which use http as ROOT_URL when build):

- if a server is deployed with ROOT_URL set as https:
 - the client first connect to the server via http.
 - the client retrieves latest version of the app by hot code push from server
 - the client connects to the server via https.

- if a server is deployed with ROOT_URL set as https AND install force-ssl package:
 - the client first connect to the server via http.
 - the client would not be able to connect via DDP. Meteor.status() shows it can't connect to the server properly.
 - workaround:
   - two-step deployment: first deploy the server with ROOT_URL set as https > first hot-code push to client > install force-ssl package > deploy again > second hot-code push to client
    - the problem is that we don't know whether all clients in the wilds have installed first hot-code push or not before we do the next deployment.


any suggestions? Thanks.

**Comment by hwillson** [comment]
A lot of the Meteor core has changed since this issue was created (sorry for the long delay in responding!). I've explained the likely cause of this issue below, but keep in mind some of the package names / structures have changed.

The `facebook-oauth` package (used to be called `facebook`) builds its login URL (see [here](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/packages/facebook-oauth/facebook_client.js#L35)) by calling the `oauth` packages [`OAuth._redirectUri`](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/packages/oauth/oauth_common.js#L3) function. This function in turn builds the necessary URL by (eventually) calling Meteor's [`Meteor.absoluteUrl`](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/packages/meteor/url_common.js#L10) function. Within this function, there is a [chunk of code](https://github.com/meteor/meteor/blob/f285bffed8bef30c4c5bf1a88f412ca9d12c0258/packages/meteor/url_common.js#L23-L24) that looks like:

```js
if (!/^http[s]?:\/\//i.test(url))
  url = 'http://' + url;
```

So if the `url` doesn't include a `http://` or `https://` prefix, a default `http://` prefix is added. Since the `Meteor.absoluteUrl` function reads from the `ROOT_URL` environment variable, and since you're getting an error with a `http://` prefix in it even though you're using SSL, this would definitely point towards an issue with your `ROOT_URL` setting. Maybe double check that you're using a valid https based `ROOT_URL`.

As part of the on-going old issue cleanup process however, since there hasn't been any activity/interest in this issue in quite some time, I'll close it for now. Thanks for posting this originally!
