### ISSUE TITLE
Make Typescript a first class citizen in Meteor Land. 

### ISSUE THREAD

**Issue by vjau** [meteor/meteor#4888]
Typescript is a pretty awesome superset of Javascript with ES6 features and static (optional and infered) typing.
With babel allowing us to write with ES6 today, the big remaining difference between TS and JS lies in its type system, which is still very useful for those who like its added "compile time" safety.
Typescript is the official language for Angular2 development. Aurelia is making it easy to develop for it with Typescript.
At the moment, it's pretty difficult to get typescript to work with Meteor because of scoping issues and lack of modules support in Meteor.
I wonder if MDG would be interested to make Typescript a first class citizen for Meteor development. I think that the future arrival of ES6 modules in Meteor means that some core changes will be made to Meteor to allow these modules to work with the established Package system. It would be cool if MDG was considering these changes with Typescript compatibility in mind. 
If MDG is interested, i can list the main issues making it difficult to use typescript today with Meteor.

**Comment by Sanjo** [comment]
http://flowtype.org/ is an alternative type system for ES2015 and it is supported by Babel. If you just want a type system, this is probably the easier router.
I'm not saying that Typescript shouldn't be supported.

**Comment by stubailo** [comment]
@vjau I suspect that the future where Meteor has modules will make it easy to harness the full power of TypeScript. I think @benjamn is currently thinking about that project, maybe he has some ideas about TS.

**Comment by vjau** [comment]
@Sanjo, i have investigated flow but it doesn't support utf-8 (!) and won't for a long time (major rewrite needed for this).

**Comment by benjamn** [comment]
I too have tried using Flow with Meteor code, and I found it exceedingly difficult (possibly impossible) to specify types for my `Mongo.Collection`s, such that Flow could infer what fields a document returned from `collection.findOne(...)` should have.

I'm not as familiar with TypeScript, but if that kind of thing is possible with TypeScript, I would be very interested to see a working example, since that's the most compelling reason for using types in a Meteor app that I can think of.

**Comment by Sanjo** [comment]
@benjamn I haven't tried Flow Type yet, but couldn't you use [declarations](http://flowtype.org/docs/declarations.html#_) for that. Like in the [example for underscore](http://flowtype.org/docs/third-party.html#example).

Typescript has also this kind of declarations via type definitions files when I remember correctly. There is also [one available for Meteor](https://github.com/borisyankov/DefinitelyTyped/blob/master/meteor/meteor.d.ts#L522-L562). This is how Webstorm supports autocomplete ;-)

**Comment by benjamn** [comment]
Right, that's what declarations are supposed to be for, I just didn't have any luck getting it to work in practice.

Specifically, I'd like to declare a `Collection` type that takes a type parameter `T` and defines the return types of the collection methods in terms of `T`, something like 
```js
declaration class Collection<T> {
  findOne(query: Object): T;
  ...
}
```

So then I could say
```js
declare var Items: Collection<{
  _id: string,
  description: string,
  price: number
}>;

Items = new Mongo.Collection("items");

// Flow should be able to infer the type of item here.
var item = Items.findOne(...);
```
That's what I tried, at least, and I couldn't get Flow to complain about anything I tried to do with `item`, so I have to assume it failed to infer the type.

**Comment by Sanjo** [comment]
@benjamn I got it working: https://github.com/Sanjo/meteor-flow-types. Flow types is still a little bit early. I hope WebStorm 11 will support it.

@vjau Not sure if no utf-8 is that dramatic. Does basically mean that you cannot use non-ascii characters in identifiers (variable names, function names etc.)?

**Comment by vjau** [comment]
@Sanjo as you probably know utf-8 are valid identifiers names in Javascript (internally it even use UTF-16). All my code is encoded as utf-8, but flow goes berserk when it encounters an UTF-8 character, even one from 7-bit ASCII space like french é which is ubiquitous in this language.
I could probably convert all my code to ASCII, or they could just conform to standards ;)

Anyway, could we please stay on topic at hand, which is TS with Meteor :)

**Comment by D1no** [comment]
TypeScript is certainly needed to embrace the enterprise ecosystem and as known, Google & Microsoft even aligned themselves to provide Angular 2.0 a native TypeScript foundation.

Due to
- broad support of JavaScript libraries and IDE's
- Microsoft's packed up detail knowledge of various application designs up to C#
- it [supports React/JSX](http://blog.mgechev.com/2015/07/05/using-jsx-react-with-typescript/) (in 1.5.3 master now, official from 1.6)
- ES6 Unicode specification (hello from Germany;)
- the goal to align [TypeScript to 100% to ES2015 standards and beyond](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)
- enterprise flavour 
larger node.js projects currently start with TypeScript.

It would be great if we could get a native typescript package just as we have a coffeescript packge. We are currently investigating how we could build off the ecmascript package a new typescript package with full sourcemap and module features, though it seems like meteors inflexible build-load order is still in the way to enable coherent amd/commonjs/webpack loading.

Here a TypeScript Collection definition:
https://github.com/meteor-typescript/meteor-typescript-libs/blob/master/definitions/meteor.d.ts#L557

Here are some Meteor TypeScript samples: 
https://github.com/meteor-typescript/meteor-typescript-compiler/tree/master/samples

@benjamn, you would do us a huge favour if TypeScript could be integrated as an alternative ES2015 transpiler

**Comment by benjamn** [comment]
Once Meteor 1.2 is out, and once we support ES2015 modules soon after 1.2 (based on CommonJS `require`/`exports` module syntax), what else would stand in the way of a community plugin package supporting TypeScript syntax in `.ts` and `.d.ts` files?

I'm trying to understand what making TypeScript a "first class citizen" would really mean, versus just supporting APIs that make it easy to implement TypeScript as a plugin…

**Comment by vjau** [comment]
@benjamn could you say a bit more what ES2015 support in Meteor would mean ? How would the modules interact with the package system ?
At the moment, this typescript code :
```js
class Foo {}
```

is transpiled to :
```js
var Foo = (function () {
    function Foo() {
    }
    return Foo;
})();
```
Which means that a class that the typescript compiler intend to be global becomes file scoped in the transpiled code. Then how does the compiler knows which class is available where ?

Now some months forward... Let's say Meteor has implemented ES6 modules.
If you put this code in a module which is transpiled as a module, then it will be probably work. 
But how do you use the meteor packages ? Do we have to drop them ? 
If you keep then aside the modules, how do they interact ? 
Can a package contains multiples modules ?
Then how will the compiler know which modules which files have access to ?
Mologie has implemented a clever Typescript plugin which patch the transpiled code after linking (by the way, why doesn't the plugin api allow us to play with the linking phase ?) to make it easier to get TS code to work with meteor. This make it easier, but this is still a hack because both technologies are not meant to get well together at the moment. 

Typescript support is not just about writing a plugin to transpile the code, but allowing the big picture of you app/package code to be in a way that is manageable for the typescript compiler.

**Comment by D1no** [comment]
Flexible external module loading. TypeScript modules can load via various external packagers (amd, common, webpack etc...). Therewith TypeScript is [module type agnostic](https://youtu.be/3Jrg8hfNXmU?t=51m10s) what is exactly what we need for isomorphic code, since the environment may change. I.e. commonJS on the server, pre-packaged amd on mobile apps, amd on the browser.

For example, I could not order to build of a 40kloc project again via a meteor-commonJS implementation.   Because meteor is not module type agnostic. Right now meteor quite literally collides into many build systems, because it is partially replicating functionality that exists in specialist tools such as webpack.

So first class would be
- easy switching of babel for typescript (the transpiler)
- ES2015 modules are implemented, how can that process be handled? (the module logic)
- How could meteor make an agnostic module schema of its internals, assets, packages and the application code available to (module-) build tools - or in anyway - achieve "isomorphic module styles"?

As soon I can amd lazy require css files next to the client side code of an isomorphic package while visiting extended areas of a mobile business intelligence dashboard app, I would probably get a meteor tattoo and never recommend any other system again.

**Comment by AugustNagro** [comment]
@D1no Great reasoning.

**Comment by thinkpadder1** [comment]
Very relevant to Typescript definitions: https://github.com/typings/typings

**Comment by Urigo** [comment]
We are working on an official Typescript package which already exists in Beta.
Please follow the progress here - https://github.com/Urigo/angular2-meteor/issues/102

**Comment by raix** [comment]
if meteor is using webpack it should possible to just add ts directly in a config and just do npm install right?

**Comment by Urigo** [comment]
@raix yes but Meteor 1.3 won't use Webpack for reason @benjamn specified earlier in the Meteor forum

**Comment by yanickrochon** [comment]
This seems like a good ides for TS developers, but as much as I do not care less about Blaze templates, this should be a de-facto feature in Meteor. A proper package is much preferable. I understand that, for some people, the illusion of choice is acceptable, but to me it is quite important that I don't have to swallow features that I do not need.

**Comment by Urigo** [comment]
just for those who are not updated, there is a great Typescript package and it's great - https://github.com/barbatus/typescript/

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/4888#issuecomment-256794549, the [barbatus:typescript](https://atmospherejs.com/barbatus/typescript) package provides a TypeScript compiler for Meteor, and works quite well. The Guide has also been updated with a [TypeScript](https://guide.meteor.com/build-tool.html#typescript) section, that recommends using this package. As part of the on-going old issue cleanup process, I'll close this issue off. Thanks for suggesting this originally!

**Comment by D1no** [comment]
@barbatus I had the "typescript" meteor org. I have added you to take it over, to potentially publish under "typescript/typescript".

**Comment by barbatus** [comment]
@D1no thanks, though don't see much sense to publish it as `typescript/typescript` so far.
