### ISSUE TITLE
Can not use meteor , Retrying after error { [Error: SQLITE_BUSY: database is locked] stack: [Getter] }

### ISSUE THREAD

**Issue by juliusxyg** [meteor/meteor#4892]
What's the business with SQLITE? 

btw, I have sqlite3 installed and its version is 3.6.20.
server: Linux xxxx 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

the error happens even I run meteor --help
Retrying after error { [Error: SQLITE_BUSY: database is locked] stack: [Getter] }
Retrying after error { [Error: SQLITE_BUSY: database is locked] stack: [Getter] }
Retrying after error { [Error: SQLITE_BUSY: database is locked] stack: [Getter] }
...

any idea ?

**Comment by sebakerckhof** [comment]
The package database is cached locally in an SQLite database.
I believe on linux you can find it here: ~/.meteor/package-metadata/v2.0.1

For some reason the database is locked. Do you have another meteor process running? Sometimes (when a package is removed for example) the entire cache is reset, this can take a while and maybe that's why the database is locked?

**Comment by glasser** [comment]
Are you using some non-standard filesystem for your home directory?

**Comment by juliusxyg** [comment]
The issue is fixed, cause home directory is mounted and the NFS lock is not released due to some cases.

**Comment by jmallott** [comment]
Could you explain how you fixed the issue? I am having the same problems.
