### ISSUE TITLE
Publish Meteor.user().services.facebook.name

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteor/meteor#4900]
Hello:

I'm trying to follow the Meteor docs to publish the user's Facebook name which shows fine on the server. Here's my code:

```
server.js

Meteor.publish('userData', function() {
  var currentUser;
  currentUser = this.userId;
  if (currentUser) {
    return Meteor.users.find({
      _id: currentUser
    }, {
      fields: {
        "services.facebook.name": 1,
      }
    });
  } else {
    return this.ready();
  }
});

client.js
Meteor.subscribe('userData');
```

But this isn't working. No matter what I do I can't access this data from the client. Help?

**Comment by stubailo** [comment]
@nicholasalanbrown do you have the `autopublish` package?

**Comment by nicholasalanbrown** [comment]
I do not have it installed as it's inherently bad practice. I assume there must be a way to publish the Facebook services only...

**Comment by stubailo** [comment]
@nicholasalanbrown I was asking because I don't think this code would with with autopublish turned on. It's good that you are not using it :]

Do you have any other publications that publish fields from `services`? Currently DDP doesn't work with publishing related nested fields: https://github.com/meteor/meteor/issues/3764

If you have multiple publications for a single top-level field, they will override each other. It sucks, I know, but the workaround would be to put them in the same publication.

If that's not your issue, then it's something else and then I would need to see a whole app to identify what is wrong.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
