### ISSUE TITLE
Meteor.loginWithPassword does not work when used within Meteor.methods function

### ISSUE THREAD

**Issue by flipace** [meteor/meteor#4912]
When trying to use the Meteor.loginWithPassword function in a function which gets called by Meteor.call('...') it always returns the error "No result from call to login".

Repository for reproduction: https://github.com/flipace/meteor-accounts-password-bug

Am I missing something? Do I have to set some context? Is this expected behavior?

**Comment by rclai** [comment]
You shouldn't be using `Meteor.loginWithPassword` from a server-side method because you would be killing off the security benefits of hashing the password on the client before being sent to the server unless you're talking about using it in a client-side method. Also [`Meteor.loginWithPassword`](http://docs.meteor.com/#/full/meteor_loginwithpassword) is a client-side call.

Look at this [line of code](https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_client.js#L28).

Also, in your reproduction, where is your method defined?

**Comment by flipace** [comment]
It is being used in a client side method. Otherwise it would throw an error since Accounts.loginWithPassword would not exist.

I define it like
    Meteor.methods({ loginMethod: function(){ [loginWithPasswordHere] } });

I forgot to commit the method to github. It's there now: https://github.com/flipace/meteor-accounts-password-bug/blob/master/login-with-password-bug.js

**Comment by rclai** [comment]
The function would get called on the server too.

**Comment by flipace** [comment]
Okay, thanks @rclai . I didn't know that.
Maybe this could be reflected within the docs for loginWithPassword, so other users don't stumble upon this same problem?

**Comment by stubailo** [comment]
@rclai I don't think hashing passwords on the client side actually improves security, so it's not a good reason to avoid calling this function on the server.

@flipace I think this is more a matter of making it more clear that client-side method stubs shouldn't have any side-effects.

**Comment by harshalyeole-tudip** [comment]
@rclai 
What if I want to use it on Server-side?

Is there any alternative?
