### ISSUE TITLE
meteor run ios in devel branch: static-assets?

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#4918]
When I try to do `meteor run ios` with the devel branch, I get the following error.

```
Error while running for mobile platforms: ENOENT, open
'/Users/name/meteorRepos/meteorDevelop/tools/cli/static-assets/cordova-bootstrap-page/meteor_cordova_loader.js
```

I realized it's simply because I don't have the file specified in that location. The file `meteor_cordova_loader.js` is located in `/tools/cli/`, not `/tools/cli/static-assets`. Why does it try to look for the file there? How can I fix it?

**Comment by woniesong92** [comment]
I could solve this problem by creating a symbolic link from .tools/static-assets -> .tools/cli/static-assets. Is there something wrong with path configuration?

**Comment by stubailo** [comment]
@Slava seems to be in the middle of moving some files around, I guess he forgot to update a reference somewhere.

**Comment by martijnwalraven** [comment]
If fixed this issue, but there are other problems preventing Cordova support from working on devel (it uses an old version of cordova-lib that relies on npm 1.3.4 while we bundle 1.4.28). So you should keep using the regular release for now.

I'm working on improvements to the Cordova integration on a separate branch and hope to merge these soon.

**Comment by woniesong92** [comment]
Hi @martijnwalraven Thank you so much for your work. I am close to publishing an app that's built in Meteor and Ionic, and I believe I am hitting a few problems with the latest release version. Here are the reasons that I wanted to use `devel` branch.

1. Meteor apps on Samsung phones are really slow without Crosswalk. The current release version of Meteor doesn't seem to support Crosswalk compilation well, but according to this [post](https://forums.meteor.com/t/how-to-get-crosswalk-working-with-android-step-by-step-guide/6683) on Meteor forum, I can use `cordova-plugin-crosswalk-webview` in Cordova 4.0.0, which will be shipped with Meteor 1.1.1.
2. WKWebkitView that was introduced with iOS8 is now available on Cordova with [this](https://github.com/Telerik-Verified-Plugins/WKWebView) and there's a wrapper for Meteor [here](https://github.com/practicalmeteor/meteor-wkwebview). It drastically improves the performance of an iOS app. However, there are some critical keyboard animation problems and these might be better with the latest cordova version (4.0.0+).
3. We have to cache data subscriptions using [subs-manager](https://github.com/meteorhacks/subs-manager) and since we are using template-specific subscriptions, we need to use `connect` attribute of `templateInstance.subscribe` which is not introduced to the release version.

Do you know the latest checkout that I can try to use for my app before Meteor 1.1.1 is released, so I can address the issues above?

**Comment by martijnwalraven** [comment]
Cordova was upgraded to 5.0 in a pull request on devel a few months ago, but this hasn't been kept up to date and there are some incompatibilities with other changes made since. In particular, the cordova-lib version included seems to require an old version of npm (1.3.4), while we bundle 1.4.28. You may be able to work around this, but I'm not sure that's worth it right now and you may encounter other problems.

If at all possible, I'd advise you to wait until I can merge the work I'm currently doing, which should be really soon (you wouldn't have to wait for Meteor 1.2 to be released, although the work won't be fully QA'ed yet until it is). Besides other improvements, this will upgrade cordova-lib to the latest version (5.2.0). However, note that cordova-android and cordova-ios are versioned independently from this.

cordova-android 4.0 introduced pluggable web views (it is currently at 4.1.0), which is needed for the `cordova-plugin-crosswalk-webview` to work. Unfortunately, cordova-ios 4.0 has not yet been released (it is currently at 3.9.0), so pluggable web views are not available for iOS at the moment. The Telerik plugin you mentioned is an unofficial alternative, but does use a fairly hacky approach, so use it at your own risk.

**Comment by woniesong92** [comment]
@martijnwalraven That's awesome! Would you mind if I asked what the timeline looks like for the release?

**Comment by martijnwalraven** [comment]
I can't give you anything more specific than 'later this Summer' for the Meteor 1.2 release, but I should be able to merge at least some of the Cordova improvements (including the version upgrades) to devel within the next week or so.

**Comment by woniesong92** [comment]
For now I am waiting for the Cordova integration. Next week sounds good! Thank you for all the good work.

**Comment by sweetticket** [comment]
+1. We are also waiting for the cordova update. @martijnwalraven Do you have an idea when this will be released? We are not sure if we should try building crosswalk by ourselves with old Meteor, or wait for your cordova integration.

**Comment by martijnwalraven** [comment]
If all goes well the first public RC with the Cordova improvements should be out really soon, so I would recommend waiting. Building Crosswalk is now just a package add away :)
