### ISSUE TITLE
Make Blaze._globalHelpers public

### ISSUE THREAD

**Issue by dalgard** [meteor/meteor#4919]
It's easy to get a Blaze helper as a function by writing `Blaze._globalHelpers[<name>]`. However, I can't rely on this, since it isn't part of the public API and may change.

Could it be time to remove the underscore in front of `globalHelpers` and add it to the docs?

It might be attached to the `Template` namespace, too, since this is where `registerHelper` is found.

**Comment by zimme** [comment]
How about defining a function under a namespace and then just register that function as a helper too, and you can access it via  the namespace as a regular function?

**Comment by dalgard** [comment]
There are at least a couple dozen ways of working around it – my current choice being `Helpers = Blaze._globalHelpers;` (so I'd only have to edit one line if the private function changes).

My point was, why not simply make the function public?

I don't see any advantages to writing any sort of custom boilerplate solution anywhere in my project.

**Comment by zimme** [comment]
I see the point, but I'm pretty sure this can be put into a community package without much effort and when that's possible I don't think we'll see this change in core in the near future. BUT I could be wrong too.

Maybe this is something to add to [`aldeed:template-extension`](/aldeed/meteor-template-extension)?

**Comment by dalgard** [comment]
Putting this line inside a community package doesn't make its use of an unsupported method totally fine:

```javascript
Blaze.globalHelpers = Blaze._globalHelpers;
```

**Comment by zimme** [comment]
That's true and I'm all for this change, I'm just pointing out that a lot of other "small" changes have been "rejected"/postponed because of it's ease to implement in a community package.

I hope MDG adds this to the public api as they've done with other stable internal features.

**Comment by dalgard** [comment]
Thanks for the support :+1:

**Comment by stubailo** [comment]
I think the initial solution @zimme proposed is correct. The global helpers object shouldn't be a dumping ground for useful functions, it's purely a way to register things so that Blaze can find them. Let's see what other people think.

Also, if we make this dictionary public we can never change the implementation of how helpers are scoped or handled, which is exactly why it isn't public.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by dalgard** [comment]
One of the challenges (and strengths) of Meteor is that app code doesn't load in an order determined by explicit dependencies, but rather by its place in the file system. This is what makes built-in APIs so desirable.

Defining utility functions and registering global template helpers *both* take place in the root scope (cf. @zimme's example), and thus, load order becomes significant and potentially problematic – unfortunately.

This can only be alleviated by confining things to one place.

I don't think there's any risk of Blaze helpers becoming a dumping ground, since there's a proper place for almost every other utility function needed by an application – places like collection helpers, schemas etc.

Also, helper functions, once defined, are always used within hooks (due to inversion of control), and they should be able to reach each other on that level. For example, a global currency conversion helper should be reusable inside a global price formatting helper.

So far, the only way is through `Blaze._globalHelpers`.

 
It's a fair point in regard to changing the implementation, but a simple idea would be retrieving the helpers by their name through a getter, kind of matching the style of `Template.registerHelper`.

Like this:

```javascript
Template.registerHelper("trim", function (str) {
  return str.trim();
});

Template.registerHelper("clean", function (str) {
  // Blaze._globalHelpers.trim
  var trim = Template.getHelper("trim");

  return trim(str.toLowerCase());
});
```

**Comment by hwillson** [comment]
Thanks for your feature request! It's been over a year since this was proposed, and given the lack of +1's here or interest elsewhere in the Meteor community, I think it's safe to assume `Blaze._globalHelpers` will remain private. Some variation of the workaround discussed in https://github.com/meteor/meteor/issues/4919#issuecomment-129860549 is generally considered to be the best way to handle this. Closing this off - thanks again!

**Comment by louwers** [comment]
@hwillson When this feature request was made the GitHub didn't even have a +1 feature. ;-)

**Comment by hwillson** [comment]
Thanks @louwers - I meant +1's anywhere; people still managed to cram +1's into comments wherever possible, when issues really hit home 😄. Thanks also for the SO link. I still think this issue should stay closed here though since 1) there is a great/completely acceptable workaround and 2) Blaze issue are no longer managed under this repo. If you're interested in keeping this request alive however, would you mind opening a new issue for this under the [Blaze repo](https://github.com/meteor/blaze)? Thanks again!
