### ISSUE TITLE
Can't install NPM serialport on Windows using Npm.depends

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4935]
Originally posted by @wildeyes:

It works on one machine, doesn't work on an exact same, but another machine.
I am able to `npm i serialport` outside of meteor (including building everything and running a test script connecting to a bot), but if I add `meteor create --package foo` and `Npm.depends({serialport:"1.7.1"})`, then I get a funny error that doesn't say anything.

The first is:
```
failed on node-pre-gyp install --fallback-to-build

=> Errors prevented startup:

   while building package foo
   error: coudln't install npm package
```

**Comment by martijnwalraven** [comment]
Not sure if this is related, but I spend some time tracking down issues with `node-gyp` on Windows a few weeks ago: https://github.com/meteor/meteor/issues/4802.

Didn't solve the issue, but one hypothesis was that it was caused by `node-gyp rebuild` not finding node or running using the wrong version of node (0.12).

**Comment by martijnwalraven** [comment]
Is this on the current release or devel?

**Comment by abernix** [comment]
This is very likely the (now-classic) tale of using a different version of node to build the binary dependencies of the module than the one that Meteor is running it with.  `meteor npm rebuild` inside an existing problem should resolve this problem.

:wave:
