### ISSUE TITLE
OSX <> Windows problems when syncing with Dropbox

### ISSUE THREAD

**Issue by obiwarn** [meteor/meteor#4975]
We share our projects via Dropbox.

OSX:
create project
build

Win 10:
build the same project

OSX:
After Dropbox sync meteor seems kind of broken:
Wherever we call "meteor run" it throws the error below.

Solution on OSX: 
delete ~/.meteor
reinstall meteor

The error:

module.js:340
W20150817-11:11:28.049(2)? (STDERR)     throw err;
W20150817-11:11:28.049(2)? (STDERR)           ^
W20150817-11:11:28.050(2)? (STDERR) Error: Cannot find module 'fibers'
W20150817-11:11:28.050(2)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150817-11:11:28.051(2)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150817-11:11:28.051(2)? (STDERR)     at Module.require (module.js:364:17)
W20150817-11:11:28.051(2)? (STDERR)     at require (module.js:380:17)
...

**Comment by stubailo** [comment]
The `.meteor/local` directory is not meant to be shared across different machines and contains platform-specific temporary files. As a courtesy, we include a `.gitignore` file in there so that people sharing code with Git don't include that folder, but with Dropbox you will need to add that to be excluded manually. Here are some options for using selective sync: http://stackoverflow.com/questions/12119613/is-there-a-way-to-tell-dropbox-not-to-upload-a-certain-file-eclipse-related

**Comment by obiwarn** [comment]
Strange is that this seems to break the meteor installation.

I could not build any project afterwards.

I had to reinstall meteor.
