### ISSUE TITLE
(Bug?) Reactivity Problem: Template instance variables in templates instantiated in an #each block

### ISSUE THREAD

**Issue by convexset** [meteor/meteor#4977]
# A Reactivity Problem with Template Instance Variables in `#each` Blocks?

### Environment and Requirements
- This requires `meteor add reactive-var`
- Tested on Meteor 1.1.0.3

### Description
- In the JS code, a very simple "reactive array" is created. Whose elements are used in an `#each` block to populate a list.
- Standard reactivity works.
    * Adding to the "reactive array" (push and activate `xxx.changed()`)
    * Updating particular elements of that "reactive array"
- However, when elements are removed, template instance variables become inconsistent (try getting rid of something in between):
    * Template instances point mismatched data and local variables
    * Note that instances are not re-created (nothing is logged to the console).
    * To directly poll the data and instance local, hit the "Show value in Reactive-Var" button
- It seems like DOM elements are being recycled but template instance variables are not being "moved" to the same template instances the data got ported over to.

### Questions
- Is the use of template instance variables in this manner an anti-pattern?
- When the underlying data store is replaced with a `Mongo.Collection` stuff works "magically", is there some special thing that has to be done to get things to work? Some secret `Tracker` sorcery? What is going one?????

### Reproduction
See https://github.com/convexset/meteor-template-instance-reactivity-problem

**Comment by stubailo** [comment]
So here is what is happening:

1. Blaze doesn't see it as array elements moving, it sees that the data in each element is changing
2. `this.data` inside `onCreated` is not reactive, so when the data is updated it doesn't update the instance variable

There are three possible fixes:

1. Use `Template.currentData()` in an autorun, which is reactive:

```
Template.reactiveArrayItem.onCreated(function() {
  var self = this;

  self.myName = new ReactiveVar(self.data.name);
  self.autorun(function () {
    // Copy the name from the data context whenever it changes
    self.myName.set(Template.currentData().name);
  });
});
```

2. Add an `_id` field to your array objects, which similar to the "sorcery" that makes it work with Minimongo. So instead of `[1, 2, 3]`, the array would be: `[ {_id: 1, value: 1}, {_id: 2, value: 2} ]`.

3. Instead of making a reactive array object, use a local Minimongo collection instead: `var myArray = new Mongo.Collection(null);`

Probably the first solution is easiest right now.

It's documented here (wow, it's really hard to find): https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#reactivity-model-for-each

**Comment by stubailo** [comment]
Also, thank you for the extremely detailed reproduction. Super appreciate it.

**Comment by convexset** [comment]
Cool. Thanks. Was wondering what was making things work for
Mongo.Collection but not something basic like what I prepared.

On Wednesday, August 19, 2015, Sashko Stubailo <notifications@github.com>
wrote:

> Also, thank you for the extremely detailed reproduction. Super appreciate
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/meteor/issues/4977#issuecomment-132358502>.
>


-- 
Regards,
Jeremy Chen

**Comment by oliverlloyd** [comment]
Ah ha, I've hit this issue a couple of times and been tearing my hair out trying to figure it out. Removing elements from arrays which are iterated using `#each` with multiple templates that use ReactiveVars has been producing very weird results for me. This just seemed like the *correct* way to do things and everything worked fine until you removed an item and then, huh!?

But the `Template.currentData()` wrapped in `autorun` solution, did the trick! Thank you @stubailo for this very useful response and @convexset for framing the problem so well.

It was quite hard to locate this issue though; this scenario might be a good candidate for an article in the Meteor Guide? Personally, I would love it if the docs could link through to example use cases for various items. But anyway, thanks again, for a while there I thought I was going mad.
