### ISSUE TITLE
return the observeHandle in Mongo.Collection._publishCursor

### ISSUE THREAD

**Issue by welelay** [meteor/meteor#4983]
In [Mongo.Collection._publishCursor](https://github.com/meteor/meteor/blob/df95e8714b7bb5edc5c1b4ca9ecc3a2d28212ce5/packages/mongo/collection.js#L302) the observeHandle is created but not returned. Would it be possible to return it?

This would allow to terminate observe handles early in a reactive join, as shown in "Advanced publications" in Discover Meteor (for now the check `commentHandles[id] && commentHandles[id].stop()` does nothing since commentHandles is always undefined).

Also note that in [minimongo](https://github.com/meteor/meteor/blob/0c93aeb6b6a2d09b1e5c55271b7eb3c5aef09a3e/packages/minimongo/minimongo.js#L245) and [mongodriver](https://github.com/meteor/meteor/blob/7d6e759954d6f3cb15b2d2c76c8e400c04887bbd/packages/mongo/mongo_driver.js#L863) the return value of Mongo.Collection._publishCursor (always undefined) is dutifully forwarded.

**Comment by stubailo** [comment]
I think this would make a lot of sense, especially since the value is passed through and just needs to be returned.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by stubailo** [comment]
Merged, thanks!
