### ISSUE TITLE
Add option to specify port used to run local mongo in development

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4986]
It would be sweet if we could set the local mongdb url with an environment variable or a Meteor.settings. This would feel less hacky when running multiple meteor instances that connect to the same mongo instance.

https://github.com/meteor/meteor/blob/devel/tools/runners/run-all.js#L47

**Comment by stubailo** [comment]
@ccorcos have you tried using `MONGO_URL`?

```
MONGO_URL=mongodb://localhost:1234
```

**Comment by ccorcos** [comment]
```
MONGO_URL=mongodb://localhost:1234; \
meteor --settings settings.dev.json --port 3000
```

Then when I do `meteor mongo` is shows up on 3001

**Comment by sjmcdowall** [comment]
I pretty sure the documentation indicates that meteor mongo is to access the meteor launched mongod .. but in your case it isn't launching it .. Now an enhancement request to have "meteor mongo" pay attention to MONGO_URL may be a pretty nice (and I would think somewhat simple) enhancement.  :)

**Comment by stubailo** [comment]
Don't put the semicolon.

http://stackoverflow.com/questions/10856129/setting-an-environment-variable-before-a-command-in-bash-not-working-for-second

**Comment by stubailo** [comment]
@sjmcdowall I think that would be a separate feature, let's not have that discussion in this thread.

**Comment by sjmcdowall** [comment]
@stubailo Valid point!  And good catch on the ";" issue!

**Comment by ccorcos** [comment]
oh yeah, crap. Well this was the error I'm getting without the semicolon

```
> MONGO_URL=mongodb://localhost:1234 \
meteor --settings settings.dev.json --port 3000

# later on

W20150818-15:14:41.549(-7)? (STDERR)          
W20150818-15:14:41.550(-7)? (STDERR) /Users/chet/.meteor/packages/meteor-tool/.1.1.4.1uijw63++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150818-15:14:41.550(-7)? (STDERR) 						throw(ex);
W20150818-15:14:41.550(-7)? (STDERR) 						      ^
W20150818-15:14:41.550(-7)? (STDERR) Error: failed to connect to [localhost:1234]
W20150818-15:14:41.551(-7)? (STDERR)     at Object.Future.wait (/Users/chet/.meteor/packages/meteor-tool/.1.1.4.1uijw63++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150818-15:14:41.551(-7)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
W20150818-15:14:41.551(-7)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150818-15:14:41.551(-7)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
W20150818-15:14:41.551(-7)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20150818-15:14:41.551(-7)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:98:1)
W20150818-15:14:41.551(-7)? (STDERR)     at packages/accounts-base/accounts_common.js:141:1
W20150818-15:14:41.551(-7)? (STDERR)     at /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/build/programs/server/packages/accounts-base.js:243:4
W20150818-15:14:41.552(-7)? (STDERR)     at /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/build/programs/server/packages/accounts-base.js:1659:3
W20150818-15:14:41.552(-7)? (STDERR)     at /Users/chet/Code/meteor/shindig/shindig-app/.meteor/local/build/programs/server/boot.js:222:10
W20150818-15:14:41.552(-7)? (STDERR)     - - - - -
W20150818-15:14:41.552(-7)? (STDERR)     at [object Object].<anonymous> (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
W20150818-15:14:41.552(-7)? (STDERR)     at [object Object].emit (events.js:106:17)
W20150818-15:14:41.552(-7)? (STDERR)     at [object Object].<anonymous> (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
W20150818-15:14:41.552(-7)? (STDERR)     at [object Object].emit (events.js:98:17)
W20150818-15:14:41.552(-7)? (STDERR)     at Socket.<anonymous> (/Users/chet/.meteor/packages/mongo/.1.1.0.r0tpk6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
W20150818-15:14:41.552(-7)? (STDERR)     at Socket.emit (events.js:95:17)
W20150818-15:14:41.552(-7)? (STDERR)     at net.js:441:14
W20150818-15:14:41.552(-7)? (STDERR)     at process._tickCallback (node.js:442:13)
```

**Comment by ccorcos** [comment]
when you specify MONGO_URL, I don't think meteor spins up a mongo instance for you

**Comment by stubailo** [comment]
Oh. I didn't realize that's what you wanted. You're saying that you still want `meteor` to start the database for you, but you want to configure the port so that it can be stable.

That makes sense!

Misunderstood the request.

**Comment by ccorcos** [comment]
There we go! :+1:

**Comment by sjmcdowall** [comment]
Ahhh -- ok.  I would think instead of changing the meaning of MONGO_URL .. maybe better as a command line switch like --mongoPort XXXX that would do the "right thing" ?

**Comment by stubailo** [comment]
Yep, that's what I'm thinking too. And it would only be useful in development, anyway.

**Comment by ccorcos** [comment]
exactly

**Comment by AdamCanady** [comment]
Hey folks, I looked into this a little bit because I'm trying to learn the meteor codebase and I thought this would be a good start. 

[Here's the line](https://github.com/meteor/meteor/blob/3d2282d9ad0b570b913a70d215cd968019d912df/tools/runners/run-all.js#L47) where the port is actually incremented by one. It would need a conditional to change to a provided option. Speaking of which, [here's where the options are parsed out of the run command](https://github.com/meteor/meteor/blob/838937e4ecd0350e85ae9d69e05549cae70ddfc9/tools/cli/commands.js#L190-L217). Those options are passed into Runner [here](https://github.com/meteor/meteor/blob/838937e4ecd0350e85ae9d69e05549cae70ddfc9/tools/cli/commands.js#L389-L408), so it would probably need to pass through there, and finally, Runner receives the options in it's constructor [here](https://github.com/meteor/meteor/blob/3d2282d9ad0b570b913a70d215cd968019d912df/tools/runners/run-all.js#L19-L37) and just a few lines below that is the original `mongoPort` declaration.

Of course, some thought would have to go avoiding conflicts with an existing `MONGO_URL` and other specified ports, but this ought to be a good start.

**Comment by necmettin** [comment]
Ping, after six months. I could really use this feature. I would be nice to let the user (me) decide the Mongo port (much like letting the user (me) decide Meteor port).

**Comment by abernix** [comment]
I'd like to get more input from those who are +1'ing this feature:

* Why do you need to set the Mongo port yourself?
* What's wrong with just knowing that the Mongo port is your "app port" + 1?

**Comment by necmettin** [comment]
I have no idea of the current situation (not using Meteor anymore), but I will answer your questions anyway.

```Why do you need to set the Mongo port yourself?```
- Because `default port` does not mean `actual port`. I should be able to choose actual port for MongoDB, just like I'm able to choose for MeteorJS.
- Port is part of the URL, as such, I should be able to choose MongoDB port. I run my MongoDB on a different port. I should be able to provide MongoDB port just like I'm able to provide MongoDB IP/URL.

```What's wrong with just knowing that the Mongo port is your "app port" + 1?```
- Because it is an arbitrary, subjective decision.
- Because it limits me to `appport+1`.
- Because I do not want my development database bound to my development runs. What if I run my own local MongoDB and I want all my development databases kept in my local MongoDB installation. `appport+1` is only valid when the app is running, but I want to be able to access the data when the app is not running.

**Comment by abernix** [comment]
Thanks for the response!

It seems that there is still some confusion about this still.  If you run your own Mongo, you can set the `MONGO_URL=mongodb://localhost:27017` (or any `MONGO_URL`, local or remote) you would like.  This has always been supported and seems like it addresses most of your desires.  Additionally, Meteor will not spin up its own Mongo if you do this.

The need to not have to start your own Mongo is a simplicity feature of Meteor.  More advanced users (which most of your bullet points fall into) can still set their own `MONGO_URL`.  Adding a port specifier for Mongo is more complex and might confuse some users and I just don't see most users wanting to have their development Meteor Mongo bound to a specific different port, and in general, caring at all. Those who do could just use `MONGO_URL`, no?

**Comment by necmettin** [comment]
Sorry about the latest bullet point, not related.

This issue is about running the Mongo that comes with Meteor in a port of my own choice, not about connecting to a different Mongo.

If you set Meteor to port 3000, bound Mongo runs on 3001. I should be able to change that 3001. This issue is about that.

**Comment by abernix** [comment]
> Sorry about the latest bullet point, not related.

No worry.

> I should be able to change that 3001. This issue is about that.

I personally only see two reasons why that could be the case though:

* You want to know what it is, for some reason. (e.g. You want to connect to it, maybe?  But you can just use `meteor mongo` to do that).
* Something else conflicts with it (i.e. something already running on port 3001).  This is the only potential issue I see you could actually run into (i.e. block development) but you could easily just run Meteor on port 4000 (and Mongo would then be 4001).

The question is, in determining a feature's usefulness is: More features add more complexity/confusion/args.  Would 99+% of users really need to run their Meteor on port 3000 and their Meteor Mongo on port 2500 (or any other port)?  My intuition says no.  Do you disagree?

**Comment by hwillson** [comment]
Since there doesn't appear to be much interest in this feature request, and there are several acceptable workarounds to almost every point brought up in this issue (see https://github.com/meteor/meteor/issues/4986#issuecomment-250712296 and https://github.com/meteor/meteor/issues/4986#issuecomment-250715250), the time has come to close this issue. Thanks for posting this originally!

**Comment by teebszet** [comment]
> What's wrong with just knowing that the Mongo port is your "app port" + 1?

is this documented somewhere?

**Comment by abernix** [comment]
@teebszet It's documented in `meteor help run` on the command line – though I admit it would be nice to have on http://docs.meteor.com/commandline.html#meteorrun (which is a relatively new addition to the docs).  A pull-request (by using the "Edit on GitHub" button) to that page in order to make that N+1 detail clear would be greatly appreciated!

**Comment by kakadais** [comment]
This issue seem like closed long time ago, I think this approach would be good to go for some cases.
N+1 port would makes our life easy but sometimes we need to test it with the other port as well.
So, left the default settings N+1, and another option would be great to be used (like --dev-mongo-port 27017)
