### ISSUE TITLE
nested sub-expression

### ISSUE THREAD

**Issue by 466023746** [meteor/meteor#5011]
class="go {{activeClass (countsPrev1 counts)}}"
 error:While building the application:
   client/template/pagination.html:30: Expected identifier, number, string, boolean, or null
   ...ss="go {{activeClass (countsPrev1 counts)...
why i can't use this?

**Comment by grsabreu** [comment]
I guess you really do not need those parentheses

**Comment by stubailo** [comment]
You don't need the parentheses, because the way Handlebars executes function calls looks just like what you have there. However, subexpressions with parentheses _is_ a new feature that is coming in Meteor 1.2, from this PR: https://github.com/meteor/meteor/pull/4101

So the answer to your question is:

1. Your code will work as is without the parentheses
2. This doesn't work in current Meteor
3. The sub-expressions with parentheses will work starting with Meteor 1.2
