### ISSUE TITLE
Run meteor app as a service

### ISSUE THREAD

**Issue by kirgene** [meteor/meteor#5019]
I need to run multiple network system services (like rabbitmq service) and I want to use Meteor for this (to share the same codebase). These services are not REST. They should only collect some data and store it in MongoDB.
Is it possible to achieve this task in Meteor?

**Comment by sjmcdowall** [comment]
This is better suited for the Meteor Forums and not the back tracking system .  However, since Meteor can access and use just about any NPM module -- if it's available and you can do it with node/npm there isn't any reason why you can't create/write a server only side Meteor application.  Of course something like Loopback.io maybe better suited to what you need. Hard to tell.

**Comment by kirgene** [comment]
Thanks!

**Comment by avital** [comment]
Thanks @sjmcdowall for helping
