### ISSUE TITLE
Don't have `webapp` use a magic string to inform the dev mode proxy that it's ready to accept connections

### ISSUE THREAD

**Issue by acemtp** [meteor/meteor#5022]
here is the repo:

> git clone git@github.com:peernohell/meteor-console-log.git
> cd meteor-console-log
> meteor

and launch a browser on http://localhost:3000

the client cannot load the page and then timeout.

it happens at least on mac 10.10.4 with meteor 1.1.0.2 and 1.0.1.

any idea?

the source code is the default project with just one line to override the console.log:

https://github.com/peernohell/meteor-console-log/blob/master/test-log.js#L20

no error, meteor shell is working and i can type commands, everything seems ok except that clients cannot connect (like if the listen port isn't binded)

**Comment by gabrielalmeida** [comment]
Meteor silently fails to start the app, even with ```--verbose``` flag, found nothing with ```meteor debug``` also. While I couldn't debug and understand why it's failing to start, you are able to get it to work by doing:

```js
    console.log('log 1');

    var consoleObj = _.clone(console);
    console = console || {};

    console.log = function(msg){

      // Do some crazy thing while logging
      // make sure you're returning normal console.log result

      return consoleObj.log(msg);
    };

    console.log('log 2');
```
And you'll get the app running, ```console.log``` default behavior and your modifications:

```console
Local package version is up-to-date: webapp@1.2.0
Local package version is up-to-date: webapp-hashing@1.0.3
=> Started your app.

=> App running at: http://localhost:5000/
I20150825-02:35:31.998(-3)? log 1
I20150825-02:35:32.000(-3)? log 2
```

Seems that Meteor internally expects ```console``` methods to work as it is. Why do you need to override? Overriding probably isn't a good path. Check [praticalmeteor/loglevel](https://github.com/practicalmeteor/meteor-loglevel/) for instance.

**Comment by acemtp** [comment]
Indeed, it's really strange.

I know there s some workaround but I still think it should work even if it's not a good path.

In my case, I override console.log to send logs to logentries.

**Comment by gabrielalmeida** [comment]
Agree with you that it should just work, or at least show why it does fail.

But, even on your use case, IMHO it would be better to take another approach, like creating a ```Logger``` object that does the job and just uses ```console``` internally for local debug purposes.

Lookback does something similar to what you're trying to achieve, but with Loggly instead of Logentries, check their [approach](https://github.com/lookback/meteor-logger).

**Comment by avital** [comment]
Here's what's happening:

In `packages/webapp/webapp_server.js`, we log "LISTENING" once the HTTP server is up and running. When running in development, this is a child process listening on some randomly chosen port, or the value of the command-line argument `app-port`, if it's passed in.

In `tools/run-app.js`, we look at stdout from the webapp server and wait to see the string "LISTENING" before we start proxying incoming requests aimed at localhost:3000 to the child process listening on the other port.

(I found this by replacing the contents of `console.log` with: `console.trace('log')`.)

So, yes, agreed this is a little weird; but your workaround is to at the very least pass through the "LISTENING" string when you change the implementation of `console.log`.

Happy to look at a pull request changing the logic in `tools/run-app.js` so that instead of looking for a magic string, it just tries to connect to the server every so often until it finds that it's listening.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Don't%20have%20%60webapp%60%20use%20a%20magic%20string%20to%20inform%20the%20dev%20mode%20proxy%20that%20it's%20ready%20to%20accept%20connections&body=Migrated%20from:%20meteor/meteor%235022) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
