### ISSUE TITLE
Client loses connection to server on server restarts

### ISSUE THREAD

**Issue by laddi** [meteor/meteor#5027]
We've been scratching our heads over a peculiar issue for a few months now, specifically that when in a logged out state we lose connection from client to the server.  We managed to figure out that this scenario would happen after a long idle time and a server restart without a client reload.

On further investigation we found out that this happens when you have publications/subscriptions but you are only publishing data for logged in users.  That will create a "weird" state where losing the connection to the server and reconnecting will not really reconnect successfully.  Running `Meteor.status()` will also report that the connection is active.

I've create a [repository](https://github.com/laddi/connection-test) that replicates the behavior and I also created a [screen grab video](https://www.dropbox.com/s/ec0v5rmw9898waw/lost-connection.m4v?dl=0) for further explanation.

**Comment by laddi** [comment]
FYI, this is probably related to #1942

**Comment by stubailo** [comment]
@laddi OK it took a while, but I managed to track down the underlying issue. Here's what happens:

1. You subscribe to `TestCollection.find()`. All of the documents load, and you get a `ready` message from the server. Everything is good, and the client helpfully remembers that you were subscribed to a subscription named `Test`.
2. You log out and restart the server. The client helpfully thinks that you would like to remain subscribed to `Test`, and in order to avoid flicker or weird results blocks everything after the reconnect until the `Test` subscription is `ready`.
3. The `Test` subscription _never_ becomes ready if you are logged out. If you return `undefined` or `null` from a publication, it thinks that you are going to use the manual `this.ready()` to mark it as ready.

So basically, this is the result of the client trying to be helpful by automatically waiting for a subscription to finish on reconnect, and a janky api for Meteor.publish where it is easy to have a subscription that never thinks it is ready. I think this is just one of many good reasons to change the API of `Meteor.publish` to make this situation not happen.

### Fix for your code

All you have to do in your repro app to stop this from happening is return something from the publication when the user is logged out, like so:

```js
        Meteor.publish('Test', function() {
            if (this.userId) {
                return TestCollection.find();
            }

            // This tells Meteor that you are done with this publication
            return [];
        });
```

However, I'd say this is deathly close to being a real bug, since no sane person would know that this is how you are supposed to use publications.

**Comment by stubailo** [comment]
Filed a feature request here: https://github.com/meteor/meteor/issues/5029

**Comment by laddi** [comment]
```javascript
Meteor.publish("secretData", function () {
  if (this.userId === 'superuser') {
    return SecretData.find();
  } else {
    // Declare that no data is being published. If you leave this line
    // out, Meteor will never consider the subscription ready because
    // it thinks you're using the added/changed/removed interface where
    // you have to explicitly call this.ready().
    return [];
  }
});
```

This is actually in the Meteor documentation, should have realized that I needed to return something.  Makes total sense, thank you so much! :)

**Comment by pdiniz13** [comment]
I am having the same issue, but I am returning an array for all of my collections.
