### ISSUE TITLE
Building meteor on Solaris / SmartOS

### ISSUE THREAD

**Issue by eimann** [meteor/meteor#5037]
I am running node on Joyent's SmartOS platform, thus trying to install meteor.
Even when cloning the git repository and building meteor myself I'm getting this message:

[node-runner@v00020100239 ~/meteor]$ ./scripts/generate-dev-bundle.sh    
This OS not yet supported

It does not even try to build. Whatever it needs to do so should already be in this environment.
There's a gcc, npm, many libraries.

How am I going to fix this? What infos do you need?
I can also provide appropiate build hosts for you to use.

**Comment by sjmcdowall** [comment]
As SmartOS is not a supported platform (much as I love it!) -- I think you are going to be pretty much on your own here.  A little google searching has this :  https://www.mail-archive.com/smartos-discuss@lists.smartos.org/msg01770.html

That may give you some ideas on how to get Meteor up and running on either a native SmartOS or LX branded "VM".  Good luck!

**Comment by stubailo** [comment]
@eimann if you are doing this to deploy your Meteor app, you should instead follow the directions here: http://docs.meteor.com/#/full/deploying

Unfortunately, Solaris/SmartOS is not currently a supported environment for development. You can try to remove the checks from `generate-dev-bundle` to see if it will build anyway. Then the Meteor forums would be a good place to discuss how it's going: https://forums.meteor.com/

This isn't really a bug because it's not one of the architectures we support. If you like, I can reopen this as a feature request for SmartOS support.
