### ISSUE TITLE
[1.2 RC] Can't add a file as source and asset

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5040]
@Sanjo originally posted:

I can no longer add a file as source file and also as asset:

```
api.addFiles(['src/lib/VelocityTestReporter.js'], ['server', 'client'])
api.addFiles(['src/lib/VelocityTestReporter.js'], 'server', {isAsset: true})
```

Now gives the error:

```
=> Errors prevented startup:                  
   
   While reading package from `/Users/jonas/Projects/sanjo:jasmine/test-app/packages/sanjo-jasmine`:
   package.js:118:7: Duplicate source file: src/lib/VelocityTestReporter.js
   at package.js:118:7
   at 
   
   
=> Your application has errors. Waiting for file change.
```

I can work around that if you decide to leave it like that. Just wanted to let you know that this is a breaking change.

**Comment by stubailo** [comment]
@Sanjo, can you help me understand some of the cases where you would want a file to be a source and an asset?

**Comment by Sanjo** [comment]
I only have my case, that is:

sanjo:jasmine has different testing modes that have different implementations. All testing modes have in common that they use Jasmine and use the Velocity test reporter for Jasmine that is part of the package (the VelocityTestReporter.js). Therefore I use the VelocityTestReporter.js in every testing mode. In the client unit mode I use the Karma test runner. I use the asset mechanism to load it, because it gives me a constant path the the original file. In the integration modes however, I load the VelocityTestReporter.js as source because in those modes the mirror mechanism is used. The mirror mechanism just starts the app in a testing mode.

**Comment by stubailo** [comment]
Is there some reason that you need the original file loaded as an asset? Does it not work if you include it as a client-side source file?

**Comment by Sanjo** [comment]
Thanks for the fix. :-)

**Comment by stubailo** [comment]
Yeah I'm glad it actually ended up improving the janky `{isAsset: true}` thing into a "real" API.

**Comment by stubailo** [comment]
Done! should come out in the next RC.
