### ISSUE TITLE
Build Plugins API: add a warning method on files

### ISSUE THREAD

**Issue by RomFouq** [meteor/meteor#5043]
The new Build Plugins API seems great by providing new ways to hook into the build process; it defines an `error` method on files that should called to raise a linting error, according to the wiki: https://github.com/meteor/meteor/wiki/Build-Plugins-API.

I think adding a `warning` method, which only reports messages, would be useful, especially for linters.
For example, Coffeelint has a `warning` level (http://www.coffeelint.org/#options) enabling this behaviour, but I think the Build Plugins API doesn't provide a clean to report them for now.

**Comment by stubailo** [comment]
I think part of the thinking here was that warnings aren't very useful because they are easy to ignore, but since a lot of linters support warnings it probably makes sense to have that be possible.

What do you use warnings for in your linter?

I don't think this feature will make it into Meteor 1.2 at this point, but we should think about it for the next release.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Build%20Plugins%20API%3A%20add%20a%20warning%20method%20on%20files&body=Migrated%20from:%20meteor/meteor%235043) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
