### ISSUE TITLE
Add default license file to meteor create --package with MIT license

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5060]
People forget to add licenses to their packages, we could help people out here by generating a default one like Atom's package generator.

**Comment by jeffmitchel** [comment]
Works for me, as does having publish complain if there isn't a license file.

**Comment by queso** [comment]
Personally, I think it is fine. I think if you care about which license you want, you can change the text of the file before you publish code...

**Comment by VladShcherbin** [comment]
Sure, this can be added. I also think that people, who want to use another (not MIT) license always add this file. And the people, who don't add license understand that and make the package free (or like MIT license).

Do we really and why need to set this license (except when it is not MIT) ?

**Comment by ManuelDeLeon** [comment]
I would recommend the process to be more obtrusive because of its legal implications. Probably ask the user upon `meteor create --package` if they want to add an MIT license if there isn't one.

**Comment by msavin** [comment]
I think its a good idea to protect the developers who distribute packages. If they publish something without a waiver, aren't they liability for potential damages?

**Comment by stubailo** [comment]
> It can be something just to clarify that the package is free, unsupported, no liability, and the code may not be re-distributed unless otherwise stated.

I don't think there is a standard license that does this. Doesn't free imply that the code can be re-distributed? Like using a package in your app === distributing code AFAICT.

**Comment by msavin** [comment]
Well, may pay to define the terms.. and to pay a lawyer to figure it out :) 

I believe GitHub has some kind of default license for public repositories that do not have a license. Maybe there are some clues there too.

**Comment by queso** [comment]
Again, I wouldn't want to tangle this up in a bunch of thoughts about legality. Just slap an MIT file in there and people can change it before release if they want to. I see this ticket as more of a friendly reminder to package devs than anything else.

**Comment by arunoda** [comment]
I like it :) 
One of the thing we forget to do.
But then it seems like some opinionated thing, since some people use some other licences.
Then if we wanna support more licences, I think that's an overkill and we have more important stuff.

I think eventually, Github will introduce a similar feature (or do they have it)

So, I think this is okay. But not important or needy at this moment.

**Comment by stubailo** [comment]
Since meteor itself is already MIT licensed, I don't think it would be any more opinionated to suggest that as a default license for packages.

**Comment by msavin** [comment]
If Meteor plans to serve the enterprise market, licensing will be need to be covered well. No license is a liability both ways. I think there needs to be "default" license, maybe baked into the Meteor TOS. But then again, I'm not a lawyer...

**Comment by jeffmitchel** [comment]
It is opinionated, but that may not be a bad thing, especially if the opinion can be easily overridden. In this case via a simple rm command. My opinion is that this helps more than it hurts. Also this: http://choosealicense.com/no-license/

**Comment by rgoomar** [comment]
I like the idea of adding a license by default. If you look at most packages out there, they are licensed MIT anyway. And those packages that get an issue asking about the license, it is typically set to MIT. As a start, I would say default it to MIT and then add on other licenses to choose from when creating a package. 

I think it would be cool to have some sort of prompt that comes up when you create a package asking what kind of license it would be.

**Comment by hitchcott** [comment]
Another idea to throw in for discussion: maybe this could be part of the `meteor publish` process? As atmosphere is actually hosting the packages it seems like checking for a license of some kind would be a good way to reduce the likelihood of legal issues for all parties.

Basically I'm suggesting that if a package is published without a license specified, the published will get a message like "In order to publish to atmosphere you must specify a license. Would you like to use the MIT license now? [Y/N]"

That way developers using `meteor add` will not accidentally be adding copyrighted code to their projects - showing a warning if no license is registered (for old packages). The license of the package could be shown when it is added to a project, and shown next to each package on atmospherejs and in `meteor show`.

In package.js there could be a `license` option just like the `git` option. Then people wouldn't even need to include the license file itself -- they just specify `license: "MIT:2015"` or `license: "GPLv3:2015"`. 

Sure, it's easier to do it using `meteor create` but I think this wouldn't solve the problem of people accidentally having unlicensed packages in their projects, because I would guess that not many people actually use `meteor package --create` to start their packages -- I just write the package.js file manually.

**Comment by zimme** [comment]
I've thought about this a bit too.

What I came up with, before seeing this thread, was that it would be nice to see Meteor requiring a license being specified in the `package.js` file, defaulting to `'LICENSE.md'`, when publishing a package.
The same kind of style `documentation` have.

In case a user actually don't want a license they will have to specify `false` explicitly, and live with the consequences :stuck_out_tongue_winking_eye:

A default `LICENSE.md` file with the MIT license in it could be create when doing `meteor create --package <package:name>`. What the default license should be is to be decided, but MIT is a pretty widely used permissive license which seem to suit the Meteor community.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20default%20license%20file%20to%20meteor%20create%20--package%20with%20MIT%20license&body=Migrated%20from:%20meteor/meteor%235060) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
