### ISSUE TITLE
PR Proposal: Fix HTTP param encoding logic for objects and arrays

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#5065]
At Dispatch we are overwriting the param encoding that the `http` package uses to allow it to properly handle arrays and objects. We have open sourced the fix as a package: https://github.com/DispatchMe/meteor-url-encode-params

I am looking for general community and MDG agreement that this is the correct way to handle param-to-query conversion. If there is agreement, we are happy to submit this as a PR.

**Comment by stubailo** [comment]
It's pretty clear to me that your output is better than printing `[object Object]` into the param string.

Just to explore a little more: this is one of those things that doesn't seem to have a standard; what kinds of backends does this encoding work with? For example, does Rails parse your format correctly by default?

**Comment by creeonix** [comment]
Rails and PHP parse that exactly as expected out of the box (to array and hashes).

`param[]=1&param[]=2` is expected to be decoded to `{"param": [1,2]}`
`param[0]=1&param[1]=2` is expected to be decoded to hash `{"param": {"0": 1, "1": 2}}`

For jQuery: http://api.jquery.com/jquery.param/

We have used same pattern in ASP.NET too and in Flex before. So, I'd say it is silent standard.
However, http://jsonapi.org/recommendations/#urls-resource-collections - uses shortened version of array encoding: `/comments?filter[post]=1,2&filter[author]=12`.

In our current project on rails API (dispatch.me) we support both ways: `filter[post][]=1&filter[post][]=2` OR `filter[post]=1,2`, second one saves when get request is getting too big.

**Comment by aldeed** [comment]
Yes, what @creeonix said. :) Except it appears that node is sadly one of the few that stringifies a bit differently: https://nodejs.org/api/querystring.html

**Comment by stubailo** [comment]
Sigh! This is why stringified JSON is the way to go IMO (at least if you control both ends of the wire)

Hmm, it is a shame that node doesn't parse this correctly. I guess it's not a big deal though because we could always add an option to use a different strategy later. I'll take another look at this on Monday, remind me!

**Comment by stubailo** [comment]
If you could submit that pr that would be awesome!

**Comment by stubailo** [comment]
Hey just a heads up, would be great to have this PR!

**Comment by hwillson** [comment]
I've created PR #8261 with the proposed/discussed changes (thanks @aldeed!).

**Comment by abernix** [comment]
This should be fixed in Meteor 1.4.3.1 thanks to @hwillson's PR!  Thanks!

    meteor update --release 1.4.3.1

The result is that `Array`s and `Object`s will be encoded in a way more similar to Rails, PHP and `jQuery.param`.  `Object` were not previously serialized at all, but `Array`s were simply `join`-ed with commas.  If you're encountering a problem with the new encoding and you're passing an array (and expect it to be joined in this way), you should simply `[].join(',')` the array into `String` yourself, prior to passing it to `HTTP.call`.  For more information on this (and one problem which popped up internally), see https://github.com/meteor/meteor/pull/8261#issuecomment-278708655.

Closing!
