### ISSUE TITLE
Subscriptions fail to fully populate on the client for "large" collections (max size browser-dependent)

### ISSUE THREAD

**Issue by ewyler** [meteor/meteor#5075]
Repro code: `git clone https://github.com/ewyler/meteor-large-count-publish-bug.git`

Local setup: Windows 10

STR:
1. Run the meteor application either locally or deployed to meteor.com. The issues are reproducible on either. You'll need to wait a minute or two for the collection to be initially populated on the server with 200,000 items 48 bytes in size.
2. Open up the javascript console. The "onStop" and "onReady" methods log to the console if they ever get called.
3. Watch  "List count" increase in the browser as items are received on the client.
4. Behavior from here varies per browser, detailed in the following table:

| Browser | Items received on client (out of 200k) | Tries again? | onStop or onReady called? |
| --- | --- | --- | --- |
| Chrome 44.0.2403.157 m | ~60k | Yes | No |
| Firefox 40.0.03 | 200k | No (completes successfully) | Yes, onReady |
| Internet Explorer 11.0.10240.16431 | ~6.5k | Yes | No |

Documentation points to no limitations on MiniMongo DB size - this is about 10MB of data. I'd expect an error or something to occur, but instead the browsers which aren't successful continue to retry ad infinitum.

**Comment by gazhayes** [comment]
I get to ~115k on Chrome Version 44.0.2403.157 (64-bit) (Yosemite). Neither onStop nor onReady called.

**Comment by avital** [comment]
My guess is that this isn't a Minimongo issue, but rather an issue with DDP heartbeats, where the server closes the client's connection if it hasn't received a heartbeat in a while, and the client is overloaded dealing with all of the incoming messages so that it doesn't set aside any time for the event loop to deal with sending a heartbeat to the server.

It may be related to #207 which seems to have been resolved, though maybe not in all cases.

Leaving open for now.

Though, honestly I don't think Minimongo would perform well with so many documents anyways -- for one thing, it doesn't have indexes so any operation other than `findOne` on a specific document id would be very slow.

If you simply want to fetch 200k documents from the server maybe better to get them directly from a method and not involve Minimongo at all.

**Comment by ewyler** [comment]
That makes plenty of sense - I don't have a specific use case for it, I was mostly evaluating the viability of Meteor for a production system. The fact that this fails concerns me less than the fact that there appears to be no way to get a notification or status that the failure occurred - so you have effectively no way to react to it, monitor it, or give an error to a user. Things will just mysteriously...not work. The significant differences between browsers is also concerning (IE barely makes it to 10k records in most cases, which I don't think is a significant number).

**Comment by ewyler** [comment]
I did some more tests on this to see if a manual partitioning scheme across subscriptions would help - I created 200 publications and subscribed to them all, with each publication only publishing 1000 items. It allows Chrome to presumably make it to 200k (I got bored around 165k), but it gets progressively slower - until it hangs every 5 subscriptions for 100+ seconds, restarts that subscription, chugs a little further and repeats. IE is still slow as molasses but does also reliably make it farther, but it still tends to keep failing more frequently as the total item count on the client increases. Firefox still far outperforms the others and makes it to 200k without many hiccups.

There is obviously a lot of browser-specific behavior here which may also be to blame - DDP is certainly part of it, but some browsers do appear to just not like a large Minimongo DB, since performance of individual subscriptions degrades as the DB grows.

I plan to try partitioning across collections to see if the behavior is specific to collection size, but even if that worked, having to partition across collections would be really unfortunate since you're back to manual partitioning schemes.

**Comment by Krisa** [comment]
That's an interesting issue. I have an existing node.js app (on express, mongoose/mongodb, websocketserver) which are doing together really heavy operations (manipulation of hundreds of thousands of records (each record ~5KB, not 48B!) client-side) and this performs really well (with a solid client-side connection) on a single free heroku dyno (but mongoDB on SSD).

I was looking whether Meteor could be a viable alternative but when looking at your issues (large collection too, but each record is actually very small), I fear it's quite far from doing what I can do with a regular node.js app. 

At the end, Meteor offers many cool real-time features which are not that much required for my app, and ultimately, such heavy DB operations are maybe not what Meteor is intended for.

**Comment by abernix** [comment]
Thanks for opening this originally!  I'm going to close this because we're cleaning up old issues and this is relatively idle and hasn't been a popular problem (and may be resolved)  Please see duplicate issues #2466 and also #5680 which may help.

We'd be happy to reopen if it's still a problem but please also try to include a reproduction on a recent version!
