### ISSUE TITLE
#each behaves differently with array of objects and strings

### ISSUE THREAD

**Issue by ManuelDeLeon** [meteor/meteor#5079]
If I have an array of strings and remove the first item I get the expected result: the first template is removed.

```html
<body>
  <button>Remove First</button>
  {{#each people}}
    {{> person }}
  {{/each}}
</body>

<template name="person">
  <br> {{name}}
</template>
```

```js
if (Meteor.isClient) {
  var arr = ["A","B","C"];
  var dep = new Tracker.Dependency();

  Template.body.helpers({
    people: function() {
      dep.depend();
      return arr;
    }
  })

  Template.body.events({
    'click button': function(){
      arr.splice(0, 1);
      dep.changed();
    }
  })

  Template.person.onCreated(function(){
    this.name = this.data;
  })

  Template.person.helpers({
    name: function(){
      return Template.instance().name;
    }
  })
}
```

Before clicking the button:
![image](https://cloud.githubusercontent.com/assets/4257750/9585866/a2e1c18e-4fd6-11e5-883e-5e5c82dc14f4.png)

After clicking the button:
![image](https://cloud.githubusercontent.com/assets/4257750/9585911/d9f8339c-4fd6-11e5-95bd-ba7f6377451d.png)

But if I then use an array of objects it removes the **last** template. It leaves the first template (which the array doesn't have) and it removes the last one (which the array does have).

```js
if (Meteor.isClient) {
  var arr = [ {name: "A"}, {name: "B"}, {name: "C"} ];
  var dep = new Tracker.Dependency();

  Template.body.helpers({
    people: function() {
      dep.depend();
      return arr;
    }
  })

  Template.body.events({
    'click button': function(){
      arr.splice(0, 1);
      dep.changed();
    }
  })

  Template.person.onCreated(function(){
    this.name = this.data.name;
  })

  Template.person.helpers({
    name: function(){
      return Template.instance().name;
    }
  })
}
```

Before clicking the button:
![image](https://cloud.githubusercontent.com/assets/4257750/9585866/a2e1c18e-4fd6-11e5-883e-5e5c82dc14f4.png)

After clicking the button:
![image](https://cloud.githubusercontent.com/assets/4257750/9585887/bceb793a-4fd6-11e5-8af9-b8c4eb9567f1.png)

The code is the same except for the array declaration:

```js
var arr = [ {name: "A"}, {name: "B"}, {name: "C"} ];
```

And extracting the name from the context:

```js
Template.person.onCreated(function(){
  this.name = this.data.name;
})
```

I expected the same behavior for both arrays.

Repros:

https://github.com/ManuelDeLeon/arrayIssue-with-Strings
https://github.com/ManuelDeLeon/arrayIssue-with-Objects

**Comment by stubailo** [comment]
@ManuelDeLeon thanks for the detailed reproduction. The reason why this doesn't work is documented here: https://github.com/meteor/meteor/tree/devel/packages/spacebars#reactivity-model-for-each

Instead of removing the template, Meteor re-uses them because we don't attempt to deep-diff array items (neither does React, for example).

You have two options:

1. Declare an `_id` on the array elements so that Blaze knows which item was removed. Change your declaration to:

```
var arr = [ {name: "A", _id: "A"}, {name: "B", _id: "B"}, {name: "C", _id: "C"} ];
```

2. Use the data context in a reactive way. Blaze isn't removing the template, but it is updating the data context - you just aren't getting the change.

If you want to extract stuff from the data context, you should use an autorun with `Template.currentData()`, like this:

```js
Template.comments.onCreated(function () {
  var self = this;
  self.name = new ReactiveVar(null);

  // Use self.subscribe with the data context reactively
  self.autorun(function () {
    var dataContext = Template.currentData();
    self.name.set(dataContext.name);
  });
});
```

This is working as documented, although I will agree that the documentation is a bit hard to find.

**Comment by ManuelDeLeon** [comment]
Nice. Thanks.
