### ISSUE TITLE
[BUG] Accounts.sendVerificationEmail returns error on optional email parameter.

### ISSUE THREAD

**Issue by evolross** [meteor/meteor#5081]
I'm adding "Resend Verification Email" functionality.  If from the server I call:

`Accounts.sendVerificationEmail(user._id, function(error) {...});`

I'm getting the error `No such email address for user`. And I can clearly see the email address at `user.emails[0].address` in Mongo. But if I call:

`Accounts.sendVerificationEmail(user._id, user.emails[0].address, function(error) {...});`

It works.

The documentation says about the **email** parameter: "*Optional. Which address of the user's to send the email to. This address must be in the user's emails list. Defaults to the first unverified email in the list.*"

I can't think of any reason why this wouldn't work without passing an email. So possible bug.

**Comment by avital** [comment]
As far as I can tell from the docs (and also by inspecting the code: https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_server.js#L573), `Accounts.sendVerificationEmail` doesn't let you pass a callback at all -- it runs synchronously, perhaps throwing an error on failure.

So what you're seeing is that it's treating the callback you passed as if it's an email address. I suppose we could improve error handling here, so that it verifies that the `address` argument is a string (happy to take a good pull request). But this isn't a bug.

**Comment by evolross** [comment]
You're right. Confirmed and tested.  Thanks for the quick response.
