### ISSUE TITLE
Blaze: how to dereference a helper with an argument?

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#5087]
Example helper:

```
Template['Admin.console'].helpers({
  socket: function (name) {
    return Connections.findOne({ name: name }, {
      sort: { timestamp: 1 }
    });
  }
});

Template.registerHelper('hasResults', (cursor) => {
  if (cursor instanceof Mongo.Cursor) return cursor.count() > 0;
  else if (cursor instanceof Array) return cursor.length;
  return !!cursor;
});
```

Then in a template:

```
if hasResults(socket 'commands')
  each (socket 'commands').messages
    div
      | {{ message }}
```

Is this possible? If not, can support be added?

**Comment by dgreensp** [comment]
Jade templating is a community package, so I can't answer for sure if this is possible or not, but if you are using `mquandalle:jade`, I think it uses the same expression syntax as Meteor's Spacebars templating.

We've talked about adding fancier expression support to Spacebars, but it is not on our immediate roadmap.

The usual way to write this template code (in Spacebars at least) would be to assign the socket to a variable or the data context, using `#let` or `#with`, and then refer to it.  This also means the database query is only done once rather than twice.
