### ISSUE TITLE
Info: Bug in Cordova affects transfer of information from native side to Meteor

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#5099]
I just wanted to inform you and the users of Meteor's iOS integration about a bug in Apache Cordova (not Meteor itself) that also affects the transfer of information from the native side to Meteor:

https://issues.apache.org/jira/browse/CB-9485

This bug occurs at a central point, where information is sent back from the native side using the **handleOpenURL** method. Due to a strange behaviour of Apple's NSURL implementation, the URL used to encode the data is being truncated with an ellipsis (...). The Cordova team is not to blame here, I would never have expected Apple's framework to do such weird things...

JesseMacFayden from the Cordova team has now fixed this problem, but as far as I can tell from the Apache JIRA, the fix is planned to be included in the 4.0 version of Cordova. For the meantime, it could be an idea to apply the patch to Meteor's Cordova version manually, as it is just a one-liner.

I am not sure how severe this is for common Meteor/Cordova usage (i.e. using the standard Cordova plugins), but for my hybrid application, it was a breaking issue, since the information I wanted to deliver to the Meteor side was too long and had been truncated because of this.

**Comment by avital** [comment]
Wow.

@martijnwalraven Do you think we should act on this?

**Comment by martijnwalraven** [comment]
(I responded to an [initial issue](https://github.com/martijnwalraven/meteor-ios/issues/63) in the meteor-ios repository, but should have posted here too.)

No, I don't think we should do something about this. (Which would have been hard, because we don't actually fork platform-specific projects like cordova-ios.) The bug mentioned is in the built-in `CDVHandleOpenURL` plugin, which is not used as a communication mechanism by either Cordova or Meteor.

@derwaldgeist I'm not entirely sure what you're trying to do here, so correct me if I'm wrong. But although using a URL to communicate from a web view to native code is a common communication mechanism when building a hybrid app from scratch, Cordova contains its own bridge that you can access from plugins. So it might make more sense to write a plugin instead. If for some reason you wanted to avoid that, and you're talking about communicating from native code to JavaScript code running in the web view, couldn't you just use `UIWebView#stringByEvaluatingJavaScriptFromString`?

**Comment by derwaldgeist** [comment]
Hi Martijn, thanks for this clarification. I thought that using handleOpenURL was the standard way to communicate back from Cordova to Meteor, as read this somewhere. If it is safe to use, I will be using stringByEvaluatingJavaScriptFormString instead. Thanks again for pointing me into the right direction.

**Comment by derwaldgeist** [comment]
PS: After revisiting my code, I now know why I was implementing the communication using the handleOpenURL method. This is because the CDVViewController's corresponding method processOpenURL automatically defers the call until the web view has successfully being loaded. Any call from the native side before this time-point will be cached and executed onPageDidLoad. If I would have called .stringByEvaluatingJavaScriptFormString() directly, my call could be sent out "into the void". Do you happen to know how this kind of messaging is being handled by custom Cordova Plugins? I already started implementing my own plugin, but did not find the right way to implement such a kind of "reliable" message queue. Maybe it's already in Cordova, but I haven't found it yet. This is especially important in Meteor as it might happen that the app is temporarily unavailable due to hot code reload.

**Comment by martijnwalraven** [comment]
I'm no expert on writing Cordova plugins, but reading through the cordova-ios source it seems the recommended way to call into the web view from a plugin is using `[self.commandDelegate evalJs:@"alert('Hello!')"];`, which takes care of some threading issues and puts the call onto the `_commandQueue`. The plugin will only be initialized after page load, so you shouldn't have to worry about that.

**Comment by derwaldgeist** [comment]
Thanks for this tip! Yes, the plugin will only be initialized after page load, but I also do need message queuing from native to the plugin, as my app is hybrid and the user may interact with it before the Cordova side has been loaded.

**Comment by martijnwalraven** [comment]
I don't believe there's a built-in way to do what you want, so you'd have to implement your own queue or otherwise remember what you want to happen on the Cordova side after page load.
