### ISSUE TITLE
[Feature Request] Automatic `publish-for-all-arches`

### ISSUE THREAD

**Issue by hitchcott** [meteor/meteor#5100]
First World Problem, but I'll put it out there anyway.

Seems strange that I'm manually having to `meteor admin get-machine` x 4 every time I want to publish a package version that requires binary code to be compiled. Why can't I just:

```
meteor publish-for-all-arches
```

... and have the arch builds be done automatically?

Or even better, do this transparently on atmosphere servers whenever I do `meteor publish`.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

I definitely feel your pain — we have [a script](https://github.com/meteor/meteor/blob/devel/scripts/admin/publish-meteor-tool-on-all-platforms.sh) to make this process easier for `meteor-tool` and even that script is a bit of a pain!  (Though publishing meteor-tool is harder than other packages because publish-for-arch does not work on it.)  It would definitely be helpful if this were easier (or if a rethinking of how binary packages work in Meteor led to it being unnecessary).

**Comment by hitchcott** [comment]
Aha! I didn't know about that script. That will definitely out for the time being - thanks @glasser.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BFeature%20Request%5D%20Automatic%20%60publish-for-all-arches%60&body=Migrated%20from:%20meteor/meteor%235100) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
