### ISSUE TITLE
Make documentation browser more friendly for search-engines and bookmarks

### ISSUE THREAD

**Issue by brylie** [meteor/meteor#5125]
As a developer, I am continually frustrated when following links to the Meteor documentation. Many times, the links will have been deprecated or will only point to the top level of the documentation. This means I have to search again within the documentation, when a simple search engine link should have sufficed.

Please re-design the Meteor documentation so that it is more friendly for search-engine and URL sharing.

**Comment by brylie** [comment]
For an example, see how Bootstrap 4 developers [re-wrote the documentation/doc browser in Markdown](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/).

**Comment by brylie** [comment]
Underscore.js is an example of a [documentation browser](http://underscorejs.org/#contains) having a similar design to Meteor and that exhibits the same difficulties in searching. The following Google search for a [method (named lastIndexOf)](https://www.google.fi/search?client=ubuntu&channel=fs&q=underscore+lastindexof&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=TRDwVavsJKmr8we6tLDwAg) demonstrates that Google only links to the top level of the documentation.

**Comment by brylie** [comment]
[GitBook](https://github.com/GitbookIO/gitbook) is one possible solution for a documentation generator that outputs .html files while offering a scrolling sidebar for navigation.

**Comment by markusgattol** [comment]
Since it's not just Meteor but also HTML, CSS, Jade, etc. I think https://zealdocs.org is really good. You can have it offline, it's searchable and auto-updates docsets https://kapeli.com/dash#docsets

**Comment by stubailo** [comment]
@brylie I couldn't agree more. The only reason we haven't changed it is because nobody currently has the bandwidth to refactor stuff. The bright side is, the docs _are_ actually written in markdown! See here: https://github.com/meteor/meteor/tree/devel/docs/client/full-api/api

So it should be pretty mechanical to migrate to markdown-based doc generator.

For the [React](http://react-in-meteor.readthedocs.org/en/latest/) and [PostgreSQL](http://meteor-postgres.readthedocs.org/en/latest/) projects, we elected to go with ReadTheDocs mainly because of the nice continuous build aspect, but it's not perfect.

The issue with a lot of the existing documentation tools is that they are appropriate for a library, but Meteor is more like a collection of libraries, so the amount of stuff to document ends up being an order of magnitude more than usual. I haven't seen a standard tool that will be able to present the amount of stuff we need to throw at it in an organized fashion.

One thing I would be really interested in knowing: How does the Angular team manage their docs? @Urigo can we ask them?

**Comment by Urigo** [comment]
@stubailo yes, in my last visit we talked about that as well.
For the new site and docs it can be a really good idea to collaborate.
For generating docs automatically they use [Dgeni](https://github.com/angular/dgeni)

There is a nice talk that talks about the broader approach to docs here:
https://www.youtube.com/watch?v=JSQrYozVLXo

Here is the new `angular.io` site's code: https://github.com/angular/angular.io

Those tools with your tutorial tools could be a huge improvement.

**Comment by abernix** [comment]
Good news (and sorry about the previous mess)!  [The newly revamped Meteor Docs are here](http://docs.meteor.com).  They are properly indexed by search engines now and we're also trying very hard to not to break permalinks/bookmarks (most existing should work fine).  Read more about it at [the new, separate Meteor Docs repo](http://github.com/meteor/docs/) where you can also directly help contribute by submitting pull-requests!  There are some small issues right now, but it's a carefully managed repo with a great community behind it and it should help out a lot.  Closing this since further issues should be handled over there.
