### ISSUE TITLE
Update MongoDB version for Meteor.com

### ISSUE THREAD

**Issue by fongandrew** [meteor/meteor#5128]
Not sure if Meteor.com deployment issues belong here, but deploying Meteor 1.1.x apps to meteor.com with `meteor deploy` sets the app up with MongoDB 2.4.10.

Since a Meteor deployment on localhost uses MongoDB 2.6.x by default, it would make sense for Meteor.com deployments to use a matching version of MongoDB to avoid compatibility errors.

**Comment by benjamn** [comment]
cc @multilinear?

**Comment by multilinear** [comment]
We're interested in doing this migration, but it turns out that Mongo didn't provide a reasonable migration path from 2.4 to 2.6 for existing data (2.6 has significantly stricter rules about what data is allowed). As a result we're pegged to 2.4 until we do quite a bit of data massaging to migrate - Something we probably won't do within the lifespan of Mother.

**Comment by chompomonim** [comment]
@multilinear, so what will be with meteor.com free hosting? Do you have any plans to update it after Galaxy release or what?

**Comment by multilinear** [comment]
We hope for Galaxy to eventually become our free hosting platform, we're still working out details though.
