### ISSUE TITLE
[1.2 regression] `meteor shell` executes each line of a multi-line function

### ISSUE THREAD

**Issue by avital** [meteor/meteor#5131]
Reproduction:
```
meteor create empty-app
cd empty-app
meteor &
meteor shell
```

Wait for the shell to load. Then type:
```
function foo () {
  console.log("inside function");
};
```

With Meteor 1.1.0.3, this doesn't print anything (but then calling `foo()` does, as expected).

With Meteor 1.2-rc.12, it prints `inside function`, even without calling the function.

Single-line functions work fine.

This bug makes it close to impossible to use `meteor shell` for scripting. (Now that we merged #5056 that makes it close to possible).

But it doesn't only affect scripting. I'm sure many users of `meteor shell` wouldn't expect this behavior.

**Comment by benjamn** [comment]
I haven't been able to reproduce this on `devel`, `release-1.2`, or curl-installed meteor `1.2-rc.2`, with or without the `ecmascript` package installed.

I was worried it might have something to do with 5a880a00bbd3cd6bc648cae67771fc2f40b12b88, so you might try reverting that commit if you can still reproduce the problem?

**Comment by avital** [comment]
Hmm. It really does only happen if you literally PASTE the function declaration, rather than typing each line separately.

**Comment by avital** [comment]
I've verified that reverting 5a88a0 indeed eliminates the problem. Good hunch!

Let me know if you need help reproducing the problem.

**Comment by benjamn** [comment]
Reproduced and diagnosed!

When you type out a multi-line function by hand, the lines pretty much always get evaluated in order, and  the `SyntaxError: Unexpected end of input` from attempting to evaluate `function foo () {` gets thrown before the `console.log("inside function")` gets evaluated, so the REPL knows it should keep defining the function instead of evaluating the `console.log`.

When you paste the same code, the first and second lines get sent as separate commands, and they arrive so close together in time that the `console.log` is evaluated before the `SyntaxError` is thrown.

Fix coming shortly.
