### ISSUE TITLE
Parallelize application build to use more than one core

### ISSUE THREAD

**Issue by 4thlaurocruz** [meteor/meteor#5132]
a multicore machine isnt using all cores when building application including --production

**Comment by stubailo** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

This would be an awesome thing to have, and might be able to significantly speed up build times for some people. Unfortunately, we aren't likely to get to it in the very near future.

Is there a particular app or package that makes builds slow? Have you tried one of the preview releases of Meteor 1.2 to see if it becomes faster?

**Comment by 4thlaurocruz** [comment]
well, when you are in debug mode, no threading, it downloads javascript one
at a time. If the later javascript is downloaded, there will be an error in
javascript beacause dependency havent been downloaded yet. Meteor should
use require.js or something. still multi core processing while uglifying
and other process is much preferred.

**Comment by hwillson** [comment]
[Meteor 1.4.2](https://github.com/meteor/meteor/blob/devel/History.md#v142) has introduced a significant number of build tool performance improvements. Please try your app out with the latest version of Meteor, and post back if you think this issue should still be considered. For now though, due to a lack of +1's (and given the positive feedback received on 1.4.2's improvements), I'll close this off. Thanks for the original suggestion!
