### ISSUE TITLE
Rename Tracker and Reactive-Dict

### ISSUE THREAD

**Issue by msavin** [meteor/meteor#5135]
Hey folks, as you probably know I'm a big fan of Meteor. I especially like how well designed the API is. However, I have a strong dislike for the name Tracker and Reactive-Dict. I would like to propose the following name changes:

Tracker to Reactor: since Tracker is the source of Meteor's REACTivity, I figured this would be a better name for it. It also sounds more alive than Tracker, like a nuclear reactor: powerful but contained, like the autorun function. It sounds a bit like React, but they don't own the word, and its buzz-wordy for you guys. 

Reactive-Dict to Namespace: we were discussing alternative names and this was @sachag's entry - its clever because the word space plays into the space theme. Plus, Reactive-Dict is a way for us to namespace our data.

```javascript
Spacefood = new Namespace("spacefood");
Spacefood.set("chicken", {calories: 400, ...});

Reactor.autorun(function () {
  calories = Spacefood.get("chicken").calories;

  if (calories >= 400) {
    console.log("Stop eating so much");
  }
});

StopOverreacting();
```

**Comment by rgoomar** [comment]
I like the change from `Tracker` to `Reactor` (sounds more catchy), but I don't think that `Namespace` would be a good name for Reactive-Dict. I feel like that would cause confusion especially since `Namespace` could be looked at as a module rather than a dictionary. Especially if those people are coming from [C# land](https://msdn.microsoft.com/en-us/library/z2kcy19k.aspx). 

I personally like the name `Reactive-Dict` because it tells you exactly what it is... a reactive dictionary.

**Comment by stubailo** [comment]
Yeah, I don't think namespace makes sense, since it's actually just a data structure. I agree ReactiveDict isn't the best name ever but it seems good enough for now and the only other names that would be appropriate are probably ReactiveMap or ReactiveObject.

As for Tracker vs. Reactor, I think there are already some things called Reactor, and this seems like an unnecessary rename - what's the actual benefit here?

**Comment by stubailo** [comment]
There's also an old mailing list thread about this: https://groups.google.com/forum/?hl=en#!searchin/meteor-core/reactor/meteor-core/OKHNz6Oga4w/d7J5hBuwE3IJ

**Comment by rgoomar** [comment]
@stubailo I like ReactiveMap

**Comment by mrzafod** [comment]
You can write a new package that could be very popular. Just one ```js``` file:
```javascript
Reactor = Tracker;
Namespace = ReactiveVar;
```

**Comment by SachaG** [comment]
In that case, watch out for my upcoming new package!
```
SpaceUnicorn = Meteor;
```

**Comment by msavin** [comment]
Thoughts: 
 - Meteor really should hire Sacha for Chief Naming Officer
 - ReactiveX should be something that's just one word, like everything else in Meteor's API
 - The APIs and libraries are your brand, so they should sound cool
 - Even though Namespace and Reactor have pre-existing meanings, I think the fact that they fit with Meteor's brand matters more

**Comment by jagi** [comment]
I've created my own [ReactiveMap](https://github.com/jagi/meteor-reactive-map) :) and it's almost one to one copy of API from `Map` collection (from ES6)

`Namespace` is ugly name...

On 0.9.1 release there was a change from `Deps` to `Tracker` and changing it one more time would cause more frustration.

I like the way of naming collection/sets by adding reactive word:
- You have normal `var` in JS and you have `ReactiveVar` in Meteor
- You have normal `Set` and you could have `ReactiveSet`
- You have normal `Map` and you have `ReactiveMap`
etc.

`Tracker` is also a good name because it it's a module responsible for tracking changes.

Using one word names for such things is bad idea. Names should be self explanatory and descriptive. That's why in Java they are using very long names for functions.

**Comment by dcworldwide** [comment]
Don't understand the need for change. The names are apt imo 

Of all the priorities the mdg have is it really worth distracting them with cosmetic changes? If you still feel strongly about it this would be better as a community PR.

**Comment by stubailo** [comment]
I think this issue isn't really productive at the moment. If there's a consensus reached somewhere other than GitHub (perhaps the forums) that this name change is important, we can reopen it then.
