### ISSUE TITLE
NPM support should build the NPM module when downloading a source version

### ISSUE THREAD

**Issue by mbrookes** [meteor/meteor#5136]
Npm.depend() accepts a github URL, but doesn't build the downloaded source.

This impacts NPM modules installed via meteorhacks:npm / cosmos:browserify, for example:

https://github.com/elidoran/cosmos-browserify/issues/13

**Comment by stubailo** [comment]
What do you mean by "build the downloaded source"?

**Comment by glasser** [comment]
Guessing they mean "run the npm publish-time automation"

**Comment by stubailo** [comment]
Oh, like if there is a compile hook or something. That makes sense.

**Comment by stubailo** [comment]
Does `npm install` do this by default? What's the workflow like when using vanilla NPM?

**Comment by mbrookes** [comment]
@stubailo - good point, just tried, 

```
npm install https://github.com/callemall/material-ui/archive/f78deffce5d3ffb830d85462103672c5efb4dc78.tar.gz
```

and no it doesn't. 

However if you then cd into `node_modules/material-ui` and run `npm install` there, it builds.

**Comment by stubailo** [comment]
That's weird. I feel like they are publishing things "wrong" in that I thought the best practice was to compile code when the package is published so that you don't rely on a specific build system.

Does adding the correct transforms to `cosmos:browserify` fix the issue? Probably babelify or something.

**Comment by mbrookes** [comment]
Honestly, I have no idea! Relatively new to JS, and its myriad of build systems, so not sure how to go about this, bit I'll do a bit of digging.

**Comment by elidoran** [comment]
In the issue at cosmos:browserify I wrote: "It seems Meteor's NPM support would need to build the NPM module when downloading a source version instead of a published version". 

What I should have written is: "It seems to me Meteor would have to be able to build npm modules from source despite the great many variations dev's use for building npm modules."

There are many tools used to build npm modules. And, there isn't a standard way to link npm scripts into building it. I use the `prepublish` hook as discussed on [npm's scripts page](https://docs.npmjs.com/misc/scripts). It's not a guarantee a module is doing that.  
 
I don't think a transform would be the best way to go because building a module seems like something to do before calling browserify on it.  Also, if someone wants to use a source version of a module for server side work in Meteor they wouldn't be using browserify.

All that being said, it does seem possible to have a transform for building modules which accepts configuration options telling it which modules to build and what commands to call to build them. With that transform, and the options specified in the options file for cosmos:browserify, then cosmos:browserify could do it.

While thinking about accepting the information to build a module it occurred to me it's possible to support building a module, for both client and server scopes, with `Npm.depend()`. Have it accept an options object as a second argument. That could specify the commands required to build a module. For example, a developer could depend on a source version via URL and specify the build commands like this:

```javascript
Npm.depends({
  someName: 'https://github.com/....'
}, {
  someName: {
    build: [ 'npm install', 'npm run-script prepublish']
  }
});
```

Although this would be a nice feature to have it may be simpler to either expect a developer to run the commands manually when they have specified a module be retrieved in source version, or, only support calling `npm install ; npm run-script prepublish` on modules downloaded from source.
