### ISSUE TITLE
Testing problems using Velocity reporter in Meteor 1.2

### ISSUE THREAD

**Issue by DAB0mB** [meteor/meteor#5139]
Whenever I try to test my package using jasmine and velocity test reporter, an error is thrown from a package called `respondly:util`, claiming jquery to be undefined (Uncaught TypeError: undefined is not a function). Well I'm not quite sure it's a Meteor issue, if I'm wrong please do tell me.

I tried running my tests using the following command:

```
VELOCITY_TEST_PACKAGES=1 meteor --release 1.2-rc.14 test-packages --driver-package velocity:html-reporter ./
```

Am I missing something? Any ideas?!

**Comment by stubailo** [comment]
@DAB0mB  this is an error with respondly:util, which has an unregistered dependency on `jquery`. We realized that a lot of packages were unknowingly depending on stuff like Mongo and jQuery because these packages were automatically added when running test-packages.

I would suggest reaching out to the authors of respondly:util and letting them know they should add a dependency on `jquery`.
