### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#5142]

**Comment by stubailo** [comment]
This is because Meteor packages are not distributed as source code. When you get an error in the client side of your Meteor app, the source maps are used to tell you which file in the package caused the error, but the file isn't present anywhere on your machine. This is just so that when you submit a bug report to the package the author can identify the line where it occurred.

Is there a way to get Chrome to suppress this warning if we know that the files don't exist?

**Comment by hwillson** [comment]
Hmm - I'm not quite sure why the original issue title and description were removed? It sounds like the original issue wasn't an issue with Meteor however, so I'll close this off. Thanks!
