### ISSUE TITLE
No way to run devel branch from the command line

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#5154]
I would love to be able to run:

```
meteor test-packages --release METEOR@devel ./
```

Very useful in Travis CI tests to see if current devel branch still works for my package.

**Comment by stubailo** [comment]
I think the equivalent that you could use in CI would be:

```sh
git clone https://github.com/meteor/meteor.git
cd meteor
./meteor test-packages ../path/to/your/package
```

Is that sufficient?

**Comment by mitar** [comment]
Hm, but I already have Meteor installed in the system. And you can then control with simple environment variable the release (which allows you to do easy build-matrix stuff: http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix). But then for `devel` branch we would have to use completely other set of commands.

**Comment by stubailo** [comment]
The thing is, Meteor releases are a whole different beast from the source code in Git. So under the hood, that command would basically do the exact thing I posted above, but now we have to maintain it, clean up old checkouts, etc etc. I can reopen as a feature request, but I don't think it will be a priority since checking out from git isn't that difficult. You can write a bash script that takes an argument and then runs the right set of commands.

**Comment by hwillson** [comment]
There hasn't been any activity/interest on this issue in a while, and given that there are acceptable workarounds (https://github.com/meteor/meteor/issues/5154#issuecomment-140202034) to the original issue, I'll close this off. Thanks for the suggestion!
