### ISSUE TITLE
[1.2-rc.15] Installing Cordova Plugins slow

### ISSUE THREAD

**Issue by raix** [meteor/meteor#5168]
Hi, I might fail to remember - but are cordova plugins cached or does that only happen if we are using npm plugins? (or not at all?)
*(Takes ages/15-20min to install 24 plugins)*

**Comment by martijnwalraven** [comment]
I don't believe it should take that long (unless you have a very slow network connection of course). 

Cordova now downloads plugins from npm or from a Git URL (which is what tarball URLs are converted into). I think these should be cached in `.plugman/cache`.

Are you using plugins from the local filesystem? These reinstall on every build because we have no way of detecting changes, so that may also slow things down.

**Comment by raix** [comment]
we still use hashed git references - takes forever - I'm on either a 20Mbit or 80Mbit line (have both)

I'll add the debug flag and see whats taking so long. (filing an issue or two on Meteor reset)

**Comment by martijnwalraven** [comment]
Let me know if you find out anything. This is all Cordova's responsibility, but I think it should also cache plugins downloaded from Git. Could you check the `~/.plugman/cache` directory?

**Comment by stubailo** [comment]
Since this is probably a Cordova thing we probably won't be able to fix it before the 1.2 release, so I'm taking it off the milestone.

**Comment by obiwarn** [comment]
Can confirm. We use 15 plugins, 8 of them with git hash.

Takes ages on every recompile.

**Comment by martijnwalraven** [comment]
@obiwarn: Is this on Meteor 1.2?

**Comment by obiwarn** [comment]
yes.

when I debug --verbose it seems to reload (and not cache) all plugins on
every build.

**Comment by cunneen** [comment]
Is there any workaround to this? It's making development very painful.

**Comment by Kostanos** [comment]
+1 to request.

Any workaround, solution for this issue? Thank you.

**Comment by martijnwalraven** [comment]
@Kostanos: Caching plugins downloaded from Git would be a feature request for Cordova. The advise is to use plugins from npm where possible.

**Comment by cunneen** [comment]
@martijnwalraven and @stubailo :  Is it not possible for meteor to parse the URL, download the tarball and install it to cordova as a local plugin? 

From [the cordova docs](https://cordova.apache.org/docs/en/5.0.0/guide/cli/#advanced-plugin-options):

> Alternately, specify a local path to the plugin directory that contains the plugin.xml file:
> ```$ cordova plugin add ../my_plugin_dir```

**Comment by martijnwalraven** [comment]
Meteor already allows you to add plugins from the local filesystem using `meteor add cordova:file://../my_plugin_dir`, but that probably won't really improve things because using local plugins forces all plugins to be reinstalled on every build (it does avoid downloading the plugin again however, so if the network is the bottleneck it might improve things).

If possible, installing plugins from npm is always the best option, because those downloads will be cached and won't force reinstallation.

**Comment by cunneen** [comment]
OK thanks @martijnwalraven that info helps a lot. I've written a very rough little bash script that grabs the git tarballs and publishes them to a private npm registry, and then replaces the meteor URL with an npm reference. 

It makes the meteor cordova build process *much* faster (although still too slow for my liking).

You could quite easily modify it to publish any git tarball cordova plugins to the official npm registry (just comment out the npm config commands at the top).

The [gist is here](https://gist.github.com/cunneen/d2f3842ae0240d8ab747) . Changes are welcome.
