### ISSUE TITLE
EJSON.clone can't clone objects with a prototype and a length property

### ISSUE THREAD

**Issue by joegoldbeck** [meteor/meteor#5175]
If I return an object from a Meteor method as follows: `return {a: 2, length: 37}`, it is sent over the websocket correctly as `{a: 2, length: 37}`.

However, if that object is an instance of another class like so `return new MyClass({a: 2, length: 37})`, then what is sent is an empty object (`{}`).

If the key "length" is not present, it also works correctly. `return new MyClass({a: 2})` sends `{a: 2}` over the websocket as expected.

**Comment by stubailo** [comment]
OK, I've tracked this down to the fact that we use `EJSON.clone` to clone any return values on methods. EJSON.clone thinks that anything with a `length` property is an array.

**Comment by hwillson** [comment]
This has been a re-occurring problem - see https://github.com/meteor/meteor/issues/8329, https://github.com/meteor/meteor/issues/594, and several others. A quick synopsis of the problem (and solution) can be found [here](https://github.com/meteor/meteor/issues/8329#issuecomment-280217394). This problem is manifesting itself in the [`_.each` within the EJSON packages `EJSON._adjustTypesToJSONValue` function](https://github.com/meteor/meteor/blob/06d00e45c7d375ef4787411c1698210ea9fc438d/packages/ejson/ejson.js#L214-L227).

**Comment by hwillson** [comment]
Just a quick update here - I started working on a PR for this, only to find out that almost every part of the EJSON public API falls apart when working with an object that has a property named `length`  (thanks to `underscore`). So this issue isn't limited to `EJSON.clone` - here's another quick example that will fail:

```js
var Widget = function () {
  this.length = 10;
};
var widget = new Widget();
var widgetJson = EJSON.toJSONValue(widget);
```

`widgetJson` will hold `{ 0: undefined, 1: undefined, ... 9: undefined }` instead of `{ length: 10 }`. I'll aim to address all `length` problem areas - more details shortly.

**Comment by hwillson** [comment]
The `ejson` package no longer uses underscore, so this is no longer an issue. Closing - thanks!
