### ISSUE TITLE
[Cordova] Meteor: launch-screen

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5206]
Hey guys,
the package isn't working here, my launch screen hides without releasing it. I've added .hold() on top of my client files, but the launch screen still hides after a few seconds. I'm using Iron Router as my router and have tested it with Android.

**Comment by martijnwalraven** [comment]
Could it be that `AutoHideSplashScreen` is set to true somewhere? I'm not sure if Iron Router affects launch screen behavior, but there might also be some interaction there.

I suspect this is a configuration issue rather than a bug, but if you can provide a reproduction I could take a look at it.

Also, what version of Meteor are you using? Have you tried this with Meteor 1.2 RC (`meteor update --release 1.2-rc.16`)?

**Comment by dnish** [comment]
If I look into my config.xml, <code>  <preference name="AutoHideSplashScreen" value="false"/> </code>.
I'm using current 1.1.0.3
