### ISSUE TITLE
Add Sass official package

### ISSUE THREAD

**Issue by VladShcherbin** [meteor/meteor#5236]
Can we have Sass official package?

It is very weird to see Less and even Stylus, but no Sass. There are lots of people, who love Sass and prefer it over Less/Stylus. It is also painful to see in the blog posts, that only Less/Stylus are supported and have new features, Sass should be definitely among them.

Maybe you can take `fourseven:scss`, test and make it `scss` or `sass` as you did with Angular package. Sass users also want to have all new features, that Less/Stylus users already have :(

**Comment by macrozone** [comment]
Agree, I also prefer scss over less, as I also work in Rails-projects and scss is common there. 

I also was suprised by lack of scss in the blog-post :-(

**Comment by gitawego** [comment]
agreed...

**Comment by stubailo** [comment]
SASS is gaining more and more popularity! Back in the day it looked like LESS was going to be the thing for JavaScript and SASS more a ruby thing, but especially with new Bootstrap switching to SASS it would make a lot of sense to basically make it the primary CSS preprocessor for Meteor.

I'm not sure exactly what the status of keeping LESS/Stylus in core will be in the near future, so I don't know how to add support for SASS without increasing the overall maintenance burden on the core project.

Is someone interested in being the primary maintainer of SASS for Meteor? I can help that person set up CI tests so that they can easily test their package with new releases of Meteor to keep up support (which is basically what we do).

**Comment by sebakerckhof** [comment]
I'd be willing to do it. I've written most of the meteor 1.2 version of fourseven:scss, but if fourseven would rather do it, than he can do it. I don't want him to feel like I've hijacked his package.

Note that there are currently some issues with the stable version of node-sass and custom importers. https://github.com/sass/node-sass/issues/1188 and https://github.com/sass/node-sass/issues/1192 . You'd probably want to wait before these are solved before releasing this is an official package (something we discovered a bit too late.)

**Comment by fourseven** [comment]
Hah, I wondered when this would happen. I'm happy for @sebakerckhof to be the primary maintainer, since he's put so much energy into the latest release. I'd like to still be able to help out if that's possible too.

**Comment by stubailo** [comment]
While this is a cool issue for discussion, there are now two main places this discussion can happen:

1. In the Meteor guide repository, where we will recommend a specific package for SCSS/SASS: https://github.com/meteor/guide/issues/41
2. In the `fourseven:scss` repo: https://github.com/fourseven/meteor-scss/issues/133

In light of that, I'm going to close this issue since any actionable things will take place there.
