### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by thalesfsp** [meteor/meteor#524]
Where's in the DOC instruction for how to remove meteor after "$ curl https://install.meteor.com | sh"?

Thanks!

**Comment by leetschau** [comment]
Why not add uninstall instruction (avital's comment) into [Quick Start of Meteor Doc](http://docs.meteor.com/#/basic/quickstart)?

**Comment by glasser** [comment]
It's in the README: https://github.com/meteor/meteor/

**Comment by thalesfsp** [comment]
Thanks guys!

**Comment by ellvtr** [comment]
After removing meteor with
```
sudo rm /usr/local/bin/meteor
rm -rf ~/.meteor
```
I still have problems installing mongodb from scratch on my linux mint, it claims that another instance of mongodb is already running - which I believe came with the meteor installation. How to remove that as well?

**Comment by cm3rt** [comment]
Please help.... Look at http://45.33.108.69/  I cannot get this to go away! My wordpress site is not loading anymore and that's all that comes up. I can't figure  out how to remove this, even following all of your directions here. I used a wget by accident and installed meteor when I didnt want to.

**Comment by hwillson** [comment]
@cm3rt It looks like you've put a copy of the Meteor install script (accessible at https://install.meteor.com) in your web servers document root. The install script is hosted as a `index.html` file (https://install.meteor.com/index.html), so you probably just `wget`'d a copy of that `index.html` into your document root. Since you mentioned it's interfering with your Wordpress site, and Wordpress doesn't use a `index.html` file (it uses `index.php`), then you're probably safe to just remove the `index.html` from your doc root (but back it up just in-case).

**Comment by cm3rt** [comment]
@hwillson Well well well. I guess that's why they pay you the big bucks. It worked! It installed index.html copies everywhere somehow. I just removed the index.html and it worked. Appreciate it!
