### ISSUE TITLE
Support for bulk Mongo operations in Meteor

### ISSUE THREAD

**Issue by lnader** [meteor/meteor#5263]
I don't know if this the right place to bring this up but I am inquiring on the timing of availability of bulk operations in Meteor.

http://docs.mongodb.org/manual/core/bulk-write-operations/

**Comment by rclai** [comment]
They are available, more specifically [here](http://mongodb.github.io/node-mongodb-native/1.4/#api-documentation). Check out the ordered bulk writes and unordered bulk writes API.

In order to have access to those APIs you see in that list, you have to use the [`.rawCollection()`](http://docs.meteor.com/#/full/Mongo-Collection-rawCollection) call before you use any of those native mongo APIs.

**Comment by lnader** [comment]
Great.  Thanks.  Closing issue.

**Comment by stubailo** [comment]
#1255 is also a duplicate of this.
