### ISSUE TITLE
Improve `meteor list` to allow for organization of packages

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#5265]
Since 1.2 core packages have become too many. It's become hard now to distinguish 3rd party packages. I propose to add a special command if one needs to see core packages. Like: 
`meteor list -c`

**Comment by jagi** [comment]
I don't think it's needed. From 1.2 you can remove any package from the project. Which packages would call **core**? `meteor-base`? What about `mongo`, `session`? You can work without them. IMHO there is no easy distribution into core and non-core packages.

**Comment by avalanche1** [comment]
Core packs are the ones installed when making a new project installation.

**Comment by jagi** [comment]
When creating a new Meteor project, we have the following packages:

```
autopublish           1.0.4  (For prototyping only) Publish the entire database to all clients
blaze-html-templates  1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript            0.1.4  Compiler plugin that supports ES2015+ in all .js files
es5-shim              4.1.13  Shims and polyfills to improve ECMAScript 5 support
insecure              1.0.4  (For prototyping only) Allow all database writes from the client
jquery                1.11.4  Manipulate the DOM using CSS selectors
meteor-base           1.0.1  Packages that every Meteor app needs
mobile-experience     1.0.1  Packages for a great mobile user experience
mongo                 1.1.1  Adaptor for using MongoDB and Minimongo over DDP
session               1.1.1  Session variable
standard-minifiers    1.0.0  Standard minifiers used with Meteor apps by default.
tracker               1.0.8  Dependency tracker to allow reactive callbacks
```

We could easily get rid of `autopublish`, `blaze-html-templates`, `ecmascript`, `es5-shim`, `insecure`, `mobile-experience`, `mongo`, `session` and still have working Meteor project. So I don't think there is a need for displaying **core** packages because there are not many of them that are required for Meteor to work.

**Comment by avalanche1** [comment]
Well, I think that's quite a lot and I personally would like to be able to see only the packs that i've installed myself.

**Comment by jagi** [comment]
The first thing that distinguish "core" packages from other packages is that the last one has a developer name at the beginning: `devName:packageName` :). So if you name Meteor built in package the "core" packages then you can easily distinguish them. If you name "core" packages the packages that are added at the project creation then at first you shouldn't call them "core" and it doesn't make sens to distinguish them.

**Comment by stubailo** [comment]
The whole point of the changes we made is that you can become aware about which packages come with a default Meteor app, and then remove them.

@avalanche1 I think you could do the following to improve your workflow: don't use `meteor list` anymore, and instead look at and edit the file in `.meteor/packages`. In that file, you can sort the list of packages however you want, add comments, etc. That way you can keep them organized. It's not super optimal, but I think it is a good workaround for now.

I think `meteor list` is pretty flawed because it doesn't give you any context about what the packages are, why they are in your app, etc. So this issue is a pretty valid complaint but more about the fact that `meteor list` isn't great, rather than there being too many packages in a new app.

Going to rename the issue to reflect that.

**Comment by jagi** [comment]
Right, it would be much better to just show why this package is in a project. Good point!

**Comment by avalanche1** [comment]
@stubailo , thank you, I'll be sure to use your advice.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Improve%20%60meteor%20list%60%20to%20allow%20for%20organization%20of%20packages&body=Migrated%20from:%20meteor/meteor%235265) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
