### ISSUE TITLE
Have scaffolding like in Rails

### ISSUE THREAD

**Issue by spyhole** [meteor/meteor#5283]
$ meteor g:scaffold todos
$ meteor g:template todos/todo_item
$ meteor g:collection todos
$ meteor g:route webhooks/stripe --where "server"
$ meteor g:controller todos/show_todo
$ meteor g:route todos/show_todo --action "show"
$ meteor g:publish todos
$ meteor g:stylesheet main

**Comment by maartenbusstra** [comment]
Meteor does not enforce a certain file structure, so it would be odd for them to provide scaffolding tools that defaults to using a certain file structure. Unless you could configure that somehow...

Anyways; you could give the iron-cli a go if you're in desperate need. But judging by the snippet you posted, you're already in the know. :)

**Comment by spyhole** [comment]
yes. i use iron-cli on windows as rails do. BUT i have not get used to use it outside meteor.

**Comment by stubailo** [comment]
We are starting to work on a [Meteor Guide](https://github.com/meteor/guide) that will provide official recommendations for file structure and other code style questions. Once that's in place, it should be fairly trivial for someone to build a generator that matches it.

Seems like a legit feature to me, but it probably won't get done very soon. But I'm excited for that possibility.

Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by spyhole** [comment]
@stubailo :+1:

**Comment by hwillson** [comment]
More advanced scaffolding functionality (like Rails) can be handled entirely outside of the core Meteor codebase. Projects like [meteor-io](https://www.npmjs.com/package/meteor-io) demonstrate this. Since functionality like this can be provided outside of the Meteor core, it's better implemented as an Atmosphere / npm package (see [Feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) for more info). As such, and due to the low activity / age of this issue, I'll close it off. Thanks for the original suggestion!
