### ISSUE TITLE
Meteor.userId() persists after reset

### ISSUE THREAD

**Issue by mbreuer23** [meteor/meteor#5292]
**_2 Upvotes**_ After resetting my database, and navigating to localhost:3000, i type Meteor.userId() in the console and get a userId associated with an old account (i.e. one that was dropped from my database after reset). This is before I've logged in, so i was expecting to have Meteor.userId() return undefined. 

This started happening after updating to Meteor 1.2.   I have verified that my database does not contain a userId matching the one returned by Meteor.userId().

Any idea what would cause this?

**Comment by joaopiopedreira** [comment]
+1

João Pio Pedreira
/// Sent from a mobile device ///

**Comment by dgreensp** [comment]
Interesting.  Can you post steps to reproduce?

**Comment by matdurand** [comment]
+1

To reproduce, using flowrouter, I have one login page and a homepage that is secured using a group with triggersEnter: [AccountsTemplates.ensureSignedIn]. I then start my server, load the login page and I log in, displaying the homepage. Then I shutdown the server, perform a "meteor reset" and restart the server. Finally I reload the homepage and I'm still able to see it instead of being taken to the login page. If I reload a second time, I'm being forwarded to the login.

I went inside the ensureSignedIn code and Meteor.userId does return something the first time. Is the userId derived from the access token?

I have no workaround at this time.

Thanks

**Comment by matdurand** [comment]
As a temporary workaround, I overrided AccountsTemplates.ensureSignedIn and have been using Meteor.user() instead of Meteor.userId() in my ensureSignedIn replacement, and it seems to work so far.

**Comment by hwillson** [comment]
This type of issue is very hard to troubleshoot without a runnable reproduction (please see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Closing for now - thanks for reporting this originally!
