### ISSUE TITLE
findOne server side Bug

### ISSUE THREAD

**Issue by peonmodel** [meteor/meteor#5301]
repro here: https://github.com/peonmodel/crispy-octo-woof

TestCollection.insert({
  stuff1: 'abc',
  stuff2: 'def'
});

// client-side
var testclient = TestCollection.findOne({
  stuff1: function(){}
});
console.log('should be undefined', testclient);  // is undefined as expected

// server-side
var testserver = TestCollection.findOne({
  stuff1: function(){}
});
console.log('should be undefined but isnt', testserver);  // is not undefined as expected

discovered this bug due to minor typo, Meteor.userId instead of Meteor.userId()

**Comment by stubailo** [comment]
Hey for the future, you should actually include `.meteor` in your git repository. `.meteor` already has a good `.gitignore` inside itself that ignores the correct things.

**Comment by stubailo** [comment]
Interesting - it looks like this method is proxied directly to the Node MongoDB driver, so there is no Meteor-specific stuff involved in this. I guess really this bug has one of several solutions:

1. Ensure Minimongo has the same functionality, so that passing a function selects everything like in server-side MongoDB
2. Throw an error when a function is used in a selector on both sides of the wire
3. Check if version 2.0 of the node Mongo driver has this issue

I would think option 3 is probably the best - we should see what it would take to update to version 2 of the node mongo driver.

**Comment by abernix** [comment]
This still happens on Meteor 1.4.2.3 which uses the 2.2 Node driver.  Since the original repo has been deleted, I've recreated it in [this repo](https://github.com/abernix/meteor-issue-5301).

I think the best option now is to aim for bullet point 1 above, though I'm not sure of the urgency right now.  The consistency would surely be nice.  That being said, I'm not sure what functionality you're expecting here with a `function` query selector, and I'm not sure if it's supported by the Mongo Node driver.  See also, my comments [here](https://github.com/meteor/meteor/issues/6509#issuecomment-266508304).

Regardless, thank you for reporting this originally, @peonmodel.

**Comment by mitar** [comment]
I think the expected behavior is to not return any documents. :-) It is unclear why node driver does return something. Maybe this should be reported upstream?

**Comment by abernix** [comment]
I might agree but honestly it wasn't immediately clear to me from any of the Mongo docs what would have been expected here and if it was even justifiable to report upstream.

**Comment by mitar** [comment]
What does Mongo shell do if you do such a query? Is it node driver or MongoDB itself who makes a strange thing here?

**Comment by abernix** [comment]
The mongo shell returns nothing, which certainly makes more sense to me than returning everything.  I think it's likely this is happening because the `function` isn't/cannot-be encoded in the `BSON` object (used to communicate between the Mongo driver and the Mongo server) and is silently dropped.  Therefore, everything is returned.

It may be possible to enable different behavior by using the [`serializeFunctions` option](https://mongodb.github.io/node-mongodb-native/api-generated/collection.html#insert) (search for it).  I have a hunch that it is observed on `find` selectors as well – unconfirmed though.

One notable mention is in the [`node-mongodb-native` history](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#097-2011-11-10):
> Serialization of functions in an object is off by default, override with parameter

But again, the query itself is a bit strange: passing a `function` in this way is is undocumented (to my knowledge).  If there is a bug, I'd venture to say that it exists in [`mongodb-core`](https://github.com/christkv/mongodb-core/)'s BSON serialization code and not [`mongodb`](https://github.com/mongodb/node-mongodb-native).
