### ISSUE TITLE
Problem with localmarket example

### ISSUE THREAD

**Issue by alextaaa** [meteor/meteor#5319]
http://i.imgur.com/edDtwIa.jpg

**Comment by martijnwalraven** [comment]
I'm not sure how you ended up with `iron:router` 1.0.9, but that seems to be the problem. When I create the localmarket example project it is locked to version 0.9.4. Did you update dependencies manually by any chance?

**Comment by alextaaa** [comment]
I deliberately put a picture with my dependencies
http://i.imgur.com/edDtwIa.jpg

I updated to the latest versions all

**Comment by martijnwalraven** [comment]
Yes, I saw your picture, where I noticed you are using `iron:router` version 1.0.9 instead of the 0.9.4 I was expecting. 

My question is how you ended up with this version, because Meteor shouldn't allow you to update to a potentially incompatible version of a dependency. Did you specify `--allow-incompatible-updates` or update dependencies manually?

**Comment by alextaaa** [comment]
it is not difficult )
> meteor remove iron:router
> meteor add iron:router
> meteor reset
> meteor update
> meteor

**Comment by martijnwalraven** [comment]
It's not difficult, but it's also not something you should do without a good reason to do so :) By removing and adding back `iron:router`, you've removed the version constraint that was locking it to 0.9.4.

These version constraints are there for a reason: they indicate that an app has been developed with a specific version and may be incompatible with later ones (which is the case here).

**Comment by alextaaa** [comment]
I understand the purpose of the fixed versions
But the concept of a meteor - updated every day, updated quickly, updated everywhere, updated everything ))
Fixed version for the guys on the Nodejs, but not for a Meteorjs ))

**Comment by abarnert** [comment]
It only takes a few lines to change the sample to work with iron:router 1.0.9, and I learned some useful stuff about the router by doing it. And this is a sample that's designed for learning from, not for actually using, right?

So maybe the best solution is not to update it, but to just update the readme to:
 * point at https://github.com/iron-meteor/iron-router#migrating-from-094
 * show the minimal changes to make the sample work
 * show how to use remove and add to force Meteor to allow the update

**Comment by alextaaa** [comment]
I think meteor will develop rapidly.
Examples for developers with fixed versions ideologically incorrect,
because the examples should demonstrate the new functionality of the framework, but not fixed on the old.

**Comment by martijnwalraven** [comment]
I completely agree Meteor needs up to date examples to learn from, especially for mobile. But in my mind, localmarket is more a demonstration of how close to a native app a mobile web app can get rather than a code example.

We're currently discussing how to improve our documentation and tutorials, and we should make sure to include better guidance for developing mobile apps in that.

To be honest, I don't use Iron Router myself, and I wouldn't recommend starting a new project with it at this point. Although given the required changes are only a few lines, we should probably just update the code.

**Comment by alextaaa** [comment]
I would like to start developing of examples for developers.
I sent my resume in Meteor Development Group, if I take the team,
I would like to develop support for jade, slim like a stylus, coffeescript
so you can enter `meteor add jade` and enjoy
