### ISSUE TITLE
Provide a handle to Mongo

### ISSUE THREAD

**Issue by drorm** [meteor/meteor#532]
There are a variety of server functions like get all the collections on the db, clone a db, show the logs, etc, that can only be done through the actual Mongo handle.

Meteor needs to provide access to this handle.

**Comment by mizzao** [comment]
I proposed what I think is a better solution at https://github.com/meteor/meteor/issues/2759#issuecomment-74819067. Would you guys take a look and let me know your thoughts?

**Comment by glasser** [comment]
See #3640 and https://rbcommons.com/s/meteor/r/13/

**Comment by mitar** [comment]
@glasser, this will not help @mizzao, who is using third party node.js codebase which is using `require('mongodb')`. So the idea is that `require('mongodb')` gets access to exactly the same MongoDB driver package.

I do not think one can do now:

 ```
Npm.depends({mongodb: MongoInternals.NpmModules.mongodb.version})
```

Or can you?

**Comment by glasser** [comment]
Then fork the third party node.js codebase and change it to do dependency injection or something.  Putting work into making the package you're wrapping work better is what repackaging is all about.

**Comment by mizzao** [comment]
I don't understand why I need to fork the node.js codebase in order to implement a ShareJS package for Meteor. All the integration work I've been doing is Meteor specific; there should be no reason for me to implement my own node dependency injection just to make Meteor's overriding of Node's `require` work properly.

I've torn my hair out over trying to communicate this issue. Now, the package is just going to constantly include the following,

```
Npm.depends({
  share: "0.6.3",
  /*
      Mongo version used in 1.0.4
      Grabbed from https://github.com/meteor/meteor/blob/devel/packages/mongo/package.js
      Update this whenever we target a new Meteor version.
      This is necessary for ShareJS to require("mongodb") and not complain.
  */
  mongodb: "https://github.com/meteor/node-mongodb-native/tarball/634759e6326dc19a228df66ddb309285532f3b8a"
});
```

and it's going to keep being built with unnecessary binary blobs.

**Comment by glasser** [comment]
@mizzao You are suggesting implementing a complicated, expansive feature (replace how `require` works inside npm packages, not Meteor's `Npm.require`) in order to implement what really is an incredibly niche use case.

I also literally don't understand what your problem is.  I just ran `npm install share@0.6.3` and it didn't seem to install mongodb at all.  Where is the require line you're talking about?

**Comment by glasser** [comment]
So eg, looking at 0.6.3: https://github.com/share/ShareJS/blob/e475766d4da3c28de998c41a143cb9aa447385c2/src/server/db/mongo.coffee

The only use of the mongodb package is if you don't pass a `client` option.  So when you're initializing this object, just pass in a `client` object instead of letting it do its default thing.  (It doesn't even declare the mongodb dependency in package.json!)  Now, there is a top-level require of 'mongodb' but this is arguably a bug in ShareJS: they should change their code to not require mongodb if you specify a `client`.

I can't for the life of me figure out where this code ended up in the current master of share (or its dependencies) though.

But at least with 0.6.3 it sure seems like a 1-line bugfix.

**Comment by mizzao** [comment]
I am **already** passing it in:

https://github.com/mizzao/meteor-sharejs/blob/master/sharejs-base/sharejs-server.coffee#L27

The `require('mongodb')` is what's causing the problem. What are you saying that I should do about that?

By the way: https://forums.meteor.com/t/trying-to-publish-for-arch-in-meteor-1-0-4-malformed-source-tarball/1369

**Comment by glasser** [comment]
It's a blatant bug in that share code that they execute the (undeclared!) require call even for the codepath that ignores the mongodb object. Send them a PR!

**Comment by mizzao** [comment]
That is a two year old branch of the code, I doubt anyone is maintaining it now. All efforts are on the new 0.7. I'll see what I can do though.

I tried the following workaround:

```
oldRequire = Npm.require
Npm.require = ->  
  return MongoInternals.NpmModules.mongodb.module if arguments[0] is "mongodb"
  return oldRequire.apply(this, arguments)
Npm.require('share').server.attach(WebApp.connectHandlers, options);
Npm.require = oldRequire
```

But the `require("mongodb")` is not using the same `Npm.require` function. Wonder if I can just hack my own dependency injection for now and be done with it?

**Comment by mizzao** [comment]
Thanks, @glasser. I'm glad you stood your ground.

https://github.com/mizzao/ShareJS/commit/05b625ea1e7f7f27bd13ba7ed05102b38dd175e5

**Comment by mitar** [comment]
Just to give one other way for future reference. If you would have access to `require` itself, you could misuse deprecated `require.extensions` to return whatever you want when code calls `require 'mongodb'`. See here: https://github.com/peerlibrary/node-meteor-package-builder/blob/master/package-builder.js#L27

I used that to make sure that `Fiber` module instance is exactly the same as running Meteor has.

The issue is that I do not think Meteor provides access to original require. Maybe it could, through `Npm._require` or something.
