### ISSUE TITLE
Cannot subclass class defined in package

### ISSUE THREAD

**Issue by belisarius222** [meteor/meteor#5351]
Meteor 1.2 supports classes and subclassing, but not if the superclass is defined in a package and the subclass is defined in an app. Here's a reproduction app:
https://github.com/belisarius222/meteor-es6-package-errors
In Meteor 1.2, subclassing a class defined in a package throws an error.

In the repro I define classes A and B in package "class-a", then try to subclass them in the app. The file client/class.js defines subclasses C and D of A and B, respectively. The classes are instantiated in the file client/es6-errors-reproduction.js.

I tried a few different ways of doing this, but all of them throw this error: TypeError: Class constructors cannot be invoked without 'new'.

Note that this is not the error that gets thrown if you forget to put 'new' in front of a constructor call. That tends to throw: TypeError: Cannot call class as a function.

To see the errors, run the app and open the JavaScript console.

**Comment by belisarius222** [comment]
Oooooh, these errors go away when I add api.use("ecmascript") to the package.js :/  Oops.

So, this isn't a bug per se, but that error message was highly misleading, especially combined with the fact that I could still instantiate compiled classes from the package! It's not clear to me how the "class" keyword didn't just throw a syntax error. I guess because ecmascript was in .meteor/packages, the app would compile the ES2015 code in the package, but not link it correctly?

It would be great if trying to use ES2015 features without the ecmascript package being present made it clear that the package was missing.

**Comment by dgreensp** [comment]
You must be getting the browser's native `class` implementation.  This error is known to occur when a Babel class tries to extend a native class.  This is actually an argument against ever using native classes, because there's no way to extend them from ES5 or transpiled ES2015.

There probably is somewhere we could catch this case, I'm just not sure where best to do it.  For example, we could catch the case where you use classes without the `ecmascript` package, deciding that this is probably not what you intended to do (though you should still be able to do it if you know what you're doing).  Or maybe the Babel runtime could catch the error and throw a better one.

**Comment by belisarius222** [comment]
Yeah you're right, it was Chrome's class implementation.

It would be great to have some kind of error message to prevent other people from falling into the same rabbit hole that I fell into. From reading the forums, it does seem like there are some people using a third-party ES2015 package, which suggests that throwing an error whenever someone uses a class without the ecmascript package could prevent some apps from running.

A warning message, or some sort of non-fatal error, might do the trick.

**Comment by stubailo** [comment]
This is related to https://github.com/meteor/meteor/issues/5387 which is another case where the browser natively supporting a feature led to confusion.

It's actually kind of weird, because you would think browsers supporting a new feature would be a good thing, but it can result in subtle bugs when things don't work together well.

**Comment by hwillson** [comment]
There hasn't been any activity on this issue in a while. Given that:

- Using the `ecmascript` package prevents this issue from occurring;
- The `ecmascript` package is enabled by default for all new applications/packages (using a recent version of Meteor);
- [Instructions on how to add the `ecmascript` package](https://docs.meteor.com/packages/ecmascript.html#Usage) to existing applications/packages were added to the docs;

we should be able to close this issue off. Thanks for posting this originally!
