### ISSUE TITLE
Large file takes a long time to build

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#5429]
Since upgrading to 1.2, I've noticed that files that are very large make the build time take 10-20 minutes on my machine. Sometimes longer. Our build server now takes about a half hour to complete.

The file that's the main cause of this is the [SpreadJS](http://spread.grapecity.com/Pages/Demos/) source code. Which clocks in at over 150000 lines of code. I have it loading in with ```{ bare: true }``` but it doesn't seem to make a difference. Pre-1.2 this was not a problem.

**Comment by stubailo** [comment]
Question: are you using the `ecmascript` package?

One workaround that will surely improve your build time is to publish a package with SpreadJS to Atmosphere, because those packages are pre-built.

**Comment by benjamn** [comment]
I'm guessing you have the `ecmascript` package installed, and so Babel is attempting to compile the large file, even though there's probably nothing in the file that needs to be compiled. Let me know if that's not the case, because the rest of what I have to say depends on that hunch.

If the file is in a package that has `api.use("ecmascript")`, then you can disable compilation for individual files when you call `api.addFiles` using the `options.transpile` flag:
```js
api.addFiles("spread.js", ["client", "server"], {
  transpile: false
});
```

If the file is in a package that has `ecmascript` in its `.meteor/packages` file, then you can avoid `ecmascript` compilation for a particular file by renaming it to have an `.es5.js` file extension.

**Comment by davidworkman9** [comment]
The package I have it in is only using jquery. However there are parts of the app that are using the ecmascript package. I don't think the spreadjs license would allow me to put it onto Atomsphere unfortunately. Adding ```{ transpile: false }``` had little or no effect on how long it took to build.

**Comment by davidworkman9** [comment]
This no longer seems to be a problem.
