### ISSUE TITLE
Impossible to Define DYLD_LIBRARY_PATH on OS X El Capitan 10.11

### ISSUE THREAD

**Issue by backdate** [meteor/meteor#5431]
process.env.DYLD_LIBRARY_PATH will be undefined when called from inside a Meteor application launched with the 'meteor' command. To replicate, run 'DYLD_LIBRARY_PATH=/opt/oracle/instantclient meteor' and make the application output process.env.DYLD_LIBRARY_PATH. The DYLD_LIBRARY_PATH environment variable is defined when the Meteor application is built and launched with 'node main.js'.

**Comment by backdate** [comment]
The issue might be related to https://github.com/oracle/node-oracledb/issues/231.

**Comment by stubailo** [comment]
I don't think this bug is Meteor-specific, and based on that other issue thread, it might be an operating system restriction. Is there something we could do in Meteor to improve the situation?

Thanks for reporting, but I'm going to close this for now because I don't know how we could do anything about this.
