### ISSUE TITLE
Meteor Access-Control-Allow-Origin with iOS

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5434]
In development, I get this error for my HTTP requests because the service I'm using is expecting localhost:3000, not meteor.local. Is there anyway I could configure this?

```
Failed to load resource: Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.
```

**Comment by martijnwalraven** [comment]
You'll have to configure the server to accept `meteor.local`, because that will be the origin of the request.

**Comment by ccorcos** [comment]
Oy. That means I'll have to create another access key on Facebook. Then I'll have to use a different settings.json for cordova. And I won't be able to test locally in the browser and on the phone at the same time... Any particular reason for using meteor.local vs localhost:3000? Any reason it shouldn't be configurable?

**Comment by martijnwalraven** [comment]
In the current plugin, we don't actually run an embedded web server, but we use `NSURLProtocol` on iOS and `remapUri` on Android to intercept requests. I'm working on a new version of the plugin that will use an embedded web server (at least on iOS, not sure about Android yet). That means we will probably switch to using `localhost`. It might make sense to make port `3000` the default, at least when running in development mode.

**Comment by ccorcos** [comment]
sweet.

**Comment by martijnwalraven** [comment]
In Meteor 1.3, we now use `localhost` with a port between 12000-13000 based on the `appId`. We couldn't use a fixed port (like 3000) because we need to avoid conflicts between multiple Meteor apps installed on the same device.

So a way to avoid creating multiple access keys might be to run the server on your local development machine on that same port.

A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.
