### ISSUE TITLE
HTTP.call error handling

### ISSUE THREAD

**Issue by robertpitt** [meteor/meteor#5450]
Hey guys.

I have a small issue with the error handling within meteor's `HTTP.call`.

So API servers usually respond with a JSON object when there is an error, my server responds with 

``` js
{-
    "error": "invalid_token",
    "error_description": "The access token provided is expired, revoked, malformed, or invalid for other reasons.",
    "code": 401
}
```

When I make a server side call to my server with an invalid access token like so:

``` js
try{
    HTTP.call('GET', 'http://my.api/v2/me', {headers: {Authorizaton: 'blah'}});
}catch(e){
    // (e) => insanceof Error
}
```

The problem is now that I can not access the error object as your `makeErrorByStatus` mangles and truncates the data.

https://github.com/meteor/meteor/blob/devel/packages/http/httpcall_server.js#L112

The error object looks like this:

``` js
{ [Error: failed [401] {"code":1,"error":"invalid_token","error_description":"The access token provided is expired, revoked, malformed, or invalid for other reasons."}] stack: [Getter] }

```

I think we can all agree that JSON response to a HTTP.call are pretty common, as most use HTTP lib to consume an API.

Can we do a better job here, extract the error_description and code if available, or even override the error being throw so it can be handled correctly on an application level?

Thanks.

**Comment by martijnwalraven** [comment]
It turns out a possible workaround is to use the asynchronous callback style, which adds a `response` property to the error (see [here](https://github.com/meteor/meteor/blob/devel/packages/http/httpcall_client.js#L77-L85)). It makes total sense to do a similar thing for synchronous calls, so it would be great if you could open a pull request for this!

**Comment by robertpitt** [comment]
Not sure about MDG views on adding external objects to an Error Object, especially if the errors travel down the client via a `Meteor.Error`. I must admit though, it would be beneficial and I know that I lot of other libraries in other languages use that sort of approach.

```php
try {
    // .. Setup code above
    $response = $request->send();
}catch (NotFoundException $e) {
    $e->getResponse()->toJson(); 
}
```

As an example!

**Comment by hwillson** [comment]
Since this is functioning as designed, the suggestions outlined here fall under the feature request category. 

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=HTTP.call%20error%20handling&body=Migrated%20from:%20meteor/meteor%235450) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
