### ISSUE TITLE
Migrate from Fibers+Callback to (proposed) ES7 Async+Promises

### ISSUE THREAD

**Issue by Gaelan** [meteor/meteor#5460]
There is a proposed ES7 syntax (supported by Babel) that allows you to do something like Fibers. Basically, it allows you to write `async function() {...}`, then inside these functions you can use `await ...` to get the return value of a promise, Fiber-style. The function then returns a promise. This has a few advantages over Fibers:
- Works on the client
- Transparent (no surprise concurrency problems because you didn't know something was async)
- No `wrapAsync` equivalent needed for APIs that are already promise-based
- Embraces the community

Dynamics could probably be implemented by patching `Promise`.

**Comment by martijnwalraven** [comment]
You'll be happy to know Meteor 1.2 already has support for async/await! I agree it makes asynchronous code a lot more readable.

Whether we should fully move away from fibers is a point of discussion, because fibers do have some benefits (in fact, [meteor-promise](https://github.com/meteor/promise) uses fibers under the hood, at least on the server). If you're interested in more details, there is [an interesting talk](http://benjamn.github.io/goto2015-talk) by Ben Newman, one of the Meteor core developers.

**Comment by f0rmat1k** [comment]
@martijnwalraven i have meteor 1.2 with added `ecmascript` and still getting error if try to use async sintax.

**Comment by ShimShamSam** [comment]
@martijnwalraven I have the same issue as @f0rmat1k. I get an unexpected token error when using the async/await keywords

**Comment by f0rmat1k** [comment]
@ShimShamSam by the way, i learned about Meteor.wrapAsync and Fiber, so async/await is no longer needed.

**Comment by ShimShamSam** [comment]
@f0rmat1k The client is exactly where I need it, since that's where DB operations are always non-blocking.

**Comment by mhagmajer** [comment]
For anyone looking through this issues, here's the way to enable async/await functions in Meteor, as
@martijnwalraven suggested in his awesome tip!

`BabelCompiler` (used by packages `ecmascript` and `jsx`) takes an object with a bunch of params (including `meteorAsyncAwait` and `modules`): https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/babel-compiler/babel.js

I ended up overwriting `jsx` modules (it was smaller and I also use React) to turn on support for async/await. You'll also need to add `promise` package to your project.

CC @benjamn who worked on the actual implementation of these features.

**Comment by benjamn** [comment]
Glad it's working well for you!

The interesting nuance here is that it's easy and natural to implement await expressions using Fibers on the server (rather than using something more standard, like generators). The real value of async functions and await expressions is in the abstraction, since async functions allow the calling code to capture any kind of asynchronicity (await, Fiber.yield) within a Promise. The abstraction also means we could stop using Fibers as an implementation detail in the future, without much/any code needing to be rewritten.

In case this sort of thinking is interesting to you, here's a talk I gave earlier this year about the possibility of exposing the power of Fibers in terms of async/await: http://benjamn.github.io/goto2015-talk/#/

**Comment by mhagmajer** [comment]
I agree, @benjamn . Also thanks to the current implementation we can use Meteor Fiber-based sync server methods inside the async functions. :)

**Comment by benjamn** [comment]
@f0rmat1k @ShimShamSam Meteor 1.3 will have async functions enabled everywhere, using [Regenerator](https://github.com/facebook/regenerator) on the client and Fibers on the server. I wish they'd been enabled in 1.2, we just didn't realize how useful they would be.

By the way, here's how `meteor-promise` preserves dynamics on the client: https://github.com/meteor/promise/blob/0dd0b10afa/promise_client.js#L9-L10
And on the server: https://github.com/meteor/promise/blob/0dd0b10afa/fiber_pool.js#L24-L30

**Comment by josmardias** [comment]
Why don't completely get rid of fibers in favor of ES7 async functions?
I think this C/C++ dependency slows down node updates

**Comment by trusktr** [comment]
What are the benefits of Fibers-based async/await compared to ES7 async/await (comparing at a future point in time when ES7 async/await is natively supported)?

**Comment by josmardias** [comment]
@trusktr
You can only await "async functions" on ES7.
With fibers, you can "wrapAsync" any async function to turn it into sync call.
But IMHO it doesn't worth it, because Fibers is server side only, so it's a non isomorphic solution.
And to add to it, we don't need to talk about a future point, it's possible to use ES7 async/await [right now on both ES5 and ES6](https://github.com/josmardias/async-await-example) enabled environments through babel

**Comment by Gaelan** [comment]
I think that requiring functions that use `await` to be `async` is a good thing. Transparency, one of the biggest advantages of async/await, goes out the window if `await`ing functions don't require `await` themselves.

**Comment by hwillson** [comment]
This functionality has been available since Meteor 1.3. Closing - thanks!
