### ISSUE TITLE
Running "meteor" doesn't work if you have a meteor.js in the directory on Windows

### ISSUE THREAD

**Issue by OptimisticLock** [meteor/meteor#5461]

**Comment by OptimisticLock** [comment]
Sorry, did not realize that I actually opened that.

What happened was, I did this on Windows:

     meteor create meteor
    cd meteor
    meteor

And it gave me an error message. I then realized that it was because it attempted to run .\meteor.js. I renamed it to main.js an it worked.

A rare corner case I know, but you may want to address this programmatically, too; i.e. never create meteor.js

**Comment by stubailo** [comment]
I'm guessing you're on Windows?

**Comment by VishalRocks** [comment]
Yeah you are right stubailo, this is working fine in Ubuntu.

**Comment by OptimisticLock** [comment]
Yes, Windows. No biggie, just thought I'd let you know

**Comment by stubailo** [comment]
This is because Windows has something called "jscript" and the command line runs `.js` files by default when you type their name, even without the extension. (This is in contrast to unix, where you have to explicitly choose to run a local file with `./meteor.js`)

I'm not sure that there's much we can do about this. We could warn if someone tries to run `meteor create meteor`, but the same problem would arise if you later renamed a file to `meteor.js`.

**Comment by OptimisticLock** [comment]
I know. 

I think that instead of warning, you might create file "main.js" or something in this particular instance. Then if the user renames it, by then they should be able to attribute the failure to renaming. 

That's the tiniest issue I've ever opened. I was going to cancel it once I realized what's going on, but it somehow went through anyway.

**Comment by stubailo** [comment]
Yeah I think this probably isn't worth thinking about too hard.
