### ISSUE TITLE
Isobuild hangs on large js files in Meteor 1.2 (even with ecmascript removed)

### ISSUE THREAD

**Issue by jedwards1211** [meteor/meteor#5474]
**_2 Upvotes**_ It seems people reached the conclusion in https://github.com/meteor/meteor/issues/5275 that `ecmascript` is to blame when isobuild hangs on large js files.

However, even with `ecmascript` removed, I've seen isobuild hang on large files.  Hence I'm creating a separate issue.  Our only workaround right now is to downgrade Meteor.

The bundles that have caused this for us contain a lot of private code so I don't want to post them in a public location.  But I'd be happy to send the bundles privately for reproduction's sake.

**EDIT** as it turned out, the build process succeeded after a long time, but it enlarged my `~/.meteor` folder by over 2 GB.

**Comment by rozzzly** [comment]
also checkout the [MongoDB `smallFiles` Directive](https://docs.mongodb.org/manual/reference/configuration-options/)

So here's a similiar issue I ran into on a remote test machine running CentOS 7. So when I ran `meteor run` it starts the `mongod` database daemon as per usual. I noticed that it got to the point where I couldn't even make it through the build process without getting `E_NOMEM`—_ie: machine out of memory._ My project wasn't doing anything crazy, but I did have `material-ui` as an NPM dep in a local package. Still, it was ridiculous. I didn't need it to be fast, but not working at all was unacceptable. So I dug deeper; the machine, which i got for free—thank you DigitalOcean—**only had 1GB of ram.** This wasn't for production so It's perfectly fine to test with. 

However, after further investigation, I found the issue. So here's what happened. By default MongoDB has a journal (or append only file) where it logs each transaction so that if there is a failure there is no/minimal data loss. Essentially it keeps a copy of each query you applied against the db. On this project, I had run your standard `meteor run` **many** times. And to reset the my fixture data, _to start fresh,_  I was using `meteor reset`. which flushes the db, removes any cached packages, etc. The issue was problem was, It would reset the DB, but it did nothing about the journal file. All of those queries just kept building on top of eachother. By the time I figured this out, I had (i believe) 3 different 2GB journal files. When meteor spins up `mongod`, it tries to load those files into memory... while it's building meteor.... **I only have 1GB of memory ⇛ out of memory errors.**

I was able to fix this by enabling the `smallFiles` config flag in my `/etc/mongod.conf`
```
storage.smallFiles=true
```

Some [configuration refernce](https://docs.mongodb.org/manual/reference/configuration-options/#storage.mmapv1.smallFiles) from the MongoDB docs

`smallFiles` makes mongoDB cap the journal's filesize at ~200mb, and then my error went away.

**Moral of the Story: pay attention to what's the compiler/bootscript is loading into memory. It can get a little greedy.**

**Comment by rclai** [comment]
@rozzzly is this something that can be configured on each individual Meteor app's local Mongo installation?

**Comment by rozzzly** [comment]
I have no clue, I don't believe meteor has any configurations available for mongo beyond the connection configs. To my knowledge, meteor doesn't have a "local mongo installation," ie binaries, but rather installs mongo and then adds a new db to it which it stores somewhere in `.meteor`. This is all conjecture, Im at work atm so I cant really look into it. It's quite possible `mup` or a similar tool does something with this because they in fact do manage your installation/play around with your config files in `/etc`

**Comment by benjamn** [comment]
I'm not sure if the issues @jedwards1211 and @rozzzly are talking about are closely related.

@jedwards1211 if you can possibly put together a minimized reproduction, that would be really helpful for a bug like this! If the contents are too sensitive for posting publicly, my work email address is just my first name at meteor.com.

**Comment by rozzzly** [comment]
Well the issue I spoke about does not preclude me from getting the 2gb `.meteor`. My "fix" only stopped mongo from making huge journal files (in the system dir, not in local meteor installs). As such, I would asset that these are not the same issue, but perhaps related. I haven't looked into @jedwards1211 issue (I am experiencing it myself) but think its very likely that the local db data file has something to do about it. Just a hunch.

**Comment by D1no** [comment]
Here is a reproduction with a "large" file (622KB), even in compatibility folder, freezing the build process on `Determining active plguins` and `Building for web.browser`.
https://github.com/D1no/Meteor-Build-Freeze

Easy to reproduce [MacBook Pro 13" 2,5GHz i5, 8GB RAM, OS X 10.11.1]
![metoerbuildfail_ecmascript](https://cloud.githubusercontent.com/assets/2397125/10883896/33632f8e-8175-11e5-99aa-e72d41ad9f2b.gif)

When the file-extension is changed to `*.es5.js` the build goes through
![metoerbuildfail_es5](https://cloud.githubusercontent.com/assets/2397125/10883920/6055c95c-8175-11e5-9a87-85e1895e0ba5.gif)

**Comment by bmustata** [comment]
+1

**Comment by vleipnik-miovision** [comment]
+1

**Comment by galdo666** [comment]
+1. We have the same problem with fabric.js (more than 700KB).

**Comment by sergiotapia** [comment]
So what's the solution here? Just change the extension?

**Comment by sergiotapia** [comment]
Ok, extremely odd but that fixed it @stubailo

**Comment by jedwards1211** [comment]
@sergiotapia so even without the `ecmascript` package added, changing the extension to `.es5.js` has an effect for you?

**Comment by benjamn** [comment]
[This commit](https://github.com/meteor/meteor/commit/ad3f56a0bf0de4f28a2476a83f5b695e3ab1d1a0) should also help quite a bit with huge files.

**Comment by sergiotapia** [comment]
Yes @jedwards1211 super strange but I am not familiar with the build internals.

**Comment by kevinpeter** [comment]
@benjamn Thanks for your answer but the error still appears with METEOR@1.3.2.4. So i think there is another error. I fix it as mention from @D1no, when changing file extionsion to `.es5.js`

**Comment by hwillson** [comment]
There hasn't been any activity on this issue in a while, and there have been many Meteor releases since this issue was posted. As part of the on-going old issue cleanup process, I'll close this off. Happy to re-open if anyone is still encountering this issue with the latest version of Meteor. Thanks for posting this originally!

**Comment by GerhardHH** [comment]
Not sure about having the same problem, but I suggested a hacky solution to Meteor: https://forums.meteor.com/t/meteor-stuck-in-processing-files-with-ecmascript-for/25227/15
Maybe it helps.
