### ISSUE TITLE
 mobile-config.js Unexpected token < Error

### ISSUE THREAD

**Issue by paddydub** [meteor/meteor#5483]
When I updated my mobile-config.js file in the root directory with:

App.info({
  id: 'co.test',
  name: 'Test'
});

I get the following error :
Uncaught SyntaxError: Unexpected token <

When I remove it the error goes away. Any ideas why it would be causing an error? 

I'm using Meteor 1.2.0.2

**Comment by miri-am** [comment]
when I copy your code into my Meteor 1.2.0.2 app, it works completely fine.

**Comment by martijnwalraven** [comment]
I assume `Uncaught SyntaxError: Unexpected token <` is an error you receive in the browser? This is usually a sign the browser is trying to interpret an HTML file as JavaScript. Because we serve a bootstrap page for every file instead of a 404, that might mean you're trying to access a non-existing resource.

**Comment by abernix** [comment]
This doesn't seem to be reproducible.  If the original poster can provide more details, this can be reopened.
