### ISSUE TITLE
How to make isotope working normally with Meteor.js ?

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#549]
every time template rendered

isotope layout will mess up

**Comment by AllanPinheiroDeLima** [comment]
Well, I've found a simple way. Generally the issue in my case happened because of the async function of Meteor. So what I had to do was load my plugin after the images were loaded. I did simply use Jquery "load" function to tell me if my images were loaded and then initialize it, since Tracker.afterFlush was not working properly for the case:

Template.media.events({

  'load img': function(event, template) {
   $('.grid').isotope({
  itemSelector: '.grid-item',
  percentPosition: true,
  fitWidth: true,
  isAnimated: true,
  transitionDuration: '0.4s',
  });
}

})

I know that it is been a long time since this was posted, but I hope helps someone
