### ISSUE TITLE
Long file paths for packages causes problems in build

### ISSUE THREAD

**Issue by ericterpstra** [meteor/meteor#5493]
When adding packages during development, many have very deeply nested node_module dependency trees.  It doesn't seem to be an issue during development, but after running `meteor build` and trying to copy the built application folder, push to a git server, or deploy via Kudu, errors pop up because there are file paths that exceed 260 characters (the limit on Windows). 

The only way I have found to fix this is to run [flatten-packages](https://www.npmjs.com/package/flatten-packages) inside `bundle\programs\server\npm\{offending-package}` or do an `npm uninstall` or delete node_modules, and `npm install` using npm3 (which creates a flat node_modules directory). 

I don't know what Meteor is actually doing when I add a package.  The particular package I'm having trouble with is [tdamsma:meteor-accounts-ldap](https://github.com/tdamsma/meteor-accounts-ldap/). The repo does not include a node_modules folder, so I assume at some point the dependencies are pulled down, and a very long string of node_modules folders are created.  Does this process use `npm install`?  If so, is there a way to force it to use npm3 to get a nice flat node_modules folder?

**Comment by stubailo** [comment]
We essentially gave up trying to flatten these directories, and instead decided to switch to tools that support long file paths. For example, the Node `fs` module has no problems with these paths. Other than switching to NPM 3, I don't know what we could do.

I think switching to NPM 3 should be a top-level goal/concern, since this isn't the only issue that would be fixed by it. Going to file that issue, and close this one.

https://github.com/meteor/meteor/issues/5553
