### ISSUE TITLE
Document App Icon and Splash Screen Sizes

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#5497]
**_2 Upvotes**_ The docs tell me the keys, but I'm not sure what that means -- what sizes are they supposed to be?

http://docs.meteor.com/#/full/App-icons

**Comment by martijnwalraven** [comment]
You're right, this should be part of the documentation and they may also need to be updated. For now, these are the sizes as defined in the code:

```javascript
const iconsIosSizes = {
  'iphone': '60x60',
  'iphone_2x': '120x120',
  'iphone_3x': '180x180',
  'ipad': '76x76',
  'ipad_2x': '152x152'
};

const iconsAndroidSizes = {
  'android_ldpi': '36x36',
  'android_mdpi': '42x42',
  'android_hdpi': '72x72',
  'android_xhdpi': '96x96'
};

const launchIosSizes = {
  'iphone': '320x480',
  'iphone_2x': '640x960',
  'iphone5': '640x1136',
  'iphone6': '750x1334',
  'iphone6p_portrait': '1242x2208',
  'iphone6p_landscape': '2208x1242',
  'ipad_portrait': '768x1004',
  'ipad_portrait_2x': '1536x2008',
  'ipad_landscape': '1024x748',
  'ipad_landscape_2x': '2048x1496'
};

const launchAndroidSizes = {
  'android_ldpi_portrait': '320x426',
  'android_ldpi_landscape': '426x320',
  'android_mdpi_portrait': '320x470',
  'android_mdpi_landscape': '470x320',
  'android_hdpi_portrait': '480x640',
  'android_hdpi_landscape': '640x480',
  'android_xhdpi_portrait': '720x960',
  'android_xhdpi_landscape': '960x720'
};
```

**Comment by ccorcos** [comment]
sweet. Thanks!

**Comment by miclaus** [comment]
Is `iphone6p_landscape` missing ?

**Comment by martijnwalraven** [comment]
@miclaus: For some reason, the `iphone6_landscape` size is not supported by Cordova. (See [here](https://cordova.apache.org/docs/en/latest/config_ref/images.html#configuring-splash-screens-in-the-cli) for supported sizes.)

In looking into this, it also turned out the iPad Pro sizes are not supported by Apple, so I had to remove these (https://github.com/meteor/meteor/commit/cb0bfc0fe036875ebbb69c1b4303652ba0c17b6b).

**Comment by miclaus** [comment]
I see; thanks for looking into this .

**Comment by skirunman** [comment]
It looks like the icon and splash screen sizes mentioned above have changed as per https://github.com/meteor/meteor/blob/release-1.3/tools/cordova/builder.js

**Comment by timmakken** [comment]
Looks like android lpi is missing from the file @skirunman linked to.

I was about to create a new issue but i think here may be a better place since its so similar:
the would be issue title : Android Icon Size ldpi is wrong/ no longer supported
`WARNING: android_ldpi: unknown key in App.icons configuration. The key may be deprecated.
` 
was the verbose output when i added the ldpi icon to the mobile-config.js
to test if it was my app that was bugged i cloned the todos example and ran it on both my phone and nvidia shield tablet.
my phone displays the icon properly but my tablet does not.

According to the cordova docs there should be a ldpi size.
and according @martijnwalraven 's post from the end of 2015 it should be there.
So i hope that can be added back to the build tool :+1:

**Comment by ThomsCass** [comment]
+1

**Comment by rjakobsson** [comment]
I believe the original issue is solved and that this could be closed.

**Comment by abernix** [comment]
Yes, this appears to be documented now in the documentation here:

https://docs.meteor.com/api/mobile-config.html#App-icons

Thanks for reporting this, @rjakobsson.
