### ISSUE TITLE
force-ssl redirects all traffic, even if it was already ssl

### ISSUE THREAD

**Issue by satyavh** [meteor/meteor#5500]
The issue is in this logic:

```
  var isSsl = req.connection.pair ||
      (req.headers['x-forwarded-proto'] &&
       req.headers['x-forwarded-proto'].indexOf('https') !== -1);
```

`req.connection.pair` is always undefined (does this even exist, it's very undocumented? When I log out the req.connection then `pair` does not exist), so unless the `x-forwarded-proto` header was set, isSsl always results in `undefined`.

Then the next logic kicks in:

```
if (!isLocal && !isSsl) {
  // perform a 301
```

so if you're on production this will always result in a redirect, no matter if your original request was already ssl.

This really has implications for CORS, because redirects don't redirect CORS headers. Besides, it results in unnecessary redirects.

**Comment by zol** [comment]
Hey @satyavh . Could you provide some more info on what the actual problem is that you're hitting. The `force-ssl` package definitely works, we use it in production for most of our apps.

Ideally, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor . Please include  the deployment environment+configuration that you're using. Without a way to replicate your problem, we can't debug and fix it.
