### ISSUE TITLE
Is it possible to disable loose mode for ecmascript?

### ISSUE THREAD

**Issue by istarkov** [meteor/meteor#5503]
How to disable loose mode for ecmascript?

**Comment by benjamn** [comment]
You should add `"use strict"` to your files manually if that's what you care about. Please note, however, that the Meteor style of assigning to package-global variables will not work in strict mode.

In our judgment, compiling in loose mode produces more efficient code, with fewer surprises due to things like temporal dead zone warnings.

Can you say more about specific behaviors that you wish were different?

**Comment by istarkov** [comment]
For me it is developer decision to enable-disable loose mode also default mode for babel is loose mode off. I had some issues with iterable destructuring. 
Like [...Array(N)] but it's not easy to find this issues having all that code works fine with babel and with grigio:babel package before. It must be written in documentation about this.

**Comment by abernix** [comment]
Meteor 1.3 has been released and supports ES2015 modules.  I don't believe you'll have any issue implementing `use strict` with the new module system.  Closing this issue because I believe it has been resolved, but please feel free to @mention me if you think it should be reopened or needs further discussion.
