### ISSUE TITLE
Add support for configuring minifiers

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#5512]
Currently, you can't specify a configuration filename for a minifier build plugin.

We need this for CSS autoprefixer: https://github.com/meteor/meteor/issues/5219

@sebakerckhof noticed this check that prevents the filename option: https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/isobuild/isopack.js#L817

It's unclear if there are more issues down the line that would prevent removing that check, but it's likely that there is real code to be written here. According to @Slava there might also be some stuff to ensure around caching.

**Comment by sebakerckhof** [comment]
Let's say this does work. What is the API to get the file?

From a quick look (I should look further if I have time, but the build system code feels like walking in a maze), the filenames are treated the same way as extensions. (really as files to process?)

**Comment by stubailo** [comment]
I think you would look at the `files` argument [here](https://github.com/meteor/meteor/blob/dd2f166fe93a6a896983b8d724c5ad1efdc8ba6d/packages/standard-minifiers/plugin/minify-css.js#L12) and filter through it until you find the right filename.

Confirmed, that's what the [jshint](https://github.com/meteor/meteor/blob/dd2f166fe93a6a896983b8d724c5ad1efdc8ba6d/packages/jshint/plugin/lint-jshint.js#L40-L42) package does, which was written by @Slava who actually implemented this feature. So it seems that is the intended usage.

**Comment by sebakerckhof** [comment]
Okay, that's what I thought, but it looked (is?) a bit weird. Anyway, it's probably not too hard to make it work, although I'm afraid there must have been a good reason to explicitly disallow this?

**Comment by stubailo** [comment]
> I'm afraid there must have been a good reason to explicitly disallow this?

According to @Slava, he just didn't have time to implement this properly. So it's not just a matter of removing that flag, there might be some other stuff. We would also need to add tests to make sure it works, but I can help with that if you can help me out with the initial implementation.

**Comment by sebakerckhof** [comment]
Btw, what would be so bad about reading the config file from process.cwd() directly? For linters it makes sense, since you might want to have different linting configurations per package, where you might not know the path to. But for css postprocessors it doesn't make sense to have more than one for the entire app.

**Comment by stubailo** [comment]
I mean, let's start with the basics - if it's not part of the officially supported Meteor API it could break at any time. We need to be able to change the internal structure of files to make any progress on the platform. So using the API if it is present is inherently better for everyone.

Then there are the more minor reasons (but the one above is really the top one):

1. File watching and reloading
2. Smart caching can know when the file has changed or not
3. People know to check that into source control, and it's not inside a location reserved for internal Meteor files
4. `process.cwd` will fail if the `meteor` command isn't run from the root of the project

**Comment by sebakerckhof** [comment]
Of course an API is better, but what I meant was: It's not going to break anything if I (as a temporary solution) read files in a build plugin? People are complaining about the lack of autoprefixer, but I guess this won't make it in the next release which is already in RC. If I'd move the config file out of the .meteor folder and into the apps root, nothing would have to change for the user when we switch to using this API.

**Comment by stubailo** [comment]
@sebakerckhof I mean at the end of the day it's up to you what you want to do, but I would prefer to do it right and take the extra time. I can try to look into the minifier config thing tomorrow.

**Comment by stubailo** [comment]
This package also implements the "read-config-file-from-fs" approach: https://github.com/juliancwirko/meteor-postcss

**Comment by carlosbaraza** [comment]
Hi @stubailo,

I am currently working on this feature. As far as I understood, you would like to be able to make available the files defined  in `options.filenames` within the callback function given to `registerMinifier`. Then this way the package creator would not need to handle the filesystem himself. Did I get it right?

However, I have a small question regarding the debugging of meteor tools code. I will add some tests [here](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/tests/custom-minifier.js) and I would like to debug the actual `isopack.js` code using `node-inspector`, running the test like this `NODE_OPTIONS="--debug-brk" ./meteor self-test 'custom minifier - devel vs prod'`. The problem is that this does not break execution if I drop a `debugger` in `isopack.js`, only if it is in the actual test app. I wonder how the meteor team debugs some code from the meteor core.

**Comment by stubailo** [comment]
@benjamn figured out how to do this, I think. Ben, can you give us a tip?

**Comment by carlosbaraza** [comment]
@stubailo and @benjamn, I was just having a look to meteor's run script and I found `TOOL_NODE_FLAGS` env variable. Therefore, now I can run `TOOL_NODE_FLAGS="--debug=6060" ./meteor self-test 'custom minifier - devel vs prod'` to set a debugger in port 6060 and use `node-inspector` to connect to it. 

However, I now face a different issue because it doesn't break the interruption at any `debugger;` in the meteor cli. Instead I receive the following output:
```
$ TOOL_NODE_FLAGS="--debug=6060" ./meteor self-test 'custom minifier - devel vs prod'
debugger listening on port 6060
custom-minifier: custom minifier - devel vs prod ...
  ... fail!
  => wrong-exit-code at ../../../../tools/tool-testing/selftest.js:665
  => Expected: 0; actual: 1
  => Last 100 lines:
  2| debugger listening on port 6060
  2| => Errors while initializing project:
  2|
  2| While loading plugin `minifyCustom` from package `custom-minifier`:
  2| error: Plugin.registerMinifier does not accept `filenames`
  2|
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying
  1| Failed to open socket on port 6060, waiting 1000 ms before retrying

Skipped 147 non-matching tests (don't match specified pattern)

1 failure:

```
My guess is that at some point `self-test` is booting the test application and then it is trying to listen to the same port. I tried the following things: 

* Set `NODE_OPTIONS="--debug=5859"` as well. It did not work, same output.
* Run `TOOL_NODE_FLAGS="--debug-brk" ./meteor self-test 'custom minifier - devel vs prod'`.
** This will actually stop at the first node line, going trough the entire module loading maze. I followed it around and finally I was able to set a break point in the `commands.js` file. However, still, if I continue the execution, it will not stop in any `debugger;`.
** If the execution is continued, the test will fail due to a timeout.
* I even tried to hardcode a port [here](https://github.com/meteor/meteor/blob/f7b2735d2320eecafe478f3e4dd77ccaab848194/tools/runners/run-app.js#L67) but it didn't work.

I feel I am getting close to be able to debug but I might be missing something you guys know :).

**Comment by carlosbaraza** [comment]
I just found a very [awesome explanation of the usage of `self-test`](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/README.md). With the trick of setting a multiplier for the timeout, I am able to break in the first line and set a `debugger;` somewhere. `TIMEOUT_SCALE_FACTOR=5 TOOL_NODE_FLAGS="--debug-brk=6060" ./meteor self-test 'custom minifier - devel vs prod'`

However, now I am trying to figure out why it tries to bind multiple times to the same port.

**Comment by carlosbaraza** [comment]
Well I finally figured out what was going on. I am able to drop a debugger where I wanted in the `isopack.js` file.

The issue is that when the test application is spawn [in the test](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/tests/custom-minifier.js#L8), and more concretely in [selftest.js](https://github.com/meteor/meteor/blob/devel/tools/tool-testing/selftest.js#L580); the env variable `TOOL_NODE_FLAGS` is trying to bind the new test app to the same port.

How I solved is setting the `TOOL_NODE_FLAGS` in the [`_makeEnv` function](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/tool-testing/selftest.js#L789). What I do is adding 1 to the port number given to `TOOL_NODE_FLAGS` (or to the default 5858 = 5859). Then, I could open a new inspector that connects to port 5859 and debug the piece of code I wanted to debug.

I will do a PR with the fix in [`_makeEnv` function](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/tools/tool-testing/selftest.js#L789):
```javascript
    // When TOOL_NODE_FLAGS is set in the main CLI call, the new spawn
    // process will have the port set to port + 1, in order to avoid collisions
    // trying to bind multiple times the same port.
    var TOOL_NODE_FLAGS = process.env.TOOL_NODE_FLAGS;
    if (typeof TOOL_NODE_FLAGS !== 'undefined') {
      let opt = TOOL_NODE_FLAGS.split('=')[0],
          port = Number(TOOL_NODE_FLAGS.split('=')[1]) || 5858;
      env.TOOL_NODE_FLAGS = opt + '=' + (port + 1);
    }
```

Any suggestions about a better way to do this @stubailo @benjamn ?

**Comment by carlosbaraza** [comment]
@stubailo and @benjamn, I submitted the issue #5776 relating the debugging and the PR #5777 to fix it.

**Comment by mitar** [comment]
Maybe this could be done as part of #7829.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20support%20for%20configuring%20minifiers&body=Migrated%20from:%20meteor/meteor%235512) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
I think this could be done as part of https://github.com/meteor/meteor-feature-requests/issues/83.
