### ISSUE TITLE
ReactDOM.render throws Target container is not a DOM element

### ISSUE THREAD

**Issue by almasakchabayev** [meteor/meteor#5580]
Hello, When using ReacDOM inside a package it throws 
```
Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

I have written an extented question on stackoverflow: http://stackoverflow.com/questions/33450282/meteor-react-split-break-down-a-meteor-app-into-packages-targeting-both-mobile

**Comment by stubailo** [comment]
Can you post an entire app that exhibits this? There are some code snippets in your SO question, but they don't seem to explain why the behavior is happening.

To fix your problem in the short term, you can remove `blaze-html-templates` from your project, and add `static-html` - this will include the HTML in the server response rather than using Blaze to render it.

If you think this is indeed a bug in Meteor, we'll need a complete app to reproduce it.

**Comment by almasakchabayev** [comment]
templating package solved the issue. I am just staring with meteor, now understading it a bit more.
By the way absolutely awesome platform, I wish I knew about it before. Although I wonder why browserify is used, webpack seems like a better solution...

**Comment by phtn** [comment]
meteor remove blaze-html-templates
meteor add static-html

**Comment by siccoo** [comment]
![reactdom](https://user-images.githubusercontent.com/43604282/46726684-c51cb400-cc76-11e8-980f-0530b8b2d836.png)
Hello I've been having this issue with React, I need someone to help out or I will just go and create a new React app. Thank you

**Comment by siccoo** [comment]
I tried fixing it but to no avail, I had to put another bracket to the ReactDOM.render as in like this ReactDOM.render((<what>, <where>)) but still it didn't work and so I need your help. Thank you

**Comment by yuvii** [comment]
@phtn Thank you! Why, though? Like why does that work?

**Comment by Johnnybar** [comment]
In case someone had the same issue and the previous answers didn't solve it:
I had similar issues after creating a meteor app. Trying to remove blaze-templates and adding static html gave me different errors, and even with adding the 'import/main.html' removing 'static-html' gave me the error above. 
Finally, I realized that the dumb reason (in my case) that this was not a 'DOM element' was because I copy-pasted the id value of the div with curly quotes (div id = “app”) instead of straight ones (div id = "app") from the tutorial I was following. So it wasn't recognized as a DOM element.
Hope this helps someone

**Comment by kishorereddy84** [comment]
check index.html and check for div id.

**Comment by KromKazuto** [comment]
I alter the id to root in div form html.index

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <title>Teste</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

  </body>
</html>

**Comment by KromKazuto** [comment]
I just especify root in div 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />

    <title>Against Fire</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

  </body>
</html>
```

**Comment by sunniafroz** [comment]
Error: Target container is not a DOM element.
render
C:/Users/HP/disney-clone/node_modules/react-dom/cjs/react-dom.development.js:26091
Module.<anonymous>
C:/Users/HP/disney-clone/src/index.js:7
   4 | import App from './App';
   5 | import reportWebVitals from './reportWebVitals';
   6 | 
>  7 | ReactDOM.render(
   8 |   <React.StrictMode>
   9 |     <App />
  10 |   </React.StrictMode>,


I got this error can anyone sort it out??
  Thanks

**Comment by yashmanuraj2** [comment]
Firebase actually changes index.htnl <div id ='message'> was there in my case change message to root it will work fine

**Comment by ramblingbarney** [comment]
for others getting this error with Jest tests see https://stackify.dev/641896-testing-react-target-container-is-not-a-dom-element

`ReactDOM.render(
  <Provider store={store}>
    <AppRouter />
  </Provider>,
  document.getElementById("root")
);
registerServiceWorker();`

to (in my case)

`ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root') || document.createElement('div')
);`
