### ISSUE TITLE
Unable to include less files that don't have .less extension (such as semantic's .variables)

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#5598]
**_1 Upvote**_ Hi,

I'm using the semantic-ui package which creates a file hierarchy inside the client folder. My local **packages** need to access these files, and under Meteor 1.1 I was doing this:

``` less
@semanticFolder: "../../../client/semantic-ui/";
@import "@{semanticFolder}themes/default/globals/site.variables";
@import "@{semanticFolder}themes/material/globals/site.variables";
@import "@{semanticFolder}site/globals/site.variables.import.less";
```

This  no longer works using less 2.5, reporting the error **Unknown import**.

I thus changed the code to this, using the new syntax:

``` less
@import "{}/client/semantic-ui/themes/default/globals/site.variables";
@import "{}/client/semantic-ui/themes/material/globals/site.variables";
@import "{}/client/semantic-ui/site/globals/site.variables.import.less";
```

This also fails with the same error. However, this sort of works:

``` less
@import "{}/client/semantic-ui/site/globals/site.variables.import.less";
```

At least it would have worked if the variables that I need were defined!

I created a test package to verify the issue. If the file doesn't have the .less extension then the **Unknown Import** error is generated, even though the file exists. Since these files are generated in the client folder I have no way to mark them as being less imports.

It's thus impossible for me to compile my project using less 2.5

**Comment by stubailo** [comment]
So in Meteor 1.2, the LESS package can only import files that are known to be LESS - `.import.less`, `.less`, etc. This is partially so that we can reliably detect which files need to be watched for changes. There are a couple ways we could try to work around this:

1. Make sure that everything has the `.less` extension - make a script that converts `.variables` into `.variables.less`
2. Make it so that the less import falls back to searching the file system in cases where Meteor can't find the file, but then we lose file watching functionality

The main issue here is that there is no way to configure which plugin is supposed to handle a certain file type without having a special file extension.

Is it an officially supported feature of LESS that you can import LESS files with no `.less` extension? It almost seems like Semantic UI is taking advantage of some weird edge case of the import functionality which it kind of shouldn't be. Not that that is a valid excuse for this not working in Meteor.

**Comment by timothyarmes** [comment]
Option 1 isn't a solution in this case since the entire semantic-ui structure is generated by the semantic package. I can't simple rename the files. Even if I did I'd then need to rename the imports inside the less files that would then be regenerated.

Option 2 sounds like the right way to go. We just need to document the fact properly.

**Comment by supdegrave** [comment]
Has there been any progress on this issue? I'm running into the same problem.

**Comment by breagan1983** [comment]
+1 Similar Issue

**Comment by djwhatley** [comment]
Also running into this issue with Semantic UI. Perhaps there could be a config file that specifies custom mappings of file extensions to watchers?

**Comment by hwillson** [comment]
With regards to the [semantic:ui](https://atmospherejs.com/semantic/ui) package specifically, this issue has been resolved (see https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/78#issuecomment-231584140). As mentioned in https://github.com/meteor/meteor/issues/5598#issuecomment-153500604, there are reasons why the `.less` extension is expected, and this isn't likely to change anytime soon. As part of the on-going old issue cleanup process, I'll close this off. Thanks for reporting this issue originally!
