### ISSUE TITLE
Session.get unavailable from iframe

### ISSUE THREAD

**Issue by hsduk** [meteor/meteor#5617]
I have user generated markdown which uses iframe to load a specific template from the same meteor app.
I can't t access Session.get vars from the referrer/parent is this by design? - this would be useful, when the url is the same app.
Is there a better way to do this? I could pass args but would prefer to use Session.get directly.

Template A (locahost:3000/foo) -> Markdown -> render iframe -> Template B  (locahost:3000/foo/bar)

I'd like to access parent Template A's Session variables from within Template B's helpers

**Comment by stubailo** [comment]
I don't think using an iframe is correct here, I'd suggest doing what you're doing in a different way.

However, you could achieve what you're looking for by using localstorage: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

We will not integrate session with localstorage because it's important for it to not be preserved across different tabs or page reloads - it's intentionally a temporary local data store.

**Comment by hsduk** [comment]
Thx, I should have researched some more earlier! I see you made https://github.com/stubailo/meteor-markdown-templating :)
