### ISSUE TITLE
ES6: Static getters are not inherited

### ISSUE THREAD

**Issue by art-reddy** [meteor/meteor#5624]
Hi!

I noticed that child classes don't get static getters of parent class in Meteor. For instance:

```javascript
class A {
    static get foo () {
        return 'bar';
    }
}

class B extends A {

}

console.log(B.foo);
``` 
If I run it in Meteor application (1.2.1) this code returns 'undefined' but if I run it here https://babeljs.io/repl/ I get 'bar'.
I use ecmascript 0.1.6 package.

**Comment by rdickert** [comment]
Confirmed. I get the same results with this code (i.e., Meteor and the Babel repl output don't match)

**Comment by benjamn** [comment]
See [this comment](https://github.com/meteor/meteor/blob/211dd58165b6f58f23c98adc807b0144a0726c9d/packages/babel-runtime/babel-runtime.js#L101-L119) for an explanation of why we deviate from Babel on this.

In short, if you rely on this difference in behavior, then your code probably would not have worked in IE8. But maybe you already knew that, because getters and setters are not supported in IE8.

We could potentially use `Object.getOwnPropertyDescriptor` and `Object.defineProperty` (thanks to core-js polyfills) instead of simple assignment, and that would preserve your getter/setter behavior in browsers that support it.

cc @dgreensp

**Comment by dgreensp** [comment]
I just learned from @benjamn that `ecmascript-runtime` already polyfills `Object.defineProperty` and `Object.getOwnPropertyDescriptor`.  I say yes, let's copy the property the descriptors, but still not set a prototype (so that unlike Babel, static methods you assign later will not be inherited).

**Comment by benjamn** [comment]
Hmm, I think these polyfills don't work so well in PhantomJS, where we run our integration tests.

**Comment by dgreensp** [comment]
That's surprising/interesting!

I remember hearing that PhantomJS is really old WebKit, sort of like a version of Safari that no one uses anymore.
