### ISSUE TITLE
TypeError: Cannot set property 'siteName' of undefined

### ISSUE THREAD

**Issue by appjitsu** [meteor/meteor#5687]
All of a sudden I am getting this error. I have included accounts-password and has been working until now. The code is server side.

    Accounts.emailTemplates.siteName = "mysite";

**Comment by appjitsu** [comment]
I just created a new project. Then copied the above code over to a file in the server folder and it works there.

The code in my original project is in a custom package and its adde to the package.js file. Im at a total loss as to why this is not working, when it was earlier.

**Comment by appjitsu** [comment]
Nevermind, it was a stupid issue on my end. <FACE_PALM/>

**Comment by kenlane33** [comment]
What was the trouble? 
I have achieved the same stupid issue. 
:|

**Comment by kenlane33** [comment]
Ahh.
Referencing 
```Accounts.emailTemplates.siteName```
when the accounts-password package has been removed. 
That will do it.
Doh!

**Comment by webmagnets** [comment]
I am having this issue, but the accounts-password package is installed.

**Comment by webmagnets** [comment]
Any ideas?

**Comment by abernix** [comment]
@webmagnets You've provided nothing helpful in making suggestions.  As you've seen above, it seems that this is generally caused by mis-use.  Without your code, there is no way to tell if you're mis-using it.   At the very least, you should explain what you're doing and where along with Meteor versions, `accounts-password` versions, etc.  Otherwise, there's not much to give.

Generally speaking, make sure that you're not using `Accounts.emailTemplates` before it's loaded.  Maybe try debugging using `console.log` statements starting with `console.log(Accounts);` and go from there.  Alternatively, please try re-creating the problem in a new, small project.

**Comment by webmagnets** [comment]
That was the problem. I was using it before it was loaded. Thanks.

**Comment by dmarkrollins** [comment]
So I hit this issue upgrading to Meteor 2.3 and my problem was that I am using packages to segment my code and I had added accounts-base and accounts-password but not explicitly to my root package. Once I pulled them into my package explicitly the issue went away.
