### ISSUE TITLE
Meteor.wrapAsync for asynchronous functions having more than 2 parameters?

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#5758]
I use the wrapAsync function for alot of functions that are async and I would like to know if there is a standard way of wrapping async functions which return more than just a single result object? So in case if a callback function has the signature `function(error, resp, body)`. Is there a way we could wrap this function? Is there a standard way the community uses for such cases?

**Comment by sorenpeterson** [comment]
The issue here is that when an asynchronous function is made into a synchronous function, it can only return one value. This is because the data is now being returned as opposed to passed into a callback. A callback can accept many params while a function can only return one. I would suggest using ES6 and object to solve your problem. Heres an example:

    var async = function(first, second, callback) {
        err = null;
        setTimeout(function() {
            callback(err, { first: first, second: second });
        }, 1000);
    }
    
    sync = Meteor.wrapAsync(async);
    
    var {first, second} = sync('abc', 123);

What I am doing here is passing both the first and second variables inside of an object to the callback so that the function is only returning one variable. Even though it contains both. And then I am using ES6's object destructuring capability to easily extract those values and place them in variables of the appropriate names.

If you would like me to explain this more I can help you out or point you in the direction of some great resources (namely frontendmasters.com).

**Comment by benjamn** [comment]
@sorenpeterson that's a great way of framing the problem, thanks!

By the way, if you're using the `ecmascript` package (for ES6 support), you can use object literal shorthand syntax to make the callback call even prettier:
```js
var async = function(first, second, callback) {
    err = null;
    setTimeout(function() {
        callback(err, { first, second });
    }, 1000);
}
```

**Comment by sorenpeterson** [comment]
@benjamn That's also an awesome point. I was worried about introducing too much new syntax and making my example too cryptic, but thank you for bringing that up.

**Comment by talha-asad** [comment]
So if i understand correctly wrapping the callback in another function that would return an object of the values needed. Basically wrapping it one more level deep. Looks like a good way to do it, I wonder if maybe it'll be more time-saving or easier to have another basic wrapping utility for such cases? So maybe ```wrapAsyncMultiParam``` that kind of returns an object with all arguments of the callback as an array or something. What do you think about that @benjamn

**Comment by hwillson** [comment]
Given that this issue thread includes a workaround to the original issue, and that it's been a while since this issue has received any attention, I'll close it off. Thanks for opening this originally!
