### ISSUE TITLE
pictures show up as "?" question marks 

### ISSUE THREAD

**Issue by kthotav** [meteor/meteor#5761]
For some reason when I run the local market app (example app on the meteor website) in a ios simulator pictures show up as "?" question marks.
on localhost:3000 the pictures show up, but not in the simulator. 

not sure if this a bug or if im missing something.

**Comment by avital** [comment]
I just tried and it works for me.

We'd probably need more information about your local setup to help with this. How did you run the app?

**Comment by kthotav** [comment]
I tried the example locally. 

$ meteor create --example localmarket

I attached a picture below how the the user's profile pic has a question mark. 

![screen shot 2015-12-08 at 4 10 22 pm](https://cloud.githubusercontent.com/assets/13564400/11672525/3c8033d8-9dc6-11e5-82a4-687f97878893.png)

**Comment by abernix** [comment]
@kthotav Meteor 1.3 is out and the localmarket app has been updated to use it.  Could you please try this and see if it works for you?

**Comment by abernix** [comment]
This problem doesn't happen to me using the latest Meteor, and I haven't seen this before.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
