### ISSUE TITLE
Meteor doesn't reconnect to Compose.io Mongodb after timeout or network change.

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#5773]
**_2 Upvotes**_ I use Compose.io as a production and development database.  In production, and in development, I'm experiencing db reconnection issues.  In production after a scheduled maintenance outage.  In development when my laptop switches AP's.  Meteor doesn't reconnect to the database.  See the logs below.

I have to manually stop and restart the server for it to reconnect.  It's very reproducible.

My connection strings look like this:

```
export MONGO_URL=mongodb://xxx:xxx@candidate.21.mongolayer.com:11951,candidate.20.mongolayer.com:11117/xxx-local?replicaSet=set-xxx
export MONGO_OPLOG_URL=mongodb://xxx:xxx@candidate.21.mongolayer.com:11951,candidate.20.mongolayer.com:11117/local?authSource=xxx
```

From the console:

```
I20151210-09:43:49.927(-6)? Exception while invoking method 'login' Error: failed to connect to [candidate.20.mongolayer.com:11117]
I20151210-09:43:49.927(-6)?     at Object.Future.wait (/home/michael/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151210-09:43:49.927(-6)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:986:1)
I20151210-09:43:49.927(-6)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1020:1)
I20151210-09:43:49.927(-6)?     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:1030:1)
I20151210-09:43:49.927(-6)?     at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:1054:1)
I20151210-09:43:49.927(-6)?     at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:869:1)
I20151210-09:43:49.927(-6)?     at [object Object].MongoConnection.findOne (packages/mongo/mongo_driver.js:776:1)
I20151210-09:43:49.927(-6)?     at Object.Collection (packages/matb33_collection-hooks/findone.js:27:1)
I20151210-09:43:49.928(-6)?     at Object.collection.(anonymous function) [as findOne] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
I20151210-09:43:49.928(-6)?     at [object Object]._.extend.findOne (packages/mongo/collection.js:305:1)
I20151210-09:43:49.928(-6)?     - - - - -
I20151210-09:43:49.928(-6)?     at [object Object].<anonymous> (/home/michael/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
I20151210-09:43:49.928(-6)?     at [object Object].emit (events.js:106:17)
I20151210-09:43:49.928(-6)?     at [object Object].<anonymous> (/home/michael/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
I20151210-09:43:49.928(-6)?     at [object Object].emit (events.js:98:17)
I20151210-09:43:49.928(-6)?     at Socket.<anonymous> (/home/michael/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
I20151210-09:43:49.928(-6)?     at Socket.emit (events.js:95:17)
I20151210-09:43:49.928(-6)?     at net.js:441:14
I20151210-09:43:49.929(-6)?     at process._tickCallback (node.js:448:13)
I20151210-09:43:49.929(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
I20151210-09:43:49.961(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
I20151210-09:43:50.045(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
I20151210-09:43:50.146(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
I20151210-09:43:50.246(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
I20151210-09:43:50.348(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
I20151210-09:43:50.449(-6)? Got exception while polling query: Error: No replica set primary available for query with ReadPreference PRIMARY
```

**Comment by tdesc** [comment]
+1 Same experience with mongolab.com database.

**Comment by stubailo** [comment]
Could you try connecting to your database using the MongoDB node driver in a regular Node app, and see if the same thing happens?

**Comment by MichaelJCole** [comment]
Hey @stubailo, I haven't tried that specifically, and don't have an node app like that handy for testing.

Here's the docs on how [handle MongoDB driver reconnects](https://mongodb.github.io/node-mongodb-native/2.0/tutorials/connection_failures/) and what [compose.io has to say](https://docs.compose.io/common-questions/debugging-connection-issues.html)

If the mongodb driver was having re-connection problems, how could my Meteor app handle it and recoonect?

Is there an event I should listen for?  And what would I put in the event to reconnect?  

This just seemed like something the Meteor DB layer would handle.

**Comment by stubailo** [comment]
Yes, I think we do try to handle it. I'm just trying to isolate the issue in your case. I'll take a deeper look at the Meteor driver code to see if we do the correct handling.

**Comment by MichaelJCole** [comment]
@stubailo I was just playing with this a bit.

This happens when the network switches interfaces:  eth0 -> eth1, wlan1 -> eth0.  Or when the access point changes wlan0 -> wlan0.  

I'm hosting on DO virtual machines that connect outside their data center to Compose.io.  So my only concern is the network will change between Meteor and Compose, and won't restart correctly.

**Comment by MichaelJCole** [comment]
It's not only when the network interface is switched.  I woke up and found a bunch of these in the logs.  The network interface had been the same all night.

http://pastebin.com/3C3nNFTP

**Comment by MichaelJCole** [comment]
Here is a SO answer talking about a similar problem with Azure, and an offer for support from support@mongolab.com

http://stackoverflow.com/a/14409431/1483977

**Comment by MichaelJCole** [comment]
I tried to get some help from Compose.io and had an extremely poor support experience.  After several emails, this was the result:

>> "cannot extend support into the application stack" - I'm experiencing this as a *transport or session layer issue*. The driver is unable to reconnect to the database. <<

> Correct, and that's the main reason why we're unable to help since by all indicators on all of the infrastructure that we have control over, there's nothing that would be refusing connections, dropping connections, or otherwise causing connection issues.

>> Devs who use Meteor have no control over the Compose servers, the driver, or how the Meteor stack uses the driver. <<

> This would be a bit of a puzzle for us, since by definition the driver and the meteor stack's usage of the drive is not within Compose's ability to manage, but is inside the developer stack and influence.

>> If it doesn't work OOTB, then it's safe to say it's broken as a back-end for Meteor Apps. <<

> Meteor does work out of the box with Compose, however in the absence of that experience there's a strong suggestion that the connection issues with failing to reconnect and seeing timeouts, there is a general development pattern for MongoDB (as well as most other databases on the market) to refresh connection pools on a several minute interval where connections are gracefully disconnect and then reconnected every few minutes. We see similar issues with any other driver on the market when connections are kept open without cycling. The connection is severed, and then when a connection is attempted to be used there is a timeout and connections have to be re-made. Cycling the pool, in whatever method is available to the driver, is the pattern to solve that for all databases essentially.

**Comment by serkandurusoy** [comment]
The problem is, the mongo driver allows for fine tuning and configuring this, but meteor [does not implement](https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/mongo/mongo_driver.js#L127) such connection management strategy/options except for auto reconnection.

The relevant configuration options are [these for v1.2](http://mongodb.github.io/node-mongodb-native/core/driver/reference/connecting/connection-settings/)

* keepAlive
* connectionTimeout
* socketTimeout

and for the [latest 2.1 driver](http://mongodb.github.io/node-mongodb-native/2.1/reference/connecting/connection-settings/) they are:

* socketOptions.keepAlive
* socketOptions.connectTimeoutMS
* socketOptions.socketTimeoutMS

In any case, they need to be set to the same number (milliseconds) and anywhere beteen a couple of minutes to an hour would be sufficient to mitigate this situation.

**Comment by babakness** [comment]
Wow. Looks like something that needs to be sorted out!

**Comment by serkandurusoy** [comment]
This is not a huge deal and requires certain conditions to be met in order to reveal itself as a problem.

That being said, a fix is in order.

Perhaps it can be incorporated into the work to be done for either one of [driver update](https://github.com/meteor/meteor/issues/5809) or [mongodb update](https://github.com/meteor/meteor/issues/5763), the latter being seemingly more imminent.

**Comment by mwkrieger** [comment]
I'm actually seeing the same exact behavior. 

Has anyone been able to come up with a working solution, yet?

**Comment by mwkrieger** [comment]
Still searching for an answer on this one. Has anyone been able to figure out a workaround at this point?

**Comment by rclai** [comment]
I'm also experiencing this issue. Reconnection doesn't work very well.

**Comment by meatwallace** [comment]
Have also been experiencing this issue. If there is some kind of temporary fix, would love to know.

Currently having to look into a new hosting strategy as these kind of unavoidable disconnects have knocked our production app offline 6 times in 4 days, and we are required by our client to host our mongo externally.

**Comment by juho** [comment]
I found a few reasons for this happening on my end; mainly the server's network was behind a NAT that closes idle TCP connections too eagerly. This happened with some service providers' networks (think cheapo VPS) and consumer grade modem/router combos. First fixed by changing router settings and the latter by changing to a better router.

**Comment by MichaelJCole** [comment]
@juho Hmmmm...  Are you suggesting people experiencing this problem should email Compose.io and Digital Ocean and tell them to "change their router settings and get better routers"?  

That would make Meteor.js an enterprise-only framework, which isn't how Compose.io or Meteor is being marketed.

**Comment by meatwallace** [comment]
FWIW, we are currently experiencing this issue using Modulus + Compose.io.

**Comment by juho** [comment]
@MichaelJCole willingly misquoting people and putting words in their mouth is generally a bad idea.

**Comment by Latnok** [comment]
My configuration is app deployed with meteorUp on cloud hosting with ip 190.#.#.# behind nginx, and my database on my own server with ip 91.#.#.# replicaSet with 3 nodes behind proxy (port forwarding).
After 3-4 connection to my app it don`t answer, in logs after 60-90 sec
Exception while polling query .... : Error: failed to connect to [91.#.#.#:27017]
Exception while polling query .... : Error: failed to connect to [91.#.#.#:27018]
Exception while polling query .... : Error: failed to connect to [91.#.#.#:27019]

"MONGO_URL": "mongodb://usr:pwd@91.#.#.#:27017,91.#.#.#:27018,91.#.#.#:27019/myapp?replicaSet=myRepl&authSource=admin"
"MONGO_OPLOG_URL": "mongodb://usr:pwd@91.#.#.#:27017,91.#.#.#:27018,91.#.#.#:27019/local?replicaSet=velesRepl&authSource=admin"

mongo nodes is up. 
connection from 190.#.#.# mongo --host=91.#.#.#:27017 is ok
connection from 190.#.#.# mongo --host=91.#.#.#:27018 is ok
connection from 190.#.#.# mongo --host=91.#.#.#:27019 is ok

**Comment by chiluap** [comment]
+1

Same here: the mongo-connection fails silently after restart of mongod.

Connecting with:  
```
    export MONGO_OPLOG_URL=mongodb://oplogger:<mypasswd>@<myserver>/local?authSource=admin
    # MongoDB connection string using todos as database name
    export MONGO_URL=mongodb://<my_db_user>:<my_db_passwd>@<myserver>:<my_port>/<my_db>
```

This is verry bad for production since no one is notified.  
I can force errors with: ```&autoReconnect=true```  
...still: we need at least an failure-event to handle the reconnect (like in DDP.connect()).

**Comment by poltak** [comment]
This has been happening with our app as well. Our setup is a docker cluster managed by mupx (mongodb container is also managed by mupx, however we've altered it slightly to allow oplog). Basically, two main containers:

- mongodb (runs mongod instance)
- meteor server (points to mongod instance via env)

Been working fine for months until the last few days where the `mongodb` container has been crashing (for whatever reason) and automatically restarted by docker. Then we get this problem where Meteor can no longer connect to Mongo. So essentially the same reason as others here (mongod restart), just in a docker context.

Simple hacky fix for us is to restart the Meteor container, then it will automatically connect back to Mongo and everything is fine again. Manually restarting the Mongo container (`docker restart mongodb`) reproduces this error, until the Meteor container is restarted.

Tried to fix it by adding the `connectTimeoutMS and `socketTimeoutMS` connection params to our Mongo connection string in our Meteor container ([Mongo docs](https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options)), to make it reconnect after 60secs, however that doesn't seem to do anything (although @serkandurusoy did say a few comments back, last year, that this isn't supported by Meteor) :\

Details:
- Meteor 1.3.4
- MongoDB 3.2.6

**Comment by poltak** [comment]
Our short-term fix for now has been to turn-off `replSet` on Mongo, and just make it a single, unscalable Mongo instance with no oplog. This has stopped it happening for now.

Good thing is, our app is small and we can sustain ourselves like this for now. Bad thing is, this isn't a long term solution and won't be a possibility for most big apps.

Feeling very lost with this one, as it's been running fine with `replSet` enabled on Mongo for months now, and everything else we have tried doesn't seem to have made any difference whatsoever.

**Comment by abernix** [comment]
Only a couple of you have included the versions of Meteor and Mongo that you're using but those that have are using incompatible versions of Mongo and Meteor.

Using any Mongo version over 2.6 with Meteor 1.3.x (or earlier) is **not** supported and is prone to error.  This is due to the version of the Mongo driver (version 1.4.32) that is bundled with Meteor.  You can see the [Mongo driver version compatibility here](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility).  If you're using Compose.io, this means that you should be using their Mongo-Classic deployment option as their normal deployment is 3.2.

The good news is that [Meteor 1.4 is coming soon](https://forums.meteor.com/t/coming-soon-meteor-1-4/23260) (in fact, the [beta is available](https://forums.meteor.com/t/announcing-meteor-1-3-4-1-and-1-4-beta-1/25460/1) for testing!), and will update the Mongo driver to support Mongo 3.2.

I would highly recommend those of you having Mongo issues to try using the new Meteor 1.4 beta and see if this problem goes away.

**Comment by chadokruse** [comment]
In case it helps anyone else troubleshoot, I was getting the `Exception while polling query` error regularly on Meteor 1.4.0.1 (mongo@1.1.10 + Compose 3.2.7) until I updated all the indirect dependencies.

After a `meteor update`, I updated the indirect dependencies as instructed. My list:
```
Newer versions of the following indirect dependencies are available:
 * autoupdate 1.2.11 (1.3.11 is available)
 * caching-compiler 1.0.6 (1.1.6 is available)
 * ddp-client 1.2.9 (1.3.0 is available)
 * ddp-server 1.2.10 (1.3.9 is available)
 * templating 1.1.14 (1.2.13 is available)
To update one or more of these packages, pass their names to `meteor update`
```

Also (Compose already suggests this btw), but using the combined MONGO URI (with failover mongo node) consistently throws the error...

`MONGO_URL=mongodb://<user>:<password>@aws-us-east-1-portal.12.dblayer.com:34567,aws-us-east-1-portal.89.dblayer.com:01234/test-meteor meteor`

...while using the single node URI appears to resolve the issue:

`MONGO_URL=mongodb://<user>:<password>@aws-us-east-1-portal.12.dblayer.com:34567/test-meteor meteor`

This may all be pure coincidence, but figured I'd share in case it helps someone.

**Comment by mattiLeBlanc** [comment]
We are also still seeing error message in our logging:

https://stackoverflow.com/questions/39583480/meteor-application-hosted-in-azure-using-accounts-package-causes-mongodb-connect

We run Meteor (demeteorized) on Azure and have a VM running Mongo 3.2. We had a lot of outages where the node process would crash and not recover.

Since we updated to 1.4 (and manually updated the packages above) we definitely see less errors (we where running meteor 1.3 with mongo 3 which was not recommended) but we still get an issue with a connection error to Mongo.
The account packages Token cleanup craps itself since there seems to be a connection drop.

Any suggestions would be welcome.

**Comment by maxnowack** [comment]
I've implemented a workaround that kills the instance, if the reconnect has failed.
It's very dirty, but prevents instances from having no working database connection:
````javascript
MongoInternals.defaultRemoteCollectionDriver().mongo.db.s.topology.on('reconnectFailed', err => {
  console.error(err.stack)
  process.exit(1)
})
````

Keep in mind, that this only makes sense if the instance would be restarted automatically.

**Comment by sferoze** [comment]
@chadokruse 

I have been having the same issues once in awhile with the connection to my compose database. I search the error and found this thread. 

I was reading the compose.io article about Meteor 1.4
https://www.compose.com/articles/meteor-1-4-mongodb-and-compose-ready-to-oplog/

And they mention that with 1.4 we can use the combined MONGO URI string since the new mongodb version 1.4 ships with supports it. 

But it looks like the combined MONGO URI was causing you issues?

Are you still using single URI or combined URI. Combined is better if it is supported and doesn't cause issues.

**Comment by MichaelJCole** [comment]
Hey, I tested this with 1.4 and it's working for me.  See notes in related bugs:

> Abernix: Closing as Meteor 1.4, which uses the updated version of the Node Mongo driver, supports this if the app is using a correct MONGO_URL and their Mongo server is properly configured. See #7450, #7492 and other related issues for more information.

I'm using Compose's new MongoDB offering (not the classic), with connection strings like this:

```
# Replicaset Dev
export MONGO_URL="mongodb://xxx:xxx@aws-us-east-1-portal.11.dblayer.com:999,aws-us-east-1-portal.10.dblayer.com:999/xxx-dev?ssl=true"
export MONGO_OPLOG_URL="mongodb://oploguser:xxxx@aws-us-east-1-portal.11.dblayer.com:999/local?authSource=admin&ssl=true"
```

I get a disconnect error in the log and no reconnection message, but after reconnecting wifi, I can login/logout of Meteor, so closing.  Thanks!

**Comment by voidale** [comment]
@MichaelJCole This bug is the other way around when the mongodb gets shutdown or restarted not your wifi, I'm also having issues right now with atlas cloud minor version being updated in the background and then my production server can't reconnect to it ever again. Thoughts on how we can fix this? I think also that another major fact is that meteor doesn't retry to reconnect to other nodes (combined URI is useless).

**Comment by MichaelJCole** [comment]
Hi Mark, I don't know where the answer is, but we won't find it in this issue.  The issue is between [Compose.io](https://www.compose.com/articles/connecting-to-the-oplog-on-the-new-mongodb/) and [MongoDB driver,](https://github.com/mongodb/node-mongodb-native) or [how Meteor uses the MongoDB driver](https://github.com/meteor/meteor/search?utf8=%E2%9C%93&q=MongoConnection).  Best to file a new issue if you see a way to improve it.
