### ISSUE TITLE
find and findOne selectors behave strangely

### ISSUE THREAD

**Issue by kamek-pf** [meteor/meteor#5775]
```javascript
collection.find(null).fetch()
    -> []
collection.findOne(null)
    -> undefined
collection.findOne(1)
    -> undefined
```

That's fine, but this : 
```javascript
collection.findOne(Function)
    -> Object
collection.find(Function).fetch()
    -> [Object, Object, ...]
```

Can be a bit confusing.
I know, garbage in, garbage out, but I felt like pointing this out :)

**Comment by tmeasday** [comment]
Hey @kamek-pf - I think this is the behaviour of the raw node mongo driver, we just replicate the same API for minimongo. 

I think what's happening here is that it treats a functional argument as a predicate to query with.

**Comment by navinSing** [comment]
the problem is with the find with query returning 1 or more than 1 elements.

find works fine for more than 1 elements 
but if the query return just 1 element find screws up the result :-1: doesn't return anything. then we have to use findOne... But why we need to hit the db twice and there is lot of boilerplate code just to handle this case.

Why can't

var query = {/* some query */ };
var resultset = ...find(query).fetch(); // with multiple documents passes 
var resultset = ...find(query).fetch(); // with one document fails   

// Why can't we fix this up ?

or may be simply provide - findRs(query)
