### ISSUE TITLE
Improve interaction between the new modules package and react

### ISSUE THREAD

**Issue by ciwolsey** [meteor/meteor#5795]
@benjamn Trying out 1.3 beta I noticed we can't use import/export keywords inside JSX files.

**Comment by willemx** [comment]
Also have this problem, see:
https://forums.meteor.com/t/need-help-with-importing-npm-package-with-1-3-beta/14778

**Comment by benjamn** [comment]
This is definitely a bug! Fixing it might be as easy as adding `modules: true` [here](https://github.com/meteor/react-packages/blob/f68f682a14a0d49814c4a753ec9711f23595c34d/packages/jsx/jsx-plugin.js#L5), but obviously we need to make sure the React integration works seamlessly otherwise. Getting the new `modules` package to work with (or take the place of) [the `cosmos:browserify` package](https://github.com/meteor/react-packages/blob/f68f682a14a0d49814c4a753ec9711f23595c34d/packages/react-runtime-dev/package.js#L29) used by `react-runtime-dev` might end up being the trickiest part.

**Comment by ciwolsey** [comment]
Yeah it's like cosmos:browserify isn't even transpiling. Assuming this is something the author needs to fix...

**Comment by ciwolsey** [comment]
Just tested { modules: true, react: true } and this does indeed work.

**Comment by avital** [comment]
We should look at this early.

What have people been doing with the browserify config time? We will no longer support this.

Time estimate: 3-5 days.

**Comment by ciwolsey** [comment]
@avital No longer support what?

**Comment by avital** [comment]
Sorry, I mean the "official way to use client-side NPM packages with react using browserify" that we've been recommending with Meteor 1.2

**Comment by benjamn** [comment]
@jeremyBYU several of the issues you mentioned in https://github.com/meteor/meteor/pull/5475#issuecomment-164837787 are being investigated as part of this issue (#5795).

**Comment by ciwolsey** [comment]
@benjamin Just seen your commit for this one. I'm gonna test it out now.
