### ISSUE TITLE
Service temporarily unavailable

### ISSUE THREAD

**Issue by Bandit** [meteor/meteor#5811]
My meteor.com hosted site is accessible, but there's nothing displaying from the Mongo DB. If I try to connect to the remote DB using `meteor mongo` I get `Couldn't open a mongo connection: Service temporarily unavailable. Please try again later.`

Is there a Meteor infrastructure status page somewhere?

**Comment by nabiltntn** [comment]
I am having the same issue , nothing is displayed other than Internal Server Error

**Comment by aspin** [comment]
Same deal, except all of my collections when visiting the Meteor hosted site are loading reaaallly slowly (or not at all; it varies a bunch).

**Comment by rdickert** [comment]
Unfortunately, some sites are experiencing outages due to problems with the Mongo cluster. This is part of a larger issue with Mongo that we are working on ([see this comment](https://forums.meteor.com/t/anybody-else-seeing-mongo-failures-on-meteor-com-hosted-apps/14495/20)). We will give status updates [here](http://status.meteor.com/) as this is sorted out.

I'm closing this issue as it is a service outage on MDG’s free hosting tier, not an issue on the Meteor framework.
