### ISSUE TITLE
.meteor/local/bundler-cache/linker folder is 709MB

### ISSUE THREAD

**Issue by timmyg** [meteor/meteor#5818]
**_3 Upvotes**_ ```
webapp|master ⇒ du -sh .meteor/local/bundler-cache/linker
709M    .meteor/local/bundler-cache/linker

linker|master ⇒ du 4e66b88173386163ea6cd7a6ee945a12f3ab5920.cache
208 4e66b88173386163ea6cd7a6ee945a12f3ab5920.cache

bundler-cache|master ⇒ find linker -type f | wc -l
     619

```
Any idea how to go about debugging this? Seems like it is saving an entire cache of my project in a file hundreds and hundreds of times, and I have a feeling this is why my saves are sooo slow (using coffeescript). Any help or a point in the right direction would be greatly appreciated!
```

**Comment by zol** [comment]
You can just delete the ~/.meteor/local directory and see if it makes a difference to your save speed.

**Comment by avital** [comment]
Yeah, looks like we never delete old cache files and deleting the contents of `.meteor/local/bundler-cache` should reduce the size of this directory. (But don't delete `.meteor/local` -- it contains your database!)

**Comment by dgreensp** [comment]
I just mentioned this problem here: https://github.com/meteor/meteor/blob/release-1.3/tools/PERFORMANCE.md#linker-cache

**Comment by dgreensp** [comment]
Which is to say, yeah, that seems not awesome and something we should look at, especially given the time it sometimes takes to write these files.

**Comment by jeffyamada** [comment]
Yikes, this directory has gotten so large on my project that it's preventing Heroku from successfully building my project. Any ideas for how to prevent it, or what it's related to? Happy to help out if anyone can point me in the right direction.

**Comment by lorensr** [comment]
I'm at 14.6 GB 😄 And 27 GB in `.meteor/local/mirrors`, but looks like that's velocity.

**Comment by dtruel** [comment]
wow, I was at 26gb!  I deleted it, but yes, this definitely needs to be looked at.

**Comment by krishaamer** [comment]
Mine has grown to 3.6 gb over a week

**Comment by danielflippance** [comment]
+1 Mine is 12.7 Gb

**Comment by rjsmith** [comment]
Hi,
Oh , I wish I had seen this ticket earlier .. it would have literally saved me hours when running `meteor test` in an upgraded Meteor 1.2 -> 1.3 project because my project's `bundler-cache/linker` folder was 32Gb in size, so copied into the temporary test app on every invocation!

https://forums.meteor.com/t/solved-1-3-meteor-test-command-gets-stuck-doing-for-20mins/21640/4?u=rsbatech

**Comment by DmitryEfimenko** [comment]
+1

**Comment by anault** [comment]
+1 Can it be turned off? Mine gets over 10Gb within 5 days.

**Comment by hwillson** [comment]
Hi all - this issue has come up again in the [forums](https://forums.meteor.com/t/getting-new-macbook-suggestions/24924/11?u=hwillson), so I'm adding a few findings (hopefully more) to the discussion. 

There doesn't seem to be any code in place to clean up the `bundler-cache` (filesystem) stored files. Every time a file change is made and the changed files are rebuilt, the old cached file stays in place, with the new file being added to the `bundler-cache/linker` directory. Needless to say this is leading to monster `bundler-cache/linker` directory sizes (I routinely climb up to 25 gigs across multiple projects).

Taking a look in [`isobuild/compiler-plugins.js`](https://github.com/meteor/meteor/blob/9897092a7c6472b794420e82e9baf804276fd41e/tools/isobuild/compiler-plugin.js#L1260-L1365), the `cacheKey` is built by hashing several values, one of which is the incoming files content hash (`inputFile.hash`). Since this hash is created based on the incoming file's contents, that means the `cacheKey` created is always going to be different than the previous `cacheKey`, for the same file. So instead of replacing an old version of the file with a new version, it appears as though we're just adding the newly changed file in, while keeping the old one.

I'm wondering if it would instead make sense to change this around a bit. What if we created the `cacheKey` by combining 2 parts. The first part would be enough to represent a specific file in the cache, with the second part being the actual content hash. Something like:

```js
const fileHashes = [];
const cacheKeyPrefix = sha1(JSON.stringify({
  LINKER_CACHE_SALT,
  linkerOptions,
  files: jsResources.map((inputFile) => {
    fileHashes.push(inputFile.hash);
    return {
      installPath: inputFile.installPath,
      sourceMap: !! inputFile.sourceMap,
      mainModule: inputFile.mainModule,
      imported: inputFile.imported,
      lazy: inputFile.lazy,
      bare: inputFile.bare,
    };
  })
}));
const cacheKeySuffix = sha1(JSON.stringify(fileHashes));
const cacheKey = `${cacheKeyPrefix}_${cacheKeySuffix}`;
```

If we did something like this, and created the cached file using this new `cacheKey`, we have a bit more control over what to do when new updates need to be cached for the same file. So when new updates for a file come in, we create the `cacheKey` using this method, then look to see if it exists in the cache. Since it won't (as the 2nd part of the `cacheKey` will be new), just before we add this new file to the cache, we can run some quick cleanup. We would be able to take the first part of the new `cacheKey` and remove any existing cache files that match it. Then when we cache the updated file, we've removed any previously cached instances of the same file. To see this in code, here are some example changes we could make to handle the caching part:

```js
if (canCache) {
  LINKER_CACHE.set(cacheKey, ret);
  if (cacheFilename) {
    const cacheKeySuffixRegex = new RegExp('_' + cacheKeySuffix, 'g');
    const oldCacheFilename =
      cacheFilename.replace(cacheKeySuffixRegex, '_*');
    // Write asynchronously.
    Fiber(() => {
      rimraf(oldCacheFilename, error => {
        // If we can't remove the old file, we'll just continue writing
        // the new file (for now).
      });
      files.writeFileAtomically(cacheFilename, retAsJSON);
    }).run();
  }
}
```

I have a branch working with these (and related) changes, and I've been monitoring the `bundler-cache/linker` dir as I work. The filesystem cache size stays nice and small.

Is this something that might be worth polishing up and firing in as a PR? Pleases let me know what you think, and I'll get something ready.

Thanks!

**Comment by lorensr** [comment]
Thanks hwilson! @platform see last comment

**Comment by hwillson** [comment]
No problem @lorensr - actually, I've been thinking about this a bit more, and I'm wondering if an easier solution to this issue would be to just wipe the bundler-cache whenever the build tool starts for the first time. Sure we'd be adding a small amount of time to each build tool startup, but only at startup, and this would help reduce complexity in `isobuild/compiler-plugins.js`. Anyways, food for thought - I'm happy to fire in a PR for any of this.

**Comment by hectoroso** [comment]
My bundler-cache folder got to over 100GB, so +100 on this.

**Comment by abcd-ca** [comment]
I just saved 117 GB by deleting the bundle cache dirs from my handful meteor projects. Woah.

**Comment by willrbc** [comment]
Linker folder over 45GB here on meteor 1.4 so +45 Gigas from me.

**Comment by hwillson** [comment]
I've just submitted PR #8687 to fix this - feedback/testing welcome!

**Comment by zimme** [comment]
Is this resolved with #8687?

**Comment by hwillson** [comment]
It should be - people might still have to clear out their old cache files to free up space, but the bundler cache should no longer grow indefinitely. Thanks for the reminder @zimme - closing.

**Comment by tomachinz** [comment]
Mine got to 882,544,582 bytes (883.5 MB on disk) for 442 items. :)
