### ISSUE TITLE
Update docs for new modules support in Meteor 1.3

### ISSUE THREAD

**Issue by avital** [meteor/meteor#5821]
Time estimate: 1 day

**Comment by DrDanRyan** [comment]
This would be really nice to have sooner than later. I am very excited for this feature, but would love to have docs before I dive in.

**Comment by tmeasday** [comment]
@avital - what do you envisage doing here?

I have a couple of other tickets that touch on this so I want to make sure I capture everything. What I have is basically:

1. Move modules/README.md into the docs proper (part of #6308)
2. Remove stuff about namespaces etc from the docs (also part of #6308)
3. Update doc boxes to explain where to import things from (#6304)

**Comment by avital** [comment]
@tmeasday Two more things come to mind:
1. There should be a section at the top, like the one on "Writing Packages" about modules or app structure. And that section should appear before the one on packages. (Maybe this also means having a new section at the top about "Using NPM libraries")
2. On the documentation for `Npm.require` it should explain that this is mainly deprecated (other than for binary packages) and that people should use `npm install` instead.

That's all I can think of.

**Comment by tmeasday** [comment]
> 1. There should be a section at the top, like the one on "Writing Packages" about modules or app structure. And that section should appear before the one on packages. (Maybe this also means having a new section at the top about "Using NPM libraries")

There won't be any more sections at the top. We have a whole guide article on app structure and modules however and the top will prominently link to the guide. Also we have another article on "using packages" which includes the npm stuff.

> 2. On the documentation for Npm.require it should explain that this is mainly deprecated (other than for binary packages) and that people should use npm install instead.

Is this true? I don't believe this is the case -- an Atmosphere package should still use `Npm.depends/require` except if there are special requirements around client bundling (e.g. React packages)

**Comment by avital** [comment]
Agreed, linking to the guide is better than writing docs.

I don't see why we'd still want package authors to use `Npm.depends`. My understanding from previous conversations with @stubailo and others is that we definitely want `npm install` to be the new standard way to use NPM libraries.

(Or, you know, really, I think the idea is to transition away from packages and into plain old NPM libraries.)

Maybe this discussion is out of scope for right now but it's something where the vision needs to be made clear.

**Comment by tmeasday** [comment]
> we definitely want npm install to be the new standard way to use NPM libraries

In an app definitely. But for an Atmosphere package which is more than just a wrapper that needs to use NPM, it's not actually that convenient to rely on the user `npm install`-ing something that you don't really have control over. In many cases there's no advantage to not using `Npm.depends()`.

**Comment by tmeasday** [comment]
Closing this issue anyway as I think this stuff is convered elsewhere

**Comment by GeoffreyBooth** [comment]
Hi, I submitted a [pull request](https://github.com/meteor/meteor/pull/6382) explaining how to use modules in CoffeeScript, which I wrote within modules/README.md. Should this text additionally go anywhere else? I think it’s worth being part of the main docs describing modules, or at least a link to it is, so that people don’t think that modules are incompatible with CoffeeScript (or TypeScript, or ES5 for that matter).

**Comment by tmeasday** [comment]
Hey @GeoffreyBooth, thanks very much for this.

It'd be good to reference this in the guide article I suppose: http://guide.meteor.com/v1.3/structure.html#es2015-modules

I'm not sure, we call out to that README there because it has all the details. Can we expect a coffeescript user to follow the link and confirm that CS works, or do we need to call it out more explicitly?

**Comment by GeoffreyBooth** [comment]
The article itself is named “ES2015 Modules,” so as a CoffeeScript user I wouldn’t think to read that article at all—I would just assume that there was no article about how to use modules with CoffeeScript, or I would think that modules are a feature only available to ES2015 users.

I ported the [todos](https://github.com/meteor/todos) app into [todos-coffeescript](https://github.com/geoffreybooth/todos-coffeescript) to test how modules might work in CoffeeScript, and it turns out that they work quite well using old-fashioned CommonJS syntax (excepting [this bug](https://github.com/meteor/meteor/issues/6381) that I filed). Perhaps the article itself should be retitled simply “Modules,” and it can include both ES2015 and CommonJS syntax throughout? (That would make it clear how to use modules in ES5 or Typescript or Iced CoffeeScript or any other funky language that compiles into ES5 JavaScript.) Or the CommonJS syntax, with a CoffeeScript example of CommonJS syntax, could be in its own section somewhere in the Modules article.

This would also make it explicit that Meteor supports CommonJS as a module import/export syntax, which I think it should. That’s what the ES2015 `import`/`export` is getting compiled down to already, so it’s almost no effort on Meteor’s part, other than writing some tests for CommonJS to ensure that changes to the build process in the future don’t break CommonJS support.

I’m happy to help, if you’d like to direct me to a repo/branch/file that I could update.

**Comment by tmeasday** [comment]
I'm unsure about this because the idea of the guide is to provide guidance on what we recommend people do rather than explain all the options in detail. If we litter the article with instances of `require()` then people will be unclear on which they should be using and that's not ideal.

By the way the article is called "Application Structure"---it's just that section which is called "ES2015 Modules"

I think maybe the correct answer here is just to add another section called "CommonJS Modules" and mention some of what you mentioned above "you can use `require()`  -- you may have to in some situations such as..."

If you'd like to make a start you could send a PR to https://github.com/meteor/guide/blob/version-1.3/content/structure.md (`version-1.3` branch). Otherwise I think I should add such a section anyway so I'll get to it at some point.

**Comment by GeoffreyBooth** [comment]
Okay, I think a section on CommonJS modules makes sense then. I know MDG recommends ES2015 now, but I hope the recommendation isn’t so strong that they’re dropping support for other compile-to-JavaScript languages. I would hope that ES2015, CoffeeScript and Typescript are all officially supported just as Blaze, React and Angular are.

Along those lines I would encourage you to keep examples in ES5 whenever possible. I understand that `todos` is meant to be an example of best practices and you consider ES2015 a best practice, but it adds quite a headache to those of us who don’t want to use ES2015 to read example code in ES2015 and have to figure out how to port it to CoffeeScript. The automated JavaScript-to-CoffeeScript website js2.coffee can only handle a subset of ES2015 syntax.

I’ll get started on updating the guide’s structure.md. Are modules getting explained anywhere other than that [readme](https://github.com/meteor/meteor/pull/6382) and in the guide? Is the plan for docs.meteor.com to just link to the guide to explain modules?

**Comment by stubailo** [comment]
I just want to pitch in and say that the overwhelming majority of feedback I've heard from Meteor users is that the best practices are too hard to discover and that the number of options for everything makes it hard to be productive. Whatever we put in our code samples will probably be directly copy-pasted by many thousands of developers, so I don't think we should try to make them overly generic or lowest-common-denominator, but instead strive for shining examples of production-ready code.

Plus, of the two largest (and loudest) JS communities out there (React and Angular) neither is using CoffeeScript. TypeScript, on the other hand, is being adopted heavily by both. I don't think CS is a very future-proof way to be writing JavaScript code at the moment.

Also, note that all ES2015 code is valid TypeScript, so this is strictly a CoffeeScript-specific concern.

Note: I'm not in charge of this and it's totally up to Tom what to do, this is just my opinion.

**Comment by stubailo** [comment]
In retrospect the above was a bit too strongly worded, sorry about that. It should be possible to use whatever language you like, and I'm sure there is a good tradeoff/balance between opinionated guidance and flexibility somewhere.

**Comment by GeoffreyBooth** [comment]
I understand I’m swimming upstream in clinging to CoffeeScript in the face of ES2015, but CoffeeScript has been available in Meteor at least since I started with Meteor back at version 0.5. I can’t be the only one who still prefers it, and I hope Meteor never drops support for it. All I meant was that you shouldn’t use ES2015 syntax where it’s extraneous: don’t convert all the examples in docs.meteor.com to use the shorthand function syntax, or `var` to `let`/`const`, etc. There’s no value to that over the current ES5 examples, and it adds a barrier to entry for anyone using CoffeeScript (or using ES5 who hasn’t learned ES2015 yet or doesn’t want to). The only place where CoffeeScript code samples are necessary would be where you use an ES2015 feature for which the conversion isn’t obvious—modules, and `class`, and that’s probably it.

I kind of agree that maybe the docs is the place for unopinionated facts and the guide can be where opinions come out; but if modules aren’t getting covered in both places, only in the guide, then I guess the guide should include the CommonJS/CoffeeScript syntax for modules in addition to the ES2015 one. There’s nothing wrong with including that and making clear that Meteor recommends ES2015; I don’t think people will be confused. We can name the section “Modules in CoffeeScript” rather than “CommonJS Modules” if you think that would help. Maybe the use case of people preferring vanilla ES5 but who also want modules is too small to warrant documentation for.

**Comment by tmeasday** [comment]
> I’ll get started on updating the guide’s structure.md. Are modules getting explained anywhere other than that readme and in the guide? Is the plan for docs.meteor.com to just link to the guide to explain modules?

The plan is for docs.meteor.com to include the modules/README.md in a section of the main docs, perhaps just above `package.js`. That's why I think it's appropriate as you have done in your PR to explain how to use them in CS there.

 > All I meant was that you shouldn’t use ES2015 syntax where it’s extraneous: don’t convert all the examples in docs.meteor.com to use the shorthand function syntax, or var to let/const, etc

I think as more and more code on the internet is written in ES2015 (this is inevitable), this will be less and less of a problem for people, even if they still use CS. In fact there'll definitely be a time (I won't predict how far off) where ES5 syntax is unfamiliar to most people. For instance the React docs are completely written in ES2015.

I think we want to be ahead of the curve on this one, although I take your point, certainly.

> We can name the section “Modules in CoffeeScript” rather than “CommonJS Modules” if you think that would help. Maybe the use case of people preferring vanilla ES5 but who also want modules is too small to warrant documentation for.

I want to call it something like "CommonJS modules" or "using `require()`" because there are use cases in ES2015 where you can't use `import` also -- principally if you want to require a client or server file from a common file in an `if (Meteor.isClient)` block for instance.

Thanks for calling this out and making effort to document the CS idioms better. I know a lot of people use CS with Meteor and I'm sure they will appreciate your efforts here.

**Comment by GeoffreyBooth** [comment]
Thanks. Okay, so the PR already covers what will go into docs.meteor.com (minus any trimming I assume you might do). The guide version will be mostly the same, though I’ll follow the example of your “ES2015 Modules” section.

We might want to consider making [`todos-coffeescript`](https://github.com/geoffreybooth/todos-coffeescript) into an official example, perhaps only linked-to from the guide. If it were me, I would find it very useful to see a real-world case of how to use modules in CoffeeScript. I’m happy to donate the repo into the `meteor` namespace if you want. At the moment it’s broken because of #6381, but when that’s fixed or I rewrite the code to remove the circular reference (if that’s possible), it can serve as a working demo.

I’m also eager to update it from its upstream parent when you finalize the testing code in the `todos` repo, to see if the tests also pass in the CoffeeScript version. I don’t have time to keep it continually updated against the regular `todos`, but updating it once to add testing would be worthwhile. Then you could use this as a way to test CoffeeScript support in future releases of Meteor: just update the release in `todos-coffeescript` and see if the tests still pass.

**Comment by tmeasday** [comment]
That sounds neat. Maybe you could just commit it as a branch on the main todos repo? I'd be happy to give you access to the repo if you like. I think we are going to do something fairly similar with the current `react` branch; I don't imagine we'll have the bandwidth to actively update it in the same way we may update the `master` (blaze) branch.

**Comment by tmeasday** [comment]
> The guide version will be mostly the same,

I would tend to try to duplicate as little as makes sense to minimize the number of places to keep up to date for this.

**Comment by GeoffreyBooth** [comment]
Yes and yes. Thanks!
