### ISSUE TITLE
Bug: break styles

### ISSUE THREAD

**Issue by JWo1F** [meteor/meteor#5829]
Hi all! I have a very strange bug: when I update styles from a helper they break down.
For example, see http://meteorpad.com/pad/wvtSb4bBpmTrqSnq3/Leaderboard

Click several times on the "click" text and the background disappears. See more in dev tools.

**Comment by tmeasday** [comment]
This is an interesting one. It seems somewhere in the stack the style declarations get re-ordered and because you don't end your styles with a `;`, you end up with an invalid style string. 

I'm not sure if it's Blaze or something in the browser but an easy fix is to ensure you also put a `;` at the end of your style string.
