### ISSUE TITLE
images and fonts from public folder is not loading in android device with meteor 1.2.1

### ISSUE THREAD

**Issue by rakeshashetty** [meteor/meteor#5835]
Hi there, 

We have a template code like the below one. 

````
<template name='home'/>
<div class='header'> 
<div class="brand-name"> 
  <img src='/images/app-logo.png'> </img>
</div>
</div>
</template>

````

We have our app folder structure like below . 
```
app_name/
    client/
    server/
    public/images/app-logo.png 
````

When we checked the adb log ,  we got the generated url for the app-logo.png is  

 meteor.cordova.updater: remapUri http://meteor.local/images/app-logo.png
 meteor.cordova.updater: Remapping to file:///android_asset/www/application/images/app-logo.png

The above generate url failed to load image in our application. 

But when I changed the url to '/app/images/app-logo.png' from '/images/app-logo.png'. 
After changing the url , its work and the below log we got from adb log. 
meteor.cordova.updater: remapUri http://meteor.local/app/images/app-logo.png
meteor.cordova.updater: Remapping to file:///android_asset/www/application/app/images/app-logo.png

Please provide an fix to it. 

Thanks,
Rakesh

**Comment by zol** [comment]
This looks odd, I would be surprised if it was a general problem as many people use the Android Cordova system.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by martijnwalraven** [comment]
Could you try if this is still an issue with the latest Meteor 1.3 beta? https://github.com/meteor/meteor/issues/6266

Closing this issue in the meantime, please reopen it if you feel this needs further discussion.

**Comment by albe-rosado** [comment]
I got the same problem... havent found a solution yet.... :(

**Comment by flake** [comment]
![meteor1 3cordovafileserr](https://cloud.githubusercontent.com/assets/404974/19387907/a9803f00-923a-11e6-99fd-34e47a9d5b2f.png)

I have been working on an app which was developed with Meteor 1.3, the app works fine on web but on android all the files have been accessed from file:/// urls instead of http://BASE_URL. I have attached chrome debugger log for errors I see.

I thought of providing full URLs to image src, than giving relative path "/", and they render images without problem but other files from public folder are still served as file:///. How do I fix this. I cannot update the meteor project to later versions as the project has unmet dependencies.

**Comment by jimfuego** [comment]
I don't know how relevant this is, given the date stamp, but I solved this by just referencing:

`const image_src = '/sammich_platter.JPG';

export default class Catering extends Component {
    render() {
        return(
            <div>
                <h1>Catering</h1>
                <img src={image_src} alt={"plate of sandwiches"} />
            </div>
        );
    }
}`

The public folder in Meteor makes images available for simple reference, as shown.
