### ISSUE TITLE
[idea] [1.3-modules-beta.2] "meteor" package to import meteor stuff from.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5895]
I think it'd be nice if there was a `meteor` package to import things from, f.e.

```js
import { Tracker, Session /* , etc */ } from 'Meteor'
console.log(Tracker) // it works
```

Along with that, allow no globals in module code, f.e.

```js
import $ from 'jquery'
console.log(Tracker) // We should expect "Error: Tracker is undefined" because it isn't imported!
```

**Comment by rozzzly** [comment]
+1 makes it real easy to switch over, lets you see exactly where globals are still being referenced.

possible alternate syntax:
`import Tracker from 'meteor/tracker'`

**Comment by stubailo** [comment]
@rozzzly I think we're going with your idea, and possibly for all atmosphere packages to avoid collisions with NPM. I can't find any threads where @benjamn has talked about it (there are so many for 1.3 now)

@trusktr I think your syntax will make it difficult to identify which modules are actually being used and avoid loading the ones that aren't, since it will just compile down to `require('meteor')` at the end.

**Comment by trusktr** [comment]
@stubailo 

> possibly for all atmosphere packages to avoid collisions with NPM

```js
import something from 'some:package/foo'
```

where `some:package` is from Atmosphere?

> I think your syntax will make it difficult to identify which modules are actually being used

Yeah, I like the `default` export option and separating things into separate files better.
