### ISSUE TITLE
Can't expand/collapse any tree-view objects on debug popups

### ISSUE THREAD

**Issue by jirikrepl** [meteor/meteor#5901]
Hi, when I want to debug with ```meteor debug``` And open the node-inspector. Then I cannot open any tree-view on objects in debug section.

In node-inspector it should be fixed in 0.10.0, which is referenced here: https://github.com/node-inspector/node-inspector/issues/584

I tried to look which version of node-inspector (and where) is included in Meteor, but without success.

Env:
Clean meteor project 1.2.1
Windows 8.1
Chrome Version 47.0.2526.106 m

I tried Firefox 43.0.3. It is totally broken

Am I missing someting?

![untitled](https://cloud.githubusercontent.com/assets/2588479/12033911/b0b4541e-ae29-11e5-9c80-1f6e9caa7d3b.png)

**Comment by rdickert** [comment]
It looks like [meteor debug is running a version 0.7.4](https://github.com/meteor/meteor/blob/e0163ff28e1a6aed4a2f73edf69c60a0d0931d24/scripts/dev-bundle-tool-package.js#L43), which would explain the problem (which I also was able to reproduce). There may be a workaround by using a newer version of node-inspector via `npm install -g node-inspector`, then running `NODE_OPTIONS='--debug' meteor` and running 'node-inspector` in a new tab. This did not work on my first attempt - apparently because that version may be too *new* for Meteor's current version of node - but further effort might uncover a way to make this work.

**Comment by timbotnik** [comment]
@jirikrepl, perhaps you can try running node-inspector manually, since you can install whatever version you want:

1. Install node-inspector: `npm install -g node-inspector[@version]`
2. Start meteor: `NODE_OPTIONS='--debug' meteor run`
3. Start node-inspector in another shell: `node-inspector`
4. In Chrome, go to the URL given by node-inspector
