### ISSUE TITLE
multi: true is not working on the server

### ISSUE THREAD

**Issue by pdiniz13** [meteor/meteor#5945]
Updating multiple collections by using {multi: true} is not working https://docs.mongodb.org/manual/reference/method/db.collection.update/#multi-parameter. I am currently having to use a find with a foreach and manually updating the documents one by one. I understand the security issues with regards to using multi from the client, but there's no reason to block it on the server.

collection.update({}, {}, {multi: true})

**Comment by picco** [comment]
confirmed, ran into the same issue

**Comment by aliogaili** [comment]
I seem to be running into the same problem, is this resolved?

**Comment by Nullpo** [comment]
+1

**Comment by aliogaili** [comment]
@Nullpo I'm also seeing this issue on my production code, but I'm unable to reproduce it on a simpler code base. You can see my attempt [here](https://github.com/aliogaili/multi-param-issue). 

Can you please try reproducing it as well? if not, then I think I'll have to close issue [9177](https://github.com/meteor/meteor/issues/9177) because it can't be reproduced.

**Comment by Nullpo** [comment]
Finally we solved this with a find -> map -> update. This weekend I will try to reproduce this in a simpler code.

Thanks!

**Comment by aliogaili** [comment]
Yeah, we used the same workaround, but I think it'll be great if you could reproduce it and report [here](https://github.com/meteor/meteor/issues/9177), so others won't have to go through this if indeed there is an issue :)

Thank you

**Comment by Alameli** [comment]
Possible solution for those with the issue:

https://github.com/meteor/meteor/issues/9177#issuecomment-388120503
