### ISSUE TITLE
[1.3-modules] Isomorphic module exports and imports

### ISSUE THREAD

**Issue by Sanjo** [meteor/meteor#5970]
``` gherkin
Feature: Isomorphic module imports

In order to write isomorphic code
as a Meteor app developer
I want to import other isomorphic modules

Background:
  Given there is a module "./myModule" that has exports with different implementations for client and server

Scenario: Import isomorphic module on the client
  When I import "./myModule" on the client
  Then the client implementation should be used

Scenario: Import isomorphic module on the server
  When I import "./myModule" on the server
  Then the server implementation should be used

# The same for all other supported platforms. E.g. Cordova.
```

With Meteor packages there is a way to specify, for what platform a file is via: `api.addFiles(..., 'server')` for example. Such a feature is also required for ES2015 modules, to write isomorphic code. Currently you need to use the client and server folder convention. So your isomporphic module structure would look like that:
- myModule
  - server
    - index.js
  - client
    - index.js

In my current project I also have a universal entry point myModule/index.js with the code:

```
const module = require(Meteor.isServer ?
  './server/index' :
  './client/index'
);

export default module.default;
export const {Export1, Export2} = module;
```

This file basically implements a dynamic export based on the current platform. That's something Meteor could do under the hood.

**Comment by benjamn** [comment]
For another approach (no preference intended), here's the browserify way of specifying different entry points for the browser: https://github.com/substack/node-browserify#browser-field

**Comment by trusktr** [comment]
> if you import myModule from 'my-module', on the client side it would require myModule/client. And on the server side it would require myModule/server

I like this idea. This could work with NPM or Meteor packages as well as with app code. I think the module system could look for these in this loose order: `myModule/{client,server}.js` depending on architecture, `myModule/{client,server}/index.js` depending on architecture, `myModule.{client,server}.js` depending on architecture, then `myModule/index.js` or `myModule.js` as is currently.

**Comment by hwillson** [comment]
Since feature requests are no longer managed in the repository, this issue will be closed. It shouldn't be necessary to migrate this issue to [meteor/meteor-feature-requests](https://github.com/meteor/meteor-feature-requests) as the solution that is put in place to remove the need for an `imports` directory (see https://github.com/meteor/meteor-feature-requests/issues/135 and https://github.com/meteor/meteor/issues/8341), will address this feature request as well. It should be noted that removing the need for an `imports` directory was recently added to the [Meteor Roadmap](https://github.com/meteor/meteor/blob/devel/Roadmap.md#get-rid-of-the-imports-directory), so more details will be coming soon. Thanks!
