### ISSUE TITLE
[Bug] ECMAScript package

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#5971]
```js
var {resp, body} = {resp: 'test', body: 'test'};
```

Works fine, however this below doesn't:
```js
{resp, body} = {resp: 'test', body: 'test'};
```

I get the following error:
> Unexpected token

I am trying to set the variables ```resp``` and ```body``` to the equivalent as in previous case, however this time the variables already exist. Is this a bug or am i missing something?

I am currently on Meteor 1.2 and the ecmascript package is versioned at ```0.1.6```

**Comment by yokujin** [comment]
In ES2015 code blocks begin with a curly brace and you are writing statement not code block so it must not start with curly brace.

Workaround:
```ecmascript
({resp, body}) = {resp: 'test', body: 'test'};
```
or
```ecmascript
({resp, body} = {resp: 'test', body: 'test'});
```

**Comment by talha-asad** [comment]
Will this be like this when they are officially part of the browser? I think the equality operator should decide on what is happening. But thanks for the work around.

**Comment by talha-asad** [comment]
```js
({resp, body}) = {resp: 'test', body: 'test'};
```

Doesn't work but the other one does.

**Comment by yokujin** [comment]
Strange but possible.

I always use the latter.

**Comment by vhf** [comment]
> Will this be like this when they are officially part of the browser?

Yes. It's part of the ES2015 standard.

**Comment by talha-asad** [comment]
ES2015 is already obsolete, more like ES2016 :)

I think the browsers will be looking at the equality sign rather than parsing it as a block when a line starts with a ```{```. It would make more sense that way anyway. I think this might be a bug in babel, i am not sure if ecma uses that to transpile code though.

**Comment by vhf** [comment]
ES2015 has not been fully implemented in any JS engine yet and is definitely not obsolete. ES2016 is at an early planning stage, nobody knows what will end up being supported by ES2016.

Meteor 1.2.x uses Babel 5.8.24, which is outdated and has several bugs.

According to the ES2015 standard, `{resp, body} = {resp: 'test', body: 'test'};` is [not a valid syntax](http://vhf.github.io/blog/2015/10/28/es6-destructuring/) because [a bare object object is not valid syntax](http://stackoverflow.com/questions/17382024/why-is-a-bare-array-valid-javascript-syntax-but-not-a-bare-object). The equality sign does not matter. Therefore, JS engines won't support this syntax. Simply use the syntax provided by @yokujin.

**Comment by talha-asad** [comment]
Thanks for all the info. Makes sense.
