### ISSUE TITLE
Standalone master oplog tailing fails

### ISSUE THREAD

**Issue by JesperWe** [meteor/meteor#6015]
***3 Upvotes*** Referring to https://forums.meteor.com/t/why-does-my-meteor-refuse-to-activate-oplog-tailing/15245

A correctly setup MongoDB master with oplog tailing operational still fails to start with:

    W20151220-13:20:33.835(0)? (STDERR) Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set

Probably due to `oplog_tailing.js:214`
I see no reason to not support this configuration, it should still be more performant than polling even if the master/replica is a single Mongo instance.

**Comment by aleixmorgadas** [comment]
+1

**Comment by potnox** [comment]
+1

**Comment by skaag** [comment]
+1

**Comment by abernix** [comment]
I'm able to reproduce this error message, but only with an improperly setup replica set (i.e. destroying my `local` db).  The oplog is a concept of Mongo replication; oplogging requires a replica set.  [Read about the oplog here](https://docs.mongodb.com/manual/core/replica-set-oplog/) (in the replication docs) and the [procedure for setting up a replica-set](https://docs.mongodb.com/manual/tutorial/deploy-replica-set/#procedure).

You are getting this because you do not have a `local` DB setup.  If you do not have a `local` DB, then you do not have a replica set – [`local` is where Mongo keeps it's replication info](https://docs.mongodb.com/manual/reference/local-database/), including the `oplog.rs` collection which is the _actual_ oplog.

You need to:

* Start your mongo server with replSet enabled (this only identifies your server as a member of set).  Either:
 * `mongod --replSet "rs0"`; **or**
 * In `mongod.conf` with:
`replication:\n  replSetName: rs0`

* Initiate your replica set – which creates the oplog:

        mongo admin --eval 'rs.initiate()'

You do not need to have secondary servers setup, but you do need to have your server setup as a replication primary so it will generate the oplog that Meteor needs to follow.  Otherwise, Meteor has nothing to work with.

The only thing I might propose is that the error message be changed to say:
```
MONGO_OPLOG_URL must point to the 'local' database of a Mongo DB with a replica set enabled.
```

**Comment by abernix** [comment]
I'll leave this open for some discussion and +1's on the message change, but this can probably be closed.

**Comment by JesperWe** [comment]
> You are getting this because you do not have a local DB setup

It appears like you have not looked at the details from my original forum post. If you look there, you will see that the replica is correctly set up (There is a transcript from connecting to the `local` database, and it shows the `oplog` collection.)

I understand that oplog requires a replica. The issue is about allowing **a single** Mongo instance with master and replica **in the same instance** (which is a perfectly valid setup) to be supported. Otherwise you have to install a multi-node cluster just to switch from polling to oplog tailing.

**Comment by abernix** [comment]
@JesperWe I did read your issue.  I am using the same single-instance setup you have described.  You did not include any settings from your `mongod.conf` though, and you did not otherwise indicate how you start your `mongod`.   However, your prompt from the original post does not show: `rs0:PRIMARY> ` (or another replicaset name), but instead it shows just ` >` which indicates that it is **not** a member of the replica set and therefore will not have oplog to follow.  The mere presence of the `oplog.*` collection does not mean it is being used.

**Comment by abernix** [comment]
Just to demonstrate that this works when oplog is setup properly here is a fresh setup, step by step on OS X 10.11.4.

##### No Mongo Installed (Just proving it's not installed)
```bash
jesse@monty:~/Dev$ ls -la /usr/local/etc/mongod.conf
ls: /usr/local/etc/mongod.conf: No such file or directory
jesse@monty:~/Dev$ mongo
-bash: /usr/local/bin/mongo: No such file or directory
```

##### Install Mongo
```bash
jesse@monty:~/Dev$ brew install mongo
==> Downloading https://homebrew.bintray.com/bottles/mongodb-3.2.4.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mongodb-3.2.4.el_capitan.bottle.tar.gz
==> Pouring mongodb-3.2.4.el_capitan.bottle.tar.gz
==> Caveats
To load mongodb:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
Or, if you don't want/need launchctl, you can just run:
  mongod --config /usr/local/etc/mongod.conf
==> Summary
🍺  /usr/local/Cellar/mongodb/3.2.4: 17 files, 208.7M
```

##### Configure IP Address and Replication Set Name Before Startup
```bash
# Change IP: By default it's only 127.0.0.1, which doesn't work in my case.
jesse@monty:~/Dev$ perl -pi -e "s/^  bindIp: 127\.0\.0\.1/  bindIp: 0.0.0.0/" /usr/local/etc/mongod.conf
# Define Replication Set Name: Using 'rs0' here
jesse@monty:~/Dev$ printf "replication:\n  replSetName: rs0" >> /usr/local/etc/mongod.conf
```

##### Start Mongo
```bash
jesse@monty:~/Dev$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
```

##### Initiate Replica Set
```bash
jesse@monty:~/Dev$ mongo admin --eval 'rs.initiate()'
MongoDB shell version: 3.2.4
connecting to: admin
{
  "info2" : "no configuration specified. Using a default configuration for the set",
  "me" : "monty.local:27017",
  "ok" : 1
}
```

##### Create User with Access to Replica Set
```bash
jesse@monty:~/Dev$ mongo admin --eval 'db.createUser({user: "oplogger", pwd: "PasswordForOplogger", roles: [{role: "read", db: "local"}]})'
MongoDB shell version: 3.2.4
connecting to: admin
Successfully added user: {
  "user" : "oplogger",
  "roles" : [
    {
      "role" : "read",
      "db" : "local"
    }
  ]
}
```

##### Start Meteor App Using Replica Set
(I added `--production` since you indicated you were using that in the forums post, but it doesn't matter here)
```bash
jesse@monty:~/Dev$ cd envdumper/
jesse@monty:~/Dev/envdumper (master)$ MONGO_URL=mongodb://localhost:27017/envdumper MONGO_OPLOG_URL=mongodb://oplogger:PasswordForOplogger@localhost:27017/local?authSource=admin meteor -p 3800 --production
[[[[[ ~/Dev/envdumper ]]]]]                   

=> Started proxy.                             
=> Started your app.                          

=> App running at: http://localhost:3800/
```

##### Showing Replica Set In Use (`oplog` driver – nothing showing as `polling`)
![screen shot 2016-05-19 at 1 26 56 pm](https://cloud.githubusercontent.com/assets/841294/15390622/621b7484-1dc5-11e6-8972-ef32c9f54ab1.png)

All Good ✅

**Comment by abernix** [comment]
I believe this issue was due to a misconfiguration.  Happy to discuss further, however this setup is proven to work as I demonstrated.

**Comment by anormore** [comment]
Hi, I've been researching this issue for literally 2 weeks. Finally come down to OpLog - whatever that means.

My Meteor application is returning 20,000 documents. I think it's because OpLog isn't running? I certainly haven't configured it. I'm running a Google Cloud Compute MongoDB instance.... Here's a snapshot of Kadira, would you say this is the issue, and that this thread is relateable?

![image](https://cloud.githubusercontent.com/assets/28155233/26022555/70762c56-3776-11e7-81ae-0f6bd8c4bae5.png)
