### ISSUE TITLE
ES6 Template instance problem 

### ISSUE THREAD

**Issue by d62remi** [meteor/meteor#6018]
if I use `()=>` instead `function()` a problem occurs when I try to access my ReactiveVar in the helpers.

This code is bad :
```javascript
Template.foo.onCreated(()=>{
   this.bar = new ReactiveVar('huhu');
});

Template.foo.helpers({
   myHelper(){
      return Template.instance().bar.get();
   }
});
```
This error occurs ...
```
Exception in template helper: TypeError: Cannot read property 'get' of undefined
```

This code is good :
```javascript
Template.foo.onCreated(function(){
   this.bar = new ReactiveVar('huhu');
});

Template.foo.helpers({
   myHelper(){
      return Template.instance().bar.get();
   }
});
```

However it works :
```javascript
Template.foo.onCreated(()=>{
   Template.instance().bar = new ReactiveVar('huhu');
});

Template.foo.helpers({
   myHelper(){
      return Template.instance().bar.get();
   }
});
```

idem for template events ...

**Comment by stubailo** [comment]
The `function () { ... }` way of declaring functions is not the same as arrow functions `() => { }`. They intentionally work differently in ES2015, specifically in the case of `this`. So when you are declaring `onRendered`, `onDestroyed`, and `onCreated` callbacks, please use the `function` keyword.

You can't just replace all occurences of function declarations with arrow functions, since they do different things.

**Comment by d62remi** [comment]
Ok thank you for information ;-)
