### ISSUE TITLE
[request] Support ARM for development.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6033]
I just tried installing Meteor on Linux (Android) on ARM, and got

```
$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0  100  6674    0  6674    0     0   6574  100  6674    0  6674    0     0   6550      0 --:--:--  0:00:01 --:--:--  8839
Unusable architecture: armv8l
Meteor only supports i686 and x86_64 for now.
```

I'd like to develop locally on my Android phone (good for when mobile and pulling out a laptop is toouch or I simply just don't have my laptop). :D

**Comment by stubailo** [comment]
I think supporting a different architecture would be a very big deal - for example, the Windows project took many months to complete, and was only done because it was the number one request for Meteor and unlocked 30% or more additional users for the platform. We would need a lot of consensus and desire to consider supporting Meteor on Android.

**Comment by trusktr** [comment]
Android is just Linux on ARM, so at least the effort might not be as
difficult as for Windows. We probably just need to supply the ARM build of
Node (and Fibers, etc) and it'll just work.

/#!/JoePea

**Comment by stubailo** [comment]
Yes, but then we need to test every release on Android, etc.

**Comment by trusktr** [comment]
I gave it a shot:

1. I installed `Termux` for Android (it installs an `apt-get` system in it's app-container).
1. I modified the script from [install.meteor.com](http://install.meteor.com) to simply not `exit 1` when it detects something other than Linux or Darwin.
1. set `PLATFORM` to the same as the Linux case.

That successfully installed Meteor.

I did `export PATH=$PATH:$HOME/.meteor`, then modified `~/.meteor/meteor` so that it too would not `exit 1` and set `PLATFORM` to the same as the Linux case. At that point, the `meteor` command would run, but would fail when trying to execute the bundled x86_64 `node` bin. So, I ran `npm install -g node` then copied over the binary into `~/.meteor` and got past the error, but then I came across the same error for `Fibers`.

I guess I can probably run `npm install -g` for everything, and replace all the binaries in `~/.meteor` with the ARM ones, and it'll probably work, but I didn't have time to try that yet.

**Comment by stubailo** [comment]
You can run the generate dev bundle script from `scripts/admin`, perhaps that will be easier! Then you just have to replace `dev_bundle` in the installation directory. Excited to see if it works.

**Comment by trusktr** [comment]
Thanks for the hint! I'm dying to get this working, but I think the following might be a road block, unless I can just host Mongo remotely: https://jira.mongodb.org/browse/SERVER-1811

**Comment by stubailo** [comment]
Ooh, that sure would be a blocker. Use Minimongo on the server? :P

And yeah you could definitely host development mongo remotely. It will make your app pretty slow, though.

**Comment by trusktr** [comment]
> Minimongo on the server

If that works, I'd be down for it! How might I start on that path? Does minimongo work outside the browser?

Someone in that Mongo JIRA issue mentioned that I might be able to run a Dockerized version of Mongo on ARM.

**Comment by appinteractive** [comment]
there is an ARM ("Universal") Fork of meteor: http://meteor-universal.tumblr.com/. But I also think it should be part of Meteor itself. There are quite some nice use cases for embedded systems (IOT) with Meteor!

**Comment by TomFreudenberg** [comment]
Hi Joseph ( @trusktr )

I do and support the meteor on ARM fork for long time now and we got a number of devices "meteor enabled" with it.

You may like the discussion on forums.meteor.com at https://forums.meteor.com/t/amazing-use-android-phone-or-tablet-as-meteor-server/13007

Beneath the tumblr blog, there are a number of hints on github at https://github.com/4commerce-technologies-AG/meteor

Looking forward to more discussions.

Cheers
Tom

@appinteractive (Grzegorz) thanks for your recommendation

P.S. Hopefully our work on that fork will come into the core sometime.

**Comment by faddat** [comment]
This may seem like it is coming out of left field, but I'm okay with that, because when it hits the right ears, it'll be well understood.  There's a lot of stuff out there that *should* be omniplatform, and in my mind it isn't far off, but requires a bit of a tweak.  Basically today we've got Dockerfiles and these usually (but not always) specify a recipie for building an application.  It's the build part that I want to concentrate on here, because that seems to be the hairiest part.  

We've got an omniplatform os, Debian or Arch.  So next, imagine a docker-compose file that contains the Dockerfiles of all of the things to be composed.   If the two OSes are actually the same what you should now have is a docker-compose that can work anywhere docker runs.  Because we've got LowRISC coming sooner than later, I think a solution like this makes a lot of sense.  The architecture for this special file could be detected from the environment, and it should-- just work.

**Comment by trusktr** [comment]
@TomFreudenberg 

Hi Tom, that is cool! I'm replying back in that Meteor forum thread.

**Comment by davidbilly** [comment]
@stubailo , Have any chance meteor will be support Android/IOS native SDK? 

Planning write an app with native code without using Webview. Sorry for asking question at wrong place ;(

Thanks :D

**Comment by stubailo** [comment]
@davidbilly please open a new issue or post on the forums, if I answer here it will be lost forever and nobody will be able to find it.

**Comment by TomFreudenberg** [comment]
@davidbilly please drop your comment - it will misslead anybody when searching for "native SDK" or similar.

Thanks
Tom

@stubailo - I am wondering that this issue is still marked as open. Isn't it equal to #442 ?

@Anyone - If you like please send in your ideas on "ARM" at our fork

**Comment by davidbilly** [comment]
@stubailo  @TomFreudenberg  : Sorry about this, i will create new issue :D

**Comment by trusktr** [comment]
Hello All, [Mongo for ARM](https://jira.mongodb.org/plugins/servlet/mobile#issue/SERVER-1811/comment/1365439) is officially complete! We're one nice step closer...

**Comment by cyclops24** [comment]
MDG please add ARM support officially. I really like to write Meteor application on my Raspberry pi.

**Comment by hwillson** [comment]
Hi @cyclops24 - please show your support for this feature request by adding a 👍 to the original comment. Adding/supporting an additional architecture is not a trivial amount of work, so there will definitely need to be strong support for this decision (see @stubailo's https://github.com/meteor/meteor/issues/6033#issuecomment-173013136 about this above).

In the meantime, while not officially supported (and currently at Meteor 1.3.4), have you tried https://github.com/4commerce-technologies-AG/meteor? It has been successfully tested/verified on a Raspberry Pi.

**Comment by abernix** [comment]
@cyclops24 While I understand what you said, just to make a clear differentiation for others who might be arriving at this issue: **developing** on a Raspberry Pi and deploying to it are different things.  Deploying to it will already work fine since it's just a `node` project once you build it with `meteor build`.

My biggest concern before going down the *developing* path would be whether the CPU performance (file-watchers, [presumably] network file saves between changes, etc.) would be even remotely reasonable or worth the endeavor.

**Comment by TomFreudenberg** [comment]
Hi @cyclops24 @hwillson 

Maybe you have seen the 1.4.x issue on meteor-universal - I will update the pre-build binaries during weekend.

@abernix  You may also need to **build** on arm architectures because some packages / node_modules will need to compile binaries. Some of the packages like bcrypt are not possible to install from atmosphere but you need to build them on target architecture. Also if you need to access hardware elements it is an important feature to be able to develop directly on the target.

Cheers
Tom

P.S.: Again @stubailo @n1mmy - still wondering that this issue is marked as open. Isn't it equal to #442 ?

**Comment by hwillson** [comment]
Thanks for the update @TomFreudenberg. 

As to why this issue is still open when related issue #442 was closed - issue #442 is quite old now, and was closed in 2012. At the time MDG had no immediate plans for adding official ARM support, so the issue was closed. The discussion continued on that issue for quite some time, but the issue has remained closed ever since. This related issue was marked as a feature request and left open. It is now the only open ARM related issue in the repo, so people are logically adding new ARM related comments to it.

Since this is a feature request it will be left open for now, but if you think anything should be handled differently, please share your advice. Thanks - and by the way - thanks for all of your work on the Meteor universal fork!

**Comment by abernix** [comment]
@TomFreudenberg Node/Node-gyp will rebuild any dependencies it needs (like `bcrypt` on the ARM arch when you `npm install`, so long as you have a compiler toolchain installed on the ARM arch.  This works the same as (for example) when MUP users right now `meteor build` on a Mac but deploy to their Ubuntu servers – it files up the re-compilation on launch.

**Comment by TomFreudenberg** [comment]
@abernix Jesse, thanks, will have a look on that ... 

Still you need access to the hardware when trying to control things like steppers, motors, shields etc.

**Comment by cyclops24** [comment]
@hwillson Thanks for your reply. It (Universal Fork) seems good but a little old. (1.3.4) and I thinks it's better to release it as Meteor core feature. It's very interesting if you can code with your favourite framework on a cheep $25 raspberry pie or android devices.

@abernix Yes you say right thing. I want **developing** on ARM based system.

@TomFreudenberg Your work is awesome man. I'm waiting for 1.4.x brother.

MDG Pleeeeeeeeeeeese use @TomFreudenberg approach and release official ARM support. MongoDB also release ARM version. I guess it's time to extent community more and add many new use case to Meteor ecosystem.

Thanks for your attention guys.

**Comment by trusktr** [comment]
Yes please MDG, I would really love to continue working on my android phone
while sitting on the loo, or in any other places where I may find myself
without laptop.

**Comment by trusktr** [comment]
@TomFreudenberg Any chance you can release a script that will install Meteor inside Termux for Android? I am happy if it only works with ARM 64, and 32 bit can connect with remote mongo if that makes it easier. What do you require to make that happen? I can make a donation.

**Comment by trusktr** [comment]
The only thing stopping (as in my original posts) was that Meteor install script downloads wrong architecture stuff when ignoring the platform checks. It should theoretically work perfectly in ARM64, with just changes to install script. Maybe I'll give it a shot if I can find time.

**Comment by trusktr** [comment]
I mean, it should theoretically work considering Mongo for ARM64 is out.

**Comment by TomFreudenberg** [comment]
@trusktr Hi Joseph

I will find the time starting next week ... please follow up at https://github.com/4commerce-technologies-AG/meteor/issues/36

On what device are you running Termux?

Cheers
Tom

**Comment by apatryda** [comment]
It would be really nice to be able to develop Meteor projects for ARM. Not only for Android's sake, but also IoT and embedded solutions. There are also some servers which I cannot use for deployment because of this limitation (i.e. Scaleway's baremetal ARM servers).

@trusktr What is the status of your efforts? If there is help needed - I can spare some time.

**Comment by TomFreudenberg** [comment]
Hi Artur @apatryda 

We are already using scaleway baremtals with our meteor arm fork. Works nice and performant.

Cheers
Tom

**Comment by apatryda** [comment]
@TomFreudenberg - Hi Tom,
But isn't your fork limited to 1.3.x version?

**Comment by TomFreudenberg** [comment]
As stable yes - 1.4 is fine on beta but without mongodb - We are still doing that packaging for arm64. I will post some updates when ready.

**Comment by TomFreudenberg** [comment]
@apatryda Which realease you are looking for?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Brequest%5D%20Support%20ARM%20for%20development.&body=Migrated%20from:%20meteor/meteor%236033) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
