### ISSUE TITLE
Remove hot-code-push from meteor-base

### ISSUE THREAD

**Issue by pradel** [meteor/meteor#6038]
Remove hot-code-push from meteor-base package. @stubailo

**Comment by stubailo** [comment]
So one would remove this when:

1. They don't want their app to reload in development (seems unlikely?)
1. They don't want their Cordova app to hot code push in production
1. They don't want their web application to hot code push in production

Should we somehow have separate controls for those three situations? Which one were you interested in in particular?

**Comment by pradel** [comment]
I am interested in 2 and 3, I want to be able to disable it in production mode.

**Comment by pradel** [comment]
Maybe we can set an option on meteor startup like `Meteor.hotCodePush(true|false)`like that users will be able to implement their own logic.

**Comment by abernix** [comment]
I'm going to close this since you're asking to fine-tune the reloading and from what I understand, https://github.com/jamielob/reloader/ will provide you that functionality.  Removing this for everyone certainly wouldn't be an option.

Additionally, in case it's still of interest to you, if you look at the [source for `meteor-base`](https://github.com/meteor/meteor/blob/devel/packages/meteor-base/package.js#L15) you'll see it's just a umbrella package consisting of other packages.    You can simply explicitly list those packages, but omit `hot-code-push` from that if you'd like.  For example, add these to your `.meteor/packages` instead of `meteor-base`:

```
meteor
webapp
underscore
ddp
livedata
```

Thanks for bringing this up originally!
