### ISSUE TITLE
Difference in behavior between client/compatibility in 1.2.1 and 1.3 beta

### ISSUE THREAD

**Issue by ndarilek** [meteor/meteor#6047]
I'm building a Meteor app using the Janus web RTC gateway, and unfortunately janus.js isn't built with many modern coding standards in mind. The only way I've gotten it to work is to add it to client/compatibility, where the Janus global gets defined.

Unfortunately, this no longer works in Meteor 1.3. client/compatibility/adapter.js seems to load, but janus.js doesn't seem to define the Janus global as it did in 1.2.1.

See [this test app](https://github.com/ndarilek/meteor-compatibility-test) as an example. When the app loads, `Janus` should be defined in the browser console but isn't.

Thanks.

**Comment by avital** [comment]
@ndarilek Yes, we've confirmed that this is a bug.

**Comment by benjamn** [comment]
Here's the code that should be implementing this logic: https://github.com/meteor/meteor/blob/3f3aac4fd1859d4c13ad432b5ad0b4ff0059d0ad/tools/isobuild/package-source.js#L1324-L1336

And here's a basic test: https://github.com/meteor/meteor/commit/877cb9e61ae8bcf6312c6cec05bc943560770118

Looking at your code, I believe the problem is that bare files don't have access to `require`.
