### ISSUE TITLE
Inline SVGs don't render when their content is from a blaze helper

### ISSUE THREAD

**Issue by mglidden** [meteor/meteor#6048]
Repro case: https://github.com/mglidden/svg-bug

When creating an inline SVG from a meteor helper (i.e. `<svg>{{{svg}}}</svg>`) the SVG doesn't render. Getting the entire SVG element from a helper (instead of just the inner section) works properly. Copying the generated HTML code into a new page renders them properly. 

I've tested this on Chrome 47 & 50, Firefox 43, and Safari 9 (all on OS X 10.10).

**Comment by avital** [comment]
Thanks for the bug report.

`{{{ ... }}}` is implemented via jQuery's `parseHTML` function, and then appends the parsed contents to the SVG wrapper element.

Now check out this Fiddle: https://jsfiddle.net/tzo3r0gL/1/. It uses `parseHTML` to get a SVG `circle` element that is then appended into the wrapper `<svg>` component. You'll see that the circle doesn't appear. This is because SVG elements must be created with `document.createElementNS` rather than `document.createElement`.

Not sure what the fix is. Maybe use something other than jQuery to parse the contents of `{{{ }}}`? FWIW in general this isn't even really solvable because some tags are used both in HTML and SVG but have different meanings, such as `<a>`. So what should `{{{ }}}` do in that case -- generate an SVG element or an HTML element?

Theoretically you could work your way up the DOM tree to find a potential first wrapper SVG component but that would be very slow.

**Comment by hwillson** [comment]
Closing as this is a jQuery issue; not a Meteor/Blaze issue. Thanks!
