### ISSUE TITLE
inconsistent minimongo insertion

### ISSUE THREAD

**Issue by peonmodel** [meteor/meteor#6051]
minimongo has inconsistent behaviour with regards to undefined

depending on where the collection is inserted, {a: undefined} will become {} or {a: undefined} or {a:null}

```

if(Meteor.isClient){
  Test = new Mongo.Collection(null); // local client collection
  Test.insert({_id: 'client-side-local', a: undefined});
  var R = Test.findOne('client-side-local');
  console.log(R);  //  returns {_id: 'client-side-local', a: undefined}  // key 'a' is unchanged
}
Test2 = new Mongo.Collection('non-local'); // non-local collection
Test2.insert({_id: 'client'+Meteor.isClient, a: undefined});  // insert in both client and server side

var R1 = Test2.findOne('clienttrue');
console.log(R1);  //  returns {_id: 'clienttrue'}  // key 'a' is deleted due to stringify()
var R2 = Test2.findOne('clientfalse');
console.log(R2);  // returns {_id: 'clientfalse', a: null}  // key 'a' value undefined is changed to null
```

shouldn't the local collection consistently delete keys with undefined as value just like how the object will be stringify when sent over the wire

local collection already replace File objects into empty object, just like what one expect from stringify, but not for undefined
e.g.

```
//Client-side
TTT = new Mongo.Collection(null);
var obj = {
  file: new File([1, 2, 3, 4, 5], "name of file.xyz", {
    type: 'text/xyz'
  }),
  undef: undefined,
}
TTT.insert(obj);
TTT.findOne()  // returns {file: {}, undef: undefined};
nobj = EJSON.stringify(obj)  // returns "{"file":{}}"
EJSON.parse(nobj)  // returns {file:{}}
```

**Comment by timbotnik** [comment]
Seems like consistency would be the preferred strategy here.

**Comment by peonmodel** [comment]
i realised that this issue may be related to this: https://github.com/meteor/meteor/issues/5301
it appears that the deletion of undefined keys causes the server to interpret the selector as "{}" which it then returns everything

**Comment by hwillson** [comment]
This is still happening with the latest version of Meteor (1.5.1 as of today). I've created a reproduction here: https://github.com/hwillson/meteor-issue-6051

`undefined` is not valid JSON, so it's being stripped via EJSON when passed from the client to the server. It's definitely inconsistent to see `undefined` converted to `null` (and saved) when the insert happens on the server. This is happening because Mongo's BSON spec doesn't support `undefined`, so the Mongo node driver is converting `undefined` to `null`, just before saving. We should probably adjust things on the server side to make sure `undefined` values are stripped instead of being converted to `null` and inserted.
