### ISSUE TITLE
Enable ES2016 @decorator syntax

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#6057]
This will be important for Angular2 support (without forking the `ecmascript` and `babel-compiler` packages).

**Comment by benjamn** [comment]
Unfortunately (though I think wisely) `babel-plugin-transform-decorators` throws an exception on any attempt to use decorators:
```
SyntaxError: /test/tests.js: Decorators are not supported yet in 6.x pending proposal update.
  291 |     }
  292 | 
> 293 |     class A {
      |     ^
  294 |       @foo
  295 |       bar(x) {
  296 |         return x + 1;
```
Decorator support will have to wait until the decorator proposal advances from stage 1 to stage 2. Watch [this page](https://github.com/tc39/ecma262#current-proposals).

**Comment by Sanjo** [comment]
https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy can be used with Babel 6.

**Comment by pbastowski** [comment]
@benjamn good that you added this task, thanks. 

I just read the [javascript-decorators](https://github.com/wycats/javascript-decorators) page and am wondering if the sentence below means what it says, with respect to applying decorators at "design time". Currently, decorators are executed at run time, not design time. I imagine that most libraries that use them depend on this staying the same. 

> Decorators make it possible to annotate and modify classes and properties at design time.

As you mentioned earlier, the actual decorator spec is still under review. So, who knows what they'll come up with and when. In the mean time, we as a community can't wait for "them" to finalise their specs, because we have been using decorators for almost a year in production already. I foresee that custom implementations will continue, unless....

To avoid complete forks with custom implementations, how about adding an "experimentalDecorators" flag in some fashion ASAP, just as the TypeScript compiler does, for example? 

With this approach, Ben, you could implement the immensely useful decorators safely now and take responsibility (within Meteor's context) for only this one single feature and not all experimental ES7 features.

How about it?

**Comment by kamilkisiela** [comment]
@benjamn This can be closed now, since `1.3.3` has been released.

```bash
npm i -S babel-plugin-transform-decorators-legacy
```

`.babelrc` or `package.json#babel`
```json
{
  "plugins": ["babel-plugin-transform-decorators-legacy"]
}
```

**Comment by abernix** [comment]
@benjamn Request to close.  Not sure if this is fixed to your original desire and not familiar enough to say if it's fixed – though I think it is.

**Comment by hwillson** [comment]
Additional Babel transforms support was added in [Meteor 1.3.3](https://github.com/meteor/meteor/blob/devel/History.md#v133), so this issue can now be closed. Thanks!
