### ISSUE TITLE
Meteor 1.2.1 uses 32-bit Node.js for Windows

### ISSUE THREAD

**Issue by aayushkapoor206** [meteor/meteor#6062]
I am trying to build https://github.com/lovell/sharp using `meteorhacks:npm` package, but on Windows, it is available only in 64-bit and node used by meteor is 32-bit as per npm's debug log.

Is there a way to install 64-bit version for meteor or node for Windows?
Is there a fix for this in Meteor 1.3?

**Comment by stubailo** [comment]
We decided to go with 32 bit node on windows at the time because the 64 bit version was relatively unstable (Node.js on Windows is hard by itself, and things get more interesting when you include Mongo etc.).

Perhaps it's time to reconsider and add 64 bit or switch from 32 to 64. Seems like this should tie in to another major change, like upgrading node: https://github.com/meteor/meteor/issues/5124

**Comment by abernix** [comment]
Closing as I believe this should be resolved.  If you install the proper build toolchain [per the instructions for `node-gyp`](https://github.com/nodejs/node-gyp#installation) Installation and utilize Meteor 1.4 which comes with Node 4.4.7, you should be able to get this to work now.

Please note that you no longer need to use `meteorhacks:npm` as `npm` can be used directly by running `meteor npm install --save sharp`.  If you're using an older Meteor project, you'll need to create a preliminary `package.json`.  I recommend taking one from a fresh `meteor create` project scaffold. :)
