### ISSUE TITLE
 require'ing at runtime in 1.3

### ISSUE THREAD

**Issue by samhatoum** [meteor/meteor#6068]
I'm using our `xolvio:backdoor` package, which allows you to [run arbitrary code on the server using a method](https://github.com/xolvio/meteor-backdoor/blob/master/server.js#L10). This package is used by Chimp's `server.execute` method, which allows tests to run code on the server.

I'd like to require modules at runtime from my tests like this:
```javascript
server.execute(function() {
  const AccountHolder = require('./account-holder');
  const accountHolder = new AccountHolder();
});
```

I can't use `import` since the code is not top-level of course, and `require` is `undefined`

Is there a way to use require at runtime in 1.3? Or some other solution for this use-case?

**Comment by seeekr** [comment]
I'm not quite up to date on all the details of 1.3 and require/import, but -- shouldn't there be some remnant of Meteor.npmRequire left in the API that does the require-thing? May not be the case of course, but thought I'd chime in with this.

**Comment by samhatoum** [comment]
Thanks for the chime. no dice with `Meteor.npmRequire`, it's undefined

**Comment by samhatoum** [comment]
You're talking about [meteorhacks/npm](https://github.com/meteorhacks/npm) - I want the raw Meteor 1.3 way :)

**Comment by Sanjo** [comment]
The exact thing that Sam and I need is: How to require any app file from a Meteor package?
It seems the Meteor package has its own require only for package files? So `require('<ABSOLUTE_PATH_TO_APP>/imports/foo')` did not find the file.

**Comment by benjamn** [comment]
We only include modules in the bundle if they were actually `import`ed or `require`d at build time, so if you want to be able to import a module dynamically, you might consider including an `if (false) require("./account-holder");` statement in your code, just to make sure the module is in the bundle.

In order to grant the `xolvio:backdoor` package access to the top-level `require` function, you can have it `api.use("modules")` and then call `var require = meteorInstall();`.

**Comment by samhatoum** [comment]
that did the trick, thanks!
