### ISSUE TITLE
Document deprecation of unused icons and launchScreen sizes in 1.3

### ISSUE THREAD

**Issue by rlech** [meteor/meteor#6069]
**_2 Upvotes**_ When I use the current `meteor 1.3-beta-2 release` it looks like the icon/splashcreen configuration handling from meteor is deprecated.

while building the app I got this error msg in the terminal.

`WARNING: iphone: unknown key in App.icons configuration. The key may be deprecated.`
`WARNING: iphone: unknown key in App.launchScreens configuration. The key may be deprecated.`

my mobile-config

``` javascript
App.icons({
    // iOS
    'iphone': 'assets/ios/icons/Icon-60.png',
    'iphone_2x': 'assets/ios/icons/Icon-60@2x.png',
    'iphone_3x': 'assets/ios/icons/Icon-60@3x.png',
    'ipad': 'assets/ios/icons/Icon-76.png',
    'ipad_2x': 'assets/ios/icons/Icon-76@2x.png'
});

App.launchScreens({
    // iOS
    'iphone': 'assets/ios/splash/Default.png',
    'iphone_2x': 'assets/ios/splash/Default@2x.png',
    'iphone5': 'assets/ios/splash/Default-568h@2x.png',
    'iphone6': 'assets/ios/splash/Default-667h@2x.png',
    'iphone6p_portrait': 'assets/ios/splash/Default-Portrait-736h@3x.png',
    'iphone6p_landscape': 'assets/ios/splash/Default-Landscape-736h@3x.png'
});
```

I also noticed that there is still the default meteor icon when I double click the home button (background apps screen) over the screen of the meteor app. @1.2.1 there is my app icon displayed

https://github.com/meteor/meteor/issues/6050

**Comment by martijnwalraven** [comment]
The `App.icons` and `App.launchScreens` settings are not themselves deprecated, but the `iphone` key is. Because there are no non-retina iPhones around that are still supported, including the 60x60 size no longer serves any purpose.

I believe the multitasking view shown when double clicking the home button uses the `ios_settings` sizes. These are 29x29, 58x58 (@2x), and 87x87 (@3x). I find the guidelines at [designcode.io](https://designcode.io/iosdesign-guidelines) very helpful for understanding which sizes are required (search for 'App Icons').

The reason it worked before is because we used to simply take the 60x60 version and use that for 58x58, but that is not strictly correct and generated warnings in recent version of Xcode.

**Comment by miclaus** [comment]
+1

**Comment by jstoup111** [comment]
+1 seeing that now and certainly would be a huge issue for production apps. Needs to be in the release notes or allow the ability to throw a depreciation warning and continue to do it even if it's "not correct".

**Comment by rlech** [comment]
how to set the mini icons in the mobile-config.js?

**Comment by skirunman** [comment]
Look in the 1.3 branch https://github.com/meteor/meteor/blob/release-1.3/tools/cordova/builder.js

**Comment by skirunman** [comment]
For Meteor Guide Mobile section it would be great if there was a link to resources to build all the required icons and splash screens. I have a pull request in for this package to generate the correct 1.3 resources.
https://github.com/lpender/meteor-assets
Would be nice to have this in the Guide or another supported option to generate all these assets.

**Comment by hwillson** [comment]
Hi all - we're reviewing this issue as part of the on-going old issue cleanup process. It looks like there are 2 main actionable items in this issue thread:

1) Document the `iphone` key deprecation.
2) Update the Guide with a link to resources showing how to easily build the required mobile icons and splash screens.

Regarding 2), this sounds like a great idea (and has several upvotes), so I've created a new issue to track this in meteor/guide#591.

Regarding 1), where would this deprecation documentation go? At this point we can't really go back and update the Meteor 1.3 release notes. Should this go into the Guide somewhere? We don't seem to have an existing deprecated mobile functionality section, so maybe we should add one? That being said 1.3 is now quite a few versions behind the current release (1.4.2.3 as of today), so we can probably assume most people have gotten used to the `iphone` key deprecation. Maybe the fact that this issue is documented here is enough? I'll assume that's the case for now and close this issue. Please let me know if anyone feels otherwise. Thanks!

**Comment by domramirez** [comment]
For those checking in on this, I'd suggest that you trust nothing but source code. The file dictating acceptable icon/splashScreen values is meteor/tools/cordova/builder.js (as of this writing). 

In my present and your past, the latest "stable" version is 1.5.2.2. That file seems to completely omit the App Store icon size:
https://github.com/meteor/meteor/blob/release-1.5.2.2/tools/cordova/builder.js

In the future it looks like the list will be more production worthy. This is the latest version in the "devel" branch (probably inaccessible to your project unless you install a later version of Meteor):
https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js

Rather than subject my whole project to a development version of a system which is far too dynamic to be predictable, I'm just going to drag-and-drop the proper icons into Xcode directly when I submit to the app store. This tutorial seems to have accurate information about how to do it as of now, but it ironically seems to be missing some images: https://www.appsfoundation.com/post/how-to-change-app-icon
