### ISSUE TITLE
IE11 crashes when Blaze updates <table> children while MutationObserver is active

### ISSUE THREAD

**Issue by DiegoOlivierFernandezPons** [meteor/meteor#6081]
**Refer to the second comment for more specific information about what triggers the crash/bug.**

We have encountered crashes in IE and have reduced the issue to a Semantic UI dropdown and a table that is reactively updated by Blaze.

https://github.com/DiegoOlivierFernandezPons/IE_crash_semantic_meteor

The code is a 2 x 2 table `[[1, 2][3]]` that is updated into a 1 x 2 table `[5,6]` and an empty dropdown initialized in an `onRendered()` callback. Internet Explorer 11 (11.64.10586) crashes. Chrome, Firefox and Edge are unaffected. 

The crash happens on line 366 of `blaze.js`

![image](https://cloud.githubusercontent.com/assets/1978836/12563336/d4080f06-c377-11e5-8803-190df808ede3.png)

![2016-01-25 7](https://cloud.githubusercontent.com/assets/1978836/12563370/000a0384-c378-11e5-8992-3027e220cd84.png)

To reproduce
- Download the code and type 'meteor'
- point the browser to localhost:3000
- type character 'b' or open the console and type 'show_bug()'

You can put a breakpoint on line 366 of blaze.js before triggering the bug.

**Comment by seeekr** [comment]
We've further trimmed down the code required to trigger the issue.

I've also discovered 2 ways to work around the bug, both of them can be seen in the [currently last commit](https://github.com/DiegoOlivierFernandezPons/IE_crash_semantic_meteor/commit/746956f29c07b3aa8810fff6859b6d76de486b86).

Basically here we have a strange interaction between a table without tbody being modified by Blaze while at the same time a `MutationObserver` is active (which is what SUI's dropdown component brings to the table - no pun intended).

Either removing the MutationObserver or adding that `tbody` wrapper for the table contents both make the crash/bug not appear in IE11. But neither of these are of course actual fixes or proper understandings of what's happening under the hood that triggers the crash.

This link seems relevant and helped me discover the workarounds: [gist: IE11 crashes when TableBodyElement.insertAdjacentHTML is called with a MutationObserver active](https://gist.github.com/josh/7597309)

**Comment by dgreensp** [comment]
Using a `<tbody>` seems like a reasonable workaround.

Some background that may or may not be relevant:  Blaze used to special-case tables lacking tbodies.  The weird thing about tables lacking tbodies is the way browsers work, if you omit `<tbody>` in your HTML, you still get a tbody in the DOM.  Blaze tried to replicate this behavior, but there's no way to tell statically that a tbody needs to be inserted; it has to be done dynamically.  (jQuery runs into a version of this problem too.)  What we realized is that, even though browsers will always insert a tbody when parsing HTML, the tbody is in fact optional in the DOM.  So if you are creating a table using the DOM API, you can leave out the tbody and things ought to work fine.  Or you can include the tbody if you want.

So, we decided it was simplest to have Blaze put a tbody in the DOM if and only if you put one in your template.  This allowed us to remove the special cases for tbody in Blaze that made the code more complicated.

Thus, you may want to include the `<tbody>` explicitly in your template if you encounter a browser that deals poorly with tbody-less tables.

I would classify this as a pure browser bug; you have one library using MutationObservers, and one library (Blaze) that will create tbody-less tables via the DOM API if so instructed, and this creates the conditions for the browser to fall over.  Hopefully this is something IE11 will fix and push out to users.

That said, it would be hard to say no to a small patch that works around this problem in Blaze.  Since you've been looking into it, do you know on what line Blaze crashes the browser?  Blaze doesn't use `insertAdjacentHTML`, so it must be some other DOM API call.

**Comment by hwillson** [comment]
This issue has been migrated to meteor/blaze#181 - closing - thanks!
