### ISSUE TITLE
Improve DDPRateLimiter docs and add extra examples

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#6087]
Specifying a rule for each and every method and subscription is not exactly friendly.
If a rule is specified, it should override global rule.

**Comment by stubailo** [comment]
The rule adding mechanism is quite flexible - are you interested in:

1. Adding a global rate limit that uses one counter for all methods and subscriptions
2. Adding a rate limit that counts calls _per_ method or subscription
3. A rate limit per method or subscription, per user or per IP?

Basically, there isn't a simple default because different applications will want different options from the above. All of them are possible with the current DDPRateLimiter API, which is a bit poorly documented in retrospect but can do a lot of stuff. I can show you how to do what you're asking for.

**Comment by avalanche1** [comment]
Thanks!
1st off I'd like to know how to set a global limit that applies same rule to every method and sub, using different counter for each.
2ndly it'd be nice to learn how to do the same but with a compound counted (1 point in ur list). 
A rate limit per user or per IP (using matcher field) is rather obvious from the docs, I guess.

**Comment by ignl** [comment]
Are there answers to those questions? I would like to add a global rate limit too. I tried to nginx rate limiting but still can to invoke Meteor.call inside a loop from browser console. I already use ddpratelimiter for some methods, but would like to have some kind of global rule for all the rest. Is it possible?

**Comment by zeari** [comment]
hi, anything going on with this? The basic login example doesnt really cut it when you want to limit anonymous users or limit subscriptions.

**Comment by abernix** [comment]
@zeari Unfortunately, this is a docs issue that hasn't been resolved yet.  Please try asking for help with your specific problem on the [Meteor forums](http://forums.meteor.com/) under `help`.  Someone will likely be able to advise there.

**Comment by stubailo** [comment]
If you get a good answer please help with a PR!

By the way, should we move this issue to https://github.com/meteor/docs?

**Comment by abernix** [comment]
Issue moved to [meteor/docs #103](https://github.com/meteor/docs/issues/103) via [**ZenHub**](https://www.zenhub.com/)

**Comment by abernix** [comment]
Yes! :smile:

And yeah, a docs PR would be super helpful for that, if you get to the bottom of it, @zeari.  I realize it's not super clear right now, but I believe what you're trying to do _is_ possible.
