### ISSUE TITLE
DDP mishandles non-JSON objects: Mongo ObjectIds, Dates, etc

### ISSUE THREAD

**Issue by antoviaque** [meteor/meteor#61]
Calls to `update()` on pre-existing mongodb records which use `ObjectId()` for their `_id` are ignored. `_Mongo.prototype.update` passes the string representation of the `ObjectId()` to `collection.update()`.

As a result, `update()` doesn't match any record. This doesn't raise any error - the update is silently ignored by the server, and the change reverted on the client.

Not sure what should be changed, but at the minimum it would be nice to be able to debug this more easily.

In my case, I've converted the _ids in my database to strings:

```
db.applications_hackers.find({}).forEach(function(app){
    db.applications_hackers.remove({_id:app._id}); 
    app._id = app._id.toString(); 
    db.applications_hackers.insert(app); 
});
```

**Comment by christiangenco** [comment]
I think this issue might be back? 

I can't `Articles.findOne("572bdb811ab1829622aeee78")`, but I can `Articles.findOne(new Mongo.ObjectID("572bdb811ab1829622aeee78"))` after creating the `Article` in `meteor mongo`.

Here's [a more detailed post I wrote about it](http://stackoverflow.com/questions/37083187/meteor-cant-find-by-id-in-a-mongo-collection/37083188) on StackOverflow.

**Comment by CarlQLange** [comment]
>I think this issue might be back?

>I can't Articles.findOne("572bdb811ab1829622aeee78"), but I can Articles.findOne(new >Mongo.ObjectID("572bdb811ab1829622aeee78")) after creating the Article in meteor mongo.

I have also seen this again today.

**Comment by abernix** [comment]
The `_id` that is created when using Meteor (through a Method, or `.insert()` within Meteor code) is **by default, not the same as the `_id` that would be created using Mongo** (with either `mongo` or `meteor mongo`).  If not specified, Mongo generates a `Mongo.ObjectID` (you can specify whatever you want for the `_id` though).

In Meteor, the `idGeneration` option when defining a `Mongo.Collection` is what determines how the `_id` is generated ([see these docs](http://docs.meteor.com/api/collections.html#Mongo-Collection)).

If you want to `.insert` rows manually using the `mongo` shell, you should use [the same technique as Meteor uses to generate the ID](https://github.com/abernix/meteor/blob/check-match-maybe-circular-objects/packages/mongo/collection.js#L64-L71).  Though as long as you are sure the ID is unique, you can use whatever random string you want – [`Random.id()` works well for this](http://docs.meteor.com/packages/random.html).

**But really, the easiest way is to just use the `meteor shell` instead of `meteor mongo`.**  This will handle the ID generation for you and works exactly the same as `.insert` inside your usual Mongo shell.

p.s. If you want to know the particular reasons that things are this way in Meteor ([someone actually this great explanation earlier today!](https://github.com/meteor/meteor/issues/3570#issuecomment-222792500)).

**Comment by CarlQLange** [comment]
Aha! That's very useful! Yes, of course, I created my collection using `mongoimport` rather than from inside meteor :)

**Comment by christiangenco** [comment]
> just use the meteor shell instead of meteor mongo

Oh whoa, I didn't even know this existed. The tutorials should be updated to use this instead - thanks @abernix 😄

**Comment by aboobakkar** [comment]
![er1](https://cloud.githubusercontent.com/assets/6416738/20428979/090458fc-adb2-11e6-9057-b90fa6250c14.png)
 command is retrived findOne!!
But Meteor Programming 
  let data1 = Tasks.findOne({mobile:mobile_number});
output console is undefined ?

**Comment by hwillson** [comment]
@aboobakkar - see my comments in https://github.com/meteor/meteor/issues/8072#issuecomment-261525532.
