### ISSUE TITLE
[1.3-modules-beta.7] trouble importing npm module 

### ISSUE THREAD

**Issue by emgee3** [meteor/meteor#6165]
I'm using the `node-mssql` npm module and under the hood it uses the `tedious` module as a dependency, which errors with `Error: Cannot find module './tedious'`

I tried importing tedious directly. `import tedious from 'tedious'` does not work, but `import * as tedious from 'tedious'` does work. Using the two modules straight from Node.js does work as expected, however.

Reproduction is at https://github.com/emgee3/npm-import-bug

**Comment by emgee3** [comment]
Looking over this further, it appears typing `import * as tedious from 'tedious'` works... However, I still think there's a bug here. I'm updating reproduction.

**Comment by appinteractive** [comment]
I had the same issues with the node filesystem ```import fs from 'fs';``` after importing it.

**Comment by emgee3** [comment]
@appinteractive I think we're having separate issues here. In my above repo adding the following:

```javascript 
import fs from 'fs'
fs.readFile('package.json', function (e, r) {
  console.log(e,r)
})
```
works fine.

**Comment by emgee3** [comment]
Additional data for MDG:

I've tried installing the node modules using the legacy node_modules folders, as well as modern node and do not notice a difference. Additionally, the problem still exists in Meteor 1.3-modules-beta.8, as well as a checkout of release-1.3 (current as of this comment's time).

**Comment by benjamn** [comment]
I believe the diagnosis for this bug is the same as what I explained in [this comment](https://github.com/meteor/meteor/issues/6173#issuecomment-186349691).

Specifically, `mssql/lib/main.js` attempts to `require` the `./tedious` module dynamically, [here](https://github.com/patriksimek/node-mssql/blob/00880a365f0091a4fc987df9d1720e2daa7a7e00/src/main.coffee#L135):
```coffee
@driver = @initializeDriver require("./#{@config.driver}")
```
You can probably get this to work by including
```js
require("mssql/lib/tedious.js");
```
in your server code, so that the dependency scanner knows to include that module. A bit tedious, admittedly, but arguably better than including everything in `node_modules` in the server bundle by default?

**Comment by benjamn** [comment]
I'm moving this to https://github.com/meteor/meteor/milestones/Post-1.3 for now, but please feel free to tell me if that workaround isn't good enough.

**Comment by emgee3** [comment]
> A bit tedious, admittedly ...

First off, I see what you did there.

Ok, so the workaround does solve my specific problem, so post-1.3 seems fine to me.  Though it is slightly galling that I write pretty `import` statements but have to drop in an old-style `require` for the side effect.

That said, kudos on the work and looking forward to the 1.3 release!

**Comment by benjamn** [comment]
Oh! You can just as well write `import "mssql/lib/tedious.js"`, that's what I should have said!

**Comment by benjamn** [comment]
This is fixed in `beta.16`, thanks to #6398.

**Comment by emgee3** [comment]
:+1: thanks Ben, works great now!
