### ISSUE TITLE
Add new target: web.worker

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#6222]
**_1 Upvote**_ This is a ticket to discuss one idea I implemented elsewhere and would like to bring it into the Meteor core.

I would like to add new target `web.worker` to the Meteor. This would allow one to use the whole toolchain (ecmascript, coffeescript, combining multiple packages) for various web workers (web workers, service workers, etc.). This would address the following issues: https://github.com/meteor/meteor/issues/5982 https://github.com/meteor/meteor/issues/2751

I have the code ready in my fork and works pretty nice.

Is this something I should make a pull request? What would be guidelines and design considerations here?

One open issue related to this is, that once you have this, some such feature is needed: https://github.com/meteor/meteor/issues/6099 My current plan to address this to add `api.onUseDependices({target: [listOfDependingTargets]})` which would register that when somebody depends on the package with `target`, also `listOfDependingTargets` should be added.

This allows one to depend a package only for `web.browser`, but would pull in also `web.worker` because it is used internally.

The other thing which is needed is something like https://github.com/meteor/meteor/issues/6203, which allows one to dynamically resolves dependencies. So if I do `importScripts('packages/ejson.js')` this will automatically pull also `packages/base64.js` as a dependency, for example. Works pretty well for both workers and `<script>` tags in my implementation.

This pull request https://github.com/meteor/meteor/pull/5714 should probably also be pulled in to get manifest file have correct URLs for content. In this way then one does not have to hard-code URLs to workers' scripts, but can read manifest and resolve them (I would not provide mechanism for resolving as part of this pull request, but it can be done later on).

**Comment by mitar** [comment]
cc @stubailo: Let's see how discussion of a feature request would work on GitHub.

**Comment by stubailo** [comment]
I'd like to note that this is much more than a feature request, this is a _Very Major_ feature request (in my view). And then pass it to the platform team, @avital and @benjamn.

**Comment by mitar** [comment]
Hm, it is less than 100 lines of code from what I see at the moment. :-)

**Comment by mitar** [comment]
Most of code changes were done because of the Cordova. This would only add one more identifier to all of those lists of possible targets. The rest is more or less already taken care of or already merged in Meteor recently by @martijnwalraven.

**Comment by mitar** [comment]
The dependency thingy is the only one really changing things, but that could be also limited only to this platform.

**Comment by trusktr-goin** [comment]
Would this automatically launch all scripts for `web.worker` in a worker? In the same worker? One worker per file? How would that be configured?

What do you think about the idea of a build plugin that uses `babel-compiler` (like `ecmascript` does) and compiles `*.blob.js` files into a URL, so that we can do

```js
import blobUrl from '/path/to/file.blob'
const worker = new Worker(blobUrl)
```

or maybe it just gives you the blob directly:


```js
import blob from '/path/to/file.blob'
const url = URL.createObjectURL(blob)
const worker = new Worker(url)
```

Or maybe a build plugin that reads `*.worker.js` files and gives you a constructor?

```js
import SomeWorker from '/path/to/some.worker'
const worker = new SomeWorker
```

**Comment by mitar** [comment]
> Would this automatically launch all scripts for web.worker in a worker? In the same worker? One worker per file? How would that be configured?

One worker per package.

> into a URL, so that we can do

Not all browsers allow loading web workers from a blob.

**Comment by mitar** [comment]
To explain it a bit more. From my experience there is no need to have multiple worker scripts. Often you can simply combine multiple files together, each with its own message handlers and this is it. And then you can use the same script in multiple workers, if you really need multiple threads, and send different messages to different threads. But otherwise you simply use one worker and send messages to it.

So there is no need really for multiple scripts. How I see it is that the package might want some features to have in background thread. So it creates one worker for that.

We could even make it so that Meteor runs that web worker for the package automatically, if files are defined for worker target. And provide some high-level API (reactive API?) for communication with the worker. Imagine that each reactive worker would have its data context which would be reactive? :-) (Just ideas.)

**Comment by trusktr-goin** [comment]
> One worker per package.

A determined package author will still be able to create any number of workers (within the limit the browser defines) if they need certain programmatic flexibility.

> How I see it is that the package might want some features to have in background thread. So it creates one worker for that.

A package might want multiple workers too. It's totally possible.

> Not all browsers allow loading web workers from a blob.

Not all browsers support web workers.

> We could even make it so that Meteor runs that web worker for the package automatically, if files are defined for worker target. 

Some of us would like to be in control of creating or destroying workers based on the content currently being displayed, to maximize memory efficiency, which is why it'd be great for us to be able to simply import a file to have easy control over the creation of workers.

> And then you can use the same script in multiple workers, if you really need multiple threads, and send different messages to different threads.

Suppose we have 10 workers to take on 10 different tasks as fast as possible, and each task is 1,000 lines of code. We would want workers to load 1,000 lines each (for a total of 10,000 between all workers) instead of 10,000 lines each (for a total of 100,000 between all workers).

> And provide some high-level API (reactive API?) for communication with the worker. Imagine that each reactive worker would have its data context which would be reactive? :-) (Just ideas.)

Having reactivity inside a Worker would definitely be awesome, especially if worker code would be able to simply `import` that API.

**Comment by martijnwalraven** [comment]
I think support for web workers is a worthwhile feature request, but I don't think this is the approach to take to bring this into core. I understand the implementation is working for you and solves an immediate need, but I think we should look at this as part of a larger overhaul of the build system.

The need to implement web workers on top of a new target is an artifact of our current build system and something we are committed to improving on in the near future. I think it is clear we want to move to a more flexible build structure (with multiple entry points, code splitting, etc.), and I feel the fine grained model made possible by this would be a better fit for web workers.

**Comment by mitar** [comment]
> We are still able to manually create any number of workers (within the limit the browser defines) if we need certain programmatic flexibility, so we may as well provide the same flexibility.

You can create multiple web workers, but there is no need for them not to share the same (minimized) code.

> A package might want multiple workers too. It's totally possible.

Yes, but they can share the same code.

> Plus, then our messaging API might need to be more complex in order to get messages to the right parts of the code.

Not really, you can have simply multiple event handlers listening for messages.

**Comment by mitar** [comment]
> I think support for web workers is a worthwhile feature request, but I don't think this is the approach to take to bring this into core.

BTW, this could then be again the issue that we will wait for "perfect" solution and then not have anything for a long time. I would rather see that we have partial solution and later on we deprecate it in favor of even better solution, then no solution.

And no, it is not really possible to solve this without a change in the core. Tried it.

We could make this an non-documented feature though. For people to use if they want, but not really part of official features.

**Comment by martijnwalraven** [comment]
I understand your frustration and I realize waiting for a better solution is not always the best strategy. But this feels like an area where the people that need it can find their own solutions for the time being, either through a private fork or an external build process (such as webpack).

Making the changes to the build system you propose (such as https://github.com/meteor/meteor/issues/6099, https://github.com/meteor/meteor/issues/6203 and https://github.com/meteor/meteor/pull/5714) just to support what is basically a temporary workaround does not seem worth it to me. It would further complicate what is already a complex part of the platform, while we really need to save our energy to focus on alternatives.

**Comment by mitar** [comment]
> Making the changes to the build system you propose (such as #6099, #6203 and #5714) just to support what is basically a temporary workaround does not seem worth it to me. It would further complicate what is already a complex part of the platform, while we really need to save our energy to focus on alternatives.

But the question here is: if I am willing to invest time to get this into the core, why this could not be in the core if it solves the problem for people now? I understand that core developers might want to develop something better and perfect in the long term, but how can we as a community create something which can be reusable by others without having to ask them to use our fork (so in fact without forking Meteor)?

**Comment by avital** [comment]
The reason is that everything in core needs to be maintained, supported,
tested going forward. The initial merge cost is a very small fraction of
the overall cost for something being in Meteor core.

**Comment by mitar** [comment]
> The reason is that everything in core needs to be maintained, supported, tested going forward. The initial merge cost is a very small fraction of the overall cost for something being in Meteor core.

True, so we get back to the proposal: if people who merged this in stop supporting it, you put a vote to the community if they still want to keep it in, and somebody else from the community keep sit maintained, or it gets removed.

We should simply have a long list of which parts of the code people are responsible for. Core parts have people from MDG, other parts inside the Meteor community can support.

Or do you have some other approach how to address this? I think this is the crucial question when you are doing a monolithic project like Meteor. How to balance these things.

I really do not see how would this 100 lines of code change be so problematic, and it would solve the concrete problem. We talk about offline use Meteor and how there is no support for it yet which would be a clear winner? Maybe having a worker target where you can compile service worker could solve that. It is really that without some features we cannot have further innovation down the road.

**Comment by avital** [comment]
This isn't how it works. Once you've merged something into core you can't just take it out.

The approach is for a core group of people, for example MDG to be able to say, "no, this is out of scope for core".

**Comment by avital** [comment]
Is there anyone else who wants this PR merged? Surely if it's a single user that wants this (even such a wonderful person like yourself @mitar), that's not a good enough reason to include it in core.

**Comment by mitar** [comment]
Hm, with this ticket I wanted to open a discussion how this should be done. I read from other tickets (like #5982) that people would like a solution to this. I am proposing a solution which can work now and here. Let's see if people want a solution now and here.

cc @dandv

**Comment by Primigenus** [comment]
I think pursuing *-worker support is a goal that is becoming increasingly relevant, but it doesn't seem so time-sensitive to me yet that we should circumvent MDG's (established, proven) process of thinking things through and architecting them the right way just so we can get it into core sooner. One thing I've always greatly respected about this project is the considerate, thoughtful nature with which new features are added and subsequently supported over time.

Having said that we do need a better way to work with the community to integrate new ideas along a timeline, but I'm sure MDG is already thinking about this.

**Comment by jiku** [comment]
Since MDG are [decoupling core](https://forums.meteor.com/t/vertical-traffic-light-transmission-6-meteor-repo-decoupling-community-member-core-maintainers-1-3-modules-webpack-2-0/17800), and it's only 100 lines, does it make more sense to add it to core now and decouple at the first opportune moment (maybe it would make a good first candidate, since it's so small and fresh?), or just wait until there's something in place so it could be integrated? What would take longer, and by how much? Would be cool but maybe not a must to have it working in core before then?

**Comment by martijnwalraven** [comment]
Unfortunately, the Meteor tool (which includes the build system) is one of the hardest parts to decouple. Apart from build plugins, most features are too intertwined to be easily extracted and independently developed. This is actually one of the things we hope to fix with an overhaul of the tool.

My resistance to this proposal is not about the number of lines, but about the changes it requires throughout the build and packaging system. I really want us to support web workers soon, but I also want us to do a good job of it and not complicate the existing system further.

Packages like Blaze or the accounts system are a much better first candidate to decouple from core because they are already relatively isolated from the rest of the system.

**Comment by mitar** [comment]
BTW, this one is really easy to add. In fact, the only really required change is like 10 lines of code, simply adding few `web.worker` strings here in there. The rest is already in the build system. The other stuff is just goodies to make things easier to use but not really required. Sadly, the list of existing targets is hard-coded, so those are the changes needed.

**Comment by jiku** [comment]
@martijnwalraven makes perfect sense for the current PR.

@mitar could lead to a working compromise? Happy to test a PR like that against your current PR, ahead of someone in a position to really assess if it meets MDG's expectations for feature-set, ease-of-use, LTS, other stuff.

**Comment by mitar** [comment]
@jiku: I do not understand what you just wrote.

**Comment by bopjesvla** [comment]
> Is there anyone else who wants this PR merged? Surely if it's a single user that wants this (even such a wonderful person like yourself @mitar), that's not a good enough reason to include it in core.

I do! Also, in #5982, one of Rocket.Chat's core developers said they'd love to use this.

**Comment by NitroBAY** [comment]
+1 meteor needs offline support and the SW are the only right way to do that today

**Comment by danlg** [comment]
Yes offline support with standard W3C technology is much better than 3rd party solution (e.g. ground db). However, to build cross platform app is there a way to have this wprking on Android and iOS. I'm confused because it is not supported on Safari but I found this plugin from Google Chromium team

https://github.com/MobileChromeApps/cordova-plugin-service-worker

**Comment by AndreasGalster** [comment]
Is this related to being able to use importScripts()? I'm currently trying to use a push notifications service provider but it seems it's not possible because meteor doesn't support the syntax?

**Comment by NitroBAY** [comment]
@danlg ground dB is for caching collections in memory. Service worker is for caching assets such as JS or CSS (or images) in ROM

**Comment by justindra** [comment]
@NitroBAY so does that mean for a fully offline app, I would implement Ground:DB and service worker?

**Comment by NitroBAY** [comment]
@justindra probably. Actually you could also use appcache to cache website, the time has proved it wasn't a good solution but there is already a package tough. And you need grounddb only if you have database (which is most of time the case)

**Comment by NitroBAY** [comment]
No but seriously, why isn't it's implemented a small changes that would make Meteor by default WORKING OFFLINE. Isn't this would be wonderful ??? This would be a great argument and it's totally into the logic of Meteor, don't you agree ? Until this PR is merged, I made a repository https://github.com/NitroBAY/meteor-service-worker

**Comment by NitroBAY** [comment]
Please now my repo has +42 stars (the universal answer ;)), so probably about one hundred ppl use my SW, that some are asking for a package (on multiple issues, lastly here https://github.com/NitroBAY/meteor-service-worker/issues/9) and that a lot seem to be agree that once I can publish the SW as a package a lot of devs are gonna use it reconsider the fact of including Mitar's work.
If you do such a thing I ensure that I and the community is gonna support the package and that we're gonna include more features (including the possibility of directly add assets as soon as the SW is registered, just like with old and deprecated Appcache)

**Comment by mitar** [comment]
Some dependencies for this issue:
* #5706
* #5706

Also useful, if we go with this support are dependencies between targets: #6238

**Comment by NitroBAY** [comment]
@mitar you may have made a typo, you wrote twice the same issue (5706). We're still seeking for a support of SW.

**Comment by mitar** [comment]
Fixed. :-) Thanks.

**Comment by mitar** [comment]
BTW, this is the sixth most upvoted issue for Meteor.

Because I have code for this made in my private fork, maybe if this would be labeled for a pull request, I could make a pull request. What it does it literally adds another target, `web.worker`, so that you can target things against it.

**Comment by rwatts3** [comment]
I second @mitar ,

This is probably the single most important feature I would need to truly take my applications and current planning to the next level.  Progressive Web Apps are the future.  Cordova was cute for the short time it lasted.

**Comment by NitroBAY** [comment]
I'm actually really surprised that what was an innovative modern framework doesn't have a global policy towards Progressive Web Apps.

> **Progressive Web Apps are the future.**

**Comment by NitroBAY** [comment]
Sorry but I'm about to be more generalist about Meteor for a moment.
Meteor has used to be a tool that features almost everything and makes everything easy : template (blaze), databases with isomorphic API (mongodb/minimongo), methods, package manager (atmosphere). Now everything is, or is going to be, deprecated.
I'm not going to talk about whether it's good or bad as in any way the evolves have good sides (more open framework, the sensation of "everything was easy at the beggining but as soon as I have complex needs, which always come in an actual project, Meteor makes everything very complex/impossible" is less present) and bad sides (the framework can be less attractive, dev time increases).
But I just want to say that : now that the framework is going to be almost empty, just a Node.js environment that makes things easier, you can **not** afford (in my point of view) to restrict possibilities. Either you make a monolithic framework as before, which implies a fast development but also some things harder to implement, either you make a light framework, which is harder at beginning but should be less restrictive.

> The reason is that everything in core needs to be maintained, supported,
tested going forward. The initial merge cost is a very small fraction of
the overall cost for something being in Meteor core.

You dropped Blaze, Atmosphere, in a some times Mongo and methods supports but still you're not able to maintain a 100-lines code change ?

The same goes for service workers, web workers, HTTP/2 etc.
Now my personal point of view : meteor is about to fail the transition (from an heavy to a light framework) and die because of the lack of resources.

**Comment by abernix** [comment]
@NitroBAY I've removed your post.  If you'd like to discuss web workers, the best implementation or argue in their favor with additional valuable data or implementation details (as in, not just generically saying "we should do this" again or re-stating the number of votes), by all means, please use this issue to do that, but let's keep blanket statements about Meteor as a framework as a whole somewhere else.

We're aware of this issue (and the actual issue about service workers – #5982) and we're currently working on items that are listed on the [Roadmap.md](https://github.com/meteor/meteor/blob/devel/Roadmap.md).  We aren't ready to add a `pull-requests-encouraged` label to this until we've had time to fully consider this, which is something we are mulling over.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20new%20target%3A%20web.worker&body=Migrated%20from:%20meteor/meteor%236222) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by mitar** [comment]
Moved to: https://github.com/meteor/meteor-feature-requests/issues/19
