### ISSUE TITLE
Better way to get template instance from helpers

### ISSUE THREAD

**Issue by lnmunhoz** [meteor/meteor#6257]
Now that we are thinking more like React, our components should have a good attention to states. Blaze provides a nice way to create nice components but when I need to access the template instance variables from helpers, I need always to write `Template.instance().someVar`. Why this syntax can't be like changed by just using callbacks like when we are working on events? 

Something like:
```js
Template.fooList.helpers({
  isLoading(template) {
  	return template.state.get(); // reactive-var
  }
})
```

Is it makes sense?

**Comment by zol** [comment]
We've split the Blaze repository away from meteor/meteor in order to make it easier for community members to contribute and the MDG team to maintain a slimmer core. Please move your issue over to the Blaze repository located at https://github.com/meteor/blaze

Alternatively, this topic may be better suited for discussion on our forums.
