### ISSUE TITLE
static file serving fails to set etag based on file contents

### ISSUE THREAD

**Issue by awwx** [meteor/meteor#626]
I was watching assets being loaded from the Meteor server and was surprised to see "200 OK" responses instead of "304 Not Modified" for files that hadn't changed.  Turns out gzippo isn't setting the etag header based on the file contents, but instead is using the file modification time (!)

https://github.com/tomgco/gzippo/blob/master/lib/staticGzip.js#L120

The result is after a redeployment (when file modification times change even if the content hasn't), the browser ends up downloading everything again -- increasing load on the server and slowing things down for the user.

connect.static doesn't set the etag header correctly either, sigh.

**Comment by glasser** [comment]
Note that we no longer use gzippo; we call send directly.  And send does this:

```

SendStream.prototype.setHeader = function(stat){
  var res = this.res;
  if (!res.getHeader('Accept-Ranges')) res.setHeader('Accept-Ranges', 'bytes');
  if (!res.getHeader('ETag')) res.setHeader('ETag', utils.etag(stat));
  if (!res.getHeader('Date')) res.setHeader('Date', new Date().toUTCString());
  if (!res.getHeader('Cache-Control')) res.setHeader('Cache-Control', 'public, max-age=' + (this._maxage / 1000));
  if (!res.getHeader('Last-Modified')) res.setHeader('Last-Modified', stat.mtime.toUTCString());
};
```

So on the one hand, we can just call `res.setHeader('ETag', hash)` before calling `send`.  On the other hand, it still ALSO sets Last-Modified by default, and so just because the etag hasn't changed doesn't mean the last-modified hasn't, so the issue isn't actually fixed.
