### ISSUE TITLE
Meteor BUILD to Android INFINITE LOOP

### ISSUE THREAD

**Issue by Jayuda** [meteor/meteor#6273]
Hello Meteor,
I tried to make Android APP with Meteor. It was No error  when I try it on an emulator or device. All work well.
But when I build and generated APK, I installed on device show error with a view infinite loop.
What the problems about it?

**Comment by martijnwalraven** [comment]
I will need some more information before I can help you. Have you read our issue guidelines before posting?

What version of Meteor are you using? What steps have you followed to build and run the app? What happens when you run it? What do you mean by 'view infinite loop'? Any other error messages, either on the device or through the Chrome remote debugger?

**Comment by Jayuda** [comment]
I am use Meteor 1.2.1.
Step build my app  :
`meteor build ./BUILD`

`keytool -genkey -alias MYAPP -keyalg RSA  -keysize 2048 -validity 10000`

`cd BUILD/android/ && jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 release-unsigned.apk MYAPP`

`/Users/ThinkMac/Library/android-sdk-macosx/build-tools/23.0.2/zipalign 4   release-unsigned.apk production.apk`

If i installed on my android phone, the app refresh loop. but if i run with 
 `meteor run android-device --verbose` 
It not found error and not refresh loop.

**Comment by Jayuda** [comment]
sorry, it was my fault when using iron: router
Thanks for the help
