### ISSUE TITLE
Meteor file load order not reflected in order in the app bundle.

### ISSUE THREAD

**Issue by trusktr-goin** [meteor/meteor#6288]
I was looking inside the app bundle that Meteor 1.3 generates, and it doesn't appear that the files appear in the file in the same order that they actually execute.

I've got a file structure like follows, and the files in the `workflows` folder appear in the app bundle *before* the files in the `components` folder (not the same as their load order).

```
meteor-app/
  client/
    components/
      someFolder/
        someFile.js # executed first, but appears second
    workflows/
      otherFolder/
        otherFile.js # executed second, but appears first
    app.js
```

It's probably not a big deal, but I was looking inside the compiled app bundle to figure out the order of execution of things, and realized the order of things in the bundle isn't to be trusted. It might be useful (for people researching their post-build app) to have files appear in the correct order.

**Comment by benjamn** [comment]
Execution order comes down to the order in which modules are imported, though. The `ImportScanner` adds files in depth-first order, according to `import` statements and `require` calls, so that's probably the source of the reordering. I see how this is slightly confusing, but I'm afraid we can't prioritize improving this behavior ahead of fixing bugs.

**Comment by benjamn** [comment]
Source maps should make the bundle ordering less important, too. I hope you're in a minority of people who are actually looking at the bundle on a regular basis :)
