### ISSUE TITLE
Update skeleton app to follow 1.3 Guide recommendations

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6306]
- [ ] App structure
- [ ] Modules
- [ ] Tests

**Comment by tmeasday** [comment]
+ no session / actually use a collection.

**Comment by stubailo** [comment]
Should create client/server dirs probably, should have a landing page that tells you to do the tutorial/guide

**Comment by laosb** [comment]
I've actually done a version of template app before and submitted it as a pr #6357 

Having client/server dirs sounds good, but it is not very useful for an one-cup-of-coffee app. Considering a kind of example or something like Mantra CLI could do this initial for a typical production app instead of a template app.

**Comment by laosb** [comment]
I would try to rewrite it with ReactiveDict and use a collection to build a simple todo (any ideas about some easy usage of collections?)

**Comment by tmeasday** [comment]
@stubailo I am going back and forth about this one.

I think @laosb is right in that there is a difference in use-case between a simple starting point and a full boilerplate. In fact I can kind of see three completing goals in what `meteor create` does:

1. Provide a simple starting point for beginners
  - Here `insecure` and `autopublish` make sense
  - A lot of files and directories is a poor choice
  - Including something to point them to the docs and guide is good.
2. Provide the starting point for a production app (i.e. boilerplate)
  - We'd probably put down every directory here: https://github.com/meteor/guide/blob/structure-content/content/structure.md#example-directory-layout
  - Probably *any* content is just annoying
  - We could also set up a bunch of scripts (e.g. linting?) in `package.json`
  - This seems more opinionated and guide-y. It's good but maybe it shouldn't go in the tool? Maybe we should let the community do it?
3. A mini-tutorial
  - e.g. showing how to use collections
  - including a test

I'm sort of turning against 3. I don't think we should not follow our recommendations (i.e. we should `import` and not use the session), but I wonder if the test is adding much?

I'm wondering if we go with 1. and call out that if they want to see a "real" app, they could run `meteor create --example todos`. And if they want to get a boilerplate, they could run ... ?

**Comment by stubailo** [comment]
Hmm, one thing to note is that Meteor doesn't have scaffolding - in Rails the starter app didn't have much, but you could generate views, tests, etc. with the scaffold command.

Honestly I don't think (1) is that important. If you want a starting point for beginners, just do the tutorial. (3) doesn't seem useful either, I agree, because a tutorial is better. Maybe we should go all-in on (2)? It doesn't stop you from deleting everything and writing one file, but I think everyone would benefit from having some directories where they could start dropping stuff in?

I also think we should have the landing page that says "go to the guide and tutorial to learn how to use this thing".

**Comment by tmeasday** [comment]
Maybe you're right. It seems like a big change. There are a lot of questions that follow:

 - Do we include autopublish and insecure?
 - Do we include any runtime JS code?
 - Do we include any files at all?
 - (Or conversely) do we include packages like flow router and mocha and put down stub/boilerplate files?
 - Do we include links in a basic routed page or just in a README.md?
 - Do we include scripts and linting config & etc & etc

My guess is that if we go down this road then we are going to want to tinker with this stuff a fair bit. Which is probably and argument for a separate project. But I'm not sure. We could just do some of the above?

**Comment by stubailo** [comment]
Hmm I dunno. I doubt anyone cares about the current starter app. But for example including flow router might make sense.
