### ISSUE TITLE
Finish/Publish tmeasday:check-npm-versions

### ISSUE THREAD

**Issue by zol** [meteor/meteor#6333]
Close this if it's already done/not required.

**Comment by tmeasday** [comment]
I think I was mainly unsure of what to call it (`check-npm-versions`, `tmeasday:check-npm-versions`, etc). 

Also we might want to finesse the error messages.

Anyhow, published `tmeasday:check-npm-versions@0.1.1` (https://atmospherejs.com/tmeasday/check-npm-versions)

**Comment by tmeasday** [comment]
One note on this:

I'm not sure if it's a recent change, but it seems we now hoist `import` statements to the top of the generated file (we/babel). This means that either you need to `require()` the npm module you care about, or you need to do the checking in a separate file. Otherwise the hoisted import just fails before the check ever runs.

cc @benjamn

**Comment by benjamn** [comment]
Yeah, unfortunately `require` is necessary for something like this.

**Comment by tmeasday** [comment]
OK, I'll update the readme to reflect this.
