### ISSUE TITLE
Error: loadLocalPlugins called twice with different search paths.Support for     this is not implemented.

### ISSUE THREAD

**Issue by Doris1994** [meteor/meteor#6349]
When I was in terminal using the command line **meteor update -- 1.3 beta release. 11**  upgrading the project from meteor1.2.1 , the project can be normal use in meteor 1.2.1, but after upgrading an error in the build.The error information is as follows:
**While adding plugin imageresizer to Cordova project:
Error: loadLocalPlugins called twice with the company search paths. Support forThis is not implemented.**
I looked at so relevant information failed to solve the problem.please the great god provides a good solution, be appreciated.

**Comment by martijnwalraven** [comment]
Please reopen an existing issue when you feel it shouldn't have been closed. This is the third time you open an issue for the same problem (#6289 and #6136) and that makes it difficult to keep track.

You also haven't answered my previous question yet:
> From [this Cordova issue](https://issues.apache.org/jira/browse/CB-7808) it seems this error message may have to do with a local plugin depending on another local plugin. Are you using any plugins added from the local file system?

Which `imageresizer` plugin you are using (name on npm, GitHub repo), what version, and how did you add it to your project?

**Comment by Doris1994** [comment]
I'm sorry, just work is not very experienced.
plugin to add way is through the **meteor add cordova: com. Raananw. ImageResizer @ file://../ cordova - plugins/imageresizer**, plugin version 0.1.2

**Comment by Doris1994** [comment]
At the same time, other local plugin loaded, build later, the plugin corresponding native file path is wrong, only by manual modification to solve

**Comment by martijnwalraven** [comment]
Could you explain a little better what you mean by the native file path being wrong and manual modification needed?

What is the reason you are installing these plugins from the file system rather than from npm or GitHub? 

The Cordova issue I linked to suggests that the error you are experiencing is a result of one local plugin depending on another, which apparently is not supported.

**Comment by Doris1994** [comment]
More convenient for installation and use of local plugins and in meteor 1.2.1 use _cordova: com. Raananw. ImageResizer @ file://../ cordova - plugins/imageresizer_ to add it is successful, so plugin's code is no problem.
Native file refers to such file "SRC/ios/UIImage + Scale. H " in the plugin,
Execute the command_ meteor build_,  than opened  project on xcode, compile error, UIImage + Scale. H does not exist, but in fact there is
Native file path For Example.
![screen shot 2016-02-26 at 6 11 37 pm](https://cloud.githubusercontent.com/assets/16999234/13349511/6bfaa28c-dcb5-11e5-87c5-503c7e193552.png)

**Comment by martijnwalraven** [comment]
I'm not sure what is going on, but since the error message seems related to installing plugins from the local file system, you may want to try installing it from GitHub instead.

If that doesn't work, I don't think I can help you with this. The [README](https://github.com/RaananW/PhoneGap-Image-Resizer) mentions that the plugin is no longer developed. Chances are, it simply won't work without modification on more recent Cordova versions, like the one we ship with Meteor 1.3. If you want it to work, you may have to look into the issues and change the plugin source yourself.

**Comment by Doris1994** [comment]
thank you for your help, According to your suggestion has now been solved the problem.
