### ISSUE TITLE
Allow users to add Babel plugins to their project

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6351]
***1 Upvote*** Copied from [https://forums.meteor.com/t/meteor-1-3-and-babel-options/15275](url)

The BabelCompiler constructor in Meteor 1.3 takes options via the extraFeatures parameter. For example, here's what the ecmascript package does:

```
Plugin.registerCompiler({
  extensions: ['js'],
}, function () {
  return new BabelCompiler({
    asyncAwait: true,
    modules: true
  });
});

Plugin.registerCompiler({
  extensions: ['jsx'],
}, function () {
  return new BabelCompiler({
    asyncAwait: true,
    modules: true,
    react: true
  });
});
```
It'd be nice if there were more options, and a way for us to configure them. Maybe they can live in package.json (since that will now be a common thing in Meteor 1.3+). It'd be nice to, for example, enable stage-0 features, etc. It might look like this:

```
// package.json
{
  // ..
  "ecmascriptOptions": {
    "classProperties": true
  }
}
```

That would enable class properties4 on top of the default options that the BabelCompiler already applies based on whether a file is a .js or .jsx file.

**Comment by gadicc** [comment]
I think that while it's nice for compiler plugins to be able to add babel plugins, usually users simply want to enable babel plugins for files the `ecmascript` package is already responsible for.  We could - as suggested above by @trusktr - have options somewhere that `ecmascript` can use.  But in light of recent conversations and strategy to be more integrated with the general Javascript ecosystem, I'd suggest simply relying on `.babelrc`.

That way, if someone wants to add a plugin, they simply follow the instructions on that plugin's webpage (i.e. `npm install` and add to `.babelrc`), rather than having a different "Meteor way" of doing it, like we had to do in the past with e.g. npm packages.

I know we disabled `.babelrc` support in https://github.com/meteor/meteor/issues/6016 via https://github.com/meteor/babel/commit/1eb5cbd97c8427f62703930e2d441710943c1720, but I think that was more for a quick fix than a design / policy decision.  Back in the [the original post](https://forums.meteor.com/t/meteor-1-3-and-babel-options/15275/5?u=gadicc) on the forums, @benjamn said:

> The Babel 6 plugin system makes configuration much, much easier than it was in Meteor 1.2. In short, I think we can support any configuration as long as it includes the preset [babel-preset-meteor](https://www.npmjs.com/package/babel-preset-meteor), along with any additional plugins you might want. In other words, you won't be able to remove features that are included in that preset, but you can add as many other features as you like. You might also have to do npm install babel-runtime in your app, but that's probably not too much to ask :)

*We could either force this preset in BabelCompiler; or, Meteor could create a root level `.babelrc` if it doesn't already exist that includes babel-preset-meteor and throws an error at runtime if the user has removed it.*

**Comment by benjamn** [comment]
We're seriously thinking about introducing a `package.json` file in the application root directory. What if we paid attention to the "babel" field in that file?

**Comment by clayne11** [comment]
I think it should work like Babel does in the rest of the NPM community. Look for `.babelrc` and if that doesn't exist then look at the "babel" field in the package.json file.

https://babeljs.io/docs/usage/babelrc/

**Comment by benjamn** [comment]
Ok, but at the very least the `.babelrc` file should have to be contained by the app directory, not inherited from some ancestor directory unrelated to the app, right?

**Comment by clayne11** [comment]
I agree with that.

**Comment by gadicc** [comment]
Sounds perfect :)

**Comment by dagatsoin** [comment]
Seems to be a good way but wonder why it is not include in the 1.3 Milestone? Does that mean that there will be only hacky ways (https://github.com/meteor/meteor/issues/6420#issuecomment-192685414) to use decorator or class properties or other babel features?

**Comment by ChrisCinelli** [comment]
I would love the support for `.babelrc`

**Comment by sscaff1** [comment]
Any updates on this? We are looking to take advantage of this feature.

**Comment by gadicc** [comment]
This is milestoned for post-1.3, but I believe (I'm not from MDG) the plan is for shortly afterwards.  As important as this is, I think everyone here will agree that not a majority of devs will use this, and hence, it's more important to get the Meteor 1.3 stable out sooner.

Having said that, I'm working on some early (community) support for this, and am almost done.  Just got one last issue I need to solve, a caching problem.  @benjamn, do you think you might have a chance to help with this over the next week or better to wait till after 1.3?  The solution is, as usual, a bit hacky, but does illustrate the kind of things that would have to be solved properly on the Meteor side of things (i.e. breaking out of the confines of a package to read a project root .babelrc).

**Comment by gadicc** [comment]
Ignore that.  Less hacky and working, it's  [.babelrc support in Meteor 1.3 betas, today](https://forums.meteor.com/t/help-test-babelrc-support-in-native-meteor/19695).

@benjamn, this ended up being a lot simpler than I thought.  Beyond https://github.com/meteor/babel/pull/9, I'm happy to do a draft PR for Meteor with tests, etc, if you can give me some feedback on [this](https://github.com/gadicc/meteor-react-hotloader/blob/master/babel-compiler-hot/babelrc.js) and related code.  The only thing outside of babel-compiler that would really be needed is better watch support on `.babelrc` in the Meteor runner unless there's a signal I'm missing.

But most importantly, this brings acceptable support for this, today, and we can get some feedback on edge-cases etc and discuss properly when things calm down somewhat.

**Comment by tomitrescak** [comment]
@gadicc you are a life saver ;) Just what I was searchin for!

**Comment by gadicc** [comment]
Sure, @tomitrescak... got you covered!

I strongly recommend that everyone who needs this feature gets started with this package.  I suspect that a lot of this logic will end up in Meteor core (eventually), and it's only been through the feedback of current users that was I able to address a number of issues that I hadn't considered originally (such as the need for different babel settings for the client and server).

**Comment by jchristman** [comment]
Does anyone know when this might be integrated into core?

**Comment by mhagmajer** [comment]
I think this needs to support separate `.babelrc` configuration for client and server. For instance, we use regenerator to implement promises on the client-side and @benjamn's transpiler for fibers on the server-side.

**Comment by benjamn** [comment]
@mhagmajer That's a great point, and will only become more important when we upgrade Node and more features are implemented natively on the server.

**Comment by gadicc** [comment]
The way I did it in ecmascript-hot is to prefer a `client/.babelrc` or `server/.babelrc` on those targets if it exists, and the recommendation is for those files is to include an `{ "extends": "../.babelrc }` to still keep all the common setup in a project root `.babelrc`.  There's an example at the end of the [README](https://github.com/gadicc/meteor-react-hotloader#sample-babelrc).  (For those interested, the implementation is [here](https://github.com/gadicc/meteor-react-hotloader/blob/38f058c8a670b0af7a72575b4757f65e42b6dd55/babel-compiler-hot/babelrc.js#L75)).

**Comment by mhagmajer** [comment]
@gadicc, I gave your package a try and it's a great proof of concept. However, for me to consider this a viable solution for something so fundamental it would have to be 1) separated from the React's HMR 2) officially supported by MDG. Hence, I'm going to hold on with upgrade to 1.3 until this issue is resolved.

**Comment by gadicc** [comment]
For sure.  `.babelrc` support belongs in core, not a community package.  The intention has always been early access with a look at discovering and solving issues ahead of the official implementation, of which there have been quite a few since I first introduced the feature (load order with the meteor preset, client/server separation, caching with BABEL_ENV, etc).

I believe that having tried-and-tested patterns that have enjoyed (fairly) long use in the community is a great help to developing the official implementation, and will help lead to less rc's and a quicker final release without issues.

**Comment by jchristman** [comment]
I enjoy the early access so I can write with features that are sure to make it into core eventually - why wait?

I got the cssInJS Babel plugin working and it greatly improved the speed of my code tremendously! Great package filling a need until the core support comes!!

**Comment by trusktr** [comment]
@jchristman Nice! I'd be very tempted to give this a shot just to try cssInJS in Meteor!

**Comment by trusktr** [comment]
@jchristman Nice! I'm very tempted to give this a shot just to try cssInJS in Meteor!

By the way, two projects, [cssx](https://github.com/krasimir/cssx/) and [jss](https://github.com/jsstyles/jss), are going to work together to create [something awesome](https://github.com/krasimir/cssx/issues/2). I can't wait to get that working in Meteor...

**Comment by jchristman** [comment]
@trusktr, I have had an excellent experience with cssInJS thus far and would highly recommend it. It's simple, lets you define your css right alongside the component that uses it, and in combination with the classnames npm module is quite flexible! It also has some rather wonderful options.

**Comment by tomitrescak** [comment]
cssinjs ... where is the page for that? I am thinking of switching to this as well just did not find enough motivation. Also there is just so much choice right now, it's difficult to choose.

@trusktr does cssx have babel plugin? I did not see that. Thanks!

**Comment by trusktr** [comment]
@tomitrescak Yes [it does](https://www.smashingmagazine.com/2016/04/finally-css-javascript-meet-cssx/#start-writing-vanilla-css-in-javascript), located in the CSSX repos if you follow the link in that section of the article.

@jchristman Ah, thanks for sharing about `classnames`. Makes it easier to construct the string based on conditionals that could change (i.e. props or state on a react component). It still requires you to make your class names unique in your own way somehow, in order for components across the app not to have conflicting class names. One of the nice things about `jss` is that it guarantees unique class names for the whole app, even if the variable names are the same. What I mean:

```js
// file1.js
import React from 'react'
import jss from 'jss'

const style = {
    button: {
        background: 'teal'
    }
}

const {classes} = jss.createStyleSheet(style).attach()

export default
class FirstButton extends React.Component {
    render() {
        return <button className={classes.button}></button>
    }
}
```

```js
// file2.js
import React from 'react'
import jss from 'jss'

const style = {
    button: {
        background: 'lightblue'
    }
}

const {classes} = jss.createStyleSheet(style).attach()

export default
class SecondButton extends React.Component {
    render() {
        return <button className={classes.button}></button>
    }
}
```

So, in both apps, the `button` class is the same name to the programmer, but the variable content is unique. In file1, `classes.button` is something like `"button-jss-0-0"`, and in file2 `classes.button` is something like `"button-jss-0-1"`, so by default it's not possible to make a name collision (there's an option to turn that off).

**Comment by benjamn** [comment]
This is coming in Meteor 1.3.3! See [here](https://github.com/meteor/meteor/pull/7033/commits/49a60f155b64e00a5f3e879540ce4be7bbb74691) for more details.

**Comment by jchristman** [comment]
👍

**Comment by benjamn** [comment]
This should be fixed if you do `meteor update --release 1.3.3-beta.0`.

**Comment by mhagmajer** [comment]
Thanks!

**Comment by sammkj** [comment]
@benjamn , it seems like 'jsx-control-statements' is not supported?

```
   While processing files with ecmascript (for target web.browser):
   module.js:338:15: Cannot find module 'babel-plugin-jsx-control-statements'
   at Function.Module._resolveFilename (module.js:338:15)
   at InputFile.resolve (/tools/isobuild/compiler-plugin.js:347:14)
   at InputFile.<anonymous> (/tools/isobuild/compiler-plugin.js:351:25)
   at InputFile.require
   (/home/skaxwng/.meteor/packages/meteor-tool/.1.3.3-beta.0.1knn4gn++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/compiler-plugin.js:353:23)
   at req (packages/babel-compiler/babel-compiler.js:209:1)
   at packages/babel-compiler/babel-compiler.js:214:1
   at Array.forEach (native)
   at infer (packages/babel-compiler/babel-compiler.js:212:1)
   at BabelCompiler.BCp._inferHelper (packages/babel-compiler/babel-compiler.js:232:1)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler/babel-compiler.js:163:1)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler/babel-compiler.js:150:1)
   at packages/babel-compiler/babel-compiler.js:92:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:40:1)
```

**Comment by myknbani** [comment]
It doesn't seem to work with `transform-decorators-legacy`.  I tried it with `gadicc:ecmascript-babelrc` and it seems to work fine.

I tried random transforms like simplify-comparison-operators and remove-console, and they are fine with Meteor 1.3.3-beta.0

```
/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/plugin.js:146:13:
   Plugin 0 specified in "base" provided an invalid property of "default"
   at Plugin.init
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/plugin.js:146:13)
   at Function.normalisePlugin
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:190:12)
   at
   /home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:30
   at Array.map (native)
   at Function.normalisePlugins
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:196:20)
   at OptionManager.mergeOptions
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:36)
   at OptionManager.init
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:506:10)
   at File.initOptions
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:243:89)
   at new File
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:159:72)
   at Pipeline.transformFromAst
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:72:16)
   at
   /home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:60:8
   at Cache.Cp.get
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/home/mykvanfifi/.meteor/packages/ecmascript/.0.4.4-beta.0.keqmrj++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:47:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:26:1)
   at packages/babel-compiler/babel-compiler.js:104:1
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/babel-compiler/babel-compiler.js:135:1)
   at packages/babel-compiler/babel-compiler.js:103:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:40:1)
   
   
=> Your application has errors. Waiting for file change.
```

Here's my .babelrc file:

```
{
  "presets": [
    "meteor",
    "es2015",
    "stage-1"
  ],

  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

**Comment by myknbani** [comment]
I also get the error `Method has decorators, put the decorator plugin before the classes one.`, when I try to use the "decorators-legacy" preset instead of the transform-plugin.  Perhaps load order issue as described here?

https://phabricator.babeljs.io/T2648#74400

**Comment by gadicc** [comment]
Hey @benjamn

Awesome news!  I'm glad the PR was helpful.  I'll be happy to help out where I can but realistically I won't have a chance until next week.  I did have a quick look over the code though and have some comments where hopefully you can benefit from my own experiences working on this (I was originally also `require()`'ing plugins directly, but had some cache/load-order issues within my own project goals of only modifying babel-compiler and not core).  I see some related issues came up in comments from others too, but hopefully this can serve as an all-inclusive list.

1. **Cache invalidation**.  The hash is [currently](https://github.com/meteor/babel/blob/188198cb8ee8c0bd70f9b4772dcce05d6cfe0ec5/cache.js#L58) on `meteorBabelVersion`, `source`, `options`.  Plugins are passed as functions but [functions aren't hashed](https://github.com/meteor/babel/blob/188198cb8ee8c0bd70f9b4772dcce05d6cfe0ec5/util.js#L48) in `util/deepHash`, so changes by the user to babelrc/package.json after initial compile will be ignored.  Quick & dirty would be to use `Function.toString()` and hope for no closures :D, and then I guess cache also by object ref for speed.  Ideal might be to pass the deps (plugin, version) along, and maybe allow a custom hash from the dev for direct plugins passed by function.  See my  [partially related PRs](https://github.com/meteor/babel/pulls) in `meteor/babel` (including a small performance gain by re-using `inputFile.getSourceHash()` related to dgrenspan's comments a while back).

1. The **`babel-preset`** / `babel-plugin` prefix is optional and is [tried preferentially](https://github.com/babel/babel/blob/dc1f40540de11045bb4714350350e012fee4f93e/packages/babel-core/src/transformation/file/options/option-manager.js#L324) as part of Babel's resolve process.  In general, that `options-manager.js` file is a handy reference, e.g. don't miss [plugin = plugin.__esModule ? plugin.default : plugin](https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/option-manager.js#L110) in **normalisePlugin**.

1. Massive, massive <3 for `inputFile.{readAndWatchFile,findControlFile,resolve,require}` :)

1. Regarding **`babel-preset-meteor`**, I had stopped forcing it in the code and instead asserted it existed in user presets for the two reasons below.  But overall this is probably a more minor issue as long as we can get `transform-decorators-legacy` to work, since it seems a looot of people are using this.  Related also to `react` and the `jscript` stuff.

  1. **Load order**.  Some presets needed to be loaded before preset-meteor, and (iirc) others after.  I'm a bit hazy on it now.  From what I recall there was also a commit to babel that reversed the array/order, which made it more complicated (I can't seem to find a ref now though).  The main issue was with `transform-decorators-legacy`, and I see you prepend additional plugins, so maybe it's ok.  Be aware that there's also a [preset](https://www.npmjs.com/package/babel-preset-decorators-legacy) that contains just this plugin, to help with load order.  I guess we'll see how people go with the beta.

  1. **Consistency** with non-Meteor tools.  I had a lot of queries involving either Meteor or an external mocha breaking, and this was because of a `.babelrc` that was mutually incompatible (e.g. using [babel-root-slash-import](https://github.com/mantrajs/babel-root-slash-import)).  It's quite nice to have a `.babelrc` that's consistent for a project rather than a tool; although it would be on the dev to ensure the correct runtimes are included.

1. Babel `env` section and `BABEL_ENV`, as you mentioned.

1. **Separate configs for client/server**, as discussed elsewhere (e.g. how to transform async/await).  It could be great if Babel supported a `BABEL_TARGET_ENV` or something for this, but they were against this (can't seem to find the issue now).  I allowed for a preferential `client/.babelrc` etc that could `extend` the root `.babelrc`.  There were some other issues at babel to blacklist certain plugins based on the env, which are possibly more mature now.  Note, the new version of react-hot-loader doesn't require a separate client config anymore, so I'm not aware of any immediate issues here beyond efficiency.

1. **Docs**.  Where should they go?  There are a lot of important comments in the code that we should get somewhere more readable.  And e.g. a working example for `transform-decorators-legacy`.  We could use https://github.com/gadicc/meteor-hmr/blob/master/docs/babelrc.md as a starting point.

As I said I'll be happy to help with some of this when I can, but can't make any firm commitment on when that could be right now.

**Comment by gadicc** [comment]
Thanks, @benjamn, for the quick work!  I updated my comment above to a checklist that reflects your changes.  Of the remaining points, I think the cache invalidation is the only really important one (and afterwards we could close this issue).

Confirming that `transform-decorators-legacy` is working, and as per your commit comments, any other load order issues that arise in the future can be addressed by the gradual move of plugins from the `meteor` preset to default plugins.

@sammkj, @myknbani, your issues above are fixed with `meteor update --release 1.3.3-beta.1` :)

@myknbani, you should also remove `meteor` from your presets section and `npm rm --save-dev babel-preset-meteor` (I'll update the meteor-hmr/babelrc docs to reflect this).  I'd also suggest removing `es2015` in the same way, it can conflict with some things in `meteor` preset which provides all the es2015 features anyway and in the way needed by Meteor (but let us know if you find something missing).

**Comment by myknbani** [comment]
Thanks @benjamn and @gadicc :D.  I've been trying to update, but I think I'm suffering from the geographical CDN issue as well.  I'll try it as soon as I can update.

**Comment by myknbani** [comment]
@gadicc Thanks for the info.  I noticed that it now transpiles things a little bit differently, but I'm no expert on that.  Things are working with the following as my .babelrc

```
{
  "presets": [
    "stage-1"
  ],

  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

And super thanks to @benjamn for the speedy fix!

**Comment by benjamn** [comment]
This will ship in Meteor 1.3.3, which you can try now by running `meteor update --release 1.3.3`. Note that we don't support `.babelrc` environments, yet, but we can revisit that for 1.4. Plugin import errors are no longer fatal, but print warnings in the terminal. If not having the plugin is really a problem, that will probably lead to fatal compiler errors.

Thanks for everyone's help with this feature, especially @gadicc!

**Comment by gadicc** [comment]
So great to have this in Meteor core now!  Very happy to have been able to contribute.  Thanks, benjamn!
