### ISSUE TITLE
Allow login handler to disable automatic resume tokens

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6386]
Revisiting #1891 now that FR's are kosher. Perhaps:
```
Accounts.registerLoginHandler( function(loginRequest) {
  ...
  return {userId: userId};
}, {dontResume: true});
```
Would a PR for this be accepted?

**Comment by zol** [comment]
Hey @lorensr . I'm not sure that this feature would be useful to enough people to include it in core. Perhaps I don't understand your use case well enough. What is an OTP link and how are standard users of your system related to those logging in over the 'OTP link'?

Would others find this useful? (comment with +1 if yes)

**Comment by lorensr** [comment]
Sorry, one-time password. I'm providing a URL that contains a temporary-use login token for a user to click in an email or sms (see eg Slack below), and I don't want the authentication to last past that session.

If the implementation in this comment doesn't have other downsides, then I'm happy to go with that: https://github.com/meteor/meteor/issues/1891#issuecomment-191835235


![image](https://cloud.githubusercontent.com/assets/251288/13620631/38a7f10c-e55f-11e5-9a0a-5ea67f12dca1.png)

**Comment by mitar** [comment]
Hm, wouldn't it be better maybe that at the login time we could somehow specify expiration? Like that it should expire after current session is closed. Or after some timestamp? So that behavior is similar to a cookie?

Currently Meteor does not allow control of this.

@lorensr: A workaround could be that you would on the server side use [`onConnection`](http://docs.meteor.com/#/full/meteor_onconnection) callback to register `onClose` callback. And then in `onClose` callback you simply clear the resume token in the database for that particular session. But downside is that if server instance crashes for some reason (could be maliciously invoked) callback might not be called. So it is better to store information about expiration into the database when token is stored there (similar to how it is for cookies).

But I would agree that Meteor is lacking more hooks into accounts. For example, `postSignUpHook` from meteor-useraccounts.

**Comment by mitar** [comment]
BTW, related: #3867

**Comment by lorensr** [comment]
Being able to configure expiration per handler, or better yet, per login / per resume token (`return {userId, expiresIn}`) would work, and would be preferable.

**Comment by mitar** [comment]
As a workaround, you can do that as well: you just have an extra Meteor method which stores into a local collection on the server this information. `onClose` callback then consults that local collection what exactly to do with a resume token in the database for that particular connection. (Connections have IDs, so you can easily store extra information about them.)

**Comment by zol** [comment]
Ah, got it. Both workarounds seem reasonable to me.

**Comment by lorensr** [comment]
@zol Thanks. I wouldn't want to depend on `onClose` for a security thing like this, but will go with the `setUserId` method. Re: custom resume token expirations, should I change the title of this, or close and create a new issue?

**Comment by zol** [comment]
Please close, re-open and reference. It's much easier to reconstruct the flow of the conversation later that way.

**Comment by lorensr** [comment]
Makes sense, thanks: #6451

**Comment by jedwards1211** [comment]
@zol @mitar I'm integration Auth0 with my app to manage authentication, and I'd rather always resume with the id token I get from Auth0 rather than using the builtin resume process.

As such, customizing token expiration isn't ideal for my use case; I'd like to be able to disable the automatic resume entirely.

**Comment by mitar** [comment]
I would suggest you open a new feature request?

**Comment by jedwards1211** [comment]
@mitar I decided to settle for a simple hack: I found the resume login handler in `Accounts._loginHandlers` and wrapped it with my own function that checks with auth0 if the resume handler succeeds.

**Comment by fgm** [comment]
@jedwards1211 similar problem here with another package. How did your technique end up ?

**Comment by jedwards1211** [comment]
Not to bad: https://github.com/jcoreio/auth0-meteor/blob/master/src/server/wrapResumeHandler.js

**Comment by fgm** [comment]
@jedwards1211 thanks for your answer. The page gives a 404, though: I guess the repo is private ?

**Comment by jedwards1211** [comment]
ah, it was for no particular reason, I just made it public so try again :)
