### ISSUE TITLE
[1.3beta12] Deploying the skeleton to Galaxy breaks at runtime

### ISSUE THREAD

**Issue by zol** [meteor/meteor#6400]
To reproduce:

```
$ meteor create --release 1.3-beta.12 g13hellotest
$ cd g13hellotest
$ DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy g13hellotest.thesnail.org --settings ~/Source/meteor-hello-world/settings.json 
```

**Comment by benjamn** [comment]
What's the runtime error?

**Comment by zol** [comment]
Ooops, forgot to include it, my apologies. Here:

![screen shot 2016-03-03 at 5 01 52 pm](https://cloud.githubusercontent.com/assets/81672/13514901/ad0062de-e161-11e5-938a-7011f353e47a.png)

**Comment by benjamn** [comment]
This is because `practicalmeteor:mocha` uses a `debugOnly` package that defines `__coffescriptShare.setupGlobals`, namely [`practicalmeteor:mocha-core`](https://github.com/practicalmeteor/meteor-mocha-core/blob/1790a305e259f0869078303ee70905701c51fb0e/package.js#L5). If you `meteor remove practicalmeteor:mocha` before deploying, it should work, though I certainly am not suggesting we should ship 1.3 with that caveat.

**Comment by tmeasday** [comment]
@zol I think it's OK for two reasons:

1. The skeleton in .13+ will *not* include a test driver
2. That driver is not correct (due to a miscommunicate between myself and @benjamn). You could try it with `avital:mocha` though

**Comment by zol** [comment]
We should remove test driver & tests from the skeleton app.

**Comment by tmeasday** [comment]
Already done!
