### ISSUE TITLE
[1.2.1] Accounts.sendVerificationEmail doesn't behave properly when called a second time

### ISSUE THREAD

**Issue by snajjar** [meteor/meteor#6410]
Hello all,
I'm using Meteor accounts (accounts-base and accounts-password).

When a user account is created, a verification email is set with a token (call it tokenA).
In MongoDB, i can see this token is set in **db.users.services.email.verificationTokens[0].token**
If the user click on the link, the email is set to verified and everything works fine.

I created a meteor method to let the user send again the verification email:

    Meteor.methods({
        'sendVerificationEmail' : function(userId, primaryEmail){
            Accounts.sendVerificationEmail(userId, primaryEmail, function (error) {
                if (! error) {
                    console.log('Verfication email sent');
                } else {
                    console.log(error);
                };
            });
        }
    });

When this method is called, another verification email is set.
But there, the token set in MongoDB **is not replaced**, it's still tokenA. As a consequence, the second validation link (with tokenB) won't work, it's still the link from the first validation email that will work.

**EXPECTED BEHAVIOR**: db.users.services.email.verificationTokens[0].token should be reset when calling Accounts.sendVerificationEmail again
**OBSERVED BEHAVIOR**: db.users.services.email.verificationTokens[0].token should is not reset when calling Accounts.sendVerificationEmail again

**Comment by stubailo** [comment]
Hmm, this doesn't seem correct:

```js
Meteor.users.update(
    {_id: userId},
    {$push: {'services.email.verificationTokens': tokenRecord}});
```

The above code appends the new token record to the user document in MongoDB. Then, when the token is clicked:

```js
var user = Meteor.users.findOne(
        {'services.email.verificationTokens.token': token});
```

The above code will find any token in that array, not necessarily just the first one.

Can you please create a reproduction I can run that demonstrates this issue? It doesn't seem like the problem is the one that you are describing (perhaps there is a different problem, but I can't find it unless I have some code to run). Here are directions for submitting a reproduction: https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor

**Comment by snajjar** [comment]
Hello,

I've done a reproduction (https://github.com/snajjar/meteor-issue-6410) but things works well on it.
I don't know how i found myself in a situation in which only the first validation link was working and not the following ones, but i'm not able to reproduce anymore.

Thank you for your help, @stubailo.
Best regards,

Sebastien
