### ISSUE TITLE
Docs site: find doesn't scroll on iOS

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6413]
Normally when I use iOS Chrome's `Find in Page...`, and I hit the up/down arrows at top, Chrome scrolls the page to bring the nth occurrence into view. For docs.meteor.com, the page doesn't scroll.

![2016-03-04 12 36 22](https://cloud.githubusercontent.com/assets/251288/13535099/79ee3696-e206-11e5-8b50-87b4f58b4446.png)

**Comment by stubailo** [comment]
This is because the scrolling part is inside a div, to enable the sidebar functionality. To be honest the experience of the docs app on mobile is pretty bad overall, so I think the only way to go is to eventually do a complete rewrite. I'm going to leave this open so that we can be aware of this issue when we do that.

**Comment by lorensr** [comment]
Fixed, thank you @tmeasday 🙌😊
