### ISSUE TITLE
Packages replacing/patching Mongo.Collection can break other packages and rely on load order

### ISSUE THREAD

**Issue by DrDanRyan** [meteor/meteor#6416]
My app runs fine with the normal `meteor run` command, but if I add the `--production` flag, then the minification/bundling process seems to break the load order, both of my packages from Atmosphere and my own code. In particular I get two errors with the `--production` flag that do not appear otherwise.

The first is from the `vsivsi:files-collection` package throwing:
`Uncaught Error: [The global definition of Mongo.Collection has changed since the file-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before file-collection.]`
Currently files-collection is at the bottom of my .meteor/packages list. I thought that this should make it load after other packages... am I wrong?

The second comes from angular complaining that it couldn't find my main module definition:
`Uncaught Error: [$injector:modulerr] Failed to instantiate module marymahoneyApp due to: Error: [$injector:nomod] Module 'marymahoneyApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`
The angular module is defined in client/lib/app.js and no other code that relies on the module is in a lib folder, so it should be loading before them (and indeed it does without the `--production` flag)

I am using Meteor 1.2.1.

**Comment by stubailo** [comment]
> Currently files-collection is at the bottom of my .meteor/packages list. I thought that this should make it load after other packages... am I wrong?

Yeah, I don't think the order of the packages file affects when the packages are actually loaded. That is determined by analyzing the dependency graph of the packages themselves.

It's possible that somehow you might have some development-only packages that cause the load order to be different in production, although I've never encountered this before. Could you please post a reproduction of the issue in the form of an app we can run? If it's a result of a specific combination of packages you are using, then there isn't much we can do to identify the issue without your help to reproduce it. Here are directions for submitting an issue report: https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor

Thanks!

**Comment by DrDanRyan** [comment]
I figured out that both errors are actually the result of `vsivsi:file-collection` throwing the first error, which then prevents the app from bootstrapping properly. Apparently there has been some problems with `vsivsi:file-collection` playing well with any package that monkey-patches `Mongo.Collection`: https://github.com/vsivsi/meteor-file-collection/issues/61#issuecomment-124293863

In this case it stems from `dburles:mongo-collection-instances` which is a dependency of `angular-meteor-data`.

I am still not clear why there is a difference between development mode and `--production` mode though.

**Comment by stubailo** [comment]
Can you put together a simple app that uses both of these packages and demonstrates the issue? (different behavior in development and production)

**Comment by DrDanRyan** [comment]
sure, no problem, will push it to Github in a few minutes

**Comment by vsivsi** [comment]
Hi @stubailo author of `file-collection` here...  I've reproduced below my perspective on this issue.

To be clear, these issues aren't because other packages are "monkey patching" `Mongo.Collection` in the traditional sense. These errors arise because other packages are **replacing/redefining** `Mongo.Collection` with their own (perhaps buggy) implementation that wraps the original.

The issue for file-collection is that when it loads, `Mongo.Collection` == X; but when it is later called (e.g. `new FileCollection()`), `Mongo.Collection` == Y.  This causes problems because file-collection is written in Coffeescript and the FileCollection object extends (inherits from, but does not modify) `Mongo.Collection`. When the definition of `Mongo.Collection` changes between when `FileCollection` is defined and when it is used, then all hell breaks loose.

I have wasted hours trying to debug problems reported by users of my packages that came down to bugs in packages that replace `Mongo.Collection`. It irritated me so much that I wrote `vsivsi:meteor-defender` to make it possible to easily see which packages are doing what to the Meteor system calls.

Here's the fundamental issue: Any package that uses `Mongo.Collection` has a potential implicit dependency on other packages that replace it. The point of packages like `collection-hooks` or `mongo-collection-instances` is to add features to the vanilla Mongo.Collection. Unlike `file-collection`, they don't do this by creating a new 'extended' collection type, they do it by replacing Meteor's implementation. Loading these packages creates a global side-effect that can impact other packages, depending on load order.  

Here's where the dependency comes in... File-collection doesn't depend on any such packages, but apps that use `file-collection` might want `FileCollection` objects to implement say, `collection-hooks`. That's great, I support that, and it totally works, so long as `collection-hooks` loads and performs its magic *before* `file-collection` loads. When it loads *after* `file-collection`, then at best your `FileCollection` objects won't have `collection-hooks` extensions, and at worst `file-collection` is destabilized because the version of `Mongo.Collection` it is an `instanceof` is no longer the version that is globally defined.

So the implicit dependency here comes either from the app developer ("I want `FileCollections` to have `collection-hooks`"), or even more likely, from the developer of some other package (e.g. `angular` "I want `Mongo.Collection` to have `mongo-collection-instances`"). The problem is that the dependency is transmitted silently through replacement of Meteor provided objects, rather than the explicit definition of new extended types that are `SomeExtendedType instanceof Mongo.Collection == true`.

This accepted way of doing things in the Meteor ecosystem is a bad practice, it makes the system difficult to debug and reason about, and it has been a real pain-point for many users. The fact that the production package loading mechanism appears to have no way for a developer to explicitly say "I want Package A to depend on global side-effects on the definition of Meteor system objects made by the loading of Package B" is a major deficiency, if we are to go on accepting that wrapping and replacement of Meteor defined objects is an acceptable practice.

**Comment by vsivsi** [comment]
Just to briefly add... This isn't just a Coffeescript issue.  ES6 defines the same type of `ClassY extends ClassX` mechanism. So this can also happen in ES6:

```js
var ExtendedCollection = class extends Mongo.Collection {
   constructor() {
      if (!(this instanceof Mongo.Collection)) {
         throw new Error("WTF!");  
      }
   } 
}
```

**Comment by DrDanRyan** [comment]
I had an example app earlier today where the development mode `meteor run` resulted in no errors and `meteor run --production` resulted in `file-collection` throwing and `angular` failing to bootstrap. However, right now I can't come up with a configuration where `file-collection` does not throw in development mode. I am not sure if there is a race condition that caused this change in behavior (like `file-collection` was loading after `angular` before and now it is happening the other way), or maybe a package got upgraded this afternoon.... really weird. Even my original app that started this whole issue for me is always having `file-collection` throw every time `new FileCollection()` is called, and it had not done that at any point in the 5 months I have been working on it until today.

The only difference at this point is that in development mode `angular` will still bootstrap fine and the app will work. With the `--production` flag, the error thrown by `file-collection` (which is loading before the declaration of the main angular module) results in the app not bootstrapping correctly. I assume this is a result of the .js files being concatenated in `--production` but the angular bootstrap coming from a separate .js file in development?

I put up a sample project showing this behavior if you are interested:
https://github.com/DrDanRyan/production-flag-test

**Comment by vsivsi** [comment]
I just tested with the sample project and I see no indication that file-collection is throwing in either development or --production mode.  In production mode, there are errors in the browser console:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 2eb944955a364e3ae33a6210426ccb7262bfcd5e.js:109:8147
Error: 
 2eb944955a364e3ae33a6210426ccb7262bfcd5e.js:3:3334
Error: [$injector:modulerr] Failed to instantiate module clickBot5000 due to:
[$injector:nomod] Module 'clickBot5000' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=clickBot5000
r/<@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:433
r/<@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:10100
t@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:9571
r@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:9885
p/<@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:18752
o@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:857
p@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:18600
tt@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:20290
se/s@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:7623
se@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:7935
ae@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:92:7181
@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:98:28413
ie.Callbacks/c@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:60:5989
ie.Callbacks/d.fireWith@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:60:6811
.ready@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:60:8668
s@http://localhost:3000/2eb944955a364e3ae33a6210426ccb7262bfcd5e.js?meteor_js_resource=true:58:1198

http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=clickBot5000&p1=%5B%24injector%3Anomod%5D%20Module%20'clickBot5000'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3DclickBot5000%0Ar%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A433%0Ar%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A10100%0At%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A9571%0Ar%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A9885%0Ap%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A18752%0Ao%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A857%0Ap%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A18600%0Att%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A20290%0Ase%2Fs%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A7623%0Ase%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A7935%0Aae%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A92%3A7181%0A%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A98%3A28413%0Aie.Callbacks%2Fc%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A60%3A5989%0Aie.Callbacks%2Fd.fireWith%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A60%3A6811%0A.ready%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A60%3A8668%0As%40http%3A%2F%2Flocalhost%3A3000%2F2eb944955a364e3ae33a6210426ccb7262bfcd5e.js%3Fmeteor_js_resource%3Dtrue%3A58%3A1198%0A
```

**Comment by DrDanRyan** [comment]
Strange... this is what I get after a fresh `git clone` and `meteor` (development mode) in the console (Chrome):
`Uncaught Error: [The global definition of Mongo.Collection has changed since the file-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before file-collection.]`

and with `--production`:
`Uncaught Error: [The global definition of Mongo.Collection has changed since the file-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before file-collection.]o @ 9ce7bd6e2a35285966b632746f09c95a19c8fa26.js?meteor_js_resource=true:69(anonymous function) @ 9ce7bd6e2a35285966b632746f09c95a19c8fa26.js?meteor_js_resource=true:117(anonymous function) @ 9ce7bd6e2a35285966b632746f09c95a19c8fa26.js?meteor_js_resource=true:117
9ce7bd6e2a35285966b632746f09c95a19c8fa26.js?meteor_js_resource=true:92 Uncaught Error: [$injector:modulerr] Failed to instantiate module clickBot5000 due to:
Error: [$injector:nomod] Module 'clickBot5000' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

**Comment by vsivsi** [comment]
Very strange indeed.  I don't know what else to say beyond the manifesto I posted above...

**Comment by stubailo** [comment]
@vsivsi really glad you posted this! I completely agree that this kind of overriding of `Meteor.Collection` is an anti-pattern. If it makes you feel a bit better, we recommend something much better in the guide:

http://guide.meteor.com/collections.html#hooks

There are couple of interesting points/questions here:

1. There is no way in Meteor to specify load order of packages.
2. Many packages rely on monkey-patching to do stuff which should be done via mixins or inheritance.
3. Many packages do stuff when they are loaded, rather than at app startup time, which causes some things to depend on the load order of packages, which is ill-defined.

A question for you: what issues arise from `! (FileCollection instanceof Mongo.Collection)`?

**Comment by DrDanRyan** [comment]
I performed a `git bisect` to try to determine what caused my real app to start throwing the `file-collection` error in the browser console in dev mode. It turns out that removing the `meteortoys:allthings` package made this error start showing up. For some reason, including this package suppressed the message (probably affected load order in some way).  This info doesn't really help solve the problem of the `--production` error and fail to bootstrap, but I figured any extra insight might be helpful.

**Comment by vsivsi** [comment]
@stubailo   In answer to your question, here's one example:  https://github.com/vsivsi/meteor-file-sample-app/issues/2#issuecomment-120780592

As I said in my "maifesto" above, the main issue is that this prevalent "anti-pattern" has made maintaining and supporting my own (popular and reasonably well-behaved) packages a pain in the butt.

The `throws` that @DrDanRyan is encountering were introduced to the code by me inform other developers when detrimental implicit package interactions are likely to be occurring, rather than allowing them to pass silently and manifest later in difficult to reproduce and diagnose bugs that inevitably land as issues filed against my packages.

Before introducing these prophylactic tests at load time, I wasted literally days chasing phantom bugs reported against my projects that turned out to be caused by poorly behaved "anti-pattern" packages that the reporting developers didn't even realize were being included in their apps. Fed-up with this monumental waste of effort, I added these checks to defend my own time and sanity.

Anyway, if Meteor has no intention of allowing app developers to control load ordering (a decision I support), then packages that replace Meteor system defined objects at load time have no place in the ecosystem, and I will simply refuse to provide any support for my packages in any app that uses them.

The question for @DrDanRyan is, where is the dependency on `mongo-collection-instances` coming from in his app?  `angular` doesn't directly require it, and it has no non-dev dependencies, so what other package is using it? Because eliminating that dependency is key for the stability of your application.

**Comment by stubailo** [comment]
I think this is actually a real issue, so I'm going to reopen it with a different name! The conversation here is too interesting to leave closed.

**Comment by stubailo** [comment]
@zol curious what you think of this issue.

**Comment by DrDanRyan** [comment]
I also found these issues over at angular-meteor:
https://github.com/Urigo/angular-meteor/issues/644
and
https://github.com/Urigo/angular-meteor/pull/1232

It looks like there is no need for the `mongo-collection-instances` package with new versions of Meteor, but there is some worry about removing it from `angular-meteor` because they don't want to break support for older versions of Meteor

**Comment by zol** [comment]
@stubailo and others - this is a real issue and I don't have a suggested short term fix. Javascript best practices call for avoiding the use of globals, avoiding modifying objects you don't own and using a module loader (now es2015 import/export) to control load order. I believe adhering to these rules would prevent this kind of issue and highlights why we're moving Meteor towards using modules and Npm.

**Comment by vsivsi** [comment]
Another example of an obscure/nasty/time consuming bug showing up as a result of this global object monkey-patching "anti-pattern":  https://github.com/dburles/meteor-collection-helpers/issues/73

**Comment by hwillson** [comment]
Hi all - we've been pushing hard over the past while to get issues here cleaned up as much as possible. Part of this push involves making sure feature requests are now managed within the http://github.com/meteor/meteor-feature-requests repo. While this issue could be considered a bug (as Meteor allows `Mongo.Collection` overriding/replacing, which can lead to issues if 3rd party package authors are expecting the capabilities of the original `Mongo.Collection` to be available, and they have been overridden), it is functioning as originally designed. Changing the way this currently works would be a significant undertaking, and would need to be handled extremely carefully (especially with regards to backwards compatibility). As such, I don't believe the work involved here could be considered a bug fix - this is a significant change/feature request.

This feature request will be closed here, but anyone interested in migrating this feature request to the new FR repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Packages%20replacing%2Fpatching%20Mongo.Collection%20can%20break%20other%20packages%20and%20rely%20on%20load%20order&body=Migrated%20from:%20meteor/meteor%236416) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
