### ISSUE TITLE
Allow control of build targets per `meteor run`

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6417]
When I'm in development, and I change a file, the server rebuilds. A few of the messages it gives me are:

```
Building for web.browser                  /
Building for web.cordova                  /
Building for os.osx.x86_64                \
```

I'm not sure what the third is for, but it spends a few seconds every time on the second. Usually I'm developing in chrome device mode with `meteor run`, not on an emulator or device with `meteor run ios`. 

Is `Building for web.cordova` necessary in order to display just a web page in Chrome? If not, it would significantly improve my rebuild time if it was skipped. Perhaps it can by default be skipped on a plain `meteor run` – and just happen on `meteor run ios/android`? Or perhaps I can provide a env var – `CORDOVA=0 meteor run`?

**Comment by martijnwalraven** [comment]
Building `web.cordova` is not necessary to develop in the browser, so it may indeed make sense to skip it when not running on mobile targets. This would mean that an already running mobile app connecting to the local development server would no longer receive hot code pushes though.

**Comment by lorensr** [comment]
Wow. That was fast 😍

**Comment by chip** [comment]
I'd definitely be interested in this feature. @lorensr - As a workaround (hack) I delete the **ios** line from `.meteor/platforms` just to speed things up since some of my builds were getting lengthy. It works well for me since most of my development is done in the browser, so I only periodically test in **ios**. Maybe that'll work for you until this feature is in place?
