### ISSUE TITLE
1.3 beta.12 bug - Testing local packacge

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#6424]
It looks to me that the new builder is not properly handling `packages` directory.

When I have `packages/foo` symlink pointing to a local package and do `meteor add foo`, all the build logs in that package would appear twice. I further discovered that in the first build `getPackageName` returns the correct package name, `"foo"` in this case, while the second build shows `null`. This tells me that the app builder is handling the local package as part of the app even after the package builder has already done what's supposed to happen.

For non-local packages the second build doesn't appear.

**Comment by abernix** [comment]
I believe this is fixed.  Can you reproduce this in Meteor 1.4.2+?

**Comment by Zodiase** [comment]
@abernix I'll take a look again.

**Comment by Zodiase** [comment]
@abernix Here's the reproduction for your convenience: https://github.com/Zodiase/Meteor-Tests/tree/meteor-issue-6424
The issue is actually worse now. The second build now appears for non-local packages as well. As the logs from package `zodiase:mdl` show.

And this is how it was (before 1.3): https://github.com/Zodiase/Meteor-Tests/tree/meteor-issue-6424-meteor-1.2.1. In this rep, the builder only detects files from the app, not the packages.

**Comment by hwillson** [comment]
Hi @Zodiase - I've run through your reproduction, but I'm having a bit of difficulty seeing the demonstrated issue. Could you be more specific about how the issue you've outlined is being shown by your reproduction? It looks like everything being logged is correct, based on the way you've defined/configured your `MultiFileCachingCompiler`. If you can let us know exactly where the problem is demonstrated in your repro, that would greatly help with troubleshooting. Thanks!

**Comment by hwillson** [comment]
We haven't heard back on the extra details requested in https://github.com/meteor/meteor/issues/6424#issuecomment-284463672, so I'll close this for now. Happy to re-open if you're able to provide the additionally requested information. Thanks!
