### ISSUE TITLE
Feature request: promisify all callback functions by default.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#6450]
Since ES6 is more standard in Meteor now, I think it might follow to use Promises instead of callbacks wherever possible. It also reads more smoothly. Take `Accounts.resetPassword` for example.

**with callbacks**

```
Accounts.resetPassword(token, password, function (err) {
  if (!err) {
    FlowRouter.go('User.profile', { _id: Meteor.userId() })
  }
});
```

**with promises and async/await**

```
await Accounts.resetPassword(token, password);
FlowRouter.go('User.profile', { _id: Meteor.userId() });
```

**Comment by servermeta** [comment]
could it be done automatically via a package maybe, so this could be applied to external libraries also?

**Comment by stubailo** [comment]
I think this is a great idea! next on the list after integrating ES2015 and modules is cleaning up our APIs to work better with these new features (for example, features like `Meteor.publish` don't currently work well with arrow functions because they rely on `this`).

I think @benjamn is very excited about the possibilities here. I don't exactly know the best way to move forward, but let's revisit it after 1.3 release.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Feature%20request%3A%20promisify%20all%20callback%20functions%20by%20default.&body=Migrated%20from:%20meteor/meteor%236450) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
