### ISSUE TITLE
[1.3-beta12] cordova/mobile app white screen of death on random resumes

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#6471]
I'm getting a 'white screen of death' on 1.3-beta12. It never happens on an initial app load. When it does happen, it ALWAYS happens on a mobile app resume, never on first load or when using the app repeatedly then going back to it -- just on a resume after some time. I need to close the app and reopen it for things to start working again.

This is on iOS.

I cannot reliably reproduce it. A given scenario is open app initially, hit home button, and let it sit a while (couple hours). Open it back up, and white screen appears. The site never loads again. You need to close the app and reopen it, then everything works again. More times than not everything works, but randomly there is a white screen of death.

This has happened to me more than once. Typically, 2-3 times a week of repeated usage.

How can I remote debug this to find out more information? I'm using Kadira, however nothing is logged. It is also not considered an 'App Crash' in iTunes Connect.

It's possible this is related to https://github.com/meteor/meteor/issues/6346, however I don't believe hot code push is involved at all because no new updates are deployed to the servers when this happens.

**Comment by zol** [comment]
Hi. Please try updating to the latest beta 16. A starting point for debugging could be adding a callback for when your app resumes (https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.resume.html) and logging whether this is called. cc @martijnwalraven

**Comment by markoshust** [comment]
@zol I can't test with beta 16 because of this ticket https://github.com/meteor/meteor/issues/6449

**Comment by martijnwalraven** [comment]
#6459 has been fixed in `1.3-rc.1`, so hopefully you should be able to test this now.

Does your issue occur both in development and production? Could you try running the app from Xcode (`meteor run ios-device`) and see if any errors are printed in the console output? Could you also try remote debugging using Safari, and looking at console output there?

**Comment by markoshust** [comment]
@martijnwalraven thank you. I'm now on `1.3-rc.1` and same issue happening. I've never received this on development (or locally with Xcode), but have within TestFlight and App Store deployments. I don't get any errors when running through Xcode, or remote debugging with Safari.

Everything works great, until this happens. It appears random. 

@zol understood, but how should I make a callback here and what should it do? it's random, only happens in TestFlight/App, and only on resumes (only sometimes).

**Comment by zol** [comment]
@markoshust - I don't understand your question. I'm saying add some code to log when the resume callback fires to better understand the behavior when it fails. In particular, when you see the white screen does the callback fire (implying that Cordova is loaded) or not.

**Comment by markoshust** [comment]
How am I supposed to know the callback fired (or not)? The app is in
TestFlight / App Store. Is there some sort of remote debugging tool out
there that I can install that will persist the data on a crash? How do I
retrieve the result of the callback when the app has died and I have to
restart it?

**Comment by martijnwalraven** [comment]
Remote debugging is disabled for production apps, so there is no easy way to get logging output from an app in TestFlight / App Store.

I think your best bet is to try and reproduce the issue locally. Have you tried running the app though Xcode and repeatedly letting the app go in the background (by going to the home screen and waiting at least 3 minutes) and resuming it?

**Comment by markoshust** [comment]
Thanks for the suggestion, I'll do some extra testing through local Xcode
to see if I can replicate this consistently.

**Comment by v3rron** [comment]
having the same issue here... working great on development and web... but when building for ios it's stuck on white screen after splash screen without any crash errors logged

**Comment by markoshust** [comment]
Here are a few errors Kadira is throwing -- this has been happening for some time. Perhaps related to this, thought it may be helpful?

![screen shot 2016-03-19 at 9 25 05 am](https://cloud.githubusercontent.com/assets/437029/13898814/b6b77a42-edb4-11e5-90f4-7b051089daff.png)
![screen shot 2016-03-19 at 9 25 25 am](https://cloud.githubusercontent.com/assets/437029/13898815/b6b7a792-edb4-11e5-9f33-ac4709c95d8c.png)
![screen shot 2016-03-19 at 9 25 40 am](https://cloud.githubusercontent.com/assets/437029/13898816/b6b8643e-edb4-11e5-9932-78127c580e88.png)
![screen shot 2016-03-19 at 9 25 47 am](https://cloud.githubusercontent.com/assets/437029/13898817/b6b91aaa-edb4-11e5-8f3d-b5e8c1af7b4b.png)

**Comment by markoshust** [comment]
Very happily, I have yet to receive this bug on any of the release candidate tags. Things appear very stable right now.

I cannot consistently reproduce this issue, or even see this issue anymore, so I'm going to close this ticket out. Perhaps it was caused by some JS bug. Anyways, I'll reopen it if it happens again in the future.

**Comment by martijnwalraven** [comment]
Really good to hear! Please reopen if you experience the issue again.

**Comment by pmwisdom** [comment]
Hey @martijnwalraven  I've seen this in one of the ios app's i've been working on lately. Its only the production application, my staging application works fine, as well as my local environment. Makes no sense since staging and production have the exact same code right now, both hosted on galaxy, etc. 

I did a little digging and didn't come up with too much. I did get a debuggable version of my production application on my iphone and white screen still occurred, so app store affecting it is also out of the question. The repro steps are to get a white screen are -

1. Launch (Debuggable) App 
2. Launch safari and open web inspector
3. Click ios power Button (Turn screen off) while app is still in foreground
4. Wait, web inspector will automatically close when white screen has happened (this means the webview possibly shut down?)
5. Turn screen back on on iphone, see white screen. 
6. Look back on safari, you won't be able to open another web inspector for the application

So I also launched the app and looked in the xcode logs, this is all I saw:

[INFO] GCDWebServer stopped  <-- (Turn screen off)

[INFO] GCDWebServer started on port 12648 and reachable at http://localhost:12648/ <-- (Turn screen on)

**Comment by pmwisdom** [comment]
Heres are some graphs from xcode. I did a comparison of when the app is in the background (click home button, put app in background, turn off screen) vs when the app is in the foreground but the screen is locked.

App In Background & Screen turned off
White screen does not occur when background traffic dies.
![App Background] (http://i.imgur.com/ja9tcKA.png)

App In Foreground & Screen turned off (Which produces white screen)
White screen occurs when the background traffic dies here.
![App Foreground] (http://i.imgur.com/Lg2pqBv.png)

**Comment by NawazKhanMd** [comment]
do we need a virtual host to run my meteor app on mobile?

cuz am running meteor run android-device -p MyIp:3000 --mobile-server virtualHostIpToWhichMobileIsConnected:3000

this gives me a blank screen

am i doing it wrong pls Reply :)
