### ISSUE TITLE
Audio signal if error prevents Meteor restart 

### ISSUE THREAD

**Issue by rolandkofler** [meteor/meteor#6475]
## Why we need an error signal
During development, Meteor restarts on every file change. The page refresh is not always fast and the developer waits to check his modifications. Often he waits longer and after a while, he checks if Meteor server was able to restart. This unnecessarily hinders the flow of work and the train of thoughts of the developer.

## What should it do
If we had the option for a console beep if Meteor can't restart

`=> Modified -- restarting.
=> Errors prevented startup:`

Then the developer would quickly check the console tab, Identify the error and correct it. 
The flow of work is less strained because the source of error is narrowed down much faster.

**Comment by lassombra** [comment]
https://www.npmjs.com/package/beepbeep

just to get a start.  This would be an awesome feature.  I always code with music playing, so I am listening to audio!

**Comment by stubailo** [comment]
Would it be better to instead have the browser beep, or have an error overlay in the browser? That way you don't need to look at your console at all.

**Comment by rolandkofler** [comment]
Error in browser is an old server side rendering tradition. Seems to be logic if the whole site is rebuilt after the error anyway. Beep is just a blink faster to implement and independent from output device, thinking at smartwatches, and lassombra promised a pull request ;-)

**Comment by lassombra** [comment]
@stubailo a beep would be a relatively quick fix.  Getting the browser to show the issue automatically would require either some tweaks to how sockjs is used by ddp-client package as a client only fix _or_ a significant change to the meteor tool so that the ddp server stays up and then the ddp client can handle special error messages and do a pop up of sorts.  The other thing is that this would have to be a development only change as we definitely would not want to see such messages in production, however useful they might be on the server console.

I'm more than willing to tackle both options, but I think the first option could possibly make it in time for a 1.3 release while the second one would be significantly longer and certainly wouldn't make it into 1.3

Perhaps option 1 and then option 2 down the road when time permits?

**Comment by stubailo** [comment]
Actually I think I could implement a browser beep in about 20 mins without worrying about sockjs at all. Let me try, hope to have something this evening.

**Comment by lassombra** [comment]
I didn't realize you were referring to just a beep on the browser.  Yeah, that could be done by just handling the error when connecting to the server.

The way I read your original response was that you wanted to display the actual error in the client, which is a bit more work.  Doable, but work.

**Comment by trusktr** [comment]
Maybe also an (optional?) desktop notification!

**Comment by stubailo** [comment]
> Maybe also an (optional?) desktop notification!

Already have it! Publishing soon, just have to iron out the edges.

**Comment by lassombra** [comment]
Awesome.  Look forward to having that to work with!

**Comment by stubailo** [comment]
Check it out guys!!!

https://github.com/stubailo/meteor-dev-error-overlay/

Improvements and PRs really appreciated, there's a lot we could do here!

**Comment by lassombra** [comment]
Ok, I see what you did there.  I was thinking that it would actually catch ddp connect errors, but that polling works as well.  It's functional, and does exactly what is needed.  Thank you!

I'm already thinking about how I would integrate it into DDP though to get rid of that poll loop.  But that's just me!  Also, lol at improvement idea #2: Improve sound playing functionality to not use a sketchy YouTube embed.

**Comment by stubailo** [comment]
> how I would integrate it into DDP though to get rid of that poll loop.

I don't actually see how that would be beneficial - this way, it actually catches errors _faster_ than the DDP client actually realizes they are happening. And it actually reconnects faster than Meteor does by default: https://github.com/stubailo/meteor-dev-error-overlay/blob/6eb1ef77661292475b9b599dff02f2724d25e359/dev-error-overlay.js#L35

That's because this package polls more frequently than Meteor itself does. I think we should change the Meteor reconnect logic to do this as well, but that's more work.

**Comment by lassombra** [comment]
Perhaps not, but I'd like to clean up the console log spam that this creates as a result of a failed build (lots of 404s, one for every half second of the rebuild time).

Also, I have a personal vendetta against polling loops, though this one is debug only and pretty small, so it really isn't an issue.

In short, you are probably right and I'm trying to over engineer a simple solution.

**Comment by stubailo** [comment]
> I'd like to clean up the console log spam that this creates as a result of a failed build (lots of 404s, one for every half second of the rebuild time).

Please do! I'd love to accept a PR and also add you as a collaborator if you'd like to make additional improvements. For example, we could also have a better screen for when your server is stopped entirely, and maybe a way to toggle the overlay in case you still want to see your app UI.

> this one is debug only

Yeah, that's why I feel it is OK. And the fact that it doesn't require deep integration with DDP mechanics is a bonus, since that makes me feel like it won't break anything else.

Going to close the issue, let's open issues on the package to discuss new features and collaboration!
