### ISSUE TITLE
Allow untrusted updates when _id is included but selector size > 1

### ISSUE THREAD

**Issue by jdconley** [meteor/meteor#6486]
I was just adding some basic optimistic concurrency control to a Meteor (1.2.1) project and ran into an issue. Meteor/minimongo doesn't allow untrusted code to do multi-document updates (good). But, I believe it is also a tad too restrictive in how that is accomplished.

I would like to do optimistic concurrency with simple version numbers. Every time a document is updated the 'version' field is incremented. That means that a document should not be updated unless the candidate version was based on the version that is currently in the database. My update code looks roughly like this:

```
let curVersion = myModel.version;
myModel.version++;
myCollection.update({ _id: myModel._id, version: curVersion }, { $set: myModel }, 
    (error: Meteor.Error, numAffected?: number) => {
                if (!error && !numAffected) {
                    // Nothing updated, but no error -- either doc no longer exists or version didn't match
                } else {
                    // Error occurred or doc was updated
                }
            });
```

The restrictive code is here in minimongo: 
https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/minimongo/objectid.js#L13

```
// Is the selector just lookup by _id (shorthand or not)?
LocalCollection._selectorIsIdPerhapsAsObject = function (selector) {
  return LocalCollection._selectorIsId(selector) ||
    (selector && typeof selector === "object" &&
     selector._id && LocalCollection._selectorIsId(selector._id) &&
     _.size(selector) === 1);
};
```

Since selectors on the top level are implicitly AND'd, as far as I know that check for the size of the selector being "1" is not required. The update will have already been limited to a single document based on the _id selector.

Removing the size check would allow the above optimistic concurrency code, or any other conditional updates where database atomicity is desired in the update conditions. For now I just monkey patched this.

**Comment by stubailo** [comment]
I think the best way to implement your code would be to move to using Meteor methods instead of allow/deny security. Those allow any kind of optimistic code because code inside a method is always trusted.

I expect a future version of Meteor will drop support for allow/deny entirely and allow developers to implement it themselves on top of Methods if they really really need to, since it's very hard to reason about the security of passing different kinds of selectors from the client.

Specifically in this case, allowing an update with additional selectors allows you to read fields from the server which aren't published to the client by doing many queries until they return something. That is why this restriction exists, and it is very hard to understand any security implications to changing that logic.

You can read more about our current recommendations for Methods and optimistic UI in the Meteor Guide: http://guide.meteor.com/methods.html
