### ISSUE TITLE
[1.3-rc.2] "meteor build" swallows NPM dependencies declared in package.json (?)

### ISSUE THREAD

**Issue by csillag** [meteor/meteor#6521]
With 1.3, we can have a `package.json` in the root directory of the Meteor app, and declare NPM dependencies there. This works great.

However, when I do a `meteor build` (to prepare the app for deployment), this `package.json` file doesn't make it to the created bundle. A `programs/server/package.json` will be generated during the build process, but it won't contain the dependencies declared in the `packages.json`. Therefore, those modules won't be installed when deploying the created bundle.

Is this a bug, or am I missing something?

**Comment by clayne11** [comment]
Are you importing the packages that you want to be using?

**Comment by benjamn** [comment]
I think the `package.json` file you're seeing contains only what the runtime module system needs: the `name`, `version`, and `main` properties from the `package.json` file. The `dependencies` field isn't needed because we don't actually run `npm install` after deploying. Instead the build process copies the `node_modules` you installed locally into the bundle that gets deployed. One benefit of this approach is that you don't actually have to use `npm` to populate your `node_modules` directories. You could, for example, check your `node_modules` into version control (not that I recommend that, but it's a valid alternative).

If you need to access more properties of `package.json` at runtime, just import it with `import {dependencies} from "./package.json"` or `require("./package.json").dependencies`.
