### ISSUE TITLE
Meteor@1.3-beta.12: why do you have to include native node libraries to have them browserified?

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#6550]
So take an example simple package. You have a common file like this.

```
import {EventEmitter} from 'events';

export class SpecialClass extends EventEmitter {
  constructor() {
    super(...arguments);
  }
}

export default SpecialClass;
```

It seems it doesn't work. However, if you add this line to the package.json, it will work:

```
Npm.depends({
  'events': '1.1.0'
});
```

Why is this?

**Comment by benjamn** [comment]
The official recommendation is that you `npm install meteor-node-stubs` in you application, which will give you all the usual native library stubs at once. This makes the stubs available to packages as well as your application code. Only the stubs you use will be bundled into your app.

As to why: client-side stubs are fake, partial implementations of the built-in modules found in Node, so you should have the option of installing a custom version that implements your desired behavior. Making that choice automatically for you might seem convenient… unless it isn't what you need, which is why we let you install your own stubs (while providing `meteor-node-stubs` if you want to use that).

**Comment by AlexFrazer** [comment]
Ah okay; seems like just a documentation thing then

thank you for the help
