### ISSUE TITLE
[1.3-rc.8] possible issue with third-party lib on client, cannot find module 'fs'

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#6578]
I put together a sample repo of this bug at: https://github.com/markoshust/meteor-keen-js

I don't know if the bug is caused by Meteor, or by the `keen-js` npm lib. However, I'm receiving the following error in the client when running it:

```
Uncaught Error: Cannot find module 'fs'
```

**Comment by jdrydn** [comment]
If Meteor doesn’t use the standard `node` libraries or hasn’t mocked `fs` properly then that’s the error you’re gonna see!

**Comment by markoshust** [comment]
Tagging https://github.com/meteor/meteor/issues/6266

**Comment by benjamn** [comment]
You can install whatever mock Node libraries you want, but an easy way to install them all is to do `npm install meteor-node-stubs` in your app directory.

**Comment by markoshust** [comment]
Thanks @benjamn  -- installed `meteor-node-stubs`, now receiving this error:

```
Uncaught TypeError: fs.readFileSync is not a function
```

**Comment by awwx** [comment]
@markoshust   are you seeing this error on the server or on the client?

(You can stub `fs` on the client but it's not going to be able to do file operations).

**Comment by markoshust** [comment]
Here's a profile if it helps at all: https://gist.github.com/markoshust/32d9eac050e1ab1ed893

**Comment by benjamn** [comment]
@awwx is correct; perhaps this Mime package is not meant to be used on the client?

**Comment by markoshust** [comment]
Weird, if I do an `import mime from 'mime'` at the top of the script, everything runs ok with no errors.

**Comment by benjamn** [comment]
Yeah, some modules work on the client if you carefully/accidentally avoid using their server-only parts. This is true of Browserify and Webpack bundles, too. Not ideal, but not unexpected.

**Comment by AlexFrazer** [comment]
The `meteor-node-stubs` seems to be missing a few modules, namely those involved in I/O, such as `net` and `fs`

**Comment by benjamn** [comment]
The support we provide for client-side Node built-in libraries is virtually identical to what Browserify and Webpack provide, because that's what client-compatible npm packages have come to expect:
* https://github.com/meteor/node-stubs/blob/master/map.json
* https://github.com/substack/node-browserify/blob/master/lib/builtins.js
* https://github.com/webpack/node-libs-browser/blob/master/index.js

Note that `fs` and `net` are there (in fact, every built-in module is represented), though some are implemented as empty stubs. Feel free to submit a pull request if you think something should be improved, but please bear in mind we're not interested in hacks that narrowly support specific use cases. Consider using a different package, or forking `meteor-node-stubs`, or monkey-patching the modules it returns, if you have special needs.

**Comment by markoshust** [comment]
Thanks for the feedback.

FYI, this appears to be caused by an outdated library (`superagent`). Upgrading the dep with the `keen-js` module seems to resolve the issue.

**Comment by chmanie** [comment]
In browserify you can actually use https://github.com/substack/brfs to inline readFileSync calls. Such kind of transform pipeline would come in handy in meteor as well.
