### ISSUE TITLE
Warn users when ~/.meteor gets too large

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6580]
https://forums.meteor.com/t/should-meteor-get-this-big-14-gigs/19904

Just wanted to run this by the team. After doing an `rm -rf ~/.meteor` and re-running meteor, it got up to about 1.1GB. Not too bad. Maybe there should be some automatic cleanup routine? Or manual? `meteor clean`.

**Comment by stubailo** [comment]
It's true - the size of this folder increases monotonically as you install new packages and Meteor releases. It also includes builds of MongoDB and Node, which is why it's so large.

I'd be happy to include a PR that checks the size of the directory at startup and prompts you to delete it to save space if it gets too big.

**Comment by gnuwilliam** [comment]
Hey guys, I'd love to start contributing to Meteor.

I've been using it for over a year now, and since it have given me so much joy, I figure I should give something back.

Is it okay if I start working on this feature?

Thanks!

**Comment by mitar** [comment]
Yes, feel free to start working on a pull request.

**Comment by abernix** [comment]
Just tagging as related: #5818.

**Comment by kulttuuri** [comment]
Anyone on this? Was just figuring out what was taking my computer's free space and my bundler-cache in the meteor build folder was around 12 GB. Some have claimed this to be over 100 GB. Would be nice to have warning for this.

**Comment by abernix** [comment]
@kulttuuri This issue is currently is currently `pull-requests-encouraged` and the consensus (this entire issue) is it would be nice to have a warning.  Is this something you'd be willing to work on?  It's definitely not high on the list of priorities for the core team right now so a community contribution of sorts would be greatly appreciated!

Discussing implementation: What do you think would be the best way to detect this would be?  My `~/.meteor/` directory is 19.2 gigs but that is because I have over 30 Meteor releases installed (for issue triaging purposes, mainly).  Unfortunately, checking the size of this folder at start-up time is a costly calculation – taking almost a full minute on my SSD hard drive using `du`.  I'm not sure if there is a faster API for checking this, but I believe Windows is notoriously slow at calculating folder sizes too.

**Comment by kulttuuri** [comment]
Hey – I'm going for 2 week holiday just tomorrow so not being able to tackle on this at the moment. If this issue is still going after I come back, it would be interesting for me to take a look at it.

**Comment by abernix** [comment]
@kulttuuri Thanks for considering a contribution!  Enjoy your holiday. :wink:

**Comment by workflow** [comment]
@abernix Ideas in case a faster solution cannot be found: What if you checked the size ony during meteor update? Or on every say 100th run of meteor?

**Comment by abernix** [comment]
@workflow Good ideas!  An extra minute during a `meteor update` would still be costly given that it's relatively frequent but I suppose a "Performing some house-cleaning..." prompt every 50th run might be reasonable, so long as when you `Ctrl-C`'d and ran it again it moved along (See, I personally run `meteor` quite a bit and benefit from its hoarding 🙂 ).  A faster API would be nice – though again, I'm not sure what exists.

**Comment by hwillson** [comment]
Migrated to https://github.com/meteor/meteor-feature-requests/issues/40 - closing here.
