### ISSUE TITLE
Inconsistent idGeneration behavior with insert and upsert

### ISSUE THREAD

**Issue by lucascorbeaux** [meteor/meteor#6599]
Hi there,

I encountered an issue while working with collections using MongoIds and upserting documents. It seems that when I upsert a new document, a string Id is always generated even if the idGeneration option is set to Mongo for this collection.

Here is a code snippet to reproduce the problem in Meteor 1.2.1:

```
var foo = new Mongo.Collection("foo", { idGeneration: "MONGO" });
foo.insert({ type: "insert" });
foo.update({ _id: null }, { bar: "update upsert" }, { upsert: true });
foo.upsert({ _id: null }, { bar: "upsert" });
```

Here are the docs viewed in Mongo shell:

```
{ "_id" : ObjectId("df0a4d11321b44bcf2be5621"), "type" : "insert" }
{ "_id" : "e6fiyMHCz87FLyRDQ", "bar" : "update upsert" }
{ "_id" : "FEptNXvQQ2SmNg4X5", "bar" : "upsert" }
```

I'm quite new to Meteor and I can't figure out precisely what's going wrong here, but it seems the wrong _makeNewID function is called when we're upserting.

**Comment by hwillson** [comment]
Thanks for reporting this @lucascorbeaux (and sorry for the delay in getting back to you!). This problem is being caused by the [Mongo.Collection._rewriteSelector](https://github.com/meteor/meteor/blob/d03b352bca91cfb6a2de039ad8ad38e90b3faabf/packages/mongo/collection.js#L365-L402) function that's being called just before the upsert's are happening. This function is intended to help protect against dangerous selectors; in this case it's seeing your `{ _id: null }` selector as a dangerous selector, and replacing it with an autogenerated (non-MongoID based) string ID. The `_rewriteSelector` function should be updated to respect the Collection's `idGeneration` setting. I'll get this fixed shortly. Thanks!

**Comment by lucascorbeaux** [comment]
Hi @hwillson thanks for explaining!
