### ISSUE TITLE
[1.3] Unable to resolve some modules (_process)

### ISSUE THREAD

**Issue by seifip** [meteor/meteor#6601]
I started getting the following error since rc13:

```
=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "_process" in
/C/Users/Philip/AppData/Local/.meteor/packages/auth0_lock/0.5.0/web.browser/auth0-lock.browserify.js
(web.browser)

Consider running: meteor npm install --save _process
```

Running `npm install --save _process` throws:

```
C:\Users\Philip\Documents\GitHub\ll-app>C:\Users\Philip\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\bin\\node.exe C:\Users\Philip\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\bin\\..\lib\node_modules\npm\bin\npm-cli.js install --save _process
npm WARN package.json application-name@1.0.0 No repository field.
npm WARN package.json application-name@1.0.0 No license field.
npm ERR! addLocal Could not install C:\Users\Philip\Documents\GitHub\ll-app\_process
npm ERR! Windows_NT 10.0.14279
npm ERR! argv "C:\\Users\\Philip\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.0_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\Philip\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.0_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "_process"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! path C:\Users\Philip\Documents\GitHub\ll-app\_process
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open 'C:\Users\Philip\Documents\GitHub\ll-app\_process'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Philip\Documents\GitHub\ll-app\npm-debug.log
```

I've also tried removing and re-adding the `auth0:lock` package to no avail.

**Comment by xcv58** [comment]
I suggest that get rid of `auth0:lock` package. You can use the native npm [`auth0-lock`](https://www.npmjs.com/package/auth0-lock) package.

**Comment by seifip** [comment]
@xcv58 But the npm package won't integrate with Meteor.user(), making things unnecessarily more complicated as I won't be able to simply access Meteor.user().services.auth0 for free?

**Comment by benjamn** [comment]
`Unable to resolve some modules` is only a warning, not a fatal error. In this case it's probably false positive, because it's coming from a Browserify bundle that has its own implementation of the `require` function. Unless your app is not working, you can safely ignore the warning.

This problem will go away once the `auth0:lock` package updates to Meteor 1.3 and starts using the new module system instead of including a Browserify bundle.

**Comment by mitar** [comment]
it seems there are another related issue here: https://github.com/peerlibrary/meteor-util/issues/2

**Comment by cellog** [comment]
I have the same issue.  Rather annoying, tbh, because I don't know what to remove to fix it

som-gbeaver:reactchiara gbeaver2$ meteor npm i --save _process
npm WARN package.json sqlite3@3.0.8 No description
npm WARN package.json sqlite3@3.0.8 No repository field.
npm WARN package.json sqlite3@3.0.8 No README data
npm ERR! addLocal Could not install /Users/gbeaver2/github/local/chiara-website/reactchiara/_process
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/gbeaver2/.meteor/packages/meteor-tool/.1.3.0_3.2t6gh2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "i" "--save" "_process"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! path /Users/gbeaver2/github/local/chiara-website/reactchiara/_process
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open '/Users/gbeaver2/github/local/chiara-website/reactchiara/_process'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gbeaver2/github/local/chiara-website/reactchiara/npm-debug.log
som-gbeaver:reactchiara gbeaver2$

**Comment by benjamn** [comment]
I'll get around to this eventually, but if you really want to make sure it gets into 1.3.2, I would happily take a pull request that silenced warnings about `_process`! Take a look at [this code](https://github.com/meteor/meteor/blob/d8287dc6eba95f5ba55654974cbad908d1d238e2/tools/isobuild/compiler-plugin.js#L896).
