### ISSUE TITLE
NPM - Cannot find module 'prefix' dependency

### ISSUE THREAD

**Issue by ArdentKid** [meteor/meteor#6608]
Upgraded from `1.3-modules-beta.8` to `1.3` and one of my dependencies broke. The library simple-color-picker is using 'prefix' package and throws the error "Cannot find module 'prefix'" despite having it installed.

**Comment by benjamn** [comment]
Can you provide a reproduction? What happens if you re-run `meteor npm install`?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Please do try in the latest Meteor 1.3.5.1 which has a lot of updates in this department.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
