### ISSUE TITLE
[Feature Req] Version range specifiers for Npm.depends

### ISSUE THREAD

**Issue by ciwolsey** [meteor/meteor#6622]
Could we possibly have a way to use formats like ^1.0.0 or 1.x.x inside our packages Npm.depends?

Perhaps this was left out by design, I'd be curious to hear the reasoning.

**Comment by stubailo** [comment]
Meteor packages are built when they are published, so by the time the user has downloaded your package, they don't get to decide which NPM dependency version to use since the code is baked in. If you want the application developer to decide which version of an NPM package to use in the particular app, use the new mechanism of peer NPM dependencies, described here:

http://guide.meteor.com/writing-packages.html#npm-peer-dependencies

This will require people to use `npm install` to get the version that they want to use in their app.
