### ISSUE TITLE
Installing npm packages should trigger development server restart

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6627]
When you `npm install` a package, you need to stop and start your dev server to pick up changes.

This isn't an ideal development experience if we claim to support npm as first-class I guess?

https://github.com/meteor/meteor/issues/6600#issuecomment-203165622

**Comment by trusktr** [comment]
One thing to keep in mind is that npm might run for a while, and Meteor would want to wait until `npm` is finished. I suppose this is easy if the official NPM support requires using `meteor npm` instead of just `npm`.

Maybe if Meteor detects a file change in `node_modules` it can check if any files in there are open by the NPM process before reloading? But I suppose that could possible get funky with users who are running things like `npm run watch` inside of the app or something.

**Comment by benjamn** [comment]
This issue will be officially fixed when Meteor 1.3.2 is released today or tomorrow, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now.
