### ISSUE TITLE
Hot Code Push doesn't push code to iOS mobile device in Meteor 1.3

### ISSUE THREAD

**Issue by cdcv** [meteor/meteor#6651]
Hot code push now seems to work on the browser, but not on iOS mobile build.
Just updated to meteor 1.3, using Galaxy.
Both pointing to the same server (as they always were).
In browser, when I refresh I get the new code.
On iOS, now matter how many times I refresh I still get the old code (from mobile server, haven't reload the code locally onto device).
If I push a new 1.2 build, both refresh to the latest code.
Does this mean that it would be impossible to hot code push to our installed base of iOS users who have the current 1.2 app (without an app store download)?
Is this a bug, or am I supposed to be doing something differently?
Also, using mdg:reload-on-resume

Thanks

**Comment by martijnwalraven** [comment]
Hot code push from a Meteor 1.3 server to a mobile app built using Meteor 1.2 is not supported. Both because of the changes to the hot code push mechanism and the upgraded Cordova versions, downloading the new JavaScript code would leave your app in a broken state. So we're explicitly blocking this, and you will have to submit a new 1.3 build to the App Store.

**Comment by cdcv** [comment]
Thanks.
