### ISSUE TITLE
Meteor build with METEOR_SETTINGS not working as expected

### ISSUE THREAD

**Issue by tgoldenberg** [meteor/meteor#6657]
As per the [1.3 docs](http://docs.meteor.com/#/full/meteor_absoluteurl), I should be able to `export METEOR_SETTINGS=$(cat settings.json)` 

Now, when I do this with a different env var, it works in my `console.log(process.env.OTHER_VAR)`. However, `console.log(process.env.METEOR_SETTINGS)` renders `undefined` and `console.log(Meteor.settings)` renders an empty object with no data. 

This is important because we are using the `meteor build` command to bundle our app, so we don't have access to `meteor run --settings settings.json`, etc. I need to know how I can have access on the client via `Meteor.settings.public` with this deployment structure. So far, seeing lots of comments on this from previous versions of Meteor, and some recommend doing what I am doing now, though it doesn't work. Not sure if I'm missing something obvious, or if this is a problem with the latest release. Really looking forward to getting help with this. Thank you.

**Comment by tgoldenberg** [comment]
so from [this](http://stackoverflow.com/questions/34726865/meteor-settings-env-variable-does-not-populate-meteor-settings), I understand that `METEOR_SETTINGS` doesn't work in a development environment - i.e., `meteor run`. I'm sure there are reasons for this, but it does seem counter-intuitive, and the docs don't really try to point this out. Any ideas on making this clearer or allowing use of `METEOR_SETTINGS` in development?

**Comment by abernix** [comment]
I think [the docs for Meteor.settings](http://docs.meteor.com/#/full/meteor_settings) do make it clear that  `METEOR_SETTINGS` is for production (i.e. the product run from `meteor bundle`).   This is the standard (only) way to pass in settings for a bundle.

In development, you pass your settings in through a `--settings settings.json` argument to the `meteor run` command.  This is so that your settings will be reactive (reload automatically) when you change them in development.

Unfortunately, I'm not aware of a way to simulate this in development, if that's what you're trying to do.  Rest assured, `METEOR_SETTINGS` will work in production.

I will say though, the behaviour is a bit inconsistent because `METEOR_SETTINGS` is actually validated (i.e. you can't pass an invalid JSON object), even in development, but it's blown away when you're not running the bundled version.  This is happening because of [this line in the meteor run tool](https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/tools/runners/run-app.js#L195).

I don't know if there is a solid reason why `METEOR_SETTINGS` *couldn't* work in dev, but it just doesn't work right now.

**Comment by tgoldenberg** [comment]
Thank you @abernix for clarifying. I was able to get it working in production just fine, just doesn't make for a seamless development experience when you have to one-off something in production that you can't test in development, though I understand there are real reasons.

**Comment by maxnowack** [comment]
There should be a warning, that `METEOR_SETTINGS` will not be parsed in development mode.
