### ISSUE TITLE
[1.3] accessing client ip address behind kubernetes/nginx proxy

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#6661]
I'm trying to get the client's IP when running Meteor on Kubernetes behind an Nginx proxy service for SSL termination.

I've followed the instructions here:
http://docs.meteor.com/#/full/meteor_onconnection

and changed `HTTP_FORWARDED_COUNT` (tested out values for 1, 2, and 3), however the IP address returned is always either an internal IP address of a Kubernetes machine or the head Kubernetes cluster ip. It should return the client IP.

Here is the docker image for the Nginx container I'm running:
https://github.com/markoshust/nginx-ssl-proxy/blob/master/nginx/proxy_ssl.conf

All of the headers appear to be set correctly and everything is functioning pretty well. 

I'm using https://github.com/mizzao/meteor-user-status to automatically store the client IP. I have this module working well on another site that runs a simple mup setup. 

Either `HTTP_FORWARDED_COUNT` is not working properly, there is a problem with Kubernetes, or there is a misconfiguration somewhere in my setup.

**Comment by abernix** [comment]
I'm not using nginx+Kubernetes anymore (Meteor+Kube were great, btw, good choice), but I had this working fine in the past.  I didn't even have to do anything with `HTTP_FORWARDED_COUNT`.

My main difference that I can see from my config is I have `proxy_redirect    off`
```
          proxy_pass http://target_service/;
          proxy_redirect      off;
```

If that works, maybe try another way to force SSL if that's what you're trying to do.  Maybe `meteor add force-ssl`?  Or another nginx method.

**Comment by abernix** [comment]
Closing this because this seems to be an issue with the proxy configuration and there's been no further updates.

The logic Meteor uses for getting the IP address is here...
https://github.com/abernix/meteor/blob/spelling-typos/packages/ddp-server/livedata_server.js#L889-L925

As you can see, if `HTTP_FORWARDED_COUNT` is 0, it simply uses the `remoteAddress` provided by Node, and if it's a positive integer, it works it's way through the IP addresses in the `x-forwarded-for` header.

If you still need help debugging this further, I might check out the [gadicohen:headers](https://atmospherejs.com/gadicohen/headers) package which will allow you to look at the headers.  If you can provide those headers along with the `HTTP_FORWARDED_COUNT` you're setting (available in your app as well at `process.env.HTTP_FORWARDED_COUNT`), it would be more helpful.
