### ISSUE TITLE
[1.3] package build is veeeery slow because npm modules

### ISSUE THREAD

**Issue by pletinsky** [meteor/meteor#6662]
Meteor 1.3 problem only (prev version was ok).

My package uses a lot of npm packages for internal need (it's not used by the package directly).
And speed of this package build is very slow (some minutes!).
I'd like to avoid any work with node_modules folder by the meteor live update.

To reproduce the problem
1. create meteor package;
2. install a lot of  npm packages inside of it (node_modules folder);
3. update package file to initiate build inside of the live update;

PS
- It's not reproduced with empty node_modules folder.
- it's not dependent from ecmascript module.

**Comment by benjamn** [comment]
Sounds like #6002 might help address this problem?

**Comment by pletinsky** [comment]
It's great idea! Thanks. .meteorignor could solve the problem.
But I expect it should work without direct managing. Meteor knows which npm modules are used.

But I need any solution really. Cause this is stopper. 
I didn't expect problems like this from the meteor :(. I have lost conﬁdence.

**Comment by jhartma** [comment]
Having the same problem, currently it takes up to 8min for a single rebuild with all the npm packages. This is really slowing down development

**Comment by pletinsky** [comment]
I have found workaround.
1) Create .build (any name started from dot) directory
2) Move the file package.json to this directory
3) npm install inside of the directory
4) Use npm from the folder

So the folder is ignored by the meteor build system

**Comment by abernix** [comment]
Have you tried Meteor 1.4.2.3 to see if this situation has improved?

**Comment by datacarl** [comment]
@abernix do you expect the meteor command line tool v `1.4.2.3` to improve build speeds of apps running older versions of meteor? Or does the app have to be upgrade to the latest version too?

Also, how is the npm install performed by `meteor build`? Does it use `meteor npm`? I'm asking since it would be nice to configure it to use `yarn` or a local npm cache.

**Comment by abernix** [comment]
@datacarl Aside from a very short boot sequence, the version of the tool is the same as the version of your app (i.e. the same as when it was initially released).  You would have to update your app itself to benefit.

As to the `meteor build` `npm` process – for the most part, it uses your current `node_modules`, as they are, copying them over to your bundle.  The actual `npm install` is run within the generated bundle on the architecture that you're deploying to – though `yarn` probably works there just fine.

As to `yarn` in general and within development (using `meteor` tool), Meteor still uses `npm` internally for some of its tasks, but if you want you can try using `yarn` yourself locally.  I honestly haven't had an opportunity to test it out much myself, and I'm speaking purely theoretically.  Meteor won't be aware enough to use the `yarn.lock` file or anything like that, but since `yarn` is basically just a package manager which installs into your `node_modules` directory, I believe you'll be fine (install with `yarn` first and then Meteor will just use it!).  Most importantly though, you should make sure that the `node` that `yarn` uses matches up properly with Meteor.  The safest way to do this is:

```sh
$ cd /your/app/directory
$ meteor npm install -g yarn
$ meteor yarn
```

Anyhow, further discussion about `yarn` should probably be in the [forums](https://forums.meteor.com/) as it's totally off-topic for this issue. :smile:

**Comment by cameronroe** [comment]
+1 on yarn. Here's a quick [write up](https://medium.com/@cameronroe/yarn-consistent-secure-fast-package-management-in-javascript-d473b0c4b23e#.al6wpou8x) if you're interested.

**Comment by hwillson** [comment]
Since we haven't heard back regarding the question asked in https://github.com/meteor/meteor/issues/6662#issuecomment-261981999, I'll close this for now. Happy to re-open if anyone is still encountering this issue. Thanks!
