### ISSUE TITLE
Rename the .meteor/local folder

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor/meteor#6704]
In it's current state it's hard to efficiently synchronize Meteor project folders to cloud services. While it's easy to put ``node_modules`` on a pattern ignore list, ``.meteor/local`` hasn't been an option so far.

- Cubby: You can create a ``.cubbyignore`` file which works like ``.gitignore``. This would work if it weren't for the ``.meteor`` being dot prefixed. Cubby ignores hidden and dot prefixed folders.

- pCloud: Here you can create an ignore pattern that lets you ignore folders like "node_modules". However the local folder can't be ignored unless you're willing to ignore all folders with the name ``local``, which ultimately is gonna lead to problems down the road. Especially as pClouds ignore filters are global.

- Mega.nz: Same as pCloud.

Unlike the prefixed folder ``node_modules``, it's impossible to efficiently target the ``local``folder, be it cloud syncing, backup, virus scanners, optimizers, you name it.

Changing the name to something like ``.meteor_local``would solve this.

**Comment by stubailo** [comment]
@jakobrosenberg, I think this issue is not going to be a priority to fix in the near future. Modifying the Meteor project structure would obsolete a lot of existing tutorials and command line tools, and this doesn't look like a strong enough reason. There are many tools out there that keep files inside dotted directories, and it seems like a real problem with those cloud services that they can't handle those files.

To avoid this on a unix-based machine, you could use symbolic links to keep the contents of `.meteor/local` somewhere else, and then perhaps the cloud service would not follow the link.
