### ISSUE TITLE
Meteor 1.3 - Cordova app name other than "app" causes build to fail

### ISSUE THREAD

**Issue by jessedvrs** [meteor/meteor#6706]
__What?__
Meteor 1.3 on OSX 10.11.3.

When configuring an app name (using `App.info()`) other than "app", the xcode build will fail. The xcode build error is:

    Target specifies product type 'com.MyAppNamele.product-type.MyAppNamelication', but there's no such product type for the 'iphoneos' platform

__Ehh what?__
The error directly implies that it's probably a search & replace mistake. "MyAppNamelication" should be "application" and "MyAppNamele" should be "apple".

__Wrongly generated "project.pbxproj" file__
I found out it's due to this generated file: 

    .meteor/local/cordova-build/platforms/ios/MyAppName.xcodeproj/project.pbxproj

In that file, all instances of the word "app" seems to be replaced with the configured app name. But here is the problem: since `wrapper`, `application`, `apple` and `webapp` also contain the characters `app`, they will be replaced respectively with "wrMyAppNameer", "MyAppNamelication", "MyAppNamele" and "webMyAppName". Obviously, this will cause the xcode build to fail.

__So where is that wrong search & replace?__
I wasn't been able to find it yet in the Meteor codebase.

__Is there a possible (hacky) fix for now?__
Yes. For people also experiencing this problem, I've written a small shell script you can run to fix the issue.

1. Create a new file in one directory above your meteor app directory, call it "fix-ios.sh" containing:

    #!/usr/bin/env bash

    cd app;
    PBXPROJ=.meteor/local/cordova-build/platforms/ios/MyAppName.xcodeproj/project.pbxproj;
    sed -i '' 's/webMyAppName/webapp/g' $PWD/$PBXPROJ;
    sed -i '' 's/MyAppNamel/appl/g' $PWD/$PBXPROJ;
    sed -i '' 's/wrMyAppNameer/wrapper/g' $PWD/$PBXPROJ;

2. Replace MyAppName with your app name as you're defining in `App.info()`
3. Make the script executable with `chmod +x fix-ios.sh`.
4. Run the xcode build to reproduce the error.
5. Run the script using `./fix-ios.sh`
6. Re-run the xcode build.

If you have questions about the issue or about the hacky fix, please ask ;)

**Comment by benjamn** [comment]
This is a truly great bug report!

Triaging to @martijnwalraven in case he has any quick ideas.

**Comment by martijnwalraven** [comment]
That is some impressive detective work indeed! 

However, I don't think the problem is that you can only use `app` as a name. The issue only seems to occur when you rename an app that was named `app` before (that is when the wacky renaming kicks in).

Unfortunately, this is not under Meteor's control but is done by Cordova. So it would be great if you could file a bug report on the [Cordova JIRA](https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel) for this.

As for fixing the issue once it occurs, a much easier solution is to simply `rm -rf .meteor/local/cordova-build` and let Meteor regenerate the project.

**Comment by jessedvrs** [comment]
Thanks for the quick retesting. Removing the cordova-build and regenerating indeed fixes the issue. I'm seriously wondering why I didn't just try that before writing a bash script. So to everyone else facing this issue: remove `.meteor/local/cordova-build` and rebuild!
