### ISSUE TITLE
Error Running Legacy App when Local 1.3 Packages Exist

### ISSUE THREAD

**Issue by patrickml** [meteor/meteor#6713]
I'm having an issue running a 1.2 application if 1.3 packages exist in my local package export

Neither of these packages are included in this application however they are affecting the startup. Is there a reason why the entire local package dir is scanned before any app is started? Might this be another issue affecting load time?

```
=> Meteor 1.3 is available. Update this project with 'meteor update'.
Errors prevented startup:

While reading package from `/Users/patricklewis/Documents/sites/meteor/packages/singularity`:
package.js:19:7: Object [object Object] has no method 'mainModule'

While reading package from `/Users/patricklewis/Documents/sites/meteor/packages/wormhole`:
package.js:20:7: Object [object Object] has no method 'mainModule'

Your application has errors. Waiting for file change.
Started MongoDB.
```

**Comment by benjamn** [comment]
After looking into this a bit, I can tell you that we're not scanning entire local packages, but we do have to execute all the `package.js` files of local packages files to find out what their names are, so that when you `meteor add singularity` we know you're talking about the local package and not some package on Atmosphere.

Given that it's the 1.2 package-reading code that's failing, I'm not sure there's much we can do to fix this unless you upgrade your app to ~1.3. If you really need to get this to work without upgrading, you might be able to change the 1.3 packages (`singularity` and `wormhole`) to simulate `api.mainModule(file, where)` by calling `api.addFiles(file, where, { mainModule: true })`, since `api.mainModule` is [mostly sugar for `api.addFiles`](https://github.com/meteor/meteor/blob/d8287dc6eba95f5ba55654974cbad908d1d238e2/tools/isobuild/package-api.js#L341-L362).

**Comment by benjamn** [comment]
Ok, here's the best workaround I have to offer (until you can upgrade everything to 1.3): in the `package.js` files of your local 1.3 modules, wrap your `api.mainModule` calls in `try`-`catch` blocks. If you're not using those packages in your 1.2 app, then those failing `api.mainModule` calls are not important, so silencing the errors will let you build the 1.2 app without problems.

**Comment by benjamn** [comment]
Feel free to reopen this issue if that workaround doesn't suit your needs!
