### ISSUE TITLE
collection.find() not instanceof Mongo.Cursor?

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#6717]
This behavior seems really odd to me. A cursor should be an instance of Mongo.Cursor. No?

**Comment by abernix** [comment]
`Meteor`'s `.find()` result, while based on `Mongo.Cursor` currently accepts different parameters and behaves differently.  Issues could currently arise if someone or some code assumed that it behaved the same simply because it identified itself as an instance of it.

Happy to reconsider and categorize as a feature request with some discussion here, but currently I don't see the need and this doesn't meet the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).  Closing.
