### ISSUE TITLE
Meteor App not showing up in Android Studio simulator

### ISSUE THREAD

**Issue by ChristophAllen** [meteor/meteor#6729]
So after many tries I'm finally able to load the Android simulator successfully but the app isn't showing up on the Android screen. Imgur link shows AVD specs, packages installed, and screenshot on Android simulator screen showing their is no app. I don't get any errors after running 'meteor run android --verbose'. Never used an Android so I don't know if I'm missing something really obvious. Any help is appreciated. http://imgur.com/a/PLfdn

**Comment by martijnwalraven** [comment]
If you don't get any errors from `meteor run android`, it may still be building/installing/starting up the app! 

The Android emulator is embarrassingly slow and difficult to use, which is why we recommend against using it in the guide. If you have any chance of testing on a real device, that will give you a much better developer experience.

**Comment by ChristophAllen** [comment]
Right on dude, thanks so much.  Would you happen to know a good, descriptive guide on doing this?  I've looked around but haven't found any great ones.

**Comment by martijnwalraven** [comment]
Well, there is our own [mobile guide](http://guide.meteor.com/mobile.html)... Anything specific you think is missing there?

**Comment by ChristophAllen** [comment]
Haha I'll be honest I just hadn't come across that, closing this issue now.  You definitely rock out loud.
