### ISSUE TITLE
Include breaking changes in History.md

### ISSUE THREAD

**Issue by lirbank** [meteor/meteor#6730]
The Meteor Guide mentions a few breaking changes http://guide.meteor.com/1.3-migration.html#breaking-changes but there is nothing in https://github.com/meteor/meteor/blob/devel/History.md

For us running production apps it's important to get clear info about breaking changes to be able to upgrade. When 1.3 I had to search for a bit before finding the docs in the Guide (it was not in the releease email, the blog or the History.md).

With Node.js I have the habit of always checking the History.md or Changelog.md in Github for each package I upgrade. I search for "Breaking" and for most packages that does the trick.

I know Meteor wants to better cater to production and large apps, so this is my little contribution to that. To consider, and communicate, how breaking changes are being documented.

Inspiration (links directly to the [changelog](https://github.com/nodejs/node/blob/v5.10.1/CHANGELOG.md), very handy, saves time):
![image](https://cloud.githubusercontent.com/assets/2538130/14340589/e3a9c752-fc3d-11e5-9dd0-4b5c30d2d424.png)

**Comment by laosb** [comment]
Yeah, but the problem is: `meteor.com` is MDG's official website and then Meteor's product website. It is designed to cover MDG first and then Meteor itself. The only reason for me to visit `meteor.com` is managing Atmosphere organizations. May be Meteor should have a separated homepage so we can have detailed information for Meteor only?

**Comment by stubailo** [comment]
I think the goal is to document these specifically in the Meteor Guide, because this is where we are going to cover what you need to do to migrate to the next version. So IMO next release we just need to do a better job of publicizing that article, when there is a "migrating to 1.4" article. History.md is too long and complicated to find any useful information, IMO the guide is the right place. It also gives us a place to write recommendations about how to work around the breaking changes.

**Comment by lirbank** [comment]
Yeah, why do it like everyone else is doing it ;)

**Comment by stubailo** [comment]
@benjamn since we are already listing all changes in History.md anyway, we may as well mark some of them as breaking changes I guess?

**Comment by abernix** [comment]
The team is trying hard to ensure that messaging is more clear and ensuring that `History.md` is amended for every change – including breaking changes.  I assure you that your request is not falling on deaf ears.
