### ISSUE TITLE
Better mechanism for porting Meteor to other Node versions

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#6732]
#5124 

Ideally, Meteor shouldn't be fixed on a specific Node version. We need to figure out what limited the portability of Meteor, and solve them so that Meteor can run on most newer Node releases.

**Comment by ChrisCinelli** [comment]
Node v6 is around the corner https://github.com/nodejs/node/issues/5766 . I would definitely plan to have node v6 on Meteor in the near term.

**Comment by martijnwalraven** [comment]
The main issue limiting Meteor running on different Node versions is binary compatibility. Because of the way the Meteor packaging system works, packages with npm dependencies with binary dependencies need to be compiled for different architectures when publishing (`publish-for-arch`). Compiling these for you means there is no need to have a compiler toolchain installed on your machine, and also ensures the environment is consistent. But the downside of this is that the resulting binary is bound to the Node version it is compiled with (because the API changes between versions).

We definitely want to move to a situation where we are less dependent on the specific Node versions, but the only sane way to do this seems to get rid of the packaging of binary dependencies. There will be some loss of convenience, but that seems worth the tradeoff. How this should work exactly and how it relates to the move to npm is something @benjamn and others will be working on next.

**Comment by lukeadams** [comment]
@laosb It's trivial to change what version of node meteor-tool builds with. The issue is the (long) list of native deps that need to be upgraded to build with Node 5/6 – many of which have had significant API changes. This causes tons of errors after launch. Upgrading is essentially fixing them one by one...
I'm playing around with it on my fork but haven't published anything yet. After the deps are recent it would be trivial to have edge (latest node) and LTS (lts node) versions of meteor-tool, fixing what breaks when it breaks.
@martijnwalraven I have literally no experience with the build backend, but would it stress the build infrastructure too much to build native binaries per node version? Similar to arch I guess: `{package-name}.{arch}.{node-version}` –  the tool pulls whatever it needs.

**Comment by abernix** [comment]
@laosb Can we close since #6921 and #6923 are in existence? 😺

**Comment by laosb** [comment]
We may leave this open until one of those prs landed.

**Comment by abernix** [comment]
@laosb What's the benefit?  This issue doesn't provide any conversation more than the existing Node upgrade issue #5124 and the individual PR tickets.  If you're just saying "Meteor should run on newer nodes" that issue takes care of it.

**Comment by benjamn** [comment]
To the end of letting users pick their own version of Node, here is my current vision: https://github.com/meteor/meteor/pull/7072

**Comment by laosb** [comment]
@benjamn Yeah, I had saw your PR so I closed this!
