### ISSUE TITLE
ReferenceError: Can't find variable: Session - Meteor 1.3

### ISSUE THREAD

**Issue by rlech** [meteor/meteor#6733]
When I create a new Project (meteor 1.3), start it and open my browser I´m not able to set Session Vars via my Javascript Console. I always get an Error "**ReferenceError: Can't find variable: Session**". 

Why is this not working anymore?

e.g. 
`Session.set("MyName", "myString");`
is giving me 
`ReferenceError: Can't find variable: Session`

**Comment by abernix** [comment]
Before Meteor 1.2, `session` used to be included in the default Meteor base bundle.  It is no longer.  Do you have the `session` package added to your project with `meteor add session`?

**Comment by d0cN4pp** [comment]
I am on Meteor 1.3.1 and I put meteor add session at the stop of my main.js and now the site will not load.  If I remove line then it will load. If Session was deprecated from meteor then what are we suppose to use for storing session variables?  I can't find an alternate command syntax.  Any suggestions for a Meteor noob would be helpful.

**Comment by abernix** [comment]
It's not code.  It's a command that you need to run in your meteor project directory.  Just like any other package that you install 

`Session` was not and is not deprecated.

**Comment by lyquocnam** [comment]
have you try ?
`import { Session } from 'meteor/session';`

**Comment by rlech** [comment]
Looks like there is a nee Package for this thanks. 

You dont Need to import sessions just if you have namespace issues

**Comment by d0cN4pp** [comment]
abernix - Yes, I am a noob at this.  I thought it went in main.js.    I ran it on the command line and I am all good.  So meteor add is like CPAN is to perl but for meteor modules.   Somehow I missed that very valuable point.

**Comment by abernix** [comment]
@d0cN4pp Yes, exactly.  Meteor has had a package system that used the Meteor package repo (CPAN equivalent) called Atmosphere for a very long time – before JavaScript (well, node's) `npm` became a huge deal.

So `meteor add` reads and installs from the atmosphere database.  `session` has always been a meteor package, but for a long time it was *explicitly* included.  As of Meteor 1.1, you had to `meteor add` it if you *needed* it (this made the overall package size of Meteor smaller, which was ideal for mobile apps, etc.).

But now, (and, sorry, this is the joy of a quickly advancing framework ecosystem :grin:) be sure to read up on the **new** Meteor 1.3 stuff ([specifically check out this section on packages](http://guide.meteor.com/using-packages.html) because as @lyquocnam wrote above, there is also direct support for `npm` packages now using the `import` statement.  That means that slowly, things are moving from `meteor add <atmosphere-package>` to `meteor npm install <npm-package>`.  It's a good thing, believe me.

Read more about npm at npmjs.org.  And please close this ticket if possible.   Further discussion should be at https://forums.meteor.com as Issues are reserved for Meteor bugs.

**Comment by xvendo** [comment]
Nobody mentioned a thing about sessions in the migration guide. 
Please could you mention things like excluded packages from meteor base.
For now I downgraded to 1.2.1 again.

**Comment by abernix** [comment]
@xvendo Please make a forum post with your problem. *Nothing* has changed about Session's in 1.3.

**Comment by MastaBaba** [comment]
A straightforward Google search easily lead me to this thread. But, after skimming the docs and changes on 1.3, I also didn't spot that the session package needed to be added explicitly on new projects.

**Comment by cortesa** [comment]
it have to be added explicitly on new projects. I don know why but if you execute "meteor create something" Session package dosen't appear in .package file

**Comment by cmeethree** [comment]
Having a similar issue on 1.3 as well. I executed the 'meteor add session' but when I look in the console log it still says "Uncaught ReferenceError: curShareList is not defined". I'm hard coding the value right now just to test: Session.set('curShareList', 'cmeethree'); - so essentially it seems to not be recognizing it.

Anyone have any more insight? It's messing up my ability to share links. Worked before I upgraded.

Here's the full router code:

    Router.map(function() {
      // declare community route here:
        this.route('postsList', {path: '/'});
        this.route('userListShared', {
          path: '/:sharelink',
          data: function () 
                  {
                       // console.log(this.params.sharelink);
                       Session.set('curShareList', this.params.sharelink);
                        //Session.set('curShareList', 'cmeethree');
                        console.log(curShareList);
                  }
            
        });

**Comment by abernix** [comment]
@cmeethree Setting a `Session` variable does not set a global JavaScript variable.  In order to access a `Session` variable that you've set, you need to use `Session.get` on the same name:

    console.log(Session.get('curShareList'));

**Comment by cortesa** [comment]
Or use the dot notation "Session.curShareList"

`
console.log(Session.curShareList);
`

**Comment by abernix** [comment]
@cortesa That is not the correct [usage of Meteor's `Session`](https://docs.meteor.com/api/session.html).  I don't even think it would work, and even if it did, it wouldn't be reactive.

**Comment by cmeethree** [comment]
Thanks abernix - still having weird issues but yeah I had a slight duh moment there. Thanks for correcting my rookie mistake.
