### ISSUE TITLE
Meteor Tutorial 6 - After appropriate installation the Todo List won't run on a device or in the emulator

### ISSUE THREAD

**Issue by LenCewa** [meteor/meteor#6739]
Hello, 

I dropped this [question](http://stackoverflow.com/questions/36475988/meteor-tutorial-creating-an-app-step-6-error-executing-cordova-command-for) on Stack Overflow as well.

**Comment by abernix** [comment]
If StackOverflow hasn't been any help, try asking for help on the [Meteor Forums](https://forums.meteor.com). There are specific instructions on how to fix your error within the error message body that you posted on StackOverflow involving setting up your Android emulator.  (I'm also sure you can find information on how to do this elsewhere on the web).

Otherwise, if you're trying to report this as a bug, please submit a complete issue following [Meteor's instructions for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)
