### ISSUE TITLE
[1.3.1] upgrade directory doesn't exist

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#6742]
After upgrading from 1.2.1 to 1.3.1, one of my applications throws the following error:
```
Error: ENOTDIR, readdir 'D:\barco\repositories\bluetest\projects\admin\.meteor\local\isopacks\.build259353.barco_admin-frontend\web.browser\client\setup\controller\.builder-tmp-file.658202'
```
Everytime I build it again, I get the same error (with different random numbers)

Windows 7

**Comment by pmwisdom** [comment]
I had this happen to me, try deleting your .meteor/local directory and try again. Thats what solved it for me.

**Comment by abernix** [comment]
Closing this as it's too vague.  Please submit a (small, minimal) reproduction for this issue if you're still experiencing this problem.  That snippet by itself is not enough to isolate the problem, or even to determine if the problem is in Meteor itself: [More information on reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)

You can also ask for help on the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor).

Also consider trying again with a new version of Meteor and on a fresh Meteor project.
