### ISSUE TITLE
Importing browser-policy is not intuitive

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#6766]
I have installed the browser-policy package (`meteor add browser-policy`) and set up some rules:

```
BrowserPolicy.framing.disallow();
BrowserPolicy.content.disallowEval();
BrowserPolicy.content.disallowObject();
BrowserPolicy.content.disallowInlineScripts();
BrowserPolicy.content.disallowFont();
```

The Meteor Guide [recommends the Airbnb javascript style guide](http://guide.meteor.com/code-style.html#style-guide), which requires that `BrowserPolicy` be defined/imported before making the above declarations. Not being able to import the `BrowserPolicy` variable results in ESLint errors, which causes the test suite (`meteor npm run test`) to fail.

However, adding the following line to the top of the file

```
import { BrowserPolicy } from 'meteor/browser-policy';
```

results in application crash:

```
Your app is crashing. Here's the latest log:
...
TypeError: Cannot read property 'framing' of undefined
...
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by skirunman** [comment]
Not sure if this will work, but try:

`import { BrowserPolicy } from '[meteor/browser-policy-common](https://github.com/meteor/meteor/blob/devel/packages/browser-policy-common/package.js)';`

I don't see an export in [browser-policy package.js](https://github.com/meteor/meteor/blob/devel/packages/browser-policy/package.js) so maybe this is the issue.

**Comment by joncursi** [comment]
@skirunman that worked, thanks!

**Comment by skirunman** [comment]
@joncursi Glad it worked. You may want to reopen this issue as this situation is confusing. I'd like to get MDG's input on if this should be changed so that the actual package browser-policy exports `BrowserPolicy` instead of the browser-policy-common package. 

In fact, I can't really see any reason why these two packages are not just combined into one package. The only place outside of the family of browser policy packages that I can find browser-policy-common is referenced is in this [test file](https://github.com/meteor/meteor/blob/abd574f38008b45f5e2a6bc322b10bcdde44763a/packages/constraint-solver/slow-test-data.js) in the constraint-resolver package.

**Comment by stubailo** [comment]
I think this falls under the set of things that should be better documented when we revamp the docs, which might be coming quite soon!

**Comment by skirunman** [comment]
Interesting, any thoughts on why there is both a browser-policy and browser-policy-common package. Is this a pattern that MDG likes to use for package development? Seems unnecessary to me.

**Comment by stubailo** [comment]
I don't know about that reason, sorry.

**Comment by abernix** [comment]
Removing the Doc tag as I've opened meteor/docs#16 to handle that side of the issue.

There is still the question about `browser-policy-common` vs. `browser-policy`.  On that note, it's a matter of modularity.  `common` is used by two other `browser-policy` packages  I don't think they should be combined into a single package, however it might be more intuitive to export the global from `browser-policy` (and maybe both).

I wouldn't expect an answer on this anytime soon, but will leave this open.  The docs should mitigate any confusion for now.

**Comment by hwillson** [comment]
Since the documentation issues are being handled in meteor/docs#16, to get this issue closed I think we should move ahead with re-exporting the `BrowserPolicy` variable. The `browser-policy*` packages were designed to be modular, which means each of the following packages can be added on their own:

- `browser-policy-content`
- `browser-policy-framing`
- `browser-policy`

Each of these packages then implies `browser-policy-common`, which exports `BrowserPolicy`. Since there is no harm in re-exporting the `BrowserPolicy` variable, let's do that in all 3 packages. This way each of the following will work:

```js
import { BrowserPolicy } from 'meteor/browser-policy';
import { BrowserPolicy } from 'meteor/browser-policy-content';
import { BrowserPolicy } from 'meteor/browser-policy-framing';
```

I've submitted PR #8295 for this. Thanks!

**Comment by hwillson** [comment]
PR #8295 was merged, so this functionality will be coming in a future release of Meteor. Closing this off - thanks for reporting this originally!
