### ISSUE TITLE
[1.3.2-rc.0] registerBuildPlugin packages compile node_modules/**

### ISSUE THREAD

**Issue by jiku** [meteor/meteor#6767]
`lalomartins:markd` attempts to compile .md files in `node_modules/**`.

Repro [here](https://github.com/jiku/meteor-tests/tree/packages/lalomartins-markd/1.3.2-rc.0).

Happens with `node_modules/**/*.md` having code examples.

Example error

```shell
=> Errors prevented startup:

  While building the application:
  node_modules/radium/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/README.md:31: Markdown compiler error: Expected `}}`
  ...or example, <code>{{a}</code> will match ...
  ^
  node_modules/radium/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/README.md:33: Markdown compiler error: Expected IDENTIFIER
  ...9;]  expand(&#39;{{A..C},{a..c}}&#39;) //...
  ^
  node_modules/radium/node_modules/inline-style-prefixer/README.md: Markdown compiler error: Expected "h1" end tag
  ...png" width=600></div> </h1> <a href="http...
  ^
  node_modules/radium/CHANGELOG.md:39: Markdown compiler error: Expected identifier, number, string, boolean, or null
  ...f={url} style={{color: &#39;gray&#39;, &#...
  ^

=> Your application has errors. Waiting for file change.
```

**Comment by talha-asad** [comment]
I just love it they have an rc0 for 1.3.2

**Comment by benjamn** [comment]
This is a really interesting unintended consequence of https://github.com/meteor/meteor/commit/a073280e3f769886d6e3022f976b11e97b8f0142. Thanks for bringing it to our attention!

The code in that commit keeps searching nested `node_modules` directories as long as it keeps finding source files that can be handled by build plugins (other than the usual `.js` and `.json` files).

Markdown files are an Achilles' heel for this approach, however, since virtually every npm package contains at least one `.md` file: namely, `README.md`. And then suddenly the `lalomartins:markd` package must handle many more markdown files than it did before, which inevitably exposes parsing problems.

The best idea I have right now is to let build plugins opt into searching `node_modules` directories for additional sources.

**Comment by jiku** [comment]
Thanks! Just tried from checkout and it's fixed. If more build plugins would be affected opt-in makes a lot of sense.
