### ISSUE TITLE
[1.3] babel-runtime module not found when using `meteor npm` (v2), but works with `npm` (v3).

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#6799]
I made a [demo](http://forums.infamous.io/t/new-demo-marrying-the-scene-graph-with-the-dom/195) with Meteor, and I found that if I use `meteor npm` (npm@2.14.22) to install dependencies that I get this error in the browser (my friend could reproduce it too):

```
Uncaught Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
```

If I use my local `npm` (npm@3.8.3) to install dependencies, it works just fine and I get no error.

To reproduce the error, run these steps:

```sh
git clone git@github.com:trusktr/site.git
cd site
git checkout infamous-motor-html-2
meteor npm install # npm@2.14.22
meteor
```

To get it working, run these additional steps:

```sh
rm -rf node_modules
npm install # npm@3.8.3
meteor
```

Why might this be?

**Comment by benjamn** [comment]
That's very likely because `npm@3` hoists conflict-free packages to the top-level `node_modules` directory as much as possible, which gives a flatter structure to your npm packages, but can also make packages like `babel-runtime` accidentally available to packages that don't explicitly depend on it.

I think the best practice with `babel-runtime` is to depend on it explicitly in your app, so you probably want to do `meteor npm install --save babel-runtime@5`.

**Comment by abernix** [comment]
@trusktr I'm closing this per what Ben explained which seems to make sense, but if you're still having problems, feel free to write back with additional details and @mention me for reopen.

**Comment by mdkshuvo** [comment]
Unable to install babel-runtime
![bable](https://user-images.githubusercontent.com/30826181/33058170-84515258-ceb8-11e7-8158-2333a4acb54b.jpg)

**Comment by abernix** [comment]
@mdkshuvo What version of Meteor is the `shoppingcart` application using?  `meteor --version` within the `shoppingcart` directory should give the answer to that!
