### ISSUE TITLE
check() failing without details

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#6800]
I'm not sure what's happening, as there are no detailed errors provided, but here's what I've got, data-wise:

```json
{
  "title": "test",
  "description": "description here",
  "orgId": "95Wct9LbcLovDn55b",
}
```

When I pass this into a Meteor method, I run a check:

```javascript
  validate(args) {
    console.log('validating:', args);
    check(args, {
      _id: Match.OneOf(String, undefined),
      title: String,
      description: String,
      orgId: String,
      tagIds: Match.OneOf([String], undefined),
    });
  },
```

The output of the log statement:

    validating: Object {_id: undefined, title: "test", description: "description here", orgId: "95Wct9LbcLovDn55b", tagIds: undefined}

Yet I get an error:

    errorClass {error: 400, reason: "Match failed", details: undefined, message: "Match failed [400]", errorType: "Meteor.Error"}

Usually it tells me which field failed and why, but not in this case. I can even change `tagIds` to match `Match.Any` and it still fails. So I'm thinking this is a bug.

Meteor 1.3.1

**Comment by ffxsam** [comment]
@benjamn ?

**Comment by KHam0425** [comment]
I was having crazy check() failures Monday where the check would fail String as result was null when expecting string.  So, I changed it to Match.any and it tells me that it's failing because result was string when expecting undefined.  I finally just gave up.  I have no answers, as the behavior was so erratic that I couldn't even figure out where to start looking.

**Comment by abernix** [comment]
Having worked on `check` recently, I'll chime in here.

First of all, there was a breaking change to `check` in Meteor 1.3, however best I can tell, it only would have affected `Match.Optional` and the new (in 1.3) `Match.Maybe` method.

@ffxsam I'm not having any success reproducing what you have said here – and I have made test repos with Meteor 1.2.1, 1.3.1 *(your stated version)* and 1.3.2 to try and confirm.

Here are the test repos.  The concept you provided works *identically* in all three versions.

* 1.2.1: https://github.com/abernix/check-check-1.2.1
* 1.3.1: https://github.com/abernix/check-check-1.3.1
* 1.3.2: https://github.com/abernix/check-check-1.3.2

In regard to the error not telling you the field that's failing: The client (browser) will never report the true error – it will always "sanitize" the result and say `Match failed` – this is for security reasons to avoid leaking anything potentially sensitive to the client.  If you want the **true** error, you will need to look in your **server** error console – the error should have been printed in your server error logs directly below the `validating` `console.log` you posted above, but you didn't include it?  Did it not print anything else in your server logs?

If this is a server method and you're calling it from the client with the data that you provided (i.e. w/o `_id` and `tagIds`), I'm not sure why the validating object would be printing it *with* undefined values.  This is not the expected result, and again, I was not able to re-produce that in these reproduction repos.  

Additionally, `undefined` cannot be serialized by `EJSON` (it is only able to handle `null`) so if that *were* the data being sent by the client, it wouldn't make it to the server in that form.  (e.g. `Meteor.call("method", { param: undefined })` would arrive to the server as an empty object).

So yea, in 3 versions of Meteor, what you are saying never seems like it *would* have worked.  Could you provide a test repo that shows exactly what you're encountering?

@KHam0425 More information/examples would be helpful to see how this might be related to your issue.

**Comment by KHam0425** [comment]
I had to remove audit-argument-checks because it insists that I'm passing more arguments to my method call than I am.  I was sending a single string from the client template event to the server method, and then calling HTTP.get to a URL.  I was sending a string slug through to the method, which was concatenated with the API key.  Even though I was only sending a single string, I was getting error messages that I wasn't checking all arguments, even though there was only one.  

It seemed that there were at least two arguments coming through, one of them a string, and another an object.  When I would try to log to the console before checking, the phantom argument would change to undefined or null.  Sometimes the phantom would arrive first, causing the string argument to fail the check, as "was expecting string, got object", and if I changed the order of the check, it would fail "expecting object, got undefined".  

I finally just removed audit-argument-checks, changed check(arg, String) to var isString = Match.test(arg, String), added a dummy argument to the method function and just check that dummy argument against Match.Any without using it again.  This happened on a few of my methods since updating to 1.3.  I'm just a hobbyist, so I found a convenient way to move on for now, assuming that it will eventually get worked out.

**Comment by abernix** [comment]
@KHam0425 Ok, I hadn't tried anything with `audit-argument-checks` installed, but just tested it and it still appears to be working fine even with it enabled (and barf-ing properly when `check` is missing).  You might be experiencing a different issue – unrelated to this one.

Perhaps a small reproduction app uploaded to github would be helpful to assist you and then we can decide whether or not your problem needs to be broken out into a separate issue.

**Comment by KHam0425** [comment]
I'll keep it in mind.  If I can think of a way to isolate to repro the issue in something encapsulated, I'll post it.  Otherwise, I'll just monitor things as updates are released for 1.3.  I'm sure people with a LOT more experience than I will pick up on it if my issue is legitimate.  My issue wasn't necessarily that it wasn't showing an error when I wasn't checking arguments, it was that the two combined were "seeing" arguments that I wasn't sending, and then "barf-ing" because I didn't check an argument that I didn't send.

**Comment by abernix** [comment]
@ffxsam I just saw your new `check` issue, but can we get this one settled up too?  You'll see in the repos I made that everything appears to be normal.

**Comment by ffxsam** [comment]
Ok, so #6959 is related, then. When I run a check on my example way above (in the meteor shell) I get:

```
Error: Match error: Missing key '_id'
    at exports.check (packages/check/match.js:34:1)
```

So at least I'm seeing a proper error now.

**Comment by abernix** [comment]
Again, you will always see the proper error in your meteor shell, but you will **not** see the proper error in the browser console, for security reasons.  Nothing has changed on that behaviour.

**Comment by abernix** [comment]
Can this be closed then, @ffxsam?

**Comment by ffxsam** [comment]
Yep!
