### ISSUE TITLE
Support build.json for Code Signing iOS in Cordova

### ISSUE THREAD

**Issue by chip** [meteor/meteor#6815]
Although working with Meteor is a joy, fighting with Xcode to generate a successful build or **manually Code sign each of my iOS builds is a total pain.**

Maybe I'm missing something here, and if so I apologize in advance for my ignorance. I have experimented with using `cordova-build-override/config.xml`, but am not finding that it helps me much in this regard. In fact, the Meteor docs on [Advanced build customization](http://guide.meteor.com/mobile.html#advanced-build) recommend not using this approach unless absolutely necessary, so I'd like to find an alternative approach.

**To that end is there some way to support a `build.json` file in Meteor?**

Per the [Cordova docs on Signing an App in iOS](http://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#signing-an-app), you can create a `build.json` file and reference it with the `--buildConfig` argument for **Code signing** the app.

I'm not sure how this would be done from within Meteor or from an external package. **If someone could offer suggestions on how to hook this into Meteor, I might take a stab at building it if I can wrap my head around it.**

I appreciate everyone's effort on Meteor. Thank you.

**Comment by martijnwalraven** [comment]
In most cases, I think using Xcode to build your project is probably preferable because it gives you better error messages and also gives you access to the publishing workflow. In fact, in Meteor 1.3.1 `meteor build` no longer tries to build your Xcode project (this was done to work around a Cordova bug, but also improves performance because you'd be redoing that work in Xcode right after).

I understand setting up your code signing details manually is a bit of a pain however. I've never used `build.json`, but it seems like a nice solution. I don't know at what stage it does its work and if `--buildConfig` is supported for `cordova prepare`, but if it is, using it should be relatively simple. [This file](https://github.com/meteor/meteor/blob/devel/tools/cordova/project.js) is probably a good starting point.

**Comment by chip** [comment]
@martijnwalraven - Thanks for this tip!

**Comment by Type1J** [comment]
Using `meteor run` is desirable, and it currently doesn't seem to work for iOS.
