### ISSUE TITLE
jquery is overwritten

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6830]
*Reposted from #6626, as it's been closed*

I'm on `1.3.2-rc.5`, I've got a lot of atmo packages that depend on atmo `jquery`, so I can't remove it. 

When I `npm remove --save jquery`, I get browser console error on pageload `cannot find module 'jquery'`, probably because I have npm packages that depend on jquery. 

When I have both npm and atmo jquery installed, with the npm version at `2.2.2`, I have this problem:
- I log `$.fn` from inside an npm package jquery plugin, and the logged object has my plugin listed, and `$.fn.jquery` is `2.2.3`
- After everything has finished loading, I look at `$.fn` in JS console, and it no longer has my plugin. `$.fn.jquery` is `2.2.2`

So it looks like the atmosphere jquery is being loaded first, then non-jquery npm packages, then npm jquery, overwriting `$`? Lmk if there's anything I can do to further diagnose ☺️

cc @benjamn

**Comment by lorensr** [comment]
Same behavior on `1.3.2.2`

**Comment by trajano** [comment]
I am using a legacy plugin that depends on JQuery-UI,I haven't been able to get JQuery UI working properly via NPM because that plugin does not use the imports/requires facility.  The only way I had to get around it was to use the existing JQuery and JQuery-UI (ruslan:jquery-ui) via atmosphere.

To help your situation, maybe you need to find the atmosphere version of the plugins you are using or migrate the code into your own code base.

**Comment by lorensr** [comment]
@benjamn Does the situation make sense? Do you have an idea of why, or should I make a reproduction to study?

Any workarounds other than wrapping with atmosphere?

**Comment by benjamn** [comment]
The background I can give you is that the Atmosphere `jquery` package now attempts to load `/node_modules/jquery` from your app, if installed. See [here](https://github.com/meteor/meteor/blob/fac2809e3320f8707ad4e257a4b2c2ff9ead670a/packages/jquery/main.js#L4).

Also, the global version of `$` could be changing because of [this code](https://github.com/meteor/meteor/blob/fac2809e3320f8707ad4e257a4b2c2ff9ead670a/packages/jquery/main.js#L15-L16), so the `$.fn` you see in the console may be different from the version that code inside your app (including npm packages) will see.

If you can run Meteor [from a checkout](https://github.com/meteor/meteor#slow-start-for-developers), you might try commenting out those lines to see if anything changes. Alternatively, you could assign `$` to some uniquely-named global variable in the plugin package, and then inspect that variable in the console.

**Comment by lorensr** [comment]
The version of npm jquery that I include in my `package.json`, `2.2.2`, is being used by atmo `jquery`, and is overwriting the version of npm jquery that my npm jquery plugins have access to when they are evaluated, `2.2.3` (for instance the version of `node_modules/intl-tel-input/node_modules/jquery`.

![image](https://cloud.githubusercontent.com/assets/251288/15168205/5a6bae58-16fd-11e6-8148-7a6910846c8e.png)

When I use a local version of atmo `jquery` in `packages/`, commenting out either the `require('jquery')` or the `exports. and global.` lines both lead to:

![image](https://cloud.githubusercontent.com/assets/251288/15168242/b98dbfac-16fd-11e6-8980-12abea0eb03f.png)

On the other hand, if I change it to never use npm:

```js
var jQuery = require("./jquery.js");

// try {
//   console.log('XXX npm')
//   var jQuery = require("jquery");
// } catch (e) {
//   console.log('XXX atmo');
//   jQuery = require("./jquery.js");
// }
```

and comment out `node_modules/jquery/dist/jquery.js`, then my npm jquery plugins throw errors on page load.

**Comment by benjamn** [comment]
If you can put together a reproduction, I can take a closer look.

**Comment by lorensr** [comment]
Haha, I was about to say no problem, but in my simple reproduction, the
jquery plugin gets v2.2.2. Not sure what in my setup could be causing the
difference

**Comment by lorensr** [comment]
Looks like it was something to do with this plugin's support for UMD. On the last line I replaced `$` with `foo` so that `$` would be `window.$`, which was the correct npm version of jquery. 

Since I can't reproduce in a simple example, let's close this until/unless other people also have the problem.

```
/*
 * International Telephone Input v8.4.9
 * https://github.com/jackocnr/intl-tel-input.git
 * Licensed under the MIT license
 */
// wrap in UMD - see https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js
(function(factory) {
    if (typeof define === "function" && define.amd) {
        define([ "jquery" ], function($) {
            factory($, window, document);
        });
    } else if (typeof module === "object" && module.exports) {
        module.exports = factory(require("jquery"), window, document);
    } else {
        factory(jQuery, window, document);
    }
})(function($, window, document, undefined) {
```

**Comment by lorensr** [comment]
Similarly, another library I used was wrapped in the below during a build step, perhaps by browserify:
https://github.com/codrops/ElasticProgress/blob/master/gulpfile.js
```js
(function(f) {
    if (typeof exports === "object" && typeof module !== "undefined") {
        module.exports = f()
    } else if (typeof define === "function" && define.amd) {
        define([], f)
    } else {
        var g;
        if (typeof window !== "undefined") {
            g = window
        } else if (typeof global !== "undefined") {
            g = global
        } else if (typeof self !== "undefined") {
            g = self
        } else {
            g = this
        }
        g.ElasticProgress = f()
    }
})(function() {
```

The intended export, `ElasticProgress`, no longer appeared as a global after upgrading to 1.3. 

I fixed it by replacing the above with:

```js
(function(f) {
  window.ElasticProgress = f()
})(function() {
```
