### ISSUE TITLE
Meteor should install npm packages automatically (feature request)

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor#6848]
I looked for issues regarding `npm install` but didn't see any that matched this request so apologies if it already exists and is buried somewhere.

I just cloned an app that has npm packages in it and ran `meteor` as usual. But then it gave me warnings that it was unable to resolve some npm modules. I quickly discovered that the reason was that I hadn't ran `npm install` and installed the packages.

With Meteor's philosophy of making development easy, I'd assumed that running `meteor` would automatically run `npm install`. So it'd be great if running `meteor` did this.

**Comment by Primigenus** [comment]
A step further: Meteor should be able to find all import statements in code, update package.json, and npm install the result.

**Comment by stubailo** [comment]
I guess the question is - of all of the things that could be improved in Meteor, is this really the top thing?

**Comment by mquandalle** [comment]
The fact that with previous versions of Meteor we could:

```
$ git clone http://somerepo.git 
$ cd somerepo
$ meteor run
```

and have a reproducible result has always been an important feature of Meteor and largely contributed to the good developer experience. Now with 1.3, not only do we have to `meteor npm install`, but even more, this extra step introduces an important source of non-determinism:

* People might forget to run `meteor npm install`, depending on the NPM packages used the app may still launch but will fail at runtime;
* Different versions of NPM might produce different results (`npm install` vs `meteor npm install`);
* NPM itself is non-deterministic especially when the pacakge version resolution is based on `package.json` manifest instead of a npm shrinkwrap.

So while I agree that the integration of NPM is awesome, and that MDG was right to release 1.3 even with the extra NPM installation step, I think that automating the npm installation from a npm shrinkwrap is indeed an important feature that will save a lot of cumulated time to Meteor developers.

**Comment by serkandurusoy** [comment]
Hah, I just came here because I wanted to post a feature request for `meteor npm install` to also imply `meteor npm shrinkwrap` because the new npm integration breaks out of box repeatable builds strategy and it also makes sense because using npm from packages already does this, so why not the app itself?

**Comment by jlukic** [comment]
Was very very surprised that meteor doesnt at least run `npm install` for npm deps. Found our whole company struggling to figure what was going on with missing dependencies after we decided to swap in some npm deps to try them out.

Would make sense that npm packages functioned at parity to atmosphere packages, as this was how meteor set the baseline expectations for package management.

**Comment by pierreozoux** [comment]
Agree with all the discussion here, the thing is we are used to all this automation out of the box, so then, it is really surprising when we need to have extra steps.
As noted in #7059 lost few hours to setup my CI because of that.
[Meteord](https://github.com/meteorhacks/meteord) is also broken because of that.

**Comment by mquandalle** [comment]
Could a core developer acknowledge that this is a relevant issue worth fixing?

**Comment by laosb** [comment]
This is essential to improve development experience.

**Comment by edwardupton** [comment]
+1

**Comment by jetlej** [comment]
+1

**Comment by bluebackground** [comment]
As I was learning about meteor, many of the tutorials and resources I used showed how meteor was easy to start up, "meteor create newapp, cd newapp, meteor" - it seemed to be one of the defining features. I'm still new to meteor, but I heard "meteor npm install" was added to accommodate  coffee script. Can this be added as an Meteor package instead so it automatically gets loaded? It seems like a 'tradition of sorts' to not have to do any other steps to set up a project.

**Comment by benjamn** [comment]
Just submitted a pull request for this (see above)!

**Comment by benjamn** [comment]
If you do
```sh
meteor create --release 1.4.3-beta.0 143b0-test
ls 143b0-test
```
you should see that `node_modules` are installed already.

**Comment by mattmccutchen** [comment]
The original feature request was to automatically install npm packages on a new checkout of an app, not when an app is first created.  @benjamn, are you intentionally declining that part of the request (in which case users such as myself who want to keep the experience from https://github.com/meteor/meteor/issues/6848#issuecomment-212184034 still have the option to use a wrapper Atmosphere package and `Npm.depends`, at least for now)?

**Comment by benjamn** [comment]
@mattmccutchen Yes, I'm deliberately declining that feature request. If your project uses `yarn` or `npm-shrinkwrap.json` or some other strategy, it definitely would not be appropriate for Meteor to run `npm install` for you whenever someone clones your repository. Meteor can't even assume that you're using `git`, so it's not clear how Meteor would know when you've just cloned the app. In fact, according to some brief research,`git` doesn't support anything like a `post-clone` hook, so I suspect you may be referring to a somewhat ill-defined event.

**Comment by mattmccutchen** [comment]
Sorry, I probably should have gone ahead and revised the feature request: have a per-app option for Meteor to automatically install and remove npm packages to match a shrinkwrap file in the app.  If some users are excited to manage their packages with another tool on every checkout, fine, but the users on this thread just want to keep Meteor's trademark simple checkout procedure and predictability (https://github.com/meteor/meteor/issues/6848#issuecomment-212184034), which we've now lost in 4ce343f even if we don't use any packages of our own.

I don't care if the option is on by default.  The most reasonable place to put it is probably in `package.json`.  It may be possible to share code with the `Npm.depends` implementation for Atmosphere packages.

**Comment by benjamn** [comment]
Adding additional configuration options only simplifies your developer experience if you're happy with the defaults. We can add various helpful warnings about running `meteor npm install`, but I'm really not interested in running it automatically, except in a brand new app, as I explained in https://github.com/meteor/meteor/pull/8108.

If you want to continue this discussion, you'll need to be a lot more specific about what the configuration options would be, and how they enable (or at least don't discourage) use cases other than your own.

**Comment by mattmccutchen** [comment]
Straw man proposal: if `meteorAutoInstallDeps` is set to true in `package.json`, then `meteor run` automatically updates the application's `npm-shrinkwrap.json` and `node_modules` based on the dependencies in `package.json`, the same way that building a local Atmosphere package in `packages/foo` automatically updates `packages/foo/.npm/package/{npm-shrinkwrap.json,node_modules}` based on the `Npm.depends` in `packages/foo/package.js`.

I think the existing workflow for `Npm.depends` is pretty much what we want here (i.e., for reproducibility, if there's an existing shrinkwrap that satisfies the dependencies, then use it, otherwise generate a new shrinkwrap), but there may be minor things we'd want to change.

Thoughts?  Does this sound good to everyone who gave thumbs up to https://github.com/meteor/meteor/issues/6848#issuecomment-212184034?

**Comment by mattmccutchen** [comment]
Possibly better idea: Just have a shell command in `package.json` that is run by `meteor run` and at other times the `node_modules` is needed, and maybe have a way to specify additional files that Meteor should watch in order to trigger a re-run of the command.  If necessary, an app developer could ship a custom script with their app and call that script.  I'm not sure if there's a simple way to emulate the conditional shrinkwrap update behavior of `Npm.depends` using only the tools distributed with Meteor, but I'd be satisfied if I could set the command to `meteor npm prune && meteor npm install` and manually update the shrinkwrap file when I change the dependencies in `package.json`.

Possible variant: allow the command and watch set to be specified in an Atmosphere package, so people could publish Atmosphere packages for integration with different node package management tools.  (Though this would conflict with the [plan to deprecate Atmosphere packages in favor of npm](https://guide.meteor.com/atmosphere-vs-npm.html).)

If the previous proposal isn't flexible enough but this one is too dangerous, then we are in a catch-22...

**Comment by benjamn** [comment]
I can get behind the general idea of adding configuration options to `package.json`, perhaps in a special `"meteor": {...}` section.

In particular, I could support an option that provides a command to run on startup if the `node_modules` does not exist, and by default this command could be `meteor npm install`. Note that this command should be executed with a `PATH` that guarantees it uses the same `meteor` command that was used to run the project.

If we support arbitrary commands, I don't think it makes sense to implement any shrinkwrapping logic, since that's only relevant for certain workflows.

I disagree with watching files in order to rerun the command, mostly because `npm install` can be very slow with lots of dependencies, even if the changes are small, and I do not want Meteor to appear responsible for that slowness.

**Comment by mattmccutchen** [comment]
OK... But if the file(s) that specify the dependencies (e.g., `package.json`, but the precise set of workflow-specific files could be configured in `package.json`) are modified, e.g., by switching to a different branch or revision of the app using version control, I want Meteor to automatically update `node_modules` to maintain predictability.  The default command would be `meteor npm prune && meteor npm install`, and users could specify an analogous command using another package manager.  Only changes to the specified dependency configuration files would trigger the re-run.  To avoid an unnecessary re-run when `meteor run` starts, Meteor could save the file hashes on disk somewhere.

Even if the package manager is slow, I don't see any reasonable use case for a user to modify the dependencies but want Meteor to run the app using the old dependencies.  I guess users could complain about having to wait for the package manager if they make an unrelated change to one of the files that contains dependency configuration, e.g., changing `version` in `package.json`.  If it really bothers them, they can write a script that does a smarter check before calling the actual package manager (or choose a better package manager, or disable the feature).

**Comment by benjamn** [comment]
At this point I may just have to ask you to submit a pull request. The burden is on you to demonstrate that your desired functionality is in the interest of every Meteor developer, and that the additional complexity is worth the benefit. The current API for manipulating npm dependencies is `meteor npm ...`, a thin wrapper around the right versions of `npm` and `node`. Making that API even more Meteor-specific requires extraordinary justification, and I would challenge you to investigate it thoroughly, rather than glossing over the most critical parts of the implementation.

**Comment by mattmccutchen** [comment]
OK, that's fair.  I don't know when or if I will get around to doing this work myself, but at least the door is open.  Would anyone else on this thread be interested in helping?  Do others agree that it's important to automatically update `node_modules` to match `npm-shrinkwrap.json` (or whatever equivalent for another package manager) after switching branches, rather than just triggering an install if `node_modules` doesn't exist at all?

**Comment by benjamn** [comment]
I would prefer a new feature that makes it possible to be as clever as you like about re-running whatever command you need to run, but that makes as few assumptions as possible about the structure of the application.

Some unexamined assumptions that you're still making:
* "branches" exist
* switching branches is a well-defined event
* `npm-shrinkwrap.json` exists, or is likely to exist
* the set of files that might affect the behavior of `npm install` (e.g. `npm-shrinkwrap.json`, `yarn.lock`, etc.) is knowable
* re-running the command is worth the cost every time the output might have changed

If you really care about reproducible installs, you should probably be using `yarn`, so it would be unfortunate to implement a version of this functionality that privileges `npm` over `yarn`.

**Comment by mattmccutchen** [comment]
Conditions 4 (with an arbitrary package manager in place of `npm install`) and 5 are the critical assumptions for the automatic re-run feature to be useful.  (As I mentioned before, some workarounds may be possible for condition 5, such as setting the command to a script that does additional checks before calling the real package manager or even just prints a warning to the console for the user to run the package manager if desired.)  I'm speculating that these conditions hold for enough Meteor users for the feature to be worth adding to Meteor; other users just wouldn't enable the feature.  How can we get better data about this?  I know little about `npm` and even less about alternative package managers.  Can you speak for `yarn` users?

Conditions 1-3 are not assumptions of the design:

- Switching branches, `git pull`, etc. are motivating use cases for the automatic re-run feature, but Meteor doesn't need to know anything about these operations; it just sees changes to the specified watch files.

- Re condition 3: The default watch list would be `['package.json', 'npm-shrinkwrap.json']`, corresponding to the default command of `meteor npm prune && meteor npm install`, but the watch list can be overridden along with the command to use another package manager.  If what you really meant was "the specified watch files are sufficient for the specified command to do an install that is reproducible in the sense the user cares about, under certain assumptions that the user is willing to make", then yes, that is the most compelling usage scenario, analogous to how Atmosphere package installation works today. But even if the installation isn't reproducible (e.g., npm without `npm-shrinkwrap.json`), Meteor is still automating the process of getting _any valid_ installation for the current state of the watch files, which the user would otherwise have to do manually or automate via other means.

**Comment by mattmccutchen** [comment]
I'd invite anyone wanting this feature to try my prototype implementation in #8165 and let me know if you run into any problems.
