### ISSUE TITLE
[feature] Core 'modules' package - more data in addStyles method in css.js

### ISSUE THREAD

**Issue by juliancwirko** [meteor/meteor#6857]
Is there a way to get not only css content in the 'modules' package -> css.js -> addStyles method, but also the extension and filename of the imported file? Or could it be implemented? Then we could build upon it. Also it would be awesome if 'modules' package could be replaceable (ecmascript implies it) or css.js file could be moved to another replaceable package so we would be able to experiment with this particular functionality. For example with something like: https://github.com/juliancwirko/meteor-css-modules-test

**Comment by benjamn** [comment]
I definitely agree that hard-coding `modules/css` was an unfortunate sacrifice of flexibility, and I'm open to making it more flexible.

Passing the filename to `addStyles` should be easy, though it will require changing https://github.com/meteor/meteor/blob/devel/tools/isobuild/css-modules.js and the two places where `cssToCommonJS` is called.

Totally replacing the implementation of `addStyles` is a little trickier. The quickest way to get it to work would be to wrap/monkey-patch `require("modules/css").addStyles` with a custom function. Another option is to split that functionality out of the `modules` package, so that it can be more easily replaced by another package. That functionality could move into an npm package or another Meteor package, though I'd like to avoid hard-coding the package name again.

Pull requests are welcome for either of those ideas!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bfeature%5D%20Core%20'modules'%20package%20-%20more%20data%20in%20addStyles%20method%20in%20css.js&body=Migrated%20from:%20meteor/meteor%236857) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
