### ISSUE TITLE
No callback invoker for method

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#6871]
Before describing my problem in details I would like to ask about two errors that I get in the client console when executing Meteor method:
- No callback invoker for method 7
- Methods should only receive results

What do they mean and in what situations they can be thrown?
I'm calling Meteor method that is defined in both client and server. And the line which is causing problem is getting document from the collection. But as I said, first I would like to know what does errors mean. Thanks!

**Comment by abernix** [comment]
Hello,

Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

In addition to checking out the [Todos Example App](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials), we highly recommend you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
