### ISSUE TITLE
EPERM, unlink '...\merged-stylesheets.css'

### ISSUE THREAD

**Issue by GrushinEgor** [meteor/meteor#6875]
![image](https://cloud.githubusercontent.com/assets/6255315/14711377/cbb6032c-07e1-11e6-910e-70a71281bd42.png)
It causes very often

**Comment by laosb** [comment]
Would you like to make a reproduce?

**Comment by GrushinEgor** [comment]
@laosb It happens unexpectedly, randomly. But, what I notice it happens often when my RAM comes to the end (80-90%).

**Comment by laosb** [comment]
`EPERM` looks like a permission issue. But it might be a memory issue.

**Comment by abernix** [comment]
@GrushinEgor, A lot has changed with Meteor since you opened this issue.  Can you try and reproduce this with the latest version of Meteor?  You can try updating with:

    meteor update --release 1.3.4.4

If it still happens, can you test and see if you experience the same problem if you keep everything on your `C:\` drive instead of `D:\`?

**Comment by laosb** [comment]
Close due to inactivity. If someone found this again, please open a new issue or comment below.
