### ISSUE TITLE
Ability to install specific versions.

### ISSUE THREAD

**Issue by nickpolet** [meteor/meteor#6915]
Currently, installing meteor through install.meteor.com forces the user to install the latest version of meteor. While this is great, it would be useful to install specific versions of meteor onto a fresh server/dev machine.

Forcing the latest version makes it difficult to automate build systems on a server. If you are targeting specific versions, you have to install the latest version, then 'downgrade' to the app specific version. This seems wasteful and unnecessary. Considering that installing specific package versions are a core feature of npm and many other package/distribution managers, I feel like this is quite important to have for meteor.

Wouldn't using something like http://install.meteor.com?release=1.3.1.1 be a better solution than forcing the latest version? Is the script at install.meteor.com generated dynamically or is just a static script that is served?

This does mean that all version will have to be available on a CDN (not sure about using github releases as a source for the .tar.gz files), but I don't see how this would be difficult to maintain. Could be automated to grab releases from github and serve them from a CDN. Maybe this already happens.

I can't see how adding this would have any detrimental behaviour to how it currently runs, only adding flexibility to installing specific versions.

Installing specific versions can currently be done by using a modified version of the install.meteor.com script, but this shouldn't be necessary to install specific versions.

**Comment by abernix** [comment]
@nickpolet The download from `install.meteor.com` is the latest version of the meteor *tool*, however the tool will always run and build your meteor project with whatever version you have already have used in your project (see your `.meteor/release` file), or whatever you pass with the `--release <version number>` flag.  It will not just run your project with the wrong version.

**Comment by lucidprogrammer** [comment]
Yes this is very helpful in build automation use cases +1

**Comment by abernix** [comment]
@lucidprogrammer Given what I said, can you elaborate on why this is necessary for you?  Again, your project will always run using the version your project was created with, regardless of what is downloaded from `install.meteor.com`.

**Comment by lucidprogrammer** [comment]
This helps mainly in build automation. For example, consider this dockerfile [Dockerfile](https://github.com/lucidprogrammer/meteor-production-base/blob/master/Dockerfile)

For ci/cd, I use wercker where I supply specific base images. It could be helpful. (Various projects are in different versions of meteor sometimes)

**Comment by abernix** [comment]
@lucidprogrammer That's a pretty strange setup for a Dockerfile – are you running your production meteor from the development environment?

**Comment by RobertLowe** [comment]
@stubailo this can maybe be closed now, but the install script now accepts `release` -- https://install.meteor.com/?release=1.2.1 however docs need to be updated, a co-worker magically found this...

**Comment by abernix** [comment]
Please avoid directly mentioning people in issues unless it's critical or specifically targeting them.  As it stands right now all issues are seen by those that need to see them within a couple days.

I agree that `?release=` is helpful for those running in particular CI setups, but I'm really not really sure the docs should be updated to encourage this behavior.  Perhaps a section of the guide particular to running CI configurations could mention this, in addition to suggesting something like the recently proposed `--no-release-check` flag in #7445?

The problem I see with making this option too obvious is that the `meteor-tool` itself is the tool responsible for delegating to previous versions of `meteor-tool` and provides seamless switching between versions.  The latest tool is always meant to run previous versions (and will always run whatever is in the project's `.meteor/release` file).  As I stated above you don't need to do anything to keep your project running the same version.  However, the tool itself has very important changes to maintain compatibility and even provides improvements on running existing versions.  Plus, I'd argue that users should be getting nudged in the direction of newer versions instead of pinning themselves to old versions.

Plus, without something like #7445, there is really no point to installing using `?release=` since `meteor-tool` is just going to download the latest release in the background anyway.

I will close this issue though since, as you can now see, it is possible to do what is being requested in the OP.  Thanks for helping to keep on top of outstanding issues like this!

**Comment by Alino** [comment]
this is my install command but it still downloads  meteor 1.4.0.1 😢 
```curl -sL https://install.meteor.com/?release=1.2.1 | sed s/--progress-bar/-sL/g | /bin/sh```
am I doing something wrong?

**Comment by mgrivera** [comment]
Hi all, 

I can clearly see the point @abernix  is trying to explain: 

1) We download and install the _Meteor tool_ from Meteor site (I'm on Windows)
2) We _create the app_ with specific version: **meteor create --release 1.2.1 myapp**

What happens is **meteor create --release 1.2.1 myapp** hangs forever and does never finishes (I even let it run for two full days and never stopped working). 

Now, can I do what @Alino did in **Windows**, which is the machine I'm using? Can I open Chrome and go to: 

https://install.meteor.com/?release=1.2.1 

What I need to do is install Meteor in a dev machine and create our app but using, specifically, release 1.2.1. 

Many thanks for your help and bye ...

**Comment by Alino** [comment]
I think your stuck download is this CDN issue https://github.com/meteor/meteor/issues/6960
I fixed it by adding this in to my hosts file:
```54.192.225.217 warehouse.meteor.com```

**Comment by mgrivera** [comment]
Thanks, yes, that should be the issue. Didn't know that issue existed at all. Thanks again ...
