### ISSUE TITLE
[TAP-I18N] Packages translations not merged on server startup

### ISSUE THREAD

**Issue by lubianm** [meteor/meteor#6919]
After upgrading to Meteor 1.3 we're experiencing an issue with packages translations on development environment: on each server startup we lose packages translations (managed with TAP-i18n) because they are missing (looking on client's built package) on .js package file. 
See, for detailed reference, issue [TAPevents/tap-i18n#161](https://github.com/TAPevents/tap-i18n/issues/161).
On Meteor 1.2 the translations worked perfectly; is there anyone else experiencing the same problem ?

**Comment by laosb** [comment]
Could you provide a clear repro?

**Comment by ramezrafla** [comment]
@lubianm is this still an issue? (Helping clean up those hundreds of issues)

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
