### ISSUE TITLE
Special characters (@) removed from file names inside bundle

### ISSUE THREAD

**Issue by gbhrdt** [meteor/meteor#6945]
When creating a bundle with `meteor build` for deployment, I have files containing `@`s in their names in my `private` directory (e.g. `icon_32x32@2x.png`). The `@` is just getting stripped out inside the bundle. I am using the latest version of meteor.

**Comment by Slava** [comment]
I suspect it is because Meteor's build-system "sanitizes" the file-names? I think this is the line of code that does it: https://github.com/meteor/meteor/blob/49c9d07be833561a789f57581416638bca4d249d/tools/isobuild/builder.js#L164

**Comment by gbhrdt** [comment]
Yes, I think so, too. There should probably rather be a 'blacklist' of special characters instead of a 'whitelist'.

**Comment by laosb** [comment]
So we just need to tell users about the sanitizing, or change this behavior?

**Comment by gbhrdt** [comment]
I would suggest to change this behaviour, because filenames like `icon16x16@2x.png` are not uncommon for e.g. iOS projects.

**Comment by laosb** [comment]
I agree. For now it doesn't seem like a bug ,neither like a feature. Hard to label.

**Comment by abernix** [comment]
I would have probably proposed `/\:*?"<>|` as the blacklist – and ideally, I think it would be best as a (very conservative) blacklist.  I'm surprised that `:` is currently allowed right now as up until recently it caused problems with HFS/HFS+.  What do we think the whitelist would look like?  Apple's recommended cross-platform filename practices [are here](https://support.apple.com/en-us/HT202808).

**Comment by hwillson** [comment]
I like @abernix's proposed blacklist. Based on what's currently implemented and that blacklist, we just need to prepare changes that allow `@` and disallow `:`. Allowing `@` is easiest, since it will be backwards compatible. Anyone who was using `@` will have had to manually remove it from their filenames, to work around this issue, so allowing it now won't impact existing applications. Disallowing `:` however is not backwards compatible. Applications that are currently expecting `:` to be available would have to be updated. 

I'll submit a PR to address `@`, and we can then decide what to do about `:`. Thanks!

**Comment by hwillson** [comment]
PR #8502 has been merged, so `@` support will be coming very soon. Thanks for posting this originally!
