### ISSUE TITLE
Date range filter not reactive

### ISSUE THREAD

**Issue by ramzauchenna** [meteor/meteor#6963]
I have a simple publication line this 

```
Core.publish("DashOrderVolumes", function(startDate, endDate){
  console.log(arguments)
  let fields = {
    'issuedAt': 1
  };
  return Orders.find({issuedAt: {$gte: startDate, $lte: endDate}}, {
    fields: fields
  });
});
```
if i have just one condition it works i.e {issuedAt: {$gte: startDate}} alone and the data comes to the client but when i add the second range nothing happens unless i make a template change event.  I am wondering if this is a usual behavior

**Comment by stubailo** [comment]
Hi, please submit a complete reproduction for this issue -- that code snippet by itself is not enough to isolate the problem, or even to determine if the problem is in Meteor itself: https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug

You can also ask for help on the [Meteor forums](https://forums.meteor.com/) or Stack Overflow.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem. Would be happy to reopen it if you provide a reproduction repository! :)
