### ISSUE TITLE
Unpin release package versions

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#7004]
As part of our 1.4 release, we want to relax the requirement that versions of Meteor core packages are pinned by the Meteor release you are using. This document outlines the technical steps required:

- [x] Remove release constraints from the constraint solver, here-ish: https://github.com/meteor/meteor/blob/devel/tools/project-context.js#L659
- [x] Update the skeleton to generate constraints for core packages in its `.meteor/packages` based on the current package versions in the tool being used.
- [x] Write a migrator that runs on every update and:
  - [x] Rewrites `.meteor/packages` to append `@x.y.z` to all core packages based on the versions in the current release.

Notes to self:
 - Check `autoupdate` selftest

**Comment by sebakerckhof** [comment]
Will `api.versionsFrom` still work in `package.js` files?

**Comment by tmeasday** [comment]
> Will api.versionsFrom still work in package.js files?
Yes

**Comment by glasser** [comment]
Is there documentation about how this affects development of core packages?  In the past, we've been able to make the admittedly somewhat lazy assumption that we could change code in two core packages in backwards-incompatible ways (eg, adding an API to package X and assuming it is immediately available in package Y, or removing a private API from package X because its only caller in package Y has been eliminated).  What guidelines should core developers follow after this change?

**Comment by benjamn** [comment]
@glasser Short answer: we're going to have to start obeying semantic versioning.

Slightly longer answer: for sets of packages that are very intimately related, such as the `accounts-*` core packages, exact `@=x.y.z` dependency versions may become (or continue to be) a best practice.

Complete answer: `TODO`, but I agree that there should be documentation!

**Comment by benjamn** [comment]
Implemented in Meteor 1.4, which has now been released: `meteor update --release 1.4` (and soon just `meteor update`).
