### ISSUE TITLE
Cannot upsert with BSON.Timestamp in modifier

### ISSUE THREAD

**Issue by cpury** [meteor/meteor#7041]
I'm using Meteor 1.2.1 on OSX. All this happens during testing with MUNIT.

Working with the Oplog, you'll have to deal with the BSON.Timestamp data type (the `ts` value of each oplog entry). When trying to `insert` or `update`, I can `$set` values to a `ts` value without any issues.

However, when trying to upsert and `$set`ting the value there, I get the following error:

```
Exception in Mongo write: TypeError: Cannot call method 'indexOf' of undefined
    at Function.MongoConnection._isCannotChangeIdError (packages/mongo/mongo_driver.js:602:15)
    at packages/mongo/mongo_driver.js:716:47
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at /Users/max/.meteor/packages/npm-mongo/.1.4.43.1lve35j++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:572:16
    at /Users/max/.meteor/packages/npm-mongo/.1.4.43.1lve35j++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1193:22
    at /Users/max/.meteor/packages/npm-mongo/.1.4.43.1lve35j++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at [object Object].Base._callHandler (/Users/max/.meteor/packages/npm-mongo/.1.4.43.1lve35j++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /Users/max/.meteor/packages/npm-mongo/.1.4.43.1lve35j++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1760:29
    at [object Object].Connection.write (/Users/max/.meteor/packages/npm-mongo/.1.4.43.1lve35j++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:272:16)
```

Checking the Mongo Driver code you can see that there might be a more meaningful error message, but `MongoConnection._isCannotChangeIdError` is dying first... So I actually don't know what the real problem is here.

Here is an example:

```ES6
const oplogEntry = ... // Get one from the db

SomeCollection.insert({ ts: oplogEntry.ts }); // This works! :)

SomeCollection.update({ name: 'x' }, { $set: { ts: oplogEntry.ts } }); // This too! :)

SomeCollection.upsert({ name: 'x' }, { $set: { ts: oplogEntry.ts } }); // This dies :(
```

Let me know if you need any other details.

**Comment by abernix** [comment]
Hey,

We highly recommend reaching out to the [Meteor forums](http://forums.meteor.com) and StackOverflow before opening an issue here due to the large number of issues that the Meteor project receives.

*However, if you do feel like this is a bug...*

Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple example as possible) and upload that project to GitHub. Then, simply include the link to it and it will be easy for any developer to clone and see the same problem you're having and decide if it's a problem with your code, or a problem with Meteor itself.

Someone will be much more able to help you if you include this. Unfortunately, without providing a reproduction or at least very easy to reproduce steps, it's very difficult to get someone to investigate.

Thanks! 😁

**Comment by abernix** [comment]
@cpury I assume you're doing this all server-side.  Can you reproduce this on the Mongo shell?

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)

**Comment by cpury** [comment]
@abernix thanks, Jesse. I'm a little busy at the moment but if I find the time soon, I'll reopen this with further details!

**Comment by cpury** [comment]
@abernix I just build a reproduction on it using the latest Meteor version, and it seems to work. So either it was my setup, or a bug in a previous version, either way this can remain closed :)

**Comment by abernix** [comment]
Thanks for the update!  Do report back if it crops up again!
