### ISSUE TITLE
Multiple method call 

### ISSUE THREAD

**Issue by zaverichintan** [meteor/meteor#7048]
I am trying to access the collection names posts to check if the current user has already liked or not . If liked then showing liked button in different color.
The issue is the function is called two times.

      isLiked: function() {
    let self = this;
    console.log();
    Meteor.call('posts.isLiked', self._id, (error, result) => {
        console.log(result);
        return result;
    }); 
    }

The above function calls the posts.isLiked as below - 

      'posts.isLiked': (_id) => {
        check(_id, String);
    
        if (!Meteor.user()) {
          throw new Meteor.Error(401, 'You need to be signed in to continue');
        }
        if (!_id) {
          throw new Meteor.Error(422, '_id should not be blank');
        }
    
      return (Posts.find( { _id: _id , already_voted: { "$in" : [Meteor.userId()]} }).count() == 1);
    }

The console shows output 2 times. 
Any help would be appreciated.

**Comment by abernix** [comment]
Hello,

Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

In addition to checking out the [Todos Example App](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials), we highly recommend you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
