### ISSUE TITLE
[1.2+] Reflect not availble

### ISSUE THREAD

**Issue by AnthonyAstige** [meteor/meteor#7060]
Making `/imports/reflect.js` with code like:

`Reflect.deleteProperty(loc, 'geo.coordinates')`

Using Meteor 1.3.2.4 I get this console exception

> ReferenceError: Reflect is not defined

This isn't a severe issue, but it'd be nice to have more ES2015 features (looks like [Babel supports Reflect](https://babeljs.io/docs/learn-es2015/)).

I'm guessing this is an issue since Meteor 1.2 as that's when the `ecmascript` package was introduced.

**Related**
* [[1.2+] Full ES2015 module support is claimed, but strict mode not on](https://github.com/meteor/meteor/issues/7050).

**Comment by abernix** [comment]
Meteor is currently using Node 0.10.x with Babel in order to provide ES2015 support and `Reflect` (as the page you linked to states), [requires the use of a polyfill](https://babeljs.io/docs/usage/polyfill/) to make this work – which can be added at the discretion of the developer since it adds (potentially unnecessary) file overhead and global namespace pollution.

You should be able to use it right now by doing `meteor npm install --save babel-polyfill` and then `import "babel-polyfill";` in your module.  You can also consider adding [exactly what you need](https://github.com/zloirock/core-js#commonjs).

Node 4 support is coming with #6921 which will reduce the polyfills that are necessary, but Node 6 (#6923) is the first Node version that will support Reflect natively.

Closing this because Node upgrades (the real solution here) are tracked in other issues. 😄
