### ISSUE TITLE
addJavaScript does not work

### ISSUE THREAD

**Issue by gooor** [meteor/meteor#7082]
I forked https://github.com/civilframe/meteor-angular-jade/blob/master/plugin.js
After upgrading from 1.3.1 to 1.3.2.4 compileStep.addJavaScript does nothing - nothing is added to app.js
After rolling back to 1.3.1 everything works fine.

**Comment by gooor** [comment]
It turns out I had to do `import 'this what comes in compileStep.inputPath';` for each file  to make this work. Is there an option for that, I didn't know that change from 1.3.1 to 1.3.2 will make me rebuild my app...

**Comment by abernix** [comment]
Closing this issue because the problem you're referring to is too vague to accurately provide help.  What you have provided is not enough to isolate the problem, or even to determine if the problem is in Meteor itself.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please ask for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.

Thanks! :)
