### ISSUE TITLE
CHANGELOG is confusing on v1.3.2, regarding change in Match.Optional

### ISSUE THREAD

**Issue by johanbrook** [meteor/meteor#7083]
In the [changelog for v1.3.2](https://github.com/meteor/meteor/blob/devel/History.md#v132), we can read:

> Match.Optional only passes if the value is null or the specified type, whereas previously it accepted undefined. Use Match.Maybe to allow undefined. #6735

Foremost, this seems like a huge breaking change, which scared us off a lot – we've got `Match.Optional()` sprinkled all over, catch undefined arguments to functions. But after some investigations, it seems like this is not the case?

This is some tests in `meteor shell` with an app on 1.3.2.4:

```
> Match.test(null, Match.Optional(String))
false
> Match.test(undefined, Match.Optional(String))
true # <== This contradicts the changelog
> Match.test(null, Match.Maybe(String))
true
> Match.test(undefined, Match.Maybe(String))
true
```

So if I'm not heavily mistaken, it's still possible for `Match.Optional()` to match and pass on `undefined` in 1.3.2.x. This might have been "fixed" in a later version than 1.3.2.

Here's the docs on `Match.Optional`, being correct:

> Behaves like Match.Maybe except it doesn’t accept null. If used in an object, the behavior is identical to Match.Maybe.

https://docs.meteor.com/api/check.html#matchpatterns

I suggest either clarifying – negating – the changelog paragraph above, or adding a new note to a point release after 1.3.2.

**Comment by abernix** [comment]
Yeah, sorry about that!  Please help! (see below). :smile:  The entry is dead opposite of what it should be.  This is my mistake for not submitting a changelog entry with my fix in #6736 and leaving (a confusing situation) to be interpreted by the person who wrote the History.

**The backstory:** Before 1.3, `Match.Optional(type)` wouldn't match `null`.  It had to be either `undefined` or `type`.  It was decided that this was weird behaviour because `null` is pretty much the same as `undefined` in the "optional" sense.

**The solution:** `Match.Maybe` was introduced in 1.3 as a more intuitive "truly optional" matcher, and a new name was used to avoid potentially breaking changes (slim chance, but it was on the safe side). `Match.Maybe(type)` would allow `null`, `undefined` or `type`.

**The failure:** Unfortunately, the `Match.Maybe` replacement DID actually change the behavior of `Match.Optional` as well 😞 – they became exactly the same function (see #6735) and you could slip a `null` through a `Match.Optional`. 1.3.2 fixed them both to work correctly again.

I'll propose this:

#### Add to 1.3
##### Check
* Introduced new matcher `Match.Maybe(type)` which will also match (permit) `null` in addition to `undefined`.  This is a suggested replacement (where appropriate) for `Match.Optional` which did not permit `null`.  This prevents the need to use `Match.OneOf(null, undefined, type)`. #6220 

#### Change 1.3.2
* Fixed unintended change to `Match.Optional` which caused it to behave the same as the new `Match.Maybe` and incorrectly matching `null` where it previously would not have allowed it. #6735 

Do you think this fixes it, or do you think there still needs to be another mention of something after 1.3.2?  Nothing changed after 1.3.2 so all we could add is: 
* Fixed incorrect History entry about `Match.Optional` in 1.3.2.

**Comment by johanbrook** [comment]
Gotcha!

I think the proposed fixes to the changelog look good.

**Comment by tmeasday** [comment]
I don't think we need a changelog entry for altering the changelog (what do you think @zol?)

**Comment by abernix** [comment]
Yeah, I think it's a bit extreme too but I thought since it was factually opposite it was worth suggesting.

**Comment by zol** [comment]
I don't think we need a changelog entry in addition to the fix either.
