### ISSUE TITLE
Auth0 inappbrowser not dismissing after successful login in iOS with meteor 1.3.2.4

### ISSUE THREAD

**Issue by mitiaptest** [meteor/meteor#7102]
After updating meteor 1.2 to meteor 1.3.2 I have got an issue. Auth0 inappbrowser not dismissing after successful login in iOS devices but its works fine on other browsers and android devices. After analysis I found that this issue with OAuth package event listeners not get called for some times.
Any help.

Thanks

**Comment by abernix** [comment]
Closing this issue because the problem you're referring to is too vague to accurately provide help.  What you have provided is not enough to isolate the problem, or even to determine if the problem is in Meteor itself.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please ask for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.

Thanks! :)

**Comment by mitiaptest** [comment]
@abernix Will provide Git repo link shortly.

**Comment by mitiaptest** [comment]
git repo link to reproduce issue : https://github.com/mitiaptest/Auth0-meteor1.3

**Comment by abernix** [comment]
Ok, reopening for now so this doesn't get lost.  I or someone else will try the reproduction soon. :smile:

**Comment by abernix** [comment]
I was able to run this using the iOS simulator, log in successfully and get returned to the app with my `userId` set.  What am I missing?

**Comment by mitiaptest** [comment]
@abernix Yes, in iOS simulator its working fine but not on actual device. Out of 10 three to four times inappbrowser not get closed. This is happening only for iOS devices.

**Comment by abernix** [comment]
II believe I'll have problems running this repo then unless I change my IP address to match one of your "Acceptable Callback URLs" – and none of the ~200 you have whitelisted right now match my environment.

Can you add, say, `http://meteor.local:3000/_oauth/auth0` as an option?  (This is generic enough that it should work easily for anyone on a Mac).

Right now, I can't get past that.  Am I missing something?

**Comment by mitiaptest** [comment]
@abernix We have added http://meteor.local:3000/_oauth/auth0 in our aut0 app callback URL and this is also not resolving problem.
Have you updated settings.json file to enter your auth0 credentials? 

For callback url you can set into your Auth0 account.

Thanks,

**Comment by abernix** [comment]
It's just so I can test easily – it won't fix your problem.   I will try to take a look this afternoon.

**Comment by mitiaptest** [comment]
@abernix Any luck ?

**Comment by abernix** [comment]
Will look right now – sorry, ended up being super busy yesterday.

**Comment by abernix** [comment]
I can confirm this is broken – and it actually happens to me every time, not just sporadically.  But this is the same as #6882 and is an [upstream (Non-Meteor) bug with Cordova](https://issues.apache.org/jira/plugins/servlet/mobile#issue/CB-11136), so I'm going to mark this as a duplicate and close.  Thank you for the repo though, it made it very easy to reproduce.  I am going to post it in #6882 and leave my notes there though so please follow that issue.

The current work-around is using a different version of `cordova-plugin-inappbrowser` using the following command.  I **highly recommend** you track the other issue and remove this plugin once the problem is resolved as using this version long-term could cause problems.
 ```
meteor add cordova:cordova-plugin-inappbrowser@https://github.com/ephemer/cordova-plugin-inappbrowser.git#04091fde737519c149e7ad6316971cb6b490c5b3
```

If you haven't already, please make sure to secure those credentials in your `settings.json` if you didn't mean to post them on Git.
