### ISSUE TITLE
Prevent removing last e-mail from accounts with no username

### ISSUE THREAD

**Issue by peonmodel** [meteor/meteor#7116]
Accounts.createUser just requires an email to create a user

Accounts.removeEmail does not check if the user has an username and whether the email address to be removed is the last email address

A meteor user account can be created that just have {_id, createdAt} that cannot be logged in to

```
Accounts.removeEmail = function (userId, email) {
  check(userId, NonEmptyString);
  check(email, NonEmptyString);

  var user = Meteor.users.findOne(userId);
  if (!user)
    throw new Meteor.Error(403, "User not found");

// addition should be
if (!user.username && user.emails.length === 1 && user.emails.find((obj)=>obj.address=email)){
throw new Meteor.Error('unable to delete last email of username-less user')
}
// end

  Meteor.users.update({_id: user._id},
    {$pull: {emails: {address: email}}});
}
```

**Comment by laosb** [comment]
I think Oauth accounts doesn't have any email too?

**Comment by abernix** [comment]
Thanks for pointing this out, @peonmodel.  Though I'm not familiar at all with the oAuth/password differences, I think for oAuth this can certainly be allowed, but otherwise yes, not having an email/username is a problem.  Not sure if this can be classified as a bug or a feature as it's been that way since it was designed years ago, so I'll go with feature for now.   :smile:

**Comment by abernix** [comment]
Let's discuss if this actually should be made as a feature or not though.  Since `Accounts.removeEmail` is a server-only method, it's reasonable to ask the developer to make their own rules for how they want this to work and check that criteria themselves before calling `.removeEmail`.   Maybe they have other ways of logging the user in where this is perfectly acceptable?  Maybe the docs just need some explanation here?

**Comment by peonmodel** [comment]
for oAuth, surely it still requires some form of identifier other than username or email?
perhaps its not possible for removeEmail to know what is the identifier beforehand, so i would settle for a documentation about the potential pitfall

**Comment by abernix** [comment]
Well, Meteor has a `Meteor.loginWithToken` method that allows (generally speaking) server-to-server communication and you can use `Meteor.loginWithPassword` with just an `id` instead of `username` or `email`:

```js
Meteor.loginWithPassword({id: "W0x9wx88a893bA"}, "password123")
```

**Comment by laosb** [comment]
I think we should change the behavior to not removing the last email, but if the developer want to do that, let them do with a extra option.

**Comment by abernix** [comment]
@laosb Why not the other way around? Since it's a breaking change otherwise.

Also, why not just document it as a rule that you need to check if you don't want to remove the last e-mail address?  The developer is likely  would already be checking things like that already since they have to check if it's a "primary" e-mail, recovery e-mail, etc. before actually deleting it.

**Comment by laosb** [comment]
That's good, but for existing apps that may be a problem. What if the user deleted his last email on a email-only-login app? They can even have no way to contact the app developer without logging in.

But this case is very uncommon and not very serious.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Prevent%20removing%20last%20e-mail%20from%20accounts%20with%20no%20username&body=Migrated%20from:%20meteor/meteor%237116) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
