### ISSUE TITLE
Run tests for app and local package simultaneously 

### ISSUE THREAD

**Issue by Ben305** [meteor/meteor#7127]
I would like to discuss the test modes that were introduced in 1.3. Before that release, the main part of my angular app was also implemented in a local package, because the packages.js file could be used to control the file load order. With the release of 1.3, I moved the implementations from the main-app package back to the app itself. Other code, which is shared with some other applications, is still implemented in local packages. 

Before 1.3, I could run the tests with a single command: `meteor test-packages main-app-package local-domain-package other-local-package`

With 1.3, I can test the app with `meteor test`, and the packages again with `meteor test-packages local-domain-package other-local-package`

It would be great to test the app and the local packages within a single test run. 

@tmeasday What do you think?

**Comment by abernix** [comment]
Before 1.3 there were still multiple ways of running various tests.  Velocity provided a `--test` flag which did not run the package tests – you still had to run `test-packages` if you were specifically testing packages.  Meteor 1.3 is basically the same in this regard, except the command is now simply `test` instead of a `--test` option.

But personally, while I used to have the same annoyance as you've described, I've found that Meteor 1.3 removes the need for me to have my own "local packages".  For me, this mean I no longer need to run `test-packages` because I don't have anything in my `packages/` directories to test (as I've moved my own packages into `imports` where I can control the load order, etc.).

Of course there are custom compilers, unpublished custom package modifications, etc. which still have package use-cases right now, but I do feel that with each step closer to NPM-land, `test-packages` becomes less necessary.

I'm also not sure how compatible these two tools are.

**Comment by Ben305** [comment]
I have multiple apps which share the domain classes and other services. That's the reason why they are implemented in packages. I could add all files with symlinks, but that would cause headaches for others running Windows. And adding them as git submodules ruins the workflow.

**Comment by hwillson** [comment]
Hi guys - just reviewing this issue as part of the old issue cleanup process. While I can appreciate how having the app and local package tests running together could save some time, I think having to run these tests separately is a very minor inconvenience. Judging by the lack of interest (+1's) in this issue, I think it's safe to assume the impact of this issue is quite low. As such, and due to the age of this issue, I'll close it off. Thanks very much for posting this originally!
