### ISSUE TITLE
`meteor debug` should use its own port

### ISSUE THREAD

**Issue by FEA5T** [meteor/meteor#7129]
`meteor debug` refuses to start when port :8080 is in use.  
### Solutions:

**1.** Meteor should detect this and choose another port so that providing a manual port is not required. _ie:_ `meteor run --debug-port=8081`

Keep in mind this is for debugging **not** production, so it would make sense to choose another port.

**2.** Choose an uncommon port (not 8080) for all meteor applications.
### Common services that use :8080
- Microsoft TFS (Team foundation server)
- Apache servers (Tomcat)
- Eclipse
- Unifi
  _\- And many, many more..._

**Comment by abernix** [comment]
Thanks for submitting this idea for a [feature request](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).

Just to clarify: `node-inspector` is also a common service that uses 8080 by default and running `meteor debug` simply calls `node-inspector`, so this isn't a port that Meteor is picking – it's just the default that `node-inspector` uses by default

The debug refuses to start, but it also displays:
```
There is another process already listening at this address.
Run `node-inspector --web-port={port}` to use a different port.
```
So it's not unclear that it's a port problem, but the error message provided is certainly the wrong way to fix it.

As far as ideas for solutions:
* Along the lines of Option 1 (above), perhaps using a similar concept to how Meteor uses `PORT+1` for the Mongo server, it could use `PORT+n` for debugging by default (not precisely sure what `n` should be as I know `+1` is used in addition to `+2` and `+3` in some test-only cases).
* Option 2 above doesn't really solve the problem because it will just happen again if you try debugging two Meteor projects.

Of course, there will always be problems with ports if you're running conflicting services.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60meteor%20debug%60%20should%20use%20its%20own%20port&body=Migrated%20from:%20meteor/meteor%237129) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
