### ISSUE TITLE
Meteor 1.3 test case failed with angular 1 and jasmin

### ISSUE THREAD

**Issue by mitiaptest** [meteor/meteor#7137]
Hello guys

We have converted our angular + ionic meteor 1.2 application with meteor 1.3.2.4 . in previous version of meteor we was using meteor Jasmine to create test case using following links http://farla.io/2015/05/11/unittesting-angular-meteor.html
After update from Meteor 1.2 into 1.3.2.4 we have successfully migrate Jasmine in mocha 
using 
https://github.com/Sanjo/meteor-jasmine/wiki/Migrate-to-Mocha
now we want to use our existing test cases with 1.3.2.4  but we was not able to execute our test case with latest migrated Jasmine

Git Repo Link : https://github.com/mitiaptest/meteor-1.3-testcase

Please any one can help me out from this

**Comment by abernix** [comment]
Hello,

Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

In addition to checking out the [Todos Example App](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials), we highly recommend you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
