### ISSUE TITLE
[METEOR@1.3.2.4 Accounts] logout only works online 

### ISSUE THREAD

**Issue by Kestanous** [meteor/meteor#7142]
What: Logout only happens when a user is online. 
Why a Bug: For offline apps and Cordova apps this can break UI and work flow. My use case uses logout to clear local data. 

Test build:
`meteor create test` (assumes 1.3.2.4)
add pacakages `accounts-ui` `accounts-password`
add `{{> loginButtons}}` and sign up.

In the console:
1. `Meteor.disconnect()`
2. `Meteor.logout()`
3. `Meteor.userId()` (outputs a user id)
4. `Meteor.reconnect()`
5. `Meteor.userId()` (outputs a undefined)

If you skip 5 and close the session, accessing it again later leaves you logged in.

**Comment by hwillson** [comment]
Instead of using `Meteor.logout` for this purpose, you can use [`Accounts.makeClientLoggedOut`](https://github.com/meteor/meteor/blob/b24f7167e16dd21344c1a875523d39125df80fb2/packages/accounts-base/accounts_client.js#L336-L347). This will force a logout without having to wait for a connection. So re-capping with your example:

1. `Meteor.disconnect()`
2. `Accounts.makeClientLoggedOut()`
3. `Meteor.userId()` (outputs `null`)
4. `Meteor.reconnect()`
5. `Meteor.userId()` (outputs `null`)

While this feature is available as part of the public Accounts API, it isn't documented. I'm not sure if this was intentional, or if it was just assumed that the need for this type of functionality would be minimal, so it was left out of the docs. Since `Accounts.makeClientLoggedOut` provides a way to logout while offline however, and since there hasn't been much activity on this issue in a while, I'll close this issue for now. If anyone feels strongly about having this documented, please open an issue within the [docs](https://github.com/meteor/docs) repo. Thanks for posting this originally!

**Comment by Kestanous** [comment]
👍 that will work, thanks.
