### ISSUE TITLE
`meteor build` should accept a `platforms` option

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#7144]
Hi, `meteor build` command line is counter-intuitive re: building mobile apps.  I'm guessing you're burning some support energy on this.

1.3 introduced the "--server-only" flag, which is the inverse of what I need for DevOps  

For DevOps, I'm either deploying a server, or wrangling a phone app build to upload to one of the stores.  A build tool is to create outputs, those are the different outputs I need, and they should be expressed on the command line.

As a developer, the experience below would be helpful to me, and maybe helpful to your support experience:

`meteor build`   -  always server+browser, with support for hot code pushes to mobile platforms.
`meteor build --platforms=ios`    -  Just build the mobile app

Maybe the second command needs to build the server,browser too.  But I want so specify on the command line "Build the android app."  or "Build the ios app".

Making "--server-only" mean "--platforms=browser,server" would be backwards compatible.  Do we really need to check platforms into the repo if they are specified on the command line?

**Comment by abernix** [comment]
Please do not include bugs and features in the same issue.  Do you mind editing this to remove the bug (and open separately, please!) then rework the rest into a more organized feature request for a single specific feature?  (It sounds like you want `meteor build` to support passing build targets irregardless of the platforms that are installed).

Currently, `meteor build` creates build directories for all enabled platforms and you pick what you want from the resulting directories – you cannot pick just `ios` or `android` if you have both platforms in your project.  `--server-only` can be passed to avoid `ios` and `android` (both!), but it's probably not the best named flag since it also builds `web.cordova`, which is for the browser.  It is not possible to build `browser` by itself with `meteor build`, nor is it possible to build `server` without browser.

**Comment by MichaelJCole** [comment]
https://github.com/meteor/meteor/issues/7148

**Comment by MichaelJCole** [comment]
"Do you mind editing this to remove the bug (and open separately, please!) then rework the rest into a more organized feature request for a single specific feature?"

If you're asking how I'd build it, I don't know.  I know gulp and grunt, but not Meteor's.

How would I design it?  I want to specify what to build:
 - There's a --platforms flag which specifies which artifacts to build.
 - The default is backwards compatible with `meteor build`
 - `meteor build --server-only` sets --platforms to build just server artifacts.
 - `meteor build --platforms=ios` builds the ios code.  Maybe other platforms are needed for this to work.

I'm making and maintaining build scripts like the one below and it seems `meteor add-platform` / `meteor remove-platform` should be specified on the command line, instead of writing to a file and checking it into the repo.  What's the point of that if I need to edit the file to build things?

```
meteor remove-platform ios || echo "Platform ios already removed"
rm -rf .meteor/local
# jigger some files for sound notifications
./patch.sh
echo "STARTING BUILD"
meteor build ./android \
  --mobile-settings ../settings.json \
  --server https://phone.example.com:443 \
  --verbose
meteor add-platform ios || echo "Platform ios already added"
popd

**Comment by abernix** [comment]
@MichaelJCole This is great for a FR.  The original request just almost sounded like multiple unrelated problems (and bugs) or things that would technically be different features when implemented.  This sounds reasonable.  

My only comment is that I think `meteor add-platform` / `remove-platform` need to stay there because they do more than just deal with the `build`.  The dependencies which are necessary to develop with are downloaded/installed when you add the platform.  I think it seems reasonable to:

* `meteor add-platform <platform>` the platforms you want to work with
* `meteor build` will build for all platforms by default (as you suggested)
* `meteor build --platforms ios,android` would build both `ios` and `android` (just showing that you can pass multiple, comma-separated values).
* `meteor build --platforms ios` would just build iOS.

Regardless, I believe the `server` and `client` will still have to be built, as of now, but this would at least allow you to not build `android` if you didn't want to (for the moment), but still have it be part of your overall project.

Now the only question is, why can't you just cherry-pick the build folder out of the build directory that you actually want? (e.g. `ios` or `android`).  Is it for speed reasons? (Of course, I realize that it's more intuitive to specify and only build what you want, but I'm inquiring for prioritization reasons, mainly).

**Comment by MichaelJCole** [comment]
Hi, ok, that makes sense for the platforms, as long as they don't need to be added/removed to build.

Why not cherry pick?  I guess if it was documented.  I develop on linux, with mac as a backup for the ios app build.  Each computer only has the one toolchain installed.  I don't think the builds work if the platform is added without the toolchains installed.  My mac is slow, so building both on it would be a nightmare if it needed any interaction (bugs, errors, scripting, etc).

**Comment by dmitry-sher** [comment]
This is an exciting feature! I often develop multiplatform apps, and it would be a breeze to build ios && android build separately. Is it already on roadmap somehow?

**Comment by abernix** [comment]
@dmitry-sher It's not currently on the roadmap for the MDG core team, but it could become a `pull-requests-encouraged` situation with some additional input and refinement.  Please +1 the original issue message if you're interested and provide any thoughts were appropriate.  Also, as you're a developer who needs this (I am not) any input/validation on what has been proposed so far would be helpful!

**Comment by observaInc** [comment]
+1.  I do all of my development on a linux machine, and only do my iOS builds on a mac.  Would be nice if I don't have to muck around with all of the android SDK stuff on both boxes.

**Comment by gwhahaha** [comment]
+1. And i hope meteor build support build android platform without generate apk file, 
`meteor build --platforms android --no-apk`

**Comment by MeteorStartup** [comment]
+1. 
Sometimes we need to set up some files or configuration on developing mobile project in .meteor/local/platfor..., and meteor remove-platform ios or android removes that project.
So if we remove-platform every single time to build only one mobile platform, that wouldn't be good choice..

Nice feature.

**Comment by fabyeah** [comment]
+1.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60meteor%20build%60%20should%20accept%20a%20%60platforms%60%20option&body=Migrated%20from:%20meteor/meteor%237144) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
