### ISSUE TITLE
Meteor build android: "No Java files found which extend CordovaActivity."

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#7145]
Got this error while building for Android on Linux.

```
=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin cordova-plugin-media@2.3.0 to Cordova project:              
   No Java files found which extend CordovaActivity.                               
   at updateProjectAccordingTo
   (/home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:151:15)
   at /home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:41:16
   at _fulfilled
   (/home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:834:54)
   at self.promiseDispatch.done
   (/home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:863:30)
   at Promise.promise.promiseDispatch
   (/home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:796:13)
   at /home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:556:49
   at runSingle
   (/home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:137:13)
   at flush
   (/home/michael/scm/bigSmall/meteor/phone/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:125:13)
   at process._tickCallback (node.js:458:13)
```

Not sure the exact root cause, but my workaround was:

```
meteor remove-platform ios
rm -rf .meteor/local
```

**Comment by abernix** [comment]
Happy to track this if there is a way to reproduce it, however otherwise this doesn't provide much to work with.  I understand that issues like these are still problematic and getting them fixed is important, but leaving this open as-is will not likely lead to any help.  [Meteor guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor).

Will definitely reopen with some guidelines for reproduction.

I'm guessing removing `.meteor/local/cordova-build` alone would have likely fixed it, but can't say for sure.

**Comment by MichaelJCole** [comment]
Google didn't have anything for "No Java files found which extend CordovaActivity Meteor" so I made this not-so-good bug.  Wish it had more to offer!

**Comment by abernix** [comment]
@MichaelJCole Another user opened #7375 with the same problem so I have left that issue open since this isn't isolated anymore.  If you have any new information to provide on how to reproduce it, please drop it in there. :smile:

**Comment by MichaelJCole** [comment]
@abernix ok, thanks.  The only value here was the workaround in the original description.  Cheers!

**Comment by abernix** [comment]
@martijnwalraven Any ideas?

**Comment by wojtkowiak** [comment]
I have the same issue. Clean meteor project created with `meteor create` with `android` platform, building with `--mobile-server`. System is Windows 10 64bit. I am trying to narrow down what is so unusual on my laptop that is making that happen. Did not have this issue previously.

**Comment by wojtkowiak** [comment]
I might be somehow related to local node_modules being used by Cordova -> https://github.com/meteor/todos/issues/107#issuecomment-212905737. At first I thought it is also because of `shelljs` because I've already had that issue. Bu apparently removing `node_modules` and installing them again solved the issue. 
@MichaelJCole @oliverthomasklein did you guys have packages like `glob`, `shelljs`, `q` in your node_modules? Could you post your package.json?

**Comment by MichaelJCole** [comment]
Hey @wojtkowiak I don't have any modules like that.  But I had some push notification stuff that might have caused it.  Details: http://pastebin.com/HvQdgaKt
