### ISSUE TITLE
New Match pattern for Tuples

### ISSUE THREAD

**Issue by diegonc** [meteor/meteor#7165]
It would be great if a new match pattern could be implemented such that it has the following semantics, describing a data type like tuples in other languages.

```
var good = ["string", {a: 4, r:3}, 5.7];
check(good, Match.Tuple(String, Object, Number));
// OK, good has the proper shape

var tooLong = ["s", {}, 4.3, "f"];
check(tooLong, Match.Tuple(String, Object, Number));
// Bad, tooLong has an extra element

var tooShort = ["s", {}];
check(tooLong, Match.Tuple(String, Object, Number));
// Bad, tooShort is missing the third element

var badType = [{}, "s", 4.3];
check(badType, Match.Tuple(String, Object, Number));
// Bad, badType[0] should be a String
```

I hope you get the idea :)

Currently this can be implemented through a `Match.Where` with the following function

```
(function () {
    var types = Array.prototype.slice.call(arguments);
    return function (v) {
        check(v, Array);
        _.each(types, function (value, index) {
            check(v[index], value);
        });
        return v.length === types.length;
   }
}(String, Object, Number))
```

where I tried to make it generic enough to be a potential implementation. Of course, the composability with other patterns and the error messages generated by a match failure could be greatly improved.

The rationale for a dedicated matcher is that you gain in expressive power; for instance one could say:

```
check(o, { a: String,
           b: Match.Tuple(Number, String),
           c: { o: [String],
                p: [ Match.Tuple(Object, Object) ] } })
```

instead of using `Match.Where` with functions one has to decode to understand its expectations and which clutter the desired shape of the object being checked.

**Comment by laosb** [comment]
Good feature to ocnsider.

**Comment by huttonr** [comment]
Would this not be sufficient?

```javascript
Match.Tuple = function (...pattern) {
  return Match.Where((arr) => {
    check(arr, Array);
    pattern.forEach((value, index) => check(arr[index], value))
    return arr.length === pattern.length;
  })
};
```

**Comment by diegonc** [comment]
Well yes, that's the naive implementation I suggested, although expressed in a much more concise way.

The issues with error messages I mentioned are

- A mismatch on the outer type (Tuple) still says Array
```
    check({a: {b: {c: {d: ["s", 4.5]}}}},
      {a: {b: {c: Match.Tuple(String, Number)}}});

I20160604-17:25:41.028(-3)? { [Error: Match error: Match error: Expected Array in field a.b.c]
```

- With a short tuple in the input, the error message complains about undefined in the field corresponding to the Tuple and not its missing component(s)
```
    check({a: {b: {c: ["s"]}}},
      {a: {b: {c: Match.Tuple(String, Number)}}});

I20160604-17:25:41.030(-3)? { [Error: Match error: Match error: Expected number, got undefined in field a.b.c]
```
- When the tuple in the input has more components than expected, the error message doesn't say that.

```
    check({a: {b: {c: ["s", 4.5, 3]}}},
      {a: {b: {c: Match.Tuple(String, Number)}}});

I20160604-17:25:41.032(-3)? { [Error: Match error: Failed Match.Where validation in field a.b.c]
```
- When a component of the tuple has the wrong type, the error message is attached to the field holding the entire tuple.
```
    check({a: {b: {c: [3, 4.5]}}},
      {a: {b: {c: Match.Tuple(String, Number)}}});

I20160604-18:14:46.200(-3)? { [Error: Match error: Match error: Expected string, got number in field a.b.c]
```

Having said that, I'm ok with the naive implementaton for my own project. But I thought I should point the issues in case an official implementation "wants to be more polished".

**Comment by huttonr** [comment]
Oh!  I misunderstood.  You are referring to the poor error messages given.  Yes, I agree these could be better for this implementation, but this is easily accomplished:

```javascript
Match.Tuple = function (...pattern) {
  return Match.Where((arr) => {
    if (!Match.test(arr, Array)) throw new Match.Error('Expected Tuple array');

    if (arr.length < pattern.length) throw new Match.Error('Tuple is missing elements');
    if (arr.length > pattern.length) throw new Match.Error('Tuple contains too many elements');

    pattern.forEach((value, index) => {
      try {
        check(arr[index], value);
      } catch (e) {
        const suffixes = ['th', 'st', 'nd', 'rd'],
              oneBasedIndex = index + 1,
              rem = oneBasedIndex % 100,
              suffix = suffixes[(rem - 20) % 10] || suffixes[rem] || suffixes[0],
              message = e.message.replace('Match error: ', '');

        throw new Match.Error(`${ message } in ${ oneBasedIndex }${ suffix } Tuple element`);
      }
    });

    return true;
  });
};
```

**The real thing I would like to point out is because [testSubtree](https://github.com/meteor/meteor/blob/devel/packages/check/match.js#L151) is not accessible, it is difficult to get a good error message going without using this `try/catch` solution.  `Match.test` doesn't output specifics as to how it erred and if there is room for improvement in the `check` package this would be it.**

**Comment by hwillson** [comment]
Thanks for suggesting this originally. As mentioned in https://github.com/meteor/meteor/issues/7165#issuecomment-223784445, since this can be handled outside of the Meteor core fairly easily (and the up-vote count on this issue has been quite low over the past year), I'll close this issue for now. I'm happy to re-open this issue if you think this functionality really is better suited in core. Keep in mind though this might be a tough sell since there are 3rd party packages that offer enhanced `check` functionality (like [3stack:match-library](https://atmospherejs.com/3stack/match-library)), that work quite well. Adding tuple support might be better suited/supported/maintained as a 3rd party package.

Regarding the statement in https://github.com/meteor/meteor/issues/7165#issuecomment-223784445 about improving the `check` packages error reporting, please consider opening a new issue about this outlining the specific issues/changes that should be made.

Thanks!
