### ISSUE TITLE
Npm library problem

### ISSUE THREAD

**Issue by Testato** [meteor/meteor#7166]
I'm trying to use the iframe-resizer npm library:
```
meteor npm install --save meteor-node-stubs
meteor npm install --save iframe-resizer
```

but when i import it whit:
`import baudo from 'iframe-resizer';
`

is there this error:
```
W20160603-18:37:19.705(2)? (STDERR)
W20160603-18:37:19.705(2)? (STDERR) C:\Users\win10\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160603-18:37:19.705(2)? (STDERR)                                             throw(ex);
W20160603-18:37:19.705(2)? (STDERR)                                                   ^
W20160603-18:37:19.705(2)? (STDERR) ReferenceError: window is not defined
W20160603-18:37:19.705(2)? (STDERR)     at Object.<anonymous> (C:\Users\win10\Desktop\1\meteor-npm\node_modules\iframe-resizer\js\iframeResizer.js:996:4)
W20160603-18:37:19.705(2)? (STDERR)     at Module._compile (module.js:456:26)
W20160603-18:37:19.705(2)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160603-18:37:19.705(2)? (STDERR)     at Module.load (module.js:356:32)
W20160603-18:37:19.705(2)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160603-18:37:19.705(2)? (STDERR)     at Module.require (module.js:364:17)
W20160603-18:37:19.705(2)? (STDERR)     at require (module.js:380:17)
W20160603-18:37:19.705(2)? (STDERR)     at Object.<anonymous> (C:\Users\win10\Desktop\1\meteor-npm\node_modules\iframe-resizer\js\index.js:1:25)
W20160603-18:37:19.705(2)? (STDERR)     at Module._compile (module.js:456:26)
W20160603-18:37:19.705(2)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160603-18:37:19.705(2)? (STDERR)     at Module.load (module.js:356:32)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by clayne11** [comment]
Are you importing it in server code? If the library depends on the `window` without checks it will fail if you try to import it in server code. Not all libraries are written with universal support in mind.

**Comment by laosb** [comment]
You may imported it to server/both environment, which doesn't have `window`.

**Comment by Testato** [comment]
I imported it only in client code

Why the issue is closed ?

**Comment by laosb** [comment]
Would you like come up with an reproduce?

>A reproduction recipe works like this:
* Create a new Meteor app that displays the bug with as little code as possible. Try to delete any code that is unrelated to the precise bug you're reporting, including extraneous Atmosphere packages. Ideally, try to use as few source files as possible so that it's easy to see the whole reproduction on one screen, rather than making a large number of small files, even if that's not how you'd choose to structure an app.
* Create a new GitHub repository with a name like meteor-reactivity-bug (or if you're adding a new reproduction recipe to an existing issue, meteor-issue-321) and push your code to it. (Make sure to include the .meteor/packages and .meteor/release files!)
* Reproduce the bug from scratch, starting with a git clone command. Copy and paste the entire command-line input and output, starting with the git clone command, into the issue description of a new GitHub issue. Also describe any web browser interaction you need to do.
* If you reproduced the issue using a checkout of Meteor instead of using a released version that was pinned with a .meteor/release file, specify what commit in the Meteor repository was checked out.
* Mention what operating system you're using and what browser (if any).

**Comment by laosb** [comment]
I did try to reproduce your issue, but failed:
```
$ meteor create test-7166
Created a new Meteor app in 'test-7166'.

To run your new app:
  cd test-7166
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

$ cd test-7166
$ meteor npm install --save meteor-node-stubs
meteor-node-stubs@0.2.3 node_modules/meteor-node-stubs
├── https-browserify@0.0.1
├── tty-browserify@0.0.0
├── path-browserify@0.0.0
├── os-browserify@0.2.1
├── constants-browserify@1.0.0
├── string_decoder@0.10.31
├── process@0.11.2
├── punycode@1.4.1
├── assert@1.3.0
├── querystring-es3@0.2.1
├── timers-browserify@1.4.2
├── domain-browser@1.1.7
├── events@1.1.0
├── util@0.10.3 (inherits@2.0.1)
├── stream-browserify@2.0.1 (inherits@2.0.1)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── http-browserify@1.7.0 (inherits@2.0.1, Base64@0.2.1)
├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
├── readable-stream@2.0.6 (util-deprecate@1.0.2, inherits@2.0.1, process-nextick-args@1.0.6, isarray@1.0.0, core-util-is@1.0.2)
├── buffer@4.5.1 (isarray@1.0.0, ieee754@1.1.6, base64-js@1.1.2)
├── browserify-zlib@0.1.4 (pako@0.2.8)
└── crypto-browserify@3.11.0 (inherits@2.0.1, create-hmac@1.1.4, randombytes@2.0.3, pbkdf2@3.0.4, create-hash@1.1.2, diffie-hellman@5.0.2, browserify-cipher@1.0.0, create-ecdh@4.0.0, public-encrypt@4.0.0, browserify-sign@4.0.0)
$ meteor npm install --save iframe-resizer
iframe-resizer@3.5.3 node_modules/iframe-resizer
$ echo "import baudo from 'iframe-resizer'; " > ./client/test.js
$ meteor
[[[[[ ~/tests/test-7166 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/

```

**Comment by laosb** [comment]
If you come up with a repro, feel free to reopen this :) Closed because it just looks like a mistake you've made.

*But I could be wrong.*

**Comment by Testato** [comment]
you are right, code server side
I have to stop working at night

Sorry and thanks for your time
