### ISSUE TITLE
[1.3.3-rc.0] BlazeComponents fail to load.

### ISSUE THREAD

**Issue by JesperWe** [meteor/meteor#7184]
Since 1.3.3-rc.0 and also in 1.3.3-rc.1, BlazeComponents fail with:

```
Uncaught ReferenceError: meteorBabelHelpers is not defined
    extend @ peerlibrary_blaze-components.js?hash=d9f1367…:1139
    (anonymous function) @ peerlibrary_blaze-components.js?hash=d9f1367…:1681
    (anonymous function) @ peerlibrary_blaze-components.js?hash=d9f1367…:2367
    (anonymous function) @ peerlibrary_blaze-components.js?hash=d9f1367…:2426
    (anonymous function) @ client.coffee:103

```
This does not happen in 1.3.3-beta.2 and earlier.

**Comment by benjamn** [comment]
I believe this can be fixed by adding `"babel-runtime"` [here](https://github.com/peerlibrary/meteor-blaze-components/blob/5fcfbdaa1c71589de6b117b81c232b95a851e661/package.js#L96), so that `meteorBabelHelpers` (defined [here](https://github.com/meteor/meteor/blob/5ae53de46b3f2cc8331de54c7b254f40059a85b5/packages/babel-runtime/babel-runtime.js#L5) and `api.export`ed [here](https://github.com/meteor/meteor/blob/5ae53de46b3f2cc8331de54c7b254f40059a85b5/packages/babel-runtime/package.js#L21)) will be available.

In the midst of recent changes to `meteor-babel`, it's likely that we stopped accidentally defining `meteorBabelHelpers` globally, but I view that as a "good thing" from the perspective of code hygiene :)

**Comment by mitar** [comment]
I agree this is good code hygiene, but I am unsure why a package which does not use ES2016 at all would need dependency on `bable-runtime`? To me this seems some leaky dependency somewhere else?

**Comment by mitar** [comment]
Also, the link you provided is for tests. I think OP is talking about using package in their own app, not tests?

**Comment by benjamn** [comment]
My mistake: https://github.com/peerlibrary/meteor-blaze-components/blob/5fcfbdaa1c71589de6b117b81c232b95a851e661/package.js#L29

**Comment by benjamn** [comment]
I think I know what this is… CoffeeScript now calls `BabelCompiler.prototype.processOneFileForTarget` when a `.coffee` file contains raw JavaScript (enclosed by backticks). This behavior was introduced in `rc.0` (see the [1.3.3 commit log](https://github.com/meteor/meteor/commits/release-1.3.3) and #6691).

The `meteorBabelHelpers` namespace is used for only one thing: `meteorBabelHelpers.sanitizeForInLoop`, which is used to sanitize objects looped over by `for`-`in` loops so that those loops behave the same way in all browsers.

So I'm guessing you've got a `.coffee` file with a `for`-`in` loop enclosed by backticks.

Given this analysis, although you could still solve this by depending on `babel-runtime`, the `coffeescript` package should really `api.imply(["ecmascript-runtime", "babel-runtime"])`.

**Comment by mitar** [comment]
> So I'm guessing you've got a .coffee file with a for-in loop enclosed by backticks.

I do not think I use any such strange contraption. :-)

OK, so this is a bug in the `coffeescript` package. :-)

**Comment by ramirez530** [comment]
Fix big get the right metricks

**Comment by benjamn** [comment]
Please retest this issue after doing `meteor update --release 1.3.3-rc.4`: https://github.com/meteor/meteor/pull/7033

**Comment by JesperWe** [comment]
Yes indeed, fixed it is.
Good work!

**Comment by jgraham-plm** [comment]
There seems to be a similar issue with ```meteorBabelHelpers``` being undefined in the context in which ```Collection.mapReduce``` functions run. I'm encountering the same error due to for loops being present in my ```mapReduce``` code.

I'm not familiar enough with Meteor's packaging structure (or your intentions with ```Collection``` support like this) to know what the right solution is, but passing ```meteorBabelHelpers``` explicitly in the ```mapReduce``` scope fixes the issue, though that is perhaps not ideal. For example:

```coffeescript
import { meteorBabelHelpers } from 'meteor/babel-runtime'

options =
    scope:
        meteorBabelHelpers: meteorBabelHelpers
MyCollection.rawCollection().mapReduce(map, reduce, options)
```

In case it matters, I am also using CoffeeScript — as you can probably tell :)
