### ISSUE TITLE
Require not working with dynamic string

### ISSUE THREAD

**Issue by AndreasGalster** [meteor/meteor#7189]
Following scenarios to dynamically require a view/component when switching a route:

```
require(`/imports/ui/views${route.path}-view.js`);
// string is '/imports/ui/views/search-view.js'
// does not work

var route = `/imports/ui/views${route.path}-view.js`;
require(route);
// string is '/imports/ui/views/search-view.js'
// does not work
    
require(`/imports/ui/views` + `/search-view.js`);
// string is '/imports/ui/views/search-view.js'
// does not work

require(`/imports/ui/views/search-view.js`);
// string is '/imports/ui/views/search-view.js'
// does work
```

As you can see, all these cases produce the same string/path to require, however anything that's dynamic won't work. This means I have to do something like this (with every future route an additional case) to load my dependencies:

```
switch (route.path) {
  case '/search':
    require('/imports/ui/views/search-view.js');
    break;
  case '/messages':
    require('/imports/ui/views/messages-view.js');
    break;
  case '/profile':
    require('/imports/ui/views/profile-view.js');
    break;
  case '/':
    require('/imports/ui/views/landing-view.js');
    break;
  case '/signup':
    require('/imports/ui/views/landing-view.js');
}
```

Whereas this could be done with just one line dynamically (given I name my views and route paths properly:

```
require(`/imports/ui/views${route.path}-view.js`);
```

Note, route.path returns the first param like '/search', '/landing', etc.

Is this a bug?

**Comment by benjamn** [comment]
This is expected behavior. Client bundling depends on statically analyzable module identifier strings. That's true for Browserify, Webpack, Meteor, and any other bundling tool, and it's one of the reasons why the syntax of `import` statements only allows string-literal source module identifiers. The expressive power you gain from dynamic string interpolation isn't worth the cost, which is that the bundler can no longer compute your dependency graph.

That said, with Meteor's module system, any module identifier you `require` or `import` as a string literal may then be imported elsewhere in your project using a dynamic expression, even if the original import statement is never executed. In other words, putting `true || require("/imports/ui/views/landing-view.js")` anywhere in your client code will ensure the module is included in the client bundle, allowing you to `require(`./ui/views/${route.path}-view.js`)` from a file like `/imports/router.js`. This is not a property that other bundlers (e.g. Webpack) provide.

**Comment by laosb** [comment]
In [Guide](http://guide.meteor.com/structure.html#using-require):
>Note that dynamic calls to require() (where the name being required can change at runtime) cannot be analyzed correctly and may result in broken client bundles.

As Meteor parse the client code to see what to include in the client bundle, dynamic calls won't work. This is intended, but supporting dynamic calls would be a good feature, with incremental loading(#6967).

**Comment by laosb** [comment]
@benjamn Didn't realize you're looking into this too when I was typing :)

**Comment by AndreasGalster** [comment]
Thanks, very insightful! Tried your workaround and it's working nicely. Still have to define them but at least it's less lines of code :). Should we close this? It does not sound like this is a feature you want to enable by default for the reasons mentioned in your post.

**Comment by benjamn** [comment]
Sure, thanks for understanding.

**Comment by AndreasGalster** [comment]
I'm sorry I have to follow up here but I am not sure if I might have misunderstood something here. My understanding was that the relevant files get attached to the client bundle, meaning the files are available to be loaded. 

But I believe what is happening is that actually all of it is being loaded since it's in one big bundle, so meaning effectively it's the same as the import syntax, meaning yes, all the code gets attached to the bundle and loaded upon page load, is that correct?

**Comment by trusktr** [comment]
@benjamn What a feature like `require.context` from Webpack?

It would at least allow us to specify that we may load any modules in a given folder, for example (based on dynamically-calculated strings), without having to list every module.

**Comment by SohelIslamImran** [comment]
**I came up with a solution that worked in my case. it's very simple 😄**

First I tried this
`const getIconComponent = (type = "MaterialCommunityIcons") => {
  return require("@expo/vector-icons/" + type).default;
};`
But got errors for the dynamic string.

Then I got a solution.

This return a object of icon components
`//import { MaterialCommunityIcons, AntDesign, Entypo, EvilIcons, Feather, FontAwesome } from "@expo/vector-icons";`

So, this worked for me.
`const getIconComponent = (type = "MaterialCommunityIcons") => {
  return require("@expo/vector-icons")[type];
};`
