### ISSUE TITLE
Firefox: Header top menu styles not changing on scroll at meteor.com

### ISSUE THREAD

**Issue by wassimans** [meteor/meteor#7197]
**Default behavior:** 
The top header menu has a transparent style when the home page is loaded. 
`<div id="header-page-menu" class="header-home-page-top">`

When we scroll down, the header menu styles change to have a gray background and the drop down menu lists are now with a red background, all this by changing the `class="header-home-page-top"` to `class="header-top-menu"` on scroll down.
`<div id="header-page-menu" class="header-top-menu">`

**Problem:**
The default behavior is missing in Mozilla Firefox, because the CSS styles are `class="header-home-page-top"` even after the scroll down event. When we scroll down, the top menu is still in transparent mode.

**Note:**
The described behavior was noticed in Windows 10 Pro, Ubuntu 16.04 and OS X El-Capitan, all with the latest stable Mozilla Firefox (47.0)

**Comment by WassiMan** [comment]
Now to my comment: do any of you people use Firefox at MDG?! It seems everyone is swearing by Chrome, and that's bad for a company doing mainly JavaScript development at large scale.

**Comment by laosb** [comment]
@meteor

**Comment by hwillson** [comment]
This is happening because in meteor.com's main Meteor JS file ([here](https://d14xs1qewsqjcd.cloudfront.net/6c83580741db22a051c531cc09f290f75fc92ef6.js?meteor_js_resource=true) as of right now, but this location might change since it's CDN hosted), the `window.onscroll` function (in the same IIFE as the `meteor_particles` call, around line 776 as of this post) is configured to check the current scroll position using `document.body.scrollTop`. Unfortunately, FF doesn't support `document.body.scrollTop`. Using `document.documentElement.scrollTop` in FF will give the proper result. So ideally the `window.onscroll` function would be updated to something like:

```js
...
window.onscroll = function () {
  (document.documentElement.scrollTop || document.body.scrollTop) > 10 
  ...
},
...
```

(👋 @abernix 🙂)
