### ISSUE TITLE
Loading page when use RouteLink is too long

### ISSUE THREAD

**Issue by tna274** [meteor/meteor#7198]
I already use @angular2/router-deprecated for use meteor route. It's work, but when I click on link (used [RouteLink]), it's loading very slow (average about 5 seconds).
What wrong with it?
/// Code ///
RouteConfig in file app.ts (have provider, APP_BASE_HREF)
`@RouteConfig([
    { path: '/', as: 'Default', component: SlackMessages, useAsDefault: true },
    { path: '/:channelName', as: 'Messages', component: SlackMessages }
])`
RouteLink in file html 
`<a class="channel_name" [routerLink]="['/Messages', {channelName: channel.name}]">`
And i already use tag <router-outlet>

**Comment by abernix** [comment]
Closing this issue because the problem you're referring to is too vague to accurately provide help.  What you have provided is not enough to isolate the problem, or even to determine if the problem is in Meteor itself.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please ask for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.

Thanks! :)
