### ISSUE TITLE
Websockets times out on satellite connections (HughesNet, bent-pipe architecture, etc)

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#7207]
Receiving this error message on a HughesNet connection to most all of my apps running on Galaxy.

```js
WebSocket connection to 'ws://checklist-manifesto.meteorapp.com/sockjs/017/3yol05u1/websocket' failed: WebSocket is closed before the connection is established.
```

**What version of Meteor you're using, and the platform(s) you're running it on**
Issue seems to be affecting Meteor 1.1.3+ through 1.3.2

**What packages or other dependencies you're using**
Nothing particularly out of the ordinary.  The error is entirely related to network topology and async upstream delays.  Bent-pipe satellite architecture is fast on the download, and slow on the upload which occurs via DSL or cellular connections.  The default WebSocket timeouts aren't handling a slow upload speed.  May also be related to TCP packet routing along completely separate routes.

**The behavior you expect to see, and the actual behavior**
Expect that the app should load, similar to synchronous cellular network connections.   

**An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)**
Connect to Galaxy apps via a HughesNet internet connection.

**Other comments**
This may feasibly fall under Galaxy or Apollo.

**Possible Fixes**
Increasing the timeout window for WebSockets.

**Comment by laosb** [comment]
That's sounds like a edge case, but it should works and increasing timeout shouldn't break anything, I think.

**Comment by awatson1978** [comment]
Polling doesn't seem to be working either.  Just receiving a white page.  Which is confusing, and why I logged the ticket.  Here is a screenshot of the console window.  

![screen shot 2016-06-13 at 11 03 10 am](https://cloud.githubusercontent.com/assets/675910/16014560/3f02d816-3157-11e6-9759-2553e9bd5507.png)

As you can see, access to the satellite's network seems to require routing through the ``http://1.2.3.4``` root DNS server, which is where a request header with client response time is added and things begin breaking down.  I'm going to see if adding an Access-Control-Allow-Origin header will get polling to work, but I'm skeptical.

**Comment by mjmasn** [comment]
@awatson1978 I don't think the warning is a problem, it's just as you say a fact of the network topology not supporting websockets. The polling fallback should work ok. 

I think the white page is possibly the recent issue with Chrome 51 + IronRouter. See https://github.com/iron-meteor/iron-router/issues/1538 

Solution is upgrading iron:middleware-stack ... `meteor update iron:middleware-stack`

**Comment by abernix** [comment]
If what @mjmasn mentioned doesn't help, I'm curious what happens if you disable HughesNet Web Acceleration, as instructed [here](https://community.myhughesnet.com/hughesnet/topics/can_i_enable_disable_my_web_acceleration_myself?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=11204503#reply_11204503) and [half-way-down here](https://jacksontech.net/index.php/articles/hughesnet-gen4-general-faq/).  Those console messages should be fine as SockJS should be falling back to polling automatically after those messages.

You might be able to debug more by checking out the Network tab in Chrome.  The "WS" filter should show an active connection when WebSockets are working, and alternatively, under the "XHR" filter, you'll see periodic requests to `/sockjs/[random]/[more random]/xhr`.

**Comment by awatson1978** [comment]
Hmmm....  well, the bad news is that I tried turning off web acceleration, and that didn't resolve the issue.  

The good news, however, is that something changed and Galaxy, the meteor.com homepage, and my latest projects are now loading across the satellite connection.  One guess is that Meteor 1.3.3 had a fix, and most of my Galaxy apps are still running on 1.3.2.  Another possibility is that the apps that are working aren't using IronRouter, as @mjmasn suggested.

Going to try to upgrade one of the apps that's not working.  Now that I have one app working, I should be able to get the others.

**Comment by abernix** [comment]
If you're still seeing the errors about `1.2.3.4` then Hughes must still be doing something.  If you are, perhaps try ensuring you're not using some special browser or extension that might be forcing [their proxy](https://www.dslreports.com/forum/r28369116-Weird-Javascript-at-top-of-pages-when-web-acceleration-is-on).  Either way, I don't see why falling back to polling wouldn't be working.

Also, meteor.com is running 1.2.1, not 1.3.3, so I'm not sure there is a connection there!

Do report back on how the upgrade goes! :smile:

**Comment by mjmasn** [comment]
@awatson1978 I promise you the issue is IronRouter! See the first error in the screenshot `Handler with name 'i' already exists`. Blank page issues are typically because IR has errored (and I have yet to see one where this wasn't the case...).

It's a new (not sure if experimental or actually part of the spec yet) JS feature in Chrome 51+ and MS Edge that names anonymous functions in object literals. E.g.

```js
var myObject = {
    myFunction: function () {} // anonymous function
}

console.log(myObject.myFunction.name); // prints "" in older browsers, "myFunction" in Chrome 51 / IE Edge
```

I haven't looked at the code but my understanding is that the unpatched version of `iron:middleware-stack` was relying on function names being empty or unique, I guess to stop you creating two routes or actions called the same thing. It affected our apps because we had multiple `onBeforeAction` calls, but it can also affect all your routes if they aren't named. If you haven't named your routes I think judging by comments I've seen that you probably still need to do so even after updating the package.

**Comment by abernix** [comment]
Agree with @mjmasn that `meteor update iron:middleware-stack` is a good idea.  Multiple folks have reported problems with that in forums and iron router issues.

**Comment by awatson1978** [comment]
Yup.  Updating ``clinical:middleware-stack`` did the trick.  Thank you much @mjmasn, @abernix.
