### ISSUE TITLE
Add retrying to package downloader

### ISSUE THREAD

**Issue by zol** [meteor/meteor#7267]
Currently, the Meteor package installer doesn't retry+resume downloads. Therefore, the tool can hang permanently whilst downloading packages over a flakey connection. 

We should add the ability for the tool to retry and resume package downloads. This will partially address the CDN issues reported in #6960

Using an existing node library with download resumption would be the preferred implementation.

**Comment by Ben305** [comment]
Yes, please fix this! Many CI builds are stopped by timeout because of this problem.

**Comment by gossel-j** [comment]
I have very often trouble with `meteor build` due to network problem. It not fail but just looks like trying to download indefinitely even if no data is coming. I checked with some strace and looks like no read are done and the process loop into some kind of poll loop or futex loop. I would like to know if it's related to this issue.

**Comment by gossel-j** [comment]
Maybe you can detect when the connection is too slow that it mean it is broken (like no data during few seconds) and retry. I think you use request internally, maybe you can try with https://github.com/FGRibreau/node-request-retry ?

**Comment by Ben305** [comment]
@benjamn Is this already solved by df77c39908dd802e00874e839e6cfb741bac8e6d? Today, we are suffering many times from this problem, and almost every third build is not working because of failing/infinite downloads.

**Comment by benjamn** [comment]
@Ben305 what error traces (if any) are you seeing?

**Comment by Ben305** [comment]
@benjamn Since our build server is running package test without settings any DEBUG-variables, I only see this in case a build times out:

<pre>
[[[[[ Tests ]]]]]
=> Started proxy.
=> Meteor 1.3.4: npm@3.9.6, .babelrc support, improved import declarations,
DDP update batching, and more:
https://github.com/meteor/meteor/blob/master/History.md#v134
This release is being downloaded in the background. Update your app to
Meteor 1.3.4 by running 'meteor update'.
=> Started MongoDB.
</pre>

I was running Meteor some days ago locally with DEBUG=1 and some other tracing variables (don't remember them exactly), when I discovered meteor was actually hanging again. The last line I saw said something like "downloading a package from warehouse.meteor.com "

**Comment by Borderliner** [comment]
This would be great! I don't have access to high-speed internet, and I can't even add small packages like flow-router because of connection timeout. Resume capability would be the best.

**Comment by Richie765** [comment]
After upgrading to 1.4, it became almost unworkable to me. My internet isn't particularly slow, 500 kb/sec, but upgrading various projects took forever, had to restart `meteor update` a zillion times.

**Comment by laosb** [comment]
Merged and released, closing
