### ISSUE TITLE
ES6 `export` from a mainModule not `api.export`ing as expected

### ISSUE THREAD

**Issue by twooster** [meteor/meteor#7273]
Tested against meteor 1.3.4-rc.1, stock dependencies.

## Expected behavior

ES6-style `export`s from an `api.mainModule` file should be the equivalent of doing an `api.export` of same.

## Observed behavior

ES6-style `export`s are somewhere between a package-level variable and an actual module export. Any packages that depend upon my package can `import` my `export`s, and can access them through `Package['mypackage']`, but they are not injected into the scope as per `api.export`.

## Test case

https://github.com/twooster/meteor-unexpected-export-behavior

## Discussion

This bit me for a long time today because it's not very clear in the documentation (indeed, it's in the comments of a code-block, http://docs.meteor.com/packages/modules.html#Modular-package-structure), and defies expected behavior.

It's puzzling and unsymmetric that I can `import { x } from 'meteor/some-package'` and get an implicit `api.use`, but the `export` statement in a main module is not an implicit `api.export`. I'm forced to duplicate my export statements in both my `mainModule` and my `package.js` file.

No rationale for this difference is given in the documentation and I cannot think of any good reason why ES6 modules are effectively given different `import` and `export` semantics to basic `api.use` and `api.export`, and why ES6 consumers of my package would have access to a wider scope of symbols than basic Atmosphere package consumers. 

Maybe (?) I can imagine that maybe it's intended to make up for the inability to deep-import from package subdirectories (I think this is the case?), but to me this is a failure of consistency and simplicity.

Lastly, using `Package['xyz']` to access these exports in non-ES6 modules is painful and doesn't feel best-practice, even if it is documented.

## Suggested fixes

1. Preferred: Make `export` symmetric to `import`'s behavior
2. Add an `api.exportModule()` or `{ autoexport: true }` flag to `api.mainModule`, or similar, so that I can specify my exports in one place (my code, not my package) only.
3. At the very least, make the documentation more shouty and clear about this asymmetry, and perhaps provide some rationale that makes it clear why the distinction is made, and how to use it effectively to one's benefit.

**Comment by benjamn** [comment]
The behavior you're observing is by design.

An `export` declaration in a main module only means the exported property can be `import`ed or `require`d by code that depends on the package. The `api.export` API is something different: it means any code that depends on this package will automatically see the exported symbol as a "global" variable, without having to import it explicitly.

Before Meteor 1.3, if you wanted to share symbols with other packages, you had to `api.export` them in your `package.js` file *and also* assign their values to package-scoped variables, e.g.:
```js
// In package.js
Package.onUse(function () {
  api.export("Symbol");
  api.addFiles("main.js");
});
```
and then 
```js
// In main.js
Symbol = "whatever";
```

The equivalent code in Meteor 1.3+ would be
```js
// In package.js
Package.onUse(function () {
  api.use("ecmascript");
  api.export("Symbol");
  api.mainModule("main.js");
});
```
and then 
```js
// In main.js
export var Symbol = "whatever";
```
So the thing that the `export` declaration is replacing is really just the assignment to the `Symbol` variable, and `api.export("Symbol")` is still necessary if you want `Symbol` to be automatically exposed to code that depends on this package.

With Meteor 1.3, you have the option of exporting properties from the main module but *not* `api.export`ing them. For instance, in the `accounts-base` package, we [`export class AccountsClient ...`](https://github.com/meteor/meteor/blob/8f86d08827d5ee686ce65a701c3c146ea7cc5a7c/packages/accounts-base/accounts_client.js#L13), but do not `api.export("AccountsClient")`, because most consumers of the `accounts-base` package should not need to use `AccountsClient` directly, and those that do can simply `import { AccountsClient } from "meteor/accounts-base"`.

The additional effort you expend to type `api.export` in your `package.js` file is intentional. Automatic imports are a peculiar feature of the Meteor package system that we must preserve for backwards compatibility, but we would like to discourage them moving forward.

Please note that `import { x } from 'meteor/some-package'` does not implicitly `api.use("some-package")`, as you claim. The `import` will work as long as the package is used in your application, but will stop working if the package is no longer used. I would consider a pull request to restrict imports to just the packages your app or package explicitly uses, I just haven't felt the need to enforce that restriction so far.

Thanks for explaining your expectations. It really is useful to hear when developers are surprised by some aspect of how the framework works. I realize Meteor's history can send mixed signals, and I'm always glad to clarify what we were thinking.

**Comment by twooster** [comment]
Very interesting, thank you for the discussion and reasoning. It makes the situation much clearer. I think I see how MDG expects to transition towards ES6 packages more widely now.

I didn't realize `import` didn't use automatically, but I understand now. (This was not an issue in my project because I'm dealing with local packages, so of course I never saw dependency fetching problems.)

On deeper thought, I can see the following pattern arising as the transition away from `api.export` is occurring: If you want to have access via ES6 `import` to a bunch of packages, but not have them pollute the global namespace of e.g. your application, one would be well advised to create some kind of metapackage. For example, under my local `yourapp/packages/import-metapackage`:

`yourapp/packages/import-metapackage/package.js`
```
Package.describe({ name: 'import-metapackage' })
Package.onUse(function(api) {
  api.use([ 'exporting-and-polluting']);
});
```

Then run `meteor add import-metapackage`. And in app code:

`yourapp/main.js`
```
import { someMethod } from 'meteor/exporting-and-polluting'

someMethod(123);
```

This pattern would close the circle on the the Meteor packaging system going forward. Sound about right?

Thanks once again for your thorough and explanatory reply. Closing the issue.
