### ISSUE TITLE
Meteor Accounts and Private Mode in Safari

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#7282]
Hey,
I'm having some trouble with the private mode of Safari and Meteor Accounts. If I log in and refresh the page, I'm not logged in anymore. This behavior doesn't exists on Chrome or Firefox and also not on common pages that use a PHP framework as backend (they work fine on Safari).

Maybe it's a problem with the local storage and the stored login token? I think Safari clears it on a refresh.

We tried also to access <code>meteor_login_token</code> cookie during startup, but it is empty.

**Comment by mjmasn** [comment]
Looks like a known issue with Safari... https://slashdot.io/blog/local-storage-is-not-supported-with-safari-in-private-mode-1274581356

**Comment by dnish** [comment]
Yeah, but Meteor also stores it's login token within a cookie, so why does it ignore the cookie on reload?

**Comment by mjmasn** [comment]
Meteor definitely doesn't use cookies. This is as you say for security reasons (preventing CSRF attacks), unless you have some package that's adding a cookie? `fast-render` perhaps?

**Comment by dnish** [comment]
Sure, fast-render is added in our project.

**Comment by hwillson** [comment]
This is a known issue with Safari. Writing to `localStorage` is not supported in private browsing mode. You can verify this by opening a new private browsing window in Safari, and attempting a `localStorage.setItem` call in the browser console. You'll be greeted with a `QuotaExceededError (DOM Exception 22): The quota has been exceeded.` exception.

Meteor does what it can to help address this through it's [`localstorage`](https://github.com/meteor/meteor/tree/devel/packages/localstorage) package. If full `localStorage` functionality  isn't available, this package essentially creates a mock `localStorage` object, which is then used by Meteor internally. Unfortunately this mock `localStorage` object isn't persisted, so refreshing your window will wipe it. 

Since this is a restriction of Safari and not an issue with Meteor itself, I'll close this issue off. Thanks for reporting this originally!
