### ISSUE TITLE
Meteor not starting hang on meteor-tools after downloaded (OSX)

### ISSUE THREAD

**Issue by jordaofranca** [meteor/meteor#7283]
![captura de tela 2016-06-23 as 10 32 38](https://cloud.githubusercontent.com/assets/4587898/16305008/58216310-392e-11e6-8d17-1c42ac721a50.png)

**Comment by benjamn** [comment]
Yeah, sometimes this takes a long time, but it usually does finish eventually. It's safe to cancel it, since it's downloading into a temp directory, so canceling won't leave your installation in a half-installed state or anything like that.

I see you're downloading Meteor 1.3.2.4. Maybe try `meteor update --release 1.3.4` (or just `meteor update` now, given that 1.3.4 was published yesterday)?

**Comment by cellog** [comment]
this is a blocking issue for me on linux.  I can't do ANYTHING with meteor because even a simple "meteor list" dies:

unl@vultr:~/unl-strings$ meteor list
Killednloading meteor-tool@1.3.2_4...        |

**Comment by aboire** [comment]
cdn https://github.com/meteor/meteor/issues/6960

**Comment by abernix** [comment]
@cellog How long did you leave it to run before you killed it?  The Meteor Tool is a rather large file (and the 1.3.2.4 bundle is even larger than the more recent versions, which are actively being trimmed down).  The compressed size is 158MB (downloaded) and the uncompressed size is just shy of a gigabyte.

With a very fast connection and a very fast CPU the minimum amount of time I expect it to take to download, uncompress, resolve package dependencies, download those, etc. is most likely 4-5 minutes but with slower conditions I could see it taking 15-20 minutes.

**Comment by cellog** [comment]
I didn't kill it. The OS did.

On Thu, Jun 30, 2016 at 2:54 AM, Jesse Rosenberger < notifications@github.com [notifications@github.com] > wrote:
@cellog [https://github.com/cellog] How long did you leave it to run before you killed it? The Meteor Tool is a rather large file (and the 1.3.2.4 bundle is even larger than the more recent versions, which are actively being trimmed down). The compressed size is 158MB (downloaded) and the uncompressed size is just shy of a gigabyte.

With a very fast connection and a very fast CPU the minimum amount of time I expect it to take to download, uncompress, resolve package dependencies, download those, etc. is most likely 4-5 minutes but with slower conditions I could see it taking 15-20 minutes.

**Comment by abernix** [comment]
@cellog Do you know why your OS would be killing it?  That is very unexpected behavior unless you're encountering an out of memory situation where the OOM killer is killing the process to maintain the stability of the core system.

What OS are you on?  And what does the output of `dmesg` show immediately after it's killed?

**Comment by cellog** [comment]
Here's the thing: I am about to go to a low-speed, high-cost Internet 
situation for 5 weeks, so last night was my only chance to get things up 
and running.

I've always liked meteor precisely because this kind of bs is (was) 
non-existent. It will be faster and easier for me to learn a whole new 
stack than to debug this for you.


via CloudMagic Email 
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.47&pv=5.1.1&source=email_footer_2]

**Comment by abernix** [comment]
@cellog Your issue is different than the original that was reported in this issue.  In case it wasn't clear, none of the components I referred to are a part of Meteor.  I also wasn't implying that you had to "debug this for (me)" but as you brought it up as an issue, I thought I'd try and help. (Though you make it sound like I asked for something unreasonable!)  As you can imagine, if _your_ Linux kernel (or some other process on your PC) is forcefully killing Meteor then that's something that would be quite hard for Meteor to deal with.  Anyhow, hope you figure it all out!

**Comment by hwillson** [comment]
> I've always liked meteor precisely because this kind of bs is (was) non-existent. It will be faster and easier for me to learn a whole new stack than to debug this for you.

@cellog - The Meteor you've always liked would never have happened if everyone who contributed to its success in one way or another thought like this.

@abernix - Just a quick side note here; you're really doing amazing work with triaging these issues. Some don't seem to understand the amount of effort you're putting into helping out with these issues, and that you're not employed by MDG. I just wanted to say thanks for all of your hard work, and please don't get discouraged when you see comments like the above.

**Comment by cellog** [comment]
well the virtual machine that I am using has 768MB of RAM.  I could upgrade for an additional $120/year just to be able to install meteor-tools on top of what I'm already paying.  But that makes no sense, I don't need the additional memory, except for the installation part of this.  It's too large.  As for those criticizing me for being upset about this, keep in mind I have invested a couple of years into meteor, including an entire website successfully running on an older version of meteor - on the same sized virtual machine.  It makes no sense that a gig of memory and an additional 5-10 minutes would be needed just to run "meteor list." after I've just installed meteor.

But with this change, I'm literally priced out of using meteor.

So before you blame the user, take a look at the situation on the ground.  Most users will find that a fresh meteor install simply fails and move on.  I took the time to report the problem, and a quick search of google reveals I am not close to alone in experiencing huge problems with this change.  So by all means, pat each other on the backs, but don't be shocked when the userbase dwindles as a result.

**Comment by abernix** [comment]
@jordaofranca Did you have any update on your original issue?  I don't want to lose focus of the initial problem.  The download of the bootstrap file and the extraction can take a while so do give it some time to run.  If you're still stuck, I'd like to maybe capture the state of your `$HOME/.meteor` project directory and take a look at it on my own development machine to try and debug.  If you can provide it with:

    tar cvf - $HOME/.meteor | gzip -9c > ~/meteor_backup.tar.gz

...and then provide me with a (Dropbox, maybe?) link, it'd be much appreciated in sorting it out.  Feel free to private message it to me in [Meteor Forums](http://forums.meteor.com) messaging if you don't feel comfortable posting it here. :smile:

**Comment by abernix** [comment]
@cellog 

> the virtual machine that I am using has 768MB of RAM

This is a low amount of memory for a development environment.  File watches, a database instance, package cataloging, re-compilation, etc. etc. have memory requirements.  Can I ask why you're running your development on a remote virtual machine instead of your own workstation?  For production, this configuration would be fine but the `meteor` tool itself is intended _only_ for development so it's expected to run on your personal workstation where you have your IDE, etc.

> I have invested a couple of years into meteor, including an entire website successfully running on an older version of meteor - on the same sized virtual machine. It makes no sense that a gig of memory and an additional 5-10 minutes would be needed just to run "meteor list." after I've just installed meteor.

Technical explanation: If you're doing a `meteor list` on an old (pre-1.3.4.1) project after you've done a fresh install (1.3.4.1) it's going to have to download the bootstrap of the previous Meteor version first in order to run it.  This will consume some resources.  The latest installer only provides the latest bootstrap and older versions are fetched as necessary.  If you keep running the existing meteor without a fresh reinstall that would be avoided as the old bootstrap would already be in place.

Opinion: I've been using Meteor since 0.6 (or so).  It has seen an overwhelming number of improvements and additions over the last 3 years and it's complexity has absolutely increased.  I fully expect additional functionality and "Meteor magic" (if I must say it) to come with additional resource consumption – as with most other evolving technologies.  Again, running production is much more toned down and a project run with `meteor build` utilizes a _fraction_ of the resources as the `meteor` tool.

> Most users will find that a fresh meteor install simply fails and move on.

I don't believe you can make this statement because you don't have stats on successful installs vs unsuccessful installs.  I know failures can be deal-breakers though.

> those criticizing me for being upset about this

Nobody did that, but I think your unwillingness to take the one minute necessary to provide the output of the single command requested and instead write a vulgar paragraph about how disappointed you are is a strange exit-strategy for your two-year Meteor investment.  I think the unwillingness to help yet still be able to complain was the issue.

If you'd like help fixing your problem, please open a new issue (since it's not the same as this one) with specific information about your environment and a desire to help resolve it.  If there is a bug involved, someone in the community (myself included) would be thrilled to find it and fix it.

**Comment by JuanJo4** [comment]
Hey all,

I have the exact problem as @jordaofranca.

I downloaded meteor as website says `curl https://install.meteor.com/ | sh` and installed version `METEOR@1.3.2.4` then I've been playing with tutorial and all worked perfect.

Then I cloned a meteor project and run `meteor` and get stuck at `Downloading meteor-tool@1.3.2_4...        /`

I'm not sure if this is a CDN issue as #6960 suggests, but in case it helps here are some info:

> http://debug.netdna-cdn.com

You are hitting the MaxCDN New York Datacenter

>http://checkip.amazonaws.com
75.101.165.142

> The output of traceroute static-meteor.netdna-ssl.com (or tracert on Windows)
`traceroute to static-meteor.netdna-ssl.com (94.31.29.248), 64 hops max, 52 byte packets
 1  xxx.xx.xxx.x (xxx.xx.xxx.x)  177.426 ms  270.390 ms  238.291 ms
 2  10.0.0.0 (10.0.0.0)  141.237 ms  352.715 ms  302.585 ms
 3  10.0.0.0 (10.0.0.0)  239.373 ms  550.868 ms  440.059 ms
 4  10.0.0.0 (10.0.0.0)  324.044 ms  225.157 ms *
 5  * 10.0.0.0 (10.0.0.0)  220.308 ms  134.571 ms
 6  10.0.0.0 (10.0.0.0)  335.010 ms  292.349 ms  225.331 ms
 7  10.0.0.0 (10.0.0.0)  136.614 ms  286.204 ms *
 8  100.92.162.85 (100.92.162.85)  315.146 ms
    100.92.162.16 (100.92.162.16)  301.882 ms
    100.92.162.120 (100.92.162.120)  223.576 ms
 9  100.92.158.84 (100.92.158.84)  319.551 ms  200.576 ms
    100.92.158.89 (100.92.158.89)  400.554 ms
10  100.92.158.67 (100.92.158.67)  309.860 ms  241.155 ms
    100.92.158.71 (100.92.158.71)  213.080 ms
11  100.92.148.168 (100.92.148.168)  355.833 ms
    100.92.148.161 (100.92.148.161)  309.895 ms
    100.92.148.185 (100.92.148.185)  219.321 ms
12  100.92.148.182 (100.92.148.182)  199.841 ms
    100.92.148.189 (100.92.148.189)  318.788 ms
    100.92.148.185 (100.92.148.185)  388.723 ms
13  100.92.152.79 (100.92.152.79)  235.313 ms
    100.92.152.121 (100.92.152.121)  421.625 ms
    100.92.152.93 (100.92.152.93)  603.454 ms
14  100.92.148.70 (100.92.148.70)  346.250 ms
    100.92.148.79 (100.92.148.79)  191.117 ms
    100.92.148.73 (100.92.148.73)  467.868 ms
15  100.92.148.233 (100.92.148.233)  301.820 ms
    100.92.148.239 (100.92.148.239)  196.940 ms
    100.92.148.230 (100.92.148.230)  310.053 ms
16  100.92.144.226 (100.92.144.226)  134.888 ms
    100.92.247.143 (100.92.247.143)  326.928 ms
    100.92.128.232 (100.92.128.232)  216.381 ms
17  100.92.144.241 (100.92.144.241)  303.560 ms
    100.92.144.249 (100.92.144.249)  314.009 ms
    216.182.224.206 (216.182.224.206)  362.630 ms
18  100.92.143.33 (100.92.143.33)  341.076 ms
    216.182.224.216 (216.182.224.216)  592.727 ms
    100.92.132.225 (100.92.132.225)  647.539 ms
19  100.92.128.196 (100.92.128.196)  441.401 ms
    100.92.128.160 (100.92.128.160)  554.445 ms
    100.92.145.189 (100.92.145.189)  301.272 ms
20  100.65.2.176 (100.65.2.176)  308.827 ms
    100.92.144.167 (100.92.144.167)  303.586 ms *
21  100.92.241.15 (100.92.241.15)  440.709 ms
    100.92.241.27 (100.92.241.27)  307.156 ms
    216.182.224.110 (216.182.224.110)  254.958 ms
22  216.182.224.38 (216.182.224.38)  213.950 ms
    216.182.225.88 (216.182.225.88)  307.180 ms
    100.66.3.14 (100.66.3.14)  228.291 ms
23  100.66.8.104 (100.66.8.104)  213.860 ms
    100.66.6.133 (100.66.6.133)  235.532 ms
    100.66.11.196 (100.66.11.196)  233.682 ms
24  100.66.15.8 (100.66.15.8)  170.674 ms
    100.66.6.71 (100.66.6.71)  278.921 ms
    100.66.6.131 (100.66.6.131)  173.275 ms
25  100.66.6.239 (100.66.6.239)  259.823 ms
    100.65.10.65 (100.65.10.65)  256.159 ms
    100.66.7.99 (100.66.7.99)  157.103 ms
26  100.66.4.221 (100.66.4.221)  199.169 ms
    100.66.4.131 (100.66.4.131)  217.007 ms
    100.66.4.75 (100.66.4.75)  293.928 ms
27  * 100.65.10.129 (100.65.10.129)  136.458 ms
    100.65.9.97 (100.65.9.97)  228.887 ms
28  54.239.108.94 (54.239.108.94)  393.253 ms
    54.239.108.49 (54.239.108.49)  133.857 ms
    54.239.111.40 (54.239.111.40)  304.421 ms
29  54.239.108.217 (54.239.108.217)  143.613 ms
    54.239.41.221 (54.239.41.221)  143.104 ms
    54.239.111.149 (54.239.111.149)  134.745 ms
30  52.93.4.25 (52.93.4.25)  145.617 ms
    54.239.41.221 (54.239.41.221)  297.928 ms  222.378 ms
31  52.93.4.92 (52.93.4.92)  218.521 ms
    52.93.4.15 (52.93.4.15)  311.471 ms
    52.93.4.90 (52.93.4.90)  173.712 ms
32  72.21.221.233 (72.21.221.233)  139.163 ms
    52.93.4.100 (52.93.4.100)  249.685 ms
    52.93.4.9 (52.93.4.9)  350.981 ms
33  52.93.4.98 (52.93.4.98)  219.867 ms
    52.93.4.90 (52.93.4.90)  199.710 ms
    ae2.cr1.lga5.us.zip.zayo.com (64.125.31.213)  331.276 ms
34  ae2.cr1.lga5.us.zip.zayo.com (64.125.31.213)  261.731 ms
    72.21.221.233 (72.21.221.233)  200.705 ms
    ae2.cr1.lga5.us.zip.zayo.com (64.125.31.213)  185.506 ms
35  ae2.cr1.lga5.us.zip.zayo.com (64.125.31.213)  144.581 ms  162.827 ms *
36  ae10.mpr3.lga7.us.zip.zayo.com (64.125.20.77)  353.659 ms
    netdna-gw.jfk.ip4.above.net (209.249.99.226)  275.872 ms  258.713 ms
37  94.31.29.248.ipyx-077437-zyo.above.net (94.31.29.248)  403.828 ms  339.922 ms  193.605 ms`

>Your location/country/geographic area

I'm on a OSX machine and located in South America.

Any help would be appreciated.

Best,
Juan

**Comment by abernix** [comment]
@JuanJo4 Does the downloading progress-bar go all the way to 100% before you experience this problem?   How long does it sit there at `Downloading`?  Is the spinner (`\ | / -`) bar there and moving?

**Comment by JuanJo4** [comment]
@abernix No, came up to 20% aprox and then spinner bar started moving, here is when gets stuck. I killed the process after 4 hours aprox.

**Comment by abernix** [comment]
@JuanJo4 Instead of just running `meteor`, you might try updating the cloned repo to the latest release candidate for [Meteor 1.3.5](https://github.com/meteor/meteor/pull/7407) (coming soon):

    meteor update --release 1.3.5-rc.1

No guarantee that this will work, but it has some fixes for some downloading problems.  Namely, #7399.

**Comment by JuanJo4** [comment]
@abernix I tried this without success. Let me know how can I help on #7399

**Comment by hyiltiz** [comment]
Anyone seeing this, try making a swap:
```BAH
dd if=/dev/zero of=/PATH/FILENAME bs=1024 count=1048576 # 1G swap file
chmod 600 /PATH/FILENAME
mkswap /PATH/FILENAME
swapon /PATH/FILENAME
```

**Comment by abernix** [comment]
@JuanJo4 Meteor 1.3.5.1 is officially out now and has a potential fix for downloads which are not finishing.  Try updating your project with `meteor update --release 1.3.5.1`.  If you're still getting stuck, please try the instructions [in this comment](https://github.com/meteor/meteor/issues/6960#issuecomment-226641013) about updating your `hosts` file and if you're still having problems after that, please open a new issue and someone will take a look.

**Comment by Sphinxxxx** [comment]
@cellog I had the same problem (on a Vagrant VM). Turns out meteor needs a lot of RAM, and there wasn't enough on the machine. I fixed it by adding a swap file. Directions here: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

SO post that helped me: http://stackoverflow.com/a/37829273/1869660

**Comment by benjamn** [comment]
Just wanted to note that one of the reasons Meteor may need lots of RAM after downloading `meteor-tools` is that we use the http://npmjs.org/package/tar to extract the archive, rather than the native `tar` command (or something like `7z` on Windows). The memory and time savings from using native extraction tools could be huge! It takes 45 seconds to extract `meteor-tool` using the JS library, but only 3.5 seconds to extract it using `tar xf` (on my machine).

**Comment by JuanJo4** [comment]
@abernix Thanks for all of your support. It works after following instructions on [this comment](https://github.com/meteor/meteor/issues/6960#issuecomment-226641013).

**Comment by yaitloutou** [comment]
hello i have the same issue

I was working on a project with version 1.3.5. but after installing meteor version 1.4 at ~/.meteor with the command: 
`curl https://install.meteor.com | /bin/sh`
the download/installation gown well. but each time I goes to my project directory and run meteor, or try to create a new one with meteor create. meteor get stuck -after reaching 100%- at 
`Downloading meteor-tool@1.3.5_1...            /`

I've tried, to:
1. remove ~/meteor, 
2. re-install it from the project, by running meteor or meteor update, but it doesn't work

my OS is ubuntu 16.04

> http://debug.netdna-cdn.com/
You are hitting the MaxCDN Paris Datacenter

> http://checkip.amazonaws.com/
105.154.71.112

> output of : meteor updtae --release 1.3.5.1
http://pastebin.com/VfrWYJZf

**Comment by JuanJo4** [comment]
@yaitloutou Try following the steps here https://github.com/meteor/meteor/issues/6960#issuecomment-226641013

**Comment by yaitloutou** [comment]
@JuanJo4 thank you. and sorry to don't report back earlier.

It was already done, I've followed the steps mentioned by @n1mmy [here](https://github.com/meteor/meteor/issues/6960#issuecomment-226641013), 
but editing /etc/hosts doesn't solve the issue for me.

what (I suppose) does it was:
- uninstalling meteor, 
- trying different network.
- re-install then update from the project directory
- and waiting for a long while: about 18 minutes instead of the usual short time.

Not sure what step does the trick, but at least I had my project running with meteor 1.4.

Then when I created a new one, i run into this issue #7476 ^^"

**Comment by hwillson** [comment]
It's been a while since anyone has added anything to this issue, and a lot of the past downloading / hanging issues were CDN related (see issue #6960 for the full backstory, just make sure you have time to grok through 297 comments ... 🙂). Anyways, the CDN issues have since been resolved and as part of the on-going old issue cleanup process, I'll close this issue off. Thanks for reporting this originally!

**Comment by justbill2020** [comment]
lol @cellog gets free open source project, bitches about his own short comings and disrepects the people attempting to assist him. what a shame, sadly this happens way too often in open source projects...

**Comment by vijaymchauhan** [comment]
You can run 'meteor update' , will fix issue in my case
