### ISSUE TITLE
Cannot import from hidden folders

### ISSUE THREAD

**Issue by gsabran** [meteor/meteor#7286]
It looks like Meteor fails to import files from hidden folders. Here is a simple reproduction: https://github.com/gsabran/meteor-import-hidden-folder

It's convenient to use hidden folders to put files there that you don't want Meteor to read by default and have full control over what is happening.

If you build with webpack:webpack, all is fine (see https://github.com/gsabran/meteor-import-hidden-folder/tree/webpack-build).

**Comment by laosb** [comment]
Hi, you should put all files to be imported in `imports`, instead of hidden folders, as dot files/folders are mostly considered *something human shouldn't touch*. However, Meteor does fail to import. If you have another case which need to import from hidden folders/files, please reopen this. It doesn't sounds like a good feature to consider for now.

**Comment by gsabran** [comment]
The reason for putting files in `.` folders is that I don't want Meteor to look at them by default, because the build time is already very slow so I just want Meteor to look at files I explicitly say I want to import.

**Comment by gsabran** [comment]
And more generally, I don't think having Meteor follow what has become standards in the node ecosystem should probably not be just a "feature"

**Comment by laosb** [comment]
I guess it's because Meteor totally ignore `.` folders/files that you can't import those files. So a quick fix is just look at all dot files and I'm afraid that this will break your hope of *just want Meteor to look at files I explicitly say I want to import*. Actually, I think all files in `imports` should be finally imported, so that won't be a big deal to watch them all. What we really need to do is **improve the build time**.
