### ISSUE TITLE
[1.3.4] wont start on windows

### ISSUE THREAD

**Issue by akhatri** [meteor/meteor#7299]
I am trying to install Meteor 1.3.4 on windows 10 (64 bit) but it throws an error

I run meteor at CMD but get this
```\AppData\Local\.meteor\\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\meteor.bat"' is not recognized as an internal or external command,
operable program or batch file.```

I have uninstalled meteor several times and deleted the .meteor folder before re-installing but had no luck.
In the folder above, there is no meteor.bat file, but just a Linux file, screenshot attached
![capture meteor issue](https://cloud.githubusercontent.com/assets/2246544/16357131/757abec0-3b31-11e6-92d2-ac038b7ffc6b.PNG)

**Comment by abernix** [comment]
Sorry to hear about your problems...  there definitely should be a `meteor.bat` in that folder!  Something very bizarre about that.

* _Specifically_ what Windows version are you using? Enterprise? Home?
* What command prompt are you using?  Default Command Prompt? MINGW32? PowerShell? Something fancier?
* Did you restart after installation completed?
* Are you just typing `meteor`?

I literally just did a fresh re-install of Meteor 1.3.4.1 about an hour ago on Windows 10 Enterprise 64-bit.  Here's what I did:

* Uninstall Meteor from Settings > System > Apps & features > "Meteor" > "Uninstall"
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

Mind trying the reinstall again?

**Comment by akhatri** [comment]
@abernix thanks for your help. I followed the steps and it worked! I guess the install I had might not be correct.

For any future users specs
- Windows 10 64-bit Home Edition
- Using standard command prompt

**Comment by ramesh-r** [comment]
@abernix Thanks for your help.It works:)
