### ISSUE TITLE
Server use ACCOUNTS_CONNECTION_URL when specified

### ISSUE THREAD

**Issue by chriscarpenter12** [meteor/meteor#7315]
This relates to [accounts-base](https://github.com/meteor/meteor/tree/devel/packages/accounts-base).

When specifying ```__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = 'http://myurl';``` shouldn't the server respect this setting as well?

I understand from this [comment](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L192) that this setting tells the client to use a different connection to handle auth. Which is working perfectly for me. Shouldn't the server use this connection as well then because if we specify any server publications and use ```this.userId``` it will always return null because we are not using a local users collection any longer?

[server_main.js](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/server_main.js#L9) is not doing any kind of checking to use another connection.

I also can't seem to override Accounts server side to use another connection with AccountServer.

In the Meteor application that is specifying ```__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = 'http://myurl';```

```
Meteor.publish('test', function() {
  var user = this.userId;
  console.error('server-user', user);
  return user;
});
```

```
App 15481 stdout: W20160627-16:31:17.029(-4)? (STDERR) server-user null
```

### METEOR@1.3.3
```
meteor-base
mobile-experience
mongo
blaze-html-templates
reactive-var
jquery
tracker
standard-minifier-css
standard-minifier-js
es5-shim
ecmascript
fourseven:scss
kadira:flow-router
kadira:blaze-layout
arillo:flow-router-helpers
accounts-password
themeteorchef:bert
session
themeteorchef:jquery-validation
sacha:spin
aldeed:template-extension
```

**Comment by abernix** [comment]
> Remember, an issue is not the place to ask questions. 

Even still, it's not at all clear what you're trying to accomplish.  If you're trying to log in from DDP, there are a number of connect-via-DDP options available to do this.  I'm not sure what you expect the server to do differently when you're pointing the client to a separate server?  The server isn't going to connect to another server if that's what you're suggesting.

Again, it's just not clear.  Instead of using Meteor issues, please pose your question on the very friendly [Meteor forums](http://forums.meteor.com/) or [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and if you actually work it into a reproducible issue or feature request that meets the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) it is more than welcome here. :smile:
