### ISSUE TITLE
meteor's HTTP.call doesn't support digest auth?

### ISSUE THREAD

**Issue by jiayuwang** [meteor/meteor#7321]
if it possible to support it?

**Comment by abernix** [comment]
It _might_ be possible right now.  It definitely supports basic auth, but digest might take additional work.

Internally, HTTP.call uses `request` to make the request and `request` supports digest authentication (search [this page](https://www.npmjs.com/package/request#http-authentication) for `digest`).

It appears you'd need to use `npmRequestOptions` (which is passed directly to `request`) to set `sendImmediately` to `false` so it can do the handshaking necessary when the 401 response is received.  You _may_ also need to set `username` and `password` on the `npmRequestOptions` instead of using the `HTTP.call` `auth` option.

I would ask for additional help on the [Meteor Forums](http://forums.meteor.com).

**Comment by lc3t35** [comment]
Works fine ;) thx @abernix 
````
var result = HTTP.get("http://xxxxx",
        { npmRequestOptions:
          { 
            'auth': {
              'user': 'xxxx',
              'password': 'yyyy',
              'sendImmediately' : false
            }
          }
        }, function (error, result) {
            /.../
        });
````
