### ISSUE TITLE
Overriding base Promise breaks project silently.

### ISSUE THREAD

**Issue by AlexFrazer** [meteor/meteor#7325]
I was following [this issue with babel-loader](https://github.com/babel/babel-loader/issues/23) in order to use Bluebird as the native promise library.

```
/** imports/polyfills/promise.js */

import Bluebird from 'bluebird';
global.Promise = Bluebird;
```

Now, whenever I use an async function, it will break.

```
export async function wait(ms=5000) {
  check(ms, Number);
  await new Promise((resolve, reject) => setTimeout(resolve, ms));
}
```
Running it will yield this error.
```
> await wait();
Exception while invoking method 'wait' Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
```

**Comment by abernix** [comment]
Meteor uses it's own [`meteor-promise`](https://github.com/meteor/promise) library internally to provide a `Promise` which is Fiber/await aware, which is currently necessary on the Meteor server.  You're essentially destroying that logic by replacing it with bluebirds.

You can `meteor add promise` to your own Meteor project and use that as your `Promise` library – it will be available on both the client and the server. If you want to use `bluebird` you will probably have some battles with fibers (as indicated by the `Meteor code must always run within a Fiber` error above).

**Comment by benjamn** [comment]
Note that the `promise` package will use the `global.Promise` constructor if one is already defined: https://github.com/meteor/meteor/blob/f19241c60b52fd87e58e7a0a16f78dc1c630a7be/packages/promise/common.js#L3-L7

**Comment by AlexFrazer** [comment]
Is there any plans of this changing in the future? Slightly annoying to use `import Promise from 'bluebird'` in every circumstances

**Comment by abernix** [comment]
> Is there any plans of this changing in the future?

Moving away from Fibers?  _Probably changing in the future, though not on the radar right now_
Moving toward using global variables to avoid `import`?  _Unlikely..._

`import`-ing what you need into at the top of each module is becoming commonplace in JavaScript with the coming of ES6 (ECMAScript 2015) and the easy and clean ability to `import`/`export` other modules.  This keeps the global namespace unpolluted and significantly helps with debugging, dependency resolution and optimization.

I will point out that since JavaScript ES6 is supported and `Promise` is part of the ES6 spec, you can just simply _use_ [`Promise`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) and you'll be using a poly-filled, fiber-aware Promise library that doesn't require you `import`-ing `bluebird` at the top of every file (or installing it at all!).

I suppose if you really _need_ to use `bluebird` you can use your own name for a global variable (i.e. `global.Bluebird` – though again, globals are discouraged), but you'll need to handle wrapping promise callbacks in fibers on your own.

**Comment by alex-shamshurin** [comment]
If this is somehow can help to someone it's what I do to replace native es6 Promise object and es6-polyfill with bluebird in webpack:

```
config.plugins.push(
		new webpack.ProvidePlugin({
			...
			'Promise'                : 'bluebird',
			...
			
		}),
		new webpack.NormalModuleReplacementPlugin(/es6-promise$/, 'bluebird')
	);
return config;
```
