### ISSUE TITLE
Meteor server method gets called multiple times even though client initiated only once.

### ISSUE THREAD

**Issue by winmhtun** [meteor/meteor#7352]
is it just me or has anyone else noticed before that Meteor.call("some_method") will get executed again after some long time if it couldnt finish execution after certain period? i.e. before 1st call of "some_method" has not been finished, 2nd call started automatically after certain period. Any ideas on how to fix that?

**Comment by abernix** [comment]
> Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/meteor) for that, or you may want to start a discussion on the [Meteor forum](https://forums.meteor.com/).

Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

Please read the [Meteor Docs](http://docs.meteor.com) and [the Meteor Guide](http://guide.meteor.com/) carefully.  If you're still having problems post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
