### ISSUE TITLE
App startup timed out - when started via background process used for Geofencing (iOS)

### ISSUE THREAD

**Issue by ddresch** [meteor/meteor#7359]
I'm running into the problem when trying to implement Geofencing in my app.

The cordova package I'm using is `cordova-background-geolocation-lt`also I checked already with the maintainer of this package if it's maybe a bug in there, the answer was - no.

https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/126#issuecomment-230746113

I created a repo to see the behavior.

https://github.com/ddresch/meteor-geofencing-test

All is fine as long as the app is running. When the app is terminated it gets started again by the background process as expected but gets stuck in `App startup timed out` ... error.

I checked this issue which I guess is not related:

https://github.com/meteor/meteor/issues/6465

Maybe this one @martijnwalraven ?

https://github.com/meteor/meteor/issues/6459

**Comment by Wade-BuildOtto** [comment]
FYI - that plugin is meant for real-time fleet tracking, Apple doesn't allow background tracking unless you can provide a use case for your app to use it all the time, if you are just using it for geofence just use cordova-plugin-geofence and turn off background location. when always is set it will use "on significant changes" which use less resources.

**Comment by observaInc** [comment]
Did anything come of this?  I experience the same problem on iOS on my iPad (no cellular service).  Here is my repo:

1. Start app with background-geolocation-lt with the setting stopOnTerminate = false.
2. Stop app.
3. Turn on Airplane Mode.  Wait 15 seconds.
4. Turn off Airplane Mode. 
5. Start app again.   Hangs on splash screen.  In log files, the only pertinent line out of the ordinary I see is:
<Warning>: Failed to load webpage with error: Could not connect to the server.

Strangely, if I perform the above steps, but just turn off wifi (instead of airplane mode) and then turn it back on again, there is no problem.
Also, if I run the app with stopOnTerminate = true, this problem does not occur.

**Comment by observaInc** [comment]
The problem I was experiencing is fixed by the fix to cordova-plugin-meteor-webapp.  Not officially release yet though.

https://github.com/meteor/cordova-plugin-meteor-webapp/issues/24

**Comment by lpender** [comment]
https://github.com/meteor/meteor/issues/8763

**Comment by hwillson** [comment]
This issue was fixed when https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25 was merged. Thanks!
