### ISSUE TITLE
accounts-twitter package is not retrieving the name of the user

### ISSUE THREAD

**Issue by ittechsathish** [meteor/meteor#7362]
accounts-twitter package is not retrieving the name of the user. Could anyone help me with this issue.

**Comment by abernix** [comment]
Hello,

These issue cases are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

There are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

Please visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community or post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or 

Thank you for your understanding!
