### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by OptimisticLock** [meteor/meteor#7381]
I am running a freshly updated Meteor 1.3.4.4 on OS X.

I am trying to `npm install selenium-webdriver` like this:
```
meteor create sel
cd sel
meteor npm install --save selenium-webdriver
meteor npm install --save bufferutil utf-8-validate
echo "require('selenium-webdriver')" > server/main.js
meteor
```

I am getting this:

```
                
                                              
Unable to resolve some modules:

  "/imports/somethingSel" in /Users/irinaapex/irina/meteor/sel/server/main.js (os.osx.x86_64)
                                              
W20160710-17:41:23.822(-7)? (STDERR)          
W20160710-17:41:24.046(-7)? (STDERR) /Users/irinaapex/irina/meteor/sel/.meteor/local/build/programs/server/packages/modules.js:654
W20160710-17:41:24.046(-7)? (STDERR) const builder = require('./builder');
W20160710-17:41:24.057(-7)? (STDERR) ^^^^^    
W20160710-17:41:24.057(-7)? (STDERR) SyntaxError: Use of const in strict mode.
W20160710-17:41:24.057(-7)? (STDERR)     at /Users/irinaapex/irina/meteor/sel/.meteor/local/build/programs/server/boot.js:292:30
W20160710-17:41:24.058(-7)? (STDERR)     at Array.forEach (native)
W20160710-17:41:24.059(-7)? (STDERR)     at Function._.each._.forEach (/Users/irinaapex/.meteor/packages/meteor-tool/.1.3.4_4.y43ln9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160710-17:41:24.059(-7)? (STDERR)     at /Users/irinaapex/irina/meteor/sel/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8                        
                                   
```

**Comment by abernix** [comment]
This is happening because `selenium-webdriver` [doesn't transpile their code to support Node 0.10](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/javascript/node/selenium-webdriver/index.js#L25) (the version of Node that Meteor 1.3 uses), this won't work with the Meteor 1.3 releases since Node 0.10 doesn't support the `const` ES6 usage and Meteor (rightfully) doesn't transpile NPM dependencies.

Meteor 1.4 (currently in beta) should run this just fine.  Follow #7218 for the progress on the 1.4 branch, and try it today by using:

    meteor update --release 1.4-beta.9

You can also pass `--release 1.4-beta.9` to the `meteor create` command you're using above and it should be good. :smile:

**Comment by OptimisticLock** [comment]
Thank you, it worked. Just curious, why was not Selenium anywhere in the call stack?

**Comment by benjamn** [comment]
@OptimisticLock If you enable source maps in your browser, it should show modules from `node_modules` as separate files in the debugger, though it's true they do get merged into that big `modules.js` file.

**Comment by OptimisticLock** [comment]
I am on the server, but I am sure the same applies. Trouble is, modules.js is rebuilt on every run. Would be nice to know how to suppress the rebuild.
