### ISSUE TITLE
Errors in 1.3.4.4

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7404]
Just upgraded and all my previous namespaces in the root of my app are throwing exceptions

```
 Uncaught Exception: 'ReferenceError: Bigquery is not defined\n    at 
meteorInstall.namespaces.workpop-bigquery.server.bigqueryNamespace.js 
(namespaces/workpop-bigquery/server/bigqueryNamespace.js:4:1)\n    at fileEvaluate 
(packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)\n    at require 
(packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)\n    at 
/Users/abhiaiyer/Projects/Workpop-Org/Workpop-
Web/.meteor/local/build/programs/server/app/app.js:33714:1\n    at 
/Users/abhiaiyer/Projects/Workpop-Org/Workpop-
Web/.meteor/local/build/programs/server/boot.js:297:10\n    at Array.forEach (native)\n    at 
Function._.each._.forEach (/Users/abhiaiyer/.meteor/packages/meteor-
tool/.1.3.4_4.pffcct++os.osx.x86_64+web.browser+web.cordova/mt-
os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)\n    at 
/Users/abhiaiyer/Projects/Workpop-Org/Workpop-
Web/.meteor/local/build/programs/server/boot.js:133:5'  >>> Error

```

Why is this happening? Why is meteorInstall running here? Any help would be appreciated

**Comment by abernix** [comment]
There isn't enough information in this issue to help at the moment.  `meteorInstall` is simply the Meteor internal that handles packages but can show up in various places in stack traces.  Please elaborate on what you've done and what you've tried.

What version of Meteor did you upgrade from? Did you upgrade other packages as well?  How are you using `Bigquery`?  Is it an NPM?  A Atmosphere package?  What happens if you try removing your `...Workpop-Web/.meteor/local/build` and letting Meteor rebuild it?  Can you provide a minimum reproduction git repo showing just this problem?

**Comment by abhiaiyer91** [comment]
Lol. Big query is an empty object in that path. You didn't answer my question, why would this path be meteorInstalled? How does it work in relation to globals made by the app. Also I upgraded from 1.3.2.4 to 1.3.4.4.

Once again, will go through Dev subscription

**Comment by abernix** [comment]
You had two questions and one of them was asking for help in figuring out why it was happening.  However, it's not possible to answer either question based on the snippet you provided.

I did explain that `meteorInstall` handles resolving modules within your project.  It really doesn't point to a problem with `meteorInstall` at all, as it can frequently just be the point where an error is caught.

Do you have `bigquery` in the `dependencies` in your `package.json`?  How are you using `Bigquery` in your project?  Are you `import`-ing it?

If you choose to answer my questions instead of lol-ing, maybe someone can assist further.
