### ISSUE TITLE
[1.4-beta] mattb33:collection-hooks receiving malformed document

### ISSUE THREAD

**Issue by copleykj** [meteor/meteor#7409]
collection.after.insert hooks seem to be getting passed something other than the document. This happens only with the 1.4-beta release track, specifically tested with beta.12-14

``` javascript
Meteor.users.after.insert(function(userId, document){
    console.log(document); //Should be the newly created user document
});
```

Instead of the inserted document, this what the value of the document param gets set to.

```
{ 
    result: { ok: 1, n: 1, opTime: [Object] },
    ops: [ [Object] ],
    insertedCount: 1,
    insertedIds: [ '2W7yfvHZvZnQ5pP9Y' ] },
    services: { password: { bcrypt: '$2a$10$tfbLr1j/5FAdf7NodOyWmeMrlVeirITtsJg96oEhJAGvOdMg94nJW' } },
    username: 'user1',
    emails: [ { address: 'user1@example.com', verified: false } ] 
}
```

**Comment by StorytellerCZ** [comment]
#7218

**Comment by benjamn** [comment]
cc @tmeasday @fabs?

**Comment by tmeasday** [comment]
It's not immediately obvious why (assuming collection hooks monkey-patches `Collection.prototype.insert`, which I *think* is what it's doing). @copleykj can you put together a simple reproduction?

Likely it'll need to be fixed in collection-hooks though

**Comment by copleykj** [comment]
Yes @tmeasday I'll get that done shortly.

@matb33 might also have some insight into this.

**Comment by matb33** [comment]
If inserts are working as expected in 1.4, then it's on me to adapt. I'll take a look.

**Comment by matb33** [comment]
I'm trying to look at this but running `meteor update --release 1.4-beta.14` hangs on `Downloading meteor-tool@1.4.0-beta.14...` (after having downloaded). Left it spinning for about 6 hours, so clearly something isn't working

**Comment by matb33** [comment]
I'm banging my head against the wall trying to run `meteor test-packages ./` with `1.4-beta.14`. Shouldn't `api.versionsFrom('1.4-beta.14')` be sufficient? I instead get a wall of constraint conflicts that don't really make sense. Could I get some guidance?

**Comment by abernix** [comment]
@matb33:

> Left it spinning for about 6 hours, so clearly something isn't working

What OS?  At that point, it probably indicates a problem extracting the tar-ball (which confusingly doesn't have it's own progress message).  Could be space, tmp folder problems, lack of a TTY (e.g. when run in `screen` or `ssh`), permissions, or something else entirely.  If this keeps happening to you, you might need to just reinstall Meteor with `curl https://install.meteor.com/ | sh`.

> Shouldn't `api.versionsFrom('1.4-beta.14')` be sufficient?

**Short answer:** I think you can remove that line completely?   **Long answer:**  I believe `versionsFrom` is meant to pin the versions of **core** packages to a particular Meteor release.  As of Meteor 1.4, packages are no longer pinned to a release (#7004) and if you omit this `versionsFrom`, it should just use the packages that are specified in that projects `.meteor/packages` file, or alternatively, whichever ones _were_ pinned to the release that Meteor is currently running with.

**Comment by matb33** [comment]
@abernix ended up deleting `~/.meteor` and re-installing, that ended up working.

In this case there is no `.meteor` folder, as this is a package and tests are run via `meteor test-packages ./`. All of my development for collection-hooks is done this way. I have a feeling some packages being used by the Tinytest framework depend on versions of packages whose versions haven't been updated for 1.4-beta

**Comment by abernix** [comment]
Ah, right – in that case then the 'alternatively' portion I mentioned applies.  You might try specifying `--release 1.4-beta.14` with your `meteor test-packages` command.  Since there is no `.meteor/release` it's probably trying to use your default `meteor` for your machine, which is probably 1.3.4.4 since Beta releases can't be default since they're not "recommended".  Also, Meteor uses Tinytest internally, so I don't believe that is the problem.

Alternatively, can you show explicit steps on how/where to reproduce this?

**Comment by Nexus7** [comment]
Having the same problem trying to run a 'meteor update --release 1.4-beta.14'... the download just seems to get stuck about 7-10% in... tried removing the .meteor folder from the project but did not make any difference... I have about 10 GB free on the machine (mac osx)

**Comment by tmeasday** [comment]
@abernix @matb33 - The `versionsFrom` stanza does still have the same meaning--it's basically saying "set the minimum (in a semver sense) version of all my core dependencies to be the versions in that release".

I wouldn't expect this release to really be any different in terms of package resolution for apps and packages, assuming you don't change the version numbers that are added to your `.meteor/packages`. 

@matb33 if you are still seeing problems and it's not due to the release thing @abernix mentioned above, can you report it please? I'd love to see any such problems.

**Comment by abernix** [comment]
@Nexus7 This is the wrong issue for your particular problem.  Please see #6960 or search for other related issues (there are several).

**Comment by matb33** [comment]
@tmeasday in this particular case, I'm using `meteor test-packages` so we're dealing with an edge case I think (we don't have `.meteor/packages`).

So I may be misunderstanding, but in my opinion, using `versionsFrom('1.4-beta.14')` should have done the trick, since I don't specify which versions I use (e.g. `api.use('mongo')` etc).

What did work was @abernix's suggestion, i.e. `meteor test-packages ./ --release 1.4-beta.14`. I'll start looking into the actual collection-hooks issue reported here :)

**Comment by matb33** [comment]
@copleykj did you re-type the results of `console.log(document)` manually? It seems you lost the `_id` property. Based on my research so far, it's only the _id property that is affected, and only for `Meteor.users`. Can you double-check that the document is actually:
```
{
  _id: {
    result: {
      ok: 1,
      n: 1,
      opTime: [Object]
    },
    ops: [ [Object] ],
    insertedCount: 1,
    insertedIds: [ '2W7yfvHZvZnQ5pP9Y' ]
  },
  services: { password: { bcrypt: '$2a$10$tfbLr1j/5FAdf7NodOyWmeMrlVeirITtsJg96oEhJAGvOdMg94nJW' } },
  username: 'user1',
  emails: [ { address: 'user1@example.com', verified: false } ]
}
```

**Comment by mitar** [comment]
In #7469 I reported a similar problem. I had a clean 1.4 release installed on my system, and when I was doing `test-packages` it was pulling an older version of `accounts-password` for testing than what comes with 1.4, thus bcrypt compilation was failing on new node. I had to use `api.versionsFrom` inside `onTest` to fix it, but I have never had to do this in the past: https://github.com/peerlibrary/meteor-peerdb/commit/59a7baa242e12a5076e67f5c0ec14bf939465504

So no idea why it was not using simply the latest `accounts-password`. Changing `api.versionsFrom` in `onUse` to 1.4 did not help either.

**Comment by tmeasday** [comment]
@mitar if you don't have `api.versionsFrom` and `api.use` something, the version is not constrained.

In test mode, the constraint solver preferences the lowest possible version of packages ("version gravity"). 

So I'm not sure what you were seeing before but what you are describing doesn't sound surprising to me.

**Comment by lucfranken** [comment]
@tmeasday After reading it twice it makes sense! Yes that logic was not what I expected but it does make sense if you publish a package. Because we use the packages only internally: Did not expect that it would not follow the Meteor the Meteor app version.

It does report very strange things, like loading an older bcrypt version, which caused for us for example: #7469  but which was not expected. We even searched for that version number but it was nowhere to be found.

So for the people who find this here: Update your internal packages to also have the same version. That will solve issues with older versions of packages which you did not include by yourself.

**Comment by copleykj** [comment]
This has been fixed in the collection-hooks package so I'm gonna close this as its no longer relevant.

**Comment by abernix** [comment]
Thanks for the followthrough, @copleykj!
