### ISSUE TITLE
Meteor crash when bundling/building because of acorn (?)

### ISSUE THREAD

**Issue by ForsakenHarmony** [meteor/meteor#7415]
```
$ meteor bundle ..\build
This command has been deprecated in favor of 'meteor build', which allows you to build for multiple platforms and outputs
a directory instead of a single tarball. See 'meteor help build' for more information.


...\Local\.meteor\packages\fourseven_scss\3.8.0_1\plugin.compileScssBatch.os.windows.x86_32\npm\n
ode_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: EPERM, symlink '..\acorn\bin\acorn'
```

**Comment by abernix** [comment]
You didn't specify what version of Windows you were on, nor the version of Meteor you were using.  Very difficult to debug properly with such little detail included in your report.  Please read [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for future reference.

Anyhow, the problem is most likely that `acorn` has binary dependencies which need to be compiled.  In Node, this means using `node-gyp`.  You should ensure that you have all the requirements listed in their instructions for Windows in order to build this NPM: https://github.com/nodejs/node-gyp#installation

Also, unrelated to your bug, but you should start using `meteor build` as the error recommends.

**Comment by ForsakenHarmony** [comment]
I have to run meteor build/bundle with admin to get it not to crash because of symlinks which appeared only now

**Comment by abernix** [comment]
I created a project and built it just fine with `acorn` on Windows 10 Enterprise 64-bit.  Again, what versions of Windows, Meteor and the package are you using?

**Comment by ForsakenHarmony** [comment]
Windows 10 Pro 64-bit
METEOR@1.3.4.4

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

# accounts-password
accounts-google
service-configuration

kadira:flow-router
kadira:blaze-layout

manuel:viewmodel

zodiase:mdl

useraccounts:core
useraccounts:unstyled
```


zodiase:mdl seems to have caused it in the first place, but now even if I remove it and try `meteor build ..\build` it gives me the same error

**Comment by abernix** [comment]
Again, with that exact package list, I am able to build without any problem.

Questions:
* Is Meteor installed on your `C:` drive or somewhere else? 
* Make sure you are using `meteor npm install` and not just `npm install`
* What version of `acorn` are you using?  `meteor npm ls acorn` should give you the answer

**Comment by ForsakenHarmony** [comment]
It's installed on my `C:` drive
I never used `meteor npm install` or `npm install` just ran the first one without any problems, the problem whilst building persists

`meteor npm ls acorn` gives me
```
[..................] - : info using node@v0.10.46

app@ C:\Users\ArmyOfAnarchists\...
`-- (empty)
```

I'm really sorry about this, I just want to resolve this error

**Comment by abernix** [comment]
Are you using `acorn`?  Do you know what it is?  Is there more to that error that you're not including?

**Comment by ForsakenHarmony** [comment]
```
C:\Users\ArmyOfAnarchists\Programming\Web\WebstormProjects\datingwebsite>meteor build ..\build

//the usual stuff that gets hidden automatically via carriage return

C:\Users\ArmyOfAnarchists\AppData\Local\.meteor\packages\fourseven_scss\3.4.3\plugin.compileScssBatch.os.windows.x86_32\npm\nod
e_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: EPERM, symlink '..\acorn\bin\acorn'

C:\Users\ArmyOfAnarchists\Programming\Web\WebstormProjects\datingwebsite>
```

**Comment by abernix** [comment]
> Are you using acorn? Do you know what it is?

I asked these questions because it's not clear if you've added `acorn` to the project yourself or if it's something you need.  Is `acorn` a dependency of another package?  Can you provide the contents of (or a link to) your `package.json` from your project root?  Maybe try running `meteor npm install --save acorn` in your project root.

Really, I'm just stabbing in the dark trying to solve your problem since there's not enough information to work with.  Meteor issues are a place for bugs with the core Meteor software and not for general help configuring your project.  This seems like a misunderstanding or misconfiguration in your project.

The best opportunity to fix this would be if you made a post on the very helpful [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).  You should include all the information I've asked for above but also provide **step by step instructions** on how to produce this from a **brand new** Meteor project starting with `meteor create your-test-project`.  If you show all the steps you're taking, it's more likely someone will be able to find the mistake you're making, or identify if it is truly a bug.  If you can prove it's a bug in Meteor core, this issue can be re-opened.

**Comment by ForsakenHarmony** [comment]
This is my package.json

```
{
  "name": "dating-website",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "build": "meteor build ../build"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0",
    "react": "15.2.1",
    "react-addons-pure-render-mixin": "^15.0.0",
    "react-addons-transition-group": "^15.2.1",
    "react-dom": "15.2.1",
    "react-mounter": "1.2.0",
    "react-tap-event-plugin": "1.0.0"
  },
  "main": "server/entry.js",
  "browser": "client/entry.js",
  "devDependencies": {
    "webpack": "^1.13.0",
    "webpack-hot-middleware": "^2.10.0",
    "url-loader": "^0.5.7",
    "file-loader": "^0.8.5",
    "style-loader": "^0.13.0",
    "css-loader": "^0.23.0",
    "extract-text-webpack-plugin": "^0.9.1",
    "json-loader": "^0.5.4",
    "babel": "^6.3.26",
    "babel-core": "^6.3.26",
    "babel-loader": "^6.2.0",
    "babel-preset-react": "^6.3.13",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-plugin-transform-decorators-legacy": "^1.3.2",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-transform": "^2.0.0",
    "expose-loader": "^0.7.1",
    "react-transform-hmr": "^1.0.1",
    "react-transform-catch-errors": "^1.0.0",
    "redbox-react": "^1.2.0"
  }
}
```

I'll just open cmd with admin, not that big of a deal
