### ISSUE TITLE
DDP.connect on the server doesn't use server name identification

### ISSUE THREAD

**Issue by guns2410** [meteor/meteor#7418]
After updating to 1.4 I get error messages while connecting two Meteor apps via DDP.

Both the servers are on LetsEncrypt SSL and hosted on Galaxy.

```
stream error Network error: wss://example.com/websocket: Hostname/IP doesn't match certificate's altnames: "Host: example.com. is not in the cert's altnames: DNS:www.meteor.com"
```

I did not find these error prior 1.4.

**Comment by abernix** [comment]
Is it possible that the certificates hadn't been matching before however upgrades in Node 4 make the certificate checking more strict?

More questions:
* What version of Meteor were you on before?
* If you downgrade back to that version does the problem go away?
* Is that the exact error message or have you redacted it/changed it in some way?

It might be hard to debug this without further details about the environment, including domains, etc.  Is there any way you can reproduce this with a small app?  I'm happy to create my own SSL certificates and DNS configuration if you can create a test app.

**Comment by guns2410** [comment]
@abernix here is the update:

What version of Meteor were you on before?
**1.4-beta.14**

If you downgrade back to that version does the problem go away?
**Yes. Downgrading to 1.3, the error goes away**

Is that the exact error message or have you redacted it/changed it in some way?
**That is the exact error message. Just chagned my hostname to _example.com_**

The app connects to 4 Meteor servers via DDP and I get the same message for all the DDP connections.

**Comment by abernix** [comment]
Based on your last edit, I'm assuming that the problem is related to my first question which you didn't provide your opinion about:

> Is it possible that the certificates hadn't been matching before however upgrades in Node 4 make the certificate checking more strict?

It sounds possible that the SSL handshake wasn't working entirely properly in the first place but more recent versions of Node are more strict about the certificate names matching.  Can you reproduce this problem locally or only on Galaxy?

What if you set the environment variable:`NODE_DEBUG=tls`?  This should provide some additional output helpful in debugging the problem, however I'm not sure how helpful it will be.

**Comment by guns2410** [comment]
Thanks for the update @abernix.

I did try with NODE_DEBUG=tls and I got the same error message.

```
W20160719-14:33:52.050(5.5)? (STDERR) TLS 7973: secure established
I20160719-14:33:52.052(5.5)? stream error Network error: wss://example.com/websocket: Hostname/IP doesn't match certificate's altnames: "Host: example.com. is not in the cert's altnames: DNS:www.meteor.com"
```

I understand that this is not meteor specific issue and I learned that NODE 4 is strict in validating SSL, but could you suggest something here?

I am closing this issue since it is not meteor related, but would be great if you could help me getting rid of this error message.

**Comment by abernix** [comment]
Can you inspect your certificates (via web-browser, perhaps?) and ensure that they are correctly installed in the correct places?  Alternatively, if you can create super basic reproduction repos that are easy for me to get up and running I'll do my best to deploy them myself and take a look.  `NODE_TLS_REJECT_UNAUTHORIZED` will obviously work, however that does potentially pose a security issue.

**Comment by guns2410** [comment]
@abernix, I am unsure that I will be able to set up a reproduction for this, however, I played around with the DDP Options.

```javascript
let options = {
  npmFayeOptions: {
    tls: {
      checkServerIdentity(serverName, cert) {
        if (cert.subject.CN == 'www.meteor.com' || cert.subject.CN == serverName)
          return undefined;
        else return 'Incorrect server identity';
      },
    },
  },
  ssl: true,
};

let connection = DDP.connect('example.com', options);
```

Looks like the CN is changing to 'www.meteor.com'. Trying to debug in web browser, however, I do not see the CN as 'www.meteor.com' but as the correct server name.

**Comment by abernix** [comment]
If `cert.subject.CN` is coming back as `www.meteor.com`, it's possible that you're encountering the Galaxy load-balancer as opposed to your _actual_ server and thus you're receiving the `www.meteor.com` certificate?   I'm not really familiar with how that is configured.  What is the value of `serverName` in that callback?

If you are hitting the load balanacer, then what you're doing seems reasonable.  Based on [`tls.connect` docs](https://nodejs.org/api/tls.html#tls_tls_connect_port_host_options_callback) and a few other things, it does seem like the `checkServerIdentity` is there so you can provide your own decision making process on what you think should be allowed - while still enforcing valid certificates, but preventing man-in-the-middle attacks.  This [StackOverflow post](https://stackoverflow.com/questions/14262986/node-js-hostname-ip-doesnt-match-certificates-altnames/28071485#28071485) has an okay explanation of why.  Meteor might need to make some recommendations on how to proceed with this in the docs though.

I'm going to reopen this for the time being.  Even though I don't think the bug itself is caused by Meteor, it could use some addressing.  Unfortunately, I still don't have a way to 100% valid that your configuration is valid, but will go on assumption. ;)

**Comment by guns2410** [comment]
The serverName comes back correctly to the server being called.

**Comment by glasser** [comment]
Specifically, www.meteor.com certificate will be served by Galaxy if the client doesn't have [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) enabled. I have no idea why that would be the case in Node, though!

**Comment by glasser** [comment]
OK, I think I've figured this out.  The Faye websocket client used by DDP.connect on the server formerly didn't support SNI.  This was fixed in https://github.com/meteor/meteor/commit/4860f30c41ba3ad9ba34dfeb2696725848160e53 (1.3.0 of ddp-client).

**Comment by hwillson** [comment]
Sounds like this was fixed in https://github.com/meteor/meteor/commit/4860f30c41ba3ad9ba34dfeb2696725848160e53 - closing. Thanks!
