### ISSUE TITLE
Allow passing an array of handlers in eventMap

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#7427]
Consider allowing this:

```
template.events({
  'click .my-link': [
    function(ev) {},
    function(ev) {}
  ]
});
```

Super useful. Especially if you're dealing with user input and you want to run some things on every keypress and some things debounced.

I actually thought this was in, considering https://github.com/meteor/meteor/issues/650 is closed and the PR was merged in. But, alas, no cigar.

**Comment by abernix** [comment]
Thanks for the feature request.  Please consider the [guidelines for feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) and ensure that your feature meets the requirements to provide the best chance of it becoming a part of core.

Those arriving at this issue can show support by up-voting the issue or providing useful input as comments.

**Comment by hwillson** [comment]
I'm not quite sure why this would be needed when you could just call whatever additional functions you want from within the one registered event handler function. So instead of your example, you could just have something like:

```js
const someCommonFunction = (event, instance) => {
  // Do something ...
};

Template.someTemplate.events({
  'click .my-link'(event, instance) {
    someCommonFunction(event, instance);
    // Do something else ...
  },
});
```

Regardless, I'll close this for now due to the low activity and age of this issue. If you're still interested in this being looked at, please open a new issue in the [Blaze repo](https://github.com/meteor/blaze). Thanks for opening this issue originally!
