### ISSUE TITLE
Meteor Skip Installation in Windows 10

### ISSUE THREAD

**Issue by Jose4gg** [meteor/meteor#7444]
This is the last opportunity i give to Meteor, im tired of busy days because errors in new versions of Meteor, since i update yesterday i cannot run meteor. First I received this error: "Cannot find the path specified" But i check my environment variables and were ok. So i decide install Meteor again, but everytime I run the installer, it simply skip the installation process and send me to a "Meteor Installed view" 

I cant install Meteor, I cannot use meteor, this is stupid...

**Comment by joe-recto** [comment]
I think we both have the same or similar problem.
Here is my original post:

Input: meteor --settings settings.json
meteor
meteor create myapp

So I tried these inputs, but I get this error:
The system cannot find the path specified

It's weird. One day Meteor was working all fine and then the next, it just didn't work.

I'm using Meteor 1.3.4.4.

I tried uninstalling Meteor and then reinstalling it, and it still doesn't work.
I also checked environment variables to see if it is included in the path, and it is.

Does anyone know how to fix this?
Would really appreciate it! Thanks!

**Comment by abernix** [comment]
I'm not sure if your current issues will be fixed by a reinstall or not – but hopefully yes!  A lot of changes have been made recently to overcome Windows limitations and hopefully the Meteor tool is improving in this department.  Of course, it won't be without some hiccups.

If you're running the installer on an **already installed** Meteor, it _will_ skip to the end and say it's already installed (since it _is_ actually already installed.  If you actually want to reinstall, do the following:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart!**
 * Yes, even on Windows 10, you'll need to restart your computer (or at least click [the Environment Variables button](https://i.stack.imgur.com/ZeExG.png) in System Properties and press "Ok" on it) since, currently, the Meteor installer doesn't fire off the `WM_SETTINGCHANGE` message. #7431
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Comment by joe-recto** [comment]
Thanks for the advice. I fellow meteor colleague also gave me the same advice, and it seems to be working. 

I ran meteor --version, and it seems to be okay!

Thanks again!

**Comment by tianchuanting** [comment]
I just got a `Cannot find the path specified` error on a win10 machine, after doing a "meteor create". Most likely it's the same issue.

**Comment by abernix** [comment]
Glad to know a re-installation worked for you.

I'm just going to point out that it's very important to restart your computer or log out and in again after installing Meteor due to the modification that is made to the `PATH`.  Alternatively, you can open the Environment Variables dialog from your control panel, and press "Ok".  This will trigger a refresh.  Unfortunately,  until #7431 is resolved, this will be a problem, but that can be tracked in that issue.

I'm going to close this as it doesn't have any particular action items at this time and there have been bugs fixed in the past which have required reinstallation.  Please use my steps above to do so.
