### ISSUE TITLE
[1.4] MongoError: no mongos proxies found in seed list

### ISSUE THREAD

**Issue by guns2410** [meteor/meteor#7450]
After updating to 1.4-rc.1, I am getting MongoError and cannot start app.

**MongoError: no mongos proxies found in seed list**

Here is the error log:

```
W20160721-16:02:00.057(5.5)? (STDERR) /Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-rc.0.11vs7oc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20160721-16:02:00.057(5.5)? (STDERR)           				throw(ex);
W20160721-16:02:00.058(5.5)? (STDERR)           				^
W20160721-16:02:00.247(5.5)? (STDERR) MongoError: no mongos proxies found in seed list
W20160721-16:02:00.248(5.5)? (STDERR)     at Object.Future.wait (/Users/gunjansoni/.meteor/packages/meteor-tool/.1.4.0-rc.0.11vs7oc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20160721-16:02:00.249(5.5)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
W20160721-16:02:00.251(5.5)? (STDERR)     at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:200:33)
W20160721-16:02:00.251(5.5)? (STDERR)     at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
W20160721-16:02:00.253(5.5)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:219:25)
W20160721-16:02:00.254(5.5)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20160721-16:02:00.255(5.5)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20160721-16:02:00.256(5.5)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20160721-16:02:00.257(5.5)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:103:40)
W20160721-16:02:00.257(5.5)? (STDERR)     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
W20160721-16:02:00.257(5.5)? (STDERR)     - - - - -
W20160721-16:02:00.258(5.5)? (STDERR)     at [object Object].<anonymous> (/Users/gunjansoni/.meteor/packages/npm-mongo/.1.5.45-rc.1.1e95ptd++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/mongos.js:304:35)
W20160721-16:02:00.258(5.5)? (STDERR)     at [object Object].g (events.js:260:16)
W20160721-16:02:00.258(5.5)? (STDERR)     at emitOne (events.js:77:13)
W20160721-16:02:00.259(5.5)? (STDERR)     at [object Object].emit (events.js:169:7)
W20160721-16:02:00.260(5.5)? (STDERR)     at Object.cb (/Users/gunjansoni/.meteor/packages/npm-mongo/.1.5.45-rc.1.1e95ptd++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:265:14)
W20160721-16:02:00.260(5.5)? (STDERR)     at /Users/gunjansoni/.meteor/packages/npm-mongo/.1.5.45-rc.1.1e95ptd++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:18
W20160721-16:02:00.261(5.5)? (STDERR)     at authenticateStragglers (/Users/gunjansoni/.meteor/packages/npm-mongo/.1.5.45-rc.1.1e95ptd++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:399:16)
W20160721-16:02:00.261(5.5)? (STDERR)     at [object Object].messageHandler (/Users/gunjansoni/.meteor/packages/npm-mongo/.1.5.45-rc.1.1e95ptd++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:421:5)
W20160721-16:02:00.262(5.5)? (STDERR)     at Socket.<anonymous> (/Users/gunjansoni/.meteor/packages/npm-mongo/.1.5.45-rc.1.1e95ptd++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:294:22)
W20160721-16:02:00.263(5.5)? (STDERR)     at emitOne (events.js:77:13)
```

My MongoDB is hosted on compose and Mongodb version is 3.0.11

_This error was not there before 1.4-rc.1_

**Update:**

```
meteor create test-project --release 1.4-rc.1
meteor
```
_Works fine_

```
meteor add accounts-password
meteor
```
_Fails with the above error_

**Comment by abernix** [comment]
Thanks for reporting this.

I haven't had a chance to confirm or reproduce myself yet, but this sounds like it's occurring due to the upgrade of the Official Node Mongo driver to `2.2.x` within this commit: https://github.com/meteor/meteor/commit/258b14af0c68216506d3ffc6124331fc20a6f676#diff-b83dca6cbd53abdda71985a45ff630adR11.

Related to this issue https://jira.mongodb.org/browse/NODE-764 which refers to this commit: https://github.com/mongodb/node-mongodb-native/commit/96f9b227e7a794dfd6c72bd7d69bbaf97137aac1 where you can see what it's checking.

@guns2410 Apparently there was a bug in the previous versions of the node driver which was allowing behavior that wasn't desired.  Do you have a `replicaSet` query parameter in your `MONGO_URL`?  If so, do you have at least _two_ seed servers in the list?  Could you perhaps provide a **censored** version of your `MONGO_URL` (`XXX` out the username and password)?

It should look something like this:
```
mongodb://user:123456@candidate.11.mongolayer.com:10240,candidate.0.mongolayer.com:10240/mydatabase?replicaSet=set-0123456789&readPreference=primaryPreferred
```

**Comment by guns2410** [comment]
@abernix, Here is my MONGO_URL

```
mongodb://username:password@candidate.65.mongolayer.com:10106,candidate.66.mongolayer.com:10069/database?replicaSet=set-56c46a3aa6a8dd4e270018a3
```

**Comment by abernix** [comment]
@guns2410 Ok, that looks fine.  Also, I just noticed your edit.  I'm assuming the difference is that a core app (before you add `accounts-password`) doesn't actually have a Mongo collection (and thus nothing to connect to) whereas when you add `accounts-password` the `users` database comes into play and Meteor wants to write it somewhere.

**Comment by abernix** [comment]
https://jira.mongodb.org/browse/NODE-772 is also open about this.

My understanding of that issue is that `replicaSet` might need to get set [inside the actual `replSet` options when connecting](https://github.com/meteor/meteor/blob/11833c4e667f54f94d44bb415dbc5ec8ff35bd90/packages/mongo/mongo_driver.js#L133-L134).  Currently, `replSet` is only set on the URL, which based on the docs still sounds like it should be enough.

I don't have an environment available at the moment to test this.

**Comment by guns2410** [comment]
Great! do know a workaround till the time the issue has fixed?

**Comment by guns2410** [comment]
**Update**

seems like removing **MONGO_OPLOG_URL** env variables resolves the error.

Guess the problem is not with **MONGO_URL**, but with **MONGO_OPLOG_URL**

**Comment by abernix** [comment]
I have no work-around at this time.

I don't have a paid Compose.io server to try this with but I created an environment to test this locally and have not not been able to reproduce it using Meteor 1.4-rc.1 (with the 2.2 Node driver) and TWO Mongo 3.2.6 servers setup as a replicaSet

Is it possible that you need to pass `&ssl=true` on the end of your `MONGO_URL`? (as in, your Mongo server only accepts SSL?)

**Comment by abernix** [comment]
Good timing. :wink:

What's your `MONGO_OPLOG_URL` look like then? (Again, redacted/censored!)

I'm curious what happens if you add the same `&replicaSet=set-0123456789` from your `MONGO_URL` on the end of it.

**Comment by guns2410** [comment]
Yes, Guess so... 😄 

Here is my MONGO_URL:
```
mongodb://username:password@candidate.65.mongolayer.com:10106,candidate.66.mongolayer.com:10069/database?replicaSet=set-56c46a3aa6a8dd4e270018a3
```

And the MONGO_OPLOPG_URL:
```
mongodb://username:password@candidate.65.mongolayer.com:10106,candidate.66.mongolayer.com:10069/local?authSource=database&replicaSet=set-56c46a3aa6a8dd4e270018a3
```

**Comment by abernix** [comment]
Unfortunately, still no luck.  Someone with Compose.IO will have to take a look further as I'm unable at the moment.

**Comment by guns2410** [comment]
Resolved with 1.4-rc.2 😄 
Thanks @abernix!

**Comment by guns2410** [comment]
Looks like the issue was with compose.io since I do not see any significant chagnes in npm-mongo package between 1.4-rc.1 and 1.4-rc.2

**Comment by abernix** [comment]
This must have been some sort of temporary issue with`compose.io` as there was [certainly nothing that changed in `rc.2`](https://github.com/meteor/meteor/compare/release/METEOR@1.4-rc.1...release/METEOR@1.4-rc.2) that could have fixed this!  But glad to hear it's working now! :smile:

**Comment by joncursi** [comment]
This is happening for me in the new 1.4. Check out https://github.com/meteor/meteor/issues/7471

**Comment by abernix** [comment]
Re-opened due to similar experiences by @patrickml and @joncursi.

**If you're experiencing this problem**, please indicate whether you are failing to setting `replicaSet` in your `MONGO_URL`.  As indicated in the JIRA tickets above, this is mandatory to ensure you are connecting to the correct replica set and is considered a bug in previous versions of the Node Mongo driver.

**Comment by dr-dimitru** [comment]
From the MongoDB native driver docs:

> Note that for replicasets the replicaSet query parameter is required in the 2.0 driver

So, everyone who uses ReplicaSet __must__ append `replicaSet` get parameter  with name of ReplicaSet to the connection string, example:

```
mongodb://<user>:<password>@<PUBLIC_IP>:<PORT>,<PUBLIC_IP>:<PORT>,<PUBLIC_IP>:<PORT>/local?replicaSet=<NAME_OF_REPLICA_SET>
```

IMHO it should be added to the docs and changelong.

**Comment by wursttheke** [comment]
Just had the same situation on my ubuntu box. Adding the `replicaSet` parameter to `MONGO_URL` and `MONGO_OPLOPG_URL` environment variables fixed the problem. 🎉

**Comment by patrickml** [comment]
adding `replicaSet` fixed the issue. For those who don't know how to get the replica set name if you use `mongod` to access your db and run `rs.config()` you will get a JOSN doc back that has `_id` use the `_id` as your `?replicaSet=<_id>`

**Comment by dr-dimitru** [comment]
Although my own comment below fixed my issue on VPS and dedicated servers, on Heroku, now I'm expecting:
```
MongoError: no primary found in replicaset
   at Object.Future.wait (/app/programs/server/node_modules/fibers/future.js:449:15)
   at new MongoConnection (packages/mongo/mongo_driver.js:216:27)
   at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
```

Any idea around this, folks?

**Comment by markoshust** [comment]
For those coming to this ticket, I can confirm that the 'issue' seems to live in the fact that if you use a replica set in Meteor <=1.3, `replicaSet` param was not needed in `MONGO_OPLOG_URL`, but it is required in Meteor 1.4.

I think this ticket should be closed :)

**Comment by WayneUong** [comment]
I've added the `replicaSet` param to `MONGO_OPLOG_URL` and I'm still encountering this error:
```
    "MONGO_URL": "mongodb://[user]:[password]@SG-Keela-[number].servers.mongodirector.com:[port],SG-Keela-[number].servers.mongodirector.com:[port]/[database]?replicaSet=RS-Keela-0"
    "MONGO_OPLOG_URL": "mongodb://[oplog_user]:[password]@SG-Keela-[number].servers.mongodirector.com:[port],SG-Keela-[number].servers.mongodirector.com:[port]/local?authSource=admin&replicaSet=RS-Keela-0"
```

**Comment by tmeasday** [comment]
Hey all, I added some notes about `MONGO_OPLOG_URL` and replicaSets to

 - the docs: https://github.com/meteor/docs/commit/cc3f8fe99b3db72c21ea2c0e8d7e574bca860ec6

 - the guide: https://github.com/meteor/guide/commit/f94532a9de0e073ce3cbaa7cd071b13bbeeb7e78

 - the changelog: https://github.com/meteor/meteor/blob/devel/History.md#v14

Can folks let me know if that sounds right?

**Comment by tmeasday** [comment]
@WayneUong - what error are you getting?

**Comment by abernix** [comment]
@tmeasday LGTM.

**Comment by Jogibaer1963** [comment]
Hello,
I changed my oplog as mentioned in the meteor/docs@cc3f8fe to:

MONGO_OPLOG_URL: 
mongodb://itsMe:passWord@candidate.36.mongolayer.com:10976,candidate.37.mongolayer.com:10986/local?authSource=sandBox_2&replicaSet=set-563d1d6efb36a6be4e0002c8 

MONGO_URL: 
mongodb://itsMe:passWord@candidate.36.mongolayer.com:10976,candidate.37.mongolayer.com:10986/sandBox_2?replicaSet=set-563d1d6efb36a6be4e0002c8 




But still no luck with connecting to the datacenter. Without oplog it works just fine. Little bit lost somehow :)

MongoError: no mongos proxies found in seed list

**Comment by patrickml** [comment]
@tmeasday seems right to me.

**Comment by abernix** [comment]
@Jogibaer1963 I would make sure you actually have oplog access with Compose.io and possibly this article there as well: https://www.compose.com/articles/connecting-to-the-oplog-on-the-new-mongodb/ (You can ignore the part about Meteor not supporting Mongo 3.2 anymore :wink:).

Alternatively, maybe Compose.io support might have some suggestions or insight?  In general, I believe this is working properly now as confirmed by those above.

**Comment by Jogibaer1963** [comment]
Thank you for your reply, but as I mentioned above, I found the issue. 
I updated the evniromental Var in the System but i did not update my App with the new env set.
In my case the issue was sitting in front of the Computer :)
Thanks

**Comment by eminaz** [comment]
@abernix thanks, I had this error using Compose.io, fixed by adding the same &replicaSet=xxx from my MONGO_URL on the end of my MONGO_OPLOG_URL

**Comment by LWCoder** [comment]
I had this same issue after upgrading to Meteor 1.4.0.1 but I am self hosted MongoDB and not using Compose.io. As mentioned above, adding the same &replicaSet=xxx from my MONGO_URL on the end of my MONGO_OPLOG_URL fixed the issue.

**Comment by kylemclaren** [comment]
Hey folks, Compose employee here, just want to add some clarification on this issue. We currently have 2 different deployment types, **MongoDB Classic** and our **new MongoDB** offering, sometimes referred to as MongoDB+.

MongoDB Classic is a standard replica set (ie. you connect directly to the data members in the connection string). The new MongoDB offering is essentially a sharded deployment with 2 routers (that you connect to in your connection string) and a single replica set (implemented as a shard) that the routers connect to.

Since Classic is an actual replica set, you will need to add the `replicaSet` parameter that was previously not required with Meteor. This is due to the Node driver upgrade. The new offering is a sharded setup and not a true replica set (despite the shard being implemented as a replica set) so it **does not** require the `replicaSet` parameter and in fact, Meteor will throw an error if you add it to your connection strings.


We encourage everyone currently running with a Classic deployment to upgrade to the newer deployment type and take advantage of SSL, the WiredTiger storage engine, MongoDB 3.2 and many other great features and add-ons not available with Classic.

Please feel free to submit a ticket to support@compose.io if you have any more questions about this.

**Comment by austinkettner** [comment]
@kylemclaren Was emailing support a few minutes back, maybe that's you? =D

How do we know if we are running MongoDB classic or MongoDB+, particularly if we are using a Heroku Add-on? The storage engine is set as 3.x

**Comment by kylemclaren** [comment]
@austinkettner the Heroku add-on uses the MongoDB Classic platform (which is now considered to be in it's legacy phase). You can upgrade to a maximum of MongoDB v3.0.11 on that platform and it utilizes the MMAPv1 storage engine. (Note, storage engine type will have zero impact on your connection to the database)

**Comment by austinkettner** [comment]
@kylemclaren Thanks for the clarification. I believe something is a still off regarding Compose specifically. We are running a mLab instance in develop with no connection string replicateset defined, meaning due to your above comment, the only thing need in staging (where we use Compose) is a replicates defined in the connection URL due to the heroic add-on being 'classic'.

Yet, even with this change I get the error of `MongoError: no mongos proxies found in seed list`, trying to add a OPLANG env var + string yields not change, adding the replicaset to the oplang url has not change, removing the replicaset to the MongoHQ env var connection url doesn't change anything either.

Thoughts?

**Comment by kylemclaren** [comment]
@austinkettner can you submit a new ticket to support@compose.io or reply to your existing ticket? We can handle it there. Thanks!

**Comment by austinkettner** [comment]
Absolutely, thanks @kylemclaren

To everyone else in this thread, I will update this ticket if I find out the proper config with regards to Heroku Addons and Meteor 1.4!

**Comment by abernix** [comment]
@kylemclaren Thanks very much for your input on the matter.  Great to understand the difference in how the sharding on Compose+ behaves with the new driver as well.

I suppose from a support standpoint you (and others) should be aware of #7455 as it has recommendations for Mongo SSL configuration (with further details in the forums link).  Nothing set in stone on that at the moment, but there's a work around that should have longevity.  If you become aware of any Meteor related issues with that integration, do drop an issue – though I'm certain that it is possible to get up with the current setup, some things might not be ideal.

**Comment by t3db0t** [comment]
All, I'm also on Galaxy and Compose, and hit this error but none of the advice has solved it yet.  I tried adding the replicaset param to the oplog url, but that didn't help.  I tried upgrading the compose mongodb version to 3.0.something (no idea what version it was previously on), and updating my `MONGO_URL`, but I'm STILL getting the same `MongoError: no mongos proxies found in seed list` error.  I've re-read this entire thread twice and I can't figure out what I'm missing.  I will also open a Compose ticket, but I think it's on my end?

**Comment by austinkettner** [comment]
@t3db0t I have yet to report this to Compose as I am still trying to figure out why, but I copied my data to a similar mLab DB (MMAPv1 driver, 1GB Cluster) and it worked flawlessly no finagling, I truly think it has something to do with Compose but still debugging before saying anything negative about Compose as I actually love their Admin Portal immensely compared to mLab.

**Comment by t3db0t** [comment]
Any more info on this? I'm on Compose mongodb "Classic" v3.0.11, and I added `?replicaSet=` to my oplog URL, but I'm still getting the error.  Is there anything else I can try? @austinkettner any more thoughts?

**Comment by t3db0t** [comment]
I just confirmed that with my current setup (Meteor 1.4.0.1, Compose MongoDB Classic v3.0.11), the ONLY way I can avoid this error is to completely omit `MONGO_OPLOG_URL`.  Any advice?  I'm not sure of what else I can even try.

**Comment by dr-dimitru** [comment]
Hi @t3db0t ,
Take a look on [this thread](https://github.com/meteor/meteor/issues/7492)
And take a look on the *Update* section of [this tutorial](https://veliovgroup.com/article/2qsjtNf8NSB9XxZDh/mongodb-replica-set-with-oplog) at the very bottom of article.

**Comment by austinkettner** [comment]
@t3db0t My only suggestion is switching to mLab, I can't find the specific reason why but I went through everything you did and every possible configuration with no luck and then switching to mLab (same driver of MMAPv1, same Mongo version) made it work without a single issue.

**Comment by kylemclaren** [comment]
@t3db0t As mentioned in your latest ticket with Compose support, the `MONGO_OPLOG_URL` you were using was incorrect. We have instances of Meteor 1.4 running well against both MongoDB Classic and the new MongoDB deployments.

The connection URI's are extremely sensitive and precise things so it's a good idea to comb through them and make sure there is no unnecessary repetition or formatting mistakes.  If you're having trouble, please reach out to support@compose.io so that we can help you.

**Comment by t3db0t** [comment]
@kylemclaren @austinkettner @dr-dimitru Yes, that was it—embarrassed that it was a typo after all.  Apologies and thanks!

**Comment by jancurn** [comment]
Just one little hint for anyone wondering why oplog tailing silently stops working after upgrading to Meteor 1.4 and adding replicaSet to MONGO_OPLOG_URL as described above: make sure you're using double quotes in your upstart configuration file, e.g.:

> `MONGO_OPLOG_URL="mongodb://user:password@candidate.xx.mongolayer.com:10078,candidate.yy.mongolayer.com:10567/local?authSource=db&replicaSet=XXX"`

instead of 
> `MONGO_OPLOG_URL=mongodb://user:password@candidate.xx.mongolayer.com:10078,candidate.yy.mongolayer.com:10567/local?authSource=db&replicaSet=XXX`

because bash interprets the newly added '&' character in a special way and Meteor silently fails to tail the oplog, without any warning...

**Comment by rjakobsson** [comment]
I'm getting the ```MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name
``` error when adding the MONGO_OPLOG_URL to my config. Have tried the double quotes, but didn't make a difference. Any other ideas? Running Meteor 1.4.1.1.

**Comment by dr-dimitru** [comment]
@rjakobsson do you set `?replicaSet=name` on `MONGO_OPLOG_URL` and `MONGO_URL`?

**Comment by rjakobsson** [comment]
@dr-dimitru yes, here's my connection env vars:
```  MONGO_URL=mongodb://user:password@lamppost.16.mongolayer.com:10307,lamppost.17.mongolayer.com:10296/my-db?replicaSet=set-56675da844ac25c2f400070a

MONGO_OPLOG_URL=mongodb://user:password@lamppost.16.mongolayer.com:10307,lamppost.17.mongolayer.com:10296/local?authSource=my-db?replicaSet=set-56675da844ac25c2f400070a 
```

**Comment by dr-dimitru** [comment]
Have you seen [this tutorial](https://veliovgroup.com/article/2qsjtNf8NSB9XxZDh/mongodb-replica-set-with-oplog)? There is important update at the very bottom. Make sure everything is properly set

**Comment by t3db0t** [comment]
@rjakobsson You've made the same tiny mistake I also made: only the first parameter uses `?`, subsequent ones use `&`

**Comment by dr-dimitru** [comment]
@rjakobsson @t3db0t is right you're using `?` twice

**Comment by kylemclaren** [comment]
Yep @t3db0t you're right... well spotted!

**Comment by rjakobsson** [comment]
@t3db0t @dr-dimitru @kylemclaren  hahaaa :D thanks!! it works! also required me to set `authSource` on my `MONGO_URL`.

**Comment by timbrandin** [comment]
This is still an issue for hosting on an internal VPN with hosts alias et al, suggest you upgrade the mongo driver to 2.2.1 which relaxes the requirement for correct anything.
https://jira.mongodb.org/browse/NODE-746
