### ISSUE TITLE
[>1.3.3] can not reuse app npm deps in build plugin

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#7451]
To make things short I was expecting that this https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies would also work in build plugins.
It seems it does not and in my particular case it is very problematic.
Whether this is an issue is probably my subjective feeling but I was hoping not to duplicate a lot of stuff because I need to use `asar, extfs, shelljs, babel-core` (around 20mb in size) which I already have as app's deps.
If this is something hard to do I would be very thankful for any ideas on how to avoid duplicating these deps.

Repro here https://github.com/wojtkowiak/meteor-reusing-npm-in-build-plugin
```
meteor npm install
meteor
```
You will get ` error: Can't load npm module 'asar' from packages/modules-runtime.js. Check your Npm.depends().` and of course I have `asar` in `package.json`.

**Comment by nathantreid** [comment]
You can use [app-module-path](https://www.npmjs.com/package/app-module-path)  to allow your build plugin to access the app's npm modules:
``` js
import appModulePath from 'app-module-path';
appModulePath.addPath(process.cwd() + '/node_modules/');
```

**Comment by benjamn** [comment]
Please don't use `app-module-path`, as it works by monkey-patching Node's `Module._nodeModulePaths` (see [here](https://github.com/patrick-steele-idem/app-module-path-node/blob/8c7a4eb1b3ed86298a979eea96426ccf8065876b/lib/index.js#L7)).

A better solution is to call `file.require("asar")` in `processFilesForTarget`, similar to the way you're calling the `getArch` method [here](https://github.com/wojtkowiak/meteor-reusing-npm-in-build-plugin/blob/dbb91d852621142c955f1360909788dad5a8dd2c/packages/bundler/src/bundler.js#L17). Note that calling `file.require("asar")` will import the `asar` package from a `node_modules` directory relative to the given file, and it will not attempt to import from the app's `node_modules` directory unless that file is part of the app.

Build plugins are built as standalone programs before the rest of the build process runs, because they modify the behavior of the rest of the build process, so there is unfortunately no opportunity for them to benefit from peer dependencies installed in the app.

**Comment by benjamn** [comment]
Also note that `files.require` was a new feature in Meteor 1.3.3, so it won't work in older apps.

**Comment by wojtkowiak** [comment]
Oh my I thought I already responded here weeks ago. Sorry for that.
@benjamn the approach with `file.require` actually fits very well into what I am trying to do as by chance I am actually compiling file that resides in the root path of the Meteor app, so I can access everything I want from `node_modules`. I am very happy that such a mechanism exists as it will save a lot time and resources in my project!
Seems this is not documented anywhere. If you want I can add a PR to the `docs` - let me know.

**Comment by abernix** [comment]
@wojtkowiak Pull-requests for docs (so long as it's not too edge-case) are always welcomed so please feel free to open that with the `docs` repo wherever you feel necessary.

**Comment by wojtkowiak** [comment]
@abernix that is exactly why I've asked :wink: as this actually felt a little edge-case'y to me, so I wanted to be sure you want it published in the docs.
So if it is ok, I'll do the PR later this week.

**Comment by abernix** [comment]
I think it's appropriate so long as it's in the section on writing packages. 😸
