### ISSUE TITLE
aws ebs doesn't support meteor json env variables

### ISSUE THREAD

**Issue by Zeioth** [meteor/meteor#7458]
This is making people use workarounds to solve the problem:
http://stackoverflow.com/questions/34761577/how-to-config-meteor-on-aws-ebs-using-meteor-settings-environment-variable/38534784#3853478

**Comment by abernix** [comment]
If what you're saying (and the StackOverflow you linked to) is in-fact the case, that would be an issue that needs to be taken up with Amazon as there is absolutely nothing incorrect about using properly escaped JSON in an environment variable.

I'm guessing this is a only problem with trying to configure this through the GUI though because I have setup Meteor using EB before without using those (very hacky) work-arounds.  You can use an [`.ebextensions/environment.config`](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html) file in the root of your project to define whatever variables you'd like.   Additionally, there are several other ways you can also set environment variables by specifying your own [`docker-compose` settings in a task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment), using the EB CLI to `eb setenv FOO=bar`, etc.

I would honestly ignore all the other recommendations in the StackOverflow link you posted as they are again, IMHO, very hacky.  There are correct ways of setting it up Meteor+EB (though frankly, I personally found their load balancer incapable of properly routing WebSockets).  For the environment variable stuff, maybe check [this SO post](https://stackoverflow.com/questions/11211007/how-do-you-pass-custom-environment-variable-on-amazon-elastic-beanstalk-aws-ebs/14491294#14491294) instead of the one you were reading.

Closing this issue as setting up AWS EB is out of the scope of Meteor Issues.  I highly recommend checking out the Amazon EBS forums – they are quite helpful.

**Comment by Zeioth** [comment]
I only have one question. When I run 'meteor --build', is the 'environment.config' file exposed to the client?

**Comment by Zeioth** [comment]
I've though about a secure a less 'hacky' way to achieve it. Is this the meteor way?
http://stackoverflow.com/a/38580848/2010764

**Comment by abernix** [comment]
`.ebextensions/**` files will not be served by Meteor, if that's what you're asking.  You are welcome to implement things however you'd like, but it's generally most important to ensure that your credentials never make it into version control.  If your SO link works for you, then that's fine.

The "Meteor way" (as in, the way it is intended/built/documented) is using the `METEOR_SETTINGS` environment variable with a JSON object.  Your need to get this working properly with AWS EB is something you will need to resolve with AWS EB.  I assure you it is possible and I provided some links already on how to do this with AWS, including a suggestion to visit the [AWS EB forums](https://forums.aws.amazon.com/forum.jspa?forumID=86) for additional help.  This type of configuration is no different than deploying _any_ Elastic Beanstalk application and there are a lot of resources explaining how to do it without modifying your Meteor code.
