### ISSUE TITLE
Upgrading node to 4.4.7 LTS

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7460]
Since Node 4.4.7 is long term supported version, is there a plan to upgrade the bundled node in meteor from 0.10 to 4.4.7 ?

**Comment by aks0020** [comment]
Already implemented in meteor 1.4
See this:
https://github.com/meteor/meteor/blob/release-1.4/History.md

**Comment by c9s** [comment]
Can we also do that on 1.3 ?

**Comment by aks0020** [comment]
No but 1.4 is already in RC so you can try that,  it also supports MongoDB
3.2

On 23 Jul 2016 6:30 pm, "Yo-An Lin" <notifications@github.com> wrote:

Can we also do that on 1.3 ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/meteor/meteor/issues/7460#issuecomment-234717000>, or mute
the thread

**Comment by benjamn** [comment]
See https://github.com/meteor/meteor/pull/7218.

**Comment by c9s** [comment]
@benjamn Thanks
