### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by countcain** [meteor/meteor#7463]
I have a legacy meteor 1.2.1 project. After I upgrade my meteor cli to 1.3, problems occurred!!

<img width="1696" alt="screen shot 2016-07-23 at 11 05 30 am" src="https://cloud.githubusercontent.com/assets/1751150/17078603/66049fb6-50c5-11e6-8c4b-224c5fa49676.png">

I don't know how to debug this. Cannot track exactly which file is related to this **module is not defined** error.

>
Btw
I really regret using meteor. I spent about 70% of my dev time to figure out how to fix various bugs of meteor, issues occurred in deploying, developing, plugins installing, odd performance. Only 30%  of my time is real work. Really sad. I am rewriting the whole project using other low coupling libraries .

**Comment by countcain** [comment]
As for this bug, I wonder is there any way to know the exactly code block that cause the error

**Comment by benjamn** [comment]
Um, your screenshot cut off the most useful information… but my guess is that you need to run `meteor add ecmascript` which implies the `modules` package, which is what provides the `module` variable. The `ecmascript` package has been installed by default for all new apps since 1.2, so I'm somewhat surprised you were not already using it.

Once you add the `ecmascript` package, you can put your ES2015 code in `.js` files rather than `.es6` files, and at some point you should be able to stop using whatever compiler plugin is compiling those `.es6` files (once you've converted everything to `.js` files).

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
