### ISSUE TITLE
build tool optimization: merge ignoreFiles pattern

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7482]
This is related to #6058

Right now you can see the pattern of ignoreFiles are like 10. so the file finder has to check the filename for 10 times in the worst case.

If we have N = 10,000 which is the number of files, then we need to match 10,000 \* 10 times, and this causes the matching really slow.

The benefit of merging the patterns is, V8's regexp engine will optimize the pattern, so it will be much faster

**Comment by mitar** [comment]
Have you measured that there is really a speed improvement or is this a speculation?

**Comment by c9s** [comment]
yes, it takes about 1200ms to scan all the files in the repository.

**Comment by mitar** [comment]
So what is time before and after this change?

**Comment by c9s** [comment]
after the modifications, it only takes about 190~210ms to scan the same
files.

Mitar <notifications@github.com> 於 2016年8月3日 星期三寫道：

**Comment by abernix** [comment]
@c9s Thanks for submitting the PR.  I know the regex changes are simple and I can imagine how this _could_ improve the speed but can you please provide a test repo so that whoever is responsible for reviewing this can see the results _you_ are seeing (versus taking your word for it) and how they were achieved (i.e. under what circumstances: number of files in project, etc.).

**Comment by hwillson** [comment]
Closing as these changes were implemented in PR #7835 and merged. Thanks @c9s and @sebakerckhof!
