### ISSUE TITLE
EACCESS error while updating to 1.4

### ISSUE THREAD

**Issue by Fen747** [meteor/meteor#7488]
Hi folks,

I've updated meteor to  1.4, [installed python 2.7](http://askubuntu.com/questions/101591/how-do-i-install-python-2-7-2-on-ubuntu), as well as the [GNU C compiler](https://help.ubuntu.com/community/InstallingCompilers).

I'm having some trouble using `meteor update`, where I get several errors looking like [this](http://pastebin.com/qg9GLU5M) (pastebin).

(BTW, no .log file is available as described in the logs)

At first attempt, I had the same problem with fourseven:scss, so I removed it in order to re-add it after the meteor update. Then I got stucked in the 1.4 [infinite download issue](https://github.com/meteor/meteor/issues/7473) (2 hours, 2mB/s, great perfs computer), that I solved by fully reinstalling Meteor again.

And now I am stuck here, and I still haven't found a solution.

Anyone else having this problem ? Any clue about how I could solve this ?

Thanks you

**Comment by abernix** [comment]
The `EACCESS` error in your pastebin indicates that the problem is with permissions.  This is very likely caused by you using both the root user and your own user to access the same project.  You really should consider using a single, non-root user to develop with.

If you have Meteor already installed on your machine, I would recommend removing the ~/.meteor of your non-root user and letting Meteor re-build that directory and then never using the root user to work with your project again.

**Comment by Fen747** [comment]
Well, I have removed the .meteor from my  user home directory, exited the sudo mode, went to my app folder and startedit. It got indefenitely stucked on "Downloading meteor-tools@1.3.5.1", after it reached the 100% downloading the meteor distrib. 3 hours later, I was still stucked here.

Then I did : 

> sudo rm -rf /root/.meteor
> sudo rm -rf /home/user/.meteor
> sudo -i
> cd /root/
> meteor (it correctly installed it in 5 minutes)

And there, it printed me some compiling errors due to a bad type cast in my app. So I corrected my code, it automatically rebuilded .... and displayed the same error, again and again, even when I deleted the file where it told me there were an error, it kept rebuilding and displaying the same message, which means it correctly detected the file change, but compiled from some other file that was not updated when I saved my changes (using atom). I retried the same process, but removing the `app_folder/.meteor/local` before (re)starting the app, it didn't changed a thing.

So I deleted everything (again), exited the sudo mode, cloned the last stable version of my app from git, runned the app using `meteor`, and now I am stucked again (with the user account), downloading forever the meteor tool 1.3.5.1.....

It's getting very annoying, and costly.... :/

**Comment by DerekTBrown** [comment]
Try the following:
1) Remove the ~/.meteor and /root/.meteor folders
2) Remove the project/.meteor/local folder and the symlink at project/.meteor/dev_bundle
3) Make sure that the ownership of everything in the project/ folder is to the current user (`chown -R ./ <username>`)
4) Restart

**Comment by mitar** [comment]
This was also reported in this comment: https://github.com/meteor/meteor/issues/7469#issuecomment-235959413, with the same package.

@jwentwistle: I think this is the issue you are looking for your problem.

**Comment by mitar** [comment]
In general, running Meteor under sudo have often bring issues to me. The issue is that once you start doing that, then you have in the future problems because non-sudo version cannot change files anymore. In general you do not have to run Meteor under sudo and you will then also not have permissions issue. The approach that you use sudo to fix your permissions issues in fact just make things more problematic. Just find why it cannot write as normal user and make sure it has normal user's permissions on files.
