### ISSUE TITLE
Very high CPU usage on 1.3.5.1 when running `meteor`

### ISSUE THREAD

**Issue by scharf** [meteor/meteor#7491]
On my mac, when I start `meteor`, node takes 175% CPU and my laptop heats up. The same happens for a coworker too. 

We came to the conclusion, that it may have to do with automatic download of some meteor tools.

_Update:_

The issue appears to be that running Meteor projects that use a version of Meteor less than 1.4 with the 1.4 Meteor tool results in extremely high CPU use. This impacts most users as the 1.4 tool is automatically downloaded and run now that it's been released (regardless of whether users are ready to update to 1.4).

--- 

NOTE: There is a workaround for this issue, as outlined by @abernix : https://github.com/meteor/meteor/issues/7491#issuecomment-235655623

SECOND NOTE: this is fixed by 1.4.0.1. You just need to ensure you have that version on your machine. The download should happen automatically, but if not (check by running `meteor --version` **OUTSIDE** of an app), grab it with `meteor update` outside of an app.

**Comment by scharf** [comment]
After I upgrade to meteor `1.4` the problem is gone. But I should be able to continue working with `1.3.5.1`..

**Comment by benjamn** [comment]
And you can continue working with 1.3.5.1! Any app whose `.meteor/release` file has `METEOR@1.3.5.1` in it will automatically use the older version of the tool. This is a special feature of Meteor that you won't find in many (any?) other framework.

**Comment by scharf** [comment]
...sure I can use `1.3.5.1`, but meteor did something so that the meteor watch process kills my laptop (it's quite hot in my office and having a a high load all the time made my laptop stop working because of overheating).

But `1.4` seems pretty stable already (we usually wait for the `x.x.1` release ;-)

**Comment by billyvg** [comment]
We are also having the same issues using release 1.3.5.1 - meteor dev server runs at 100% CPU with this release, but it seems to be fine at 1.4.

Tried `reset` and reinstall meteor to no avail.

**Comment by marcuscarr** [comment]
I'm running into this problem, too, on 1.2.1.

@scharf @billyvg - Are you using CollectionFS? Kadira showed a lot of Mongo activity, and `db.system.profile` shows a lot of queries to the `cfs.<myFileCollection>.filerecords` collections.

**Comment by scharf** [comment]
I tried another (much simpler) app that connects to the same database -- there I don't see the problem.

**Comment by marcuscarr** [comment]
I commented out all the CFS code and Node is still running like crazy. Guess that was a red herring.

**Comment by scharf** [comment]
I tried to debug/profile the meteor node process, but I got this:

```
Your Node version (v0.10.46) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to v0.11.13 or newer to get full support.
```

When I break the running process, I end up in this file: https://github.com/meteor/meteor/blob/master/tools/index.js but I have no idea that is relevant, because there is no real stacktrace....

**Comment by djules75** [comment]
I have the exact same problem with 1.3.5.1 and CPU usage is stuck at 175% on the node process. Problem is gone when updating to 1.4.

I'm getting the problem even with a simple barebones app created with meteor create.
Same problem with 1.3.2.4: meteor create <app> --release=1.3.2.4 => 175% cpu usage.

This happens only in development, not in production. I'm on Os X El Capitan.

If there is anyway to help you debug the problem please let me know.

**Comment by marcuscarr** [comment]
Looks to me like the solution is for Meteor to revoke the update until they fix this. :grin:

**Comment by pashka4281** [comment]
same stuff here. Having 1.2.1 app and 1.4 installed in the system makes 1.2.1 app eat 178% of my cpu (mb pro, el capitan). But if I only install 1.2.1 like this (`curl https://install.meteor.com/?release=1.2.1 | sh`) than it works fine. This is a production running app and upgrading to 1.4 isn't on our agenda (at least not now) so this causes an annoying issue.

**Comment by pashka4281** [comment]
It's getting even worse because meteor somehow manages to silently download 1.4 in the background and the whole story begins over again: `removing meteor => installing 1.2.1 => hoping that it won't download 1.4 behind the scenes`

**Comment by scharf** [comment]
I have had this before: I really wonder why meteor changes the existing environment when a new version comes out. I would expect that the silent download of a new version does not influence the existing version.

**Comment by apendua** [comment]
Is it possible that this is a Node 4.x issue?

**Comment by berkaey** [comment]
+1 mine is gone too after update to 1.4. it was happening all of my meteor apps with 1.3.2.4 and it just start today. yesterday same app was working fine.

**Comment by scharf** [comment]
I think the problem is, that suddenly meteor 1.3.5.1 uses node v4.4.7:

```
$ meteor --version
Meteor 1.3.5.1
$ meteor node --version
v4.4.7
```

My guess is that this may be the cause of the problem.

**Comment by pashka4281** [comment]
@scharf could be the case. This is definitely not something app-specific since I see the same behaviour on a new empty app

**Comment by abernix** [comment]
_I am able to reproduce this problem, but have no solution at the moment._

@scharf What directory are you running that command in?  It will behave different when run within a project directory versus outside a project directory but it's strange that your versions are not properly matched in that output.

Meteor 1.4 (the tool) _should_ still be running 1.3.5.1 apps using the 1.3.5.1 dev_bundle on Node 0.10.x.

**Comment by scharf** [comment]
I does behave differently: when I am outside the project, I get

```
$ meteor --version
Meteor 1.4
$ meteor node --version
v4.4.7
``` 

inside the project, the meteor version is correct, but the node version is wrong:

```
$ meteor --version
Meteor 1.3.5.1
$ meteor node --version
v4.4.7
```

**Comment by abernix** [comment]
@scharf Interesting.  I'm still able to reproduce the problem but my project is definitely using the correct `node`.  Ok – questions!

While your project is running – Can you provide the output of following commands when executed from another shell in your project root?:
* `echo process.version | meteor shell`
* `cat .meteor/release`
* `ls -la .meteor/local/dev_bundle .meteor/dev_bundle ~/.meteor/meteor ~/.meteor/packages/meteor-tool`

**Comment by pashka4281** [comment]
@abernix 
1. meteor shell hangs on any operation so can't really tell the output of this `echo process.version | meteor shell`
![Alt text](https://monosnap.com/file/1SD3oo9FUfmLcz9viwkwhIuoyyHJXp.png)

2. `cat .meteor/release` => METEOR@1.2.1

3.
```
➜  foo-bar-app git:(master) ls -la .meteor/local/dev_bundle .meteor/dev_bundle ~/.meteor/meteor ~/.meteor/packages/meteor-tool
ls: .meteor/dev_bundle: No such file or directory
ls: .meteor/local/dev_bundle: No such file or directory
lrwxr-xr-x  1 paul  staff  50 Jul 27 14:10 /Users/paul/.meteor/meteor -> packages/meteor-tool/1.4.0/mt-os.osx.x86_64/meteor

/Users/paul/.meteor/packages/meteor-tool:
total 16
drwxr-xr-x    6 paul  staff   204 Jul 27 14:09 .
drwxr-xr-x  181 paul  staff  6154 Jul 27 14:07 ..
drwxr-xr-x   15 paul  staff   510 Oct 27  2015 .1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova
drwxr-xr-x   15 paul  staff   510 Jul 27 14:09 .1.4.0.1vopth2++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 paul  staff    54 Oct 27  2015 1.1.10 -> .1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova
lrwxr-xr-x    1 paul  staff    53 Jul 27 14:09 1.4.0 -> .1.4.0.1vopth2++os.osx.x86_64+web.browser+web.cordova
```

**Comment by apendua** [comment]
@abernix For what it's worth, I've had similar problems with node process eating CPU like crazy when I was trying to pipe stdout from `meteor` to the parent process, i.e. `meteor` was spawned as a child process.

**Comment by acemtp** [comment]
Same here, I can run different meteor project (1.3 and less) and they all take 180% cpu on my mac.

![pasted image at 2016_07_27 05_32 pm](https://cloud.githubusercontent.com/assets/103561/17181662/320aca6e-5421-11e6-8c57-2893d3ed7b18.png)

**Comment by myktra** [comment]
@scharf I am experiencing all of this as well on a 1.3.5.1 project after the 1.4 tool download. However, my setup still reports Node v0.10.46 as the node version "in effect" inside my Meteor project:

```
$ meteor --version
Meteor 1.3.5.1                                
$ meteor node --version
v0.10.46
```

**Comment by tgardner4** [comment]
We're having the same issues here. The new update is burning up the CPU and we can't manage to stop it.  Here's our experience:

Prior to the automatic update being downloaded in the background, there were no issues with the CPU running high on my local machine. After Meteor automatically downloaded the latest build I received the following message at the command line:

Meteor 1.4 is available. Update this project with 'meteor update’.

From then on, any time I started the app, regardless of whether or not the app is being displayed in a browser, the node process would run at 90%+. After killing the app the CPU usage would go down. I left the machine alone, running at 90%+ for about 30 minutes to see if the problem would resolve itself, but no luck.

node version 4.4.7
meteor version 1.2.1
mongodb version 3.2.4

**Comment by rlora** [comment]
Same issues here.

```
$ meteor --version
Meteor 1.2.1
$ meteor node --version
v0.10.40
```

Even when I test an isolated minimal package CPU burns immediately.

![node](https://cloud.githubusercontent.com/assets/1533339/17183088/09615484-53f4-11e6-8b9a-dbd25f90a804.png)

**Comment by apendua** [comment]
FYI, a temporary workaround that worked for me was manually updating the `meteor` symbolic link to point to the old dev tool, which BTW works quite well even with Meteor 1.4. So basically,

    ~/.meteor/meteor -> packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64/meteor

fixes the problem.

The main difference here is that the meteor tool itself will be run with node `0.10.x` rather than `4.x`. However, the meteor dev server will be spawn with the node version corresponding to the project's release, so `meteor node --version` should still return the right value.

**Comment by abernix** [comment]
@apendua You're right that using the correct tool directly solves the problem.  Those using this should be careful as it will depend on their architecture and tool version.  I probably wouldn't recommend using 1.4 with the 1.3 tool though.

For those developers that need to work simultaneously on Meteor 1.4 and older versions concurrently (or don't want to change their symlink), a better solution might be to just execute the tool for their desired version directly from within their project directory:

Something similar to:

    ~/.meteor/packages/meteor-tool/**TOOL-VERSION**/**ARCH**/meteor <arguments as usual>

**Here's some ready-made copy-pasta commands for Mac and Linux:**

#### Mac
* For 1.3 and before: `~/.meteor/packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64/meteor`
* For 1.4: `~/.meteor/packages/meteor-tool/1.4.0/mt-os.osx.x86_64/meteor`

#### Linux
* For 1.3 and before: `~/.meteor/packages/meteor-tool/1.3.5_1/mt-os.linux.x86_64/meteor`
* For 1.4: `~/.meteor/packages/meteor-tool/1.4.0/mt-os.linux.x86_64/meteor`

Just as some explanation as to what's going on: The actual problem seems to be with `kexec` which is a NPM module that is used to "springboard" the process to the correct version of the `meteor-tool`.  I haven't got to the bottom of the problem yet, but it seems switching to  Node's `child_process`.`execFile` (or similar) might be a suitable option.

**Comment by apendua** [comment]
@abernix Or you can have two symbolic links with a little more effort ;)

Also, please see my comment above. As I said ... I've experienced a very similar issue some time ago when spawning meteor as a child process. I remember this worked pretty well with node `0.10.x` and broke as soon as I updated to `0.12.x`. I couldn't find the exact reason behind that but I remember I was able to fix it by using different `stdio` option when calling `spawn()`. If I am right, `inherit` was causing CPU problems and `pipe` worked much better.

**Comment by abernix** [comment]
@apendua Yes, but from a debugging standpoint, I would rather people weren't changing their symlinks too much or at all. :smile:

I have a proof-of-concept already that solves this, however it needs to be vetted a bit.  It sounds like the problem you were experiencing is very similar – if not the same.  [`execFile`](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) seems like a reasonable replacement here.

**Comment by scharf** [comment]
I think the problem is in the meteor script itself. It gets linked to newest version of meteor. Inside the script, paths are calculated by taking the [(physical) filename of the `meteor` script](https://github.com/meteor/meteor/blob/05f65f9b2180efa6293289393e4fa0e3b1efa3a9/meteor#L38-L49). From the script, the `$SCRIPT_DIR` is generated and all paths are taken relative to that.

Instead, meteor should calculate the `$SCRIPT_DIR`based on content of `meteor/release` and not on the currently linked directory (wich is the newest version).

**Comment by abernix** [comment]
@scharf For various reasons, the hand-off you're describing takes place in a springboarding process, [here specifically](https://github.com/meteor/meteor/blob/devel/tools/cli/main.js#L496-L497) when `kexec` is called.  It's not a problem with the Meteor launcher script (as you're referring to).

**Comment by scharf** [comment]
@abernix hmm, so why does changing the link solve the problem? Because then the script sees only the files and versions inside the specific package. E.g. `packages/meteor-tool/1.4.0/mt-os.osx.x86_64` or `packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64`. 

I think it is a **very** bad idea to compromise the stability of existing environments by running the newest version of node and then trying to execute an older version.

So, I think the `~/.meteor/meteor` script should detect and read the `.meteor/release` file (if it exists) and then execute the correct meteor. For example like this:

```sh
# read the .meteor/release file if it exists and extract the version 
# else take the newest version
METEOR_RELEASE=`extract-release`
 # form the script that creates the link to `~/.meteor/meteor`
PLATFORM=`get-platform`
# now execute the correct of meteor
exec packages/meteor-tool/$METEOR_RELEASE/$PLATFORM/meteor "$@"
```

Instead of updating the a link in `~/.meteor/meteor` when the version changes, the `meteor` script should figure out which version of meteor to run. 

This dangerous linking strategy also explains why I had troubles when meteor updated to the newest version but my project uses an older (stable) version.

My conclusion for this is: I will set $PATH directly to `~/.meteor/packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64/tools/cli/meteor`. Then I don't have problems with meteor changing the world when it does the automatic update. Then I am not affected when meteor uploads a new version...

**Summary**:  do not distinguish between releases in the node code -- do it in the shell! Always run the `~/.meteor/packages/meteor-tool/*/*/meteor` that belongs to the version you are using in the project.

**Comment by zol** [comment]
@abernix and others. Here's my understanding of the issue (correct me if I'm wrong):

Running Meteor 1.3.x projects with the 1.4 Meteor tool results in extremely high CPU use. This impacts most users as the 1.4 tool is automatically downloaded and run now that it's been released.

**Comment by rlora** [comment]
@zol that's correct. It holds true for Meteor 1.2.1 as well. Linking to the previous tool (`1.3.5_1`) solves the issue for older meteor apps as well.

**Comment by zol** [comment]
Thanks for confirming @rlora

**Comment by abernix** [comment]
@zol Correct. 100%.  Specifically the pass off.  

@scharf There is nothing dangerous about the current strategy.  Meteor needs to make some decisions for various reasons (based on the package catalog) and for OS/platform reasons but your summary is essentially all it does.  Your code is not ever running with the wrong version.  The `meteor-tool` makes sure of this. I'm on my phone right now and not at liberty to elaborate extensively but I assure you the current setup is very reasonable. Significant improvements were made to make it all even more seamless in 1.3.5.1 and this is just a small (but frustrating) residue from the major migration to Node 4.

**Comment by abernix** [comment]
@zol ***specifically the pass off with `kexec`.

**Comment by scharf** [comment]
@abernix 
> There is nothing dangerous about the current strategy. 

True, but the implementation has some long existing problems. I always wondered, why the node/npm version changed whenever meteor decided to push a new update to my machine. Now I understand: it just decides to use some of the newest tools for the old installations. 

I would expect that the current version should not silently updated to a new version. Meteor has the concept of the `.meteor/release` file and keeps the release stable. I would expect that I can run different projects at different versions and new version should not silently update or influence existing version.

In fact, I use isolated environments for pretty much everything (python virtualenv, nvm, java, etc) and therefore I install meteor next to my project and not in the `~/.meteor` directory to keep the environments isolated. But with the funky meteor push strategy, the environments are not as isolated as I thought they would be. So, at the end I can just use `~/.meteor`...

**Comment by tmeasday** [comment]
> I always wondered, why the node/npm version changed whenever meteor decided to push a new update to my machine. Now I understand: it just decides to use some of the newest tools for the old installations.

I'm fairly confident it was never the case that springboarding ran the `meteor` process with the wrong version of node. It is true the `meteor node` command used to just default to the node of the latest recommended release (which is confusing), but that is an issue that has been recently fixed.

Did you actually see problems with incorrect node versions?

---

The decision was made at some point (and has been the case for a long time without causing problems, more or less) to simplify things for users and have the tool manage the job of choosing the correct version of Meteor for you. I can definitely understand the desire to have more control over it and it's definitely a tradeoff that has it's downsides.

Of course when a major problem like this happens it seems like a bad decision was made, but this is luckily a bit of a once off, as it turns out!

**Comment by tmeasday** [comment]
I wonder if any users that are seeing this problem are on windows?

**Comment by dcusan** [comment]
I'm having the same problem (Mac OS X) without having applied the 1.4 update. Updating to 1.4 solved the problem as reported.

I remember I had similar problems when using `npm run ...` directly without the preceding `meteor` to run meteor locally when 1.3 got out. Using the bundled npm with meteor via `meteor npm run ...` solved this.

Unfortunately running the `1.3.5.1` tool with the provided link by @abernix didn't solve the issue for me after reverting back to 1.3.5.1.

**Comment by tmeasday** [comment]
I created `1.4.0.1-rc.1` which appears to fix the problem (see https://github.com/meteor/meteor/pull/7510)

I haven't created a proper release or recommended it yet, but if it works we can do that fairly quickly. If you want to test it out in the meantime, that'd be great. I *think* this process replicates what will happen when it is properly released:

1. Get the release by creating a dummy app: `cd /tmp; meteor create --release 1.4.0.1-rc.1 dummy`

2. Go to your <1.4 app and start it up using this tools version:

```
METEOR_DEBUG_SPRINGBOARD=true ~/.meteor/packages/meteor-tool/1.4.0-1-rc.1/mt-os.osx.x86_64/meteor
```

(you don't need the `METEOR_DEBUG_SPRINGBOARD`, but it's handy for sanity checking.

Please 👍 this comment if it works and 👎 and maybe give more info if it does not.

(Thanks to @apendua for pointing out the pipe vs inherit weirdness)
-- 

@abernix: I went with `spawn` because `execFile` seems to not be suited to long-running processes that have (potentially infinite) output. Is my understanding wrong?

**Comment by acemtp** [comment]
@tmeasday it fixes the problem but the spinning wheel during the build is not displayed so we don't know that meteor is working. I don't know if it's a regression or normal.

**Comment by tmeasday** [comment]
@acemtp - you're right, the build messages aren't coming through. Thanks

**Comment by apendua** [comment]
@acemtp @tmeasday That's happening because in "pipe" mode any writes to stdout that are happening in "raw" mode will not be visible. This is actually very unfortunate because it looks like neither "pipe" not "inherit" mode is perfect.

When it comes to capturing "raw" writes I think that tools like:

https://github.com/chjj/pty.js

might come handy, but I also remember this particular library broke my node apps on windows, so it's probably not an option either. Though, it may still be worth checking if the CPU issue is gone when using "pty.js".

**Comment by tmeasday** [comment]
Ok, after some messing around with @abernix, we managed to put together a very simple reproduction where a node 4 process spawns a node 0.10 process, crucially *AFTER LOGGING SOMETHING*, and we see this behavior.

What does this mean for the tool? We could ensure that we have not logged anything before springboarding (although that seems pretty restrictive and easy to mess up). We could also try and wrap the node 0.10 process somehow to avoid this? IDK.

--- 

The repro is pretty simple, for those interested. Run this script with node 4 (probably available at `~/.meteor/packages/meteor-tool/1.4.0-1-rc.1/mt-os.osx.x86_64/dev_bundle/bin/node` - ish):

```js
var node = process.env.HOME + '/.meteor/packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64/dev_bundle/bin/node';
var script = '/tmp/test-2.js';

console.log('shelling out')

var child = require("child_process").spawn(node, [script], { stdio: 'inherit' });
```

Where `/tmp/test-2.js` contains:

```js
var i = 0;
setInterval(function() {
  i += 1;
  console.log(i);
}, 1000)
```

**Comment by apendua** [comment]
@tmeasday I was able to reproduce the same behavior with node 4 on my machine. As you said, this only happens when the parent process is logging something.

An interesting thing though, is that it's not happening when node 6. So maybe we could switch to node 6? for dev tool only of course.

**Comment by abernix** [comment]
As a bit more follow-up (and back story to answer the previous question about `spawn` vs `execFile`) and just to further document what's been found...

I had originally hoped `execFile` would be a suitable replacement closest to the functionality that `kexec` provides to essentially "replace" a running process.  [`kexec`](https://github.com/jprichardson/node-kexec/blob/39208e5d3d42994e2d1d1f497b6592d9a3adb9eb/src/kexec.cc#L35) (what Meteor was using already) does this with a `libc` function called `execvp` – explained a bit [on this page](http://linux.die.net/man/3/execvp) where it's actually referred to as "execute a file".  I figured it would be synonymous with the shell-builtin `exec`, [Python's `execv`](https://docs.python.org/2/library/os.html#os.execv) and [Ruby's `exec`](http://ruby-doc.org/core-2.3.1/Kernel.html#method-i-exec).  Long story short?  It doesn't seem to be ([node docs](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_execfile_file_args_options_callback)) and I find that to be a bit silly.

Alas!  Ultimately, `execcv` functionality is desired since it replaces the running process and doesn't leave an unnecessary `node` "wrapper" program and any increased memory footprint caused by that.  Currently, with the `spawn` fix in 1.4.0.1 `rc.0` and `rc.1`, that additional memory footprint is there because the parent process is waiting for the child to terminate.  It's not unreasonable resource usage (~78MB isn't much RAM these days, right???), but it'd be nice to avoid it.

Now getting back to the reproduction @tmeasday posted above and possible solutions...

It seems that `node@4.x` is not happy when it's been initiated by a `node@0.10.x` process which has produced STDOUT.   😕❗❓  Why? (Please enlighten me, someone).

Avoiding logging pre-springboard is certainly doable, but certainly not desirable.

Ok, so wrapping it in another program?  If we take the above reproduction script (the first one) and replace it with this:

```js
var node = process.env.HOME + '/.meteor/packages/meteor-tool/1.3.5_1/mt-os.osx.x86_64/dev_bundle/bin/node';
var script = '/tmp/test-2.js';

console.log('shelling out')

var childArgs = ['-q', '/dev/null', /* -c here for Linux */ node, script];

require("child_process").spawn('script', childArgs, { stdio: 'inherit' });
```

Presto... the problem goes away!  `script` is an age-old *nix tool that essentially puts command output in a file but also feeds it to STDOUT so you can see it.  Wrapping the node program in it (and sending its output to `/dev/null`) solves the problem (at the cost of about 6MB of RAM).  Also, I've confirmed that we can go back to using `kexec` with this method and spare the "parent" `node` process created by `spawn`. 🎆 

Using `script` is kinda a silly workaround and we should check on its portability/availability.  Also, its invocation is slightly different on Linux.  It's nothing that can't be handled and this might be a reasonable work around if we can't find a better solution soon.

Anyway, hopefully we can figure out what's going on with pass-off between these.  Digging: commence.

**Comment by apendua** [comment]
@abernix Back to your "why?", do you this could be related?

https://github.com/nodejs/node/issues/3596#issuecomment-152516780

I know that the symptoms are somewhat different here but what I am suggesting is that it may be related to some BUG in MacOS itself. Why don't we just use node 6?

**Comment by abernix** [comment]
@apendua Nice find.  That sounds _very very_ much like the issue.  OS X Kernel issue, eh?  Fun.  I'll look more when I'm back at a computer.

The Node 6 standpoint so far has been: When Node 6 is considered stable and under LTS support by Node, then it will be used.  As of right now using Node 4 and Node 6 would require shipping both in the `dev_bundle`, increasing the both the size and adding complexity.

**Comment by abernix** [comment]
I can confirm that the issue does not happen in Ubuntu 14.04.

I'm not _entirely_ sure that is the same bug (as that is isolated one version), but it's certainly very related.  It's interesting that I cannot find any combination aside from Node 4 spawning Node 0.10 as being problematic.  A fun fact though!  In the above example, if instead of doing a `console.log` before the spawn you simply assert `process.stdout;` the CPU usage is 103% instead of 170%.  *shrug*

**Comment by apendua** [comment]
@abernix Looks like the other issue I mentioned was fixed by updating node's libuv from 1.8.0 to 1.9.1. The good news are this fix is already present in node 4.x-staging branch:

https://github.com/nodejs/node/blob/v4.x-staging/deps/uv/configure.ac#L16

I think it may be worth checking if this also solves the meteor's issue we are discussing here. If that's true then we should be fine as soon as they release the next node 4.x.

**Comment by apendua** [comment]
FYI, I've built from the v4.x-staging branch and it looks like the issue is gone.

**Comment by scharf** [comment]
This is the script I use to run old versions of meteor. I call it `meteor` and put it into a directory in my `PATH` (instead of `~/.meteor`)

```sh
#!/usr/bin/env bash
set -e
# make sure we can find meteor 
METEOR_ORIG=~/.meteor/meteor

# get the first level of links to meteor
ORIG_DIR=`pwd`
METEOR_DIR="$(dirname $METEOR_ORIG)"
cd $METEOR_DIR
SCRIPT="$(readlink $(basename $METEOR_ORIG))"
cd $ORIG_DIR
SCRIPT_PATH=$METEOR_DIR/$SCRIPT

echo 'Getting meteor version. If this takes very long, meteor may download the required version...'
echo 'In this case it may be better kill this process to call once to see the console output:'
echo "   $METEOR_ORIG --version"
# extract the version and convert the last `.` into `_`
# This is pretty slow! In the worst case, it may download the required version of meteor
VERSION=`$METEOR_ORIG --version| sed 's/[^0-9.]*//g' |sed 's/\([0-9]*[.][0-9]*[.][0-9]*\)[.]\([0-9]*\)/\1_\2/g'`

# replace the version in the path
METEOR=`echo $SCRIPT_PATH | sed "s~/meteor-tool/[0-9.]*/~/meteor-tool/$VERSION/~"`

echo 'running meteor form' $METEOR
exec "$METEOR" "$@"
```

I know that this may be fragile since I have no control over the meteor installation process, but it makes sure that each version is called as if it not other version of meteor exists (no node 4.x forking node 0.10 processes).

**Comment by tmeasday** [comment]
Fixed in 1.4.0.1, although I think I'll leave it open until node 4.5.0 is out, and we can revert the change.

**Comment by tmeasday** [comment]
Thanks again to @apendua and @abernix for the assist on this one.

**Comment by abernix** [comment]
@scharf As my last opinion on this within this issue (happy to discus further in the forums): I've been using Meteor for years now and, like Tom said, I don't believe what you said above has ever been true.  Yes, `meteor node` and `meteor npm` were sometimes using the wrong version, but this has been fixed recently – even those commands themselves are very new, they were created in order to get ready for Meteor 1.4!  In general, Meteor has done a great job switching between versions.

If the script you provided and the work arounds you're using to run exact Meteor versions are working for you, great!  However this is exactly what the Meteor tool is supposed to do for you and I don't think it's expected that the user should have to work around it – `meteor-tool` should be quick, efficient and reliable at making this decision.  That's the point.  Can it improve?  I'm sure.  But work-around shell scripts with that sort of functionality, while great for temporary fixes, don't do anything to help the greater Meteor community, and don't work at all for the very large number of Windows users who may have similar issues.  I hope nobody has to leave your script in place!

Your original suggestion to move all functionality into a shell script doesn't quite work as there are package resolution/downloading tasks that the Meteor code must handle.  Aside from this particular issue as a hiccup (in an otherwise very very large upgrade), I'd encourage you to have trust in the Meteor tool to do the right thing – and if you experience problems, open issues with improvement ideas that will hopefully turn into PRs and improvements for everyone.  In recent activity, I think preventing automatic downloads (#7445), intention of making this easier to [find in prereleases](https://github.com/meteor/meteor/issues/7338#issuecomment-230474031), and on-going discussion in #7026 - the tool will improve further.

That being said.  Everyone should update to 1.4.0.1 where this issue is hopefully settled! :)

    meteor update --release 1.4.0.1

**Comment by scharf** [comment]
`1.4.0.1` fixes the CPU problem! 👍 


@abernix I started using meteor `METEOR@1.3-beta.12` and I have seen a few surprising changes in node and npm versions **without** upgrading to the next version. We have always updated relatively quickly to the next version of meteor, but I think it is not ok to change the version under the hood while using an old version.

If the goal of meteor it to keep versions stable and this was just a bug, **I am absolutely willing to trust meteor**  and drop my script (one thing less to worry about).

I have seen too many changing environments in the last 40 years. Therefore I try to protect my systems form outside influences as much as possible. Upgrades are absolutely necessary but I want to control when I do the upgrade and I want a way back it the new version causes problems.

One of the simplest solution is to have independent installations and set `$PATH` depending on the  used version (like python virtualenv and nvm). A bit more complex is to have wrappers (scripts or in some other way) for each command that make inside a decision which version of the program to execute. 

However: even with `1.4.0.1` the following happens:

```sh
$ meteor --version
Meteor 1.3.2.4
$ meteor node --version
v4.4.7
$ meteor npm --version
3.10.5
```

This is **exactly** what I want to avoid. Or does meteor  `1.3.2.4`  work with node `4.4.7`????

Fortunately, `meteor` is using the correct version of node, just `meteor node` is using the newest one.

OTOH: `meteor npm install` is using the **wrong** version of node and npm which can be fatal:

```
/Users/scharf/.meteor/packages/meteor-tool/.1.4.0-1.1rhgg5f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/scharf/.meteor/packages/meteor-tool/.1.4.0-1.1rhgg5f++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/index.js npm install
```

**Comment by skishore** [comment]
I saw the same issue with an app on Meteor 0.9.1. Updating my meteor-tool version to 1.4.01 didn't fix it for me, though. One strange thing I noticed is that when run `meteor`, it selects a strange tool version:

    .1.0.26.1jddtpq++os.osx.x86_64+web.browser+web.cordova

Here's what the diagnostics say:

    $ meteor --version
    Meteor 0.9.0.1
    $ meteor node --version
    v4.4.7
    $ meteor npm --version
    3.10.5

I tried to run `meteor update`, but got an error installing bcrypt: http://pastebin.com/1Z3UDwS

node-gyp is installed:

    node-gyp@3.4.0  /usr/local/n/versions/node/5.2.0/lib/node_modules/node-gyp
    node@6.2.2

I have no clue where I can go from here. Is there any way to get this old app working again?

**Comment by skishore** [comment]
My update is failing because of this error when adding the `bcrypt` package:

    ld: library not found for -lgcc_s.10.5

In turn, that error is caused because I don't have Xcode 7. Macs are truly a hostile ecosystem for anyone who doesn't stay up to date... However, there's still the CPU issue with the old version of Meteor. Are releases prior to 1.0 still supported?

**Comment by c9s** [comment]
I understand that meteor wants the users to get the upgrade as soon as possible. however, if you can 100% so sure that there is no bugs in the latest release, or you need to let the meteor users keep on the stable version.

thus, I would like to suggest just to remove the auto-upgrade feature since it's breaking things everytime a new release come out.

**Comment by juho** [comment]
Release QA has been dreadful in the past half a year. Hope to see improvements fast.

**Comment by tmeasday** [comment]
@skishore  - wow, still running an app on 0.9.1? I didn't know anyone was still doing that :). I think I can understand why the CPU issue might remain for you then. This problem will be fixed when node 4.5 is released (any minute now...). I would encourage you to update anyway, although it might be tricky to go straight from 0.9.1 to 1.4 in one go! (Sounds like you just need a [build toolchain](https://guide.meteor.com/1.4-migration.html#binary-packages-require-build-toolchain) though).

@c9s - the problem with this kind of bug (where the recommended release causes a problem with running other releases) is it's kind of by definition impossible to discover until we recommend the release. However, to my knowledge this is the first time such an issue has happened (where the latest release causes issues to people who aren't running that release).

We don't anticipate bumping major versions of Node all that often, however :)

**Comment by mitar** [comment]
I run 0.8.3. :-)

**Comment by skishore** [comment]
@tmeasday thanks for the tips! In looking around, I wasn't able to find a way to install a sufficiently new xcode-select toolchain without installing Xcode 7, so I ended up doing that. Updating to meteor-tool 1.3 would probably also have worked for me.

My main project is up-to-date, but the reason I had one back at 0.9.1 was because it was a side project that I haven't touched in a year. I would be nice if there was testing that guaranteed that such projects would run without continual maintenance.

**Comment by tmeasday** [comment]
In case people are still seeing this because the tool is *not* autoupdating to 1.4.0.1 I added a note to the top of the issue

**Comment by tmeasday** [comment]
Closing this issue as it's fixed by 1.4.0.1. Hopefully anyone stung will find it if they google it.

**Comment by skishore** [comment]
I think Meteor 1.4.1 may have reintroduced this bug for apps still using older versions. I had somewhere between 100-200% CPU usage for a 1.4.0.1 app when the tool was updated, with no clients connected. The issue was immediately resolved upon updating to 1.4.1.

What kind of testing is there for apps running old versions of Meteor? The backwards compatibility feature is not useful if performance is affected so drastically.

**Comment by skishore** [comment]
Interestingly, now that I've downloaded meteor-tool@1.4.1, I can revert my app back to a 1.4.0.1 commit and everything works fine as well.

**Comment by tmeasday** [comment]
Hi @skishore, not seeing this. Are you able to reproduce at all?

**Comment by skishore** [comment]
Unfortunately I am completely unable to reproduce the issue. I tried creating a new app at release 1.4.0.1 by directly invoking meteor-tool@1.4.0.1 (i.e., to mimic the old setup that was failing) but that still worked well. Is it possible that the CPU usage was due to downloading the tool in the background? I've saw on another issue that the "There is a new release of meteor ready to download." message is only shown after the download is complete.

**Comment by tmeasday** [comment]
It sounds conceivable; or certainly unpacking the download perhaps.

**Comment by c9s** [comment]
Running meteor 1.4.1.2 with app (1.4.1.2) still causes very high CPU usage.

**Comment by abernix** [comment]
@c9s That doesn't match the original issue here which only occurred when springboarding a Meteor 1.4 app to a 1.3 (Node 0.10) app.  It was actually an upstream Node issue and is definitely fixed.  I cannot reproduce this problem you are referring to so if you're experiencing this (1.4.1.2 release and 1.4.1.2 app), please open a new issue with a fresh reproduction.
