### ISSUE TITLE
error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by hellzakk** [meteor/meteor#7499]
Hi all, in my company we have a certificate for the firewall https inspection.
I have already inserted it in the ca-certificate in my ubuntu 16.04 LTS and i have already installed meteor with curl, but when i create a new project it give errors

```
=> Errors while creating your project         
                                              
While downloading autoupdate@1.2.11...:
error: self signed certificate in certificate chain

While downloading caching-compiler@1.0.6...:
error: self signed certificate in certificate chain

While downloading ddp-client@1.2.9...:
error: self signed certificate in certificate chain

While downloading ddp-server@1.2.10...:
error: self signed certificate in certificate chain

While downloading templating@1.1.14...:
error: self signed certificate in certificate chain
```
any hint?

**Comment by abernix** [comment]
I have no experience in how this works in practice but, [based on this code](https://github.com/meteor/meteor/blob/8169b6fd573722e8b02e30202627ede922e3f037/tools/utils/http-helpers.js#L184-L186), you should be able to use the `CAFILE` environment variable just like NPM does.

You can either prefix all your Meteor commands with: `CAFILE=/path/to/certificate` or set it in your environment by adding something along the lines of `export CAFILE=/path/to/certificate` to your `.bashrc` or `.zshrc` and re-logging in.

I hope this helps, otherwise my next question is going to be for you to help figure it out! ;)

**Comment by hellzakk** [comment]
Hi @abernix 
it's working with CAFILE=/path/to/certificate prefix
Thanks :)

**Comment by jjj1981** [comment]
hello @hellzakk I am facing the same problem. How did you get the ca-certificate and insert it in your Ubuntu box? Here we use windows, I tried using 'certmgr.msc' and exported the ca-cert as DER and then tried using openssl to convert to pem. However I am still getting the same issue.

**Comment by parechayui** [comment]
I am new to meteor , still facing the same issue when i execute "meteor create simple-todos" in my company's machine .please help me understand how to overcome this.
please find the attached
![image](https://cloud.githubusercontent.com/assets/15204070/23510250/c1908452-ff26-11e6-8661-2eced88391c7.png)

1) I tried the same thing in my personal laptop everything works fine 
2) I tried white listing the https://atmospherejs.com/, i assume that meteor is pulling libraries from atmospherejs while creating the project ( correct me if am wrong)
3) meteor npm install works fine as it is pulling libraries from http://registry.npmjs.org/
4) I updated environment variable CAFILE='path/to/CA-FILE' from my company but still i come up with some other errors
