### ISSUE TITLE
Facebook - Work with Pre-existing Client Side Authentication Token

### ISSUE THREAD

**Issue by philcockfield** [meteor/meteor#750]
**_2 Upvotes**_ Ref (Avital) https://groups.google.com/forum/?fromgroups=#!topic/meteor-talk/84ABNbpPmks
## Context

FB is now pushing usage of it's API in web-apps via it's [JS SDK](https://developers.facebook.com/docs/reference/javascript/). This includes authentication in the client, via this API, without any server interaction.
## Problem

The Meteor facebook authentication package initiates it's own OAuth authentication step to authenticate on the server (getting and storing the authToken).

When a Meteor app is surfaced within the Facebook containing site, as either a canvas app, or within a FB page, Meteor does not recegonize the logged in status of the user, requiring the user to re-authenticate.

This is a UX annoyance when working on a sites own domain (outside of Facebook's container) but downright confusing (and suspicious) for the user when the are encountering the app within Facebook itself.
## Use Cases
1. Meteor app surfaced within Facebook cavas app (inside FB frame)
2. Meteor app surfaced within a Facebook page (inside FB frame)
3. Site on own domain reusing existing FB client login (via the Facebook JS SDK).
## Requirement Considerations
- Have Meteor use the FB-JS-SDK to login, or recognize an already logged in user, and then manage:
  - Creation or updating of the corresponding Meteor user object.
  - Pop meteor into a "logged in" state so that the standard `user`, `userId` methods on the client, and the user-id context is passed to server methods.
- Ability to specify required permissions (see http://developers.facebook.com/docs/reference/login/#permissions)
## Comments

Having the client already authenticated by FB potentially opens up a security hole, in that this may be spoofed somehow.  This must be a problem that FB has worked out, as perhaps there is a way to re-confirm in the background from the server that the given authToken is valid.

**Comment by glasser** [comment]
Maybe also related: #3515

**Comment by stubailo** [comment]
+1 - came up in relation to native login at HackMIT 2015

**Comment by juniobranco** [comment]
+1

**Comment by hwillson** [comment]
First off, I know it's been a while, but thanks for the detailed feature request! 

Quite a bit of time has passed since this feature request was created. While looking into ways that Facebook's JS SDK can be more tightly integrated with Meteor sounds interesting, I'm not sure that adding this type of functionality into the Meteor core would be beneficial. Leveraging Facebook's JS SDK for authentication can already be achieved outside of the Meteor core, as demonstrated by packages like [`heysailor:accounts-facebook-accesstoken`](https://github.com/heysailor/meteor-accounts-facebook-accessToken) (allows you to take an `accessToken` created after logging in through FB's JS SDK and pass it into `accounts-facebook`, to bypass a second login). Since this functionality can be achieved outside of the Meteor core, as outlined in the [Feature requests](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) section of the Contributing guide, it's a much better fit for an external package.

At this point the Meteor accounts system is very well defined - the fact that each `accounts-*` package leverages OAuth directly, in a very similar fashion, means that there is quite a bit of code re-use between accounts packages. As demonstrated by the [recent `accounts-*` package refactoring](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13) that happened to remove the mandatory Blaze dependency, this re-use has proven to be quite helpful from a maintenance point of view. Tightly integrating FB's JS SDK into `accounts-facebook` would be a break away from the consistency of the other accounts packages, which means more internal maintenance.

Given the above, and since there hasn't been much interest/activity on this issue in quite some time, I'll close it off. Thanks for posting this originally!
