### ISSUE TITLE
Include windows-build-tools in the Windows dev bundle to avoid compiler toolchain prerequisite

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#7502]
The `node-gyp` project [recently](https://github.com/nodejs/node-gyp/commit/f6eab1f9e4b160b60b2736bb01a09c83785ba979): added a new option for installing the necessary compiler toolchain on Windows: [`npm install windows-build-tools`](npmjs.org/package/windows-build-tools).

If the footprint of this installation is small enough to include in the dev bundle (a low bar, since we already include a Python installation and lots of npm packages), and it works on most versions of Windows, it would be great to provide it automatically, so that Windows developers no longer have to install Visual Studio by hand.

Thanks to @dimitriuz for [pointing this out](https://github.com/meteor/meteor/issues/7469#issuecomment-235545320)!

**Comment by s-devaney** [comment]
Definitely a great idea, but have we considered alternative packages which don't require native binaries rather than having to package a compiler with Meteor?

AFAIK the only Meteor dep that requires compiling is bcrypt - there are two well supported native JS implementations of bcrypt available:

https://www.npmjs.com/package/bcryptjs
https://www.npmjs.com/package/bcrypt-nodejs

**Comment by abernix** [comment]
@s-devaney Aside from the fact that JavaScript crypto libraries are significantly slower, the issue isn't only Meteor – it's solving the problem of what to do with the greater `npm` ecosystem which Meteor wants/needs to have access to. There are hundreds, (? thousands?) of NPM packages which will need to build from C libraries.  In Meteor alone you also need to consider the `mongo` driver and its dependencies (`bson`, etc.)

**Comment by abernix** [comment]
This comment from the `node-gyp` project is also interesting: https://github.com/nodejs/node-gyp/issues/629#issuecomment-225578519

It seems that MS has recently released a new VC++ Build Tools specifically meant to address some of these problems and official recommendations [on this page](https://github.com/Microsoft/nodejs-guidelines) where they claim:

> Microsoft ❤️ Node.js!

I'm not sure if they used the right emoji, but this is at least somewhat promising.

**Comment by zetos** [comment]
My Meteor was getting stucked on: `Downloading meteor-tool@1.4.0-1...` everytime when i tried to update <1.3.5.1 releases.

Even with [MS Build Tools](https://www.microsoft.com/en-us/download/details.aspx?id=48159) downloaded/installed through Microsoft site.

But by running `npm install windows-build-tools` this issue was solved.

**Comment by fvpDev** [comment]
https://github.com/meteor/meteor/issues/7469#issuecomment-238037142

**Comment by benjamn** [comment]
After some more examination, this proposal doesn't really make sense, because the `windows-build-tools` is more of a tool for easing system-wide installation of the build tools. Because of that, it's not clear how we could provide the build tools as part of the dev bundle.
