### ISSUE TITLE
"meteor npm list -g" not working on windows (looking in wrong directory)

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7508]
### Observed

On Windows run `meteor npm list -g` command:

```
meteor npm list -g
C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\bin
`-- (empty)
```
### Expected

List of node modules found here:`C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules`

Looks like the command is looking in the wrong directory.

This is windows only, seems to work fine on my MacOS install.
### Version info
- Windows 10.10586.494
- Meteor: 1.4
- Meteor npm: 3.10.5
- Meteor node: v4.4.7

**Comment by abernix** [comment]
I don't think the global NPM scope of the Meteor bundled `npm` has really been considered before.  The inconsistency between Windows and Linux is bizarre, but what do you need out of this functionality?

In a way, giving users access to the correct Meteor "global" directory and user's willingness to copy and paste _whatever_ examples they come across (which might install into the global scope) leaves possibility for users to break core functionality of their meteor tool by doing `meteor npm install -g package@incompatible-version`.

**Comment by brucejo75** [comment]
Interesting point @abernix.
- using `meteor npm install -g` was an attempt to understand what packages were in my `dev_bundle`
- overall I am struggling with how to think about the meteor global repository in the dev bundle.

If you do not want people to execute this command, it is weird for it to work on MacOS (linux) and not work on Windows.  Would you prefer to disable it overall?  I think it might be simpler to simply make it work.

And I think it may be worthwhile to write up an explanation of the dev_bundle and how you expect users to think about it.

I have been confused about the different repositories and I posted my perspective on it in the [forums](https://forums.meteor.com/t/meteor-and-the-npm-global-repository/27154).

Would you mind taking a few minutes and clarifying the meteor perspective?  Are my assumptions correct?  Is there more to consider?

Thanks!

**Comment by hwillson** [comment]
While it is definitely a bit annoying this works on MacOS but not windows, I think we're okay to close this issue for now since:

- Using the global scope of the Meteor bundled npm isn't something that developers should have to do.
- If anyone runs into this issue in the future, the discussion here (and [in the forums](https://forums.meteor.com/t/meteor-and-the-npm-global-repository/27154)) documents it fairly well.
- The chances of anyone working on addressing this issue are quite low, since this isn't really a feature that Meteor devs should need to worry about.

Thanks very much for opening this issue originally!

**Comment by abernix** [comment]
See also #8277, as it sounds related (still open and being debugged).
