### ISSUE TITLE
Error: Cannot find module 'meteor-promise'

### ISSUE THREAD

**Issue by shtefcs** [meteor/meteor#7524]
Hi people,

Recently I started facing this issue and can't run meteor apps.

`Error: Cannot find module 'meteor-promise'`

Screenshot below: ![](http://content.screencast.com/users/shtefcs/folders/Jing/media/389ab8c9-9fad-4b6b-a078-0d4c76cf10a7/2016-07-29_1343.png)

Whatever i type with `meteor` I am getting that error.

I found this issue https://github.com/meteor/meteor/issues/7221 , but I don't see solution.

I re-installed meteor, nodejs, today, but still same.

Sfefan

**Comment by abernix** [comment]
Can you try these more extensive reinstall instructions?

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Comment by benjamn** [comment]
Yeah, it sounds like your dev bundle (the pre-built bundle of tools and npm packages that we ship with each version of Meteor) is somehow corrupt (i.e. missing `meteor-promise` and potentially other packages).

**Comment by shtefcs** [comment]
@abernix Thank you mate, it worked.

I got another problem, not sure if its related and should I create new issue for it. 

When I do `meteor npm install` I get this ![](http://content.screencast.com/users/shtefcs/folders/Jing/media/b8fca5f1-b814-4c39-aba9-e12e4b53458e/2016-07-30_1342.png)

Here is the whole console log https://gist.github.com/shtefcs/239996c42810a3422eb23cb1eed588b8 .

@benjamn Thanks for your help to!

**Comment by abernix** [comment]
@shtefcs That is not a Meteor error.  Most likely, Chimp links to dependencies in GitHub directly and NPM is attempting to clone a Git repository over the SSH protocol and failing because you don't have `ssh` installed.   I'm not sure what to recommend, but you might start by opening an issue with `xolvio:chimp`, I guess – or maybe by forcing your Git to use non-ssh URLs via [this method](https://github.com/npm/npm/wiki/Troubleshooting#npm-only-uses-git-and-sshgit-urls-for-github-repos-breaking-proxies).

**Comment by Sanxel** [comment]
**abernix**, thanks, that helped me on Windows. 
But now i have some error again after I did the following. Made a copy of working project folder, installed 3 packages(semantic:ui, flemay:less-autoprefixer, jquery) and changed some code, then just decided to revert to a backed up project, that now have stopped working. 
In the root 'meteor --version' works and shows 1.4.2. But the project that just resently worked now shows:
![image](https://cloud.githubusercontent.com/assets/10211444/20100154/3c94e372-a5cd-11e6-8708-a33f4f959239.png)

**Comment by abernix** [comment]
@Sanxel Maybe try deleting that `dev_bundle` link yourself in Windows Explorer (possibly as administrator, if necessary).  It should be re-created automatically the next time you run the `meteor` command on that project.

**Comment by Sanxel** [comment]
@abernix Thanks for quick reply! Will definetly try this. At this point I just couldn't wait and manually recreated new project with required packages(took me like 20minites) and copyed the code over. I will try deleting dev_bundle link, if encounter this again. Thanks.

**Comment by brettg2** [comment]
I have reinstalled Meteor 2-3 times and this issue continues to appear.
