### ISSUE TITLE
IE10 bug when use Session.set() inside a Meteor.setTimeout()

### ISSUE THREAD

**Issue by jmbizarrolopes** [meteor/meteor#7525]
Hey, People

In my project, in a Template events, I have this code (to change dynamic checkboxes in a form):

`Meteor.setTimeout(() => {
    Session.set('variable', true);
}, 1000);`

And I found this message in IE:
[Internet Explorer has stopped working](http://www.eightforums.com/attachments/browsers-mail/16246d1360311264t-ie-10-java-internet-explorer-has-stopped-working.jpg)

This happened with IE 11 and older versions.

After this appear, I need to close the browser and I can't set the session.

I'm using Meteor 1.3 and my OS is Linux Fedora 22, but this was tested in Windows 7, 8.1 and 10.
I tried to execute this code isolated and had the same problem.

I'm using this packages:

`meteor-base            
mobile-experience    
mongo                   
blaze-html-templates  
session                 
jquery                  
tracker                
es5-shim             
ecmascript          
semantic:ui
flemay:less-autoprefixer
accounts-base
accounts-password
iron:router
sanjo:jasmine
useraccounts:semantic-ui
lbee:moment-helpers
risul:moment-timezone
kadira:debug
bankfacil:vanilla-masker
gfk:notifications
raix:handlebar-helpers
mrt:mask
momentjs:moment
meteor
drewy:datetimepicker
http
email
cfs:standard-packages
cfs:gridfs
cfs:filesystem
velocity:core
velocity:html-reporter
aldeed:template-extension
gwendall:body-events
hotpea:stale-session-with-callback
standard-minifier-css
standard-minifier-js
mizzao:user-status
`

**Comment by abernix** [comment]
Does the same thing happen if you use a `function () {}` expression instead of the arrow function?

**Comment by jmbizarrolopes** [comment]
Yes, it happens the same way.

**Comment by macrozone** [comment]
Does it happen when you set another Session-variable like `Session.set('othervariable', true);`?

If no, then it has probably to do with what you do when updating `variable`. Maybe IE can't cope with the re-renders that are triggered by Session.set('variable', true).

Check where you use Session.get('variable') and see if you can reduce the rerenders

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and haven't received any other similar reports.  It could be a bug in your code or something isolated to your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it – namely, a reproduction per the guidelines for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor).  Without a reproduction, it's hard to say if this is a bug in your implementation or a bug with Meteor.
