### ISSUE TITLE
Meteor on Windows node-sass cannot download v3.2.0 win32-ia32-46_binding.node

### ISSUE THREAD

**Issue by cope** [meteor/meteor#7526]
When trying to run Meteor on Windows:
```
=> Errors prevented startup:

   While downloading fourseven:scss@3.2.0...:
   error: Command failed: C:\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild --no-bin-links --update-binary
   Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/win32-ia32-46_binding.node": HTTP error 404 Not Found
```

Meteor 1.4 on Windows

Packages:
```
http@1.2.8
less@2.7.4
email@1.1.16

accounts-base@1.2.9
accounts-facebook@1.0.10
service-configuration@1.0.10
iron:router

materialize:materialize
themeteorchef:jquery-validation

yuukan:streamy
mizzao:user-status
mizzao:jquery-ui

peerlibrary:reactive-publish

ecwyne:mathjs
jparker:crypto-md5
percolate:momentum

meteor-base@1.0.4
mobile-experience@1.0.4
mongo@1.1.10
blaze-html-templates@1.0.4
session@1.1.6
jquery@1.11.9
tracker@1.1.0
logging@1.1.14
reload@1.1.10
random@1.0.10
ejson@1.0.12
spacebars@1.0.12
check@1.2.3
standard-minifier-css@1.1.8
standard-minifier-js@1.1.8
matdutour:popup-confirm
```

I see that win32-ia32-44_binding.node is available, maybe that one can be used instead?
![3 2 0](https://cloud.githubusercontent.com/assets/112515/17252873/9ae96c50-55ae-11e6-8467-4bf3e346dd8c.png)

**Comment by cope** [comment]
I've tracked this issue to `.meteor\packages\materialize_materialize\0.97.7`, as it seems to be the only place that uses fourseven:scss

**Comment by cope** [comment]
I've solved the issue by commenting out `materialize:materialize` from packages, then adding fourseven:scss and meteor started properly, as I expected, since it took the latest version of scss which is 3.8 something. Then I uncommented `materialize:materialize` and crossed my fingers. It worked.

**Comment by abernix** [comment]
(Cross-posting/copy-paste from your issue on `materialize:materialize`)

Yes, this is due to `materialize`'s dependency on `fourseven:scss@3.2.0`.  `fourseven:scss` made (necessary) changes to work with Meteor 1.4.  In addition, Version 3.2.0 of `fourseven:scss` has a cross-dependency on the same version of `node-sass@3.2.0` which is over a year old.  For some (newer) operating systems like Ubuntu 16.04, the installation of this package will fail entirely because the 3.2.0 bindings aren't published for all platforms, requiring users to have their own compiler toolchain.

Changing `materialize:materialize` to use `fourseven:scss@3.8.0_1` and bumping the release version would be the the fix for the rest of the Meteor community who are also experiencing issues.  Hopefully the issue you opened over there will get some attention!
