### ISSUE TITLE
Set meteor-install-tmp in /tmp instead of $HOME for Unix install script

### ISSUE THREAD

**Issue by BlackYoup** [meteor/meteor#7540]
Hi,

Is there any reason for the `.meteor-install-tmp` directory to be created by default in `$HOME` instead of `/tmp` ? (in `scripts/admin/launch-meteor`).
`/tmp` is about temporary files so why download + decompress the tarball on the user's home ? (also, it can be a tmpfs which may be faster).

I can make a PR about that if you want. The change would be to update the `INSTALL_TMP_DIR` and `TARBALL_FILE` variables to point to the right directory.

Arnaud

**Comment by abernix** [comment]
That "temp" directory ultimately gets renamed to `.meteor` so it's really just a place to dump the download – it's not temporary in the sense that it's going to be deleted.  In fact, putting it on `/tmp` and then moving it to the users home directory could be less efficient since they might be on different file systems and necessitate a copy.

Happy to discuss further, but I'm not seeing the benefit here as ultimately the Meteor installation is installed in your home directory.
