### ISSUE TITLE
Meteor tool 1.4.0.1 first run

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7546]
I use Codeship to test and deploy my app. I've run into an issue with binary deps and the first build that gets completed after cloning a Meteor repo.

I'm on Meteor `1.3.5.1`, and after cloning my repo and running `meteor npm version` for the first time I get the following:

```
{
    'casalova-web': '0.55.14',
    npm: '3.10.5',
    ares: '1.10.1-DEV',
    http_parser: '2.5.2',
    icu: '56.1',
    modules: '46',
    node: '4.4.7',
    openssl: '1.0.2h',
    uv: '1.8.0',
    v8: '4.5.103.36',
    zlib: '1.2.8'
}
```

This is incorrect since Meteor `1.3.5.1` runs on node `v0.10.46`. This means that if I do a `meteor npm install`, the wrong versions of binary deps get build and `node-sass` has the wrong bindings.

I worked around this by manual setting the `node` version to `v0.10.46` to work with Meteor `1.3.5.1`, but this should be working properly with the Meteor tool out of the box.

Once I run `meteor build` once, the next time I run `meteor npm version` it will have the correct version.

**Comment by benjamn** [comment]
Ah, yes, that is most likely because the `.meteor/local` directory does not exist yet, so [this check](https://github.com/meteor/meteor/blob/57a28eafff7c173f4889ff1feec5940f36cc12e1/tools/cli/dev-bundle.js#L31) fails.

I will fix this in 1.4.0.2 or 1.4.1, but if you need a workaround in the meantime that's less expensive than running `meteor build`, I believe `mkdir .meteor/local` (or `md .meteor\local` on Windows) will work.
