### ISSUE TITLE
Facebook auth from access token

### ISSUE THREAD

**Issue by gsabran** [meteor/meteor#7556]
I've recently work on getting the Facebook authentication to work directly from an access token (mobile clients directly acquire an access token)

Here is an example of how my API looks like: https://gist.github.com/gsabran/8bab053beb05a0a5bf871b4caa00f9b6

Let me know if it is of interest of getting part of that in the Facebook package. Things that would make sense there could be:
- test that the access token sent from a client correspond to the registered fb app id
- acquiring the expiration of an access token directly from facebook
- updating (and creating if needed) the user that corresponds to the facebook account

**Comment by abernix** [comment]
As mentioned in https://github.com/meteor/meteor/pull/7550#issuecomment-237077107, and in the push toward compartmentalizing various components, Meteor  is currently looking for maintainers/contributors interested in working on particular aspects of the less-core Meteor ecosystem which they are more familiar with.  `facebook` is definitely one of those packages and frankly, packages such as `facebook` haven't changed in a while and could probably use some new features/love (see also: [crude list of ~20 issues which might be relevant](https://github.com/meteor/meteor/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20facebook%20in%3Atitle)).

If there are features, like the ones you mentioned above, that Meteor is missing and that the community is working around or lacking, I think these features are welcome so long as they come with explanations of why they are necessary and how the current offerings are insufficient (because honestly, I don't know if anyone monitoring issues is super familiar with their need – I know I'm not).

Do you think the issues you mentioned above should be separate feature requests and accept votes from users?  Or you just want to give it a go?

**Comment by gsabran** [comment]
I can give it a go!

**Comment by abernix** [comment]
Any updates on this @gsabran? :smile:

**Comment by hwillson** [comment]
Since there hasn't been any activity/interest in this issue in a while, I'll close it for now. Happy to re-open if anyone wants to re-visit this - thanks for posting this originally!
