### ISSUE TITLE
Does the the cordova build that is packaged with meteor 1.4 support the latest version the cordova-plugin-file 4.1.1

### ISSUE THREAD

**Issue by tlambeir** [meteor/meteor#7561]
It seems like the events of filereader er not being fired when using meteor 1.4 and meteor cordova-plugin-file 4.1.1 when running the application on android 5.0

```
resolveLocalFileSystemURL(pathToFile, function(fileEntry) {
            fileEntry.file(function(file) {
                var reader = new FileReader();
                reader.onloadend = function(event) {
                    // this event does not fire
                    console.log(event.target.result);
                };
                reader.readAsDataURL(file);
            },function(error) {
                console.log(error);
            });
        },function(error) {
            console.log(error);
        });
```

Could it be that the Cordova build packaged with meteor 1.4 doesn't support the most recent version of the cordova-plugin-file. Can I somehow downgrade it or force meteor to install the older plugin version?

Should I create a ticket with Cordova instead of here?

**Comment by abernix** [comment]
You can install whichever version of that `cordova-plugin-file` plugin you would like to install:

    meteor add cordova:cordova-plugin-file@x.y.z

Where `x.y.z` is one of the versions returned from the command:

    meteor npm view cordova-plugin-file versions

**Comment by tlambeir** [comment]
No i cannot


I tried to install an older version of the file plugin like

meteor add cordova:cordova-plugin-file@3.0.0

However when I run my application it automatically installs a newer version of the plugin

WARNING: Attempting to install plugin cordova-plugin-file@3.0.0, but it should have a minimum version of 4.1.1 to ensure compatibility with the current platform versions. Installing the minimum version for convenience, but you should adjust your
         dependencies.

Can i stop meteor from doing that?

**Comment by abernix** [comment]
Ok, I should probably add that it must be a version that is recommended with your current platform – Meteor 1.4 comes with Cordova 6 which wants you to have a newer version of `cordova-plugin-file`.  What is the reason you are trying to use such an old plugin?  Could it be that another package that you are depending on might need to have its dependencies updated?

**Comment by tlambeir** [comment]
The reason I tried that package because someone had a similar issue with phonegap-build and this plugin:

http://stackoverflow.com/questions/35303863/cant-read-a-file-from-android-directory-using-cordova-plugin-file-plugin

Does the latest version of cordova-plugin-file  actually work with cordova 6? How can I find out?

My project is setup using step 1 from the meteor angular tutorial http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

And the only other thing i added is the cordova-plugin-file plugin. Maybe some of the packages used in the tutorial are icompatible with this plugin?

**Comment by abernix** [comment]
I would just try different versions of the plugin as it's presumably compatible with Cordova 6 since it's being actively maintained (it's official repo is [found here](https://github.com/apache/cordova-plugin-file)).  Really though (and I know you asked the best place to ask this earlier), you are better off asking in an Angular-Meteor group.  This repo is for issues with the core Meteor functionality.

While I'm aware of that tutorial, it's not official Meteor and this is the wrong place to ask for support on a Cordova plugin.  I might check https://github.com/Urigo/angular-meteor (the maintainer of that tutorial) for help resources that might be available, the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged `meteor`](https://stackoverflow.com/questions/tagged/meteor).

The only other suggestion I have is something a bit hacky by directly modifying `cordova-plugins`, but realistically there should be a better (read: correct) solution available:

    echo "cordova-plugin-file@3.0.0" >> ~/.meteor/cordova-plugin

Sorry there isn't more to provide here.
