### ISSUE TITLE
Client files in server-side isopacks

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7573]
Reproduction: https://github.com/mitar/meteor-issue7573

If you run that Meteor app and do:

```
$ ../.meteor/local$ grep -r 'Test string.' .
./isopacks/core/os/test.coffee:"Test string."
./isopacks/core/web.browser/test.coffee:"Test string."
```

You see that `test.coffee` exists both for `os` and `web.browser` targets, despite being added only to `client` in `package.js`.

I have found out during some debugging of some issues with targeting. I think it is at least confusing, but I am not yet sure if it is really problematic.

**Comment by abernix** [comment]
I've noticed this before – I'm not sure if this should be marked as a bug or a feature though as I don't believe it's breaking anything.

**Comment by benjamn** [comment]
This inclusion of additional files is intentional, because those files might be imported by other modules that are explicitly added.

The `ImportScanner` does not run compiler plugins itself, so If we don't include these files when running compiler plugins, it won't be possible to import them later.

Explicitly adding a file with `api.addFiles` or `api.mainModule` just means the file will be eagerly evaluated; it doesn't determine whether the file is compiled with compiler plugins.

**Comment by mitar** [comment]
But if I add a file with `api.addFiles` with client only target, why would then a server-side ever try to import that? That would be a bug in the server-side code which tries to import it.

**Comment by mitar** [comment]
> This inclusion of additional files is intentional, because those files might be imported by other modules that are explicitly added.

Yes, but client side things should be able to be imported only by client side. No need to add them to server side to be potentially imported on server?

**Comment by benjamn** [comment]
The CoffeeScript compiler plugin process both client and server files, so `.coffee` files are not "client side things" in the same way that, say, `.html` files are client-only.

Calling `api.addFiles("file.coffee", "client")` causes the file to be evaluated eagerly (as an entry point) on the client, but doesn't (and shouldn't) forbid it from being imported by server code.

**Comment by mitar** [comment]
But the issue is that then the server side restarts, instead of just client-side would reload. This means that any change to code which I marked as client-side only and I want to use only on client side, restarts my server side. This makes development much slower.

> Calling api.addFiles("file.coffee", "client") causes the file to be evaluated eagerly (as an entry point) on the client, but doesn't (and shouldn't) forbid it from being imported by server code.

This is a change in semantics from Meteor before 1.3. I am not sure if I would agree with that. When I call `api.addFiles` I am saying that I want to use it on client, and not that I also want to use it on server. This is maybe even related to #6823 as well.

So, what I would say is, that Meteor should work like:
* if I do `api.addFiles("file.coffee", "client")`, then I am saying that this file should be (eagerly) available only one client
* I should be able to add a file to be available on client, lazily (#7867)
* if I then also do import of `file.coffee` from a server-side file, then `file.coffee` should be made available on server-side as well

If I do not import `file.coffee`, then it should not be available on the server, but more, it should not trigger server-side restart, and slowing down everything.

Also, `.html` are not client-only. Blaze Components allow server-side HTML files, so that you can use Blaze for rendering HTML e-mails. So now that we support this feature, it means all `.html` files explicitly set that they will be used only on client, are making Meteor changing server-side every time?

**Comment by mitar** [comment]
OK, so the same thing is happening even with JavaScript only. It is not even just a question of CoffeeScript. I updated the repository above with JavaScript only version. Now that I run `meteor`, I can do:

```
$ ../.meteor/local$ grep -r 'Test string.' .
./isopacks/core/os/test.js:"Test string."
./isopacks/core/web.browser/test.js:"Test string."
```

And if I change the file (added only to client) it reloads the server side.

On the other hand, if I add a file to `client` directory outside `packages`, then it is added only to `./build/programs/web.browser/app/app.js`. Moreover, if I change it, only a client-side refresh happens. Very quickly, very nicely.

It is interesting, that `Test string` is also only available in `./build/programs/web.browser/packages/core.js`. So then the question is: why it is added to isopackage, and why a change to the server-side which is not being used inside the app (not inside `./build/programs/os/`) forces server side reload?

So I would really like to see that one could use packages in the same way as you use top-level directories. If I can do at top-level `client` and then a file is added only on client, why I cannot do the same in the package? If I can mark a file as lazy imported on client outside package, how do I do the same inside?

**Comment by mitar** [comment]
So can we agree that being able to create packages which have client files in the same way as one can do files at the app-level inside `client` directory would be something useful? What would be an API for that?

**Comment by veered** [comment]
@mitar I definitely agree that it would be useful; it could significantly decrease the size of the server bundle and make server-only reloads much faster!

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/7573#issuecomment-256759037, the way this currently works is intentional. That means changing this around is considered a feature request.

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Client%20files%20in%20server-side%20isopacks&body=Migrated%20from:%20meteor/meteor%237573) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
