### ISSUE TITLE
after subscriptionsReady collections count is zero

### ISSUE THREAD

**Issue by lifenglsf** [meteor/meteor#7577]
```javascript
Template.groupchat.onCreated(function(){
	Meteor.subscribe('groups');
	Meteor.subscribe('allusers');
	Meteor.subscribe('chatlogs',this.data.groupid);
});
Template.groupchat.onRendered(function(){
	template = this;
	this.autorun(function(c){
		if(template.subscriptionsReady()){
		console.log(cchatlog.find().count())
		curgroup = cgroup.findOne({_id:template.data.groupid});
		if(!curgroup){
			BlazeLayout.render('mainLayout',{main:'datanotfound'});
		}
		}
		
	})
})
```
console output 0.
how can i get correct collection count

**Comment by abernix** [comment]
Hello,

Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

In addition to checking out the [Todos Example App](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials), we highly recommend you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!

**Comment by lyquocnam** [comment]
try: `this.subscribe(...) `replace for `Meteor.subcribe(...)`
