### ISSUE TITLE
Twitter force_login and Facebook authType not working?

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#7584]
This is about OAuth logins, via these [commits](https://github.com/meteor/meteor/pull/6987)

Twitter offers a [force_login parameter](https://dev.twitter.com/oauth/reference/get/oauth/authenticate) to ask the user to re-enter their password.  This is useful for selecting a twitter account in the case someone has more than one account.  It's coded in Meteor [here](https://github.com/meteor/meteor/blob/5d5cfca5b005b3b25f44ecb0284b39ee4336b1a1/packages/twitter/twitter_client.js#L42)

Facebook offers a similar feature through [auth_type](https://developers.facebook.com/docs/facebook-login/reauthentication) which seems to be encoded in Meteor as [authType](https://github.com/meteor/meteor/blob/5d5cfca5b005b3b25f44ecb0284b39ee4336b1a1/packages/facebook/facebook_client.js#L41)

I'm using the [meteor-link-accounts package](https://github.com/yubozhao/meteor-link-accounts/blob/master/core-services/twitter.js#L16) but neither request seems to be adding these parameters to the URL.  (The link shows the code that calls into Meteor Framework).

Is there an example for this?

Here's a [reproduction](https://github.com/MichaelJCole/meteor-7584-force_login).

The expected behavior is that force_login is passed to twitter, but that doesn't appear to be happening.

**Comment by abernix** [comment]
Thanks for opening this issue.

For Facebook's `auth_type`, you're absolutely right – it's implemented incorrectly as `authType` in Meteor.  I don't think it has ever been `authType` [according to the Facebook docs](https://developers.facebook.com/docs/facebook-login/reauthentication) (as you linked to).  Additionally, a cursory look through their API history didn't show anything about it being changed.  It's possible that somewhere in their full JS API (which is not used by Meteor) it's possible that it converts it automatically from `authType` to `auth_type`, but I can't tell.  I've submitted PR #7928 to fix that.

***
As far as Twitter:

Yeah, the implementation of `force_login` is broken there too. *sigh*   I'll try to check it out next week.

**Comment by abernix** [comment]
@MichaelJCole Again, thanks for reporting this.  This should be fixed in the release candidate right now (specifically, `1.4.2-rc.1`).  Hopefully this is finally working properly!

I tested it with your reproduction, and it did in-fact work.  I did run into a bit of a problem getting the `twitter` package to update properly.  I ended up having to manually change the versions of `oauth1` to `@1.1.11-rc.1` and `twitter` to `@1.1.13-rc.1` in the `.meteor/versions` file.  I believe this is unrelated though and might not happen on a fresh project. :)

Please report back if you still have problems with this!

**Comment by MichaelJCole** [comment]
Right on, thanks!
