### ISSUE TITLE
PACKAGE_DIRS environment variable is too generic

### ISSUE THREAD

**Issue by c9s** [meteor/meteor#7585]
Since the name `PACKAGE_DIRS` is too generic, some softwares already use this kind of environment variable for loading packages, for example.. GNU Make also use `PACKAGE_DIRS` and perl modules also use this name.

To avoid the conflict, we can't just add it in our bashrc because the meteor package is totally different.

I would suggest adding a prefix `METEOR_` to the existing `PACKAGE_DIRS`, but keep the original one for deprecation notice.

**Comment by c9s** [comment]
Related issue #227

**Comment by c9s** [comment]
cc @benjamn @abernix

**Comment by laosb** [comment]
Actually in your pr there is no notice outputs to users. Many users don't read History.

Generally it's fine for me(read: I don't use this env). Wait for other's reaction.

**Comment by abernix** [comment]
@c9s Please don't directly mention people when opening issues (I deleted it).  Everyone sees what they need to see within a few days.   Thank you.

> GNU Make also use PACKAGE_DIRS and perl modules also use this name.

I believe that both of these are false statements.  GNU uses `PACKAGE_DIR` not `PACKAGE_DIRS` and Perl uses `PERL5LIB` and `PERL6LIB` (and maybe `PERLLIB` still too).

But, with that being said, I get your point.  I do believe that Meteor `ENV` variables should start with `METEOR_` and this might be a good solution for #4204 – which is potentially a breaking change. 

Since I'm fairly sure this change would only affect development and I don't _feel_ this is a very common feature, I would propose:

* The existing `PACKAGE_DIRS` should print a deprecation warning that it has been changed to use `METEOR_PACKAGE_DIRS`.  And this text as a `Console.warn` message with no wrapping:

 ```
For compatibility reasons, the 'PACKAGE_DIRS' environment variable is deprecated and will be removed in a future release of Meteor.  Developers should now use 'METEOR_PACKAGE_DIRS'.
 ```
 * If `process.platform === 'win32'` then an additional message should print:

   ```
Windows developers should now use a semi-colon (;) to separate multiple paths.
   ```
* The existing `PACKAGE_DIRS` variable should keep working exactly as it is right now.
* A comment `//` should specify what version it was deprecated in with this issue number.
* The new `METEOR_PACKAGE_DIRS` variable should use the `;` (semi-colon) separator when `process.platform === 'win32'` and use the `:` (colon) separator for everything else.

That's my thought.

**Comment by c9s** [comment]
Done.

**Comment by c9s** [comment]
I think we can avoid `process.platform === 'win32'` check by using the `path.delimiter`
