### ISSUE TITLE
[Windows 7] Angular2-meteor, Unable to resolve modules: "angular2-meteor/build/meteor_component"

### ISSUE THREAD

**Issue by cooervo** [meteor/meteor#7593]
So I have a meteor app which uses Angular2.

After installing dependenciens with `meteor npm install` and launching app with `meteor` I get:

```
Unable to resolve some modules:
"angular2-meteor/build/meteor_component" in path/to/my/dir/...

If you notice problems related to these missing modules, consider running: 
   meteor npm install --save angular2-meteor
```

Off course I tried using `meteor npm install --save angular2-meteor` and still doesn't work. I read some where to use node 5 or 6 and latest npm, I have done that and still get same error.

**Comment by abernix** [comment]
I'm not sure where you read the recommendation to try using Node 5 or 6 as Meteor does not recommend using anything other than the compatible corresponding version (Node 4 for Meteor 1.4 and Node 0.10.x for previous versions).  Additionally, I wouldn't suspect that a Node version difference was responsible for this sort of error.

You haven't really provided enough information to debug your problem here though (including not specifying what version of Meteor you were using) nor are Meteor Issues the place to ask such a question.  Please consider asking for help on the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor).  If you truly feel this is a bug, then you may ask for this issue to be reopened if you provide a bare-minimum reproduction of the problem which clearly shows it as a bug.
