### ISSUE TITLE
Google OAuth login in Cordova never calls back when google oauth popup is closed without logging in

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#7602]
Meteor 1.3.4.1

Steps to reproduce:
1. Call `Meteor.loginWithGoogle({...}, function(err) { console.log('done', err); })`.
2. Close the OAuth popup (hit `done`) without actually choosing any of the Google accounts.

Result:
The callback never gets called.

Expected result:
The callback gets called with an error.

BTW, I'm using `loginStyle: 'redirect'` but it doesn't seem to change when I change that to `popup` (looks like I get a popup in both cases).

**Comment by abernix** [comment]
Per [the Meteor Docs on `accounts`](https://docs.meteor.com/api/accounts.html#Meteor-loginWith<ExternalService>), the callback can not be run when using the `redirect` option for `loginStyle`.

Have you tried using the [client-side login-hooks](https://docs.meteor.com/api/accounts-multi.html#AccountsCommon-onLoginFailure) to see if you can accomplish what you are trying to do?

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem.

Also, please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is expected when opening an issue.
