### ISSUE TITLE
Wrong error description from test runner when assertions fail

### ISSUE THREAD

**Issue by zenweasel** [meteor/meteor#7603]
### Expected Behavior
Meteor test runner should show an accurate description of why test failed

### Actual Behavior
Test runner shows ` Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.` even though the test failed because of a failed assertion

### How to reproduce this error
Run test runner on this repo: https://github.com/zenweasel/meteor-testing-bug
`SERVER_TEST_REPORTER="dot" meteor test --once --full-app --headless --driver-package dispatch:mocha`

### Meteor Version
`METEOR@1.4.0.1`

**Comment by abernix** [comment]
Something you might not be expecting is happening...

Since you're calling this test from the server and calling it with a callback (i.e. `Meteor.call('name', function (error, result) {...});`), it's executing the callback after the method is called but it's executing under a different context and the callback itself is being (perhaps not-so-obviously, [through this code](https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/ddp-server/livedata_server.js#L1582-L1590)), wrapped in a `try`/`catch` via `Meteor.bindEnvironment` (via [this code here](https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/meteor/dynamics_browser.js#L31-L61)) in order to make sure it runs within the same server fiber and the server can wait appropriately.

Then, since Mocha's `expect` throws the actual error, the test runner can't see the true issue, `done` never gets called, and the test just times out.

You can solve this by either:

0. Calling `Meteor.call` synchronously without the callback (which is what happens anyway) _(I'd probably recommend)_:

  ```js
  const result = Meteor.call("test/thisMethod");
  expect(result).to.be.true;
  ```
0. Catching the error yourself:

  ```js
      Meteor.call("test/thisMethod", function (error, result) {
        try {
          expect(result).to.be.true;
          done();
        } catch (err) {
          done(err);
        }
      });
  ```

Closing as I'm confident that this is what is happening.  You'll see the correct error and proper response via one of these methods.  Hope this helps explain!

**Comment by zenweasel** [comment]
Unfortunately this same error occurs whether you call the method asynchronously or synchronously.
