### ISSUE TITLE
Can't use private NPM servers that require authentication

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#7636]
Commit https://github.com/meteor/meteor/pull/7162/commits/a8063e81f7ddb25c541af85c9b4b4d48fe890322 made it so that if you use a private NPM server, Meteor tool will check if that one's available instead of the default one. This is good, but the problem is that most private NPM servers require authentication, even for get requests. 

This will result in meteor throwing:
`error: Can't install npm dependencies. Are you connected to the internet?` even if the server is available.

**Comment by benjamn** [comment]
You might need to set the `$NPM_TOKEN` environment variable? https://docs.npmjs.com/private-modules/ci-server-config

**Comment by sebakerckhof** [comment]
That's not the problem. The problem is meteor checks if the registry url is available using a normal http get request. If it isn't or errors, it will halt.

**Comment by abernix** [comment]
This will be fixed in a future stable release of Meteor but is available in beta right now (specifically, `1.4.2-beta.7`)

The beta channel isn't always bug free and you may run into unrelated bugs, but if you're in a position to test that this particular feature has been fixed for you, it would certainly be appreciated.  You can find instructions for using the current beta release in #7668.

Please report back if you still have problems with this!
