### ISSUE TITLE
[Up for grabs] Optimize ClientTarget#minifyCss

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#7673]
**Normally I would assign this to myself, but it seems like a nice task for an outside contributor, since it shouldn't require a deep understanding of the Meteor build tool. If you're interested in tackling this, or have any insight to share, please comment below!**

A number of [profiling](https://github.com/meteor/meteor/issues/7493#issuecomment-235777225) [reports](https://github.com/meteor/meteor/issues/7493#issuecomment-240765913) have indicated that [`ClientTarget#minifyCss`](https://github.com/meteor/meteor/blob/88db65c8378336d20104792c7f2ce3604afa7d74/tools/isobuild/bundler.js#L1239) is taking too long, especially when an app has many `.css` files.

I suspect a large part of the problem lies in composing CSS source maps, which happens [here](https://github.com/meteor/meteor/blob/88db65c8378336d20104792c7f2ce3604afa7d74/packages/standard-minifier-css/plugin/minify-css.js#L107-L113), and takes more than 8 seconds in the Workpop profile.

I'm not even sure that code is doing what it claims to do, since `originals` contains all the CSS files that are being combined, and `newMap.applySourceMap` is a method that you're supposed to call when there are multiple transforms at work, such as SCSS-to-CSS and CSS-to-minified-CSS.

Suggested approach:

- [ ] To measure your optimizations accurately, you'll want to have a test app with lots of `.css` files, and you'll want to run it with `METEOR_PROFILE=100 meteor`. Make sure you have enough `.css` files so that `ClientTarget#minifyCss` and `composing source maps` shows up in the profile.

- [ ] As a first step, I would try simply disabling the source map combination code, to approximate the ideal performance improvement.

- [ ] As a second step, if you believe the source map combination code is important enough to justify the cost, I would try to rewrite it using [the `sourcemap.SourceNode` API](https://www.npmjs.com/package/source-map#sourcenode).

Your changes should be confined to the `standard-minifier-css` package, which is good news because it means that we can release a new version of that package without having to do a whole new Meteor release.

**Comment by veered** [comment]
I opened a PR that does the most basic possible implementation of this optimization [here](https://github.com/meteor/meteor/pull/5875). Apparently this implementation has some issues, but I've been using it on our large web application for 6+ months without a single issue.

**Comment by arist0tl3** [comment]
To follow up, I've been using the solution @veered posted for ~2 months on a medium-sized project. Client-side changes used to look like:

```
ClientTarget#minifyCss............................5,336 ms (1)
|    │        └─ mergeCss.......................................5,245 ms (1)
|    │           ├─ CssTools.parseCss                           2,480 ms (32)
|    │           ├─ CssTools.mergeCssAsts.........................242 ms (1)
|    │           │  └─ CssTools.rewriteCssUrls                    182 ms (32)
|    │           ├─ CssTools.stringifyCss                         886 ms (1)
|    │           ├─ composing source maps                       1,390 ms (1)
|    │           └─ other mergeCss                                247 ms
```

After:

```
ClientTarget#minifyCss                                4 ms (1)
```

**Comment by klaussner** [comment]
As far as I can tell, having many `.css` files is not a problem for source map composition. The excessive build times are a result of resolving chains of source maps from the final bundle to the original source files.

I profiled two builds, one with 1000 `.css` files and one with 1000 `.less` files (both `.css` and `.less` files have the same contents, I just changed the extension). Source map composition is only problematic for `.less`:

`.css` build:
```
mergeCss...........5,698 ms (1)
  parseCss.........2,570 ms (1001)
  stringifyCss.....1,865 ms (1)
  SOURCE MAPS........726 ms (1)
  …
```

`.less` build:
```
mergeCss..........74,165 ms (1)
  parseCss.........2,886 ms (1001)
  stringifyCss.....1,708 ms (1)
  SOURCE MAPS.....68,969 ms (1) !!
  …
```

If a source map is generated by a previous build step (in this case `.less` to `.css` compilation), the plug-in uses that to map from the concatenated bundle to the intermediate `.css` files and then back to `.less` (see diagram below), which is really slow. If there are no source maps for the `.css` files (i.e., if plain `.css` files are used in the application), the plug-in can use the source map generated by `stringifyCss` instead.

I couldn't figure out how to speed this up because the concatenated CSS is generated from a modified AST and the resulting source map is the only information available to get from the bundle to the original `.less` files.

![meteor-css](https://cloud.githubusercontent.com/assets/1312807/18616887/89fe039a-7dc4-11e6-9054-3d951aefd2ce.png)

**Comment by benjamn** [comment]
Wow, great work @klaussner! This makes a lot of sense. I wonder what we can do to speed up the composition. Perhaps the source maps generated by the compiler plugin for `.less` files are too detailed, and we could strip them down to just one mapping per line.

**Comment by klaussner** [comment]
I think reducing the number of mappings wouldn't help much because the generated source maps are already quite small. But I found out a bit more about `applySourceMap`:

The part of `applySourceMap` that looks up the positions in the applied source map seems to be fast enough. In total, it takes 200-300 ms for 1000 files with 100 lines each. However, `applySourceMap` processes _all_ mappings of the large, concatenated CSS file and performs the lookup only for mappings that belong to the source map that is being applied. This is the case for only 0.1% of all mappings in my test app, so the function is doing a lot of unnecessary work.

Considering that `applySourceMap` is called for each intermediate `.css` file, the 'composing source maps' part of the build plugin has a complexity of Θ(n²m) where n is the number of files and m is the average number of mappings per file.

It would be better to do it the other way around: iterate once through all mappings of the concatenated file and find the original source position for each mapping. That would reduce the run time by a factor of n.

**Comment by klaussner** [comment]
#7877 fixes the problem and should produce the exact same source maps as before. I will test this a bit more in the next few days, though. Maybe these changes would also help fixing the performance problems with PostCSS mentioned in #7668?

Before:
```
ClientTarget#minifyCss...........................59,222 ms (1)
├─ mergeCss......................................59,059 ms (1)
│  ├─ CssTools.parseCss                           1,630 ms (1000)
│  ├─ CssTools.mergeCssAsts                         115 ms (1)
│  ├─ CssTools.stringifyCss                         882 ms (1)
│  ├─ composing source maps                      56,109 ms (1)
│  └─ other mergeCss                                323 ms
└─ other ClientTarget#minifyCss                     163 ms
```

After:
```
ClientTarget#minifyCss............................3,708 ms (1)
├─ mergeCss.......................................3,597 ms (1)
│  ├─ CssTools.parseCss                           1,583 ms (1001)
│  ├─ CssTools.mergeCssAsts                         114 ms (1)
│  ├─ CssTools.stringifyCss                         846 ms (1)
│  ├─ composing source maps                         932 ms (1)
│  └─ other mergeCss                                108 ms
└─ other ClientTarget#minifyCss                     111 ms
```

**Comment by arggh** [comment]
This is awesome.

**Comment by benjamn** [comment]
Thanks again to @klaussner for tackling this important issue! There may be other possible `ClientTarget#minifyCss`-related performance optimizations, but #7877 was exactly what I was hoping for when I opened this issue back in August. Cheers!

**Comment by klaussner** [comment]
It was fun to figure this out. 😊 The issue description made it really easy to start contributing, so it would be great to see more issues like this–with a short assessment of the problem and a suggested approach–in the future.
