### ISSUE TITLE
Any possible way to use imports in packages.

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7681]
We at Workpop are trying to move away from Packages. We are making considerable strides moving from our Package based architecture to imports! 

Our current limitation is using our imports in packages. I was wondering is there any way we could use imports in packages OR provide an alternative migration path strategy? Currently working at the leafnodes prevent us from moving fast. Ideally I'd love to do something to transform the packages to imports ASAP.

**Comment by trusktr** [comment]
This is a question better suited for the [forums](http://forums.meteor.com).

**Comment by laosb** [comment]
What @trusktr said.

**Comment by abhiaiyer91** [comment]
The forums? Where conversations go to die? and No real feedback from people who work on the product? GREAT! TO the forums.

**Comment by laosb** [comment]
Following the Issue Triaging Guide, questions like that should go to forums. Though, I agree with you on the atmosphere of Forums, which is pretty bad and most posts end up with nothing (even without any conversation). Anyway, I'm just doing what they told me and I think issues should always for FR/bugs, too. 

So changing this into a feature request form may make sense, like *[FR]`import` in packages* and remove your questions in your issue.

**Comment by stubailo** [comment]
> No real feedback from people who work on the product? 

This issue is a question. Questions are not immediately actionable tasks for maintainers of an open source project. That is why questions like this are redirected to the forums, where other people can help you figure out a solution.

If the conclusion is that some change needs to be made to the code in this repository, then it's the right time to open an issue about it.

**Comment by trusktr** [comment]
> and No real feedback from people who work on the product? 

Actually, I see MDG devs reply to questions quite often.

Also, this topic is actually already covered in the Meteor Guide (I've converted Atmosphere packages to imports before) as well as here in some other issues (sorry, not time to hunt down links at the moment). The gist: just `export` stuff instead of using `api.exports`. Then, `import whateverYouExported from 'meteor/your-package'` or `import whateverYouExported from 'meteor/your-package/path/to/specific/file'`, or just move your code into your app instead of having an Atmosphere package at all.

Go to https://guide.meteor.com, then in the search box type "modules".

**Comment by trusktr** [comment]
Alright, I hunted for you, this may help: https://github.com/meteor/meteor/issues/5788

;)

**Comment by abhiaiyer91** [comment]
@trusktr Thats not the solution I'm looking for. The goal is to not have any Meteor packages. But the problem I illustrated above is I can't take a meteor package from `/packages` that is depended on by several packages into imports. I would have to move leaf node packages first then the one that is the common dependency.

Today, we don't have a way to do that so it's harder to get out of package hell faster without some heavy cost upfront.

I was looking to see how we could use imports in packages just to migrate out of the packages pattern OR an alternate strategy that still achieves the end goal: NO packages.

**Comment by trusktr** [comment]
Converting to `api.mainModule` and using `export` instead of `api.export` may be the way to transition. That's what I did when converting all `/packages` in an app to modules. Then, `import {foo} from 'meteor/foo'` simply becomes `import {foo} from '/foo'` once you move the files from `/packages/foo` to `/foo`.

**Comment by trusktr** [comment]
> But the problem I illustrated above is I can't take a meteor package from /packages that is depended on by several packages into imports. 

Yes you can. Packages can import from the app by referring to the root. So, if you move a non-leaf package to the app root (f.e. move /packages/foo to /foo), then you modify the dependent packages to use `import {foo} from '/foo'` instead of `api.use`.

**Comment by abhiaiyer91** [comment]
> by referring to the root

I'm not sure I follow.

I have a module defined in `/imports`. From the errors I have seen, the package cannot find that module form imports.

`[EXCEPTION][ERROR] Uncaught Error: Cannot find module '/imports/workpop-customers-page/client/components/CustomerPage'  >>> Error: Cannot find module '/imports/workpop-customers-page/client/components/CustomerPage'`

**Comment by trusktr** [comment]
Doesn't matter where in the app it is, it's just `import foo from '/any/path/relative/to/the/root/of/the/app'`, but there appears to be a bug as it is not working for me either (I recall it was working before, plus this part doesn't seem to be well-documented), so I opened a new issue: https://github.com/meteor/meteor/issues/7704
