### ISSUE TITLE
[1.4] Error when accessing HTML file in /public

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#7684]
I'm having some issue when I try to access a HTML file within my <code>public</code> folder. After accessing it via iFrame, the whole server crashes:

```
=> App running at: http://localhost:3000/
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:430:15)
    at IncomingMessage.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:759:26)
    at resume_ (_stream_readable.js:739:3)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

Process finished with exit code 1
```

If I call it directly, I also noticed that there was some "error text" added in the document:

<code>Unexpected error.html lang="en"></code>

This is my HTML file, saved as <code>/public/banner.html</code>:

```
<!DOCTYPE html>
<html lang="en">
<head>
<style>
    html,body {
        padding: 0 0;
        margin: 0 0;
        width: 100%;
        height: 100%;
    }
</style>
</head>
<body>
<div style="width: 100%;">
    <script src="some ad code"></script>
</div>
</body>
</html>
```

//Edit: Seems like removing <code><!DOCTYPE html></code> solves that issue.

**Comment by laosb** [comment]
That sounds like `templating` was handling HTMLs in public. Terrible.

**Comment by laosb** [comment]
Not sure which project.

**Comment by abernix** [comment]
This sounds like it confirms that Meteor is not only watching the `public` directory for changes (which I'm almost certain Meteor does, possibly for good reason), but also running the files through compilers?  #6952.

That being said, a simple reproduction of this in a Git repo would be appreciated for testing/debug/fixing purposes.

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem, it lacks a reproduction, and it seems like it could be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
