### ISSUE TITLE
[1.4.1] Unable to import app modules into a package.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#7704]
I have an app with the file `/client/main.js` and a package `foo` in `/packages/foo` that imports from `/client/main` but Meteor throws an error that the module cannot be found.

Reproduction:

``` sh
git clone git@github.com:trusktr/meteor --branch issue-7704 --single-branch
cd meteor
./run-dev.sh
```

then visit [localhost:7654](http://localhost:7654).

The error is:

```
Error: Cannot find module '/client/main.js'
    at Function.require.resolve (packages/modules-runtime/.npm/package/node_modules/install/install.js:101:1)
    at Module.resolve (packages/modules-runtime/.npm/package/node_modules/install/install.js:57:1)
    at Module.Mp.import (/Users/trusktr/.meteor/packages/modules/.0.7.5.60d8mq++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:61:29)
    at meteorInstall.node_modules.meteor.foo.foo.js (packages/foo/foo.js:1:17)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /Users/trusktr/src/meteor+meteor/meteor-app/.meteor/local/build/programs/server/packages/foo.js:31:15
    at /Users/trusktr/src/meteor+meteor/meteor-app/.meteor/local/build/programs/server/packages/foo.js:37:3
    at /Users/trusktr/src/meteor+meteor/meteor-app/.meteor/local/build/programs/server/boot.js:297:10
    at Array.forEach (native)
```

**Comment by benjamn** [comment]
Importing modules into a package from an app currently only works for npm packages in the app's `node_modules` directory.

What's your use case?

**Comment by trusktr** [comment]
One use case is that it would help people transitioning from Atmosphere packages to modules, as in https://github.com/meteor/meteor/issues/7681. So that the app can work while only some of the packages have been converted (moved from /packages to the app).

**Comment by wallslide** [comment]
I've run into this problem a lot, and it's forced us to move a lot of code backwards into packages rather than using the `/imports` directory.

In the latest case, we have a fulfillment system that takes several different order types, and merges them together into a single view. Each order type has its own collection.

We have recently added a new order type, written a UI for it, utils, etc, everything using the new modules and the `/import` folder. Now I'm integrating it into our fulfillment system. Unfortunately the fulfillment system needs to access the collection for the new order type.

Since we can't import the collection into the existing fulfillment system package, and can't define a collection twice, now I have to migrate a bunch of the files related to our new order type into a package (collection definition, schema definitions, enums, etc.), otherwise our existing fulfillment package can't use them. Then I have to refactor the files relying on those files that I moved into a package. All because I can't just import my collection which is defined in `/imports` into an existing package :(

**Comment by wallslide** [comment]
And if I have any general utility functions that are used by any package, then those also need to be a package, which is frustrating. Or if at some point I decide to use one in a package, then I then have to go through the refactoring process of first moving it into a package, then refactoring everything that used to point to it in order to allow it to be used from within a package.

**Comment by trusktr** [comment]
That is indeed annoying! Hopefully that can be changed.

**Comment by timbotnik** [comment]
👍  @benjamn going to upvote as we could really use of this too!

**Comment by dr-dimitru** [comment]
👍  We would like to add dynamic imports support to [`flow-router-extra`](https://github.com/VeliovGroup/flow-router) package. This is impossible now as we can not access application' `/imports` from the package.

Use case:
In app:
```js
FlowRouter.route('/page', {
  name: 'page',
  action() {
    this.render('_layout', 'page');
  },
  import: ['/imports/client/page.js'],
  whileWaiting: startSpinner,
  endWaiting: stopSpinner
});
```

In the package:
```js
const importDeps = () => {
      for (let i = _imports.length - 1; i >= 0; i--) {
        _imports[i] = import(_imports[i]);
      }

      Promise.all(_imports).then(() => {
        next(current, this._data && getData());
      }).catch((err) => {
        throw err;
      });
    };
```

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5B1.4.1%5D%20Unable%20to%20import%20app%20modules%20into%20a%20package.&body=Migrated%20from:%20meteor/meteor%237704) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
