### ISSUE TITLE
why run 1.4 Meteor project on 1.4.1.1, it try to download 1.4.0 Meteor-tools

### ISSUE THREAD

**Issue by DSDavid** [meteor/meteor#7720]
why run 1.4 Meteor project on 1.4.1.1, it try to download 1.4.0 Meteor-tools
Downloading meteor-tool@1.4.0.....

**Comment by laosb** [comment]
It's intended.

**Comment by DSDavid** [comment]
where can i download Meteor 1.4 version

**Comment by laosb** [comment]
If you really need a 1.4 version instead of the latest, you can add a query param to the install command. Actually Meteor will download it for you, you just need to wait for a few seconds to few minutes. If you have problem in meteor's downloading, like stuck in `Downloading xxx@x.x.x...`, please report to #6960.
