### ISSUE TITLE
onAfter callback to onCreateUser?(FR?)

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7741]
Not sure where this should go, but here at Workpop we do a bunch of initialization of other collections when users are created. We were wondering if there was a way to call an 'onAfter' hook once a user is created.

Preferably right here: 
https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_server.js#L1307

The reason I bring this up is some code we have in our onCreateUser callback depends on the user being in the database. Since thats not guaranteed our current solution was observing the users cursor and waiting for an added message to come through.

Any ideas?

**Comment by tmeasday** [comment]
Sounds like a FR. I think we've had people ask for this before.

`Accounts.onAfterCreateUser`?

**Comment by hwillson** [comment]
Just adding a few details for reference (as part of the on-going issue cleanup process); issue #2809 talked about adding this feature, but the request was closed. Observing/watching a `users` cursor for changes was suggested as being a better solution, since an `onAfterCreateUser` callback couldn't be guaranteed to run (if the server crashed just before it ran for example). Between that and this issue however, there are a few upvotes, so I'll leave this issue open for now. Thanks!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=onAfter%20callback%20to%20onCreateUser%3F(FR%3F)&body=Migrated%20from:%20meteor/meteor%237741) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
