### ISSUE TITLE
A way to disable configureLoginService method altogether

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#7745]
I do not like how there is a `configureLoginService` method available which allows configuring service the first time without any permission checks. This means that anyone who installs my app and does not configure all services my app otherwise integrates (and uses their packages) can get their services configured by somebody, no? And this could then open others to login into the app using a different authentication mechanism then expected.

**Comment by hwillson** [comment]
Hi all - just reviewing this issue a bit. Currently, [there are safeguards in place](https://github.com/meteor/meteor/blob/42ab2fd607d0bf0c33613d73a44135b982ff321e/packages/accounts-base/accounts_server.js#L665-L668) to prevent the following (extracted from https://github.com/meteor/meteor/commit/37201062e1233ee6cb4627016303e40d1ad3fa4a):

> - Alice launches site with Facebook login
> - Mallory sends configureLoginService method to configure the Twitter service
> - Alice runs "meteor add accounts-twitter" and is impressed that Twitter integration
    Just Works with no configuration
> - Now the app is using Mallory's credentials

The problem that remains (as I understand it) is covered under the following scenario:

- Alice ships an app (that others can install themselves) with the `accounts-twitter` package installed, but no initial service configuration has been completed (since the idea is that people who install the app will take care of this themselves).
- Mallory installs a copy of Alice's app without taking care of the initial Twitter service configuration.
- Bob notices this and fires in a `configureLoginService` method to configure the Twitter service using his credentials
- Pwnage?

Given the above scenario, how would we go about locking this down? The  `configureLoginService` Method exists to help facilitate wizard-style UI's for the initial service configuration, so locking it down further could hamper this feature. I know this issue has been marked as `pull-requests-encouraged`, but I don't think we have enough of a plan broken out here to help contributors.

**Comment by mitar** [comment]
(I took a liberty of replacing Mallory and Bob names in above scenario, because in many such scenarios Mallory stands for a malicious one.)

**Comment by mitar** [comment]
Yes, the above scenario explains it well. The existing code does not seem to protect it.

What I would do is simple allow one to ship an app without `configureLoginService` enabled. This is what me as an app developer would want. That I can ship an app without it, and provide my own admin panel with my own configuration for admins (which I am already doing) and then I can check permissions in my custom way to allow only people in admin group or something to do it.

Personally, I would do it so that if no `-ui` package (with Blaze ;-) ) for accounts is present, this method is disabled. If you add any such package, which provides easy configuration, then you get this fancy method. Otherwise, no method, no ui (no Blaze). I think now that we moved ui out of packages because of removing Blaze, we could also move out this method.

**Comment by hwillson** [comment]
Thanks @mitar - I prefer the opt-in approach as well. This sounds great!

**Comment by mitar** [comment]
So, just to be clear, opt-in has slight backwards incompatibility if you have been relying on it being present in the base package, but not using ui package. But I think it is worth it.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=A%20way%20to%20disable%20configureLoginService%20method%20altogether&body=Migrated%20from:%20meteor/meteor%237745) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
