### ISSUE TITLE
Load "ecmascript" package prior to all other packages

### ISSUE THREAD

**Issue by Twisterking** [meteor/meteor#7756]
So today I ran into a big problem. I had added Aldeed's "simple-schema-index" package, and [this line](https://github.com/aldeed/meteor-schema-index/blob/master/lib/indexing.js#L45) caused me many troubles. Unfortunately many users of my meteor app still use IE9 (don't ask), and this line's `const` broke the whole app. I asked about what to do [here](https://forums.meteor.com/t/es5-6-polyfill-for-ie9/28962).

I had the idea to add 
```
Package.onUse(function (api) {
  api.use('ecmascript');
});
```
to the `package.js` of Aldeed's package and this seems to have fixed all my issues!

Some developers seem to forget about this line in their `package.js`. Some may even have a hard time to realize this "mistake" as they don't test their package in legacy browsers.
So I propose the following: make the `ecmascript` package part of `meteor-core` and thus **load it before any other packages are loaded** to prevent stuff like this from happening. I'm gonna make the wild assumption that there are many packages out there who forget about the `ecmascript` package.
Having to `git clone` packages like this one only to add this line is not a good solution obviously.

Let me know what you guys think. Rock on Meteor!

**Comment by lassombra** [comment]
This actually won't work.  ecmascript is a build plugin.  The authors of the packages need to include it in order to ensure that their code goes through that build step before publishing to atmosphere.

**Comment by lassombra** [comment]
This actually won't work.  ecmascript is a build plugin.  The authors of the packages need to include it in order to ensure that their code goes through that build step before publishing to atmosphere.

**Comment by Twisterking** [comment]
Well but apparently it is possible to have a public package which is missing the `ecmascript` package while still using ES6 features. Thus stuff like this happens and will happen again. I am not a real hardcore meteor dev but I actually don't really understand why this package can't be part of the meteor core to prevent errors like this from happening?!

**Comment by lassombra** [comment]
`ecmascript `is not required to have a meteor application.  In fact, a package is not required to use it.  Even if it was forced to load first, before all other code in existence, it wouldn't solve the problem you experienced.

Build plugins (which `ecmascript `partially is) are compile time includes.  They are run against your code when it builds (when you start the app, when you deploy, and importantly here *when you publish a package*).  By the time the package is in atmosphere, it is already too late.  Had the package developer in this case used some ES6 function which uglify trips on (such as arrow functions) then they would have gotten a nasty reminder when they tried to publish the package.  However, all they used was block scoping, which gets through uglify, only to later break on IE9.  Because packages are pre-compiled meteor doesn't run them through your chosen build plugins.  This is why you can include a package which depends on coffeescript and not necessarily use coffeescript yourself and it works.  At the end of the day, all packages have been already built.

Because of this, the order in which `ecmascript `loads is not nearly as important as whether the package used it when it should have.  Yes, this will happen from time to time.  One of the pitfalls of open source is that packages like this are not maintained to the rigor that say google would expect a package to be.

Additionally, had the author of that package tested their package against IE9 it would have broken on them, no re-create needed.  That is because their `const `was leaking through instead of hitting up against a babel compile step.  This is important.  The `ecmascript `package *changes the output code* converting it from the input ES6+ code to 100% ES5 code.  And in the case of packages, it does that *before they are published* so if there is a published package which doesn't include `ecmascript `but uses ES6 code, then they are emitting ES6 in all applications that use them.  This isn't something that MDG can fix without forcing `ecmascript `across the board which isn't necessarily a good idea.  Some people are going to make packages in 100% es5 and that should remain allowed, at least for the time being.

**Comment by laosb** [comment]
Things will change since `ecmascript` was already in the `package.js` of new package creation. That's doesn't seem like what we or MDG can solve.

Closing this and please open another one if you get a better solution for this!
