### ISSUE TITLE
Meteor mobile apps do not support Hot Code Push without --mobile-server option to meteor command

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#7760]
I have been struggling to get [Hot Code Push](https://guide.meteor.com/mobile.html#hot-code-push) working on my mobile devices.

Maybe this is **BY DESIGN**?
## Environment

[Mobile App creation]
- MacOS X v10.11.6 (El Capitan)
- Node v4.5
- Meteor 1.4.1.1

[Server]
- Windows 10 Version 1511 (OS Build 10586.545)
- Meteor 1.4.1.1

> Note: I also tried this on my mac as the server with the same results
## Observed

[Mobile App Creation]

```
env ROOT_URL=http://192.168.1.100:4000 meteor run ios-device -p 4000  --mobile-server http://192.168.1.100:4000 
```

This creates the app with the connectivity I want for debugging.

[Launch Server]

```
set ROOT_URL=http://192.168.1.100:4000
meteor –p 4000
```

The app connects and works great.  But no **Hot Code Push**.
## Expected

**Hot Code Push** to the mobile app should work.
## Work Around

I flailed around, consulted with @queso and finally came up with this working scenario:

[Mobile App Creation]

```
meteor run ios-device -p 4000 --mobile-server http://192.168.1.100:4000 
```

This creates the app with the connectivity I want for debugging.

[Launch Server]

```
meteor –p 4000 --mobile-server http://192.168.1.100:4000
```

This launches a server that the mobile device can connect to and also **Hot Code Push** works.
## Meteor commands

The help for the meteor command says this:

```
  --mobile-server  Location where mobile builds connect to the Meteor server.
                   Defaults to your local IP and the port that the Meteor
                   server binds to. Can include a URL scheme (for
                   example, --mobile-server=https://example.com:443).
```

What does

> Defaults to your local IP and the port that the Meteor
>                    server binds to.

mean?  I suspected that the local IP and port was what got displayed when I ran `meteor` e.g.

```
=> App running at: http://192.168.1.100:4000
```

When I ran the meteor command with or without the `--mobile-server` option I get the following output:

```
e:\app>npm start

> APP@0.0.1 start e:\app
> meteor -p 4000

[[[[[ ~\e\app ]]]]]

=> Started proxy.
W20160906-14:00:53.399(-7)? (STDERR) Debugger listening on port 6868
=> Started your app.

=> App running at: http://192.168.1.100:4000
   Type Control-C twice to stop.
```

Is Meteor not setting the default correctly? [I guess we have a bug]
Or am I not configuring properly? [if so, may need to update documentation]
Or is this option required?  [if so, need some better documentation]

**Comment by laosb** [comment]
In most cases we use `--mobile-server` option everywhere when we're developing a mobile app.

I guess (just guesssing without reading the actual code) it's because when you generate the app, you set it to `http://192.168.1.100:4000` manually, exactly "a URL scheme", but Meteor defaults to "your local IP and the port that the Meteor server binds to" in some other ways rather than "a URL scheme". It's a documentation issue if so, or we need to improve the code which is not very necessary.

**Comment by brucejo75** [comment]
@martijnwalraven, can you confirm whether this is a bug or expected behavior?  Thanks!

**Comment by lucfranken** [comment]
@brucejo75 What is the advantage of entering that ip manually for you? We never enter it on local development. We only enter it sometimes when we want to test a new version of our app with a hosted test server for example. Why don't you just use the local development server in this case? Some native Windows functionality?

**Comment by brucejo75** [comment]
Hi @lucfranken,
For most development I use `localhost`.  But when I want to connect to my server with a mobile device with support for hot code push,  I need to specify the IP of the host server for the mobile device.  Mobile device cannot connect to `localhost` because localhost is on the mobile device, see [this](https://guide.meteor.com/mobile.html#configuring-server-for-hot-code-push).

I also wrote up my understanding of how to configure for mobile devices [here](https://forums.meteor.com/t/enabling-hot-code-push-to-mobile-applications/29426).

If you have a simpler way to see the results of your development on a mobile device I would like to understand it.

**Comment by lucfranken** [comment]
@brucejo75 ah that forum post makes much clear!

**Standard way**

If you run this, doesn't it work?:

```
server: meteor –p 4000
client: meteor run ios-device -p 4000 --mobile-server http://192.168.1.100:4000
```

That makes sense right? The server just starts like normal on it's own ip. And because you want to use a custom server you have to inform the client build on that.

**ROOT_URL**

In general: We never manually play with ROOT_URL and things. Meteor should work out of the box. We only use the --mobile-server flag and we use it for every build. On our local machines we never use it. In your forum post you call it a work-around but it is just the standard commands as documented. The ROOT_URL stuff is a work-around actually.

**Disconnect**

Also you write in your forum post that you disconnect the device from your computer. Why is that?

**The custom server**

What is not clear to me is: Why does a developer need to connect to a different server? We always try to have a simple checkout from our repository, run it and it should work. Is there anything special that server is doing? Maybe that makes more clear what you are trying to achieve.

**Comment by brucejo75** [comment]
Correct, that does not work.  It connects to the server but hot code push does not work.

_Maybe this is why I am different:_
My main machine is a windows machine.
I only use my macBook Pro to create and install the mobile applications on my mobile devices: ios and android.

So I run the server on my windows desktop, install the sw on my devices and unplug them and use them while at my windows desktop.

(This is really the only way to go for windows based developers)

The only way that HCP works is if I pass the `--mobile-server` option to the server on startup.  Which is not documented anywhere and I do not understand if it is a bug or feature.

**Comment by lucfranken** [comment]
Ah now I get why you are doing it this way! We use TestFlight to work on mobile when we want to move around (so we have multiple test apps in the App store only available for internal testers). Off course we then keep our Cordova plugins the same otherwise it won't work. 

**On your issue:**

I am not totally sure on this one but I have a guess. Unfortunately I don't have a similar setup to test it in full. What I was looking at this this code which defines the `meteor run` command line:

https://github.com/meteor/meteor/blob/8cdab91bc415433aa693e045534996e5a3ba4f05/tools/cli/commands.js#L341

The meteor command `meteor` === `meteor run`.

When you run: `meteor run ios` this code seems to add the Cordova architecture.  What I expect: The whole Cordova part of Meteor is just not building at all on your server.

**Possible fix**

So what you could try to debug this issue is: Install the Android platform (since you can't run iOS): `meteor add-platform android` and run your app with `meteor run android` since the Cordova architecture is the same for both iOS and Android.

That might make the difference in this case I hope. If that's the case the issue seems a relatively easy fix. But again: It's a guess I am not 100% sure.

Also it would be useful to see your logs from the iOS device (those you can see when you inspect with Safari and those from Xcode).

**Interesting but not directly related to your question:**

Interestingly on the other hand: `meteor build`, which is what we use, seems to have the logic another way around: It has a special option to disable mobile platforms:

```
meteor help build
 --server-only       Skip building mobile apps even if mobile platforms have been added.
```

So the functionality seems to work different based on the command. Quite related on this: https://github.com/meteor/meteor/issues/7144

**Comment by brucejo75** [comment]
@lucfranken, thanks much for looking into this!  That line (or rather the next couple of lines) explain a lot.

I will try your suggestion to verify when I hit a stable point.  I have my server torn apart right now.

It looks like the cordova code will load if I use the `--mobile-sever` option or if I run a target (e.g. `meteor run ios`, `meteor run android`, etc).

I always used `meteor run ios` simply as a quick way to get the app onto my iPhone without going through the process of a `meteor build`.  (I have yet to get `meteor build` to work, need to investigate more).  

The way it works now is a little obtuse.  It is a little strange to run a target as part of the server startup.

### Suggested change
By default hot code push works and you can disable cordova and hot code push if you use the '--server-only' flag.

**default:** If a mobile platform is configured (e.g. `.meteor/platforms` includes one of the mobile targets) then cordova will load for hot code push.

**override:** The `--server-only` flag would disable loading cordova.

**Comment by lucfranken** [comment]
It is reproducible in terms of building like this:

`$ ../meteor-local/meteor/meteor run iOS`

Result:

<img width="1036" alt="schermafbeelding 2016-09-29 om 11 42 26" src="https://cloud.githubusercontent.com/assets/1609379/18949114/2dcac742-863a-11e6-98b3-82c2c6b252ab.png">

`$ ../meteor-local/meteor/meteor run ios`

Result:

<img width="1040" alt="schermafbeelding 2016-09-29 om 11 43 26" src="https://cloud.githubusercontent.com/assets/1609379/18949122/38ebaad8-863a-11e6-97a5-3c2404754de6.png">

If you would need an update of the code for Cordova (via hot code push) I assume the server needs a build for that. Otherwise it cannot send an update I think? I think that's the reason behind it. To fix it you would need to be able to build the Cordova build as well I think.

**Comment by iwoj** [comment]
Usinf the --mobile-server option on the server itself doesn't enable hot code push for me. I can't get it to work at all on iOS or Android. I'm running in dev mode with these local commands:

`meteor run ios-device --mobile-server https://production.domain`

and

`meteor run android-device --mobile-server https://production.domain`

My production server is running with:

`ROOT_URL=https://production.domain meteor --port 4000`

I've got nginx forwarding port 80 to port 4000.

If I update the client code on the production site, mobile and desktop browsers reload the code fine, but iOS and Android cordova builds will not.

**Comment by hwillson** [comment]
Hi all - reading this issue over, it doesn't sound like there is a Meteor bug here, but there are perhaps further improvements that could be made? I'll mark this a feature request (let me know otherwise!).

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Meteor%20mobile%20apps%20do%20not%20support%20Hot%20Code%20Push%20without%20--mobile-server%20option%20to%20meteor%20command&body=Migrated%20from:%20meteor/meteor%237760) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by brucejo75** [comment]
Thanks @hwillson, yes, this is a feature improvement request.  good call...
