### ISSUE TITLE
MongoError: Cursor not found, cursor id: 228742002948

### ISSUE THREAD

**Issue by gabrieli** [meteor/meteor#7763]
Got this error when doing a forEach over a cursor of around 6500 elements. It's a problem on latest version of Meteor, using Mongo 3.2.

Here's the stacktrace: 

2016-09-08T20:47:53.992892+00:00 app[web.1]: Exception while invoking method 'training:senior:run' MongoError: Cursor not found, cursor id: 228742002948
2016-09-08T20:47:53.992903+00:00 app[web.1]:     at Object.Future.wait (/app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:449:15)
2016-09-08T20:47:53.992904+00:00 app[web.1]:     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1021:47)
2016-09-08T20:47:53.992905+00:00 app[web.1]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1055:22)
2016-09-08T20:47:53.992906+00:00 app[web.1]:     at Cursor.cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:126:1)
2016-09-08T20:47:53.992907+00:00 app[web.1]:     at Cursor.kadira_Cursor_forEach [as forEach](packages/meteorhacks_kadira/lib/hijack/set_labels.js:53:1)
2016-09-08T20:47:53.992908+00:00 app[web.1]:     at Monitor.runAndLogOnList (app_modules/monitoring/server/models/monitor.js:40:14)
2016-09-08T20:47:53.992908+00:00 app[web.1]:     at Object.run (app_modules/training/server/senior-cron.js:26:17)
2016-09-08T20:47:53.992914+00:00 app[web.1]:     at Function.MongoError.create (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-

It appears some other mongo drivers are having a similar problem:
https://github.com/Automattic/mongoose/issues/3927

**Comment by laosb** [comment]
According to a reply in your description:

> For others who are experiencing this issue, using mongoose 4.4.10 with MongoDB 3.2, it was just fixed in mongodb-core version 1.3.13.
> 
> christkv/mongodb-core@caa169d
> 
> The MongoDB driver would intermittently throw errors of the form:
> 
> Cursor not found (namespace: 'some.collection', id: 73106491510903863)."
> 
> This would mainly happen on find calls returning more than some random threshold of data.
> 
> I've used npm-shrinkwrap to bump Mongoose's dependency of mongodb-core up to version 1.3.13 from 1.3.9. Hopefully, this version bump will come from the Mongoose team soon.

It sounds like a Mongo Driver issue. If it does fix, we should just need to bump the driver version.

**Comment by abernix** [comment]
@gabrieli Exactly what version of Meteor are you running in your app and what version of `npm-mongo` do you have installed?  Running the following from your project root should provide both of those answers:

    cat .meteor/release && cat .meteor/versions | grep npm-mongo

Also, you said that this is returning a large number of results, but is it taking a very long time to _start_ returning those results or are you doing something within the `forEach` that is taking a very long time?  It's possible that the cursor is expiring (timing out) in the process of returning the results.  Some information on how long this is taking would be helpful.

@laosb Meteor 1.4 has been using `mongodb-core` 2.x since it was released so bumping the driver version likely wouldn't help; Meteor is way ahead of that driver update.

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)

**Comment by acomito** [comment]
I had the same error forEaching over a cursor of about 4M:

METEOR@1.4.2.3
npm-mongo@2.2.11_2

**Comment by abernix** [comment]
@acomito The cursor will timeout if it's taking a long time to iterate over those results.  Please understand though that this is a Mongo issue and not a Meteor issue.  You would experience the same problem on the Mongo shell if you did not take the proper precautions.

You should consider breaking your query up in to smaller groups (recommended) and you may want to look into [`Mongo.setConnectionOptions`](https://github.com/meteor/meteor/blob/release-1.4.2.2/packages/mongo/connection_options.js) which you can call before your collections are loaded to change your default connection settings.  You can also use `rawCollection` if this is an advanced query you need to run.  Please understand that `rawCollection` will not be reactive.

All in all, you'll want to review the Mongo documentation.

**Comment by acomito** [comment]
You're right @abernix. Thanks for taking time to respond.

**Comment by a4xrbj1** [comment]
We're having the same issue but it's only 400 documents in the whole collections and we're taking some selected ones. However, each doc is about 2Mb big, that seem to cause the issue.

METEOR@1.4.4.3
npm-mongo@2.2.24

Any idea how to get around this, @abernix ?
