### ISSUE TITLE
Unable to Npm.depends() to github repo

### ISSUE THREAD

**Issue by nytamin** [meteor/meteor#7771]
When using `Npm.depends` in a package and linking to a github repo:
`Npm.depends({
  "lodash": "git+https://github.com/lodash/lodash.git"
});`

I recieve the following errors during build:

`=> Errors prevented startup:`
`   While building package nytamin:testnpm:`
`   error: couldn't install npm package`
`   lodash@git+https://github.com/lodash/lodash.git: Command failed:`
`   C:\Users\Nytamin\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd`
`   install git+https://github.com/lodash/lodash.git`
`   npm ERR! git fetch -a origin (https://github.com/lodash/lodash.git)`
`   fatal: Unable to find remote helper for 'https'`
`   npm ERR! Windows_NT 6.1.7601`
`   npm ERR! argv`
`   "C:\\Users\\Nytamin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"`
`   "C:\\Users\\Nytamin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"`
`   "install" "git+https://github.com/lodash/lodash.git"`
`   npm ERR! node v4.5.0`
`   npm ERR! npm  v3.10.6`
`   npm ERR! code 128`
`   npm ERR! Command failed: git -c core.longpaths=true fetch -a origin`
`   npm ERR! fatal: Unable to find remote helper for 'https'`
`   npm ERR!`
`   npm ERR!`
`   npm ERR! If you need help, you may report this error at:`
`   npm ERR!     <https://github.com/npm/npm/issues>`
`   npm ERR! Please include the following file with any support request:`
`   npm ERR! C:\SourceTree\testNpmError\packages\test\.npm\package-new-oerj5q\npm-debug.log`
`   npm ERR! git fetch -a origin (https://github.com/lodash/lodash.git)`
`   fatal: Unable to find remote helper for 'https'`
`   npm ERR! Windows_NT 6.1.7601`
`   npm ERR! argv`
`   "C:\\Users\\Nytamin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"`
`   "C:\\Users\\Nytamin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"`
`   "install" "git+https://github.com/lodash/lodash.git"`
`   npm ERR! node v4.5.0`
`   npm ERR! npm  v3.10.6`
`   npm ERR! code 128`
`   npm ERR! Command failed: git -c core.longpaths=true fetch -a origin`
`   npm ERR! fatal: Unable to find remote helper for 'https'`
`   npm ERR!`
`   npm ERR!`
`   npm ERR! If you need help, you may report this error at:`
`   npm ERR!     <https://github.com/npm/npm/issues>`

When linking to a npm-repo it all works fine, but not when linking to a github repo.

I've encountered the issue on Windows 7 & 10, running Meteor 1.4.1.1.

To reproduce:
`git clone https://github.com/nytamin/testNpmError`
`cd testNpmError`
`meteor`

**Comment by abernix** [comment]
This is a common issue ([see Google search results](https://www.google.fi/search?q=Unable+to+find+remote+helper+for+%27https%27+windows)) for Windows when using `git` unfortunately and is out of the control of Meteor (that output is actually an error from `git`).

From my understanding, you will need to either change the URL to something along the lines of:

    git://github.com/user/project.git#commit-ish

Or perhaps try it with `http` instead of `https` as I believe the bottom line is that because of OpenSSL import/export/distribution reasons, the `git` that ships with `npm` does not have the correct SSL libraries to handle `https`, but I'm not certain.

You should also try installing [Git for Windows](https://git-scm.com/download/win) and ensuring it's in your `PATH` as I believe `npm` will properly use that `git` when it's available instead of using its own.  I recommend rebooting after making any changes to your `PATH`.
