### ISSUE TITLE
[dev] `meteor reset` with the option to preserve the database

### ISSUE THREAD

**Issue by abernix** [meteor/meteor#7789]
Running `meteor reset` is very handy for 'repairing' a project that may have become corrupted or is acting funky for _whatever_ reason, but often times (in fact, _usually_, from a support standpoint) wiping the users database is unnecessary.  While it does meet the requirement for a true `meteor reset`, it's a bit overboard for most support issues and usually needs to be prefaced with "btw, be careful, this will wipe your whole dev DB!!!" – because I don't know about most developers, but I like my dev DB the way it is.   What **is** usually desirable is getting rid of `.meteor/local/{build,bundler-cache,isopacks,plugin-cache}` – essentially, everything in `.meteor/local/` besides the `db` directory.

Two initial propositions would be:
- Adding a `--preserve-db` argument to the existing `meteor reset` command
- Adding a `meteor clear-cache` (or any other name _TBD_) command.

Discuss.

**Comment by pozylon** [comment]
I would love to see the second proposition, "meteor clean" command. --preserve-db is risky (chance is higher of accidently do the hard reset).

**Comment by axelvaindal** [comment]
I also would love to see the second proposition.

I suppose it is way much clearer to prepare a second command to do this, either one to clean the database or one to do the emptying .mongo/local thing.

**Comment by jerodmoore** [comment]
meteor clean sounds like a logical name for this function. So logical in fact I gave it a try instinctively when trying to get past some build problems. Meteor reset --operator would be my second.

**Comment by abernix** [comment]
I'm concerned that `meteor clean` and `meteor reset` have too similar of a meaning.  And I'm not sure if I'm a fan of adding another command anymore.

What if we changed the current functionality of `meteor reset` so it would _no longer_ wipe the database _unless_ a flag was passed.  Maybe `meteor reset --with-db`?  This might break some automated test workflows that might be doing this right now but would be very unlikely to break anything in production.  It's very clear though, and we could add a message about it to the existing `meteor reset` command.

**Comment by axelvaindal** [comment]
Hum...
This sounds like a good approach to me.

So `meteor reset` would clean the actual `.meteor/local/` folder (except for the `db` directory) if no flags are passed, but would wipe the database if you use it with a flag.

For instance:

`meteor reset` => Clean the `.meteor/local/` folder and other things but leave the `db` directory untouched.
`meteor reset --with-db` => Do the current process and thus also clean the `db` directory.

If this is the way you are thinking about, I'm okay about it.
However, I am not sure about the `--with-db` flag name.

Are we 100% sure there is no way of misunderstanding or change the behavior of the command in the future ?

If the default behavior of the command does *not* touch the `db` directory, and passing the flag only add the clean behavior of this directory, the name is perfectly fine.
But if passing the flag also extends the scope, or will extend the scope in the future, to much more behavior than this, I think we should perhaps look for another flag name in order to be sure developers understand the actual process of the `meteor reset --flag` execution.

Anyway, adding a message about it to the `man` of the command is a good idea, perhaps also in the documentation :).

**Comment by abernix** [comment]
Yes, that is what I was proposing.

That being said, I just found the commentary in https://github.com/meteor/meteor/issues/5328#issuecomment-147863406 which indicates that `meteor rebuild` is essentially supposed to do exactly what this feature request is suggesting: `meteor reset` without the database.  That's a super reasonable option and I don't recall seeing that command before.

I guess that means, assuming that `meteor rebuild` is extended to do what it's supposed to do, the main concern would be accidentally wiping your dev database with `meteor reset`.  By definition `reset` does sound pretty destructive though – so maybe a `[y/N]` prompt when in interactive mode and nothing when running non-interactively (i.e. without a shell, running from a script, etc.).

Or maybe just close this feature request and try to popularize `meteor rebuild` – well, and obviously try to make sure that it's not necessary by not having any bugs. 🙂

**Comment by axelvaindal** [comment]
Considering this :

> Usage: meteor rebuild [<package name>...]
> 
> Rebuild specified local packages. Deletes the package's build directory
> and rebuilds the package from scratch. Packages are specified by name.
> 
> If you pass no arguments, this will rebuild all local packages.
> That includes packages found through the
> METEOR_PACKAGE_DIRS environment variable, local packages in the current
> application, and, if running Meteor from a checkout, the packages in
> the checkout. It doesn't include any packages for which we don't have
> the source.
> 
> You should never need to use this command. It is intended for use while
> debugging the Meteor packaging tools themselves.

I am not sure `meteor rebuild` is a perfect choice for the behavior `meteor reset` is proposing.
I understand that `meteor rebuild` actually do the thing, but isn't it a bit unstable to use an actual non-recommended command to do a very common behavior ?

If think we should stick to your original proposition with the flag, considering it will not be destructive at all and will provide a recommended way of fixing this kind of problem, without having to use a *trick* with a non-recommended command.

It's pretty obvious considering the size of the meteor project that the original issue (i.e having bugs in meteor preventing build or such thing) will be there for a very long time no matter how hard you pass working on it because there is so many things not even coming from your code which could prevent a build for working well.
I suppose it's way clearer to provide a solution for such contingency (such as the `meteor reset --flag` command) and keep doing the good work to prevent this bugs from happening from your actual scope of code.

Furthermore, it looks like @hwillson closed the issue (https://github.com/meteor/meteor/issues/5328#issuecomment-261913956) considering this one should be the actual reference for fixing the problem, and thus using `meteor rebuild` need more discussion than there was in the original post considering this warning in the `man` command 😋.

**Comment by abernix** [comment]
Well, it _might_ be important to ignore the current "Usage" that's printed there. 🙊

The suggestion from #5328 is that if `meteor rebuild` worked properly, it's exactly what I proposed in the original post: `rm -rf .meteor/local/{build,bundler-cache,isopacks,plugin-cache}` (without `db`), so it actually seems like the perfect choice to me.  Perhaps #5328 should be reopened.  It _shouldn't_ be necessary to `meteor rebuild` but it also shouldn't be necessary to `meteor reset`.

My original intention for opening this issue was to have a command that can easily be offered in the case of a misbehaving application, for the process of debugging and triaging issues.  Essentially, the triage instruction could be: "Does this bug go away if you run `meteor rebuild`?"

**Comment by hwillson** [comment]
I'm all for not duplicating effort (and keeping the codebase easier to maintain), so if `meteor rebuild` works properly (and it's not going anywhere) then let's go with it! I agree with @abernix's idea of still adding a `[y/N]` prompt to `meteor reset` though, as well as possibly spitting out a message that points people to the `meteor rebuild` command if they want to reset without wiping the DB. So moving forward, we'd be looking at something like this:

1) Make sure `meteor rebuild` works the way we expect it to.
2) Update `meteor help rebuild` to remove the "you should never need to use this" message, and add more details about how the local database won't be wiped, etc.
3) Update `meteor reset` to show something like this when run:

```
> meteor reset

WARNING - this will wipe your local database. If you want to reset your 
project but keep your local database, please use "meteor rebuild" instead.

Are you sure you want to proceed? [y/N]
```

4) Update the [Command Line docs](https://docs.meteor.com/commandline.html) to include `meteor rebuild`.

**Comment by axelvaindal** [comment]
@abernix 
I was not aware you would like to use this command as an issue triage option, although I find it being a pretty nice idea considering the number of issue it could help resolving and triaging :).

I agree it should be necessary to `meteor rebuild` in the sense it is **always** being used when a bug occurs.
For the `meteor reset` command, I like being able to completely remove my `db` with a simple command in order to test things on collections and {insert, update, remove} process with hooks.

However considering the current "Usage", I am thinking something is perhaps going wrong with this command currently, so if it's the case, it should be fixed before migrating the documentation and the process reset.

That is exactly what @hwillson is proposing in his 4 steps situation, which is good for me.

Just to be sure I understand the process completely though, this would provide these scenarios to the actual meteor ecosystem : 

- You want to reset your project because it does not build anymore or want to clear your `.meteor/local` directory, you have to use `meteor rebuild`.
- You **also** want to wipe the local database, you have to use `meteor reset`.

If so, it appears the `meteor reset` command is no more than an extension of `meteor rebuild` in the sense that it extends the cleaning behavior to the database as well.
Makes me wonder if it wouldn't be better to have a command to rebuild correctly the project (i.e `meteor rebuild`) and one to **only** wipe out the database (i.e `meteor reset` currently).

Considering this use case, it appears the `meteor reset` is no longer needed if `meteor rebuild` is working correctly and can accept a flag in order to extend his scope to the database as well, for instance something like this :  `meteor rebuild --wipe-db`.

If I misunderstand things, could you please enlighten me, this is something I found very interesting and I would like to understand the eventual differences between `meteor rebuild` and `meteor reset` not only from the database point of view :).

**Comment by abernix** [comment]
@axelvaindal I believe we're all saying the same thing here now, but again yes, currently `meteor rebuild` is not thorough enough for this.

@hwillson's bullet points outline the action items correctly, but I think this qualifies as one feature request.

Marking as confirmed (as in, "the specification for this feature is ready").  My only question is whether adding the prompt will break any existing workflows.  I think if we only do this in interactive mode then this should be fine.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bdev%5D%20%60meteor%20reset%60%20with%20the%20option%20to%20preserve%20the%20database&body=Migrated%20from:%20meteor/meteor%237789) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
