### ISSUE TITLE
Meteor 1.3 on Mac OS X 10.11.5: Cannot start server

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#7795]
I'm on Mac OS X 10.11.5, Meteor 1.3.5.1. We've been using `meteorhacks:npm` which seems to work fine. But now I'd like to switch to using npm and standard `node_modules` and I can't.

Here's what I'm getting.

```
=> Started proxy.                             
=> Meteor 1.4.1.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
                                        
/Users/realyze/.meteor/packages/coffeescript/.1.1.4.plioy6++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EMFILE, readdir '/Users/realyze/code/scribblepost/code/node_modules/iconv/build/Release/obj.target/libiconv/deps/libiconv/lib'
```

Why does the coffeescript package even go into `node_modules`?

**Comment by Zhangzhiyue** [comment]
$meteor npm install
$meteor

**Comment by abernix** [comment]
Meteor Issues are not the place for questions.  Please read the docs for [migrating to NPM](https://github.com/meteorhacks/npm#using-with-meteor-13) at the `meteorhacks:npm` repo and ask for help on the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).

**Comment by realyze** [comment]
@abernix Well that was more of a rhetorical question. What I'm saying is "it's broken" and I think it's broken because Meteor's CofeeScript module is breaking it by watching `node_modules`.

@Zhangzhiyue Thanks for the suggestion but doing `meteor npm install` doesn't change this. Plus, guide.meteor.com says I can use global npm if I prefer that (https://guide.meteor.com/using-npm-packages.html#using-npm).

**Comment by abernix** [comment]
The problem is likely not due to `coffeescript` at all.  In the error, you'll see that it's simply getting caught in the `meteor-promise/promise_server.js` functionality, which happens to be the place that a lot of errors are caught due various asynchronous behaviours.  If you believe this is actually a bug, please submit a reproduction of the issue by following the [guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug), specifically the section about reproduction recipe.
