### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by RKurcan** [meteor/meteor#7796]
Hi everyone my project is running in browser but I try build I see write my screen errors
  

>   at toDosPath (C:\Users\MSFT\AppData\Local\.meteor\packages\meteor-tool\1.4.1
> _1\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:35:13)
>     at C:\Users\MSFT\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.wi
> ndows.x86_32\tools\static-assets\server\mini-files.js:85:16
>     at Array.map (native)
>     at Function._.map._.collect (C:\Users\MSFT\AppData\Local\.meteor\packages\me
> teor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\un
> derscore.js:97:56)
>     at Object.pathResolve (C:\Users\MSFT\AppData\Local\.meteor\packages\meteor-t
> ool\1.4.1_1\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:82:16)
> 
>     at buildCommand (C:\tools\cli\commands.js:891:26)
>     at Command.func (C:\tools\cli\commands.js:798:12)
>     at C:\tools\cli\main.js:1410:23

**Comment by abernix** [comment]
Something is very wrong here as it seems that Meteor is installed directly in your `C:\`.  What shell are you running Meteor from? (e.g. PowerShell, Command Prompt, etc.)

Could you please try a fresh re-install of Windows using the following steps:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.1.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

Then, try your application again.  If you still have problems, please see if it happens on a NEW Meteor project or only existing projects (i.e. `meteor create my-new-project`).

**Comment by RKurcan** [comment]
Thanks bro but I trying your all directions and I see error

**Comment by abernix** [comment]
> What shell are you running Meteor from? (e.g. PowerShell, Command Prompt, etc.)

Still curious what the answer is to this.

Also, what version of Windows are you using and can you provide the output of running `SET`?  This command should output show what all of your environment variables are set to.  Perhaps there is a strange variable that is causing this.

**Comment by RKurcan** [comment]
Thanks for answer.
Today I will  try another PC.

**Comment by abernix** [comment]
I'm going to close this as we haven't heard back from you and it seems to be a problem isolated to your particular setup.  If you're still having this problem, please try it on a brand new Meteor app (you didn't specify if you had tried that).  Also, please provide the full error as it seems you've chopped off some important parts.

I'm happy to reopen and help further if you can come up with additional information to reproduce it, but without a reliable reproduction, there isn't much to do here.
