### ISSUE TITLE
[1.4.1.1] Update operation not affecting document when using utf8 character in query (local DB)

### ISSUE THREAD

**Issue by tomyo** [meteor/meteor#7798]
Here's the bug reported at mongo, they told me repost it here:
[https://jira.mongodb.org/browse/NODE-821](https://jira.mongodb.org/browse/NODE-821)

I'm using linux 64 bit (Ubuntu), when performing the update below, using the utf8 character Ú, the query finds the document, but doesn't change it. I'm using a clean 1.4.1.1 install (did meteor reset after upgrade). I noticed the query runs fine in production (compose.io), so it looks like something with the local implementation of mongo or something like that. I tried the operation from meteor shell and meteor mongo, same result.

```
db.orders.update({_id: 'WB3HT38fGpsBS2Du3', 'items.productId': 'WoXYnAfCZkex9Qugv', 'items.color': 'Verde', 'items.size': 'Única'}, {$set: {'items.$.status': 'Pendiente'}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 0 })
```

**Comment by mjmasn** [comment]
I wasn't able to replicate your issue using the Ú character, but I don't think your query works the way you think it does. You need to use $elemMatch if you're matching on more than one sub field, otherwise I think Mongo will just update the first match for the first field you've queried (productId). It should still update though, albeit potentially updating the wrong element.

Try:
```
db.orders.update({
    _id: 'WB3HT38fGpsBS2Du3',
    items: {
        $elemMatch: {
            productId: 'WoXYnAfCZkex9Qugv', 
            color: 'Verde', 
            size: 'Única'
        }
}, {
    $set: {
        'items.$.status': 'Pendiente'
    }
});
```

It might be helpful to post the result of `db.orders.find({_id: 'WB3HT38fGpsBS2Du3'})` (or at least the items array from that document if the document contains sensitive information).

The only other thing I could think would be if you were trying to write to a secondary member the query would succeed but the update would fail, but that doesn't seem possible with a local Meteor database.

**Comment by abernix** [comment]
@mjmasn Is likely right that you're misunderstanding the way `mongo` is working on array elements and that you are not seeing anything change because the`status` of the first element of the `items` array is is already set to `Pendiente`.  

And yes, it is actually difficult to help without providing the full contents of `db.orders.find({_id: 'WB3HT38fGpsBS2Du3'})`.

Lastly, this is not the place for _questions_ about using Meteor (or Mongo).  If this is a reproducible bug then it would be acceptable to post a reproduction here but you have not included information to reproduce the problem (in this case, as said before, the contents of `db.orders.find({_id: 'WB3HT38fGpsBS2Du3'})` might be sufficient).

Does not appear to be a bug.

**Comment by abernix** [comment]
To prove the point, I'm assuming if you ran these two commands one after another (setting `Pendiente` to _anything_ else, like `Inactivo`), over and over, you _would_ see changes:

#### Command 1
````
db.orders.update({_id: 'WB3HT38fGpsBS2Du3', 'items.productId': 'WoXYnAfCZkex9Qugv', 'items.color': 'Verde', 'items.size': 'Única'}, {$set: {'items.$.status': 'Pendiente'}})
````

#### Command 2
````
db.orders.update({_id: 'WB3HT38fGpsBS2Du3', 'items.productId': 'WoXYnAfCZkex9Qugv', 'items.color': 'Verde', 'items.size': 'Única'}, {$set: {'items.$.status': 'Inactivo'}})
````

... then run **Command 1** again, etc.

**Comment by tomyo** [comment]
Hi @mjmasn, @abernix.  Thanks for the responses!, and sorry it took me this long to answer.
Ok, last night I was reviewing this. I tried the $elemMatch syntax, with same result (in fact, what I was using is a syntax sugar of $elemMatch: when there's only one query, [is not necessary](https://docs.mongodb.com/manual/reference/operator/query/elemMatch/#op._S_elemMatch). But I'm not a mongo expert, and I do feel like I don't really get how this update i'm trying in a sub array document works.
Ok, lets move to the problem. here's the result of `db.orders.find({_id: 'WB3HT38fGpsBS2Du3'})`

```
{ "_id" : "WB3HT38fGpsBS2Du3", "buyerId" : "ozJHZQJvaw9P3Aohe", "items" : [ { "productId" : "FfW26ZPwr3viM7Yyh", "sellerId" : "eh7AhgWtiM9M58ZXs", "name" : "Atreyena", "photo" : { "url" : "http://localhost:3000/img/zapatilla.png", "fileId" : "noFileId" }, "price" : 20815, "sellCommission" : 0.15, "shippingPrice" : 2000, "size" : "Única", "color" : "Rosado", "quantity" : 1, "status" : "Pendiente" }, { "productId" : "o6uE584g53yxsKMsf", "sellerId" : "se2byvKXvZTEuncay", "name" : "Ony", "photo" : { "url" : "http://localhost:3000/img/traje.png", "fileId" : "noFileId" }, "price" : 41695, "sellCommission" : 0.15, "shippingPrice" : 0, "size" : "46", "color" : "Plateado", "quantity" : 1, "status" : "Pendiente" }, { "productId" : "WoXYnAfCZkex9Qugv", "sellerId" : "se2byvKXvZTEuncay", "name" : "Beward", "photo" : { "url" : "http://localhost:3000/img/zapato1.png", "fileId" : "noFileId" }, "price" : 35489, "sellCommission" : 0.15, "shippingPrice" : 0, "size" : "Única", "color" : "Verde", "quantity" : 1, "status" : "Pendiente" } ], "createdAt" : ISODate("2016-08-31T15:52:38.402Z"), "updatedAt" : ISODate("2016-09-23T22:44:31.002Z"), "orderNumber" : 1609023478 }
```

Oh, oh, wait, I was just trying some alternatives, when I stumble upon [http://stackoverflow.com/questions/4669178/how-to-update-multiple-array-elements-in-mongodb](http://stackoverflow.com/questions/4669178/how-to-update-multiple-array-elements-in-mongodb), looks like what I'm trying to do is imposible in mongo right now, I have to call update one time for each element I want to modify in the array.

Anyway, I did discover why even running the update operations several times didn't do anything before (showing 1 matched, o modified).

If I do, for example: `db.orders.update({_id: 'WB3HT38fGpsBS2Du3', 'items': {$elemMatch: {sellerId: 'se2byvKXvZTEuncay'}}}, {$set: {'items.$.status': 'Recibido'}}`, the first run finds the first element in the array that matches the sellerId (the one with color: 'Plateado') and changes it, but then, when I run it again, it matches the same array item, making no modifications as the status is already 'Recibido'. 
In order to work I need to change the query to: ` db.orders.update({_id: 'WB3HT38fGpsBS2Du3', 'items': {$elemMatch: {sellerId: 'se2byvKXvZTEuncay', status: 'Pendiente'}}}, {$set: {'items.$.status': 'Recibido'}})`. This time, the second run of the update operation, it finds the second array element, as the first one doesn't match any more.

So, this no mongo or meteor problem at all, just a misunderstanding of mongo update functionality.  although, I think they should mention this limitation in the mongo docs, as the {multi:true} flag makes you think this is posible.

Thank again for your time an patience. At least I learn something new about mongo today (hopefully you too), and I can move forward in my project. ^_^

**Comment by mjmasn** [comment]
Glad you've worked it out, another option is to move the contents of the items array into their own collection, then you can use `multi: true` to update multiple items, but obviously you then have to 'join' the two queries manually if you want to e.g. display the order with all the items. Mongo is all about the compromises!

**Comment by tomyo** [comment]
Yeah, hope I don't regret my choice in the future, but if I do, doesn't look like a complicated migration anyway (at least at DB level). Have a good day!
