### ISSUE TITLE
ddp login bug - user forgotten on server

### ISSUE THREAD

**Issue by vacarsu** [meteor/meteor#7803]
Repo - https://github.com/vacarsu/ddp-login-bug

I'm connecting server a to server b via ddp. Login works on client but when you refresh the client the user is saved on client and it appears the user is logged in, however any reference to userId in publications is null on the server. You can see this by looking in the terminal which is serving server b, the publication serving permissions logs `this.userId` is null. in the client you can see the 'administration' link no longer shows up, but if you logout and login again, everything works as normal.

Steps to Reproduce -
1. Clone repo
2. run meteor npm install on server a
3. run server a on port 3000, run server b on port 3030
4. login on server a in browser then refresh
5. check server b's terminal for the logged `this.userId`
6. refresh browser.
7. check server b's terminal again for the logged `this.userId`

**Comment by abernix** [comment]
Thanks for filing this issue.  I'm sorry it hasn't received attention until now.  I had tried before to follow your reproduction steps but ran into a variety of issues, starting at step 2.  I toyed around with it for a while but I think there is some combination of dependencies which are just incompatible and would take too long to research.

Since you're probably more familiar with your deps, Cculd you please simplify this reproduction, remove things (NPM packages, for example) which aren't absolutely necessary and update them to more recent versions?  Many of them are `-beta` and `-rc` releases that seem to be several months old.

Also, please try updating to at least 1.4.1.3 (since you were on 1.4.1.1) but ideally going to 1.4.2.3 which may have bug fixes pertaining to your problem (and also has significant performance enhancements).

Happy to look again with an updated reproduction.  Thanks!

**Comment by abernix** [comment]
@vacarsu Any updates on this?

**Comment by hwillson** [comment]
Hi @vacarsu - since we haven't heard back from you regarding the additionally requested details in https://github.com/meteor/meteor/issues/7803#issuecomment-263018459, I'll close this issue for now. I'm happy to re-open this issue if you're still encountering this problem, and are able to post back with an up to date (and ideally as simple as possible) reproduction. Thanks for reporting this originally!
