### ISSUE TITLE
[1.4.1.1] Cordova meteor build iOS local plugins path bug

### ISSUE THREAD

**Issue by jackkav** [meteor/meteor#7804]
Referencing this issue https://github.com/meteor/meteor/issues/6810

During meteor build of a cordova project: 
The plugin is copied into the /ios/myapp/Plugins folder then not referenced in the project.pbxproj and rather the original is referenced at a relative path given in the cordova-plugins manifest instead. I can imagine this is useful for an meteor run during plugin development. However for a meteor build this logic is incorrect. The build should copy into Plugins and then reference the copied folder.

**Expected behaviour** After copying local plugins into ios/myapp/Plugins folder should use that new folder reference in the project.pbxproj for the xcode build

**Actual behaviour** After copying local plugins into ios/myapp/Plugins folder the path used to find the plugin is used in project.pbxproj

**Comment by dmitry-sher** [comment]
Adding cordova packages from Git is immensenly slow for people in some parts of the world.. Yesterday i had to include cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5, because otherwise it doesn't works in Xcode 8. Now my build takes tens of minutes. It's a real pain.

![image](https://cloud.githubusercontent.com/assets/6441391/19027738/021bed10-893c-11e6-82d0-74659a87e386.png)

**Comment by hwillson** [comment]
Since there have been 7 Meteor releases since this issue was created, and there hasn't been any activity on this issue in over a year, I'll close it for now. I'm happy to re-open this issue if anyone is still encountering this problem with Meteor 1.6. Thanks!
