### ISSUE TITLE
[1.4.2-beta.5] App will not start - getting a crash

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#7815]
`1.4.2-beta.4` works fine.

When I update to `1.4.2-beta.5` I get the following error:

```
W20160923-17:54:54.446(-4)? (STDERR) /Users/clayne/.meteor/packages/meteor-tool/.1.4.2-beta.5.j68yf6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160923-17:54:54.446(-4)? (STDERR) 						throw(ex);
W20160923-17:54:54.446(-4)? (STDERR) 						^
W20160923-17:54:54.446(-4)? (STDERR)
W20160923-17:54:54.446(-4)? (STDERR) Error: Cannot find module './lib/patch'
W20160923-17:54:54.447(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:85:1)
W20160923-17:54:54.447(-4)? (STDERR)     at meteorInstall.node_modules.react-hot-loader.patch.js (node_modules/react-hot-loader/patch.js:1:1)
W20160923-17:54:54.447(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160923-17:54:54.447(-4)? (STDERR)     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160923-17:54:54.447(-4)? (STDERR)     at Module.Mp.import (/Users/clayne/.meteor/packages/modules/.0.7.7-beta.5.j07iqc++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20160923-17:54:54.448(-4)? (STDERR)     at meteorInstall.imports.bootstrap.index.js (imports/bootstrap/index.js:1:8)
W20160923-17:54:54.448(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160923-17:54:54.448(-4)? (STDERR)     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160923-17:54:54.448(-4)? (STDERR)     at Module.Mp.import (/Users/clayne/.meteor/packages/modules/.0.7.7-beta.5.j07iqc++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20160923-17:54:54.448(-4)? (STDERR)     at meteorInstall.imports.bootstrap.server.index.js (imports/bootstrap/server/index.js:1:8)
```

**Comment by abernix** [comment]
This _appears_ to be due to the fact that [this line](https://github.com/gaearon/react-hot-loader/blob/794c02b0aeef3d13ec09a939824c5ed8ec836a09/patch.js) in the `react-hot-loader` package which you are using is referencing `./lib/patch` – a file that does not exist in the `react-hot-loader` [source tree on Git](https://github.com/gaearon/react-hot-loader/tree/794c02b0aeef3d13ec09a939824c5ed8ec836a09) nor in the published NPM.

Presumably, that file (and the rest of the `lib/` directory) would only be generated once the Babel compilation of the `src` directory was completed.  Taking a look at the [`package.json` for `react-hot-loader`](https://github.com/gaearon/react-hot-loader/blob/794c02b0aeef3d13ec09a939824c5ed8ec836a09/package.json#L14) you can see that the `npm` script exists to do just this.  The NPM package needs to be distributed with that file in order for it to work.  Other than that, I don't immediately see any other changes in #7668 that would have caused this issue so this is my best guess.

That being said, I'm sure you understand that the intricacies of your individual setup have some bearing on the reproducibility of this issue and without more detail renders it difficult to understand what's wrong.  If at all possible, please reproduce this on a project that you can share with us so someone could take a look at.

**Comment by clayne11** [comment]
It certainly does exist because it builds perfectly fine on `1.4.2-beta.4` and only fails on `1.4.2-beta.5`. Also, if I remove `react-hot-loader` another dependency fails to load. It seems to me that the bundling / module system is broken in `1.4.2-beta.5`. Everything is working perfectly for me with `1.4.2-beta.4`.

**Comment by abernix** [comment]
> nor in the published NPM.

I stand corrected on this – it is in the published `react-hot-loader@3.0.0-beta5` NPM so I'd be curious if `node_modules/react-hot-loader/lib/patch.js` exists within your Meteor project.

> It seems to me that the bundling / module system is broken in 1.4.2-beta.5.

Ok, but this just isn't true as a general statement, so it must be something distinct to your particular setup.

Not sure how close it gets to a setup similar to yours, but I took a quick pass at getting @gadicc's [`meteor-hmr`](https://github.com/gadicc/meteor-hmr) running, using `react-hot-loader@3.0.0-beta.5` and it ran fine.  Additionally, I tried running it under Meteor `1.4.2-beta.4` and upgrading it to `.5` and still did not experience a problem.  [Git Repro here](https://github.com/abernix/meteor-issue-7815)

Maybe try a `meteor reset` or removing the cache directories from your `.meteor/local/` directory and rebuilding to see if that resolves the problem?

Perhaps you could take a look at differences in #7668 and see what you can come up with.  It's possible that optimizations that are being made for speed in 1.4.2 may compromise some of the complexities of HMR, meteor+webpack, etc., or that other packages involved in this process may need changes.

Please, make a reproduction.

**Comment by clayne11** [comment]
@benjamn has access to my repo. I have changed absolutely nothing between `beta.4` and `beta.5` and it stopped working. I've tried deleting `node_modules`, resetting Meteor, none of it is working. When I go back to `beta.4` it works perfectly.

`beta.6` is having the same issue. You can ask @benjamn to look into it since he does have a reproduction.

**Comment by clayne11** [comment]
I figured it out - I had `react-hot-loader` in `devDependencies`. When I moved it to `dependencies` the issue went away.
