### ISSUE TITLE
Add serviceOptions to accounts-ui configuration

### ISSUE THREAD

**Issue by funkyeah** [meteor/meteor#7820]
Update: I believe this to be a google oauth issue now since I can re-produce on non-meteor websites. http://stackoverflow.com/questions/39708665/bug-with-google-oauth-when-logged-in-in-a-different-tab-on-a-different-service

Steps to reproduce are:
1. open a new incognito window
2. use one tab to login to an existing google service like gmail
3. after doing this use another tab to signup to an app with accounts-google
4. accept the permissions it asks for
5. log back out
6. log back in again with accounts-google

At the last step the google login service should provide you with an option to select/switch to a different google account, but instead it automatically logs you in with the account that is active in the other tab.

The login window that opens should present you with the option to select or switch to which google account you would like to login with e.g this:
![image](https://cloud.githubusercontent.com/assets/469403/18826339/8891f5ba-8392-11e6-8799-4e30c011998e.png)

This is problematic when I'm using multiple google accounts on the same computer. I have to sign-out of the  other account before I can sign in with the account I would like to on my app. Funny enough, if I sign into gmail with two different google accounts (through the Add Account feature) the the issue no longer happens because the app provides the ability to select between those two accounts `or` to sign in with a different one.

This may just be a straight issue with google's oauth service implementation because I have seen it behave similarly with other sites that implement google oauth (stackoverflow for 1).

See on Meteor 1.2.1 but have seen this same issue on many versions.
See with Ubuntu Linux and Chrome Version 53.0.2785.80 beta (64-bit) ... but have seen the issue on other platforms as well including Windows+Firefox.

Reproduction is kind of a pain because you need to setup Google API credentials:

I used this meteorchef tutorial code to reproduce:
https://github.com/themeteorchef/roll-your-own-authentication

It has a bit more going on that needed to minimally reproduce but the issue is pretty well isolated from the rest of the code since the above app doesn't do almost anything without first logging in.
- I just removed the other oauth login options
- Added a `settings-development.json` file:

```
{
  "public": {},
  "private": {
    "oAuth": {
      "google": {
        "clientId": "",
        "secret": ""
      }
    }
  }
}
```
- and fired it up with npm start

**Comment by abernix** [comment]
Actually, this is the normal functionality of the Google OAuth API.  I'll try to explain briefly, but I'll refer you to [the Google OAuth docs](https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters).

The functionality (not asking for other accounts) is preferred in most workflows because, well, most people don't use multiple Google accounts with the same service.  The first time a user authorizes with your app, they will see the option to change accounts using the drop down in the top right corner. 

![glogin](https://cloud.githubusercontent.com/assets/841294/19387443/df55386e-9222-11e6-9750-9be100cae260.png)

But once the user has given the permissions, it will automatically just log them in immediately.

Going back to the documentation I linked above, in the "Authentication URI parameters" section you'll see there's a `prompt` parameter and one of the options is `select_account`.  If you have decided that prompting the user every time is okay for your workflow, then you can pass the option to the `Meteor.loginWithGoogle` function:

    Meteor.loginWithGoogle({prompt: 'select_account'})

Unfortunately, as the `accounts-google` is intended to be a very simple implementation, it doesn't support this by default so right now you would need to provide your own button to login with Google using the `Meteor.loginWithGoogle` function.

**Comment by funkyeah** [comment]
Looks like you nailed it on the head. I'm using useraccounts so I'm another layer removed from accounts-google.

Sounds like this would then turn into a feature request for accounts-google, but I won't presume that it's worth it to enough pepople.

**Comment by abernix** [comment]
Actually, I should have said that it was `accounts-ui` that didn't support this because `accounts-google` does support it (as I demonstrated). 

If you'd be interested in making a [contribution to Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md), I don't think this would be a very difficult modification, however in your case, the contribution wouldn't do Meteor's `accounts-ui` itself much good if you were already using `useraccounts`; `useraccounts` would need the PR in your case.  Both would be relatively easy!

If you were just using `accounts-ui`, this would be pretty straightforward:

* [The `google` package](https://github.com/meteor/meteor/blob/devel/packages/google/google_client.js#L51-L55) _already_ supports a different kind of `prompt` via the `Accounts.ui.forceApprovalPrompt` which explicitly sets `prompt` to `consent` (This would have to be left in place for backwards-compat.  I'm not sure why this wasn't implemented to support both to begin with :shrug:).
* That option is set programmatically when the button is pressed by [this code](https://github.com/meteor/meteor/blob/devel/packages/accounts-ui-unstyled/login_buttons_single.js#L48-L49)
* That option is configured by the [`Accounts.ui.config` function](http://docs.meteor.com/api/accounts.html#Accounts-ui-config)

I might propose just having `Accounts.ui.config.serviceOptions` be an object of services (e.g. `google`, `facebook`, etc. similar to how `requestPermissions` works) which is directly passed along to the service.  It would allow something similar to work for all  other services, and specific settings to be set for each one.

Anyhow, just a thought, and just a proposal right now if you were interested in massaging it out.

**Comment by funkyeah** [comment]
Thanks for the guidance. I just might have to give contributing to a Meteor a go.

**Comment by abernix** [comment]
Thanks to @lucfranken, a recently cleaned up "slow start for developers/contributors" has just landed in the 1.4.2 branch to help make it easier.  If you're interested, maybe [take a peak](https://github.com/meteor/meteor/blob/release-1.4.2/README.md#slow-start-for-developers).  

Essentially, I think the change I described above, in addition to something like it in the package you're using (this [`useraccounts` code](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js#L83-L90)) would make them both work and be valuable to the community (`accounts-*` is frequently touted as one of the more valuable features of Meteor).

If what I said checks out (and doesn't seem to break everything/seem totally unsafe), report back and we can see about getting this a `pull-requests-encouraged` tag.

**Comment by lucfranken** [comment]
@abernix looks much better than it was! 👍

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20serviceOptions%20to%20accounts-ui%20configuration&body=Migrated%20from:%20meteor/meteor%237820) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
