### ISSUE TITLE
[Meteor 1.4.1.1] Unable to run in iOS with Xcode 8

### ISSUE THREAD

**Issue by dotansimha** [meteor/meteor#7828]
Meteor version: 1.4.1.1
OS: Mac OS X Sierra 
XCode Version: 8.0 (8A218a)
Application version: 1.4.1.1

When trying to run `meteor run ios`, the following errors occurred:

```
** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/dotansimha/Dev/meteor-angular2.0-socially/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,meteor-angular2.0-socially.xcodeproj,ARCHS=i386,-target,meteor-angular2.0-socially,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/dotansimha/Dev/meteor-angular2.0-socially/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/dotansimha/Dev/meteor-angular2.0-socially/.meteor/local/cordova-build/platforms/ios/build/sharedpch
=> Errors executing Cordova commands:

   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:
   /Users/dotansimha/Dev/meteor-angular2.0-socially/.meteor/local/cordova-build/platforms/ios/cordova/run
   --emulator

   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 END CAPTURE 0 starting app on iOS Simulator took 2351

/Users/dotansimha/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
ExitWithCode:1
```

Tried:
- meteor reset
- remove/add platform
- remove Meteor / reinstall
- remove Xcode / reinstall 
- remove iPhone Simulator / reinstall
- Verified the Xcode license agreement

When using debug flags, I noticed this issue as well:

```
=== BUILD TARGET meteor-angular2.0-socially OF PROJECT meteor-angular2.0-socially WITH CONFIGURATION Debug ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

I can't modify the Swift version, and I can't set `SWIFT_VERSION` externally - which means that the generated `plist` file of the application should contain the correct flag.

**Comment by hamzamu** [comment]
I have the same issue ... do not know yet is it Meteor ,  Cordova  , Gradle or xCode 8  !!!

**Comment by hamzamu** [comment]
@dotansimha : please check this out 
[iOS 10 compatibility - Meteor Forums ](https://forums.meteor.com/t/ios-10-compatibility/26065/17?u=hamzamu)

**Comment by ozanpekmezci** [comment]
same here

**Comment by hamzamu** [comment]
@ozanpekmezci  Hello , I am still unable to run ios " meteor run ios " , however i managed to build iOS  with the fix i mentioned above  [iOS 10 compatibility - Meteor Forums ](https://forums.meteor.com/t/ios-10-compatibility/26065/17?u=hamzamu)

**Comment by crazybaud** [comment]
> @martijnwalraven  > With help from @aldeed, there is now a swift3 branch of cordova-plugin-meteor-webapp ... `meteor add cordova:cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5`

Is it planned to integrate this inside 1.4.2 release https://github.com/meteor/meteor/issues/7828 ? It would be nice :) If not, how can we help ?

**Comment by rerenWorkGit** [comment]
@crazybaud You are right，i solved the problem

**Comment by sferoze** [comment]
@crazybaud just ran into the same issue. 

Adding the package @martijnwalraven posted on the meteor forum solved this issue

This is the fix: https://forums.meteor.com/t/ios-10-compatibility/26065/17?u=hamzamu

**Comment by martijnwalraven** [comment]
Note that there is now actually a newer released version of the plugin available. `meteor add cordova:cordova-plugin-meteor-webapp@1.4.1` should do the trick.

**Comment by sferoze** [comment]
@martijnwalraven Hey Martin,

Just tried the new plugin. With the new one, when it asks you to convert to swift 3, i do so as per your instructions in the forums. 

But with the new one, there are many code changes it asks me to review.

With the previous plugin, there were no code changes. 

Whats goin on? And how should one proceed?

**Comment by sferoze** [comment]
@martijnwalraven oh well actually I just restarted xcode. 

And now there is no code changes when I open the project.

So its working now normally just like the previous plugin.

**Comment by martijnwalraven** [comment]
@sferoze: The new plugin version will not ask you to convert to Swift 3, because it sets the `SWIFT_VERSION` on your Xcode project automatically. There should be no further conversion needed.

**Comment by Jolo510** [comment]
@martijnwalraven solution worked for me. Thanks!

**Comment by jensljungblad** [comment]
@martijnwalraven I still get a lot of Swift compiler errors (24 of them) trying to build in Xcode 8 with `cordova:cordova-plugin-meteor-webapp@1.4.1` and Meteor 1.4.1.2.

![screen shot 2016-10-06 at 23 33 17](https://cloud.githubusercontent.com/assets/271354/19171515/841103e4-8c1d-11e6-862a-1b0bcd860c26.png)

**Comment by NicholasEli** [comment]
I am having the same issue, running latest version of meteor and xcode.  I also tried the plugin mentioned above.

```
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:                     
   /Users/nicholas/Desktop/meteor/fb/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
   ** BUILD FAILED **
   
   
   The following build commands failed:
   Check dependencies
   (1 failure)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/nicholas/Desktop/meteor/fb/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,fb.xcodeproj,ARCHS=i386,-target,fb,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/nicholas/Desktop/meteor/fb/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/nicholas/Desktop/meteor/fb/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

/Users/nicholas/.meteor/packages/less/.2.7.5_1.18rviws++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
ExitWithCode:1
```

**Comment by Chey47** [comment]
@NicholasEli Juste install this one : meteor add cordova:cordova-plugin-meteor-webapp@1.4.1
the first one mentioned doesnt work but this one does..

THANK YOU ALL for your help and of course a big respect to aldeed our Meteor savior :)

**Comment by tanutapi** [comment]
Combine with:
`meteor add cordova:cordova-plugin-meteor-webapp@1.4.1`
and then
`rm -rf .meteor/local/cordova-build`
works for me.

**Comment by NicholasEli** [comment]
@Chey47 That plugin did allow the simulator to start, however the run process stops and this error occurs: 
`=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:                     
   /Users/nicholas/Desktop/meteor/the-plug/the-plug/.meteor/local/cordova-build/platforms/ios/cordova/run
   --emulator
   ENOENT: no such file or directory, stat
   '/Users/nicholas/Library/Logs/CoreSimulator/61E68A38-0BF9-4277-A442-F2A54E3EDB05/system.log'
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

/Users/nicholas/.meteor/packages/coffeescript/.1.0.17.14p7hgu++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode:1`

**Comment by dotansimha** [comment]
Now working with 1.4.2 and latest XCode. 

Thanks!

**Comment by albertbuchard** [comment]
I am unable to build even the basic meteor app you get after meteor create... the plugin did not change the error. 

Any leads ?

```
$ meteor run ios
[[[[[ ~/Google Drive/dev/test-ios ]]]]]       

=> Started proxy.                             
WARNING: Attempting to install plugin cordova-plugin-splashscreen@3.2.1, but it should have a minimum version of 4.0.0 to ensure compatibility with the
         current platform versions. Installing the minimum version for convenience, but you should adjust your dependencies.
=> Started MongoDB.                           
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed: /Users/Pro/Google Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
   ** BUILD FAILED **
   
   
   The following build commands failed:
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/WebAppConfiguration.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/AssetBundleManager.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/AssetBundle.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/Asset.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/AssetBundleDownloader.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/AssetManifest.swift
   CompileSwift normal i386 /Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/test-ios/Plugins/cordova-plugin-meteor-webapp/Errors.swift
   CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
   (9 failures)
   Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,test-ios.xcodeproj,-target,test-ios,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
   Simulator,build,CONFIGURATION_BUILD_DIR=/Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Pro/Google
   Drive/dev/test-ios/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
                                              
/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/Users/Pro/.meteor/packages/meteor-tool/.1.4.2_3.1atntm4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at /tools/cordova/runner.js:98:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at AppRunner._runOnce (/tools/runners/run-app.js:763:21)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

**Comment by dgolds** [comment]
I have the exact same issue. final error line is also line 190 of promise_server.js

Xcode Version 7.3.1 
macOS Sienna 10.12.2 (16C67)

I will also try latest xcode, but I note the prior comment had same issue with xcode 8

**Comment by mjovkovic** [comment]
I'm upgrading my app from Meteor 1.3 to Meteor 1.4.2 and Xcode 8.2.1.

I got everything working, and I can successfully run, build and start the app when I'm using `meteor run ios-device`. 

However, when i run e.g. `meteor build /tmp/output --server "$SERVER"` the resulting iOS project in the output path can not be built - it uses Swift 2.3. The strange thing is that the Xcode project that is being built inside of `.meteor/local/codrova-build` (during the same meteor build process) is built using Swift 3.0. 
I did a full folder comparison between the two, and practically the only difference is that the `cordova-build` one has `SWIFT_VERSION = 3.0;` line under the `buildSettings` in `app.xcodeproj/project.pbxproj` file.

It seems as if the `cordova-plugin-meteor-webapp` is not executed for the output path. 

I totally ran out of ideas what could be the problem. Do you have any?

**Comment by terrorhawks** [comment]
I got it working by using...  (change the ../output to where you ios project is built)

`echo "SWIFT_VERSION = 2.3" | tee -a ../output/ios/project/cordova/*.xcconfig`

**Comment by macrozone** [comment]
I have the same problem with METEOR@1.4.2.3

I just added the meteor package mobile-status-bar
and removed .meteor/local/cordova-build and all of sudden, i get this error

"Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly"

**Comment by MatteoOrtiz** [comment]
Goodnight :
in my case I'm in version 1.6 of the meteor, install the latest version of Xcode and everything worked perfect .... until I showed up in my appstore an Xcode update, which installs without worry, the version in which the Xcode is 9.2, but now that I run meteor, I run the following error:


=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:                     
   /Users/matyu/Security_Network/.meteor/local/cordova-build/platforms/ios/cordova/run
   --emulator
   xcodebuild: error: Unable to find a destination matching the provided
   destination specifier:
   { platform:iOS Simulator, OS:latest, name:iPhone X }
   
   The requested device could not be found because multiple devices matched the
   request.
   
   Available destinations for the "Security_Network" scheme:
   { platform:iOS Simulator, id:2C88623B-35E4-408C-86AD-32F936246C10, OS:11.2,
   name:iPad (5th generation) }
   { platform:iOS Simulator, id:317E482C-904F-40B5-B611-ED331DC0EB52, OS:11.2,
   name:iPad (5th generation) }
   { platform:iOS Simulator, id:4C24E5BB-3AA4-4974-BB63-50DEAD868A5D, OS:11.2,
   name:iPad Air }
   { platform:iOS Simulator, id:D04D049D-538A-4A90-8A51-1E4482A2582D, OS:11.2,
   name:iPad Air }
   { platform:iOS Simulator, id:44A1994B-610A-4436-8EC1-BDE291F743C3, OS:11.2,
   name:iPad Air 2 }
   { platform:iOS Simulator, id:FAD1D5B0-C7A2-47B3-9760-3ADFAC4772B7, OS:11.2,
   name:iPad Air 2 }
   { platform:iOS Simulator, id:27A1659F-2F99-476C-80DA-A7E023C2AD46, OS:11.2,
   name:iPad Pro (9.7-inch) }
   { platform:iOS Simulator, id:3D7FED07-65DD-4D21-A630-E81B8082358C, OS:11.2,
   name:iPad Pro (9.7-inch) }
   { platform:iOS Simulator, id:752AD389-F1C7-422D-9B1D-2EDAA941EC19, OS:11.2,
   name:iPad Pro (10.5-inch) }
   { platform:iOS Simulator, id:65DB1D75-33A4-4B81-8048-00CD0867389C, OS:11.2,
   name:iPad Pro (12.9-inch) }
   { platform:iOS Simulator, id:72C9375C-68E7-4D5F-85EE-FDB2BB608A76, OS:11.2,
   name:iPad Pro (12.9-inch) }
   { platform:iOS Simulator, id:981CE76F-1B5B-45DC-9429-037379A1EEDC, OS:11.2,
   name:iPad Pro (12.9-inch) (2nd generation) }
   { platform:iOS Simulator, id:DA510FA3-376D-4EF5-A5B3-59D24E1C649D, OS:11.2,
   name:iPhone 5s }
   { platform:iOS Simulator, id:E0ECB39D-4749-4DC8-B3C2-73F580362ADC, OS:11.2,
   name:iPhone 5s }
   { platform:iOS Simulator, id:0D91DBDA-C554-4FD4-AB19-C0A47648AA91, OS:11.2,
   name:iPhone 6 }
   { platform:iOS Simulator, id:D721D744-22D6-4BAE-8ACF-24A9C136F9CE, OS:11.2,
   name:iPhone 6 }
   { platform:iOS Simulator, id:15512A22-6E1D-49D6-9356-334AE636B596, OS:11.2,
   name:iPhone 6 Plus }
   { platform:iOS Simulator, id:AF1D031C-685A-46AB-9C90-EE13F2A191D8, OS:11.2,
   name:iPhone 6 Plus }
   { platform:iOS Simulator, id:2769B964-26EB-4F5C-8D60-1C256B19D60F, OS:11.2,
   name:iPhone 6s }
   { platform:iOS Simulator, id:C4C1D28B-0EDB-473D-AE15-F1ED60939E84, OS:11.2,
   name:iPhone 6s }
   { platform:iOS Simulator, id:37809E97-B4CE-48AC-B7D4-0F2A00498AC0, OS:11.2,
   name:iPhone 6s Plus }
   { platform:iOS Simulator, id:6F208067-D066-4E5E-BB06-772E8C868C3D, OS:11.2,
   name:iPhone 6s Plus }
   { platform:iOS Simulator, id:3233301D-BDB9-4520-AAC8-946E2929AC50, OS:11.2,
   name:iPhone 7 }
   { platform:iOS Simulator, id:A6FA33F8-9DBA-4592-BA8F-C5989D7804EE, OS:11.2,
   name:iPhone 7 }
   { platform:iOS Simulator, id:A5B9B2E5-2169-4E7B-9AC7-1051BB0E95EB, OS:11.2,
   name:iPhone 7 Plus }
   { platform:iOS Simulator, id:F62817E4-160B-4373-BFCD-574A98618695, OS:11.2,
   name:iPhone 7 Plus }
   { platform:iOS Simulator, id:9AE9B014-6CF1-4173-BEFC-9C27BFB795D6, OS:11.2,
   name:iPhone 8 }
   { platform:iOS Simulator, id:B8CCF670-BAA6-468E-8A7B-40B746267A06, OS:11.2,
   name:iPhone 8 }
   { platform:iOS Simulator, id:4AA7D787-5FA5-42B1-968F-009D2EF4A8F5, OS:11.2,
   name:iPhone 8 Plus }
   { platform:iOS Simulator, id:EB23FF62-A6DB-42E6-89AF-2245E27AE7A3, OS:11.2,
   name:iPhone 8 Plus }
   { platform:iOS Simulator, id:381886E4-B5D2-46C8-A8EA-EBDE53CFA277, OS:11.2,
   name:iPhone SE }
   { platform:iOS Simulator, id:545E3C77-2B72-4E4E-8837-3C03EBFD02E4, OS:11.2,
   name:iPhone SE }
   { platform:iOS Simulator, id:6EE728A7-A268-4514-98AE-D284C3A04CB2, OS:11.2,
   name:iPhone X }
   { platform:iOS Simulator, id:78C856F4-B138-4956-8407-A91D83BD518D, OS:11.2,
   name:iPhone X }
   
   Ineligible destinations for the "Security_Network" scheme:
   { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder,
   name:Generic iOS Device }
   { platform:iOS Simulator,
   id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder,
   name:Generic iOS Simulator Device }
   Error code 70 for command: xcodebuild with args:
   -xcconfig,/Users/matyu/Security_Network/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-workspace,Security_Network.xcworkspace,-scheme,Security_Network,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
   Simulator,name=iPhone
   X,build,CONFIGURATION_BUILD_DIR=/Users/matyu/Security_Network/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/matyu/Security_Network/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:125:13)
   at ChildProcess.emit (events.js:213:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
                                              
/Users/matyu/.meteor/packages/angular-templates/.1.0.9.1p59k5q.gmaqk++os+web.browser+web.cordova/plugin.compileNGTemplate.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
ExitWithCode:1

**Comment by aldeed** [comment]
@MatteoOrtiz I suggest submitting a new issue to be sure your comment is seen and investigated
