### ISSUE TITLE
[1.4.2-beta.6] Error: Cannot find module './entry.js

### ISSUE THREAD

**Issue by jakobrosenberg** [meteor/meteor#7830]
meteor create beta6 --release 1.4.2-beta.6
cd beta6
meteor

<details>
 <summary>Trace log</summary>
=> Started proxy.                                                                                                              
=> Started MongoDB.                                                                                                            
W20160927-22:22:38.417(2)? (STDERR) c:\Users\jakob\kitchensink\meteor\beta6\.meteor\local\build\programs\server\boot.js:333    
W20160927-22:22:38.480(2)? (STDERR) }).run();                                                                                  
W20160927-22:22:38.481(2)? (STDERR)    ^                                                                                       
W20160927-22:22:38.481(2)? (STDERR)                                                                                            
W20160927-22:22:38.482(2)? (STDERR) Error: Cannot find module './entry.js'                                                     
W20160927-22:22:38.482(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:85:1)
                                                                                                                               
W20160927-22:22:38.483(2)? (STDERR)     at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.js (node_mo
dules/meteor/modules/node_modules/reify/lib/runtime.js:1:1)                                                                    
W20160927-22:22:38.483(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:
153:1)                                                                                                                         
W20160927-22:22:38.484(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
                                                                                                                               
W20160927-22:22:38.485(2)? (STDERR)     at meteorInstall.node_modules.meteor.modules.server.js (packages/modules/server.js:4:1)
                                                                                                                               
W20160927-22:22:38.485(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:
153:1)                                                                                                                         
W20160927-22:22:38.485(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
                                                                                                                               
W20160927-22:22:38.486(2)? (STDERR)     at node_modules/meteor/modules/node_modules/reify/lib/runtime.js:127:1                 
W20160927-22:22:38.486(2)? (STDERR)     at node_modules/meteor/modules/node_modules/reify/lib/runtime.js:127:1                 
W20160927-22:22:38.486(2)? (STDERR)     at c:\Users\jakob\kitchensink\meteor\beta6\.meteor\local\build\programs\server\boot.js:
292:10                                                                                                                         
=> Exited with code: 1   

</details>

**Comment by jakobrosenberg** [comment]
Issue persists in beta.7

**Comment by tcastelli** [comment]
still persists in beta.9

```
W20161006-06:21:16.545(2)? (STDERR) D:\Programming\webstorm_workspace\testapp\.meteor\local\build\programs\server\boot.js:333
W20161006-06:21:16.548(2)? (STDERR) }).run();
W20161006-06:21:16.549(2)? (STDERR)    ^
W20161006-06:21:16.550(2)? (STDERR)
W20161006-06:21:16.551(2)? (STDERR) Error: Cannot find module './entry.js'
W20161006-06:21:16.552(2)? (STDERR)     at require (packages\modules-runtime.js:102:19)
W20161006-06:21:16.553(2)? (STDERR)     at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.js (packages\modules.js:193:13)
W20161006-06:21:16.555(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:170:9)
W20161006-06:21:16.559(2)? (STDERR)     at require (packages\modules-runtime.js:99:16)
W20161006-06:21:16.560(2)? (STDERR)     at meteorInstall.node_modules.meteor.modules.server.js (packages\modules.js:24:1)
W20161006-06:21:16.564(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:170:9)
W20161006-06:21:16.565(2)? (STDERR)     at require (packages\modules-runtime.js:99:16)
W20161006-06:21:16.567(2)? (STDERR)     at packages\modules.js:324:15
W20161006-06:21:16.570(2)? (STDERR)     at packages\modules.js:337:3
W20161006-06:21:16.571(2)? (STDERR)     at D:\Programming\webstorm_workspace\testapp\.meteor\local\build\programs\server\boot.js:292:10
=> Exited with code: 1
```

**Comment by ignl** [comment]
+1 I get it too in beta.9

**Comment by wojtkowiak** [comment]
+1 Windows 10 64bit

**Comment by tcastelli** [comment]
still persists in beta.11, exactly the same Error Windows 10 64bit

**Comment by benjamn** [comment]
I believe this will be fixed by `meteor update --release 1.4.2-beta.12`, thanks to https://github.com/meteor/meteor/commit/c572b12f26859c94889658c4e1838ea1b5156739 and https://github.com/meteor/meteor/commit/91058b53a743b3504b833591281768f9e4fc2e9e.

The solution involved calling `files.symlink(source, target, "junction")` to create "junction points" instead of fully copying `node_modules` directories. Junction points are like symbolic links except that they only work for directories (a drawback), and you don't have to be an administrator to create them (a big advantage).

If you test out `1.4.2-beta.12` on Windows, and you see any `EACCESS` errors relating to `node_modules` directories, you might need to run PowerShell or `cmd` as an administrator. That shouldn't be necessary, but it might help.

**Comment by xauxatz** [comment]
I still have this problem on Windows 10 with meteor version 1.4.2.3....
How can I fix it?

**Comment by abernix** [comment]
@xauxatz Please try a fresh re-install using these instructions and try to avoid running Meteor as "Administrator" ever.  If you still have a problem, please open a new issue about your configuration and how you're experiencing this in a new issue as this issue is closed.

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7/Win8.1:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.2.3 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working. 

Thanks!

**Comment by xauxatz** [comment]
Ok, thanks, I already did the above and it doesn't work, so I'll open a new one

**Comment by dongzhi-yang** [comment]
@xauxatz , where is the new case, I have the same problem now, I am trying to upgrade from 1.4.2.3 to the latest on windows 10. Thanks!!

**Comment by xauxatz** [comment]
I can't recall whether I actually created it, sorry - you may have to do it. I fixed my issue but also don't remember how :-(

**Comment by dongzhi-yang** [comment]
Opened new issue https://github.com/meteor/meteor/issues/8727
