### ISSUE TITLE
[1.4.1.1] platform.js:734 Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by stolinski** [meteor/meteor#7839]
```
platform.js:734 Uncaught TypeError: Cannot read property '0' of null
```

I'm getting this odd error when attempting to use https://github.com/nygardk/react-share 

I don't see anything odd about the react-share package and it's pretty heavily used. I'm only getting the error when importing 

```
import {
  ShareButtons,
  ShareCounts,
  generateShareIcon
} from 'react-share';
```

**Comment by abernix** [comment]
[Guidelines for reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)

I realize it may seem simple, but building reproductions takes a significant amount of developer's time.  Cloning a repo is easy and there are a lot more issues than there are developers to work on them.  Please make a very basic sample reproduction of your problem in a new Meteor project (as small and simple as possible), upload to GitHub and link it here.

**Comment by sakulstra** [comment]
@stolinski Did you find a solution to your problem?

@abernix I'm facing the same error, so I created a small reproduction repository: https://github.com/sakulstra/meteor-react-share-bug

**Comment by abernix** [comment]
@sakulstra Thank you very much for the easy reproduction!

This is occurring because of the [`platform` dependency](https://www.npmjs.com/package/platform) of the `react-share` NPM.  The `platform` package [does the following to check for Node](https://github.com/bestiejs/platform.js/blob/master/platform.js#L736-L741) but since `process` is defined as an object because of [the `process` module](https://github.com/defunctzombie/node-process/blob/da3e95de86ebbc23a81f80d2964de39ece947044/browser.js#L36) (a module that I believe is typical of all [Meteor](https://github.com/meteor/node-stubs/blob/master/package.json#L24)/[Browserify](https://github.com/substack/browserify-handbook#process)/[Webpack](https://github.com/webpack/node-libs-browser/blob/master/package.json#L23) setups) it's inadvertently classifying itself as Node in this step and then failing when it tries to grab the numeric version of the `process.version` (which is just an empty string).

Since `process` sets `process.browser` to `true` in the browser environment, this could be avoided if the `platform` checked that, like this:

```js
else if (typeof context.process == 'object' && !context.process.browser && (data = context.process)) {
```

I'm not entirely sure how this is avoided on other platforms, but my gut is that maybe `platform` should check this?  Though I'm admittedly not entirely familiar with these environments.  Anyone have an idea?

**Comment by abernix** [comment]
Thanks to the PRs that you submitted to `platform` in bestiejs/platform.js#109 and the dependency on `platform` getting updated in nygardk/react-share#46, I'm happy to say that this problem is resolved.  I tested by using your same reproduction and simply updating the packages in your `package.json` with `meteor npm update --save`.

Thanks for filing this issue and thanks for your work in helping getting it resolved!
