### ISSUE TITLE
onCreated has no this.data, but onRendered does

### ISSUE THREAD

**Issue by femans** [meteor/meteor#7856]
**version and architecture:**
Meteor 1.4.1.1, arch linux

**behavior and expected behavior**
When requesting the data in onCreated, `null` is returned. In onRendered it returns the normal data context. My expectation and understanding was that both should be able to use the data. 

**code:**
```
Template.architecture.onCreated(function architectureOnCreated(){
  var dataContext = this.data
  console.log('oncreated dataContext:',dataContext  )
}
Template.architecture.onRendered(function architectureOnRendered() {
  var dataContext = this.data
  console.log('onrendered dataContext:',dataContext  )
}
```

Output in the console of the browser: 
```
oncreated dataContext: null
onrendered dataContext: Object {_id: "xYAs5NgwcAFempasG",  ... }
```

**packages list:**
accounts-password            1.3.0  Password support for accounts
aldeed:collection2           2.10.0  Automatic validation of insert a...
aldeed:simple-schema         1.5.3  A simple schema validation object...
blaze-html-templates         1.0.4* Compile HTML templates into react...
check                        1.2.3  Check whether a value matches a p...
ecmascript                   0.5.8  Compiler plugin that supports ES2...
es5-shim                     4.6.14  Shims and polyfills to improve E...
fortawesome:fontawesome      4.5.0* Font Awesome (official): 500+ sca...
ian:accounts-ui-bootstrap-3  1.2.89  Bootstrap-styled accounts-ui wit...
insecure                     1.0.7  (For prototyping only) Allow all ...
iron:router                  1.0.13  Routing specifically designed fo...
jquery                       1.11.9  Manipulate the DOM using CSS sel...
matb33:collection-hooks      0.8.4  Extends Mongo.Collection with bef...
mdg:validated-method         1.1.0  A simple wrapper for Meteor.methods
mdg:validation-error         0.5.1  A standard validation error to be...
meteor-base                  1.0.4  Packages that every Meteor app needs
mizzao:bootstrap-3           3.3.1_1  HTML, CSS, and JS framework for...
mobile-experience            1.0.4  Packages for a great mobile user ...
mongo                        1.1.12  Adaptor for using MongoDB and Mi...
reactive-dict                1.1.8  Reactive dictionary
reactive-var                 1.0.10  Reactive variable
sacha:spin                   2.3.1  Simple spinner package for Meteor
session                      1.1.6  Session variable
shell-server                 0.2.1  Server-side component of the `met...
standard-minifier-css        1.2.0* Standard css minifier used with M...
standard-minifier-js         1.2.0  Standard javascript minifiers use...
tracker                      1.1.0  Dependency tracker to allow react...
u2622:persistent-session     0.4.4  Persistently store Session data o...

**Comment by abernix** [comment]
Both can use the `data`, but the `.data` _attribute_ (as you are calling it) is non-reactive, read-only and only current as of the last render ([per the Blaze documentation here](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-data).  Therefore, it will not be available on the initial call into `onCreated` since that occurs before the first render.  If you need to auto-run something reactively inside of `onCreated`, consider using `Template.currentData` (which _is_ reactive) inside an `autorun`.

Also, in the future, unless you're absolutely 100% sure it is a bug, questions like this are better suited for the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).
