### ISSUE TITLE
[ubuntu] Extracting stuck / stopped / stalled

### ISSUE THREAD

**Issue by Rhywden** [meteor/meteor#7862]
See https://github.com/meteor/meteor/issues/7688 for a similar thing on Windows.

OS is Ubuntu 14.04 LTS (server variant)

I'm on 1.4.1.1 and I just tried to create a new project in order to facilitate a bug reproduction.

The creation is now stuck at

```
Extracting npm-mongo@1.5.50...
```

Just for fun, I tried a `meteor update` on my existing (and still working) project. It will show the same problem.

**Comment by abernix** [comment]
I've run into this, but this could happen for any number of file-system related issues.  (Though, hopefully the Meteor output message/behavior can be improved, as yes, usually it just sits forever).

To help debug, please provide the output of these commands, run in another terminal, from your Meteor app directory, after `meteor` has been stuck (make sure it's been stuck for at least a few minutes):

* `df --output .` (This will show your current partitions usage, including inode usage)
* `pstree $(pgrep -f "meteor.*index.js")` (This will show the Meteor process tree including, most likely, stuck `tar` processes).

**Comment by jamesgibson14** [comment]
Same problem on ubuntu, output: 
`james@ubuntu:~$ df . --output
Filesystem                  Type  Inodes  IUsed  IFree IUse% 1K-blocks    Used    Avail Use% Mounted on
/dev/mapper/ubuntu--vg-root ext4 1196032 199191 996841   17%  18705132 3031276 14700648  18% /`
`james@ubuntu:~$ pstree $(pgrep -f "meteor.*index.js")
node─┬─tar───tar───gzip
     └─10*[{node}]`

**Comment by jamesgibson14** [comment]
Okay I found a solution, the permissions were messed up on my /tmp. Running this `sudo chmod 1777 /tmp` and I was able to run update without problem.

**Comment by abernix** [comment]
@jamesgibson14 Glad you found the solution.  That would certainly cause an issue!

@Rhywden Thanks for reporting this originally.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
