### ISSUE TITLE
Server sent add for existing id

### ISSUE THREAD

**Issue by mitiaptest** [meteor/meteor#7874]
Hello All,

I am facing following issue on my production server 
Uncaught Error: Server sent add for existing id: tsdfdfdfdff","Script":"http://meteor.local/035c166275243dec943f409a6249caa251ff8465.js?meteor_js_resource=true","Line":73,"Error":{"type":"javascript","url":"","localtime":1469762833104,"message":"Uncaught Error: Server sent add for existing id: tsdfdfdfdff","fileName":"http://meteor.local/035c166275243dec943f409a6249caa251ff8465.js?meteor_js_resource=true","lineNumber":73,"columnNumber":17188,"name":"Error"}}

After that logged in user mongo collection document get deleted from collection.

Please help me on this issue.

Thanks,
Mit

**Comment by abernix** [comment]
It seems that you're passing an explicit `_id` instead of allowing the server/client to decide one on your own.  Perhaps you're allowing the user to choose their own `_id`?  `tsdfdfdfdff` certainly looks like a user entering random input into some field.

But closing this issue because the problem you're referring to is too vague to accurately provide help and this is not the place to ask for help with using Meteor.  Additionally, what you have provided is not enough to isolate the problem, or even to determine if the problem is in Meteor itself.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please ask for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.

Thanks! :)
