### ISSUE TITLE
"The system cannot find the path specified."

### ISSUE THREAD

**Issue by javietanh** [meteor/meteor#7891]
Dear meteor team,

I found the problem with meteor install on window with error "The system cannot find the path specified."

- Meteor : 1.4.1
- Window: 10

Descriptions: when you open cmd outside of the project and check the version by command "meteor --version" and it's work. but on the project folder using the same command the error will happen "The system cannot find the path specified."

- The problem happen because on project folder have the same folder name ".meteor". when i change the name of the ".meteor" folder then the problem gone. I think the problem happen when it know the wrong .meteor folder (local project folder and appdata folder)

- Is there any way to change the meteor install folder from AppData/.meteor to any other like "c:\meteor"?

Viet Anh,
Cheers

**Comment by abernix** [comment]
This just doesn't seem to be true for me.  Did you restart your computer after installing Meteor?  See this screen-capture:


![screen recording 2016-10-11 at 03 16 pm 1](https://cloud.githubusercontent.com/assets/841294/19270155/3c2f5c3a-8fc7-11e6-873c-d37df590c43d.gif)

**Comment by abernix** [comment]
I believe #7766 is the solution to your problem as the `meteor-tool` might not have been fully extracted after being downloaded.   Since we haven't heard back from you, I'm going to close this issue, but please try that work-around and see if it fixes your problem.

As to your other question about having the install folder be something besides `.meteor`.  It must be named `.meteor`, but it should be possible to make a junction to another location if you'd like – but the other location's directory must still be called `.meteor`.  See https://github.com/meteor/meteor/issues/7838#issuecomment-254763741 where it's mentioned that this should work.
