### ISSUE TITLE
Meteor 1.4.1.2 use npm@v3.10.8 issue!

### ISSUE THREAD

**Issue by Here21** [meteor/meteor#7895]
```
Started proxy.                             
webpack:webpack: updating npm dependencies -- underscore, connect, cors, webpack, webpack-dev-middleware, webpack-hot-middleware, memory-fs, mime...
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While building plugin `webpack:webpack` in package `webpack:webpack`:
   error: couldn't install npm packages from npm-shrinkwrap: Command failed:
   /home/martin/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
   npm ERR! Linux 4.4.0-38-generic
   npm ERR! argv "/home/martin/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/martin/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
   npm ERR! node v4.6.0
   npm ERR! npm  v3.10.8
   npm ERR! code EBADPLATFORM
   
   npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
   npm ERR! notsup Valid OS:    darwin
   npm ERR! notsup Valid Arch:  any
   npm ERR! notsup Actual OS:   linux
   npm ERR! notsup Actual Arch: x64
   
   npm ERR! Please include the following file with any support request:
   npm ERR!     /home/martin/WorkSpace/Coding.io/webpack/courierwarrior/newApp/packages/webpack/.npm/plugin/webpack_webpack-new-1fwrd90/npm-debug.log
   npm ERR! Linux 4.4.0-38-generic
   npm ERR! argv "/home/martin/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/martin/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
   npm ERR! node v4.6.0
   npm ERR! npm  v3.10.8
   npm ERR! code EBADPLATFORM
   
   npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
   npm ERR! notsup Valid OS:    darwin
```

maybe npm@v3.10.8 has a bugs, [npm@v3.10.8 issue](https://github.com/npm/npm/issues/14042)

but now, I had to downgrade to 3.10.7, so I let `METEOR@1.4.1.1` and then, new problem has coming.

```
/home/martin/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-17ebq6/os.json'
    at Error (native)
```
same problem? please comment.

**Comment by aboobakkar** [comment]
ya.. same problem in my solution...
.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-1aziw8k/os.json'
    at Error (native)

**Comment by alexmironof** [comment]
https://github.com/meteor/meteor/blob/release-1.4.2/tools/fs/files.js#L728
this is the solution: I manually replcased this line and it works fine

**Comment by aboobakkar** [comment]
i have issue for this change 

.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fs/files.js:464
files.cp_r = function(from, to, options = {}) {
                                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/home/aboo/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tools/utils/buildmessage.js:2:13)
    at Module._compile (module.js:409:26)

**Comment by alexmironof** [comment]
@aboobakkar  `options = {}` is ES2015 feature. it is default value for function param. 
you dont need to replace whole file. just one line:
`  var promise = process.platform === "win32"
    ? tryExtractWithNative7z(buffer, tempDir, options)
    : tryExtractWithNativeTar(buffer, tempDir, options);`

**Comment by alexmironof** [comment]
Oh sorry, this is windows related problem with using `tar` if it is in path and this line helps. But I think the linux problem also with native tar

**Comment by kaiyes** [comment]
so how does one solve this problem in linux ? @alexmironof

**Comment by alexmironof** [comment]
@kaiyes maybe you can try to replace whole thing with `tryExtractWithNpmTar` function

**Comment by abernix** [comment]
@aboobakkar @alexmironof @kaiyes Let's keep this conversation for the original issue mentioned and not the second (unrelated) issue which happened after the downgrade and is tracked in its own ticket, #7806.  @Here21 Please keep _one issue_ per ticket when opening issues! :smile:
***
As to the original issue with `webpack` not building under NPM 3.10.8, it must be a bug with `webpack` or NPM directly and this has nothing to do with Meteor.

My guess?  Maybe this is happening because the shrinkwrap is being generated on one `arch` (e.g. OS X) and used on another, but I'm not entirely sure.  The _real_ issue here is that something is trying to install `fsevents` (a Mac OS-only package that will NOT run on Linux) on what is clearly a linux x64 machine, as indicated by `(current: {"os":"linux","arch":"x64"})`.  You might try adding the `--no-optional` flag to the `npm` command when you install `webpack`, which could help – assuming its setup as optional by `webpack`. Anyhow, this isn't the place for a `webpack` setup discussion.

Lastly, you didn't include a reproduction repo, so I don't have a way to try it myself.  Closing as unrelated to Meteor.

**Comment by abernix** [comment]
Also, if they're unable to fix it, you could probably add `fsevents` to the [`optionalDependencies` section of your `package.json`](https://docs.npmjs.com/files/package.json#optionaldependencies).

**Comment by cocacrave** [comment]
When I try to `meteor update` to 1.4.1.2 it starts downloading but eventually throws error:

```
/Users/cocacrave/.meteor/packages/meteor-tool/.1.4.1_1.8cimor++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/55/l6y1kpqs0jxd8lnsfv3651lw0000gn/T/mt-9j2wq9/os.json'
    at Error (native)
```

I tried couple of times but throws same errors. How do I update?

**Comment by Here21** [comment]
It is recommended to keep the 1.4.1.1 version, This problem does not seem to exist under the mac os, And this change little change, it is recommended to maintain 1.4.1.1 version.

**Comment by abernix** [comment]
@Here21 I realize you're having a problem with external components, but as I explained above your issue is **not** related to a Meteor bug.   It is not recommended to keep 1.4.1.1 as 1.4.1.2 includes important upgrades to Node and NPM for security fixes and nothing else (see [Node's announcement](https://nodejs.org/en/blog/vulnerability/september-2016-security-releases/) here).

@cocacrave Your actual error is #7806.  Please see that error for a work-around, and to follow it for a permanent solution.

**Comment by Here21** [comment]
yes, I totally agree with you, I want to know why the downgrade will fail.
I am sorry that my question is not clear

**Comment by abernix** [comment]
The downgrade is failing because of a CDN/tar-extraction issue.

Try doing your downgrade by:

* Change `.meteor/release`, `.meteor/packages` and `.meteor/versions` files back to the old versions (using `git`).

* Setting the following environment variable:

        export METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net

* Then:

        meteor
