### ISSUE TITLE
Extracting meteor-tool@1.4.1_1...

### ISSUE THREAD

**Issue by ManuelDeLeon** [meteor/meteor#7901]
What's the official response to `Extracting meteor-tool@1.4.1_1...` taking forever?

Some people have said "reset your project and delete the versions file" but 1) It doesn't work and 2) even if it did, it's not really a solution.

**Comment by abernix** [comment]
I don't work for MDG (read: not official), but my response (as in, a person who monitors Meteor issues) is: This issue began as the eternal "Downloading" message.  The issue is not _completely_ resolved, as indicated by existing open issues (e.g. #7862, #7476), but the issue has been significantly improved by additional messaging such as providing additional details such as "Extracting" or "Loading" (thanks to 536eecea01bff1a285f0a4569ab95548e4877e9e).  Improvements have also been made to the actual downloading process (thanks to resuming in #7267).  There have been recent issues that were found and fixed, such as #7688 and #7766 (via d5c83aaf8fe59a09688f0d17a61b6e7f10ee7af2 which will land in 1.4.2, currently in beta).  Please scour those existing issues for possible work arounds.

Right now, if you're experiencing this problem, it's believed to have something to do with actual tool being used to extract or file-system issues (full disk, out of inodes, etc.). 

If you're having a specific problem, consider reviewing closed issues to see if your problem is resolved (or will be resolved) in another release or add additional input to the most relevant issue.  Opening new issues without any details about your versions/platform/environment or details about what you've tried isn't helpful.
