### ISSUE TITLE
✗ Xcode: xcode-select: error: tool 'xcodebuild' requires Xcode, but active   developer directory '/Library/Developer/CommandLineTools' is a command line   tools instance

### ISSUE THREAD

**Issue by xubuhang** [meteor/meteor#7905]
meteor add-platform ios 
<img width="570" alt="qq20161011-3 2x" src="https://cloud.githubusercontent.com/assets/4189632/19260494/971ab6d6-8fbc-11e6-8b61-d9412670990e.png">

**Comment by abernix** [comment]
As indicated by the message, this is not a bug with Meteor and there is a problem with your Xcode installation.

Please see: https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786

**Comment by stormbkk87** [comment]
On a brand new Macbook Pro, OS X Sierra, I also get this error. Nowhere in your prerequisite documentation does it show how to fix the xcode-select path. Really should be added to the documentation where you direct developers on a command line error.

http://guide.meteor.com/mobile.html#installing-prerequisites

    sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by Chicooz** [comment]
i got same error and the fix worked for me but i don't use meteor in this project :)

**Comment by cisum-la** [comment]
Fixed the issue for me as well (High Sierra+ XCode 9.2)

**Comment by abernix** [comment]
It seems that that during the `meteor add-platform ios` step we advise using the "full" Xcode installation rather than the "Command Line Tools"-only approach.  This is certainly important since the full Xcode installation is necessary to build the app, but it seems that the additional installation of the command line tools is not part of that Xcode installation process.

The popularity of the above command by @stormbkk87 makes it pretty clear that we need to, at the very least, amend the Meteor Guide to account for this.  Therefore, I've opened https://github.com/meteor/guide/pull/838, and hope that this will help future developers avoid this pitfall.

If developers are still arriving here with this problem in the future (and unaided by the Meteor Guide change), it's possible that we should add an additional interactive step to the `meteor add-platform` tooling that will run `xcode-select -p` (on behalf of the developer) to check if it is already set.  If it's not, then we can instruct developers to run `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` at that time.

Thanks for raising the issue @stormbkk87—I hadn't caught wind of the popularity of your helpful comment until recently!

**Comment by fborie** [comment]
The command pointed by @stormbkk87 nailed it 100%. I wasnt even trying to use meteor in a brand new Macbook pro 2017, when the problem about bad path for _select-xcode_ arise (trying to build some nodejs services - with some native dependecies as I can see now -) . Thanks!

**Comment by erickfer17** [comment]
esto ha funcionado para mi, 
Primo abres xCode sino lo has abierto por primera vez y creas un proyecto cualquiera, luego en la terminal colocas
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

**Comment by iflam** [comment]
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer worked for me too

**Comment by iagopiimenta** [comment]
https://medium.com/@vschroeder/xcode-select-error-tool-xcodebuild-requires-xcode-but-active-developer-directory-fb7d3408c80b

```bash
xcode-select --install
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license accept
```

**Comment by lpcheniris** [comment]
> 🚫
> 
> ```
> > $ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer                                       [±master ●]
> xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/Developer'
> ```
> 
> 😞

I got the same error..................

**Comment by Smokolisz** [comment]
> > 🚫
> > ```
> > > $ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer                                       [±master ●]
> > xcode-select: error: invalid developer directory '/Applications/Xcode.app/Contents/Developer'
> > ```
> > 
> > 
> > 😞
> 
> I got the same error..................

 @lpcheniris  @mikeumus did you found the fix? I have the same issue.

**Comment by killkrt** [comment]
@Smokolisz I guess that you have the "Command line tools" installed instead of XCode, so you could try to use:

`sudo xcode-select -switch /Library/Developer/CommandLineTools`

**Comment by Smokolisz** [comment]
Thanks for your reply, but it didnt work for me. I get this error:
`Promise rejected with non-error: "xcode-select: error: tool 'xcode build" requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance\n`
I have installed XCode, i can open it and create a new project and run it on iphone emulator. I have no idea why this isnt working

**Comment by markkuetemeyer** [comment]
I have the same problem as @Smokolisz ...

**Comment by filipenevola** [comment]
Hi, if we are still having this issue on Meteor 1.11 please open a new issue.
