### ISSUE TITLE
windows extract issue

### ISSUE THREAD

**Issue by zernitta** [meteor/meteor#7907]
**Problem symptoms**

When trying to add the angular-templates to my meteor project it gets stuck and just keeps spinning at:
Extracting angular-templates@1.0.9...

I don't seem to be getting an error.

**Environment**

Meteor: v1.4.1.2 (node: v4.2.4, npm: 2.14.12)
Windows 7 64-bit

**Comment by abernix** [comment]
This is likely due to #7689 and should be fixed with Meteor 1.4.2 (Currently in beta).  Please feel free to try updating the beta to see if this problem goes away for you:

    meteor update --release 1.4.2-beta.9

The beta channel isn't always bug free and you may run into unrelated bugs, but if you're in a position to test that this particular feature has been fixed for you, it would certainly be appreciated.  You can always roll-back the version of Meteor you were using by undoing the update with `git`. You can find instructions for using the current beta release in #7668.

Please report back if you still have problems with this or if it fixes it for you.

**Comment by abernix** [comment]
Meteor 1.4.2 is now out and should (hopefully) fix this problem for you.  Can you please try reinstalling Windows fresh with these instructions: (this will allow the installer to install the full version with the new downloading mechanism, without having to use the old mechanism to install it).

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.1.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

Let us know if this is fixed!  Would be nice to cross it off the list! ;)
