### ISSUE TITLE
Add `meteor "pre-build"` command

### ISSUE THREAD

**Issue by laosb** [meteor/meteor#7914]
My Docker image build system can cache built layers to boost the build process. So to use the cache feature, we need a command which installs(downloads) all meteor packages in `.meteor/packages`. I guess many users want that, too.

**Comment by hexsprite** [comment]
Would be great to have to avoid stuff like this in Continuous integration scripts:

https://github.com/xolvio/qualityfaster/blob/master/.scripts/cache-build-and-dependencies.js

**Comment by abernix** [comment]
You could easily accomplish this right now by:

In a `server` File:
```js
import { Meteor } from 'meteor/meteor';
Meteor.startup(() => Meteor.isDevelopment && process.env.EXIT_ON_START && process.exit(0));
```

Starting Meteor with that variable set and `--once`:

```sh
EXIT_ON_START=true meteor --once
```

@hexsprite That looks pretty complicated.  In most CI environments you can just add the `.meteor` directories to the "cached directories" and have them restored/saved automatically before/after a build.  This might make that unnecessary?

@laosb I know the cache method would be different, but similarly, in `docker` you could just mount the cached `.meteor` directory in the same place and experience a benefit.

**Comment by laosb** [comment]
Actually many cloud Docker build platforms don't support cached folders. They just automatically cache layers (If the previous layer is the same and the command in this step is same, then the cached layer applies, unless the file `COPY`-ied from repo (previous layer) is changed.)

So in my case I've already cache `npm` packages by:

```
WORKDIR /app
ADD package.json /app/
RUN meteor npm i --production
```
*(Actual Dockerfile part from [VividCloud/dometeor](https://github.com/VividCloud/dometeor/blob/master/Dockerfile.buildtime#L4))*

In this way if the list of npm packages didn't change (`package.json`), then it will use the cached layer. I want to a similar solution like caching npm packages.

**Comment by abernix** [comment]
@laosb I understand. I was referring specifically to it being a different caching technique.  You could have your `$HOME/.meteor` directory mounted as a `--volume` when the `docker run` is executed and speed things up by means of using the cached directory instead of rebuilding from scratch.

Your suggestion still sounds like a good idea.  And you could accomplish this right now by adding the code I suggested above to a server file and adding the following to your `Dockerfile`:

    RUN EXIT_ON_START=true meteor --once

I'm not sure `meteor install` is a good command to use for this as it's too similar to `meteor add`.  It might be easiest to build this as part of the `run` command.  (e.g. `meteor run --something`, `meteor --something`).  Maybe:

* `--no-spawn`?
* `--build-and-exit`?
* `--stop-before-start`? (kidding) :smile:

Not sure I'm happy with any of those.

I don't think it's this easy but maybe this could be implemented along the lines of a conditional around [this line](https://github.com/meteor/meteor/blob/9a85f0cbb369dea10110cc9f33d3ddedc8b38a8f/tools/runners/run-app.js#L752) which simply did a `appProcess.stop()` instead?

**Comment by laosb** [comment]
Yeah, but adding an extra server file sounds numb. A flag is fine for my case. --no-spawn is a good idea.

**Comment by athyuttamre** [comment]
@abernix I'm also interested in being able to install packages separately from building.

I'm not familiar with the Meteor source code, but forcing a build and then short-circuiting it seems a little convoluted for what should ideally be just a download step. Is this really the cleanest way to fix this?

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20%60meteor%20%22pre-build%22%60%20command&body=Migrated%20from:%20meteor/meteor%237914) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by athyuttamre** [comment]
Posted a follow-up here: https://github.com/meteor/meteor-feature-requests/issues/185.
