### ISSUE TITLE
Input type="time" and b or strong tags do not work in android cordova

### ISSUE THREAD

**Issue by openqubit** [meteor/meteor#7936]
I have made an android app in cordova and meteor js but i cannot display time or b tags in my android app. I am using framework7 for the frontend

`<input type="time" />` and `<b></b>` do not display time and bold respectively.

**Comment by abernix** [comment]
Meteor Issues are reserved for reporting bugs in Meteor with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but a question about how to use it or an issue with the other frameworks you're using (or just a CSS issue).

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for this sort of question.

I highly recommend you post your question to [StackOverflow](https://stackoverflow.com/) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thanks for your understanding.

**Comment by openqubit** [comment]
"but a question about how to use it or an issue with the other frameworks you're using (or just a CSS issue)."

Alight from ya high horsy your highnee!
