### ISSUE TITLE
Add mongodb collation support

### ISSUE THREAD

**Issue by serkandurusoy** [meteor/meteor#7946]
MongoDB 3.4 is around the corner now coming in with a [long awaited](https://jira.mongodb.org/browse/SERVER-1920) and recently implemented [collation support](https://docs.mongodb.com/master/reference/collation/) built in.

The nodejs driver is already going to be providing support for it so it leaves us to complete the frame by doing the following:
- Expose collation configuration options to the `Mongo.Collection` constructor
- Enhance `Minimongo.Sorter` to accept and respect collation options, possibly passing the options on to an implementation of `String.prototype.localeCompare`
- Allow `Collection.find` to pass per-query collation options on the client
- Allow [supported commands](https://jira.mongodb.org/browse/SERVER-1920) on the server to accept per-command collation options

to add collation support to our mongo/minimongo.

**Comment by pozylon** [comment]
I don't think that Minimongo should support that. Minimongo doesn't support Geospatial queries or $text searches either but that is absolutely no issue because if you have full-text search or geospatial query this should be handled by the server anyway.

If you really need it, regex and options like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare come into my mind.

Server side support for collation is a plus though.

**Comment by serkandurusoy** [comment]
I think you may have confused collations with something else. Collation is not (primarily) an index or query type. It has much more to do with the sort order of the returned result.

localeCompare is merely a hack you (now) have to apply to your query result. Furthermore, implementing localeCompare on Minimongo.Sorter instead of the current string comparator is extremely trivial.

You don't want to use it? Fine, don't use it. But I don't think I understand why you are simply *against* it.

**Comment by pozylon** [comment]
Don't get me wrong, I'd be very happy to see this feature in production. But it's too much at once.

If localeCompare or any other sort comparator in the wild can behave exactly like the mongodb implementation of collation, I'm not against minimongo implementation at all, but as you can see on the mozilla page for example localeCompare's options are not supported by major mobile browsers and not in line with mongodb's capabilities.

So having that feature in Minimongo.Sorter ensuring the sort order is perfectly consistent leaves us with basically two variants:

1. Support collation 100% on the server (pass through) and keep up to date with MongoDB versions. client side insert, update etc. with collation will have to be supported as well so we would have to make sure update and any query with $eq respect the collation options as well. Having all together would be a huge amount of work and is not trivial at all.
2. Only support very few options of collation on the server through the meteor-mongo wrapper and implement that, consistently throwing an error when collation is being used with options not supported on the client and server.

That's why I would rather like to see full per-command support server side and an error "collation is not supported" on the client and split the feature request in smaller chunks.

**Comment by serkandurusoy** [comment]
Well thank you indeed for clarifying why you would object to having it.

MongoDB collation support is based on ICU, so is Javascript's. That means, we get compatible results.

I do agree that the server support should be pass through, since what is supported by the db and its driver should not be reinvented on the application layer.

As for minimongo, I do respectfully disagree. I've been dealing with multilingual content my whole developer life and would strongly argue that having whatever support available is much much better than having none at all.

I would go as far as arguing that anyone dealing with in-browser string sorting would already be aware of the limitations. Supported options already cover a huge majority of requirements.

Desktop/mobile support is also very wide (the way I look at it, major mobile browsers indeed support it) and it should not be a new concern for anyone who deals with multilingual content anyway.

As per your argument, supporting a subset of the options sounds just fine and yet a better option than not supporting it at all.

And it still looks like supporting (on minimongo) the options that javascript support would still be as trivial as creating any new meteor feature would be.

So I'd be much happier with

>  full per-command support server side and an error "collation is not supported" on the client

rephrased as 

>  full per-command support server side and a warning "collation options are not fully available on the client" on the client when an unsupported one's being used

**Comment by pozylon** [comment]
"I've been dealing with multilingual content my whole developer life and would strongly argue that having whatever support available is much much better than having none at all."

I absolutely agree with that. And I think we both want the same thing, it's just the holistic approach i'm not happy with.

Some research:
https://github.com/andyearnshaw/Intl.js/#what-about-intlcollator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator

<img width="757" alt="bildschirmfoto 2016-10-22 um 17 24 23" src="https://cloud.githubusercontent.com/assets/2109393/19620367/67f811fa-987c-11e6-8a3b-04dd61376d75.png">

**Comment by serkandurusoy** [comment]
Intl.Collator is indeed the suggested method for string comparison where localeCompare falls short in terms of performance, but that being said, performance has never been minimongo's strongest suite. 

_(There has even been outstanding feature requests to implement indexing and those were not accepted due to the - possibly correct - assumption that client-side data sets would be small in size and not benefit from them.)_

Regarding intl.js, it is what it is, a polyfill for old browser support. But yet againg, I look at the same mobile browser support matrix and see it as quite a positive thing.

There already are lots of different browser compatibility quirks here and there with all things javascript, so I don't quite get the argument that this less-than-ideal coverage would be grounds for omitting this whole thing following an either/or approach.

**Comment by ShockiTV** [comment]
I would not be so optimistic about this even on server side.
It is same as with Geospatial - you need to decide if new document from oplog should be in the results so you need to know the full logic. Geospatial are forcing polling mode - it is not only affecting mini-mongo.
If u wanna use raw queries on server, nothing is stopping you and you have all the features of driver.
Enabling it by default and letting user to "sort correctly" cause he can could have very noticeable performance outcomes.
But if geo stuff got in, maybe this could too.

**Comment by serkandurusoy** [comment]
@ShockiTV I must admit I did not consider that. 

So does it mean that, while we're tailing the oplog, the query resultset should be updated based on the collated sort, requiring the oplog driver to be aware of and able to process collation options. Right?

Well, in that case, if one is able to implement an "acceptable" solution for minimongo, that solution could then be implemented for oplog tailing.

I'm arguing for this because I am assuming it is much easier to implement locale based string comparison compared to implementing geospatial queries. Right=

**Comment by dtruel** [comment]
Collation support on the server side is absolutely huge. It allows for case-insensitive indexes, which will provide a massive performance boost for some applications.  This should definitely be a priority for the server side.

**Comment by mitar** [comment]
BTW, one workaround for Minimongo: it accept now a function as a `sort` option, so you can sort documents in any way you want. See #6008.

**Comment by brylie** [comment]
> Enhance Minimongo.Sorter to accept and respect collation options, possibly passing the options on to an implementation of String.prototype.localeCompare

Locale aware sorting would be very useful in our project.

**Comment by simonozzy** [comment]
MongoDB 3.4 [views support](https://docs.mongodb.com/manual/core/views/) would also be super useful and will also hopefully be a workaround to use MongoDB aggregation pipelines which aren't supported in Meteor?
Any plans for supporting this in the roadmap? I could raise a new request?

**Comment by mitar** [comment]
@simonozzy: I think you should open another issue for views. I think it would be better to track discussion for that than here.

**Comment by mitar** [comment]
@serkandurusoy: So collation does not work on the server side, if you force Mongo polling?

I think that in general Meteor should have easy time to support any Meteor feature using polling. Even aggregation pipelines. That should probably be easy to fix if something does not work. For oplog, that is much harder because you have to duplicate the logic. I would wonder if somebody could test aggregation pipelines and collations using polling.

**Comment by serkandurusoy** [comment]
Anything can use polling in theory but the afaik problem is minimongo. It should be enhanced to support this, right?

**Comment by mitar** [comment]
Aha, so this is mostly Minimongo issue. I see.

**Comment by serkandurusoy** [comment]
Yep, otherwise we can achieve this on the server with rawCollection, but the sorting inconsistency across the client/server and the need to resort on the client from the fetched array with localeCompare (which itself is a little inconsistent with mongodb collation) makes it really an undesirable choice.

So yes, minimongo would be the only sane place to solve this problem.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Add%20mongodb%20collation%20support&body=Migrated%20from:%20meteor/meteor%237946) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
