### ISSUE TITLE
[1.4.2-rc.2] Exception: Accounts._getPasswordEnrollTokenLifetimeMs is not a function

### ISSUE THREAD

**Issue by od1k** [meteor/meteor#7951]
Getting this exception when calling Accounts.resetPassword.
Reverting to accounts-password 1.3.0 solves this issue.

<pre>Exception while invoking method 'resetPassword' TypeError: Accounts._getPasswordEnrollTokenLifetimeMs is not a function
    at packages/accounts-password/password_server.js:673:36
    at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
    at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:381:5)
    at [object Object].resetPassword (packages/accounts-password/password_server.js:656:19)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1107:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1107:17)
    at packages/ddp-server/livedata_server.js:707:46
</pre>

**Comment by benjamn** [comment]
This method was introduced to `accounts-base` in https://github.com/meteor/meteor/pull/7817. Try `meteor update accounts-base`? Then any version of `accounts-password` should work.

**Comment by od1k** [comment]
With `accounts-password@1.3.1-rc.2` tried to update accounts-base, which  upgraded from `1.2.11` to `1.2.13` but it still didn't solve the issue.
I had to `meteor add accounts-base@1.2.14-rc.2` to resolve it.

Shouldn't `accounts-password` have a higher version of `accounts-base` in its `package.js`?

**Comment by benjamn** [comment]
So, the only reason for `accounts-password` to have `@` version constraints in its `package.js` file is to allow publishing `accounts-password` without doing a full Meteor release, which is something that's only been possible since Meteor 1.4. To be honest, we're still figuring out best practices for post-1.4 `package.js` files, and the use of explicit version constraints is still an open question.

Since we're coming up on the Meteor 1.4.2 release, I've removed the version constraints, so the right (latest) versions should get picked up automatically by the release script, and hopefully this won't be a problem once 1.4.2 is released.

Thanks for alerting us to this annoyance.

**Comment by od1k** [comment]
Tested with rc.3 and it upgrades `accounts-base` and works as expected! 👍
