### ISSUE TITLE
Mongo.Collection throws EventEmitter

### ISSUE THREAD

**Issue by gsabran** [meteor/meteor#7954]
This code:
```js
try {
  var coll = new Mongo.Collection('__dummy_coll_' + Random.id());  
} catch (e) {
  console.log('error!', e);
  throw e
}
```
is throwing an error that is 
```
error! EventEmitter {
   id: 1,
   s: 
    { options: 
       { disconnectHandler: [Object],
         cursorFactory: [Object],
...
```

This only happens with a real `MONGO_URL`, and not why any url so it might be related to the database configuration. I started Meteor with:
`$  MONGO_URL=mongodb://<user>:<password>@<what-compose.io-told-me-to-put-here> meteor`

This still happens in `1.4.2-rc.3`, but and also in versions since `1.4.1` that I've tested (and possibly earlier)

So I don't know why this is throwing, and why this is throwing an `EventEmitter`

My entire application's code is the default code, replacing `server/main.js` by:

```js
import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { Mongo } from 'meteor/mongo';

Meteor.startup(() => {
  // code to run on server at startup
});

try {
  var coll = new Mongo.Collection('__dummy_coll_' + Random.id());  
} catch (e) {
  console.log('error!', e);
  throw e
}
```

**Comment by gsabran** [comment]
This might be a specific error since reading Meteor's code, I've been able to reproduce it in pure node with:

```js
var MongoDB = require('mongodb');

var url = 'mongodb://<user>:<password>@<what-compose.io-told-me-to-put-here>';
var mongoOptions = {
  db: { safe: true, native_parser: false },
  server: { autoReconnect: true, reconnectTries: Infinity },
  replSet: {}
};

var err;
var cb = function (e, r) { console.log('error:', !!e, 'res', !!r); err = e; };

MongoDB.connect(url, mongoOptions, cb);
```

that logs a similar error. Not really where to go from here!

**Comment by abernix** [comment]
Hmm, when I run the Meteor repo reproduction you provided against my MongoDB (I don't have Compose), it starts up successfully.

And when I run your pure Node script, it returns:

    error: false res true

The `res` (`r`) is indeed an `EventEmitter`, but that's correct as a [`MongoDB.Db`](https://mongodb.github.io/node-mongodb-native/2.2/api/Db.html) is an object that can emit events.  The `error` is not set.   Could this be a problem with connecting to your MongoDB?

Are you able to run `mongo mongodb://your-mongo-url` on the command line and connect successfully?  What happens if you try your Node reproduction against a (much older) version of `mongodb`, like `mongodb@1.4.40`?

**Comment by gsabran** [comment]
Yes it was a connection error indeed. I talked with compose.io who is hosting me and they changed some things that made it work. They had an issue with my whitelisted ips and where blocking recently added ones. Still unclear why the error thrown is an event emitter and not something like a connection refused.

**Comment by abernix** [comment]
First of all, thanks for filing the issue and doing the extensive research on this!  I'm watching your JIRA ticket; I'll be very curious to see what they come back with.

It looks to me like since you have multiple servers and both are closing, there are two errors (one for each server) being generated and the [`MongoClient` callback doesn't catch it](https://github.com/mongodb/node-mongodb-native/blob/6787b16938975742453841545cfe5b0b8cb0f929/lib/mongo_client.js#L304-L316), instead returning the [`mongos`](https://mongodb.github.io/node-mongodb-native/2.2/api/Mongos.html) event object.  This doesn't seem expected (or anticipated) by the Mongo driver and I believe this will come back as a bug with that.  Meteor can easily bump the Mongo driver version if it proves to be a bug that they fix.

**Comment by abernix** [comment]
So based on the response on [`mongodb`:NODE-838](https://jira.mongodb.org/browse/NODE-838) it appears that this was in-fact an unhandled error in `mongodb-core` and will be fixed by https://github.com/christkv/mongodb-core/commit/aaaa4e45f75e24a5b0cfd8b101e1851c0672a3b9.  That being said, based on their response they seem to think you might have been using an invalid URL as well (without `replSet` set).   I'm not sure if that's true or not, but if this is the case, then I suppose Compose.io was offering you the wrong URL?

When `mongodb` bumps its dependency version on `mongodb-core`, Meteor can bump the version of `mongodb` it uses too.

**Comment by gsabran** [comment]
Yes I'm not sure about the replica set thing and I'm no mongo expert. Compose.io suggests me to use URI like:
<img width="753" alt="screen shot 2016-10-25 at 12 36 15 pm" src="https://cloud.githubusercontent.com/assets/4228246/19701332/c4adef2a-9aaf-11e6-90bd-1c4bc0e03e86.png">

without any `?replicaSet=...` parameter so I'm not sure what I should do. Since it looks that they're willing to give extra info for Meteor users, I can ask them to update their explanation if we're confident that that should be done.

Thanks a lot for helping me going through all that!

**Comment by abernix** [comment]
I'm not 100% familiar with how Compose runs things, but based on the wording there ("mongos"; i.e. shard) it seems they do want you to use a shard and not a replica set.  Christian didn't really explain why he felt that way (that you intended on using a repl set), but perhaps you can ask in the Jira issue?

**Comment by gsabran** [comment]
Good call. I can't comment on the jira now that's closed, but I've left a message on the commit https://github.com/christkv/mongodb-core/commit/aaaa4e45f75e24a5b0cfd8b101e1851c0672a3b9
