### ISSUE TITLE
Problem with bcrypt when adding accounts-password

### ISSUE THREAD

**Issue by wew84** [meteor/meteor#7955]
I installed useraccounts:bootstrap and was about to install accounts-password, but I keep on getting an error. It seems to be related to bcrypt I am running it at version 7.7.  Attached are the terminal outputs from the error.
![screenshot from 2016-10-25 12-13-03](https://cloud.githubusercontent.com/assets/8680620/19680267/b6a2a242-9aad-11e6-8611-a602e07299db.png)
![screenshot from 2016-10-25 12-13-38](https://cloud.githubusercontent.com/assets/8680620/19680269/b6a3593a-9aad-11e6-9000-a64f3f8d3b71.png)
![screenshot from 2016-10-25 12-14-59](https://cloud.githubusercontent.com/assets/8680620/19680266/b6a27cea-9aad-11e6-96d1-2e4e203f1c85.png)
![screenshot from 2016-10-25 12-18-00](https://cloud.githubusercontent.com/assets/8680620/19680270/b6a550c8-9aad-11e6-958b-2270d19d3de2.png)
![screenshot from 2016-10-25 12-18-16](https://cloud.githubusercontent.com/assets/8680620/19680268/b6a2d744-9aad-11e6-987a-d8692aac14d1.png)

Thank you for your help,
wew84

**Comment by abernix** [comment]
As a request, for the purposes of opening an issue, it would be much more convenient to copy-paste the text output from your terminal instead of taking 5 successive screenshots.  Screenshots are hard to navigate, difficult to keep track of where you are and impossible for others to search through so this issue will provide little help for others in the future.

Anyhow, `npm-bcrypt@0.7.7` is [a relatively old version of `npm-bcrypt`](https://atmospherejs.com/meteor/npm-bcrypt).  What happens if you run?:

    meteor update --all-packages

Or if you run:

    meteor add npm-bcrypt@0.9.1_1

**Comment by abernix** [comment]
Closing as I'm fairly sure my suggestion above will solve your problem.  Please report back if it turns out that using the latest version of `accounts-password` and `npm-bcrypt` doesn't fix your problem.
