### ISSUE TITLE
[1.4.2] Unable to update on IPv6-only connection

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#7967]
Trying to update meteor, I'm receiving this error if I have IPv4 turned off:

```
Marks-Air:src markshust$ meteor update
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy


Changes to your project's package version selections from updating the release:

accounts-base          upgraded from 1.2.14-rc.3 to 1.2.14
accounts-password      upgraded from 1.3.1-rc.3 to 1.3.1
babel-compiler         upgraded from 6.13.0-rc.3 to 6.13.0
babel-runtime          upgraded from 0.1.12-rc.3 to 0.1.12
...
```

**Comment by abernix** [comment]
Do you have a NAT64 gateway setup?  Otherwise, `packages.meteor.com` (the package catalog server) has no `AAAA` record so there is no way this would work.  Meteor obviously isn't helping the situation by not having those DNS records setup, but I'm not sure that turning IPv4 completely off is a recommended idea right now as the global transition to IPv6-only is still not complete (and far from it, I believe).

I'm curious what the results of http://ipv6-test.com/ show for you.

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I won't say that it's not possible that some bug exists, but I'm going to close this because we haven't heard anything back from you about this problem.

Happy to reopen it if you come up with some additional details that are helpful in debugging the problem.  In this particular case, it's just affecting your development tool's ability to access the package server and really it's just that the package server doesn't support IPv6 and you don't support IPv4.  If you're just disabling IPv4 on your development machine and hoping for everything on the Internet work, you're bound to run into problems.  IPv4 is not gone and it's generally expected that your devices are configured to communicate with both protocols.  Just as a reference timeline, Amazon AWS just started making progress on supporting IPv6 in the last few months and [just yesterday announced support](https://aws.amazon.com/about-aws/whats-new/2016/12/announcing-internet-protocol-version-6-support-for-ec2-instances-in-amazon-virtual-private-cloud/) for IPv6 within VPCs.

This is not to say that Meteor doesn't support IPv6.  In fact, quite the contrary, and deployed Meteor apps should work just fine with IPv6 (and they don't need access to the package server).
