### ISSUE TITLE
[1.4.2] meteor build - problems with node_modules

### ISSUE THREAD

**Issue by PolGuixe** [meteor/meteor#7984]
I just updated to 1.4.2 and I am getting the error below when I try to run the app after bundling it with `meteor build` (either on the server or my local machine): 
```
Error: Can't find npm module 'react/lib/ReactComponentWithPureRenderMixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/bundle/bundle/programs/server/boot.js:200:17)
    at options.fallback (packages/modules-runtime.js:445:18)
    at require (packages/modules-runtime.js:112:16)
    at meteorInstall.node_modules.react-addons-pure-render-mixin.index.js (packages/modules.js:17838:18)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (/bundle/bundle/programs/server/packages/react-meteor-data.js:234:256)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
```
The file that is missing actually exists inside `bundle/programs/server/npm/node_modules/react/lib/`

I have no problems at all with `1.4.1.2`.

My `dependencies` are: 
```
"dependencies": {
    "bcrypt": "^0.8.7",
    "faker": "^3.1.0",
    "install": "^0.8.1",
    "lodash": "^4.13.1",
    "mantra-core": "^1.7.0",
    "material-ui": "^0.16.1",
    "moment": "^2.15.1",
    "money-math": "^2.4.3",
    "npm": "^3.10.6",
    "react": "^15.3.2",
    "react-dimensions": "^1.3.0",
    "react-dom": "^15.3.x",
    "react-helmet": "^3.1.0",
    "react-komposer": "^1.13.1",
    "react-komposer-plus": "^2.2.3",
    "react-mounter": "^1.0.0",
    "react-redux": "^4.4.5",
    "react-simple-di": "^1.0.1",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "^3.5.2",
    "redux-form": "^6.0.1",
    "redux-form-material-ui": "^4.0.1"
  },
  "devDependencies": {
    "babel-core": "6.x.x",
    "babel-plugin-react-require": "2.x.x",
    "babel-polyfill": "6.x.x",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "6.x.x",
    "babel-preset-stage-2": "6.x.x",
    "babel-register": "^6.9.0",
    "babel-root-slash-import": "1.x.x",
    "chai": "3.x.x",
    "enzyme": "^2.2.0",
    "eslint": "2.7.x",
    "eslint-plugin-react": "4.3.x",
    "jsdom": "^8.0.4",
    "mocha": "2.x.x",
    "react-addons-test-utils": "15.3.x",
    "sinon": "1.17.x",
    "@kadira/storybook": "^2.5.2"
  }
```

**Comment by PolGuixe** [comment]
This issue was previously raised in https://github.com/kadirahq/meteor-up/issues/344

**Comment by abernix** [comment]
Per my comment https://github.com/kadirahq/meteor-up/issues/172#issuecomment-256877604, it seems that `react-addons-pure-render-mixin` should be in your `dependencies` and isn't.

What happens if you run:

    meteor npm install react-addons-pure-render-mixin --save

And then try your `meteor build` again?

If this doesn't fix it, you'll need to provide a minimal-reproduction GitHub repo to proceed with debugging this per the guidelines for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor).

**Comment by PolGuixe** [comment]
**Thanks @abernix, installing `react-addons-pure-render-mixin` worked.** 

However right now I am totally confused:
- Why was 1.4.1.2 working without any problems?
- Why 1.4.2 works locally without any problems? 
- Why I have to install `react-addons-pure-render-mixin`, separately, as it is a piece of code already included in the react `installation`?

Any clarification will be really appreciated!

**Comment by abernix** [comment]
Hard to say for sure; I don't know if it's an explicit dependency of any of the `react` packages to be honest (I don't use this – maybe dig around and see if you can find out?) but the actual change is likely due to https://github.com/meteor/meteor/pull/7668/commits/03e798abc95f4edf4e0eceea7bfe036f73b27080, an intentional change to Meteor to not package up unneeded dependencies in your production build.  You likely had the dependency invisibly installed (i.e. not saved in `package.json` with `--save` when you `npm install`-d it).
