### ISSUE TITLE
[1.4.2] iOS build status-bar is broken

### ISSUE THREAD

**Issue by v3rron** [meteor/meteor#7988]
After upgrading from Meteor 1.4.1.3 to 1.4.2 and building for iOS, the status-bar text changes color from black to white during the launch-screen and overlaps over the app header.
Here's the mobile-config.js that I use:

```
App.setPreference('StatusBarOverlaysWebView', 'false');
App.setPreference('StatusBarStyle', 'default');
App.setPreference('StatusBarBackgroundColor', '#f9f9f9');
App.setPreference('AutoHideSplashScreen', 'true');
App.setPreference('ShowSplashScreenSpinner', 'false');
App.setPreference('android-minSdkVersion', '19');
App.setPreference('android-targetSdkVersion', '19');
```

I also tried changing it to `App.setPreference('StatusBarStyle', 'black-translucent')` without any luck.
Had to downgrade back to 1.4.1.3 and the issue was resolved.

**Comment by tonymckendry** [comment]
My team and I have also been experiencing this issue since upgrading to 1.4.2 - is there anything we can do to fix it other than adding some extra room in our header to accommodate the status bar height?

**Comment by johnthepink** [comment]
Same issue.

I found that in the `config.xml` generated for Cordova, there are a few preferences that are getting set more than once.

My `mobile-config.js` contains this:

```js
App.setPreference("StatusBarOverlaysWebView", false);
```

And the generated `config.xml` contains this:

```xml
<preference name="StatusBarOverlaysWebView" value="false" />
<preference name="StatusBarOverlaysWebView" value="true" />
```

Since the true preference comes later, it's taking priority over the one I actually want set.

For now, I'm just removing the extra preference manually.

**Comment by tonymckendry** [comment]
@johnthepink How are you accomplishing the removal of the extra preference manually?

**Comment by johnthepink** [comment]
@tonymckendry If you open the generated XCode project, there should be a `Staging/config.xml` file.

<img width="152" alt="screen shot 2016-11-09 at 1 09 24 pm" src="https://cloud.githubusercontent.com/assets/816517/20149255/78ba6442-a67e-11e6-96d2-68912b5a4777.png">

Then I'm just removing the extra 

```xml
<preference name="StatusBarOverlaysWebView" value="true" />
```

Or whatever your needs may be.

**Comment by tonymckendry** [comment]
awesome, I will give that a shot!

**Comment by abernix** [comment]
Forgive my unfamiliarity with the issue, but I'll try to shed some light as I can.  Meteor 1.4.2 updates Cordova to 6.2 – so presumably this is related to that update.

If you are using (in your `.meteor/packages` file) the [`mobile-experience` package](https://atmospherejs.com/meteor/mobile-experience) or the (deprecated) [`meteor-platform` package](https://atmospherejs.com/meteor/meteor-platform), Meteor will load (by default) a [`mobile-status-bar` package](https://atmospherejs.com/meteor/mobile-status-bar) which provides `cordova-plugin-statusbar`.  You also may have directly added this package to your project, if you chose with `meteor add mobile-status-bar`.

Prior to Meteor 1.4.2, it used version 2.1.2 but that has since been updated [to `2.2.0`](https://github.com/meteor/meteor/blob/3120b9324d25aaa0dff538acca4ec03a2f7518e2/packages/mobile-status-bar/package.js#L6-L9) (see [release notes](https://github.com/apache/cordova-plugin-statusbar/blob/master/RELEASENOTES.md)).  I don't see anything in those release notes that jumps out at me, but I'm not familiar with the package.  Regardless, the builder defaults [`StatusBarOverlaysWebView ` to `false`](https://github.com/meteor/meteor/blob/3120b9324d25aaa0dff538acca4ec03a2f7518e2/tools/cordova/builder.js#L120-L123) if the `mobile-status-bar` package is used in your project.  You can check in your `.meteor/versions` file (from your project root) to see if some dependency might be including it.

Anyhow, this is more of an FYI which might help others who are more familiar with Cordova than I am.  I'm not sure if Cordova is suddenly adding its own `true` setting, but it doesn't seem that Meteor is duplicating it or promoting a `true` setting for this that I can see.

**Comment by lpender** [comment]
I'm experiencing similar issues. 

Here are some other things I noticed:

- The issue doesn't occur only when running `meteor build`. The status bar appears correctly when running, i.e. `meteor run ios-device`.
- `App.appendToConfig` also seems to be effected, again, only when running `meteor build`. 

Thanks,
-Lee

**Comment by Lindstrom1989** [comment]
Also getting this a on a few apps, only on build :/

**Comment by arnoldgamboa** [comment]
I think this 1.4.2 error. I'm also experiencing this problem.

**Comment by chrisknu** [comment]
Only recently started getting this error with METEOR@1.4.3.1, appeared to be fine in 1.4.2.7 (prior working version).

Going to try hacking the config in xcode; Android devices appear fine

**Comment by observaInc** [comment]
My status bar woes seemed to disappear when upgrading the cordova-plugin-statusbar to 2.2.2.  There were a lot of fixes in that release regarding iOS status bar.  Currently, the meteor [mobile-status-bar package](https://github.com/meteor/meteor/tree/master/packages/mobile-status-bar) is still dishing out 2.2.1 which has a lot of the problems described here.

[2.2.2 release notes here](https://github.com/apache/cordova-plugin-statusbar/blob/master/RELEASENOTES.md)

**Comment by hwillson** [comment]
The `mobile-status-bar` package was updated to use `cordova-plugin-statusbar` version 2.2.3, so this issue should be fixed with newer versions of Meteor. Closing this off - please post back if anyone is still encountering this issue. Thanks!
