### ISSUE TITLE
How to connect Meteor on external MongoDB? Getting error in accounts base when connected.

### ISSUE THREAD

**Issue by Furqankhanzada** [meteor/meteor#7993]
Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/meteor) for that, or you may want to start a discussion on the [Meteor forum](https://forums.meteor.com/).

Before you open an issue, please check if a similar issue already exists or has been closed before.
### When reporting a bug, please be sure to include the following:
- [ ] A descriptive title
- [ ] What version of Meteor you're using, and the platform(s) you're running it on
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] An _isolated_ way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

See [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for more detail on what is expected of a bug report.
### When you open an issue for a feature request, please add as much detail as possible:
- [x] A descriptive title
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

See [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) for more detail on what is expected of a feature request.
### Independent core packages

We've split some packages out of meteor/meteor in order to make it easier for community members to contribute and the MDG team to maintain a slimmer core (this enables us to untie package versions from Meteor releases). Please ensure your issue is opened against the appropriate repository. Packages that have been split from core and their repositories are:
- Blaze: https://github.com/meteor/blaze

**Comment by laosb** [comment]
> Remember, an issue is not the place to ask questions. You can use Stack Overflow for that, or you may want to start a discussion on the Meteor forum.

How do you connect to an external MongoDB? What error did it thrown? Please replace the issue instructions with your detailed issue information.

**Comment by Furqankhanzada** [comment]
I am trying to connect localhost:27017 mongodb to meteor
but meteor runs mongodb  3001 port

**Comment by abernix** [comment]
Meteor's built in Mongo uses the application port plus one (Meteor on port 3000 = Mongo on port 3001; Meteor on 3009 = Mongo on port 3010). 

When you deploy your production application, you will start it using the `MONGO_URL` that is provided by your MongoDB provider.  You can read more about that in the [Custom deployment](https://guide.meteor.com/deployment.html#custom-deployment) section of the Meteor guide.

If you're trying to use your own Mongo server on your local development machine, you should also provide the `MONGO_URL` environment variable.  This can be done by starting Meteor as:

    MONGO_URL=mongodb://localhost:27017 meteor run

This environment variable is documented [here in the Meteor Docs](https://docs.meteor.com/api/collections.html#mongo_url).

Closing this since it is not a bug with Meteor but rather a question on how to use it.  In the future, please post your questions to [Stack Overflow](https://stackoverflow.com) or ask on the [Meteor Forums](http://forums.meteor.com).

**Comment by Furqankhanzada** [comment]
I tried this many time but it won't work "MONGO_URL=mongodb://localhost:27017 meteor run"

**Comment by abernix** [comment]
You should include the `databasename` as well:

    MONGO_URL=mongodb://localhost:27017/databasename meteor run

What does "Won't work" mean?  What is the exact error message that you're receiving?

**Comment by Furqankhanzada** [comment]
I am using windows and I "SET MONGO_URL=mongodb://localhost:27017/databasename" and it works

**Comment by abernix** [comment]
Yes, you would need to set the environment variable properly for your operating system.

In the future, if you open a GitHub issue, please provide more information.  If you look at the issue you opened, you actually only provided a title.  Knowing the operating system you are on, etc. helps a lot in debugging.  (For example, if you ever switch to PowerShell you would need to do `$Env:MONGO_URL="mongodb://localhost:27017/databasename"` instead.)

Closing as resolved.

**Comment by thearabbit** [comment]
How to set env on Window?
