### ISSUE TITLE
meteor npm install --save bcrypt not working

### ISSUE THREAD

**Issue by saransh1525** [meteor/meteor#8001]
On window 7, when i run meteor then it shows 'meteor npm install --save bcrypt'. But on Ubuntu, it doesn't show.

And when i have install 'bcrypt' getting some error (Please check attachment).
![error](https://cloud.githubusercontent.com/assets/16717564/19928131/26e60352-a123-11e6-9485-f1be3b7c048f.png)

**Comment by abernix** [comment]
If you want to use native `bcrypt` (which is what is provided by the `bcrypt` NPM) instead of the JavaScript implementation, you'll need to make sure your Windows environment is capable of compiling the node bindings with a compiler toolchain.

For instructions on how to set your environment up with the proper compiler toolchain, you'll need to carefully follow [these `node-gyp` requirements](https://github.com/nodejs/node-gyp#installation).

I truly wish it was more simple than that, but Windows is a hellion when it comes to this.  As an alternative, if you can avoid the binary dependency in your development environment only install it in production (which will be much more likely to be capable of compiling), that would be another option.  If you use the Meteor `npm-bcrypt` package (`meteor add npm-bcrypt`), it will handle this for you, but you'll have to deal with the JavaScript warning and you'll need to remember to do the compilation for this project on a compile-capable-machine.

If you really want to dig into it, I believe you'll get more debug output if you run `set V=1 && meteor npm --verbose install bcrypt --save`.

Closing as this is really a Microsoft issue.  And as a search on previous issues will show you, this is a regular problem.
