### ISSUE TITLE
Modifying ./meteor/packages in trivial ways shouldn't cause a rebuild

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#8006]
If all I did to the `.meteor/packages` file was add a space, a new-line, a comment, or edit a comment, it shouldn't cause a whole app rebuild. Can this be optimized?

I'm on a Windows 7 Pro build.

**Comment by abernix** [comment]
Can you explain a bit more why purely cosmetic formatting changes are happening to your `.meteor/packages` file so often that this would be a benefit?  I'm all for optimizations but I don't feel that the added logic (and thus code to maintain) to avoid this seemingly infrequent change would really be worth it.  I suppose a relatively simple hashing mechanism might not be too hard, but again – how often are these changes being made that this would be beneficial and developers would notice?

And of course, as additional optimizations are made in Meteor (as were done in 1.4.2), they will automatically improve the re-build time.

**Comment by rclai** [comment]
I've been using the Windows version of 1.4.2 and while I've noticed the rebuild improvements, I noticed that rebuilds take a while when it comes to anything related with installing/removing packages. For example, I was commenting out packages, and commenting them back in to find certain problems, then eventually I needed to reorganize them so that the commented packages are all above and the non-commented ones below. Then I would put a comment on why I commented the packages.

**Comment by abernix** [comment]
> Then I would put a comment on why I commented the packages.

But this represents a very, very small percentage of the time spent on modifying the `.meteor/packages` file.   Most of what you described involved actively adding and removing packages – something which requires rebuilding several aspects of the bundle.

> I can't imagine it would be too hard to maintain code that checks whether anything really changed before having to make potentially expensive network requests.

I would argue that this is a pretty inaccurate statement.  The Meteor tool spends a lot of time, and has a lot of code which checks what things have changed and tries not to do too much.  Meteor might need to do a network request in order to figure out what can be updated.  Have you quantified that the network requests are the expensive part of it?  Part of the magic of Meteor is that it checks for new packages – but I don't even know if that's the slow part of it.

It sounds to me that your bigger problem is the speed for how long it takes to add and remove packages – a likely non-trivial task.  I think a feature request for that would be reasonable, but it would be ideal if it came with some specific ideas or suggestions on how to address the particular aspects of what's than us starting another "Make Meteor faster" issue.

But speaking to the original issue, I personally don't foresee a lot of improved speed benefit for the community (aside from when you're rearranging commented lines or adding spaces) by simply checking if the file has the same content in it – work still needs to be done.  It's possible that it could be done less frequently or something along those lines.

**Comment by tcastelli** [comment]
I'm with @abernix on this one, I think the benefit of doing something like this is not worth the effort, since you can always edit the packages file while the server is stoped if you are only formatting the file. Just my 2 cents

**Comment by hwillson** [comment]
Based on the feedback supplied for this feature request, and a lack of +1's/interest, I'll close it for now. Thanks for suggesting this originally!
