### ISSUE TITLE
meteor build with yarn linked modules doesn't copy symlinks properly

### ISSUE THREAD

**Issue by damonmaria** [meteor/meteor#8023]
Meteor 1.4.2-beta.1
MacOS 10.12.1
yarn 0.16.1

We've switched over to yarn after the Meteor 1.4.2 release notes mentioned Meteor is now working with yarn. Everything has worked so far but I've picked up an issue. 

`yarn link` creates relative symlinks. For example:
````console
$ ll node_modules/@mindhive/
total 16
drwxr-xr-x    7 damon  staff    238  6 Nov 15:41 ./
drwxr-xr-x  711 damon  staff  24174  6 Nov 14:58 ../
lrwxr-xr-x    1 damon  staff     56  2 Nov 18:49 components@ -> ../../../../../../.yarn-config/link/@mindhive/components
drwxr-xr-x   11 damon  staff    374  6 Nov 15:08 di/
lrwxr-xr-x    1 damon  staff     52  6 Nov 15:41 meteor@ -> ../../../../../../.yarn-config/link/@mindhive/meteor
drwxr-xr-x    9 damon  staff    306  6 Nov 15:08 some/
````

Where as `npm link` uses absolute paths. I presume there's a good reason yarn has chosen this difference. 

When `meteor build` runs however it copies the symlinks as they are. So unless by chance the build destination happens to be the same number of directories deep on the same filesystem then the relative symlinks won't work. I've tried with the `--directory` option, and without. 

But this raises other questions. Shouldn't the distribution `meteor build` creates be 'self contained' and portable across filesystems? And therefore shouldn't `meteor build` actually follow the symlinks and copy what they point to rather than copying the symlink itself?

**Comment by benjamn** [comment]
I suspect this is the same problem as https://github.com/meteor/meteor/issues/8005, which should be fixed in the most recent 1.4.2.1 release candidate, thanks to [this commit](https://github.com/meteor/meteor/pull/7975/commits/af51b8160ce443e0bf46b9a801cb2068eaf85a21). You're absolutely right that `meteor build` should not be creating symbolic links that point outside of the bundle, which is why that commit now forces "external" symlinks to be copied as files rather than recreated as links.

**Comment by benjamn** [comment]
In other words, try this again after `meteor update --release 1.4.2.1-rc.1` :)

**Comment by damonmaria** [comment]
rc.1 solves this issue. Thanks again @benjamn. Nice work.
