### ISSUE TITLE
Inheritance bug

### ISSUE THREAD

**Issue by derencel20** [meteor/meteor#8040]
I kept getting this error.
![image](https://cloud.githubusercontent.com/assets/17394978/20173668/2f74b36c-a775-11e6-92a5-bae1f202f70d.png)

My Model extends Player and Chaser extends Player it gives this error.

dependencies:
![image](https://cloud.githubusercontent.com/assets/17394978/20173702/55cb794c-a775-11e6-81cf-c093f25c672e.png)

**Comment by derencel20** [comment]
Hmmm. @benjamn, is multilevel inheritance not allowed in meteor?

**Comment by benjamn** [comment]
It definitely *is* allowed. I would need more information about the code in question to help you resolve this problem.

**Comment by derencel20** [comment]
Would you like to see my code? I'll attach it if you want.

**Comment by benjamn** [comment]
Some specific questions for you:

* What version of Meteor are you using?
* Have you run `meteor npm install --save babel-runtime` in your app?
* What happens if you log the value of the `extends` super-class expression just before the class is declared (I'm guessing it will be `undefined`, for reasons that should be addressed by other means)?

If you can share the code that defines the class in question, or (even better) a small reproduction, that would be great!

**Comment by derencel20** [comment]
i'll have it uploaded it gitlab. what's your name there?

**Comment by benjamn** [comment]
Just registered! Fortunately https://gitlab.com/benjamn was still available 😌

**Comment by derencel20** [comment]
Invited. Hehe.. Right after you registered.

**Comment by derencel20** [comment]
It's getting an error right? Even tho the code seems correct.

**Comment by benjamn** [comment]
Unfortunately, I don't get the error on Meteor 1.4.1.1, 1.4.1.3, or 1.4.2.1. Have you tried running `meteor npm install` again recently, or updating to the latest version (1.4.2.1, which has some notable changes to the way `babel-runtime` works)?

**Comment by derencel20** [comment]
wait.. maybe that's the outdated one.. wait.

**Comment by derencel20** [comment]
try running `npm test`

**Comment by derencel20** [comment]
I tried 1.4.2 last time but got the same error so I downgraded it.

**Comment by derencel20** [comment]
You don't get errors there because I haven't used any class from the models folder yet. In the unit-tests folder, I used the Snitch model. The boom! the error is there.

**Comment by derencel20** [comment]
Did you get the error now?

**Comment by benjamn** [comment]
You've got a circular import problem because `imports/both/models/Player.js` imports `./Team` and `Team.js` imports `./Chaser` and `Chaser.js` imports `./Player`.

You can break this cycle by pushing the `import Team from './Team'` declaration into the `Player#team` method:

```js
import Model from './Model'

class Player extends Model {
  get team() {
    import Team from './Team'
    return Team.findOne(this.teamId)
  }
}
```

The original error was warning you that you were attempting to extend an undefined value rather than a class. You can see that by putting a `console.log({Player})` before the `class Chaser` declaration. In other words, the error was actually helpful!

**Comment by derencel20** [comment]
thanks. I am really confused with this problem since I didn't encounter it in the past.. ^_^

**Comment by benjamn** [comment]
Yeah, it's a sneaky problem, rare enough that most folks don't encounter it very often. But now you know!

**Comment by derencel20** [comment]
thank you very much. you're an eye opener. ^_^

**Comment by derencel20** [comment]
I've just read about circular dependencies. Are they the same?
