### ISSUE TITLE
Most recent Meteor Version requires "meteor npm install --save babel-runtime", crashes on build

### ISSUE THREAD

**Issue by NicholasEli** [meteor/meteor#8059]
When doing 'meteor create my app' and then running meteor after creation is complete. The app fails to build unless I install "meteor npm install --save babel-runtime" manually.

**Comment by abernix** [comment]
Yes, this is in the [changelog](https://github.com/meteor/meteor/blob/devel/History.md#v1421) for the 1.4.2.1 release and is expected behavior.

You can also just run `meteor npm install`, but it has been recommended to run `meteor npm install` after `meteor create` for quite some time now as this also installs the other package in the default `package.json`: `meteor-node-stubs`, which provides "stubbed" node methods to the client.

I realize this isn't very clear in the documentation (or when you run `meteor create`), but #6848 is already open to cover the automatic aspect of this and this can hopefully be simplified soon.
