### ISSUE TITLE
TypeError: httpProxy.createProxyServer is not a function

### ISSUE THREAD

**Issue by seandlg** [meteor/meteor#8069]

**Comment by seandlg** [comment]
Hey Folks. 
Unfortunately I'm having issues with my Meteor (1.4.2_1) installation on Windows 10 Pro. The issue produces the same error as on https://github.com/meteor/meteor/issues/7717 ,however quick fixing the path as described in that thread does not help.

When trying to create a new app on meteor (e.g. the simple-todos), while trying to build the app with 'meteor' I get this error message:

C:\Users\Sean\learn>meteor
C:\Users\Sean\AppData\Local\.meteor\packages\meteor-tool\1.4.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

TypeError: httpProxy.createProxyServer is not a function
    at Proxy.start (C:\tools\runners\run-proxy.js:40:28)
    at Runner.start (C:\tools\runners\run-all.js:119:16)
    at Object.exports.run (C:\tools\runners\run-all.js:322:10)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:360:17)
    at C:\tools\cli\main.js:1483:23

Clearly the path C:\tools is wrong, but I don't know where this is coming from. I installed a fresh Windows copy a few days back, trying to run Meteor on the Surface Pro 4. Any suggestions on what to do? Setting the installation path manually in the meteor.bat didn't help (even with a freshly created Meteor app after that 'fix'). Did anybody else encounter that issue with this Meteor version and Windows 10 and knows what to do?

**Comment by abernix** [comment]
The `C:\tools` path is fine (though a bit confusing, I agree); that's just the way that paths show up in the stack trace.  On Unix they would show as `/tools/runners/run-proxy.js` but the "root" is relative to the Meteor installation (which is actually in `C:\Users\Sean\AppData\Local\.meteor\packages\meteor-tool\1.4.2_1\mt-os.windows.x86_32\` in your case), not the root of the hard-drive.  Do not fear. :)

Anyhow, that thread (and the [several other old issues about this](https://github.com/meteor/meteor/issues?utf8=%E2%9C%93&q=is%3Aissue%20createProxyServer)) suggests that the problem goes away with a re-installation.  I'm not sure what the specific cause for the problem is but can you try doing a reinstallation and see if the issue goes away?

For Windows, I would recommend:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7/Win8.1:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.2.3 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working. 

Please report back if that fixes your problem.  I hope it does.  Unfortunately if it doesn't, there have been no ways reported to reproduce this so someone can fix it.  This doesn't happen very often and while it would be great to resolve the issue, without a reproduction there isn't a lot of use leaving this issue open.

If you have the time to devote to it – your help would be appreciated in figuring it out!  I'll leave this open for now.

**Comment by seandlg** [comment]
Hello abernix.
First of all thanks for you reply. I have followed the steps exactly as described and hurray: It does work. Maybe as a side-note: I've done this before, without Restarting the machine - the error persisted. Remove Meteor - Restart - Install Meteor - Restart - did it for me. Maybe this helps somebody. Thanks!

**Comment by abernix** [comment]
Thanks for reporting back, and glad it fixed it for you!  Hopefully it will happen to me eventually. :)

**Comment by mocolicious** [comment]
This did not fix the issue for me.

**Comment by kjkiss** [comment]
This did not fix the issue for me.

WHY??

**Comment by abernix** [comment]
@mocolicious / @kjkiss A few questions:

* Are you getting _exactly_ the same error?  Can you provide it, regardless?
* What versions of Meteor?
* Does it happen on a new project?  Existing projects?
* Is it possible that some sort of tool (virus scanner, etc.) is _somehow_ blocking `http-proxy`?

**Comment by kjkiss** [comment]
I have reinstalled win10 system to solve the problem
Thanks
发送自我的 Windows 10 手机

发件人: Jesse Rosenberger
发送时间: 2017年6月13日 18:13
收件人: meteor/meteor
抄送: kjkiss; Mention
主题: Re: [meteor/meteor] TypeError: httpProxy.createProxyServer is not afunction (#8069)

@mocolicious / @kjkiss A few questions:
• Are you getting exactly the same error? Can you provide it, regardless?
• What versions of Meteor?
• Does it happen on a new project? Existing projects?
• Is it possible that some sort of tool (virus scanner, etc.) is somehow blocking http-proxy?

**Comment by mocolicious** [comment]
- I'm getting the exact same error
- using latest version of meteor
- happens for every project
- I don't have any special tools, my system is a brand new surface book from Microsoft 

My current work around has been to install the Linux subsystem features for Windows 10 pro and use bash to install it on the Linux subsystem.  However, there are a lot of issues with doing it this way but it will run

**Comment by abernix** [comment]
@mocolicious Thanks for the response!  Just to check some basics, can you go into the following directory path:

> **Note:** Replace `YOUR_USER` and `YOUR_VERSION` appropriately.  `YOUR_VERSION` can be grabbed from the error message you're receiving.

    C:\Users\YOUR_USER\AppData\Local\.meteor\packages\meteor-tool\YOUR_VERSION\mt-os.windows.x86_32\dev_bundle\lib\node_modules

Within that directory, make sure that:

* `http-proxy` is a directory.
* `http-proxy/index.js` is a file with a `module.exports = require('./lib/http-proxy');` line.
* `http-proxy/http-proxy.js` exists and defines `module.exports.createProxyServer` (Mine is 59 lines, 2377 bytes).
* `http-proxy/lib/http-proxy/index.js` exists and looks proper (Mine is 184 lines, 4695 bytes)

I'll reopen this issue, for the time being.

**Comment by sharksoft** [comment]
The definitive solution is:

remove folder http-proxy under /users/username/node_modules

**Comment by hwillson** [comment]
Since we haven't heard back regarding the extra information requested in https://github.com/meteor/meteor/issues/8069#issuecomment-308328603, and others are reporting this issue as fixed, I'll close this for now. Happy to re-open if anyone is still encountering this issue, and can supply the extra requested debugging details. Thanks!

**Comment by ishaqashraf** [comment]
@sharksoft thanks you save my day .. 
who faced this problem simply go to the node module and delete folder http-proxy and then run meteor
