### ISSUE TITLE
[1.4.2+] Upgrading project to 1.4.2+ may have impacted rebuild.

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#8075]
## IGNORE THIS, see comments below

If I create a sub folder in my client folder and put files in it.  Changing those files does not kick off a rebuild.  I have noticed this since 1.4.2 and just tested this on 1.4.2.3.

I know the 1.4.2 was intended to speed up builds, this is a significant slowdown.

### Environment
meteor v1.4.2.3
Windows 10

### Repro
1. `meteor create test`  and get it running `meteor npm install; meteor`, etc..
2. In the project add a sub folder under client, e.g. `sub`
3. move all project files into this sub folder. (e.g. `main.css, main.js, main.html`)
4. build the project and verify it works.
5. change one file (for example, I added a `console.log` into the `main.js` file)
**Result:** project does **not** rebuild.
**Expected:** project to rebuild.

**Comment by hwillson** [comment]
Hi @brucejo75 - I can't seem to re-create this issue; changes made in sub-folders are being picked up for me. I've created a quick repro (https://github.com/hwillson/meteor-issue-8075) based on your steps - can you try it out and let me know what you see? Thanks!

**Comment by brucejo75** [comment]
Hi @hwillson, thanks for posting the repro.  The results are a little less straightforward.

I downloaded your [repo ](https://github.com/hwillson/meteor-issue-8075) and indeed changing the .js file resulted in a rebuild.  I also tried changing the css and html files and they would rebuild.  I also noticed that if I do a new save without changing anything that no rebuild occurs.  (e.g. touch the file)  I assume this is a new feature?

In my larger project I have been noticing that some files will kick off a rebuild and others will not.  The depth of the folder tree has no effect (I will remove that description).

In my tests I think I may have been simply touching files and expecting a rebuild in some cases so my test case is not exhibiting the problem when I actually change the file as near as I can tell.

But the problem remains with my project.  I had noticed that if I copied a failing file to another file it would start to work for rebuild.  So I tried another route: I archived my project and did a git clone of the project in a new directory.  And now, changing files seems to work for all files I tried (small sample).  Would that make any sense?  This may only be an issue for in place upgrades of older projects?  Or could just be my config?

### Maybe this is a workaround?
If you are having problems with rebuld, then recreate your project from your git repo.  Or copy offending files to new copies.

**Comment by ShinyLeee** [comment]
@brucejo75 
After I delete all CACHE files in .meteor/local/bundler-cache/linker/ , some files will rebuild fine.
Maybe the issue caused by these former Meteor version's CACHE files?

**Comment by brucejo75** [comment]
I had tried deleting all of .meteor/local but it did not help.

After using this for the past couple of days, I have found that the workaround to recreate the project seems to have worked.

**Comment by abernix** [comment]
If you've deleted all of you `.meteor/local` directory, you essentially have a brand new project as this is where any residue would be left.   (Btw, it is probably better to use `meteor reset`, which does basically the same thing, but in a controlled way).

I guess you could also have a bugged package version, in which case deleting your `.meteor/versions` could be helpful, but that seems unlikely to be the case and you'd probably just reinstall the same version again on a recreated project too.

Regardless, after deleting `.meteor/local` your next execution of `meteor` would then rebuild the project from scratch using the remaining contents in the `.meteor` directory (e.g. `.meteor/packages` and `.meteor/release` and others, if they're available, though those are the most important two).

If that doesn't work, that leaves the question of whether you had something in your `node_modules` directory (i.e. an NPM package) affecting it.  Otherwise, I can't imagine how recreating the project would turn out any different.  You can always delete your `node_modules` directory and run `meteor npm install` to re-build it.

**Comment by brucejo75** [comment]
OK, I rebuilt the node_modules in an existing project.  It now works as expected.
