### ISSUE TITLE
npm peer requirements not installed

### ISSUE THREAD

**Issue by iHaiduk** [meteor/meteor#8083]
>W20161121-22:02:30.949(2)? (STDERR) WARNING: npm peer requirements not installed:
W20161121-22:02:30.992(2)? (STDERR)  - react@15.4.0 installed, react@0.14.x needed
W20161121-22:02:30.993(2)? (STDERR)  - react-dom@15.4.0 installed, react-dom@0.14.x needed
W20161121-22:02:30.993(2)? (STDERR)  - react-addons-transition-group@15.4.0 installed, react-addons-transition-group@0.14.x needed
W20161121-22:02:30.993(2)? (STDERR)  - react-addons-css-transition-group@15.4.0 installed, react-addons-css-transition-group@0.14.x needed
W20161121-22:02:30.993(2)? (STDERR)  - react-addons-linked-state-mixin@15.4.0 installed, react-addons-linked-state-mixin@0.14.x needed
W20161121-22:02:30.994(2)? (STDERR)  - react-addons-create-fragment@15.4.0 installed, react-addons-create-fragment@0.14.x needed
W20161121-22:02:30.994(2)? (STDERR)  - react-addons-update@15.4.0 installed, react-addons-update@0.14.x needed
W20161121-22:02:30.994(2)? (STDERR)  - react-addons-pure-render-mixin@15.4.0 installed, react-addons-pure-render-mixin@0.14.x needed
W20161121-22:02:30.994(2)? (STDERR)  - react-addons-test-utils@15.4.0 installed, react-addons-test-utils@0.14.x needed
W20161121-22:02:30.994(2)? (STDERR)  - react-addons-perf@15.4.0 installed, react-addons-perf@0.14.x needed
W20161121-22:02:30.995(2)? (STDERR) 
W20161121-22:02:30.995(2)? (STDERR) Read more about installing npm peer dependencies:
W20161121-22:02:30.995(2)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20161121-22:02:30.995(2)? (STDERR)

Hi! After update react to 15.4.0 and meteor to 1.4.2.3 this problem appeared again.
Version: METEOR@1.4.2.3
### First step
$ meteor add kadira:graphql 
$ meteor add react
$ meteor add react-meteor-data
### Second step
$ meteor npm install
### Third step
$ meteor

package:
> "dependencies": {
    "babel-runtime": "6.18.0",
    "meteor-node-stubs": "~0.2.0",
    "react": "^15.4.0",
    "react-addons-pure-render-mixin": "^15.4.0",
    "react-addons-create-fragment": "^15.4.0",
    "react-addons-css-transition-group": "^15.4.0",
    "react-addons-linked-state-mixin": "^15.4.0",
    "react-addons-perf": "^15.4.0",
    "react-addons-test-utils": "^15.4.0",
    "react-addons-transition-group": "^15.4.0",
    "react-addons-update": "^15.4.0",
    "react-dom": "^15.4.0"
  }

**Comment by abernix** [comment]
Your problem is that the third-party [`kadirahq:graphql`](https://github.com/kadirahq/meteor-graphql/) package you are using (not updated in almost a year) [depends directly](https://github.com/kadirahq/meteor-graphql/blob/master/package.js#L40) on an [old version of `react`](https://atmospherejs.com/meteor/react)

Just so you understand how to discover problems like this yourself, if you ran `meteor list` (to show installed packages), it would have showed an asterisk next to the `react` package, indicating that the package is out of date.  If you just follow the instructions you quickly find the answer:

```sh
$ meteor list
...
react                  0.14.6* Everything you need to use React with Meteor.
                             ^ here
...
* New versions of these packages are available! Run 'meteor update' to try to update those packages to their latest versions. If your packages cannot be updated further, try
  typing `meteor add <package>@<newVersion>` to see more information.
$ meteor update
The following top-level dependencies were not updated to the very latest version available:
 * react 0.14.6 (15.0.1 is available)
$ meteor add react@15.0.1
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint react@0.14.3 is not satisfied by react 15.0.1.
Constraints on package "react":
* react@15.0.1 <- top level
* react@0.14.3 <- kadira:graphql 1.2.4
```

The `kadirahq:graphql` package probably doesn't have to forcibly rely on `react`, but it's relatively old so it does.  If it was updated to use the 15.x version, it might work okay.  Regardless, you'd need to open that issue with them.  You may also want to check out [this Apollo integration](http://dev.apollodata.com/core/meteor.html) for another GraphQL + Meteor option and [the Meteor Todos React example](https://github.com/meteor/todos/tree/react).
