### ISSUE TITLE
error deploying meteor 1.4.2 to Galaxy via CodeShip

### ISSUE THREAD

**Issue by tomzamir** [meteor/meteor#8090]
Hi

I am getting the flowing error when trying to deploy:

/home/rof/.meteor/packages/meteor-tool/.1.4.2.1qpw6dn++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
throw error;
^

SyntaxError: Unexpected end of input
at Object.parse (native)
at readSessionData (/tools/meteor-services/auth.js:145:15)
at Object.exports.isLoggedIn (/tools/meteor-services/auth.js:886:19)
at Command.func (/tools/cli/commands.js:1281:23)
at /tools/cli/main.js:1454:23

not sure if it has anything to do with the CDN issue, I did try the 

`
export METEOR_WAREHOUSE_URLBASE=https://d3fm2vapipm3k9.cloudfront.net
meteor update
`
but it isn't working still.

**Comment by tomzamir** [comment]
same with 1.4.2.3
node v0.10.48 (npm v2.15.1)

**Comment by benjamn** [comment]
It appears your `~/.meteorsession` file has become malformed. Please don't post the contents here, since it contains sensitive information, but I would recommend examining it for errors, renaming and/or deleting it. Meteor will recreate the session file for you if you run `meteor login` or `meteor deploy` or any other command that requires authentication.

For future reference, the stack trace and error here are pretty clear about the nature of the error. Check out [this line](https://github.com/meteor/meteor/blob/b1df3ed0ed2b686e96d89ee66252f447b3c3b87e/tools/meteor-services/auth.js#L145) and then [this function](https://github.com/meteor/meteor/blob/b1df3ed0ed2b686e96d89ee66252f447b3c3b87e/tools/meteor-services/config.js#L130). Can you see how you might have identified this solution yourself?

**Comment by tomzamir** [comment]
Thanks for pointing me in the right direction Benjamn

indeed the issue was with the meteor session file, so I followed these two guides, one to break down the auth/deploy process

https://www.okgrow.com/posts/meteor-galaxy-ci-deployment

and one that explains how (see last comment) to store the session content in base64 encoding.

https://gist.github.com/nagelflorian/2e7509750d1254a1549a

happy happy joy joy!

**Comment by stubailo** [comment]
> happy happy joy joy!

Sounds like it has been resolved!
