### ISSUE TITLE
Error: Cannot find module '/packages/meteor-accounts-saml/saml_server.js'

### ISSUE THREAD

**Issue by Gobliins** [meteor/meteor#8099]
Hi i put this https://github.com/steffow/meteor-accounts-saml package inside my meteor projetcs package folder. And did some mmoification to it.
I changed the name to ..-modded and updated the packages file inside the .meteor directory.

This worked quiete well a couple of weeks ago. Today is tried starting this project and i got this error message from title, but the file is present in the directory.

Anyone can help?

Error message:

W20161123-12:39:01.604(1)? (STDERR) .meteor/packages/meteor-tool/.1.3.5_1.nec0ub++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161123-12:39:01.604(1)? (STDERR)                                             throw(ex);
W20161123-12:39:01.605(1)? (STDERR)                                                   ^
W20161123-12:39:01.741(1)? (STDERR) Error: Cannot find module '/packages/meteor-accounts-saml/saml_server.js'
W20161123-12:39:01.741(1)? (STDERR)     at Function.require.resolve (packages/modules-runtime/.npm/package/node_modules/install/install.js:101:1)

**Comment by abernix** [comment]
I just tried to replicate this on a new project as you specified and it worked perfectly fine:

```sh
$ meteor create --release 1.3.5.1 issue-8099
$ cd issue-8099
$ git clone https://github.com/steffow/meteor-accounts-saml packages/meteor-accounts-saml
$ sed -i.bak -e 's/\(steffo:meteor-accounts-saml\)/\1-modded/' packages/meteor-accounts-saml/package.js
$ echo "steffo:meteor-accounts-saml-modded" >> .meteor/packages
$ meteor
...
=> App running at: http://localhost:3500/
```

Please consider doing some additional debugging or asking for help on the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor) before opening an issue.  "It worked a couple weeks ago" when you're still using Meteor 1.3.5.1 (which has been out for months) indicates that something else has changed in your environment.  Happy to help, but you haven't given much to work with here.

**Comment by Gobliins** [comment]
Fun fact is, each time i start the project, meteor does an upgrade:
=> Started proxy.
=> Started MongoDB.
   Downloading meteor-tool@1.4.2_3...        [=======                   ] 27% 23.7s
...

which i assumed was the cause of the problem..

**Comment by abernix** [comment]
That would appear as if your upgrade isn't finishing then, but that still doesn't seem like it would be the cause.  I don't think that's even related.  I'm not sure it will solve the original problem try just doing a re-install (`curl https://install.meteor.com | sh`) and see if that helps the updating.   At the very least, ensure that the install finishes (or let it finish) – it certainly shouldn't be running every time.  You will know if it's finished when if you run `meteor --version` outside of a project directory it shows a newer version (i.e. `Meteor 1.4.2.3`).  Again, a reinstall may be a more reliable option since some of the actual updating code has been changed since 1.3.5.1.

Once you get over that, then maybe there are other issues that can be looked at or perhaps it will fix itself. :smile:

**Comment by Gobliins** [comment]
Like said, it was not a meteor  / node problem, it was some false import statement. Sorry i first recognized it after you couldn't reproduce the issue. 
About the upgrade, i blame out environment for this. You can delete this issue if you want.
