### ISSUE TITLE
METEOR_SETTINGS not passing json as expected?

### ISSUE THREAD

**Issue by gsabran** [meteor/meteor#8100]
Originally posted here: https://forums.meteor.com/t/meteor-settings-not-passing-json-as-expected/31630

It looks like the env var I'm trying to pass to define Meteor settings is not working. I'm not really sure, but why is the variable deleted here: https://github.com/meteor/meteor/blob/693fce59be5240801e762a7288283a96ab154af4/tools/runners/run-app.js#L187 ?

**Comment by abernix** [comment]
This is working [as documented](http://docs.meteor.com/api/core.html#Meteor-settings) (the same link you referred to in the forums):

> `Meteor.settings` contains deployment-specific configuration options. You can initialize settings by passing the `--settings` option (which takes the name of a file containing JSON data) to `meteor run` or `meteor deploy`. When running your server directly (e.g. from a bundle), you instead specify settings by putting the JSON directly into the `METEOR_SETTINGS` environment variable. 

I've responded further on the forum post.  In the future, unless you're sure it's a bug, instead of cross-posting almost immediately, please post questions in forums and give them time for response.  Aside from doubling up on work (and losing context by splitting across locations), if we don't try to stick to this it opens the doors for too many questions being posted here losing track of real bugs.  Thanks!

**Comment by gsabran** [comment]
Thanks, and sorry for the double posting. The current design doesn't work well for me, but if it makes sense for most than I'll find something else!
