### ISSUE TITLE
No way to implement "Login on public computer"

### ISSUE THREAD

**Issue by nazarposhta** [meteor/meteor#8103]
We need to make possible to choose the type of login. For user's own computer and for public computers (with checkbox "[public computer]"). Is that possible to implement with some nice Meteor.method?

**Comment by abernix** [comment]
Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions.

We highly recommend you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
