### ISSUE TITLE
Three backticks on top of iOS app with Meteor 1.4.2.3

### ISSUE THREAD

**Issue by albertbuchard** [meteor/meteor#8131]
Hi,

I am having an issue with the cordova version of my app. Three backticks appear on the top of the main page the rest works fine. Those back tick are not present in the code, nor are they present if I build for my local pf deploy on galaxy.

Any suggestions as to how to remove the backticks ? Is it a comon issue?

Thanks !

**Comment by abernix** [comment]
It's not something I've heard of and search through issues doesn't show anything.  Three backticks vaguely sounds like [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet), but could be a lot of things.

You really haven't provided much to work with or mentioned any steps that you've taken to debug the situation.  I'd recommend removing third party packages or creating a new application to see if you can replicate the problem there.  Delete large portions of your project and see it goes away.  If you can replicate it in a smaller project that you can share, then that'd be something to work with, but as of right now what you've provided is too vague to provide help, not enough to isolate the problem, or even to determine if the problem is in Meteor itself.

Closing for the reasons I've listed, but happy to reopen with a reproduction.  You'll likely find the culprit while narrowing the application down to a reproduction.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Alternatively, please try asking for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.
