### ISSUE TITLE
EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by JohanTh** [meteor/meteor#8139]
Running 2 servers on the same machine that use the same package in windows 10:

```
C:\Users\gatsu\AppData\Local\.meteor\packages\meteor-tool\1.4.1_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: EPERM: operation not permitted, unlink 'C:\Users\gatsu\AppData\Local\.meteor\packages\fourseven_scss\3.8.0_1\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\node_modules\node-sass-garbage-1eq8035\vendor\win32-ia32-46\binding.node'
    at Error (native)
```

**Comment by kildareflare** [comment]
I fixed a similar issue by running the cmd window as admin.

Some other things to try:
* use the native command window

**Comment by abernix** [comment]
What you've reported in the original issue simply isn't as simple and straightforward as you've reported it here.

While this is very likely a permission issue (as eluded to by @kildareflare) a better solution is to **never** run Meteor as administrator.  If you've ever done it, even just once, you've left behind a trail of files which have administrator privileges and can therefore only be modified if you _always_ run as Administrator.

I truly don't think it is necessary and I've not encountered any situation where I've had to be root.  You're not solving the underlying problem by running as Administrator, you're simply making it so your computer's permission model doesn't care.  It would be best to figure out the underlying issue.  For starters, you should examine the Properties of the `C:\Users\gatsu\AppData\Local\.meteor\packages\fourseven_scss\3.8.0_1\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\node_modules\node-sass-garbage-1eq8035\vendor\win32-ia32-46\binding.node` to see what permissions currently apply to it.

I cannot reproduce this error using the following steps in two windows on Windows 10 with Meteor 1.4.2.3:

#### Window 1
```sh
> meteor create 8139-1
> cd 8139-1
> meteor npm install
> meteor add fourseven:scss
> move client\main.css client\main.scss
> meteor --port 3100
```

#### Window 2
```sh
> meteor create 8139-2
> cd 8139-2
> meteor npm install
> meteor add fourseven:scss
> move client\main.css client\main.scss
> meteor --port 3200
```

For starters, please reinstall Meteor using the following instructions:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7/Win8.1:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.1.3 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

Also, consider updating to more recent versions of `fourseven:scss` as the version you're using is quite old.

Without better reproduction steps from a fresh install, I'm not sure there is much to do about this.  If you'd like further help on this, please provide more accurate reproduction steps based off a fresh installation.

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)

**Comment by stephen-alan-miller** [comment]
I am having the same issue when I run meteor test with practicalmeteor:mocha.

My computer is running windows 10 and meteor 1.5.1

```
PS C:\Users\userName\Dev\projectName> meteor test --driver-package practicalmeteor:mocha
C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, symlink 'C:\Users\userName\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\' -> 'C:\Users\USER~1\AppData\Local\Temp\meteor-test-run1s35wbj\.meteor\local\build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1586:35)
    at Object.files.cp_r (C:\tools\fs\files.js:515:11)
    at C:\tools\fs\files.js:502:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:489:25)
    at C:\tools\fs\files.js:502:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:489:25)
    at C:\tools\fs\files.js:502:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:489:25)
    at copyDirIntoTestRunnerApp (C:\tools\cli\commands.js:1712:15)
    at doTestCommand (C:\tools\cli\commands.js:1718:5)
    at Command.func (C:\tools\cli\commands.js:1547:10)
    at C:\tools\cli\main.js:1483:23
```

@abernix, I uninstalled and reinstalled meteor with the steps you posted above, and unfortunately I am having the same problem.

**Comment by stephen-mi11er** [comment]
Many thanks to @mmoo9154 for finding a workaround. 

I was able to solve by running the commands posted here: https://github.com/meteor/meteor/issues/8091#issuecomment-298139868

```
meteor reset
meteor npm install
meteor test --driver-package practicalmeteor:mocha
```

**Comment by Mklueh** [comment]
Same here, meteor reset helped

meteor npm install not required

**Comment by tommy0x2a** [comment]
Trying to meteor create simple-todos. Getting EPERM errors and sitting in Installing npm dependecies for ever. Have tried to install on 3 different Windows 7 machines. Have done both the chocolatey and InstallMeteor.exe installs.
c:\projects\meteor>meteor create simple-todos
{ Error: EPERM: operation not permitted, unlink 'C:\Users\asiaynrf\AppData\Local
\Temp\mt-11wgpte.78p3\npm\node_modules\uglify-es'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\asiaynrf\\AppData\\Local\\Temp\\mt-11wgpte.78p3\\npm\\node_m
odules\\uglify-es' }
{ Error: EPERM: operation not permitted, unlink 'C:\Users\asiaynrf\AppData\Local
\Temp\mt-1yhw6cw.xiv2\npm\node_modules\meteor-deque'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\asiaynrf\\AppData\\Local\\Temp\\mt-1yhw6cw.xiv2\\npm\\node_m
odules\\meteor-deque' }
{ Error: EPERM: operation not permitted, unlink 'C:\Users\asiaynrf\AppData\Local
\Temp\mt-11pnek4.t5a6\npm\node_modules\install'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\asiaynrf\\AppData\\Local\\Temp\\mt-11pnek4.t5a6\\npm\\node_m
odules\\install' }
{ Error: EPERM: operation not permitted, unlink 'C:\Users\asiaynrf\AppData\Local
\Temp\mt-1ag69mr.8m3si\npm\node_modules\sockjs'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\asiaynrf\\AppData\\Local\\Temp\\mt-1ag69mr.8m3si\\npm\\node_
modules\\sockjs' }
{ Error: EPERM: operation not permitted, unlink 'C:\Users\asiaynrf\AppData\Local
\Temp\mt-1j54s68.i5xe\npm\node_modules\source-map'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\asiaynrf\\AppData\\Local\\Temp\\mt-1j54s68.i5xe\\npm\\node_m
odules\\source-map' }
   Installing npm dependencies               /

**Comment by sylwekg** [comment]
@tommy0x2a I had exactly the same error on Win10 with meteor installed by chocolatey. Problem disappeared when I run cmd as admin. 
Maybe this problem is due to the fact that installation meteor with chocolatey requires to be admin...

**Comment by ca333** [comment]
i strongly recommend to *never* run any external code (that has not been fully reviewed) as admin or with root privileges. From a security point of view this is the worst you can do. 
This issue needs to be cleared by the devs. I for instance am not able to reproduce this.
