### ISSUE TITLE
NPM module code does not refresh in dev

### ISSUE THREAD

**Issue by QHose** [meteor/meteor#8144]
Hi,

Hi,

current version of meteor METEOR@1.4.2.3
source: https://github.com/QHose/QRSMeteor/tree/master/imports/ui/impress

I modified code in my NPM module (impress), but nothing changed in meteor on windows.

regards

**Comment by abernix** [comment]
Closing this issue because the problem you're referring to is too vague to accurately provide help.  What you have provided is not enough to isolate the problem, or even to determine if the problem is in Meteor itself.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please ask for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.

Thanks! :)

**Comment by QHose** [comment]
HI Sorry, you are right. 

- Create a new meteor project
- meteor npm import --save impress.js
- meteor start
- make a change to the .js file file in your modules impress folder
- meteor does not recognize you have changed the file.
