### ISSUE TITLE
add timestamp to terminal messages

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#8168]
Eg, when saving changes to file and meteor rebuilds it outputs `Client modified -- refreshing`. It would be nice to see `20161219-16:18:03.713 - Client modified -- refreshing` instead.

**Comment by larsvanherk** [comment]
I assume the timestamp would also be updated along with the refresh counter, and would not be printed on a new line?

If this is to check if Meteor actually rebuilt your last save, isn't that what the counter is for?

**Comment by avalanche1** [comment]
I suggest: new timestamp = new line.
Re cluttering: after you've rebuilt your app previous console output is void anyway so why bother?

**Comment by abernix** [comment]
@avalanche1 Can you elaborate on **why** you would find this helpful, what problem would this solve, and how this would improve your developer experience?

I disagree that the "previous console output is void".  I could _maybe_ see the value in adding the timestamp and updating it _in addition_ to the counter (it would become a "last reloaded at" date, I suppose), but the new line definitely doesn't seem necessary.  For many developers their entire screen might only be filled with "Client modified -- refreshing" under your proposal.

**Comment by avalanche1** [comment]
> For many developers their entire screen might only be filled with "Client modified -- refreshing" under your proposal.
What's wrong with dat? Perfectly fine wit me.

> Can you elaborate on why you would find this helpful
For my app to rebuild it takes 30-60sec. During this time I usually look elsewhere, I don't look at localhost tab and wait for refresh. In some cases the app won't rebuild on file change (like putting 3 whitespaces instead of 1 in html string; and other scenarios - I dont remember them exactly - this simply happens SOMETIMES); and in those cases, when the app hasnt rebuilt I don't know how to tell it, because only thing I see in terminal is 'Client modified -- refreshing (xTimes)'. As I don't book keep how many time the app have already refreshed during this working session, there is no way for me to tell whether I should test out my UI for the latest changes I've made to the source code, or I should manually restart the app...

**Comment by merlinpatt** [comment]
Perhaps this could be optionally shown through some sort of command line flag `--show-timestamps`?

This would not change the behavior of what developers have come to expect, as the default would not show timestamps, but with the flag, it would

**Comment by abernix** [comment]
@avalanche1 So you're saying that _with_ this feature, you would instead compare the current time on your computer to the timestamp shown in your console to know if your page has reloaded?

> For my app to rebuild it takes 30-60sec.

What version of Meteor are you on?  This is _such_ a long time, especially given recent performance increases in Meteor 1.4.2.x.  I believe you're a Windows user, so please add your [performance profiling](https://github.com/meteor/meteor/blob/devel/tools/PERFORMANCE.md) details (e.g. `METEOR_PROFILE=50 meteor`) to the long standing #5091.  Actual profiles of slow projects (along with `.meteor/packages` files) are more helpful than +1's on that!

> In some cases the app won't rebuild on file change

Again, as I believe you're on Windows, this sounds like #8106.  Please try to pay attention to _what_ causes these things to happen and report them in the appropriate issue.

@merlinpatt Would you find this feature useful?  We should try to establish the necessity for a feature first before discussing its implementation.

In general, I think we could come up with a more helpful solution (or work together to solve the _actual_ problems) that will help all developers consistently rather than adding a flag to fix what seems to me to be a hack-y work-around to a bigger problem.  If most developers would find this as a suitable work-around until that's done, then that's fine, but you should try to build support and gain +1's for this feature first.

**Comment by avalanche1** [comment]
@abernix I support your commentary. Though I cannot allocate resources to tracking down the root issue. Thus I've proposed a quick fix that would've solved my probs.

**Comment by hwillson** [comment]
Hi all - it doesn't look like there is much support for this feature request, so I'll close it for now. Happy to re-open if this changes - thanks for submitting this idea originally!
