### ISSUE TITLE
Problem running "todos" on meteor 1.4.2.3 on Windows 10

### ISSUE THREAD

**Issue by xauxatz** [meteor/meteor#8174]
Steps to reproduce:

- uninstall meteor on windows 10
- install fresh meteor 1.4.2.3
- git clone https://github.com/todos todos
- cd todos
- meteor

This produces the following error output:

[[[[[ ~\D\meteor\todos ]]]]]

=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "babel-runtime/helpers/classCallCheck" in /D/meteor/todos/imports/api/todos/todos.js (web.browser)
  "babel-runtime/helpers/possibleConstructorReturn" in /D/meteor/todos/imports/api/todos/todos.js (web.browser)
  "babel-runtime/helpers/inherits" in /D/meteor/todos/imports/api/todos/todos.js (web.browser)
  "faker" in /D/meteor/todos/imports/api/todos/todos.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save babel-runtime faker

---------------------------------------------

So next step is to run:
meteor npm install --save babel-runtime faker

Then I get this:

[[[[[ ~\D\meteor\todos ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While minifying app stylesheet:
   error: Can't load npm module 'autoprefixer' from packages/minifier-postcss_plugin.js. Check your Npm.depends().

=> Your application has errors. Waiting for file change.
=> Started MongoDB.

**Comment by abernix** [comment]
The first thing you should do after you clone a Meteor app is to run:

    meteor npm install

This is specified in the README for the `todos` app, but this has also become a normal recommendation for all Meteor apps.  This is not unlike a regular project that uses Node packages as you need a package manager (such as NPM or Yarn) to install the dependencies from the `package.json` manifest and they are not installed automatically.

If you run `meteor npm install` on the Todos app after you clone it, you won't need to run anything else besides `meteor` in order to run it and your reproduction steps will work fine.  (Side-note: You don't need to uninstall Meteor to reproduce the case that you're referring to either).
