### ISSUE TITLE
users collection update leak

### ISSUE THREAD

**Issue by emrekeskinmac** [meteor/meteor#8187]
http://joshowens.me/the-curious-case-of-the-unknowing-leaky-meteor-security/ solution doesnt work

and 

coding write 

```
Meteor.users.allow({
  'update': function() {
    return false
  }
});
```
doesnt work 

I get this error when I try Chrome Meteor Dev Tools plugin

```

I20161222-20:03:24.668(3)? Exception while invoking method '/users/update' Error: Match error: Expected object, got undefined
I20161222-20:03:24.668(3)?     at exports.check (packages/check.js:57:15)
I20161222-20:03:24.668(3)?     at [object Object].CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:261:3)
I20161222-20:03:24.668(3)?     at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:171:46)
I20161222-20:03:24.669(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20161222-20:03:24.669(3)?     at packages/ddp-server/livedata_server.js:711:19
I20161222-20:03:24.670(3)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161222-20:03:24.670(3)?     at packages/ddp-server/livedata_server.js:709:40
I20161222-20:03:24.670(3)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161222-20:03:24.670(3)?     at packages/ddp-server/livedata_server.js:707:46
I20161222-20:03:24.671(3)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20161222-20:03:24.672(3)? Sanitized and reported to the client as: Match failed [400]
I20161222-20:03:24.672(3)? 

```

How can I fix

**Comment by abernix** [comment]
Closing this issue because the problem you're referring to is too vague to accurately provide help and this is not the place to just ask questions.  With what you've provided, it's not possible to determine if the problem is in Meteor or the way you're calling it.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please ask for help on this issue in the [Meteor forums](http://forums.meteor.com/) or on [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor) and return here if you find it to truly be a bug and have a working reproduction with Git repo link someone can look at.

You _might_ want to review how [`allow`/`deny`](https://github.com/meteor/meteor/blob/release-1.4.2.2/packages/allow-deny/allow-deny.js#L23-L29) collection rules are evaluated, but ultimately, I think you're invoking the method incorrectly (as indicated by the error message, which is not saying anything about a permission issue).  Again though, you didn't include any reproduction of **how** you were invoking that method so someone could help you.  The `/users/update` method certainly expects an object, but it's not clear if you're passing anything.
