### ISSUE TITLE
How to add transform function to all Meteor.users.find operations?

### ISSUE THREAD

**Issue by nlhuykhang** [meteor/meteor#8226]
`Meteor.users` collection is predefined so to transform the document, I have to do it every times I call `.find`.  To solve this tedious routine, I use this code:

`Meteor.users._transform = LocalCollection.wrapTransform(function(user) {});`

Should there be a function to add transform function after defining the collection?

**Comment by ramezrafla** [comment]
@nlhuykhang , what do you mean "transform"? There are many packages that add variables to the user docs (e.g. into profile and services). Have you looked into SimpleSchema?

**Comment by nlhuykhang** [comment]
@ramezrafla I mean this:

```
Meteor.users.find({}, {
  transform(doc) {
    modifyDoc(doc);
    return doc;
  }
});
```

Because users collection is predefined so I have to add this code to all `.find` command on users collection.

**Comment by abernix** [comment]
It's true that you cannot specify a `transform` directly on the `users` collection in the same way you can with your own collections.  This is due to the fact that, as you said, `Meteor.users` is tied to the `users` collection behind the scenes in the Meteor Accounts package.

There is a work around provided by @matb33 in his post here: https://github.com/matb33/meteor-collection-hooks/issues/15#issuecomment-25809919 that will save you from having to pass the `transform` on every `Meteor.users.find` call.

I think a pull request for this could be a great contribution to Meteor if you're looking to help out the project.  I think an additional parameter to [`Accounts.config`](http://docs.meteor.com/api/accounts-multi.html#AccountsCommon-config) could be a reasonable way to implement this but I believe it would require a bit of refactoring as the `users` collection is initiated very early in the initialization ([code found here](https://github.com/meteor/meteor/blob/893ef11e2e36304a27ee76e2a3fad1f1c3867d19/packages/accounts-base/accounts_common.js#L23-L26)) and `Accounts.config` settings wouldn't be set yet.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=How%20to%20add%20transform%20function%20to%20all%20Meteor.users.find%20operations%3F&body=Migrated%20from:%20meteor/meteor%238226) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
