### ISSUE TITLE
Can't download because of corporate proxy

### ISSUE THREAD

**Issue by thebetterjort** [meteor/meteor#8231]
curl https://install.meteor.com/ | sh
I've tried to pass -k and --insecure. My corporate environment decrypts all SSL traffic and our self signed cert is not trusted CA. Although I do work for the United States Government, so this probably should change ;). 

Where can I find the install script to make changes?

**Comment by k5e** [comment]
This is rather a curl issue than a meteor one.
Set the proxy configuration in the environment before you run curl:
```
export http_proxy=http://proxy:8080
export https_proxy=http://proxy:8080
```
Of course, you put your own proxy address.

HTH
Christian

**Comment by thebetterjort** [comment]
curl: (56) Received HTTP code 501 from proxy after CONNECT
When you using export vars. Looks like we can't use meteor.

**Comment by k5e** [comment]
Does your proxy require user/password?

Put userid:password@ between // and hostname and try again.

Further, you could just download the installer script with your browser and run it yourself.


Am 10. Januar 2017 17:12:39 MEZ schrieb thebetterjort <notifications@github.com>:

**Comment by thebetterjort** [comment]
No -- We basically MITM ourselves. I will go the second route.

**Comment by abernix** [comment]
Meteor requires WebSockets to be proxied properly and your proxy isn't doing that.  In addition to needing the proper (standard) configuration (the same that is used by NPM, `curl`, and many other tools ) of `HTTP_PROXY` and `HTTPS_PROXY` environment variables, you need to ensure that WebSockets are permitted to be upgraded properly.  Depending on which proxy software you use, configuring a proxy to handle WebSockets correctly will take configuration.

If you're using `mitmproxy`, for example, it's as easy as changing the proxy to forward the WebSocket TCP packets instead of trying to intercept them.  See [these docs](http://docs.mitmproxy.org/en/stable/features/tcpproxy.html) for more information.  This is probably the most simple way to solve your problem.

Closing as this isn't a problem with Meteor.
