### ISSUE TITLE
Accounts.sendResetPasswordEmail Still User Not Found

### ISSUE THREAD

**Issue by aldo235** [meteor/meteor#8242]
i use Accounts.sendResetPasswordEmail for forgot password in API, why this still return User not found, i log user find use same _id and i found that user, but in Accounts.sendResetPasswordEmail still  not found

`let checkEmail = Meteor.users.findOne({"emails.0.address": json.email});
				if (checkEmail) {
					let email = json.email;
					let userId = checkEmail._id;
					Accounts.sendResetPasswordEmail({userId,email},function(err, ress) {
						if (err) {
							return Meteor.call('apiResponse', '400' ,res.error);
						}else {
							return 'success';
						}
					})
}`

**Comment by hwillson** [comment]
Hi @aldo235 - this type of question is better asked on the [Meteor Forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor), since this isn't an issue with Meteor or a feature request. That being said, `Accounts.sendResetPasswordEmail` doesn't support object destructuring - you can see the function signature [here](https://github.com/meteor/meteor/blob/90f7efd98b87da080955398688fd0d82e3f62fe0/packages/accounts-password/password_server.js#L529). You're passing in `{ userId, email }` which is then stored in the `userId` variable within the `sendResetPasswordEmail`, meaning the full `{ userId, email }` object is used when it tries to do the `Meteor.users.findOne` call. Thanks!
