### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by pierreozoux** [meteor/meteor#8259]
Docker is used by more and more people, so we should support an official docker image, and be listed here: https://hub.docker.com/explore/

I guess the main pain point for people is to have a nice production image.
Let's start with that and add different tags after.

Would you accept a PR for that matter, and let us help you get official?

This is related to:
 - https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/28
 - https://github.com/wefork/wekan/issues/33#issuecomment-272722033

**Comment by abernix** [comment]
Thank you for trying to make a contribution to Meteor.  I'm willing to discuss this a bit, but there really isn't a "PR" that can be opened with Meteor Core to make a Docker "official" image – it's a large project deserving of its own repo.

In addition to that, the statement has previously been made by MDG that the community would be a better maintainer of this image since it wouldn't be used internally and therefore would fall out of date very quickly.  I think it's reasonable that with enough use this _might_ eventually be promoted to an "official" image (that is to say, _possibly_ contained within the Meteor organization), but I think that's a long ways off.

The first (and largest part) of a Docker project would be getting the community to come to a consensus on an image – which as you know from the forum thread, hasn't happened.  I think that consensus is still best accomplished in the forums or with one of the existing Docker image projects.  If one of the projects snowballs into a defacto standard, then great, but until that happens this is too complex of an issue to tackle with a PR.

You might also be interested in meteor/guide#575 which is a Guide PR for at least documenting the images.  Closing, but happy to discuss further if you disagree.
