### ISSUE TITLE
lovell/sharp impossible to install on production

### ISSUE THREAD

**Issue by gooor** [meteor/meteor#8260]
https://github.com/lovell/sharp works ok on development, it works on prodction mashine but when I build my app and try to run npm install in programs/server it fails with:

```
> sharp@0.17.1 install /home/members/bundle/programs/server/npm/node_modules/sharp
> node-gyp rebuild

make: Entering directory `/home/members/bundle/programs/server/npm/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
g++: error: ../vendor/lib/libvips-cpp.so: No such file or directory
g++: error: ../vendor/lib/libvips.so: No such file or directory
g++: error: ../vendor/lib/libglib-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgobject-2.0.so: No such file or directory
g++: error: ../vendor/lib/libcairo.so: No such file or directory
g++: error: ../vendor/lib/libcroco-0.6.so: No such file or directory
g++: error: ../vendor/lib/libexif.so: No such file or directory
g++: error: ../vendor/lib/libffi.so: No such file or directory
g++: error: ../vendor/lib/libfontconfig.so: No such file or directory
g++: error: ../vendor/lib/libfreetype.so: No such file or directory
g++: error: ../vendor/lib/libgdk_pixbuf-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgif.so: No such file or directory
g++: error: ../vendor/lib/libgio-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgmodule-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgsf-1.so: No such file or directory
g++: error: ../vendor/lib/libgthread-2.0.so: No such file or directory
g++: error: ../vendor/lib/libharfbuzz.so: No such file or directory
g++: error: ../vendor/lib/libjpeg.so: No such file or directory
g++: error: ../vendor/lib/liblcms2.so: No such file or directory
g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
g++: error: ../vendor/lib/libpng.so: No such file or directory
g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
g++: error: ../vendor/lib/libtiff.so: No such file or directory
g++: error: ../vendor/lib/libwebp.so: No such file or directory
g++: error: ../vendor/lib/libxml2.so: No such file or directory
g++: error: ../vendor/lib/libz.so: No such file or directory
make: *** [Release/obj.target/sharp.node] Error 1
make: Leaving directory `/home/members/bundle/programs/server/npm/node_modules/sharp/build'
```

Everything is ok on this machine outside meteor, there's ok on development - there's something wrong only when doing npm install.

**Comment by abernix** [comment]
I'm assuming that you're developing on a different architecture than you're deploying to (expectedly), but you haven't really specified.  Please include information like this when opening issues as it can be helpful.  But I'm fairly sure my assumption is correct and this is the same issue as #7730.  Please see my comment on that issue [here](https://github.com/meteor/meteor/issues/7730#issuecomment-266476495) and read the rest of the thread.  There's a work-around there as well.

Unfortunately, this is a problem with either [`node-gyp`](https://www.npmjs.com/package/node-gyp) or the way that `sharp` is configured.  Essentially, there are shared-libraries placed in the `lib` directory when `sharp` is built on your development machine which are not properly rebuilt on the production machine.  This might sound like a Meteor problem, but Meteor uses the Node-standard `node-gyp rebuild` command to rebuild the NPMs for the target architecture and nothing else.

You'll find this same exact problem happens if you create an NPM project on your development machine, `npm install sharp --save`, copy it somewhere on your production machine (or another machine with different architecture) and then run `node-gyp rebuild` there.  Perhaps you could take the time to verify and then open an issue with `sharp`?

I'm closing in favor of #7730, but happy to discuss further there.

**Comment by gooor** [comment]
@abernix thanks for your response. After digging around I tried to rebuild libvips from source on production machine and then `node-gyp rebuild` succeeded. The worrying part of this story is that it was working ok when I did `npm install sharp` on that machine and it worked ok. Also meteor in development on that machine also worked ok (I mean sharp did what I wanted to do - resize an image). Only when doing production bundle I received that error.
I still cannot tell what actually happen - why this worked without this libvips on development environment
