### ISSUE TITLE
Importing a Meteor module's NPM packages

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8262]
I am trying to import code from an NPM package from within a Meteor module.  Specifically, Meteor module `mizzao:sharejs-codemirror` NPM-depends on `codemirror`, and I want to import specific `.js` files from within `mizzao:sharejs-codemirror`'s `codemirror`.  (These are add-ons/modes/extra features that can be optionally added onto CodeMirror.)

I **can** `import "meteor/mizzao:sharejs-codemirror/node_modules/codemirror/lib/codemirror.js"`.  This leads me to believe that it should be possible to import from within an NPM package within a Meteor module (but perhaps that assumption is wrong).

I **cannot** `import "meteor/mizzao:sharejs-codemirror/node_modules/codemirror/mode/markdown/markdown.js"` (for example, or any other JS file).

I'm hoping this is a bug.  Alternatively, if there is a better way to include optional JavaScript code within a Meteor package, please let us know.  This corresponds to issue https://github.com/mizzao/meteor-sharejs/issues/73 .

In case it is useful, [here is a demo repository](https://github.com/edemaine/meteor-sharejs-codemirror-addons) illustrating what I want to do and a current workaround.  [This is the line that I want to work](https://github.com/edemaine/meteor-sharejs-codemirror-addons/blob/master/client/client.js#L2).  Instead what I've had to do is [copy the CodeMirror module and its dependencies](https://github.com/edemaine/meteor-sharejs-codemirror-addons/tree/master/client/codemirror), while [replacing the opening lines with an import of Meteor-ShareJS's CodeMirror module](https://github.com/edemaine/meteor-sharejs-codemirror-addons/blob/master/client/codemirror/markdown.js#L4-L14).

**Comment by laosb** [comment]
It might because that this file (mizzao:sharejs-codemirror/node_modules/codemirror/mode/markdown/markdown.js) wasn't there since during the package build process, only imported files are bundled. So basically you should just npm install by yourself in your app.

**Comment by edemaine** [comment]
Thanks for the clarification on the build process.  (However, I found that even imported files were not available, strangely...)  I take it that it's impossible to make a Meteor package optionally provide some code?

Unfortunately, npm installing `codemirror` in my app does not result in getting the same `CodeMirror` instance (it gives a second copy), which means that any extensions installed (by importing the app version of codemirror) do not actually show up in the Meteor package.  So this isn't a solution.

**Comment by merlinpatt** [comment]
The Meteor package seems to be a wrapper around codemirror and sharejs, with only a little Meteor functionality. Have you considered importing both sharejs and codemirror from npm and adding the functionality yourself? This is a little more work, but you'll have much more control over your code.

**Comment by edemaine** [comment]
@merlinpatt Certainly an option, but there is a fair amount of code in there, and it would seem a shame to replicate it.  Getting ShareJS and CodeMirror to work together is actually a lot of work, done by this package.

A different approach would be to make mizzao's work available as an NPM package instead of a Meteor module.  That might work better... but also seems like Meteor's module system should be up to the task.

**Comment by abernix** [comment]
I believe the [`import` scanner](https://github.com/meteor/meteor/blob/devel/tools/isobuild/import-scanner.js) currently only analyzes within the context of its own own package when considering what to link and include in the bundle.  Essentially, (I think you'll find) since Meteor can't see the _need_ to bundle and link that package in the bundle (since it's not used within the context of the package), that it's not being shipped to the client.  To investigate, while in development, if you "view source" and examine the `mizzao_sharejs......js` bundle, you'll likely see which paths are _actually_ available to `import` in other places (by examining the `// source-map //` framing around each section).

While we might be able to fix this, I'm not sure it will be addressed soon and there would be additional overhead to it.  The recommended approach (in order to reap the full benefits) for packages like `mizzao:sharejs-codemirror` is to use the [Peer npm dependencies](https://guide.meteor.com/using-atmosphere-packages.html#peer-npm-dependencies) model.  This would allow you to have one global installation of the npm packages, `import`able by Meteor and usable by `mizzao:sharejs-codemirror`.

Does that address your problem at all, @edemaine?

**Comment by hwillson** [comment]
Hi @edemaine - does https://github.com/meteor/meteor/issues/8262#issuecomment-287298762 help address this issue? (just doing some issue cleanup - let us know if this issue can be closed, or if you'd prefer to see it stay open as a `feature` request). Thanks!

**Comment by hwillson** [comment]
We haven't heard back regarding https://github.com/meteor/meteor/issues/8262#issuecomment-305890146, so I'll close this for now. Thanks!

**Comment by edemaine** [comment]
Sorry for not responding earlier.  I think @abernix's suggestion of using [peer npm dependencies](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies) is the right way to go.
