### ISSUE TITLE
Infinite reload when setting remote default connection

### ISSUE THREAD

**Issue by raix** [meteor/meteor#827]
I wanted to make an app that connected to a remote app - collections, methods and users - simply building smaller apps that interact via common data - So I figured should be possible to do something like:

``` js
  _.extend(Meteor, {
    default_connection: Meteor.connect('http://issue769.meteor.com/', true /* restart_on_update */),
    refresh: function (notification) {}
  });
```

It kept reloading it self - kind of like when migrating so I tried changing it at server start:

```
$ DDP_DEFAULT_CONNECTION_URL=http://issue769.meteor.com/ meteor
```

_The address is just a simple app with a user login, dont mind the title_

A more cleaner approach, but still refreshing, I can se that the `Meteor.connect` is set to `true` for restart on update.
As I can se scanning Meteor code, it only affects client side, but shouldn't it possible to do this? _Or am I missing out on somthing_

**Comment by patte** [comment]
Hey! I'm trying a similar thing. I have one conventional app (Server & Client) (master), now I try to connect a "Client-Only" one to it. Basically all DPP traffic should go to the master, which holds the data and handles RPCs. I do this mainly because the two clients use different stylesheets and templates. The models/collections are identical.

I tried two approaches:
```
DDP_DEFAULT_CONNECTION_URL=http://localhost:3010 meteor -p 3020
```
I guess this one would be the easiest, because all app code can stay the same, the Meteor.connection already points the correct server. But my App keeps reloading, like you mentioned.

Second:
```
DDPURL = 'http://127.0.0.1:3010/'
console.log "Opening DDP connection to #{DDPURL}..."
@DDPConnection = DDP.connect(DDPURL)
Meteor.connection = DDPConnection
Accounts.connection = Meteor.connection
Meteor.users = new (Meteor.Collection)('users')
Meteor.connection.subscribe 'users'
```
This is from (http://stackoverflow.com/questions/28484319/ddp-connect-and-meteor-users) and kind of works (user login/session gets lost on page reload) but is ugly and Meteor.Collection calls have to get the connection...
```
@Humans = new Meteor.Collection("humans", DDPConnection)
```

Do you know a cleaner approach?

**Comment by glasser** [comment]
See https://github.com/meteor/meteor/issues/3815#issuecomment-77019985 for more details on DDP_DEFAULT_CONNECTION_URL. Short answer: it's not intended for this use case.  Use DDP.connect.

**Comment by raix** [comment]
We can set a different connection for Accounts + DDP.connect on collection - so that solved the issue
