### ISSUE TITLE
Strange errors or warnings when running app on device

### ISSUE THREAD

**Issue by ludovers** [meteor/meteor#8270]
Hello,

Im getting strange errors when I'm running an app on my android device using `meteor run android-device`.

I've just created the 'full' example, using `meteor create --full test`. I've updated everything using `meteor update` and `meteor update --all-packages`.

I deleted all meteor apps from my phone, and restarted my phone so if any data still was saved, it would be gone.

Still I'm getting these strange errors / messages:

```
I20170119-14:35:10.665(1)? I/chromium(10907): [INFO:library_loader_hooks.cc(163)] Chromium logging enabled: level = 0, default verbosity = 0
I20170119-14:35:10.733(1)? E/chromium(10907): [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
I20170119-14:35:10.733(1)? I/MeteorWebApp(10907): Serving asset bundle with version: c321e57259e39fc8ccf6c1b11e8cadee0a138ea3
```

It seems like the app is working as it should, and also saving data to the mongoDB, but what does these errors or warnings mean?

**Comment by hwillson** [comment]
The `Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver` error you're seeing was a [known Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=662040#c53), and has since been fixed (and as a bug it was pretty harmless - just more annoying than anything - you can see the reason why [here](https://bugs.chromium.org/p/chromium/issues/detail?id=662040#c50)). Since this isn't a Meteor issue, I'll close this off. Thanks for reaching out!
