### ISSUE TITLE
Coffee script doesn't show source maps

### ISSUE THREAD

**Issue by Laboratory** [meteor/meteor#8281]
Hello,

We can't see source maps in DevTools
- Meteor 1.4.2.3
- Coffeescript 1.11.1_4*
<img width="348" alt="screen shot 2017-01-24 at 15 54 41" src="https://cloud.githubusercontent.com/assets/1676506/22247990/999fff36-e24d-11e6-9907-d974c15da0bb.png">

Who can help us?
Because it's not comfortable a long time no see anything.

V

**Comment by klaussner** [comment]
Apparently, the [CoffeeScript compiler](https://github.com/meteor/meteor/blob/1b456d41a2de9137e75e5a3e43bfecbe449255f9/packages/coffeescript/plugin/compile-coffeescript.js#L79) doesn't add a `sourcesContent` property with the CoffeeScript code to the source map. If the compiled code is also passed through the Babel compiler (i.e., always since f4dbab623ba45dfb903c1de3a446d79426630ecf), the final source map is empty:

```js
{
  version: 3,
  sources: [],
  names: [],
  mappings: '',
  file: '/client/client.coffee.map'
}
```

**Comment by abernix** [comment]
@klaussner Interesting finding.  I'm inclined to believe this might have been an API change at some point and [that this line](https://github.com/meteor/meteor/blob/1b456d41a2de9137e75e5a3e43bfecbe449255f9/packages/coffeescript/plugin/compile-coffeescript.js#L48) might just need to be changed to use `inlineMap` instead of `inline` (based on [this](https://github.com/jashkenas/coffeescript/blob/0b2d852f678694179e2d3f7e62e4ae256e60921f/src/command.coffee#L417).

Care to give it a try?  If it works, maybe a PR? 🙂.  This is likely the same as #8138.

**Comment by mjmasn** [comment]
@abernix I can confirm the issue with our coffeescript apps - all `.coffee` source files are blank. Tried to look into in by running Meteor from a git checkout but it seems to remove most of the package folders from the sources list in Chrome, even with the change you suggested. Is there an obvious reason for this I might have missed?

Only thing I did was checkout meteor with `git clone --recursive git@github.com:meteor/meteor.git` and then changed `meteor ...opts...` to `~/Code/meteor/meteor ...opts...` in my bash script to run the app.

The remaining packages all contain plain js and/or css/styl files, but nothing coffee related.

| Running with meteor... | Running from checkout... |
|---|---|
| ![screen shot 2017-01-25 at 09 45 18](https://cloud.githubusercontent.com/assets/2977095/22274793/7a088a80-e2e3-11e6-979d-e30fd525a2f0.png) | ![screen shot 2017-01-25 at 09 47 05](https://cloud.githubusercontent.com/assets/2977095/22274792/7a011638-e2e3-11e6-89c9-cb2b4f5050cb.png) |

**Comment by abernix** [comment]
Thanks so much for reporting this originally, @Laboratory, and super thanks to @mjmasn for testing and applying the fix!  This will hopefully surface in an upcoming Meteor 1.4.3 beta release, quite soon(-ish).
