### ISSUE TITLE
Chrome 56 will aggressively throttle background tabs

### ISSUE THREAD

**Issue by raphaelarias** [meteor/meteor#8287]
I just saw this article, and it mentions websockets. I believe it's going to affect Meteor, too. Isn't it?

http://blog.strml.net/2017/01/chrome-56-now-aggressively-throttles.html

Chrome 56 introduces a commendable optimization to throttle background tabs' timers. From the Intent to Implement, the gist is:

Each WebView has a budget (in seconds) for running timers in background. 
A timer task is only allowed to run when the budget is non-negative. 
After a timer has executed, its run time is subtracted from the budget.
The budget regenerates with time (at rate of 0.01 seconds per second).

**Comment by dnish** [comment]
I think this is already the normal behavior on mobile devices, now we get this behavior on desktop too. It's not a pure Meteor issue, it's more a web application thing. One solution could be to provide a seperate desktop app (https://github.com/wojtkowiak/meteor-desktop) if you're running heavy tasks in the background, or you switch over to service workers, but for the moment I don't know, if Meteor already supports service workers.

BTW: It will not be shipped with Chrome 56, a Chromium dev posted something here: https://news.ycombinator.com/item?id=13471543

**Comment by abernix** [comment]
I'm not really convinced this will negatively effect Meteor.  Meteor uses [SockJS](https://github.com/sockjs/sockjs-client) to provide it's WebSocket support and the WebSockets won't be idle and SockJS will continue its usual heartbeat which will likely be enough to combat any problem.  Additionally, SockJS is a very popular framework for this and any fix will likely be in that project and not in Meteor (aside from Meteor needing to upgrade SockJS, see #4114).

Regardless, there are plenty of pre-release channels for us to reproduce this problem on instead of just being theoretical about it.  If you have a documented reproduction we could make that consideration now, but this change hasn't even been released in yet and when it does, in a dev channel, we'll have 10 weeks to react accordingly (as will the Chrome team).

Thanks for raising this concern though!  In the future, I think it's fine to create conversation about potential problems like this to raise awareness, but probably best left to the forums until it becomes technical, and specifically until a problem is identified.  For example, the same post about this on the forums: https://forums.meteor.com/t/chrome-56-will-aggressively-throttle-background-tabs-meteor-ramifications/33433
