### ISSUE TITLE
LocalCollection observe returns before delivering initial results if called concurrently on server

### ISSUE THREAD

**Issue by mattmccutchen** [meteor/meteor#8294]
On the server, if several fibers call `observe` (or `observeChanges`) concurrently on cursors on the same `LocalCollection`, then one fiber will start draining the observe queue and the other fibers' calls to `drain` will do nothing, so their `observe` calls will return before delivering the initial results.  This is the same issue as #2315 but for concurrent observes instead of reentrant changes.

Reproduced with METEOR@1.4.2.3 on Linux.  [Test app](https://github.com/mattmccutchen/meteor-concurrent-transactions-repro).

I ran into this when I put a `LocalCollection` in front of each of the MongoDB collections on the server in order to ensure that updates are sent to clients in the order they are performed by server code, as one step toward the end goal of twisting Meteor's arm to give me transaction isolation in my scenario with a single server process and a small data set.  This bug broke the transaction isolation when multiple clients subscribed to the same collection.

**Comment by mitar** [comment]
You could try maybe to use [fiber-utils](https://github.com/peerlibrary/node-fiber-utils) package to wrap  `observeChanges` prototype with `synchronize`. In this way all calls to `observeChanges` will block until other calls (the first one) finish. Not sure though if they will deliver initial results.

**Comment by mattmccutchen** [comment]
I've already [solved the problem for my app](https://bitbucket.org/objsheets/objsheets/commits/a1209a8e9a9f8fbc7ff192b453e3cfb4fdbd886d?at=master#Lsrc/lib/collections.tsT162).  If you're interested in fixing the bug in Meteor, my proposal based on my understanding of the issue so far would effectively be to revert 91c273fa417a30a1012451e3fb2bbd50270a60d5.  That suggests that 91c273fa417a30a1012451e3fb2bbd50270a60d5 tried to address a case I'm not aware of.  (If so, we don't seem to have a test for that case; I get the same two failures from `./meteor test-packages` before and after the proposed change.)

**Comment by hwillson** [comment]
Thanks for reporting this issue. While there are improvements that could be made here, this is not a popular/common issue. The chances of this being worked on anytime soon are very low, so I'll close this issue for now. If developer demand to address this becomes greater in the future, we'll be happy to re-open this issue. Thanks!

**Comment by j18ter** [comment]
We've been bitten by this issue (or a related issue causing the same symptoms). We don't use MongoDB, instead relying on server-side LocalCollections, which we synchronize with a proprietary external database. The early return of the observe function breaks the accounts-base package. Opening the application in another browser tab gets into an infinite loop because the _setLoginToken function assumes that the added callbacks have been invoked for existing documents in the users collection before observe returns. With LocalCollection this is not necessarily the case, the foundMatchingUser variable remains undefined, and it closes the connection, forcing a retry, which immediately encounters the same problem again.
