### ISSUE TITLE
Check the real IP in DDPRateLimiter

### ISSUE THREAD

**Issue by artpolikarpov** [meteor/meteor#8304]
This is a feature request. It is critical to have an access to the real user’s IP in DDPRateLimiter’s matcher. Yes, we have `clientAddress` but when your server it behind proxies `clientAddress` is not the right IP, and we need somehow access `httpHeaders` of user’s connect.

Is there any workaround at this moment?

**Comment by abernix** [comment]
Do you have [`HTTP_FORWARDED_COUNT`](https://docs.meteor.com/api/connections.html#Meteor-onConnection) set properly?

**Comment by laosb** [comment]
Actually it's hard to know the true HTTP_FORWARDED_COUNT, if your app is on a not-by-yourself infrastance.

**Comment by abernix** [comment]
@laosb Are you suggesting that the infrastructure you're deploying to has a randomly changing number of proxies which are modifying the `X-Forwarded-For` header?  This seems particularly strange and uncommon to me – also, not really the reason I asked.  I'm mainly curious if it's being set, or if @artpolikarpov has tried using it.  If you're proposing a problem with this method, then that seems like a topic for another issue.

**Comment by laosb** [comment]
@abernix For example, if you deploy to some Docker-based infrastructure, the service provider is unlikely to provide you with the info about how many proxies they have set before your container.

**Comment by artpolikarpov** [comment]
Number of proxies can change of course. Imagine that one client is serving by http (0 proxies) and second by https (1 proxy). My current function to find real IP looks like this:

```
ipFromConnection = function (connection) {
    var ip;

    if (connection.httpHeaders && connection.httpHeaders['x-forwarded-for']){
        ip = connection.httpHeaders['x-forwarded-for']
            .split(/[ ,]/)
            .filter(function(a){return a.trim()})[0];
    } else {
        ip = connection.clientAddress;
    }

    ip = _._property((ip || '').match(/\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/), '0');

    return ip;
};
```

We use it in some places to define user’s IP because `HTTP_FORWARDED_COUNT` just doesn’t help.

**Comment by abernix** [comment]
I'm afraid that the methodology you're using (and proposing) might be subject to spoofing since you're trusting that the far left-most element of the `X-Forwarded-For` header is in fact the clients address.  The original client could easily have spoofed that address though.  Typically, the same proxy server would be traversed irregardless of whether it was where your SSL was terminated or not – proxies provide functionality beyond the scope of simple SSL termination.  

The method which Meteor uses counts back through the known number of proxies by `HTTP_FORWARDED_COUNT` to get the address as it was recorded by the proxy on the connection.  A possible new RFC which is meant to improve the `X-Forwarded-For` header is [RFC 7239](https://tools.ietf.org/html/rfc7239), but I'm not sure if it's mature enough or in place enough to be trusted.

@laosb said:

> @abernix For example, if you deploy to some Docker-based infrastructure, the service provider is unlikely to provide you with the info about how many proxies they have set before your container.

Why is this unlikely?  I would absolutely expect any service provider to give information on how many proxy servers it was going to run the request through, and even if they didn't provide the information, it's relatively easy to discover and I would not expect it to be a number which was constantly changing.

**Comment by artpolikarpov** [comment]
@abernix it’s all clear what you say, but useless. We need to now ip of each connected client (in Chatra.io we have millions of them). When we were trying to use Meteor’s method with `HTTP_FORWARDED_COUNT` set to `'1'`, we get unexpected `null` for 50% of visitors, because, yes, we have dynamic number of proxies, and sometime we want to change the number of proxies on the fly without redeploying and reconfiguring running apps.

**Comment by abernix** [comment]
If you're willing to trust the `X-Forwarded-For` address (again, easily forged), you can do that using the code that you've provided however it sounds like you're asking for a way to have Meteor use a spoof-able value for the the DDP rate limiter.  This would clearly be a bad idea.

If you're willing to take the risk, you may have luck forking the `ddp-server` package into your own `packages` directory and making changes to [`livedata_server.js`](https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js#L910).

Have you thought about what the correct solution to this problem might be?

**Comment by laosb** [comment]
Actually, I know @abernix 's solution is the currently best & secure way to do that. My provider can't provide me with the count of proxies, since our container will be transferred from a data center to another at any time, but unluckily, different data centers have different number of proxies ahead. Also, data centers often change proxies for performance reasons.

**Comment by laosb** [comment]
Is there any solutions for an app to detect proxies automatically?

**Comment by mjmasn** [comment]
@laosb When you say the number of proxies changes, you mean explicit proxies? Because transparent proxies don't matter here. It only matters if there are more/fewer proxies that are adding to the `X-Forwarded-For` header. But in what situation would the number of explicit proxies change dynamically, other than @artpolikarpov's example of during an attack? That's rare for most and if you're doing that switching you could also switch to a different `HTTP_FORWARDED_COUNT` value when you switch over. Other than in that specific scenario it doesn't sound like a good idea for your infrastructure to randomly change, sounds like a recipe for all sorts of issues.

I guess if you could compile a list of possible forwarded-for IPs for the edge servers of your setup - probably the private IPs of your public facing servers, plus whatever IP ranges your attack protection uses to proxy to your site (if they append those to the `X-Forwarded-For` header) - you could take the IP address immediately before the last occurrence of one of your known IPs and that should be trustable as far as I know.

Also worth checking out if you use CloudFlare - There is a header called `CF-Connecting-IP` (and also one called `True-Client-IP` if you're on the enterprise plan, but I can't work out what the difference is...). Either way you should be able to get the user's real IP address.

**Comment by abernix** [comment]
Agree with @mjmas's comments/suggestions above as potential options, but it still seems like it would be a bizarre setup.

Changing network topography is a common tactic in the event of an attack (for example altering routing tables or changing IP space), but I'm not familiar with any mitigation tactic or defense which would change the number of reverse/forward proxy **layers** actually _visible_ to the application server (Meteor) – and that is even more true on shared infrastructure (such as the Docker scenario above).  Let's make sure we're not confusing "proxies" with network hops.  For example, I can run a Docker, inside a VirtualBox, through a router without ever needing to change the `HTTP_FORWARDED_COUNT`.

Unexpected additional proxies could easily be a sign of an intrusion (MITM) in and of themselves and should throw up red flags all over the place.  Also, changing your _internal_ network configuration in an attack seems like you'd be attempting to defend yourself against an internal attack, no?  More information on the defense tactics you're employing may offer some better suggestions here, but if you're simply referring to changing networks, etc. then those changes would not be visible to the Meteor app.

Regardless, I see no way to safely implement the feature that's being requested here.  As a suggestion, if you're really adding additional reverse proxies  (ones which would be adding `X-Forwarded-For` headers, not just additional hops/transparent proxies), perhaps its worth configuring those proxy servers to **not** modify the `X-Forwarded-For` header?  Alternatively, perhaps you could setup a secure REST end-point on your app servers which would permit you to dynamically set the `process.env.HTTP_FORWARDED_COUNT`?  It's unlikely that Meteor will offer anything like this or the insecure implementations that have been suggested.
