### ISSUE TITLE
Not working good in ie9

### ISSUE THREAD

**Issue by zaqueoae** [meteor/meteor#8315]
I'm building a web application with your framework. I am testing results in different web browsers and I have found several bugs in internet explorer 9. Do you support this version?

Thank you.

**Comment by hwillson** [comment]
Hi @zaqueoae - sorry to hear you're having problems. Can you provide specific details about the bugs you're seeing? Making sure Meteor apps work with IE 9 isn't a high priority since [Microsoft themselves no longer support IE 9](https://www.microsoft.com/en-ca/WindowsForBusiness/End-of-IE-support), but many people are successfully using IE 9 with Meteor. If you can outline the specific issues you're seeing, I'm sure someone can help. Thanks!

**Comment by hwillson** [comment]
Closing as we haven't heard back with further details outlining the issue. Thanks!
