### ISSUE TITLE
Upsert does not set default values specified in collection schema when creating document

### ISSUE THREAD

**Issue by tab00** [meteor/meteor#8323]
Meteor version: 1.4.2.3
Platform: Windows 10

When the document does not exist, upsert should behave exactly like an insert, i.e. new document created with default values set as specified in the collection schema.

What actually happens is that a new document does get created but no default keys are created and values set if key and value pairs were not explicitly passed via the modifier.

Example code:
```
Listings = new Mongo.Collection('Listings');

Listings.schema = new SimpleSchema({
    name: { type: String },
    isNew: { type: Boolean, defaultValue: true, optional: true },
    createdAt: {
        type: Date,
        optional: true,
        autoValue() {
            if (this.isInsert) {
                return new Date();
            }
        },
    },
});
Listings.attachSchema(Listings.schema);

Listings.upsert({ name: "name 1" }, { $set: { name: "name 1" }});

```

The new document would not contain `isNew` or `createdAt` keys.

**Comment by hwillson** [comment]
Hi @tab00 - this isn't an issue with the Meteor core, since as you said `upsert` works when key/value pairs are passed explicitly via the modifier. Both [`SimpleSchema`](https://github.com/aldeed/meteor-simple-schema) and [`Collection2`](http://trello.com) (which provides `attachSchema`) are third party packages. I'd recommend opening an issue for this within those repositories. Closing here - thanks!
