### ISSUE TITLE
Reactive dict does not support javascript Sets?

### ISSUE THREAD

**Issue by Kshatra** [meteor/meteor#8335]
Whenever i try to get a Set object from reactive dictionary i get an empty object. For example:
```javascript
myReactiveDict.set('someKey', new Set([1,2,3]) );
console.log( myReactiveDict.get('someKey') );
```
The output is an empty plain object;

**Comment by hwillson** [comment]
When you set something in a `ReactiveDict`, behind the scenes you end up calling [`EJSON.stringify`](https://github.com/meteor/meteor/blob/6a4d76ef8e78ef2e764514596028817edc0921f1/packages/reactive-dict/reactive-dict.js#L6). Since `Set` is not supported by [EJSON](http://docs.meteor.com/api/ejson.html) , it can't be used directly with `ReactiveDict`'s. As a workaround, you could do something like convert your `Set` into an array using `Array.from(yourSet)`. You can store your array in your `ReactiveDict`, then when you pull it back out, convert it back into a `Set` using `new Set(someArray)`. Closing - thanks for reaching out!
