### ISSUE TITLE
[Feature] No more imports directory

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor#8341]
Almost a year ago, @zol mentioned at a [Meteor night](https://youtu.be/NICqNT-U4gk?t=1h11m58s) that a future release might get rid of globals, which also get rid of the need for an imports/ directory.

I bring it up now because recently the focus has been on features surrounding the build process (mostly to improve performance, but still a valid concern).

I understand that this would be a huge breaking change, but I think it's time. Developers have had plenty of time to switch over to using imports, and it's recommended by the tutorials and the guide. If developers don't want to use imports, they can stay at whatever version still has globals. Having automatic globals can also pose security risks as well.

Since this is a big change, one possible in between step might be to have a `globals/` directory. Then you put all files with *dev-created* globals (like collections) in there, and everything else needs to be imported. This would essentially be the reverse of what we have now. (I do apologize if this isn't actually feasible or if it's extremely difficult. I don't know enough about how the build process works)

@awatson1978 suggested having "a `globals` package that provides the currently shipped globals"

As @stubailo said, "It might make sense to launch this alongside [code splitting](https://github.com/meteor/meteor/pull/8327) because that gives people a serious motivation to use imports everywhere."

I've copied all this over from the [forum post](https://forums.meteor.com/t/no-more-imports-directory/33825) that kicked this off out of laziness and to keep the relevant comments in the history of this issue.

(Oh and I think I labeled it properly, but am not sure. Other `imports/` related issues were also labeled as `Project:Tool` which is why I chose that one)

**Comment by chompomonim** [comment]
Totally agree with this suggestion and +1 for globals package to have backwards compatibility for old style applications, so they still will be able to migrate their code gradually.

**Comment by CarlQLange** [comment]
I would be extremely sad to lose globals - having the possibility of a `/globals` dir sounds like a great idea to me!

**Comment by merlinpatt** [comment]
@benjamn what are your thoughts on this?

**Comment by benjamn** [comment]
I think there are two different proposals here, both worth considering.

First, we could eliminate the need for `imports` directories if we made all modules lazy, as in Node, if there was some way for the developer to specify client/server entry point modules. One incremental approach would be to adopt this behavior if the application `package.json` file has a `"main"` and a `"browser"` field (or perhaps a `"meteor": { "client": ..., "server": ... }` section).

Getting rid of package global variables is a separate question in my mind. While we encourage explicit imports over `api.export`, globals are still undeniably useful. For example, the `promise` package has `api.export("Promise")`, which makes a reliable `Promise` constructor available wherever the `promise` package is used. Explicitly importing `Promise` is not something you're supposed to have to do (it's part of the ECMAScript spec now), so the global style makes more sense.

**Comment by ephemer** [comment]
I'm all for killing the globals + optional opt-in

@benjamn I think it'd be ok for packages to keep their present behaviour for now, provided the docs make it clear that api.export() should only be used in rare cases.

The big win here would be in the app, where there is currently little ability to control the build process, unlike in packages where devs already have full control.

To me, making the app directory "lazy", as you say, would make the entire dev environment more internally consistent (with packages)

**Comment by laosb** [comment]
I think we can start with using main and browser entry in package.json, and keep imports/ for now.

**Comment by stubailo** [comment]
I don't think we should "kill globals" or anything like that. But perhaps there would be a possibility to have one of two modes of operation:

1. "Legacy/globals mode" where things work as they do today - anything outside of `imports/` is an "entry point"
2. "Module mode" where everything is lazy except for particular files specified in `package.json`

There are few questions here:

1. What about entry points beyond just "client" and "server"? We should make sure the configuration works in such a way that alternate entry points are also possible, for example for service workers, Cordova, react native, etc.
2. Does "module mode" still need the `client/` and `server/` directories to make code appear only in that environment? If it were possible, the "holy grail" would be to eliminate file system conventions entirely IMO.

**Comment by ephemer** [comment]
By "kill globals" I was mostly referring to the globals from the Meteor packages. We obviously shouldn't remove any standard javascript functionality, but I think a broad culture shift towards imports can only be a good thing for code clarity, maintainability, bundler speed, etc.

The suggestion regarding "legacy / globals mode" was that they are opt-in, i.e. you need to put these in a `legacy` directory for them to eagerly load as they do now. Everything outside of that directory must be referenced directly or indirectly by the entry point listed in `package.json`.

As it already is now in the `imports` directory, I don't think it makes sense to have `client` or `server` directories do anything in particular in terms of loading in a particular environment. Again, these should continue working as they do now when in the `legacy` directory (i.e. `/legacy/client` or `/legacy/server`).

I think your questions about further entry points can be solved in `package.json`, assuming that is the solution moving forward (I have no strong opinion at all about where to set the entry points, but that solution seems reasonable).

```
// package.json
{
  ...
  "meteor" : {
    entryPoints: {
      "client": "./clientMain.js",
      "server": "./serverMain.js",
      "cordova": "./cordovaMain.js" // use this only if it exists, otherwise use "client"
    }
  }
  ...
}
```

**Comment by tcastelli** [comment]
I forgot about this and posted at the forums but my 2 cents are
- Instead of using a legacy folder (which can be a pain for people that still prefer to use globals) I prefer to use a "globals" package / start meteor with -loading globals or define a meteor:{loading:"globals"} in package.json.
- I also think defining entry points at the package.json is the way to go, thus eliminating any kind of client & server folders. However, I think the functionality of client/server/cordova folders is ver handy to make sure you don't import code on the wrong place. So if present in the folder structure, I would keep that functionality for future versions too.
- For future entry points, it would be cool to make the addition of entry points dynamic, in the sense that the build tool could read the package.json and get the instructions of for example "when to deliver react-native" from another file or meteor package. 
- Regarding what to do with packages, I'm not sure if this easily feasable, but my idea is (if the globals package is not used):
  1) Convert all meteor package dependencies into imports and all the global exports into module exports, so if we want to use a package we will have to import it, but it won't be broken on the inside since the package itself will import variables from the other packages. 
 2) Always import Package variable from "meteor/package" inside the packages to allow checking for weak dependencies. 
3) Defined assets could be loaded with dynamic imports once the package is imported in the app code.
4) For things that need to be global like Promise, meteor could automatically add them to the global level at startup based on a variable configuration at package.json, or just add them directly and document which global variables would be available at all the times.

**Comment by hluz** [comment]
> But I'd suggest this legacy directory be decommissioned by Meteor 2.0 at the latest.

Is this a suggestion that a "globals mode" (opt-in) be removed from 2.0? If so, I strongly disagree. Unless there is some technical reason that makes it somehow inoperable, what would be the point? Just to create pain for people that have app in production?

Also, although I understand the intent for naming the dir "legacy", I would try not to stigmatise it. "globals" should do.

**Comment by ephemer** [comment]
@hluz I can't see Meteor 2.0 coming out any time soon. And a major version number is usually associated with breaking changes.

For all sorts of reasons (bundling performance, testability and lazy code [down]loading being just a few that immediately come to mind) it does make sense to remove global functionality eventually and entirely. Meteor has always been strongly opinionated in order to benefit developers, and this is one opinion that would likely improve developer experience significantly. So doing it in Meteor 2.0 (which may still be a year away if it is to exist at all) seems reasonable to me.

To be clear (again) I'm not suggesting that Meteor somehow prevents developers from writing `window.xyz = xyz` to make a global variable. Just stopping variables (including the Meteor-internal ones) from being global and eagerly loaded by default. It is easy to see though that using variables created in that way could break if the required global code hasn't even been downloaded from the server yet. Or if you're trying to test one tiny package or submodule and don't want to re-bundle the entire app at every change.

For those same reasons, I imagine it wouldn't be as easy from a technical perspective to add the global functionality as a package. Also a package wouldn't give the developer as much as a `legacy` directory over what is eagerly loaded or not. But I'd be happily wrong about either of those points.

**Comment by stubailo** [comment]
I want to add here that I was trying to switch to nested imports and dynamic imports in my app and since I forgot to use an "imports" directory they didn't work as I expected. So for new apps I can imagine having lazy loading as a default would actually improve the developer experience for some people.

**Comment by cubitworx** [comment]
I really like the suggestions from @stubailo and @ephemer about entry points but I would **really** like to see entry points being controlled from the settings file instead of from `package.json`. This would allow you to run/build different configurations from the same code base. Importantly allowing finer control over assets (scss, etc) and not just js files.

You could run them like this:
```
meteor --settings private/settings/browser.json
meteor --settings private/settings/cordova.json
meteor --settings private/settings/micro-service.json
```

```
// private/settings/browser.json
{
  "meteor": {
    "entryPoints": {
      "client": ["browser/client.js","browser/client.scss","browser/client.html"],
      "server": ["browser/server.js"]
}}}
```
```
// private/settings/cordova.json
{
  "meteor": {
    "entryPoints": {
      "cordova": ["cordova/client.js","cordova/client.scss","cordova/client.html"],
      "server": ["cordova/server.js"]
}}}
```
```
// private/settings/micro-service.json
{
  "meteor": {
    "entryPoints": {
      "server": ["micro-service/server.js"]
}}}
```

Directory structure could be something like this:
```
browser
    client.html
    client.js
    client.scss
    server.js
common
    client          // Shared files for client
    server          // Shared files for server
cordova
    client.html
    client.js
    client.scss
    server.js
micro-service
    server.js
```
Shared files could in reality exist anywhere because you would be doing all the imports in the files defined in your `entryPoints` in `settings.json`

**Comment by lazaridis-com** [comment]
Just don't forget that you're confusing newcomers with all this. See, just forget all and start from scratch. Ther is this question:

#110 - "Where is the best place to put common code?"

The answer is essentially ad folder named "common".

So, we have a structure (this is independent of Meteor, as we start from scratch) :

* client
* server
* common

In Meteor you have your `imports` folder, which I understand is used for lazy-loading **and** for `common` code.

Instead of making everything `lazy-loading`, a temporal (and immediately introducable) solution could be this:

* Introduce a config-option, which specifies the lazy-load folders. The default is `imports`. This would be backwards compatible, would not introduce any new behavior.

* I for example would place my common code into `common` folder, and add it to the lazy-load.
* dev X would simply continue with the existent "imports" folder (thus he does not have to change his thinking)
* dev Y would slowly migrate away from Imports, using more and more other folders (which he configures to be lazy-loading)

**Comment by ephemer** [comment]
@lazaridis-com yeah, the possibility of having opt-in lazy loading is one I like the sound of in the meantime. I doubt we could make any hard optimizations regarding build time/testing etc. with that solution but at least it would allow developers to get their codebases in order for a potential move to lazy loading being the default

**Comment by mitar** [comment]
I think the best approach is to have entry points in `package.json` and new apps created with `meteor create` should have those populated. In this way you get lazy imports. If you do not have those entry points defined, then things operate as now.

I do not understand though why would globals just be disabled when lazy imports are enabled. This is on the author of the package to decide (and users of the package to decide to use such a package). If package exports a global object, then it should be available globally with lazy imports or without.

**Comment by merlinpatt** [comment]
Disabling globals shouldn't happen automatically when lazy imports are enabled. But it is important that be disable-able. For my app, I don't want the possibility of any client accessing a global and changing things even if the change is only on the client side.

**Comment by mitar** [comment]
> For my app, I don't want the possibility of any client accessing a global and changing things even if the change is only on the client side.

Hm, I think packages exporting globals and you adding those packages at the app level does not mean that those globals should also be added to the browser global scope. I think the latter I agree is something useful only for integration with old-school libraries, and debugging.

So, maybe we have two settings here:
* should Meteor app-level scope be the same as browser's global scope
* should globals from a package be added as globals automatically of your code in `client` and `server` so that you do not have to import anything

I use local packages approach to organizing code in my apps, where all code is inside `packages/<package>` directories, with almost no package listed in `.meteor/packages`, and I use global exports almost exclusively, but my browser's global scope does not get dirty by that.

**Comment by cubitworx** [comment]
@lazaridis-com I really don't think that we should be telling people how they **have** to structure their application. I'm all for recommended structure but we have to move away from the legacy mindset of the **must have** `client`, `server` and `both` folders. The only reason we have these questions at the moment is because we still have some files automatically loaded by Meteor. Once lazy-loading is the norm for _all_ files it doesn't matter where you put your files because the entry points can be controlled and you can put your files any where you want to.

**Comment by cubitworx** [comment]
@mitar Why would it be best to have entry points in `package.json` and not in `settings.json`? I think having them in `settings.json` offers more flexibility with running multiple applications off a single code base. If we put it in `package.json` you can only have 1 set of entry points for all applications on that meteor app.

**Comment by mitar** [comment]
I think `package.json` is more reasonable because it allows something you can commit into a repository, and have it picked automatically by the app. I think if you want `settings.json`, then I do not see it too hard to make in `package.json` an entry point which loads a script which checks `settings.json` and loads the next one. But if we put things into `settings.json` I worry that people will have issues committing their private keys and stuff into a repository by accident.

**Comment by cubitworx** [comment]
> I think package.json is more reasonable because it allows something you can commit into a repository

Good point. I retract my suggestion of having it in `settings.json`

**Comment by CaptainN** [comment]
I like the idea of making every folder lazy by default, and providing a way to mark folders as eager for the different special folders we have now, on an opt-in basis. This way legacy upgrades are as simple as adding the `client` and `server` (and maybe `both`) folders to the eager config area in `package.json`.

The clear change then is that instead of having every page be eagerly loaded on `both` by default, and then some specialty folders (like `server`, `client` and `imports`) - every folder becomes lazy loaded, and then to get special folders you need to mark them as such. A new project would have no eager folders by default. Legacy apps would have a clear migration path to maintain backward compatibility by adding config options.

If the eager loading feature ends up getting deprecated new devs wouldn't even need to be aware of the feature - though maybe it's nice to have, and we'll need a way to get server and client booting anyway.

**Comment by merlinpatt** [comment]
To make the legacy upgrade even easier, would it be possible to have meteor automatically add a line to `package.json`?

If not, it's not a huge deal for someone to have to add a line or two to their `package.json`, but making things easy to upgrade is one of Meteor's specialties :-)

**Comment by stubailo** [comment]
Yeah we have a facility for modifying projects during a version upgrade! So adding something to `package.json` should be super simple.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5BFeature%5D%20No%20more%20imports%20directory&body=Migrated%20from:%20meteor/meteor%238341) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
