### ISSUE TITLE
[1.4.3.1] facebook-oauth (appId - clientId) question ?

### ISSUE THREAD

**Issue by d62remi** [meteor/meteor#8381]
Hi, 
Little question !

In facebook-oauth package : https://github.com/meteor/meteor/blob/devel/packages/facebook-oauth/facebook_client.js#L34

`'https://www.facebook.com/v2.2/dialog/oauth?client_id=' + config.appId +`

Why not used **clientId** instead of **appId** for iso functionality with google, twitter, ... ?

`'https://www.facebook.com/v2.2/dialog/oauth?client_id=' + config.clientId +` 

I searched for why google-oauth did not work with this example replacing facebook by google before I realized that I needed to use **clientId**
https://guide.meteor.com/security.html#api-keys-oauth
```javascript
ServiceConfiguration.configurations.upsert({
  service: "facebook"
}, {
  $set: {
    appId: Meteor.settings.facebook.appId,
    loginStyle: "popup",
    secret: Meteor.settings.facebook.secret
  }
});
```

**Comment by abernix** [comment]
Thanks for bringing this up!  Yes, this is unfortunate.  [Facebook calls it `appId`](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#login), and (I'm assuming) we were trying to use terminology that was consistent with the individual oAuth service providers documentation and terminology, especially since different services offer _additional_ options (such as `login_style`, etc.) which are not consistently implemented.  Each provider should be presumed to have different parameter names.   It could be argued that the faux pas here was on Facebook for choosing to deviate from the oAuth standard "client_id".

At the very least, I think the documentation could make it clear that there are variations in settings.  At the very most, perhaps we could alleviate the pain for developers who make this mistake by supporting both: `config.appId || config.clientId` and then changing that guide example once it's done?

Thoughts?  Maybe submit a pull-request to fix it? 😃

**Comment by hwillson** [comment]
Just to add - this has come up before (#2562), so adjusting the code to handle both `appId` and `clientId` sounds like the way to go.

**Comment by abernix** [comment]
I'm tempted to change actually change the "supporting both" option since Twitter uses yet another option: `consumerKey`.  I noticed this when reviewing the documentation pull-request tied to this issue: https://github.com/meteor/docs/pull/125

Maybe this should just be a doc issue?  Having a third fallback seems odd.

**Comment by d62remi** [comment]
Maybe used that :

```javascript
var config = ServiceConfiguration.configurations.findOne({service: 'twitter'});
if (!config) {
  credentialRequestCompleteCallback && credentialRequestCompleteCallback(
   new ServiceConfiguration.ConfigError());
 return;
}

// Used clientId instead of consumerKey
config.consumerKey = config.consumerKey || config.clientId;

var credentialToken = Random.secret();
// We need to keep credentialToken across the next two 'steps' so we're adding
// a credentialToken parameter to the url and the callback url that we'll be returned
// to by oauth provider

var loginStyle = OAuth._loginStyle('twitter', config, options);

// url to app, enters "step 1" as described in
// packages/accounts-oauth1-helper/oauth1_server.js
var loginPath = '_oauth/twitter/?requestTokenAndRedirect=true'
      + '&state=' + OAuth._stateParam(loginStyle, credentialToken, options && options.redirectUrl);
```

What do you think ?

**Comment by abernix** [comment]
@d62remi So you're saying that all the OAuth services used would fall back to `clientId`?

**Comment by d62remi** [comment]
@abernix 
I think ! 

If I list all OAuth services packages apart facebook and twitter, I find clientId :
- Github : https://github.com/meteor/meteor/blob/devel/packages/github-oauth/github_client.js#L30
- Google : https://github.com/meteor/meteor/blob/devel/packages/google-oauth/google_client.js#L65
- Meetup : https://github.com/meteor/meteor/blob/devel/packages/meetup-oauth/meetup_client.js#L34
- Meteor Developer Accounts : https://github.com/meteor/meteor/blob/devel/packages/meteor-developer-oauth/meteor_developer_client.js#L30
- Weibo : https://github.com/meteor/meteor/blob/devel/packages/weibo-oauth/weibo_client.js#L30

As a result, we could remove this doc PR : https://github.com/meteor/docs/pull/125 and used single clientId for all OAuth services ;-)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5B1.4.3.1%5D%20facebook-oauth%20(appId%20-%20clientId)%20question%20%3F&body=Migrated%20from:%20meteor/meteor%238381) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
