### ISSUE TITLE
EISDIR tools/cli/dev-bundle-links

### ISSUE THREAD

**Issue by tmignot** [meteor/meteor#8383]
I'm running an error while trying to run a meteor app that have been sent to me zipped from a Windows 10 computer.
I'm running under ArchLinux.

here is what I get when running meteor in my unzipped directory:

> $ meteor
> /home/user/.meteor/packages/meteor-tool/.1.4.1_3.1212xo3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
>       throw error;
>       ^
> 
> Error: EISDIR: illegal operation on a directory, unlink '/home/user/app/.meteor/local/dev_bundle'
>     at Error (native)
>     at Object.fs.unlinkSync (fs.js:932:18)
>     at exports.makeLink (/tools/cli/dev-bundle-links.js:20:8)
>     at [object Object].ensureDevBundleLink (/tools/project-context.js:1416:7)
>     at [object Object]._readFile (/tools/project-context.js:1350:10)
>     at new exports.ReleaseFile (/tools/project-context.js:1300:8)
>     at /tools/cli/main.js:847:22

I openned _tools/cli/dev-bundle-links.js_ and two issues can be found here:

- unlink should be tried/catched because when failing, it leaves tempPath (in the form "dev-bundle-xxxxxxxxxxx" in the _app/.meteor/local/ directory/_) which could be removed in the catch block

- unlink can't delete the _dev-bundle_ directory as the error code says: **EISDIR**

maybe **fs-extra** would be a good solution.

My own problem is resolved since I have manually deleted the _dev-bundle_ directory before re-running my app, but I could not find any tips on this error under my OS on the web, so I write it here in case someone else runs the same issue.

**Comment by arrygoo** [comment]
Ran into the same issue.

**Comment by abernix** [comment]
Out of curiosity, if you open the `.meteor/local/dev_bundle` directory, is it empty or is there a structure?

The `dev_bundle` is not actually a part of an app, but rather the Meteor tool itself (and platform/architecture specific).  Realistically, the entire `local` directory (and similar observances listed in the `.meteor/.gitignore` file) should be excluded when moving a Meteor project to another computer.  Just "Zip"-ing the project probably didn't observe that and you might try something like `git archive --output=../file.zip HEAD` (within your app, which hopefully is Git-initialized) in the future to create that archive since it will only grab items which are _in_ Git and `.gitignore`d files like `.meteor/local/dev_bundle`, `.meteor/local/db`, etc. would be left out.

**Comment by hwillson** [comment]
We haven't heard back regarding the questions asked in https://github.com/meteor/meteor/issues/8383#issuecomment-288906842. I'll close this for now, but we'll be happy to re-open if you can respond to the questions in that comment (and if the provided suggestions don't help). Thanks!
