### ISSUE TITLE
Offline Installer for Windows

### ISSUE THREAD

**Issue by Giraldez** [meteor/meteor#8413]
Hey guys,
I follow the directions here: https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md
but still need internet conection.
I run _meteor create projectname_ command and meteor still need to download some pakages.
Later meteor say something like: run _meteor npm install_ on every new project and still need internet connection
So, please, make a full meteor windows installer offline. I need to work full offline!
Thank in advance

**Comment by arielf-camacho** [comment]
+1 to this. This is critical for some people. Please, make the life easier to new meteor lovers that have no good Internet connection or none at all.

Thanks

**Comment by klaussner** [comment]
Meteor can already be used offline (even to create new projects) because it caches every Atmosphere package that it downloads. This means that you can add any version of a package to your project as long as you have downloaded it before. For example, if you add `coffeescript` to your *.meteor/packages* file and run `meteor` once, it will download the package and cache it so that it doesn't have to be downloaded again the next time you add it to a project.

You can get similar offline features for npm packages with [Yarn](https://yarnpkg.com/en/). Run `meteor npm install --global yarn` to install Yarn and then (in your project directory) `meteor yarn install` to install npm dependencies. When you create a new project, run `meteor yarn install --offline` instead to install the packages from the Yarn cache.

**Comment by Giraldez** [comment]
Thank Klaussner for your answer and arielf for your support.
I will explain may situation in better way!
I have a computer on my home with no internet connection and I need bring to my home an offline installer what no need internet connection to create a simple meteor project like other frameworks: Django, Silex, AngularJS, etc
The directives here:  https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md is not the solution at all! because, still need to download some packages the first time I run meteor create and meteor npm install commands on every new projects.
Conclussions:
-I need to download an offline Installer(in a computer of my work)
-copy it to my pendrive
-go to home
-install it
-run meteor create and meteor npm install commands with no internet connection for a simple meteor project
Thanks again!
Giráldez.

**Comment by abernix** [comment]
First, make sure you set the `METEOR_OFFLINE_CATALOG` and `METEOR_NO_RELEASE_CHECK` variables are set to any truth-y value – that will help by making sure Meteor doesn't try to check the catalog for package updates and doesn't bother checking updates for Meteor itself:

    SET METEOR_OFFLINE_CATALOG=true
    SET METEOR_NO_RELEASE_CHECK=true
    meteor

If that doesn't help, the instructions linked to (the Alternate Windows Installation) do represent an accurate way to make an offline version of Meteor _itself_, but since Meteor needs access to NPM packages, you may run into another problem when we need to download an NPM dependency (or dependency of a dependency).

You _might_ be able to get some more visibility into _what_ it's trying to download by setting `METEOR_LOG` to `debug`:

    SET METEOR_LOG=debug

... and then running `meteor` again.

Please note that any of these environment variables will have to be reset if you change to a new Command Prompt or PowerShell terminal.

As to the actual request though, having a fully offline install is still going to be difficult because as soon as you need another package outside of core packages, it will have to be downloaded and installed.  I can understand your desire for this though!

What if you installed Meteor on the computer _with_ the Internet connection, make sure you have everything you need, and then move `%LocalAppData%\.meteor` to the offline computer?  You will have to manually set your `PATH` (again, per the alternative instructions).  This is probably the best chance you have at making this work.

We could analyze our bootstrap build process (the process which builds the file you download in the Alternative Installation instructions), but this isn't currently a top priority and is unlikely to get looked at any time soon.  If someone wanted to look into it though, the code is [here](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L2321-L2325).

**Comment by Giraldez** [comment]
Thanks, abernix.
Today I will try to move meteor and project from online to offline computer using your tips. Tomorrow I will feedback to you!
And my request is still alive. Please make an offline installer that need zero internet connection to start. Is usefull to beging start meteor project while read a book on offline computer.

**Comment by Giraldez** [comment]
Hello abernix,
yesterday, I moved the meteor framework and procjetc "microscope" from online to offline computer.
In the online computer everithing work OK!
I copied %LocalAppData%\.meteor from one computer to another and the procjetc folder too.
finally in the offline computer I got an error:
I:\PINCHA\microscope>meteor
C:\Users\Cluster\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\met
eor-promise\promise_server.js:190
      throw error;
      ^
Error: EPERM: operation not permitted, unlink 'I:\PINCHA\microscope\.meteor\local\dev_bundle'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at exports.makeLink (C:\tools\cli\dev-bundle-links.js:20:8)
    at [object Object].ensureDevBundleLink (C:\tools\project-context.js:1444:7)
    at [object Object]._readFile (C:\tools\project-context.js:1378:10)
    at new exports.ReleaseFile (C:\tools\project-context.js:1328:8)
    at C:\tools\cli\main.js:898:22
And I don't know what to do now : (

**Comment by Giraldez** [comment]
Hello Abernix,
- When I run rmdir I:\PINCHA\microscope\.meteor\local\dev_bundle, the result is: "Directory is not empty"
- I deleted de directory I:\PINCHA\microscope\.meteor\local\dev_bundle completely, run meteor command inside microscope folder and voila! meteor create de juction dev_bundle and now the project is running 100% OK on the offline computer.
I learn, thank to you, to move framework and project folder from online to offline computer.
Thanks Again

**Comment by abernix** [comment]
Great!  I suppose I understand what happened - when you copied the app to your local computer, it copied the entire `.meteor\local\dev_bundle` not as a junction but as if it were an actual directory.  I've been told the next version of Windows will be much more reasonable about the way it treats junctions and symlinks.  Specifically, it will be possible to create a symlink as an unprivileged user – something which will benefit Meteor greatly as currently we use junctions (which _are_ permitted) to make Meteor work.  (On *nix we use symlinks, so this will bring the functionality more closely together).

I'll leave this open for now as a [feature request](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests).

**Comment by Giraldez** [comment]
Yes! abernix. I used teracopy as copy handler. This program copy all(include the junction directory).
the other way I found is running meteor reset command before copy the project folder to the offline computer.
Yesterday, I run meteor update and add some new packages to my project. Latter, I copied the framework and project folders to the offline computer with no problem.
Thank again for your help, and thank for maintain my "feature request" Think the benefit for people that have limited internet connection. An offline installer will give starter point to learn meteor with tutorial/book in the peace of offline home. : )

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Offline%20Installer%20for%20Windows&body=Migrated%20from:%20meteor/meteor%238413) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
