### ISSUE TITLE
Meteor App Build Issue

### ISSUE THREAD

**Issue by taislam** [meteor/meteor#8420]
Hi.

I am facing internet connectivity issue in my app. When app build is pointed to the local machine, API's using internet work e.g 
meteor build ../ --server=192.168.1.1:3000 --mobile-settings=settings.json

but when we are building it to another, API's that using internet don't works e.g
meteor build ../ --server=app.meteorapp.com --mobile-settings=settings.json

Internet permission is allowed to the app.
How to solve this issue?
Thanks

**Comment by abernix** [comment]
> API's using internet work

Are you saying that outgoing API calls from your application stop working when you're using `app.meteorapp.com`?  Outgoing calls shouldn't really be affected.

> meteor build ../ --server=app.meteorapp.com --mobile-settings=settings.json

Have you tried including the scheme in the `--server`?  For example: `--server=http://yourdomain.com`.

You're using `meteorapp.com` as your domain, are you actually deploying to Galaxy or not?  If you are using Galaxy, you shouldn't be using `meteor build`, you should be using `meteor deploy` (see the exact command on your Galaxy dashboard).

**Comment by taislam** [comment]
Actually we have used geo location API in our website. It's work well on the web. On below command, geo location API works well
`meteor build ../ --server=192.168.1.2:3000 --mobile-settings=settings.json`

But when we are pointing it to server like below, Geo location API stops working 

`meteor build ../ --server=app.meteorapp.com --mobile-settings=settings.json`

**Comment by abernix** [comment]
Any answers to the rest of my questions? :smile:

**Comment by tariqjawed83** [comment]
@abernix yes we are using galaxy server for now, and we are using deploy command successfully to install the web application on galaxy. All works fine on web application deployed to galaxy server itself.

The issue arises when we build an android application and points it our galaxy sever address address as mentioned, the android app is able to hit the galaxy server and fetch mongo data as well. But when used any other address such as AWS S3 or GeoLocation API, then it is unable to do that from Android app, although from web application itself they works fine.

I am wondering is there any configuration related to security we need to do for Android build/package?

**Comment by abernix** [comment]
You're saying that your mobile app itself is unable to connect to an AWS S3 API or GeoLocation API from within the context of the application.  You are running into a problem with the [Same-origin policy]().  Please refer to [this section](https://guide.meteor.com/mobile.html#cors) of the [Meteor Guide](https://guide.meteor.com/) which specifically mentions this and ensure that you are implementing [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) correctly:

> CORS relies on headers set by the server. In other words, in order to allow access to a remote resource, you may have to make configuration changes on the server, such as setting a `Access-Control-Allow-Origin` header.

You may really just want to consider doing the actual request from your server (via a Meteor Method) where you will be less restricted by these limitations instead of from the mobile WebView.

You can try asking for help on [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).
