### ISSUE TITLE
Babel fails to transpile NumericLiteralTypeAnnotation

### ISSUE THREAD

**Issue by wursttheke** [meteor/meteor#8423]
After updating my app to v1.4.3.1 on MacOS Sierra Meteor is throwing the following error at startup:

```
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):

   /Users/phw/.meteor/packages/ecmascript/.0.6.3.1eko5q7++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/types.js:663:19:
   did not recognize object of type "NumericLiteralTypeAnnotation"
   at Object.getFieldNames
   (/Users/phw/.meteor/packages/ecmascript/.0.6.3.1eko5q7++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/types.js:663:19)
...
   at Object.Babel.compile (packages/babel-compiler.js:48:24)
   at packages/babel-compiler.js:162:22
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/babel-compiler.js:192:20)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:161:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:93:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:92:14)
   
   
=> Your application has errors. Waiting for file change.
```

## Reproduction
- Create a blank meteor app: `meteor create meteor-test`
- Run `meteor npm install`
- Add following line to `main.js`: `var a : 1 = 1;`
- Start the app `meteor`

I found several hints on the web which might be relevant:

- [Pull request on benjamn/ast-types](https://github.com/benjamn/ast-types/pull/205)
- [Babel Issue](https://github.com/babel/babylon/issues/329)
- [Meteor forum post](https://forums.meteor.com/t/error-after-updating-meteor/33917)

**Comment by abernix** [comment]
Thanks for reporting this!

You've found the relevant issues.  `NumericLiteralTypeAnnotation` was definitely renamed and that's part of the problem, but it would seem that `ast-types` just wasn't aware of that concept in general on the Babel side of things (the Flow definitions seem correct).

This hasn't cropped up before because previously, Babel was being used to parse the AST first and now Reify goes first (thanks to https://github.com/meteor/babel/commit/c8815d26f184d2dcae7bdfbeb2190b55337e9092).  This should be a preferable implementation in the end though, once we work through this.

The bad news is that since https://github.com/meteor/meteor/pull/8030 was a part of 1.4.3.x, it demands that you use `ecmascript@0.6.3` (or `ecmascript@0.6.2`, which is functionally the same) and isn't compatible with `ecmascript@0.6.1`, which means you will need to continue to use Meteor 1.4.2.7 (or less) with `ecmascript@=0.6.1`.

The good news is that @benjamn works on (and for) Meteor and I think he can take care of this relatively easily.  The continued bad news is he's out of the office through next week.

**Comment by wursttheke** [comment]
Thanks for looking into it, @abernix. I'll just stick with 1.4.2.7 for now.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.4.3.3-beta.3` in your application directory. Please feel free to reopen this issue if it's not resolved for you.

**Comment by wursttheke** [comment]
Hi @benjamn ! Unfortunately the error still occurs.

```
While processing files with ecmascript (for target web.browser):

/Users/phw/.meteor/packages/ecmascript/.0.7.0-beta.3.dg6tc++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/types.js:663:19:
did not recognize object of type "NumericLiteralTypeAnnotation"
...
```

Reproduction like above, just with `meteor create meteor-test --release 1.4.3.3-beta.3`

**Comment by abernix** [comment]
Reopening until we can take a look!

**Comment by abernix** [comment]
@benjamn Does this have something to do with some overlapping packages between the 1.4.3.x and 1.5 branches?  The output above seems to indicate `ecmascript@0.7.0-beta.3` is in use and the `1.4.3.3-beta.2` version bump [seems to show](https://github.com/meteor/meteor/commit/046b3f0e92bf327c40a260c8ec689c7884f3bb83#diff-adfc7aa5c6b9d8ed73279b06d8873386R3) that `0.7.0-beta.2` was the intended `ecmascript` version, but `meteor show ecmascript--show-all` is showing:

```sh
  0.7.0-beta.0               March 16th, 2017
  0.7.0-beta.1               March 16th, 2017
  0.7.0-beta.2               February 8th, 2017
  0.7.0-beta.3               February 9th, 2017
  0.7.0-beta.4               February 9th, 2017
  0.7.0-beta.5               February 10th, 2017
  0.7.0-beta.6               February 14th, 2017
  0.7.0-beta.7               February 17th, 2017
  0.7.0-beta.8               February 21st, 2017
  0.7.0-beta.9               March 5th, 2017
  0.7.0-beta.10              March 9th, 2017
  0.7.0-beta.11              March 14th, 2017
```

**Comment by benjamn** [comment]
@abernix that's entirely possible; I'll look into it today

**Comment by wursttheke** [comment]
Sorry for the dumb question: Can you guys tell me what a `NumericLiteralTypeAnnotation` actually is? I've never come across it and I didn't find any sources about what it does or how it works:

```javascript
var a : 1 = 1;
```

Thanks!

**Comment by benjamn** [comment]
Good question. The goal of any "type" is to define a set of legal values, and I believe the numeric literal type `:1` restricts the variable to exactly one value (i.e., 1). By itself, it's probably not that useful, but it might be useful when it's one of several options:
```js
var b = 3;
var a: 1 | 2 = b;
```
Try changing the value of `b` to fix the errors [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzAIzAF4wBmAbk1zCwC4wBGMAHzACZiDyg).

**Comment by wursttheke** [comment]
That makes perfect sense. Thanks for the explanation!

**Comment by benjamn** [comment]
Good news—@abernix was correct in his [comment](https://github.com/meteor/meteor/issues/8423#issuecomment-287332131) above. If you run `meteor update --release 1.4.3.3-beta.4` (`.4` not `.3`), I believe this issue should be resolved at last. Instead of closing the issue optimistically, I'll leave that to your discretion. 😉

**Comment by wursttheke** [comment]
Works perfectly now! 🎉

**Comment by EulerTourist** [comment]
Geezus, I was about to cry. Thank you for this post.
