### ISSUE TITLE
Add .delete function to Session api

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#8430]
As discussed in http://stackoverflow.com/questions/10743703/how-do-i-delete-or-remove-session-variables simply deleting a key from Session object will not result in a re-run of hooked dependencies.
Thus I propose to add a `Session.delete` function which will set corresponding key to `undefined`, rerunning all Tracker dependencies & then delete the underlying key from Session dictionary.

```js
Session.delete = (keyName)=>
	Session.set(keyName, undefined);
	delete Session.keys[keyName];
```

**Comment by stubailo** [comment]
> Session.set(keyName, undefined);

Does this not work by itself?

**Comment by avalanche1** [comment]
Yes, but it pollutes Session namespace wit obsolete keys

**Comment by lieuwex** [comment]
FWIW es6 `Map` [has this too](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete).

**Comment by hwillson** [comment]
Hi @avalanche1 - that SO post is out of date. In current versions of Meteor `Session` objects are  really just `ReactiveDict`'s (see [here](https://github.com/meteor/meteor/blob/b18b1e275559012bc76d81a07a17b40de8354ff6/packages/session/session.js#L1)). `ReactiveDict`'s already have an associated `delete` function, that is fully reactive. You can see the source [here](https://github.com/meteor/meteor/blob/b18b1e275559012bc76d81a07a17b40de8354ff6/packages/reactive-dict/reactive-dict.js#L184-L198), but here's a quick synopsis:

```js
delete: function(key) {
  var self = this;
  var didRemove = false;

  if (_.has(self.keys, key)) {
    var oldValue = self.keys[key];
    delete self.keys[key];
    changed(self.keyDeps[key]);
    if (self.keyValueDeps[key]) {
      changed(self.keyValueDeps[key][oldValue]);
      changed(self.keyValueDeps[key]['undefined']);
    }
    self.allDeps.changed();
    didRemove = true;
  }

  return didRemove;
},
```

So given the above, the `Session` API already supports a reactive `delete`. That being said, the [`Session` API docs](http://docs.meteor.com/api/session.html) don't mention this, so you might want to consider opening an issue in the [docs repo](https://github.com/meteor/docs) about this. For now though, I'll close this issue here. Thanks for posting this originally!
