### ISSUE TITLE
Symbolic links not working in /private

### ISSUE THREAD

**Issue by rogeriojlle** [meteor/meteor#8441]
Any file in Meteor private directory on fresh Meteor installs apps not working

ex: AppRoot/private/bin/x11vnc

in AppRoot/server/main.js
```
...
Assets.absoluteFilePath('bin/x11vnc')
...
```

the error is Error: Unknown asset: bin/x11vnc

https://docs.meteor.com/api/assets.html

Meteor version is 1.4.3.1

in my older instalations works

**Comment by klaussner** [comment]
Could you please provide a Git repo that shows the problem? I created a Meteor project exactly as you described and `Assets.absoluteFilePath` returns the correct path to the asset (*[project root]/.meteor/local/build/programs/server/assets/app/bin/x11vnc*).

**Comment by rogeriojlle** [comment]
Send the git will not solve, as I think I found the source of the bug, is this snippet:

[AppRoot] /server/main.js

```
Let Fs = Npm.require ('fs');
Let x11vncExecutavel = Assets.absoluteFilePath ('lalala.txt');
Fs.chmod (x11vncExecutable, '500', function (err) {
   If (err) {
     Throw 'x11vncExecutable failed:' + res;
   }
})
```

How to reproduce the bug:

Generate a new installation of Meteor normally,  with the --bare option but do not put any files in the private folder.

Put the above code in [AppRoot]/server/main.js

When running Meteor, the error happens for obvious reasons. (The fact file does not exist)

Copy 'lalala.txt' from another location, make sure it is already 500 (to simulate the assertion I made that in old installs, it works)

Under these conditions, the bug occurs

**Comment by klaussner** [comment]
There are typos in the code you posted. After changing `x11vncExecutavel` to `x11vncExecutable` and `If` to `if`, the code works as expected. The server starts and no error is shown in the console.

**Comment by rogeriojlle** [comment]
Sorry, my English is very weak, I missed those two words when I wrote the post in Google Translator.
Below is fixed:

```
let Fs = Npm.require ('fs');
let x11vncExecutavel = Assets.absoluteFilePath ('lalala.txt');
Fs.chmod (x11vncExecutavel, '500', function (err) {
   if (err) {
     throw 'x11vncExecutable failed:' + res;
   }
});
```

**Comment by rogeriojlle** [comment]
In fact, with this example the error does not happen, but see when cloning the git of "websockify" in the private folder, according to video.
It is something inside the folder "websockify / include" erasing only it the bug disappears. Although in the video I deleted the whole folder

https://github.com/novnc/websockify.git
https://youtu.be/5Ss7UFBnc_o

**Comment by klaussner** [comment]
It looks like Meteor can't handle symbolic links in the *private* directory. If you delete the symbolic link *tests/include* in the cloned "websockify" repository, the server starts without errors. That being said, it's probably better to include only the files you really need in your *private* directory, instead of the whole repository.

**Comment by hwillson** [comment]
Hi all - I've looked into this a bit further. It looks like Meteor can handle symbolic links in the `/private` directory properly, as long as the symbolic link points to a directory outside of the `/private` directory (I'm not sure why anyone would want to do this, but hey it works). A symbolic link in `/private` pointing to another directory in `/private` causes this problem (and the error message returned by Meteor is a bit misleading, since it just says it can't find the asset file, even though it exists).

Regardless, to help with troubleshooting (and a PR), I've created a focused repro demonstrating the issue here: https://github.com/hwillson/meteor-issue-8441

I'll also rename this issue to better represent the issue, and mark as `pull-requests-encouraged`. Thanks!

**Comment by hwillson** [comment]
Just to add - I see 2 possible ways of addressing this:

1. Adjust the error message to better explain what the issue is (that symbolic links can't be used within `/private`)

OR

2. Allow symbolic link use in `/private`

Since this issue appears to be just coming up now, and there really haven't been many changes to the `/private` directory support in quite some time, I have a feeling symbolic link support isn't a hot topic. Option 1 above should be the easiest to implement.

**Comment by hwillson** [comment]
For now we'll just document that symbolic links can't be used in an apps `/private` directory. See https://github.com/meteor/docs/issues/175.

**Comment by hyounesi** [comment]
@hwillson is this case resolved now?
