### ISSUE TITLE
Error: Can't find npm module mime-type/with-db

### ISSUE THREAD

**Issue by Nemra1** [meteor/meteor#8478]
im working in RC system and i need to know what i miss in this pkg
METEOR@1.4.2.6
![2017-03-13_002139](https://cloud.githubusercontent.com/assets/22897987/23836779/66bf9a82-0786-11e7-90f3-0a77620583f4.png)

**Comment by hwillson** [comment]
Hi @Nemra1 - sorry to hear you're having trouble. At a first glance this doesn't appear to be a Meteor issue however. Normally I would recommend opening an issue about this in the RocketChat repo, but it looks you have already (RocketChat/Rocket.Chat#6133). Since RocketChat has a dependency on `mime-type` and `mime-db`, have you verified those packages are installed (do you see them in `node_modules`)? Also - Meteor 1.4.2.6 is not a "recommended" version (meaning you should try to avoid using it). Have you tried using 1.4.2.7 or 1.4.3.1?

**Comment by Nemra1** [comment]
Rc not replay..and really ineed to figure out how ican fix that..

**Comment by hwillson** [comment]
Frustrating I know, but please see my previous questions:

> Since RocketChat has a dependency on mime-type and mime-db, have you verified those packages are installed (do you see them in node_modules)? Also - Meteor 1.4.2.6 is not a "recommended" version (meaning you should try to avoid using it). Have you tried using 1.4.2.7 or 1.4.3.1?

**Comment by hwillson** [comment]
We haven't heard back regarding the additionally requested info, so closing for now. Thanks!

**Comment by Nemra1** [comment]
sorry for late replay
im trying with METEOR@1.4.3.2
also is same thing no changes.. all my work is down now :(

**Comment by abernix** [comment]
Please take some time and review the request we have for you and make you have answered all the questions before responding.  You have provided almost no information on the steps you took leading up to this error.

Specifically, you have not answered:
> have you verified those packages are installed (do you see them in node_modules)?

Also, how are you starting your project?  Are you using:

   meteor npm start

Did you run?

    meteor npm install

**Comment by Nemra1** [comment]
im start with meteor npm install

**Comment by abernix** [comment]
What is the output of?:

    meteor npm ls

**Comment by Nemra1** [comment]
output 
![1](https://cloud.githubusercontent.com/assets/22897987/24452973/34784364-1486-11e7-9be0-e4638d95130f.jpg)
