### ISSUE TITLE
[Cordova] Serving static assets is very slow

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#8481]
Since the upgrade to Meteor 1.4.3, we have a problem with some of our included assets like images (placed in public/images and also within packages). They getting loaded very slowly, f.e. an flag icon takes about 10 seconds until it gets displayed. All assets are delivered via localhost, we've checked it by debug console. The problem didn't exist before the Cordova upgrade.

In debug mode, everything is working fine - but if I set production flag, assets are delivered slowly.

```
Request URL:http://localhost:12144/packages/jss_flag-icon/flags/4x3/de.svg
Request Method:GET
Status Code:200 OK (from cache)
``` 

Timing:

![bildschirmfoto 2017-03-14 um 00 21 24](https://cloud.githubusercontent.com/assets/7636313/23879254/352a979e-084c-11e7-8149-f9030b313264.png)

**Comment by abernix** [comment]
We will definitely need more information in order to help debug this.  For example:

* Is this only observable on a particular device?
* Is it observable in the simulator?
* Are the load times also slower if you attempt to download the same assets from the desktop?
* Are assets loaded slowly in _actual_ production (for example, a deployed bundle made with `meteor build ...`) or just when using the `--production` flag to the `meteor` tool (which is _not_ intended to be used in production)?

**Comment by dnish** [comment]
@abernix On normal desktop and mobile browsers everything is working fine. We've deployed our app via PM2, so we use the bundled Node application on our servers. I'm having the issue on 2 devices (LG G3 and OnePlus 3 with Android 7). 

The issue also occurs when running <code>meteor run android-device</code>. In our case, only the flag assets (svg files) seem to be delivered very slowly (like in the example above). We're using the Cordova Crosswalk plugin within our app.

**Comment by abernix** [comment]
@dnish Ok, thanks for the quick follow-up.

It sounds like you would agree that this is not a Meteor bug but rather a bug in Cordova or Crosswalk.  Have you search around in their respective issue trackers?  We'd be happy to bump a minor Cordova version to fix this (if they fix it upstream), but I'm not sure there is anything else we can do otherwise.

**Comment by dnish** [comment]
@abernix Just tested it without Crosswalk, all assets are loaded fine with Androids Chromium version. So I guess it's more a Crosswalk issue. We can close this. By the way Crosswalk is officially deprecated (https://crosswalk-project.org/blog/crosswalk-final-release.html). So I don't think that this will be fixed 😀.

**Comment by abernix** [comment]
Ahh, good to know, though that's probably frustrating for your own purposes.  Regardless, good to have reported here for posterity's sake. :smile:
