### ISSUE TITLE
Array in Collection

### ISSUE THREAD

**Issue by karma151** [meteor/meteor#8487]
Hello,

I just started a project with Meteor. I'm trying to make a relation between two entities and unfortunately, it's impossible with noSql database.

Take as example those 2 Collections : 

>Recipes: {name: "recipe_name", ingredients: [
{name: "first_ingredient"},
{name: "second_ingredient"},
.... ]}

> Ingredients : {name: "ingredient_name"}

So, as this [tutorial](https://www.meteor.com/tutorials/blaze/adding-user-accounts) is doing it, i would like to store the id but i would like to do a many to many relation.

My question is : How can i store an array of id in my Collection to do this ?

Another solution could be to do another Collection to store the both id like : 

>RecipeHasIngredient: {recipe_id: 5, ingredient_id: 8}

I'm not familiar with Meteor and i don't found the documentation to do that. May be a package could do that ?

Thanks for the future answer !

**Comment by abernix** [comment]
Hello,

Meteor Issues are reserved for reporting bugs with well-produced reproductions and design conversations for feature-requests.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

Luckily, there are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality and features – this is not the place for these sorts of questions, as noted in the text you cleared when submitting this issue.

In addition to checking out the [Todos Example App](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials), we highly recommend you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
