### ISSUE TITLE
Unable to run two meteor applications

### ISSUE THREAD

**Issue by devarashetty** [meteor/meteor#8524]
When I tried to run two applications (one is on default port 3000 ) and the other on (3002 ) . Application ran on 3000 but when other applications tries to run on 3002 it gives me following error.

` Update this project now with 'meteor update --patch 
Unexpected mongo exit code 100. Restarting.   
Unexpected mongo exit code 100. Restarting.   
Unexpected mongo exit code 100. Restarting.   
Can't start Mongo server.                     
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
events.js:141                                 
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3500
`

**Comment by abernix** [comment]
Could you try running it with ports which are further away from each other?  Your error message seems to indicate another port being used entirely (3500) than the ones you are stating in the issue.

Regardless, Meteor uses ports `N` (3000, if you're starting with the default), `N+1` (3001) and sometimes `N+2` (3002).  You haven't made it clear what the actual command is that you're running, but tests do use additional ports as well sometimes.

Please try using ports which are further away from each other, include more information about what version of Meteor and what platform you are using (Windows/Linux/Mac) and if this is a new problem, something you've just recently experienced for the first time and what you've tried already in order to fix it.

See [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for what is expected.

**Comment by devarashetty** [comment]
@abernix  I tried with 6000. Also when I killed all mongo and made `meteor reset` . I ran the latter mentioned application above first and then ran the first mentioned in above then it works.Thanks for early reply.

But if I do as above order then it shows that error. I know there can be multiple reasons why it can be happened. But I couldn't get it fixed when I tried earlier with different port (even after checking that port is free and port + 1 too )

**Comment by abernix** [comment]
What operating system are you using?

**Comment by devarashetty** [comment]
Linux

**Comment by hwillson** [comment]
Hi @devarashetty - it's a bit difficult to tell from your earlier response (https://github.com/meteor/meteor/issues/8524#issuecomment-289445529); how and on which ports exactly have you tried to run both apps at the same time? Can you post the specifics, something like:

- I started the first app with `meteor --port 3000`
- I started the second app with `meteor --port 3100`

**Comment by devarashetty** [comment]
I tried the first app at using `./run`  which is the shell script file and runs `meteor ` command.
I tried the second app using the command `meteor --port 6000`

**Comment by devarashetty** [comment]
@hwillson  I will try today and see if the error still comes and if it comes I wil attach the gif file .Thanks for responding so early.I appreciate it .

**Comment by hwillson** [comment]
Any luck with getting this resolved @devarashetty? It sounds like you're running 2 meteor instances, one with the default base port of 3000, the other with a base port of 6000. The mongo instances started for these apps should not conflict with each other, so if you're getting a conflict it's likely coming from somewhere else (maybe a previously hung mongo instance on a conflicting port?). Let us know if you're still having issues, and please pass along any additional troubleshooting details you can. Thanks!

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
