### ISSUE TITLE
Provide this.unblock in publish context

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#853]
**_3 Upvotes**_ Provide `this.unblock` in `Meteor.publish` context, same as it is provided in `Meteor.methods`.

**Comment by funkyeah** [comment]
I'm going to +1 this as well. My use case proactively subscribing to data the user is very likely to need at some point. Publications for subscriptions run at the template level should be to the minimum data needed and should block because it is required to render. 

The programmer often can anticipate what data the user will want or need and also knows what data should be kept around. In my opinion these cases often lead to wanting to subscribe to larger super-sets of data outside of the template context.

Because this data isn't immediately needed, its best if the DDP connections transporting the superset data doesn't block DDP connections transporting the data required to render a given template.

I've tried to explain an example of this in an [issue](https://github.com/meteorhacks/unblock/issues/4) file in arunodas this.unblock repo.

**Comment by dandv** [comment]
+1 for core support given the increasing usage of template-level subscriptions.

**Comment by dohomi** [comment]
+1 for this. I guess thinking in components way of template-level subscription this would be a great benefit.

**Comment by ShuyinBlack** [comment]
+1 switched my app's architecture to template-level subscriptions to improve performance. Using this.unblock() package from arunoda speeds up response times even more, very easily. So why not integrate into Meteor. : )

**Comment by tmeasday** [comment]
I just took a look at this again. @arunoda's package does exactly what we need here, in that if you stop (`UNSUB`) the publication before the `onStop()` handler is setup (i.e. before the publish body is completed), the `onStop()` handler runs anyway, immediately. I think this is pretty transparently exactly what you want. Sure there are some cases where you might be doing a lot of work:

```js
Meteor.publish(function() {
   this.unblock();
   const r1 = doSlowStepOne();
   // If the pub has been stopped at this point, it might be useful to abort here and not do the unnecessary step 2.
   const r2 = doSlowStepTwo(r1);
   this.added(r2);
   this.ready();
});
```

But you can do that by defining your `onStop()` early and carefully handling the various cases.

More than that, I think @mitar asked the pertinent question:

> After some more though: why are subscriptions even blocking to begin with? Is there really an use case where you would want it to block other subscriptions? Why it not unblocked default

I think this is true. I can't think of a case where I'd want a sub to block. As @glasser has said, the default use case (returning cursors) doesn't block. Why would you want it to? It makes sense for methods, not for pubs IMO.

@arunoda -- I propose you update your package (or publish a new one) that just unblocks pubs *always*. I also think we should get this in core.

**Comment by arunoda** [comment]
Yeah that's a good idea Tom. I will do a release today.

**Comment by tmeasday** [comment]
I think it would make the implementation simpler too :)

**Comment by arunoda** [comment]
Yeah. Literally, I unblock all publications :)

**Comment by mitar** [comment]
Blast from the past. :-)

**Comment by stubailo** [comment]
Wow, just discovered this. @arunoda you got a PR for this? Or have you done the aforementioned release?

**Comment by arunoda** [comment]
Didn't got a PR. I was planning to do it this weekend. But welcome any PR :)

**Comment by stubailo** [comment]
Just going grave digging for old issues to close :P

**Comment by arunoda** [comment]
ha ha. cool.

**Comment by Pushplaybang** [comment]
@arunoda  @stubailo  - this ever resolved?

**Comment by Nexus7** [comment]
Another check on this, was this ever going to make it into core? @stubailo looked like he was keen to integrate?

**Comment by Pushplaybang** [comment]
Would love to know if this is even a thing considering the move away from DDP overall as the data layer. I've got some long term projects that'll likely stay on DDP to avoid reimplementation on native clients etc, so still keen.

**Comment by abernix** [comment]
@Pushplaybang @Nexus7 The `pull-requests-encouraged` label (as already applied) is still in effect here.  It's something we'll consider, but would be looking for a contribution from the community to make it happen.  Is this something you'd be able to help revive?

**Comment by zimme** [comment]
I don't think it's a good idea to unblock all publications by default as we would probably get a lot of confused developers because of unexpected behaviours when subscribing using parameters from reactive variables. https://github.com/meteorhacks/unblock/issues/11#issuecomment-266263478.

The better option would probably be to have a `this.unblock()` and document this side effect so that people using it will be aware of this potential pitfall.

**Comment by zimme** [comment]
However, this might be an for this behaviour.
https://github.com/meteor/meteor/issues/2440#issue-41136962

Unblicking all publications might "solve" that problem.

**Comment by mitar** [comment]
For changing limits on an active subscription, I think a much better approach is to use my [subscription data](https://github.com/peerlibrary/meteor-subscription-data) package.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Provide%20this.unblock%20in%20publish%20context&body=Migrated%20from:%20meteor/meteor%23853) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
