### ISSUE TITLE
Unable to add nodets:mysql in Windows 10

### ISSUE THREAD

**Issue by AndyB37** [meteor/meteor#8552]
Meteor version: 1.4.3.2
OS: Windows 10.0.14393

When I try to run the following:
meteor add nodets:mysql

It goes through the Downloading and Extracting phases, but then it gets stuck at:
Loading nodets:mysql@2.8.6...

...and never finishes. I've left it overnight with no change. The same thing happens when trying to run the project.

I have been able to add nodets:mysql (I think it was a different version) just fine in the past in an earlier version of Meteor (1.3.4), but not after updating the project to the current release.

**Comment by hwillson** [comment]
Hi @AndyB37 - a few questions:

1. Do you see `nodets:mysql` in your apps `.meteor/packages` file?

2. Do you see a `./nodets_mysql/2.8.6` directory in your HOME `.meteor/packages` directory?

3. What happens if you try to add an earlier version of `nodets:mysql`? Something like: `meteor add nodets:mysql@=2.8.3`

**Comment by AndyB37** [comment]
> 1. Do you see nodets:mysql in your apps .meteor/packages file?
Yes

> 2. Do you see a ./nodets_mysql/2.8.6 directory in your HOME .meteor/packages directory?
Not exactly. There's a ./nodets_mysql/.build720956.2.8.6 directory, though. See #3 below for more on this...

> 3. What happens if you try to add an earlier version of nodets:mysql? Something like: meteor add nodets:mysql@=2.8.3
I tried going back one version at a time through 2.8.3 (same issue), 2.8.2 (same issue), until I got to 2.7.6. At that point, it loaded perfectly and created the ./nodets_mysql/2.7.6 directory next to that one that started with .build mentioned above.

And, now our app started just fine.

It appears maybe there's something that changed in version 2.8.2 of nodets:mysql that causes it to not load correctly in the latest version of Meteor. The app seems to run ok with 2.7.6, maybe we can leave it at that, for now, but if anybody knows of a way to get 2.8.6 loaded, I'd appreciate it.

**Comment by abernix** [comment]
Thanks for providing the details, @AndyB37.  I can confirm that this is happening for me as well with the same package, and only on Windows.

I should start by prefacing this with the fact that `nodets:mysql` is a relatively old package, last published in November 2015 with Meteor 1.2.1 and [no longer available on GitHub](https://github.com/nodets/meteor-mysql) for browsing.  It doesn't seem to be actively maintained and previous versions did appear to work fine.  I may suggest looking at another package for future development as the reliance on this unmaintained package could be risky.

I spent some time debugging this odd behavior and I know where the problem is happening, but don't have an acceptable permanent fix.  I do have an explanation and a work-around though, and a suggestion which would probably allow you to avoid this Atmosphere package entirely.

The problem is happening in the process when Meteor tries rebuilding the binary npm dependencies for the `meteor-mysql` npm package, a step which is necessary on some Node packages in order to make sure the correct link to native C extensions exist.  This is done within Meteor's [`runNpmCommand` logic](https://github.com/meteor/meteor/blob/release-1.5/tools/isobuild/meteor-npm.js#L789-L839) but the work itself is done by [`node-gyp`](https://github.com/nodejs/node-gyp), which is the Node.js tooling for recompilation of npms with native extensions.

For whatever reason, when Meteor calls out to `npm rebuild --rebuild-binary` from a Node.js [`execFile`](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) or [`spawn`](https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options), the process stalls (forever) as soon as `node-gyp` calls out to `Python.exe` (a necessary part of recompilation of Node.js packages with binary dependencies).

If you kill `Python.exe` in the Windows Task Manager, the process returns (with a failure, obviously), but then Meteor continues on its way – indicating that some combination of events is causing `Python.exe` to lock up.  Unfortunately, there is zero information provided from Python or `node-gyp` to allow us to recover gracefully from this.  And again, this doesn't happen on other packages with native C extensions, like `bcrypt` which also do the same call.

If the call is changed from an `execFile` to a `spawn` and we add `detached: true` and `shell: true` to the `options`, then everything does work, however a separate CMD.exe window pops up and does the execution, which is a bit of a jarring UX.  I'd be hesitate to apply this fix because of this lone package.

First, since you're using more recent versions of Node.js, this package doesn't actually provide much functionality from the Meteor standpoint as the Atmosphere package (`nodets:mysql`) is simply a npm wrapper for the [`meteor-mysql`](https://www.npmjs.com/package/meteor-mysql) npm package which exports the npm package on the global `Mysql` symbol in your project.  (The package author has removed it from GitHub, but you can see this by downloading the Atmosphere package source [here](https://warehouse.meteor.com/sources/t4vMgfLXgGkWfc7x2/1448449097000/7rJERe5nh5/nodets:mysql-2.8.6-source.tgz).

In new versions of Meteor, you can just:

    meteor npm install --save meteor-mysql

And then in your actual code, instead of using the `Mysql` symbol, you can just `import` it:

```js
import Mysql from `meteor-mysql`;
```

For me, this worked fine in Windows and the package compiled successfully.  Can you give this a shot and see how it goes for your application?

**Comment by hwillson** [comment]
We haven't heard back regarding the question asked in https://github.com/meteor/meteor/issues/8552#issuecomment-291075468, so I'll close this for now. Happy to re-open if anyone is still seeing this problem (with a recent version of Meteor and after following the steps broken out in https://github.com/meteor/meteor/issues/8552#issuecomment-291075468). Thanks!

**Comment by innoharshit** [comment]
@hwillson 
Hey Hugh,
I have the same issue as comment #8552 .
Meteor Version: 1.5.2.2
Windows 10
Should this issue be reopened in this case?
I followed the steps given above but, it just doesn't seem to work. 
Gonna try meteor-mysql now.

**Comment by hwillson** [comment]
> Gonna try meteor-mysql now.

@innoharshit Post back if `meteor-mysql` doesn't work, and if you can please test with Meteor 1.6.

**Comment by gauravarya1** [comment]
@hwillson 
Hey Hugh,
I am facing the same issue as #8552 , Using meteor 1.5.2.2 on Windows 10.
I will test it with Meteor 1.6 soon and post a reply here.

About `meteor-mysql` , `windows-build-tools` installation is taking forever to complete, will update once its done.

PS: Apologies, I posted as  @innoharshit by mistake. That's my colleague's account. Had to delete that comment as I would not have been able to follow that one.

**Comment by gauravarya1** [comment]
@hwillson I tried `meteor-mysql` with Meteor 1.6 and it installs without problems.
But `meteor-mysql` fails to install for My Meteor version i.e. 1.5.2.2, I cannot upgrade Meteor in my project right know. Is there any other workaround that you can think of?

Also, for now I am using `nodets:mysql` version 2.7.6 which installed on Meteor 1.5.2.2 without issues, but I don't want to keep using an outdated version.
