### ISSUE TITLE
NPM Package 'gm' keeps saying "missing modules"

### ISSUE THREAD

**Issue by talha-asad** [meteor/meteor#8570]
NPM package `gm` which is quite common, works flawlessly, but the server console keeps bugging for "missing" modules that are used by this module. I don't see a reason to save them to my Meteor's package.json or installing them for that matter. How can I silence these warnings?

They start with "meteor npm install --save spawn-sync" and even if I do install that module, though I don't use it, gm does. It asks for another and then another. Why is Meteor recommending to install these packages, these packages are not being linked by my app directly.

Additionally is there a way to tell Meteor to not include the gm package on the client, as it is of no use on the client anyway. Do we now have, that `.meteorignore` file implemented?

**Comment by hwillson** [comment]
Hi @talha-asad - if you're seeing `meteor npm install ...` messages, it usually means there is a weak/optional package dependency somewhere. In the case of the `meteor npm install --save spawn-sync` recommendation for example, this is because [`gm`](https://github.com/aheckmann/gm/blob/c6a6c5a18a65e9b9344955a5cf9d7417db25dff3/package.json#L45) has a direct dependency on `cross-spawn`, but `cross-spawn` has an [optional dependency on `spawn-sync`](https://github.com/IndigoUnited/node-cross-spawn/blob/a4b56721ad5ce0f32ebcdedb02660088b4ba67af/index.js#L26-L40). Since `spawn-sync` hasn't been installed by `gm`, Meteor is recommending that you install it yourself.

In some cases you can safely ignore these messages, but in other cases you cannot. It's not usually a good idea to silence these warnings however, since they usually do point to a dependency trail that should be considered.

All of that being said, which version of Meteor are you using? I'm using `gm` (with Meteor 1.4.3.2) and don't get asked to install `spawn-sync`.

Regarding how to tell Meteor to not include the `gm` package on the client, it won't unless you reference it on the client in your code. Double check your code to make sure you aren't accidentally referencing it in your client code.

`.meteorignore` support is being tracked in #6002.

Since your issue doesn't appear to represent a bug with Meteor itself, I'll close this issue for now. For Meteor use/support related questions, you'll likely have better luck reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). Thanks!

**Comment by talha-asad** [comment]
I'm also using it with Meteor 1.4.3.2, perhaps you forgot to Import it ?
