### ISSUE TITLE
Arrow functions in Meteor.publish throw Exception

### ISSUE THREAD

**Issue by jonaspm** [meteor/meteor#8580]
**Meteor version:** 1.4.3.2
**Platform:** Windows 10 x64
**Installed packages:**
- angular-templates
- accounts-password@1.3.4
- check@1.2.5
- email@1.1.18
- alanning:roles
- aldeed:simple-schema
- fabienb4:synced-scheduler
- jcbernack:reactive-aggregate

**npm dependencies:**

- "angular": "^1.6.2"
- "angular-meteor": "^1.3.11"
- "angular-meteor-auth": "^1.1.1"
- "angular-password": "^1.0.3"
- "angular-ui-bootstrap": "^2.5.0"
- "angular-ui-router": "^0.4.2"
- "babel-runtime": "^6.23.0"
- "bcrypt": "^1.0.2"
- "bootstrap": "^3.3.7"
- "chart.js": "^2.5.0"
- "chartjs-plugin-zoom": "^0.4.5"
- "font-awesome": "^4.7.0"
- "meteor-node-stubs": "~0.2.0"

**What I expect:** No errors & reactive subscription
**Actual result:**
```
I20170410-02:16:07.990(-6)? Exception from sub answers id jrtatLosfRtZk72xX TypeError: sub.ready is not a function
I20170410-02:16:07.992(-6)?     at ReactiveAggregate (packages\jcbernack_reactive-aggregate.js:71:7)
I20170410-02:16:07.993(-6)?     at [object Object]._handler (imports/api/answers/publish.js:14:5)
I20170410-02:16:07.994(-6)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170410-02:16:07.995(-6)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
I20170410-02:16:07.998(-6)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
I20170410-02:16:07.999(-6)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20170410-02:16:08.000(-6)?     at packages/ddp-server/livedata_server.js:559:43
```

**What works:**
```
13. Meteor.publish('answers', function(room_id) {
14.    ReactiveAggregate(this, Answers, [
```

**What doesn't work:**
```
13. Meteor.publish('answers', room_id => {
14.    ReactiveAggregate(this, Answers, [
```

**Comment by abernix** [comment]
That is because the function you are passing to `Meteor.publish` has its "`this`" context re-bound to an object that represents the Meteor publish handler.  That handler is expected to be available and by using an arrow function you are stripping it away since arrow functions do not bind their own `this`, nor do they allow re-binding `this` to something else.

[The examples in the docs](https://docs.meteor.com/api/pubsub.html#Meteor-publish) mention the importance of `this` and specifically use `function () {}` (as opposed to arrow functions), so this is working as expected.

**Comment by jonaspm** [comment]
Thank you for your didactic response @abernix
