### ISSUE TITLE
Can't depend on NPM module with ECMAScript code?

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8597]
Bug demonstration repository: https://github.com/edemaine/bug-npm-ecma

In trying to fix #8591, I'm trying to `NPM.depend` on a package (`nodemailer@4.0.1`) that has ES6 code in it.  Here is the relevant part of `package.js`:

```javascript
Package.onUse(function(api) {
  api.versionsFrom('1.4.3.2');
  api.use('ecmascript');
  api.mainModule('foo.js');
});

Npm.depends({nodemailer: "4.0.1"});
```

But when running Meteor, I get an error message suggesting that transpilation isn't happening:

```
W20170413-12:42:31.923(-4)? (STDERR) .../bug-npm-ecma/packages/foo/.npm/package/node_modules/nodemailer/lib/mailer/index.js:31
W20170413-12:42:31.924(-4)? (STDERR)             compile: [(...args) => this._convertDataImages(...args)],
W20170413-12:42:31.925(-4)? (STDERR)                        ^^^
W20170413-12:42:31.925(-4)? (STDERR)
W20170413-12:42:31.926(-4)? (STDERR) SyntaxError: Unexpected token ...
W20170413-12:42:31.927(-4)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20170413-12:42:31.928(-4)? (STDERR)     at Module._compile (module.js:373:25)
W20170413-12:42:31.929(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170413-12:42:31.929(-4)? (STDERR)     at Module.load (module.js:343:32)
W20170413-12:42:31.930(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170413-12:42:31.930(-4)? (STDERR)     at Module.require (module.js:353:17)
W20170413-12:42:31.930(-4)? (STDERR)     at require (internal/module.js:12:17)
W20170413-12:42:31.931(-4)? (STDERR)     at Object.<anonymous> (/tmp/edemaine/test/packages/foo/.npm/package/node_modules/nodemailer/lib/nodemailer.js:3:16)
W20170413-12:42:31.931(-4)? (STDERR)     at Module._compile (module.js:409:26)
W20170413-12:42:31.932(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
```

Is this supposed to work?  Or does Meteor require that NPM modules have already-transpiled code to be included in a Meteor package?  (I've also tried on master branch.)

Actually, the same behavior happens outside a package... `npm install --save nodemailer` and calling `require('nodemailer')` from a `.js` file causes `meteor` to output an error similar to above, despite having the `ecmascript` package installed in the Meteor project.

**Comment by klaussner** [comment]
Npm packages have to be compatible with the Node version that Meteor uses (currently 4.8.1) because they are not processed by Babel (to avoid unnecessary transpilation if they are already transpiled for older Node/browser versions before they are published). Unfortunately, Nodemailer requires Node v6. :disappointed:

> Requirements:
> Node.js v6+. That’s it.

https://nodemailer.com/about/#requirements

**Comment by abernix** [comment]
For performance reasons (and even with the `ecmascript` package) Meteor doesn't re-transpile external Node package dependencies, which are expected to be transpiled at publish time to the engines which they are intended to run on.

This is a bit frustrating since we're in need of this package right now, but `nodemailer` has made a conscious decision to not support Node 4 and has declared this in [its `package.json`](https://github.com/nodemailer/nodemailer/blob/master/package.json#L40) by setting [`engines`](https://docs.npmjs.com/files/package.json#engines) to `"node": ">=6.0.0"`.  Meteor 1.4 is using Node 4.x, so we'll have to find another way to fix the mail package.  

Closing, but I guess we'll need to brainstorm alternate solutions, possibly with the current `mailcomposer` implementation, but I suppose we could put the source within the package itself (at which point it would be transpiled by `ecmascript`) – This will no longer be necessary once Meteor 1.6 (#6923) releases with Node 6 – though that is very, very pre-release right now.

**Comment by edemaine** [comment]
Thanks -- I figured I was missing something, and didn't realize the Node version differences.

Would it be possible to transpile in this specific case, somehow automatically?  Perhaps the "right" place to do that would be my own NPM package...?

**Comment by abernix** [comment]
Since time is probably of the essence, publishing your own npm package may be the only suitable stop-gap here.

There are merely a few locations where the author has decided to use rest and spread (`...`) operators to gather argument overflow and there don't seem to be any other ECMAScript features used which aren't supported by Node 4.  It's certainly the authors prerogative (and there may be more here that I'm not considering) but it's certainly a shame that the entire package is not usable by [the Node 4 community](https://semaphoreci.com/blog/2016/10/12/nodejs-versions-used-in-commercial-projects-2016-edition.html) at the cost of that one (admittedly great!) ES feature.  It certainly wouldn't be as clean (and possibly less efficient as `slice`-ing `arguments` can cause some optimizations to fail in v8), but I believe a combination of `Array.from(arguments)` and `Array.prototype.slice`-ing would do the trick.

I'm not sure if the work necessary to make that happen would be welcomed by the `nodemailer` project but it might be worth asking or starting a discussion about whether they'd accept a pull-request.  Given the limited scope of problems, this isn't even a situation where they would need to Babel the entire project.

Thoughts?

**Comment by HoptimizeME** [comment]
Regarding #8591 when I was troubleshooting the other day I tried to add a `pool.quit` (IIRC) after the `DATA` has been sent.  It was greatly helping to close the connection after its use.  But .. my (somewhat important) problem was when I quitted the pool, no other email could be sent after that.

I was assuming we needed to warn `email.js` that it needs to re-create a new pool (`new SMTPConnection`) and I didn't have time to dig in the code further to understand how it could be done.

So, looking at the complexity to upgrade `nodemailer`, it might be simpler to only add "quit + reconnect" logic in our `email.js` code.

**Comment by edemaine** [comment]
I ended up writing my own package, [node4mailer](https://www.npmjs.com/package/node4mailer).  In addition to manually removing the use of spread (`...`) operators, I had to replace the use of `array.includes` with a polyfill.

The code is decidedly messier, so I'm not sure they'll want this upstream, but [I've asked just in case](https://github.com/nodemailer/nodemailer/issues/763).  Anyway, we just need this as a stop-gap until Meteor 1.6, so eventually we can switch to the original nodemailer.

**Comment by abernix** [comment]
@edemaine Thanks for asking, thanks for doing `node4mailer` and thanks for opening [the PR](https://github.com/meteor/meteor/pull/8605)!  Looks like they're going to stick with the newer constructs, so we'll just set our sights on Meteor 1.6 for this. ;)
