### ISSUE TITLE
Remove server only packages from the bundle

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor#8606]
I've been analysing bundles to see what is taking the space, and discovered what looks like a simple optimisation which will shave off a few bytes.

There are a number of packages (atmosphere ones) that end up having no client payload. But these still show up in the bundle, for example:
```
!function(){"undefined"==typeof Package&&(Package={}),Package["hot-code-push"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["angular2-compilers"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["barbatus:typescript"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["meteor-base"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["babel-compiler"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package.ecmascript={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["ddp-server"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["standard-minifier-css"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["standard-minifier-js"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["shell-server"]={}}();
!function(){"undefined"==typeof Package&&(Package={}),Package["angular2-compilers"]={}}();
```
Whilst they clearly don't take up that much space they appear to be unnecessary. One could use a 'marker' package and test for its existence - but this is unlikely and can easily be worked-around by adding something to the client side.

So it would be nice to have these automatically removed to save space, memory, and a tiny bit of cpu.

Affects Meteor 1.4.x and 1.5-beta.13.

**Comment by benjamn** [comment]
Hi @sdarnell! Thanks for this suggestion.

Here's an older issue where we removed unnecessary package imports from packages that contain no actual code, which helped reduce package size in a similar spirit: https://github.com/meteor/meteor/issues/7927

In this case, I'm afraid the remaining stub is indeed meaningful, because it allows client-side code to test whether a package is present in the app by checking if `Package[packageName]` is defined.

It's tempting to shorten this code a bit, but I think the minifier is already doing a reasonable job, and it's worth remembering that `gzip` compression can take advantage of the repetition to reduce the network size of this code significantly, by representing the repeated prefix `!function(){"undefined"==typeof Package&&(Package={}),Package["` with just a few bits.

**Comment by sdarnell** [comment]
I don't particularly disagree with any of the arguments put forward, but my feeling is that the package API should probably have a way of saying that the given package should not be exposed to the client side, and then empty packages of that form could be discarded.

For example, in my list earlier I pretty sure that all of them cannot meaningfully be of use on the client - except possibly hot-code-push (but not sure).
