### ISSUE TITLE
App broken on iOS 10.3+

### ISSUE THREAD

**Issue by renanccastro** [meteor/meteor#8622]
Our app is broken on iOS 10.3.1.
The error occurs when using the app in Safari from the url and from the Cordova App too.

When subscribing from the client the following error appears on the console:

```bash
WebSocket connection to 'wss://xxxxxxx.xxxx.xxxxx/sockjs/660/fl6kk4_1/websocket' failed: Failed to send WebSocket frame. 
```

With previous version of iOS it does not occur.

We think it is caused by the webkit bug that was reported [here](https://bugs.webkit.org/show_bug.cgi?id=170463) and we don't know of any workaround.

I know there is not much the meteor team can do from the webkit side, but I'm opening the issue to both track the bug and see if someone can workaround this issue.

**Comment by joaopiopedreira** [comment]
Same here!

**Comment by fabian-aramendi** [comment]
+1

**Comment by hwillson** [comment]
The webkit team has found and fixed the issue, but unfortunately we're now stuck waiting for the fix to be released with the next version of Safari. In the meantime, one of the following workarounds might help (but they definitely aren't ideal):

- Consider [disabling websockets](https://github.com/meteor/meteor/blob/devel/History.md#v064-2013-06-10) within your environment using `DISABLE_WEBSOCKETS=1`. This will force Meteor to use SockJS.
- Try to limit the amount of data you're sending over the wire. For example, consider sending less or smaller chunks of data, through your subscriptions/publications and/or Methods.

At this point however, there isn't much Meteor itself can do to help move things along. Since we're trying hard to get Meteor's open issue count down, we have to reserve issues here for bugs or feature requests against the Meteor platform itself. At this point it's probably best to continue this discussion in the Meteor Forums, within this issue thread: https://forums.meteor.com/t/failed-to-send-websocket-frame.

Thanks for posting this originally!

**Comment by gillbates** [comment]
waiting for the fix, we are experiencing the same issue ...

**Comment by macrozone** [comment]
@hwillson would it be possible that meteor itself falls back to long-polling if this error does occure or if meteor detects ios < 10.3.3 ?
