### ISSUE TITLE
mrt:jquery-ui@1.9.2 overrides and breaks bootstrap tooltips

### ISSUE THREAD

**Issue by UnforeseenSoftware** [meteor/meteor#8641]
Server: Meteor 1.4.4.1 on CentOS release 6.6 (Final). 
Client: Chrome 56.0.2924.87 on Windows 7

When using mrt:jquery-ui@1.8.16, bootstrap tooltips work fine (twbs:bootstrap@3.3.6).
But after upgrading to mrt:jquery-ui@1.9.2, bootstrap tooltips are overridden by jQuery tooltips.
I could not find a workaround except to downgrade back to mrt:jquery-ui@1.8.16. Stackoverflow workarounds cannot apply to Meteor applications (as it requires order of javascript loading and intermediate package code).

Can we please not include the jquery widgets in mrt:jquery-ui? Maybe make them modular and not part of core. (Or exclude tooltips; I'm unsure of other widget conflicts; I don't know how many widgets already existed in 1.8.16.)

This would be a blocking upgrade issue if minimum query-ui core increases with next monolith.
I'll go through the trouble of creating a GitHub repo if necessary, but this is simply about a namespace conflict.
```
<a href="#" data-toggle="tooltip" title="Hello Bootstrap">Hover over me</a>
$('[data-toggle="tooltip"]').tooltip();  // mrt:jquery-ui@1.9.2 overrides this for bootstrap.
```

**Comment by hwillson** [comment]
Hi @UnforeseenSoftware - the [mrt:jquery-ui](https://atmospherejs.com/mrt/jquery-ui) package is a 3rd party package, which means it was not developed as part of the Meteor platform, and it is in no way associated with this repo. GitHub issues here are reserved for either bugs with, or feature requests for, the Meteor platform itself. Since `mrt:jquery-ui` is no longer maintained, you should look into finding a replacement. Thanks!
