### ISSUE TITLE
react-meteor-data not passing props

### ISSUE THREAD

**Issue by Lindstrom1989** [meteor/meteor#8646]
Meteor version 1.4.4.1
react-meteor-data version 0.2.9

There seems to be a problem passing the props returned by the container object to the component.
An example:

```
// CollectionListContainer.jsx

export default createContainer((props) => {
  const subscription = Meteor.subscribe('listitems');
  const list = ListItems.find().fetch();
  return {
    list: list
  };
}, CollectionList);
```
```
// CollectionList.jsx

export default class CollectionList extends React.Component {
  constructor(props) {
    super(props)
  }

  componentWillReceiveProps(newProps) {
    console.log(newProps); // i get the right data!
    console.log(this.props); // empty array >_<
  }

  render() {
    return (
        <ul>
          {this.props.list.map(listItem => {
            <li>list item</li>
          })}
        </ul>
    );
  }
}
```

The new props are received but not updated.

**Comment by hwillson** [comment]
Hi @Lindstrom1989 - this is actually working as intended. To see what's happening, drop a `console.log` here:

```js
export default createContainer((props) => {
  const subscription = Meteor.subscribe('listitems');
  const list = ListItems.find().fetch();
  
  console.log(list);
  
  return {
    list: list
  };
}, CollectionList);
```

The first time the container runs, your subscription isn't ready yet, so `ListItems.find().fetch()` returns an empty array. This empty array is passed into the props of your `CollectionList`; this is why calling `console.log(this.props)` in your component shows `list` as being an empty array. When your subscription is ready however, the container re-runs your `ListItems.find().fetch()` call, returning the loaded array, which is then passed back into your already initialized component. As you've shown, this newly loaded array can then be seen in the `nextProps` of `componentWillReceiveProps`. 

The above being said, for questions like this you'll have much better luck reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). GitHub issues are reserved for bugs or feature requests with the Meteor platform itself. If you think you've uncovered a bug with `react-meteor-data` itself, please open an issue in the http://github.com/meteor/react-packages repo. Thanks!

**Comment by Lindstrom1989** [comment]
I understand that but the props are not being updated after the initial empty array, as in the props are always empty. I cant do props = newProps as thats mutation and I should be getting the updated props as props not just newProps. The async is not the problem here.

**Comment by hwillson** [comment]
> props are not being updated after the initial empty array

They should be - in your code sample, you listed the following:

```js
componentWillReceiveProps(newProps) {
  console.log(newProps); // i get the right data!
  console.log(this.props); // empty array >_<
}
```

When your component is first mounted (so when `list` is really just an empty array), `componentWillReceiveProps` is by-passed completely (since `componentWillReceiveProps` isn't called during mounting). So before `componentWillReceiveProps` is ever called, your component has a `list` prop of `[]`. Then when your subscription finishes loading and the updated `list` array is passed into your component, `newProps.list` has the loaded array, but when you call `console.log(this.props)`, `this.props.list` is still pointing to the empty array. Your props haven't been updated yet. Now, if you crack open a `meteor shell` for your app and call a `ListItems.insert({ name: 'some item' })`, watch  the console statements in your `componentWillReceiveProps`. You will now see the new props coming in, but your `console.log(this.props)` will have the previously loaded array now set and showing.

If you still think there is an issue here, please open a new issue in the https://github.com/meteor/react-packages repo, along with a reproduction that clearly demonstrates your issue. I will add however that if this was broken in anyway, we would know about it (there would be a very angry mob of Meteor + react dev's lining up outside the `react-packages` repo ... 🙂).

**Comment by Lindstrom1989** [comment]
I have made a sample repo to show the problem I am having https://github.com/Lindstrom1989/meteor-react-data-issue 
And also opened an issue in react-packages https://github.com/meteor/react-packages/issues/220

**Comment by Lindstrom1989** [comment]
Solved, was just a syntax error >_<, thanks.
