### ISSUE TITLE
Allow options on UglifyJS

### ISSUE THREAD

**Issue by PEM--** [meteor/meteor#8658]
* Meteor 1.4.4.1
* Package: minify-js
* Former behavior: Package author were able to setup options on Uglify.
* New behavior: Default options are now forced and there's no capability to setup new ones.
* Expected behavior: Allow package author to setup options on Uglify.

Code would change from:
```js
meteorJsMinify = function (source) {
  var result = {};
  uglify = uglify || Npm.require("uglify-js");

  try {
    result.code = uglify.minify(source, {
      fromString: true,
      compress: {
        drop_debugger: false,
        unused: false,
        dead_code: false
      }
    }).code;
```

into:
```js
meteorJsMinify = function (source, options) {
  var result = {};
  uglify = uglify || Npm.require("uglify-js");

  try {
    result.code = uglify.minify(source, options || {
      fromString: true,
      compress: {
        drop_debugger: false,
        unused: false,
        dead_code: false
      }
    }).code;
```

**Comment by hwillson** [comment]
Thanks for reporting this @PEM--; I see what you mean. We used to [allow uglify options to be passed in](https://github.com/meteor/meteor/blob/6c4507f004c53c44df668e20c8319510797566d8/packages/standard-minifier-js/plugin/minify-js.js#L123). I've marked this issue a `pull-requests-encouraged` as this is a regression, and I think the solution you've proposed makes sense. 

One thing to mention - the [`meteorJsMinify`](https://github.com/meteor/meteor/blob/0d10b33be632afbaa72bfe3a780854f850462b95/packages/minifier-js/minifier.js#L3) function can potentially call 2 different minifiers. It will first try `uglify` since it's faster, but if minification fails, it will then try [`babili`](https://github.com/babel/babili) (since it has better ES2015+ support). So passing a single `options` param into the `meteorJsMinify` function could be bit confusing, since those options could be intended for either one of the minifiers. Since we can't re-use the same options for both minifiers (since they have different options), in the future we'll probably want to allow options for either minifier to be passed in. Again though, since this issue is a regression, I think it's safe to say we'll review a PR that just allows `options` for uglify (to get the same previously allowed functionality back in place). Thanks!

**Comment by PEM--** [comment]
The PR #8665 should do the trick.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20options%20on%20UglifyJS&body=Migrated%20from:%20meteor/meteor%238658) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
