### ISSUE TITLE
Errors on  "meteor update", "meteor" on Ubuntu Server VM

### ISSUE THREAD

**Issue by Kshatra** [meteor/meteor#8681]
I'm trying to update Meteor 1.4.4_1 project to the newest 1.4.4_2 on Ubuntu 14.04 Server on VirtualBox VM. On "meteor update" and simple "meteor" i'm constantly getting 

```
/home/user/.meteor/packages/meteor-tool/.1.4.4_2.5g3s0q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
Error: failed to make temporary directory in /tmp at make (/tools/fs/files.js:642:3)
at Object.files.mkdtemp (/tools/fs/files.js:675:12)
```

Looking at mkdtemp in /tools/fs/files.js it seems that it's a nodejs problem- it simply refuses to create a directory at some point, although creating dozen of similar temp directories before the error actually occurs.

I've tried with no luck:
> chmod -R 777 /tmp
> changing tmp directory with export TMPDIR="~/tmp" like described in #6189 last post (note that it's also related with linux on VM)

I'm also getting wierd behavior with forever-lasting package extraction described in #7688

**Comment by abernix** [comment]
This is quite bizarre, though this doesn't occur to me on an Ubuntu 14.04 Server image so a detailed reproduction would be required.  Since 1.4.4.2 has been out for quite a long time (Meteor 1.5.1 is the most recent) and there haven't been and further reports of this, I'll assume that this is something isolated to your environment.  Happy to reopen, but additional reproduction information and instructions would be necessary.  Thanks!
