### ISSUE TITLE
Can’t send emails from my app with email@1.2.1

### ISSUE THREAD

**Issue by mgscreativa** [meteor/meteor#8696]
Hi! I have Meteor 1.4.4.1 running in my dev machine Ubuntu 16.04 (but the error is the same on heroku deploy) and enabled MAIL_URL as env var.

I had a really bad time with this. After correct MAIL_URL setup, I can run an email example from here https://github.com/themeteorchef/using-the-email-package, this is a email demo with email@1.1.18 that works just fine. 

So after implemented the very same in my project, it didn't send any emails, so I started to check differences and the only one is that my project installed email@1.2.1 and the demo runs on email@1.1.18.

Here is the very same demo using email@1.2.1 that fails https://github.com/mgscreativa/using-the-email-package. In this code, If I downgrade email to email@1.2.0 I can send emails just fine!!! maybe this is a regression of latest PR #8605 https://github.com/meteor/meteor/pull/8605/files#diff-8b2faad35ab5c720c37a39b84135fe14 (by the way, such a huge change for releasing a simple patch release, it should be named 1.3.0!)

My  MAIL_URL uses a google apps account like this MAIL_URL = 'smtp://user%40domain.com:Password_With_%40_Character@smtp.gmail.com:465';

Here is a complete forum post with more info if you need https://forums.meteor.com/t/bug-cant-send-emails-from-my-app-with-email-1-2-1/36505

**Comment by edemaine** [comment]
@mgscreativa Change `smtp:` to `smtps:` in your MAIL_URL and email@1.2.1 should work.

I don't recommend using email@1.2.0 as the mail server will eventually timeout and cause email to crash.

**Comment by mgscreativa** [comment]
Ups, that did the trick...

Can someone update the docs to point that?

Thank you!

**Comment by mgscreativa** [comment]
Just thinking...why no error messaje is thrown? because the app never finished running email.send if I try to send with this  MAIL_URL = 'smtp://user%40domain.com:Password_With_%40_Character@smtp.gmail.com:465';

I think that mail.send should trow an error advising to use smtps when required...

something like: **You are trying to connect port 465 over smtp, try to change MAIL_URL to smpts**

What you think?

PS: please add that error message, I spent all my Saturday trying to figure out the issue, but no error messages sent!

**Comment by edemaine** [comment]
I worry that an unconditional warning would be annoying if someone legitimately wanted to use SMTP on port 465... but I could go either way.  @abernix, care to weigh in?  In either case, I can PR a note about this in the documentation.

I agree that the infinite delay isn't the greatest output in case of error.  I see that nodemailer has [three different timeouts](https://nodemailer.com/smtp/#connection-options) which default to infinity.  Perhaps Meteor's email package should default them to more reasonable values, like 1 minute?  @mgscreativa could you tell me what happens when you try with MAIL_URL set to `smtp://user%40domain.com:Password_With_%40_Character@smtp.gmail.com:465?greetingTimeout=5000`?  Hoping for an error message after 5 seconds.

**Comment by mgscreativa** [comment]
Hi! if I try to send emails with my demo repo here https://github.com/mgscreativa/using-the-email-package I hope to get **Message sent!** in server console log...but I only get **Sending email...**

Tou can test taht on https://github.com/mgscreativa/using-the-email-package/blob/master/imports/api/messages/methods.js

**Comment by abernix** [comment]
@edemaine Thanks for staying on top of, and chiming in on, these issues.

We can certainly improve the developer experience here by providing a warning, but as stated above, the warning might be inappropriate.  Port numbers don't dictate what security is meant to be used.  This is what the scheme (`https://`, `http://`, `ftp://`, etc.) is responsible for.  This enables the using `https://` on port 4443, or any port including port 80, instead of the "standard" SSL port, 443.

`smtp://` with port 465 and the intention of using TLS/SSL is simply incorrect. Of course that intention must be the desired behavior when using Gmail since they [don't support non-SSL/TLS connections](https://support.google.com/mail/answer/7104828?hl=en&visit_id=1-636304569155951617-2331230301&rd=3).  Using `smtp://` with any Gmail SMTP server is always incorrect, and has been with `email` versions prior to 1.2.0 as well.

@mgscreativa I believe if you were using `smtp://` and port 587 (instead of 465) this _might_ work properly since Gmail supports `STARTTLS` on port 587 (but they do not support it on 465).

All that said, I don't think it would be too painful if a single warning (per run) was printed to the console when a developer used `smtp://` in combination with one of these typically-secure ports.  If anything, we should add the warning and see if there is any push-back on it.  Generally speaking, if you're using port 465 or 587, you probably want SSL or TLS and this certainly isn't the first confusion we've run into on this.

We should probably update the docs too.

@edemaine I'm not sure about the timeout at the moment, but should we add the warning and see if we get complaints about it from those who truly desire non-secure usage of typically-secure ports?  I think it will probably solve more problems than it would cause.

**Comment by mgscreativa** [comment]
@abernix seems fair to me, just a warning would saved me hours of pain! jajaja

**Comment by mgscreativa** [comment]
Maybe something like "You are using smtp over port 465/587, should you update MAIL_URL to use smtps?"

**Comment by edemaine** [comment]
@abernix Recall that `email@1.1.18` automatically converted port 465 URLs into using `smtps` protocol.  So the warning *shouldn't* affect people except those that were negatively affected by the issue and who could use it (which is 2 or 3 so far on the issue tracker).

I'm not sure that we should warn about port 587, though, because the old code didn't do anything in that case, so if someone's MAIL_URL worked before, it should still.

**Comment by abernix** [comment]
@edemaine Ok, then I think it's safe to add the warning then, once per startup.  If you're not able to look at adding that, I can take a look at it in the next few days (or a PR from anyone involved here would be welcome!)

**Comment by mgscreativa** [comment]
Don't look at me, not confident enough to do such change! jeje

**Comment by edemaine** [comment]
Done: #8707

**Comment by abernix** [comment]
This was addressed with #8707 and released with `email@1.2.3`.

Thanks, @edemaine.
