### ISSUE TITLE
Dynamic import(...) should still work regardless of IndexedDB errors

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#8697]
As reported in [this comment](https://github.com/meteor/meteor/issues/8685#issuecomment-300939963), in Firefox, calling `indexedDB.open` in a private browsing window results in an uncaught global exception, since Firefox disables IndexedDB when browsing privately. This seems like a reasonable choice, though I wish Firefox made the global `indexedDB` variable undefined, rather than defining it uselessly, or simply threw away any new IndexedDB data when the private browsing session ended.

In any case, since we use IndexedDB for caching dynamic modules, Firefox users won't benefit from that caching during private browsing, which is totally acceptable and maybe even desirable. However, we should definitely handle that case more defensively, so that dynamic modules can still be fetched without the cache.

Thanks to @vladejs for noticing this problem!

**Comment by benjamn** [comment]
Relevant Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=781982
Relevant `localForage` issue: https://github.com/localForage/localForage/issues/195

**Comment by benjamn** [comment]
Steps to reproduce:
```sh
cd meteor
git checkout release-1.5
cd tools/tests/apps/dynamic-import
meteor npm install
NODE_ENV=production meteor test --full-app --driver-package dispatch:mocha-browser --production
```
and then open [`localhost:3000`](http://localhost:3000) in the browser.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.5-rc.3` in your application. Please feel free to reopen if you discover otherwise.

**Comment by dr-dimitru** [comment]
I'm hitting 
```
Uncaught (in promise) DOMException: Entry was not found.
```
Error in [Maxthon Browser on Windows](http://www.maxthon.com/) (*yes, I know nobody using it, except one of our clients*). This is definitely `indexedDB` issue as older Meteor@1.4.* projects without dynamic imports is working well.

Should I start separate ticket?

**Comment by abernix** [comment]
@dr-dimitru Heh. Yes, please open a new issue for it. I'm assuming it's occurring in the `.put` [in this code](https://github.com/meteor/meteor/blob/b010e205bcbfedbd91a27baab2b985d97482ef83/packages/dynamic-import/cache.js#L178-L185), perhaps due to some bizarre size limit (`0`?)

> Time to upgrade your browser to an information assistant.

Maybe we should all start using "information assistants" instead of "browsers"? 🤔:wink:

**Comment by dr-dimitru** [comment]
> perhaps due to some bizarre size limit (0?)

Might be, might be... Browser is bizarre itself, for example `window` has `URL`, `Worker`, `Blob` although all of those constructors is accessible, each throws an exception on usage attempt.

> Maybe we should all start using "information assistants" instead of "browsers"? 🤔😉

I'll vote for Lynx

> Yes, please open a new issue for it.

I will, later today. Thank you on this.

**Comment by dr-dimitru** [comment]
Hi @abernix ,

This was a false alert, perhaps Maxthon have some issues with exceptions, so it pointed me to the wrong piece of code. Turns out issue was in `Promise` as it isn't supported in Maxthon and polyfill is used, which is detected as `[object Function]` instead of `[object Promise]`.

Took me a 4 days to make Meteor work in Maxthon and IE >= 9.

Btw what is the official Meteor support for IE?
