### ISSUE TITLE
Reference error: undefined collection when starting meteor app

### ISSUE THREAD

**Issue by brayoh** [meteor/meteor#8705]
Ive been stuck with the following error since yesterday after setting up Jest unit Testing in my meteor app, ive tried stack overflow solutions and most suggest the problem is the folder structure but i tried changing the structure and still no success
W20170518-18:35:58.696(3)? (STDERR)                                             throw(ex);
W20170518-18:35:58.696(3)? (STDERR)                                             ^
W20170518-18:35:58.697(3)? (STDERR) 
W20170518-18:35:58.697(3)? (STDERR) ReferenceError: Teams is not defined
W20170518-18:35:58.698(3)? (STDERR)     at meteorInstall.lib.collections.js (lib/collections.js:1:1)
W20170518-18:35:58.698(3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170518-18:35:58.698(3)? (STDERR)     at require (packages/modules-runtime.js:120:16)

**Comment by hwillson** [comment]
Sorry to hear you're having trouble @brayoh! Issues here are reserved for either Meteor bugs and/or feature requests however. If you feel like you're encountering a bug with Meteor, please provide a small runnable reproduction showing your issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info). Since you haven't had much luck on SO, you might want to consider trying the [Meteor forums](https://forums.meteor.com). Closing for now - thanks!
