### ISSUE TITLE
1.4.4.2 - Minification causes error at runtime in production

### ISSUE THREAD

**Issue by dagatsoin** [meteor/meteor#8706]
Meteor 1.4.4.2
Deps: React, Mapbox GL
Repo for repro: https://github.com/dagatsoin/bug-meteor-minification

I don't have any error during development but as soon as the app is minified I got a runtime error: 
`blob:http://localhost:3000/9a38abb6-9fec-43b8-99fc-4e1674b58539:3 Uncaught ReferenceError: e is not defined`
This seems to be a variable of the Mapbox package which is minified twice.

- I have this error both on Galaxy and my local machine. 
- I don't have this error with Meteor 1.4.2.x

**Comment by hwillson** [comment]
Hi @dagatsoin - it looks like there are a few issues with your repro. I'll assume the `wizar-hierarchy` package isn't needed (since it's referenced locally in your `package.json`), but after removing that package, `meteor npm install`ing, and starting your app, I'm seeing a `Error: Input data is not a valid GeoJSON object.`. Is this intended? I just want to make sure the repro is working the way you planned, before debugging further. Thanks!

**Comment by dagatsoin** [comment]
Sorry, did not double check my repro! You can update it.
Note that you will need the command line tool for compiling some Mapbox dependencies at `npm install`

**Comment by armadilio3** [comment]
I also have this issue on Meteor 1.4.2.x. @dagatsoin have you had any luck in finding a solution?

**Comment by dagatsoin** [comment]
I just removed the js-minimifier package as a workaround 🙁

**Comment by armadilio3** [comment]
@dagatsoin seems extremely drastic for such a weird issue 😀. But it seems like I will have to do the same thing. I hoped it won't come to this. But I am still looking into the possibility to just use webpack and hopefully forget this issue.

**Comment by hwillson** [comment]
Thanks for updating your repro @dagatsoin - I've taken a closer look. Based on the environment detection code mapbox is using, uglify is stripping code that's needed at runtime. This issue is being tracked here: mapbox/mapbox-gl-js#4359 (see https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888 for the detailed explanation of what's happening - it outlines the issue from the context of webpack, but the issue is still the same with Meteor).

@armadilio3 Webpack will have the same issue unfortunately (if using uglify that is).

Unfortunately there isn't much that can be done in core to help address this issue, other than find a different minifier that doesn't have this problem. I tested your repro with Meteor's fallback minifier [babili](https://github.com/babel/babili), but ran into other issues. You might want to try a [3rd party minifier](https://atmospherejs.com/?q=minifier) to see if any of them can handle mapbox properly.

Uglify use is pretty common, so hopefully mapbox will consider rolling out a patch for this (even though they aren't really doing anything wrong). For now though, there isn't much else that can be done on the Meteor side. Thanks for reporting this!

**Comment by joedeveloper** [comment]
I am confused as to why this is closed - you state that the current default js minifier used in Meteor breaks code that it shouldn't.

If Mapbox can run into this issue then so could code from any other source, breaking Meteor and developer hearts - shouldn't _you_ ( and I guess here I mean *we* ) be looking for an alternative to a minifier with a now known bug?

**Comment by joedeveloper** [comment]
@hwillson As a forward looking capability that could address the issue, is it possible to pass options to the standard-minifier-js ?

**Comment by dagatsoin** [comment]
I agree. The break happened on a change on Meteor. Not on mapbox. This should be left opened.

**Comment by hwillson** [comment]
Thanks for the input @joedeveloper @dagatsoin.

>I am confused as to why this is closed - you state that the current default js minifier used in Meteor breaks code that it shouldn't.

Yes, uglify is breaking mapbox, and Meteor uses uglify. Uglify is far from perfect and issues when using it with Meteor are scattered throughout [this repo's issue history](https://github.com/meteor/meteor/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20uglify). There have been several discussions/attempts made to replace uglify with something else, but in the end (for a variety of reasons) uglify is still best minifier available at the moment (bugs and all). To help work around some of uglify's issues, Meteor automatically falls back on using [babili](https://github.com/babel/babili), but babili has its own set of problems as well (mostly its performance - it's quite slow). That being said, PR https://github.com/meteor/meteor/pull/8698 was opened to consider upgrading uglify to its latest version, or consider alternatives. Please feel free to join in the discussion there.

> As a forward looking capability that could address the issue, is it possible to pass options to the standard-minifier-js ?

There was an open issue to track this - see https://github.com/meteor/meteor/pull/8698. That issue was recently closed as part of the `meteor/meteor-feature-requests` transition, but please feel free to click on the migrate link in https://github.com/meteor/meteor/issues/8658#issuecomment-306661907, and have it restored in the new repo.

> I agree. The break happened on a change on Meteor. Not on mapbox. This should be left opened.

The break is happening because of decisions made by mapbox, that don't play nicely with ulgify (which Meteor uses). We don't control uglify or mapbox, so we can either wait for them to fix this issue, or find a work around. Possible workarounds include finding/using a new minifier or allowing the existing minifiers to be configured differently. Both of these possibilities are already being tracked in other issues (well, assuming someone champions issue https://github.com/meteor/meteor/pull/8698), so I'm not sure if there is much value to leaving this issue open.

All of that being said, I'm easily persuaded if you guys still think there is value in leaving this open (after reading the above). Thanks!

**Comment by joedeveloper** [comment]
FYI - in case anyone just wants this working for them - I have created [unomi:standard-minifier-js](https://github.com/joedeveloper/standard-minifier-js), which has comparisons: false set for uglify - this makes mapbox work for me.

Be aware that the unomi:standard-minifier-js  is forked from [abernix:standard-minifier-js](https://github.com/abernix/standard-minifier-js) - because I was pressed for time and didn't see a good way to just get the 1.5 standard-minifier-js package to work with.

So far I have seen no issues with Meteor 1.5

**Comment by nicooprat** [comment]
@joedeveloper Many thanks, I can confirm it's working with Meteor 1.5.1 & Mapbox-gl 0.38.0.

**Comment by systemlevel** [comment]
@joedeveloper I get an error when trying to add unomi:standard-minifier-js to my project.  I am having the same issue with the mapbox-gl library not minifying correctly.

```
   error: Conflict: Constraint babel-compiler@6.18.1 is not satisfied by babel-compiler 7.1.1.
   Constraints on package "babel-compiler":
   * babel-compiler@~7.1.1 <- top level
   * babel-compiler@7.1.0 <- ecmascript 0.11.1
   * babel-compiler@6.18.1 <- unomi:minifier-js 2.0.0 <- unomi:standard-minifier-js 2.0.3
```

I'm using the most recent meteor 1.7.0.3 and the most recent mapbox-gl 0.46.0-beta.1
