### ISSUE TITLE
meteor update --all-packages doesn't update all packages

### ISSUE THREAD

**Issue by Deozaan** [meteor/meteor#8721]
After updating Meteor to the latest version with `meteor update` I was informed that there was an update for a package and that I should run `meteor update --all-packages` to update it. That seemed like a good idea, so I tried it. This is what happened:

```
> meteor update --all-packages
This project is already at Meteor 1.4.4.3, the latest release.
Your top-level dependencies are at their latest compatible versions.

Newer versions of the following indirect dependencies are available:
 * ecmascript-runtime 0.3.15 (0.4.0 is available)
To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
```

In my opinion, running `meteor update --all-packages` should update *all packages*.

Or at the very least, that command should be renamed to something that accurately describes what it does. Perhaps something such as `--most-packages` or `--some-packages` or `--maybe-if-you-feel-like-updating-a-package-i-guess-like-whatever-man-you-do-you` would be more accurate. Additionally, the console shouldn't tell me that I can use a command to update packages when it won't update those packages after all.

**Comment by dr-dimitru** [comment]
Same here, always end up with (since `v1.4.4.2`, including `1.4.4.3`):
```
This project is already at Meteor 1.4.4.3, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest version available:
 * accounts-base 1.2.17 (1.3.0 is available)  
```

**Comment by benjamn** [comment]
As of Meteor 1.4.3, core packages like `ecmascript-runtime` and `accounts-base` are constrained to the same minor version (e.g., `0.3.x` or `1.2.x`) that they had when the current release was published. See [further explanation in the `History.md` for Meteor 1.4.3](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13).

Just because a newer version of a package has been published doesn't mean you should be able to update to it. Between Meteor 1.4 and Meteor 1.4.2.7 there were no constraints on core package versions, and it was nearly impossible to make any guarantees about the consistency of core packages. Before Meteor 1.4, core package versions were constrained to exactly one version, which was too restrictive. The current system is a practical middle-ground, because it lets you install new package versions with non-breaking changes, without updating your Meteor release.

In this case, if you really want the newest version of those packages, you'll have to wait for Meteor 1.5, or clone the package locally into your app's `packages` directory. If you resent being told true facts about a future you will soon be able to hold in your hands, I would suggest you channel that frustration into anticipation of Meteor 1.5!

**Comment by Deozaan** [comment]
I don't understand what you mean by that last sentence. But I get the feeling it was a throwaway comment that doesn't really matter.

If I have to clone the latest version of the package into my app's `packages` directory then the instructions should tell me that's what I have to do.

It's bad UX to have a message that seemingly recommends I update to the latest packages, supposedly tells me how to update to the latest packages, but following those instructions doesn't actually work and no indication is given as to why. It just leads people on a wild goose chase trying to accomplish something that you're saying goes against the "best practices" for Meteor.

We all could have saved ourselves a bit of time today if Meteor didn't even notify me about updates it wasn't willing to allow me to update to.

**Comment by benjamn** [comment]
> If I have to clone the latest version of the package into my app's `packages` directory then the instructions should tell me that's what I have to do.

No, that's not what I'm recommending, unless you can identify a good reason to force the newer version. I suspect you haven't done that; you're just optimistic about trying out the latest version, despite the risks. My official recommendation is that you be patient, and trust that `meteor update --all-packages` is giving you the most recent versions of core packages that you can safely use, even if there happen to be newer versions that you can't use yet.

**Comment by benjamn** [comment]
By the way, if you want to help test Meteor 1.5 before it's released, you can run `meteor update --release 1.5-beta.9` in your application directory. After that, `meteor update --all-packages` should give you all the latest versions.

**Comment by Deozaan** [comment]
> No, that's not what I'm recommending, unless you can identify a good reason to force the newer version. I suspect you haven't done that; you're just optimistic about trying out the latest version, despite the risks. My official recommendation is that you be patient, and trust that meteor update --all-packages is giving you the most recent versions of core packages that you can safely use, even if there happen to be newer versions that you can't use yet.

That's exactly my point.

I actually don't care about the latest version of this package. But the message in the console leads me to believe that Meteor is recommending I update to the latest version of the packages. You're telling me that is actually not recommended because it could be dangerous. If I had known that I wouldn't have wasted my time looking for a solution to the problem and writing a bug report in the issue tracker.

But how is anyone supposed to know that?

I'm saying the message in the console shouldn't recommend that I do something dangerous, seemingly tell me how to do that dangerous thing, not actually do anything when following those instructions, but not tell me why it's not doing anything.

> By the way, if you want to help test Meteor 1.5 before it's released, you can run meteor update --release 1.5-beta.9 in your application directory. After that, meteor update --all-packages should give you all the latest versions.

Are you saying that in 1.5 `--all-packages` will always update all packages to the latest version? Or will they be constrained to the same minor version similarly to how they are now?

If it's the former, then good. Problem solved. If it's the latter, then the UX is bad and the console message(s) should be changed so it doesn't make people waste their time trying to do things Meteor doesn't actually want (or allow) them to do.

To reiterate, this is currently what is happening in Meteor:

1.  Tells me about unsafe updates (without telling me they are unsafe!).
1.  Tells me how to install the unsafe updates.
1.  When given the command to install the unsafe updates, ignores it without saying why.
1.  Goto 1.

Do you see how stupidly pointless that is?

**Comment by benjamn** [comment]
Meteor 1.5 will constrain the minor versions of core packages, just as other Meteor releases have done since 1.4.3. However, those minor versions will (in some cases) be more recent than the versions that were current when previous Meteor releases were published. Note that "current" versions are dictated by the state of the `meteor/packages` directory, not just the latest published versions at the time the release was published (I mention this because 1.4.4.3 was published very recently, but was branched off `master` rather than `release-1.5`).

For what it's worth, here's how I read the console messages that you found confusing:
```sh
> meteor update --all-packages
This project is already at Meteor 1.4.4.3, the latest release.
Your top-level dependencies are at their latest compatible versions.
```
This is authoritative and should be trusted at face value.

```sh
Newer versions of the following indirect dependencies are available:
 * ecmascript-runtime 0.3.15 (0.4.0 is available)
To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
```
Both of these sentences are true, but the recommendation may be moot if `meteor update ecmascript-runtime` refuses to change the version of `ecmascript-runtime`, because the new version fails to satisfy constraints.

Perhaps a slight change of wording would clear everything up! Please feel free to submit a pull request if you can think of a better way of conveying this guidance.

**Comment by Deozaan** [comment]
Thanks for taking the time to explain things to me.

**Comment by mhlmhl** [comment]
I ran into the same problem, and was confused by the same output from meteor update. I wish the output was clearer.

I wanted version 2.0 of the "react-meteor-data" package, but already had version 0.2.16.  I did "meteor update" and assumed it gave me the latest-and-greatest, without looking at the output.  I had no idea that it doesn't do that.  Then I spent quite awhile figuring out why my dependencies on the new "useTracker" feature of react-meteor-data did not work.  Then I spent more time trying multiple variations of "meteor update" trying to get it to update that package. Eventually, I explicitly removed and then added the package and I got what I wanted.

Overall, quite frustrating.

**Comment by mhlmhl** [comment]
I've run into this issue several times, where it says "... just run `meteor update --all-packages`" so I do that and then it just repeats the same message again. Each time, I've wasted my time googling the issue.  I think the message should be suppressed.  If the packages are up-to-date with respect to the installed version of Meteor, then I already have the current packages and I should not be told about updating them.

Strong recommendation: only generate this message for those packages that can be updated, omitting any packages that would be updated via the --update-all option.
