### ISSUE TITLE
Email: Content-Transfer-Encoding: quoted-printable can't be overriden

### ISSUE THREAD

**Issue by marxo** [meteor/meteor#8723]
Hi, I'm using Meteor 1.4.4.2 and when sending emails using Email.send, my e-mails get encoded automatically with `Content-Transfer-Encoding: quoted-printable`.

The issue with this is that I'm trying to integrate Gmail actions which are not working because the HTML is encoded afterwards. The email view itself renders fine, however, the underlying code is encoded, and Google's engine is unable to process data that make action buttons appear. The solution would be to force encoding to `7bit`, however, if I try and set `headers: { 'Content-Transfer-Encoding': '7bit'}` I end up getting both and the e-mails are messed up.

**Is there a possibility to override or disable encoding that I'm not aware of?** If I'm right, this practically means we're not able to send a single e-mail that will have Gmail actions working. Things are even harder given that we build on top of the Email package. As an example: We use `lookback:emails`, which is adding a level of complexity to this issue.

The solution would be to enable changing the `qp` setting to something else or disabling encoding, where HTML could get parsed for schema.org data.

**Comment by hwillson** [comment]
Instead of setting `Content-Transfer-Encoding` in the `headers` object, have you tried setting it directly using the `textEncoding` email field? See the [mailcomposer](https://github.com/nodemailer/mailcomposer/blob/v4.0.1/README.md#e-mail-message-fields) docs for more info.

Since this doesn't appear to be an issue with Meteor, I'll close it for now. If you still think there is a bug here somewhere, please post back and I'll re-open. Thanks!
