### ISSUE TITLE
Dynamically import atmosphere packages

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#8745]
Can we dynamically import meteor packages yet?
e.g. `import('meteor/froala:editor');`

When I do this, the package is still pre-loaded in the minified bundle.

**Comment by benjamn** [comment]
Today, most Meteor packages perform some initialization on the client and/or server at application startup time, which unfortunately means their code needs to be included in the initial bundle. You can still import the package using the dynamic syntax, but the code won't actually be fetched from the server (as you saw).

However, if you are writing your own package (or modifying someone else's package locally), then you have options:

* Any modules contained by a package but not explicitly added via `package.js` can be imported dynamically. So this works if `some/file.js` is just sitting in the package:
```js
import('meteor/froala:editor/some/file.js').then(...)
```

* If the package defines a main module with
```js
api.mainModule("main.js", "client", { lazy: true })
```
in `package.js`, then the package will not load its main module (or anything imported by it) until the package is imported, which makes it possible to import the package dynamically.

You can see an example in the [`dynamic-import` test app](https://github.com/meteor/meteor/tree/devel/tools/tests/apps/dynamic-import/): passing `lazy: true` [here](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/tests/apps/dynamic-import/packages/lazy-test-package/package.js#L14) enables [this dynamic `import(...)`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/tests/apps/dynamic-import/tests.js#L111) in the test app, and [this `import(...)`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/tests/apps/dynamic-import/tests.js#L124) works because the [`dynamic.js`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/tests/apps/dynamic-import/packages/lazy-test-package/dynamic.js) module is sitting unmentioned in [`lazy-test-package/package.js`](https://github.com/meteor/meteor/blob/4b18c00cc6f0839c67c548360ae20639d66ef126/tools/tests/apps/dynamic-import/packages/lazy-test-package/package.js).

Also note that packages can use dynamic `import(...)` if they depend on both the `dynamic-import` and the `ecmascript` packages. However, choosing to depend on `dynamic-import` effectively restricts the package to Meteor 1.5+, which may not be appealing for package authors until more Meteor developers have upgraded.

**Comment by dr-dimitru** [comment]
This should be documented in a Guide, see https://github.com/meteor/guide/issues/641

**Comment by benjamn** [comment]
@dr-dimitru right again!

**Comment by benjamn** [comment]
Full disclosure: I just fixed a bug that might have interfered with your example working as expected: https://github.com/meteor/meteor/issues/8751

**Comment by hwillson** [comment]
@WayneUong Let us know if this problem is fixed for you after running `meteor update dynamic-import`, and if this issue can be closed. Thanks!

**Comment by WayneUong** [comment]
I've tested and it works great (:

**Comment by erwzqsdsdsf** [comment]
it great work。！！！！！！！！！！！！！！！

**Comment by adamgins** [comment]
@WayneUong any chance you could please post an example of what you did for Froala?

**Comment by adamgins** [comment]
@WayneUong @erwzqsdsdsf any chance you could do a PR for Froala https://github.com/froala/meteor-froala/issues/37 ?
