### ISSUE TITLE
Meteor@1.5 Android build OOM issues on CircleCI

### ISSUE THREAD

**Issue by realyze** [meteor/meteor#8772]
Meteor@1.3 builds fine, Meteor@1.5 fails after cca 18 minutes with OOM error.

The machine is Ubuntu 14.04. I'm passing `GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3096m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'` (tried to set mem limit to 2048 but it's the same). 

The error is: `Your build has exceeded the memory limit of 4G on 1 container.`

Here's the relevant lines from the memory dump:

```
  PID   RSS %CPU COMMAND
 21156 1896960 155 /usr/lib/jvm/jdk1.8.0/bin/java -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/ubuntu/.gradle/wrapper/dists/gradle-2.14.1-all/53l0mv9mggp9q5m2ip574m21oh/gradle-2.14.1/lib/gradle-launcher-2.14.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 2.14.1
 20022 1826084 74.2 /home/ubuntu/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node --max-old-space-size=2047 /home/ubuntu/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/index.js --mobile-settings settings/settings-actionableNotes-qa.json build /home/ubuntu/meteor_build --server https://beta-qa-scribblepost.herokuapp.com
 21100 362260 4.0 /usr/lib/jvm/jdk1.8.0/bin/java -Dorg.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.daemon=false -Dorg.gradle.appname=gradlew -classpath /home/ubuntu/cloned_repo/.meteor/local/cordova-build/platforms/android/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain cdvBuildRelease -b /home/ubuntu/cloned_repo/.meteor/local/cordova-build/platforms/android/build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true
```

**Comment by abernix** [comment]
I'm not sure what to suggest here – you are clearly exceeding the 4GB RAM offering of CircleCI (looks like your `RSS` adds up to ~4.08GB).  [CircleCI has an article on this, particularly about Android/Java](https://circleci.com/docs/1.0/oom/).

The 4GB RAM limit for CircleCI applies to the total of all running processes, not just Meteor (which is taking ~1.83GB), so you'll need to take that into consideration with your memory calculations.  You can see that Meteor, along with the Gradle build is problematic in this situation, but software has a RAM requirement and you're exceeding it.

You could try giving Gradle less memory (since you don't have more to give), perhaps `1024m` instead of `3096m`?

Have you tried SSH-ing into the machine during a 1.3 build and analyzing the memory usage of those?  It's possible you were already nearing the same memory limit with Meteor 1.3.

**Comment by realyze** [comment]
@abernix Thanks for the reply! I filed this issue because I'm surprised by Meteor build tool using 1.8 GB of RAM. I'm not that surprised by Gradle because Java is just a memory hog but Meteor@1.3 didn't seem to take up quite as much memory. I unfortunately don't have time to look into @1.3 RAM usage now but I'll see if I can do it in the next week or two.

**Comment by abernix** [comment]
That'd be great!

Obviously usage will vary on an app by app basis, if it's only 5% more that would be quite different than, say, 50% more.  For example, this (your) app could have already been running close to 1.8 GB and a very small percentage increase (which might be expected due to feature additions) put it over.  If it turns out to be a small(-ish) percentage then there might be less value looking into it.

**Comment by hwillson** [comment]
Since there isn't really anything actionable here on the Meteor side, and there hasn't been any activity in a while, I'll close this off. Thanks!
