### ISSUE TITLE
[1.5] TypeError: [object Object] is not a function

### ISSUE THREAD

**Issue by jacobjuul** [meteor/meteor#8791]
After doing meteor update from `1.4.4.1` to `1.5` I get
```
undefined: 0
TypeError: [object Object] is not a function
```

I suspect the culprit might be webpack:webpack (no longer maintained), but I have no way of confirming this, as I am relying on the ability to import .sass files into my react components.

packages: 
```
accounts-base                  1.2.16* A user account system
accounts-facebook              1.1.1* Login service for Facebook accounts
accounts-password              1.3.5* Password support for accounts
accounts-ui                    1.1.9  Simple templates to add login widgets t...
aldeed:collection2             2.10.0  Automatic validation of insert and upd...
aldeed:simple-schema           1.5.3  A simple schema validation object with ...
awatson1978:browser-detection  1.0.4  Meteorite package that provides browser...
blaze-html-templates           1.0.5* Compile HTML templates into reactive UI...
deanius:promise                3.1.3  Utilities for Promise-based wrappers, m...
edgee:slingshot                0.7.1  Directly post files to cloud storage se...
email                          1.2.0* Send email messages
es5-shim                       4.6.15  Shims and polyfills to improve ECMAScr...
facebook-config-ui             1.0.0  Blaze configuration templates for Faceb...
fortawesome:fontawesome        4.6.3* Font Awesome (official): 500+ scalable ...
http                           1.2.12  Make HTTP calls to remote servers
juliancwirko:postcss           1.1.1* Minifier for Meteor with PostCSS proces...
mdg:meteor-apm-agent           3.0.0  Performance Monitoring for Meteor
mdg:seo                        1.1.0  Provide SEO support for enabled apps.
meteor-base                    1.0.4* Packages that every Meteor app needs
meteorhacks:ssr                2.2.0  Server Side Rendering for Meteor with B...
mobile-experience              1.0.4  Packages for a great mobile user experi...
mongo                          1.1.16* Adaptor for using MongoDB and Minimong...
mrgalaxy:stripe                2.2.2  Stripe.js and Node-Stripe brought to Me...
nooitaf:colors                 1.1.2_1  Add colors to strings using Colors.js
react-meteor-data              0.2.9* React mixin for reactively tracking Met...
reactive-dict                  1.1.8* Reactive dictionary
reactive-var                   1.0.11  Reactive variable
reactrouter:react-router-ssr   3.1.5* Server-side rendering for react-router ...
service-configuration          1.0.11  Manage the configuration for third-par...
session                        1.1.7  Session variable
shell-server                   0.2.3  Server-side component of the `meteor sh...
standard-minifier-js           2.0.0* Standard javascript minifiers used with...
staringatlights:inject-data    2.0.5  A way to inject data to the client with...
themeteorchef:bert             2.1.1* A client side, multi-style alerts syste...
tracker                        1.1.2* Dependency tracker to allow reactive ca...
vsivsi:job-collection          1.4.0* A persistent and reactive job queue for...
webpack:react                  1.2.2  Integrate React with Webpack
webpack:sass                   1.1.4  Integrate SASS (.scc and .sass) import ...
webpack:webpack                1.3.4  Seamlessly integrate Webpack to improve...
```

**Comment by abernix** [comment]
The problem you've presented here to is far too vague to accurately provide help, though I _suppose_ (wild guess) it could be related to https://github.com/meteor/meteor/issues/8740.  Are you on Windows?

You may think you have no way to confirm your suspicious, however on that basis, others trying to solve this issue aren't going to have much luck either as you have provided even less details to work with here considering you have the actual project experiencing the problem.  :smile:

I respect if you can't share that project (private, etc.) but you could make a copy and selectively start removing packages (and SASS components, if necessary) until the problem goes away.

[Please read more information about reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Also, semi-related, if the problem turns out to be any of the [`webpack:*` packages](https://atmospherejs.com/webpack/) (which havn't been updated in quite some time and state on their `README` that they work with Meteor 1.2 and 1.3, not 1.4 or 1.5), I believe there are other ways to solve your need to import SASS into React components though that might be best posed as a question on the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/8791#issuecomment-308030990, without a reproduction there isn't much here to troubleshoot against. Closing for now, but I'll happily re-open this issue if anyone is still encountering this problem, and can provide a reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!
