### ISSUE TITLE
1.5 babelrc doesn't work with babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#8793]
.babelrc
```js
{
  "plugins": [
    "add-module-exports"
  ]
}
```

lib.js
```js
helloworld = () => 1

export default helloworld
```

main.js
```js
Test = require('/lib/lib')

console.log(Test) // produce undefined
```

so if i use require to call module

i have to remove 'babel-plugin-add-module-exports' and 

```js
Test = require('/lib/lib').default
```

**Comment by abernix** [comment]
The `add-module-exports` plugin forces the (older, deprecated and, frankly, confusing) Babel 5 behavior which selectively set `module.exports` to the default object (e.g. `module.exports = exports["default"];`) **only** if there were no other _named_ (i.e. non-default) exports in the module.

This means that if you add a named export to an existing module (`lib.js`, in your example), it would cause breaking changes anywhere you used `require('/lib/lib')` since the default `export` would then become a named export (called `default`) alongside the newly added named-export: (roughly: `exports["default"] = existingDefaultFunction; exports.newExport = "blah";`)

You are already using the ES2015 `export` statement (`export default helloworld`) in your `lib.js`.  If you just use the ES2015 `import` statement (`import Test from '/lib/lib';`), you can be confident that if you add a named export to `lib.js` that it won't break your code in `main.js` (and _everywhere else_) by requiring you to add `.default`.

**Comment by zachguo** [comment]
For people having same problem, tldr: `babel-plugin-add-module-exports` is bad and not supported.
@abernix Thanks for the explanation

**Comment by crapthings** [comment]
i will change pattern, i think its okay

**Comment by vblagomir** [comment]
I have some weird behaviour with `babel-plugin-import` and `babel-plugin-component`. 

Both similar packages to automatically import styles for components for React (ant.design) and VueJS (element) frontend libraries - whereas the packages are imported but styles not. 

Just thought it might be connected with this issue.

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/8793#issuecomment-308047267 and https://github.com/meteor/meteor/issues/8793#issuecomment-308925088, this isn't a Meteor issue. Closing - thanks!
