### ISSUE TITLE
Wrong MAIL_URL configuration documentation

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8804]
In these places:
https://github.com/meteor/meteor/blob/devel/History.md (1.4.4.2 section)
https://docs.meteor.com/changelog.html#v144220170502
https://guide.meteor.com/1.5-migration.html#mail-url
https://docs.meteor.com/environment-variables.html#MAIL-URL
https://docs.meteor.com/api/email.html

It is mentioned that one should use `smtps` for port `465` and `587` in the `MAIL_URL` setting. This is wrong!
Typically 587 starts out as a non-secured connection and does a connection upgrade with starttls.
So `smtps` should usually only be used for port `465`. Setting this for port `587` will usually result in a failed connection to the smtp server.

More info see:
https://nodemailer.com/smtp/

**Comment by sebakerckhof** [comment]
I've created PR's for every instance of this error I could find.

**Comment by abernix** [comment]
Thanks!  I'll get these merged.

Honestly, I think this clarification is great since since it reinstates that if one option doesn't work, you should try the other.  SMTP implementations are frequently done incorrectly. I cannot emphasize how understated the Nodemailer documentation is when it mentions: "In most cases".  Unfortunately, this whole process just changed at some point and it's still not consistent (though most major players get it right). 

Alas, thanks again.

**Comment by sebakerckhof** [comment]
Closing, since everything merged. Thanks @abernix for the additional clarifications.
