### ISSUE TITLE
Meteor 1.5 Dynamic imports don't seem to work with variable inputs

### ISSUE THREAD

**Issue by chluke123** [meteor/meteor#8809]
Works:
`import('/imports/ui/components/pageTemplates/navigation');`

Doesn't work:
`const importPath = '/imports/ui/components/pageTemplates/navigation';
import(importPath);
`
Get an error "Uncaught (in promise) Error: Cannot find module".

Any suggestions?

**Comment by dr-dimitru** [comment]
Hello @chluke123 

This is expected behavior.

`import`, `import()` and `require()` can accept only string as argument, not a *variable* - __only string__. See [#8717](https://github.com/meteor/meteor/issues/8717) , [forum post](https://forums.meteor.com/t/how-to-use-import-require-with-dynamic-path/21955), [SO thread](https://stackoverflow.com/questions/40844484/how-to-import-by-dynamic-path-with-meteor)

**Comment by abernix** [comment]
I've updated #8717 with quotes from the original 1.5 PR thread since it's so slow to load (and even then still requires multiple extra "load more" clicks).  

See https://github.com/meteor/meteor/issues/8717#issuecomment-308961284

(Thanks, very much @dr-dimitru!)
