### ISSUE TITLE
Meteor tutorial correction on collections

### ISSUE THREAD

**Issue by davesierra** [meteor/meteor#8816]
While a bug, it's in the tutorial, so not sure as to whether it belongs here.

Following the tutorial, I got stuck on the collections section: https://www.meteor.com/tutorials/react/collections

Specifically, when it states `import '../imports/api/tasks.js';` I was getting nothing on the client side. Changing this to `import {Tasks} from '../imports/api/tasks.js';` fixed it for me. I'm running the latest Meteor 1.5 if that's any indication, MacOsx 10.12.

Thanks.

**Comment by abernix** [comment]
Are you sure you were making the change in `/server/main.js`?  Is it possible you had confused it with `imports/ui/App.jsx`?

I ask because at first check it seems the main goal there is initialize the database on the server (hence the `server` folder), not to make use of it.  The actual `import` for the client was in `App.jsx`.

**Comment by davesierra** [comment]
Thanks for looking into the issue. Strangely, I created a new app from scratch, following the tutorial again, and it works. 

I'm not sure what caused it to not show up the first time, maybe some latency. The only explanation I could think of: since there was no export default in imports/api/tasks.js, I concluded I might have to specify the import {Task} in server/main.js then while I made that change, the data came through and it *seemed* like that was the fix.
