### ISSUE TITLE
Compiler plugin automatically loads files from node_modules

### ISSUE THREAD

**Issue by jamiter** [meteor/meteor#8836]
### Reproduction
1. Create a clean meteor project (1.4 or 1.5).
2. `meteor add swydo:graphql@=0.1.0`
3. `meteor npm install persistgraphql`
4. `meteor`

### What happens
It will directly crash because it tries to load `.graphql` files from `node_modules`.

### What was supposed to happen
It should simply start the app and only load `.graphql` files that are actually imported somewhere.

According to this comment https://github.com/meteor/meteor/issues/6037#issuecomment-173362716 a compiler plugin should never load files in `node_modules`.

Full discussion here: https://github.com/Swydo/meteor-graphql/issues/5

**Comment by benjamn** [comment]
That comment on #6037 is out of date. The current implementation considers any files with extensions that are handled by a compiler plugin that you've installed. So, in this case, adding `swydo:graphql` causes `.graphql` files in (top-level) `node_modules` packages to be importable.

If there are errors when compiling those `.graphql` files, the errors should be reported via the `inputFile.error` function: [example](https://github.com/meteor/meteor/blob/2a3a01acb36620036e6dd33ca05bcb6313eef8a4/packages/babel-compiler/babel-compiler.js#L100). Because compiler plugins run before the `ImportScanner` analyzes your module dependencies, errors reported via `inputFile.error` will be hidden until/unless the module is actually imported. For example, although [this `illegal.html` file](https://github.com/meteor/meteor/blob/devel/tools/tests/apps/modules/packages/modules-test-package/illegal.html) is processed by the `templating` package, and fails to compile, the failure is not a problem because the `illegal.html` module is never imported.

It looks like what's happening here is that the `swydo:graphql` compiler plugin is throwing an exception rather than properly handling compilation errors via `inputFile.error`. You probably need a `try`-`catch` block [here](https://github.com/Swydo/meteor-graphql/blob/f8e76a76134c26c038825bb14700403ba3528959/compiler.js#L22).

I'm reluctant to catch and hide arbitrary exceptions thrown by compiler plugins, since they may not be related to compilation.

**Comment by jamiter** [comment]
Thanks @benjamn for the detailed answer. There's not much info around on how to build a good compiler so this helps a lot. I'll update the implementation to handle the error.

**Comment by abernix** [comment]
Docs could definitely be improved! A pull request to the guide based on your experience would be gladly reviewed! :)
