### ISSUE TITLE
Meteor.loginWithPassword is not a function 

### ISSUE THREAD

**Issue by mragwa** [meteor/meteor#8845]
Dears,
I'm using Meteor with angular4.
I have a problem with loginWithPassword function i'm using it in client side but it gives me that error 
![screen shot 2017-06-26 at 6 02 32 am](https://user-images.githubusercontent.com/5574454/27524441-35616202-5a35-11e7-9f6a-6d27c2153b28.png)
i declared Meteor types in tsconfig.json file :
 ```
"types": [
      "hammerjs",
      "jasmine",
      "node",
      "source-map",
      "uglify-js",
      "webpack",
       "meteor-typings",
      "@types/underscore"
    ]
```

also if i want to import Meteor from 'meteor/meteor' like whats app tutorial it returns 
`Module not found: Error: Can't resolve 'meteor/meteor' 
`
any work around that issue ??
Thank you.

**Comment by lightningboss** [comment]
Have you tried console logging the Meteor object? Did you import with ` import { Meteor } from 'meteor/meteor'`?
Have you installed the `accounts-base` and `accounts-password` packages?

**Comment by hwillson** [comment]
@mragwa - As @lightningboss mentioned, this problem is likely caused by not adding the `accounts-password` package:

```
meteor add accounts-password
```

That being said, requests for help like this are much better suited on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). If you think there is a bug here somewhere, please provide a small runnable reproduction demonstrating this issue (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!

**Comment by laobento** [comment]
I'm using meteor in ionic(v4) project according to the tutorial "WhatsApp Clone with Meteor and Ionic 2 CLI", then I met this problem and almost crazy. I wonder  should I switch to ionic v2/v3?
