### ISSUE TITLE
[bug] hoisted `function`s invalidly access `let` and `const` variables.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#8848]
I'm in Meteor 1.5.

Something like the following should throw an error according to ES spec:

```js
foo() //  Should throw an Error, f is not defined.

let f = 'foo'
function foo() {
  console.log(f)
}
```

however in Meteor the code does not throw, and `undefined` is logged to console.

You should be able to reproduce by pasting that snippet into a Meteor 1.5 app.

For reference, Chrome throws.

**Comment by hwillson** [comment]
Hi @trusktr - this looks right to me. Your code sample:

```js
foo();
let f = 'foo';
function foo() {
  console.log(f);
}
```

get's translated into the following behind the scenes:

```js
foo();
var f = 'foo';
function foo() {
  console.log(f);
}
```

Then after variable hoisting, this ends up looking like:

```js
var f;
foo();
f = 'foo';
function foo() {
  console.log(f);
}
```

Then since you're using a function declaration (instead of a function expression), the entire function declaration is hoisted as well. So calling `foo()` works, and `f` is really `undefined` when referenced.

You can also verify this by trying your example out on [babel's site](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=GYexAoEoG4CgBsCmAXABMVBeVByUIc5gBXAOwGNkBLEU9MKVAb1lVXNoGcQkA6eEAHNwwGLAC-QA).

**Comment by trusktr** [comment]
Hello @hwillson , then maybe Bable Is wrong. If a let/const variable is not yet defined, it should be an error. This is the designed behavior of let/const.l, and looks like maybe Babel isn't throwing a compile error on that?

Try running it natively, in Chrome console...

**Comment by trusktr** [comment]
I know how `var` hoisting works (f.e. in the Babel output), but `let`/`const` is not supposed to work the same.

**Comment by hwillson** [comment]
Right, but Meteor (via the `ecmascript` package) is transpiling ES2015 syntax to ES5 syntax, via Babel. So the `let` is converted into a `var` behind the scenes. As long as Babel is handling it this way,  Meteor is doing the same (until the day comes that native `let` can be supported). That being said, if you want to get close to replicating this behaviour with Meteor, you can:

1. `meteor npm install --save-dev babel-plugin-transform-es2015-block-scoping`
2. Add the following to your `.babelrc`:

```
{
  "plugins": [    ["transform-es2015-block-scoping", {"tdz": true}]
  ]
}
```

This will throw a temporal dead zone reference error when attempting to make the `foo()` call.

**Comment by trusktr** [comment]
Ah, cool, thanks for that tip!
