### ISSUE TITLE
Import fails in local package with default install of ver. 1.5

### ISSUE THREAD

**Issue by far4599** [meteor/meteor#8849]
Hi,

Reproduction is here: [https://github.com/far4599/meteor-1.5-package-fails](https://github.com/far4599/meteor-1.5-package-fails)

I have came across the problem with importing variables inside my package. I use fresh installation of Meteor 1.5 on Windows 7 x64.

The problem was the following:
When I import variable from another file inside my local package i get error: 
```console
import TestFails from "./class.js";

SyntaxError: Unexpected reserved word
```

To solve the problem I had to add ecmascript module (however it is included in ".meteor/packages" file) to package.js:
```javascript
  var packages = [
    'ecmascript',    
  ];
  api.use(packages);
  api.imply(packages);
```

In my repro there is 2 kind of packages: one - fails, one - success.

**Comment by hwillson** [comment]
Hi @far4599 - this is functioning as designed. Since you're using ES2015 features in your package (like  `import`), `ecmascript` is a package dependency. Adding the `ecmascript` dependency by calling `api.use('ecmascript');` is the correct approach. Having `ecmascript` defined in your apps `.meteor/packages` doesn't help with packages, as packages are meant to be portable. If you share/publish your package, whoever uses it needs to have all necessary dependencies pulled in. Thanks!
