### ISSUE TITLE
Upgrade Facebook Graph API version

### ISSUE THREAD

**Issue by yogiben** [meteor/meteor#8856]
We received the following warning from fb:

```
Your App, XXX, is currently accessing Graph API v2.3 which will reach the end of its 2-year lifetime on 10 July, 2017. We estimate 2 endpoints that Bitwala calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.4 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.

Visit our changelog to see the full list of changes in all Graph API versions.
```

This line should be updated:
https://github.com/meteor/meteor/blob/master/packages/facebook-oauth/facebook_client.js#L34

**Comment by hwillson** [comment]
This was discussed a little while back in a commit comment - https://github.com/meteor/meteor/commit/873f13d743053fc080b5562dec786784bc52a610#commitcomment-22062669. This should definitely be looked into - PR's welcome! 🙂

**Comment by abernix** [comment]
Thank you very much for filing this issue.

Not that this shouldn't be fixed, but out of curiosity, does the [API Upgrade Tool](https://developers.facebook.com/tools/api_versioning/) for that app show any impacted calls?  Facebook APIs never actually stop working, but instead roll over to the next still-active version.

Just trying to gauge the impact here for older users since there is a ramp-up period before older users update, and also some that never get updated and I'd like to be, let's say, mentally prepared for July 10th. :wink:  Honestly, I'm not sure there are actually any breaking changes in that particular API with the way Meteor uses it and I'm hoping that this is as easy rolling over to the new version number in the API URL.

**Comment by hwillson** [comment]
PR #8858 was merged, meaning new `facebook-oauth` and `accounts-facebook` packages are now available. Run `meteor update` to get them - thanks!
