### ISSUE TITLE
How to test the helper with parameters in Meteor Mocha 

### ISSUE THREAD

**Issue by salimakhtar786** [meteor/meteor#8872]
Ho to test the following ` checkUser ` helper with two parameters `currentUser.username` and `username` using Mocha
```
<div class="col-sm-1">
      {{#if checkUser currentUser.username username }}
        <button class="btn btn-small btn-danger my-delete-btn pull-right"><span class="glyphicons glyphicon glyphicon-trash"></span></button>
      {{/if}}
</div>
```

**Comment by abernix** [comment]
Hello,

As explained in the [issue template](https://github.com/meteor/meteor/blob/devel/.github/ISSUE_TEMPLATE.md) when you submitted this issue, Meteor Issues are reserved for reporting bugs with reproductions.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

There are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality, general questions are not accepted here.  Be sure to check out the [Meteor Guide](https://guide.meteor.com) and the [Documentation](https://docs.meteor.com) along with the ["Todos" example application](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials).

If you still need help, it's recommended you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
