### ISSUE TITLE
Console logged verification emails no longer work.

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#8877]
I believe this just started happening with 1.5. Verification tokens that are logged to the console are not working anymore. And for some reason they have a new line near the end of the URL. [Reproduction](https://github.com/davidworkman9/verify-email-meteor).

<img width="548" alt="screen shot 2017-07-05 at 1 36 15 pm" src="https://user-images.githubusercontent.com/1152186/27877249-eb2b2c86-6187-11e7-8708-6485da5e8065.png">
(It's not that the text is being wrapped by the terminal, the terminal is plenty large enough to fit the URL I just clipped it for the screenshot).

**Comment by davidworkman9** [comment]
Update: Seems to be something to do with Email.send. I replaced Email.send with my own implementation.
```
const old = Email.send;
Email.send = (...args) => {
    const [opts] = args; 
    const { to, from, subject, text } = opts;
    console.log(`To: ${to},\nFrom: ${from},\nSubject: ${subject},\n\n${text}`);
    return old.apply(Email, args);
};
```

Above renders the following output when sending a verification email:

```
To: dworkman@industrialwebapps.com,
From: Accounts Example <no-reply@example.com>,
Subject: How to reset your password on localhost:3000,

Hello,

To reset your password, simply click the link below.

http://localhost:3000/reset-password/yMFsMP24LQe2YltGaom1xFgmgDIDrPiPZqcQKqh847F

Thanks.

====== BEGIN MAIL #0 ======
(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
Content-Type: text/plain
From: Accounts Example <no-reply@example.com>
To: dworkman@industrialwebapps.com
Subject: How to reset your password on localhost:3000
Message-ID: <8bef5a8e-81fc-8b66-2973-6dc794ad6f8f@example.com>
Content-Transfer-Encoding: quoted-printable
Date: Thu, 06 Jul 2017 15:14:27 +0000
MIME-Version: 1.0

Hello,

To reset your password, simply click the link below.

http://localhost:3000/reset-password/yMFsMP24LQe2YltGaom1xFgmgDIDrPiPZqcQKq=
h847F

Thanks.
====== END MAIL #0 ======
```

Correct token: `yMFsMP24LQe2YltGaom1xFgmgDIDrPiPZqcQKqh847F`
Email.send's token: `yMFsMP24LQe2YltGaom1xFgmgDIDrPiPZqcQKq=
h847F`

**Comment by abernix** [comment]
This hasn't changed with Meteor 1.5 and I've confirmed that it still happened with the older version of `email` (1.1.8).  The "broken token" you're seeing there isn't the token itself being wrong, it's just the encoding of the e-mail itself.  The `quoted-printable` encoding (which appears in the header of the e-mail on the `Content-Transfer-Encoding` line) dictates that lines be wrapped at 76-characters with `=\r\n`.  If you view the "original e-mail" in your e-mail client, you'll see this format on most all e-mails.  Additionally, if the `reset-password` portion of the URL was 5 characters shorter, it would fit on one line and this wouldn't happen.

Unfortunately, there isn't much we can do about this without jeopardizing the validity of the e-mail on the console since the alternative is `base64`, which would be even more illegible.

If you need to test these by clicking on them you'd need just manually remove this `=` and carriage return.  But really, I'd recommend setting up a mail provider (like [Mailgun](mailgun.com)) and just sending them as real e-mails.  Most mail providers, Mailgun included, have a test server mode which won't allow the e-mails to actually be sent, but instead put them in a place where you can view them in their control panel (and sometimes even forward them onto you directly).

**Comment by davidworkman9** [comment]
This did not happen on 1.4.2.3. Sounds a lot easier to just stick with my overwritten ```Email.send``` method I guess then. No way am I paying for a mail provider for development!
