### ISSUE TITLE
Unable to run any Meteor app under older WebKit via `meteor build` or via `meteor --production`: throws a JS error

### ISSUE THREAD

**Issue by vflyson** [meteor/meteor#8928]
iPad 1G reports an error on line :55 within the main .js bundle for a sample app created via `meteor create simple-todos`. The error description is: "SyntaxError: Parse error". Same happens with my other apps, just the line number varies, same block of code though.

This is the latest Meteor of version 1.5.1, and the error does not get thrown when ran in development mode via `meteor`.

[[the link to pastbin with the code from line 55](https://pastebin.com/Y3xn93LX)] I... assume it could be those Unicode symbols within the code?

upd: tried running `simple-todos` via `meteor --production --release 1.5`; same result, same line 55. Happens only on iPad 1G (iPhone 5 works fine, so it's not an iOS issue, at least not with the latest one).

upd 2: changed babel to version `^6.23.0` from `^6.20.0` in `package.json` -- no go, still error on line 55 within .js when used via iPad 1G.

upd 3: so it seems like there's a byte sequence within that line which mirrors the line horizontally (both on pastebin.com via Chromium and within my desktop IDE)... so e.g. word `constructor` gets rendered as `rotcurtsnoc`, yet I'm able to find by searching for "const". Apparently that's the byte which messes up the old iOS' JS engine. I have no other explanation for the bug that I found.
I think I can say that I've seen too much in my life at this point.

upd 4: this seems to be the uncompressed chunk of code that causes the issue: https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/packages/ddp-client/sockjs-0.3.4.js#L407
Please note how there are no unicode chars within the original (L407), only within the minified version (pastebin). The minification does something to that code, so old JS engines trip on it and refuse to compile.

upd 5: 
I can confirm that removing package `standard-minifier-js@2.1.1` from .meteor/packages solves the issue, yet it ends up leaving my app uncompressed (therefore unsuitable for being deployed to production).

upd 6:
The issues seems to be triggered by the right-to-left unicode control character mark, here's an example (try selecting the code within the highlight): `<span class="st0">"‮"</span>`

**Comment by vflyson** [comment]
So it seems to be `&#8238;` (`&#x202e;`) http://www.fileformat.info/info/unicode/char/202e/index.htm
Unless the error's being triggered by any other unicode character, removing that should fix the issue.

**Comment by vflyson** [comment]
Okay, so I've switched away from `standard-minifier-js@2.2.1` in favor of `ssrwpo:uglifyjs2` -- that one lets you configure options via your app's `package.conf`. The good news: I've managed to build it to run on iPad 1G (I suppose my app will work in Tesla's browser now as well, tho haven't tried yet). More good news: the parse error happens with both ascii_only on and off, which means the unicode bytes merely make it hard to disassemble the file. I'll keep them on for now, even though it's still weird af to be having a raw ltr order mark within the code.
What seems to be causing the error for older browsers is this UglifyJS2 option set to true: `collapse_vars`.
So I've managed to solve this issue by using this config for the aforementioned package:
```
  "uglifyjs2": {
    "options": {
      "compress": {
        "collapse_vars": false,
        "global_defs": {
          "UGLYFYJS_DEAD": false
        }
      }
    }
  }
```

**Comment by abernix** [comment]
Thanks for your research on this!  Have you been able to track down the specific version of `uglify-js` which introduced this problem?  You can fork the [`standard-minifier-js`](https://github.com/meteor/meteor/tree/master/packages/standard-minifier-js) and [`minifier-js`](https://github.com/meteor/meteor/tree/master/packages/minifier-js) packages into your projects local `packages` directory and roll back [the `uglify-js` npm version](https://github.com/meteor/meteor/blob/master/packages/minifier-js/package.js#L7) until the problem goes away.

Since Meteor has been using the same SockJS implementation (and file) for 5 years, it's likely that this will trace back to some change in UglifyJS or its default settings.  While turning off `collapse_vars` may fix it, we'd rather not disable that for the entire community unless we've tried to address the bug first (perhaps by submitting a report to [`uglify-js`](https://github.com/mishoo/UglifyJS2/).

**Comment by vflyson** [comment]
I haven't tried to roll back the thing, but I did try to submit the bug to the `uglify-js` repo -- the latter has rather felt like I was at DMV, so I've decided to confirm with the MDG first that the bug's not in the meteor package. I could try to pinpoint the version and even the line number within the uglify-js repo if I get some time this weekend or the next week, but I just feel like it's urgent enough to patch up within the meteor package ASAP and not wait for the uglify-js devs to patch it on their side. To roll back the NPM's version is perhaps a better option, but I really rather work on my app instead and am currently using a different minifier package which sort of works, even though I prefer using official packages over community-built. I'm kind of selfish after all, I guess.

**Comment by green-coder** [comment]
I might have the same problem, with my meteor 1.5.1 *website* going all white when browsed from iOS 9.3.5 while it works fine on iOS 10.2.1

It did work fine with meteor 1.5 before I ran the upgrade.

**Comment by hwillson** [comment]
Meteor now uses `uglify-es` (as of Meteor 1.6). If you have a chance, please consider upgrading to 1.6, switching back to `standard-minifier-js`, and testing things out. If you continue to notice issues, please post back and let us know. I'll close this for now since testing results based on `uglify-js` are now outdated. Thanks!
