### ISSUE TITLE
Internal exception while processing message: TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by cwohlman** [meteor/meteor#8947]
I created a new app using meteor 1.4.4.1: `meteor create wrong-ddp-package-version-reproduction --release 1.4.4.1`

When I tried to run the app I got this error (on both the client & the server):

```
I20170726-09:56:56.210(-5)? Internal exception while processing message { msg: 'connect',
I20170726-09:56:56.210(-5)?   session: 'C25WdMWFhMqtBW7BT',
I20170726-09:56:56.211(-5)?   version: '1',
I20170726-09:56:56.211(-5)?   support: [ '1', 'pre2', 'pre1' ] } Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
I20170726-09:56:56.211(-5)?     at withoutInvocation (packages/meteor.js:443:33)
I20170726-09:56:56.212(-5)?     at bindAndCatch (packages/meteor.js:452:33)
I20170726-09:56:56.212(-5)?     at Object._.extend.setInterval (packages/meteor.js:479:24)
I20170726-09:56:56.213(-5)?     at [object Object]._.extend._startHeartbeatIntervalTimer (packages/ddp-common.js:89:44)
I20170726-09:56:56.213(-5)?     at [object Object]._.extend.start (packages/ddp-common.js:84:10)
I20170726-09:56:56.213(-5)?     at new Session (packages/ddp-server/livedata_server.js:318:20)
I20170726-09:56:56.213(-5)?     at [object Object]._.extend._handleConnect (packages/ddp-server/livedata_server.js:1463:29)
I20170726-09:56:56.214(-5)?     at packages/ddp-server/livedata_server.js:1379:18
```
Reproduction:
https://github.com/cwohlman/wrong-ddp-package-version-reproduction

Work around:
Correct the versions for the meteor and/or ddp packages in the .meteor/versions file (the bug is caused by a variable rename, as far as I can tell, causing a missmatch between the expected variable name and the actual variable name).

Other details:
- I'm running on Mac OS 10.12.5

**Comment by crapthings** [comment]
we have the same issue while updating from METEOR@1.4.2.3

**Comment by abernix** [comment]
This will go away if you update to Meteor 1.5.1.  You can also explicitly set your `meteor` (the package, not the tool) version pinning to `meteor@1.6.1`

The undefined `get` property it's talking about stems from 35c9ffec3078ee87aaf7058c9f840825e4073bf6 which was a change included in #8629.  I should have bumped the [`meteor`](https://github.com/meteor/meteor/blob/master/packages/meteor/package.js) package version more substantially (major?) in my faa5b2ec0331060110e1705bc15f3ef4762d2886.  It doesn't appear that minor would have even been enough since `meteor@1.7.0` came out with Meteor 1.5.1 and I would have expected Meteor 1.4.4.1 to stay pinned to the minor version series (i.e. `1.6.x`).

I'm not sure the best way to fix this for older versions now, as I believe an attempt to fix this would then break Meteor 1.5.1 - though there may be a creative solution.  Luckily, the upgrade path to Meteor 1.5.1 is [quite straightforward](https://guide.meteor.com/1.5-migration.html).

/cc @benjamn

**Comment by cwohlman** [comment]
Couldn't you fix this by introducing a compatibility check (like I describe below) and then pushing a patch update?

```
const currentInvocation = DDP._CurrentInvocation ? DDP._CurrentInvocation.get() : DDP._CurrentMethodInvocation.get() || DDP._CurrentPublicationInvocation.get();
```

(from https://github.com/meteor/meteor/commit/35c9ffec3078ee87aaf7058c9f840825e4073bf6#diff-2ae5b6c36ab4132c1a2d0e33b5fd8443R80)

**Comment by cwohlman** [comment]
> I would have expected Meteor 1.4.4.1 to stay pinned to the minor version series (i.e. 1.6.x).

So would I, but that's not the behavior we're seeing as far as I can tell.
