### ISSUE TITLE
onPageLoad issues

### ISSUE THREAD

**Issue by rgnevashev** [meteor/meteor#8977]
1) How can I redirect inside the onPageLoad func? See react-router v4 SSR example
2) How can I obtain userId in my components on server side? My App depends on currentUser and I want obtain userId on server side and pass to my App entry point component...

https://github.com/meteor/meteor/blob/21d2dab151eb3e5048f41f588d31fe21ad3b7f3d/packages/webapp/webapp_server.js#L110

We should pass connect req and res to onPageLoad callback

**Comment by AirBorne04** [comment]
I think the problem here is that there is no user context outside the web socket connection in general. There are some ssr router packages for meteor, as far as i can tell the do solve this issue with mirroring the client token into cookies in order to get that token together with the initial request. https://github.com/thereactivestack-legacy/meteor-react-router-ssr/search?utf8=%E2%9C%93&q=cookies&type=

**Comment by aliogaili** [comment]
These libraries are working by fetching the the login token from the client storage and storing it as a cookie, and then they use this cookie to infer if the user is logged in. 

I don't need the user id for now but just away to tell if the user has a login token so I can decide at the server to render the singin page or the app skeleton. 

However the Meteor request object which is being passed to the sink object [doesn't have the cookies in it ](https://github.com/meteor/meteor/blob/21d2dab151eb3e5048f41f588d31fe21ad3b7f3d/packages/webapp/webapp_server.js#L114)  so I'm unable to replicate this signin detection mechanism. 

Can we expose the cookies to the Meteor request object?

**Comment by AirBorne04** [comment]
The initial question explicitly asked for the userId.

For the case that you are only interested into whether somebody is loggedIn or not the same procedure is required. To get access to the cookies you do need to register the `cookie-parser` for the `connecthandlers` the same way those libraries do like [here](https://github.com/thereactivestack-legacy/meteor-react-router-ssr/blob/a0db510fbcef172454393aeed85578413c5cd4f5/lib/server.jsx#L65) Or parse them manually from the `req.headers`.

**Comment by aliogaili** [comment]
Thanks for the response @AirBorne04 . 

If I register the cookie-parser will the cookie information be available at the[ server sink object ](https://github.com/meteor/meteor/blob/0ebca07f06f1e2e2481e77ba9eaadeabb20f2a10/packages/server-render/server-sink.js#L3)in the meteor server render package?

**Comment by aliogaili** [comment]
The` cookie-parser` package takes the cookies from the http headers and attach it to the **webapp req** object. However the **[Meteor "request" object](https://github.com/meteor/meteor/blob/21d2dab151eb3e5048f41f588d31fe21ad3b7f3d/packages/webapp/webapp_server.js#L67-L69)** still doesn't have any information about the cookies since  it's[ not being  passed ](https://github.com/meteor/meteor/blob/21d2dab151eb3e5048f41f588d31fe21ad3b7f3d/packages/webapp/webapp_server.js#L110-L115)by the webapp_server.js 

This is what's being passed to the Meteor request object: 
```
ServerSink {
   request: 
    { browser: { name: 'chromeMobile', major: 60, minor: 0, patch: 3112 },
      url: 
       Url {
         protocol: null,
         slashes: null,
         auth: null,
         host: null,
         port: null,
        hostname: null,
        hash: null,
        search: '',
        query: {},
        pathname: '/login',
        path: '/login',
         href: '/login' } },
   arch: 'web.browser',
   head: '',
   body: '',
   htmlById: {},
   maybeMadeChanges: false }
```
I think we need an isAuthenticated flag, or at least access to the req cookies at the sink object to have more meaningful usecases with [ server-render](https://github.com/meteor/meteor/tree/devel/packages/server-render) onPageLoad function.

**Comment by rgnevashev** [comment]
I've done that:
```
import { onPageLoad } from 'meteor/server-render'

const app = express()
const pageLoad = (req, res, next) => {
  onPageLoad((sink) => {
    // access to cookies
    req.cookies
    // more code here ....
  })
}

app
  .use(cookieParser())
  .use((...args) => {
    pageLoad(...args)
  })

WebApp.connectHandlers.use(app)
```

**Comment by rgnevashev** [comment]
I think, sink object should be extended by req,res,next ...

**Comment by aliogaili** [comment]
Much more elegant solution then my quick hack, thanks for the share!

```
WebApp.rawConnectHandlers.use(cookieParser());

// A workaround to pass the cookies info to the request sink object
WebApp.connectHandlers.use('/', (req, res, next) => {
  if (req.cookies.meteor_login_token) {
    req.dynamicBody = '<span id="signedIn"/>';
  }
  return next();
});

// A workaround to detect if the user has signed on
const isSignedIn = sink => {
  if (!sink || !sink.request || !sink.request.dynamicBody) return false;
  return sink.request.dynamicBody === '<span id="signedIn"/>';
};
```

**Comment by aliogaili** [comment]
@benjamn @hwillson  @abernix any thoughts on extending the Meteor Request object?

**Comment by hwillson** [comment]
I think adjusting this makes sense! That being said, since feature request https://github.com/meteor/meteor-feature-requests/issues/174 is already tracking this, let's move the discussion over there. Thanks!
