### ISSUE TITLE
Manipulate a div when using npm package for client side

### ISSUE THREAD

**Issue by gigibang** [meteor/meteor#8979]
I want to use a npm timeline package (http://visjs.org/docs/timeline/) for in client side. I am trying to manipulate the div which is a container of the timeline elements. An error is occurred (Cannot read property '$' of undefine). Anybody can tell me which is the best way I am able to handle this? 

The html is 
```
<template name="timeline">
    <div id="visualization"></div>
</template>
```
The js is

```
import vis from 'vis';

Template.timeline.rendered (function (template) {

    var container = template.$("#visualization");

    // Create a DataSet (allows two way data-binding)
    var items = new vis.DataSet([
        {id: 1, content: 'item 1', start: '2013-04-20'},
        {id: 2, content: 'item 2', start: '2013-04-14'},
        {id: 3, content: 'item 3', start: '2013-04-18'},
        {id: 4, content: 'item 4', start: '2013-04-16', end: '2013-04-19'},
        {id: 5, content: 'item 5', start: '2013-04-25'},
        {id: 6, content: 'item 6', start: '2013-04-27'}
    ]);

    // Configuration for the Timeline
    var options = {};

    // Create a Timeline
    var timeline = new vis.Timeline(container, items, options);

    console.dir(timeline);

})
```

**Comment by abernix** [comment]
Hi there!,

As explained in the [issue template](https://github.com/meteor/meteor/blob/devel/.github/ISSUE_TEMPLATE.md) when you submitted this issue, Meteor Issues are reserved for reporting bugs with reproductions.  The issue you have reported does not appear to be an actual bug with Meteor, but instead a question about how to use it.

There are many helpful resources available to help you with your problem, however, due to the importance of taking care of core Meteor functionality, general questions are not accepted here.  Be sure to check out the [Meteor Guide](https://guide.meteor.com) and the [Documentation](https://docs.meteor.com) along with the ["Todos" example application](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials).

If you still need help, it's recommended you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
