### ISSUE TITLE
Error calling super property getters in inherited classes

### ISSUE THREAD

**Issue by daniel-mf** [meteor/meteor#8990]
Meteor version: 1.5.1

The following code should log:
`"A-bar|B-foo - B-bar|B-foo"` 

But when the code runs in a Meteor project it logs:
`"A-bar|A-foo - B-bar|B-foo"`

```javascript
class A {

    get foo() {
        return 'A-foo';
    }


    get bar() {
        return 'A-bar|' + this.foo;
    }

}

class B extends A {

    get foo() {
        return 'B-foo';
    }

    get bar() {
        const bBar = 'B-bar|' + this.foo;

        //super.bar should be "A-bar|B-foo"
        return `${super.bar} - ${bBar}`;
    }

}

const x = new B;

console.log(x.bar);
```

If I change the getters to methods, it works as expected. So the problem is related to getters.

The code also works as expected in [Babel REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=MYGwhgzhAECC0G8BQTpugcwKYBdoDMB7QgCgEpFV1qAnXAVxoDtoByWAWiMNYG4q0AXxQDMuaACMwNcpWq0GzNpyk0APq2gBqaDgAWASwgA6bv2rCkl0JBgAhaFgAeOLEwAmMeMlHY83WWR5dDocRhZWOy5iPlFLaj9JaUDRamBCJgg8CTtpaABeNijVDW1dQxMzFGC0AHpaiHoABywaY1VoCD1CehB3SSxoACIVaTUo7iHUkMUWAAMAEgRGlrbVQWgOaCWc6UE583RLawys6CcC6CYsAHdoO34kdMzCECxjEEIMEid26TJeEA)

**Comment by daniel-mf** [comment]
Could someone help with this?
I think this is a serious issue, once it shows that meteor is running buggy javascript.
Its probable an issue in the ecmascript package.

**Comment by klaussner** [comment]
Here is a reproduction repo: https://github.com/klaussner/meteor-issues/tree/8990, including the compiled output of [Meteor (`app.js`)](https://github.com/klaussner/meteor-issues/blob/8990/.output/meteor.js) and the [Babel REPL](https://github.com/klaussner/meteor-issues/blob/8990/.output/babel.js).

The Babel REPL version transpiles `super.bar` to
```js
_get(B.prototype.__proto__ || Object.getPrototypeOf(B.prototype), 'bar', this)
```
which calls the `bar` getter of `A` with `this` set to the instance of `B`. The Meteor version does this instead:
```js
_A.prototype.bar
```

**Comment by daniel-mf** [comment]
[babel-compiler (`README.md`)](https://github.com/meteor/meteor/blob/devel/packages/babel-compiler/README.md) says that [babel-runtime](https://github.com/meteor/meteor/tree/devel/packages/babel-runtime) cannot use `Object.defineProperty` because "Meteor's core packages must run on IE 8 without polyfills"

Maybe that's why we can't have a result like Babel's.

I'm working on a new project and we're using lots of getters.
Is it possible to clone babel-compiler to use it like a local package, so I could tweak it?

**Comment by hwillson** [comment]
This issue is related to https://github.com/meteor/meteor/issues/8583. Actually, it's likely a duplicate. I'll keep this issue open and close https://github.com/meteor/meteor/issues/8583, even though this is the newer issue, as there is more context here. That being said the repro in https://github.com/meteor/meteor/issues/8583 is still quite valid, and exhibits similar behaviour when updated to use a newer version of Meteor.

**Comment by hwillson** [comment]
Meteor runs Babel transforms in loose mode, for performance and browser-compatibility reasons. You can simulate the same behaviour in the [Babel REPL by selecting `es2015-loose` instead of `es2015`](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAECC0G8BQTpugcwKYBdoDMB7QgCgEpFV1qAnXAVxoDtoByWAWiMNYG4q0AXxQDMuaACMwNcpWq0GzNpyk0APq2gBqaDgAWASwgA6bv2rCkl0JBgAhaFgAeOLEwAmMeMlHY83WWR5dDocRhZWOy5iPlFLaj9JaUDRamBCJgg8CTtpaABeNijVDW1dQxMzFGC0AHpaiHoABywaY1VoCD1CehB3SSxoACIVaTUo7iHUkMUWAAMAEgRGlrbVQWgOaCWc6UE583RLawys6CcC6CYsAHdoO34kdMzCECxjEEIMEid26TJeEA&debug=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=react%2Cstage-2%2Ces2015-loose&prettier=false&targets=&version=6.26.0). Changing this is not currently planned. If you think this should be changed, please consider opening a new feature request for this over in http://github.com/meteor/meteor-feature-requests. Thanks!

**Comment by benjamn** [comment]
As for a workaround, you should be able to add `babel-plugin-transform-es2015-classes` to the `plugins` section of a `.babelrc` file to make sure this code is compiled without the `loose` option.

You can see which plugins we run in `loose` mode [here](https://github.com/meteor/babel-preset-meteor/blob/master/index.js) (note that it's only a few of them, classes included).
