### ISSUE TITLE
[1.6-beta.18] Issue with fast-render `dynamics.slice is not a function`

### ISSUE THREAD

**Issue by chongwang87** [meteor/meteor#9003]
### When reporting a bug, please be sure to include the following:
- [x] A descriptive title
- [x] What version of Meteor you're using, and the platform(s) you're running it on
1.6-beta.18
- [x] What packages or other dependencies you're using
only meteorhacks:fast-render
- [x] The behavior you expect to see, and the actual behavior
should have fast-render code injected while running the page
- [x] An *isolated* way to reproduce the behavior
meteor create test
cd test
meteor update --release 1.6-beta.18
meteor add meteorhacks:fast-render
meteor --production

error i get
``error on fast-rendering path: / ; error: TypeError: dynamics.slice is not a function``
``at Object.Meteor.bindEnvironment (packages/meteor.js:1166:41)``
``at PublishContext.onStop (packages/ddp-server/livedata_server.js:1226:23)``
``at Context.processPublication (packages/meteorhacks_fast-render.js:497:18)``
``at packages/meteorhacks_fast-render.js:313:15``
``at Array.forEach (<anonymous>)``
``at Context.<anonymous> (packages/meteorhacks_fast-render.js:310:18)``
``at packages/meteorhacks_fast-render.js:285:18``
``at Array.forEach (<anonymous>)``
``at packages/meteorhacks_fast-render.js:284:31``

**Comment by abernix** [comment]
This is occurring because `fast-render` (a third-party package, not ours) [incorrectly redefines/monkey-patches](https://github.com/kadirahq/fast-render/blob/59ca6d499fde6a05c212a68296bb648ffe01c431/lib/server/context.js#L23-L24) an internal Meteor variable (`Fiber.current._meteor_dynamics`) to an empty `Object` instead of an `Array`, as it [was intended](https://github.com/meteor/meteor/blob/4665f2aab3a9344a9fc5e17d31e57a70f3da05e4/packages/meteor/dynamics_nodejs.js#L51) [to be](https://github.com/meteor/meteor/blob/4665f2aab3a9344a9fc5e17d31e57a70f3da05e4/packages/meteor/dynamics_nodejs.js#L87).

When refactoring the `meteor` package (in https://github.com/meteor/meteor/commit/7f062192e1f9e4cb669d378b1140da9a33b0db42), we didn't (nor should we have had to) take into consideration actions outside packages are taking which touch internal methods.  This certainly isn't the first time `meteorhacks:fast-render` has taken such unfortunate liberties!

The `meteorhacks:fast-render` package is no longer actively maintained.  You may want to consider using a more active fork, such as https://github.com/abecks/meteor-fast-render, which already has https://github.com/abecks/meteor-fast-render/pull/5 submitted by @hexsprite to solve this exact problem. (See also, https://github.com/abecks/meteor-fast-render/issues/4).

**Comment by derwaldgeist** [comment]
Just ran in to this. Thanks @abernix for pointing to an alternative.
