### ISSUE TITLE
meteor angular2 stuck on buiding application..

### ISSUE THREAD

**Issue by Gavotech** [meteor/meteor#9047]
meteor angular2 stuck on building application..
I am using window 10. I am facing building application for long time. Some time application start and work. but for most of time it is stuck on building application..
And one thing more most of time server not restart when I change in Type script file.
Please help me.

**Comment by abernix** [comment]
Sorry to hear you're experiencing problems!  Unfortunately, this isn't enough to really assist you with.  Please submit a complete reproduction for this issue, as what you have included here is not enough to isolate the problem or even tell if this is a problem with Meteor itself (or Angular2, etc.).  [More information on reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).  If you are able to open a new issue with a reproduction, that would be most appreciated but please ensure it is without Angular2, since that's not a core part of Meteor.

You can also ask for help on the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow](https://stackoverflow.com/questions/tagged/meteor), which are probably better places to start.
