### ISSUE TITLE
Cannot use Meteor on Windows - Seems that know one can 

### ISSUE THREAD

**Issue by GaddMaster** [meteor/meteor#9055]
* ❗️ Bug?
          Cannot run meteor from Windows CMD

### This bug report should include:
RUN : Running "meteor" in windows CMD (Or any command)
Version : Newest
OS : Windows 10
Error : (hasStacks = !!e.stack) => RangeError: Maximum call stack size exceeded

**Comment by klaussner** [comment]
This issue is already tracked in #7896. Apparently, it has something to do with conflicting npm package installations. This comment describes a solution that worked for some people: https://github.com/meteor/meteor/issues/7896#issuecomment-292659481. An alternative solution in another issue: https://github.com/meteor/meteor/issues/8983#issuecomment-320148837. 🙂
