### ISSUE TITLE
bundle/ should be a meteor 'special directory'

### ISSUE THREAD

**Issue by Falieson** [meteor/meteor#9078]
The list of special directories: ```imports, node_modules, client, server, public, private, tests, client/compatibility```

During development if I run `meteor build . --directory` , I then need to `rimraf bundle/` before I can run `meteor` and continue programming w/ the dev server. Otherwise bundle is lazy loaded by Meteor Isobuild.

There is a feature request to create a .meteorignore file : https://github.com/meteor/meteor-feature-requests/issues/5 which would be an appropriate place for `bundle/` to be added.

 ``` Using the --directory option will produce a bundle directory instead of the tarball.``` [guide.meteor/meteorbuild](https://docs.meteor.com/commandline.html#meteorbuild)

But since `bundle/` is a fixed setting defined by meteor, I will file this as a bug which should be resolved by adding bundle to the list of special directories.

**Comment by abernix** [comment]
The `.` that you are passing is the `<output path>` of the build, not the source of the build, as seen here in `meteor build --help`:

```
Usage: meteor build <output path> [--debug] [--directory] [--server-only]
          [--mobile-settings settings.json] [--server http://example.com:3000]
```

By passing the `.` you're _telling_ it to build it in the current directory and the `--directory` flag simply makes it generate a directory tree instead of a tarball (of the same ething).  Just like the tarball, the root directory of a build will be the `bundle` directory, no matter where it is output.

If you really want to build it in the current directory, you can currently put it into a hidden folder (which won't be watched by Meteor), such as `.build`:

    meteor build .build --directory

And this should yield a `.build/bundle/...` file structure.  You can also build it outside your application directory entirely:

    meteor build ../output-dir-above-project --directory

Does this help at all?  You certainly should not need to `rimraf`, etc.

**Comment by Falieson** [comment]
Thanks @abernix
