### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mrbigmouth** [meteor/meteor#9101]
Meteor Version: 1.5.2
OS: ubuntu 16.04, use mup 1.3.3 to deploy

After about 4-8 hours running, server will crash with error:

> [35.201.250.246]2017-09-17T10:22:13.063817676Z packages/meteor.js:798
> [35.201.250.246]2017-09-17T10:22:13.063901842Z     }).run();
> [35.201.250.246]2017-09-17T10:22:13.063908651Z        ^
> [35.201.250.246]2017-09-17T10:22:13.063912834Z 
> [35.201.250.246]2017-09-17T10:22:13.063916666Z RangeError: Maximum call stack size exceeded

When I put console.log debug code in all method/setInterval code,
Error may happens even no script is executing.

**Comment by abernix** [comment]
This is usually due to something running in an infinite loop.  I'm not saying it's your code's fault, but it's certainly possible something else might be running infinitely that you are not considering.  Unfortunately, without a reproduction, there is no way to tell if this is an issue with the code you've written, a third party package, or with Meteor itself.  We'd need a reproduction to be able to help with this.  Please attempt to create a reproduction recipe per the instructions for [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) and include it when opening a new issue (as requested in [the instructions](https://raw.githubusercontent.com/meteor/meteor/devel/.github/ISSUE_TEMPLATE.md) when you opened this issue).

If you can reproduce it reliably, then you'll be our best help in trying to figure out how to solve it and we're happy to look into it further!  Unfortunately, if you can't provide a reproduction, there isn't much we can do.

Thanks!

See also, from recent memory:  #9029.
