### ISSUE TITLE
Package version not upgraded if newer version used in other package

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#9109]
Up now, I had been using `underscorestring:underscore.string@3.2.3` in some packages. Now I needed some extended functionality provided by `underscorestring:underscore.string@3.3.4` in one of my packages. So I set the dependency in this package to:

`api.use('underscorestring:underscore.string@3.3.4');`

In earlier versions, Meteor would detect this and upgrade the package dependency in the `versions`file to 3.3.4. But this didn't happen. It stayed on 3.2.3.

Only after I manually patched the `versions` file, the new version was downloaded.

**Comment by hwillson** [comment]
Thanks for reporting this @derwaldgeist. This hasn't been a common complaint, and since there hasn't been much activity here (and there is a fairly painless workaround), I'll close this issue for now. If anyone encounters this issue in the future and feels like this should be looked into further, please let us know.
