### ISSUE TITLE
Babel compiler caches too aggressively (without considering NODE_ENV)

### ISSUE THREAD

**Issue by steventebrinke** [meteor/meteor#9145]
When configuring babel per env (as supported through #8963), running `meteor --production` or `meteor build` might give incorrect results unless `meteor rebuild` is run just before. The reason is that the babel compiler reuses cached source that has been build for a development environment, because the cache assumes that the `NODE_ENV` has no influence on the generated output.

**Comment by klaussner** [comment]
Could you share a small repo that shows the problem? I tried to reproduce it with a Babel plugin that is only used in development but running `meteor --production` after `meteor` (without changing a file) caused the Babel compiler to recompile the code. This is the `.babelrc` file that I've used:

```json
{
  "env": {
    "development": {
      "plugins": ["<Babel plugin>"]
    }
  }
}
```

**Comment by steventebrinke** [comment]
It seems you're right, this bug is not triggered by babel plugins that are only enabled in a specific environment, but by plugins that are always enabled and read the environment. So far, I only tested it in our large meteor app, which has many babel plugins enabled, but I have a small example that can reproduce the behaviour. (Note that this example uses `babel-plugin-transform-node-env-inline` to illustrate the bug. Actually using this plugin is not really useful, but it happens with other plugins that read the environment too.)

You can create a meteor app as follows:
```sh
meteor create simple-todos
cd simple-todos
meteor npm install --save babel-plugin-transform-node-env-inline
```

Now edit `.babelrc` such that it looks like:
```json
{
	"plugins": ["transform-node-env-inline"]
}
```

Finally add to the method `startup` in `server/main.js` the following line:
```js
console.log(`App running in ${process.env.NODE_ENV}`);
```

Now, try running meteor both in development and production and observe that the output doesn't change:
```sh
meteor
meteor --production
```

**Comment by klaussner** [comment]
Here's a small reproduction repo, based on your comment: https://github.com/klaussner/meteor-issues/tree/9145. :slightly_smiling_face: I'm not sure what's the best way to deal with this issue because, theoretically, every environment variable can invalidate the cache (even during development). Maybe `NODE_ENV` could be treated as a special case by simply including it in the [hash of the compiled file](https://github.com/meteor/babel/blob/d1906de293cafe120398674a41790f70c0979548/cache.js#L59-L70)?

**Comment by steventebrinke** [comment]
Including `NODE_ENV` into the hash would be a fine solution for me.

As you say, theoretically any environment variable could invalidate the cache, so another solution might be to allow specifying which environment variables do (or just allowing to override the hash function) and explaining in the docs that whenever you configure the babel plugins, you should consider whether you need to specify environment variables that invalidate the cache. Since adding babel plugins requires some thought anyway, it wouldn't be strange to ask anyone who does to think about the influence on caching, IMO.

**Comment by hexsprite** [comment]
In theory babel plugins could have all sorts of side-effects.

Here's an example, this babel plugin creates some global variables that provide the GIT revision.

https://github.com/renke/babel-plugin-git-version

Meteor would have no way of knowing that so the revision could get out of sync with actual. Is that true?

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's triage doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
