### ISSUE TITLE
[v1.4.2+] Problem with files in  lib importing from ../imports/client

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9156]
Thought I was going insane.  I discovered that my `init.js` file in the `<project>/lib` directory was not able to import a file from the `../imports/client` directory.  But it can import from the `../imports` directory.

Verified on simple projects back to v1.4.2 (did not try any earlier versions).  Weird.  Details below...

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Verified on Meteor v1.4.2, v1.5, v1.5.2.2

### Repro
1. `meteor create testImport`
2. Create 2 sub-directories in the project `lib` & `imports/client`.
3. Add file init.js in the `lib` sub-directory:
```
import '../imports/client/foo1';

console.log('in init.js');
```
4. add file `foo1.js` in sub-directory `imports/client`:
```
console.log('imported foo1.js');
```
5. build result is error. **See below**.

6. Move `init.js` into the `client` directory.  Build works fine.

Somehow, files in the `lib` directory are unable to import files on directory deep in the `imports` directory.

### Result

```
=> Exited with code: 1
W20170929-21:22:39.889(-7)? (STDERR) C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170929-21:22:39.891(-7)? (STDERR)                                            throw(ex);
W20170929-21:22:39.891(-7)? (STDERR)                                            ^
W20170929-21:22:39.892(-7)? (STDERR)
W20170929-21:22:39.893(-7)? (STDERR) Error: Cannot find module '../imports/client/foo1'
W20170929-21:22:39.894(-7)? (STDERR)     at makeMissingError (packages\modules-runtime.js:221:12)
W20170929-21:22:39.894(-7)? (STDERR)     at require (packages\modules-runtime.js:231:19)
W20170929-21:22:39.895(-7)? (STDERR)     at meteorInstall.lib.init.js (lib/init.js:1:14)
W20170929-21:22:39.896(-7)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170929-21:22:39.896(-7)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170929-21:22:39.897(-7)? (STDERR)     at E:\temp\testi42\.meteor\local\build\programs\server\app\app.js:32:1
W20170929-21:22:39.897(-7)? (STDERR)     at E:\temp\testi42\.meteor\local\build\programs\server\boot.js:295:34
W20170929-21:22:39.897(-7)? (STDERR)     at Array.forEach (native)
W20170929-21:22:39.899(-7)? (STDERR)     at Function._.each._.forEach (C:\Users\Bruce\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20170929-21:22:39.900(-7)? (STDERR)     at E:\temp\testi42\.meteor\local\build\programs\server\boot.js:128:5
```

### Expected
To be able to import files one directory deep (& more) in the `imports` directory from files in the `lib` directory.

**Comment by abernix** [comment]
Using your reproduction steps, if you rename your `/imports/client` directory to `/imports/anything_else` it will work on the server.  Alternatively, if you try importing `/imports/client/foo1` from code which is executed only on the client (so for example,`/clients/init.js`, instead of `/lib/init.js`, which is executed on both client _and_ server), it would import properly—on the client.

Some folders in Meteor have special meaning.  Any directory named `client` is not loaded on the server, regardless of whether it is in the `imports` directory or not.  Likewise, anything in a `server` directory cannot be loaded on the client.  This might be viewed as frustrating, or it might be viewed as a security benefit (_especially_ the latter), but these special directories have been a part of Meteor since very early on.  This is explained in the [special directories](https://guide.meteor.com/structure.html#special-directories) section of the documentation.

There was talk in https://github.com/meteor/meteor/issues/4969 of providing a better error message but as of yet I'm not aware of a feature request that has been opened.  There's a link in that issue if you want to proceed with filing that, but this is working as documented.

See also: https://github.com/meteor/meteor/issues/7153
