### ISSUE TITLE
[v1.6-rc.3] Passing --inspect flag via NODE_OPTIONS causes fail at meteor start

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9174]
I know that `meteor debug` will stop my program at a known point on start.  Often times I do not need to debug the startup of my app and it is more valuable to put Node into debug mode but let it run.
-  I can put my own `debugger` statement into my code so it will stop there.
- Or after it starts running I can connect and place my breakpoints where I want.

To accomplish this previously I had set the `NODE_OPTIONS` environment variable to `-debug`.  With version 8 of node they use the `--inspect` flag.  So I expected that passing the `--inspect`  flag would put node in debug mode for later attachment.

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor 1.6-rc.1

### Repro
1. `set NODE_OPTIONS=--inspect`
2. `meteor`

**Result:** `Starting inspector on 127.0.0.1:9229 failed: address already in use`

### Other attempts
1. `set NODE_OPTIONS=--inspect=7654`
2. `meteor`

**Result:** `Starting inspector on 127.0.0.1:7654 failed: address already in use`

No matter which port I gave it, meteor / node failed on startup.

**Comment by jbbr** [comment]
I guess that Meteor spawns multiple node instances at the same time (e.g client & server build). Both are started with `--inspect` but only the first can occupy the port. 
If my guess is correct, a special environment variable like `NODE_OPTIONS_SERVER` could be introduced for server-specific node options.

Though I think the best solution for debugging would be a flag for `meteor debug` to disable the default breakpoint.

**Comment by brucejo75** [comment]
Thanks @jbbr, you are right.  For v1.6 it looks like mdg uses multiple instances of Node for the build, which was not true previously.  I have been using this technique for the last 2 years.

Added in [request 194](https://github.com/meteor/meteor-feature-requests/issues/194) to address this.

**Comment by benjamn** [comment]
Just confirming that `NODE_OPTIONS` should never be used for this, since that causes both the build process and the server process to attempt to start the debugger/inspector on the same port. One of the original goals of `meteor debug` was to make it easier to enable the debugger just for the server process and not for the build process. We intended `meteor debug` as an alternative to `NODE_OPTIONS` for exactly this reason. This build/server two-process system has been in place since before Meteor supported Windows, so it's not anything new. `NODE_OPTIONS` may have worked previously with `--debug` because Node would automatically choose a different port, but that was never the intended behavior.

**Comment by brucejo75** [comment]
Thanks @benjamn, interesting that it worked prior to 1.6...
Closing issue
What do you think of [request 194](https://github.com/meteor/meteor-feature-requests/issues/194)?

**Comment by benjamn** [comment]
@brucejo75 @jbbr I like the idea! Just opened https://github.com/meteor/meteor/pull/9201 with an implementation that works like Node's `--inspect` and `--inspect-brk` flags. The `meteor debug` command still works, but it's equivalent to `meteor run --inspect-brk`.
