### ISSUE TITLE
Installer is failing

### ISSUE THREAD

**Issue by zol** [meteor/meteor#9184]
Looked on Twitter and the forums and haven't seen mention of this so figured I'd report it here. This is from our CircleCI build machine.

```
$ curl https://install.meteor.com | /bin/sh 2>&1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0   100k      0 --:--:-- --:--:-- --:--:--  101k
Downloading Meteor distribution

curl: (22) The requested URL returned error: 404 Not Found
Retrying download in 5 seconds...
```

```
$ wget https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.5.2.2/meteor-bootstrap-os.linux.x86_64.tar.gz
--2017-10-06 18:48:50--  https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.5.2.2/meteor-bootstrap-os.linux.x86_64.tar.gz
Resolving meteorinstall-4168.kxcdn.com (meteorinstall-4168.kxcdn.com)... 198.24.170.178
Connecting to meteorinstall-4168.kxcdn.com (meteorinstall-4168.kxcdn.com)|198.24.170.178|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-06 18:48:50 ERROR 404: Not Found.
```

**Comment by tobiaswirtz** [comment]
Also experiencing this!

**Comment by jeffyamada** [comment]
Same.

Thanks @zol just did the same and couldn't find anyone else, relieved to know I'm not alone!

**Comment by johnwils** [comment]
Also experiencing this.

The TARBALL_URL in the meteor install script seems to be down (at least version 1.5.2.2 on macOS currently)

https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.5.2.2/meteor-bootstrap-os.osx.x86_64.tar.gz

**Comment by benjamn** [comment]
Confirming this is broken, probably at the MaxCDN level. We (@abernix and I) are working on it. Thanks everyone!

**Comment by bo01ean** [comment]
Same issue here :D

**Comment by abernix** [comment]
We're not sure why at the moment, but the `meteorinstall-4168.kxcdn.com` host has stopped working.

We've switched it over to an alternate host, `static-meteor.netdna-ssl.com` (which is on the same CDN provider but with a different SSL-enabled hostname), and it should be up and running again.  We've updated the installer at `installer.meteor.com`, to use this new host so that `curl https://install.meteor.com | sh` will work as expected in CI and elsewhere.

Thanks for reporting this @zol and others!  I'll leave this open for the time-being, but expect it to be okay from now on.

**Comment by slaphead** [comment]
It looks like it is working again for me

**Comment by zol** [comment]
Working for me too.

**Comment by jeffyamada** [comment]
BOOM, fixed for me too. THANK YOU!

**Comment by tobiaswirtz** [comment]
Thank you so much @abernix !!

**Comment by abernix** [comment]
Glad it's working properly for everyone now.  I'll close this but don't hesitate to comment if problems are still occurring.
