### ISSUE TITLE
Meteor trying to do a stack pivot ...

### ISSUE THREAD

**Issue by bo01ean** [meteor/meteor#9202]
Everytime I try to load meteor it crashes instantly with:
```
$ meteor create myapp
Killed: 9
```

Meteor version info:
```
$ meteor --version
Meteor 1.5.2.2
Killed: 9
```

Verbose info provides:
```
$ METEOR_PROFILE=1 METEOR_LOG=debug meteor  --verbose
Opening db file /Users/me/.meteor/package-metadata/v2.0.1/packages.data.db
Killed: 9
```

Here are some system specifics:
```
$ uname -a
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

```
$ node -v
v7.10.1
```

Please advise

**Comment by bo01ean** [comment]
Looks like Meteor is trying to stack pivot:

```
Oct 11 14:01:51 HOST CylanceSvc[62]: process Terminated by policy - path:/Users/me/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node pid:51724 violation:StackPivot occurrences:1 SHA:
```

**Comment by abernix** [comment]
Without being able to debug this further, since I don't have [Cylance](https://www.cylance.com/en_us/home.html) installed, my first guess would have been that the Meteor springboarding ([which happens in this code](https://github.com/meteor/meteor/blob/abernix/redo-win-gen-dev-bundle/tools/cli/main.js#L535-L536)) might be triggering this.

Suffice to say that I think this is a false-positive by that software, but your help in debugging it would be appreciated.  You can find out how to [run Meteor from a checkout](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-from-a-git-checkout), and possibly add some `console.log` messages to find exactly where the problem is happening, or use the `release-1.6` branch (which uses Node.js 8) and add the `TOOL_NODE_FLAGS=--inspect-brk` environment variable before running `./meteor-checkout/meteor` command and use the awesome Chrome/FireFox DevTools to "Step through" it.

Forewarning though: It's possible that the checkout won't trigger the problem since it doesn't actually do the springboarding, so it'd be informative to see if you experience the same problem in development!

**Comment by bo01ean** [comment]
Ok, thanks. That link to the springboard is broken (i see abernix in the path). I'll take a look at stepping through a dev build later today.

**Comment by abernix** [comment]
@bo01ean Sorry about the link.  Updated above!

**Comment by bo01ean** [comment]
oh, this is not a false positive after all. Underneath the covers the meteor springboard calls kexec which calls system execvp ... which is a legit stack pivot:

https://github.com/jprichardson/node-kexec/blob/master/src/kexec.cc#L41

We ended up whitelisting the image in Cylance ...

**Comment by hwillson** [comment]
Thanks for the update @bo01ean. It looks like the chances of this being exploitable are pretty low, but if you feel otherwise please consider sending an email to [security@meteor.com](mailto:security@meteor.com) with your findings.
