### ISSUE TITLE
It should be possible to do Npm.depends with a url ({"module": "https://......tar.gz"})

### ISSUE THREAD

**Issue by edi9999** [meteor/meteor#9236]
meteor version : 1.5.2.2

Create a package with following package.js file : 

```
Npm.depends({
	async: "https://github.com/caolan/async/archive/v2.3.0.tar.gz",
});
```

# Actual behavior : 

The code is failing with : 

```
package.js:1:-26: must declare valid version of dependency: async@https://github.com/caolan/async/archive/v2.3.0.tar.gz
```

# Expected behavior.

It should install the module 

`npm install https://github.com/caolan/async/archive/v2.3.0.tar.gz` works as expected.

I have found the source of the problem and will do a small Merge request.

**Comment by hwillson** [comment]
Thanks for reporting this @edi9999. I wouldn't necessarily call this a bug; `Npm.depends` was designed to meet NPM's original dependency requirements, which at the time didn't include supporting any type of http/https URL. Adjusting `Npm.depends` to line up with https://docs.npmjs.com/files/package.json#urls-as-dependencies is more of a feature request. That being said, since you're already submitted a PR to address this, we'll leave this issue open here (instead of migrating it to http://github.com/meteor/meteor-feature-requests). Thanks for your work on this!

**Comment by bmanturner** [comment]
I actually do this already... The following works for me.

```
Npm.depends({
  'ionic-sdk': 'https://github.com/driftyco/ionic-v1/tarball/298ad4b6451defcfbd3cd34da1533826d5731c42',```
});
```

**Comment by hwillson** [comment]
@bmanturner That works, but the submitted PR (https://github.com/meteor/meteor/pull/9237) is interested in opening things up further. The current implementation supports tarball links in the format you mentioned, with a commit hash. The PR opens this up to any http/https based link.
