### ISSUE TITLE
Meteor run confused about: ROOT_URL, --port settings

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9241]
Discovered that the application of and priority of meteor settings during `meteor run` is inconsistent.

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor 1.6-rc.9

### Repro
I ran a series of tests varying the `ROOT_URL` and the `--port [PORT]` option and got inconsistent results:

| Case| `ROOT_URL` | `--port` | Displayed | Actual Working |
| -- | ------------- | ------------- | ------------- | ------------- |
| 1 | `undefined` | `undefined` | `App running at: http://localhost:3000/` | `http://localhost:3000/` |
| 2 | `http://localhost:4444` | `undefined` | `App running at: http://localhost:4444/` | `http://localhost:3000/` |
| 3 | `http://localhost:4444` | `-p 5555` | `App running at: http://localhost:4444/` | `http://localhost:5555/` |
| 4 | `undefined` | `-p 5555` | `App running at: http://localhost:5555/` | `http://localhost:5555/` |

Case 2 & 3 are broken, they say they are displaying the `ROOT_URL` but are actually running the default URL.

I also took a look at the output of `Meteor.absoluteURL()` it always matched what was displayed, not the actual.

### Expected
Displayed URL to be the same as the Actual URL.
`Meteor.absoluteURL()` to be the same as the Actual URL.

**Note**: I am confused about what `ROOT_URL` is supposed to be?  [Documentation ](https://docs.meteor.com/environment-variables.html#ROOT-URL) is a little vague. Is it simply a way to set the value of `Meteor.absoluteURL()`?  But `Meteor.absoluteURL()` is not used by meteor to set the URL?  What is the scenario?

Thanks!

**Comment by bmanturner** [comment]
ROOT_URL sets the address that you would need to connect to in order to load the page. All hyperlinks are relative to ROOT_URL. Test cases 2&3 are not broken because you are telling meteor to listen on a particular port (```--port```) but telling meteor the url of the website (```ROOT_URL```) is something different than a port. 

Example: If a website typically runs on port 80 or 443, it will not work if you specify a port other than 80 or 443 because it's not listening to those ports. It's like lying to the post office about your address and then being confused when your mail doesn't show up.

**Comment by brucejo75** [comment]
Here is what I am saying:

If `--port` overrides the port in `ROOT_URL` which it looks like it does, then `Meteor.absoluteURL()` should report a value with that override and the output display should output a value with that override.

Or... if `--port` should not override `ROOT_URL`'s port then the actual working URL should be `ROOT_URL`.

Today, meteor does neither.  `--port` overrides `ROOT_URL` but not everywhere.  I think this is worthy of a fix.

## Meteor URL and PORT confusion

I will also add, that the whole URL root concept in meteor is a little confused.  Take a look at a number of discussions in the forum.

It is hard to penetrate what actual settings should be, here is my list of ways to control the Port & URL:

### Environment Varibles
```
ROOT_URL
PORT
BIND_IP
```
### Command Line options
```
meteor build --server
meteor run --port --mobile-server
```

Which ones have precedence for `meteor run`?  Which ones have precedence for `meteor build`?

Here are some questions:
- Why is there a `BIND_IP` & `PORT` & `ROOT_URL`?  is `ROOT_URL` a convenience to not specify `BIND_IP` & `PORT`?  If so, why don't `BIND_IP` & `PORT` work for `meteor run`?
- Does `ROOT_URL` override `BIND_IP` & `PORT`?
- For development `BIND_IP` env variable is not processed.  But don't worry you can pass an obfuscated `--port` option which includes the IP.  What?
- Do environment variables override options?  or vice versa? (My issue is they do neither today).
- Why does `meteor build` use `--server` but `meteor run` use `--mobile-server`?  Do they imply the same thing?  Can I build mobile apps that connect to a server other than the one I am building?  What is the scenario?

## Opinion
- It looks to me like a lot of these options and Environment Variables were added over time to plug gaps in the overall ability to bind the app to an IP:PORT.  I could not find an adequate explanation of how they interact with each other in the docs.
- This should be completely re-thought out and be consistent for all `meteor` commands that need them.  It causes a lot of unnecessary confusion.  There are too many options & patches.

### Proposal
Only 2 concepts:  a server IP and a server Port.  Any mobile apps built will bind themselves to these addresses as well.

Environment variables: `BIND_IP`, `BIND_PORT`  will bind the server & any mobile apps to the IP and the port. 
Each of these environment variables can be overridden by command line options:
```
meteor run --bind-ip --bind-port
meteor build --bind-ip --bind-port
```
Specifying a port for `BIND_IP` is an error.
Specifying an IP for `BIND_PORT` is an error.

For `meteor run` defaults are `localhost` & `3000`.
For `meteor build` defaults are `localhost` & `80`.


... guess I am touching a nerve.  🤕

**Comment by bmanturner** [comment]
Respectfully, I still think you're confused. I'd love if someone else could chime in if I'm completely off base here.

>If ```--port``` overrides the port in ROOT_URL which it looks like it does, then Meteor.absoluteURL() should report a value with that override and the output display should output a value with that override.

```--port``` isn't overriding the port in ROOT_URL because ROOT_URL has nothing to do with the port. It is an address that ultimately resolves to your application that optionally includes a port should you need one. ROOT_URL is indifferent to the inclusion of a port. ROOT_URL is the address you would link someone to in order to direct them to your page. It could be ```my-home-pc.local```, it could be ```www.mywebsite.com```, it could ```192.168.1.12:3000```. ROOT_URL is not parsed, it is not used for anything programatically. It creates links that people use to navigate to your site..

> For meteor run defaults are localhost & 3000.
> For meteor build defaults are localhost & 80.

Correct. When you're building meteor for production it defaults to port 80 as port 80 is the default listening port for web traffic. If you did not use a web server such as nginx or caddy you would want the port to be 80 (or 443 for https traffic). If you use nginx or caddy as a proxy in front of meteor then it doesn't matter what port meteor uses (as long as it's not bound to a port nginx/caddy is listening on). Your web server would be responsible for listening on the ports you specify in the web server's configuration and forwarding the traffic to the meteor app (whose address may internally look like ```localhost:3000```). In this case, ROOT_URL is the location of the web server that will forward traffic to the actual meteor instance. This is why ROOT_URL behaves the way it does.

**Comment by brucejo75** [comment]
@bmanturner, thanks for taking the time to reply.  I think? I am getting it.  😃 and I agree that I am definitely confused. 😕 (your scenario about a proxy front end tripped my light bulb, but maybe still a dim light)

I think the documentation is scattered on this topic.  So I was thinking I would like to write up a gist of how all these variables interact along with some good scenarios.

If you have the inclination would you be interested in collaborating with me on this document?  I could do the writing and you would provide me with some feedback / direction.  And if you don't mind I could do it over email using your profile email address...

**Comment by bmanturner** [comment]
@brucejo75 

The Meteor community has been great to me the past 2 years so I won't pass over an opportunity to do what I can to help. Unfortunately I don't know much about BIND_IP as I've never had to use it, but I'll give feedback where I can. Feel free to drop me a line at my email (which I just updated on my profile).

**Comment by hwillson** [comment]
Hi guys - it sounds like this should be addressed via the docs. Would one of you mind opening an issue to track this over in http://github.com/meteor/docs or http://github.com/meteor/guide (wherever you feel it is more appropriate)? Thanks!

**Comment by brucejo75** [comment]
@hwillson , Will do!  I am planning to write up a gist to make sure I have a clear understanding.  Then I could address with doc change requests...

Thanks!
