### ISSUE TITLE
Allow overruling constraint resolver

### ISSUE THREAD

**Issue by GeoffreyBooth** [meteor/meteor#9244]
See https://github.com/meteor/meteor/pull/9107#issuecomment-336779144. The package `practicalmeteor:mocha`‘s `package.js` includes `api.versionsFrom("1.3")`, which means it wants `coffeescript@1.0.4`. I’m trying to upgrade `coffeescript` to `coffeescript@2`, but when I do, `practicalmeteor:mocha` prevents the app from starting because `coffeescript@2` doesn’t satisfy its version requirement.

Meteor shouldn’t require that there be only one installed version of the `coffeescript` package per app, that satisfies both the app code and all packages. Why can’t package dependencies function the way they do in Node, where if the app itself has `lib@2` in its package.json and a dependency has `lib@1` in _its_ package.json, both `lib` versions get loaded respectively?

Sooner or later a core package like `ecmascript` will get upgraded to a new major version that differs from the major version in `api.versionsFrom("1.3")`, and then `practicalmeteor:mocha` will be unusable in that version of Meteor unless it gets patched. Seeing as there are many abandoned packages out there, this will be an increasing problem. I don’t want to choose between either not upgrading Meteor or needing to abandon or patch old packages that my app is using.

**Comment by benjamn** [comment]
I hear your frustration, but this is not a bug. Meteor's package system is designed to be single-loading, so you can never have two different versions of the same package loaded side-by-side in the same app. This is particularly useful for packages that include a lot of client-side code, packages that expect to be singletons, and packages that run code during application startup (since running that code twice may be undesirable).

The possibility of sometimes ending up with distinct copies of packages using npm is a major problem for that ecosystem. For example, React stops working if you load it twice, `instanceof` fails for instances of duplicated constructors, and the widespread duplication of heavily-depended-upon packages like `lodash` is something people constantly struggle with. So that's why Meteor packages don't function the way they do in Node.

As we saw with https://github.com/meteor/meteor/pull/9107#issuecomment-337091582, major version updates are major for a reason: they introduce breaking changes that require updating packages like `practicalmeteor:mocha`. That's a natural part of working with independent packages, and it's why we have semantic versioning in the first place. Allowing `practicalmeteor:mocha` to continue using a different version of `coffeescript` is not a safe or sustainable solution to that annoyance.

It's unfortunate when packages are abandoned, but it's relatively easy to fork them locally, submit PRs, and/or republish them under a different developer name. That kind of work is worthwhile and unavoidable.

The good news is that Meteor's constraint solver will find a solution that respects every package's constraints, if one exists. There's nothing like it in the Node/npm world, and that's their loss. I hope the benefits of single-loading make themselves apparent to you over time, even if single-loading seems like your nemesis right now.

**Comment by GeoffreyBooth** [comment]
The issue is how this works in practice. Ideally `practicalmeteor:mocha` should list its dependency versions as absolute version numbers, as in, “we tested this package with these versions of our dependencies, and it works.” That package’s tests are [currently failing](https://github.com/practicalmeteor/meteor-mocha/pull/92); but I presume they used to pass at one point. (It would be pretty ironic if they didn’t.) Yet I don’t know what specific versions it was using back then, just that they were within the range of versions covered by `api.versionsFrom("1.3")`, assuming that `versionsFrom` returns the newest set of version numbers from any 1.3.x release, which might have some versions newer than the 1.3.x release that was current when the package was written. This is basically the same problem that Yarn and `package-lock.json` files are trying to solve.

This puts package developers in an difficult position. If I were the developer of `practicalmeteor:mocha`, I would want to list exactly the version numbers of my dependencies, the ones that I know work for my package. But then I’m dictating to projects that use my package what version numbers they need to choose for a host of packages they might want to install, and that’s not good. So instead I guess what you’re recommending is that the package fix the major versions of dependencies, either via `api.use('coffeescript@1')` or `api.versionsFrom('1.3')`; but then that presents the problem that the package promises compatibility with future minor versions of its dependencies, and it might not actually be the case. It _should,_ becuase semver, but doesn’t always work in the real world. To take just one example, for CoffeeScript we often fix what we consider to be a bug in how syntax is parsed, and people then complain because they were relying on the buggy parsing for their code to work. Theoretically any minor or patch release can introduce changes that break dependents.

I really should be releasing the new `coffeescript` package as version 2. It _is_ a breaking change release. But if I do that, then anyone using `coffeescript` in their projects will need to track down every package that depends on it and patch those projects to accept the new version. This incentivizes me to just [never bump the major version](https://github.com/meteor/meteor/pull/9107#issuecomment-337033815), even when I should. And then I really am releasing breaking changes in a minor release, and violating semver, and we’re back to the problem in the previous paragraph. Alternatively I could release a `coffeescript2` package, that can be installed concurrently with the `coffeescript` package, and I achieve an end run around your policy. This wouldn’t work in `coffeescript`‘s case, because it needs to install a build plugin for `.coffee` files and I presume you can’t have two build plugins for the same file extension, but this is a potential workaround for other packages that have this issue.

It sounds like what you’re trying to do is essentially replicate [what Bower does](https://jaketrent.com/post/bower-resolutions/), which makes sense for frontend code; but you don’t offer Bower’s extra functionality of overriding the constraint resolver if I choose to. Also, while I agree we don’t want several versions of jQuery, or React, or something else loading on the frontend, server-side code doesn’t have that issue. I understand there are other concerns like you said of packages running code on startup, or my case of registering a build plugin, but there should be a way to load multiple versions of server-side “static” packages (that only do things as a result of dependents importing and using them). You already allow different packages to have different _NPM_ dependencies; if I could somehow rewrite the `coffeescript` package to be an NPM module, that would also solve this issue. I’ve never been able to find any good info on how to replicate the Meteor packages’ `package.js` functionality within an NPM module, however.

**Comment by benjamn** [comment]
> Alternatively I could release a `coffeescript2` package, that can be installed concurrently with the `coffeescript` package, and I achieve an end run around your policy. This wouldn’t work in `coffeescript`‘s case, because it needs to install a build plugin for `.coffee` files…

There would be nothing wrong with this approach if `coffeescript` and `coffeescript2` were pure libraries that had no conflicts with each other. But alas, they compete over a specific role within a Meteor app, so there can be only one of them. Please try not to focus on the particular nature of this role (handling `.coffee` files), because this is a general pattern that makes it risky to install multiple copies of any package.

> I’ve never been able to find any good info on how to replicate the Meteor packages’ `package.js` functionality within an NPM module, however.

We would be much further along in our transition to npm if the functionality was equivalent, but it's not. We've had a hard time replicating the functionality of Meteor's compiler plugins, and Meteor's ability to run startup code on both client and server, specifically.

---

Honestly, I think you should just release `coffeescript@2.0.0`, knowing that it won't be immediately installable in many apps, and we'll do everything we can to help people sort out their version constraints to make the upgrade possible. Keeping `coffeescript@1.x.y` was momentarily tempting when we thought it might work with all the `practicalmeteor:*`packages, but we now know that was a naive hope, so I would encourage you to trust your instincts about the major version bump.

**Comment by GeoffreyBooth** [comment]
Yes, that seems to be the best of unappealing options. However it would be nice to have a way to override the constraint resolver, to basically somehow say “I know `practicalmeteor:mocha` wants `coffeescript@1`, but `coffeescript@2` will do as well.” In other words, functionality similar to what Bower offers. That would let users avoid needing to fork and patch such packages, and they’d be fully aware of that they’re taking a risk in allowing the exception.

**Comment by GeoffreyBooth** [comment]
Suggested improvements you could make:
- Allow installing a Meteor package from a Git repo, e.g. `meteor add https://github.com/GeoffreyBooth/meteor-mocha.git` . Atmosphere is getting polluted with forks of other packages, and allowing installing packages directly from GitHub would resolve this. (See https://atmospherejs.com/?q=t9n for an example.)
- Give Atmosphere an equivalent of NPM’s https://www.npmjs.com/browse/depended, so we can see what packages have the most dependents.
- In Atmosphere, provide a way to see all the dependents for a particular package, ordered by popularity. Currently a package’s Atmosphere page just shows the top few (see https://atmospherejs.com/meteor/coffeescript).
- Provide a way to override the constraint resolver, like how it’s possible to do so with Bower. There are lots and lots of old packages out there that slap on `api.versionsFrom` with old versions of Meteor, needlessly constraining lots of dependencies. It be nice to be able to add something to `.meteor/packages` or `.meteor/versions` or `package.json` to override this constraint rather than needing to fork and patch the package.

**Comment by hwillson** [comment]
Great discussion here all, but let's continue this over in the FR repo.

----

To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=Allow%20overruling%20constraint%20resolver&body=Migrated%20from:%20meteor/meteor%239244) to start the feature request migration process. Thanks!
