### ISSUE TITLE
Versioning discipline / breaking changes in point releases

### ISSUE THREAD

**Issue by kentonv** [meteor/meteor#9254]
The 1.5.2.1 point release introduced several different subtle, breaking changes compared to 1.5.2. In particular, three different changes managed to break (admittedly bad code in) Sandstorm:

* The handling of the PORT environment variable changed, becoming more strict than before, causing servers with invalid values in PORT to fail to start.
* Meteor began calling `http.listen()` with a single object containing `{port,host}` rather than as two parameters, which interacted badly with a monkey-patch Sandstorm uses to make Meteor listen on an inherited file descriptor.
* The semantics of `Npm.require()` changed to stop searching up the directory tree for `node_modules` directories, the way Node's built-in `require()` does.

For Sandstorm, two of the breakages were caught in testing; unfortunately, due to lackluster testing on my part, the remaining one made its way to production and [led to a mass outage](https://github.com/sandstorm-io/sandstorm/issues/2993).

The first two issues were caused by #8702, which added support for listening on unix domain sockets. The third came from #9095, which was ostensibly intended to clean up error messages.

To reiterate, these are good changes and the breakages in Sandstorm are entirely our fault -- our code sucked and my testing should have been more thorough.

The small issue I want to raise, though, is that Meteor's use of version numbers is surprising. All these changes came in a "nano" release (incrementing the fourth component of the version number). Normally, I would expect a nano release to contain only security fixes and low-risk bug fixes, never new features, cleanups, nor refactoring. (In fact, I'd expect the same of micro releases (third component), though this is pretty obviously not the case with Meteor.) And, my perception of the amount of change in an update affects how much testing I do.

This seems especially important when the release is introducing a critical security fix -- which, coincidentally, 1.5.2.1 did.

Would it make sense for Meteor to adopt a stricter approach to versioning, where nano releases contain strictly non-risky or critical changes? Or should we assume, going forward, that every Meteor release may contain significant, breaking changes, and must be thoroughly tested?

**Comment by hwillson** [comment]
Thanks @kentonv - definitely fair questions. Quick answers:

> Would it make sense for Meteor to adopt a stricter approach to versioning, where nano releases contain strictly non-risky or critical changes?

Maybe.

> Or should we assume, going forward, that every Meteor release may contain significant, breaking changes, and must be thoroughly tested?

Yes.

Clear as mud, right? 🙂 

Meteor strives to be as backwards compatible as possible, and when breaking changes are introduced, we try to make sure they're well documented (and in some cases, handle the breaking changes automatically with the help of code based updaters). That being said, it can sometimes be difficult to gauge the impact certain changes will have on platform users and integrators. In the name of progress however, we sometimes have to roll the dice. While we don't necessarily see the changes you've identified as being backwards incompatible changes, we're sorry to hear they impacted you and your users.

When it comes to Meteor's versioning scheme, it's important to note that Meteor releases do not follow any form of semantic versioning (Meteor packages do, but that's another discussion). The process of deciding which changes go into which version works like this:

1. Do we have some large chunk of functionality we want to release, that could impact Meteor users significantly, that needs to be extremely well tested, and will likely require many beta's and release candidates? If so, those changes are going into a Meteor 1.x release (like the upcoming Meteor 1.6 release with Node 8).
2. Do we have enough new bug fixes and/or functionality ready (either from MDG or community pull requests) to put together a new release, and we're not planning a 1.x release anytime soon? If so, those changes are going into a Meteor 1.x.x release.
3. Do we have a critical bug or security fix ready that needs to be released immediately, and we're not planning a 1.x or 1.x.x release anytime soon? If so, that fix is going into a 1.x.x.x release.
4. We're putting out a 1.x.x.x release; since we're going through the process of testing, bundling, deploying, etc. a new release, are there any other pending (not major) changes we're interested in including?

This is of course a super high-level representation of the release decisions made (there are other technical details that come into play when deciding on releases), but this pretty much covers the big picture. Looking at this, `#4` is why the changes you identified were included in `1.5.2.1`. They were deemed to be okay to release (not perceived as breaking backwards compatibility), and since a new release was being put out anyways, were included. Again, Meteor doesn't follow a semver type of versioning approach, so decisions like this can be made as needed. 

All of the above being said, I know this doesn't really answer your first question - should Meteor releases follow a more strict versioning approach. Definitely an interesting question, and one that I know has been debated for quite some time. There are pros/cons to the current approach versus adopting a more strict approach, and we can definitely start at discussion around potentially changing this process. To kick start that discussion, would you mind opening a new issue over in the http://github.com/meteor/meteor-feature-requests repo? Thanks!

**Comment by kentonv** [comment]
Thanks for the explanation.

I guess I don't feel the need to turn this into a feature request. Now that I understand the philosophy I know what to expect.
