### ISSUE TITLE
Meteor stuck on extracting process (urigo:static-html-compiler..)

### ISSUE THREAD

**Issue by Kingbalou** [meteor/meteor#9273]
Meteor version : METEOR@1.5.2.2
OS : windows 10

I'm just trying to start the simple todo app
https://www.meteor.com/tutorials/angular/templates

and i'm stuck here 
![image](https://user-images.githubusercontent.com/6079068/32172099-bf490d1e-bd7a-11e7-90e1-c52d80e866a1.png)
It's been launch this morning at 8am and now it's 2pm, still stuck here.
No logs or info so don't know what to do , what is the problem.

Cpu load is about 100% since this morning with some nodejs process but no more info

**Comment by hwillson** [comment]
@Kingbalou This sounds very similar to issue https://github.com/meteor/meteor/issues/7907. Maybe try re-installing Meteor following the instructions listed in https://github.com/meteor/meteor/issues/7907#issuecomment-256871645? Post back and let us know if that helps. Otherwise, you might want to try again when Meteor 1.6 is officially released (hopefully later today/tomorrow). It includes a new Windows installation process that should help.

**Comment by Kingbalou** [comment]
Installing meteor takes years ! (more than 10 minutes to extract ,still extracting and I still count..)

**Comment by Kingbalou** [comment]
Works great with 1.6 meteor release ;) thx
