### ISSUE TITLE
Cannot install Meteor through Chocolatey on Windows 7

### ISSUE THREAD

**Issue by dhulme** [meteor/meteor#9289]
I am unable to install Metoer 1.6 through chocolatey on Windows 7 64-bit. I have removed the old Meteor installer. Below is the output from Powershell. The first time I tried to install, I think I got an error about path being over 240 characters, but I have not been able to reproduce this since. 

```powershell
PS C:\Windows\system32> choco install meteor
Chocolatey v0.10.8
Installing the following packages:
meteor
By installing you accept licenses for the packages.
Progress: Downloading meteor 0.0.1... 100%

meteor v0.0.1 [Approved]
meteor package files install completed. Performing other installation steps.
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

ERROR: A parameter cannot be found that matches parameter name 'file'.
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by dhulme** [comment]
Attached chocolatey log here [chocolatey.log](https://github.com/meteor/meteor/files/1438151/chocolatey.log)

**Comment by abernix** [comment]
Thanks for reporting this.  Do you mind opening this on the https://github.com/meteor/meteor-chocolatey-installer/issues repository instead of here?

I believe this has to do with the version of PowerShell that Windows 7 uses and some of the (more modern?) commandlets that I used.  I don't have a Windows 7 box available, so perhaps you might be able to help take a look too?  (Though I think that I can just run `powershell -Version 2 script.ps1` on more recent PowerShell versions and have the same effect.)

**Comment by dhulme** [comment]
Sure, new issue created here: https://github.com/meteor/meteor-chocolatey-installer/issues/3

Thanks for looking into it.
