### ISSUE TITLE
Meteor APM - Make it more hackable

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9342]
## Problem

Doing this here because I cannot create any issues here: https://github.com/meteor/meteor-apm-agent . Maybe open it for issue creation?

In order to offer support for APM (tracking redis events, performance, applied changes) inside redis-oplog (https://github.com/cult-of-coders/redis-oplog), I need to be able to "hijack" the hijack functions:
https://github.com/meteor/meteor-apm-agent/blob/master/lib/hijack/wrap_observers.js#L4

## A possible solution
https://github.com/meteor/meteor-apm-agent/blob/master/lib/hijack/instrument.js
```
    wrapServer(MeteorX.Server.prototype);
    wrapSession(MeteorX.Session.prototype);
    wrapSubscription(MeteorX.Subscription.prototype);
```
do
```
Kadira.utils.wrapServer() ...
```

I saw the comment about starting instrumentation imediately (https://github.com/meteor/meteor-apm-agent/blob/master/lib/hijack/instrument.js#L38), but can it be defered to Meteor.startup() ? I don't know what implications does it have.

I'm open to any suggestion that would allow us to hack it and I'm willing to write a PR for it.

**Comment by theodorDiaconu** [comment]
I would also be interested if Kadira can accept custom tracking events and automatically aggregate them into meaningful data. This is how you pave the way of integrating other "resource consumers" into the APM. Like certain API calls or lambda function calls, etc.

**Comment by hwillson** [comment]
I'm looking into whether https://github.com/meteor/meteor-apm-agent can be opened for issue creation. More details shortly - thanks!

**Comment by theodorDiaconu** [comment]
@hwillson any updates ?

**Comment by abernix** [comment]
@theodorDiaconu This is blocked on me at the moment, and I'm not sure we're going to open the repository or not.

While we are, in general, all for bug-fixes, I'm not how much additional logic will be added to the current `meteor-apm-agent` at this time, if any.  Especially something which is a monkey-patch to a monkey-patch.

Can you think of another way to implement this?  Can you elaborate?  Also, since this is just the agent, how do would you propose this get introduced into the GUI itself?  Is this just for your own Open-Kadira APM use or is that not necessary for your plans?

**Comment by theodorDiaconu** [comment]
@abernix I understand what you mean. My plan was initially to extend meteor-apm-agent to allow hooking redis-oplog metrics in it. 

But I guess it would be possible to just fork it, and do a meteor-apm-agent-redis-oplog, to allow it to work with Galaxy and other Open Kadria APM.

Is galaxy allowing other apm-agents, or does it require the exact package meteor-apm-agent ?

**Comment by abernix** [comment]
Galaxy should work fine with a fork of `meteor-apm-agent`, if that's what you're asking.  I guess I'm not understanding what Galaxy would do with any additional information on additional metrics is received, even from a fork, since it's not configured to show any new/additional graphs for metrics that might come from other sources, such as Redis Oplog.

Either way, at the current time we're not planning on adding more surface area to the Meteor APM (previous, Kadira) agent.  Again, ideally there would be hooks in Meteor for this rather than monkeypatching all of Meteor's core functionality from the APM agent package — whether that be `meteor-apm-agent`, `meteorhacks:kadira`, or some other fork.  If you're embarking on creating additional metrics in a similar fork, you may also find it beneficial to engage in those conversations.  If you want to draw out what that might look like, feel free to open an issue on the feature request repository!

I really appreciate the work you've put into Redis Oplog.  Maybe I'm misunderstanding how Kadira works (and admittedly, I'm not super familiar with it), but if you're adding new metrics, which would need to be supported by the Meteor APM dashboard in Galaxy, that's a much more in-depth discussion.  There is a lot of aggregation infrastructure for each specific metric, and I'm not sure that it's as easy as sending more metrics and having those just work.  Maybe I'm missing something, but a feature-request would be the place to correct that misunderstanding.  😉
