### ISSUE TITLE
Meteor hangs the first time you try to start it on a new server

### ISSUE THREAD

**Issue by QHose** [meteor/meteor#9389]
Also mentoined in #9321, but I tested this 20 times last week, consistent behavior:

If I try to run my meteor project via the dev client, it hangs

![image](https://user-images.githubusercontent.com/12411165/32957771-f12a31c8-cbbc-11e7-943d-f02823f306ad.png)

Nothings happens, no CPU usage at all...

Steps to reproduce:

blank windows 2012 r2 server
git clone https://GitHub.com/QHose/QRSMeteor.git --branch simplify-settings-file c:\GitHub\QRSMeteor
run meteor npm install
run QRS start.bat (which does meteor run command)

**Comment by bompi88** [comment]
Getting the same behaviour on Windows 10 (running properly "speced" VMs using Virtual box or Parallels), and using Appveyor. Seems that it breaks when it use 7-zip. The amount of time it takes to extract a package, seems to increase for each package extracted. If I run meteor mutliple times, it seems to eventually arrive at the actual building steps and finnish without interuptions.

**Comment by hwillson** [comment]
Is this still happening with Meteor 1.6.1, installed via `choco install meteor`?

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
