### ISSUE TITLE
Roadmap.md is out of date

### ISSUE THREAD

**Issue by vfonic** [meteor/meteor#9404]
Roadmap.md mentions upgrading to Node 8. Now that Meteor 1.6 is out, it should be updated.

Is `Roadmap.md` used anymore?
https://github.com/meteor/meteor/blob/devel/Roadmap.md#upgrade-to-node-8

**Comment by stubailo** [comment]
@vfonic hi! It is used, and we have a recurring meeting to update it. Thanks for reminding that it's fallen behind.

**Comment by hwillson** [comment]
Thanks @vfonic - this is being tracked elsewhere, so expect an update shortly. Closing for now - thanks!

**Comment by vfonic** [comment]
Hi @hwillson! Can you point me to where this is being tracked? Thanks! ❤️

**Comment by hwillson** [comment]
Hi @vfonic - it's being tracked internally by MDG. We discussed this in a recent contributors meeting, so updates will be coming soon. I closed this issue here since tracking internal MDG tasks in this repo is a bit of a challenge; they have an internal process for handling issues/requests like this. I'll keep this closed for now, but I've flagged this issue to make sure it's reviewed again in our next meeting. In the meantime, [episode 22 of Transmission](https://transmission.simplecast.fm) touches on some of Meteor's future plans (e.g. - Meteor as middleware). Thanks!
