### ISSUE TITLE
Stopping Upstart script leads to Zombie process since 1.6 release

### ISSUE THREAD

**Issue by joaomframos** [meteor/meteor#9415]
For the past couple of months we have been using a simple shell script to start our app and we also set an upstart daemon to ensure that the app keeps on running forever.

We have been using this approach until meteor 1.3.4.1 an also used it on previous versions. Ever since we updated to meteor 1.6 we have been facing this issue.

We can start our app just fine and it runs just as expected but as soon as we run service stop the app turns zombie, whilst still having the same PID attached. We can only free it up if we run an upstart cleaner script.

Steps to reproduce this:
1) Create a standard meteor app with 
```shell
meteor create --full FOLDER_NAME”
```
2) Add simple shell script with only “meteor” to startup the app
3) Add a upstart config (like: https://stackoverflow.com/a/38482017) : 
```shell
description "meteor server"

start on (net-device-up and local-filesystems and runlevel [2345])
stop on runlevel [016]

respawn
script
exec /path/to/your/shellScript.sh
end script
```
4) Run the script
```shell
service SERVICE_NAME start
```
5) Ensure that that it’s running
```shell
initctl list | grep SERVICE_NAME
```
6) Stop the app 
```shell
service SERVICE_NAME stop
```
7) Check that the app is zombie

Once again, we have been using this approach for about a year now and it now happens with every app since the meteor tools were updated to 1.6, if not mistaken.

This issue happens on both Ubuntu 14.04 LTS and 16.xx LTS, at least.

**Comment by hwillson** [comment]
@joaomframos Can you share your startup script, the one you're referencing from your upstart script? (so the script that the boilerplate is referring to as `/path/to/your/shellScript.sh`).

**Comment by joaomframos** [comment]
@hwillson As mentioned on "2)", the script only contains a single line "meteor".

You pretty much shellScript.sh:
```shell
meteor
```

**Comment by hwillson** [comment]
Thanks @joaomframos, I just wanted to know the exact contents of the script (in-case you were using any Meteor Tool parameters). When you say the "app is zombie", which process are you referring to - the Meteor Tool node process or the application node process? 

The above being said though, using the Meteor Tool with `upstart` is not common practice. Usually a bundled/deployed version of an application is wired up to be managed by `upstart`, not the Meteor Tool itself. I'm not surprised to hear that a process is left defunct, since the Meteor Tool spawns and manages its own processes. If you're interested in getting this working, I'd suggest reaching out in the [Meteor forums](https://forums.meteor.com) or on [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Someone there might be able to give you a hand with this further. If you think using the Meteor Tool with `upstart` should be properly supported, please consider opening a feature request over in http://github.com/meteor/meteor-feature-requests. Thanks!
