### ISSUE TITLE
choco install error:  "Couldn't find bootstrap tarball to extract"

### ISSUE THREAD

**Issue by GoaGit** [meteor/meteor#9468]
**Action**: install Meteor on a Windows machine

**Operating system**: Windows 10 64-bit

**Command line tool**: Powershell version 5.1 (run as admin)

When trying to install meteor (uninstalled old Windows meteor installer first) on a Windows machine, the following error message is thrown. Meteor is not installed.

I can't find a related issue with this particular error message. Any suggestions for me how I can resolve this issue?

```
PS C:\> choco install meteor
Installing the following packages:
meteor
By installing you accept licenses for the packages.

meteor v0.0.2
The package meteor wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Extracting C:\Users\<USER>\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteorInstall.zip to C:\Users\<USER>\AppData\Local\Temp\meteor\0.0.2...
 7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
 Processing archive: C:\Users\<User>\AppData\Local\Temp\chocolatey\meteor\0.0.2\meteorInstall.zip
 Extracting  meteorInstall
 Everything is Ok
 Size:       676034560
 Compressed: 150549566
 C:\Users\<USER>\AppData\Local\Temp\meteor\0.0.2
 Couldn't find bootstrap tarball to extract
 At C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1:72 char:3
 +   throw "Couldn't find bootstrap tarball to extract"
 +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (Couldn't find b...ball to extract:String) [], RuntimeException
     + FullyQualifiedErrorId : Couldn't find bootstrap tarball to extract
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - meteor
```

The chocolately log shows the same error message:

```
[ERROR] -  Couldn't find bootstrap tarball to extract
[ERROR] -  At C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1:72 char:3
[ERROR] -  +   throw "Couldn't find bootstrap tarball to extract"
[ERROR] -  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR] -      + CategoryInfo          : OperationStopped: (Couldn't find b...ball to extract:String) [], RuntimeException
[ERROR] -      + FullyQualifiedErrorId : Couldn't find bootstrap tarball to extract

```

**Comment by GoaGit** [comment]
I removed chocolately from my computer and reinstalled it. That did the trick. I was not experiencing any problems with the chocolately installation until trying to install Meteor. So unfortunately I cannot be more specific about the issue and why it works now. But this step my be sufficient for others that run into the same problem.

**Comment by abernix** [comment]
Strange.  Thanks for filing the issue for the next person.  If anyone else runs into this issue, please do let us know!

**Comment by salamander194** [comment]
I have tried 12 (twelve) times now to install version 1.6 on Windows 7 Enterprise running Powershell with administrator rights. The download mostly fails before it is complete, but when it does complete, I get the same error as above. The file is there, but the issue seems to be folder permissions.

Please, please, PLEASE give us another way of installing; I am about to give up on Meteor

**Comment by abernix** [comment]
@salamander194 This issue is closed, so please open a new issue.  Additionally, in the new issue please provide some additional details, such as:

* What version of Chocolatey are you using? (`choco --version`)
* The output of the installation log with the verbose (`-v`) and debug (`-d`) flags enabled.  For example:

      choco install meteor -dvy

If the download is regularly failing before the installation is complete, that seems more like a problem with the connection and even a different Meteor installer wouldn't solve that problem.  Hopefully with more details, we can help resolve the problem for you!  But again, please open a new (your own) issue since the original poster of this issue reported that the problem was resolved by re-installing Chocolatey (suggesting that your problem is different and/or more complicated).

Thanks!

**Comment by abernix** [comment]
@salamander194 Also, please open the issue on the `meteor` Chocolatey installer repository, which can be found at https://github.com/meteor/meteor-chocolatey-installer.
