### ISSUE TITLE
native async/await support

### ISSUE THREAD

**Issue by staeke** [meteor/meteor#9473]
### This bug report should include:
- [X] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [X] The version of Meteor showing the problem.
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
- [X] The operating system you're running Meteor on.
- [X] The expected behavior.
- [X] The actual behavior.
- [X] A **simple** reproduction!
      (example: A GitHub repository that anyone can clone to observe the problem.)

**Meteor version:** 1.6.0.1
**OS**: Mac OSX 10.13.1

By reading this https://blog.meteor.com/announcing-meteor-1-6-abf30f29e2c6, I was under the impression that native async/await was supported from Meteor 1.6. Depending on if that' the case, you could argue that this should instead be a feature request. If that's the case, please let me know and I'll report it there instead.

Consider this code
```js
const pDelay = delay => new Promise(res => Meteor.setTimeout(res, delay));

(async () => {
    await pDelay(0);
    await pDelay(0);
})();
```

If you compile (with appropriate babel/typescript settings) to equivalent target of Node 8.8.1, i.e. with native async/await support, this fails with 

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

Obviously there's now no hook for calling `Meteor.bindEnvironment` correctly. I suppose this can be done with async-hooks in Node 9. I don't know of other ways to fix it.

What's your take? Bug? Feature request?

**Comment by benjamn** [comment]
In order to run `async` functions and `Promise` callbacks in a `Fiber`, Meteor still does compile `async` functions for server-side code. However, the compilation should have a minimal impact on debugging `async` functions, unlike previous Babel compilation strategies.

A good way to see how that works is to put the following code in `server/main.js`:
```js
const pDelay = delay => new Promise(res => Meteor.setTimeout(res, delay));

(async function f(delay) {
  console.log(String(f)); // Show the actual code.
  await pDelay(delay);
  await pDelay(delay);
})(10);
```
The resulting code of `f` looks like this:
```js
function f(delay) {
  return Promise.asyncApply(() => {
    console.log(String(f)); // Show the actual code.
    Promise.await(pDelay(delay));
    Promise.await(pDelay(delay));
  });
}
```
Although this is not purely "native," it does solve the problem you mentioned (the code runs in a `Fiber`), and replacing `await x` expressions with `Promise.await(x)` is much less invasive than compiling the code down to a generator function (good luck ever debugging that!).

> If you compile (with appropriate babel/typescript settings) to equivalent target of Node 8.8.1, i.e. with native async/await support

Just to be clear, that's not what Meteor does. Your thought experiment is reasonable, but the equivalence doesn't hold.

If you're confused how a function like `Promise.await` could possibly implement the behavior of an `await` expression, well, that's the magic of `Fiber`s. The crucial reason why we use `Promise.await` instead of just using `await` expressions is to make sure a `Fiber` is used when calling back into the function, after the awaited `Promise` resolves. The `Promise.asyncApply` function is necessary to ensure the first part of the function (before the first `await`) runs synchronously in a new `Fiber`.

In Meteor 1.6.2, thanks to https://github.com/meteor/meteor/pull/9439, we will stop compiling `async` functions at all for _client_ code (where `Fiber`s don't matter), as long as the browser you're using has native support for `async` functions—as 73% of browsers currently do!

**Comment by benjamn** [comment]
Also note that purely native `async` functions would work just fine as long as they don't call any Meteor functions that call `Fiber.yield`, but of course that's hard to anticipate, so we've erred on the side of safety.

**Comment by staeke** [comment]
Big thanks for your thorough reply @benjamn . It's so often in projects that owners don't reply in long times. Really appreciate it!

Getting to the bottom, and being more specific though - I realize I left out important details. Apologies. My use case is typescript, and I'm using `target: es2017` to compile to native async/await. But, that doesn't seem to work. The end code produces doesn't include `Promise.await`/`Promise.apply`

What's the solution here? Am I missing something? Should the typescript-compiler maybe include a pre/post-processing step with the `Promise.await/apply` processing?

**Comment by benjamn** [comment]
That's a good question. I would like the answer to be "no, TypeScript shouldn't have to worry about this," though right now we implement this logic in the `ecmascript` and `babel-compiler` packages, which are not used for `.ts` files.

The best way to achieve this common functionality might be to re-compile the output of all compiler plugins (e.g., `barbatus:typescript`, `ecmascript`, `coffeescript`, etc.) when building for the server platform.

While we're at it, we could handle `import` and `export` syntax at this level, too, so that TypeScript could generate native ECMAScript module syntax, and Meteor would just handle it.

**Comment by staeke** [comment]
@benjamn sounds like a good plan!
