### ISSUE TITLE
Unable to update from 1.4.4.4 to 1.4.4.5 on Windows

### ISSUE THREAD

**Issue by joshuadavidson** [meteor/meteor#9474]
### OS
Windows 10 Pro, Version 1709, 64-bit.

### My Steps
Below are the steps that I took when encountering this issue on our app.
1. Currently running a 1.4.4.4 app and tried to `meteor update --patch` to 1.4.4.5 for the security patch in cmd as well as powershell.
2. Got an unintelligible error due to Windows improper console logging (#6785). 
3. Decided to start fresh by uninstalling meteor from Add Remove Programs (I was on an pre 1.5 version). 
4. Used choco to install the new 1.6.0_1 meteor tool.
5. Manually installed 1.4.4.5 by running `meteor update --release 1.4.4.5` outside of my application directory.
6. Attempted to re-run `meteor update --patch` in my application directory.
7. Received the following error : 
```
C:\Users\JoshDavidson\AppData\Local\.meteor\packages\meteor-tool\1.4.4_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: missing tool for os.windows.x86_32 in meteor-tool@1.6.0_1
    at Error (native)
    at springboard (C:\tools\cli\main.js:491:11)
    at C:\tools\cli\main.js:1501:7
```
### Reproduction
I attempted to update from a newly created 1.4.4.4 app to 1.4.4.5 and ran into the same issues. Here is what I did to reproduce:
1. Created a new 1.4.4.4 app by running `meteor create test --release 1.4.4.4`.
2. Tried to update the test app by running `meteor update --patch`.
3. Same error received.

**Any help would be appreciated. I would like to get this security patch in before Christmas.**

**Comment by joshuadavidson** [comment]
Looks like it may be a relative vs absolute path issue as it is looking for `C:\tools\cli\main.js` rather than `C:\Users\JoshDavidson\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\tools\cli\main.js`? Just my two cents.

**Comment by abernix** [comment]
Installing Meteor with Chocolatey (via `meteor install choco`), should automatically uninstall any and all previous versions of Meteor, even if it was installed with the older `InstallMeteor.exe` (GUI installer).  This could have failed, say, if the files were in use (for example, if `meteor` was running in another window).

The output you've provided above is particularly curious because you're saying you "Received the following error", and that error includes a "1.4.4.4" version of Meteor (which shouldn't even have been downloaded, based on the information you provided):

> ```
> C:\Users\JoshDavidson\AppData\Local\.meteor\packages\meteor-tool\1.4.4_4\mt-os.windows.x86_32\...
>                                                                  ^^^^^^^
> ```

Could you try uninstalling Meteor again, this time by:

* Ensuring you have no `meteor` instances running.
* Uninstall with `choco uninstall meteor -y`
* Ensure that `C:\Users\JoshDavidson\AppData\Local\.meteor` (aka `%LocalAppData%\.meteor`) is completely deleted—if not, restart and delete it.
* Install with `choco install meteor -y`
* Create a test app with `meteor create test-new-app`.  At this point, you should only have a single version of Meteor in your `C:\Users\JoshDavidson\AppData\Local\.meteor\packages\meteor-tool\` directory (as of this writing, it would be `1.6.0_1`).
* Try updating your other application to exactly Meteor 1.4.4.5 with `meteor update --release 1.4.4.5`.  If this fails, try resetting the app first with `meteor reset` (which will remove your development database, but will also remove the possibly problematic `dev_bundle` junction in your app's `.meteor/local` directory, as well as any residue in other `.meteor/local/` directories.

Let us know how that goes.  Hope this helps!

**Comment by joshuadavidson** [comment]
Thanks for the quick reply. 👍 I'll give it a whirl tomorrow.

**Comment by joshuadavidson** [comment]
I followed your outlined steps and ensured that choco my `%LocalAppData%\.meteor` folder was deleted before doing a fresh install using choco. I was able to create and run the `test-new-app` via the `meteor create test-new-app` command. But when I tried to run `meteor update --release 1.4.4.5` in my application directory I got the following output:
```
This project uses Meteor 1.4.4.5, which isn't available on this platform. To work with this app on all supported platforms, use
meteor update --release METEOR@1.6.0.1 to pin this app to the newest compatible release.
```
I ran meteor reset which immediately kicked off a download task in the CLI for the 1.4.4.4 meteor-tool:
```
Downloading meteor-tool@1.4.4_4...        [======                    ] 23% 45.3s
```
I let it run it's course and tried the `meteor update --release 1.4.4.5` command again only to get the same error: 
```
This project uses Meteor 1.4.4.5, which isn't available on this platform. To work with this app on all supported platforms, use
meteor update --release METEOR@1.6.0.1 to pin this app to the newest compatible release.
```
Not able to get anywhere, I then attempted to run the `meteor update --patch` command as suggested in the CLI only to get the exact same error:
```
C:\Users\JoshDavidson\AppData\Local\.meteor\packages\meteor-tool\1.4.4_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: missing tool for os.windows.x86_32 in meteor-tool@1.6.0_1
    at Error (native)
    at springboard (C:\tools\cli\main.js:491:11)
    at C:\tools\cli\main.js:1501:7
```
Any ideas?

**Comment by abernix** [comment]
I realize this isn't as smooth as it should be, but can you perform the same steps again, but right before you run the `meteor reset`, can you change the contents of your `.meteor/release` file to `METEOR@1.4.4.5`?

Also, is there anything keeping you from upgrading to Meteor 1.6?  There really should be too much resistance in that upgrade, and the improvements of a truly 64-bit experience are almost certainly worth it for a Windows developer.  We put a lot of work in on Windows for Meteor 1.6, and we can't backport that work to Meteor 1.4.x.  Even if you're installing a 64-bit version, you're ultimately going to be a 32-bit version of that older Meteor/Node since that release line was never designed for it.

**Comment by joshuadavidson** [comment]
No such luck with changing the `.meteor/release` file. We attempted 1.5 back when it came out but immediately ran into issues so upgrades went to the back burner. I'll give 1.6 a try as it looks like 1.4.4.5 isn't gonna happen. I can't be the only one wanting to upgrade to 1.4.4.5--maybe the only windows guy in the meteor universe 😕.

**Comment by abernix** [comment]
I think there are a couple options here, but if you're not actually making the jump to Meteor 1.6 yet, I think the best option is probably for you to just install the 32-bit version through and through— including the initial install with Chocolatey.  You're not going to reap any benefits from the 64-bit version until your apps themselves make the upgrade to Meteor 1.6.x.  Hopefully you can figure out what those blockers are—please open issues if you have anything that's not resolvable!

To enact on this, the easiest solution is to just install the 32-bit of 1.6.0.1 with Chocolatey (rather than the 64-bit, which is what you'd be receiving by default), which will then springboard (the process of changing Meteor versions automatically) to the 32-bit of both 1.4.4.4 and (eventually) 1.4.4.5.  To do so, you can run:

    choco install meteor -y --x86

Thereafter, I expect you should be able to go into the existing application directory and run `meteor update --release 1.4.4.5` without problem. 
 When you eventually make the upgrade to Meteor 1.6.0.1+, you'll want to reinstall with `choco uninstall meteor -y` and the same install command without `--x86`.

**Comment by joshuadavidson** [comment]
Well, I'm running into all sorts of issues trying to upgrade. I created a new issue (#9476) documenting an error in 1.6.0.1 that prevents me from running the app. I'll try your 32bit suggestion on Monday.

**Comment by joshuadavidson** [comment]
Success! I was able to update my 1.4.4.4 app to 1.4.4.5 using the 32-bit version of the 1.6.0.1 Meteor tool.

Here are the steps I ran through if anyone else runs into this:
1.  Completely uninstalled meteor with `choco meteor uninstall` and ensured `%LocalAppData%/.meteor ` was gone.
2. Deleted .meteor/local folder from my app (for that freshly cloned repo feeling 😉).
3. Installed the 32-bit version of Meteor 1.6.0.1 with `choco install meteor -y --x86`.
4. Successfully started my 1.4.4.4 app with `meteor run --settings=settings-local.json` (which downloads the 1.4.4.4 tool). This step seemed to be key.
5. Successfully updated using `meteor update --release 1.4.4.5`. Note: CLI didn't show that process completed but the versions, release, and package files showed updated.
6. Successfully started my 1.4.4.5 app with `meteor run --settings=settings-local.json`.

@abernix thanks for the help and feel free to close if there are no actions for MDG.

**Comment by ziwer1** [comment]
@abernix followed the instructions in your first comment. 
After running
`meteor create test-new-app`

I got the following output:

`This project uses Meteor 1.6.0.1, which isn't available on Windows. To work with this app on all supported
platforms, use meteor update --release METEOR@1.6.0.1 to pin this app to the newest Windows-compatible release.`

I am running windows 7 on a 32 bit laptop.

**Comment by hwillson** [comment]
Closing as this issue was resolved in https://github.com/meteor/meteor/issues/9474#issuecomment-352539834. 

@ziwer1 If you're still encountering problems, please consider opening a separate issue.
