### ISSUE TITLE
Unable to update meteor from 1.5 to 1.6.0.1

### ISSUE THREAD

**Issue by gauravkadam** [meteor/meteor#9499]
Hi,

I want to update my existing codes meteor version from 1.5 to 1.6.0.1
I have tried with "meteor update" command and manually update version in "release" file but o wont work.

please help me to fix this issue so i can work on meteor 1.6.0.1

![image](https://user-images.githubusercontent.com/16930579/34356727-62d7d862-ea66-11e7-8545-e125304143d3.png)

npm version : 5.5.1

node version : 9.3.0

**Comment by pkhand0** [comment]
@ Team - Request you to please update us on this.

**Comment by hwillson** [comment]
Have you tried a `meteor reset` after updating? (usual warning - will wipe your local DB)

**Comment by gauravkadam** [comment]
Hi @hwillson ,

I did "meteor reset" as well after updating version but still facing same issue.

**Comment by hwillson** [comment]
Can you try removing/re-adding `barbatus:typescript`? So:

```
meteor remove barbatus:typescript
meteor add barbatus:typescript
```

**Comment by crapthings** [comment]
can u try

1. open .meteor/packages, remove all @version by manually
2. delete this file .meteor/versions then meteor --verbose

**Comment by gauravkadam** [comment]
Tried both solution still result is same.

**Comment by hwillson** [comment]
Thanks @gauravkadam - it would be great to know what happens when you rule out the `barbatus:typescript` plugin. Any chance you could try removing it and see what happens? I realize removing a TypeScript build plugin is not trivial (since your `.ts` files will no longer be picked up properly), but it would be a helpful troubleshooting step. 

Also - moving forward, is there any chance you can supply a small runnable reproduction that demonstrates this issue?

**Comment by hwillson** [comment]
We haven't heard back regarding https://github.com/meteor/meteor/issues/9499#issuecomment-355612418, so I'll close this for now. If you have additional troubleshooting details to share, please post back and we'll re-open this issue. Thanks!
