### ISSUE TITLE
App JS bundle contains ES6 code coming from accounts-xxx packages

### ISSUE THREAD

**Issue by jancurn** [meteor/meteor#9506]
Looking at the JS bundle generated by Meteor 1.6.0.1, I see it contains the `const` keyword in the code coming from the accounts-xxx packages. For example:

```js
if (c.oauth.registerService("facebook"),
        e.isClient) {
            const o = function(e, o) {
                o || "function" != typeof e || (o = e,
                e = null);
                var a = c.oauth.credentialRequestCompleteHandler(o);
                n.requestCredential(e, a)
            };
            c.registerClientLoginFunction("facebook", o),
            e.loginWithFacebook = function() {
                return c.applyLoginFunction("facebook", arguments)
            }
        }
```

This code is generated from https://github.com/meteor/meteor/blob/master/packages/accounts-facebook/facebook.js 

Similar problem is with accounts-google, accounts-github etc.

I don't know whether Meteor's build system transpiles the Meteor packages from ES6 to ES5, but IMHO the resulting JS bundle should not contain any ES6 code. For example, this breaks PhantomJS UI tests as it doesn't support ES6.

A simple fix would be just to change `const` to `var` in the affected packages.

**Comment by klaussner** [comment]
The `const` was added to the accounts packages in [this commit](https://github.com/meteor/meteor/commit/1c9eacaeb882f9f7b70a4a1e8b7e8d4cf7bd9161#diff-8d80b31ff289a12c24554ea74ad96320) but Meteor doesn't transpile the ES2015+ code because they don't depend on the `ecmascript` package. We could either replace `const` with `var` as you suggested or add `api.use("ecmascript");` to `accounts-{facebook, github, google, meetup, meteor-developer, twitter, weibo}`. Not sure which is better. :smile:

**Comment by hwillson** [comment]
Great catch guys - thanks! Since `accounts-base` and `accounts-password` are both explicitly depending on `ecmascript` already, we should be safe to add `ecmascript` to the other packages. I've submitted PR #9507 to take care of this. Thanks again!
