### ISSUE TITLE
1.6.1 wrong manifest url for cordova will break hot code reload between <1.6.1 and >=1.6.1

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#9526]
While fixing problems with https://github.com/meteor/cordova-plugin-meteor-webapp i realized that hot code reload will not work between apps created before 1.6.1 and with backends updated to 1.6.0.

the reason is https://github.com/meteor/meteor/pull/9424 and https://github.com/meteor/meteor/pull/9424https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/ios/AssetBundleManager.swift#L93

old apps can't get the new manifest.json (also new apps can't get an old manifest)

EDIT: actually, the problem lies somewhere else in the code. with 1.6.1 the manifest gets delivered from
`__cordova/__meteor__/webapp/manifest.json`

instead of

`__cordova/manifest.json`

**Comment by benjamn** [comment]
This is most likely due to https://github.com/meteor/meteor/pull/9424.

**Comment by benjamn** [comment]
This should be fixed in `1.6.1-rc.4`. Specifically (cc @hwillson @abernix et al.), the manifest will now be served from either `/__browser/manifest.json` (for `web.browser`) or `/__cordova/manifest.json` (for `web.cordova`), thus preserving Cordova URLs from before #9424.

Thanks for all your help in this area @macrozone!
