### ISSUE TITLE
Unecessary check in Mongo.Collection constructor.

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#9531]
https://github.com/meteor/meteor/blob/devel/packages/mongo/collection.js#L29

```js
    if (! (this instanceof Mongo.Collection))
      throw new Error('use "new" to construct a Mongo.Collection');
```

change was done here: https://github.com/meteor/meteor/commit/6fcf190bb489db19dc6b13052dc1391cf9209cb4#diff-9d3eee78c27b2ff499f0abf2e53eb3c7

Those lines were used to counter the fact that people forgot `new`. This is prior-to-ES6 boilerplate code that we used for mis-usage. If I want for example to wrap Mongo.Collection and override Mongo.Collection  I have no way to do it like this.

Just remove those lines and all is good.

Related:
https://github.com/rclai/meteor-collection-extensions/issues/14
https://github.com/cult-of-coders/redis-oplog/issues/227

**Comment by benjamn** [comment]
The first bug you linked to is displaying a similar but different error that would *not* be fixed by removing those two lines. In fact, the error is coming from the JS runtime itself, because native ECMAScript classes must be instantiated with `new`. In other words, this problem is not going away, because it has now been baked into the language, for better or worse.

To your question of how to wrap `Mongo.Collection` without running into these errors, you should be careful to subclass `Mongo.Collection` using the `extends` syntax, so that `this instanceof Mongo.Collection` will continue to be true for your subclass. If there's a bug here, I think it's that the `instanceof` check uses the current value of `Mongo.Collection`, rather than the original class, which might be a problem if you reassign `Mongo.Collection` to something else.

**Comment by theodorDiaconu** [comment]
@benjamn I understand that the first problem will not be solved. What would be the purpose of the check then ? It's like you define a class, and inside the constructor you verify that `this` is `instanceof` the current class... which is strange.

As I mentioned, those 2 lines, protected us in the past for using Functions as factories. But right now it's no longer the case. 

Even if you do the check with a local variable it still does not make sense.

**Comment by benjamn** [comment]
You're right. Can you submit a quick PR to remove the `instanceof` check? If not, I'll do it sometime soon.

**Comment by theodorDiaconu** [comment]
Ok
