### ISSUE TITLE
1.6.0.1 Cannot use linked modules on the server

### ISSUE THREAD

**Issue by Dartv** [meteor/meteor#9532]
When using yarn link with a local module, and then importing the module on the server error is thrown.
I assume this is the problem with ramda, but on the client everything works fine.
Also tested it with node, everything is ok.

Expected behavior:
Should log `hello world` to the console

Actual behavior:
Error is thrown:
```js
W20180112-16:19:19.058(2)? (STDERR) Error: Cannot find module './F'
W20180112-16:19:19.059(2)? (STDERR)     at makeMissingError (packages\modules-runtime.js:231:12)
W20180112-16:19:19.059(2)? (STDERR)     at require (packages\modules-runtime.js:241:19)
W20180112-16:19:19.059(2)? (STDERR)     at index.js (packages\modules.js:382:33)
W20180112-16:19:19.060(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180112-16:19:19.060(2)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180112-16:19:19.061(2)? (STDERR)     at index.js (packages\modules.js:353:17)
W20180112-16:19:19.061(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180112-16:19:19.062(2)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180112-16:19:19.062(2)? (STDERR)     at main.js (server/main.js:1:119)
W20180112-16:19:19.063(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
```

Reproduction: https://github.com/Dartv/meteor-link-issue
```
cd hello-module
yarn link
cd ../app
yarn install
yarn link hello-module
yarn start
```

Tested on both macOS and Windows 10

**Comment by benjamn** [comment]
Thanks for including a reproduction here. I believe this will work if you simply add `hello-module` to the `"dependencies"` section of `app/package.json`. Meteor deliberately ignores extraneous `node_modules` when building your app, since those dependencies will not be reliably recreated when anyone else runs `meteor npm install` (including you, at some later time).

Feel free to reopen this issue if the problem persists after putting `hello-module` into `package.json`.
