### ISSUE TITLE
Meteor 1.6.0.1 does not work on Centos 7

### ISSUE THREAD

**Issue by fabianfabian** [meteor/meteor#9541]
Node version: 8.9.3

Raw process output:
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/www/vhosts/myapp/1516119546/bundle/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node)
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/vhosts/myapp/1516119546/bundle/programs/server/node_modules/fibers/fibers.js:24:38)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

Last working version for me was Meteor 1.5.2.2 with Node 6.12.2

Similar problem described here and it seems glibc will not change on Centos 7:
https://centos.org/forums/viewtopic.php?f=47&t=64860

For now I will have to downgrade back to 1.5.2.2 and Node 6.12.2.

**Comment by benjamn** [comment]
Possibly related: https://github.com/meteor/meteor/issues/9068

**Comment by fabianfabian** [comment]
-bash-4.2$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by benjamn** [comment]
Am I right to assume that CentOS 7 is your deployment environment, not your development environment?

**Comment by fabianfabian** [comment]
Yes, I run meteor build on OSX 10.13.1 and then deploy on CentOS 7

**Comment by benjamn** [comment]
For what it's worth, we compile the `dev_bundle` (which contains binary dependencies like Node, Mongo, and `fibers`) for Linux using CentOS 6.4 with `g++ (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)` and GLIBC 2.12, in an attempt to provide backwards compatibility for older Linux distributions. That should be compatible with CentOS 7 and GLIBC 2.17, so I think the problem may lie with precompiled `fibers.node` binaries that are downloaded by the `fibers` build script.

If you have control over environment variables in your deployment environment when you run `npm install` in `bundle/programs/server`, I would recommend setting
```
export METEOR_NPM_REBUILD_FLAGS=--build-from-source
```
in order to force `fibers` to be rebuilt. See [this code](https://github.com/meteor/meteor/blob/79b5ed8e6524ccbd573c1900188090ec13f81fb9/tools/static-assets/server/npm-rebuild-args.js#L13) for implementation details.

Happy to elaborate if these suggestions don't make sense.

**Comment by fabianfabian** [comment]
Thanks, I will try this on our next deployment.

**Comment by fabianfabian** [comment]
Setting the environment variable didn't force fibers to rebuild. What I did now is:
- Delete node_modules/fibers/bin/linux-x64-57/fibers.node
- Rebuild fibers with node-gyp rebuild
- Copy fibers/build/Release/fibers.node to fibers/bin/linux-x64-57/fibers.node

This worked.

**Comment by hshaterian** [comment]
@abianfabian @benjamn

I have same probem here, from 'fibers':

`_Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found_`

this is my system specification:

- centos 6.8
- meteor 1.6.1
- node 8.9.4
- gcc - g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
- glibc-2.12-1.209.el6_9.2.i686

how can i rebuild fibers? can you help me?

**Comment by fabianfabian** [comment]
@hshaterian 

On your server delete the file programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node

Then go in the directory programs/server/node_modules/fibers/ and run: node-gyp rebuild
(if command not found run: npm install -g node-gyp)

Then move the rebuilt binary to the right place: mv build/Release/fibers.node bin/linux-x64-57/

**Comment by hwillson** [comment]
This issue is related to factors outside of Meteor's control. Anyone encountering this issue should try the solutions outlined in https://github.com/meteor/meteor/issues/9541#issuecomment-359259999. Thanks!
