### ISSUE TITLE
npm build commands do not exist

### ISSUE THREAD

**Issue by nhhockeyplayer** [meteor/meteor#9546]
platform meteor-1.6.0.1
windows 7
node v9.3.0
npm 5.6.0

the readme file documents a build command... 
but no build command exists in package.json

to what extent is new interest to determine what does what

any attempts to build using angular-cli fail

how to build
I cannot build

**Comment by hwillson** [comment]
I'm really not sure what you're trying to do here @nhhockeyplayer, or what the actual problem is. Can you try explaining your issue a bit differently (and more concisely), preferably with a small runnable reproduction that shows the problem? See [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor) for more info.

**Comment by nhhockeyplayer** [comment]
Ok I am unable to invoke a build

the readme specifies a npm build script
but in the package.json none exists

what is the build command for the project

thanks for understanding

**Comment by benjamn** [comment]
@nhhockeyplayer Because your questions aren't making a whole lot of sense (our README doesn't say anything about an "npm build script," for example), it sounds like you must be new to Meteor and this repository, or you're running some sort of script that generates nonsensical comments.

If you're actually here to learn, the Guide is a great place to start: https://guide.meteor.com
