### ISSUE TITLE
Can't update packages

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#9569]
After update to Meteor 1.6.x, `meteor update --all-packages` just keeps giving the same list of packages that have newer versions and asking me to run `meteor update --all-packages`.

Maybe related: https://github.com/meteor/meteor/issues/9271, https://github.com/meteor/meteor/issues/9284 (but coffeescript package not involved)

Noticed this in two different apps.

Reproduce:

```
git clone git@github.com:aldeed/meteor-collection2-core.git
cd meteor-collection2-core
git checkout meteor-package-update-issue
cd tests
meteor update --all-packages
meteor update --all-packages --allow-incompatible-update
```

Nothing works. I tried `meteor update <pkg>` on a couple of the packages and that didn't work also. Tried deleting the versions file and it was rebuilt with the same issue.

Output:

```
Your top-level dependencies are at their latest compatible versions.

The following top-level dependencies were not updated to the very latest version available:
 * dynamic-import 0.2.1 (0.3.0 is available)
 * ecmascript 0.9.0 (0.10.0 is available)
 * es5-shim 4.6.15 (4.7.1 is available)
 * meteor-base 1.2.0 (1.3.0 is available)
 * mongo 1.3.1 (1.4.2 is available)
 * standard-minifier-css 1.3.5 (1.4.0 is available)
 * standard-minifier-js 2.2.3 (2.3.1 is available)

Newer versions of the following indirect dependencies are available:
 * autoupdate 1.3.12 (1.4.0 is available)
 * babel-compiler 6.24.7 (7.0.0 is available)
 * babel-runtime 1.1.1 (1.2.0 is available)
 * boilerplate-generator 1.3.1 (1.4.0 is available)
 * callback-hook 1.0.10 (1.1.0 is available)
 * check 1.2.5 (1.3.0 is available)
 * ddp-client 2.2.0 (2.3.1 is available)
 * ddp-common 1.3.0 (1.4.0 is available)
 * ddp-server 2.1.1 (2.1.2 is available)
 * diff-sequence 1.0.7 (1.1.0 is available)
 * ecmascript-runtime-client 0.5.0 (0.6.0 is available)
 * http 1.3.0 (1.4.0 is available)
 * id-map 1.0.9 (1.1.0 is available)
 * minifier-css 1.2.16 (1.3.0 is available)
 * minifier-js 2.2.2 (2.3.1 is available)
 * ordered-dict 1.0.9 (1.1.0 is available)
 * random 1.0.10 (1.1.0 is available)
 * reload 1.1.11 (1.2.0 is available)
 * retry 1.0.9 (1.1.0 is available)
 * url 1.1.0 (1.2.0 is available)
 * webapp 1.4.0 (1.5.0 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
```

@benjamn

**Comment by coagmano** [comment]
Isn't this because the new versions are for 1.6.1, which hasn't been marked as recommended in the CLI yet?

You could try forcing it to update to 1.6.1 then update packages?
```
meteor update --release 1.6.1 --all-packages
```

**Comment by hwillson** [comment]
Thanks @coagmano - exactly right. See https://github.com/meteor/meteor/issues/2500#issuecomment-359962541. 1.6.1 hasn't been officially recommended yet, but it's available (and should be recommended soon). Let us know if that helps @aldeed - thanks!

**Comment by aldeed** [comment]
OK, that makes some sense, but I don't think it's necessarily logical. If the individual packages are truly individual, and the updates to them are minor/patch, shouldn't I be able to update one or more of them without worrying about what Meteor version I'm on?

Also, I created this issue more so that the output of the command could maybe be updated to explain better. So if this behavior is desirable and remains, I'd still request one of the following:
- Don't even list the newer versions as available since you can't get them on your current Meteor version
- Or list them, but say that you'll need to pass `--release` to be able to use `--all-packages`.

**Comment by benjamn** [comment]
> If the individual packages are truly individual, and the updates to them are minor/patch, shouldn't I be able to update one or more of them without worrying about what Meteor version I'm on?

For core packages, Meteor constrains the major *and minor* versions for a given release. In practice, we bump the minor versions of core packages whenever there's a change that should not be available unless you're on the new Meteor release. The minor versions of all these packages were bumped in Meteor 1.6.1. There was one major bump, too: `babel-compiler@7.0.0`. So that's what's happening here.

For packages that aren't in https://github.com/meteor/meteor/tree/devel/packages (i.e., non-core packages), there's usually more flexibility. Specifically, minor versions can change as long as minimum version constraints are met. So your expectation above holds for most non-core packages. I say "most" because it's possible someone is using exact version constraints (`@=`), though that's relatively rare.

I'm sympathetic to both of your proposed solutions, though I will note that this should be less of a problem once Meteor 1.6.1 is recommended as the latest release. The delay there is mostly because we need to write a blog post explaining the Babel 7 upgrade.

**Comment by benjamn** [comment]
Also note that you can always clone a package into your local `<app>/packages/` directory in order to change its version constraints or force a particular version of the package. That's not super easy, of course, but I'd say it should be somewhat difficult to disregard version constraints.

**Comment by aldeed** [comment]
Thanks for the explanation @benjamn. Yeah, I guess I would say if it's easy to update the messaging so that it doesn't say "To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`, or just run `meteor update --all-packages`" when that isn't actually possible, then it seems like a good idea. If it's not easy, then feel free to close this and hopefully someone can at least find it as reference.

**Comment by hwillson** [comment]
While we think implementing the suggestion in https://github.com/meteor/meteor/issues/9569#issuecomment-360257110 would be a great addition to the Meteor project, we're going to close this issue for now due to inactivity (see the [bug issue lifespan](https://github.com/meteor/meteor/blob/a770e9959fec4e499a8f8c01dac5c211808c72e3/ISSUE_TRIAGE.md#bug-issue-lifespan) section of Meteor's traige doc for more information). If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!

**Comment by kjrhody** [comment]
I see that this is closed, but I'm currently having the same issue and am not sure where to post for help. I'm trying to run a local dev instance of meteor but it won't build or let me run any updates.

`=> Errors while initializing project:         
                                              
While selecting package versions:
error: Conflict: Constraint aldeed:collection2@3.0.0 is not satisfied by aldeed:collection2 2.7.1.
Constraints on package "aldeed:collection2":
* aldeed:collection2@2.3.2 <- msavin:mongol 2.0.0
* aldeed:collection2@3.0.0 <- aldeed:autoform 6.3.0
* aldeed:collection2@2.5.0 <- sach:flow-db-admin 1.1.5

Conflict: Constraint aldeed:autoform@5.7.1 is not satisfied by aldeed:autoform 6.3.0.
Constraints on package "aldeed:autoform":
* aldeed:autoform@=6.3.0 <- top level
* aldeed:autoform@4.0.0 || 5.0.0 || 6.0.0 <- aldeed:autoform-bs-button-group-input 1.0.3
* aldeed:autoform@5.7.1 <- sach:flow-db-admin 1.1.5
* aldeed:autoform@4.0.0 || 5.0.0 || 6.0.0 <- aldeed:autoform-bs-datetimepicker 1.0.7
* aldeed:autoform@6.0.0 <- aldeed:autoform-bs-datepicker 2.0.0`
