### ISSUE TITLE
Uncaught TypeError: o is not a constructor [M@1.6.1 es5-shim@4.7.1 error]

### ISSUE THREAD

**Issue by flean** [meteor/meteor#9572]
Meteor 1.6.1
After updating when the Cordova apps would request the hot code update I would get the error
with es5-shim 4.7.1
I went back to es5-shim 4.7.0 and had no problems
```
b49a89a….js?meteor_js_resource=true:279 Uncaught TypeError: o is not a constructor
   (anonymous function) @ b49a89a….js?meteor_js_resource=true:279
   t @ b49a89a….js?meteor_js_resource=true:279
   es5-shim-sham.js @ b49a89a….js?meteor_js_resource=true:279
   a @ b49a89a….js?meteor_js_resource=true:5
   e @ b49a89a….js?meteor_js_resource=true:5
  (anonymous function) @ b49a89a….js?meteor_js_resource=true:279
  (anonymous function) @ b49a89a….js?meteor_js_resource=true:279

```

**Comment by benjamn** [comment]
Can you reproduce this without running in production mode, so that the stack trace isn't minified?

**Comment by paulincai** [comment]
@benjamn

meteor build ~/apk --server=https://..........
Opened project in Android Studio
Ran on emulator. I can confirm production build on physical device failed too (that's why I got to running on emulator)

01/25 09:17:34: Launching project
$ adb install-multiple -r -t /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_7.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_1.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_8.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_0.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/dep/dependencies.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_6.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_5.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_2.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_3.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_4.apk /Users/paulailincai/apk/android/project/build/intermediates/split-apk/debug/slices/slice_9.apk /Users/paulailincai/apk/android/project/build/outputs/apk/debug/project-debug.apk 
Split APKs installed
$ adb shell am start -n "com.beamps.activitree/com.beamps.activitree.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 4543 on device Pixel_XL_API_25 [emulator-5554]
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/EGL_emulation: eglMakeCurrent: 0xb68855a0: ver 2 0 (tinfo 0xb6883800)
D/EGL_emulation: eglMakeCurrent: 0xb68855a0: ver 2 0 (tinfo 0xb6883800)
D/CordovaWebViewImpl: onPageDidNavigate(http://localhost:12552/)
I/MeteorWebApp: Serving asset bundle with version: 1bcdf96ad52494f36ea9a7e86d8539fe6e6af320
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 4543
D/SystemWebChromeClient: http://localhost:12552/: Line 6 : The key "viewport-fit" is not recognized and ignored.
I/chromium: [INFO:CONSOLE(6)] "The key "viewport-fit" is not recognized and ignored.", source: http://localhost:12552/ (6)
D/JsMessageQueue: Set native->JS mode to EvalBridgeMode
I/LaunchNavigator: pluginInitialize()
W/art: Attempt to remove non-JNI local reference, dumping thread
D/SystemWebChromeClient: http://localhost:12552/626eefafebae3433a45ee523fe2176b59dcee12f.js?meteor_js_resource=true: Line 11 : 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
I/chromium: [INFO:CONSOLE(11)] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.", source: http://localhost:12552/626eefafebae3433a45ee523fe2176b59dcee12f.js?meteor_js_resource=true (11)
D/SystemWebChromeClient: http://localhost:12552/626eefafebae3433a45ee523fe2176b59dcee12f.js?meteor_js_resource=true: Line 11 : 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
I/chromium: [INFO:CONSOLE(11)] "'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.", source: http://localhost:12552/626eefafebae3433a45ee523fe2176b59dcee12f.js?meteor_js_resource=true (11)
D/SystemWebChromeClient: http://localhost:12552/626eefafebae3433a45ee523fe2176b59dcee12f.js?meteor_js_resource=true: Line 91 : Uncaught TypeError: o is not a constructor
I/chromium: [INFO:CONSOLE(91)] "Uncaught TypeError: o is not a constructor", source: http://localhost:12552/626eefafebae3433a45ee523fe2176b59dcee12f.js?meteor_js_resource=true (91)
D/SystemWebChromeClient: http://localhost:12552/: Line 26 : The key "viewport-fit" is not recognized and ignored.
I/chromium: [INFO:CONSOLE(26)] "The key "viewport-fit" is not recognized and ignored.", source: http://localhost:12552/ (26)
D/CordovaWebViewImpl: onPageFinished(http://localhost:12552/)
W/art: Attempt to remove non-JNI local reference, dumping thread
W/art: Attempt to remove non-JNI local reference, dumping thread
W/art: Attempt to remove non-JNI local reference, dumping thread
W/art: Attempt to remove non-JNI local reference, dumping thread
W/art: Attempt to remove non-JNI local reference, dumping thread
W/art: Attempt to remove non-JNI local reference, dumping thread
W/art: Attempt to remove non-JNI local reference, dumping thread

**Comment by benjamn** [comment]
This should be fixed with `es5-shim@4.7.2`.

**Comment by flean** [comment]
I'm getting a different error now

```
makeMissingError | @ | modules-runtime.js?hash=9f9bb5e…:241
-- | -- | --
require | @ | modules-runtime.js?hash=9f9bb5e…:251
cordova.js | @ | es5-shim.js?hash=a670231…:72
fileEvaluate | @ | modules-runtime.js?hash=9f9bb5e…:353
require | @ | modules-runtime.js?hash=9f9bb5e…:248
(anonymous function) | @ | es5-shim.js?hash=a670231…:139
(anonymous function) | @ | es5-shim.js?hash=a670231…:144

```

**Comment by paulincai** [comment]
meteor build ~/apk --server=https://..........
Opened project in Android Studio
Ran on emulator with es5-shim@4.7.2 . App stack on splash screen.

D/SystemWebChromeClient: http://localhost:12552/1147e5fcd8c79edf8f724054f156cb4d55237a95.js?meteor_js_resource=true: Line 9 : Uncaught Error: Cannot find module 'es5-shim/es5-shim.js'
[INFO:CONSOLE(9)] "Uncaught Error: Cannot find module 'es5-shim/es5-shim.js'", source: http://localhost:12552/1147e5fcd8c79edf8f724054f156cb4d55237a95.js?meteor_js_resource=true (9)

**Comment by benjamn** [comment]
@paulincai Argh, that's my fault. Fixing momentarily.

**Comment by benjamn** [comment]
Try `meteor update es5-shim` again to get version 4.7.3?

**Comment by paulincai** [comment]
@benjamn Looks ok

**Comment by flean** [comment]
Agreed, works. Thanks
