### ISSUE TITLE
[1.6.1] Collection subclass bug with custom .babelrc

### ISSUE THREAD

**Issue by maartenbusstra** [meteor/meteor#9595]
I'm on macOS.

I'm getting `First argument to new Mongo.Collection must be a string or null` with the following code:

```js
import { Mongo } from "meteor/mongo";

class Collection extends Mongo.Collection {
  constructor({ name, options } = {}) {
    super(name, options);
  }
}

class FooCollection extends Collection {}

const foo = new FooCollection({ name: "foo" });

foo.remove({});
foo.insert({ bar: "baz" });
```

And `.babelrc`:

```json
{
  "presets": ["@babel/preset-env", "@babel/preset-stage-2"],
  "plugins": ["@babel/plugin-proposal-decorators"]
}
```

example app: https://github.com/maartenbusstra/collection-subclass

**Comment by benjamn** [comment]
Two suggestions here:
* Your reproduction doesn't need either of the `presets` in your `.babelrc` file, and at least part of the problem here is that `@babel/preset-env` includes a faulty (too strict) version of the `@babel/plugin-transform-classes` plugin. I don't know what Babel plugins your application needs, but both `@babel/preset-env` and `@babel/preset-stage-2` are somewhat redundant with what Meteor already provides via `babel-preset-meteor`, so I would strongly recommend adding individual plugins that you really need, rather than adding whole presets.
* If you run `meteor update mongo` to get version 1.4.3, this problem should be fixed regardless of what you put in your your `.babelrc` file, thanks to this commit: 17eaa5bd6f9f4837c6c22001c30bfd65e5d28496

Please feel free to close this issue if the problem is resolved for you, and of course please let us know if you're still having problems!

**Comment by maartenbusstra** [comment]
Thanks Ben, you da man. 🙌

**Comment by maartenbusstra** [comment]
Hmm, now I'm getting this in my main app:

> We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

But that's unrelated. I'll investigate later on.

**Comment by abernix** [comment]
@maartenbusstra https://github.com/meteor/meteor/issues/9571 was exhibiting the same error, so you may want to check there, specifically in @benjamn's https://github.com/meteor/meteor/issues/9571#issuecomment-360223847.
