### ISSUE TITLE
[1.6.1] 'meteor add-platform' returns Cordova error.

### ISSUE THREAD

**Issue by davinderkumar** [meteor/meteor#9602]
I'm getting following error on command

**meteor add-platform ios**

> => Errors executing Cordova commands:         
>                                               
>    While adding platform iOS to Cordova project:
>    TypeError: Path must be a string. Received undefined
>    at assertPath (path.js:28:11)
>    at Object.resolve (path.js:1181:7)
>    at Function.getPlatformDetailsFromDir (/Users/davinder/node_modules/cordova-lib/src/cordova/platform/getPlatformDetailsFromDir.js:30:23)
>    at /Users/davinder/node_modules/cordova-lib/src/cordova/platform/addHelper.js:314:35
>    at _fulfilled (/Users/davinder/node_modules/q/q.js:787:54)
>    at self.promiseDispatch.done (/Users/davinder/node_modules/q/q.js:816:30)
>    at Promise.promise.promiseDispatch (/Users/davinder/node_modules/q/q.js:749:13)
>    at /Users/davinder/node_modules/q/q.js:557:44
>    at flush (/Users/davinder/node_modules/q/q.js:108:17)
>    at _combinedTickCallback (internal/process/next_tick.js:131:7)
>    at process._tickCallback (internal/process/next_tick.js:180:9)
>    => awaited here:
>    at Function.Promise.await
>    (/Users/davinder/.meteor/packages/meteor-tool/.1.6.1.8o8ahq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
>    at Promise.asyncApply (/tools/cordova/project.js:390:7)
>    at /Users/davinder/.meteor/packages/meteor-tool/.1.6.1.8o8ahq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
>    => awaited here:
>    at Function.Promise.await
>    (/Users/davinder/.meteor/packages/meteor-tool/.1.6.1.8o8ahq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
>    at CordovaProject.runCommands (/tools/cordova/project.js:731:14)
>    at CordovaProject.addPlatform (/tools/cordova/project.js:386:10)
>    at CordovaProject.ensurePlatformsAreSynchronized (/tools/cordova/project.js:417:12)
>    at main.captureAndExit (/tools/cli/commands-cordova.js:54:20)
>    at /tools/utils/buildmessage.js:271:13
>    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
>    at /tools/utils/buildmessage.js:264:29
>    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
>    at /tools/utils/buildmessage.js:262:18
>    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
>    at /tools/utils/buildmessage.js:253:23
>    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
>    at Object.capture (/tools/utils/buildmessage.js:252:19)
>    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
>    at doAddPlatform (/tools/cli/commands-cordova.js:36:8)
>    at Command.func (/tools/cli/commands-cordova.js:125:3)
>    at /tools/cli/main.js:1523:15
>

**Comment by abernix** [comment]
What version of the Android SDK do you have installed?

**Comment by davinderkumar** [comment]
25.0.3
It works fine with Meteor 1.6.0.1

**Comment by abernix** [comment]
It seems as if you have `cordova-lib@8` installed in your own `node_modules` directory, outside of the Meteor installation (as indicated by the `/Users/davinder/node_modules/cordova-lib` path in your stacktrace).  Meteor isn't ready for `cordova-lib@8` yet (though that is something we're working on), but the tool is finding a copy of it in your global `node_modules` directory and trying to use it.

Can you move your `/Users/davinder/node_modules` out of the way (e.g. renaming it `node_modules.old`) and then try running `meteor remove-platform ios` followed by `meteor add-platform ios`?

**Comment by abernix** [comment]
For the record, you're getting that failure because `cordova-lib@8` has [this critical conditional](https://github.com/apache/cordova-lib/blob/fc69a0bda186123bb18154707f292e119efb2acd/src/cordova/platform/addHelper.js#L294-L306) (that is to say, without it set you'll always end up with an undefined `libDir` on [this line](https://github.com/apache/cordova-lib/blob/fc69a0bda186123bb18154707f292e119efb2acd/src/cordova/platform/addHelper.js#L314)), which can't be entered without having `opts.fetch` set truth-y.  That would necessitate having `fetch` set to `true` [hereabouts](https://github.com/meteor/meteor/blob/99ddadca228d9d78a960330611f9a112f51e7ac9/tools/cordova/project.js#L688-L690) in Meteor's `CordovaProject` class, but that's not an exposed option to developers (nor should it be).

Anyhow, there are a number of other problems with `cordova-lib@8` which I've been investigating which will likely be good reason to stay at `7.x` for the time-being.  To do that, you'll want to get that `cordova-lib` module out of your `$HOME/node_modules` directory, at which point Meteor will install it's own 7.1.0 version, [as defined](https://github.com/meteor/meteor/blob/99ddadca228d9d78a960330611f9a112f51e7ac9/tools/cordova/index.js#L11).

**Comment by davinderkumar** [comment]
It is working fine after removing /Users/davinder/node_modules. My bad!
Thanks for help.
