### ISSUE TITLE
Meteor.bindEnvironment seems to remove an argument

### ISSUE THREAD

**Issue by jpsear** [meteor/meteor#9624]
Hi,

I am trying to wrap a function from the [Agenda](https://github.com/agenda/agenda) queue library with `Meteor.bindEnvironment()`, so my async code runs within a fibre. However, one of the standard arguments to this function becomes undefined when I use it (but the Meteor code runs as expected).

Here is a code snippet to illustrate:

```js
agenda.define('queueHandleWebhook', Meteor.bindEnvironment((job, done) => {
  // job === an object :)
  // done === undefined :(

  handleWebhook(token, provider, data)
    .then(result => {
      console.info(`Webhook with token: ${token} from provider: ${provider}, successfully run from queue!`, result)
      done()
    })
    .catch(error => {
      console.warn(`Webhook with token: ${token} from provider: ${provider}, failed from queue`, error)
    })
}))
```

However, if I remove the `Meteor.bindEnvironment()` call, the arguments remain defined...

```js
agenda.define('queueHandleWebhook', (job, done) => {
  // job === an object :)
  // done === a function :)

  handleWebhook(token, provider, data) //...
})
```

I am using Meteor version 1.6.0.1, on a Mac, Sierra: 10.12.6, Node: 8.7.0

**Comment by klaussner** [comment]
Agenda uses the [`length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) property of the `define` callback function to determine [if it should pass the `done` argument](https://github.com/agenda/agenda/blob/2d78b12599de5483f10cd7407d7144c171614750/lib/job/run.js#L55-L61). However, `Meteor.bindEnvironment` returns [a function without parameters](https://github.com/meteor/meteor/blob/0a1e1f042a925659e351412006f4c1f1af43fc92/packages/meteor/dynamics_nodejs.js#L100) (i.e., with `length` zero) and uses the `arguments` object to forward all arguments to the wrapped function.

I'm not sure if this can be fixed in Meteor but you can get around the problem by passing a regular function to `define` and calling the wrapped function from there:

```js
const callback = Meteor.bindEnvironment((job, done) => {
  // ...
  done();
});

agenda.define('queueHandleWebhook', (job, done) => {
  callback(job, done);
});
```

**Comment by hwillson** [comment]
Since this isn't a common occurrence, Meteor core will likely not be updated to handle this edge case (unless of course this issue becomes more prevalent). Please use @klaussner's great workaround as needed. Thanks!

**Comment by jpsear** [comment]
@klaussner Thanks for the great explanation and awesome work-around. @hwillson Makes complete sense — thanks!
