### ISSUE TITLE
Meteor dynamic imports not resolving correctly, v1.6.1

### ISSUE THREAD

**Issue by Elviron** [meteor/meteor#9631]
Meteor 1.6.1, OS X 64

I cannot seem to get the dynamic imports working with the new Meteor version. I had a related issue in another project, so i created this new meteor project to find the issue.
But in this brand new meteor project the dynamic imports will not work as usual.

Getting this error:
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:4000/app/Test

You should be able to recreate it just by downloading this project.

Maybe I'm missing something obvious, but I cannot figure it out.. Please help

Here is the repo with the brand new meteor project:
https://github.com/Elviron/meteor-dynamic-import-error/tree/master

**Comment by benjamn** [comment]
You should remove the `meteor` preset from your `.babelrc` file, since Meteor already provides the `babel-preset-meteor` preset automatically, regardless of what else you put in `.babelrc`. Running the entire preset twice seems to be preventing dynamic `import(...)` expressions from being compiled, somehow.

Note that you may need to run `meteor reset` after that to force dynamic `import(...)` expressions, and it may also be worth mentioning that [this line](https://github.com/Elviron/meteor-dynamic-import-error/blob/331aa87c2dd8863944b5dbb7abf83cfb12bd86f5/imports/ui/App.js#L14) should look like this instead:
```js
import('./Test').then(({ default: TestAsync }) => {
  this.setState({ TestAsync });
});
```

**Comment by benjamn** [comment]
This should be fixed by the [commit](https://github.com/meteor/meteor/commit/bd5cf99edb6f9a3987129f0c5624908b033d8202) mentioned above, if you run `meteor update babel-compiler ecmascript` to get versions 7.0.1 and 0.10.1, respectively.

**Comment by Elviron** [comment]
Yes, that fixed the problem! :)
The problem i had with the other project was the same, with the only addition that i also had to remove the ```@babel/preset-stage-1``` i had in ```.babelrc```.
So now my ```.babelrc``` is empty.
