### ISSUE TITLE
Losing much rebuild performance

### ISSUE THREAD

**Issue by Gywem** [meteor/meteor#9642]
**version:** 1.6
**OS:** OS X El Capitan 

Hello everyone! I am working with a team in a complex meteor project. We have been experiencing high rebuild times from the beginning of the project, some of them were alleviated by newer meteor versions or applying [some tips reported here](https://medium.com/@lucashansen/faster-meteor-reloads-62cca5b56460). Some months ago one of our app got the minimum consistent time we've got lately, which is 8-10 seconds per code change. But, recently after code addition we've experienced it rising up to 20-24 seconds. We think that it may be caused by something introduced by us, but can also be related on bad practices we follow that are not reported in consideration on how the meteor builder works and/or a possible bug on meteor itself. Anyway, we'd want to understand the causes behind.

We've prepared a report explaining how our meteor app infrastructure is shaped. There we provide the project sizes and some profiles measuring our timings on code change. I hope this can serve for someone to foresee what could be doing wrong in our project. Besides, we've also reported some of our practices that may affect the meteor builder to get down performance. We just want to check with you if these are good patterns or if can significatively affect to our timings.

You can check out the report [here](https://gist.github.com/Gywem/f8fd9a4b3207359eb7970c2cad1d689e).

## Debug the meteor builder
We've done a lot of debugging to track this issue down and we are aware about the facilities you provide for debugging the meteor build process and some tips to understand possible causes as is stated on the [docs](https://github.com/meteor/meteor/blob/devel/tools/PERFORMANCE.md).

We've been researching a way to get further info on the build system. According to the docs for analyzing the Meteor’s build tool performance, [there is an advanced manner to instrument the code for the profiler](https://github.com/meteor/meteor/blob/devel/tools/PERFORMANCE.md#instrumenting-code-for-the-profiler) and get further sense of what could be the culprit in a build/reload process.

We really don’t understand how we can proceed with this strategy to get further build information, and we cannot find any example around the matter. We only found in [this post](https://medium.com/@lucashansen/faster-meteor-reloads-62cca5b56460) a reference of using v8-profiler package, but still we're not able to figure out how this can be used to analyze the meteor build tool.

Can you provide any usage example of v8-profiler for meteor? Having a way to debug it would be definitely better.

**Comment by abernix** [comment]
Thanks for filing this detailed report!  Thanks to @benjamn's recent https://github.com/meteor/meteor/commit/c6d481d53bb9e1d4a451536b1626cbb36a29baa4 and https://github.com/meteor/meteor/commit/82e61fe085fc78c47100332eab9af69c8dd5fd1b commits on the `release-1.6.2` branch (being tracked in #9559), there should now be some additional profiling information available (in the upcoming Meteor 1.6.2) which should help with further quantifying what occurred in those steps.  You can try these now by updating to the latest 1.6.2 beta:

    meteor update --release 1.6.2-beta.5

And then running your commands again with the `METEOR_PROFILE` environment variable set.   It'll be interesting to see if that reveals anything!

As a more advanced step, and since you requested:  If you're using Meteor 1.6, thanks to Node 8, you'll be able to benefit from connecting your Chrome (or other browser) DevTools to the Node.js Inspector API.  I believe the functionality of the [`v8-profiler` npm](https://npm.im/v8-profiler) has been integrated into the Node.js Inspector API.  This should enable to you to generate flame-graphs that demonstrate where slowness is occurring, but I believe you'll find it's best to [run Meteor from a checkout](https://github.com/meteor/meteor/blob/devel/DEVELOPMENT.md#running-from-a-git-checkout) in order to do so.

Once you've got the local checkout of `meteor` setup, it should be as easy as:

```sh
TOOL_NODE_FLAGS=--inspect-brk /path/to/meteor/checkout/directory/meteor ... # command as usual
```

This should, upon running, indicate that the inspector is waiting for you.  For example:

```zsh
some-meteor-app $ TOOL_NODE_FLAGS--inspect-brk ~/Dev/jesse/meteor/meteor run --settings ./settings.json
Debugger listening on ws://127.0.0.1:9229/3ef16ca1-89a9-5916-1314-ae14a935311e
For help see https://nodejs.org/en/docs/inspector
```

Then, in Chrome, go to `chrome://inspect` (as the URL) and you should see a "Remote Target" with an "inspect" link, ala:

<img src="https://user-images.githubusercontent.com/841294/35859869-770f990a-0b4a-11e8-8ada-06b4f64d5d10.png" height=200 />

Clicking on `inspect` should take you to a (familiar, if you're used to using the Dev Tools normally in Chrome) panel which will allow you to "Profile" the `meteor` command.

Though again, you may gain some additional visibility in Meteor 1.6.2 if you wanted to try that `1.6.2-beta.5` beta first. :smile:

**Comment by benjamn** [comment]
I endorse everything @abernix said above, and I would just add the following: if you don't want to try updating your app to 1.6.2 first, you can checkout a specific Meteor version when running from a checkout, and the cherry-pick my `METEOR_PROFILE` commits:
```sh
cd path/to/meteor
git checkout -t origin/release-<your current version>
git cherry-pick c6d481d53bb9e1d4a451536b1626cbb36a29baa4
git cherry-pick 82e61fe085fc78c47100332eab9af69c8dd5fd1b
cd path/to/app
METEOR_PROFILE=20 meteor
```

**Comment by filipenevola** [comment]
Hello, @benjamn and @abernix I'm trying to do what you have asked (use 1.6.2) but I'm getting errors to build the app and I can't build the app, it looks like an infinite loop.

I noticed that if I remove stage-1 preset I don't get this infinite loop but I can't remove that because we are using plugin-syntax-export-namespace-from and that feature is in stage-1.

Our app is on 1.6 version of Meteor then I'm trying to migrate first to 1.6.1 (but I have the same problem with 1.6.2-beta-* too)

See the logs:
https://gist.github.com/filipenevola/48b41e40b2410f58bf01c669b6377e3b

Do you think that's a problem with Meteor babel-compiler or only with Babel? Thanks.

ps: I'm joining Pathable in March ;) but I'm already trying to help with that in my free time for now.

**Comment by abernix** [comment]
@filipenevola Hello! It sounds like it'd be best to open a new issue with an exact reproduction for the problem you're experiencing here, since it sounds like a _separate_ issue.

To build the reproduction, please start a new Meteor project on the latest 1.6.2 beta (so, currently `meteor create --release 1.6.2-beta.7 demo-app`), copy your custom Babel configuration into the new project, ensure the reproduction demonstrates the problem, upload the reproduction repository to GitHub, and share a link to that repository in the new issue.

Also, it's probably worth suggesting not using the entire `stage-1` preset if you only need `@babel/plugin-syntax-export-namespace-from`, since "Stage 1", in general, could include a lot of very experimental features (as suggested by the name).  Just making this change alone could resolve this problem, but please do open a new issue.

**Comment by filipenevola** [comment]
@abernix Hi, I have tried to remove stage-1 preset (because I agree with you, is too much risk) and only use the plugin but I got this error:
`This experimental syntax requires enabling the parser plugin: 'exportNamespaceFrom'`

Looks like Meteor is ignoring it (it's weird because I already used plugins with Meteor in the past).

package.json
`
    "@babel/plugin-syntax-export-namespace-from": "^7.0.0-beta.40",...`

.babelrc
`{
  "plugins": [
    "@babel/plugin-syntax-export-namespace-from", ...`

And I really want to try with Meteor 1.6.2-beta-* because @benjamn asked it, but if you want to take a look at this: https://github.com/filipenevola/build-performance-9642 . It's a reproduction for our build time issue. What do you think? I believe we can do better in Meteor build too ;)

**Comment by filipenevola** [comment]
Hello, @benjamn @abernix any feedback about my reproduction? It still very slow with 1.6.2-beta.

**Comment by filipenevola** [comment]
Hello @benjamn @abernix , we have provided more situations in our reproduction repo.

We know that Meteor takes double of time to build the same amount of files if they are in a package and we change something in the package code. Meteor does something twice for package code?

| n  | App files | Package #A files | Package #B files | Change on | PreProjBuild | RebuildApp | ServerStartup | Total |
|----|-----------|------------------|------------------|-----------|--------------|------------|---------------|-------|
| 3  |    1000   |       5000       |         1        |    app    |     1,074    |    2,405   |      613      |  4092 |
| 4  |    1000   |       5000       |         1        |    p#A    |     5,454    |    2,740   |      614      |  8808 |

See more here https://github.com/filipenevola/build-performance-9642/tree/master/private/with-meteor-packages

We would really appreciate feedbacks about our reproduction, there are very serious problems.

And we are only not trying these stuff with Meteor 1.6.2-beta.* (as you have asked) because we have a blocker there ( #9711 ).

**Comment by benjamn** [comment]
@filipenevola If the logs in https://github.com/filipenevola/build-performance-9642/tree/master/private are up-to-date, it seems clear that initial build times are dominated by Babel compilation, and we're able to eliminate that cost (mostly) for rebuilds, thanks to caching in the build process. Is there some part of the profiling output that jumps out at you because it seems to be taking way too long, other than initial Babel compilation? Is the initial build time a problem for your development productivity, given that rebuilds are much faster?

**Comment by filipenevola** [comment]
Hello @benjamn, our main focus is to have better rebuild time, initial build time is not good too but that's not our biggest problem.

I don't know if I understood what you have said, do you think that 8,721 ms of rebuild time is fast enough for 5,000 almost empty dummy files? I think it's pretty slow.

Another thing you have said: "we're able to eliminate that cost (mostly) for rebuilds", do you mean you can do something on Meteor tool to improve this? Or are you saying that is already good in the way it's right now?

In Pathable's code, we have it around 20 sec (more sometimes) for every rebuild, which is huge.

And see this comparison:
Using meteor packages (our case in Pathable)
https://github.com/filipenevola/build-performance-9642/tree/master/private/with-meteor-packages

Using npm packages
https://github.com/filipenevola/build-performance-9642/tree/master/private/with-npm-packages

See that npm packages are a lot faster, looks like we have problems with Meteor packages build.

**Comment by benjamn** [comment]
Faster is always better, but we should be focusing on the problems that you are actually experiencing, and asking why those problems have gotten worse. The only way this situation is going to improve is if you work with us to find specific solutions, by identifying specific performance bugs and/or optimization opportunities, rather than simply showing that an app with lots of files (empty or not) takes a long time to build. If it takes five times as long to (re)compile five times as many files, that's not surprising. If a specific part of the profiling output stands out in every rebuild, that's much more interesting. Specifically, if we can identify unnecessary work that can be avoided, or work that isn't being effectively cached across rebuilds, or make small improvements to operations that happen very frequently (such as Babel compilation), we might be able to achieve some significant reductions in build times, just like we did in the Meteor 1.4.2 days, when rebuild times were much worse than they are today. Turning this into an adversarial discussion, where you claim some amount of time is "pretty slow" or "huge," hoping that I can guess how to solve the problem for you, will not get us anywhere.

**Comment by filipenevola** [comment]
I’m sorry you’re interpreting my reply as adversarial, that’s definitely not how it was intended. I certainly wasn’t asking you to do any work for us. Indeed, the work we’ve done in our `build-performance` repository referenced above has been considerable and all with the goal to help identify specifically what’s going on.

I apologize if perhaps my English is poor. My only goal with my latest reply was to understand if you believe there are opportunities to improve the rebuild performance or if the current state of things is expected and acceptable.

**Comment by flippyhead** [comment]
Hi @benjamn! I think what we’re trying to understand here is if the current (re)build performance is expected and that perhaps we’ve just reached the limits for our special use case. The latest work from @filipenevola and @Gywem has produced what we thought were interesting results in that a similar distribution of files build far faster via NPM than via the Meteor package system. We were thinking this might indicate a path to discover how to significantly improve the build times of medium to large size Meteor projects. I think @filipenevola really did just want to know if you feel this is worth pursuing further or if our setup is somehow unique and we should pursue a different approach, perhaps imply working to convert our packages to NPM modules.

**Comment by benjamn** [comment]
Ah, my apologies! I'm very sorry for misreading the tone of your comment, and for taking it more personally than you intended.

When I think about the rebuild performance problems  Meteor had before 1.4.2, I honestly wish developers had been more skeptical of rebuild times in the minutes(!!), rather than assuming everything was working as intended (that is, very poorly). So I do appreciate your asking whether rebuild times of 10-20 seconds are normal, because I am much happier to work with anyone who is optimistic that we can improve performance, rather than blindly pessimistic about the limitations of Meteor.

When we were working on Meteor 1.4.2, I instinctively knew that minutes of rebuild time were unacceptable (ridiculous, really) so I was confident there must be some way we could *fix* those problems (not just improve them slightly). To be honest, I do not instictively know whether we can dramatically improve your rebuild times without some clever reengineering of how Meteor works. It doesn't feel (to me) like an easy fix is hiding somewhere. It doesn't sound like your app is doing anything unusual that obviously needs to be fixed, though I would love to be wrong about that!

To put it another way, I believe that any improvements we could make to speed up your rebuild times would benefit anyone with a large Meteor application. If you were doing something unusual, of course we could help you identify the problem and hopefully fix it, but the benefit would be limited to your app, or other very similar applications.

As for the difference in build times of Meteor packages versus npm packages, I'm afraid that's an apples-and-oranges comparison. Meteor packages have a lot more going on: they have to be built for multiple architectures (e.g. client and server), they can run code on application startup (rather than waiting for you to import them), and they are compiled when you build your application, instead of getting pre-compiled by the package author at publishing time. These are important design decisions that we are not likely to abandon, since they make Meteor packages much more powerful than npm packages, and allow us to continually improve the way compiler plugins like `ecmascript` and `babel-compiler` work, without worrying about code that was compiled long ago, whenever some Meteor package was last published.

If you don't need these powerful features of Meteor packages in every case, then you can certainly try moving some of your logic into npm packages (or just into subdirectories of your application), though it may take a while for the benefits of that transition to pay off (it's not as easy as flipping a switch, or running `meteor update` to get better performance immediately).

To give you something more concrete to consider, I have a hunch that your application may be relying more heavily than other apps on imports across packages, which have to be handled specially in `computeJsOutputFilesMap` [here](https://github.com/meteor/meteor/blob/46257bad264bf089e35e0fe35494b51fe5849c7b/tools/isobuild/compiler-plugin.js#L1153-L1158). Specifically, I seem to remember talking to you about importing modules like `meteor/package-name/some/module`, as opposed to just `meteor/package-name`? Since most imports are within packages (or within the application), performance problems with these cross-package imports might have gone unnoticed by the majority of Meteor developers. If you notice `computeJsOutputFilesMap` in `METEOR_PROFILE` output for *rebuilds*, then perhaps we should take a closer look at what's happening there.

**Comment by RobertLowe** [comment]
Just to weigh in on performance, I got to improve one apps performance then another and applied the same kinds of changes, I managed about 35% gains in build speed, reload speed, pageload speed and file size.

Some numbers:

Project before optimizations:

    | (#1) Total: 31,625 ms (ProjectContext resolveConstraints)
    | (#2) Total: 17,471 ms (ProjectContext prepareProjectForBuild)
    | (#3) Total: 40,436 ms (Build App)
    | (#1) Total: 14,754 ms (Server startup)

Boot: 104286ms

    | (#4) Total: 9,811 ms (ProjectContext prepareProjectForBuild)
    | (#5) Total: 12,163 ms (Rebuild App)
    | (#1) Total: 9,946 ms (Server startup)

Server restart: 31920ms

---

Project with optimizations:

    | (#1) Total: 1,279 ms (ProjectContext resolveConstraints)
    | (#2) Total: 43,807 ms (ProjectContext prepareProjectForBuild)
    | (#3) Total: 16,020 ms (Build App)
    | (#1) Total: 5,430 ms (Server startup)

Boot: 66536ms (36.1% faster)

    | (#4) Total: 8,744 ms (ProjectContext prepareProjectForBuild)
    | (#5) Total: 6,861 ms (Rebuild App)
    | (#1) Total: 6,237 ms (Server startup)

Server restart: 21842ms (31.5% faster)


Quite nice, considering this is a fairly sizeable application. 

So what did I do?

I removed `meteor-node-stubs`, it adds *a lot* of weight when you aren't looking especially as it loads an NPMs modules dependancy tree. What else? Ensure you're not double loading packages and NPM dependancies (jQuery, underscore, etc), `meteor list --tree` can help with this, but dig around.In one project I brutally hacked jQuery out as a dep from packages and load it from CDN now. Review your `package-lock.json` look for packages and big trees, remove leaf dependencies where possible. Removing deps helps speed meteor up as it has to `files.stat` less for big trees. In one app I managed to remove 156 dependencies, from around 500ish.  Anymore? Yea, sure, review your `client` and `server` so they don't leak to each other, this will easily fatten up `meteor-node-stubs`. Some more? Okay one last one, if you're using `useraccounts/core` be wise of `softwarerero/accounts-t9n` as it loads translations for ton of languages, many of which you probably don't need, it has a `T9N_LANGUAGES` environment flag you may want to investigate. And always run with `METEOR_PROFILE`, sometimes you'll notice slow library with large deps, I noticed one loading `mocha` needlessly.

Happy hacking 👍
