### ISSUE TITLE
[1.6.1] Unable to fetch dynamic import

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#9653]
When updating from 1.6.0.1 to 1.6.1:
I have an `index.js` file that import a `main.js` file in the import folder.
```
FlowRouter.wait();
import('/imports/client/main.js');
FlowRouter.initialize();
```
The fetch request is pending and unable to get any data:
`http://localhost:3000/__meteor__/dynamic-import/fetch`

**Comment by WayneUong** [comment]
So I determined the problem is this package: https://github.com/meteorhacks/picker

**Comment by sakulstra** [comment]
@WayneUong we actually got a similar error. The error occurred because of https://github.com/meteor/meteor/pull/9384 and our setup manipulating the post response via picker.
We got rid of it by just removing the package.

**Comment by hwillson** [comment]
`meteorhacks:picker` is unfortunately no longer maintained, and has fallen behind in terms of working properly with modern day Meteor. You can try forking + updating the package to get it working, or look into using an alternative. Actually, the package is quite small and its functionality is easily replicated by building your own custom [connect](https://github.com/senchalabs/connect) middleware. This is quite easy to do with Meteor, and you can use [picker's source](https://github.com/meteorhacks/picker/blob/807619954428960e638c6d8195a17c4a7fbf9220/lib/instance.js) for guidance. Closing as this isn't a Meteor core issue. Thanks!

**Comment by etyp** [comment]
@hwillson thanks for spotting this issue :)

I'm working to replace Picker in our app and am curious exactly what about how Picker is set up causes it to be incompatible. Is there anything specific to the [Picker code](https://github.com/meteorhacks/picker/blob/master/lib/implementation.js) that causes this issue?

**Comment by hwillson** [comment]
@etyp Picker registers itself in the middleware chain using `WebApp.rawConnectHandlers`:

https://github.com/meteorhacks/picker/blob/807619954428960e638c6d8195a17c4a7fbf9220/lib/instance.js#L2-L4

This intercepts Meteor's incoming `dynamic-import` requests before the registered dynamic import middleware is called (which is installed after `WebApp.rawConnectHandlers` using `WebAppInternals.meteorInternalHandlers`):

https://github.com/meteor/meteor/blob/db1c03e3eb59805fad03c76e3bed1b841fa04836/packages/webapp/webapp_server.js#L693-L695

So Picker is preventing the incoming dynamic import request from being passed down the chain, likely because it's attempting to resolve and handle the endpoint itself. You could look into adding an exception in Picker that ignores `/__meteor__/dynamic-import` based URLs, or find some other workaround to ignore dynamic import requests.

**Comment by hexsprite** [comment]
what is a recommended server-side router for Meteor these days then if you don't want to use a bunch of legacy crap?

**Comment by WayneUong** [comment]
@hexsprite we just rebuilt picker ourselves. Look at its source code, it's not that complex.

**Comment by benjamn** [comment]
@WayneUong Care to publish your version? 😉

**Comment by WayneUong** [comment]
I don't think a package this really needed since it's only a few lines

```
import bodyParser from 'body-parser';
import multiparty from 'multiparty';

let jsonParser = bodyParser.json(),
    urlencodedParser = bodyParser.urlencoded({extended: false});

function serverRoute(url, middleware, callback) {
    middleware && WebApp.rawConnectHandlers.use(url, middleware);
    callback && WebApp.rawConnectHandlers.use(url, callback);
}

serverRoute('/server/events', jsonParser, function (req, res) {
    req.body.forEach(function (event) {
        console.log(event);
    });
    
    res.end('success');
});
```

**Comment by hexsprite** [comment]
thanks, I'll keep it in mind when replacing legacy code. I think it would still be worthwhile to have a lightweight meteor router. Maybe if I still feel that way later I'll release what I come up with ;)
