### ISSUE TITLE
browser-policy package missing CSP2 and CSP3 directives

### ISSUE THREAD

**Issue by danrubins** [meteor/meteor#9689]
The Content Security Policy builder from the `browser-policy` package is excellent for building basic CSPs, but is currently missing quite a few of the newer and more arcane directives for advanced CSP configurations as well as the ability to create a `Content-Security-Policy-Report-Only` header, useful for working with new configurations.

From what I see, the following are missing (text from MDN web docs on CSP):

### Directives
- **`manifest-src`** Specifies valid sources of application manifest files.
- **`worker-src`** Specifies valid sources for Worker, SharedWorker, or ServiceWorker scripts.

### Document directives
- **`base-uri`** Restricts the URLs which can be used in a document's <base> element.
- **`plugin-types`** Restricts the set of plugins that can be embedded into a document by limiting the types of resources which can be loaded.
- **`sandbox`** Enables a sandbox for the requested resource similar to the <iframe> sandbox attribute.
- **`disown-opener`** Ensures a resource will disown its opener when navigated to.

### Navigation directives
- **`form-action`** Restricts the URLs which can be used as the target of a form submissions from a given context.
- **`navigation-to`** Restricts the URLs to which a document can navigate by any means (a, form, window.location, window.open, etc.)

### Reporting directives
- **`report-uri` / `report-to`** The ``report-uri`` directive instructs the user agent to report attempts to violate the Content Security Policy. These violation reports consist of JSON documents sent via an HTTP POST request to the specified URI. Note: `report-uri` was added in CSP2 but removed from CSP3 in favor of `report-to` which raises a `SecurityPolicyViolationEvent`, as in #9688, I think we should have support for both to allow someone building their CSP maximum flexibility

### Other directives
- **`block-all-mixed-content`** Prevents loading any assets using HTTP when the page is loaded using HTTPS.
- **`require-sri-for`** Requires the use of SRI for scripts or styles on the page.
- **`upgrade-insecure-requests`** Instructs user agents to treat all of a site's insecure URLs (those served over HTTP) as though they have been replaced with secure URLs (those served over HTTPS). This directive is intended for web sites with large numbers of insecure legacy URLs that need to be rewritten.

I'm planning to submit a PR for the missing CSP2 and CSP3 directives soon since they easily fit within the established pattern. 

Guidance on the preferred way to implement the `Content-Security-Policy-Report-Only` header is welcome. Perhaps we could just clone `BrowserPolicy.content`, call it `BrowserPolicy.contentReportOnly` and append the header name with `-Report-Only` inside `contentReportOnly`?

**Comment by dhrubins** [comment]
LOL, I just saw that I already mentioned this here meteor/meteor-feature-requests#170.

**Comment by dhrubins** [comment]
@hwillson I like that approach a lot better, especially since CSP recommendations seem to be changing so rapidly. I'm happy to look into it.

**Comment by dhrubins** [comment]
Ok, nice. Helmet seems to have everything I wanted in this issue, plus #9688, meteor/meteor-feature-requests#271, etc.

Just so we don't accidentally remove an important security feature that people could be using, how about we add some text to the Meteor guide with sample code for something like helmet and a deprecation warning to `browser-policy`.

**Comment by hwillson** [comment]
Awesome - adding an example to the Guide would be a welcome first step! When it comes to deprecating packages, we usually follow one of two approaches:

1. Move the package to the `deprecated` folder and mention it's deprecated in the `History.md` (e.g. [`deprecated/spiderable`](https://github.com/meteor/meteor/tree/devel/packages/deprecated/spiderable)).

or

2. Move the package to the `deprecated` folder, mention it's deprecated in the `History.md`, but also update the package so all of its source is removed, leaving a single `deprecation_notice.js` file. That file is then usually wired up so that if someone attempted to use the most recent version of the package, they'll see the notice. [`deprecated/stylus`](https://github.com/meteor/meteor/tree/devel/packages/deprecated/stylus) does this for example, but this isn't always needed, since future versions of deprecated packages aren't necessarily published (so the last published version continues to work if anyone wants to use it).

The `browser-policy-*` packages aren't used by any other core packages, which is great. That means we should be able to deprecate them pretty easily. `dynamic-import` checks to see if `browser-policy-content` exists, to work around `eval` blocking, but that code can stay as is (since it's an optional check). The BP packages have been used extensively in the past however, and many people are still using them, so I think we should take the light-footed approach to deprecating them, option 1 above. So after we've verified `helmet` can successfully replace the `browser-policy-*` packages (which a Guide article will do), I think we should just:

- Move all `browser-policy-*` packages to `deprecated`
- Update the `History.md`
- Leave the code as is (for now anyways)
- Skip adding a deprecation warning. Warnings are great, but they can quickly get annoying. I have a feeling there are a lot of devs out there that will want to keep using the BP packages as is (since they're only using them in a very limited state). When people reach out for new BP features or to report BP bugs, we can let them know it's deprecated, and point them to the Guide's `helmet` section.

Thanks!

**Comment by toinevk** [comment]
I have created a tiny repo [@todo](https://github.com/toinevk/todo) confirms that Helmet will do the trick (for CSP at least). There is a base config required (lifted straight out of the current browser policy package) to ensure it works. @hwillson In terms of where this should be documented - would it be under production -> security?

**Comment by hwillson** [comment]
Awesome @toinevk! Yes, I think so; maybe "Production > Security > Content Security Policy (CSP)". We already have a ["Content Security Policy (CSP)" section under mobile](https://guide.meteor.com/mobile.html#csp), but I think that's okay since it's talking about CSP from Cordova's point of view (but once the new "Production > Security > Content Security Policy (CSP)" section is done, we should add a link to it from the mobile CSP section, and replace the `browser-policy` recommendation with `helmet`). Thanks for looking into this!

**Comment by toinevk** [comment]
Thanks. I have created a pull request for the guide update https://github.com/meteor/guide/pull/750.  Upon closer inspection it turns out Browser Policy package sets the X-Frame header as well. I have slightly deviated and added a HTTP Header section with CSP & X-Frame as sub sections.

**Comment by mitar** [comment]
So one thing `browser-policy` does is that if you call `BrowserPolicy.content.disallowInlineScripts()` it also moves inline Meteor config section to an additional `<script>`. Does moving to `helmet` addresses this?

**Comment by nathan-muir** [comment]
@mitar the api is in the `webapp` package.

```
WebAppInternals.setInlineScriptsAllowed(false)
```

**Comment by mitar** [comment]
Then that should be added/explained in the documentation. I do not see it mentioned in https://github.com/meteor/guide/pull/750.

**Comment by mitar** [comment]
> The browser-policy-* packages aren't used by any other core packages, which is great.

This does not seem to be true (at least anymore). See #10704 where currently `dynamic-import` package configured browser policy to enable inline eval.

**Comment by mitar** [comment]
Still relevant.

**Comment by filipenevola** [comment]
thanks @mitar, I already labeled as `confirmed` then stale bot will ignore it.

**Comment by mitar** [comment]
Still relevant. Shouldn't stale bot be ignoring this issue?

**Comment by StorytellerCZ** [comment]
Closing this in favor of this discussion: https://github.com/meteor/meteor/discussions/11591
