### ISSUE TITLE
Warning when installing npm packages inside the bundle

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#9696]
When running `npm install` inside `/bundle/programs/server` in extracted bundle, I get the following warning:

```
npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /bundle/programs/server
npm WARN meteor-dev-bundle@0.0.0 No description npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
```

This happens with Meteor 1.6.0.1 inside Docker build.

I worry especially about the first warning.

**Comment by klaussner** [comment]
Are you trying to run `npm install` with root privileges?

**Comment by klaussner** [comment]
npm scripts [won't run with root privileges](https://docs.npmjs.com/misc/scripts#user) unless you set the `unsafe-perm` flag: `npm install --unsafe-perm`. Maybe that's why npm cannot run in "wd" (which, I assume, is the working directory).

Depending on your Docker (parent) image, you could also change the user with `USER <name>` for all commands that write to the working directory.

**Comment by mitar** [comment]
I thought `--unsafe-perm` was removed/made unnecessary. Let me test this.

**Comment by mitar** [comment]
That helped. Thanks.
