### ISSUE TITLE
Return to development mode

### ISSUE THREAD

**Issue by gabimoncha** [meteor/meteor#9699]
I use Meteor 1.6 with React.
I somehow entered production build even though I don't remember using `meteor build`
Is there any way to return to development mode?

**Comment by paulincai** [comment]
Hi there, by any change you run Cordova? 
I take it you are trying to run Meteor in dev on a local station. It happens to me that when I run Cordova, Meteor goes in production. To enforce dev: `NODE_ENV=development meteor run ios`

**Comment by hwillson** [comment]
@gabimoncha It's difficult to tell from your comment what your issue is. Since it doesn't sound like you're reporting a Meteor bug, but are instead running into issues using Meteor, I'd suggest reaching out for help via the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) (tag `meteor`). Issues here are reserved for bugs with the Meteor platform itself. Closing for now (but I'll happily re-open this issue if you can clearly demonstrate that you've encountered a Meteor bug). Thanks!
