### ISSUE TITLE
Errors prevented startup:  While loading plugin `basicFileTypes` from package `meteor`:

### ISSUE THREAD

**Issue by VioletaCalvo** [meteor/meteor#9700]
When I launch the app with `meteor run android-device` or simply `meteor run` I get this error in the console

```
(19:21:32)[meteortest]$ meteor run android-device
[[[[[ ~/meteor-projects/meteortest ]]]]]      

=> Started proxy.                             
=> Errors prevented startup:                  

   While loading plugin `basicFileTypes` from package `meteor`:
   packages/basicFileTypes_plugin.js:39:9: Package._define is not a function
   at packages/basicFileTypes_plugin.js:39:9
   at packages/basicFileTypes_plugin.js:41:3


=> Your application has errors. Waiting for file change.
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
```

Just after a simple change in the code the app continues launching. For example: add a console.log in the client or clear a line, just to force Meteor to detect that code has been modified. If I stop the app with Ctrl+C and relaunch again, same error occurs.

My configuration:
- Project with Meteor 1.4.4.5 with Meteor 1.6.1 installation
- Android Studio 2.3.3 (also tested with Android Studio 3.0.1)
- Android SDK Tools 25.2.5
- Running this in Mac OS X High Sierra

This issue also occurs with the example project created with meteor:
```
meteor create testapp --release 1.4.4.5
```

[Here](https://github.com/VioletaCalvo/meteorissue) a reproduction of this issue

I think this is a very strange error. By removing some meteor packages (inserted by meteor by default) same problem occurs.

Thank you in advance!

**Comment by hwillson** [comment]
This is (unfortunately) a known issue. In a nutshell, when you create a new 1.4.4.5 based app using `meteor create someapp --release 1.4.4.5`, if you look in that new apps `.meteor/versions` file, you'll see a dependency of `meteor@1.8.3` listed. `meteor@1.8.3` is actually the most recent (published) version of the `meteor` package, and includes calls to code that didn't exist when Meteor 1.4.4.5 was released. Long story short, your Meteor 1.4.4.5 based app should have had its `meteor` version pinned to `1.6.1`, but doesn't.

As a workaround (and according to my dependency resolution machine named @abernix 🙂), the following should work:

```
meteor add ecmascript@=0.7.3 ejson@=1.0.13 logging@=1.1.17 meteor@=1.6.1 shell-server@=0.2.3 standard-minifier-js@=2.0.0 mobile-experience@=1.0.4
```

That being said, I would highly recommend moving away from any Meteor version that relies on Node 4.x, since it's coming out of LTS this April (meaning it will no longer receive critical bug and security fixes, which ultimately means older Meteor versions won't either). Upgrading to Meteor 1.6.1 should go well, but if you run into any issues, definitely let us know!

I'm going to close this issue since the aren't any plans to go back and fix this for older 1.4.x (and up to 1.5.1) releases. If this becomes more of a reported issue, we might consider releasing a patch, but ideally people should consider moving away from older Meteor versions. 

Thanks for reporting this!

**Comment by jamiter** [comment]
@hwillson, thanks for digging into this. We're using meteor version `1.6.0.1` and are having the same issue.

Should everyone using a version before `1.6.1` start pinning the meteor package version now? And also all other packages you mentioned?

It's unrealistic to expect everyone to upgrade overnight, especially with some breaking changes in `1.6.1`.

**Comment by jamiter** [comment]
I would like to add that this breaks our CI builds and is giving us issues with local development. Fingers crossed when we try to deploy 🤞

**Comment by hwillson** [comment]
Thanks for the additional details @jamiter - this should have been resolved as of Meteor 1.5.2 due to https://github.com/meteor/meteor/commit/cfdc69bf717d3689e15bc7488a0a6dae30437cec. Re-opening to investigate further.

**Comment by hwillson** [comment]
@jamiter While this is being looked into, since you're using 1.6.0.1, you can pin your `meteor` package version to 1.8.0:

```
meteor add meteor@=1.8.0
```

This will fix the error for now.

**Comment by hwillson** [comment]
@jamiter This should now be fixed by updating to the latest version (1.8.4) of the `meteor` package:

```
meteor update meteor
```

Let us know if you're still running into any issues. Thanks!

**Comment by mitar** [comment]
This might be related to #9695.

**Comment by VioletaCalvo** [comment]
`meteor update meteor`  Has updated meteor from 1.8.3 to 1.8.4, and this worked for me, thank you!
