### ISSUE TITLE
[1.6.1] Kadira endevent forced complete

### ISSUE THREAD

**Issue by lynchem** [meteor/meteor#9730]
We recently updated our packages (not the meteor version) and this warning started appearing a lot. We tracked down the package that causes it to the meteor package. On 1.8.2 this doesn't happen, but with >= 1.8.3 it does. 

I'm not even sure this warning is of any real consequence or if it's just a nuisance in the log but thought I'd put it here just in case. 

There's a very old bug open about it [here](https://github.com/meteorhacks/kadira/issues/174) which doesn't shine much light on it. We do use PublishCounts but I can confirm that removing it doesn't get rid of the warnings. We also suspected PublishComposite but removed that also and can still get the warning to fire by just requesting a reset password. 

There's also a PR open [here](https://github.com/meteor/meteor-apm-agent/pull/5) to remove the logging of this warning. Maybe we can get this merged if everyone agrees that it's harmless?

**Comment by hwillson** [comment]
@lynchem Issues here are reserved for bugs with the Meteor platform itself. Kadira is not managed under this repo, and is not something we can support here. If you're interested in having changes made to MDG's Meteor APM (formerly Kadira), then please open a support ticket with Galaxy directly. If you're instead interested in having changes made to the open source version of Kadira, then hopefully someone can help you elsewhere. Thanks!

**Comment by lynchem** [comment]
Thanks @hwillson  but I believe the problem is related to an update to a meteor core package. Issues are not open on Meteor APM. So the logical place for me was to put it here. 

What I had hoped for was someone with more knowledge about the inner workings of the update from 1.8.2 -> 1.8.3 to maybe give their opinion. I doubt that Galaxy support will be able to shed any light on this without bothering the meteor devs (such as yourself). 

It might not even be a problem if we all agree the error is benign.

**Comment by tcastelli** [comment]
I was checking the commits between 1.8.2 and 1.8.3 and the only potential problems could be in #9274 and #9654 which are quite short changes. 
Hopefully those two links will bring more light to someone at mdg to figure out why the meteor apm package is giving those errors from 1.8.3.

**Comment by hwillson** [comment]
Thanks for the extra details. This request really should go through Galaxy support though as MDG team members are the only people that have access to the internal Meteor APM infrastructure, and can effectively troubleshoot, run tests, make changes, etc. We can speculate what might be happening here, but without this being officially raised and handled through Galaxy support, this issue won't be properly resolved. If you haven't done so already, please do open a Galaxy support request about this. In the meantime, until this is resolved, you could consider pinning your `meteor` package to 1.8.2 (so `meteor add meteor@=1.8.2`).

**Comment by lynchem** [comment]
Yeah, we've done both.

**Comment by glasser** [comment]
Hi, just to be clear — literally the only change necessary to make this occur is changing meteor from 1.8.2 to 1.8.3 without any other package version changes?

**Comment by lynchem** [comment]
Yes @glasser , that's all it takes in our case at least.

**Comment by glasser** [comment]
So my suspicion is that dropping the warning isn't the right answer: dropping the entire call to endLastEvent might be the answer. If I understand correctly this code is trying to "clean up" missing "end" calls by adding its own artificially, and before meteor@1.8.2 it basically was always a no-op.

It looks like meteor@1.8.3 is adding async (fiber.yield) events to various places in the system. But we have no reason to believe that this actually leads to the "end" events not being there — there's just a surprising extra async event. My suspicion is that with meteor@1.8.3, the force-added end events are just wrong.  So the agent can probably just remove this ancient "force a fix and warn" code.

That said, I'm not an expert in this codebase (and due to its history as an acquisition, the overall depth of expertise in the client-side Kadira codebase at MDG is not as deep as one might hope).

**Comment by glasser** [comment]
Can you share some specific examples of what the log message looks like when it happens, including the full JSON thing that gets sent? (If it has private info, email glasser@meteor.com.)

**Comment by glasser** [comment]
Actually this is super trivial to reproduce. I see why folks are complaining.

**Comment by glasser** [comment]
I think we should probably revert the Meteor change (or expose it as a different withValueAndAwait that awaits). Changing something that doesn't yield to something that does yield is a big change.

What's going on here is that the Meteor change inverts the order of the hacky wrapper around the `method` DDP message handler finishing and the `result` message being sent so that the message can get sent before the `method` handler finishes, even though it happens asynchronously via a promise.  Maybe Kadira shouldn't be relying on this ordering (I mean, certainly), but breaking Kadira is not great.

I think we could just stop the logging but it really exposing a semantic change here.

**Comment by lynchem** [comment]
Thanks for getting that sorted @glasser

**Comment by glasser** [comment]
Thanks @benjamn ! Updating to `meteor@1.8.5` should resolve this issue, and presumably Meteor Release 1.6.2 will have `meteor@1.8.5` so we'll never have a Meteor release whose default `meteor` package has the issue.

**Comment by yasaricli** [comment]
@glasser thanks. I have updated meteor@1.8.6,  no problem.

**Comment by darrentu** [comment]
@glasser Sorry for the silly question. Isn't meteor still currently at version 1.6.1? How do I get Meteor@1.8.5?

**Comment by klaussner** [comment]
@darrentu `meteor` is also the name of a package. You can find the currently used version in the `.meteor/versions` file of your app. To update the package, run `meteor update meteor`.
