### ISSUE TITLE
Importing "simple-peer" breaks app

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#9734]
I'm using METEOR@1.6.0.1 and trying to import a class which uses the WebRTC library "simple-peer". For example, this is how my class looks like

```
import Peer from 'simple-peer';

class Test {
...
}

export {Test};
```

If I do now import the class in more than 2 files, my app crashes on client side without detailed errors (only Buffer is not defined and some iron-router errors). After some testing, I find out that the following dependency within simple-peer is causing the issue:

```
var stream = require('readable-stream')
```

If I fork the package and replace the dependency with

```
var stream = require('readable-stream-meteor')
```
everything is working fine again. Any idea why the "official" package causes the issue? Is there a "workaround" without forking the package?

**Comment by benjamn** [comment]
Yes! I can tell you exactly why the official `readable-stream` package hast this problem. It's because this issue has never been addressed: https://github.com/isaacs/core-util-is/pull/12

That's what motivated us to fork the package, as you can see from the additional commits in our fork repository: https://github.com/meteor/readable-stream/commits/master

**Comment by dnish** [comment]
Ah great, thanks :) - so I'll close the issue.

**Comment by benjamn** [comment]
Instead of installing and requiring `readable-stream` or `readable-stream-meteor`, you (or the `simple-peer` library authors) may be able to rely on the version that comes with `meteor-node-stubs`, by calling `require("_stream_readable")`.

Alternatively, you can make it work right now by making sure `Buffer` is defined globally in your application:
```js
// Put this in code that runs before simple-peer is imported:
global.Buffer = require("buffer");
```
However, the `Buffer` polyfill is kinda large, so that's the tradeoff.
