### ISSUE TITLE
Image not rendered after several app changing

### ISSUE THREAD

**Issue by chasset** [meteor/meteor#9736]
Hello,

At first, I want to encourage your efforts in helping us to build fantastic software. Many thanks.

There is a small bug. My app works well on browser. On mobile, the first time I open my app, it works perfectly. BUT, when I lock my phone or when I switch between several apps, and then return to my app, images and icons are not rendered any more.

Images and icons are stored in the public folder of the meteor project. I load css of icons in the head.html of the client and the image in a template.

It happens with:
- server running on ubuntu 16.04 built with meteor 1.6.1
- mobile iPhone iOS 11.2.6

Best regards,

Pierre-Olivier

**Comment by JamesFalero** [comment]
Hi Pierre-Olivier, not a developer but a little clarification will go a long way. 

On mobile, are you using cordova to embed your meteor.js app or another method?

Have you tested your app on android, and if so, did you encounter the same problem?

**Comment by chasset** [comment]
Hi James, I am using cordova and I actually can't test on android.

**Comment by skirunman** [comment]
There is (was?) a known issue with [cordova-plugin-meteor-webapp](https://github.com/meteor/cordova-plugin-meteor-webapp) where assets like photos or icons don't render correctly on iOS after your applicaton goes into the background like when you lock the screen. You can read the gory details in this [PR](https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30).  

Not sure if this was supposed to be fixed in Meteor 1.6.1, but in our case we ended up forking that PR and are using cordova-plugin-meteor-webapp@https://github.com/clozertech/cordova-plugin-meteor-webapp.git#ba9d19cd701bfb12c721839cd08b478cce06201a on Meteor 1.6.1 with iOS 11 and have not seen this problem. 

I don't have time right now to get to the bottom of this, but this info may help you go in the right direction.

**Comment by chasset** [comment]
Many thanks @skirunman. It works since I use this!

**Comment by eskan** [comment]
a fix have been merged recently to update webapp plugin and this should be fixed in next Meteor version https://github.com/meteor/meteor/pull/9761
