### ISSUE TITLE
All DPP messages should use DDPCommon (de)serialization

### ISSUE THREAD

**Issue by radekmie** [meteor/meteor#9752]
I wanted to experiment a bit with few JSON compression methods. Overwriting default implementation of [`DDPCommon.parseDDP`](https://github.com/meteor/meteor/blob/devel/packages/ddp-common/utils.js#L43) and [`DDPCommon.stringifyDDP`](https://github.com/meteor/meteor/blob/devel/packages/ddp-common/utils.js#L79) was an obvious choice, but it turned out, that there is one message, that is not serialized using these: [this old style welcome message](https://github.com/meteor/meteor/blob/5e32a127631f7a6d21e90ffaeec979e92e0c6aac/packages/ddp-server/stream_server.js#L116-L121).

**Comment by hwillson** [comment]
Thanks for pointing this our @radekmie. I can't think of any reason why this shouldn't be using `DDPCommon.stringifyDDP`. Marking as `pull-requests-encouraged` if you're interested. 

I'm going to go ahead and close this though since this isn't a bug, but please feel free to submit a PR to address this, or re-open this over in http://github.com/meteor/meteor-feature-requests. Thanks!
