### ISSUE TITLE
aggregate in Meteor 1.5.4.1 with Mongo 3.6 produces The 'cursor' option is required, except for aggregate with the explain argument

### ISSUE THREAD

**Issue by jdonzet** [meteor/meteor#9753]
I was using aggregate in Meteor 1.5.4.1 with an external mongodb 3.4.x and it worked fine.
After upgrading Mongo to 3.6 version I get this error:
`
The 'cursor' option is required, except for aggregate with the explain argument
`

This is because since Mongo 3.6 it is mandatory to pass the option 'cursor'.
I tried passing the cursor option but meteor restarts in a loop without printing any error.

I'd appreciate any help on how to deal with it.

Kind regards.

**Comment by abernix** [comment]
Thanks for filing these details! We're still working on updating Meteor to support Mongo 3.6, so it's probably best to wait until that's done prior to filing bugs.  Please follow the pull request to know when it's ready!  The work is being tracked in https://github.com/meteor/meteor/pull/9632.  I think it's almost ready, so hopefully that'll be done soon.

I'll close this since the feature request to support Mongo 3.6 is already open (https://github.com/meteor/meteor-feature-requests/issues/233) but please do help test Meteor with Mongo 3.6 once that PR lands and it becomes available in a Meteor 1.6.2 beta!

**Comment by raza2022** [comment]
@jdonzet have you found anything am stuck at same position. my production app breaks due to mongo db version auto upgrade :(

**Comment by raza2022** [comment]
I did a very hack workaround and at least it's fixed my production aggregation. I just posting here for reference (not recommended :no_entry_sign:) Please note for some reason am using the meteor version `1.4.4`
1. I just override the in npmmongo package within `versions` file with `npm-mongo@2.2.34`
2. just added `cursor` in my aggregate so the simple aggregation within method looks like
```
var rawUsers = Meteor.users.rawCollection();
var aggregateQuery = Meteor.wrapAsync(rawUsers.aggregate, rawUsers);
var pipeline = [
    {$match: {}},
    {$project: {username: 1, profile: 1}}
];
var result = aggregateQuery(pipeline, { cursor: {} });

return result;
```
