### ISSUE TITLE
server-render sink object is missing host information on applications with subdomains

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#9765]
Hello, our app has something like *myevent*.env.mainsite.com or even *app.myevent*.env.mainsite.com and we want to add the event information as meta tags on the initial server-side rendered HTML.

We added server-render package and got the sink object but a few of the values are null, see below:
```json
{"request":{"browser":{"name":"other","major":0,"minor":0,"patch":0},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/","path":"/","href":"/"}},"arch":"web.browser","head":"","body":"","htmlById":{},"maybeMadeChanges":false}
```
I have used this object without problems in the past but was not in a subdomain request and we need that to return the tags because our strategy to discover what is the event is based on subdomains names. See that the `host, hostname`, etc are `null`.

**My question is: is that a bug or we can't rely on server-render package for applications with subdomains?**

**Comment by benjamn** [comment]
Yep, that's definitely a bug!

**Comment by filipenevola** [comment]
I can work on this PR but I need some initial guidance.

**Comment by benjamn** [comment]
[Here](https://github.com/meteor/meteor/blob/ee32e1328e669fb8ae53c1f0de9e2fa0d9a9cbff/packages/webapp/webapp_server.js#L121-L126)'s where we parse the request in the `webapp` package. I think something must be going wrong in the call to `parseUrl(req.url, true)`, but it might be worth stepping through that code while running `meteor --inspect-brk`. When the application pauses on the initial `debugger` statement, you should be able to find the `webapp/webapp_server.js` module using the file tree on the left side of the debugger, so you can set additional breakpoints before continuing. Let us know if you have any questions!

**Comment by filipenevola** [comment]
I have questions :)

I'm trying to run Meteor from this tag https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.6.1 but I got this error below.

```
➜  pathable-app git:(development) pmeteor run --settings private/env/development/settings.json --port 3001 --inspect-brk
=> Running Meteor from a checkout -- overrides project version (Meteor 1.6.1)
[[[[[ ~/Documents/pathable/ws/pathable-next/pathable-app ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint coffeescript@1.0.17 is not satisfied by coffeescript 2.0.3-3-rc161.3.
   Constraints on package "coffeescript":
   * coffeescript@=2.0.3-3-rc161.3 <- top level
   * coffeescript@1.0.17 <- vsivsi:job-collection 1.4.0 <- pathable-collections 0.0.1

=> Your application has errors. Waiting for file change.
```

Is there any difference in package versions resolution when running from a checkout? My project is working with Meteor 1.6.1 but not from a checkout of this same version.

Or any workaround? I'm not depending on coffeescript, it's a package inside my package that's depending on that.

**Comment by hwillson** [comment]
@filipenevola Instead of trying to run things from the tagged release, maybe just create a new branch off of `devel` to work from. The instructions in the [`DEVELOPMENT.md`](https://github.com/meteor/meteor/blob/ddaa6d1284ea6d5a2513711d49df3d768f77aa4e/DEVELOPMENT.md) doc should help you get a `devel` based git checkout setup.

**Comment by hwillson** [comment]
Hi all - I've looked into this further, and don't think there is a bug here. Taking `webapp` and `server-render` out of the equation for a sec, let's look at a simple request being sent into a vanilla Node [`http.Server`](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_class_http_server) (which is what `webapp` is ultimately using):

**index.js**

```js
const http = require('http');                                                        
const url = require('url');                                                          
                                                                                     
const server = http.createServer((req, res) => {                                     
  res.end();                                                                         
});                                                                                  
                                                                                     
const port = 4000;                                                                   
server.listen(port, (err) => {                                                       
  console.log(`Running on port ${port}`);                                            
});                                                                                  
                                                                                     
server.on('request', (request) => {                                                  
  console.log(url.parse(request.url));                                               
});
```

If you `node index.js` the above, and send a `http://localhost:4000` request in, you'll get back:

```
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: '/' }
```

So the protocol, host, port, etc. are `null`, just like the result you're seeing when dumping the request from the `ServerSink` object. If you put this super simple server behind a test nginx instance, then `proxy_pass` a configured subdomain's requests back to it, I think you'll find that the result of `url.parse` will still be the same, with the same values set to `null`. This is because `request.url` only stores the URL string that is present in the actual HTTP request. So in our case the `http.Server` instance is seeing something like

```
GET / HTTP/1.1\r\n
...
```

then extracting out the URL details (which don't include protocol, host, port, etc.), and storing them. If you were to call `url.parse` like `url.parse('https://somedomain.com:1234/some/path')`, then you would get back 

```
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'somedomain.com:1234',
  port: '1234',
  hostname: 'somedomain.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/some/path',
  path: '/some/path',
  href: 'https://somedomain.com:1234/some/path' }
```

but Node isn't doing this by default, since it's basing the URL off of the incoming HTTP request details. So long story short, the missing `url` values you're seeing lines up with how Node works by default.

All of that being said, if you want to get the protocol, host, port, etc. from the request, there are other ways defined within Node's request API to do so. Not everything the `request` API supports is exposed to the `ServerSink` object, since it's using a [scaled down version of the full `request` object](https://github.com/meteor/meteor/blob/7b06c6043a70699de1d32478474c206f1446c743/packages/webapp/webapp_server.js#L121-L126), but you can likely get most of the missing details from `sink.request.headers`.

Given that everything appears to be working properly here, I'll close this off. If you feel otherwise, definitely let us know. Thanks!

**Comment by filipenevola** [comment]
@hwillson I didn't get it.

The problem can be elsewhere, ok, but how can I get the real request URL? I need to know it to decide what information to return from the server in the initial HTML.

As you can see in the original post I don't have `sink.request.headers` in the sink object.

Maybe I'm not getting something, sorry for that, but what can I do to get the URL info that I need inside `onPageLoad`?

**Comment by hwillson** [comment]
When you run something like

```js
import { Meteor } from 'meteor/meteor';

if (Meteor.isServer) {
  import { onPageLoad } from "meteor/server-render";

  onPageLoad(sink => {
    console.log(sink);
  });
}
```

you should see something like

```
ServerSink {
  request: 
   { browser: { name: 'chrome', major: 65, minor: 0, patch: 3325 },
     url: 
      Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: '',
        query: {},
        pathname: '/',
        path: '/',
        href: '/' },
     headers: 
      { 'x-forwarded-host': 'localhost:3000',
        'x-forwarded-proto': 'http',
        'x-forwarded-port': '3000',
        'x-forwarded-for': '127.0.0.1',
        cookie: 'aelia_cs_selected_currency=GBP',
        'accept-language': 'en-US,en;q=0.9,fr;q=0.8',
        'accept-encoding': 'gzip, deflate, br',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        'upgrade-insecure-requests': '1',
        'cache-control': 'max-age=0',
        connection: 'keep-alive',
        host: 'localhost:3000' },
     cookies: {} },
  arch: 'web.browser',
  head: '',
  body: '',
  htmlById: {},
  maybeMadeChanges: false,
  statusCode: null,
  responseHeaders: {} }
```

Is that working on your side?

**Comment by filipenevola** [comment]
Yes, now I can see it! Thanks!
