### ISSUE TITLE
remove meteor-node-stubs - what if?

### ISSUE THREAD

**Issue by avalanche1** [meteor/meteor#9769]
This is not a bug report, but I think this is the only place and possibly @benjamn is the only person that can know about this - 
https://forums.meteor.com/t/how-i-made-our-app-35-faster-in-build-rebuild-browser-load-time-size here OP advises to remove `meteor-node-stubs` to increase build perfomance and reduce bundle size.
What are the possible implications after doing this?

**Comment by abernix** [comment]
Since this is still not the place for questions, I've gone ahead and answered the question on the forum post.

Though just to reference some places where it has been discussed, https://github.com/meteor/meteor/issues/8645#issuecomment-305322822 and https://github.com/meteor/meteor/issues/6056 come to mind.

**Comment by avalanche1** [comment]
> Though just to reference some places where it has been discussed, #8645 (comment) and #6056 come to mind.

You got really broad memory, Jesse :)
