### ISSUE TITLE
Still getting segmentation fault with Meteor 1.6.1.1 and NodeJS 8.11.1 in Galaxy Production Env

### ISSUE THREAD

**Issue by oohaysmlm** [meteor/meteor#9797]
- [ 1.6.1.1] The version of Meteor showing the problem.
- [Galaxy Production Env] The operating system you're running Meteor on.
- [segmentation faults with no additional info ] The actual behavior.

We recently made the jump from 1.4.X up to 1.6.1 and had been following issue #9745 closely and hoping it would be resolved with 1.6.1.1.  We have no instances of the segmentation fault occurring on our development machines, which could be because there is zero load on localhost as compared to the live app, or could be because of how the Meteor Galaxy environment is configured (possibly).

**Comment by benjamn** [comment]
The official Node 8.11.1 still suffers from the segmentation fault problem, because [8.11.0](https://nodejs.org/en/blog/release/v8.11.0/) was a security release that did not include the necessary patch, and [8.11.1](https://nodejs.org/en/blog/release/v8.11.1/) was a release without any additional commits.

To fix the problem in development, Meteor 1.6.1.1 comes with a custom build of Node 8.11.1 with one additional commit: https://github.com/meteor/node/commits/v8.11.1-meteor

However, Galaxy mistakenly does not use this custom build of Node 8.11.1, but instead uses the official build. I believe that's why you're seeing the segmentation faults in production but not in development.

**Comment by oohaysmlm** [comment]
@benjamn thanks for the quick response, that was my suspicion.  We are attempting a roll back to 16.0.1 in the meantime to see if that fixes the issue.  Meteor Galaxy is also aware of the issue.

**Comment by oohaysmlm** [comment]
It's already in progress in the issue @benjamn linked to above https://github.com/meteor/galaxy-images/pull/2

**Comment by benjamn** [comment]
This should now be fixed if you redeploy a Meteor 1.6.1.1 app to Galaxy!
