### ISSUE TITLE
Polling used instead of Oplog in specific scenarios

### ISSUE THREAD

**Issue by dovydaskukalis** [meteor/meteor#9803]
It seems that it fallbacks to polling if we specify limit param but don't have sort param set.

The following works fine:

```
Meteor.publish('usingOplog', function() {
  return Test.find({}, { limit: 1, sort: { createdAt: -1 }});
});
```

However this one doesn't use Oplog, instead it uses polling:

```
Meteor.publish('usingPolling', function() {
  return Test.find({}, { limit: 1 });
});
```

Demo repo: https://github.com/dovydaskukalis/meteor-sub-bug

**Comment by klaussner** [comment]
This works as intended. Meteor falls back to polling because the default ("natural") sort order is an implementation detail of MongoDB. Therefore, the oplog driver wouldn't know how to sort documents and apply the `limit`. See [this comment](https://github.com/meteor/meteor/issues/1947#issuecomment-38397951) for more details.
