### ISSUE TITLE
Error on TypeScript compilation "Meteor.Server"

### ISSUE THREAD

**Issue by tibs245** [meteor/meteor#9808]
A problem on typescript compilation :

```
Property 'server' does not exist on type 'typeof Meteor'.
```

When I take this project : https://github.com/Urigo/angular-meteor-base

And I create server unit test :

```
const deleteArticle = Meteor.server.method_handlers["removeArticle"];
```

I have a error on TypeScript compilation because "Meteor.server" not exist on type of "Meteor" (TS2551)

But this work it.

How we can resolve it ?

**Comment by hwillson** [comment]
There are 2 main ways to resolve this:

1. Submit a PR to the https://github.com/DefinitelyTyped/DefinitelyTyped repo to add `Meteor.server` to the [`meteor.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/meteor/meteor.d.ts) type declaration file (which https://github.com/Urigo/angular-meteor-base is using).

OR 

2. Explicitly type `server` as `any`:

```ts
import { Meteor } from 'meteor/meteor';
const { server } = Meteor as any;
console.log(server);
```

For further help with the https://github.com/Urigo/angular-meteor-base project, please open issues in that repo. Thanks!

**Comment by santiagopuentep** [comment]
@hwillson I'm having a similar problem with types for Meteor.user(options), since the DefinitelyTyped version is not updated and doesn't allow for parameters in that function. Should I create a feature request on Meteor for this? Or an issue? I think TypeScript types should be handled officially, since everyone seems to be moving to ts.
