### ISSUE TITLE
Please add license in GitHub settings

### ISSUE THREAD

**Issue by fedir** [meteor/meteor#9816]
Please add license in GitHub settings of the repository.

Currently, GitHub could not identify Your project licence, and it's not shown in interface, and not available via API also.

Ref : https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by hwillson** [comment]
This repo already has a [LICENSE](https://github.com/meteor/meteor/blob/devel/LICENSE). For some reason GitHub isn't automatically recognizing the license, which means the license identifier and link aren't displayed in the GitHub UI. GitHub uses [`Licensee`](https://github.com/benbalter/licensee) to see if a license file exists, which for some reason doesn't like the Meteor `LICENSE`. If anyone is interested in looking into why it isn't recognized, and can submit a PR, that would be great. Closing for now though since this isn't a Meteor core bug (and a `LICENSE` file does exist).
