### ISSUE TITLE
ie10 as modern browser => renders the modern packages BUT should render the legacy packages

### ISSUE THREAD

**Issue by arnoschn** [meteor/meteor#9818]
https://github.com/meteor/meteor/blob/1c1020b6b2bc2d39d4cfee254960b819938bcf8f/packages/socket-stream-client/server.js#L9

The definition of IE10 as modern browser from this package results in blank pages in ie10 and above.

As IE10 does not support ES2015+ this should not be defined as modern browser, I think.

**Comment by benjamn** [comment]
Does IE10 specifically not support `WebSocket` (at least not fully)? There are other places where we call `setMinimumBrowserVersions` that might also be passing `ie: 10` mistakenly. Either way, I'm totally open to moving IE10 to legacy, I just want to find the right place to do it.

**Comment by arnoschn** [comment]
The problem is that this call does not just handle the module specific includes but for the whole client packages. with this setting all the es6 code lands in IE10 for example and it just does not handle es6.

**Comment by benjamn** [comment]
That's correct, but I would still like to set accurate minimum versions for each individual feature, so the system can automatically adjust if (for example) we stopped using the `socket-stream-client` package.

If you can give a quick example of something that fails when you load the page in IE10, I'm happy to help track down the appropriate `setMinimumBrowserVersions` call.

I just noticed that we don't provide a minimum `ie` version in the `ecmascript-runtime-client` package [here](https://github.com/meteor/meteor/blob/release-1.6.2/packages/ecmascript-runtime-client/versions.js), so we could just put `ie: 11` there and call it a day, since `ecmascript-runtime-client` is responsible for all sorts of polyfills that legacy browsers might need.

**Comment by benjamn** [comment]
Is there any version of IE (vs. Edge) that should be considered modern?

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7-beta.25`. Please reopen (or create a new issue) if you discover otherwise!
