### ISSUE TITLE
Loading es5-shim-sham.js from wrong path (subfolder missing from path)

### ISSUE THREAD

**Issue by vlasky** [meteor/meteor#9819]
I am running my Meteor 1.6.1 webapp in a subfolder `/live`. That is, `ROOT_URL=https://vmcentos7:3000/live/`

When I access my Meteor app from Microsoft's Edge browser version 41.16299.334.0, I see the following error message in Edge's console log:

```
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://vmcentos7:3000/packages/es5-shim/es5-shim-sham.js
```

In other words, Meteor's client side code is attempting to load the file `es5-shim-sham.js` from the wrong place because it is not including the `/live` subfolder in the path. It should be looking in:

`http://vmcentos7:3000/live/packages/es5-shim/es5-shim-sham.js`

**Comment by benjamn** [comment]
That sounds like a bug in [this code](https://github.com/meteor/meteor/blob/bd26ce3d1e50f37fa4228923f7c11b164fedc0fb/packages/shim-common/server.js#L35). This will be fixed in the next release of Meteor, since we're moving away from the `shim-common` package in favor of `web.browser[.legacy]`, but we can definitely fix this with a patch release for the `shim-common` package in the meantime.
