### ISSUE TITLE
 [1.7-rc.11] Regression - Typescript source map does not show up

### ISSUE THREAD

**Issue by dagatsoin** [meteor/meteor#9894]
- Last version of Meteor where the problem did _not_ occur: **1.5.x**
- OS: OSX 10.12.6
- Expected behavior : source map leads to TS files.
- Actual behavior: source map does not show up in browser (Chrome 66, Safari 11.1, did not test on others)
- A **simple** reproduction : https://github.com/dagatsoin/meteor-ts (`$sh meteor`)

**Comment by benjamn** [comment]
This appears to be a problem with the `typescript` package that you're using, or perhaps with your `tsconfig.json` file. The TypeScript plugin is putting comments such as
```js
//# sourceMappingURL=Entity.js.map
```
at the bottom of every compiled module, but those `.map` files do not exist. Also, it's a mistake to have multiple `//# sourceMappingURL` comments in a script loaded by the browser, which happens because Meteor concatenates compiled modules together to create a single JS bundle for application code. When this concatenation happens, Meteor automatically generates a combined source map for all the files, so the individual `//# sourceMappingURL` comments are unnecessary.

Somehow the TypeScript compiler needs to be reconfigured to avoid adding those `//# sourceMappingURL` comments to compiled code.

**Comment by dagatsoin** [comment]
I pinged the author of `barbatus:typescript` on this issue, hoping he could do something.

But why the same plugin would works on 1.5 and not on 1.7? The two main difference I see is the switch to babel7 and the update of the ecmascript package. May be there any changes un those package which could produce this regression?

**Comment by dagatsoin** [comment]
Source map are back! Thx you!
