### ISSUE TITLE
[1.7-rc.11] Less imports regression

### ISSUE THREAD

**Issue by aldeed** [meteor/meteor#9899]
Error on startup after upgrading Reaction Commerce app from Meteor 1.6.1 to 1.7-rc.11

You can reproduce this by checking out the branch in this PR, `meteor npm install`, and attempting to start the app or run tests (`npm run test:app`): https://github.com/reactioncommerce/reaction/pull/4265

```
=> Errors prevented startup:

   While processing files with less (for target web.browser):
   imports/plugins/included/default-theme/client/styles/main.less:159: Unknown import:
   {}/node_modules/react-select/less/select.less

   While processing files with less (for target web.browser.legacy):
   imports/plugins/included/default-theme/client/styles/main.less:159: Unknown import:
   {}/node_modules/react-select/less/select.less
```

Note:
- The `react-select` package is present and has this file.
- This worked in 1.6.1
- This is documented as being the correct way to do it here: https://github.com/meteor/meteor/tree/devel/packages/less (although doesn't mention how to do it from node_modules specifically)
- I also tried `node_modules/react-select/less/select.less` and got the same error.

**Comment by benjamn** [comment]
This is a deliberate breaking change in Meteor 1.7, due to c5302bb2ba609e5535dcce8647adf30e0a6f8daf. I discussed the new way to import non-JS files from  from `node_modules` [here](https://github.com/meteor/meteor/pull/9826#issuecomment-386823185), and (more generally) in the second bullet point of [`History.md`](https://github.com/meteor/meteor/blob/1aabda8fcf6dfbd31a1d11e6ff7d8b74e1defcf9/History.md). The short answer is: you should create a symlink within your app that points to the directory (or file) within `node_modules` that you would like to be compiled, and then import from the symlink path (that is, `node_modules` should not appear in the imported file name). Although this is a bit more work, it means Meteor will no longer waste time scanning `node_modules` for modules the application developer did not intend to compile.

**Comment by benjamn** [comment]
It would be nice to provide better error messages for this problem (including a recommendation of what to do instead), but unfortunately these errors are generated by third-party CSS-to-JS packages, so there's not much that Meteor can do to be more helpful.

**Comment by aldeed** [comment]
@benjamn Thanks, I had a feeling it was related to that change. Your commit comment explanation is clearer to me than what History.md says, so maybe pull a little of that into the change log? In particular, I didn't realize that I could symlink a single less file that I wan't to include. The `less` package readme could mention how to do this, too.

I did get this working after:

```
ln -s ../../node_modules/bootstrap/less/ ./imports/module_symlinks/bootstrap-less
ln -s ../../node_modules/react-select/less/ ./imports/module_symlinks/react-select-less
ln -s ../../node_modules/font-awesome/less/ ./imports/module_symlinks/font-awesome-less
```

I'm hoping this works for Windows developers...

**Comment by benjamn** [comment]
For what it's worth, we're doing a Meteor 1.7.0.1 release that reverts the change that caused this regression: https://github.com/meteor/meteor/pull/9917
