### ISSUE TITLE
Bad `else` in login_buttons_dropdown.js

### ISSUE THREAD

**Issue by RacingTadpole** [meteor/meteor#9909]
I was just linting my own fork of `accounts-ui-unstyled` and discovered a misleading indent in the code at this line:
https://github.com/meteor/meteor/blob/devel/packages/accounts-ui-unstyled/login_buttons_dropdown.js#L98

Specifically, the last `else` in this block:

```
    if (username !== null)
      document.getElementById('login-username').value = username;
    else if (email !== null)
      document.getElementById('login-email').value = email;
    else if (usernameOrEmail !== null)
      if (usernameOrEmail.indexOf('@') === -1)
        document.getElementById('login-username').value = usernameOrEmail;
    else
      document.getElementById('login-email').value = usernameOrEmail;
```
is indented as if it should apply to the top `if`, but will actually apply to the last `if`. I suggest adding some braces to make it work.

I don't know if this actually leads to an error in practice.

**Comment by abernix** [comment]
My analysis: The functionality is correct and the indentation is wrong.  Specifically because of the setting to `usernameOrEmail` on the last two (thus splitting the combined `usernameOrEmail` into the separate `username` or `email` inputs, when compared to the explicit setting (on the first two assignments) to `login-username` _or_ `login-email` inputs using the corresponding values `username` and `email` respectively.

A PR to fix this by adding braces would be welcomed!
