### ISSUE TITLE
Sorry but why do I need to use chocolaty to install Meteor? I dont use chocolaty because it's shit!

### ISSUE THREAD

**Issue by CreativeKoen** [meteor/meteor#9913]

**Comment by benjamn** [comment]
You seem to have some preconceived notions about Chocolatey that have nothing to do with Meteor. For what it's worth, once you've installed Meteor once with Chocolatey, you hardly ever have to use Chocolatey again, since you can just run `meteor update` to get future versions of Meteor and its packages. Chocolatey is just a tool that has solved a lot of problems with the initial installation.

**Comment by danielocdh** [comment]
Administrator requirements, changing security settings when installing and no easy way to uninstall chocolatey on windows.
I know op way of asking wasn't great but please considering getting rid of chocolatey, it makes using meteor too much trouble on windows.
