### ISSUE TITLE
[1.7.0.1] upgrade from 1.6.1.1 on Mac causes terminating with uncaught exception of type

### ISSUE THREAD

**Issue by wlodi83** [meteor/meteor#9946]
After Meteor upgrade from version 1.6.1.1 on Mac to 1.7.0.1, my application does not run, and verbose mode prints following error:

libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector

System: macOS High Sierra (10.13.5)

I run following commands:

meteor reset
rm -rf node-modules
meteor npm install
meteor run --verbose --settings settings.json

**Comment by raphaelarias** [comment]
I'm having the same problem.

**Comment by abernix** [comment]
What version of Xcode do you (both) have installed?

**Comment by wlodi83** [comment]
@abernix I have XCode 9.4.1

**Comment by wlodi83** [comment]
I tried it with 1.7, 1.7.0.1 and 1.7.02 versions and unfortunately it's the same error. When I downgrade to 1.6.1.3 it works.

**Comment by wlodi83** [comment]
Hi,

does anyone have similar problem? Any idea how to solve it?

**Comment by raphaelarias** [comment]
For future reference, what I did to "fix" it:

- Remove the whole Meteor folder.
- Clone from your git repo
- Follow the Migration 1.7 guide
- meteor npm install
- meteor npm start

I can't use Meteor 1.7 yet, because apparently meteor vue is incompatible, but I believe it's unrelated issue (https://github.com/meteor-vue/vue-meteor/issues/326)
