### ISSUE TITLE
Rebuild time takes too long with less package

### ISSUE THREAD

**Issue by phibya** [meteor/meteor#9957]
I just created the whole brand new Meteor app then added `less` and `antd` packages,
```
meteor add less
meteor npm i antd
```
Everytime client changes, the rebuild time takes so long with more than 30 seconds.

`Meteor` version `1.7.0.1`
`less` version `2.7.12`
`antd` version `3.6.1`

```
├─ plugin ecmascript.................................57 ms (2)
│  ├─ optimistic statOrNull                           1 ms (460)
│  ├─ Babel.compile                                  10 ms (188)
│  ├─ sha1                                            4 ms (192)
│  └─ other plugin ecmascript                        42 ms
├─ plugin templating-compiler                         2 ms (2)
├─ plugin less...................................33,512 ms (2)
│  ├─ wrapped.fs.readFileSync                        66 ms (134)
│  ├─ wrapped.fs.writeFile                           18 ms (326)
│  ├─ sha1                                           28 ms (326)
│  └─ other plugin less                          33,402 ms
├─ plugin meteor.....................................85 ms (2)
│  ├─ sha1                                           19 ms (342)
│  └─ other plugin meteor                            67 ms
└─ other Target#_runCompilerPlugins                  18 ms
```

I think this is `meteor` problem since I don't have this issue in my another project using `meteor 1.6.1`, `less 2.7.11` and `antd 3.6.1`

**Comment by benjamn** [comment]
What does the following command show?
```sh
find node_modules | grep '\.less$'
```
Between Meteor 1.7 and 1.7.0.1, we reverted an [optimization](https://github.com/meteor/meteor/pull/9825) that would have ignored any `.less` files found in `node_modules`, since some folks rely on being able to import `.less` files from `node_modules`: https://github.com/meteor/meteor/issues/9899

In other words, if you're able to downgrade to Meteor 1.7 (rather than 1.7.0.1), the `less` plugin probably won't have as many files to process, which might help with this problem.

Alternatively, you can tell Meteor to ignore any `.less` files in `node_modules` by putting a pattern like
```
node_modules/**/*.less
```
in a `.meteorignore` file.

**Comment by purplecones** [comment]
I'm in the same situation and after some trial and error, removing the less package reduces the rebuild time **drastically**. From 33 seconds to literally 1-3 seconds. For this particular situation, I'll just `import '../node_modules/antd/dist/antd.css';` for now.

**Comment by benjamn** [comment]
@purplecones Can you try running `find node_modules | grep '\.less$'` as I suggested above, just to help me test that hypothesis?

**Comment by benjamn** [comment]
Great, that confirms my suspicions. I'm surprised that the `less` compiler has trouble with this many files (it's a lot but not a *lot*), but I think there are some things we can do here. Specifically, the `less` compiler plugin could avoid compiling files in `node_modules` unless they are imported. Since `less` is a core Meteor package, this is a change that could be made entirely within this repository.

**Comment by purplecones** [comment]
A small side question, is there a more efficient way to see which pieces the meteor compiler spends the most time on? Like a bundle visualizer for the compiling process itself? This tool would be helpful in troubleshooting and determining why some meteor projects just take so long to rebuild.

**Comment by veered** [comment]
This does exactly that https://github.com/qualialabs/profile

**Comment by hungbya** [comment]
@purplecones You can try with this command `VELOCITY_DEBUG=1 VELOCITY_DEBUG_MIRROR=1 METEOR_PROFILE=1 meteor run`

**Comment by veered** [comment]
@hungbya `METEOR_PROFILE=1` often doesn't give granular enough profiling information

**Comment by benjamn** [comment]
`METEOR_PROFILE` would be a good way to figure out that the `less` compiler plugin is taking too long, as a starting point, but https://github.com/qualialabs/profile is a great way to dig even deeper into exactly where the time is being spent.

**Comment by timbotnik** [comment]
Thanks @benjamn!

**Comment by gotjoshua** [comment]
What is the status on this issue? Is there any work around? think antd and meteor could be great together, but 30+ seconds wait on every file save is just too much...

**Comment by StorytellerCZ** [comment]
Updated less package recently as well. Since @gotjoshua reported this as fixed I'm closing this issue. Comment if that is not the case and I'll re-open.
