### ISSUE TITLE
server-render does not work for android/cordova

### ISSUE THREAD

**Issue by ayalpani** [meteor/meteor#9970]
Hi.

Steps to reproduce:

```
meteor create test-server-render
cd test-server-render/
meteor add server-render
meteor add-platform android
```

Edit server/main.js:

```
import { Meteor } from 'meteor/meteor';
import { onPageLoad } from 'meteor/server-render'

Meteor.startup(() => {
    onPageLoad(sink => {
      sink.appendToBody('<span>Hello World!</span>')
      sink.appendToHead('<meta prop="hello" content="world" />')
    })
});
```
Then:

`meteor run android-device --verbose`

The web version http://localhost:3000/ in my browser shows both changes to `body` and `head`.

Unfortunately, the app on Android phone doesn't. Neither the `head` changes (only the boilerplate code shows up), nor the `body` shows "Hello World!".

--
*Please* help me with this issue. I already spent days solely to solve the issue of changing the boilerplate header code. I also get no responses on the meteor forum. I seem to be the only person in the world, trying to modify the boilerplate code for cordova (to achieve changes to the Content-Security-Policy meta tag).

**Comment by benjamn** [comment]
Cordova works a bit differently from Meteor's standard `webapp` package. Specifically, the static boilerplate HTML is generated once, during build, rather than every time you access the app on the device. See [the `cordova-plugin-meteor-webapp` README](https://github.com/meteor/cordova-plugin-meteor-webapp) for more information. This means server-side rendering does not work the same way for Cordova, which is admittedly unfortunate, but that's the best answer I can give you right now.

The CSP rules for Cordova are hard-coded in [`boilerplate-generator/template-web.cordova.js`](https://github.com/meteor/meteor/blob/devel/packages/boilerplate-generator/template-web.cordova.js), so a possible workaround here would be to copy the `boilerplate-generator` package into your app's local `packages/` directory, and then modify that file as necessary. This will override any other version of the `boilerplate-generator` package that your app might be using.

**Comment by ayalpani** [comment]
Hi Ben, 

thank you for taking the time and for the workaround proposal. I tried copying the package locally as proposed and it did work perfectly.

I love meteor, keep up the good work!
