### ISSUE TITLE
[1.4.4.6] Install script fails to download meteor-bootstrap

### ISSUE THREAD

**Issue by carljdp** [meteor/meteor#9971]
### Expected behavior
Running `curl https://install.meteor.com/?release=1.4.4.6 | sh` should download and install Meteor 1.4.4.6

### Actual behavior
Running `curl https://install.meteor.com/?release=1.4.4.6 | sh` fails to download meteor-bootstrap .tar.gz via the link generated by the install script `https://static-meteor.netdna-ssl.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz`  
_terminal output:_
```log
curl: (22) The requested URL returned error: 403 Forbidden
Retrying download in 5 seconds...
```

### Versions / Environment
- Meteor 1.4.4.6
- os.linux.x86_64

### Reproduction
- try to install via `curl https://install.meteor.com/?release=1.4.4.6 | sh`
- https://static-meteor.netdna-ssl.com/packages-bootstrap/1.4.4.6/meteor-bootstrap-os.linux.x86_64.tar.gz (this will fail with error: Access Denied)

### Last known working version
- Meteor 1.4.4.5
- via `curl https://install.meteor.com/?release=1.4.4.5 | sh`
- https://static-meteor.netdna-ssl.com/packages-bootstrap/1.4.4.5/meteor-bootstrap-os.linux.x86_64.tar.gz (this will succeed)

**Comment by benjamn** [comment]
Workaround: install Meteor 1.4.4.5 and then run `meteor update --release 1.4.4.6`.

We did not publish bootstrap archives for 1.4.4.6, because the only way to install 1.4.4.6 directly is to specify a `?release=1.4.4.6` query parameter (as you're doing here), which is not something we encourage. Node 4 has reached end-of-life, so everyone should be updating to at least Meteor 1.6.x if not Meteor 1.7.

That said, if you have a pressing reason for wanting to install 1.4.4.6 from scratch, and the workaround I mentioned above somehow does not work for you, please explain!

**Comment by carljdp** [comment]
@benjamn, I was trying to update an old project I inherited without causing breaking changes regarding dependencies on some older packages.

I will follow your instructions. Thanx.

**Comment by meggarr** [comment]
This is still an issue, seems all the last version of the major release are not able to download, this include
```
1.4.4.6
1.5.4.2
1.6.2
```
Is this a bug?
