### ISSUE TITLE
after upgrade to 1.7, query no longer works if it has _ character. (i.e. user._id)

### ISSUE THREAD

**Issue by tdotholla** [meteor/meteor#9980]
after upgrading from Meteor 1.6 to 1.7.0.1: 
cursors that use "_id" in the query are not working. 

my query: 
```
let user = {_id: "dflkdjflskf", name: "myName", ... }
Events.find({
  userId: user._id
})
```
after upgrading i had to change to array notation: 
```
Events.find({
  userId: user["_id"]
})
```

i'm assuming because underscore is now in global namespace as per [v1.7, 2018-05-28](https://docs.meteor.com/changelog.html#v1720180528)

i'm on a Mac desktop upon discovering this issue. 

I'm trying to remove underscore and then reinstall via npm to work around this. i'll just import it on the pages i need and use array notation on those pages. ... hopefully that'll work.

**Comment by macrozone** [comment]
@tdotholla that has certainly nothing to do with underscore, but I can't tell without more code.

`user._id` and `user["_id"]` is semantically the exact same thing and both syntax exist since the dawn of js.

It would be better to post that problem on http://forums.meteor.com/ (with some more code and context) as it is probably not an issue with meteor itself.

**Comment by tdotholla** [comment]
Ok thanks. Yes I know both are ways of expressing an object key's value.

This occurred after updating meteor. It looks as though meteor removed underscore as a native dependency, so I had to install and import Explicitly.
