### ISSUE TITLE
[1.7.0.1] Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by carrot93** [meteor/meteor#9987]
Old version: 1.6.1, works good.
Bug: New version 1.7.0_1 can't run on ubuntu 14.10 server.

Meteor Version:
meteor -> packages/meteor-tool/1.7.0_1/mt-os.linux.x86_32/meteor

Ubuntu Versioin:
$uname -a
Linux devTestv4 3.13.0-147-generic #196-Ubuntu SMP Wed May 2 15:51:53 UTC 2018 i686 i686 i686 GNU/Linux

Node Version:
$node --version
v0.10.42

Problem:
$meteor
Segmentation fault (core dumped)

More Error Message:
$dmesg
...
[ 2465.957719] node[1298]: segfault at 7 ip 08bf0f48 sp bfda8d48 error 6 in node[8048000+1a32000]
[ 2484.602458] node[1319]: segfault at 7 ip 08bf0f48 sp bf8c6b48 error 6 in node[8048000+1a32000]
[182204.261920] node[4643]: segfault at 7 ip 08bf0f48 sp bfcf8218 error 6 in node[8048000+1a32000]
[182248.131666] node[4667]: segfault at 7 ip 08bf0f48 sp bfcc2768 error 6 in node[8048000+1a32000]
[182856.154361] node[4724]: segfault at 7 ip 08bf0f48 sp bfee5218 error 6 in node[8048000+1a32000]

So:
I must unlink the meteor command back to 1.6.1, any help?

**Comment by abernix** [comment]
I just tested Meteor 1.7.x on Ubuntu 14.**04.5** (Trusty Tahr) and it worked.

We do not test on Ubuntu 14.**10** (Utopic Unicorn!) which is a non-LTS version of Ubuntu which has been End-of-Life'd since July 2015 and doesn't receive updates from Canonical (its vendor).  I'm surprised you're able to get any updates for that distribution since the "Utopic" `apt` repository is no longer present: http://archive.ubuntu.com/ubuntu/dists/utopic/ (Trusty's on the other hand looks like [this](http://archive.ubuntu.com/ubuntu/dists/trusty/) - in tact).

If you need to remain on Ubuntu 14, that's likely fine, but I suggest switching to a version of the operating system that's still actively maintained/supported!  Unfortunately, there's no way of knowing why this segmentation fault is occurring for you, but it's likely due to updates in Node's underlying V8 engine and its compiler-toolchain requirements (g++, glibc, etc.).

If you can provide a reliable reproduction on an OS that is still within an LTS agreement, I'm happy to look into this further, but we have to focus our attention on OSes that are maintained.

**Comment by j18ter** [comment]
The problem is with 32-bit platforms. See new issue #10080. It crashes every time one runs meteor via the main script on a 32-bit system. It is caused by a recent change in the meteor script, which now requests 4GB of old space, which amounts to all addressable memory on 32-bit platforms. The commit that causes the problem is 5c1ba3a85ec17141f02c61cea03044596c9b4a78, which adds this flag:
``--max-old-space-size=4096``
This either needs to be reduced somewhat, or there needs to be a check for platform and if it is 32-bit a lower number must be used for that case.
