### ISSUE TITLE
Meteor 1.7.0.1 VS semantic-ui ( after update meteor to 1.7.0.1  semantics dont work correctly ) 

### ISSUE THREAD

**Issue by archiagent47** [meteor/meteor#9989]
After update meteor  to 1.7.0.1 
Semantic have some problems 
You can see under what can see in terminal 

Also try remove meteor and setup again and create new empty app with semantics packages 
get same problem 

Please help me to understand what happened 

npm info it worked if it ends with ok
npm info using npm@6.1.0
npm info using node@v10.4.1
npm info attempt registry request try #1 at 21:00:30
npm http request GET https://registry.npmjs.org/npm

MacBook-Pro-Kandratovich:akrobot kandratovichartur$ meteor 
[[[[[ ~/meteor_solution/akrobot ]]]]]         

=> Started proxy.                             
app/client/lib/semantic-ui/semantic.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/client/lib/semantic-ui/semantic.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/

**Comment by pmogollons** [comment]
Hi @archiagent47,

Whats the issue you are having with semantic, can you please describe your issue so that is easier to understand.

If you are only refering to the warning on the terminal, I have used the package with 1.7.0.1 and is working correctly even if it throws that warning. It also happens to me on 1.6.
```bash
app/client/lib/semantic-ui/semantic.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
```

**Comment by pagesrichie** [comment]
The fix for that warning is found here:
https://github.com/juliancwirko/meteor-postcss

Follow the instructions under "Usage", once you get to part 4. Add PostCSS plugins, the "postcss-easy-import": {}, part under the postcss plugins json object is whats needed (along with the devDependency of postcss-easy-import.  Then your warning should go away.

Tagging @jlukic (The maintainer of semantic ui meteor repo) would be a good idea to update the documentation

I did however notice that it takes 8 seconds or more for all the LESS files to compile for semantic ui.. if there is a lead on a fix for it, https://github.com/meteor/meteor/pull/9983 , if there is any other leads for a fix on it please do post as these compile times are too long.

**Comment by lesliedoghouse** [comment]
@pagesrichie thanks for the info. Good to mention once added the two line, one need to run 'meteor npm install' before running the app.

**Comment by jlukic** [comment]
I'm planning on looking into implementing Ben's fix when it merges.

**Comment by tvogt** [comment]
There's also this issue, not sure if it can be fixed on the meteor side:
https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/137

**Comment by vbelolapotkov** [comment]
had some problems after upgrade from meteor 1.6.0.1 to 1.7.1 as well. Steps which helped:

1. Upgrade postcss package as suggested by @pagesrichie 
2. If semantic ui package version before the update was different from 2.3.1 =>  Rebuild semantic files by cleaning up custom.semantic.json. Hint here: make sure you don't have any meaningful changes in git because rebuild will add a lot of changes.
